windows/src/desktop/help/common/linux.xml, windows/src/desktop/help/common/mac.xml
Corresponding fix to 11.0 alpha for #1067 
This fixes the links on the help pages for
* https://help.keyman.com/products/desktop/11.0/docs/common_mac.php
* https://help.keyman.com/products/desktop/11.0/docs/common_linux.php
=> [Windows] Fix docbook links (alpha)

mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m, mac/history.md
setLineBreakMode not supported prior to 10.10.
colorWithRed:green:blue:alpha: not supported prior to 10.9.
=> [Mac] Fixes #1059 - Don't call unavailable selectors on old OS versions

ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/history.md
Setting animated to false "fixes" the display problems and prevents the crash (on iPad 10.5" and 12.9"), but it makes the transition less smooth (obviously) and probably isn't the "right" way to fix the problem. Presumably there is some kind of underlying plumbing issue that is the true source of the problems. This should therefore be regarded as a stop-gap measure and not a permanent fix for #1045 and #1046.
=> [iOS] #1045,#1046 - Quick fix for OSK layout: disable animation

mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m, mac/KeymanEngine4Mac/KeymanEngine4MacTests/KMEngineTests.m, mac/history.md
Previous fix over-corrected by preventing a non-virtual rule from being used for normal shifted characters. For example, if a rule was supposed to fire for a left curly brace, it would not fire if the rule contained '{' instead of [SHIFT K_LBRKT].
=> [Mac] #1090 - Fixed follow-on bug (when Shift is pressed)

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/history.md
This PR fixes 2 null-pointer crashes appearing on Crashlytics.
1. Cleaning up the console log in #837 introduced a bug when the InputConnection in KMManager is `null` and build variant is `release`.
2. PackageActivity is crashing when the package name is null.
=> [Android] Fix crashes when input connection or package name is null

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/history.md
There are some crash reports coming from `KeyboardPickerActivity.java` because the keyboards list is null (file access error). When the app tries to display the installed keyboards list, this results in the crash.
`getKeyboardsList()` already checks the existence of the `keyboards_list.dat` file, so some of that code is also redundant.
With this PR, if `keyboardsList` is null, we'll populate the list with the default keyboard.
atm, I'm deciding not to overwrite the `keyboards_list.dat` file so we don't lose the info of previously installed keyboards.
=> [Android] Ensure keyboards list has an entry

windows/src/developer/TIKE/xml/app/editor/editor.js
Arising from todo list in #1097
Wait on: #1134 (rebase)
The Alt+letter/digit bindings conflict with Windows menu and command shortcuts. Function keys also have predefined meanings in Keyman Developer. Hence remove them all from the editor bindings. If we find that we need a specific binding we can always remap it in the future, however none of the mapped bindings were significant for Keyman Developer use.
=> [Developer] Remove Alt+letter/digit and function key bindings from editor

windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.dfm, windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.pas, windows/src/developer/TIKE/xml/app/editor/editor.js
The focus management in the CEF component is slightly flawed. This patch fixes the ActiveControl state for the component when focus is set to a child window of the web control, which helps track the focus per Delphi's expectations.
=> [Developer] Manage focus correctly for setting breakpoints and more

windows/src/developer/TIKE/main/UframeTextEditor.pas, windows/src/developer/TIKE/xml/app/editor/editor.js
This fixes two issues:
1. Double-clicking an error doesn't select the row with the error, just highlights it
2. Selecting a row from Delphi code causes the selection to extend to the row rather than just moving the cursor to the row
Arises from todo list in #1097
=> [Developer] Tidy up row selection in web editor

windows/src/developer/TIKE/child/UfrmEditor.pas, windows/src/developer/TIKE/child/UfrmKeymanWizard.pas, windows/src/developer/TIKE/main/KeyboardParser.pas, windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.pas, windows/src/developer/TIKE/main/TextFileFormat.pas, windows/src/developer/TIKE/main/UframeTextEditor.pas, windows/src/developer/kmcomp/kmcomp.dpr, windows/src/developer/kmcomp/kmcomp.dproj, windows/src/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dpr, windows/src/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dproj
Arises from todo list in #1097
(Also fixes an access violation in shutdown in rare circumstances when focus changes, in UframeCEFHost: `if Assigned(cefwp) and ...`)
=> [Developer] Support CSS, JS and JSON formats in text editor

windows/src/developer/TIKE/main/UframeTextEditor.pas, windows/src/developer/TIKE/xml/app/editor/editor.js
The JSON parser currently does not return the offset of the error in the file. This is a Delphi limitation.
However, the infrastructure is there if we need it.
Arises from todo in #1097
=> [Developer] Add FindErrorByOffset support for future use by JSON, XML editors

windows/src/developer/TIKE/xml/app/editor/editor.js, windows/src/developer/TIKE/xml/app/editor/language.keyman.js
Currently based on developer-web-editor-monaco. This PR adds basic
syntax highlighting support for .kmn file format, with most common
structures highlighting correctly. It does not attempt to add any
language parsing or other features -- these would be nice-to-have 
but can come later!
=> [Developer] Add basic monarch syntax highlighting for .kmn

windows/src/developer/TIKE/Tike.dpr, windows/src/developer/TIKE/Tike.dproj, windows/src/developer/TIKE/child/UfrmKeymanWizard.pas, windows/src/developer/TIKE/main/KeymanDeveloperUtils.pas, windows/src/developer/TIKE/main/UframeTextEditor.pas, windows/src/developer/TIKE/xml/app/editor/editor.css, windows/src/developer/TIKE/xml/app/editor/editor.js, windows/src/developer/TIKE/xml/app/editor/language.keyman.js, windows/src/global/delphi/general/Keyman.UI.FontUtils.pas
This PR adds support for differing code and char fonts in the Monaco text editor. It also fixes a few minor display issues in the editor (e.g. document scrollbars were wrong).
------
NOTE: Old comments below regarding ACE kept for posterity.
This PR is WIP because of a limitation in ACE -- [turns](https://github.com/ajaxorg/ace/issues?q=is%3Aopen+is%3Aissue+label%3Amonospace) [out](https://github.com/ajaxorg/ace/issues/460) it doesn't support variable width fonts, 
which is a total deal breaker for us with complex script requirements. Most of the code in this PR will still
apply if we replace with another editor, but I will wait on merging until we have come to a conclusion on way forward to
resolve the variable width font issues.
Options for resolution to the problem:
* Finish and apply …
=> [Developer] First pass of managing code and char fonts in web text editor

windows/src/README.md, windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas, windows/src/developer/history.md, windows/src/global/delphi/general/kmxfile.pas, windows/src/global/delphi/general/utilfiletypes.pas
This is an initial cut at refactoring MergeKeyboardInfo to address issue #1110 
Eventually, it will need to be cherry-picked to 10.0
Refactor MergeKeyboardInfo to handle these keyboard scenarios:
1. JS file not in package (web only)
2. KMP package with kmx files (desktop only)
3. KMP package with JS files (mobile only)
4. KMP package with kmx and JS files (desktop, android, ios)
TODO
1. Rename `FKMXFiles` to `FPackageKMXFileInfos`
2. Create private var `FPackageJSFileInfos`
3. Update `TMergeKeyboardInfo.LoadKMPFile` to populate `FPackageJSFileInfos`
4. Rename `FJSFiles` to `FJSFileInfo`, change it from array to scalar, and apply only to js files outside package
5. Update `LoadKMPFile` to use the Keyboards structure in `FKMPInfFile` to determine which files inside the package are keyboards …
=> [Developer] Refactor merge keyboard info

windows/src/desktop/help/common/linux.xml, windows/src/desktop/help/common/mac.xml, windows/src/desktop/history.md, windows/src/developer/history.md
This fixes the links on the help pages for
* https://help.keyman.com/products/desktop/10.0/docs/common_mac.php
* https://help.keyman.com/products/desktop/10.0/docs/common_linux.php
I propose holding off on this merge to coincide with whenever a Windows bugfix gets merged to 10.0 stable.
=> [Windows] Fix docbook links (stable)

ios/keyman/Keyman/Keyman-Info.plist
This should prevent warning from AppStore. We probably don't need to cherry-pick this into stable unless we make some other change there that triggers the warning.
=> [iOS] Added entries to plist to say that Keyman is not document-based

windows/src/Defines.mak, windows/src/desktop/inst/keymandesktop.wxs, windows/src/developer/inst/kmdev.wxs, windows/src/engine/inst/components.wxi, windows/src/engine/inst/keymanengine.wxs
We moved to WiX 3.11 for Keyman 11 as 3.5 is no longer available for download.
As we cannot have two versions of WiX installed on the build agents, it's easier to update the 
.wxs source files to meet the requirements of WiX 3.11 than it is to maintain a separate 
build agent infrastructure. This is not necessarily always the case -- we may in the future
find a situation where we want separate stable and alpha build agents, but not in this case.
=> [Windows] Fixup installer .wxs sources for use with WiX 3.11 (RegistryKey/@Action)

linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/kmpmetadata.py
Fixes #1188 and Fixes #1190 
uses an enum `KMFileType` for keyman file type and only calls determine-filetype in parsing metadata
adds website url to parsed and printed metadata
conditionally print optional metadata if it exists
show exceptions in printing
in parsing kmp.inf split language entry only on first ','
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1202)
=> [Linux] determine-filetype enum and website metadata

linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/kmpmetadata.py
Fixes #1189  
Fixes #1187 
1189: Detects more files as doc files and detect teckit, cc and also xml
.js files with same name as a keyboard id are assumed to be touch keyboard files. keymanrender is recongnised, others are marked KM_UNKNOWN
Remaining windows binary file extensions ignored:
cfx
dll
exe
thmx
1187: moves the generation of keyboard data to parsing instead of in install_kmp
generate keyboard info for all legacy kmx in a kmp
#1177 will also changed shared installs to put all files into /usr/local/share/keyman/<kbid> and then link them to /usr/local/share/doc/... and /usr/local/share/font/... which will bring in the remaining windows only files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> [linux] 1189 other files and 1187 multiple keyboards

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebBrowserActivity.java, android/history.md
This is a follow-on fix of #913
`webView.pauseTimers()` disables Javascript in all WebViews (including Keyman as a system keyboard).
The bug is when the WebBrowserActivity is paused, the globe button in system keyboards is disabled.
Reference: https://developer.android.com/reference/android/webkit/WebView#pauseTimers()
=> [Android] Fix globe button when pausing WebBrowser

linux/keyman-config/km-kvk2ldml, linux/keyman-config/km-package-uninstall
the jenkins keyman-config build currently fails because it can't run km-package-uninstall -h with some dependent packages not installed.
This moves the import to after -h and -v are processed
print is a keyword on python2 so use the short form args.p in km-kvk2ldml (just allows running -h)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1214)
=> [linux] fix help2man on jenkins

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java, android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/history.md, web/history.md, web/source/kmwbase.ts, web/source/kmwcallback.ts
Fixes #289
When changing to a digit/phone number text field, set the OSK to "numeric" layer if it exists. 
This will occur after `resetContext()`.
=> [Android] Change system keyboard to "numeric" layer for numeric text fields

windows/src/developer/history.md, windows/src/global/delphi/packages/Keyman.System.PackageInfoRefreshKeyboards.pas
This was fixed in alpha with the bigger set of changes in the Import and Project Template work
=> [Developer] Avoid a crash in package editor when compiled keyboard file is missing

windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.dfm, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas, windows/src/developer/inst/Makefile, windows/src/developer/inst/copydev.in, windows/src/developer/inst/kmdev.wxs, windows/src/developer/kmconvert/Keyman.Developer.System.ImportWindowsKeyboard.pas, windows/src/developer/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas, windows/src/developer/kmconvert/Keyman.Developer.System.KeymanConvertMain.pas, windows/src/global/delphi/general/BCP47Tag.pas
This PR:
* Fixes a breaking issue with the installer for Keyman Developer [5ed4af8a]
1. Target folder names were incorrect
2. kmconvert template files were missing from build
* Fixes up a bug kmconvert command line tool [b64e1b48]
1. kmconvert crashes because COM was not initialized
* Tidies up various small bugs in the New Basic Project dialog and kmconvert [a70efed0]
1. Don't require language id?
2. &A on two controls
3. Does not enablecontrols on Name field change
4. Browse button does nothing
5. .js file was not added to .kps when building from a template with ktAny as target
6. baz language code was not added to package or .keyboard_info when creating from a template
7. kmconvert should fail if folder already exists
=> [Developer] Fixes for project templates and installer

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/history.md
Fixes Crashlytics  [crash report](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5b59a79f6007d59fcdced3c2)  that's caused by trying to display the preview key when the token is null.
=> [Android] Fix crash when displaying preview key

linux/scripts/version.sh
only get latest linux tag for calculating current tag number - fixes glitch in versioning local builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1233)
=> [linux] fix glitch in versioning local builds

linux/ibus-kmfl/src/kmfl.xml.in.in, linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/keyman_config/kmpmetadata.py, linux/keyman-config/keyman_config/list_installed_kmp.py, linux/keyman-config/km-package-install
Fixes #1222 : raises InstallError exceptions for install errors and warnings and handles them to present messages to the user where install_kmp is called
Fixes #1184 : restarts ibus after installing the keyboard to ibus
adds /usr/local/share/keyman/ and ~/.local/share/keyman/ to ibus-kmfl observed paths which appears to help ibus-kmfl to find the keyboards more reliably
Fix running on xenial which doesn't have enum.auto()
This appears to work on wasta xenial, wasta bionic and mate bionic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1235)
=> [linux] ibus install issues

windows/src/desktop/inst/keymandesktop.wxs, windows/src/developer/TIKE/main/Keyman.Developer.System.CEFManager.pas, windows/src/developer/inst/kmdev.wxs
1. Use compression="high" instead of "mszip" for better compression of msi
2. Remove unneeded CEF files
=> [Developer] Reduce installer size for Keyman Developer

windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectFiles.pas, windows/src/developer/TIKE/xml/project/distribution.xsl, windows/src/developer/TIKE/xml/project/packages.xsl
The Distribution tab now lists any other files you add to the project (that is, files that are not .kmn or .kps), so that you can more easily track .keyboard_info, readme.md, license.md, history.md etc.
Fixes #1220
=> [Developer] Project - List other files, such as .keyboard_info, in Distribution tab

windows/src/desktop/history.md, windows/src/developer/history.md, windows/src/engine/keyman32/K32_DBG.CPP, windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp, windows/src/engine/keyman32/kmhook_getmessage.cpp
We don't attempt to serialize input to the console windows because they 
behave somewhat differently to normal windows. For now, this should be 
sufficient. In the future, we may want to find a way to interrogate the 
focused process to find out which window actually has focus for posting
messages, because we appear to post the messages to the wrong thread
for console windows.
=> [Windows] Serialized input: don't trigger on console windows

windows/src/developer/TIKE/dialogs/UfrmOptions.dfm, windows/src/developer/TIKE/dialogs/UfrmOptions.pas, windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.App.pas, windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.AppSource.pas, windows/src/developer/TIKE/main/KeymanDeveloperOptions.pas, windows/src/developer/TIKE/main/UframeTextEditor.pas, windows/src/developer/TIKE/xml/app/editor/editor.js, windows/src/global/delphi/general/JsonUtil.pas, windows/src/global/delphi/general/RegistryKeys.pas
After implementing the Monaco editor, I had not included configurable options and theming. This fixes that.
=> [Developer] Add support for editor options and themes

linux/keyman-config/debian/control, linux/keyman-config/km-package-install
move imports so that jenkins can run km-package-install -h without dependencies installed - for generating man page
add missing dependency for tab completion: python3-bs4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1258)
=> [linux] make jenkins happy: km-package-install -h

linux/kmflcomp/src/Makefile.am
because APIs were added since last release (0.9.10)
ref https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
scenario 2 so set to 1:0:1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1259)
=> [linux] bump lib version number of libkmflcomp

linux/kmflcomp/NEWS, linux/kmflcomp/debian/changelog, linux/kmflcomp/kmfl_compiler/Makefile.am, linux/kmflcomp/src/Makefile.am, linux/scripts/launchpad.sh
minor tweaks for packaging
fix longstanding build bug reported to Debian by Ubuntu about linking X11 lib in kmflcomp
clean keyman-config before launchpad build
make kmflcomp NEWS file different from Changelog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1266)
=> [linux] misc packaging

web/package-lock.json, web/package.json, web/source/kmwdom.ts, web/unit_tests/CI.conf.js
According to https://www.browserstack.com/list-of-browsers-and-platforms?product=js_testing, it appears that iOS devices aren't available for BrowserStack-based JS testing.  This PR thus removes iOS devices from that list while updating test targets for the other, supported devices.  The goal is to allow us to re-enable BrowserStack testing as part of our KeymanWeb CI.  (A shame it won't be able to cover iOS, though.)
This also updates KeymanWeb's testing dependencies, though it does not fully update TypeScript versions.  TypeScript's had a major version update, and it breaks a few things in the codebase.  Updating to 3.1.3+ should probably be pushed to 12.0 work, since 11.0 beta's target date is pretty close.
=> Updates BrowserStack configuration settings, fixes a minor error.

common/predictive-text/testing/index.html, common/predictive-text/testing/simple-webworker/canaryWorker.js, common/predictive-text/testing/simple-webworker/index.html
Adds a small, extremely light-weight WebWorker testing page as a basic, first-stage test for LMLayer viability on various platforms.
In doing so, also adds the start of a 'testing' section to the common/predictive-text subproject.
=> [LMLayer] Basic WebWorker testing

android/KMEA/app/src/main/res/drawable/list_item.xml, android/KMEA/app/src/main/res/layout/list_layout.xml, android/KMEA/app/src/main/res/values/colors.xml
Fixes #1304 
This PR adds a light gray background to the selected list item.
(currently set/active keyboard remains in a light orange/salmon color)
Note: in KM 10, the initial focus was on the back button in the toolbar. and the user could jump between the back button <--> first list item.  So far in KM 11, the navigation is restricted to the list items.
=> [Android] Add styling to show current selection in list

windows/src/buildtools/build_standards_data/Keyman.Console.BuildStandardsData.pas, windows/src/buildtools/build_standards_data/Keyman.System.BuildNRSIAllTags.pas, windows/src/buildtools/build_standards_data/Makefile, windows/src/buildtools/build_standards_data/build_standards_data.dpr, windows/src/buildtools/build_standards_data/build_standards_data.dproj, windows/src/buildtools/buildpkg/buildpkg.dpr, windows/src/buildtools/buildpkg/buildpkg.dproj, windows/src/desktop/kmshell/kmshell.dpr, windows/src/desktop/kmshell/kmshell.dproj, windows/src/developer/TIKE/Tike.dpr, windows/src/developer/TIKE/Tike.dproj, windows/src/developer/kmcomp/kmcomp.dpr, windows/src/developer/kmcomp/kmcomp.dproj, windows/src/developer/kmconvert/kmconvert.dpr, windows/src/developer/kmconvert/kmconvert.dproj, windows/src/engine/keyman/keyman.dpr, windows/src/engine/keyman/keyman.dproj, windows/src/engine/kmcomapi/kmcomapi.dpr, windows/src/engine/kmcomapi/kmcomapi.dproj, windows/src/global/delphi/general/Keyman.System.LanguageCodeUtils.pas, windows/src/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dpr, windows/src/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dproj, windows/src/unit-tests/kmx-file-languages/KMXFileLanguagesTestSuite.dpr, windows/src/unit-tests/kmx-file-languages/KMXFileLanguagesTestSuite.dproj
rename build alltags from Keyman.System.BuildLibPalasoAllTags.pas to Keyman.System.BuildNRSIAllTags.pas
to make explicit that this is from the NRSI repo and nothing to do with libpalaso
Tom made me aware of the alltags use in Keyman and I thought this looked confusing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1302)
=> [windows] rename build alltags

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/history.md
Addresses #1312  for Keyman for Android 10.0 
Character replacement functions would crash when TextView selections had `end` positions before `start` positions. 
This PR adds a workaround to just swap positions.
Verified on ltr and rtl keyboards
=> [Android][stable] Swap TextView positions when end < start

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java
Fixes #1129
Since Cloud API 5.0 won't be developed til 12.0, going ahead with updating to Cloud API 4.0 (in line with iOS platform)
=> [Android] Update to Cloud API 4.0

common/predictive-text/package-lock.json, common/predictive-text/package.json, common/predictive-text/unit_tests/headless/basic.js, common/predictive-text/unit_tests/in_browser/CI.conf.js, common/predictive-text/unit_tests/in_browser/base.conf.js, common/predictive-text/unit_tests/in_browser/browser-test.sh, common/predictive-text/unit_tests/in_browser/cases/basic.js, common/predictive-text/unit_tests/in_browser/manual.conf.js, common/predictive-text/unit_tests/test.sh
While this PR doesn't add any notable test cases, it does provide a couple of token cases to serve as example placement for any developed test cases we may add in the future.  I've largely modeled the infrastructure off of what we already use for KMW, though with an additional section for DOMless testing, as the LMLayer should be able to support that.
A minor guide to interesting files:
* `unit_tests/in_browser/base.conf.js` specifies our base, common configuration for Karma (in-browser) testing.  Two separate *.conf.js files extend this for local vs remote (BrowserStack) testing, the latter of which is very useful for CI integration.
* `unit_tests/test.sh` is the core testing script.  As may be discerned from package.json, calling `npm test` runs this script.  This script in turn runs …
=> Adds testing infrastructure to the common LMLayer project.

ios/Cartfile.resolved, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/history.md, ios/keymanios.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Parallels #1301, cherry-picked for 10.0 stable.  A few environment and dependency updates were included out of necessity, since we're building on a newer version of Xcode that is incompatible with the old state.
=> Reachability crash alleviation

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/history.md, ios/keymanios.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Fixes #1166.
Due to some unfortunate mis-organization of code, we had internet "reachability" checks running from the system keyboard.  This makes sense in the app, which can check for keyboard updates and has event handlers designed toward that end, but little sense for the system keyboard - and since the handlers weren't intended for the system keyboard, the latter has been causing crashes.
Easiest solution?  Just disable reachability checks for system-keyboard contexts.
Also, Xcode 10's been causing some issues with IDE-based builds that are resolved by using the legacy/"original" build system.  Since it's pretty helpful to use the Simulator for testing through Xcode, the workspace settings change is being included.
=> [iOS] System keyboard + Reachability crash fix

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/KeymanWebDelegate.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/TextField.swift, ios/engine/KMEI/KeymanEngine/Classes/TextView.swift, ios/keyman/Keyman/Keyman/MainViewController.swift, ios/keymanios.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Fixes #1084.
This fix hides the in-app keyboard whenever the "Get Started" view is active, restoring it when that view is dismissed.  To accomplish this, it was necessary to add two new public API functions to KMEI's Manager.swift and extend a few related internal objects a bit.
=> [ios] "Get Started" view / keyboard conflict fix

windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas, windows/src/developer/history.md, windows/src/developer/kmcomp/main.pas, windows/src/global/inst/data/keyboard_info/keyboard_info.source.json, windows/src/global/inst/data/keyboard_info/readme.MD
From review of sillsdev/keyman-keyman.com#220
kmcomp needs to handle a parameter ~`-addHelpPath`~ `-add-help-link` which populates .keyboard_info with a link to a keyboard's help page on https://help.keyman.com/keyboard/
=> [Developer] Add "-add-help-link" parameter to kmcomp

common/engine/keyboardprocessor/src/kmx/kmx_options.cpp, common/engine/keyboardprocessor/src/kmx/kmx_processevent.cpp
This leaves a few warnings in the options_api.cpp unit test as that currently is stubbed out awaiting the options refactor. Other warnings cleared up.
=> [common] Eliminate warnings on Linux build

common/predictive-text/index.ts, common/predictive-text/package-lock.json, common/predictive-text/package.json
Targets #1365 to help fix a CI test failure related to IE missing `Promise`.
Since our goal is to eventually support LMLayer code across all our platforms, we'd like to keep support for LMLayer code in IE.  (I mean, we'd rather not, but there is that ~2.5% global user base that we do care about.)  So, to facilitate this, a polyfill for the ES6 `Promise` can be used to help bridge the gap while allowing usage of nice, newer JS features.
=> [LMLayer] Adds promise polyfill for IE.

windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectFile.pas
This was found by running through a profiler to catch calls to UI methods on threads other than the main thread.
=> [Developer] Do not callback to UI handler when creating project file on http worker thread

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java, android/KMAPro/kMAPro/src/main/res/layout/get_started_list_layout.xml, android/KMAPro/kMAPro/src/main/res/layout/get_started_row_layout.xml, android/KMAPro/kMAPro/src/main/res/menu-sw600dp/main.xml, android/KMAPro/kMAPro/src/main/res/menu/main.xml, android/KMAPro/kMAPro/src/main/res/values-sw600dp/dimens.xml, android/KMAPro/kMAPro/src/main/res/values-sw720dp-land/dimens.xml, android/KMAPro/kMAPro/src/main/res/values-sw720dp/dimens.xml, android/KMAPro/kMAPro/src/main/res/values-v21/styles.xml, android/KMAPro/kMAPro/src/main/res/values/dimens.xml
Fixes #1376 
Tweak miscellaneous UI layout for tablet
show all menu items
align the checkboxes
fix label size in titlebar
fix label size in titlebar
=> [Android] Tweak tablet layout

common/engine/keyboardprocessor/src/keyboard.cpp, common/engine/keyboardprocessor/src/kmx/kmx_xstring.cpp
Build agents had a later version of VS installed. The version check is intentionally very
specific because it is working around a bug in the standard library included with VS so we
don't want to apply it unless we have to.
=> [Common] Update VS version checks to 19.16 for latest release of VS2017 (bug in VS workaround)

ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
Fixes the iTunesConnect issue that arose with our recent iOS nightly submissions.
For reference, see https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos.  The procedure there was done for all but DeviceKit, which was just added in a recent PR.  Correcting this will fix the submission process.
=> [iOS] Fixes Carthage's link to the app for App Store submission.

linux/ibus-keyman/src/keymanutil.c
as it says on the tin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1425)
=> [linux] 'us' is the default us xkb keyboard not 'en'

common/engine/keyboardprocessor/tests/unit/kmx/000 - null keyboard.kmn, common/engine/keyboardprocessor/tests/unit/kmx/015 - ralt 2.kmn, common/engine/keyboardprocessor/tests/unit/kmx/017 - space mnemonic kbd.kmn, common/engine/keyboardprocessor/tests/unit/kmx/028 - smp.kmn, common/engine/keyboardprocessor/tests/unit/kmx/kmx.cpp
handle python compatible /Uxxxxxxxx format for smp
use e.g. [K_A] instead of a in keys:
RALT K_B is ” on an Alt-Gr keyboard so use LALT instead
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1423)
=> [common] tweak kmx tests for ibus-keyman test

linux/ibus-keyman/configure.ac, linux/ibus-keyman/debian/changelog, linux/ibus-keyman/debian/control, linux/ibus-keyman/src/Makefile.am, linux/ibus-keyman/src/engine.c
use gdk_display_beep instead of X11 beep (which is implemented in #1408 )
alternative strategy for detecting right mod keys instead of X11 calls to try and find current keypress state
forward keycode instead of keysym
N.B. this alternative strategy for detecting right mod keys effectively implements a form of compulsory sticky keys. Any Control or Alt key pressed in any order at any time before the next key is processed by keyman will be the modifier for that key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1429)
=> [linux] remove X11 dependency from ibus-keyman

linux/keyman-config/keyman_config/kvk2ldml.py
for any unshifted or shifted key that isn't specified in the kvk
recent keyboards e.g sil_pan_africa_mnemonic have all the keys in the kvk but legacy keyboards like lahu only have the changed keys. This change puts the keysto the OSK in if they are missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1438)
=> [linux] put underlying base "us" keyboard into LDML

web/source/kmwosk.ts
This PR extracts the code used to generate the OSK's keys and subkeys into their own objects, related polymorphically by a common superclass.  The main goal?  `OSKKey.generateKeyText()`, a centralized point used by both key types to build the textual representation of each key.
Focusing on this method will allow us to more easily address #1070 in a single, centralized location.  Likewise, by noting the style assigned to the relevant elements within that method, we can more easily address #382 with techniques like the one documented here: https://stackoverflow.com/a/21015393.  Finding the width of a key's text will allow us to dynamically shrink the font size as needed.
There's also the obvious benefit of improving the readability of this section of code dramatically.
=> [Web] OSK key generation refactor

windows/src/global/delphi/comp/OnScreenKeyboard.pas
This PR adds checks for the vertical text extent for each key cap as well as the horizontal text extent.
This results in most OSKs having a slightly reduced font size, which does not impact them very adversely. 
I have checked against the keyboards in keyboards/release repo folder.
The sil_tai_dam keyboard is most impacted by this but currently has whitespace on each key for a manual workaround of the overflow,
so the improvement won't really be visible until whitespace is reduced. See screenshot below for sample before-and-after. While I 
am not 100% satisfied with this improvement for Tai Dam, it does at least make the characters visible on the key cap.
[Note base on windows-osk-renderer-tool currently, will rebase once PR is merged]
=> [Windows] Tweak vertical scaling for characters that may overflow OSK key boxes (e.g. Tai Dam)

linux/ibus-keyman/configure.ac, linux/scripts/dist.sh
set GTK_CFLAGS and GTK_LIBS for make dist on jenkins because of new dependency for ibus-keyman on gdk for the alert bell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1441)
=> [linux] set GTK_CFLAGS and GTK_LIBS for make dist on jenkins

common/engine/keyboardprocessor/include/keyman/keyboardprocessor.h.in, common/engine/keyboardprocessor/src/keyboard.cpp, common/engine/keyboardprocessor/src/keyboard.hpp, common/engine/keyboardprocessor/src/km_kbp_keyboard_api.cpp, common/engine/keyboardprocessor/src/km_kbp_options_api.cpp, common/engine/keyboardprocessor/src/km_kbp_processevent_api.cpp, common/engine/keyboardprocessor/src/km_kbp_state_api.cpp, common/engine/keyboardprocessor/src/kmx/kmx_capslock.cpp, common/engine/keyboardprocessor/src/kmx/kmx_context.cpp, common/engine/keyboardprocessor/src/kmx/kmx_debug.cpp, common/engine/keyboardprocessor/src/kmx/kmx_environment.cpp, common/engine/keyboardprocessor/src/kmx/kmx_environment.h, common/engine/keyboardprocessor/src/kmx/kmx_file.cpp, common/engine/keyboardprocessor/src/kmx/kmx_modifiers.cpp, common/engine/keyboardprocessor/src/kmx/kmx_options.cpp, common/engine/keyboardprocessor/src/kmx/kmx_options.h, common/engine/keyboardprocessor/src/kmx/kmx_processevent.cpp, common/engine/keyboardprocessor/src/kmx/kmx_processevent.hpp, common/engine/keyboardprocessor/src/kmx/kmx_processor.cpp, common/engine/keyboardprocessor/src/kmx/kmx_processor.h, common/engine/keyboardprocessor/src/kmx/kmx_xstring.cpp, common/engine/keyboardprocessor/src/mock/mock_processor.cpp, common/engine/keyboardprocessor/src/mock/mock_processor.hpp, common/engine/keyboardprocessor/src/option.cpp, common/engine/keyboardprocessor/src/option.hpp, common/engine/keyboardprocessor/src/processor.hpp, common/engine/keyboardprocessor/src/state.cpp, common/engine/keyboardprocessor/src/state.hpp, common/engine/keyboardprocessor/tests/unit/kmnkbd/state_api.cpp, common/engine/keyboardprocessor/tests/unit/kmx/kmx.cpp
This refactors the underlying keyboard & abstract processor set and relationship. Moving the existing keyboard object down to a keyboard_attributes class as all it does it manage the memory and initialisation of the API km_kbp_keyboard_attrs object and makes this a member of the abstract_processor class.  Abstract_processor is now promoted to back the km_kbp_keyboard API object as performs that function anyway and this consolidates keyboard object creation and simplifies initialising the attributes and option stores.
This is in prepartion for delegating the API option store mangement to the processors.
This is branched off the common-refactor-path branch as it uses the path class and utf generic convert function work done there.
=> [wip] [Common] refactor processor init

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/history.md
Addresses the iOS portion of #1070.
Fixes https://github.com/keymanapp/keyboards/issues/436.  I have directly tested against this keyboard to help verify the overall fix.
Also fixes #382.
Applies the strategy of #1421 to subkeys within the iOS app, which is (fortunately) a far more controlled and favorable environment.
Why WIP?  [Moved to issue #1449.]
It appears that something in the change from #1421 may have revealed a bug in how the iOS app is managing certain keyboards' fonts.  Android doesn't suffer from this while iOS does.  I need to figure out what's up with SIL EuroLatin's font changing from the current `master`'s.
=> [iOS] Subkey combining diacritic display fix

web/source/kmwosk.ts
Fixes #1449.
Somehow, setting the `fontFamily` style property of the `span` element used to display key caps for KMW's OSK is bugging out within the iOS app's WKWebView, at least for certain fonts.  (Known cases occur when the OSK's global font is set to the same... but this is not sufficient, as some additional, unknown situation must also apply.)  Extra time and effort would be required to determine the exact situations in which this applies... but it's easy enough to work around for now.
=> Works around odd embedded iOS issue.

common/engine/keyboardprocessor/src/km_kbp_options_api.cpp, common/engine/keyboardprocessor/src/km_kbp_state_api.cpp, common/engine/keyboardprocessor/src/kmx/kmx_actions.cpp, common/engine/keyboardprocessor/src/kmx/kmx_environment.cpp, common/engine/keyboardprocessor/src/kmx/kmx_environment.h, common/engine/keyboardprocessor/src/kmx/kmx_options.cpp, common/engine/keyboardprocessor/src/kmx/kmx_options.h, common/engine/keyboardprocessor/src/kmx/kmx_processevent.cpp, common/engine/keyboardprocessor/src/kmx/kmx_processevent.hpp, common/engine/keyboardprocessor/src/kmx/kmx_processor.cpp, common/engine/keyboardprocessor/src/mock/mock_processor.cpp, common/engine/keyboardprocessor/src/mock/mock_processor.hpp, common/engine/keyboardprocessor/src/option.cpp, common/engine/keyboardprocessor/src/option.hpp, common/engine/keyboardprocessor/src/processor.hpp, common/engine/keyboardprocessor/src/state.cpp, common/engine/keyboardprocessor/src/state.hpp, common/engine/keyboardprocessor/tests/unit/kmnkbd/state_api.cpp, common/engine/keyboardprocessor/tests/unit/kmx/035 - options double set staged.kmn, common/engine/keyboardprocessor/tests/unit/kmx/036 - options - double reset staged.kmn
Refactor all options storage and management to be done by processor sub-classes and add a persistence cache to allow implementation save/reset.
=> [Common] Refactor options storage and lookup

linux/ibus-keyman/src/engine.c, linux/keyman-config/experiments/osk/ibus_dbus.py, linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/kmpmetadata.py, linux/keyman-config/keyman_config/uninstall_kmp.py
All the kmx in a kmp will be installed to ibus (if it is already running) for the first language of the keyboard so that users should be able to use them straight away.
using the IBus gi API rather than subprocess
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1453)
=> [linux] install kmx to ibus when installing kmp

linux/ibus-keyman/src/engine.c
It turned out I needed to pass a keysym as well as keycode, renamed func to forward_backspace
also cherry-picks the commit to fix the build from #1453 which needs review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1454)
=> [linux] forward backspace

android/history.md, web/history.md, web/source/kmwembedded.ts
Fixes #1473 by adding default handling of "tab" and "backspace" keys.
If there's keyboard rules for `K_TAB` or `K_BKSP`, they'll continue to be handled by KMW.
Otherwise, the default mapping inserts `\t` and default backspace respectively.
=> [web] Fix default mapping of external keyboard keys for "tab" and "backspace" in mobile apps

ios/Cartfile.resolved, ios/engine/KMEI/KeymanEngine/Classes/Constants.swift, ios/history.md
Addresses #1169, #1170, #1172.
One interesting detail I found while investigating #1169 was in regard to how KMEI loads data from its own bundle.  It was using its unique bundle identifier, corresponding to the following link's documentation:  https://developer.apple.com/documentation/foundation/bundle/1411929-init
Of particular note, under "Discussion":
> However, if the initial lookup of an already loaded and cached bundle with the specified identifier fails, this method uses potentially time-consuming heuristics to attempt to locate the bundle. 
Surely the framework's bundle is already loaded if we're executing `Manager` code?  `Manager` only exists within the bundle, after all.  Why search the system (what that API does) when we can retrieve it through the `Manager` type?  Hence the …
=> [iOS] System keyboard launching efficiency

linux/scripts/reconf.sh
`oldvers` is the version that comes from resources/VERSION.md before `newvers` is put into that file
the majorversion is used in the URL used by the download window
Closes: #1486
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1490)
=> [linux] fix majorversion which broke download window

common/engine/keyboardprocessor/tests/unit/kmx/meson.build
xenial doesn't like files in args. This is meson 0.40 from xenial backports which the ppa can build with
Error message is:
"Command line arguments must be strings, files or targets"
even though the arguments are files()
This is kludgy so I hope there is a better way to fix this, but if not then there is this PR
Closes: #1476
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1477)
=> [common][linux] keyboardprocessor on xenial

windows/src/README.md, windows/src/desktop/history.md, windows/src/engine/kmcomapi/com/languages/keymanlanguages.pas
=> [Windows] If a language was dynamically loaded by Windows, then the hotkey entry is never assigned when a keyboard is installed

windows/src/developer/TIKE/main/Keyman.Developer.UI.ImportWindowsKeyboardDialogManager.pas, windows/src/developer/TIKE/main/UfrmMain.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProject.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas, windows/src/developer/history.md
Fixes #1483. Also fixes a crash if project template files cannot be found (can usually only occur if running from source for debugging)
=> [Developer] Creating a new project doesn't open it automatically.

windows/src/desktop/history.md, windows/src/desktop/kmshell/main/initprog.pas
=> [Windows] kmshell now only checks for damaged profiles when starting Configuration or Keyman itself

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/FileUtilsTest.java, android/history.md
This PR addresses two issues in how Keyman for Android handles fonts:
gff_amharic keyboard lists associated fonts in this order:
```
"wookianos.woff",
"wookianos.ttf",
"wookianos.mobileconfig",
"ETHIOPI0.eot"
```
and the current Android app just grabs the first one (.woff) when making the Typeface in the WebView.
1. Fixes #1478 where certain Android SDK levels crash when attempting to create a Typeface from a .woff font
This could be replicated in an emulator of SDK level 15 and attempting to download the Amharic keyboard.
2. When downloading keyboard that lists multiple fonts, choose the .ttf if available
=> [Android] Improve font handling

windows/src/engine/kmtip/keys.cpp, windows/src/engine/kmtip/kmtip.h
The switch could fail when attempting to initialize the keystroke sink, because it is already initialized,
because TSF does not deactivate the TIP when switching between different registered profiles with the same
TIP CLSID.
=> [Windows] Switching between Keyman keyboards in same language using TSF interface could fail

linux/history.md, linux/ibus-keyman/configure.ac
reduce the version dependency on json-glib-1.0 to 1.0 so that it will build with the version in xenial
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1518)
=> [linux] build ibus-keyman on xenial

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/FileUtilsTest.java, android/history.md
Fixes #1512 
Currently, keyboard versions as floats are compared for determining when to update the keyboard.
This doesn't work for the current default keyboard sil_euro_latin version 1.8.1
* Move compareVersions() from KMManager to FileUtils
=> [Android] Change keyboard version comparison from Float to strings

linux/history.md, linux/ibus-keyman/debian/postinst, linux/ibus-keyman/debian/postrm
This time do things differently on gnome-shell
It needs to run `ibus exit` instead of `ibus restart`
check just 1 pid
sudo -H to get the right user environment for running ibus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1521)
=> [linux] more on restarting ibus

android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHardwareKeyboardInterpreter.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardJSHandler.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMScanCodeMap.java, android/history.md, web/source/kmwembedded.ts
Fixes #1500 
In the case KMW doesn't process some keys ("tab" or "enter"), have the app dispatch the keyEvent for Android OS to natively handle it.
This way, "Tab" can insert whitespace in text fields and navigate in forms
Expected system keyboard behavior
tab (sometimes) inserts whitespace
tab (in a form) - navigate to next field
shift-tab (in a form) - navigate to previous field
enter - inserts newline
alt-tab - Android app overview (app switcher)
ctrl-tab - brings Keyman language menu
=> [Android] dispatch external keys if KMW doesn't handle them

windows/src/developer/TIKE/xml/layoutbuilder/builder.js
=> [Developer] Rename default to '(current layer)' to reduce ambiguity.

common/predictive-text/docs/worker-communication-protocol.md, common/predictive-text/index.ts, common/predictive-text/message.d.ts, common/predictive-text/promise-store.ts, common/predictive-text/unit_tests/headless/promise-store.js, common/predictive-text/unit_tests/headless/worker-initialization.js, common/predictive-text/unit_tests/headless/worker-predict-dummy.js, common/predictive-text/unit_tests/headless/worker-predict.js, common/predictive-text/unit_tests/helpers.js, common/predictive-text/unit_tests/in_browser/CI.conf.js, common/predictive-text/unit_tests/in_browser/base.conf.js, common/predictive-text/unit_tests/in_browser/cases/top-level-lmlayer.js, common/predictive-text/unit_tests/in_browser/cases/worker-dummy-integration.js, common/predictive-text/unit_tests/in_browser/json/future_suggestions/i_got_distracted_by_hazel.json, common/predictive-text/unit_tests/test.sh, common/predictive-text/worker/dummy-model.ts, common/predictive-text/worker/index.ts, common/predictive-text/worker/worker-interfaces.ts
~~**NOTE**: still a work in progress; do not merge!~~ Please review!
This creates a new language model that suggests exactly what you tell it to suggest! It's instantiated with a list of `futureSuggestions`, which it will return sequentially on each call to `.predict()`.
This is looking to be a bigger PR than I thought, so please review what's there right now as I tackle the remaining TODOs:
=> [LMLayer] Implement Dummy language model + refactorings

web/source/kmwosk.ts, windows/src/developer/TIKE/compile/CompileKeymanWeb.pas, windows/src/developer/TIKE/oskbuilder/TouchLayout.pas, windows/src/developer/TIKE/oskbuilder/TouchLayoutDefinitions.pas, windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas, windows/src/developer/TIKE/xml/layoutbuilder/builder.css, windows/src/developer/TIKE/xml/layoutbuilder/builder.js, windows/src/developer/TIKE/xml/layoutbuilder/builder.xsl
Fixes #1117.
Also fixes:
* A crash switching between Code and Design tabs in Touch Layout Editor
* KDU flag is always filled by KMW compiler, even if no OSK is included in the compiled keyboard
However, currently KMW effectively ignores the KDU flag for desktop because of the `isDesktop` test 
in kmwosk:312, which is something we could improve!
There is a separate issue of blank keys getting a default character in the desktop OSK. Changing this
would require much care around testing existing keyboard layouts to ensure that what is displayed 
continues to make sense, particularly for latin-based layouts.
=> [Web] [Developer] displayUnderlying flag is now separate for different platforms.

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMModifierCodes.java, android/Tests/KeyboardHarness/app/src/main/assets/cloud/chirality-1.0.js, web/package-lock.json, web/package.json, web/source/kmwbase.ts, web/source/kmwcallback.ts, web/source/kmwdomevents.ts, web/source/kmwembedded.ts, web/source/kmwhotkeys.ts, web/source/kmwkeyboards.ts, web/source/kmwkeymaps.ts, web/source/kmwtypedefs.ts, web/source/osk/defaultLayouts.ts, web/source/osk/oskManager.ts, web/source/osk/visualKeyboard.ts, web/source/recorder_ui_and_stubs.js, web/source/text/codes.ts, web/source/text/processor.ts, web/testing/chirality/chirality.js, web/unit_tests/resources/keyboards/khmer_angkor.js, web/unit_tests/resources/keyboards/test_deadkeys.js
This PR refactor's KMW's keystroke mapping functionality into a common module.  With all the OSK reorganization work done to this point, it's now comparatively simple to extract its old `.clickKey` function and related helpers into a new `Processor` module and to refactor it alongside the hardware-based keystroke functions.  A few areas of commonality have been found and utilized to simplify future code maintenance in this area.
During work on this, some additional issues with mnemonic support have been noted.  While I have refactored the existing code, I have not addressed the issues themselves; they have been noted on https://github.com/keymanapp/keyman/issues/846.
=> [Web] Keystroke processing refactor

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMModifierCodes.java, android/Tests/KeyboardHarness/app/src/main/assets/cloud/chirality-1.0.js, web/package-lock.json, web/package.json, web/source/kmwbase.ts, web/source/kmwcallback.ts, web/source/kmwdomevents.ts, web/source/kmwembedded.ts, web/source/kmwhotkeys.ts, web/source/kmwkeyboards.ts, web/source/kmwkeymaps.ts, web/source/kmwnative.ts, web/source/kmwtypedefs.ts, web/source/osk/defaultLayouts.ts, web/source/osk/languageMenu.ts, web/source/osk/oskManager.ts, web/source/osk/visualKeyboard.ts, web/source/recorder_ui_and_stubs.js, web/source/text/codes.ts, web/source/text/processor.ts, web/testing/chirality/chirality.js, web/unit_tests/resources/keyboards/khmer_angkor.js, web/unit_tests/resources/keyboards/test_deadkeys.js
This PR seeks to improve OSK code by adding a TS 'merger' type for its keys, allowing our customized properties to be tracked by TypeScript in a manner associated with their DOM element.  This, in turn, improves type checking on the OSK's keystroke processing methods.
=> [Web] Adds better typing for OSK keys, some related fixes.

common/predictive-text/promise-store.ts, common/predictive-text/unit_tests/headless/promise-store.js, common/predictive-text/unit_tests/in_browser/cases/worker.js, common/predictive-text/worker/index.ts
- documented use of `Map` in IE11
- fixed bug where reusing a token would replace the new token with a rejected promise
- removed ability to send a model as source code; now it must be a dummy model
✨ 😂
=> [LMLayer] Tidying up, plus fix minor bug

common/engine/keyboardprocessor/src/km_kbp_context_api.cpp, common/engine/keyboardprocessor/src/utfcodec.hpp, common/engine/keyboardprocessor/tests/unit/kmnkbd/context_api.cpp
Iterators now deduce and track remaining buffer space from == or != comparision operators. They default to infinite (> 4) when no comparisions are called, making them still useful for scan until terminator uses. This is supplied to every call of get and put.
=> [common] bugfix for potential utf overrun on beta brach

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardListActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageListActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/MapCompat.java, android/history.md
During implementation of #1550, HashMap.getOrDefault() calls were used.
That method is only available for Android API levels 24+, so this PR provides an alternative for older API's.
=> [Android] Add HashMap.getOrDefault for older Android API levels

android/.gitignore, android/KMAPro/kMAPro/src/main/res/layout/get_started_list_layout.xml, android/KMEA/app/src/main/AndroidManifest.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ConfirmDialogFragment.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageListActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/JSONUtils.java, android/KMEA/app/src/main/res/values/styles.xml, android/history.md
This PR adds some polish to the UI to clean up some nuisances.
1. Fix "Get Started" checkbox label
For lower versions of Android API levels, the "Get Started" checkbox label doesn't appear. I suspect it's vertically aligned, and off  the screen. These screenshots are with the Nexus S emulator on Android API 16.
2. Currently, a "Keyman" label flickers after downloading keyboards and ConfirmDIalogFragment finishes.
These changes make the flicker less noticeable:
* Set the app name blank in the Manifest
* Dismiss the dialog fragment and finish the activity
* Updated ConfirmDialogFragment to have a flexible message body (second parameter)
* Updated gitignore to ignore artifacts from Android Studio's "Layout Inspector" tool
3. Fix pattern used in SimpleDateFormat found while testing this PR. …
=> [Android] Misc UI cleanup

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardListActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageListActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java, android/KMEA/app/src/main/res/values/strings.xml, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/FileUtilsTest.java, android/history.md
Fixes #1552 
Currently when downloading a keyboard from the cloud, the download activity silently fails if the font or keyboard fails to download.
* This PR add a toast warning when font fails to download. (Keyboard is still installed)
* Also adds an error dialog if the keyboard fails to download
From the LanguageListActivity
* From the KeyboardListActivity
(test code used to induce the above scenarios)
* The toast notifications in MainActivity and KeyboardListActivity also removed since they're handled in LanguageListActivity
* Finally, fixed null string exception when FileUtils.download() fails
=> [Android] Add notifications when font/keyboard fails to download

windows/src/desktop/kmshell/main/initprog.pas, windows/src/developer/TIKE/actions/dmActionsMain.dfm, windows/src/developer/TIKE/actions/dmActionsMain.pas, windows/src/developer/TIKE/child/UfrmPackageEditor.pas, windows/src/developer/TIKE/compile/CompileKeymanWeb.pas, windows/src/developer/TIKE/dialogs/UfrmNew.pas, windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectFile.pas, windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectLoader.pas, windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectSaver.pas, windows/src/developer/TIKE/project/Keyman.Developer.System.Project.kmnProjectFileAction.pas, windows/src/developer/TIKE/project/Keyman.Developer.System.Project.kpsProjectFileAction.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmProjectSettings.dfm, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmProjectSettings.pas, windows/src/developer/kmcomp/kccompilepackage.pas, windows/src/developer/kmcomp/kccompileproject.pas, windows/src/developer/kmcomp/main.pas, windows/src/developer/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas, windows/src/global/delphi/general/CompilePackage.pas, windows/src/global/delphi/general/CompilePackageInstaller.pas, windows/src/global/delphi/keyboards/Keyman.System.KeyboardUtils.pas, windows/src/unit-tests/keyboard-package-versions/Keyman.Test.System.CompilePackageVersioningTest.pas
Fixes #984.
While I would not normally include this in beta, it has been outstanding since v10 and 
really is needed for keyboard quality and cross-platform stability.
* A 'clean' component consists of only alphanumeric, `_`, `-` and `.` characters.
* Filename component must be lowercase, not start with a digit, and contain only alphanumeric and underscore.
* Extension component must be lowercase and 'clean'
* Filename component must be 'clean'.
* Extension component must be lowercase and 'clean'
=> [Developer] Add option to check filename conventions

windows/src/global/delphi/general/kmxfile.pas, windows/src/global/delphi/packages/Keyman.System.PackageInfoRefreshKeyboards.pas
Fixes #1219.
Note: history.md updates in #1575 (expecting both PRs to land on same day).
=> [Developer] Package RTL keyboard metadata was being overwritten if .kmx was after .js in package file list

linux/history.md, linux/ibus-keyman/src/kmpdetails.c, linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/uninstall_kmp.py
When km-config parses kmp.json to install keyboard packages, the languages array can be empty. e.g.
```
"keyboards": [
{
"name": "General",
"id": "ge",
"version": "9.0",
"languages": [
]
}
]
```
This causes install/uninstall to throw index out of bounds exception.
Tested with https://darcywong00.github.io/examples/invalid/ge.kmp
=> [linux] Update km-config to handle packages with empty "languages"

mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutWindowController.m, mac/Keyman4MacIM/Keyman4MacIM/KMInputController.m, mac/Keyman4MacIM/Keyman4MacIM/KMOSVersion.h, mac/Keyman4MacIM/Keyman4MacIM/KMOSVersion.m
This should obviate PR #686 by improving the code to run on all versions, including the buggy ones, but only call the workaround on those (or future) buggy versions.
=> [mac] Where available, call showPreferences, otherwise, call our workaround

web/package-lock.json, web/package.json, web/source/kmwapi.ts
Fixes #1516.
Removes a dependency on the Google Closure library (separate from the compiler) that was intended to facilitate better minification, but was causing issues on some devices.  Said 'advanced-level' minification is no longer a priority and is nowhere on our roadmap at this point, so little is lost here.
Note that this fix will need a tweak when it reaches 'master' / the alpha to reflect some of its recent refactorings.
=> [Web] Unintended use of goog.DebugLoader fix

windows/src/engine/keyman32/kmprocess.cpp, windows/src/engine/keyman32/message-analyzer/README.md
=> [Windows] Keyman now handles backspace correctly again for SMP characters in TSF-aware apps

linux/history.md, linux/keyman-config/keyman_config/ibus_util.py, linux/keyman-config/keyman_config/install_kmp.py
This addresses the issue in legacy KMFL keyboard packages that used to install but fail in Keyman for Linux because of filecasing.
e.g. the .kmp filename or .kmx files are upper-case so when the ID's in kmp.json are parsed, things don't align.
Example: https://darcywong00.github.io/examples/invalid/BDH.kmp
Changes:
* Lower-case the folder (packageID) when extracting the .kmp file.
* Lower-case the .kmx files that match the keyboards list.
=> [linux] Sanitize packageID, keyboardID, and kmx filenames

windows/src/engine/keyman32/keyman-debug-etw.man, windows/src/engine/keyman32/serialkeyeventserver.cpp
Fixes #1620.
When Windows has a European layout that uses AltGr installed, it can emit an additional LCtrl down via software when RAlt is pressed. However, the corresponding LCtrl up is never received, seemingly because when Keyman re-emits the LCtrl+RAlt, there are subtle differences in the event flags which we cannot duplicate -- specifically the flag that emits WM_SYSKEYDOWN for the VK_LCONTROL, even though it is received before the VK_RALT event. It appears that Windows figures this out by giving this VK_LCONTROL the scan code 0x21D instead of 0x1D. But we are unable to emit that scan code: Windows truncates the scan code sent through SendInput so that we can only send 0x1D.
So we simulate the release of the Left Control key ourselves when the release of the Right Alt is received, …
=> [Windows] AltGr causes sticky Left Control when some Windows European layouts are installed.

common/predictive-text/unit_tests/in_browser/CI.conf.js, web/unit_tests/CI.conf.js
It's obviously not ideal, but since the Safari checks have been causing CI to report failures due to not actually running (it's something with BrowserStack), this will disable them until that issue is resolved.
=> [Web] Disables Safari tests for KMW pending BrowserStack fix.

web/history.md, web/source/kmwuitoolbar.ts
Context:  We've long had Closure's "advanced" minification in place on most of KMW's UI modules, which can get rather... aggressive... about renaming methods.  Accessing KMW methods through an "associative array" style bypasses this tendency.
Fixes the underlying issue of https://github.com/keymanapp/keymanweb.com/pull/2.
=> [Web] Toolbar UI minification fix

common/engine/keyboardprocessor/src/kmx/kmx_base.h
__x86_64__ is only for Intel __LP64__ and _LP64 are for any arch that has 64bit `long int` and pointers, and 32bit `int` same as Intel.
=> Use more generic preprocessor macro 64bit

android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageListActivity.java, android/history.md
Fixes [crash report](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5c73bebdf8b88c29630d9b7d?time=last-seven-days&sessionId=5C73FD0B01F50001606FDCD1E526D22F_DNE_0_v2) when the LanguageListActivity is attempting to show the error dialog after the Activity is finished.
References: 
* https://stackoverflow.com/questions/7811993/error-binderproxy45d459c0-is-not-valid-is-your-activity-running
* http://dimitar.me/android-displaying-dialogs-from-background-threads/
=> [Android] Check activity is not finishing before showing error dialog

web/source/kmwembedded.ts
Looks like during the work on `outputTarget` conversion, I forgot to properly add the necessary code into the `executePopupKey` method for the embedded, in-app version.  This resulted in some issues Darcy noted with Android longpress keys, hence this quick fix.
=> Fixes mobile app longpress key regression.

mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutBGView.m, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutWindowController.xib
by going back to defaults for text colors and button borders, but having the background view use windowBackgroundColor instead of white to fill.
Fixes #1624 at least for Mojave Light Mode (and Dark Mode looks better than ever)
Will test on VMs of earlier OSes next.
Light Mode:
Dark Mode:
=> [Mac] fix dark/light brokenness in About Box

web/source/kmwapi.ts, web/source/kmwutils.ts
Fixes #1638.
Certain UI related methods were accidentally being overwritten, as the `publishAPI` calls related to them had the parameters in the incorrect order.  This fixes that and makes one other related method more consistent with the others to prevent confusion.
=> [Web] Fixes Web UI controller alignment

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/JSONParser.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/build.sh
When downloading a keyboard from the cloud, also download associated lexical models.
(Currently limited to the first one)
* Refactor JSONParser to download JSONObject or JSONArray from a URL
* Also update TC reporter of unit tests
=> [Android] Get lexical model packages from API

android/README.md
Adds to the Mac instructions what I had to do to get Android Studio running and building.
=> [Android] add Mac instructions for getting Android Studio running

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java
Turns out order of operations matter...
Revert some import statements that #1654 "cleaned up" but are still needed in #1653
=> [Android] Fix the build

android/KMAPro/kMAPro/build.gradle
The newer gradle-play-publisher changed from `jsonFile` to `serviceAccountCredentials`
=> [Android] Fix gradle syntax for account credentials

web/source/kmwembedded.ts, web/source/text/processor.ts
This PR aims to centralize text processing even further, finding common aspects between 'embedded' and 'native' modes so that the `Processor` can handle the central aspects of text processing and coordinate with our in-development predictive text module.
Fortunately, much of embedded mode's `executePopupKey` was a pre-existing copy-paste of its corresponding native-mode control path.  While some of the `KeyEvent` generation code is necessarily unique (there's no DOM element corresponding to mobile in-app popup keys), much of the rest can easily be handled by existing `Processor` code.
More troublesome - handling external keyboard keystrokes, as many of the existing 'default' keystroke handling is designed from the perspective of _browser_ defaults.  Fortunately, we're using TS, which is …
=> [Web] Embedded-mode processing refactor

common/predictive-text/message.d.ts, web/source/includes/lmMsgs.d.ts, web/source/text/kbdInterface.ts, web/source/text/outputTarget.ts, web/source/text/prediction/modelManager.ts, web/source/text/processor.ts
This PR will allow KMW to start making prediction requests on the LMLayer for keyboards with supported lexical models, providing the necessary values to initiate such requests.
At this time, no effort is made to supply any layout or timing data which could be used to enhance the accuracy of predictions in cases of potential fat-fingering or typos - this will require further design and implementation work to achieve.
=> [Web] Generation of prediction requests

web/source/osk/bannerManager.ts
Noting @mcdurdin's recent comment on #1678, this adds that PR's notes on `BannerManager` design as documentation to the TS file.  It's been formatted to look nice with VS Code Intellisense.
=> [Web] BannerManager docs

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java, android/KMAPro/kMAPro/src/main/res/values/strings.xml, android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardEventHandler.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardListActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageListActivity.java, web/source/kmwembedded.ts
* When lexical models are installed, add them to a cachable `lexicalModelsList` that is stored on a file `lexical_models_list.dat` (similar to how existing installed keyboards get saved to `keyboards_list.dat`)
* When a keyboard is switched, determine if there's an associated lexical model and register it to KMW
TODO
Troubleshoot KMW console errors from KMW when registering lexical models
=> [Android] Store a lexical models list and register lexical models to KMW

common/predictive-text/package-lock.json
Quick PR:
`npm` has been changing the lock file, and asking me to update deps with security vulnerabilities, so here's the result of running `npm audit --fix`.
=> [LMLayer] Update dependencies based on npm audit

common/predictive-text/package.json
Small PR:
Allow the LMLayer to be used as from node, outside of the `predictive-text` directory. E.g., from the keyman root dir:
```
$ node
> const LMLayer = require('./common/predictive-text');
undefined
> let lm = LMLayer({}, new Worker);
```
=> [LMLayer] Allow LMLayer to be imported as a Node module

common/predictive-text/message.d.ts, common/predictive-text/worker/index.ts, web/source/dom/contentEditable.ts, web/source/dom/designIFrame.ts, web/source/dom/input.ts, web/source/dom/textarea.ts, web/source/dom/touchAlias.ts, web/source/dom/touchAliasElement.ts, web/source/osk/banner.ts, web/source/osk/bannerManager.ts, web/source/osk/oskManager.ts, web/source/resources/osk/kmwosk.css, web/source/text/outputTarget.ts, web/source/text/prediction/modelManager.ts
When complete, this PR will allow active use of the `SuggestionBanner` UI, allowing a user to apply LMLayer-generated predictions.
Done:
- Restoring an `OutputTarget`'s context to the state that generated the prediction request
- Applying a `Suggestion`'s `Transcription` to a destination `OutputTarget`
- Some refactoring of the new `SuggestionBanner` and some enhanced styling.
- Styling is likely not permanent, but will at least make the interactive area more clear than otherwise.
Note that #1714, which is based on this PR, implements touch interactivity.
=> [Web] Application of predictive Suggestions.

common/test/predictive-text/README.md, common/test/predictive-text/index.js, common/test/predictive-text/package.json
Adds batch mode, invokable three ways:
```sh
$ lmlayer-cli author.bcp47.uniq -p "a test phrase" -p "another test phrase"
$ lmlayer-cli author.bcp47.uniq -i my-test-file.txt
$ echo "anything from stdin" | lmlayer-cli author.bcp47.uniq
```
The output is tab-separated, with the first column being the input, and the remaining columns being the suggestions, e.g.,
```sh
$ lmlayer-cli example.en.wordlist -p "d"
d      dinosaur        dumbo octopus
$ echo "c" | lmlayer-cli example.en.wordlist
c      cat     cheetah
```
Resolves #1726.
=> [LMLayer] Batch mode for CLI

web/testing/regression-tests/src/known-failures.js
This updates the available regression tests to remove known failures that are now resolved along with the updated 11.0 stable compiler. Ref #183.
=> [Web] Remove keyboards that have been addressed from known-failures for #183 fix

android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardJSHandler.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html, web/source/kmwbase.ts, web/source/osk/banner.ts, web/source/text/outputTarget.ts, web/source/text/prediction/modelManager.ts
This PR allows embedded-KMW to properly output predictive suggestions to the apps' IME interfaces.
Already implemented:
- With this change in place, basic interaction is now fully possible within the Android app!
- Basically, just enough to mirror this PR's Android changes.
Yet to implement:
* Right-deletions
- As per Slack conversations with @eddieantonio and @mcdurdin, supporting these is not a priority at this point.
=> In-app acceptance of predictive suggestions

windows/src/developer/kmcmpdll/Compiler.cpp
In some rare circumstances, we could see keyboard builds fail when Unicode characters were used, for example, in store names. For example, we saw this sometimes with gff_geez when doing a pull request regression test.
```
[06:51:51][Step 5/5] gff_geez.kmn: Compiling 'C:\BuildAgent\work\bf14f11ed1179e5e\keyboards\release\gff\gff_geez\source\gff_geez.kmn' for Windows, macOS, Linux...
[06:51:51][Step 5/5] gff_geez.kmn: Error: line 93  error 400A: Invalid token found chr:19 extra:token: %
[06:51:51][Step 5/5] gff_geez.kmn: Error: line 127  error 400A: Invalid token found chr:2 extra:token: %
[06:51:51][Step 5/5] gff_geez.kmn: Error: line 318  error 401D: Store referenced does not exist chr:18
[06:51:51][Step 5/5] gff_geez.kmn: Error: …
```
=> [Developer] Calls to non-Unicode versions of ctype functions could cause instability

windows/src/engine/kmcomapi/util/utilkeyman.pas, windows/src/global/delphi/general/klog.pas
=> [Windows] [10.0] Fix FieldWorks LT-19402, buffer overrun in GetDefaultKeyboardID for 64 bit

windows/src/desktop/history.md, windows/src/developer/history.md, windows/src/engine/kmcomapi/util/utilkeyman.pas, windows/src/global/delphi/general/klog.pas
=> [Windows] [11.0] Fix FieldWorks LT-19402, buffer overrun in GetDefaultKeyboardID for 64 bit

windows/src/desktop/history.md, windows/src/engine/kmcomapi/util/utilkeyman.pas, windows/src/global/delphi/general/klog.pas
The buffer size for the return of SPI_GETDEFAULTINPUTLANG is 8 bytes (HKL, or UINT_PTR) on Win64 but we were only allocating 4 bytes (Cardinal). This led to memory corruption, which was messy enough that when the inevitable access violation occurred, our error handling was unable to log it.
Ref https://jira.sil.org/browse/LT-19402
This will be backported to 11.0 stable, 10.0 stable.
=> [Windows] Fix FieldWorks LT-19402, buffer overrun in GetDefaultKeyboardID for 64 bit

android/KMAPro/build.gradle, android/KMAPro/gradle/wrapper/gradle-wrapper.properties, android/KMAPro/kMAPro/build.gradle, android/KMEA/app/build.gradle, android/KMEA/build.gradle, android/KMEA/gradle/wrapper/gradle-wrapper.properties, android/Samples/KMSample1/app/build.gradle, android/Samples/KMSample1/app/src/main/java/com/keyman/kmsample1/MainActivity.java, android/Samples/KMSample1/build.gradle, android/Samples/KMSample1/gradle/wrapper/gradle-wrapper.properties, android/Samples/KMSample2/app/build.gradle, android/Samples/KMSample2/build.gradle, android/Samples/KMSample2/gradle/wrapper/gradle-wrapper.properties, android/Tests/KeyboardHarness/app/build.gradle, android/Tests/KeyboardHarness/app/src/main/java/com/keyman/android/tests/keyboardHarness/MainActivity.java, android/Tests/KeyboardHarness/build.gradle, android/Tests/KeyboardHarness/gradle/wrapper/gradle-wrapper.properties, android/Tests/keycode/build.gradle, android/Tests/keycode/gradle/wrapper/gradle-wrapper.properties
Android Studio is warning a call (from Firebase) will be deprecated end of 2019. This updates the versions of
* Firebase
* Gradle from 4.10.1 to 5.1.1
Also stubs a missing keyboard event handler in some of the sample/test projects.
=> [Android] Update dependencies again

android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardJSHandler.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/res/values-land/dimens.xml, android/KMEA/app/src/main/res/values-sw600dp-land/dimens.xml, android/KMEA/app/src/main/res/values-sw600dp/dimens.xml, android/KMEA/app/src/main/res/values/dimens.xml, android/KMEA/build.sh, ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html, web/source/build.sh, web/source/kmwbase.ts, web/source/kmwdom.ts, web/source/kmwembedded.ts, web/source/kmwnative.ts, web/source/osk/banner.ts, web/source/osk/bannerManager.ts, web/source/osk/oskManager.ts, web/source/text/outputTarget.ts, web/source/text/prediction/modelManager.ts, web/source/text/processor.ts
This PR does some cleanup and integrates suggestions with the Android app
* Per @jahorton , allow the apps to specify `Banner.DEFAULT_HEIGHT`.
* Add listener for `mm.modelchange` event to detect model changes "unload" and "load"
* Have Android app track the banner (suggestion vs blank) on lexical model change
* Pass the banner height to KMW on device rotations (portrait vs landscape)
* Update build scripts so `-debug` variant uses unminified KMW
1. Install Joshua's en wordlist `/web/testing/prediction-ui/simple-en-wordlist.js`
2. Add another English (US) keyboard
3. On the device, delete the en.custom model that gets installed (it currently generates exceptions)
4. The suggestion banner should appear when switching to an English keyboard. Accepting suggestions will have the same …
=> [Android] Accommodate dimension for device banner

web/source/kmwdomevents.ts, web/source/osk/banner.ts, web/source/osk/bannerManager.ts, web/source/text/kbdInterface.ts, web/source/text/outputTarget.ts, web/source/text/prediction/modelManager.ts, web/source/text/processor.ts, web/testing/prediction-ui/index.html
New features:
- Upon initialization and change-of-context, new predictions will be generated.
- These will be based on the caret position within the context, allowing the LMLayer to use context for these predictions.
- Hitting the spacebar with a highlighted suggestion will auto-accept it.
- Outside of touch-interaction, nothing presently 'highlights'/selects a suggestion - **yet**.
- Future work:  language modeling input is needed for automatic selection.
- Acceptance will also auto-trigger new predictions.
- Hitting backspace immediately after accepting a prediction rejects it:
- The 'accept' operation will be reverted.
- The rejected suggestion will be removed from the stored suggestion buffer/list.
- While we only ever have three at max presently, that can easily be altered - …
=> [Web] Predictive text UX improvements

common/predictive-text/unit_tests/headless/ascii-word-breaker.js, common/predictive-text/worker/defaultWordBreaker.ts, common/predictive-text/worker/index.ts, common/predictive-text/worker/models/trie-model.ts, common/predictive-text/worker/models/wordlist-model.ts, common/predictive-text/worker/word_breaking/ascii-word-breaker.ts, common/predictive-text/worker/word_breaking/placeholder-word-breaker.ts, common/predictive-text/worker/worker-interfaces.ts
This pull request introduces the basic word breaking API. At its simplest, the word breaker is simply a function that returns words.
```ts
interface WordBreakingFunction {
(phrase: USVString): Span[];
}
```
A `Span` is the word, plus data like what index it started on, and what index it ended on.
```ts
interface Span {
readonly start: number;
readonly end: number;
readonly length: number;
readonly text: string;
}
```
---
A model may explicitly require a word breaking function in its options; the compiler will generate the appropriate code:
```ts
var parameters = {/* ... */};
LMLayer.loadModel(new MyCoolModel(parameters, { wordBreaker: function (phrase) { return []; }));
```
=> [LMLayer] Word breaking

web/source/osk/banner.ts, web/source/text/prediction/modelManager.ts
Fixes the following issue:
- Selecting a 'blank' suggestion element was erroneously triggering predictive state management.
- Most significantly, this tended to temporarily break the BKSP key.
=> [Web, Android, iOS] Null suggestion banner bug

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
Update KMManager to handle determining associated lexical models and registering accordingly.
The current lexical model info is kept so switching keyboards into the same language won't trigger a new model registration.
Model registration now also occurs on app / keyboard startup
=> [Android] Insert more places for lexical models to be registered

android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/JSONParser.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/KeyboardCommandStructs.swift, ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html, web/source/kmwembedded.ts, web/source/osk/banner.ts
Provides hooks for KMW to notify the apps of an ongoing longpress on a predictive text option, ensuring any relevant data reaches each app's native code.  Nothing of use is done with this data yet (just logging), but the transfer of data has been tested and verified, providing a useful starting point to add options for predictive text suggestions.
=> [Web, iOS, Android] Base for predictive text longpress

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, common/predictive-text/worker/models/trie-model.ts, common/predictive-text/worker/models/wordlist-model.ts, ios/.gitignore, ios/build.sh, ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Storage.swift, web/source/build.sh, web/source/kmwdomevents.ts, web/source/kmwembedded.ts, web/source/osk/banner.ts, web/source/text/prediction/modelManager.ts
This PR does not provide any UI for rotating suggestions; just the underlying functionality that any such UI might connect to.  It also provides an API endpoint for use by the Android and iOS apps, designed to be called by yet-to-be-implemented longpress menus on the SuggestionBanner's options.
To test, call the following within the Dev Console within Chrome when testing a mobile form factor: `keyman.osk.banner.activeBanner.rotateSuggestions()`.  Make sure the banner is visible when entering this console command, as the suggestions will reset whenever the OSK reappears (as KMW [rightly] thinks a context change has occurred.)
I've noticed that the apps' initial state for the SuggestionBanner is a bit off with this in place, so I do need to chase down what's causing that.
=> [Web] Support for 'rotation' of predictive suggestions

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsFragment.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMAPro/kMAPro/src/main/res/values/strings.xml, android/KMEA/app/src/main/AndroidManifest.xml, android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ConfirmDialogFragment.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguagesSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelInfoActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelsPickerActivity.java, android/KMEA/app/src/main/res/layout/language_settings_list_layout.xml, android/KMEA/app/src/main/res/layout/list_row_layout4.xml, android/KMEA/app/src/main/res/values/strings.xml, web/source/text/prediction/modelManager.ts
This PR connects the menu settings hierarchy:
Keyman Settings --> Languages Settings --> Language Settings
Language Settings displays associated keyboards that are installed for a language ID.
There's also some toggles for configuring lexical models later.
Preliminary screenshot accessed by clicking through "Keyman Settings"
(screenshot updated to remove "Manage dictionary" setting)
Note: Entry to "Uninstall keyboard" is not available on the default SIL Euro Latin keyboard
Language Settings --> can select Models Picker (bottom line)
Models Picker --> Model Info
longpress to delete model doesn't do anything
Originally, this only confirmed downloading keyboards. Dialog now expanded for more uses:
* Delete keyboard
* Download model (future PR)
* Delete model
=> [Android] Add "Language Settings" menu stub

android/KMEA/app/src/main/assets/keyboard.html
After #1770 , KMW deregisters and sets the banner height to 0.
This revealed a bug in the Android JS `setBannerHeight()` function where `kmw` wasn't defined and attempted to call `kmw.correctOSKTextSize();`
Expand line 52 when viewing the change
=> [Android] Fix exception when setting banner height 0

common/predictive-text/unit_tests/in_browser/cases/worker-wordlist-integration.js
The in-browser test `LMLayer using the word list model » Prediction » will predict an empty buffer` fails sporadically in builds. I initially just thought it was the build server, then noticed it happening once on my machine. It turns out that this test is just a slow boi, and exceeds Mocha's 2000 ms timeout value for asynchronous tests. Mocha assumes that tests that have exceeded this timeout have crashed, which is not the case here! So I simply doubled this particular test's timeout value. Hopefully, this gets rid of all of the test flakiness.
=> [LMLayer] Treat flakiness in 'empty buffer' test.

web/source/text/prediction/modelManager.ts
As IE9- doesn't support `WebWorker`s and IE10 doesn't appear to support the method we use to initialize it (generates `SecurityException`s), this PR simply disables the LMLayer (within KMW) in IE9 and IE10.  This is necessary to allow KMW to properly load in these browsers.
=> [Web] Disables the LMLayer when IE active and < 11.

common/test/predictive-text/index.js, common/test/predictive-text/package-lock.json
Small PR that deselects the current suggestion when you have just accepted a suggestion. It doesn't make sense to select the same index of the suggestion again!
=> [LMLayer] Deselect suggestions when one is selected.

developer/js/index.ts
=> [developer] Lexical model compiler was not flattening languages arrays for .model_info file

common/predictive-text/unit_tests/headless/worker-predict-trie.js, common/predictive-text/worker/models/trie-model.ts
Say you wanted to write the name of the FPCC conference: "HELISET TŦE SḰÁL".
Previously , if you started off by writing:
> helis|
[HELIS] [HELISE] [HEL¸ISET] [HELISET] [HELISETNOṈET]
Then you'd accept [HELISET], it would result in this buffer:
> helisET |
[TŦE] [E] [SEN] [Ȼ] [SW̱] [NIȽ] [U¸] [I¸] [ȻSE] [I] [YÁ¸] [ȻE]
Now that the model _replaces_ the prefix you wrote with what's in the model, it does the following:
> HELISET |
[TŦE] [E] [SEN] [Ȼ] [SW̱] [NIȽ] [U¸] [I¸] [ȻSE] [I] [YÁ¸] [ȻE]
The replacement is probably what you want!
---
By the way, using the predictions with the `lmlayer-cli` and the SENĆOŦEN model, makes it actually possible to type the name of this conference on a regular old ANSI keyboard! 👌
=> [LMLayer] Trie model: Replace the prefix with the suggestion

common/predictive-text/worker/index.ts, web/testing/prediction-ui/index.html
A strange error has been arising in the Android app when swapping from a keyboard with no predictive model to a different one with a predictive model - in these cases, despite a single `postMessage` being sent to the LMLayer to load the model, the `LMLayerWorker` is receiving that message **twice**.  So far, this only happens within the Android app; no such errors occur in the 'native' web test page.  (The prediction-ui test page has been updated to match my attempts to repro the error there.)  This error triggers a detector in the Android app which then assumes that the keyboard has crashed and is in need of a reset, which is less-than-ideal _here_, but is otherwise reasonable.
Attempted workarounds:
* I can tell that it's not due to our use of a `Promise` polyfill.
* I tried moving the …
=> [LMLayer, Android] Adds workaround for Android duplicate load msg bug.

ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
for the language of the newly downloaded keyboard
I.e., You've just dowloaded a keyboard.  We get the list of models to choose from. It is an empty list. It used to crash. (Error or nil list wouldn't have)
=> [ios] fix crash when there  is no model to download

common/predictive-text/index.ts, common/predictive-text/message.d.ts, common/predictive-text/unit_tests/headless/worker-predict-dummy.js, common/predictive-text/unit_tests/headless/worker-predict-trie.js, common/predictive-text/unit_tests/headless/worker-predict-wordlist.js, common/predictive-text/worker/index.ts, common/predictive-text/worker/model-compositor.ts, common/predictive-text/worker/models/dummy-model.ts, common/predictive-text/worker/models/trie-model.ts, common/predictive-text/worker/models/wordlist-model.ts, common/predictive-text/worker/worker-interfaces.ts, web/source/text/outputTarget.ts, web/source/text/prediction/modelManager.ts, web/source/text/processor.ts
This PR implements the rest of #1802, adding a new middle layer to the LMLayer called the `ModelCompositor`.  This layer will allow the LMLayer to combine probabilities from KMW's fat-finger analysis code with those from the lexical model (once they are made available), allowing us to, for the first time, support predictive suggestions.
Of course, there are some pretty significant limitations at this stage:
- Corrections will only consider the most recently-typed keystroke as erroneous - it doesn't model correction for multiple typos at this time.
- The probability combination code doesn't yet consider the (hopefully) edge-case where two different keystrokes produce the same resulting output in a manner that allows merging their probability masses.
- The existing model templates were …
=> [LMLayer] The ModelCompositor

common/predictive-text/unit_tests/headless/worker-predict-trie.js
One test did not get updated to use the new predict() API, introduced in #1803. This cherrypicks the fix from #1805.
=> [LMLayer] Cherrypick test that did not use updated predict() API.

common/predictive-text/worker/models/trie-model.ts, developer/js/lexical-model-compiler/build-trie.ts
Previously, if the key function was unspecified, the LMLayer and compiler
would use DIFFERENT key functions, and hence nothing would match. Now they use
the same key function 👍
=> [LMLayer] Make default key function consistent in compiler and worker.

common/predictive-text/package-lock.json, common/predictive-text/package.json, common/predictive-text/unit_tests/in_browser/cases/test-config.js, common/predictive-text/unit_tests/in_browser/cases/top-level-lmlayer.js, common/predictive-text/unit_tests/in_browser/cases/worker-dummy-integration.js, common/predictive-text/unit_tests/in_browser/cases/worker-wordlist-integration.js, common/predictive-text/unit_tests/in_browser/cases/worker.js, common/predictive-text/unit_tests/in_browser/helpers.js, web/package-lock.json, web/package.json, web/unit_tests/cases/basics.js, web/unit_tests/cases/engine.js, web/unit_tests/cases/test_config.js
We're having enough issues lately with CI test stability that it's high time to fix our timeout settings and figure out why they aren't properly being handled.
In case this issue arises again in the future, I'm also adding 'canary tests' to Web and the LMLayer so that we'll quickly know when timeouts break.
=> Fixing BrowserStack CI test timeout configs

web/source/kmwembedded.ts, web/source/text/kbdInterface.ts
Looks like I forgot to handle certain parts of the embedded use case when making #1802 to integrate fat-finger processing.  This remedies the resulting issues.
=> [Android][iOS] Fix for embedded Mock-targetted processing

android/KMAPro/kMAPro/build.gradle, android/KMEA/app/build.gradle, oem/firstvoices/android/app/build.gradle
Instead of using system properties, we use environment variables. This has the added
benefit of being easily testable externally.
=> [Android] Fix gradle scripts for CI build using build.sh instead of gradle runner

windows/src/engine/keyman32/Keyman32.cpp
This relates to the crash in closing sumatrapdf referenced in #1723.
Fixes #1723.
=> [Windows] Keyman32/keyman64 should detach without cleanup on process termination

windows/src/desktop/history.md, windows/src/engine/keyman32/Keyman32.cpp
Fixes #1723. Stable cherry-pick for 11.0 from #1813.
=> [Windows] [11.0] Keyman32/keyman64 should detach without cleanup on process termination

windows/src/desktop/history.md, windows/src/desktop/kmshell/xml/keyman.xsl, windows/src/desktop/kmshell/xml/onlineupdate.xsl, windows/src/desktop/kmshell/xml/proxyconfiguration.xsl, windows/src/desktop/kmshell/xml/usage_keyboard.xsl, windows/src/desktop/kmshell/xml/vkhints.xsl, windows/src/desktop/kmshell/xml/welcome_fonts.xsl
Stable version of #1826. This fixes compatibility issues on some systems where IE runs in a legacy mode and results in errors such as reported at https://community.software.sil.org/t/object-doesnt-support-property-or-method-addeventlistener/2207
=> [Windows] [11.0] Add meta x-ua-compatible to all remaining XSL templates to avoid conflicts with system config of IE

windows/src/desktop/kmshell/xml/keyman.xsl, windows/src/desktop/kmshell/xml/onlineupdate.xsl, windows/src/desktop/kmshell/xml/proxyconfiguration.xsl, windows/src/desktop/kmshell/xml/usage_keyboard.xsl, windows/src/desktop/kmshell/xml/vkhints.xsl, windows/src/desktop/kmshell/xml/welcome_fonts.xsl
This fixes compatibility issues on some systems where IE runs in a legacy mode and results in errors such as reported at https://community.software.sil.org/t/object-doesnt-support-property-or-method-addeventlistener/2207
=> [Windows] Add meta x-ua-compatible to all remaining XSL templates

ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelPickerViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift
From Language Settings, clicking on the current model now launches the list of models instead of directly launching the Info view of the current model
we should always be able to remove a lexical model
LexicalModelPickerViewController can be used to view all LMs or just those for a language
In language settings, don't assume the current model is relevant to this language
remember the user's chosen currentLexicalModelID
if no preference, register the first one
=> [ios] UI lexical model list

mac/Keyman4MacIM/Keyman4MacIM/Info.plist, mac/Keyman4MacIM/Keyman4MacIM/InfoPlist.strings, mac/Keyman4MacIM/Podfile.lock
Replaces PR#1809 which had the wrong base. Darcy cherry picked my changes to mac-kbdl-error2. These fixes are for issue#1808 (client side).
The client side fix is to put just the version number in the API call.
=> [Mac] keyboard download page error

windows/src/desktop/kmshell/Makefile
This has no impact on the release build but ensures that the locale files are available during debug sessions.
=> [Windows] Ensure locale files are copied to bin folder during build

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ConfirmDialogFragment.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguagesSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/JSONUtils.java, android/KMEA/app/src/main/res/values/strings.xml, web/source/text/prediction/modelManager.ts
In the case that a user has two more more lexical models downloaded for the same language code, this PR allows proper management of their installation states.  Whenever the active model is changed, the previously-installed model will be de-installed automatically.  Afterward, the new model will be registered in the background and will be automatically activated once the Settings menus are closed.
This PR relies on #1836 at a minimum, though I've based it off of #1842 for ease of testing (and to facilitate a potential imminent demo).  The recent longpress PR's changes (#1844) also appear here since the longpress changes haven't yet been merged into the base.  (Basically - ignore KMKeyboard.java's changes.)
=> [Android] Lexical model swapping + management

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsFragment.java, android/KMAPro/kMAPro/src/main/res/values/strings.xml, android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageSettingsActivity.java
Following from #1857, this PR integrates its changes into the current version of the Android app.  This involves tracking new settings with `SharedPreferences` and some bug fixes necessary to make things work right.
Note that the "Always show banner" global option is not yet fully connected to anything, as Android currently lacks the resources needed to mirror iOS's image banner behavior.
=> [Android] Predict vs correct options

mac/Keyman4MacIM/Keyman4MacIM/KMInputController.m, mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h, mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m, mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/Categories/NSArray+Action.m, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMCompStore.h, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMCompStore.m, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.h, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMXFile.h, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMXFile.m
This addresses #1832 by implementing support for `if()`, `set()`, `reset()`, and `save()` on macOS. These now behave as expected and there is no more garbage output.
In order to support `reset()` and `save()`, I had to add another array of stores to `KMXFile` (with saved values) and implement `copyWithZone` on `KMCompStore`, so that it's easy to duplicate the initial array of stores.
=> [Mac] add support for if(), set(), reset(), save()

mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/Categories/NSArray+Action.m, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/Categories/NSString+XString.m, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m
This fixes two unrelated deadkey issues on macOS:
* Multiple deadkeys in a rule did not work, as in [019 - multiple deadkeys](https://github.com/keymanapp/keyman/blob/master/common/engine/keyboardprocessor/tests/unit/kmx/019%20-%20multiple%20deadkeys.kmn) cases "4" through "8". This was because `addAction` was skipping any deadkey actions following another deadkey action. I modified it to append in such cases.
* Keyboards with more than 9 deadkeys would fail when the 10th or higher deadkey was used. This was because the deadkey ID was being appended to the context buffer as a decimal string. Any ID above 9 therefore appended two characters, but the code reading the buffer expected only one. I fixed this by instead encoding it as a single UTF-16 character whose codepoint is the deadkey ID, …
=> [Mac] fix two deadkey issues

mac/Keyman4MacIM/Keyman4MacIM/KMInputController.m, mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m, mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
The current code for detecting keyboard commands in [KMInputMethodEventHandler.m](https://github.com/keymanapp/keyman/blob/master/mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m) checks `keyDown` events for `event.modifierFlags` to detect keyboard commands that can change the contextBuffer (command-A to change selection, etc.). 
I've found that command-key combinations never trigger `keyDown` events. This can cause the context buffer to be out of date. The solution I've found is to handle `flagsChanged` events, as in the low-level event tap. This patch does so and sets `contextOutOfDate` for `flagsChanged` events. 
It also correctly passes event flags to `CGEventTapCreate` (per Apple's documentation).
=> [Mac] fix out-of-date context buffer after keyboard commands

developer/js/tsconfig.json
This fixes a regression from #1861. It may not have been visible on developer machines because the build doesn't wipe dist/ by default; however build agents start with a clean tree when doing lexical model builds, so it fell over there.
=> [Developer] Include index.ts in tsconfig.json for Lexical Model compiler

common/predictive-text/package-lock.json, common/predictive-text/package.json, web/package-lock.json, web/package.json, web/source/kmwdom.ts, web/unit_tests/cases/attachmentAPI.js, web/unit_tests/test_utils.js
We've had a major jump in the number of detected vulnerabilities that Node's reporting, so even though they're all focused on the development/testing environment, it's probably wise to get them updated.
Most of the reports require semantic-version updates, so `dependabot` seems to prefer we handle those ourselves... hence this PR.
=> [Web, LMLayer] Dependency updates

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelPickerViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html, web/source/osk/bannerManager.ts
This PR aims to fix most of the current iOS banner instability issues.  That said, there's one I've yet to fully fix: when swapping the keyboard in-app, the banner never shows at first.  Simply rotating the device will fix this, though.  It appears that there's some strange order of events for keyboard loading within the app which is making a full solution difficult for this aspect.
Fortunately, that in-app issue is not reflected in the system keyboard, which appears to work flawlessly with the fix in place.
=> [iOS] Banner Repair

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #1880.
The code triggering the error was never meant to be merged into master; it was from work toward a now-postponed feature.  As such, we can safely remove it for now - the key is to remove any calls to `showSuggestionLongpress`.
Compare vs #1773 (Intended) and #1778 (unintended), as noted by #1844.  While #1844 fixed a more notable bug, it failed to notice that there were actually active hooks into the incomplete feature.
=> [Android] Comments out hooks for rotation suggestion.

common/predictive-text/unit_tests/in_browser/CI.conf.js, common/predictive-text/unit_tests/in_browser/browser-test.sh, common/predictive-text/unit_tests/in_browser/manual.conf.js
Both Firefox and Edge test runners are proving flaky, so disabling them at this time. Not removing refs from package.json, just disabling the runners in hope that stability improves.
It appears that both runners are not being maintained (no updates in 2 years) so this is a bit of a concern.
=> [LMLayer] Disable Firefox and Edge in unit tests

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
... sometimes it's just a matter of knowing where to look.
So a while back, I refactored the iOS app and the root of the system keyboard to also function in-app, as opposed to the scheme previously used.  It turns out at the time that I forgot one small detail - and that detail is part of why the banner hasn't been able to display in-app after a keyboard swap.
Note the old comment about that line there - _as system keyboard_.  We were doing this in-app too, which triggers a keyboard.html reset.  The problem is that the reloading process that occurs has a little issue with the order of events in which the OSK height won't be set after the banner is initialized, thus hiding the banner.
But we don't actually need to reload in-app, or even in the system keyboard, except for in one case.  The …
=> [iOS] Fixes the in-app banner issue.

android/KMAPro/kMAPro/build.gradle, android/history.md, web/package-lock.json
KitKat (4.4) is the first version that included Chrome as the inbuilt browser instead of Android Browser. As we no longer support Android Browser, we need to set the minimum supported version to KitKat.
=> [Android] Force KitKat as minimum supported version

common/predictive-text/worker/worker-interfaces.ts
As noted in feedback for #1869, we're currently missing documentation for some of the core functions.  This PR seeks to address those concerns... though I'm afraid it might be a bit wordy.
=> [LMLayer] Documents the methods of WorkerInternalModel

android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, web/package-lock.json
Fixes #1884. 
This is not reproducible on all devices, but on some devices it seems that Javascript functions are called even when the page hasn't finished loading. So this fix is multi-part:
1. If any Javascript call is made from the engine to the web frame before the page finishes loading, we cache it and issue it after the load completes.
2. The `WebView.onPageFinished` event occurs too soon after the page load, and script has not necessarily finished executing. This can cause the Javascript calls to fail. So we now issue `'pageLoaded'` event when the web page calls its own `window.onloaded` event, and only mark the page as ready then.
=> [Android] If the keyboard view is not ready, calling javascript functions will crash

ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift
Capitalize the heading for Keyboards and Language settings in LanguageSettingsViewController
=> [ios] Capitalize the heading for Keyboards and Language settings

developer/js/build.sh
Quick PR to add `./build.sh` to this directory, as is present in `common/predictive-text` and `web/source`. This is in order to keep consistent build instructions across different subdirectories in this repo and beyond.
This was adapted from `common/predictive-text/build.sh`.
=> [Developer] Add build.sh to developer/js

common/predictive-text/unit_tests/headless/worker-custom-punctuation.js, common/predictive-text/unit_tests/headless/worker-predict-trie.js, common/predictive-text/unit_tests/in_browser/json/future_suggestions/i_got_distracted_by_hazel.json, common/predictive-text/unit_tests/in_browser/resources/models/simple-dummy.js, common/predictive-text/worker/model-compositor.ts, common/predictive-text/worker/models/dummy-model.ts, common/predictive-text/worker/models/trie-model.ts, common/predictive-text/worker/worker-compiler-interfaces.d.ts, common/predictive-text/worker/worker-interfaces.ts, developer/js/index.ts, developer/js/lexical-model-compiler/lexical-model.ts, developer/js/tests/test-punctuation.ts, developer/js/tests/tsconfig.json, developer/js/tsconfig.json
This PR introduces a `punctuation` object, when defining models.
This allows model authors to specify what quotes will go around the "keep" option.
It also allows model authors to specify what, if anything, should be inserted after a word .
The defaults to both of these options work well for... pretty much just English.
Fixes #1883.
=> [LMLayer] Allow model authors to specify quotes for keep message, and what to insert after a word

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/KeyboardPickerViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/KeyboardSwitcherViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelPickerViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift
A first pass at a slimmed down keyboard picker launched from the globe icon.
I haven't tested the case where we call the KeyboardPickerViewController with true for shouldAddKeyboard (which immediately launched the add view). But that should still work as before. (See the minor change in Manager).
=> [ios] slimmed down keyboard picker

ios/keyman/Keyman/Keyman/MainViewController.swift
Fixes #1913.
Turns out the settings button simply didn't get added to the tablet navbar, while it had been added to the `dropdownItems` list.
=> [iOS] Settings menu tablet access

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
Fixes #1911. 
While this doesn't yet enact image settings for the in-app version of the banner or manage the "always show" option, this fixes the core layout issues that would make a terrible first impression.
Regarding the "Always show" option, it looks like the in-app and system keyboards are managed quite separately.  We may require a slight redesign to get that part working correctly - a small interface that can be passed into both versions of the keyboard would be useful, since we can't rely on the app's subclass for in-app keyboard use.
=> [iOS] Fixes banner display misalignments.

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
Fills in functionality missing from #1923.  As a result:
Fixes #1921.
This will automatically deactivate and deregister a newly-deleted lexical model if it is active.
=> [iOS] Deregisters deleted registered models.

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
1. Remove embedded frameworks from `KeymanEngine.framework` (these must be embedded at the parent app level).
2. Fix paths so that the build doesn't inadvertently create a `Framework` folder in  `KeymanEngine.framework` (which is invalid)
3. Add `Reachability.framework` to list of frameworks which Carthage must copy and thin (remove x86_x64, i386).
See https://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr for some additional background on points 1 and 2 above.
=> [ios] Fix validation issues in build

android/history.md, web/source/resources/osk/kmwosk.css
Looks like a `vertical-align` got missed in some of the recent CSS work; the other permutations all had that line, which fixes the Android tablet issue.
Fixes #1908.
=> [Android] Suggestion text misalignment on tablets

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/GetStartedActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsFragment.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SystemIMESettings.java, android/KMAPro/kMAPro/src/main/res/layout/get_started_list_layout.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguagesSettingsActivity.java, android/history.md
Addresses the following concerns from #1904:
> 1. [Settings] Back from Settings/Installed Languages/Installed Language takes you to Settings instead of Settings/Installed Languages
> 3. [Get Started] The "Show Get Started" checkbox is only touchable on the checkbox, not the label, unlike the items above it
> 6. Default keyboard and Enable System Keyboard should really be available from Settings
=> [Android] Settings UI enhancement

web/history.md, web/source/osk/visualKeyboard.ts
Fixes the lack of spacebar captions in KMW 12.0.  Turns out that the split of kmwosk.ts into two separate classes and files missed a small detail that caused this.
Apparently `#text` elements don't play nice with CSS or `.innerHTML` - who knew?
=> [Web] Spacebar captioning fix

windows/src/developer/TIKE/child/UfrmKeymanWizard.pas, windows/src/developer/TIKE/main/UfrmMessages.pas, windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectFile.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.kmnProjectFileUI.pas, windows/src/developer/kmcomp/main.pas
Fixes #1919.
Note that the fix is in two places in kmcomp because there is a legacy pathway for the compiler that is outside the scope of this PR to refactor.
=> [Developer] Prevent keyboard files with many warnings clobbering build reports by stopping reports after 100 messages

developer/js/lexical-model-compiler/build-trie.ts, developer/js/tests/test-parse-wordlist.ts
I've added documentation that the byte-order mark is a-okay at the beginning of a word list TSV file. I wrote the test first, and was surprised that it passed already without me writing any code.
It turns out that `String.prototype.trim()` removes the BOM, a.ka. U+FEFF from either side of a string. This is used to trim whitespace when parsing a line. Check out the polyfill!
> ```javascript
> if (!String.prototype.trim) {
>  String.prototype.trim = function () {
>    return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g, '');
>  };
> }
> ```
>
> Source: [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim#Polyfill)
**EDIT**: I explicitly remove the BOM from the beginning of each line anyway!
Closes #1916.
=> [Developer] Update documentation on UTF-8 BOM handling; write test.

ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/KeyboardPickerViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift, ios/history.md
Fixes #1948.
Fixes #1949.
This removes swipe-deletion for keyboards from the old picker (currently only accessible via "Get Started") and moves it to the language-specific keyboard management menu.
There may be a bit of refinement needed with regard to detecting the default keyboard.
=> [iOS] Slide-deletion for keyboards via Settings menu

web/history.md, web/source/text/prediction/modelManager.ts
Fixes #1946.
Also fixes a few other minor related bugs discovered when testing the change; proactive integration testing saved the day there.
=> [Web] "Enable Predictions" as sole factor in for activating predictive banner

ios/engine/KMEI/KeymanEngine/Classes/Settings/SettingsViewController.swift
SettingsViewController now reloads table data in loadUserLanguages so deletion or addition shows right away when we come back to it.
Fixes #1952
=> [ios] reload table data so deletion or addition shows immediately

ios/engine/KMEI/KeymanEngine/Classes/Settings/SettingsViewController.swift, ios/history.md, ios/keyman/Keyman/Keyman/GetStartedViewController/GetStartedViewController.swift
Fixes #1935.
Somehow the Get Started menu's settings handling got broken with some of the recent Settings UI work; this PR should correct that.
=> Fixes iOS Get Started

developer/js/package.json, developer/js/tests/helpers/index.ts, developer/js/tests/test-compile-trie.ts, developer/js/tests/test-parse-wordlist.ts, developer/js/tests/test-punctuation.ts
This addresses some todos in `developer/js`; namely, the tests `eval` the model source code, but apart from checking for the absence of a syntax error, they didn't assert much. Through some effort, we can now:
1. compile model source code in the tests
2. determine the name of the constructor of the last model instantiated (i.e., `new models.SomeModel()` is `SomeModel`).
3. Actually figure out what the compiled code passed to `LMLayerWorker.loadModel()`.
Assertions are a little bit more assert-y now!
**EDIT**: Also, I added a helper that returns the path to fixtures!
=> [Developer] Better compilation assertions

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SplashScreenActivity.java, android/KMAPro/kMAPro/src/main/res/layout/activity_splash_screen.xml, android/KMAPro/kMAPro/src/main/res/values/strings.xml, android/KMAPro/kMAPro/src/main/res/values/styles.xml, android/history.md
In #1511, it was decided to avoid a startup delay and not display version/copyright info on the splash screen. The current timeout of 0ms doesn't work, as the splash screen still flickers with version/copyright text.
This addresses #1964 by blanking the version and copyright text fields.
=> [Android] Disable version and copyright text from flashing on splash screen

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageDetailViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelPickerViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/ResourceDownloadStatusToolbar.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift
Yeah, I know.  It's technically an enhancement rather than a bug fix.  This is an extracted part of my current work toward fixing the following issues:
* #1967
* #1968 
* Eventually, #1975
I realized that this part was very reasonable to `git rebase -i` out of everything else.  Since smaller, segmented code reviews are far easier to do, I figured this would be wise.
So, what brought this 'enhancement' about?  All of the keyboard updating code tends to generate notifications that display things in a similar manner to the newly refactored code.  Since we have yet to fully complete lexical model updating, this will only become worse as as that's completed.  Tracking all of the random sites of UI code was creating a lot of unnecessary mental overhead and slowing my progress.
This PR seeks to …
=> [iOS] Settings notification bar refactor/prep

ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageDetailViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift
Fixes regressions related to mistakes in merging other recent PRs with #1991's work.
The language-specific keyboard list view was locking up; this restores it.
=> [iOS] Language-specific keyboard download regression fix.

developer/js/source/index.ts, developer/js/source/lexical-model-compiler/lexical-model.ts, developer/js/tests/test-compile-trie.ts
Allows model authors to specify a word breaker as a function that returns an array of [`Span` objects](https://github.com/keymanapp/keyman/blob/master/common/predictive-text/worker/worker-compiler-interfaces.d.ts#L28-L43).
=> [Developer] Add Word Breaking API

developer/js/source/index.ts, developer/js/source/lexical-model-compiler/lexical-model.ts, developer/js/tests/fixtures/example.qaa.sencoten/example.qaa.sencoten.model.ts, developer/js/tests/helpers/index.ts, developer/js/tests/test-compile-model.ts, developer/js/tests/test-compile-trie.ts
This changes the name of the `wordBreaking` model specification property to `wordBreaker`. `wordBreaking` is still kept so nothing in the lexical-models repo breaks (😏). I also added documentation for the `wordBreak` property inline.
Fixes #2012.
After keymanapp/lexical-models#54 is merged, we can remove all mention of `wordBreaking` altogether!
=> [Developer] Use the term "wordBreaker" instead of "wordBreaking"

ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift
Turns out that the default keyboard within the iOS app is meant to be deletable, just not when there aren't enough keyboards.  A small mistake in the info view's initialization meant that the "enough keyboards" check would fail, blocking its deletion.  (See `KeyboardInfoViewController.canDeleteKeyboard` - it's the property's final check.)
This remedies the issue and also changes the recently relocated slide-deletion functionality (#1969) to mirror the correct logic.
=> [iOS] Allows deletion of default keyboard

android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMEA/app/src/main/AndroidManifest.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguagesSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelInfoActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/LexicalModelPackageProcessor.java, android/KMEA/app/src/main/res/xml/file_paths.xml, android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/LexicalModelPackageProcessorTest.java, android/history.md
Fixes #2006 
The keyboard and model info pages were inconsistent in what they displayed, resulting in buggy behavior with "uninstall".
* version
* help link (<-- sometimes this entry not generated if help link didn't exist)
* uninstall
This PR makes it consistent so "Help" field is always displayed, but is either:
* disabled
* has right arrow signifying help link available (either keyman.com/keyboards or local welcome.htm)
FileProvider also moved from KMAPro to KMEA for the info pages to display local welcome.htm files.
=> [Android] Fix keyboard and model info pages

web/source/resources/osk/kmwosk.css
Fixes #1909.
Turns out that some versions of Android and/or Chrome were ignoring part of KMW's CSS due to an extra `f` in the color spec:
The warning indicator on the `color: #ffff` line basically indicated that it was rejected because it wasn't a proper color spec with either 3 or 6 hex digits.
=> [Web] Fixes CSS issue affecting some Android devices

oem/firstvoices/keyboards.csv
Right now, the FV Keyboards app does not support having two languages with the same keyboard. The Canadian Multilingual keyboard is a very good alternative for French because it is optimised for it anyway.
Support for multiple languages using the same base keyboard should be available when the app includes BCP 47 codes in keyboards.csv, but this isn't really required for 12.0 stable, as far as I can tell.
=> [Android] [iOS] Use Canadian Multilingual keyboard for French for FV Keyboards, rather than Eurolatin

developer/js/source/lexical-model-compiler/lexical-model-compiler.ts, developer/js/source/lexical-model-compiler/lexical-model.ts
As noted in #2014, we've moved from using a `wordBreaking` parameter to `wordBreaker` instead.  Now that the appropriate changes to mirror this have been carried out with https://github.com/keymanapp/lexical-models/pull/54, it's time to finalize removal of the old property.
While moving the `ClassBasedWordBreaker` to the newer parameter at this time may be ideal, this results in less code changes for now.  There's also the pending work on #2048 - this PR will trust that one to finalize any decisions regarding this potential argument type.
=> [Developer] Removes final references to old wordBreaking property

web/history.md, web/source/osk/defaultLayouts.ts, web/source/osk/visualKeyboard.ts, web/source/utils/version.ts, web/unit_tests/cases/versions.js
Fixes #1460.
As determined in conversation in other channels, we've decided to use the keyboard `KVER` property to do a version check, allowing us to preserve the original behavior for legacy keyboards while allowing those compiled with Developer 12.0+ to no longer auto-provide default keycaps.
=> [Web] Removes default key cap text behavior

web/source/kmwdom.ts
Turns out that a bug went unnoticed in #2045 that breaks KMW tests.  It wasn't directly caused, either - there was an interesting chain of events causing the problem.
As it turns out, for quite a while now the testing-oriented `shutdown` method has inadvertently been calling `setKeyboard` and such *during* the shutdown process - in particular, when element attachment is removed by the `disableInputElement` method.  During `shutdown`, there should be no active keyboard - and the new version checks the erroneous calls trigger result in the visible errors.
After a bit of investigation... there's no reason for `disableInputElement` to call `setKeyboard` here.  The keyboard's about to be hidden, and there are other handlers that will automatically set the keyboard appropriately when focusing …
=> [Web] Test bug squashing

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
This fixes a regression that was missed from the combination of #2029 and #2053 
I missed updating the FileProvider `authority` in the MainActivity.
=> [Android] Fix missing FileProvider authority for MainActivity

windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectFiles.pas, windows/src/developer/history.md, windows/src/global/delphi/general/Keyman.System.CanonicalLanguageCodeUtils.pas
Fixes #2046.
Note: .model_info change in ProjectFiles.pas is to allow Developer to load .model_info files by default, rather than opening in external editor, which I encountered when testing.
=> [Developer] Don't overwrite a BCP 47 code that the user has chosen when writing project templates.

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardPickerAdapter.java, android/history.md
Fixes crashlytics [issue](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/ae3e98fa5c6cd16e57f3140cc1949fd6?time=last-seven-days&sessionId=5D72B3F3033400016E434EDE02CAAA49_DNE_0_v2) where a keyboard map didn't contain `KMKey_CustomKeyboard`.
=> [Android] Add check for `KMKey_CustomKeyboard`

web/history.md, web/source/dom/uiTouchHandlerBase.ts, web/source/resources/osk/kmwosk.css
Fixes #1980.
Due to some of the requirements of the OSK, we can't rely upon native scroll handling for `overflow-x` elements, but we can still apply that styling toward the same goals if we just implement the scroll behavior ourselves.
I've tried to aim for a "natural" feel with the scroll implementation and its interactions with our normal banner-bar event handling.  **Please** live-test these changes and give feedback on the resulting UX.  I advise following the repro instructions in #1980 when testing; a great testing model is provided there.
---
Expected behaviors:
If the user's touch started within an "overflowing" suggestion:
- subsequent `touchmove` events will only scroll the suggestion
- if the user scrolls the suggestion significantly, moving a total of over 10 units, releasing …
=> [Web] Suggestion banner overflow-x support

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/history.md
Fixes #2072.
Turns out there was an interesting unexpected interaction that occurred on the swap to using `viewWillLayoutSubviews` - the function is unexpectedly called whenever users interact with the WebView via touch.  This, in turn, was triggering keyboard resize requests that replaced the keyboard elements _during_ keystroke processing, causing loss of important data for necessary predictive calculations that in turn broke the context that was being sent to the LMLayer.
"Fun" stuff.  Fortunately, it's somewhat easy to filter out the cases; I've made sure to document the reasoning in the critical locations so that we don't accidentally re-introduce the bug later.
=> [iOS] Fixes iOS predictive banner due to key-distribution calc breakage

developer/js/source/lexical-model-compiler/lexical-model-compiler.ts, developer/js/source/lexical-model-compiler/lexical-model.ts
This removes the undocumented, and unimplemented class-based word breaker. Less code to maintain, at least for now!
Note: if we want to continue with #2048, simply revert this pull request:
git revert 65a0e9d
=> [Developer] Remove class based word breaker

web/source/dom/uiTouchHandlerBase.ts, web/source/osk/visualKeyboard.ts
Fixes #1733.
As best as I can tell, the original check simply neglected to compare the JS instances, preferring the id instead.
The `visualKeyboard.ts` edit is the important one, but the code in `uiTouchHandlerBase.ts` is an abstraction that will eventually replace `visualKeyboard.ts`'s code.  (At present, it only backs the predictive banner, but it was designed to back both.)
=> [Web] Highlighting checks key instance, not key id

windows/src/developer/history.md, windows/src/developer/kmconvert/Keyman.Developer.System.ProjectTemplate.pas
Fixes #2080.
The primary problem here is that the canonicalization process depends on alltags.txt, and only allows tags in that list. This overrides the wishes of the keyboard developer, and in some cases, such as `hre`, gives us a code which is too descriptive.
=> [Developer] Disable canonicalization when building keyboard and model projects from template because it's inadequate.

windows/src/global/delphi/packages/Keyman.System.PackageInfoRefreshKeyboards.pas
Fixes #2081.
This issue would typically only surface if the target .js file did not exist, but then in some circumstances the package source file would contain a spurious `<Keyboard>` entry.
To reproduce:
1. Create a new model from template.
2. Open the package file, switch to source tab.
3. You'll see a blank `<Keyboard>` entry listed under `<Keyboards>`. This should not be present.
=> [Developer] Prevent package metadata preprocessor from treating .model.js files as keyboard files when they don't exist.

windows/src/buildtools/help-keyman-com.sh
This will help prevent errors where help.keyman.com is updated while a build is in progress, for example https://build.palaso.org/viewLog.html?buildId=162936&buildTypeId=KeymanDesktop_Beta&tab=buildLog
Changes easier to see if you use the cog to select 'ignore whitespace'
=> [Windows] Reduce CI failures by ensuring help.keyman.com is locally up-to-date before pushing

web/source/text/kbdInterface.ts
This resolves casing issues for legacy API as sometimes referenced within our legacy CJK keyboards.
=> [Web] Legacy API casing fixes

web/history.md, web/source/text/processor.ts
Turns out that there's an interesting difference in Firefox for Windows vs for Mac and Linux - the existence of `window.event`, which was a key part of our keymap-checking code.
Firefox's keycodes are the same for `K_EQUAL` on all platforms; the issue was that the keymap-check was failing.
=> [Web] Updates Firefox-check for keymapping.

ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift
Mirroring an enhancement in #2119 for Android, this PR's changes hide the "Enable corrections" toggle when manipulating it is not a valid option instead of leaving it disabled but visible.
Predictions enabled:
Predictions disabled:
=> [iOS] Disabled predictions - settings UI enhancement

android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageSettingsActivity.java, android/KMEA/app/src/main/res/drawable/textview_item.xml, android/KMEA/app/src/main/res/layout/list_row_layout4.xml, android/history.md
This mirrors the iOS PR #2098 so the user can't toggle corrections when predictions are disabled.
When predictions toggle is set
* Enables corrections toggle (doesn't change the value)
* Makes corrections toggle visible
* Enables corrections text view
When predictions toggle is not set
* Disables corrections toggle (doesn't change the value)
* Hides the corrections toggle
* Disables corrections text view
(screenshots updated from review comments)
**Corrections toggle disabled (because predictions toggle disabled)**
**Corrections toggle enabled (because predictions toggle enabled)**
=> [Android] Disables correct toggle when predict disabled

windows/src/developer/history.md, windows/src/developer/inst/kmdev.wxs
=> [Developer] Icon indices in kmdev.wxs were incorrect for tike.exe after removal of legacy .kct and .kpp icons.

windows/src/developer/TIKE/Tike.dpr
Fixes #2040.
This weird issue arises due to some complex interactions in ownership chains for windows between Delphi and Chromium as implemented in CEF4Delphi. Changing the MainFormOnTaskbar property addresses the issue and does not appear to introduce any side-effects.
=> [Developer] Modal dialogs could appear behind the main form on Windows 7.

windows/src/developer/TIKE/web/UmodWebHttpServer.pas, windows/src/developer/TIKE/xml/kmw/index.html, windows/src/developer/TIKE/xml/kmw/packages.html, windows/src/developer/TIKE/xml/kmw/test.css
Fixes #1771. New look.
Keyboard test view, mobile mode:
Keyboard test view, desktop mode:
Package install view:
=> [Developer] Remove legacy 'Install keyboard' link in web test and cleanup look somewhat.

windows/src/developer/TIKE/main/UfrmHelp.pas, windows/src/developer/TIKE/xml/help/contexthelp.xml, windows/src/developer/TIKE/xml/help/help.xsl
Fixes #2089.
Fixes #2130.
Additional content work is in #2131. I have not attempted to do a full cleanup of the context help, just clean up the infrastructure to make it easier to do so later. There is a bit of a challenge in matching up the online help content with this context help; ideally we would automate it and have a (unit) test to ensure that all forms + controls have corresponding documentation, and a build step to generate one set of help from the other (to keep the content DRY). Anyone want to take that on? :-)
=> [Developer] Fix some of the issues with Context Help, and address one specific topic - touch layout editor.

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, web/source/osk/visualKeyboard.ts, web/source/utils/version.ts
This handles two things:
1. It's possible to instantiate a `VisualKeyboard` instance without an `activeKeyboard`.  KMW is currently set to provide a default interactive OSK on mobile devices when no keyboards are available, since something must be available to interact with the touch-alias elements.  The KMW edits handle this case.
2. The `loadJavascript` function doesn't wait for the page to actually load before executing the first JS command after page load, as the `.javascriptAfterLoad` array does not include the `loadURL` call that resets the page.  Fortunately, the `pageLoaded` event handler already calls `callJavascriptAfterLoad`, so we can simply condition on `this.keyboardSet`, which is set at the end of that handler.
=> [Android] Improves keyboard swap stability

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/history.md
1. Fixes crashlytics issue in KMTextView of a [ClassCastException](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5c48b419f8b88c2963468341?time=last-seven-days&sessionId=5D8A6E990027000120BCBEDF388131A9_DNE_0_v2) being thrown.
This follows the pattern of getting `AppCompatActivity` from the context as done in `showKeyboard()` l. 260
```
private void showKeyboard() {
AppCompatActivity activity = (AppCompatActivity)context;
Window mainWindow = activity.getWindow();
```
2. Fixes out of bounds [crash](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/164399637b92bc6efe61f84f7fc2523c?time=last-seven-days&sessionId=5D88C9C303BA000134F638CB49122030_DNE_0_v2) in …
=> [Android] Fix two crashes reported in Crashyltics

android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageListActivity.java, android/history.md
This fixes the numerous crashes reported in Crashlytics in [LanguageListActivity](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/1f8ec181433fccb0f7f135f5737d53e2?time=last-seven-days&sessionId=5D8BBF2303090001482B99A421C3910B_DNE_0_v2)
where the user attempts to download a keyboard, but the catalog info doesn't exist.
Steps to replicate scenario:
1. Clean install of app
2. Close the "Get Started" page and let the in-app load the English model
3. Re-open "Get Started" and click "Add a keyboard for your language"
4. Cancel the dialog 
5. The resulting Language screen has default English keyboard entries, but no catalog info backing it.
6. Now, attempting to click on them gives a notification at the bottom
=> [Android] Guard against condition when `language.keyboards` entries don't exist

developer/js/build.sh, windows/src/developer/inst/copydev.in
Fixes #2124.
Took the design decision to append -tier to the version number for npm packages. Happy to be corrected.
Windows version numbers have 4 components; the script will trim any more than 3 components as we only use the first three anyway.
=> [Developer] Set the package version when building kmlmx during Developer build.

windows/src/developer/TIKE/main/UfrmHelp.pas, windows/src/developer/history.md
Fixes #2144.
This arose because around the removal of the splash screen which changed the timing of the display of the help. Moving the instantiation of the web control to FormShown avoids the window being recreated and other side-effects.
=> [Developer] Context help screen was not showing on startup in 12.0.39 (regression).

windows/src/developer/history.md, windows/src/engine/keyman/UfrmKeymanMenu.pas
Fixes #2146.
This fixes a crash scenario for what is technically an unsupported configuration -- running different versions of Desktop and Developer. It's unsupported because they both use the same engine and we do not currently have a way to have multiple versions of the engine installed, so there may be api conflicts.
In this case, the problem was that a new file, menutitle.png, was expected by Keyman Engine 12, but was missing for Keyman Desktop. The mitigation is to only load the file if it exists, which leaves a blank bar in the Keyman menu, which is an acceptable compromise.
Long term, this issue will be resolved in a more elegant way as Keyman Developer will not use Keyman Engine directly (used only for debugging keyboards) as it will instead embed Keyman Core for debugging.
=> [Windows] If Keyman Desktop 11 and Keyman Developer 12 are installed together, Keyman Desktop will crash on startup.

windows/src/engine/keyman/main.pas, windows/src/engine/kmcomapi/util/keymanautoobject.pas
Fixes #2147.
This may fix #2147. Despite having many reports, I have never been able to reproduce this on my computer. It appears to be related to destruction order because it looks like during Keyman shutdown, Keyman is trying to load keyman32.dll. That in itself is strange; in my debugging keyman32.dll is always already loaded at this point in the shutdown process.
Notes:
* It's not an upgrade scenario because it occurs on latest release versions of Keyman.
* It occurs across 10.0, 11.0 and 12.0
* The error is buried somewhere in C++ code called from the COM layer, which means our diagnostic call stacks don't show the detail we need.
* I'm enabling reporting of call stacks for kmcomapi. That may help trace the issue with additional .errlog files included in the attached .tsi, even if it …
=> [Windows] Change destruction order for Keyman to avoid error reloading.

common/predictive-text/build.sh, developer/js/build.sh, windows/src/test/unit-tests/Makefile
The `npm link` command must run directly before `npm install` to succeed. This PR moves this step from the `build` phase to the `install` phase, to prevent build failures.
=> [LMLayer] Fix linking step

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/history.md
Fixes #2166 by adding wrappers to missing API methods:
* addKeyboardDownloadEventListener
* getVersion
* removeKeyboardDownloadEventListener
Ignoring `setKeymanLicense`. (Shouldn't it be deprecated?)
=> [Android] Add wrappers to missing API methods

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/LanguageResource.swift
While working on https://github.com/keymanapp/help.keyman.com/pull/58, we became aware that a few published API endpoints were missing due to refactoring in v11 and the work toward v12.  This PR recreates those originally-published endpoints as closely as possible, along with a few closely-paralleling new endpoints for lexical models.
In the long term, we'll want a more complete API overhaul, but that's been placed further down the line on our road map.
=> [iOS] KMEI:  Reinstates pre-refactor API endpoints w helpers

windows/src/developer/TIKE/xml/layoutbuilder/builder.css, windows/src/developer/TIKE/xml/layoutbuilder/builder.js, windows/src/developer/history.md
Fixes #1890.
Default padding in the designer was 5 units. It is now 15 units, which matches the left padding in KeymanWeb. This means that the designer key layout matches what you see in KeymanWeb, more precisely.
Changing the default padding has required adjusting the position of the key size hints slightly, hence changes to the CSS. This probably means that there are some embedded default padding constants that affect the overall layout as well...
=> [Developer] Make default padding in touch layout editor match default padding in KeymanWeb.

web/source/osk/activeLayout.ts, web/source/osk/visualKeyboard.ts
Relates to #1890.
This does not necessarily need to be merged for beta. I did the work while investigating the issue and it looks like a minor improvement to the rendering. However, there is some change to the functionality with the reduction of rounding, ~~and a difference with the right margin value in one place~~.
I'm opening this PR for comment and consideration by the team and am not worried if it doesn't land just yet.
UPDATE:
After re-review and a minor tweak, I think it is now low-risk and good for beta. I like constants :)  I am aware that this doesn't touch the vertical padding constants ... a task for another day -- this is still an improvement.
=> [Web] Refactor magic values for key width, padding and margin into constants, and reduce over-enthusiastic rounding efforts

developer/js/README.md
Similar to #2178, this changes the documentation for [@keymanapp/lexical-model-compiler](https://www.npmjs.com/package/@keymanapp/lexical-model-compiler) to make it more accessible to users, and not the Keyman core team!
=> [Developer] Make lexical-model-compiler README slightly more user-centric.

linux/history.md, linux/ibus-keyman/debian/watch, linux/ibus-kmfl/debian/watch, linux/keyman-config/debian/watch, linux/kmflcomp/debian/watch, linux/libkmfl/debian/watch
The current Debian watch files matches  `beta|stable` (in order). Trying to run launchpad.sh means the latest beta build 12.0.18 matches as the the latest build when it should be 12.0.51 stable
=> [Linux] Change watch to only follow stable

android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/LexicalModelPackageProcessor.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/LexicalModelPackageProcessorTest.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/PackageProcessorTest.java, android/history.md
Fixes #2190
For lexical model packages, use the package version for the lexical model version.
Keyboard packages will continue to use the keyboard versions in kmp.json.
Screenshot showing the installed lexical model
=> [Android] Use lexical model package version for lexical model version

web/source/kmwdomevents.ts, web/source/kmwkeyboards.ts, web/source/text/kbdInterface.ts, web/source/text/processor.ts
While examining the old CJK picker keyboards towards updating their code, I noticed that the `notifyKeyboard` function, which connects to selectively-defined `KNS` functions within compiled keyboards, hadn't been properly updated to reflect the new 12.0 abstraction provided by `outputTarget`s.  This broke part of the Japanese keyboard's functionality - the ability to swap between hirigana and katakana with the SHIFT key.
Fortunately, it's nothing too hard to fix.  I also relocated `notifyKeyboard` to kbdInterface.ts, which is a much more 'proper' home for the function - it _is_ a part of the keyboard interface, after all.
Best tested with the legacy Japanese keyboard on desktop form factors.
=> [Web] Updates notifyKeyboard and uses of KNS

windows/src/desktop/inst/keymandesktop.wxs, windows/src/desktop/setup/RunTools.pas
Fixes #2207.
Fixes #2074.
(#2074 is a little ambiguous but most likely the same issue)
This replaces #2212 as it addresses the root issue far more cleanly.
The one downside is that the msi is slightly less self-contained for upgrades from 7,8,9,10, but the reality is that ship sailed many moons ago. The major version upgrades up until 11.0 relied on setup for transferring data between registry keys anyway. So we haven't actually lost anything.
Going forward, this actually reduces our reliance on setup.exe as the .msi can do a major upgrade for any 11.0+ version without external transforms. This is a good thing :)
The one technology that I have struggled with more than anything else is Windows Installer. Years and years worth of struggle. I think the hardest part is having to guess the …
=> [Windows] Upgrades from 11.0 and 12.0 were losing installed keyboards and settings.

windows/src/Defines.mak, windows/src/README.md, windows/src/buildtools/delphiprojectmanager/Makefile, windows/src/buildtools/devtools/DevDelphiCompileWrapper.pas, windows/src/buildtools/devtools/DevDelphiStarterCompileWrapper.pas, windows/src/buildtools/devtools/DevIncludePaths.pas, windows/src/buildtools/devtools/DevInstallPackages.pas, windows/src/buildtools/devtools/Makefile, windows/src/buildtools/devtools/UfrmCompilerErrors.pas, windows/src/buildtools/mkver/Makefile, windows/src/buildtools/msbuild-wrapper.bat, windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas, windows/src/developer/TIKE/compile/ValidateKeyboardInfo.pas, windows/src/ext/mbcolor/mxs.inc, windows/src/global/delphi/comp/FixedTrackbar.pas, windows/src/global/delphi/general/JsonUtil.pas, windows/src/global/delphi/general/Keyman.System.RegExGroupHelperRSP19902.pas, windows/src/global/delphi/general/Keyman.System.UpdateCheckResponse.pas, windows/src/global/delphi/general/kpsfile.pas, windows/src/test/unit-tests/group-helper-rsp19902/Keyman.Test.RegExGroupHelperRSP19902Test.pas
This allows the build to work with either Delphi 10.2 or Delphi 10.3 by setting the DELPHI_VERSION variable. If not set, then assumes Delphi 10.3.
=> [Windows] Update build scripts, compiler conditionals, and address hints arising with move to Delphi 10.3.2

resources/git-hooks/commit-msg
Make commit-msg hook executable. Also use bash - Ubuntu has `dash`
linked as `/bin/sh` which doesn't support some of the features we use
in the hook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2262)
=> fix: commit-msg requires bash and +x

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java, android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/history.md
Fixes #2251 
On entering a hidden password field, disable the dictionary so the password won't appear as the left suggestion.
On entering a non-password field, re-enable the dictionary
=> fix: Temporarily disable dictionary when entering password field

android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/JSONUtils.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java, android/history.md
Cherrypick #2242 and fixes #2190 on master
=> [Android][Cherrypick] Also use the lexical model package version for generating Dataset

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java, android/KMAPro/kMAPro/src/main/res/layout/activity_package_installer.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/FileUtilsTest.java
Addresses #1855
Custom keyboard installtion on android shows welcome page before installation.
On other platforms before installation a readme.htm is shown and the welcome.htm is displayed after installation.
On android custom keyboard installation behaves the same as on other platforms.
After selection a Custom package the readme-file is shown
After finishing the installation the welcome-file is display
Goto keyboard details and show welcome.htm from info link
- add Readme-Page-Helper-Method to FileUtils
-  Change PackageAcitivity to show Readme before starting installation
- Change PackageAcitivity to show Welcome page after finishing installation
- Goto Settings/ Add Keyboard from Device
- Select a downloaded custom keyboard package
- Select a keyboard from the list
- See the readme …
=> feat[android]: change readme page handling for custom package install

web/source/dom/contentEditable.ts, web/source/dom/designIFrame.ts, web/source/dom/input.ts, web/source/dom/textarea.ts, web/source/dom/touchAlias.ts, web/source/text/kbdInterface.ts, web/source/text/outputTarget.ts, web/unit_tests/cases/element_interfaces.js
Fixes #2261.
This adds a check to context-deletion commands, ensuring that we never attempt to delete more characters than are actually in the context - something that can break context-management within the `OutputTarget` classes due to the implementation of `.kmwString` allowing negative parameters.
I've also added a bounds-check within the `OutputTarget`s themselves; these checks are relatively easy to unit-test, so I've added something for that.
=> [Web] Bounds-check on context deletion from keyboard rules

web/source/kmwdevice.ts, web/source/utils/version.ts
Fixes #2267.
This aims to provide a very directed fix for iOS user-agent spoofing as seen in its recently-released offerings.  By testing against specific versions of macOS, we establish a pattern that can be used to adjust device detection accordingly in future versions is the `TouchEvent` check becomes invalid.  Regarding that check itself... https://stackoverflow.com/questions/56578799/tell-ipados-from-macos-on-the-web
Noting the standard aspect ratio of iPad screens to be 4:3 (https://www.lifewire.com/what-is-ipads-screen-resolution-ips-display-1994325) and that iPhones have slimmer form factors, we rely on this ratio to detect the difference betwen iPhones and iPads.
---
Note that without any additional changes, this also fixes in-app and system keyboard behavior for the iOS app on …
=> fix(web): iOS-Safari user agent spoof detection

web/history.md, web/source/text/processor.ts
Fixes #2209.
OK, this one was a bit fun.
We had a similar error before with non-mnemonic layouts that was fixed, but I forgot about the "other" backspace handler in `defaultKeyOutput`.  Easy enough to fix... though it turns out that this was triggered in combination with another bug.  (It took two things going wrong to occur.)
In v12, `defaultKeyOutput` gained an extra purpose when compared to prior versions - it's now used to lookup mnemonic keystroke codes _in addition to_ handling default output.  The "disableDOM" bit indicates that it's functioning in "lookup" mode, so no change should happen to the DOM when `true`.
That "another bug"?  Try hitting the "Delete" key with the sil_ipa keyboard active on the current version of KeymanWeb - it outputs periods instead!  The code we use for …
=> fix(web): Fixes mnemonic code handling issues

windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
This issue arises only in keyboards with `store(&version) '10.0'`.
Fixes #2272.
Relates to #2261.
Follow the steps described in #2261 before and after this fix to see the improved behaviour. For the test keyboard, paste the following code:
```
store(&VERSION) '10.0'
store(&TARGETS) 'web'
begin Unicode > use(main)
group(main) using keys
store(consonants_ra_key)  [K_N] [K_B] [K_Y]
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF
nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)
```
=> fix(developer): nul in context caused incorrect deletion for 10.0 keyboards

windows/src/developer/TIKE/xml/layoutbuilder/builder.js
Fixes #2256.
This one can be a little tricky to reproduce. Recommend trying these steps in 12.0.52 version to reproduce the error before testing the fix.
1. Create a touch layout with `phone` and `tablet` platforms. Ensure the first platform is selected.
2. Then, go to code view, and delete the entire first platform block in the JSON file.
3. Switch back to design view. The app should no longer crash; the view will be a little funny, because no presentation is selected, but that's acceptable (just select a presentation to resolve).
=> fix(developer): crash when deleting selected platform in code view

web/source/osk/oskManager.ts
Fixes #2289.
The cause:  a tale as old as Javascript-time. (`this` handling in events)
Note that the combo doesn't seem to work on Macs, as CTRL+click usually launches a context menu, blocking the hotkey from being processed properly.  That's probably a conversation for later, though.
=> fix(web):  Fixes bug in version hotkey combo

android/KMAPro/build.sh, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebBrowserActivity.java, android/KMEA/app/build.gradle, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageListActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudCatalogDownloadTask.java, android/KMEA/build.sh, android/history.md
Follow-on to #2279 
Linting apparently was only being done on release builds, so the master alpha build failed.
(I still don't understand why it wasn't an issue on the PR builds done on the same build agent)
This PR adds linting flag to the `./build.sh` scripts.
Also fixes these lint errors:
* Add `super.onActivityResult()`
* Fix `TAG` strings to be <= 23 characters
* Suppress `ResourceType` lint error (TODO to address when our SDK > 17)
* Remove unused `org.apache.commons:commons-text` (gave a packaging lint error)
Lint reports will now be generated in:
android/KMEA/app/build/reports/lint-results(-debug).html
android/KMAPro/kMAPro/build/reports/lint-results(-debug).html
1. Check the CI artifacts for the lint-result reports
2. Verify no errors in red
=> fix(Android, ci): Resolve linting errors

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
Fixes #2137
Keyboard switch using the keyboard picker in keyman seems to swaps the keyboard more than once.
@jahorton already analyzed that this behavior is caused by two separate calls to the embedded page's `setKeymanLanguage` function. 
The first one is the language switch and the second one a reload of keyboard when keyboardpicker is closed.
Keyboard switch using the keyboard picker swaps only once. 
Fixed the multiple call of `setKeymanLanguage` function.
- Remove the call  to the embedded page's `setKeymanLanguage` function in the original `switchKeyboard`-method of keyboardpicker.
The keyboardswitch is now executed in 2 phases: 
- first step only prepares the keyboard switch on android site.
- second step: reload the keyboard and execute `setKeymanLanguage` when closing the …
=> fix[android]: Fix UI problem during keyboard switch

ios/engine/KMEI/KeymanEngine/Classes/SubKeysView.swift
Fixes #2299.
This PR ensures that the popup keys are always displayed within the keyboard's area for the system keyboard.  It turns out there was no bounds-checking for the vertical position, so this implements some logic to handle this.
Accordingly, a bit of adaptive styling is necessary to ensure that the displayed popup keys "look right."  For comparison, an example that doesn't need to be constrained:
For the 'i' key, constrainment is needed because there are two rows of popup keys.  I've managed to implement a reasonable UI adjustment for this:
The base y-coordinate of the "extension" of the base key for the popups is located identically.  Should the base key ever be entirely hidden behind popup keys, no "extension nub" will be displayed.
The positioning of the popup menu will only …
=> fix(ios): System keyboard popup-key positioning confinement

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
Fixes #2260.
These changes ensure that the Swift side of the keyboard can provide the KMW side with an initial width, bypassing the need for the failing `window.orientation` check (which was used to produce said initial width).
=> fix(ios): Fixes bad initialization of system keyboard width

windows/src/engine/keyman/main.pas
Fixes #1680. This issue arose only on some systems where
permissions for Keyman registry keys were not being
set correctly.
=> fix(windows): Keyman was not working with Skype

windows/src/engine/keyman/UfrmKeyman7Main.pas, windows/src/engine/keyman/keyman.dpr, windows/src/engine/keyman32/K32_DBG.CPP, windows/src/engine/keyman32/Keyman32.cpp, windows/src/engine/keyman32/hookutils.cpp, windows/src/engine/keyman32/hotkeys.cpp, windows/src/engine/keyman32/hotkeys.h, windows/src/engine/keyman32/k32_dbg.cpp, windows/src/engine/keyman32/k32_globals.cpp, windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp, windows/src/engine/keyman32/keyboardoptions.cpp, windows/src/engine/keyman32/kmhook_callwndproc.cpp, windows/src/engine/keyman32/serialkeyeventclient.cpp, windows/src/global/delphi/general/klog.pas, windows/src/global/inc/keyman64.h
Fixes #2147.
This potentially addresses the issues reported in #2147 where Keyman
would crash due to a race condition as a critical section was not
deleted before attempting to recreate it.
Some logging has been added for debugging these issues.
Also fixes memory leaks and another race on startup relating to loading
the taskbar icon.
There are still some known memory leaks because DLL_THREAD_DETACH is
not called for all threads before keyman32.dll is unloaded, so those
threads don't get the opportunity to clean themsselves up. However, the
key danger with the csGlobals critical section has been addressed.
=> fix(windows): Keyman was crashing sporadically

linux/scripts/reconf.sh
This change allows to calculate the version number once at the
beginning and then skip the calculation when we create the source
packages for the various packages. This allows to set the version
number in Jenkins early on.
Also fix some whitespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2321)
=> chore(linux): Allow to skip calculation of version number

web/source/dom/contentEditable.ts, web/source/dom/designIFrame.ts, web/source/dom/input.ts, web/source/dom/textarea.ts, web/source/dom/touchAlias.ts, web/source/text/kbdInterface.ts, web/source/text/outputTarget.ts, web/unit_tests/cases/element_interfaces.js
A simple `git rebase -i` cherrypick of #2274.
=> cherry(web): Bounds-check on context deletion from keyboard rules

web/source/kmwdevice.ts, web/source/utils/version.ts
This is a cherrypick of #2268 for 12.0 stable.  As iOS 13.1 is already out and causing issues with Keyman on updated iPads, it's pretty important that we get this out soon.
Since we're early in the 13.0 development cycle, a simple `git rebase -i` was all that was needed for this cherrypick.
=> cherry(web): iOS-Safari user agent spoof detection

android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java, android/history.md
Fixes #2298
Sanitize the app version to `#.#.#` to match the API query spec
1. Load the PR test build
2. start Keyman
3. Go "Settings" --> "Languages" to bring up the language picker
4. Search for "Salish, Straits" / "SENĆOŦEN" keyboard and install
5. Return to language picker
6. Search for "SENĆOŦEN" / "SENĆOŦEN" keyboard and install (this is fv_sencoten version 9.1)
=> fix(android): Sanitize version for API query

.editorconfig, linux/scripts/.editorconfig, linux/scripts/reconf.sh
This allows IDEs to automatically pick up the preferred coding style and might help with a more consistent use of spaces/tabs for indentation. This might need some fine-tuning for certain files or platforms, but it is a start...
The motivation for this change is that I'm tired of telling VS Code every time I open this project to use spaces for the files I edit. There are other ways how this could be achieved, but an `.editorconfig` is a pretty standard way of achieving this across different machines, users and IDEs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2327)
=> chore(common): Add .editorconfig file

windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.dfm, windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.pas, windows/src/developer/TIKE/main/UframeTextEditor.pas
The focus code paths for Chromium frames (CEF4Delphi) were incorrect.
The return value for preventing focus on navigation events was
inverted, and then other code was attempting to work around this
inversion, wrongly. Fixed the root issue of the inverted test (it would
help if the parameter cefSetFocus was known as `Handled` rather than
`Result`!) and then the remaining code pathways became far simpler.
Fixes #2314.
=> fix(windows): focus is incorrect for CEF

windows/src/desktop/history.md, windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas
Cherry-pick of #2330.
If the On Screen Keyboard was closed when on a monitor other than the 
primary monitor, it would restore to the primary monitor in the top- left
corner instead of the previous location.
This fix allows the OSK to be restored to another monitor, but still avoids
positioning the window off screen if the monitor has been disconnected.
Fixes #2270.
=> fix(windows): OSK restores to wrong monitor 🍒

windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.dfm, windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.pas, windows/src/developer/TIKE/main/UframeTextEditor.pas, windows/src/developer/history.md
Cherry pick of #2331 for stable-12.0.
The focus code paths for Chromium frames (CEF4Delphi) were incorrect. The
return value for preventing focus on navigation events was inverted, and
then other code was attempting to work around this inversion, wrongly.
Fixed the root issue of the inverted test (it would help if the parameter
cefSetFocus was known as `Handled` rather than
`Result`!) and then the remaining code pathways became far simpler.
Fixes #2314.
=> fix(windows): focus is incorrect for CEF 🍒

windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas
The .keyboard_info merge of `platformSupport` would not always give the
right result, for .js keyboards. We have a certain lack of information
in the .js which makes it a little tricky to determine precisely what
the set of supported platforms are. Thus, if we find a .js within a
.kmp, we'll assume it supports mobile; if we find a .js by itself,
we'll assume it supports web. (Thus, a keyboard that builds a .js
is assumed to always support web -- but not necessarily mobile now).
Some keyboards that have incorrectly added a .js into a package, e.g.
sil_cipher_music, will be marked as supporting mobile even though they
don't. The correct fix here is to remove the .js from the package for
that keyboard.
Fixes #2199.
=> fix(developer): keyboard_info merge mobile wrong

windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas, windows/src/developer/history.md
Cherry-pick of #2334.
The .keyboard_info merge of `platformSupport` would not always give the 
right result, for .js keyboards. We have a certain lack of information in
the .js which makes it a little tricky to determine precisely what the set
of supported platforms are. Thus, if we find a .js within a
.kmp, we'll assume it supports mobile; if we find a .js by itself, we'll
assume it supports web. (Thus, a keyboard that builds a .js is assumed to
always support web -- but not necessarily mobile now).
Some keyboards that have incorrectly added a .js into a package, e.g. 
sil_cipher_music, will be marked as supporting mobile even though they 
don't. The correct fix here is to remove the .js from the package for that
keyboard.
=> fix(developer): keyboard_info merge mobile wrong 🍒

web/package-lock.json, web/package.json, web/source/kmwdevice.ts, web/source/kmwexthtml.ts, web/source/osk/visualKeyboard.ts, web/source/utils/version.ts
Fixes #2322.
Fixes #2328.
TypeScript has gotten a little more restrictive than before, causing the initialization style used for some function stubs to generate errors now.  On the other hand, it now properly defines `onselectstart` now, allowing for us to drop our crude manual definition from before.
=> [Web] Toolchain update + dev-resource compilation fix

web/source/osk/visualKeyboard.ts
Fixes #2311.
The `displayUnderlying` flag introduced in #1539 was somehow missed from
the 12.0 work. This PR restores the behaviour from 11.0 by adding the
relevant changes from #1539.
Tested in Chrome Emulator.
@makarasok
1. Create a basic keyboard project. Turn **on** 'display underlying layout characters' in the On-Screen editor.
2. Make sure that the 'display underlaying' switch is off for both Phone and Tablet in the Touch Layout editor.
3. Compile and test the keyboard in desktop configuration.  Make sure that the underlying characters **are** shown.
4. Test in phone and tablet configurations. Make sure that the underlying characters **are not** shown.
1. Create a basic keyboard project. Turn **off** 'display underlying layout characters' in the On-Screen editor.
2. Make sure that …
=> fix(web): displayUnderlying flag was ignored

android/KMEA/app/src/main/AndroidManifest.xml, android/history.md
On API level 19, the DownloadManager was throwing an exception because it needed WRITE_EXTERNAL_STORAGE permission to download the cloud catalog info.
Reference: https://developer.android.com/reference/android/app/DownloadManager.Request#setDestinationUri(android.net.Uri)
=> fix(android): Grant WRITE_EXTERNAL_STORAGE permission

windows/src/engine/keyman/UfrmKeyman7Main.pas, windows/src/engine/keyman/keyman.dproj, windows/src/engine/keyman32/appint/aiTIP.cpp, windows/src/engine/keyman32/globals.h, windows/src/engine/keyman32/hotkeys.h, windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp, windows/src/engine/keyman32/keybd_shift.cpp, windows/src/engine/keyman32/kmhook_callwndproc.cpp, windows/src/engine/keyman32/kmhook_keyboard.cpp, windows/src/engine/keyman32/selectkeyboard.cpp, windows/src/engine/keyman32/serialkeyeventserver.cpp, windows/src/global/delphi/general/DebugPaths.pas, windows/src/global/delphi/general/KeymanControlMessages.pas, windows/src/global/delphi/general/RegistryKeys.pas, windows/src/global/inc/keyman64.h, windows/src/global/inc/keymancontrol.h, windows/src/global/inc/registry.h
Fixes #364.
Hotkeys in Windows are currently implemented using RegisterHotkey.
However RegisterHotkey does not distinguish between left and right
modifier keys, which means that they override some keyboards' RAlt
combinations.
This feature reimplements hotkey support in the low level keyboard hook,
and adds a feature flag / debug flag Flag_UseRegisterHotkey to return
to the RegisterHotkey model if that is so needed.
I have made minimal refactoring changes to this code, although there
are certainly functions here which could be improved.
I have flagged a couple of potential future improvements with TODO.
I will not cherry-pick this to 12.0; it's a new feature that can wait for 13.0 release.
**note to reviewer**: Use 'ignore whitespace' to see code changes more clearly.
=> feat(windows): left-only hotkeys

web/unit_tests/CI.conf.js
So, turns out that Firefox tests on Mac have gone unstable recently, but at least we can reclaim Safari, which is a slightly more important test for the platform.
Also, BrowserStack insists on reporting Chrome and Android tests identically, so since there's no identifying distinction, we may as well just run the default Chrome tests and eliminate any confusion in the test log reports.
=> change(web): Updates unit test browser targets for CI

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/CharSequenceUtil.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/CharSequenceUtilTest.java, android/history.md
Fixes #2250
Cherrypick of #2281 for master
Due to a Chromium [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1024738) in the implementation of deleteSurroundingText, we need to save off the original context and re-insert characters that shouldn't have been deleted.
=> fix(android): Fix left-deletions

web/history.md, web/source/osk/visualKeyboard.ts
Fixes #2311.
Cherry-pick of #2353 for stable-12.0
The `displayUnderlying` flag introduced in #1539 was somehow missed from 
the 12.0 work. This PR restores the behaviour from 11.0 by adding the 
relevant changes from #1539.
Tested in Chrome Emulator.
=> fix(web): displayUnderlying flag was ignored 🍒

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/history.md
Follow-on to #2281
This fixes Crashlytics [issue](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/054f29f4c0601121ea1102c0eadf7cb6?time=last-seven-days&sessionId=5DDAD1AB0156000132ECCEAF30E92E2B_DNE_0_v2)
by adding additional checks for when `getTextBeforeCursor()` returns null context. The length in determining `newContext` was also fixed to handle the test scenario involving steps 5 below.
1. Load the apk
2. Install either the custom "[moo](https://darcywong00.github.io/examples/moo/moo.kmp)" keyboard or **xinaliq** from the cloud.
3. As a system keyboard, repeatedly hit backspace when the context is empty.
4. Verify keyboard doesn't crash
5. Enter a context of 6 emojis (s or w key), followed by p^p^ (p key 4 times)
6. …
=> [Android] Check getTextBeforeCursor() doesn't return null

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/history.md
Follow-on to #2376, cherrypick of #2377 for master
This fixes Crashlytics [issue](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/054f29f4c0601121ea1102c0eadf7cb6?time=last-seven-days&sessionId=5DDAD1AB0156000132ECCEAF30E92E2B_DNE_0_v2)
by adding additional checks for when `getTextBeforeCursor()` returns null context. The length in determining `newContext` was also fixed to handle the test scenario involving 6 emojis (SMP chars) followed by `p̂p̂`
=> [Android][Cherrypick] Check getTextBeforeCursor() doesn't return null

android/KMEA/app/src/main/assets/keyboard.html, common/predictive-text/index.ts, common/predictive-text/message.d.ts, common/predictive-text/package-lock.json, common/predictive-text/package.json, common/predictive-text/promise-store.ts, common/predictive-text/worker/index.ts, web/bulk_rendering/renderer_core.ts, web/package-lock.json, web/package.json, web/source/build.sh, web/source/dom/utils.ts, web/source/kmwbase.ts
This will need a 🍒-pick to the `master` branch.
Addresses #2323.
----
Everything's in a pretty "rough-draft" state, as I'm still working on a baseline compat fix that will also handle APIs below 23.
Among other things, referencing the JS `console` from the WebWorker was also generating errors that could crash KMW.
=> [Android] ES6 & API 19-23 compatibility changes

web/source/kmwdevice.ts, web/unit_tests/CI.conf.js, web/unit_tests/base.conf.js, web/unit_tests/cases/attachmentAPI.js, web/unit_tests/cases/basics.js, web/unit_tests/cases/element_interfaces.js, web/unit_tests/cases/touch_aliases.js, web/unit_tests/test.sh, web/unit_tests/test_init_check.js, web/unit_tests/test_utils.js
Fixes #2379.
Further addresses issues noted in #2371.
---
To help make our unit tests a bit more robust, I've modified the testing somewhat so that Karma reliably reports errors here when device detection fails.  There's a specific, targeted test for device detection now as well, to help highlight the underlying issue when it fails.
Note that commit https://github.com/keymanapp/keyman/pull/2381/commits/efe440c65908f2e6a650619a2f8a30c81e63176a is expected have a failure for the KMW build as a result; it has the new testing in place, but not the fix.  The resulting error logs are now more informative as a result.
=> fix(web): macOS Firefox detection/fire + test stability

developer/js/source/model-info-compiler/model-info-compiler.ts
Author email could be undefined, or the regex could fail to match. Either way, there would be a crash here with a bad error message. Now it shows an error message if the email is in an unexpected format (i.e., it doesn't match the regexp!), and it only merges the email address if it is present in the `.kps`.
Fixes #2370 
Fixes #2373
=> fix(developer): check if author email exists

android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtil.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/JSONUtils.java, android/history.md
This PR cherrypicks #2378 to master
This fixes a few issues involving the Cloud Repository
1. Add some null checking to prevent crashes
2. This addresses an issue where a custom .kmp package is installed (which currently associates the first language listed in kmp.json). Trying to install additional languages listed in the kmp.json failed because the package ID info wasn't being propagated.
=> [Android] Fix a few CloudRepository issues

developer/js/package-lock.json, developer/js/package.json, developer/js/source/jszip.d.ts, developer/js/source/lexical-model-compiler/stub.ts, developer/js/source/model-info-compiler/model-info-compiler.ts, developer/js/source/package-compiler/kmp-compiler.ts, developer/js/source/package-compiler/kps-file.ts, developer/js/source/util/util.ts, developer/js/tsconfig.json
I made sure `kmlmc`/`kmlmp`/`kmlmi` all type check under compiler options  `--noImplicitAny`, `--noImplicitThis`, `--alwaysStrict`, `--strictBindCallApply`, and `--strictFunctionTypes`. 
`--strictNullChecks`, `--strictPropertyInitialization` (which depends on the former) are simply too dificult to implement. Also, the typechecker is too dump to realize that an `if(foo === undefined) { process.exit()}` means that `foo` cannot be undefined after this block :/
Fixes #2387
=> [Developer] Enable stricter type checks

windows/src/desktop/history.md, windows/src/engine/keyman32/appint/aiWin2000Unicode.cpp, windows/src/engine/keyman32/kmprocess.cpp, windows/src/global/inc/Compiler.h
Fixes #2398.
When told to delete a surrogate pair, the engine would internally delete too much of the cached context, leaving the context out of sync with the text store.
The `BK_SUPP2` flag was a holdover from the days when Windows required two backspaces to delete a surrogate pair. Events with the flag were theoretically ignored but the code paths which needed to test for this were not 100% covered, so deleting the flag was the correct and simplest way to resolve the bug.
See https://community.software.sil.org/t/problem-with-some-input-sequences-in-indic-smp-scripts/2822/1 for original report.
=> fix(windows): smp characters could break context

windows/src/desktop/history.md, windows/src/engine/keyman32/appint/aiWin2000Unicode.cpp, windows/src/engine/keyman32/kmprocess.cpp, windows/src/global/inc/Compiler.h
Fixes #2398. Cherry-pick of #2399.
=> fix(windows): smp characters could break context 🍒

windows/src/developer/TIKE/xml/project/project.js
Fixes #2394. The show help checkbox was not working on
the Distribution tab of Project. Also tidies up, slightly,
the relevant js code with a new constant.
=> fix(developer): show help was not working

windows/src/developer/inst/Makefile, windows/src/developer/inst/copydev.in
CI needs to build the model compiler from an alternate path because the
production build from npm can have files not in the development build.
This was causing CI errors such as:
kmlmc.wxs(170) : error LGHT0103 : The system cannot find the file
'C:\...\node_modules\.bin\node.ps1'.
=> fix(developer): ci alternate installer path

windows/src/developer/inst/Makefile, windows/src/developer/inst/copydev.in
Cherry pick of #2407 to master.
CI needs to build the model compiler from an alternate path because the 
production build from npm can have files not in the development build.
This was causing CI errors such as:
kmlmc.wxs(170) : error LGHT0103 : The system cannot find the file
'C:\...\node_modules\.bin\node.ps1'.
=> fix(developer): ci alternate installer path 🍒

android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java, android/history.md
Starts to address #2367 
Adds a preference that tracks when an update notification for keyboard / lexical model ID is cancelled.
For 3 months, that notification won't appear again.
=> [Android] Add preference to ignore update notification

ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableLexicalModel.swift
Useful reference:  https://www.swiftbysundell.com/articles/customizing-codable-types-in-swift/
Since we had some issues with our Cloud API when language IDs weren't consistently lowercased, that's been changed for consistency with infrastructure (for keyboards).  Of course, users with language resources already installed may have local keyboards and/or lexical models with non-lowercased language IDs - this PR will prevent potential resulting language-code matching from being an issue.
Designed to address the same issues as #2404, just for iOS.
=> fix(ios): prevents lowercased API returns from causing mismatches

common/predictive-text/unit_tests/headless/default-word-breaker.js, common/predictive-text/unit_tests/in_browser/cases/worker-dummy-integration.js, common/predictive-text/unit_tests/in_browser/cases/worker-trie-integration.js, common/predictive-text/worker/models/trie-model.ts, common/predictive-text/worker/word_breaking/default-word-breaking/index.ts
Note:  we'll probably want to 🍒-pick this to stable once it's ready.
... so, it turns out that our "default" word breaker wasn't the actual default.  That honor goes to the "placeholder" wordbreaker... which probably should have been removed a while back.
That said, it turns out that there's a problem this was masking.  The `default` wordbreaker doesn't honor context-final spaces that should trigger suggestions for new words instead of modification of pre-space text; this is what is currently breaking MTNT 0.1.3.  (0.1.2 relies on the "placeholder" instead.)
For proof, note the test results of this PR's first commit.  In it, I've corrected the "default" issue so that the tests we thought were running against the default wordbreaker _actually do_.  One failure should result - the one …
=> change(lmlayer): 'default' word breaker issues

common/predictive-text/unit_tests/headless/default-word-breaker.js, common/predictive-text/unit_tests/in_browser/cases/worker-dummy-integration.js, common/predictive-text/unit_tests/in_browser/cases/worker-trie-integration.js, common/predictive-text/worker/index.ts, common/predictive-text/worker/models/trie-model.ts, common/predictive-text/worker/word_breaking/default-word-breaking/index.ts
A 🍒-pick of #2405.
This will fix any issues with MTNT 0.1.3 in the apps, which may be needed/wanted to allow 'stable' to start publishing again for the apps.
1.  Build and run the Android app (or download the .apk from a successful linked Android CI test)
2. Set the keyboard to SIL EuroLatin (and make sure the predictive text banner is shown.
3.  Test use of the predictive banner suggestions, ensuring they "feel right."  A few concrete aspects of this:
- Selecting a suggestion should add the suggestion and a space, as well as resetting the banner to the default three suggestions.
- Selecting a second suggestion immediately afterward appends the new suggestion, rather than replacing the first.
- All text manipulation from predictive banner interaction is "clean," not leaving stray extra …
=> cherry(lmlayer): 'default' word breaker issues

mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m, mac/history.md
Fixes #2345.
The OSK shouldn't show base letters when a Keyman keyboard is active that includes a visual keyboard.
Fixed keyboard:
=> fix(mac): osk shouldn't show base letters

windows/src/developer/TIKE/xml/project/common.js
Fixes #2395. The popup menus in the project window would sometimes
be obscured because they would pop below the height of the window. This
PR changes the menu to pop up instead in those situations.
=> fix(developer): project menu obscured sometimes

windows/src/global/delphi/general/kpsfile.pas
Fixes #2201. If the flag followKeyboardVersion is set, then this removes
the version number embedded in the package source file.
=> fix(developer): Remove kps version when needed

windows/src/developer/TIKE/main/UframeTextEditor.pas, windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas
For all editors other than kmn, it only makes sense
to drop characters, not character codes.
Fixes #2125.
=> fix(developer): character map drops chars reliably

windows/src/developer/history.md, windows/src/developer/kmconvert/Keyman.Developer.System.ImportWindowsKeyboard.pas
When importing a Windows keyboard, the default keyboard id would not necessarily be lower case, which could be confusing as it wasn't clear why the OK button was not enabled.
=> fix(developer): keyboard id should be clean in import

windows/src/developer/TIKE/main/UfrmMain.pas, windows/src/developer/history.md
The application title for Developer should always be
'Keyman Developer' and not show the active project. Only
the title of the main window should show the active project.
=> fix(developer): application title was confusing

windows/src/developer/history.md, windows/src/global/delphi/comp/KMDActions.pas
Fixes #2421. With fixes to the focus in text editors, this changed the
active control reported back through Delphi and we were then testing the
wrong control for availability.
=> fix(developer): Hotkeys in text editor regression

windows/src/developer/history.md, windows/src/global/delphi/comp/KMDActions.pas
Cherry-pick of #2424.
Fixes #2421. With fixes to the focus in text editors, this changed the
active control reported back through Delphi and we were then testing the
wrong control for availability.
=> fix(developer): Hotkeys in text editor regression 🍒

windows/src/developer/TIKE/actions/dmActionsKeyboardEditor.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmProject.pas, windows/src/developer/history.md
Fixes #192. This does not implement Ctrl+F7 but just F7 to compile the 'project'. I can see potential in the future to consolidate the 'compile' command into a single command rather than splitting between Model and Keyboard, and have the same shortcut. But I won't do that in this PR.
=> fix(developer): F7 to compile all in project view

.gitignore
This adds Jetbrains IDE files to the top-level .gitignore.
=> chore: add Jetbrains IDE files to top level .gitignore

windows/src/developer/TIKE/dialogs/UfrmNew.pas, windows/src/developer/TIKE/dialogs/UfrmNewFileDetails.pas, windows/src/developer/TIKE/dialogs/UfrmOptions.dfm, windows/src/developer/TIKE/dialogs/UfrmOptions.pas, windows/src/developer/TIKE/main/KeymanDeveloperOptions.pas, windows/src/developer/TIKE/main/UfrmMain.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewModelProjectParameters.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas, windows/src/developer/history.md, windows/src/global/delphi/general/RegistryKeys.pas
Fixes #1689. Sets the default project path to 'Documents\Keyman Developer\Projects' so that Keyman Developer files don't clutter user's Documents folder. Can be changed in Options dialog.
=> feat(developer): Default project path

android/KMEA/build.sh, web/source/build.sh
Fixes #2323.
So, it turns out that the final issue for #2323 was being caused by the Closure minifier, which tries to be helpful by adding polyfills for us.  Just... that actually broke things on API 19, which apparently is too old for one of its polyfills.
This also adds a simple "build without testing" option to Android's build.sh, allowing for easier compilation of the entire app whenever unit tests fail.  Sometimes this is useful for narrowing things down with live testing.
Note that this issue originally wasn't caught because it doesn't show up with the `debug_embedded` flag for KMW, which itself is set by using the `-debug` flag when compiling the Android app.  Testing locally may require the state seen in commit https://github.com/keymanapp/keyman/commit/4600e2a4069b7db6dce6f8d1f515 …
=> fix(android): Removes Closure's auto-polyfills, adds test case bypass

android/KMAPro/build.gradle, android/KMAPro/kMAPro/build.gradle, android/KMEA/app/build.gradle, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/QRCodeUtil.java, android/KMEA/app/src/main/res/layout/activity_list_layout.xml, android/KMEA/app/src/main/res/layout/qr_layout.xml, android/KMEA/app/src/main/res/values/dimens.xml, android/KMEA/app/src/main/res/values/strings.xml, android/KMEA/app/src/main/res/values/styles.xml, android/KMEA/build.gradle, android/README.md, android/history.md
Addresses Android for #1535
Add QR Codes which link to the keyman.com keyboard page. These are displayed on Keyboard Info and Keyboard Settings Activity. I've also verified the QR codes generate fine on Android API 19.
If the main app doesn't include the QRGen libraries, the QR Code isn't generated/displayed.
* Also update the list of dependencies in README.md
=> feat(android): Add QR Codes on Keyboard Info pages

ios/keyman/Keyman/Keyman/AppDelegate.swift
Fixes #2455.
All in all, a pretty simple fix once you realize what was going on.  Though... why doesn't Apple provide a parameter `permitOverride` or something like that?  Oh well.
Will need a 🍒-pick.
Easy test:
1. Go to https://keyman.com/keyboards/khmer_angkor (or similar page for any .kmp language resource, really)
2. Download the file in Safari.
3. From downloads, install into Keyman.  Follow through to complete installation.
4. Return to Safari, and repeat step 3.  (Installation should proceed without error, as if identical to step 3.)
When not fixed (so... current `master` branch), step 4 will fail - an error will be thrown on the attempt to open it in Keyman, as documented within #2455.
Note that steps 1 and 2 can be replaced with anything that loads the file onto iOS in an …
=> fix(ios): Adhoc resource overwrite/file-replacement

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift, ios/keyman/Keyman/Keyman/AppDelegate.swift, ios/keyman/Keyman/Keyman/MainViewController.swift
As noted in "Yet to do" on #2460, the current state of KMP installation on iOS generates alerts tied to a specific `UIViewController` (the main, bottom-level one) in the app.  Since this will be a problem once we integrate file browsing into the app... and since keeping functionality tightly tied to UI code is a bad practice, this PR factorizes those two aspects.
Note that the functions now maintain a split between UI management and the various aspects of KMP installation.  The new breakdown:
- `prepareKMPInstall` takes in a KMP file and decompresses it to facilitate installation.
- Its "completion handler" will receive the corresponding `KeymanPackage` object if successful, indicating that the KMP's contents are not corrupted.
- It comes in two flavors:
- The first one does all the file …
=> iOS: Refactors KMP installation's connection to app UI

web/source/kmwdom.ts
This remedies an issue where `initializeUI()` would be continuously called within our mobile apps' WebViews, as no UI module is ever loaded in the embedded format.  Said behavior sometimes interfered with live debugging sessions.
=> fix(web): Prevents infinite loop (w timeout) for ui init when embedded

web/source/kmwdevice.ts, web/source/kmwnative.ts, web/source/kmwutils.ts, web/source/utils/styleConstants.ts
As noted by @mcdurdin in https://github.com/keymanapp/keyman/pull/2468#discussion_r364990442,
> I think it would be good to be factoring these types of constants out of the code here and either to the top of the file or into a separate file. I don't have a huge problem with the disconnect between this and the CSS; it's not ideal, of course, but the work to unify this is significant and not really worthwhile.
In further discussion, we decided to merely start an object for this - we can always add to it in the future as future tasks permit.
=> change(web): starts StyleConstants object for centralized style defs

linux/README.md, linux/history.md, linux/scripts/version.sh
Address some of #2435
In README.md, clean up packages to install
* remove devtools (maybe later change to ubuntu-dev-tools?)
* remove gir1.2-webkit-3.0 (deprecated by gir1.2-webkit2-4.0 which is already installed)
Fix default tier so the correct version number is generated during build
=> [Linux] Cleanup to build 13.0 on upcoming 20.04 LTS (Focal Fossa)

ios/exportAppStore.plist
With a new build agent, we have a new distribution certificate for iOS. Given the thumbprint is stored as a parameter, we need to update it.
For the future, we could consider making this an environment variable and putting it into the TC
configuration.
=> chore(ios): replace distribution certificate

windows/src/developer/TIKE/main/UframeTextEditor.pas, windows/src/developer/history.md
With changes to the text editor relating to focus,
double-clicking and drag-dropping from character
map no longer worked reliably. This patch resolves
this problem.
Fixes #2466.
=> fix(developer): char map drop into text editor

windows/src/developer/TIKE/main/UframeTextEditor.pas, windows/src/developer/history.md
Cherry-pick of #2503.
With changes to the text editor relating to focus,
double-clicking and drag-dropping from character
map no longer worked reliably. This patch resolves
this problem.
Fixes #2466.
=> fix(developer): char map drop into text editor 🍒

windows/src/developer/kmdecomp/kmdecomp.vcxproj
kmdecomp had the wrong Windows SDK dependency (note: this issue goes away with VS2019 but breaks build for VS2017 unless the specified SDK is present). We currently depend on 8.1 for all other Windows apps.
=> chore(windows): kmdecomp winsdk version to 8.1

windows/src/desktop/kmshell/main/initprog.pas, windows/src/global/delphi/general/KPInstallPackageStartMenu.pas
Fixes #2467. This is a two part fix. First, the actual shortcuts
now work. Secondly, because the shortcut points to kmshell.exe,
Windows 10 Start Menu will hide it because it is identical to
the Keyman Desktop shortcut. So we add a uniquifier to un-hide
it. A bit silly, but makes sense in this instance.
=> fix(windows): '(Start Product)' shortcuts

ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift, ios/keyman/Keyman/Keyman/AppDelegate.swift, ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift
Fixes #2508.
As noted by the issue above, turns out I may have slightly broken part of the adhoc install process with the document browser work.  This corrects that bug.
=> fix(ios): Tracks 'isCustom' flag for adhoc resources

web/source/text/prediction/modelManager.ts
Fixes #2516.
Turns out I forgot to change a few references when working on #2477, which broke text prediction in the alpha.  Simple enough to fix, though it's a shame that slipped through.
=> fix(web): Hotfixes recent break for text prediction

ios/engine/KMEI/KeymanEngine/Classes/Colors+Extension.swift, ios/engine/KMEI/KeymanEngine/Classes/Colors.swift, ios/engine/KMEI/KeymanEngine/Classes/KeyboardMenuView.swift, ios/engine/KMEI/KeymanEngine/Keyboard Colors.xcassets/SelectedKey.colorset/Contents.json
Fixes #2519.
As it turns out, the system keyboard can't access color definitions managed solely by the main app's bundle.  (The keyboard was crashing from unexpected `nil` values that resulted; they were referenced for popup key/menu formatting.)  We could simply include those as part of the SWKeyboard target, but it's more important that they be accessible from KeymanEngine instead, since they'll be needed by anyone who wishes to link with KMEI.
Retrieving resources from `Bundle`s is easy when everything's in the top-level one (for the app), but it's a bit trickier when you need an embedded framework's `Bundle` instead.
=> fix(ios): Proper handling for xcassets colors in sys kbd

ios/engine/KMEI/KeymanEngine/Classes/Storage.swift
Addresses one issue noted here:  https://github.com/keymanapp/keyman/issues/2530#issuecomment-577954518.  This allows MTNT to be properly default-installed again, even if the constant reinstallation still needs addressing (see #2512).
This one small tidbit was missed after the other code changes to the KMP installation rework; `asZip`'s default value was inverted in [#2489](https://github.com/keymanapp/keyman/pull/2489/files#diff-bfe1674a30111bbeb987ff86394c1519R125).
=> fix(ios): Fixes default model (MTNT) installation

web/source/kmwembedded.ts, web/source/osk/defaultLayouts.ts
Note:  this may also affect (and fix!) the same issue for Android, if it exists there.  Given what was needed... I expect it to have been a problem on Android, too.
Fixes an issue noted [here](https://github.com/keymanapp/keyman/issues/2530#issuecomment-577954518):
> Testing the French: French keyboard - the Alt-Ctrl layer does not activate when selected.
Turns out that the `nextLayer` property for subkeys was never being mapped onto the `KeyEvent` generated for embedded popup key processing... _probably_ a significant oversight.
----
There are a few other idiosyncracies I noted in the function and in how the base & subkey themselves were managed... these aspects are probably in need of some TLC for a future version.
- The key's id isn't set correctly (defaultLayouts.ts, line 212) - left …
=> fix(ios): Fixes embedded subkey layer-shifting

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/Alerts.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageDetailViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageViewController.swift
Addresses part of the notes on #2530:
> After the app successfully loads the keyboard catalog, disable internet connectivity and then attempt to download a keyboard.
>    - This may either crash the app or fail silently.
I only ever saw the crash once during pre-beta testing, so that may have been an instability of sorts from branch hopping.  That said, the "fail silently" part definitely needs to be addressed, which is the aim of this PR.
... and, true to form, I made a small separate module to avoid code duplication for the two error cases that needed addressing.  The functions there should also be useful for lexical model downloads, but for now, "If it ain't broke, don't fix it."
=> [iOS] Keyboard download error notifications

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #2539
During #2326, `KMManager.onDestroy()` was updated to set `InAppKeyboard` and `SystemKeyboard` to null. While good in practice, this created  an issue when closing Keyman as a System Keyboard. Lingering Javascript calls in the WebView would crash with the null keyboards.
This reverts `onDestroy()` to how it has been since before 2.8 stable
* Rotate between profile and landscape orientation and verify Keyman doesn't crash
* Use the globe button to bring up keyboard picker
* Click "Close Keyman" to switch to next system keyboard and verify Keyman doesn't crash
* Bring up Keyman app and verify Keyboard doesn't crash
=> fix(android): Revert KMManager.onDestroy

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/history.md
May fix #2259; at a minimum, strongly mitigates it.
Long story short, turns out the bug was double-layered.
**Layer 1**:  assuming that only two states may exist within `KeymanWebViewController.keyboardLoaded()`. 
- First load of the keyboard:
- `Manager.shared.currentKeyboardID = nil` - it hasn't yet been set.
- `shouldReloadKeyboard == false` - why reload when you haven't reloaded once?
- Subsequent loads of the keyboard
- `Manager.shared.currentKeyboardID` has been set (a default was previously chosen, if naught else)
- `shouldReloadKeyboard == true` - this WebView has already loaded once, but to be safe, it's best if we reset everything to regain a blank slate.
Somehow (I've yet to pin down _exactly_ how, but it's likely due to erraticness with the `viewWillDisappear` lifecycle …
=> fix(ios): keyboard stability

web/source/dom/utils.ts
Fixes bug that shows up in `build_dev_resources.sh`:
source/dom/utils.ts(148,77): error TS2339: Property 'singleton' does not exist on type 'typeof keyman'.
Since that build script ignores kmwbase.ts in order to keep the "dev resources" lightweight for simpler testing, `com.keyman.singleton` isn't defined in this pathway.  For now, `com.keyman.DOMEventHandlers` existing is sufficient to ensure that `com.keyman.singleton` exists as well... though that could be made a bit more explicit.
=> fix(web): dev_resource compile fix

linux/history.md, linux/scripts/launchpad.sh
Update launchpad.sh so that `${tier}` corresponds to the ppa link:
`stable` --> ppa:keymanapp/keyman
others --> ppa:keymanapp/keyman-daily
=> fix(linux): Update launchpad PPA by tier

android/KMEA/app/src/main/java/com/tavultesoft/kmea/ConfirmDialogFragment.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/history.md
When cancelling the Android system notifications about lexical model update being available, the notification would still remain in the notifications bar.
This PR passes the language ID to lexical model confirmation dialogs so it can be cancelled.
Keyboard update notifications already were receiving language ID.
=> fix(android): Fix cancelling ConfirmDialogFragment

android/history.md, web/history.md, web/source/kmwembedded.ts, web/source/text/processor.ts
Fixes #2540
This fixes KMW for embedded devices to not process `K_TAB` so the device will handle it.
Hardware needed: Android device, external keyboard (either via Bluetooth or USB). This won't work in Android Studio emulator
* Rebuild and load the Keyman app
* Set Keyman as the system keyboard
* Open an Android app like Chrome or Google Keep
* Using the external keyboard, type in a text field and verify they appear
* Hit the "Tab" key
* Verify the app navigates to another field
* Hit Shift+Tab
* Verify the app navigates to a previous field
Note: if Google Chrome goes to a page like https://downloads.keyman.com/android/beta
Tabbing will highlight different release folders
I haven't seen an app that will insert `\t` when tab is hit yet...
=> [Web] Fix K_TAB from external keyboard

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift, ios/history.md
Fixes #2549.
It turns out that our iOS app has indeed been ignoring the "Keyboard Clicks" system setting that iOS provides.  Fortunately, there's a way to utilize this:  https://developer.apple.com/documentation/uikit/uidevice/1620050-playinputclick
That stated, there's an unfortunate part.  iOS feels that apps and app extensions should only ever need to poll this setting when they first load.  If the user backs out and changes the "Clicks" setting, neither will update until the process is terminated and restarted... despite the fact that iOS's default keyboard will _instantly_ update.  (Thanks, Apple.)
I've done some web searching to find ways to _force_ an update to the setting check, but the only lead I found [only worked back in 2010](https://stackoverflow.com/a/6236350), so... yeah. …
=> fix(ios): Now (eventually) uses sys pref for kbd clicks

ios/history.md, ios/keyman/Keyman/Keyman/GetStartedViewController/GetStartedViewController.swift
While investigating a different issue, we recently came across https://developer.apple.com/documentation/uikit/uiapplication/1623042-opensettingsurlstring.  A bit of investigation later, and it turns out that as of iOS 11, it's possible to set Keyman as system keyboard _through_ the Keyman settings submenu - making this a much simpler way to enable the system keyboard for compatible devices.
On older devices, though...
So, as a result, we maintain the status quo for 10.0 and before:
But for 11.0+, we can get fancy:
(Please ignore the version string - this was generated outside of our CI pipeline that manages the actual alpha/beta/release versions.)
While yes, this doesn't suggest that users "Allow Full Access", it doesn't appear to be needed on iOS (11.0+, at least) anyway - our App …
=> feat(ios):  Deeplink into Keyman settings for system keyboard setup

common/lexical-model-types/index.d.ts, common/predictive-text/docs/worker-communication-protocol.md, common/predictive-text/worker/model-compositor.ts, web/history.md
Fixes #2522.
This allows for the model's LTR/RTL preference to be specified for use in generating suggestion text.  As noted with upcoming specifications:
> so bcc-Arab uses
>
>     <delimiters>
>     <quotationStart>«</quotationStart>
>     <quotationEnd>»</quotationEnd>
>
> from http://ldml.api.sil.org/bcc-Arab
Note that following that spec, `quotationStart` should be inserted **_after_** `quotationEnd` for RTL languages.  This happens to work nicely with our punctuation defaults; when using the standard English opening & closing quotes, the "open" quote would need to go last for RTL language use.
I did debate for a while whether or not `isRTL` should be specified outside of the `LexicalModelPunctuation` object or not; here's why I eventually went with the version seen here.
index.d.ts …
=> fix(common): RTL model specification

.github/workflows/auto-merge-keyman-server-pr.yml
The previous one failed with errors, e.g.
https://github.com/keymanapp/keyman/pull/2563/checks?check_run_id=420416770.
It's a known, unaddressed issue.
=> chore: use alternate automerge

resources/build/build-utils.sh
Adds version tags and publishes them to
TeamCity as a starting point. We'll add them
progressively to project 'about' dialogs.
=> chore: version tags

resources/build/increment-version.sh
Adds version tagging (and removes extraneous exit line) to increment-version.sh so that no longer needs to be per-platform in GitHub
=> chore: add version tags

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift, ios/history.md
Fixes another issue noted at https://github.com/keymanapp/keyman/issues/2530#issuecomment-577954518.
Before:
After:
=> fix(ios):  Fixes margins on keyboard in iOS 9/10

resources/build/increment-version.sh, resources/build/trigger-builds.sh
After a version is incremented, we trigger builds for all the platforms based on the *last* commit before the version change.
This ensures that history and version numbers are valid and complete before we start the build. In the future, we could import the version history into the documentation or archive for the projects.
=> chore(ci): trigger builds after version increment

web/history.md, web/source/text/processor.ts
Fixes the Windows-OS issue noted here:  https://github.com/keymanapp/keyman/issues/2528#issuecomment-578565837
> Attempting to use BKSP within a design-mode <iframe> seems to redirect backspaces to the most recent alternative input and focuses that one instead. Other keystrokes are fine; just BKSP.
>
>    - If the design-mode <iframe> had been the previous input (due to focus loss + regain), it'll accept them then
>    - Content-editables do not share this issue.
>    - Happens in all browsers on Windows; does not happen on macOS.
While I didn't fully investigate why this only broke on Windows, it turns out there was a glaring inefficiency in the code that, when fixed, resolved the issue anyway - the `defaultKeyOutput` method actually _does_ have access to the current `OutputTarget`, so …
=> fix(web): default BKSP output targeting

linux/.pbuilderrc, linux/history.md, linux/scripts/cow.sh, linux/scripts/launchpad.sh
Since cosmic and disco Ubuntu releases are EOL, launchpad is rejecting package updates for those releases. This PR removes them from CI.
=> fix(linux) Remove cosmic and disco releases

linux/history.md, linux/keyman-config/keyman_config/keyboard_details.py
Found during investigation of #2575 after installing the attached Malayalam keyboard package.
"About" keyboard fails to show when package copyright information is missing.
This PR adds a check for the copyright info (normally displayed below "Package version")
=> fix(linux): Fix 'About' keyboard when missing copyright

configure-repo.sh, resources/git-hooks/commit-msg, resources/git-hooks/commit-msg-defs, resources/git-hooks/prepare-commit-msg
Having gotten more than a bit annoyed at how the default merge commit messages are blocked by the current conventional commit-hook checks, I decided to invest a bit of effort to develop a `prepare-commit-msg` hook for use within the Keyman repo.
Refer to https://git-scm.com/docs/githooks for documentation if desired, and compare against [git's official example](https://github.com/git/git/blob/master/templates/hooks--prepare-commit-msg.sample).
**Rule 1** - if it's already in our [Conventional Commits format](https://github.com/keymanapp/keyman/wiki/Pull-Request-and-Commit-workflow-notes), don't touch it.
If the message _isn't already in the right format_, then for certain event types this hook will then alter the suggested message before presenting it to the user for editing.  To do so, …
=> feat: prepare-commit-msg hook for autogenerated conventional commit messages

common/engine/keyboardprocessor/src/km_kbp_context_api.cpp
A static buffer for UTF-8 encoded characters used in debugging and test logs did not provide enough space for SMP characters (require 6 bytes rather than 4). This was used only for test cases and not in production code -- outputting JSON text. Also requires nul terminator.
This should fix the failing keyboardprocessor test builds on Windows and macOS.
=> fix(common/core): buffer overrun in context api

resources/build/run-required-test-builds.sh
It depends on 14.0 alpha version infrastructure; we shouldn't need it for triggering the test builds for beta.
=> fix(ci): don't include build-utils.sh

ios/keyman/Keyman/Keyman/MainViewController.swift
Addresses part of #2491.
By having the `customButton` perform image scaling instead of prescaling the image, iOS will automatically transition the icon images for our nav-bar buttons.
This PR does _not_ fix the lack of a "dark mode image banner" - that is addressed instead by #2594.
=> fix(ios): Icon image change on light/dark mode transition

linux/keyman-config/debian/control
Xenial doesn't provide python3-qrcode, and specifying the
alternative package in the control file doesn't work because the
build always uses the first specified alternative. This change
makes use of build profiles ([1]) to select the correct package.
[1] https://wiki.debian.org/BuildProfileSpec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2609)
=> fix(linux): Fix packaging of keyman-config on Xenial

web/source/kmwuifloat.ts, web/source/kmwuitoggle.ts
Fixes #2595.
While I was at it, I also checked the other UI styles and noticed that Float seemed to be broken.  A small bit of investigation later, and it turned out that the `'LEnabled'` check was the only reference to the property; it was changed in KeymanWeb itself a while back by some of the refactoring.  Conditioning on the referenced element being 'attached' seems a natural fix and gets the Float UI working properly, too.
=> fix(web): patches Float and Toggle UI issues

web/source/build.sh
This simply fixes a couple of minor gripes that've been bugging me for a bit, along with one small logic error.
Small logic error:  proper error reporting if Node.js isn't installed.  Gotta read that error code in the right spot.
Minor gripe 1:  the `-test` and `-ui` compilation options really shouldn't force a rebuild of the lm-layer - these options exist for streamlined, rapid re-compilation for testing during development.  So, I tweaked the script a bit to allow skipping lm-layer compilation for these options.
Minor gripe 2:  it's rather bad form for `./build.sh -h` to trigger a `npm install` before it, you know, actually displays the help message.  (Also, it _**absolutely**_ shouldn't require compiling the lm-layer, which was the case before this PR!)
Since a `npm install` isn't …
=> change(web): build.sh recompilation of LMLayer only performed when needed

ios/engine/KMEI/KeymanEngine/Classes/Colors+Extension.swift, ios/engine/KMEI/KeymanEngine/Classes/Colors.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/KeyboardSwitcherViewController.swift, ios/engine/KMEI/KeymanEngine/Keyboard Colors.xcassets/KeyboardSelectionPrimary.colorset/Contents.json, ios/samples/KMSample2/KMSample2.xcodeproj/project.pbxproj
Fixes #2625.
Caught an extra bug after fixing the first, triggered by how the refactored Color definitions are set up.
=> fix(ios): Fixes in-app use of KMSample2

windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas, windows/src/engine/keyman/touchkeyboard/Keyman.System.FrameworkInputPane.pas
Fixes #2577.
The touch layout editor was not accepting characters inserted from character map by double-clicking or using the menu, only by drag+drop.
=> fix(developer): touch layout editor character map integration

windows/src/developer/history.md, windows/src/global/delphi/packages/Keyman.System.PackageInfoRefreshKeyboards.pas
Fixes #2555.
The package compiler would give a misleading error when it was verifying keyboard version numbers if one of the files could not be found; it would say the keyboard file versions (between .kmx and .js) mismatched instead of complaining about the missing file.
This reduces this error to a warning, allowing the verification to continue, and the resulting log shows that the file is missing and fails the build more logically.
=> fix(developer/compiler): package: version mismatch

windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas, windows/src/developer/history.md
Fixes #2498.
The .keyboard_info merge was incorrectly assuming the presence of a .js in the .kmp file if the source .kmn file asserted support for touch platforms, when testing the .kmx files. Now, platform support for Android and iOS will only be added if the package actually includes the .js file that makes that possible.
=> fix(developer/compiler): compiler sometimes merges touch platform support wrongly in .keyboard_info

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/history.md, ios/keyman/Keyman/SWKeyboard/KeyboardViewController.swift
Fixes #2597.
It usually helps for a file to actually be a .zip file when you try to decompress it.  Try as you might, it just doesn't work the same when you try to decompress a renamed .js file.
---
Also fixes a lint warning about line length by splitting the offending line into two.
=> fix(ios): Fixes lexical model url generation for updates

windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.Base.pas, windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.Debugger.pas, windows/src/developer/history.md
Fixes #2630.
The MIME type for .js was being read from the registry, which on some systems has been corrupted to text/plain, which causes Chrome to abort loading the script. The fix is to avoid loading the system registered MIME types, which we don't need anyway, because all the MIME types we are using are in the default hard-coded list.
=> fix(developer/ide): model debugger mime type mismatch

oem/firstvoices/android/app/build.gradle
On older Android 5.0 (API 21) devices without Play Store, androidx.appcompat:1.1.0 is causing the FirstVoices app to crash inflating WebView.
* Per SO suggestion, update androidx.appcompat to version `1.2.0-alpha02`
While updating build.gradle
* Also split `firebase-core` dependency to `firebase-analytics` and `firebase-messaging` (mirrors kMAPro)
=> fix(oem): Update version of androidx.appcompat

web/history.md, web/source/dom/touchAliasElement.ts, web/source/osk/languageMenu.ts, web/source/resources/osk/kmwosk.css
I'm honestly surprised this hadn't been reported as an issue yet.
While testing something else, I noticed some very odd behavior with the touch-OSK's display of the native-mode language menu:.  The following images are from use of the testing/attachment-api testing page (in Chrome emulation, with 5 'input' elements labeled with text from 'a' through 'e'.):
Position where I clicked on the Globe key:
Position where the language menu actually appeared:
In short, for long web pages, the language menu wouldn't properly align with the OSK's position.  Also, as may be noticed, the language menu was at an 'absolute' position on the page and would not scroll with the page.
---
Rather than do anything terribly complicated, this PR sets the language menu to use a similar positioning strategy to that …
=> fix(web): fixes positioning of native-mode language menu

android/KMAPro/kMAPro/build.gradle, android/KMEA/app/build.gradle, android/Samples/KMSample1/app/build.gradle, android/Samples/KMSample2/app/build.gradle, android/Tests/KeyboardHarness/app/build.gradle, android/Tests/keycode/app/build.gradle, android/history.md
#2640 fixed the FirstVoices OEM app from crashing on Android 5.0 devices.
This applies the same fix (updating to `androidx.appcompat:appcompat:1.2.0-alpha02`) for all the other Android apps.
* Also fix up history.md entries
Android Studio emulator for Pixel 2 XL API 21 (no Play Store)
=> change(android): Update app dependencies

ios/engine/KMEI/KeymanEngine/Classes/Migrations.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/Version.swift
Fixes an issue introduced by #2578 - the app would not automatically install the default lexical model for English.
Turns out I made an invalid assumption; `Migration.updateResources` was not able to handle initial installations because it didn't realize there was no prior installation.  The keyboard was being installed due to our failsafe "if no keyboards, reinstall EuroLatin" check later in the code.
By adding a check for this condition, signaling it with a simple `Version.freshInstall` sentinel, that control path can now properly "upgrade"/"migrate" from a nil install, handling both initial installs and migration for prior app/engine versions.
=> fix(ios): initial-install check within Migrations

web/source/text/prediction/modelManager.ts, web/source/text/processor.ts
Bugs fixed:
1) `defaultKeyOutput` may emit console warnings (etc) when performing fat-finger checks.  (This may result in the same warning being emitted 40+ times, like for ctrl-alt layers with few assigned keys.)
2) `keyman.modelManager.enabled` returns `true` even when no model is active, which causes KMW to perform fat-finger calculations unnecessarily.
=> fix(web): Fat-finger complication fixes

configure-repo.sh
On Linux, the `configure-repo.sh` script to setup the repo for Conventional Commits isn't linking `commit-msg-defs`.
This prevented commits from being added.
Not an issue on Windows or macOS
=> fix(common): Update configure-repo.sh to ln commit-msg-defs

mac/build.sh
I accidentally pulled old parameters into mac/build.sh for the
make-km-dmg.sh script when merging from beta. The script no longer
requires `-version`. This fixes that.
=> fix(mac): invalid build script params removed

windows/src/developer/TIKE/main/UfrmHelp.pas
Fixes sillsdev/keyman-issues#6207.
Fixes sillsdev/keyman-issues#5801.
Fixes sillsdev/keyman-issues#5742.
Fixes sillsdev/keyman-issues#6186.
Fixes sillsdev/keyman-issues#6124.
Fixes sillsdev/keyman-issues#5647.
Fixes sillsdev/keyman-issues#5726.
Fixes sillsdev/keyman-issues#6149.
Fixes sillsdev/keyman-issues#6228.
Fixes sillsdev/keyman-issues#6001.
Fixes sillsdev/keyman-issues#6148.
Fixes sillsdev/keyman-issues#6159.
Fixes sillsdev/keyman-issues#6171.
This fixes a crash when context help is unable to determine the
current context.
=> fix(developer): crash in context help

common/engine/keyboardprocessor/src/utfcodec.hpp, linux/history.md, linux/ibus-keyman/debian/control, linux/keyman-config/Makefile, linux/keyman-config/debian/control
Fixes #2645 and addresses some of #1648 
* Define `fallthrough` macro appropriate for the gcc version on a particular LTS
* Use a lower version of `libjson-glib-dev` for Xenial (the version it comes with)
With this PR, keyboard processor builds cleanly on Xenial. But I still have integration issues with ibus (Keyman keyboards can install, but ibus doesn't see them)
=> fix(common, linux): Misc keyboard processor fixes for Xenial

common/engine/keyboardprocessor/debian/watch, linux/history.md, linux/ibus-keyman/debian/control, linux/ibus-keyman/debian/watch, linux/ibus-kmfl/debian/watch, linux/keyman-config/debian/watch, linux/kmflcomp/debian/watch, linux/libkmfl/debian/watch, linux/scripts/launchpad.sh
Fixes #2552 
The current debian/watch files won't work for `stable` tier because the regex `(beta|stable)` matches the existing beta versions first.
Also, to support upcoming 14.0, the tier will be set by a `TIER.md` file.
This PR updates launchpad.sh so that:
1. tier is determined by `TIER.md` file or environment var $TIER. Fail if not set
2. Use `sed` to update debian/watch files with the specified `${tier}`. This will overwrite the tier from a previous run.
=> [Linux] Fix tier used in debian watch files

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/Colors+Extension.swift, ios/engine/KMEI/KeymanEngine/Classes/Colors.swift, ios/engine/KMEI/KeymanEngine/Keyboard Colors.xcassets/HelpBubbleGradient1.colorset/Contents.json, ios/engine/KMEI/KeymanEngine/Keyboard Colors.xcassets/HelpBubbleGradient2.colorset/Contents.json, ios/history.md
While working on #2649, I stumbled upon the solution to get the old KeymanEngineDemo target compiling properly; as it turns out, a similar project as a "test container" for file-oriented user tests seems ideal.  Getting the 'original' demo project up and running should help with developing a more focused "test container".
While it's not perfect, these changes are sufficient to get the demo up and running, at least at a basic level.
On the iPhone SE, things look proper; the layout issues are likely related (at least in part) to either the notch or the larger resolution of the iPhone X.
Changelist:
- Turns out the source of the compile errors?  Use of `swiftlint` on KeymanEngine code.
- We'll probably want a pass at KeymanEngine code formatting separately in the future, but for now this can …
=> fix(ios): Engine demo fix

windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas, windows/src/developer/history.md, windows/src/developer/inst/kmdev.wxs
The uninstall is supposed to remove HKCU settings for developer. However a
side-effect is that an upgrade (which msi treats as uninstall/ install
internally) also removes HKCU settings. This is sad and it is probably
better overall to leave a dangling HKCU key after uninstall.
Fixes #2667.
Cherry-pick of #2668
=> fix(developer): upgrade removes preferences 🍒

windows/src/developer/inst/kmdev.wxs
The uninstall is supposed to remove HKCU settings for developer. However
a side-effect is that an upgrade (which msi treats as uninstall/
install internally) also removes HKCU settings. This is sad and it is
probably better overall to leave a dangling HKCU key after uninstall.
Fixes #2667.
=> fix(developer): upgrade removes preferences

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift
Fixes #2673.
Turns out that there's a property (`preferredLexicalModel`) that was never getting properly set, which meant that the "update" code for settings changes was never triggering.  I've added secondary handlers to match what already existed within `Manager.setKeyboard()` that perform the same default, allowing the settings to properly trigger now.
Also, `self.activeModel`  was being used as part of the condition for adding the additional height needed for a banner.  This was always being added, even if predictions were deactivated - this field is now set to `false` so that this specific case does not occur, as deactivated predictions means a deactivated model.
=> fix(ios): Responsive predictive toggles

linux/history.md, linux/keyman-config/MANIFEST.in
Attempts to address #2682.
Launchpad keyman-config build fails because `com.keyman.gschema.xml` isn't included in the manifest so it can't be copied into the destination.
=> [stable][linux]: Add gsettings schema to manifest

ios/engine/KMEI/KeymanEngine/Classes/HTTPDownloader.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/KMPKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/KMPLexicalModel.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/KeyboardKeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/LexicalModelKeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift
Turns out, iOS update + KMP parsing code was in need of a little TLC.
- Lexical models' versions were not found in the most up-to-date KMPs, as it's only specified at the top level now ("info" > "description"), and not on the model itself as before
- Version metadata wasn't being updated, so even after successful updates, the app still thought updates were needed
- There was a major CTRL-C/CTRL-V bug in one of the lexical model control paths that went unchecked until now
=> fix(ios): Resource update issues

web/unit_tests/CI.conf.js
Someone (me) might have accidentally forgot to re-enable the other browser targets for testing after debugging issues with Edge...
=> fix(web): Web CI target reversion

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
Follow-on to #2319
For 14.0 alpha, the app version needs to be sanitized to #.#.# when downloading a keyboard.
This refactors the regex to KMManager.getVersion()
=> fix(android): Sanitize app version string for api query

resources/build/increment-version.sh
`trigger-builds.sh` now makes use of the definitions in `trigger-definitions.config`. Therefore we need to make those definitions available.
This change should fix the failure in https://build.palaso.org/viewLog.html?buildId=184503&buildTypeId=Keyman_TriggerReleaseBuildsMaster&tab=buildLog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2714)
=> fix(ci): Fix increment-version.sh script

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
Fixes #2711 and the corresponding [crash](https://fabric.io/keymanproduction/android/apps/com.firstvoices.keyboards/issues/2f6322b926b19e5cf28f3b85c9c0a844) for the FirstVoices app.
This PR adds a null check on the `kbdMapList` and initializes accordingly.
It follows the pattern of `lexMapList` a few lines later (l. 590)
=> fix(android) Fix crash on kbdMapList

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
Cherrypick #2715 to stable-13.0
Regex to only use `#.#.#` for the app version.
history.md to be updated in #2723
=> fix(android): Sanitize app version for api query

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/history.md
For stable-13.0, initialize null `kbdMapList`. This follows the pattern of lexMapList.
=> fix(android): Cherrypick #2711 to fix null kbdMapList

windows/src/developer/TIKE/xml/layoutbuilder/builder.js
Keyman Developer could crash if a specific sequence was invoked
importing a keyboard into a touch layout and then changing the
template. Fixes #2712.
Same as #2721, for master.
=> fix(developer): crash when switching layout templates

windows/src/developer/TIKE/xml/layoutbuilder/builder.js, windows/src/developer/history.md
Keyman Developer could crash if a specific sequence was invoked importing a keyboard into a touch layout and then changing the template. Fixes #2712.
=> fix(developer): crash when switching layout templates 🍒

windows/src/developer/TIKE/child/UfrmKeymanWizard.pas, windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas, windows/src/developer/history.md
Double-click to insert a character from char map into the touch layout
editor would not work reliably after focus changes.
Fixes #2702.
=> fix(developer): insert from charmap into touch editor

configure-repo.sh
When using worktrees in git the hooks directory is under the main
worktree directory. `$ROOT/.git` might be a text file instead of a
folder. `git rev-parse` will return the correct location in all
cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2722)
=> feat(common): Support git worktree when configuring local hooks

docs/linux-packaging.md, linux/README.md
This is an attempt to document Linux packaging of Keyman. Please add comments where you think something is missing or where things are unclear.
I initially thought I would create a page on the wiki for this document and use this PR just for discussion. After looking at the other two files in the `docs` folder it looks like it might fit in there as well. Where do you think this doc should be?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2720)
=> docs(linux): Add linux packaging documentation

windows/src/developer/TIKE/child/UfrmKeymanWizard.pas, windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas
Double-click to insert a character from char map into the touch layout
editor would not work reliably after focus changes.
Fixes #2702.
🍒 of #2736.
=> fix(developer): insert from charmap into touch editor 🍒

windows/src/developer/TIKE/child/UfrmDebug.pas
In the past, we received two bksp events when deleting smp,
but that code was eliminated a version or two ago, and this missed
the cut then.
Fixes #2730.
=> fix(developer): debugger breaking smp with bksp

windows/src/support/Makefile, windows/src/support/etl2log/Makefile, windows/src/support/etl2log/etl2log.cpp, windows/src/support/etl2log/etl2log.sln, windows/src/support/etl2log/etl2log.vcxproj, windows/src/support/etl2log/etl2log.vcxproj.filters, windows/src/support/etl2log/load.cpp, windows/src/support/etl2log/logging.cpp, windows/src/support/etl2log/logging.h, windows/src/support/etl2log/stdafx.cpp, windows/src/support/etl2log/stdafx.h, windows/src/support/etl2log/version.in
Converts .etl logs from Keyman debug log into .log files for simpler analysis. These log files are generated when Keyman is running with Debugging on, into %localappdata%\Keyman\Diag.
The generated files are in UTF16 TSV which is easily loaded into Excel.
While the .etl files can also be loaded with Perfmon and other Event Tracing for Windows tools, they are typically cumbersome to configure and use.
=> feat(windows): etl2log support tool

android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadIntentService.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/FileUtilsTest.java
Addresses deep linking for #2708 
Handle `keyman://` protocol for downloading .kmp packages
Verified with the test link
`keyman://?filename=khmer_angkor.kmp&url=https%3A%2F%2Fkeyman.com%2Fkeyboard%2Fdownload%3Fid%3Dkhmer_angkor%26platform%3Dandroid`
TODO for a future PR - download in the background
=> Feature: Android - Handle keyman:// protocol to download kmp keyboard

ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Migrations.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/Version.swift, ios/engine/KMEI/KeymanEngineTests/VersionTests.swift, ios/keyman/Keyman/Keyman/InfoViewController/InfoViewController.swift, ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift
Important note:  Commit https://github.com/keymanapp/keyman/commit/77f7c20cf0077d6bce794c3c3a38405b1beae795 is :cherries:-picked for 13.0 release at #2774!
Fixes #2725.
The other commits are for use in 14.0 only; this adds a few changes to prevent further breaks down the line and starts the iOS app/engine on the right path toward directly drawing from its actual versioning information where appropriate, also adding new Version testing to these extensions.
- `change(ios): separates app version from engine-feature version` creates the split version scheme.  While it _could_ be 🍒'd as well, there's no reason to add a potentially-breaking change to stable-13.0 at this time.
- This change will link _quite_ nicely with the upcoming changes in #2775.  (In fact, development on that PR started …
=> fix(ios): fixes broken online-help versioned link

resources/build/run-required-test-builds.sh
This caused the build triggers to fail in some circumstances, for example see log at 
https://build.palaso.org/viewLog.html?buildId=188008&buildTypeId=Keyman_Test&tab=buildLog&_focus=113#_state=99
```
[12:56:36][Step 2/2]  * [new tag]             windows-release-stable-13.0.102.0 -> windows-release-stable-13.0.102.0
[12:56:36][Step 2/2] . Get list of changed files in the pull request
[12:56:36][Step 2/2] fatal: option '--name-only' must come before non-option arguments
```
=> fix(common): parameter order incorrect in git diff

ios/engine/KMEI/KeymanEngine/Classes/KeyboardScaleMap.swift
Cherrypick of #2695's bugfix.
The omitted changes from that PR were all in support of unit-testing.  As unit-testing won't be merged into the stable-13.0 branch, those may be safely left out.
This can technically be delayed until Apple releases a new device, but it's simple and safe enough to "throw in" whenever we have a more substantial iOS bug fix to release for Stable.
=> fix(ios): fixes scale-selection logic 🍒

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
🍒-picked at #2776.
Turns out that #1756 was actually slightly incomplete in one aspect.
Apple has some really, uh, "interesting" behavior for its IME text context objects.  What was happening:
1. A user types a block of text
2. They then hit ENTER for a newline
3. Type a small bit of extra text that matches a keyboard rule prefix
4. Type the key that triggers the keyboard rule, deleting context up to the point of the newline as _part_ of the rule.
At this stage, Apple triggers a `textDidChange` event, saying "oh, your only context _is_ that newline"... _after_ the keyboard rules have been triggered and suggestions generated.  Not catching this detail causes a state where any suggestions accepted are then applied as if there were no context, creating masses of duplicated text.
So, we now …
=> fix(ios/engine): Fixes context bug for certain keyboard rules after newlines

android/KMAPro/kMAPro/src/main/res/values/strings.xml
Follow-on to #2751 
This updates additional strings in the KMAPro app for crowdin
* `action_file_browser` was unused, so removed
=> feat(android): Update additional main app strings for crowdin

ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
Looks like I didn't quite get the framework copying part of the build right when adding Sentry to the iOS app:
```
[01:57:07]
[Step 3/3] ERROR [2020-03-10 05:57:57.57]: [Transporter Error Output]: ERROR ITMS-90087: "Unsupported Architectures. The executable for Keyman.app/Frameworks/Sentry.framework contains unsupported architectures '[x86_64, i386]'."
[01:57:07]
[Step 3/3] 
[01:57:07]
[Step 3/3] ERROR [2020-03-10 05:57:57.57]: [Transporter Error Output]: ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'Keyman.app/Frameworks/Sentry.framework/Sentry' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
[01:57:07]
[Step 3/3] 
[01:57:07]
[Step 3/3] ERROR [2020-03-10 05:57:57.57]: [Transporter Error Output]: ERROR ITMS-90125: "The …
```
=> fix(ios): fixes Carthage framework copy for Sentry

linux/scripts/dist.sh
Follow-on to #2735
The dist.sh script also needs to be updated to fix path from common/engine/keyboardprocessor/
to common/core/desktop/
=> fix(linux): Fix CI dist path to common/core/desktop

web/source/kmwkeyboards.ts
Fixes #2785.
I'd actually noticed this behavior recently on the KMW local testing pages, but just hadn't gotten around to making an issue for it in the midst of everything else last week.  It turns out that a change intended only for 14.0 got backported to 13.0 - how the old `_BUILD_` property is now relocated to `keyman.build` so that it can be set by environment.inc.ts.
The resulting issue is best highlighted by the two following API calls, both requesting `sil_euro_latin@no` - a Norwegian-tagged request for use of the SIL EuroLatin keyboard:
- (Current) https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype=bcp47&version=14.0.undefined&keyboardid=sil_euro_latin@no&timerid=7
- (Fixed) https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype …
=> fix(web): fixes build number reference of API call

web/source/kmwbase.ts, web/source/osk/visualKeyboard.ts, web/testing/build-visual-keyboard/index.html, web/testing/index.html
Addresses #2784.  🍒-pick will be required to actually fix it.
This PR fixes the existing issue with `BuildVisualKeyboard` by directly reusing the actual `VisualKeyboard` constructor.  I did attempt to keep it closer to the original implementation, but ran into much more trouble doing so.  The key: we want a static method that doesn't depend on an already-operating OSK so that we can utilize `deviceDependentLayout`.  This is best accomplished by allowing our desired static keyboard to _be_ that OSK, at which point it will automatically use the function anyway.
To do this, it was necessary to further modularize `VisualKeyboard` a bit.  Long story short, it can now (optionally) take a `Device` parameter rather than constantly re-referencing `keyman.util.device`, allowing it to target …
=> fix(web): updating BuildVisualKeyboard

windows/src/Defines.mak, windows/src/Makefile, windows/src/README.md
Make sure that our prerequisites are in place *before* starting a release build. Note: doesn't currently check that certificates are valid so that's a future test we could include.
One day it'd be nice to remove dependency on 7-zip: perhaps we won't need it once we have better crash reporting.
Note: Only setting this up as draft so it doesn't confuse during release phase. Will merge post release of 13.
=> chore(windows): improve build script tests

linux/scripts/dist.sh
Follow on to #2735 and #2795 
The project.version in meson.build is no longer replaced to `#.#.#` in the file, which caused dist.sh to fail on CI test builds.
This PR has vers use the same VERSION.md file as all the other platforms.
=> fix(linux): Fix how keyboardprocessor version is set in dist.sh

android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMAPro/kMAPro/src/main/res/menu/overflow_menu.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Revert intentional crash from #2778
Now that the call stack in Sentry is tested on Release build
http://sentry.keyman.com/organizations/keyman/issues/61/?project=7
* The temporary menu to generate the intentional crash can be removed.
Additional updates
* Disable monitoring Application Not Responding (ANR)
* Add NPE checks before sending KMW error to Sentry.
(Addresses https://sentry.keyman.com/organizations/keyman/issues/58)
Fixes KEYMAN-ANDROID-K.
=> feat(android): Additional Sentry integration

web/source/osk/visualKeyboard.ts
Fixes #2756.
For review, it may help to refer to VisualKeyboard.ts, line 74 or so.  `.layer` is the key's display layer, while `.spec.layer` refers to the modifier layer.  Tracking these properties gets a bit tricky.
@mcdurdin has data for a (private) keyboard affected by the bug this addresses; please ensure that it behaves as expected when on a build based off this branch.  (Note the "attached keyboard" detail in the original issue... which was not attached.)
=> fix(web): applies base key layer property to unassigned subkeys

common/predictive-text/worker/models/trie-model.ts
This fixes a community-reported bug when for Trie-based lexical models for SMP-based languages.  The reported issue:  a character had to be typed twice for its suggestions to appear.  (Privacy has been requested for the original bug-reproducing resources, hence nothing being explicitly provided here.) 
As it turns out, the reason is that the second entry was necessary to traverse nodes to match the first actual character; we're currently building our Tries for SMP languages on a per-UCS-2 character basis, meaning that each UTF-8 SMP character has two nodes - one for each UCS-2 codepoint comprising it.  The first character was only ever "completed" once a second character (_any_ second character) was typed.
So, while our wordbreaking and transforms need to be SMP-aware, internally the Trie …
=> fix(common/lmlayer): fixes word lookup from Tries for SMP script-based languages

resources/build/sentry-control.sh
It's not 100% clear to me what the purpose of splitting 'new' and 'final' versions of releases is in [Sentry](https://docs.sentry.io/cli/releases/#finalizing-releases). But here it is.
=> feat(common): add release finalization for Sentry

web/bulk_rendering/renderer_core.ts
So, in v12 we split the OSK into two pieces - the `OSKManager` and the `VisualKeyboard`.  The bulk renderer never quite got the memo, as a critical (internal) reference for bulk rendering was moved from `keyman.osk` to `keyman.osk.vkbd` as a result - the part responsible for changing layers.
=> fix(web): fixes internal reference for validation tool

oem/firstvoices/android/app/src/main/AndroidManifest.xml
This PR disables the OEM FirstVoices Android app from monitoring "Application Not Responding"
1. Matches KMAPro
2. The startup issue is tracked as #2811
=> fix(oem): Disable monitoring of ANR for oem Android app

web/source/dom/contentEditable.ts, web/source/dom/designIFrame.ts, web/source/dom/utils.ts, web/source/kmwdom.ts, web/source/kmwdomevents.ts, web/source/kmwuitoggle.ts, web/source/osk/oskManager.ts
For a little while now, design-mode iframes have been a bit... broken - they've never displayed the OSK or the Float/Toggle UI modules when active.  Before fixing #539, it's best to get these working again so that they aren't _further_ broken by anything uncaught during that upcoming rework.
As it turns out, there was _also_ a break whenever the ENTER key was pressed within either a content-editable or a design-mode iframe - this one a regression from 11.0 to 12.0, when the `OutputTarget`s were introduced.  Turns out that issue was embarrassingly simple to resolve, at least.  (See the single line added to the respective wrapper classes... which took over an hour or two of debugging to realize.  Yay, end-of-day debugging.)
So, after all that, a snippet from the Attachment API testing page: …
=> fix(web): fixes design mode and content editable issues

web/source/build.sh, web/source/kmwdomevents.ts, web/source/kmwembedded.ts, web/source/text/kbdInterface.ts, web/source/text/keyEvent.ts, web/source/text/processor.ts
Based on #2830.  While the changes likely aren't directly dependent, I'd like to avoid... uh, `git branch` hell as the refactoring work proceeds.  It's already looking a bit nasty in the near future regarding #2838, which has code that will need to be considered for the next stage of work.
------
If we're going to have a headless web-core, we have to remove the HTMLElement reference from `KeyEvent.Ltarg`.  Fortunately, we can easily replace that with the `OutputTarget` of the original reference.
* Important keyboards for testing:
- `sil_euro_latin`:  Desktop mode still provides its custom OSK, which still functions correctly
- `japanese`, `chinese`:  Both still display their pickers and are still fully functional.
* Predictive text (on testing/prediction-ui) is still properly functional. …
=> refactor(web/engine): KeyEvent object now refers to outputTarget over element

android/Tests/KeyboardHarness/app/build.gradle
As part of supporting RTL layouts in #2816,  the KMEA `minSdkVersion` API version upgraded from 16 to 19.
This PR updates the Sample apps and Tests/KeyboardHarness to also use API version 19.
Test/keycode does not use KMEA so it doesn't need to update atm.
=> fix(android): Fix min SDK version for Sample and Test apps

android/Samples/KMSample1/app/build.gradle, android/Samples/KMSample2/app/build.gradle
These KMSample (bolded) files didn't get attached to #2860
> This PR updates the **Sample apps** and Tests/KeyboardHarness to also use API version 19.
=> fix(android): Update min SDK versions for sample apps

android/KMEA/app/src/main/assets/keyboard.html, web/source/kmwembedded.ts, web/source/text/defaultOutput.ts, web/source/text/kbdInterface.ts, web/source/text/processor.ts
The second half of #2853.
Now it's time for the real default key output rework.  For a while now, KMW has been overloading `defaultKeyOutput` to do a lot of different things all in a single place:
- mnemonic key mapping
- character lookups (for base layouts, Unicode keys)
- browser behavior emulation (especially for the OSK)
- lookup error output (but only for actual user keystrokes, not predicted ones)
These changes look to untangle a lot of the mess that resulted from this.  For example, when doing mnemonic key mapping, we aren't looking to _apply_ a backspace - simply returning '\b' is far more accurate.
On `DefaultOutput`:
- The function `forAny` is extremely analogous to the old `defaultKeyOutput` - it's basically a plain character-lookup version devoid of special handling.  This is …
=> refactor(web/engine): reworks default output handling to return RuleBehaviors

web/source/dom/contentEditable.ts, web/source/dom/designIFrame.ts, web/source/dom/input.ts, web/source/dom/textarea.ts, web/source/dom/touchAlias.ts, web/source/kmwembedded.ts, web/source/text/outputTarget.ts, web/source/text/processor.ts, web/testing/prediction-ui/index.html
Adds two new members to the `OutputTarget` abstraction type:
* `OutputTarget.isSynthetic` - notes whether or not an element has default keystroke processing, as provided by a browser.
- `false` for most types, `true` for `TouchAlias` and `Mock`.
* `OutputTarget.handleNewlineAtCaret` - provides element-specific default handling for the ENTER key, allowing us to remove that code from `defaultKeyOutput`.
- Note that two types (`DesignIFrame` and `ContentEditable`) explicitly lack actual handling.
- There's no actual functionality change here - this is documenting problems that have already long existed within KeymanWeb.  I noted this detail during work on #2838.
With those changes in place, significant cleanup of `defaultKeyOutput` was then possible, which helped to remove most of its …
=> refactor(web/engine): extended abstraction with OutputTarget

web/source/text/kbdInterface.ts, web/source/text/processor.ts
While very small in terms of lines changed, this little number is important enough to merit its own specialized PR.  This one method - `keyman['oninserttext']` - is the lynchpin that connects embedded KMW's output to app-native code.
As originally implemented, this function was generally called once per output statement of a KMW keyboard's rule.  This may mean multiple calls:
Keyman rule (approximate):
```
'a' any(my_store) 'p' + K_1 > context(1) index(s2, 2) 'e'
```
Compiled output rule:
```
KeymanWeb.KO(2, 'p', t);
KeymanWeb.KIO(0, this.s2, 1, t);
KeymanWeb.KO(0, 'e', t);
```
As `KIO` calls `KO`, each of these would trigger separate calls.  That, and we had to explicitly block these calls when the outputTarget (`t`) was of `Mock` type.
Now, instead we simply accumulate all the effects …
=> refactor(web/engine): reworks use of embedded's keyman['oninserttext']

web/source/text/kbdInterface.ts, web/source/text/processor.ts, web/source/text/ruleBehavior.ts
A pretty simple code relocation PR.  Now that `RuleBehavior` is used in multiple files, it's probably best to give it its own *.ts.
=> refactor(web/engine): moves new RuleBehavior type & behaviors to own file

web/source/dom/contentEditable.ts, web/source/dom/designIFrame.ts, web/source/dom/input.ts, web/source/dom/textarea.ts, web/source/dom/touchAlias.ts, web/source/text/kbdInterface.ts, web/source/text/outputTarget.ts, web/source/text/processor.ts
Just removing yet another DOM dependency from `KeyboardInterface` in preparation for headless mode.
While I could move it earlier in the PR chain, there's a single (but desired) `if`-check dependent on work on the PR's current base.
=> refactor(web/engine): doInputEvent moved to OutputTarget

windows/src/buildtools/sentrytool/Keyman.System.MapToSym.pas, windows/src/developer/TIKE/main/KeymanDeveloperUtils.pas, windows/src/developer/TIKE/main/UfrmMain.pas, windows/src/ext/sentry/Sentry.Client.pas, windows/src/ext/tds2dbg/tds2dbg.sln, windows/src/ext/tds2dbg/tds2dbg.vcxproj, windows/src/ext/tds2dbg/tds2dbg.vcxproj.filters, windows/src/global/delphi/general/Keyman.System.KeymanSentryClient.pas
Two issues:
* There was a bug in the map file line number mapping where length of the last line in a function was too long
* Functions without line information were ignored by Sentry so adding a synthetic line entry for those functions (library functions primarily)
Two tweaks:
* Added a Visual Studio project file for the existing tds2dbg code (which was previously built with Borland C++? many years ago) while looking at alternative mapping solutions and decided to keep it.
* Instead of an access violation for crash tests, now uses a specific `ESentryTest` exception which is better for filtering.
=> fix(windows): some sentry symbolication was not working

linux/README.md, linux/keyman-config/keyman_config/__init__.py, linux/keyman-config/keyman_config/downloadkeyboard.py, linux/keyman-config/keyman_config/version.py.in, linux/scripts/reconf.sh
In 13.0, the VERSION.md file contained 13.0 and so that was used for downloadkeyboards.
As of 14.0, `resources/build/build-utils.sh` define the build variables:
```
```
The go/linux links need an #.# version (e.g. 14.0 instead of 14) so this PR changes from __majorversion__ to __releaseversion__.
Also updated the linux README.md for minor edits
=> fix(linux): Use __release_version__ for downloadkeyboard window

android/KMEA/app/src/main/assets/keyboard.html, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
Looks like I missed one detail on #2863 - the Android and iOS apps have been looking at  `keyman.interface` when setting the keyboard.  Merging that broke them, though it's at least a simple fix.  The `KeymanWeb` global doesn't seem to be going away any time soon.
Fixes KEYMAN-ANDROID-H.
=> fix(web): fixes embedded kbd initialization

web/source/osk/visualKeyboard.ts
=> fix(ios): popup keys over base keys no longer emit base char.

web/source/keyboards/keyboard.ts, web/source/keyboards/kmwkeyboards.ts, web/source/text/kbdInterface.ts, web/source/text/processor.ts
This PR is focused on refactoring references to the existing keyboard 'tag' object.  At present, it's only used to cache previously post-processed keyboard properties - "exploded" stores.
Tested with `khmer_angkor`, which has extensive use of stores with its reorder rules; everything checks out, and the cached stores are used properly after these changes are in place.
=> refactor(web/engine): relocates keyboard tag code, adds typing

web/source/text/defaultOutput.ts
... kinda forgot that `null == false` in JS is actually `false`, despite both acting as `false` in an if-check.  (Whereas `false == ''` is `true`, etc.)  As a result, we need these lookup helper functions to return `null` when they do not match.
Among other things, this PR fixes currently-broken physical typing with SIL EuroLatin on the current alpha.
=> fix(web/engine): Fixes default key lookup returns

android/crowdin.yml, resources/build/l10n/README.md
This PR adds the [Crowdin CLI (v3)](https://support.crowdin.com/cli-tool-v3/#configuration) to automate downloading/uploading files between Keyman platforms and https://crowdin.com/project/keyman
We should be able to remove the previous scripting in `/resources/build/l10n`.
Setup notes are in resources/build/l10n/README.md
1. To upload Android strings
```
crowdin upload sources
```
2. To download Android strings (for Khmer)
```
crowdin download -l km
```
=> feat(common): Use Crowdin CLI (v3) for handling l10n files

windows/src/developer/TIKE/main/KeymanDeveloperOptions.pas
Fixes #2910. Keyman Developer's options were using REG_SZ where Sentry
expected REG_DWORD.
=> fix(developer): use correct registry types for sentry options

windows/src/global/delphi/general/Keyman.System.KeymanSentryClient.pas
Fixes #2911. This adds a default parameter so the error reporting dialog can show details of the
report. It does not address manual report sending.
=> fix(windows): replaces empty eventid with underscore when autoreport errors off

web/source/dom/domEventHandlers.ts, web/source/dom/preProcessor.ts, web/source/kmwhotkeys.ts, web/source/text/processor.ts
This PR is focused on relocating physical-keystroke preprocessing (quite DOM-reliant) out of the `Processor` class with minimal actual changes otherwise.  This will be extended further in later PRs.
=> refactor(web/engine): starts DOM pre-processor

web/source/kmwembedded.ts, web/source/osk/preProcessor.ts, web/source/osk/visualKeyboard.ts, web/source/recorder_ui_and_stubs.js, web/source/text/processor.ts
Since relocating all the DOM preprocessing was quite the batch of its own, I decided to make this PR (for OSK preprocessing) separate.  Similar purpose and scope otherwise.
=> refactor(web): starts OSK preprocessor

web/source/dom/preProcessor.ts, web/source/keyboards/keyboard.ts, web/source/kmwdevice.ts, web/source/kmwembedded.ts, web/source/osk/preProcessor.ts, web/source/text/engineDeviceSpec.ts, web/source/text/kbdInterface.ts, web/source/text/keyEvent.ts, web/source/text/processor.ts
And now for some actual changes.  Keystroke processing is partly reliant on device awareness, especially since we have the `ifStore` rule component that tests against various device properties.  So, we need a headless-friendly version that can exist within web-core that is separate from the current `com.keyman.Device` class.  (That class includes lots of detection methods that are DOM-reliant.)
The particularly icky stuff is yet to come, though.
=> refactor(web): headless device representation

web/source/dom/domEventHandlers.ts, web/source/dom/preProcessor.ts, web/source/kmwembedded.ts, web/source/osk/preProcessor.ts, web/source/text/kbdInterface.ts, web/source/text/processor.ts
This PR aims to relocate most of the condition-specific code out of the `Processor`.
A significant amount of code was embedded-OSK specific, some not-embedded-only specific, and some was hardware-specific.
The most tricky aspects to follow will likely be the `swallowKeypress` changes.  I ended up comparing against KMW 10.0, in which this was only set for hardware keystrokes toward support for mnemonics.
Mnemonics... have long been significantly broken in KMW (it's been termed low-priority); we'll look for a more comprehensive mnemonic review and fix at a later point.  The amount of work needed in KMW's current state to completely validate such keyboards would delay web-core work far too much.
----
I aimed to keep commits small and focused, in case that might help with the review process. …
=> refactor(web): cleanup for Processor.processKeyEvent

.gitignore, resources/build/l10n/README.md
Crowdin CLI doesn't extract into a temporary `.crowdin-tmp/` folder so that can be removed. (.crowdin-tmp was used in prior Bash scripts).
Also moved note about using a VPN to the wiki https://github.com/keymanapp/keyman/wiki/Crowdin-CLI
=> chore(common): Cleanup unused folders and update README

web/source/dom/preProcessor.ts, web/source/keyboards/activeLayout.ts, web/source/keyboards/defaultLayouts.ts, web/source/keyboards/keyboard.ts, web/source/osk/oskManager.ts, web/source/osk/preProcessor.ts, web/source/osk/visualKeyboard.ts, web/source/text/processor.ts
Also places `emulatesAltGr` as property of the `Keyboard` wrapper object.
As things already were, the `ActiveLayout` and `DefaultLayouts` classes are practically headless-ready; just a bit more tweaking will be needed.
Next goal:  have the `Keyboard` wrapper handle default layout construction as needed; it'll help with `OSK`/`VisualKeyboard` cleanup and guarantee that the abstracted layout is available for web-core use and testing.
=> refactor(web/engine): Preps keyboard layouts definitions for web-core

android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/LexicalModelPackageProcessor.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/LexicalModelPackageProcessorTest.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/PackageProcessorTest.java
Currently when installing a keyboard package where the keyboard is associated with several languages, only the first listed language gets associated with the keyboard.
In a future sprint where cloud keyboards install kmp files, we will need a way to specify a language ID that the user searched for.
This PR makes the language ID optional, so it it doesn't match in kmp.json, the first listed language gets used.
Note: the language ID parameter is passed but unused in `LexicalModelPackageProcessor` because all the model/language combinations are returned.
=> feat(android): Specify optional language ID for installing kmp

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #2786 as reported by user
I verified globe button still works as before for the apps:
Keyman - both in-app and system keyboard
KMSample1 - in-app
=> fix(android): Fix globe button crash on 3rd party apps

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/history.md
Cherrypick of #2930 for stable-13.0
=> fix(android, stable): Fix globe button crash for 3rd party apps

web/source/keyboards/keyboard.ts
When doing the layout refactor, I forgot to check against chirality-enabled keyboards.  Due to their structure, they may not necessarily have a ['BK'] entry; we should first check for a ['KLS'] entry, which all chirality-enabled keyboards will have.
=> fix(web/engine): default layout fix for chiral keyboards

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java
Fixes #2743 and crashlytic issue
https://console.firebase.google.com/u/1/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5abd6c9831c913e93eb75d28da472079
which affected many users.
The primary fix was checking the context isn't null.
While updating ResourcesUpdateTool(), also added a cleanup method to clear the notification bar when exiting Keyman.
=> fix(android): Fix exception in ResourcesUpdateTool

web/source/text/kbdInterface.ts, web/source/text/systemStores.ts
This is part 1 of 2 toward reworking how and where KMW manages the current OSK layer.
The new abstract `SystemStore` base class will also be used for managing the layer, but first I felt it best to convert over the _other_ existing system store, since its conversion is far more straightforward to verify.
Tested against the following keyboards:
- `khmer_angkor` (Has a form-factor dependent BKSP implementation)
=> refactor(web/engine): start of system store abstraction

web/bulk_rendering/renderer_core.ts, web/source/kmwbase.ts, web/source/kmwembedded.ts, web/source/osk/visualKeyboard.ts, web/source/text/kbdInterface.ts, web/source/text/processor.ts, web/source/text/ruleBehavior.ts, web/source/text/systemStores.ts
Picking up where #2919 left off, this is part 2 of 2 for the layer management rework.
This PR now formalizes layer as a web-core accessible system store, with the OSK listening for changes rather than being the layer manager.  This change turned out to be... remarkably more direct than I feared it would be, which was a very pleasant surprise.
I've tested against the following scenarios:
- The desktop OSK properly changes layers to match the currently-held modifier keys (tested with `khmer_angkor`, though any keyboard should suffice)
- Touch tests:
- `sil_cameroon_qwerty` - has a _lot_ of layers, next layer behaviors, and keys with custom layer properties that don't match the layer they're on.
- `nrc_crk_cans` - has a lot of next-layer stuff going on to compose vowels, uses `KSETS` …
=> refactor(web/engine): Processor now manages current layer; OSK listens via callback

web/source/dom/domManager.ts, web/source/dom/variableStoreCookieSerializer.ts, web/source/kmwbase.ts, web/source/text/kbdInterface.ts, web/source/text/processor.ts, web/source/text/ruleBehavior.ts
This PR simply abstracts the currently-existing variable store load/save model.  While the objects involved aren't necessarily the most efficient, they are accurate to how KMW has operated thus far and are compatible with saved values in older cookies.  We'll worry about a headless implementation of the abstraction after we finally turn web-core headless and are ready to unit-test this functionality in that environment.
This also brought to light the need for a proper "options" object for `Processor` initialization.
=> refactor(web/engine): variable store storage abstraction

web/source/dom/domEventHandlers.ts, web/source/dom/domManager.ts, web/source/kmwbase.ts
Fixes #539.
#2838 resolved a lot of the ongoing type confusion for managing the active element within the DOM part of KMW.  After a little more work, we can finally eliminate the `HTMLElement|Document` dual-typed parameters, making things a bit cleaner overall.
=> fix(web): fixes activeElement typing

android/KMEA/build.sh, android/Tests/KeyboardHarness/build.sh, android/Tests/KeyboardHarness/readme.md
On CI, the `android/` folder was getting locked because KeyboardHarness/build.sh would rebuild KMEA without passing `-no-daemon`.
This PR updates KeyboardHarness/build.sh to follow KMAPro and Sample apps build.sh scripts and not build KMEA.
KMEA/build.sh also updated to directly copy the artifact to the KeyboardHarness project
=> fix(android): Change KeyboardHarness/build.sh to not rebuild KMEA

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadIntentService.java
This updates how the Keyman app handles URLs for downloading kmp files (in preparation for keyboard picker revamp).
If the URL contains "language" or "platform", those values are propagated for when the kmp gets downloaded.  The "languageID" is then used during kmp installation.
Also fixed a few things with URL handling:
* Catch UnsupportedOperationException if the original URL has invalid query parameters
* Handle DownloadIntentService fails
Load the Keyman app.
Open a Chrome browser and go to the link:
```
keyman://?filename=sil_cameroon_qwerty.kmp&url=https://keyman.com/keyboard/download?id=sil_cameroon_qwerty&language=bbj-Latn&platform=android
```
The KMP should install and use the specified `bbj-Latn` language (Ghomálá').
Normally, sil_cameroon_qwerty defaults to `aal` (Afade).
=> feat(android): Propagate languageID when downloading kmp

android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDownloadMgr.java
Fixes #2710
The DownloadManager used to get cloud updates can only save to external storage. On some Android devices, this requires the `WRITE_EXTERNAL_STORAGE` permission.
=> fix(android): Add check for WRITE_EXTERNAL_STORAGE permission

common/predictive-text/unit_tests/in_browser/cases/worker-trie-integration.js, common/predictive-text/unit_tests/in_browser/resources/models/naive-trie.js, common/predictive-text/worker/models/trie-model.ts
Here's a regression test for https://community.software.sil.org/t/search-term-to-key-in-lexical-model-not-working-both-ways-by-default/3133.
However, I could not reproduce this error? I will ask the author of the issue for more details.
**EDIT**: I realize I misinterpreted the original poster's question. I'll be back!
**EDIT 2**: Issue reproduced! Now to fix it >.<
**EDIT 3**: My regex character range was incorrect 🤦‍♂️ Fixed!
=> fix(common/lmlayer): use searchTermToKey() on input

web/source/dom/domDefaultOutput.ts, web/source/dom/domEventHandlers.ts, web/source/dom/domManager.ts, web/source/dom/targets/contentEditable.ts, web/source/dom/targets/designIFrame.ts, web/source/dom/targets/input.ts, web/source/dom/targets/outputTarget.ts, web/source/dom/targets/textarea.ts, web/source/dom/targets/touchAlias.ts, web/source/dom/targets/wrapElement.ts, web/source/keyboards/defaultLayouts.ts, web/source/kmwembedded.ts, web/source/kmwutils.ts, web/source/text/defaultOutput.ts, web/source/text/outputTarget.ts, web/source/text/processor.ts, web/source/utils/deepCopy.ts
Referring to our [Web-Core Refactor design doc](https://docs.google.com/document/d/1yXcxuVoXaT1nRFvGq9ws7U9GluZVI9t1VsGLEP0SbFE/edit?usp=sharing), it's almost time to complete "stage 1" for a headless web-core.  To facilitate the actual split, this PR splits a few classes into headless vs DOM-aware variants.
It's largely just moving code around and tying up the loose ends that process causes.
=> refactor(web/engine): proper split-off of DOM-reliant code

web/bulk_rendering/renderer_core.ts, web/source/dom/domEventHandlers.ts, web/source/dom/domManager.ts, web/source/dom/preProcessor.ts, web/source/keyboards/keyboard.ts, web/source/keyboards/kmwkeyboards.ts, web/source/keymanweb.ts, web/source/kmwbase.ts, web/source/kmwdebug.js, web/source/kmwembedded.ts, web/source/osk/banner.ts, web/source/osk/oskManager.ts, web/source/osk/preProcessor.ts, web/source/osk/visualKeyboard.ts, web/source/text/inputProcessor.ts, web/source/text/kbdInterface.ts, web/source/text/keyEvent.ts, web/source/text/keyboardProcessor.ts, web/source/text/prediction/modelManager.ts, web/source/text/ruleBehavior.ts, web/testing/chirality/chirality.js, web/testing/regression-tests/src/test-runner.js, web/unit_tests/cases/engine.js
Referring to our [Web-Core Refactor design doc](https://docs.google.com/document/d/1yXcxuVoXaT1nRFvGq9ws7U9GluZVI9t1VsGLEP0SbFE/edit?usp=sharing), it's almost time to complete "stage 1" for a headless web-core.
This PR splits the old `Processor` into two separate modules - `KeyboardProcessor`, which will be free of all references to predictive text, and `InputProcessor`, which will manage both `KeyboardProcessor` and predictive text operations as the outermost class for the eventual completed web-core (stage 2).  For now, `InputProcessor` still has DOM-references in need of fixing, while `KeyboardProcessor` is headless-ready outside of two small, final ties.
To follow the conventions we've set in our discussions, `InputProcessor` will be referred to as `keyman.core` - as it's the eventual …
=> refactor(web/engine): InputProcessor/KeyboardProcessor split

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
Alas, this doesn't really resolve the longpress issue for iOS, but it's still a bug within the code regardless.  I'm fairly certain I've seen a bit of keyboard instability along these lines at other times as well; this should help ensure that the in-app keyboard's display is more stable.
Note that, at present, the 'first responder' status has typically been blocked by an `e.preventDefault()` call as part of the OSK's touch handling code.  It's probably best if we don't fully rely upon that, so this adds a second layer of protection against in (within the app).
=> fix(ios): prevents in-app keyboard resets

common/predictive-text/unit_tests/in_browser/CI.conf.js, common/predictive-text/unit_tests/in_browser/browser-test.sh
The LMLayer was still testing under IE11. I apparently didn't get the memo that we dropped for support for IE11, and I can't seem to find the documentation supporting this. In fact, I've found this documentation:
https://help.keyman.com/troubleshooting/browsers
> KeymanWeb is designed to be fully compatible with the following browsers:
>  Internet Explorer 6, 7, 8
>  Firefox 2, 3, 3.5
>  Safari 4
>  Chrome 2
That documentation is so out-of-date, it's probably best to just delete it!
Anyway, this gets rid of the IE11 config. I may add testing in Edge in a separate PR.
=> chore(common/lmlayer): do not run tests in IE11 in Windows

android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebBrowserActivity.java, android/KMEA/app/src/main/AndroidManifest.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMPBrowserActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguagesSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/JSONUtils.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java, android/KMEA/app/src/main/res/layout/activity_kmp_browser.xml, android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/JSONUtilsTest.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/PackageProcessorTest.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/FileUtilsTest.java
Follow-on to #2944 and addresses most of #2708
For adding keyboards, this PR replaces the language/keyboard search
**From:** language picker (scrolling through the super long list)
**To:** Embedded webView to https://keyman.com/keyboards where the searchbox to find a keyboard.
Instead of using the legacy `keyman://` protocol for downloading cloud keyboards, we will use a deep link along the lines of
```
keyman:download?filename=sil_cameroon_qwerty.kmp&url=https%3A%2F%2Fkeyman.com%2Fkeyboard%2Fdownload%3Fid%3Dsil_cameroon_qwerty%26bcp47%3Dbbj-Latn%26platform%3Dandroid
```
The link is based on an embedded windows search
https://keyman.com/keyboards/blackfoot_syllabics_u?embed=windows&version=10.0.0.0
This PR also updates the intent handling to associate the opaque URI `keyman:download`.
The …
=> feat(android): Download cloud keyboards from https://keyman.com/keyboards

ios/history.md, web/source/osk/visualKeyboard.ts
=> fix(ios): [cherry] popup keys over base keys no longer emit base char

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/SubKeysView.swift, web/source/kmwembedded.ts
A temporary workaround for #2716.
Unfortunately, Apple broke something in iOS 13.4 that we've been heavily relying upon for longpresses on the keyboard.  Longpresses that start within a `WKWebView` can now be blocked by JS events, which completely broke all subkey menus.
This PR will adapt Keyman for iOS to rely on Web-side longpress detection instead.  Unfortunately, web-side longpresses can't exactly control Swift-side UI, but we _can_ at least trigger display of the subkey menus.
With this workaround in place, once the subkey menu displays, the user **must** start a second touch within that menu in order to select whatever key/option they desire.  We simply can't tie the menu-generating longpress to the Swift UI, unfortunately.  So, it won't be as smooth as before, but at least it'll …
=> fix(ios): iOS 13.4 subkey menu workaround

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
Fixes #2950
Update system keyboard to hide the OSK when Back pressed.
=> feat(android): Dismiss system keyboard on Back press

android/KMAPro/kMAPro/build.gradle, android/KMEA/app/build.gradle, android/Samples/KMSample1/app/build.gradle, android/Samples/KMSample2/app/build.gradle, android/Tests/KeyboardHarness/app/build.gradle, oem/firstvoices/android/app/build.gradle
Fixes #2989
This updates the minimum supported Android SDK to 21 (Lollipop). This applies to KMEA, KMAPro, Sample Apps, KeyboardHarness, and FV Android app.
Tests/keyCode doesn't use KMEA so no change there.
=> modify(android): Update minimum SDK to 21

web/source/keyboards/activeLayout.ts, web/source/keyboards/keyboard.ts, web/source/kmwembedded.ts, web/source/osk/preProcessor.ts, web/source/osk/visualKeyboard.ts, web/source/text/inputProcessor.ts, web/source/text/keyboardProcessor.ts, web/source/utils/deepCopy.ts, web/testing/chirality/chirality.js
To be able to do predictive text headlessly, we need to be able to generate events for untyped keys so that their results can be analyzed for potential corrections.  This previously relied on code with ties to the main, DOM-aware `com.keyman.singleton` object.
After this, there are still a few small ties that must yet be resolved:
- `InputProcessor` should own the `modelManager`.
- There's a critical `keyman.isEmbedded` check in `processKeyEvent` that needs to be properly resolved.
=> refactor(web/engine): precomputation for OSK key events, headless production thereof

web/source/dom/domEventHandlers.ts, web/source/kmwbase.ts, web/source/osk/banner.ts, web/source/osk/bannerManager.ts, web/source/osk/preProcessor.ts, web/source/osk/visualKeyboard.ts, web/source/text/inputProcessor.ts, web/source/text/prediction/languageProcessor.ts, web/source/text/prediction/modelManager.ts
Based on #2969, this PR starts formally splitting off `LanguageProcessor` functionality from `ModelManager` functionality, as noted by the [Web-Core Refactor design doc](https://docs.google.com/document/d/1yXcxuVoXaT1nRFvGq9ws7U9GluZVI9t1VsGLEP0SbFE/edit#).  `ModelManager` will remain in DOM-aware KMW, while `LanguageProcessor` will become a web-core component, and thus headless.
Since there's a lot of code to be moved and loose ends to keep tied before continuing, this one's pretty much just code relocation.
=> refactor(web/engine): initial ModelManager split

web/source/dom/domManager.ts, web/source/dom/domOverrides.ts, web/source/osk/bannerManager.ts, web/source/osk/preProcessor.ts, web/source/text/inputProcessor.ts, web/source/text/prediction/languageProcessor.ts, web/source/text/prediction/modelManager.ts
Based on #2974.
The old enablement model presents a few issues for going headless; changing `mayPredict` from `false` to `true` required access to the central `com.keyman.singleton` object.  Allowing a model to be loaded while `mayPredict` is false is more-headless friendly - models can be set from outside the `LanguageProcessor` even while prediction is off and will no longer need to be dynamically loaded on state change.
To allow this without breaking things, we simply prevent interactions (`predict`, `wordbreak`) from proceeding while `mayPredict` is false (and thus, `isActive` is false).  Accordingly, the `'modelchange'` event has been retooled into a `'statechange'` event that has the same actual meaning within KMW as `'modelchange'` always had; it just realigns the semantics to …
=> refactor(web/engine): lm-layer enablement state management rework

web/package-lock.json, web/package.json, web/source/dom/preProcessor.ts, web/source/includes/blank-module.ts, web/source/includes/events.ts, web/source/kmwembedded.ts, web/source/osk/banner.ts, web/source/osk/bannerManager.ts, web/source/osk/preProcessor.ts, web/source/text/inputProcessor.ts, web/source/text/prediction/languageProcessor.ts, web/source/text/prediction/modelManager.ts, web/source/text/ruleBehavior.ts
WIth this in place, we're getting close to taking `InputProcessor` headless, though there are a few odds and ends yet to tie up.
The trickiest remaining part - making `lm-layer` headless-ready, as it currently depends on the `Worker` type and paradigm.
=> refactor(web/engine): predictive data routing, LanguageProcessor as EventEmitter

web/source/build-web-core.sh, web/source/dom/domEventHandlers.ts, web/source/dom/domOverrides.ts, web/source/osk/banner.ts, web/source/text/inputProcessor.ts, web/source/text/prediction/languageProcessor.ts, web/source/text/prediction/modelManager.ts, web/source/web-core.tsconfig.json
After these changes, the only needed changes remaining are those that will allow the lm-layer to be used headlessly.  (These have their own, separate PR chain - #2986, #2987, and #2988.)  The current lm-layer design requires DOM access for WebWorkers, after all.
The exact compilation errors:
```
jahorton@Joshuas-MacBook-Pro source % ./build-web-core.sh
> keyman@11.0.0 tsc /Users/jahorton/keymanapp/keyman/web
> tsc "-p" "source/web-core.tsconfig.json"
../common/predictive-text/index.ts:51:22 - error TS2304: Cannot find name 'Worker'.
51     private _worker: Worker;
~~~~~~
../common/predictive-text/index.ts:65:54 - error TS2304: Cannot find name 'Worker'.
65     constructor(capabilities: Capabilities, worker?: Worker) {
~~~~~~
../common/predictive-text/index.ts:67:36 - error TS2552: Cannot …
```
=> refactor(web/engine): web-core build prep

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java, android/history.md
Cherrypick #2933 to  stable-13.0
This fixes crashlytic [issue](https://console.firebase.google.com/u/1/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5abd6c9831c913e93eb75d28da472079) by checking for valid context before setting a preference.
=> cherrypick(android) - Fix ResourcesUpdateTool crash

android/KMEA/app/src/main/assets/keyboard.html, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
#2975 changed up how KeymanWeb triggers model-related events.  This didn't affect anything in iOS, but it did break Android.  These changes bring Android's code in line with the new event spec.
=> fix(android): predictive banner display bugfix

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #2962 
Only apply relative layout `ALIGN_PARENT_BOTTOM` for inapp keyboard (keeps it anchored to the bottom of the app)
I don't have access to WeChat account to test if this addresses #1870
Verified with Keyman as system keyboard in the Telegraph app.
Hitting the smile (emoji) did not fill the screen as originally reported in the issue.
=> fix(android): Fix system keyboard alignment

.gitignore, common/predictive-text/README.md, common/predictive-text/package-lock.json, common/predictive-text/package.json, package-lock.json, package.json, resources/shellHelperFunctions.sh, web/README.md, web/bulk_rendering/build.sh, web/package.json
Rather than force users to `npm install -g lerna`, it turns out there is a way to use local installs instead.
Alas, this _does_ involve manipulating a few package.json files... which in turn causes some _*massive*_ package-lock.json changes.
=> feat(common): lerna now npm-installed locally

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/GetStartedActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsFragment.java, android/KMAPro/kMAPro/src/main/res/values/strings.xml
PR #2751 cleaned up UI strings, changing the label from `Show "Get Started" on startup` to `Show this menu on startup`. This change was fine for the "Get Started" menu, but the label is confusing when reused on the Keyman Settings menu.
This PR reverts the label (while formatting the string to include the localized string for "Get Started".
stable-13.0 didn't have the cleaned up strings, so this doesn't need to be cherry-picked
=> fix(android): Clarify label that shows "Get Started" on startup

developer/js/source/lexical-model-compiler/lexical-model-compiler.ts, developer/js/source/lexical-model-compiler/lexical-model.ts, developer/js/tests/fixtures/example.qaa.wordbreaker/example.qaa.wordbreaker.model.ts, developer/js/tests/fixtures/example.qaa.wordbreaker/wordlist.tsv, developer/js/tests/test-compile-model.ts
This introduces an expanded way that the word breaker can be specified.
Whereas before, we'd have this:
```typescript
{
wordBreaker: 'default'
}
```
Now we _may_ have this:
```typescript
{
wordBreaker: {
use: 'default',
}
}
```
This makes it easier to add options to the word breaker specification (see #2753), as the options can be provided as additional properties to the `wordBreaker` object. e.g., in the future, we could have this:
```typescript
{
wordBreaker: {
use: 'default',
joinWordsAt: ['-'],
}
}
```
This change is backward-compatible. The old way of specifying word breakers still works.
=> feat(common/lmlayer): allow for verbose word breaker specification

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardPickerAdapter.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtil.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Dataset.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Keyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LanguageResource.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtilTest.java
This PR refactors `com.tavultesoft.kmea.data.Keyboard` to not use Map.
Instead, the class can be instantiated via JSON Objects or passed properties.
There's still many areas to refactor HashMap out. Some TODOs for future PRs are:
* com.tavultesoft.kmea.data.LexicalModel (sibling class to Keyboard)
* installed keyboard lists and installed lexical models lists - these are currently saved as `ArrayList<HashMap<string, string>>` to the filesystem. Maybe we should migrate them to `ArrayList<Keyboard>` and save to new files?
=> modify(android): Refactor Keyboard class to not use Map

developer/js/source/lexical-model-compiler/build-trie.ts, developer/js/tests/test-default-search-term-to-key.ts
Following from the discussion in #2971, I've changed the default `searchTermToKey` in two ways:
* lowercases input one code point at a time, to eliminate context-sensitive lowercasing (e.g., `ΣΚΥΛΟΣ` to `σκυλος`)
* normalizes to NKFD to neutralize confusing compatibility forms of characters (e.g., Arabic presentational forms, alternate Latin letter forms)
**Question**: Should NFKD normalization happen after or before lowercasing forms individually? Are there any edge cases you can think of that I should test?
=> change(common/lmlayer): improvements to default searchTermToKey

common/predictive-text/unit_tests/headless/join-word-breaker.js, common/predictive-text/worker/word_breaking/join-word-breaker-decorator.ts
Laying down some work for #2753. This adds a new word breaker _decorator_. The word breaker decorator takes an existing word breaker, and outputs an enhanced word breaker. The enhanced word breaker joins spans that were a broken a little _too_ much by the given word breaker.
For example:
```javascript
defaultWordBreaker("khui-chhùi").map(s=>s.text) === ["khui", "-", "chhùi"];
```
But with the joiner:
```javascript
let improvedWordBreaker = decorateWithJoin(defaultWordBreaker, ['-']);
improvedWordBreaker("khui-chhùi").map(s=>s.text) === ["khui-chhùi"];
```
Importantly, `decorateWithJoin(existingWordBreaker, ...)` returns another word breaker!
This means that features like joining at hyphens can be implemented _without modifying existing word breaker code_. By using this decorator, all …
=> feat(common/lmlayer): create join word breaker decorator

ios/README.md, oem/firstvoices/ios/build.sh, oem/firstvoices/ios/build_keyboards.sh, resources/build/jq.inc.sh, resources/build/run-required-test-builds.sh
Instead of building and copying from keyboards repo, just
download the final fv keyboards from download server. This
avoids a bunch of dependencies on macOS build agents.
Later, we'll do the same for Android. This will also need to
be reviewed when we move from embedding .js to embedding .kmp
later in phase 10 (14.0 alpha).
=> fix(ios): download fv keyboards

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardPickerAdapter.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageListUtil.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelInfoActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtil.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudKeyboardMetaDataDownloadCallback.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Dataset.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Keyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LanguageResource.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtilTest.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/FileUtilsTest.java
This PR follows-on to #3020 in addressing more tech debt
The meaning of a "custom ad-hoc keyboard/lexical-model installation" has changed over the years.
Back in Keyman 10, cloud keyboards didn't use kmp's, and "custom" keyboards used ad-hoc kmp installations. Thus, there was a convention to treat all kmp installs as "custom".
Now in Keyman 14, cloud keyboards are also installed via kmp packages. So the properties  "custom" keyboard and "custom" lexical-model can be removed.
* Convert LanguageResource() base class from interface to abstract
* This involves moving the order of some common parameters (version and help link)
* Add some helper functions in Keyboard
There's some temporary HashMaps that got added, but will be completely removed in a future PR when the installed dat files get …
=> modify(android): Refactor LanguageResource() and remove "Custom" property

common/predictive-text/package.json
I just noticed this mistake! My affiliation in the package is incorrect; it should be my NRC affiliation, and not my personal one.
=> chore(common/lmlayer): change author from personal to work affiliation

developer/js/source/lexical-model-compiler/lexical-model-compiler.ts, developer/js/source/lexical-model-compiler/lexical-model.ts, developer/js/tests/fixtures/example.qaa.joinwordbreaker/example.qaa.joinwordbreaker.model.ts, developer/js/tests/fixtures/example.qaa.joinwordbreaker/wordlist.tsv, developer/js/tests/helpers/index.ts, developer/js/tests/test-compile-model.ts
This completes support for the `join` word breaker decorator.
Now you can specify a model like this:
```typescript
const source: LexicalModelSource = {
format: 'trie-1.0',
sources: ['wordlist.tsv'],
wordBreaker: {
use: 'default',
/* 👇👀 */
joinWordsAt: [':', '-', '·']
}
};
export default source;
```
And words like _Kanien'kehá:ka_, _amiskwaciy-wâskahikan_, and _cel·la_ will no longer be split in the middle! 🙌
---
This will compile to the following model code:
```javascript
(function() {
'use strict';
LMLayerWorker.loadModel(new models.TrieModel({"totalWeight":1110,"root":{"type":"internal","weight":1000,"values":["k","a","c"],"children":{"k":{"type":"leaf","weight":1000,"entries":[{"key":"kanien'keha:ka","weight":1000,"content":"Kanien'kehá:ka"}]},"a":{"type":"leaf","weight":100,"entries":[ …
```
=> feat(common/lmlayer): compile joinWordsAt property

oem/firstvoices/android/app/src/main/AndroidManifest.xml
On sentry.keymanc.om, we're moving the OEM FirstVoices Android app from  *#keyman-apps* to the *#keyman-oem-apps* team.
It's also split into its own [fv-android](http://sentry.keyman.com/settings/keyman/projects/fv-android/) project (vs sharing with the Keyman Android app)
This PR updates the Sentry DSN accordingly
=> modify(oem): Update DSN for FV Android app

android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/FileUtilsTest.java
Fixes #3502 by using `File.separator` in the test
=> fix(android): Fix FileUtilsTest to be cross-platform

ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj, oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj
Fixes #3065. The version number was not set in the Settings bundle for the swkeyboard during the build. So WET!
=> fix(ios): FV settings bundle for SWKeyboard

oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj
This is probably a temporary patch as we need to remove the dependency from Keyman Engine and have it only in Keyman.
=> fix(ios): add sentry framework to fv keyboards

oem/firstvoices/ios/Cartfile, oem/firstvoices/ios/Cartfile.resolved, oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj
FV keyboards still crashing with missing Sentry framework. This appears to match the ios Keyman build so not sure exactly why this is happening. Trying an alternative.
=> fix(ios): try embed of sentry again for fv

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtil.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Keyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LanguageResource.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java
This PR is laying some groundwork towards migrating the installed keyboards list and installed lexical models list from HashMaps to JSONArray
There's also some static utility constants for default LexicalModel and default Keyboard.
They will be for the use-cases where the current dictionary/keyboard needs to revert to the default ones.
=> modify(android): Add methods to go between LanguageResource and JSON

resources/build/increment-version.sh
Time for a little "`lerna`-fu", as it were.
This PR leverages the [versioning `npm` script](https://github.com/keymanapp/keyman/pull/2997#discussion_r415486289) defined in #2997 (implemented [here](https://github.com/keymanapp/keyman/blob/bd0de177e859df3c84347360bdb29317690ca7c6/package.json#L10)) to auto-update of all our lerna-managed package.json versioning.
It seemed wiser to simply incorporate it as part of the increment-version shell script, rather than try to force it into the TS-based script that manages the other components.
=> feat(common): auto-update for package versioning

windows/src/global/vc/keymansentry.cpp
The manual callstack generation for x64 c++ apps was truncating formatted pointer strings, leading to corrupted stack traces in error reports.
=> fix(windows): sentry x64 stacks truncated pointers

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
Follow-on to #2950 (Use back button to minimize System Keyboard)
A user reported 
> When I tested it out, I found that hitting Back now hides the keyboard, but hitting Back again and multiple times does nothing, the UI that was up is not dismissed. It seems Keyman is still active somehow and capturing Back.
>
>I added the following check and am now able to hit Back to exit to previous UI (browser, Signal, etc)
```java
if (isInputViewShown()) {
KMManager.hideSystemKeyboard();
return true;
}
```
* Load Keyman
* From the "Get Started" screen, enable Keyman as a system keyboard
* Open a Chrome browser and browse to a few pages
* With Keyman selected as a system keyboard, start typing
* Hit the back button once (will dismiss the system keyboard)
* Hit the back button a few more times and …
=> fix(android): Fix back button after System Keyboard dismissed

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java, android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java, android/history.md
Cherry-pick  #2950 and #3093 to stable-13.0
This allows the back button to dismiss the system keyboard if shown. Additional back-presses revert to default UI behavior.
As a throw-in, I made the same change to KMSample2
* Load Keyman
* From the "Get Started" screen, enable Keyman as a system keyboard
* Open a Chrome browser and browse to a few pages
* With Keyman selected as a system keyboard, start typing
* Hit the back button once (will dismiss the system keyboard)
* Hit the back button a few more times and verify the browser goes back with each press
=> fix(android): Back button to dismiss system keyboard

android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java
Bring in the changes from #2950 and #3093 to KMSample2
This PR has the back button to dismiss the KMSample2 system keyboard
=> fix(android): Back button to dismiss KMSample2 system keyboard

oem/firstvoices/android/.gitignore, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java
Bring in the changes from #2950 and #3093 to the FV Android app
=> fix(oem): Back button to dismiss FV Android system keyboard

oem/firstvoices/ios/Cartfile, oem/firstvoices/ios/Cartfile.resolved, oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj, oem/firstvoices/ios/FirstVoices/FVKeyboardList.swift, oem/firstvoices/ios/FirstVoices/KeyboardInfo.swift, oem/firstvoices/ios/build_common.sh
Depends on #3041, but since I'm not likely to be the one merging it, I decided to implement its fixes separately from that branch.
Is a 🍒-pick of #3105 for master, where #3041's equivalent (#3040) has already been merged.
#3041 doesn't provide the app with the same keyboard metadata as before, so I've tweaked the typings to match the new format.
Outside of that, there was just a bit of project linkage to the dependencies that had to be resolved.
I also threw in a bit of work on `build_common.sh` that will facilitate running the app in the Simulator for `-debug` builds.  There was also some local certificate manipulation, but I'd rather not include that, as it might break our CI builds.
----
One issue still remains:
The red bar expected for the FV banner is missing due to CSS misalignments …
=> fix(ios/oem): Fixes FV app's system keyboard 🍒

oem/firstvoices/ios/Cartfile, oem/firstvoices/ios/Cartfile.resolved, oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj, oem/firstvoices/ios/FirstVoices/FVKeyboardList.swift, oem/firstvoices/ios/FirstVoices/KeyboardInfo.swift, oem/firstvoices/ios/build_common.sh
A few changes were needed to get the FV app up and running again.
For one, #3040 didn't provide the app with the same keyboard metadata as before, so I've tweaked the typings to match the new format.
Outside of that, there was just a bit of project linkage to the dependencies that had to be resolved.
I also threw in a bit of work on `build_common.sh` that will facilitate running the app in the Simulator for `-debug` builds.  There was also some local certificate manipulation, but I'd rather not include that, as it might break our CI builds.
----
One issue still remains:
The red bar expected for the FV banner is missing due to CSS misalignments within KMW.
Adjusting the `top: 6px` entry (for the KMW-based banner) to something more like `3px` for this particular case fixes it, but that …
=> fix(ios/oem): Fixes FV app's system keyboard

windows/src/engine/Makefile, windows/src/engine/keyman/Makefile, windows/src/global/delphi/chromium/Keyman.System.CEFManager.pas
When Sentry is trying to shutdown an app which has CEF windows active, the main process can hang waiting for the CEF renderer etc processes to shutdown. Instead, we now rely on the child (CEF renderer etc) processes to shutdown when their parent process aborts, with a watchdog thread, and  then abandon everything in the parent process with ExitProcess. This is more reliable, especially with nastier crashes like memory corruption or stack corruption.
=> fix(windows): sentry cef shutdown interactions

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/KeyboardController.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LanguageResource.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java
Follow-on to #3079 
This adds a controller to start managing the installed keyboards list.  The intention in a future PR is to replace the processing of [KeyboardPickerActivity.keyboardslist](https://github.com/keymanapp/keyman/blob/master/android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java#L57) with KeyboardController methods.
The installed keyboards list is also migrated to `keyboards_list.json`. (Easier to maintain than keyboards_list.dat)
=> feat(android): Migrate installed keyboards list to keyboards_list.json

resources/git-hooks/commit-msg
This change allows a different project to override the definitions
by providing a local `commit-msg-defs` file while still sharing the
`commit-msg` hook. Other projects might have a different set of
scopes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/3112)
=> chore: Allow to override hook defs

oem/firstvoices/ios/FirstVoices/FVKeyboardList.swift, oem/firstvoices/ios/FirstVoices/KeyboardInfo.swift
A :cherries:-pick of #3135.
**Note**:  Is based on #3109.
=> fix(ios/oem): Fixes keyboard metadata decoding 🍒

common/core/web/input-processor/src/text/inputProcessor.ts, common/core/web/keyboard-processor/src/keyboards/activeLayout.ts, common/core/web/keyboard-processor/src/keyboards/keyboard.ts, common/core/web/keyboard-processor/src/text/kbdInterface.ts, common/core/web/keyboard-processor/src/text/keyEvent.ts, common/core/web/keyboard-processor/src/text/keyboardProcessor.ts, common/core/web/keyboard-processor/src/text/systemStores.ts, common/core/web/tools/recorder/src/index.ts, common/core/web/tools/recorder/src/nodeProctor.ts, common/core/web/tools/recorder/src/proctor.ts, common/core/web/utils/src/deviceSpec.ts, common/core/web/utils/src/index.ts, web/bulk_rendering/tsconfig.json, web/source/dom/preProcessor.ts, web/source/kmwdevice.ts, web/source/osk/oskManager.ts, web/source/osk/visualKeyboard.ts, web/tools/recorder/browserProctor.ts
As a followup to #3130, this PR renames `text.EngineDeviceSpec` to `utils.DeviceSpec`.  It's really more of a common utility type across the Web codebase than anything directly text-related.  As this type was only introduced during the Alpha, now's the time to perform little polishes like this before they become cemented.
It was also overly verbose; "EngineDeviceSpec" was simply the first decent name I could come up with during KMW's recent refactoring, as I was too worried at the time about confusing it with `com.keyman.Device`.  I feel that a simple `DeviceSpec` still accomplishes this while feeling cleaner, matching its use for `com.keyman.Device.coreSpec` - the property that returns the matching `DeviceSpec` for the detected device.
=> refactor(web/engine): renames DeviceSpec, moves to utils

windows/src/ext/sentry/Sentry.Client.pas
Fixes #3004. Fixes a crash when Keyman Developer starts
by double-clicking an associated file type in Explorer.
=> fix(developer): crash when developer starts

common/core/web/utils/package.json, common/core/web/utils/src/tsconfig.json
It would be useful if the `index.d.ts` was usable in other packages. This PR:
1. builds an `index.d.ts`
2. lists it in the `package.json` as the types of this package
3. runs the build automatically _before_ the package is "published"; in this case, during a `lerna bootstrap`. This makes the `index.d.ts` available to all internal packages that depend on this one.
Note: merging this would help out #3128 a lot ^.^
=> change(web/utils): add and distribute type declaration

lerna.json
Fixes our failed build triggers from last night.
Turns out, `lerna version` isn't functioning properly for us when a package doesn't actually have a package-lock.json file.  That said... if we've marked a package as deprecated, should we actually be updating its version?
```
[01:00:59]
lerna info ci enabled
[01:00:59]
lerna info Executing command in 10 packages: "git add package.json package-lock.json"
[01:00:59]
warning: LF will be replaced by CRLF in common/core/web/tools/sentry-manager/package-lock.json.
[01:00:59]
The file will have its original line endings in your working directory
[01:00:59]
warning: LF will be replaced by CRLF in common/core/web/tools/sentry-manager/package.json.
...
[01:00:59]
warning: LF will be replaced by CRLF in common/models/types/package.json.
[01:00:59] …
```
=> fix(common): drops version updates for deprecated common/lexical-model-types

resources/build/trigger-definitions.inc.sh
**NOTE**: I have NO IDEA what I'm doing!!!!
When I was `git grep`'ing yesterday for `lexical-model-types`, I noticed this file. I assume this + `run-required-test-builds.sh` figures out when to run tests on TeamCity. So I updated the paths to include the new directory for all of the models stuff, namely, `common/models`. Feel free to reject or modify this PR as required!
=> chore(common/resources): add `common/models` to build trigger definitions

resources/gosh/package-lock.json
When the package rework for our "Good Ol' Shell" (`gosh`) was put in place, no `package-lock.json` was checked in.  While it may not have seemed necessary due to its lack of dependencies, `lerna` expects it to exist when doing versioning updates.
From last night's [build release trigger script](https://build.palaso.org/viewLog.html?buildId=207276&buildTypeId=Keyman_TriggerReleaseBuildsMaster&tab=buildLog):
```
[01:00:48] - @keymanapp/resources-gosh: 14.0.81 => 14.0.82 (private)
...
[01:00:49]> lerna "exec" "--concurrency" "1" "--" "git" "add" "package.json" "package-lock.json"
...
[01:00:50]
fatal: pathspec 'package-lock.json' did not match any files
[01:00:50]
lerna ERR! git add package.json package-lock.json exited 128 in '@keymanapp/resources-gosh'
```
Since it was unable to `git …
=> fix(common): adds package-lock.json for gosh package

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, web/source/osk/visualKeyboard.ts
Fixes #3035.
Also fixes an error discovered while investigating #3038.  I couldn't reproduce the original issue, but did find an error that sometimes occurred in an intermediate state during keyboard swaps.  Adding a `null` check was simple enough to remedy that.
=> fix(ios): fixes build warning on Error coersion, fixes logged error for intermediate embedded state

common/models/types/build.sh
Build script was missing a minor but important tweak after the `models-types` rename & relocation - a simple `../`.
But, while we're here... standard `build.sh` header time.
Fixes the following error for Web's `master` build configuration:
```
[01:13:41]
Step 4/4: Publish Lexical Model Types NPM modules (Command Line) (4s)
[01:13:41]
Starting: C:\BuildAgent\temp\agentTmp\custom_script1069343044492610800.cmd
[01:13:41]
in directory: C:\BuildAgent\work\281d1bc6d3c88cfd\keyman\common\models\types
[01:13:42]
build.sh: line 10: ../../resources/shellHelperFunctions.sh: No such file or directory
[01:13:43]
build.sh: line 10: ../../resources/shellHelperFunctions.sh: No such file or directory
[01:13:44]
build.sh: line 10: ../../resources/shellHelperFunctions.sh: No such file or directory …
```
=> fix(common/models/types): fixes models-types build script, sets std header

web/source/build.sh
Fixes #3150.
Using the changes from #3162 as a base, this modifies Web's `build.sh` to do Sentry uploads only when appropriate.
=> change(web): Selective Sentry uploads

ios/engine/KMEI/KeymanEngine/Classes/HTTPDownloader.swift
As it turns out, there was little reason to implement all the `URLSession*Delegate` stuff, and actually some loss in doing so when it comes to unit testing.
This PR aims to simplify the class by removing the `Delegate` interference, facilitating unit testing that will come in a follow-up PR.
=> refactor(ios/engine): Polishes HTTPDownloader to prep for unit testing

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/HTTPDownloadRequest.swift, ios/engine/KMEI/KeymanEngine/Classes/HTTPDownloader.swift, ios/engine/KMEI/KeymanEngineTests/HTTPDownloaderTests.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/ExpectationDownloaderDelegate.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/URLSessionDownloadTaskMock.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/URLSessionMock.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/TestUtils.swift
Continuing from the work #3179, this PR implements unit testing against the `HTTPDownloader` at the core of iOS's resource download requests.
As there's already a lot to review here, I'll leave development of unit tests against the downloading-related `ResourceDownloadQueue` and `ResourceDownloadManager` for other PRs.
=> feat(ios/engine): HTTPDownloader unit testing

linux/keyman-config/keyman_config/keyboard_details.py, linux/keyman-config/keyman_config/view_installed.py
This change disables the uninstall, about, and help buttons in km-config if the list of installed keyboards is empty.
This fixes #3181.
This change also increases the padding on the inside of the About window so that there is more whitespace between the UI elements and the window border.
=>  fix(linux): Disable buttons if no keyboard installed

developer/js/.npmignore, windows/src/developer/inst/copydev.in
Replaces #3119 as a patch to #3071.  Turns out that approach had a number of continuing issues, not the least of which would be major complications with our newfound use of npm `prepare` scripts breaking during the `--production` bootstrap.
Instead, a paradigm shift is in order - why aren't we relying on existing `npm` functionality to package the model compiler?  In particular:  `npm pack`, which basically does `npm publish`, but just to a local file - which is thus precompiled and stripped down to the bare essentials.
Obviously, that's a bit too far, and then there's the fact that we _would_ run into problems installing the unpublished local copy of `@keymanapp/models-types`... if it weren't for the fact that we can `npm install` the packed tarball, which then overrides remote lookups …
=> change(developer): packs ModelCompiler via npm pack, 7-zip

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/QRCodeUtil.java
For `master`, this is a trivial rename from `QR_BASE`  to `QR_CODE_URL_FORMATSTR` to convey it's a format string.
The intent for this PR is to later cherry-pick to `stable-13.0` to fix the shared QR Code.
=> modify(android/engine): Clean up naming for formatting QR code URL

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/QRCodeUtil.java, android/history.md
Cherry-pick of #3187 to stable-13.0
This fixes the format string for generating the QR code link to share keyboards.
Screenshot with the fix
link goes to https://keyman.com/go/keyboard/khmer_angkor/share
=> fix(android/engine): Fix generation of QR code

ios/engine/KMEI/KeymanEngineDemo/MainViewController.swift, resources/shellHelperFunctions.sh
So, turns out a late tweak on #3071 wasn't implemented quite right, according to our most recent iOS Master build:
```
[01:33:25]
> root@ bootstrap /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman
[01:33:25]
> lerna bootstrap -- --no-optional "--concurrency=1"
[01:33:25]
[01:33:26]
lerna notice cli v3.21.0
[01:33:26]
lerna info ci enabled
[01:33:26]
lerna info Bootstrapping 12 packages
[01:33:26]
lerna info Installing external dependencies
[01:33:26]
lerna info hoist Pruning hoisted dependencies
[01:33:26]
lerna info hoist Finished pruning hoisted dependencies
[01:33:26]
lerna info hoist Finished bootstrapping root
[01:33:29]
lerna ERR! npm install --global-style --no-save --no-optional --concurrency=1 exited 254 in '@keymanapp/input-processor'
[01:33:29]
lerna ERR! npm install …
```
=> fix(ios): fixes lerna concurrency workaround and missing func reference

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtil.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudCatalogDownloadCallback.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtilTest.java
This is a pre-req in #2708 before lexical-model package updates can be retrieved  from api.keyman.com
Currently, `ModelPickerActivity()` is only displaying **installed** models.
Since there's a TODO to download associated lexical model after downloading a cloud keyboard package, only the default nrc.en.mtnt model is ever getting installed.
This PR updates `ModelPickerActivity()` so it displays **available** models (sourced from the lexical model cloud catalog and lexical model packages that exist on the filesystem). The lexical model package on the filesystem could be previously installed, since uninstalled.  
This way, the user can choose the language, browse the associated models, and click on them to install the lexical model package.
From a clean install of Keyman
1. From the …
=> fix(android/engine): Use available models for ModelPickerActivity()

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #3102
This adds a user-requested system globe action `GLOBE_KEY_ACTION_SHOW_SYSTEM_KEYBOARDS` that brings up the Android input method picker.
This action can only be set for `KEYBOARD_TYPE_SYSTEM`. 
Tested by modifying SystemKeyboard.onCreate() to
```java
KMManager.setGlobeKeyAction(KeyboardType.KEYBOARD_TYPE_SYSTEM,
KMManager.GlobeKeyAction.GLOBE_KEY_ACTION_SHOW_SYSTEM_KEYBOARDS);
```
(not included on this PR).
A screenshot of hitting the system globe button
I've added this to the 14.0 migration wiki, and documented the help.keyman.com change below
=> feat(android): Add system globe action to show system keyboards

windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
Works around #119 on the compiler side. This normalises the touch layout file in the compile phase, fixing integers which should be strings, etc. This means that we no longer need to correct the issue in the Engine; a rebuild of affected keyboards is sufficient (although of course we'll need a version bump in order for them to be distributed.
Given this is an isolated fix, I think I will cherry-pick this to 13.0, after testing to make sure that the result doesn't break existing keyboards -- it is low risk though!
=> fix(developer/compilers): normalise touch layout on compile

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Keyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/BCP47.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/BCP47Test.java
Fixes #2972
Add a BCP47 utility to check if two language IDs are equivalent.
For now, this simple utility only handles language IDs, and not intended to parse BCP 47 subtags.
=> feat(android): Add utility to check BCP47 equivalence

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/KeyboardKeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/LexicalModelKeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableLexicalModel.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/LanguageResource.swift, ios/engine/KMEI/KeymanEngine/Classes/Storage.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPFile.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPLanguage.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPLexicalModel.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPMetadata.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPOptions.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPResource.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPSystem.swift, ios/engine/KMEI/KeymanEngineTests/FileManagementTests.swift
Continues on from the work in #3205.
I figured I'd put this up for review before I modify the core aspects (`parseKbdKMP`, `parseLMKMP`) even further beyond recognition than I already have.
The goal here:  as seen after a bit of abstraction work, `parseKbdKMP` and `parseLMKMP` are nigh-identical in what they do, with just one point of distinct logic separating them.  I've preserved all the logic exactly, with one exception:
- `FileManager.default.createDirectory` may be called multiple times for the same directory.  Fortunately, our call is idempotent, so it still yields the same result.
The next step is to merge the two implementations into a single method, maintaining the original functions as helpers for legacy purposes.  This will then pave the way toward selective resource …
=> refactor(ios/engine): Abstraction of KMP installation methods

linux/keyman-config/keyman_config/downloadkeyboard.py, linux/keyman-config/keyman_config/ibus_util.py, linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/keyman_config/view_installed.py, linux/keyman-config/km-config
This change modifies DownloadKmpWindow and InstallKmpWindow so that
they are modal dialogs. This will cause them to show up in front of
the km-config window and will prevent accidentally open multiple
download windows.
This change also fixes an unused method in ibus_util that was using
a variable that got renamed previously.
=> feat(linux): Make two windows modal dialogs

linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/keyman_config/keyboard_details.py, linux/keyman-config/keyman_config/view_installed.py, linux/keyman-config/keyman_config/welcome.py
This fixes the problem where typing inside of `km-config` is not possible after installing a keyboard.
This fixes #2087.
This PR also adds a comment about the limitations of WebKit2. It also converts two additional windows to modal dialogs.
=> fix(linux): Restart km-config after installing keyboard

ios/engine/KMEI/KeymanEngine/Classes/Extension/UserDefaults+Types.swift, ios/engine/KMEI/KeymanEngine/Classes/KeyboardKeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/ResourceInfoViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LexicalModelKeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Migrations.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/FullKeyboardID.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/FullLexicalModelID.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableLexicalModel.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/LanguageResource.swift, ios/engine/KMEI/KeymanEngine/Classes/Notification/Notifications.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Storage.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPLexicalModel.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPResource.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Migrations.swift
Swift generics are... really weird and cumbersome.  Especially once `protocol`s get involved.
Most of the changes contained in this PR are to approximate Java-style generic polymorphism regarding language resources and how we key them.  Alas, Swift lacks the ability to "wildcard" its generics, so "type erasure" is necessary - note the `Any*` classes.
Some "fun" Swift reading along those lines:  https://medium.com/@bobgodwinx/swift-associated-type-design-patterns-6c56c5b0a73a
- I followed the "Shadow Type Erasure" strategy where possible.
All of this is to allow a few things:
- `KeymanKeyboardPackage.installables` is of type `[[InstallableKeyboards]]` - something reasonably clear (though I could improve its docs) and exposable as an API on packages.
- Likewise, `KeymanLexicalModelPackage` …
=> refactor(ios/engine): Language resource + keying polymorphism

.github/labeler.yml, .github/workflows/labeler.yml, resources/scopes/README.md
Using GitHub's labeler action to apply appropriate labels automatically based on paths. Fixes #3231.
=> chore: labeler

ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift, ios/engine/KMEI/KeymanEngineTests/FileManagementTests.swift, ios/engine/KMEI/KeymanEngineTests/KeymanPackageTests.swift, ios/keyman/Keyman/Keyman/AppDelegate.swift, ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift
While preparing for some of the upcoming file management migration work for the iOS KeymanEngine, I noticed something interesting:  despite using a lot of asynchronous method signatures, the entire process has _always_ been synchronous.
This PR looks to make that far more explicit by simplifying the code base, deprecating the synchronous-looking method signatures, and adding explicitly synchronous analogues in their place.  This makes the control flow _significantly_ simpler to follow, both in current and upcoming code.
Note how the + and - numbers are nearly identical, and that's after adding deprecation annotations onto the (new) stubs that maintain the original method signatures along with duplicated documentation comments.  If we didn't need those, this would easily be more concise …
=> refactor(ios/engine): explicitly synchronous Package processing

ios/engine/KMEI/KeymanEngine/Classes/KeyboardKeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/LexicalModelKeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableLexicalModel.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/LanguageResource.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPLexicalModel.swift, ios/engine/KMEI/KeymanEngineTests/KMPJSONTests.swift, ios/engine/KMEI/KeymanEngineTests/KeymanPackageTests.swift
A little something needed for proper migration... that probably should have already been in-place anyway.
=> feat(ios/engine): KeymanPackage now parses its ID

windows/src/developer/TIKE/xml/layoutbuilder/builder.js
Fixes #2658. Double-clicking on a layer change key will now update the combo box at the top of the editor appropriately.
=> fix(developer/ide): double click to change layer update combo

linux/keyman-config/debian/control
This change adds `onboard` as a recommended package. This will
install it by default for most users, unless they told their
package manager not to automatically install recommended packages.
This implements part of #3223.
=> feat(linux): Add onboard as recommended package

ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Migrations.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
While this doesn't fully fix up the FV app for 14.0, this should provide a decent stopgap for any 3rd party libraries that have been relying on use of the now-deprecated `preloadFiles` command to add resources.
As `preloadFiles` only, well, _preloads_ the files, we need to wait for the matching `addKeyboard`/`addLexicalModel` call in order to obtain the `LanguageResource` key necessary for migration.
-----
In regard to the FV app, this will take effect on the next in-app keyboard selection.  However, the FV app itself does not bother with migrating resources (direct use of `Migrations`) in any fashion, so it won't automatically generate kmp.json files for all available keyboards - not even if installed from an earlier version.
Of course, for a _proper_ FV app, we should be installing the …
=> fix(ios/engine): migration of preload-sourced resources

resources/web-environment/package-lock.json
Adds a simple package-lock.json for the new `@keymanapp/web-resources` packages so that our lerna-based version updates don't fall over.  
(Refer to #3171, which fixed a similar situation in the recent past.)
=> fix(common/resources): web-environment package-lock.json

ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
Looks like I got a bit over-eager with some of the package adjustments on iOS. I failed to realize that `keyman.registerStub` would mutate the stub's ID when packages are specified, which caused the package-id to be re-prepended before the `setKeyboard` call.  This went live with the package-based rework in 14.0.95, so it's not been in the wild for long.
Basically, I ended up with `khmer_angkor::khmer_angkor::Keyboard_khmer_angkor` because I re-prefixed the ID with the code being removed, which didn't match the internal single-prefixed version.  
Short version:  Bug = accidental `<package-id::package-id::keyboard-id>` did not match `<package-id::keyboard-id>`.
=> fix(ios/engine): fixes keyboard swapping

ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelPickerViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift, ios/engine/KMEI/KeymanEngineDemo/MainViewController.swift, ios/keyman/Keyman/Keyman/MainViewController.swift
This PR serves two purposes:
- Resources will no longer be installed through a `Notifications` callback.
- Some related code may still require them, such as automatically setting newly installed keyboards as active.
- Removes a lot of old, unreferenced `Notifications`-related code from the codebase.
- The biggest trigger:  `private var launchURL` hasn't seen use since 10.0 and was always `nil`.
- Its last known non-`nil` use may be seen [here](https://github.com/keymanapp/keyman/blob/stable-10.0/ios/keyman/Keyman/Keyman/MainViewController.swift#L486).
- Noting its method's comment, we actually _did_ remove said method in 11.0.
=> refactor(ios/engine): Notification rework prep, simplification

android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsInstallActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageActivity.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectPackageActivity.java, android/KMAPro/kMAPro/src/main/res/values/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/KeyboardController.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java
Follow-on to #3245 
This PR implements the menu to **"Add language to installed keyboard"**
When the user selects this menu, they're given a list of installed package ID / keyboard ID pairing.  When selecting a keyboard, they are then given a list of associated languages (from kmp.json). 
* Languages that aren't installed have an arrow and can be clicked to install
* Installed languages have a check and are disabled.
* If the entire language list is installed, the title reflects that.
------------------------------
Each entry is an installed keyboard name and package ID
(updated with installed languages being disabled)
Different title if all languages installed
(original screenshot showed list of uninstalled languages)
@MakaraSok 
1. Load the PR test build
2. From the "Settings" menu, …
=> feat(android): Implement menu to add language for installed keyboard pkg

mac/build.sh
Follow-up on #3264 because I missed the second call to altool in the script.
=> fix(mac): altool second call report ci errors

ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift, ios/keyman/Keyman/Keyman/MainViewController.swift
As it turns out, #3261 removed the last reference to `MainViewController.performAction(from:)`.  Since its use was dependent on `launchURL` being non-`nil`, it also hasn't seen use since 11.0.
I didn't chase down a version for the other removed block, but there were no references to it, either - parallel versions exist in the subviews that do the actual installation prompts.
=> refactor(ios/engine): more dead code removal

linux/libkmfl/debian/control
The first line of the description shows up in the Software Update tool. The previous description didn't really tell what it was referring to since the name of the package is not directly visible at that point.
=> feat(linux): Improve Linux package description

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift
This PR finally starts to implement completion-block callbacks for KeymanEngine's download requests.  At this stage of implementation, I've managed to refactor all of the download-related notifications (save for resource updates) out of `ResourceDownloadQueue` and have placed them in closures defined within `ResourceDownloadManager`.
The plan for the next PR is to move the actual downloaded-resource installation code into completion blocks, which will be defined where the original download requests are generated.  The completion blocks / closures are already receiving the downloaded `KeymanPackage`; they're just not being used yet, as getting the notification stuff right was already complex enough.
=> refactor(ios/engine): Download notifications via completion blocks

ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageDetailViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageLMDetailViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelPickerViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift
This extracts the data-management aspects of resource installation from the various KeymanEngine views and defines it in the same class as the actual installation methods.  I've set things up with a few functions that configure installation closures that may be set to run when downloads complete.  This helps to ensure installation consistency regardless of origin in the view hierarchy while also allowing further configurability / customization as needed.
This doesn't add unit tests for all the recent downloader-refactoring work; the plan is to address that once KeymanEngine is downloading keyboard KMPs.  At that point, `ResourceDownloadQueue` will be far more stable.  While it's already more test-friendly than before, use of keyboard KMPs will improve things on that level as well.
=> refactor(ios/engine): Resource-download installation closures

.flake8, linux/keyman-config/keyman_config/downloadkeyboard.py, linux/keyman-config/keyman_config/gnome_keyboards_util.py, linux/keyman-config/keyman_config/ibus_util.py, linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/uninstall_kmp.py, linux/keyman-config/keyman_config/welcome.py, linux/keyman-config/tests/test_gnome_keyboards_util.py, linux/keyman-config/tests/test_ibus_util.py, linux/keyman-config/tests/test_install_kmp.py, linux/keyman-config/tests/test_uninstall_kmp.py
This change adds the keyboard to the Gnome input sources after
installing the .kmx file, and removes it on uninstall.
This implements #2728.
=> feat(linux): Install keyboard on Gnome

linux/keyman-config/keyman_config/install_kmp.py
We have to restart IBus even when installing keyboards in Gnome.
Otherwise the new keyboards won't show up in the list of input
sources.
This fixes #3283.
=> fix(linux): Always restart IBus when installing keyboard

linux/keyman-config/keyman_config/kvk2ldml.py
This change fixes a crash that happened installing the
BJCreeUni (east) keyboard. This keyboard contains a OSK that
gets converted to LDML.
This fixes #3208.
=> fix(linux): Fix crash converting kvk into LDML

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/Queries/Queries+PackageVersion.swift, ios/engine/KMEI/KeymanEngine/Classes/Queries/Queries.swift, ios/engine/KMEI/KeymanEngineTests/HTTPDownloaderTests.swift, ios/engine/KMEI/KeymanEngineTests/QueryPackageVersionTests.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/URLSessionDataTaskMock.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/URLSessionMock.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Queries.swift, ios/engine/KMEI/KeymanEngineTests/resources/Queries.bundle/package-version-case-1.json
While currently not connected to anything within KeymanEngine, this PR adds support for use of our [package-version API](https://help.keyman.com/developer/cloud/package-version/1.0/) endpoint.  A unit test proving the code works has been included.
The likely best path forward for downloading KMPs for keyboards instead of JS will involve use of this endpoint.  It'll be useful long term for resource updates but also in the short-term for finding keyboard KMPs.
=> feat(ios/engine): package-version query implementation

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMPBrowserActivity.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/KMManagerTest.java
For pre-release builds (`alpha` and `beta` tier), use the keyboard search from the staging site
https://staging-keyman-com.azurewebsites.net/keyboards
=> fix(android): Use tier to determine keyboard search host

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift
After some of the recent download-rework PRs, a small bit of extra work allows us to remove some now-dead code.
This also contains traces of setup code for mocked downloads for unit tests, although none are added at this time.
=> refactor(ios/engine): Resource download cleanup and mocking prep

ios/engine/KMEI/KeymanEngine/Classes/Model/LanguageResource.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift
While preparing to start downloading packages based solely on a resource's ID, I noticed a problem with the current download management within KeymanEngine - it still requires full resource metadata (because of cloud keyboard installs).  Fortunately, with a little work, that can be dropped with no downsides.
- If the user were to perform a keyboard search, that search would yield the package filename, possibly with the resource's id & preferred language code... but not the rest of `InstallableKeyboard`'s metadata.
- As a result, KeymanEngine will have less data from the search than it had with the old cloud-based installs.  This PR adjusts the downloading infrastructure accordingly.
The trickiest aspect of this was the requirement to rework update notifications at the same time; the …
=> refactor(ios/engine): ID-based download tracking, update notification rework

common/core/web/input-processor/src/text/prediction/languageProcessor.ts
An important thing to remember with TS type definitions:  `var a: 10` means that the variable's type is constrained to only allow initialization with `10`.  It does _**not**_, however, actually initialize it.
This bug was found while investigating https://community.software.sil.org/t/the-more-i-type-the-slower-the-prediction-speed/3552.  In KMW's currently-published versions, including stable-13.0, the buffer is currently broken due to the defined constant's lack of actual initialization:
This basically serves as a memory leak, as old transcriptions are kept around in memory.  In reference to the linked posting, two pages' worth of text should be into the thousands of entries.  Considering that transcriptions are _also_ buffered with their corresponding fat-finger alternate distributions, …
=> fix(common/core/web): fixes transcription buffer cap

android/KMAPro/kMAPro/src/main/res/values/dimens.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMPBrowserActivity.java
[description edited per review comments]
~This small PR adjusts the language query (if given) to specify BCP 47 match.~
Also makes the PackgeActivity title font size smaller so the string "Install Keyboard Package version X.Y.Z" fits
=> fix(android): Resize PackageActivity title text

android/KMEA/build.sh
#3300 tightened up the Android `build.sh` scripts.  But it caused release builds to fail because `DEBUG_BUILD` is an unbound variable.
This one-liner fixes the build.
=> fix(android/engine): Fix unbound variable in build script

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
When installing cloud keyboard packages that have a specified language ID, this PR fixes the feature to download the associated dictionary package.
Some things to note about the current staging keyboard search:
* Keyboard searches won't specify language ID unless it's a language query (`q:l:id:...`)
* Search results currently use `tag=` for language ID, but eventually production will use `bcp47=`.
* Language searches involving script (e.g. `glk-arab`) currently return a tag `glk`. If the associated dictionary package (`sil.glk-arab.ptwl1`) doesn't include that tag (it only lists `glk-arab`), the dictionary package won't get installed.
@MakaraSok 
1. Load the test build
2. Install fv_sencoten from the cloud
* From "Settings" --> "Install Keyboard or Dictionary" --> "Install from …
=> fix(android/app) Download associated dictionary when installing cloud keyboard package

android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/KeyboardController.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java
Fixes #3311 
This PR creates a utility `LogJSONException()` which provides additional logging to Sentry if there's issues reading the installed keyboards list.
Now we'll get reports if the installed keyboard list is null.
If the file has content but fails to parse, we'll get the contents of `installed_keyboards.json` written to Sentry.
=> feat(android): Add additional info on installed keyboards exceptions

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/HTTPDownloader.swift, ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift, ios/engine/KMEI/KeymanEngineTests/HTTPDownloaderTests.swift, ios/engine/KMEI/KeymanEngineTests/ResourceDownloadManagerTests.swift, ios/engine/KMEI/KeymanEngineTests/ResourceDownloadQueueTests.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/ExpectationDownloaderDelegate.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/URLSessionDownloadTaskMock.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/URLSessionMock.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/TestUtils.swift
This PR is centered around the new function `downloadPackage(forFullID:from:)`, which is designed to facilitate download of any supported package type from a known URL.  (The URL should be sourced separately, which is where query code comes in.)  The method supports both keyboard and lexical model downloads, the former of which took a little work.  This also adds a "temporary" download naming scheme, only overwriting existing files when a download is confirmed to be successful.
All packages downloaded by this method will have a copy stored within the app's Documents directory, allowing users to share KMP files directly with others or to install other resources (language pairings) from them at a later time via the "Install From File" option.
When writing user tests, it became apparent that …
=> refactor(ios/engine): Centralized package download utility function

ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/LanguageResource.swift, ios/engine/KMEI/KeymanEngine/Classes/Queries/Queries+PackageVersion.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngineTests/QueryPackageVersionTests.swift
In #3327, use of `LanguageResourceFullID`s in the package-version query was starting to bother me, since those specify language IDs that aren't useful as part of package lookups.  These get in the way when trying to simply but uniquely identify packages in need of updating.
Enter `KeymanPackage.Key`, which is more explicit about being language-agnostic and is designed for use in keying "dictionary" (hash-map) structures.
=> refactor(ios/engine): hashable package keys

ios/engine/KMEI/KeymanEngine/Classes/Model/Version.swift, ios/engine/KMEI/KeymanEngineTests/VersionTests.swift
Turns out custom use of `==` in Swift is a little trickier to get right than was first thought.  It appears that the complexity arises because `Version` is a `class`, and thus `isEqual` also needs to be defined in order for things to work correctly for optionals.  `struct`s do not have to override this method, as they aren't derived from `NSObject`, unlike `class`es.
=> fix(ios/engine): version equality

android/KMAPro/build.sh, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java, oem/firstvoices/android/.gitignore, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVShared.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java, oem/firstvoices/android/build.sh
From discussion on [3322](https://github.com/keymanapp/keyman/pull/3322#pullrequestreview-445130562)
> We're going to need to add the nrc.str.sencoten model as well I think? That could go in a separate PR too.
This PR adds nrc.str.sencoten model to the FV Android app.
Since SystemKeyboard needs to adjust for banner height, I also incorporated other changes from KMAPro:
* Select numeric layer if applicable
* Disable predictions if entering a hidden password field
* FVShared updated to rebuild active keyboards list using info from kmp.json.
* Add nrc.str.sencoten and register if no models exist
Previous versions of the FV app had assigned languageID "en" to all the keyboards. This PR does not handle any migrations to fix those language ID's.
nrc.str.sencoten model will only be available …
=> feat(android/oem): Add nrc.str.sencoten model and update SystemKeyboard from KMAPro

developer/js/source/lexical-model-compiler/build-trie.ts, developer/js/tests/test-parse-wordlist.ts
This reworks the file loading strategy for wordlists to merge duplicate terms found in wordlists during the load, and sum their weights. This also helps to resolve situations where there are words with different normalization forms in the wordlist. See #2880 for more on this (this PR mitigates but doesn't completely solve the issue as reported).
This was reported initially on the Community Forum at https://community.software.sil.org/t/lexical-models-how-to-influence-predictive-text-behaviour/3597/5.
While the pattern I have used is naive (in terms of its duplicate detection strategy) and not the most performant (in terms of its search), it is also probably the simplest change I could come up with.
I have updated test cases accordingly.
(On performance: the wordlist would probably be quite …
=> fix(developer/compilers): merge duplicate words during compile

developer/js/package-lock.json, developer/js/package.json, windows/src/developer/history.md
So, the current issue we're dealing with in [keymanapp/lexical-models](https://github.com/keymanapp/lexical-models) is actually due to the lexical model compiler's package.json.  In particular, its `install` script, which sees use for both local _and_ remote (distributed) `npm install` commands.
By converting the `install` to a `prepare` script, local development use of `npm install` will now go fetch the latest version of the dependency... but then immediately run the `prepare` script afterward, establishing an `npm link` for development use.
`prepare` will not affect the distributed package, and so this will drop the current `npm link` nonsense when CI compiles models for distribution from [keymanapp/lexical-models](https://github.com/keymanapp/lexical-models).
As current 14.0 …
=> fix(developer): distributed model complier no longer relies on npm link

android/history.md, ios/history.md, web/source/text/prediction/modelManager.ts
This is a handwritten 🍒-pick of #3301.  The underlying files were refactored, but finding the corresponding line in the original source wasn't too difficult, as the responsible constant went completely unchanged between versions.
=> fix(web): properly initializes transcription buffer cap constant 🍒

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #3328 
The Android call to switch system keyboards (while on the lock screen) has been deprecated in Android P to now use [InputMethodService.switchToNextInputMethod](https://developer.android.com/reference/android/inputmethodservice/InputMethodService#switchToNextInputMethod(boolean)) 
This PR updates the call in `advanceToNextInputMode()` accordingly.
=> fix(android/engine): Update deprecated call to switch system keyboard for Android P

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/history.md
Addresses #3328 for stable-13.0
The Android call to switch system keyboards (while on the lock screen) has been deprecated in Android P to now use [InputMethodService.switchToNextInputMethod](https://developer.android.com/reference/android/inputmethodservice/InputMethodService#switchToNextInputMethod(boolean))
This PR updates the call in advanceToNextInputMode() accordingly.
=> fix(android/engine): Update deprecated call to switch system keyboard for Android P 🍒-pick of #3353

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngineTests/ResourceDownloadManagerTests.swift
This PR accomplishes the basic changes needed to convert from downloading just the keyboard JS to downloading its KMP.  This will be necessary to maintain `Manager.downloadKeyboard`, as it never involved any kind of keyboard search or selection.  Doing so also allows us to drop some old WET code!
Note that this PR **breaks** keyboard updates, as the necessary changes to fix that would have caused this PR to balloon in size significantly.  The plan is to tackle that later this week.
=> refactor(ios/engine): keyboard downloads now retrieve KMPs

ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageLMDetailViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift, ios/engine/KMEI/KeymanEngineTests/FileManagementTests.swift, ios/engine/KMEI/KeymanEngineTests/KeymanPackageTests.swift, ios/engine/KMEI/KeymanEngineTests/ResourceDownloadManagerTests.swift, ios/engine/KMEI/KeymanEngineTests/ResourceDownloadQueueTests.swift
Removes some of the old JS-download-specific code and simplifies related parts of the codebase.  A fair number of the changes are also preparation for proper implementation of resource updates, now that both keyboards and lexical models are installed from KMPs.
Keyboard updates are still broken at this point, but this paves the way to resolve that within my planned followup-PR.
=> refactor(ios/engine):  download queue & download state detection cleanup

windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas, windows/src/desktop/setup/Keyman.Setup.System.OnlineResourceCheck.pas, windows/src/desktop/setup/SetupStrings.pas, windows/src/desktop/setup/TntDialogHelp.pas, windows/src/desktop/setup/UfrmInstallOptions.pas, windows/src/desktop/setup/bootstrapmain.pas, windows/src/unit-tests/windows-setup/Keyman.System.Test.InstallInfoTest.pas
If no tier is specified, it uses the tier from the executable version.
=> feat(windows): setup select tier from filename or parameter

ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageDetailViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageLMDetailViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelPickerViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Notification/Notifications.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift, ios/engine/KMEI/KeymanEngineTests/FileManagementTests.swift, ios/engine/KMEI/KeymanEngineTests/ResourceDownloadManagerTests.swift
_**Note**_:  This one's features a number of small-scale breaking changes, but at least they're on things that should be less utilized.  In particular, please note that the FV app still builds, despite there being absolutely zero changes to its code.
---
Try as I might, I couldn't find a way to continue forward with resource updates that didn't involve significantly reworking KeymanEngine's notification scheme.  That stated, the scheme did need a significant overhaul anyway - as of 14.0, it will only be downloading _packages_, and so those are what it should raise notifications about, rather than what those packages contain.
- `keyboardDownloadStarted`, `lexicalModelDownloadStarted` -> `packageDownloadStarted`
- `keyboardDownloadCompleted`, `lexicalModelDownloadCompleted` -> …
=> refactor(ios/engine): package download notifications

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/Model/Version.swift, ios/engine/KMEI/KeymanEngineTests/VersionTests.swift
A small tweak along with a small bug fix to prep for tier-based server selection.
While the main app ("Keyman") was properly getting its tier information set, `KeymanEngine` was not.  The project-file tweak fixes that.
=> fix(ios/engine): engine tier enum, proper detection

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/Alerts.swift, ios/engine/KMEI/KeymanEngine/Classes/KeyboardRepository/APIKeyboardRepository.swift, ios/engine/KMEI/KeymanEngine/Classes/KeyboardRepository/APILexicalModelRepository.swift, ios/engine/KMEI/KeymanEngine/Classes/KeymanHosts.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelInfoViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/ResourceInfoViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/Queries/Queries+LexicalModel.swift, ios/engine/KMEI/KeymanEngine/Classes/Queries/Queries+PackageVersion.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift, ios/engine/KMEI/KeymanEngineTests/KMPJSONTests.swift, ios/engine/KMEI/KeymanEngineTests/KeymanHostTests.swift
A first step to enabling tier-specific domain selection - actually having centralized definitions for those domains.
I'll follow this up with another PR once we've gotten the "staging" site architecture finalized and ready for use.
=> refactor(ios/engine): Centralized Keyman domain definitions

linux/keyman-config/keyman_config/downloadkeyboard.py, linux/keyman-config/keyman_config/gnome_keyboards_util.py, linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/keyman_config/uninstall_kmp.py, linux/keyman-config/keyman_config/view_installed.py, linux/keyman-config/tests/test_install_kmp.py
When installing a keyboard install it under the language the user searched for (if any). This change depends on an API change (cf #1456).
This fixes #3282.
=> fix(linux): Use language from search when installing keyboard

developer/js/source/lexical-model-compiler/build-trie.ts, developer/js/tests/test-parse-wordlist.ts
To produce better error/warning messages, we want the word list parser to know which line of which file it's on. Hence, I refactored the parser to take a `WordListSource` which can either be from memory or from a file name. The parser itself can then consult the `WordListSource` about which file it's working on, and what line number it's processing. Our tests use files in memory, which is supported too but with the filename `<memory>`.
=> refactor(developer/compilers): reading from a wordlist

windows/src/global/delphi/general/httpuploader.pas
This configures the proxy options per Windows settings; we should be able to remove the Proxy Configuration UI from Keyman and simplify in future as well, but this at least gets us over the line for the bootstrap installer.
If necessary, the installer will pop a system dialog prompting for credentials.
Relates to #3339.
=> fix(windows): proxy configuration from system

developer/js/source/errors.ts, developer/js/source/lexical-model-compiler/build-trie.ts, developer/js/tests/helpers/index.ts, developer/js/tests/test-error-logger.ts, developer/js/tests/test-parse-wordlist.ts, windows/src/global/delphi/general/CompileErrorCodes.pas, windows/src/global/inc/Comperr.h
Adds a logging message mechanism to the lexical model compiler.
So now, given a wordlist like this:
```tsv
hello   1
helló   2
helló   3
hello  4
hello   5
```
...we generate the following log messages:
```
wordlist.tsv (3): Warning: 2801 “helló” is not in Unicode NFC. Automatically converting to NFC.
wordlist.tsv (4): Warning: 2802 duplicate word “helló” found in same file; summing counts
wordlist.tsv (5): Warning: 2802 duplicate word “hello” found in same file; summing counts
wordlist.tsv (6): Warning: 2802 duplicate word “hello” found in same file; summing counts
```
I've implemented two new warnings: Mixed normalization forms (which is really just being consistent in using NFC), and duplicate words within the same file. More warnings should be added/adjusted given the guidelines in …
=> feat(developer/compilers): logging errors and warnings in the lexical model compiler

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngineTests/ResourceDownloadManagerTests.swift
Since we're moving to use of an 'evergreen' link format for package downloads, we can safely drop any package-version query usage solely used to find a valid location for the package.
This also allows us to receive a bit more metadata for analytics, as it's specified as part of the URL.
Not done in this PR:
- queries for lexical models return a different link
- package-version queries return different links
While both of the above are planned to be converted to use of the same 'evergreen' link type, it may be worth ignoring those in favor of use of the new `defaultDownloadURL` method, as the app has the most direct access to any relevant analytics metadata.
=> refactor(ios/engine): builds package download links

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift
Man, this keyboard-search rework really is "the gift that keeps on giving."
As it turns out, the "simplest" way to provide nice, clean callbacks from the keyboard-search (see #3384)... kinda requires a bit of concurrency support.  Why?
- Callback 1:  The keyboard search _immediately_ knows what package a user's selected for download.  Easy.
- Callback 2:  It does _not_ immediately know what lexical model best matches that package.  An async model-query fetch is _required_.
While we _could_ wait on the model-query fetch to return before 'returning' from keyboard-search, a poor connection or loss of data could spell a poor user experience.  They'd have to wait for the async fetch to complete... and _then_ have to wait on both downloads.  Also sequential.  This would also be a "hard and …
=> feat(ios/engine): download queue concurrency

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/KeyboardSearchViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift, ios/engine/KMEI/KeymanEngineTests/KeyboardSearchTests.swift
Addresses a noted issue on #3384.
Sometimes we won't know the language tag to use for a package's resources until after it's been downloaded.  For these cases, we need a way to trigger the lexical model "search" after installation, rather than before.  (Admittedly, this was the standard case before #3384 anyway...)  An ideal solution would still allow us to trigger the lexical model "search" before installation when we do have foreknowledge of the language tag... and this PR makes that dream a reality.
When the `keyboardSelectionClosure` denotes an `.untagged` search result, it is provided with a custom-made closure that may be called after the package is installed.
- Providing it with `.none` (which should be used for installation failures) will abort the lexical-model search, calling …
=> feat(ios/engine): support for deferred chaining of lexical model downloads

ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
Aside from the design changes, there are a couple of bug fixes included with these changes:
- Images in a package's welcome.htm now display properly.
- Previously,  the keyboard images in the screenshot below simply never appeared.
- Package-internal links (to pages, pdfs, etc) now work correctly.
Minor additional feature:
- the name of the package is now displayed in the package installer's title bar.  If no "pretty" name is specified within the kmp.json's data (info->name->description), it'll display the package's ID instead.
- Before, the "Khmer Angkor" text between Cancel and Install did not exist.  This is from the name of the _package_, which _may_ (but does not _have to_) correspond to hosted resources.
-----
Finally, the "refactor" component of this PR.  As we've talked about …
=> refactor(ios/engine): package installer tweaks

windows/src/desktop/kmshell/xml/basekeyboard.xsl, windows/src/desktop/kmshell/xml/dialoginfo.xml, windows/src/desktop/kmshell/xml/downloadkeyboard.xsl, windows/src/desktop/kmshell/xml/elements.xsl, windows/src/desktop/kmshell/xml/help.xsl, windows/src/desktop/kmshell/xml/hint.xsl, windows/src/desktop/kmshell/xml/installkeyboard.xsl, windows/src/desktop/kmshell/xml/locale.xml, windows/src/desktop/kmshell/xml/onlineupdate.xsl, windows/src/desktop/kmshell/xml/proxyconfiguration.xsl, windows/src/desktop/kmshell/xml/splash.xsl
Removes Dialog elements from locale.xml and places them in dialoginfo.xml. These may be eliminated entirely at some point.
The next step is to convert locale.xml to strings.xml, now that the non-string data has been removed from locale.xml. (Again, I don't need to do this with the translations because that will be cleaned up automatically when we do the conversion.)
=> refactor(windows): refactor Dialog elements

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
Now that api.keyman-staging.com is available, this updates the cloud queries to use the applicable api.keyman.com site depending n the tier.
* Change from `KMKeyboardDownloaderActivity.kKeymanApiModelURL` to `CloudRepository.API_MODEL_FORMATSTR`
* Change from `KMKeyboardDownloaderActivity.kKeymanApiPackageVersionURL` to `CloudRepository.API_PACKAGE_VERSION_FORMATSTR`
=> feat(android): Use api.keyman-staging.com for pre-release builds

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
Following the reference from https://developer.android.com/training/app-links/verify-site-associations
> When `android:autoVerify="true"` is present on any one of your intent filters, installing your app on devices with Android 6.0 and higher causes the system to attempt to verify all hosts associated with the URLs in any of your app's intent filters.
=> feat(android): Add app association to keyman.com

windows/src/desktop/kmshell/xml/strings.xml
This formats comments in strings.xml so that they are hopefully clearer for translators in the Crowdin interface.
Because Crowdin treats all comments above a `<string>` tag as part of the context, I have removed the section comments and used whitespace instead. The context comments should make it reasonably clear to see the sections when editing strings.xml.
=> chore(windows): cleanup comments in strings.xml

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java, android/README.md
I had a fresh Linux installation, and the project wasn't building because of a missing `super()` call. 
Also updated the README about needing to install `jq` on Linux.
=> fix(android): Fix KMTextView to compile on Linux

android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
Follow-on to #3343 and circling back to a [point](https://github.com/keymanapp/keyman/pull/3343/files#r455287611) @mcdurdin raised in the review 😞 
> That is, if I visit that link from Chrome, will it open Keyman? (It shouldn't -- only the /keyboards/install/ links should)
At the moment, KMPBrowserActivity converts `/keyboards/install` links to the necessary `/go/package/download` for the main app to process.
This PR updates the Android Manifest to associate the Keyman app with `/keyboards/install` links in case an external browser is generating the Keyman keyboard search. This way, the intent routes through the main app to create the `/go/package/download` link and install the keyboard package.
Also tweaks the scheme to include 'http' (all the scheme/host combinations will end up in the …
=> feat(android/app): Associate app with /keyboards/install links

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMPBrowserActivity.java
KMPBrowserActivity should only be handling Keyman `/keyboards/` links. All other links should go to the user's browser.
@MakaraSok 
Install and launch Keyman
1. Access keyboards search via Settings --> "Install Keyboard or Dictionary" --> "Install from keyman.com"
2. Search for a keyboard (e.g. khmer_angkor) and click on the resulting keyboard
3. Click the green button and install the keyboard
4. Verify the keyboard installs
1. Access keyboards search via "Settings" --> "Install Keyboard or Dictionary" --> "Install from keyman.com"
2. Search for another keyboard (e.g. basic_kbdkni) and click on the resulting keyboard
3. Do not install the keyboard. Instead, scroll down to "Keyboard Details" and click Documentation: "Keyboard help"
4. Verify the help link opens in an external user browser …
=> fix(android): Update KMPBrowser to pass external links to user browser

android/KMAPro/kMAPro/src/main/res/values/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/LanguageSettingsActivity.java, android/KMEA/app/src/main/res/values/strings.xml, android/utility/.gitignore, android/utility/i18n-check-unused-strings.sh
Similar to #3412
1. Adds a similar script from Windows to identify unused Android strings (from KMAPro and KMEA strings.xml)
2. Remove the unused strings from strings.xml
As part of the manual cleanup, consolidated the strings `missing_metadata` and `invalid_metadata`.
Also changed string name `model` to a more specific  `model_label`
=> chore(android): Add script to find unused strings. Manually remove them

ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/LanguagePickAssociator.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift, ios/engine/KMEI/KeymanEngineTests/LanguagePickAssociatorTests.swift
Following from #3451, this PR implements the progress-tracking infrastructure needed for the ideas noted as "future thoughts" in the description.  It requires a shift in the callback's signature, so it's best to get it out of the way before 14.0 lands.
This also gives us more fine-grained info for use in `LanguagePickAssociator`'s unit tests, and the new information itself is easily unit-testable.
Basic integration with the `PackageInstallViewController` has also been added, though no code yet actually provides it with associators.  That's left to future work.
=> feat(ios/engine): LanguagePickAssociator progress tracking, base integration with package lang picker

android/KMAPro/kMAPro/build.gradle, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/InfoActivity.java, android/version.gradle, resources/build/build-utils.sh
When displaying the Info page of alpha builds from the Play Store, we noticed the version string displayed the wrong environment:
`14.0.X-alpha-local` (CI builds should have ended with `-alpha`).
It turns out  the `VERSION_` shell variables  from `build-utils.sh` aren't visible in `version.gradle` (though CI environment variables like `build_counter` are visible).
This PR:
* Exports the two VERSION strings needed in version.gradle
* Updates the Info page to simply display `BuildConfig.VERSION_NAME`
=> fix(android/app): Fix environment portion of app version string

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/AssociatingPackageInstaller.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/LanguagePickAssociator.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift, ios/engine/KMEI/KeymanEngineTests/AssociatingPackageInstallerTests.swift, ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift
This PR aims to merge handling for all forms of package installation into a shiny, specialized class - the `AssociatingPackageInstaller`.  KeymanEngine users may specify which, if any, types of language associations should be made for installing packages on a per-use basis of the class.  Currently, only lexical-model associations have a default implementation, with 'custom' associations also having a supported pathway.  This association must be specified for associated lexical models to be automatically installed upon keyboard package installation.
This class will track the query and installation process for resources for the selected language to install alongside the 'base' package.  It's designed to support number-backed progress reporting, though this initial implementation will only …
=> feat(ios/engine): Associating package installer

ios/engine/KMEI/KeymanEngine/Classes/Alerts.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/KeyboardSearchViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift, ios/engine/KMEI/KeymanEngineTests/KeyboardSearchTests.swift, ios/keyman/Keyman/Keyman/AppDelegate.swift, ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift
Following from #3458, the new core installer is now used in more contexts:
- When a keyboard search completes, the user will now be prompted with the installer and may choose languages
- When a user is in another app (like Safari) and chooses to "Open [a KMP] in Keyman":
1. The app is launched (same as before)
2. The app then returns to the main screen (_**new**_, _bugfix_)
- Before, if the user was within the Settings menu (or possibly, the picker), the install screen would never show - even in 12.0 / 13.0 stable.
3. Once that completes, the installer will then launch and act the same as in standard in-app contexts.
As universal link handling isn't _yet_ supported within the app, that'll be handled in the next PR.  It'll be _quite_ easy to plug in after these changes, though.
----
I'm …
=> feat(ios/app):  Associating package installer use within existing install paths

android/build-publish.sh
Currently, CI calls Gradle tasks for publishing APKs to the Play Store
Per @mcdurdin  we want to:
1. wrap those gradle calls in a build script
2. combine the two build steps in CI to a single build script.
When merged, the CI build step becomes:
```
./build-publish.sh -kmapro -fv
```
=> fix(android): Add CI script to publish to Play Store

android/KMAPro/build.gradle, android/KMEA/build.gradle, oem/firstvoices/android/build.gradle
Fixes #3460
Update the sentry plugin versions for KMEA, kMAPRo, and FV app to remove build warnings of obsolete API use.
(Fixed in [sentry-android-gradle-plugin-1.7.32](https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/v1.7.32))
=> fix(android): Update sentry plugin to remove obsolete API  use

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/Model/FullKeyboardID.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/KeyboardSearchViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/UniversalLinks.swift, ios/engine/KMEI/KeymanEngineTests/KeyboardSearchTests.swift, ios/engine/KMEI/KeymanEngineTests/UniversalLinkTests.swift, ios/keyman/Keyman/Keyman/AppDelegate.swift, ios/keyman/Keyman/Keyman/Keyman.entitlements
Continuing on from #3465, this fine fellow gets universal links connected and working.
In my current local tests, I have to longpress the links (to get an "Open in Keyman" option), but this is due to my local machine's refusal to auto-update to the latest provisioning profile.  Build environment matters here.
=> feat(ios/app): universal links for keyboard installation

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/AssociatingPackageInstaller.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/LanguagePickAssociator.swift, ios/engine/KMEI/KeymanEngineTests/AssociatingPackageInstallerTests.swift, ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/URLSessionMock.swift
Addresses a lingering `TODO` / comment from https://github.com/keymanapp/keyman/pull/3458#discussion_r466129228.  The `AssociatingPackageInstaller` now properly deinitializes and can better guarantee a nice 'contract' on its completion closure.
Also addresses a race condition that popped up during one test run by always synchronizing accesses to the affected variable.
=> fix(ios/engine): Proper associating-installer deinitialization, cancellation tests

common/predictive-text/worker/index.ts, common/predictive-text/worker/worker-interfaces.ts
In order to proceed with edit-distance work, one of the first things that we have to do:  allow a persistent `ModelCompositor` that can store intermediate calculations, rather than reconstructing it every time.  
To facilitate this and to allow `ModelCompositor` to be accessible as an LMLayer property when in the correct state, the three states of the LMLayer have now been represented as a TS discriminated union.  The new `.compositor` properly is only accessible on the state object after condition-checking against `state.name == "ready"`.
=> refactor(common/models): LMLayer state management tweak, persistent ModelCompositor

linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/tests/test_install_kmp.py
When installing a keyboard with a bcp47 tag we now look up the
language tag in the keyboard kmp.json file. This fixes #3399 in
case a script subtag is required for the language and will cause
the keyboard to properly show up in the Linux keyboard selection
list.
=> fix(linux): Lookup language tag from keyboard

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/KMManagerTest.java
I noticed the Info page on Keyman 14.0.129-alpha was displaying "Page not found" because it was using the production host https://help.keyman.com instead of https://help.keyman-staging.com. This is because the regex in `KMManager.getTier()` was incorrect for CI versions because of an extra `-`.
A local development version string `14.0.248-alpha-local` would correctly return Tier.ALPHA, but a CI build `14.0.248-alpha` would return Tier.STABLE.
This PR fixes the regex and  adds additional unit test cases (adds PR test and CI version strings)
=> fix(android): Fix util to getting the tier on CI builds

resources/build/l10n/README.md
Up- and download from Crowdin now happen automatically on GitHub
(at least once it's enabled again).
=> docs(common): Clarify l10n readme

linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/keyman_config/keyboard_details.py, linux/keyman-config/keyman_config/view_installed.py, linux/keyman-config/keyman_config/welcome.py
- Remove "package" from the tooltips text since that might be
confusing to users.
- Also make title of Welcome (Help) dialog optionally say "installed"
instead of always so that we open that dialog via the Help button
we just display the keyboard name.
- Refactor Keyboard Details dialog to remove an unnecessary box.
- Add padding after keyboard details in Keyboard Details dialog.
Tooltip before:
Tooltip after:
Help dialog before:
Help dialog after:
Keyboard Details dialog before:
Keyboard Details dialog after:
=> feat(linux): Small UI improvements

common/models/templates/src/common.ts, common/models/templates/src/trie-model.ts, common/models/templates/test/fixtures/tries/smp-apple.json, common/models/templates/test/test-trie-traversal.js, common/models/types/index.d.ts
While our currently-published model template is a Trie-based wordlist, it's important to note that we may support other model templates in the future.  When it comes to examining the lexicon for possible words, the important thing for an edit-distance based search is that we can search the lexicon '_like_' a Trie, not necessarily that the full model itself is Trie-based.
For highly agglutinative languages, it may be more efficient to reconstruct the words from morphemes (as needed) than to actually store every possible word within a Trie.  Furthermore, edit distance doesn't care whether or not a model's backing Trie stores probabilities on a per-word basis or uses some alternate function.  It only cares what words 'neighbor' the current word it's examining.
----
Past that... it turns out …
=> feat(common/models): lexicon traversal

common/models/templates/src/priority-queue.ts, common/models/templates/src/trie-model.ts, common/models/templates/test/test-priority-queue.js
Addresses this old comment: https://github.com/keymanapp/keyman/blob/32df4035a5a2dcc8c0ecded1abf8e9367eab103c/common/models/templates/src/trie-model.ts#L383-L385
As it turns out, a proper priority queue will _also_ be quite helpful for a correction algorithm using edit-distance calculations to search across a lexicon.  So... two birds, one stone.  That algorithm will want a 'min-heap' style queue instead of the Trie's 'max-heap' style queue, so it's been abstracted to take a comparator tailored to each use-case.
- Accordingly, the class is now defined outside of the `TrieModel` class, though still within the `models` namespace.
Immediate benefits:
- Predictions should be snappier, particularly when many are available.
- Drops from O(N^2 log N) to O(N log N), an order of magnitude faster …
=> feat(common/models):  actual priority queue for Trie models

common/models/templates/src/priority-queue.ts, common/models/templates/test/test-priority-queue.js
Looking more closely at what will be need for edit-distance based correction searches, it looks like a more efficient batch-enqueue method is in order.  This corrects the 'lazy' approach previously noted and also facilitates O(N) heap construction from existing arrays.
=> feat(common/models): efficient batch-enqueue

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java
Fixes #3500
When KMManager is copying asset kmp files, check if the asset package is a downgrade before installing it.
=> fix(android/engine): Check asset package version before installing

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java
Fixes #3522 by injecting a meta viewport tag if the help document in WebViewFragment doesn't contain it.
This replaces the 200% zoom.
Screenshots
generated readme.htm
display welcome.htm
display readme.htm
display welcome.htm
generated readme.htm
generated (blank) welcome.htm
=> fix(android/app): Inject meta viewport tag for viewing help

windows/src/desktop/kmshell/main/UfrmMain.pas
Fixes #3178. (Does not apply the "Close" button remodelling, which is a bigger job which I have split into a separate issue #3518). Part of #3512.
=> fix(windows): refresh configuration after changes

linux/ibus-keyman/debian/postinst
If for whatever reason ibus wasn't running for the current user
the installation failed previously, leaving the user in a broken
state until he reboots and tries the installation again. This change
detects this situation and skips restarting ibus.
=> fix(linux): Improve robustness when installing ibus-keyman

android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudKeyboardPackageDownloadCallback.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudLexicalPackageDownloadCallback.java
Fixes #3530 
When downloading keyboard package updates, the cloud API uses links such as
https://keyman-staging.com/go/package/download/sil_euro_latin?version=1.9.1&update=1
Currently, keyboard package updates would be saved with an invalid filename `sil_euro_latin?version=1.9.1&update=1`.
The cloud keyboard package download callback need to be updated to convert that path to a filename `sil_euro_latin.kmp`.
I updated CloudLexicalPackageDownloadCallback.java to use the same pattern to keep things similar. 
Note, downloads from keyboard searches (https://keyman-staging.com/keyboards/...)  don't use the background downloader, so MainActivity is triggered with the correct filename "sil_euro_latin.kmp".
=> fix(android/engine): Fix package filename when downloading from cloud

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas, windows/src/desktop/kmshell/install/Keyman.Configuration.UI.InstallFile.pas, windows/src/desktop/kmshell/install/UfrmInstallKeyboard.pas, windows/src/desktop/kmshell/xml/installkeyboard.css, windows/src/desktop/kmshell/xml/installkeyboard.js, windows/src/desktop/kmshell/xml/installkeyboard.xsl, windows/src/desktop/kmshell/xml/strings.xml, windows/src/engine/kmcomapi/com/keyboards/keymankeyboardfile.pas
For packages with a single keyboard, we now make it possible to select a language at install time.
Fixes #1456.  Part of omnibus #3512.
These are the same as before.
The combo is pre-filled with the bcp47 tag found in the search.
=> feat(windows): select language at keyboard install

windows/src/engine/keyman32/Keyman32.cpp, windows/src/engine/keyman32/appint/aiTIP.cpp, windows/src/global/inc/keyman64.h, windows/src/global/inc/registry.h
Keyman32/keyman64 were not reading the new 'Transient Language Profiles'
key which is needed with Keyman 14. Minor tweak to ensure we don't scan
through more profiles than necessary when activating tip in aiTIP.cpp also.
=> fix(windows): add transient profile support to keyman32

windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguageinstalled.pas, windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguagesinstalled.pas, windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.Process.KPInstallKeyboardLanguage.pas, windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.Process.KPUninstallKeyboardLanguage.pas, windows/src/global/delphi/general/RegistryKeys.pas, windows/src/global/delphi/general/Windows8LanguageList.pas, windows/src/global/delphi/general/utiltsf.pas
Fixes #1282.
Fixes #1719.
This PR handles the case where Windows installs a BCP 47 tag that may not match our tag 100% precisely. In this case, Keyman maps the Windows BCP 47 tag to the in-memory data for consistency. It also allows for install of more complex tags.
Part of #3512.
=> feat(windows): map installed bcp47

windows/src/desktop/kmshell/main/UfrmMain.pas, windows/src/desktop/kmshell/main/initprog.pas, windows/src/desktop/kmshell/xml/keyman_keyboardlist.xsl, windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguageinstalled.pas, windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.Process.KPUninstallKeyboardLanguage.pas
This does two things:
1. It fixes an issue where uninstall of a profile would fail because of registered-but-not-installed profiles in the same list.
2. It simplifies referencing the profile to be uninstalled so we can avoid looking up in the registry again, given we already have the active data.
There is another round of refactoring that we can do in Keyman Configuration relating to profile uninstallation, but as it is working at present, I am holding off to fix other issues. May return and refactor if time permits.
Part of #3512
=> fix(windows): simplify profile uninstall

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
This fixes the [ActivityNotFoundException](http://sentry.keyman.com/organizations/keyman/issues/390/?project=7&query=is%3Aunresolved) exceptions reported on Sentry.
Back when KMA and KMAPro were separate apps (predating Keyman for Android 2.8), KMA had an intent for "Keyman.ACTION_GET_USERDATA" while KMAPro did not.
This PR cleans up the calls to the unused activity.
=> fix(android/app): Remove unused intent ACTION_GET_USERDATA

android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java, android/history.md
This addresses #3484 for stable-13.0 (similar to #3546)  
[setAutoCancel](https://developer.android.com/reference/android/app/Notification.Builder#setAutoCancel(boolean))(true) can make the notification automatically dismiss when the user touches it (choices are either cancel or download)
=> fix(android/engine): Dismiss notification when touched

android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java
This addresses #3484 for 14.0.
Since cloud keyboards now download packages instead of individual files, the handler ResourceUpdateTool.onPackageInstalled() needed to cleanup the system notification. (Refer to onKeyboardDownloadFinished at l.506)
Will still need to investigate why 13.0 notifications aren't getting dismissed...
(update):
[setAutoCancel](https://developer.android.com/reference/android/app/Notification.Builder#setAutoCancel(boolean))(true) can make the notification automatically dismiss when the user touches it (choices are either cancel or download)
=> fix(android/engine): Remove notification after installing kbd package

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
For investigating #2811, this reverts #2828 and re-enables Sentry monitoring of Application Not Responding (ANR)
=> fix(android): Re-enable monitoring of Application Not Responding (ANR)

common/predictive-text/unit_tests/headless/edit-distance/classical-calculation.js, common/predictive-text/worker/correction/classical-calculation.ts
One feature that the initial edit-distance implementation was lacking:  the ability to trace the path used to find the minimum edit distance.  While not strictly necessary for the core search algorithm, it's useful for diagnosing any issues that may arise when debugging, etc.
As it turns out, it looks like this algorithm will be quite useful for 'aligning' contexts as the user continues typing.  A specialized, hand-written version was looking to be tricky to hand-code properly due to the wide variance of possible control paths, so I bumped up the priority of this previously-missing feature.
Note that a pair of `'transpose-start'` and `'transpose-end'` constitute a _single unit_ of edit distance.  It took me a little bit to settle on this representation, as this is a bit odd... but it does …
=> feat(common/models): Edit path derivation

common/predictive-text/unit_tests/headless/edit-distance/classical-calculation.js, common/predictive-text/unit_tests/headless/edit-distance/distance-modeler.js, common/predictive-text/worker/correction/classical-calculation.ts, common/predictive-text/worker/correction/distance-modeler.ts, common/predictive-text/worker/model-compositor.ts, common/predictive-text/worker/tsconfig.json
Following from #3526, this PR starts integrating use of Damerau-Levenshtein-based edit-distance for use with modeling/generating 'corrections'.  In particular, two "low-level" classes are introduced:  `SearchEdge` and `SearchNode`.  Part of addressing #2223.
After significant analysis and work, I've noticed that the overall algorithm will effectively be an implementation of the A* algorithm over a virtualized search graph with directed edges.  (Said graph will be _mostly_ tree-like, though some branches may converge.  The graph will be acyclical, at least.)
Inputs:  
- a list of probability distributions over the possible input tokens
- This allows us to, in theory, search over _**all**_ possible input sequences.
- a `LexiconTraversal` object, allowing efficient search throughout a …
=> feat(common/models):  low-level correction-algorithm infrastructure

common/core/web/keyboard-processor/src/keyboards/defaultLayouts.ts
While testing out recent predictive-text work, I discovered that "shift" wasn't functioning properly for keyboards with default layouts and mobile form factors.  Just shift, though.
=> fix(web): default layout shift not changing layer

windows/src/developer/TIKE/oskbuilder/TouchLayout.pas
Fixes #3487.
The fontsize property for touch layout elements was treated as an integer by Developer but should be a string (as it might contain units such as 'em').
To help with back-compat, updated the GetValue string overload to ignore value type and return the stringified form, regardless of the actual type, which should always work.
Cherry-pick of #3585.
=> fix(developer): Touch font size should be string 🍒

windows/src/developer/TIKE/oskbuilder/TouchLayout.pas
Fixes #3487.
The fontsize property for touch layout elements was treated as an integer by Developer but should be a string (as it might contain units such as 'em').
To help with back-compat, updated the GetValue string overload to ignore value type and return the stringified form, regardless of the actual type, which should always work.
See #3584 for stable-13.0 cherry-pick.
=> fix(developer): Touch font size should be string

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/InfoActivity.java, android/KMAPro/kMAPro/src/main/res/layout/activity_info.xml, android/KMAPro/kMAPro/src/main/res/values-land/dimens.xml, android/KMAPro/kMAPro/src/main/res/values-sw600dp/dimens.xml, android/KMAPro/kMAPro/src/main/res/values-sw720dp/dimens.xml, android/KMAPro/kMAPro/src/main/res/values/dimens.xml
Fixes #3566 
This updates the Info page to reuse the titlebar styling.
Since the Info page includes the online help.keyman.com banner, I also commented out the logo in the titlebar.
(Updated screenshots with version string moved to bottom of page)
Except for Nexus S, all screens from emulated devices show portrait and landscape orientation.
=> fix(android/app): Fix Info page title size

linux/keyman-config/keyman_config/install_kmp.py
During KMP installation, hard links to some of the keyboard files are created.
This throws [FileExistsError](https://sentry.keyman.com/organizations/keyman/issues/874/?environment=alpha&project=12) if the file already exists
Before this fix, here's the steps to trigger the error:
1. Load keyman-config
2. "Download" to install sil_euro_latin.kmp from keyman.com 
(A hard link is created at `~/.local/share/fonts/keyman/sil_euro_latin/DejaVuSans.ttf`)
3. In a browser, download the keyboard package from https://downloads.keyman.com/keyboards/sil_euro_latin/1.9.2/sil_euro_latin.kmp
4. From keyman-config, "Install" the local sil_euro_latin.kmp file.
This tries to make the hard link to the existing font file, and the FileExistsError is reported to the terminal
=> fix(linux/config): Check if file exists before creating hard links

oem/firstvoices/windows/src/xml/menu.js, windows/src/desktop/kmshell/xml/menu.js
Fixes #3361. Remove obsolete releaseCapture calls from Keyman Config.
=> fix(windows): remove obsolete releaseCapture calls

linux/keyman-config/keyman_config/keyboard_details.py, linux/keyman-config/keyman_config/kmpmetadata.py, linux/keyman-config/locale/keyman-config.pot
This catches [JSONDecodeError](https://sentry.keyman.com/organizations/keyman/issues/873/?environment=alpha&project=12) when kmp.json is invalid JSON.
Question: Is it appropriate to exit out? The Keyman config dialog can't really handle if kmp.json is invalid.
=> fix(linux/config): Catch if kmp.json is invalid JSON

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas, windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguage.pas, windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguagesinstalled.pas
Lookup a language name from various sources rather than using the BCP 47 code, where possible.
Relates to #3512.
=> fix(windows): lookup language name on create

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift, ios/engine/KMEI/KeymanEngineTests/ResourceDownloadManagerTests.swift
Since https://github.com/keymanapp/keyman.com/pull/162 has been merged, our iOS code may now target use of go/package links for lexical model packages.
=> feat(ios/engine): go/package use for model pkg downloads

common/predictive-text/unit_tests/headless/edit-distance/distance-modeler.js, common/predictive-text/unit_tests/headless/worker-model-compositor.js, common/predictive-text/worker/correction/context-tracker.ts, common/predictive-text/worker/correction/distance-modeler.ts, common/predictive-text/worker/model-compositor.ts
My current set of optimization tweaks for improving the performance of #3555.  It's definitely 'snappier' with these in place.
This also addresses some of the 'rough edges' noted on #3555:
- Suggestion 'acceptance' has been fixed, as well as some bugs that resulted within the context manager when applying suggestions.  (Kinda forgot about that case when designing its logic.)
- I've now more thoroughly tested continuous input; that concern has been alleviated.
The "new" biggest rough edges:
- Performance will take a serious hit when nonsense is input / when there is no reasonable corrective match.
- I still need to determine a good threshold strategy for this case.
- Further optimizations would be wise.
That said... it's already working a lot better for "good input" use cases.
=> feat(common/models): correction thresholding, acceptance

common/predictive-text/unit_tests/headless/edit-distance/distance-modeler.js, common/predictive-text/worker/correction/distance-modeler.ts
Now that things are becoming a bit more stabilized with the new corrective-algorithm's code, it's a reasonable time to back and clean up some of the... uh... "less optimal" aspects of the distance-modeling implementation.  There's a lot of redundancy between `SearchEdge` and `SearchNode` - enough so that we can actually straight-up nix the former and merge the two roles into a single class.
Corresponds to a refactor of #3534... after edits from intermediate PRs have also taken place.  It'd be a minor nightmare to backport to #3534, though... hence this PR.
=> refactor(common/models): distance modeler cleanup

common/core/web/input-processor/src/text/prediction/languageProcessor.ts, common/predictive-text/worker/correction/context-tracker.ts, common/predictive-text/worker/correction/distance-modeler.ts
Knew I forgot something with the last PR; the recently-added context-modeling code also was in need of some significant cleanup.  Also, in hindsight, I realized that the context-tracking pattern was... less than optimal.  Also, the object-orientation was pretty poor; this has been significantly cleaned up now.
Rather than creating new `TrackedContextState` instances on every keypress, a better approach is to create new instances only on new _tokens_ (words).  We need such instances to revert to the final pre-acceptance context of a token... whenever a suggestion rooted on that token is reverted.  The intermediate states leading to that final context don't matter; just the last one before a suggestion is applied.  So, this changes context tracker system to iteratively mutate (update / …
=> change(common/models): context tracker cleanup, optimizations, fixes

common/core/web/keyboard-processor/src/keyboards/defaultLayouts.ts, common/models/templates/src/trie-model.ts, common/models/types/index.d.ts, common/predictive-text/unit_tests/headless/edit-distance/distance-modeler.js, common/predictive-text/unit_tests/headless/worker-model-compositor.js, common/predictive-text/worker/correction/context-tracker.ts, common/predictive-text/worker/correction/distance-modeler.ts, common/predictive-text/worker/model-compositor.ts
Note:  to facilitate testing some of the new logic, this also includes the changes seen in #3754.  (Kinda hard to test the case-matching 'keep' if you can't type it.)
Adds two features:
1. If a model uses a 'keying' function, it may now expose it as part of the lexical model interface.  The corrective search may then use it to 'key' corrective searches in the same manner.
2. Adds a minimum threshold for search-path cost to the correction algorithm to help keep things 'snappier'.
=> feat(common/models): Correction improvement

common/predictive-text/unit_tests/headless/edit-distance/distance-modeler.js, common/predictive-text/worker/correction/distance-modeler.ts
To keep things snappy, this adds a (by default) 33ms timer on the correction algorithm.  It will automatically return results after that time, whether or not any valid corrections have been found.
Note: this time will not be cut short if/when a new keystroke is received.  That's why I'm labelling it 'naive'.  See #3580 for notes toward a more robust (but also markedly more complex) design... the 'complex' part being why we're going 'naive' for now.
=> feat(common/models): naive correction-algorithm timer

common/core/web/input-processor/src/text/prediction/languageProcessor.ts, web/source/dom/targets/outputTarget.ts, web/source/osk/banner.ts
As KMW has existed until now, the application & reversion part of the code has been UI / DOM dependent.  These changes will bring it into a lower level, adapting it to fit within the `input-processor` core module.  This will allow the lm-layer to better assist with display text while also allowing KMW to better provide the lm-layer with acceptance/reversion/etc feedback about the state of the context.
Note that this PR aims only to refactor existing behavior; no new features have been added with these changes.  Those will come later.  We'll likely want a similar PR to refactor reversion as well, after which we can start implementing related features.
=> refactor(web/engine): application of predictive suggestions

windows/src/desktop/kmshell/main/KeyboardTIPCheck.pas
Now that we have an idempotent function to register a TIP for a language, it makes sense to use that to repair existing profiles, rather than the prior, rather WET code (which also was not quite right for the new design, anyway).
Relates to #3512.
=> fix(windows): simplify profile repair

windows/src/desktop/kmshell/install/Keyman.Configuration.UI.InstallFile.pas, windows/src/desktop/kmshell/install/UfrmInstallKeyboard.pas, windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguageinstalled.pas, windows/src/engine/kmcomapi/com/keyboards/keymankeyboardinstalled.pas, windows/src/engine/kmcomapi/com/keyboards/keymankeyboardsinstalled.pas, windows/src/engine/kmcomapi/keymanapi_TLB.pas, windows/src/engine/kmcomapi/kmcomapi.ridl, windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.Process.KPInstallKeyboardLanguage.pas, windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.Process.KPUninstallKeyboardLanguage.pas, windows/src/engine/kmcomapi/util/internalinterfaces.pas, windows/src/global/delphi/general/RegKeyboards.pas, windows/src/global/delphi/general/RegistryKeys.pas
Fixes #3560. This reworks the functionality for disabling keyboards to work with the new TIP registration pattern. Much of the code is the same as in Keyman 13, but there are some significant differences, so it all needs to be reviewed.
=> fix(windows): add back support for disabling keyboards

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas, windows/src/desktop/kmshell/install/Keyman.Configuration.UI.InstallFile.pas
If the user does not specify a language in the bootstrap install, then the package would be installed without any language selection. This happens, for example, in a bundled installer run without parameters, or if there are additional .kmp files in the same folder as the setup.exe that are to be installed, and the user does not open the Setup Options dialog to choose languages for each package.
Also, the elevated portion of the language install was doing a register and install instead of just register. This was not particularly harmful but was unwanted for scenarios where the elevated user is different to the login user.
=> fix(windows): bootstrap package install specified language bugs

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java
Fixes #3595
With the refactoring in #3614, KMPBrowserActivity can now start an intent for MainActivity to install the kmp.
Screenshots of the workflow:
Pressing the "Install Keyboard" button
starts the kmp download
kmp install shows readme.htm
after keyboard (and dictionary) installed
=> fix(android/app): Change install intent to MainActivity
