keymanapp/keyman

android/KMEA/app/src/main/assets/keyboard.html

fix(android): include DOMRect polyfill for older ES6-supporting devices

---

android/KMEA/app/src/main/assets/keyboard.html

Fixes: #11653
Fixes: KEYMAN-WEB-JD

fix(android): include DOMRect polyfill for older ES6-supporting devices 🍒  🏠

---

.github/workflows/api-verification.yml

In #11571 we tried to fix the failing API verification by moving setting up the environment and restoring artifacts to the same job as the api verification itself. However, this doesn't help and the `artifacts` subdirectory still vanishes, caused by https://github.com/actions/checkout/issues/1201.
This change reverts the change introduced in #11571 and changes the git checkout to end in a separate subdirectory.
Reverts: #11571

fix(linux): move environment to separate job and checkout to separate subdirectory

---

.github/workflows/api-verification.yml

This change reverts #11659 and moves setting the environment and restoring the artifacts in the same job as the actual API verification. It keeps checking out the git files to a separate directory.

fix(linux): restore of artifacts still needs to be in same job

---

common/web/input-processor/src/text/prediction/languageProcessor.ts

We can't really apply a suggestion unless we have the configuration object (that provides the context).
Cherry-pick-of: #11594
Fixes: #11593
Fixes: KEYMAN-WEB-FX

fix(web): Don't apply suggestion unless fully configured 🏠

---

.github/workflows/api-verification.yml

fix(linux): remove escape character in wildcard for package filename

---

.github/workflows/api-verification.yml

The previous wildcard was too broad and matched on `libkeymancore-dev` which is missing the API version number in the filename. This change requires a digit after the name.

fix(linux): match digit in package filename

---

windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp
windows/src/engine/keyman32/serialkeyeventserver.cpp

Fixes: #11651 
Add debug log messages in the code that processes modifier key presses. This will be useful for debugging issues with the serialized event server and modifier keys.

chore(windows): add debug log messages for modifier key press processing

---

core/tests/unit/ldml/test_unicode.cpp

- group output by functional area
#10183
Sample output:
```shell
----------------------------------- stdout -----------------------------------
= test_all
== load_json loading /Users/srl295/src/keymanapp/keyman/core/build/mac-x86_64/release/tests/unit/ldml/nodeversions.json
== load_json loading /Users/srl295/src/keymanapp/keyman/core/build/mac-x86_64/release/tests/unit/ldml/package.json
= get_block_unicode_ver load /Users/srl295/src/keymanapp/keyman/core/build/mac-x86_64/release/tests/unit/ldml/Blocks.txt
6
== test: test_unicode_versions
ICU Versions:
* 73.1	..linked from C++
* 74.2	..in Node.js
Unicode Versions:
* 15.0	..in ICU linked from C++
* 15.1	..in ICU in Node.js
* 15.1.0	..in Keyman repo Blocks.txt
Node.js
* "18.20.2"	Actual version of Node.js
* ^18.x	Version of Node.js requested …
```

test(core): clarify output of test_unicode

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m

When handling command keys, which are passed through after marking the context as stale, a call to logDebugMessage was formatting the event type, which is an integer value, as an object. This caused Keyman to crash for users that had verbose logging enabled.
The event type could safely be written to the logs by formatting it correctly, but it was removed as it was not particularly useful.
Fixes #11673
Fixes KEYMAN-MAC-FC

fix(mac): handle command keys without crashing 🏠 

---

common/web/lm-worker/src/main/model-compositor.ts

Fixes: #11684
Fixes: KEYMAN-WEB-KR
Fixes: #11620
Fixes: KEYMAN-WEB-KT
Fortunately, this one's `alpha`-only, as the triggering code landed in #11598.  This PR essentially reverts it and deletes the no-longer-referenced local (`finalInput`) and the code used to initialize it.
As we already know things were working fine in this regard before #11598...
At least now there's a far clearer reason to eliminate that section outright.

fix(web): revert #11598 to eliminate use of `finalInput` which caused crash after moving caret

---

resources/build/test/test.sh
resources/builder.inc.sh

Previously with the right number of parameters that take values and the right order it could happen that a parameter value got replaced by an action when the script output the parameters. This change fixes this.
Also output the actual script name instead of hard-coded `build.sh`.
Fixes: #11676

fix(common): correctly display result of multiple option parameters in builder

---

web/src/engine/osk/src/visualKeyboard.ts

Fixes #11650.
It turns out that the underlying error for the observed flick-breakages is due to the current layer's row-height being `undefined`... because it's initialized immediately _after_ we try to access it, as part of `this.layerGroup.refreshLayout`:
A layer's `rowHeight` field is initialized only here: 
https://github.com/keymanapp/keyman/blob/b63acb156feb71bb5daee19041c53da766f38706/web/src/engine/osk/src/keyboard-layout/oskLayer.ts#L153-L165
It would appear that _most_ of the time, an extra call is triggered; that extra call would have the value initialized by the first call.
While it's extremely hard to reproduce, and I thus lack any specific test instructions to give...
TEST_GESTURES: Use Keyman for Android or Keyman for iOS with the default (EuroLatin) keyboard and verify …

fix(web): get row-height for flick constraints after performing layout

---

android/KMEA/app/src/main/java/com/keyman/engine/cloud/CloudDownloadMgr.java
android/KMEA/app/src/main/java/com/keyman/engine/util/KMLog.java

Replaces #11580.
Addresses #11561.  This change should prevent crashes, but there may be lingering side-effects we want to resolve before closing the issue outright.
This PR does two main things:
1. It ensures we `catch` the _right_ exception type - `IllegalArgumentException` instead of `IllegalStateException` - in our existing error handlers.  This should, at least, prevent a crash.
2. We didn't have manual breadcrumb logging yet within Keyman Engine for Android, so this adds a method to accomplish that.
Toward that latter point, here's how a stack-traced breadcrumb appears in Sentry:
Here's a link to the Sentry event I temporarily generated in order to expose this: https://keyman.sentry.io/share/issue/0d3661c2239842ff8ba31bed996087ec/
The `stacktrace` entry is initially collapsed, but …

fix(android): handle `IllegalArgumentException` when initializing `CloudDownloadMgr`, add logging to check for unhandled side-effects

---

common/web/types/package.json
developer/src/kmc-ldml/package.json
package-lock.json

3.0.1 includes our fix. However, 3.0.2 does not yet appear to have been published, which has a patch for our fix?
Fixes: #8616

chore: replace git dep on restructure with 3.0.1 in npm

---

common/web/types/build.sh

The CLDR imports are copied into the build/ folder, so it makes more sense for them to be done during the build phase, particularly as it is a very quick operation. (Before this, removing the build/ folder did not trigger a build.sh configure, so subsequent tests and usage would fail with confusing LDML import errors. An alternative solution would have
been to declare the configure output to be one of these files.)

chore(common): move CLDR import copy into build step for common/web/types

---

developer/src/tike/xml/app/editor/editor.js

Fixes: #11586
Fixes: KEYMAN-DEVELOPER-1K7
Cherry-pick-of: #11587

fix(developer): handle editor initializing after debugger when setting execution point 🍒 🏠

---

developer/src/tike/xml/app/editor/editor.js

Note: this was a silent exception for the user.
Fixes: #11586
Fixes: KEYMAN-DEVELOPER-1K7

fix(developer): handle editor initializing after debugger when setting execution point

---

developer/src/common/delphi/packages/Keyman.System.PackageInfoRefreshKeyboards.pas

Fixes: KEYMAN-DEVELOPER-201
Fixes: #11687

fix(developer): treat js files with unrecognized encodings as non-keyboard files

---

developer/src/common/delphi/packages/Keyman.System.PackageInfoRefreshKeyboards.pas

Cherry-pick-of: #11698
Fixes: KEYMAN-DEVELOPER-201
Fixes: #11687

fix(developer): treat js files with unrecognized encodings as non-keyboard files 🍒 🏠

---

developer/src/tike/child/UfrmPackageEditor.pas

Fixes: #11700
Fixes: KEYMAN-DEVELOPER-1FT

fix(developer): disable example edit controls if no examples in Package Editor

---

developer/src/tike/child/UfrmPackageEditor.pas

Cherry-pick-of: #11701
Fixes: #11700
Fixes: KEYMAN-DEVELOPER-1FT

fix(developer): disable example edit controls if no examples in Package Editor 🍒 🏠

---

web/src/engine/osk/src/views/touchEventPromiseMap.ts

Fixes: #11704
Fixes: KEYMAN-WEB-HY.  Turns out that the original variant of that issue was resolved with #11505, leaving only the current form in place.  (Note:  is not currently commit-tagged; I realized this later.)
The offending code attained its current form in #11462, wherein I converted this class from using a `Record<,>`  Object-based "map" to an actual ES6 `Map`.  
Before: `Object.keys()`.
After: `map.keys()`.
`Object.keys()` actually _does_ return an array, while `map.keys()` does not.  Fortunately, this means that the bug this fixes should only occur for 18.0-alpha.
TEST_ATTEMPT_REPRO:  Using Keyman for Android, attempt to reproduce #11704:
1. Installed this PR's APK file and give all permissions to the application.
2. Check the "Enable Keyman as system-wide keyboard" and set …

fix(web): fix osk touch-focus tracking

---

web/src/app/browser/src/contextManager.ts

This PR implements the changes that have already been made by #11505, but this time within the app/browser variant of the Web engine.  Those fixes successfully stopped related errors we'd been seeing within the app/webview variant, and there's little reason not to include the fix for app/browser.
We don't currently have any matching error reports yet for stable, but that may just mean we haven't received any _yet_.

fix(web): defer keyboard activation requests made during engine initialization

---

web/src/tools/building/sourcemap-root/tsconfig.json
web/tsconfig.base.json

fix(common): remove allowJs from web's tsconfig.base.json

---

developer/src/tike/child/UfrmDebug.pas
developer/src/tike/debug/Keyman.System.Debug.DebugEvent.pas

I have not been able to reproduce this problem, so adding some extra debug logs in an attempt to determine what is causing the assertion failure.
Relates to: #11706

chore(developer): add extra logging for assertion failure when pressing backspace in debugger

---

resources/git-hooks/prepare-commit-msg

Fixes: #11702
I just realized that with the `git cherry-pick` workflow, this probably doesn't do much for us -- because the automated commit message prep will never run

chore: add cherry-pick information in commit messages

---

developer/src/tike/child/UfrmDebug.pas
developer/src/tike/debug/Keyman.System.Debug.DebugEvent.pas

I have not been able to reproduce this problem, so adding some extra debug logs in an attempt to determine what is causing the assertion failure.
Relates to: #11706
Cherry-pick-of: #11707

chore(developer): add extra logging for assertion failure when pressing backspace in debugger 🍒 🏠

---

developer/src/tike/child/Keyman.Developer.UI.UframeWordlistEditor.pas

Fixes: #11710
Fixes: KEYMAN-DEVELOPER-1S4

fix(developer): handle encoding errors when loading wordlists

---

mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj

Cherry-pick of #11730 
For the Keyman Input Method (Keyman target -> Build Phases) task 'Copy Files' to copy the Keyman Engine dsym file to the Products directory, change the project setting runOnlyForDeploymentPostprocessing=1. (In Xcode this corresponds to the 'Copy only when installing' checkbox.)
It is unclear why this was needed in Xcode 15 and not earlier versions, but with this change, the cycle error stopped occurring, and the application built successfully.
Fixes: #11726

fix(mac): change build configuration to prevent cycle error in Xcode 15 🍒 🏠 

---

mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj

For the Keyman Input Method (Keyman target -> Build Phases) task 'Copy Files' to copy the Keyman Engine dsym file to the Products directory, change the project setting runOnlyForDeploymentPostprocessing=1. (In Xcode this corresponds to the 'Copy only when installing' checkbox.)
It is unclear why this was needed in Xcode 15 and not earlier versions, but with this change, the cycle error stopped occurring, and the application built successfully.
Fixes: #11726

fix(mac): change build configuration to prevent cycle error in Xcode 15

---

developer/src/tike/child/UfrmKeymanWizard.pas
developer/src/tike/main/UfrmMain.pas
developer/src/tike/oskbuilder/UframeTouchLayoutBuilder.pas

The keyboard editor has a complex edit state machine, which has grown a lot over time. This is a minimal patch to address one specific edge case scenario on that state machine, without any attempt to improve the state machine overall. The biggest change here is bubbling failure up to the main form so that it can destroy (aka Release, which is an asynchronous destroy) the editor window if it fails to load completely.
Fixes: #11715
Fixes: KEYMAN-DEVELOPER-1JC
I have tested a number of scenarios with this to satisfy myself that it is operating as intended. It can be tricky to manually test outside of the debug environment, so skipping user test.

fix(developer): prevent two touch layout editors opening for the same file

---

developer/src/kmconvert/Keyman.Developer.System.ImportWindowsKeyboard.pas
developer/src/kmconvert/Keyman.Developer.System.VisualKeyboardToTouchLayoutConverter.pas
developer/src/kmconvert/kmconvert.dpr
developer/src/kmconvert/kmconvert.dproj
developer/src/tike/oskbuilder/UframeTouchLayoutBuilder.pas
developer/src/tike/tike.dpr
developer/src/tike/tike.dproj

Also, renames `TouchLayoutToVisualKeyboardConverter` to `VisualKeyboardToTouchLayoutConverter`.
Cherry-pick-of: #11720
Fixes: KEYMAN-DEVELOPER-1NN
Fixes: #11719

fix(developer): handle missing OSK when importing a Windows keyboard into a touch-only project 🍒 🏠

---

developer/src/tike/child/UfrmKeymanWizard.pas
developer/src/tike/main/UfrmMain.pas
developer/src/tike/oskbuilder/UframeTouchLayoutBuilder.pas

The keyboard editor has a complex edit state machine, which has grown a lot over time. This is a minimal patch to address one specific edge case scenario on that state machine, without any attempt to improve the state machine overall. The biggest change here is bubbling failure up to the main form so that it can destroy (aka Release, which is an asynchronous destroy) the editor window if it fails to load completely.
Cherry-pick-of: #11717
Fixes: #11715
Fixes: KEYMAN-DEVELOPER-1JC

fix(developer): prevent two touch layout editors opening for the same file 🍒 🏠

---

developer/src/tike/xml/help/contexthelp.xml
developer/src/tike/xml/help/help.xsl

Adds support for `<LanguageReference Name='keyword'>` in contexthelp.xml.

feat(developer): support language reference in context help

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java

Replaces #11484.
Noting [two](https://github.com/keymanapp/keyman/pull/11484#issuecomment-2130521268) [different](https://github.com/keymanapp/keyman/pull/11484#issuecomment-2136533495) comments from #11484, I now suspect the issue is that the _system keyboard_ simply lacked "on resume"-style orientation checking.  After some investigation, I _think_ I've identified the correct place for it.
The new code essentially duplicates the following in-app block for handling orientation changes when the app is restored:
https://github.com/keymanapp/keyman/blob/c8d8e4187aa20f7db7f22c8fa7ccd21a04a2615b/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java#L243-L251
While a bit WET, note that a special state variable is needed for tracking.  Both would lie within "app" space, …

fix(android): check current orientation when redisplaying system keyboard

---

android/KMEA/app/src/main/assets/android-host.js
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Fixes: #10054
This aims to fix the size and orientation issues we've been seeing for our touch-keyboards on Android.
Note that this PR _adds_ to the adjustments made by ##11604.  That does appear to properly ensure the correct "outer size" of the keyboard - that of the hosting WebView.  The remaining issues appear to lie within the keyboard host-page inside of the WebView.
In order to properly handle this, ensuring proper layout for our WebView-internal keyboard, we split management of WebView's layout operations from the JS calls used to set the WebView-internal layout, the latter of which are based on the final size of the hosting WebView.  To do so, we relocate the latter set of calls to `onSizeChanged`, overriding a superclass method that ought be triggered after …

fix(android): fix keyboard size after rotation and restore via onSizeChanged, after layout

---

developer/src/kmcmplib/tests/gtest-compiler-test.cpp

Backslashes in paths are Windows-only, may have caused recent *nix-agent-based CI-build failures.

fix(developer): fix kmcmplib unit-test include paths

---

developer/src/tike/xml/help/contexthelp.xml
developer/src/tike/xml/help/help.xsl

Adds support for `<LanguageReference Name='keyword'>` in contexthelp.xml.
Cherry-pick-of: #11737

feat(developer): support language reference in context help 🍒 🏠

---

developer/src/tike/xml/help/contexthelp.xml

docs(developer): context help in package-editor and put the existing context help in their own tab comments

---

common/models/wordbreakers/src/default/index.ts
common/web/lm-worker/build-polyfiller.js
common/web/lm-worker/src/polyfills/array.from.js

Fixes: #11502
Fixes: KEYMAN-WEB-K4
We removed almost all uses of `Array.from` from the lm-worker and its subpackages during 17.0's release cycle, aiming to simplify the number of polyfills needed.  However, two cases were missed:
1. https://github.com/keymanapp/keyman/blob/614f957de583e68aaad9193c397bcc88ff065c09/common/models/wordbreakers/src/default/index.ts#L277
2. https://github.com/keymanapp/keyman/blob/614f957de583e68aaad9193c397bcc88ff065c09/developer/src/kmc-model/src/model-defaults.ts#L58
While it's possible to correct the first one and simply "move on", the second poses a greater problem.  We've baked use of `Array.from` into a number of our distributed models, and so we _must_ provide some form of polyfill for `Array.from`.
To remedy that, this adds a very limited version of …

fix(web): add limited Array.from polyfill for lm-worker use

---

linux/mcompile/keymap/deadkey.cpp
linux/mcompile/keymap/deadkey.h
linux/mcompile/keymap/keymap.cpp
linux/mcompile/keymap/keymap.h
linux/mcompile/keymap/mc_import_rules.cpp
linux/mcompile/keymap/mc_kmxfile.cpp
linux/mcompile/keymap/mc_kmxfile.h
linux/mcompile/keymap/mcompile.cpp
linux/mcompile/keymap/mcompile.h
windows/src/engine/mcompile/mc_savekeyboard.cpp

fixes parts of [PR #9384](https://github.com/keymanapp/keyman/pull/9384) 
This PR addresses and bundles comments made on [PR #9384](https://github.com/keymanapp/keyman/pull/9384) about renaming symbols. 
While reviewing [PR #9384](https://github.com/keymanapp/keyman/pull/9384) several comments on renaming symbols came up. Most of them address the use of non-capital letters in variable names, renaming symbols to other names and adding comments into the code.
This PR only addresses requests for changes in comments and symbol names throughout all mcompile-linux. There might still be other unaddressed comments in functions or modules that have already had symbols renamed.

feat(linux): rename symbols throughout mcompile-linux 🐘

---

web/src/engine/osk/src/views/floatingOskView.ts
web/src/test/manual/web/index.html
web/src/test/manual/web/issue11785/index.html

Fixes: #11785
Fixes: KEYMAN-WEB-KC
TEST_STANDARD_USE:  Using the test page "Test unminified Keymanweb" on a desktop or laptop, verify that KeymanWeb operates normally.
- In particular, each keyboard's OSK should display normally and without issue.
TEST_QUICKLOAD:  Using the new test page "Test OSK loading with early add-keyboard calls", verify that KeymanWeb operates normally.
- In particular, each keyboard's OSK should display normally and without issue.

fix(web): prevent desktop OSK crash when addKeyboards is called before engine init

---

web/src/engine/main/src/keymanEngine.ts

Fixes: #11740
Cherry-pick-of: #11743

fix(web): set new-context rules' device to match that of the active OSK 🍒 🏠

---

web/src/engine/osk/src/views/floatingOskView.ts
web/src/test/manual/web/index.html
web/src/test/manual/web/issue11785/index.html

Fixes: #11785
Fixes: KEYMAN-WEB-KC
Cherry-pick-of: #11786

fix(web): prevent desktop OSK crash when addKeyboards is called before engine init 🍒  🏠

---

core/commands.inc.sh
docs/build/macos.md

fix(core): serialize tests for core/wasm on mac agents

---

linux/ibus-keyman/tests/scripts/run-tests.sh
linux/ibus-keyman/tests/scripts/test-helper.inc.sh

Previously keyboard input was no longer input after manually running the integration tests. This change fixes this by restarting ibus after the tests. However, we only want to do that if the ibus instance we started for the tests got killed. The cleanup script might get called multiple times, so we need this check.

fix(linux): restart ibus after manual integration test run

---

oem/firstvoices/windows/src/inst/Makefile

keyboards repo build.sh now uses -k parameter to specify the keyboard to build. This patch does not need to be ported to 18.0 as the 18.0 build does not directly build the keyboard package, but rather uses the currently released version.
Blocked-by: keymanapp/keyboards#2828
Fixes: #11683

fix(windows): add -k parameter for keyboards build.sh 🏠

---

package-lock.json
package.json

Fixes: #11689
I set the minimum to 18.20.0 because it's [the first version of `node 18` that has proper support for import attributes](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2024-03-26-version-18200-hydrogen-lts-richardlau).  [20.10.0](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2023-11-22-version-20100-iron-lts-targos) is the minimum Node 20 version for the same reason.

chore(common): update base-package node-engine setting

---

common/web/lm-worker/src/main/model-compositor.ts

Now only skips emitting the after-word text if it is the immediate prefix of the current right-hand context.
Fixes: #5256
**TEST_GOOGLE_DOCS_SUGGESTIONS**:  Using Keyman for Android and the Google Docs app, verify that applying predictive-text suggestions properly appends whitespace for English.
1. Install Keyman for Android and ensure that it is set as the default system keyboard.
2. Load Google Docs (doing any sign-in, etc necessary)
3. Type `th`, then select the `the` suggestion.
4. Verify that the caret is after a space following `the`.
5. Type some more text - a few words.
6. Move the caret to directly after the `the`.
7. Tap an available suggestion - `they` and `there` will likely be available options, so pick one.
8. Verify that no _additional_ space is added and that `the` is …

change(web): change after-word whitespace check to be more selective

---

common/web/types/src/util/file-types.ts
developer/src/kmc/build.sh
developer/src/kmc/src/commands/buildClasses/BuildKeyboardInfo.ts
developer/src/kmc/src/commands/buildClasses/BuildModelInfo.ts
developer/src/kmc/src/util/getLastGitCommitDate.ts
developer/src/kmc/test/fixtures/get-last-git-commit-date/README.md
developer/src/kmc/test/test-getLastGitCommitDate.ts

This updates the calculation of the lastModifiedDate property of the .keyboard_info and .model_info file. It now looks for the most recent commit to HISTORY.md, and then falls back to the project folder for .keyboard_info and .model_info.
getLastGitCommitDate now also returns UTC date (it was giving TZ=0 which is affected by daylight saving), and works for a file rather than just for a folder, and a corresponding unit test has been added.
The date strings returned will now always include '.000' msec suffix. I have manually verified that the import into the api.keyman.com database copes with this, and that this change still conforms to the expected schema for .keyboard_info and .model_info files.
Fixes: #11793
Cherry-pick-of: #11805

fix(developer): check HISTORY.md to get last modified date for keyboard_info and model_info 🍒 🏠

---

common/web/lm-worker/src/main/correction/distance-modeler.ts
common/web/lm-worker/src/main/correction/execution-timer.ts

chore(web): move correction-search execution timer to its own file 🕐 

---

common/web/lm-worker/src/main/correction/distance-modeler.ts
common/web/lm-worker/src/main/correction/execution-timer.ts
common/web/lm-worker/src/main/correction/index.ts
common/web/lm-worker/src/test/mocha/cases/edit-distance/execution-timer.js

This is work toward #3580, but not the final resolution of it.
There are three main operations during correction-search:
- replay of old results, if applicable
- generation of new corrections
- generation of predictions rooted on found corrections
Each type naturally has a different 'expected' runtime... so we now make buckets for each.  We can then use stats principles to detect outliers on each level.  (Mixing them all together = higher variance, thus worse detection.)
Also adds a full set of unit tests at 100% coverage for the new implementation.
Fun detail - in practice, when running all of the unit tests on my personal machine, it's able to pick up a fair few 1-5 ms outliers during the prediction-oriented tests!  We previously lacked the resolution to detect those smaller-end cases. …

refactor(web): overhaul predictive-text engine's timer to better detect paused time 🕐 

---

linux/keyman-config/keyman_config/convertico.py
linux/keyman-config/keyman_config/install_kmp.py
linux/keyman-config/keyman_config/view_installed.py

This changes re-creates the `<package>.bmp.png` as well as the `<package>.json` files if they are missing when `km-config` starts.
- `<package.bmp.png` gets created from a `.bmp` or `.ico` file included in the package, similar to what happens when installing the keyboard.
- `<package>.json` gets created from downloaded metadata, similar to the installation.
If the files are missing or we can't write to the directory, e.g. if it's the shared area, we skip the re-creation.
Fixes: https://github.com/keymanapp/keyman/issues/9396
Also some small refactorings.
- Reboot
- Install the Khmer Angkor keyboard
- Install the SIL IPA keyboard into the shared …

feat(linux): re-create missing files at run-time

---

common/web/lm-worker/src/main/model-compositor.ts

Now only skips emitting the after-word text if it is the immediate prefix of the current right-hand context.
Fixes: #5256
Cherry-pick-of: #11800

change(web): change after-word whitespace check to be more selective 🍒  🏠

---

developer/src/kmc-ldml/src/compiler/messages.ts
developer/src/kmc-ldml/test/fixtures/sections/layr/error-bogus-modifiers.xml
developer/src/kmc-ldml/test/test-layr.ts

- the error message was broken when there wasn't a layer id (which is allowed)
- add a test case
Fixes: #10553

fix(developer): layr: fix modifier err message on layer w/o id 🙀 

---

android/KMEA/app/src/main/assets/android-host.js
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Fixes: https://github.com/keymanapp/keyman/issues/11532
Cherry-pick-of: https://github.com/keymanapp/keyman/pull/11826

fix(android): clear globe highlight when displaying keyboard picker 🍒  🏠

---

android/KMEA/app/src/main/assets/android-host.js
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Fixes: #11532
**TEST_REPRO**: Attempt to reproduce #11532.
1. Install this PR's Keyman for Android build and give all permissions to the application.
2. Check the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Install the "Khmer angkor" keyboard by clicking Settings/Install Keyboard/Install from keyman.com.
4. Change the keyboard from Khmer to English by short-pressing the globe key.
5. Open the "Keyboard Picker" dialog by long-pressing the globe key.
6. Select the default keyboard (e.g., English) and then return to the keyman home screen.
7. Verify that the globe key is no longer highlighted.
8. Open the "Keyboard Picker" dialog by long-pressing the globe key (again).
9. Dismiss the keyboard picker without selecting any …

fix(android): clear globe highlight when displaying keyboard picker

---

linux/ibus-keyman/src/engine.c
linux/ibus-keyman/src/keymanutil.c
linux/ibus-keyman/src/keymanutil.h
linux/ibus-keyman/src/test/keymanutil_tests.c
linux/ibus-keyman/tests/testfixture.cpp

This renames the existing methods that read and write keyboard options so that it's visible from the name that they read/write keyboard options. This is in preparation of new methods that read and write more general options, related to #7697.

refactor(linux): rename methods that deal with keyboard options :checkered_flag: 

---

.clang-format

This change updates two formatting options:
- pointers and references will be left-aligned (`int* foo`). Previously we had the setting to left-align but that got ignored because of the `DerivePointerAlignment` setting which tries to use the style used elsewhere in the file, which is not good to get consistent styling.
- no longer always add a line break after the return type of a function, only if type and name don't fit in a line. Unfortunately clang-format doesn't have a setting to only add the line break if the method definition is too long to fit in one line. The new setting matches the alternative formatting from our style guide.

chore(common): update C/C++ formatting options

---

linux/keyman-config/keyman_config/get_kmp.py

Using the cache when getting data from the server is just an optimization to speed up things. However, things still work if we don't use the cache. This change therefore catches the AttributeError that sometimes happen on some machines for unknown reasons and falls back to not using the cache.
Fixes: #11855
Fixes: [KEYMAN-LINUX-6R](https://keyman.sentry.io/issues/KEYMAN-LINUX-6R)
- Reboot
**TEST_STILL_WORKS**: test that installing a keyboard in Keyman Configuration still works

fix(linux): ignore exceptions trying to install cache

---

common/web/input-processor/src/corrections.ts
web/src/engine/osk/src/visualKeyboard.ts

While investigating the current state of predictive text for a different work item, I noticed that we weren't actually getting fat-finger data from simple keypresses with the current state of `master` and 17.0.  The data was calculated... it just wasn't passed along properly.
TEST_FAT_FINGER: Using Keyman for Android, verify that corrections to nearby keys works properly.
1. Tap `T` near its center, then tap `i`.  
2. Verify that corrections starting with `To` appear.

fix(web): use fat-finger data with simple keypresses

---

developer/src/common/include/kmn_compiler_errors.h
developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
developer/src/kmcmplib/src/CompMsg.cpp
developer/src/kmcmplib/src/Compiler.cpp

Currently, keys must be a UTF-16 code unit or a virtual key. Non-BMP characters are unsupported. Technically, there is space available in the .kmx `COMP_KEY` structure to accommodate UTF-32 codepoints, from kmx_file.h:
KMX_WORD_unaligned Key;
KMX_WORD_unaligned _reserved;
However, the utility of this is almost nil, as it is very unlikely we will encounter base keyboards (for mnemonic layouts) that generate any characters outside the BMP, so there is little value in adding support for this at this time.
The compiler will generate an error if this is encountered.
Note: unit test is not cherry-picked because gtest was added in 18.0.
Fixes: #11643
Cherry-pick-of: #11806

fix(developer): prevent non-BMP characters in key part of rule 🍒 🏠

---

common/models/templates/src/index.ts
common/models/templates/src/trie-model.ts
common/web/lm-worker/src/main/correction/distance-modeler.ts
common/web/lm-worker/src/test/mocha/cases/edit-distance/distance-modeler.js
common/web/utils/src/index.ts
common/web/utils/src/priority-queue.ts
common/web/utils/src/test/priorityQueue.js

This PR was originally part of #10973.  
Note how the `PriorityQueue` implementation is currently part of `common/models/templates`, but for dictionary-based wordbreaking, it's needed in `common/models/wordbreakers` as well.   As the `wordbreakers` package is lower-level and is imported _by_ `common/models/templates`, it'd be awkward to have an inverted import.
Note that it's already used fairly extensively within `common/web/lm-worker` via import from the `common/models/template` package.

refactor(common/models): move TS priority-queue implementation to web-utils 📚 

---

windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/calldll.cpp
windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/k32_dbg.cpp
windows/src/engine/keyman32/k32_globals.cpp
windows/src/engine/keyman32/keyman32.cpp
windows/src/engine/keyman32/keymanengine.h
windows/src/engine/keyman32/kmhook_getmessage.cpp
windows/src/engine/keyman32/kmprocess.cpp

Also cleanup the use of state.msg as that had no relevant data in it.
Fixes: #11917
* **TEST_WINDOWS:** Please run a basic test of Windows functionality, verifying that Keyman operates as expected.

refactor(windows): remove wm_keyman_keydown and wm_keyman_keyup

---

core/tests/unit/ldml/test_kmx_plus.cpp

Without this change trying to build the core tests on Ubuntu 24.04 fails with "error: 'intptr_t' has not been declared in '::'". I'm not sure why that is happening, but this is an easy fix.

fix(core): allow to successfully build on Ubuntu 24.04

---

common/models/templates/src/trie-model.ts
common/models/templates/test/test-trie-traversal.js
common/models/types/index.d.ts

This PR was originally part of #10973.
In order to efficiently traverse a full lexical efficiently for dictionary-based wordbreaking, it's best to directly provide relevant probability data as efficiently as possible.  Fortunately, it's easily possible to make this O(1) on the lexical model's internal iterator - the `LexiconTraversal` type.  It would take O(log(N)) time to recompute it via the model's `.predict` method instead.
Note that this provides two different probability value types:
1. The probability of each reached entry.
2. The probability of the highest-frequency entry either represented by the current node or by any of its descendants.
There are uses for this outside of dictionary-based wordbreaking, too.  The latter 'probability' listed above can be useful for optimizing the …

feat(web): provide lexicon probabilities directly on the search path 📚 

---

common/models/templates/src/trie-model.ts
common/models/templates/test/test-trie-traversal.js
common/models/types/index.d.ts

This PR was originally part of https://github.com/keymanapp/keyman/pull/10973.
These changes will facilitate the next PR's changes (#11870), in which it becomes possible to support prediction, in full, solely via the `LexiconTraversal` iterator structure.
Note that this gives us a neat way to support new model types:  if a `LexiconTraversal` can be defined for that model, we can efficiently search it and predict for it, even if it's not actually supported by a Trie!  There would be no need for the model to define a separate `predict` method on the model itself, as it can be implemented via the traversal.

feat(common/models): support direct-child access for Trie node iteration 📚 

---

common/models/templates/src/trie-model.ts
common/models/types/index.d.ts

This PR follows from #11868 and #11869.  While not originally part of #10973, it certainly leverages the same set of changes and will make a great base for future work toward user-dictionary support.  (I did originally piece this together at the same time, though - just as a 'sibling' branch instead of as a descendant.)
Rather than keep two separate sets of logic for navigating through the Trie's nodes, this set of changes removes the old pattern, allowing prediction-lookup based on a prefix to operate via the properties defined on the `LexiconTraversal` structure.  This essentially "dog-foods" the new pattern while keeping to DRY principles.
As mentioned in the description of #11868, this also aims to support merging / blending two (or more) different models together via their …

change(common/models/templates): rework Trie predict method to utilize traversals 📚 

---

common/predictive-text/unit_tests/in_browser/cases/worker-dummy-integration.spec.ts
common/test/resources/model-helpers.mjs
common/web/lm-worker/src/main/model-compositor.ts
common/web/lm-worker/src/test/mocha/cases/worker-predict.js

This PR serves to facilitate autocorrect. 
After some brainstorming and design work, I've determined that a suggestion's underlying correction will be an important factor in deciding whether or not to enable the suggestion for automatic application.  While it _is_ possible to recompute some of the properties after the fact, the logic will be much more straightforward if we properly track each prediction's underlying correction from the outset.
While making the change, I remembered a comment from one of my recent PRs: https://github.com/keymanapp/keyman/pull/11424#discussion_r1619739920
> Where else would this type be used?
(In regard to `lexical-p`, `correction-p`, etc)
We're able to more cleanly compute these values now.  Additionally... we don't really need to emit them during standard …

change(web): track the base correction for generated predictions 📚 

---

common/models/types/index.d.ts
common/web/input-processor/src/text/prediction/languageProcessor.ts
common/web/input-processor/src/text/prediction/predictionContext.ts
common/web/lm-worker/src/main/model-compositor.ts
web/src/engine/osk/src/banner/suggestionBanner.ts

This establishes something I've been waiting a long time to enable:  when one prediction is sufficiently more likely than all alternatives, it will be automatically selected for application when tapping the space bar.  In short:  auto-correct.
Current conditions for auto-correct:
- The pre-existing prefix for the correction/prediction is not zero-length.  (We don't want to auto-select 'the' from an empty string with SIL EuroLatin, after all.)
- Any "correction" applied to generate the suggestion must be the highest-probability correction that leads to a valid suggestion.
- It doesn't have to be the most likely keystroke - just the most likely keystroke that can reasonably produce a word from the model.
- The suggestion to be auto-selected must have at least twice the probability of all …

feat(web): add and enable auto-correction 📚 

---

windows/src/engine/keyman32/hotkeys.cpp
windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp
windows/src/engine/keyman32/kmhook_keyboard.cpp
windows/src/engine/keyman32/serialkeyeventserver.cpp
windows/src/engine/keyman32/syskbdnt.cpp
windows/src/engine/keyman32/syskbdnt64.cpp

For: https://github.com/keymanapp/keyman/pull/11906#discussion_r1665233617

chore(windows): add comments for _WIN64 tests

---

common/predictive-text/unit_tests/headless/worker-trie-integration.js
common/web/lm-worker/src/test/mocha/cases/worker-model-compositor.js

fix(web): remedy unit-test stability issues

---

windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/appint/aiTIP.h
windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/kmprocessactions.cpp
windows/src/engine/kmtip/globals.h
windows/src/engine/kmtip/inserttext.cpp
windows/src/engine/kmtip/kmkey.cpp
windows/src/engine/kmtip/kmtip.h
windows/src/test/manual-tests/test_i3619/i3619tip/i3619tip/i3619tip/kmkey.cpp

Fixes: #7870
Add a bool to the KeymanGetContext call, the Windows engine will emit backspace keystroke when text is selected and a backspace key is pressed allowing the application to make the correct decision on how to handle it.  
This change feels like it is half the solution the full solution would be to have a mechanism for allowing the Keyman Core to know if text has been selected. &hasSelection As discussed in issue #9073 as a Future solution. 
With this change the core will request the character closest to the selection to be deleted its internal cache will match this, even though the engine will essentially overide this request and just emit the backspace keystroke.  As it is TSF - context aware it will be updated on the next key stroke anyway with the correct context. 
Install …

fix(windows): add text selected bool emit backspace key when text selected in TSF

---

developer/src/kmc-kmn/src/kmw-compiler/compiler-globals.ts
developer/src/kmc-kmn/src/kmw-compiler/javascript-strings.ts
developer/src/kmc-kmn/test/fixtures/kmw/version_9_caps_lock.kmn
developer/src/kmc-kmn/test/fixtures/kmw/version_9_chiral_modifiers.kmn
developer/src/kmc-kmn/test/fixtures/kmw/version_auto_caps_lock.kmn
developer/src/kmc-kmn/test/fixtures/kmw/version_auto_chiral_modifiers.kmn
developer/src/kmc-kmn/test/kmw/test-kmw-compiler.ts
developer/src/kmc-kmn/test/kmw/test-kmw-messages.ts

Adds support for determining minimum version 10.0 when chiral modifiers or state modifiers are found in virtual keys, e.g. `[LCTRL K_A]`, `[CAPS K_A]`, and corresponding unit tests.
Fixes: #11958

feat(developer): handle automatic versioning of chiral modifiers

---

developer/src/kmc-kmn/src/kmw-compiler/compiler-globals.ts
developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts
developer/src/kmc-kmn/test/fixtures/kmw/version_special_key_caps.keyman-touch-layout
developer/src/kmc-kmn/test/fixtures/kmw/version_special_key_caps.kmn
developer/src/kmc-kmn/test/fixtures/kmw/version_special_key_caps_14.kmn
developer/src/kmc-kmn/test/kmw/test-kmw-compiler.ts
developer/src/kmc-kmn/test/kmw/test-kmw-messages.ts

Special key caps on normal keys in touch layout files are supported with Keyman 14.0 and later versions. Handle automatic determination of the version number if `store(&VERSION)` is not present. Add corresponding unit tests.
Fixes: #11960

feat(developer): handle automatic versioning of special key caps on normal keys

---

developer/src/kmc/src/commands/messageCommand.ts
developer/src/kmc/src/messages/infrastructureMessages.ts
developer/src/kmc/src/messages/messageNamespaces.ts
developer/src/kmc/src/util/extendedCompilerOptions.ts

Fixes: #10875
(Low priority for user test because this is probably mostly used internally)

feat(developer): add searching for message identifiers to `kmc message`

---

common/web/input-processor/src/text/prediction/predictionContext.ts

Addresses part of #11963.  In particular, this change ensures that an option to preserve the current context exists whenever auto-correct is ready to activate in a manner that would change the context.
These changes, in isolation, break one input-processor unit test.  The follow-up PR - #11970 - has changes that address the affected area anyway and will fix the unit test as a side-effect.  Accordingly, all user tests for this PR will be included as part of it.

fix(web): present a "keep" option when a context-altering suggestion is auto-selected

---

common/web/input-processor/src/text/prediction/languageProcessor.ts
common/web/input-processor/src/text/prediction/predictionContext.ts
common/web/lm-worker/src/main/model-compositor.ts

Addresses part of https://github.com/keymanapp/keyman/issues/11963. 
In particular, this change ensures that auto-correct doesn't immediately undo reversions immediately after applying them.  Suppose a name is typed that's not in the dictionary.  (I ran into this personally when typing "Esther" and trying to get "Esther" to actually 'stick'.)  The idea:
- Reverting restores the original text, as it was.
- If I'm undoing an auto-correct, the original text may well have been correct.
- If I tap space right after a reversion, I likely mean for the reverted text to be preserved, rather than re-corrected.  
- I didn't want whatever suggestion was applied, so we should be way less aggressive about auto-applying one.
- On the other hand, if I make edits to the text before pressing space, …

fix(web): prevents auto-accept immediately after reversion

---

.github/workflows/deb-packaging.yml
linux/scripts/launchpad.sh

Ubuntu 23.10 Mantic is EOL, Ubuntu 24.10 Oracular will be the next release.

chore(linux): remove Ubuntu Mantic, add Oracular

---

.github/workflows/deb-packaging.yml
linux/.pbuilderrc
linux/scripts/cow.sh
linux/scripts/launchpad.sh

Mantic is EOL.
Kind of cherry-pick of #12003, but doesn't add Oracular and removes Mantic from some additional files that no longer exist in `master` branch.

chore(linux): remove Ubuntu 23.10 Mantic 🏠

---

common/web/keyboard-processor/src/text/stringDivergence.ts
common/web/keyboard-processor/tests/dom/cases/domKeyboardLoader.spec.ts
common/web/types/package.json
common/web/types/src/kmx/element-string.ts
common/web/types/src/ldml-keyboard/pattern-parser.ts
common/web/types/src/main.ts
common/web/types/src/util/consts.ts
common/web/types/src/util/index.ts
common/web/types/src/util/util.ts
developer/src/kmc-ldml/src/compiler/empty-compiler.ts
developer/src/kmc-ldml/src/compiler/messages.ts
developer/src/kmc-ldml/src/compiler/tran.ts

Consider this a "patch PR" for #11881 - feel free to merge it early without my consent, as this is intended to fix issues I personally raised for that PR.

chore(web): improve auto-test references to globals in #11881

---

windows/src/engine/keyman32/kmhook_getmessage.cpp

Fixes: #11919 
The code has already been commented out, this was more a clean-up of dead code. WM_KEYDOWN events are not expected by the IM window anymore.

chore(windows): remove the posting WM_KEYUP/DOWN events to IM

---

common/web/lm-worker/src/main/model-compositor.ts

After working again with the main method for generating predictions over the past few PRs, I got reminded of just how _long_ that method is.  This was further complicated after recognizing issues regarding near-match suggestion prioritization (#11876).
With a bit of effort, we should be able to spin off individual 'sections' of the predict method into their own individual functions.  This would help clarify exactly what each section specifically needs and increase code clarity for future maintainers.
For simplicity of review, I'll be doing one section at a time, working from bottom-to-top.  Each section has effects for those that follow it, so this should minimize the number of cross-effects for the PR set as a whole.

refactor(web): extract suggestion-finalization block into its own function 📚 

---

developer/src/kmc-ldml/src/compiler/compiler.ts
developer/src/kmc-ldml/src/compiler/disp.ts
developer/src/kmc-ldml/src/compiler/empty-compiler.ts
developer/src/kmc-ldml/src/compiler/keys.ts
developer/src/kmc-ldml/src/compiler/layr.ts
developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts
developer/src/kmc-ldml/src/compiler/linter-keycaps.ts
developer/src/kmc-ldml/src/compiler/loca.ts
developer/src/kmc-ldml/src/compiler/meta.ts
developer/src/kmc-ldml/src/compiler/tran.ts
developer/src/kmc-ldml/src/compiler/vars.ts
developer/src/kmc-ldml/src/compiler/visual-keyboard-compiler.ts
developer/src/kmc-ldml/src/main.ts
developer/src/kmc-ldml/test/test-disp.ts
developer/src/kmc-ldml/test/test-helpers.ts
developer/src/kmc-ldml/test/test-keys.ts
developer/src/kmc-ldml/test/test-layr.ts
developer/src/kmc-ldml/test/test-linter.ts
developer/src/kmc-ldml/test/test-loca.ts
developer/src/kmc-ldml/test/test-messages.ts
developer/src/kmc-ldml/test/test-meta.ts
developer/src/kmc-ldml/test/test-strs.ts
developer/src/kmc-ldml/test/test-tran.ts
developer/src/kmc-ldml/test/test-vars.ts
developer/src/kmc/src/messages/messageNamespaces.ts

It is easier to differentiate between all the compiler message classes if each one has its own name; and this makes it consistent with other compiler message classes and removes one more unnecessary alias.
BREAKING: `LdmlKeyboardCompilerMessages` export is renamed to `LdmlCompilerMessages`.

chore(developer): rename kmc-ldml `CompilerMessages`, `LdmlKeyboardCompilerMessages` to `LdmlCompilerMessages`

---

developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/package-compiler-messages.ts
developer/src/kmc-package/src/compiler/package-keyboard-target-validator.ts
developer/src/kmc-package/src/compiler/package-metadata-collector.ts
developer/src/kmc-package/src/compiler/package-validation.ts
developer/src/kmc-package/src/compiler/package-version-validator.ts
developer/src/kmc-package/src/compiler/windows-package-installer-compiler.ts
developer/src/kmc-package/src/main.ts
developer/src/kmc-package/test/test-messages.ts
developer/src/kmc-package/test/test-package-compiler.ts

It is easier to differentiate between all the compiler message classes if each one has its own name.

chore(developer): rename kmc-package `CompilerMessages` to `PackageCompilerMessages`

---

developer/src/tike/project/Keyman.Developer.System.Project.kpsProjectFile.pas

When a project is loaded, the IDE parses .kps files to retrieve metadata for viewing. If the .kps file was malformed, then the parser could fail, blocking the load of the project. Instead, we just ignore the errors and show no metadata. Note that the Package Editor already loads the file successfully and reports on the problem, allowing the user to fix it.
Fixes: #11992
Fixes: KEYMAN-DEVELOPER-23W

fix(developer): handle errors parsing .kps file when loading project

---

common/web/lm-worker/src/main/predict-helpers.ts
common/web/lm-worker/src/test/mocha/cases/auto-correct.js

Fixes: #11935
Also adds a fix for this comment on an ancestor PR: https://github.com/keymanapp/keyman/pull/11876#issuecomment-2216341032
> we're not currently auto-selecting something like can't with priority when the current context is cant - where there's no exact context match, but there is an exact-key match. I'll want to fix that, whether it be within this PR or within a descendant.
In retrospect, `cant` actually _is_ a valid English word, but it's rare enough to communicate the core idea here, I believe.

feat(web): add unit tests for predict auto-selection method 📚 

---

common/models/templates/src/common.ts
common/web/lm-worker/src/main/models/dummy-model.ts

The old `DummyModel` used to mock models for automated testing was lacking support for a number of model features we'd like to unit test.  Since we're looking to unit-test the recently-refactored predictive-text component functions, it would be helpful to use it for mocking instead of requiring a fully-compiled model.  So, I thought it wise to give the old test-oriented class an update.  

feat(web): extend unit-test oriented dummy model 📚 

---

common/web/lm-worker/src/main/predict-helpers.ts
common/web/lm-worker/src/test/mocha/cases/auto-correct.js
common/web/lm-worker/src/test/mocha/cases/suggestion-similarity.js

While #11941 addresses the main aspects of #11935, it doesn't hurt to add tests for highly-related behaviors.  It could easily be argued that suggestion-similarity is a "part" of the auto-select process and thus should be included before fully resolving #11935 anyway.
There are a couple of small tweaks to facilitate simpler unit-test comparisons; why assign something `undefined` when it's implicitly `undefined` anyway?  (The thing is, the Chai assertion library differentiates between implicit and explicit `undefined` for certain test-assertion statements.)
For what it's worth, #11941 + #11944 achieve full test coverage for `processSimilarity` and `predictionAutoSelect` according to the coverage report output.

feat(web): add unit tests for suggestion-similarity detection 📚 

---

developer/src/common/include/kmn_compiler_errors.h
developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
developer/src/kmc-kmn/test/fixtures/keyboards/hint_index_store_long.kmn
developer/src/kmc-kmn/test/fixtures/keyboards/hint_index_store_long_key.kmn
developer/src/kmc-kmn/test/fixtures/keyboards/warn_index_store_short.kmn
developer/src/kmc-kmn/test/fixtures/keyboards/warn_index_store_short_key.kmn
developer/src/kmc-kmn/test/test-messages.ts
developer/src/kmcmplib/src/CompMsg.cpp
developer/src/kmcmplib/src/Compiler.cpp

While it does not cause any problems to have a index() store that is longer than its corresponding any() store, it often indicates a mistake, as the trailing characters in the store are ignored. Thus, adding as a hint (which can be disabled via message suppression) rather than as a warning or error.
Example code:
```
store(abc) 'abc'
store(defg) 'defg'
any(abc) + 'x' > index(defg, 1)  c generates HINT_IndexStoreLong
```
Fixes: #10666

feat(developer): add hint when index() store is longer than any() store

---

linux/keyman-config/km-kvk2ldml

If the user specifies just an output file without directory name (or doesn't specify an output file), we will now use the current directory instead of crashing.

fix(linux): set local directory if not specified

---

developer/src/.gitignore
developer/src/common/web/test-helpers/tsconfig.json
developer/src/common/web/utils/test/tsconfig.json
developer/src/kmc-analyze/build.sh
developer/src/kmc-analyze/src/analyzer-messages.ts
developer/src/kmc-analyze/tsconfig.json
developer/src/kmc-keyboard-info/test/tsconfig.json
developer/src/kmc-keyboard-info/tsconfig.json
developer/src/kmc-kmn/build.sh
developer/src/kmc-kmn/package.json
developer/src/kmc-kmn/test/tsconfig.json
developer/src/kmc-kmn/tsconfig.json
developer/src/kmc-ldml/test/tsconfig.json
developer/src/kmc-ldml/tsconfig.json
developer/src/kmc-model-info/test/tsconfig.json
developer/src/kmc-model-info/tsconfig.json
developer/src/kmc-model/test/tsconfig.json
developer/src/kmc-package/test/tsconfig.json
developer/src/kmc/test/tsconfig.json
developer/src/kmc/tsconfig.json
developer/src/server/tsconfig.json
package-lock.json
package.json

Fixes: #12027
This addresses the build failure in the parent PR #12017.

fix(developer): remove `paths` from tsconfig.json

---

developer/docs/api/etc/kmc-analyze.api.md
developer/docs/api/etc/kmc-keyboard-info.api.md
developer/docs/api/etc/kmc-kmn.api.md
developer/docs/api/etc/kmc-ldml.api.md
developer/docs/api/etc/kmc-package.api.md

Updates API references per api-extractor for v18 alpha

chore(developer): api doc refresh

---

oem/firstvoices/keyboards.csv

Cherrypick of #11889 to stable-17.0
keyboards.csv changes
* Add fv_severn_ojibwa_rdot
* Add fv_ojibwa_rdot
* Add fv_ojibwa_ifinal
* Add fv_ojibwa_ifinal_rdot Update other keyboard versions (as of fv_all.kmp 12.14 [fv_all] Add BC Sans Regular font keyboards#2902)

chore(android,ios): Add ojibwa ifinal/rdot keyboards to FirstVoices 🏠

---

HISTORY.md

Manually updates HISTORY.md from 17.0.327 stable. (See #9415)
Also populates blank history entries (See #10351)

chore(common): Update history from 17.0.327 and add missing descriptions

---

android/KMEA/app/src/main/assets/android-host.js
common/web/input-processor/src/text/prediction/predictionContext.ts
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js
web/src/app/browser/src/contextManager.ts
web/src/app/browser/src/keymanEngine.ts
web/src/app/browser/src/viewsAnchorpoint.ts
web/src/app/webview/src/keymanEngine.ts
web/src/engine/main/src/keymanEngine.ts
web/src/engine/osk/src/config/viewConfiguration.ts
web/src/engine/osk/src/views/floatingOskView.ts
web/src/engine/osk/src/views/oskView.ts

Fixes #11962.
Reverts #11174.
Reverts: #11258.
Debug-mode keyboards are not safe to load before the OSK is initialized due to certain debug APIs being published _through_ `keyman.osk`.  The cleanest way to remedy #11962 is thus to revert the PR that attempts to load keyboards before the OSK is initialized.
There were a few merge conflicts that resulted when reverting a few of the commits, though nothing terribly extensive.  Still, it'd be best to test and verify that the reversion process was handled correctly.
**TEST_REPRO**:  Attempt to reproduce #11962 using Keyman for Android.
- Install the package provided within that issue.
- Force-quit the app.
- Relaunch the app.
- If the issue is not properly fixed, an error notification will appear on app-relaunch.
**TEST_ANDROID**:   Do simple …

change(web): revert #11174, which loads keyboards before initializing the OSK

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m

Add custom tags to Sentry so that Mac issues display whether accessibility is enabled when keyman starts and also the current clientAppId and keyboard.
The new tags will be displayed in Sentry as shown below:

change(mac): add custom tags in sentry to better identify errors

---

developer/src/common/web/test-helpers/tsconfig.json
developer/src/common/web/utils/test/tsconfig.json
developer/src/kmc-analyze/tsconfig.json
developer/src/kmc-keyboard-info/build.sh
developer/src/kmc-keyboard-info/test/tsconfig.json
developer/src/kmc-keyboard-info/tsconfig.json
developer/src/kmc-kmn/tsconfig.json
developer/src/kmc-ldml/test/tsconfig.json
developer/src/kmc-ldml/tsconfig.json
developer/src/kmc-model-info/test/tsconfig.json
developer/src/kmc-model-info/tsconfig.json
developer/src/kmc-model/test/tsconfig.json
developer/src/kmc-model/tsconfig.json
developer/src/kmc-package/test/tsconfig.json
developer/src/kmc-package/tsconfig.json
developer/src/kmc/test/tsconfig.json
developer/src/kmc/tsconfig.json
developer/src/server/tsconfig.json

With the full move to ES Modules, we no longer need to include `references` in tsconfig.json, as we can rely on package.json and build.sh dependency management. Note however that `tsc -b` may not work to build dependencies -- they need to be built using `build.sh`, which calculates which dependencies need building.
kmc-keyboard-info was missing a dependency link to kmc-package in build.sh, correcting this at the same time.
See-also: #12033
See-also: #12028
Relates-to: #12027

chore(developer): remove redundant references from tsconfig.json

---

android/KMEA/app/src/main/assets/android-host.js
common/web/input-processor/src/text/prediction/predictionContext.ts
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js
web/src/app/browser/src/contextManager.ts
web/src/app/browser/src/keymanEngine.ts
web/src/app/browser/src/viewsAnchorpoint.ts
web/src/app/webview/src/keymanEngine.ts
web/src/engine/main/src/keymanEngine.ts
web/src/engine/osk/src/config/viewConfiguration.ts
web/src/engine/osk/src/views/floatingOskView.ts
web/src/engine/osk/src/views/oskView.ts

Debug-mode keyboards are not safe to load before the OSK is initialized due to certain debug APIs being published _through_ `keyman.osk`.  The cleanest way to remedy #11962 is thus to revert the PR that attempts to load keyboards before the OSK is initialized.
Fixes: #11962
Reverts: #11174
Reverts: #11258
Cherry-pick-of: #12015
**TEST_REPRO**:  Attempt to reproduce #11962 using Keyman for Android.
- Install the package provided within that issue.
- Force-quit the app.
- Relaunch the app.
- If the issue is not properly fixed, an error notification will appear on app-relaunch.
**TEST_ANDROID**:   Do simple general-use testing with Keyman for Android and report back if any odd behaviors occur.
**TEST_IOS**: Do simple general-use testing with Keyman for iOS and report back if any odd …

change(web): revert #11174, which loads keyboards before initializing the OSK 🍒 🏠

---

web/src/engine/osk/src/views/oskView.ts

#12015 included a reversion to #11258, which was originally a followup that edited the same region as edited by #11174, the focus of #12015.  #11258's changes should be fine to include though, so this PR restores its change.
**TEST_REPRO**:  Attempt to reproduce #11962 using Keyman for Android.
- Install the package provided within that issue.
- Force-quit the app.
- Relaunch the app.
- If the issue is not properly fixed, an error notification will appear on app-relaunch.
**TEST_ANDROID**:   Do simple general-use testing with Keyman for Android and report back if any odd behaviors occur.
**TEST_IOS**: Do simple general-use testing with Keyman for iOS and report back if any odd behaviors occur.
**TEST_WEB**:  Do simple general-use testing with the "Test unminified Web" test page and report …

fix(web): unrevert #11258, leaving OSK hidden before instructed to display

---

developer/src/common/web/test-helpers/tsconfig.json
developer/src/common/web/utils/test/tsconfig.json
developer/src/kmc-analyze/tsconfig.json
developer/src/kmc-keyboard-info/build.sh
developer/src/kmc-keyboard-info/test/tsconfig.json
developer/src/kmc-keyboard-info/tsconfig.json
developer/src/kmc-kmn/tsconfig.json
developer/src/kmc-ldml/test/tsconfig.json
developer/src/kmc-ldml/tsconfig.json
developer/src/kmc-model-info/test/tsconfig.json
developer/src/kmc-model-info/tsconfig.json
developer/src/kmc-model/test/tsconfig.json
developer/src/kmc-model/tsconfig.json
developer/src/kmc-package/test/tsconfig.json
developer/src/kmc-package/tsconfig.json
developer/src/kmc/test/tsconfig.json
developer/src/kmc/tsconfig.json
developer/src/server/tsconfig.json

Reverts keymanapp/keyman#12037. The references are needed currently, for `tsc -b` to rebuild the referenced projects.

chore(developer): Revert "chore(developer): remove redundant references from tsconfig.json"

---

package-lock.json
package.json
resources/build/_builder_nvm.sh
resources/build/jq.inc.sh
resources/shellHelperFunctions.sh

Used by default only on build agents. See docs/build/node.md and resources/build/_builder_nvm.sh on  master (18.0) branch for documentation of this change -- documentation only added on master.
Specifies node v18.17.0.
Fixes: #11376
Cherry-pick-of: #12069

chore(common): use `nvm` to select version of node for builds 🍒 🏠

---

developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmcmplib/include/kmcmplibapi.h
developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/CompilerErrors.cpp
developer/src/kmcmplib/src/CompilerErrors.h
developer/src/kmcmplib/src/CompilerInterfaces.cpp
developer/src/kmcmplib/src/CompilerInterfacesWasm.cpp
developer/src/kmcmplib/src/NamedCodeConstants.cpp
developer/src/kmcmplib/tests/api-test.cpp
developer/src/kmcmplib/tests/gtest-compiler-test.cpp
developer/src/kmcmplib/tests/gtest-compmsg-test.cpp
developer/src/kmcmplib/tests/util_callbacks.cpp
developer/src/kmcmplib/tests/util_callbacks.h

This is a significant rework of the callbacks from kmcmplib -- using `std::vector` and other C++ std classes to remove memory management calls and simplify the WASM bindings.
* Removes redundant calls for `loadFileProc` (aka `loadFile` in the new pattern)
* Uses C++ classes on the interface side
* Removes global callbacks from the Javascript side
In preparation for cleanup of compiler messages.

refactor(developer): improve the callbacks for kmcmplib 🌋

---

developer/src/kmcmplib/src/CompileKeyboardBuffer.cpp
developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/UnreachableRules.cpp
developer/src/kmcmplib/src/UnreachableRules.h
developer/src/kmcmplib/src/kmcmplib.h
developer/src/kmcmplib/tests/api-test.cpp
developer/src/kmcmplib/tests/gtest-compiler-test.cpp

This supports upcoming changes for parameterized errors in `GetCompileTargetsFromTargetsStore` and `VerifyUnreachableRules` (now a `void` return because it always returned success anyway).

refactor(developer): move error reporting inside `GetCompileTargetsFromTargetsStore` and `ProcessGroupFinish` 🌋

---

developer/src/kmcmplib/src/CheckForDuplicates.cpp
developer/src/kmcmplib/src/CheckNCapsConsistency.cpp
developer/src/kmcmplib/src/CheckNCapsConsistency.h
developer/src/kmcmplib/src/CompileKeyboardBuffer.cpp
developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/CompilerErrors.cpp
developer/src/kmcmplib/src/CompilerErrors.h
developer/src/kmcmplib/src/CompilerInterfaces.cpp
developer/src/kmcmplib/src/DeprecationChecks.cpp
developer/src/kmcmplib/src/DeprecationChecks.h
developer/src/kmcmplib/src/UnreachableRules.cpp
developer/src/kmcmplib/src/versioning.cpp
developer/src/kmcmplib/src/versioning.h
developer/src/kmcmplib/tests/gtest-compiler-test.cpp

This can be reviewed commit-by-commit
1. Replace `AddWarning()` and `AddWarningBool()` macro usage with call to `ReportCompilerMessage()`
The `AddWarning()` and `AddWarningBool()` macros just called `ReportCompilerMessage()`. A side-effect of removing `AddWarningBool()` is that the functions that called it always returned `TRUE` (and the return value was never checked anyway), and so these functions have been made `void`.
2. rename `AddCompileError()` to `ReportCompilerMessage()`

refactor(developer): rename compiler error reporting functions in kmcmplib 🌋

---

developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/CompilerErrors.cpp
developer/src/kmcmplib/src/CompilerErrors.h
developer/src/kmcmplib/src/CompilerInterfaces.cpp
developer/src/kmcmplib/src/kmcmplib.h

chore(developer): support filename field in kmcmplib compiler messages 🌋

---

developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/versioning.h

Remove the `VERIFY_KEYBOARD_VERSION()` and `VERIFY_KEYBOARD_VERSION_ret()` macros, and instead use `VerifyKeyboardVersion()`. The DRYing out of this function call pattern moved the return statement into a macro, which is an inappropriate way to reduce repetition, because (a) it is hard for devs to spot function exits, and (b) automated code analysis tools stumble on it.
Also means that we uncover more clearly the return mismatches between `KMX_DWORD` and `KMX_BOOL` through the compiler source.
I think this is the last PR in this chain, for now. See #12062 for further cleanup (waiting for other unit tests to be completed first).
Fixes: #12047

refactor(developer): replace `VERIFY_KEYBOARD_VERSION()` calls with `VerifyKeyboardVersion()` 🌋

---

developer/src/samples/imsample/imdllref.rtf
developer/src/samples/imsample/imlib.h
developer/src/tike/debug/UfrmDebugStatus_Events.pas
windows/src/engine/keyman32/appint/aiWin2000Unicode.cpp
windows/src/engine/keyman32/appint/appint.cpp
windows/src/engine/keyman32/appint/appint.h
windows/src/engine/keyman32/kmprocess.cpp
windows/src/engine/testhost/testhost.cpp

Fixes: #11925
QIT_VSHIFTDOWN and QIT_VSHIFTUP is no longer sent out in the windows engine. This commit cleans up any remnant references to these.

chore(windows): remove QIT_VSHIFTDOWN QIT _VSHIFTUP

---

common/models/templates/src/index.ts
common/models/templates/src/tokenization.ts
common/models/templates/test/test-tokenization.js
common/web/lm-worker/src/main/correction/context-tracker.ts
common/web/lm-worker/src/main/model-compositor.ts
common/web/lm-worker/src/main/model-helpers.ts

In pursuit of a fix for #11963 - particularly, for better punctuation handling in our predictive-text engine - this PR changes the tokenization function to emit tokens for whitespace in addition to non-whitespace.  This is only done at the `common/models/template` level thus far in order to keep the changeset constrained.
I've adapted the original tokenization unit tests to work with the new return format.  For now, within the lm-worker at large, the new tokenization output format is simply mapped to the original output format.
The next three PRs in sequence will integrate the enhanced tokenization pattern into the predictive-text process:
- #11998
- #11979 
- #11997
----
For the reasoning behind this change, see https://github.com/keymanapp/keyman/issues/11963#issuecomment-2246953233. …

change(common/models): change model tokenization to also tokenize whitespace 📚 

---

common/web/lm-worker/src/main/correction/transform-tokenization.ts
common/web/lm-worker/src/test/mocha/cases/transform-tokenization.js

In order to better handle complex keystrokes that trigger context tokenization, this PR adds a method designed to split incoming keystroke Transforms according to their contribution to the tokenization of the context that results from applying it.
I'm not sure how to clearly and concisely describe it; I feel like the clearest "explanation" is via example.  So, toward that...
Example:
- Current context, before keystroke: `an apple b` 
- Tokenization: `['an', ' ', 'apple', ' ', 'b']`
- Context after keystroke: `an apple a day.`
- Tokenization: `['an', ' ', 'apple', ' ', 'a', ' ', 'day', '.']`
- Keystroke transform: `{ insert: 'a day', deleteLeft: 1 }` (delete one character - the 'b')
- Tokenization:
- `{ insert: 'a', deleteLeft: 1 }` - delete `'b'` from the corresponding token, inserting …

feat(web): support transform tokenization when given a root context 📚 

---

common/models/templates/src/index.ts
common/models/templates/src/tokenization.ts
common/web/lm-worker/src/main/correction/context-tracker.ts
common/web/lm-worker/src/main/model-compositor.ts
common/web/lm-worker/src/main/model-helpers.ts
common/web/lm-worker/src/main/predict-helpers.ts
common/web/lm-worker/src/test/mocha/cases/edit-distance/context-tracker.js

With these changes, the context-tracking + search-reuse mechanisms within our predictive-text engine will now use the new form of context tokenization introduced with #11975, including complete whitespace modeling.
Benefits:
- I personally feel like the context-matching algorithm is _far, far_ clearer and straight-forward to parse than before.
- The original version had to account for the lack of tokens representing whitespace, which introduced a number of complicating caveats.
- The new format is much more compatible with potential future efforts that might seek to do phrase-level correction and/or prediction.
- We get far closer to properly handling tokenization boundaries triggered by punctuation marks.
**Note**:  this PR has notable limitations when input causes a new token to result. …

change(web): track whitespace-aware tokenization for context + correction-search caching 📚 

---

common/predictive-text/src/node/tsconfig.json
common/web/lm-worker/build.sh

Ran into a scenario just earlier where `$KEYMAN_ROOT/common/web/lm-worker/build.sh clean build test` would fail because `tsc` was never used to actually build the project's files; the tests would report that certain imports from compiled source files were missing.  (The lm-worker currently does not provide a 'test-index', instead providing import maps to each source's compiled form.)
The only reason that our CI builds didn't fail is that `./common/predictive-text` built a project with a reference to the lm-worker project, and _that_ triggered the build that lets the associated tests pass.

fix(web): patch up worker build to provide artifacts for its tests

---

common/web/keyboard-processor/src/keyboards/defaultLayouts.ts
common/web/keyboard-processor/src/keyboards/keyboard.ts
common/web/keyboard-processor/src/keyboards/keyboardHarness.ts
common/web/keyboard-processor/src/text/codes.ts
common/web/keyboard-processor/src/text/defaultRules.ts
common/web/keyboard-processor/src/text/kbdInterface.ts
common/web/keyboard-processor/src/text/keyboardProcessor.ts
common/web/keyboard-processor/tests/node/chirality.js
common/web/keyboard-processor/tests/node/non-positional-rules.js
common/web/keyboard-processor/tests/node/specialized-backspace.js
common/web/types/src/consts/modifier-key-constants.ts
common/web/types/src/consts/virtual-key-constants.ts
common/web/types/src/kmx/kmx.ts
common/web/types/src/main.ts
web/src/app/browser/src/defaultBrowserRules.ts
web/src/app/browser/src/hardwareEventKeyboard.ts
web/src/engine/main/src/hardKeyboard.ts

refactor(web): refactor and harmonize constants 🏗️

---

developer/src/kmc-model/src/build-trie.ts

This PR is direct prep-work for #12083, making the code migration there much more straightforward by relocating a part of the code that should _not_ be migrated out from the part that _is_ migrated in advance.

refactor(developer/compilers): prepare for trie-compiler split 📖 

---

common/build.sh
developer/src/.build-builder
developer/src/build.sh
developer/src/common/build.sh
resources/build/builder.md
resources/build/test/builder-platform.test.sh
resources/build/test/test-utils.inc.sh
resources/build/test/test.sh
resources/builder.inc.sh

Add `builder_describe_platform` function to builder.inc.sh, associated documentation and unit test, and use it in Developer and Common build scripts.
If you run `./developer/src/build.sh` with no targets, it will build all available targets on the current platform -- for example on Linux, excluding projects like :tike.
However, if you run `./developer/src/build.sh :tike` on a mac or linux machine, then the build will fail with an error which is hopefully clear enough: 
```
Target :tike is unavailable because it requires win
```
Relates-to: #11755

chore(common): add support for build target platform exclusions

---

build.sh
resources/build/builder.md
resources/builder.inc.sh

This top-level builder script will build as many projects as are possible to build on the current platform. For example, iOS and macOS projects can only be built on macOS; Windows and parts of Developer can only be built on Windows.
Relates-to: #6268

feat(common): add top-level build.sh

---

common/models/templates/src/index.ts
common/models/templates/src/trie-builder.ts
developer/src/kmc-model/src/build-trie.ts

refactor(common/models): refactor migrated trie-construction code for improved encapsulation 📖 

---

common/models/templates/src/index.ts
common/models/templates/src/trie-builder.ts
common/models/templates/src/trie.ts
common/models/templates/test/test-trie-builder.js

This PR aims to further flesh-out the new `TrieBuilder` encapsulation.
Some of the less immediately-intuitive changes revolve around the modifications to `sortTrie`.  Here's what they allow:  the implementation now allows the Trie to be kept in sorted order even while edited at runtime, even if edits are interleaved with prediction requests!
The rest of the changes are focused on adding unit-test support directly for Trie construction and its various facets.  Note also the pending draft PR for compression and decompression - #11088.  Those features are likely to land here and afterward.  Fortunately, they're completely orthogonal to the "live sort" feature, in case we decide to drop it.

change(common/models):  add unit tests + optimize live Trie sorting 📖 

---

common/models/templates/src/traversal-model.ts
common/models/templates/src/trie-model.ts

The new `TraversalModel` type inherits almost all code from `TrieModel`, serving as its base class.  That said, `TrieModel` will still be responsible for `Trie` loading.
With this change, _any_ model (in theory) can now worry only about implementing the `LexiconTraversal` interface; the new class can take care of the rest.

refactor(common/models): spin off model template based directly on LexiconTraversals 📖 

---

common/models/templates/src/trie.ts
common/models/templates/test/test-trie-traversal.js
common/models/types/index.d.ts

At present, our correction and prediction search methods are not leveraging the generator-based form of the `children()` field on the `LexiconTraversal` type.  When we ask for it, we always utilize every entry in the array in some form.  So, why continue to maintain the generator pattern if we can just return an array instead?
To support #11994, this also adds a new entry to the returned objects:  `p`, the probability of the highest-frequency entry on the node's path.  We've already been returning it on the node itself, but there can be benefits to making it available _before_ constructing the traversal itself; we can compare against the value and avoid overhead if we decide not to take the path, rather than constructing it and only _then_ checking.
Part of the motivation here: …

refactor(common/models): convert traversal.children method to return array 📖 

---

common/web/lm-worker/src/test/mocha/cases/worker-model-compositor.js

So, it looks like I messed up with a merge conflict resolution a while back and restored a flaky component of one of our worker-oriented automated tests.  I can't seem to reproduce it on my local machine, but it has been affecting [a few of our CI builds](https://build.palaso.org/buildConfiguration/Keyman_Common_LMLayer_TestPullRequests/485803?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true).
The easiest solution is to drop that piece, especially since the value returned by the `await firstPredict` line is quite subject to race-condition-like effects.  The key thing to check is the stability for `await secondPredict`.
Ideally, I'd want to …

chore(web): drop flaky auto-test component

---

resources/builder.inc.sh

Previously we didn't show the description for the target if the target definition specified a an alternate folder, e.g. `:app=src/app`. This change fixes this.
**TEST_FIXED**:
- run `web/build.sh --help`
- verify that the following line displays (under Targets):
```
:test-pages                 Builds resources needed for the KMW manual testing pages
```

fix(common): show description even if child projects specifies path

---

docs/file-formats/kmx-file-format.md
docs/file-formats/kmx-plus-file-format.md

This is very long overdue. Good to have it written down somewhere, hopefully largely matching reality!
I moved the somewhat poorly named `C7043_ldml.md` at the same time to our docs folder.
Fixes: #11407
Unblocks: #12163

docs: add .kmx specification

---

web/src/test/auto/headless/engine/interfaces/prediction/predictionContext.spec.js

feat(web): test skipped prediction round handling

---

web/src/engine/osk/src/input/gestures/specsForLayout.ts

While @darcywong00 was working on #12170, he noticed that adjusting the longpress delay timing value wasn't passing through; this PR fixes that.
The cause:  on the longpress contact model, `duration` simply copied the value as a literal - not a function or property that will re-fetch it when needed.  So... it didn't update after the OSK was constructed.
The obvious solution is to make it a `get`-property on the model.  A little extra work was needed to preserve this due to the deep-copying protection that's in place to prevent permanent adjustments to the model definitions, but a well-placed redefinition of the property seems to do the job just fine.
I did a mild inspection of other uses for the gesture parameterization object and its values, and fortunately all other cases appear to be …

fix(web): support live configuration of longpress delay

---

web/src/engine/osk/src/config/commonConfiguration.ts
web/src/engine/osk/src/input/gestures/specsForLayout.ts
web/src/engine/osk/src/views/oskView.ts
web/src/engine/osk/src/visualKeyboard.ts

Adds a more 'stable' internal API point (`keyman.osk.gestureParams`) for configuring gesture parameterization settings.  I'm not convinced it's the long-term best solution as the "true" API point, but I think that even if not, it's likely to be quite usable by whatever we decide on _making_ that API point.
With this changeset, the gesture parameters only need to be adjusted once; the new setting will persist for the lifetime of the OSK, even across keyboard swaps.
Example:
```typescript
keyman.osk.gestureParams.longpress.waitLength = 5000 // sets the longpress delay to 5 sec
```

feat(web): add osk.gestureParams for better gesture-config persistence

---

developer/src/tike/child/UfrmDebug.pas

The Windows Clipboard Win+V key event emits Ctrl+V after rewriting the clipboard, in order to trigger a Paste action in the active app. However, the Ctrl key event has been given a scan code value of zero by Windows Clipboard, which was confusing the Keyman Developer Debugger, causing it to process Ctrl as an unrecognized key rather than as a modifier, and leading to an unsupported state.
This is a fix for the immediate issue. We could do more to improve resilience such that `km_core_state_debug_items()` can never end up with this exception when `km_core_process_event()` has returned true.
Fixes: #11978
Fixes: KEYMAN-DEVELOPER-20W
* **TEST_WIN_CLIPBOARD:** In the Keyman Developer debug window, Press Win+V, select an item from the clipboard history, and press Enter to insert it into the …

fix(developer): fix crash with Windows Clipboard by ignoring zero scan code in debugger

---

common/web/lm-worker/build.sh

Linux' file system is case-sensitive. This change fixes building `lm-worker` on case-sensitive systems.

fix(web): allow `lm-worker` to build on Linux

---

developer/src/tike/child/UfrmDebug.pas

The Windows Clipboard Win+V key event emits Ctrl+V after rewriting the clipboard, in order to trigger a Paste action in the active app. However, the Ctrl key event has been given a scan code value of zero by Windows Clipboard, which was confusing the Keyman Developer Debugger, causing it to process Ctrl as an unrecognized key rather than as a modifier, and leading to an unsupported state.
This is a fix for the immediate issue. We could do more to improve resilience such that `km_core_state_debug_items()` can never end up with this exception when `km_core_process_event()` has returned true.
Fixes: #11978
Fixes: KEYMAN-DEVELOPER-20W
Cherry-pick-of: #12166

fix(developer): ignore scan code if zero in debugger 🍒 🏠

---

web/src/engine/osk/src/input/gestures/specsForLayout.ts
web/src/engine/osk/src/visualKeyboard.ts

Turns out that #12176 actually broke flicks due to a side-effect of no longer rebuilding the gesture-parameterization object when swapping keyboards.  The culprit:
https://github.com/keymanapp/keyman/blob/69a3fa1795a457e49608e9f80561318d6dc556b7/web/src/engine/osk/src/input/gestures/specsForLayout.ts#L251
If rebuilding the parameter object from scratch, this is all well and good.  If _not_, however... we run the risk of keeping 'roaming' mode in place if the previous keyboard had roaming enabled.  This was the only spot that ever set the flag, so... it would never turn 'off' once turned 'on'.  Short version:  due to certain initialization patterns, it was basically _always_ turned on.  (When the OSK initializes during standard use, there's no actual Keyman keyboard ready yet... and so the …

fix(web): restore flick functionality

---

developer/src/kmc-keyboard-info/src/keyboard-info-compiler-messages.ts
developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts
developer/src/kmc-model-info/src/model-info-compiler-messages.ts
developer/src/kmc-model-info/src/model-info-compiler.ts

The Description field should be required for published keyboards and models, so this change means kmc-keyboard-info and kmc-model-info will report an error if it is missing.
Relates-to: keymanapp/keyboards#3037
Relates-to: keymanapp/lexical-models#262
Fixes: #12202

fix(developer): enforce presence of kps Info.Description field in info compilers

---

developer/src/kmc-keyboard-info/test/test-keyboard-info-compiler.ts
developer/src/kmc-package/src/compiler/package-compiler-messages.ts
developer/src/kmc-package/src/compiler/package-version-validator.ts
developer/src/kmc-package/test/fixtures/absolute_path/source/absolute_path.kps
developer/src/kmc-package/test/fixtures/invalid/error_package_file_has_empty_version.kps
developer/src/kmc-package/test/test-messages.ts
developer/src/kmc-package/test/test-package-compiler.ts

fix(developer): enforce presence of Version field when FollowKeyboardVersion is not set, in package compiler

---

developer/src/kmc-package/src/compiler/package-compiler-messages.ts
developer/src/kmc-package/src/compiler/package-version-validator.ts
developer/src/kmc-package/test/fixtures/absolute_path/source/absolute_path.kps
developer/src/kmc-package/test/fixtures/invalid/error_package_file_has_empty_version.kps
developer/src/kmc-package/test/test-messages.ts
developer/src/kmc-package/test/test-package-compiler.ts

Fixes: #12193
Cherry-pick-of: #12205

fix(developer): enforce presence of Version field when FollowKeyboardVersion is not set, in package compiler 🍒 🏠

---

developer/src/kmc-keyboard-info/src/keyboard-info-compiler-messages.ts
developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts
developer/src/kmc-model-info/src/model-info-compiler-messages.ts
developer/src/kmc-model-info/src/model-info-compiler.ts

The Description field should be required for published keyboards and models, so this change means kmc-keyboard-info and kmc-model-info will report an error if it is missing.
Relates-to: keymanapp/keyboards#3037
Relates-to: keymanapp/lexical-models#262
Fixes: #12202

fix(developer): enforce presence of kps Info.Description field in info compilers 🍒 🏠

---

windows/src/desktop/kmshell/xml/splash.xsl
windows/src/desktop/kmshell/xml/strings.xml

Fixes: #9635
The attribute `translatable="false"` and be added to the strings.xml for Android resources. This is a hint to the translators not to translate this string. However, that applies to the whole string.
This PR adds a new string for the splash screen which allows the translator to change the word "start" and place it before or after the place holder for Keyman.
1. Install the Keyman build for this PR
2. Start Keyman and the splash screen button should still correctly say Start Keyman.

fix(windows): "Keyman" is not localized in UI strings

---

core/cross-mac-arm64.build
core/cross-mac-x86_64.build

- add as option to compiler
- Match version in #11302
Fixes: #11423

fix(core): set mac build version for meson cli build to 10.13

---

core/wasm.build.linux.in
core/wasm.build.mac.in
core/wasm.defs.build
developer/src/kmcmplib/wasm.build.linux.in
developer/src/kmcmplib/wasm.build.mac.in
resources/locate_emscripten.inc.sh

`emcc.py` is not marked as executable in emcripten's git repo so the build failed when trying to locate emscripten. However, it turns out that `emcc` is marked as executable, so we use that instead on macOS and Linux (on Windows, executable bit is irrelevant).

fix(core): look for `emcc` instead of `emcc.py`

---

common/models/templates/src/tokenization.ts
common/models/templates/test/custom-breakers.def.js
common/models/templates/test/test-tokenization.js

This aims to mitigate the worst side-effects from custom wordbreakers exhibiting the same behaviors that resulted in #12200.
This strongly enforces tokenization in a single direction within the context, never rewinding - even if an encountered `span.left` value would otherwise indicate to do so.  This occurred in the improperly-implemented custom wordbreaker we published with `sil.km.gcc` - see https://github.com/keymanapp/lexical-models/pull/265, which corrects it.
As blank-string spans `''` always appear first within a `string` at index `0`, any time such a blank token appeared, it had the effect of that span being mapped to the _full context_ that preceded the span's actual position.  The next span in line would also appear to start from the beginning of context, which would never …

fix(web): improve tokenization output when wordbreaker breaks spec for span properties in output

---

web/src/engine/main/src/keymanEngine.ts
web/src/engine/osk/src/visualKeyboard.ts

Addresses part of #12214.
Does not fully solve the issue, as we'd need additionally need a way to pass a flag into the worker to further prevent corrective edits.
This fix does restore the correction-toggle back to its state from 16.0, but that still lacks the full intended effect for the toggle.

fix(web): disable fat-finger data use when mayCorrect = false

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/res/drawable/ic_action_decrement.xml
android/KMAPro/kMAPro/src/main/res/drawable/ic_action_increment.xml
android/KMAPro/kMAPro/src/main/res/layout/text_size_controller.xml

Follows #12227 and #12228 for #12215
This fixes the increment/decrement arrows on the "Text Size" dialog to be RTL compatible.
In RTL locales, the decrement arrow points to the right and increment arrow points to the left.
Also refactored the "Text size: " string so the numerals appear with regular Arabic numbers.
**Setup** - Install the PR build of Keyman for Android on an Android device/emulator. Then in Keyman for Android, change the display language to Arabic (an RTL language)
**TEST_TEXT_SIZE** - Verifies arrow keys on Text Size dialog are RTL compatible
1. Launch Keyman for Android where the display language is Arabic.
2. From the Keyman menu --> Text Size
3. On the "Text Size" dialog, verify the decrement arrow pointing right makes the text size smaller
4. On the "Text size" …

fix(android): Auto-mirror increment and decrement arrows for RTL support 📟

---

developer/src/kmcmplib/src/CompilerInterfacesWasm.cpp
resources/build/minimum-versions.inc.sh
resources/locate_emscripten.inc.sh

The build agents will now automatically install and activate the Emscripten version found in minimum-versions.inc.sh when configuring WASM projects. For developer machines, this behaviour can be enabled by setting the environment variable `KEYMAN_USE_EMSDK` (recommended).
This will be back-ported to 17.0 so that we can ensure that all builds use a consistent Emscripten version.
Also, Emscripten 3.1.60 made a breaking change to `BindingType::toWireType` (why is this done in a patch version?) so this change ensures that we can continue to build on 3.1.58 and 3.1.64 (which is needed for #12234), as a bridging strategy.
Relates-to: emscripten-core/emscripten#21692
Relates-to: #12234

chore(common): allow build agents to automatically select emsdk version, and enable support for 3.1.60+

---

core/wasm.build.linux.in
core/wasm.build.mac.in
core/wasm.defs.build
developer/src/kmcmplib/src/CompilerInterfacesWasm.cpp
developer/src/kmcmplib/wasm.build.linux.in
developer/src/kmcmplib/wasm.build.mac.in
resources/locate_emscripten.inc.sh

The build agents will now automatically install and activate the Emscripten version found in minimum-versions.inc.sh when configuring WASM projects. For developer machines, this behaviour can be enabled by setting the environment variable `KEYMAN_USE_EMSDK` (recommended).
Also, Emscripten 3.1.60 made a breaking change to `BindingType::toWireType` (why is this done in a patch version?) so this change ensures that we can continue to build on 3.1.58 and 3.1.64 (which is needed for #12234), as a bridging strategy.
Relates-to: emscripten-core/emscripten#21692
Relates-to: #12234
Cherry-pick-of: #12243
Cherry-pick-of: #12235

chore(common): allow build agents to automatically select emsdk version, and enable support for 3.1.60+ 🍒 🏠

---

web/src/engine/osk/src/visualKeyboard.ts

Fixes: #12231
TEST_DOC_KEYBOARDS:  Using the "Tests keyboard documentation rendering" Web test page, verify that the spacebar labels are always properly constrained within the space allotted to the spacebar.

fix(web): fix documentation-keyboard spacebar-text scaling

---

core/cross-mac-arm64.build
core/cross-mac-x86_64.build

- add as option to compiler
- Match version in #11302
Fixes: #11423
Cherry-pick-of: #12223

fix(core): set mac build version for meson cli build to 10.13 🍒 🏠

---

developer/src/kmc-model/test/test-compile-model.ts

chore(developer): extend timeouts for lm compiler tests to 5 secs

---

android/KMEA/app/src/main/assets/android-host.js

I was checking the Chrome console while investigating #12203 and noticed some stray debug statements.
This fixes some `console.debug` calls to use `console_debug` (the wrapper used in android-host.js)

chore(android): Cleanup stray debug statements in console

---

common/models/templates/src/common.ts
common/models/templates/src/index.ts
common/models/templates/src/trie-builder.ts
common/models/templates/src/trie-model.ts
common/models/templates/src/trie.ts
common/models/templates/test/test-trie-builder.js
developer/src/kmc-model/build.sh
developer/src/kmc-model/package.json
developer/src/kmc-model/src/build-trie.ts
package-lock.json
web/src/engine/predictive-text/worker-main/README.md

This PR extracts the changes currently within the `epic/user-dict` feature branch that are _also_ needed for enhanced model encoding to serve as the base of `epic/model-encoding`.  All were changes were previously reviewed for epic/user-dict:
- #12080
- #12084
- #12083
- #12085
- #12086
Other PRs have since been merged there, but are irrelevant for the purposes of the epic/model-encoding feature.

chore(models/templates): seed epic/model-encoding with cherry-pick from epic/user-dict 💾 

---

common/models/wordbreakers/src/dict/index.ts
common/models/wordbreakers/test/test-dict-breaker.js

This adds a first-pass feature for handling entries not found within the wordbreaker's backing data.  I won't claim it's the best solution, but it's definitely better than nothing - as evidenced by the practical cases displayed in the unit-test code.

feat(common/models/wordbreakers): fuse adjacent unmatched characters when dictionary-breaking 🔬 

---

common/models/wordbreakers/test/test-search-property.js

I noticed this after merging in the wordbreaker PRs - it appears one of the late changes to one of them had an unintended side effect in a descendant that wasn't caught before merge.

fix(web): fixes wordbreaker test import path

---

docs/file-formats/kmx-plus-file-format.md

docs(core): fix a typo in the KMX+ doc

---

oem/firstvoices/keyboards.csv

* Keyboard version updates corresponding to fv_all.kmp version 12.15
* Add fv_lekwungen. afaict, the language tag `str` is used for Sencoten and Lekwungen, so it's a future BCP 47 discussion in the FirstVoices team. See [review comment](https://github.com/keymanapp/keyboards/pull/2989#issuecomment-2251351179)
Note, there will be another bump in fv_all.kmp to get the final round of FV keyboard updates. But this is to get :cherries: picked into 17.0 to capture the latest fv_all.kmp.

chore(android,ios): Update FirstVoices keyboards to fv_all.kmp 12.15

---

core/src/ldml/ldml_processor.cpp
core/src/ldml/ldml_vkeys.cpp
core/src/ldml/ldml_vkeys.hpp

While the modifier state property in core's API is 16-bit, internally ldml_processor supports the modifier flag LDML_KEYS_MOD_OTHER with a value of `0x10000`, which requires widening the value (we match the 32-bit size of the KMX_DWORD value from KMX+).
Note: this is not yet well unit-tested.
Relates-to: #11072
Fixes: #12057
Cherry-pick-of: #12281

fix(core): properly support 'other' modifier state with `uint32_t` type 🍒 🏠

---

developer/src/common/web/utils/build.sh
developer/src/common/web/utils/src/types/ldml-keyboard/ldml-keyboard-xml-reader.ts

The default import path is relative to ldml-keyboard-xml-reader.js. The bundling of kmc with Keyman Developer reduces the directory tree depth, so we move the import path to be a subdirectory of the immediate parent directory, rather than two levels up, so that `C:\Program Files\Keyman\Keyman Developer\kmc` can refer to `C:\Program Files\Keyman\Keyman Developer\import` when kmc is bundled.
Fixes: #12279
**TEST_LDML_COMPILE:** Create an LDML keyboard and try to compile it -- it should not have the error "Import could not read data"

fix(developer): make LDML import path consistent for all bundlings of kmc

---

core/src/ldml/ldml_processor.cpp
core/src/ldml/ldml_vkeys.cpp
core/src/ldml/ldml_vkeys.hpp

While the modifier state property in core's API is 16-bit, internally ldml_processor supports the modifier flag LDML_KEYS_MOD_OTHER with a value of `0x10000`, which requires widening the value (we match the 32-bit size of the KMX_DWORD value from KMX+).
Note: this is not yet well unit-tested.
Will cherry-pick once approved.
Relates-to: #11072
Fixes: #12057
Please paste in the following LDML keyboard source for testing:
```xml
<?xml version="1.0"?>
<keyboard3 xmlns="https://schemas.unicode.org/cldr/45/keyboard3" locale="arc" conformsTo="45">
<info author="Marc Durdin" name="Test 'other' modifier"/>
<version number="1.0.0"/>
<keys>
<import base="cldr" path="45/keys-Zyyy-punctuation.xml"/>
<import base="cldr" path="45/keys-Zyyy-currency.xml"/>
<key id="a" output="🅐" />
<key id="b" output="🅑" …
```

fix(core): properly support 'other' modifier state with `uint32_t` type

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Follows #12125 and fixes #12310
This fixes the system ENTER key to prioritize certain actions (e.g. GO / SEARCH) over inserting a newline for multi-line fields.
**Setup** - Install the PR build of Keyman for Android on a device/emulator and set Keyman as the default system keyboard
* **TEST_SEARCH** - Verifies ENTER key submits search instead of inserting newline
1. Launch the Chrome browser
2. On the top search bar, select Keyman as the keyboard
3. Start typing
4. Hit the <kbd>ENTER</kbd> key
5. Verify Chrome performs the search
6. On Chrome, select the next line to start another search (below the top bar with the URL)
7. Start typing
8. Hit the <kbd>ENTER</kbd> key
9. Verify Chrome performs the search
* **TEST_MESSAGING** - Verifies ENTER key submits a newline instead of  sending text …

fix(android): Prioritize certain actions over multi-line for ENTER key

---

web/src/engine/interfaces/src/prediction/predictionContext.ts

Fixes: #12309
TEST_MID_CONTEXT_SUGGESTIONS:  Edit words in the middle of context and test their interactions with predictive-text.
- If a suggestion is applied via the banner...
- Verify that no new space is appended
- Verify that tapping the space bar afterward does emit the expected space.
- If a suggestion is applied automatically via the spacebar...
- Verify that a new space is appended.

fix(web): prevent unintuitive space-output blocking for mid-context suggestions

---

oem/firstvoices/keyboards.csv

:cherries: pick of #12362 to stable-17.0
Updates the FirstVoices mobile apps to the latest fv_all.kmp package (version 13.0)

chore(oem/fv): Update to fv_all 13.0 🏠

---

mac/Keyman4MacIM/Keyman4MacIM/Privacy/PrivacyConsent.m

Cherry-pick of #12354 
To read the state and gain access to the Accessibility permission under the macOS Privacy & Security settings, Keyman calls the API `CGPreflightPostEventAccess`.  This API is [documented as being available with with macOS 10.15](https://developer.apple.com/documentation/coregraphics/3656520-cgpreflightposteventaccess?language=objc) (Catalina), but, based on experience, this does not appear to be the case. Limit use of API `CGPreflightPostEventAccess` to macOS 11.0 (Big Sur) and later, and, instead, use an older API, `AXIsProcessTrusted`, with OS versions before 11.0.
Fixes: #12295
1. Install this version of Keyman on a system running macOS Catalina
1. Confirm that keyboards can be installed and that they appear in the Keyman menu
1. Type with the installed Keyman …

fix(mac): avoid crash on startup with macOS 10.15 (Catalina) 🍒 🏠 

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java

Fixes #11368
Fixes [KEYMAN-ANDROID-4G](https://keyman.sentry.io/issues/2705960665)
Turns out when the Android app is install a lexical-model package, we don't need to determine the `languageCount` (number of languages associated with the first keyboard package). That value is only used in the language-picker during keyboard package installation.

fix(android): Skip language counts for lexical-model packages

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java

:cherries: pick of #12361 to stable-17.0
skips computing languageCount for lexical-model packages

fix(android): skip language counts for lexical-model packages 🏠

---

web/src/app/browser/src/keymanEngine.ts

The help page for `BuildVisualKeyboard` is under `core`, not `osk`.

docs(web): fix link to documentation page

---

core/include/keyman/keyman_core_api.h
core/src/layout.hpp
core/src/mock/mock_processor.cpp

- loading a keyboard from a BLOB
- getting the on-screen keyboard layout from Core. This is an internal- only API because of it's use of C++.
Part-of: #11293
Part-of: #8093

feat(core): spec out Core API extensions 🎼

---

developer/src/kmcmplib/include/kmcmplibapi.h

For whatever reason I suddenly got compile errors on Ubuntu 24.04 when building Developer. Including `cstdint` solves this.
See also #11926.

fix(developer): fix building with Ubuntu 24.04

---

package-lock.json
web/.mocharc.json
web/package.json

#11746 removed the `ts-node` dependency. Unfortunately that broke running TypeScript test files with Mocha in VSCode Test Explorer because it no longer knows what to do with .ts files. This change adds the more modern `tsx` package as developer dependency, which allows to use Test Explorer again.
See https://stackoverflow.com/a/77609121.

chore(web): allow to run unit tests in vscode test explorer

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustLongpressDelayActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Follows #12170 and #12185 for adjusting the longpress delay.
This adds minimum and maximum longpress delay limits to the API per
https://github.com/keymanapp/help.keyman.com/pull/1500#discussion_r1730879065

fix(android): Add gating to setLongpressDelay()

---

common/web/types/src/kmx/kmx-plus/kmx-plus.ts
developer/src/kmc-ldml/src/compiler/vars.ts
developer/src/kmc-ldml/test/fixtures/sections/vars/fail-badref-7.xml
developer/src/kmc-ldml/test/test-vars.ts
developer/src/kmc-ldml/test/test-visual-keyboard-compiler.ts

Validation of vars was not properly checking for forward references to string variables. This, coupled with a null vs undefined bug in subsequent use, meant that forward reference variables were ending up with a literal string value of 'undefined'.
This also fixes the test for visual-keyboard-compiler, where the fixture was actually buggy and was the trigger for investigating this problem.
Fixes: #12403
Relates-to: #12395

fix(developer): check vars string usage before definition

---

common/web/types/src/kmx/kmx-plus.ts
developer/src/kmc-ldml/src/compiler/vars.ts
developer/src/kmc-ldml/test/fixtures/sections/vars/fail-badref-7.xml
developer/src/kmc-ldml/test/test-vars.ts
developer/src/kmc-ldml/test/test-visual-keyboard-compiler.ts

Validation of vars was not properly checking for forward references to string variables. This, coupled with a null vs undefined bug in subsequent use, meant that forward reference variables were ending up with a literal string value of 'undefined'.
This also fixes the test for visual-keyboard-compiler, where the fixture was actually buggy and was the trigger for investigating this problem.
Fixes: #12403
Relates-to: #12395
Cherry-pick-of: #12404

fix(developer): check vars string usage before definition 🍒 🏠

---

web/src/engine/js-processor/build.sh
web/src/test/auto/headless/engine/js-processor/kbdInterface.tests.ts

refactor(web): move kbdInterface tests to typescript 🎼

---

resources/git-hooks/commit-msg
resources/git-hooks/pre-commit

Sometime ago we lost the ability to detect git remotes that use ssh (git@github.com:keymanapp/keyman.git) and we only detect remotes that use https (https://github.com/keymanapp/keyman.git). This change restores this ability.
Also add some empty lines between the different parts of the error message.

chore(common): detect ssh remotes in git hooks

---

common/tools/hextobin/build.sh

This change fixes a dependency problem when building Core. Previously this failed on a clean source tree because hextobin was missing dependencies but didn't run its `configure` action if the top-level `node_modules` folder did already exist.

fix(common): add proper configure output for hextobin

---

developer/src/kmc/build.sh

Core depends on `kmc` which in turn depends on `core/include/ldml`. This change adds the missing dependency to the build script and fixes building core from a clean `core` subdirectory.

fix(core): add missing dependency for core

---

developer/src/kmc-ldml/src/compiler/compiler.ts

chore(developer): remove .js output from LDML compiler

---

mac/Keyman4Mac/Keyman4Mac/AppDelegate.m
mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/Base.lproj/preferences.xib
mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
mac/Keyman4MacIM/Keyman4MacIM/KMSettingsRepository.h
mac/Keyman4MacIM/Keyman4MacIM/KMSettingsRepository.m
mac/Keyman4MacIM/KeymanTests/TestAppDelegate.h
mac/Keyman4MacIM/KeymanTests/TestAppDelegate.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreHelper.h
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreHelper.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.h
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m
mac/KeymanEngine4Mac/KeymanEngine4MacTests/CoreTestStaticHelperMethods.m
mac/KeymanEngine4Mac/KeymanEngine4MacTests/KMEngineTests.m

In the Options tab of the Configuration window, removed the checkbox titled 'Use verbose Console logging'.
Also remove code related to debug mode. Instead of using the verbose logging option to determine whether we are in debug mode or not, write to the log based solely on the unified logging settings for Keyman. This change follows naturally from #11515.
Because the related UserDefaults setting is retired, introduce a new UserDefaults flag with a narrower scope to force a sentry crash for testing purposes. The key for this flag is "KMForceSentryError". It is not tied to any UI but can be set manually from the command line if needed for testing purposes.
Fixes: #11525

change(mac): remove verbose logging option

---

resources/build/builder.md
resources/builder.inc.sh
resources/shellHelperFunctions.sh

A lot of the `configure` actions rely on node dependencies and so call `npm install`. Without a internet connection this hangs forever, even if you had successfully installed the dependencies before and nothing changed since then. This change adds a `--offline` parameter that passes `--prefer-offline` to npm, which causes npm to use the cached dependencies.
Also sets the `MESON_PACKAGE_CACHE_DIR` environment variable so that all (sub-)projects share the same package cache dir. This will speed up regular builds a bit (e.g. `developer/src/kmcmplib` and `core` both have `icu4c` as a dependency), but will also help with offline builds.
`MESON_PACKAGE_CACHE_DIR` requires Meson 1.3, however older Meson versions ignore this environment variable and simply continue to use a cache per subproject, …

chore(common): Allow to build offline

---

docs/websites/README.md

Documents the website builder step how to skip generating CDN 
from keymanapp/keyman.com#471

docs(common): Document how to skip generating CDN on websites

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardWebViewClient.java

Fixes #12441 and needs to :cherries: pick to stable-17.0
This adds a check in System Keyboard to disable suggestion banner on certain fields (e.g. password field)
* **Setup** - Install the PR build of Keyman for Android on an Android device/emulator
* **TEST_BANNER_DISABLED_ON_PASSWORD** - Verifies suggestion banner is disabled on certain fields
2. On the Get Started menu, set Keyman as the default system keyboard
3. Launch Chrome and select a text area
4. With Keyman selected as the system keyboard, verify the OSK displays suggestions as you type
5. On Chrome, go to a page with password fields (e.g. https://darcywong00.github.io/examples/form.html). That page is small so you may need to zoom in
7. On the test page, select the "Visible Text Field"
8. Verify …

fix(android): Hide suggestion banner on password fields

---

developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts
developer/src/kmc-ldml/src/compiler/vars.ts
developer/src/kmc-ldml/test/fixtures/sections/vars/fail-invalid-identifiers.xml
developer/src/kmc-ldml/test/test-vars.ts

Adds checks for invalid string IDs and corresponding unit tests.
Note: marker tests will be split into separate issue+PR.
Fixes: #12451

fix(developer): prevent invalid string ids

---

developer/src/kmc-ldml/src/compiler/layr.ts
developer/src/kmc-ldml/test/fixtures/sections/layr/row-keys-whitespace.xml
developer/src/kmc-ldml/test/test-layr.ts

fix(developer): ignore excess whitespace in `<row keys>` attribute

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardWebViewClient.java

:cherries: pick of #12442 for stable-17.0
This adds a check in System Keyboard to disable suggestion banner on certain fields (e.g. password field)
* **Setup** - Install the PR build of Keyman for Android on an Android device/emulator
* **TEST_BANNER_DISABLED_ON_PASSWORD** - Verifies suggestion banner is disabled on certain fields
2. On the Get Started menu, set Keyman as the default system keyboard
3. Launch Chrome and select a text area
4. With Keyman selected as the system keyboard, verify the OSK displays suggestions as you type
5. On Chrome, go to a page with password fields (e.g. https://darcywong00.github.io/examples/form.html). That page is small so you may need to zoom in
7. On the test page, select the "Visible Text Field"
8. Verify the OSK displays …

fix(android): Hide suggestion banner on password fields 🍒 🏠

---

linux/debian/libkeymancore2.symbols

I have no idea why this C++ symbol suddenly shows up in the API check, but since it's not part of our API we can ignore it.

fix(linux): ignore additional C++ symbol in API check

---

.github/workflows/api-verification.yml

This change adds the branch name to the API verification workflow so that it's easier to see which run belongs to which PR or branch build.

chore(linux): display branch name with API verification

---

docs/file-formats/kmx-plus-file-format.md

docs(core): Update kmx-plus-file-format.md

---

resources/build/minimum-versions.inc.sh
resources/locate_emscripten.inc.sh

Also fix a typo in a comment in a script file.

docs(common): mention `KEYMAN_USE_NVM` in minimum versions doc

---

web/src/app/browser/src/contextManager.ts
web/src/app/browser/src/keymanEngine.ts
web/src/engine/keyboard/src/keyboards/keyboardProperties.ts
web/src/engine/main/src/keyboardInterface.ts
web/src/engine/osk/src/views/oskView.ts

docs(web): fix paths to several help pages

---

web/src/test/manual/web/index.html

When looking at `index.html` in VSCode's hierarchical view I noticed that the structure was off because some closing tags were missing. This fixes that.

docs(web): fix structure of test document

---

developer/docs/help/guides/test/keyboard-touch-and-desktop.md
developer/docs/help/guides/test/keyboard-touch-mobile-emulator.md

Follows #12427
Fixes the broken image links in the CI build of keymanapp/help.keyman.com#1579

docs(developer): Fix image links in help

---

oem/firstvoices/keyboards.csv

Fixes #12461 and depends on keymanapp/keyboards#3125
This updates keyboard versions and names in keyboards.csv to match the latest fv_all.kmp file.
Later will :cherries: pick for 17.0
**Setup** Install the PR build of FirstVoices for Android on device/emulator
* **TEST_VERSION_NAMES** - Verify keyboard versions and names updated
1. Launch FirstVoices app and go to "Select keyboards" menu
2. For the regions below, verify keyboard versions and names match the table below
* BC Coast
| Keyboard Name | Keyboard Version |
|-------------------------|---------------------------|
| Haíɫzaqvḷa            | 10.0                       |
| Sḵwx̱wú7mesh  (snichim) | 10.0        |
| X̄aʼislak̓ala          | 10.0                         |
| Éy7á7juuthem    | 10.2                        |
| ’Wuìk̓ala …

fix(oem/fv): Update keyboard versions and names for fv_all.kmp 13.1

---

oem/firstvoices/keyboards.csv

🍒 pick of #12461 to stable-17.0
This updates keyboard versions and names in keyboards.csv to match the latest fv_all.kmp file.
**Setup** Install the PR build of FirstVoices for Android on device/emulator
* **TEST_VERSION_NAMES** - Verify keyboard versions and names updated
1. Launch FirstVoices app and go to "Select keyboards" menu
2. For the regions below, verify keyboard versions and names match the table below
* BC Coast
| Keyboard Name | Keyboard Version |
|-------------------------|---------------------------|
| Haíɫzaqvḷa            | 10.0                       |
| Sḵwx̱wú7mesh  (snichim) | 10.0        |
| X̄aʼislak̓ala          | 10.0                         |
| Éy7á7juuthem    | 10.2                        |
| ’Wuìk̓ala                | 9.4                         |
* BC …

fix(oem/fv): Update keyboard versions and names for fv_all.kmp 🏠

---

.gitignore
common/tools/hextobin/build.sh
common/tools/hextobin/package.json

This improves #12440. The previous change was a bit fragile if we updated commander versions. This change now implements a better solution that doesn't rely on dependencies and their locations for detecting if we need to run the `configure` action for hextobin.

chore(common): improve configuration detection for hextobin

---

developer/src/common/delphi/components/Keyman.Developer.UI.RichEdit41.pas
developer/src/common/delphi/components/KeymanDeveloperDebuggerMemo.pas
developer/src/tike/child/Keyman.Developer.UI.Debug.UfrmLdmlKeyboardDebug.pas
developer/src/tike/child/UfrmDebug.pas
developer/src/tike/tike.dpr
developer/src/tike/tike.dproj

RichEdit allows text selection one character past end-of-string, so we need to cater for that as well in passing text ranges to the character grid.
Note: in draft as this uses RichEdit 2.0 which has other spacing issues for complex scripts (e.g. Khmer), need to be basing on RichEdit 4.1 preferably.
Fixes: #12454
* **TEST_KMN_DEBUGGER:** In Keyman Developer, open a Keyman .kmn keyboard, and press F5 to start the debugger. Run through a number of normal operations in the debugger, selecting text, typing, etc, and look for any unexpected display issues or anomalies. Pass this test if no issues are encountered.
* **TEST_LDML_DEBUGGER:** In Keyman Developer, open or create a Keyman LDML keyboard, and press F5 to start the debugger. Run through a number of normal operations in the debugger, …

fix(developer): use richedit in debug memo to support Egyptian cartouches

---

.github/workflows/api-verification.yml

- remove useless branch name from name (this is always `master` due to the way the workflow gets triggered)
- add PR# to step summary so that it's visible on the Summary page
- fix PR check message to say "API verification" instead of "Package build"

chore(linux): Improve output of API Verification

---

developer/src/kmc-ldml/src/compiler/messages.ts
developer/src/kmc-ldml/src/compiler/vars.ts
developer/src/kmc-ldml/test/fixtures/sections/vars/fail-invalid-identifiers.xml
developer/src/kmc-ldml/test/test-vars.ts

Adds checks for invalid string IDs and corresponding unit tests.
Fixes: #12451
Cherry-pick-of: #12465

fix(developer): prevent invalid string ids 🏠

---

developer/src/kmc-ldml/src/compiler/layr.ts
developer/src/kmc-ldml/test/fixtures/sections/layr/row-keys-whitespace.xml
developer/src/kmc-ldml/test/test-layr.ts

Cherry-pick-of: #12468
Fixes: #12449

fix(developer): ignore excess whitespace in `<row keys>` attribute 🏠

---

linux/scripts/deb-packaging.sh

When running locally it might be beneficial to be able run the API verification checks without having to build a binary package. This change allows to omit the `--bin-pkg` parameter and outputs a warning instead if it's missing.

chore(linux): allow to skip API change

---

developer/src/common/web/utils/src/types/kpj/kpj-file-reader.ts
developer/src/common/web/utils/src/types/kvks/kvks-file-reader.ts
developer/src/common/web/utils/src/types/ldml-keyboard/ldml-keyboard-xml-reader.ts
developer/src/kmc-package/src/compiler/kmp-compiler.ts

`toString()` only works when the Uint8Array is actually a Node Buffer.

fix(developer): use TextDecoder to convert Uint8Array to string

---

core/tests/meson.build
core/tests/unit/json/meson.build
core/tests/unit/utftest/meson.build

This fixes a meson warning that `common/include` was specified multiple times (in `core/include/meson.build` and
`core/tests/meson.build`).

fix(core): cleanup include directories 🎼

---

core/src/meson.build

Due to emscripten bug emscripten-core/emscripten#22754 specifying only `webview` as environment resulted in a broken `core.js` file when doing a debug build. In release builds things worked because of the `-Wl,-O1 -O2` that meson added for the release build. This change works around that bug by adding `web` as additional environment.

fix(core): fix generated `core.js` file for debug builds 🎼

---

mac/Keyman4MacIM/Podfile
mac/Keyman4MacIM/Podfile.lock

Upgrade Sentry version as 18.24 does not build with Xcode 16
See [sentry issue #4050](https://github.com/getsentry/sentry-cocoa/issues/4050) for more info.

chore(mac): support Xcode 16 build

---

android/KMEA/app/src/main/java/com/keyman/engine/packages/JSONUtils.java
android/KMEA/app/src/test/java/com/keyman/engine/packages/JSONUtilsTest.java
android/KMEA/test_resources/invalid_packages/null_languages/kmp.json

Fixes #11812 
This adds more error handling to JSONUtils.getLanguages() where the reported issue had crashed from
```
Exception java.lang.NullPointerException: Attempt to get length of null array
```
Also added a unit test.

fix(android/engine): Increase robustness when checking package kmp.json languages

---

developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts
developer/src/kmc-ldml/src/compiler/tran.ts
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-IllegalTransformUsetRHS-1.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/ok-2.xml
developer/src/kmc-ldml/test/test-tran.ts

- to="$[triisap]" is a mistake and not allowed.
- it's either meant to be a regular variable, or a map. Both of those are different syntax.
- add a test for the failing case, and also for the escaped case (to="\$[…)
Fixes: #12455

fix(developer): ldml don't allow a uset as right-hand-side variable

---

core/src/meson.build
web/src/app/browser/build.sh
web/src/app/webview/build.sh
web/src/engine/core-processor/build.sh
web/src/engine/core-processor/src/core-processor.ts
web/src/engine/core-processor/tsconfig.json
web/src/test/auto/dom/cases/core-processor/basic.spec.ts

There are too many `core.js` out there, so renaming it to a unique name makes it a bit easier to track down problems when debugging.

feat(core): rename `core.js` to `km-core.js` 🎼

---

web/src/test/auto/dom/web-test-runner.config.mjs
web/src/test/auto/integrated/web-test-runner.config.mjs
web/test.sh

This gives us access to the keyboards needed for the core-processor tests.

feat(core): run tests from `KEYMAN_ROOT` instead of `web` 🎼

---

developer/src/tike/main/KeymanDeveloperOptions.pas

Also use back-off logic for saving in case config file is locked by another process.
Cherry-pick-of: #12608
Fixes: #12607
Fixes: KEYMAN-DEVELOPER-1Z1

fix(developer): create Server config directory before options save 🍒 🏠

---

developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-kmn/test/fixtures/invalid-keyboards/error_cannot_read_bitmap_file.kmn
developer/src/kmc-kmn/test/test-messages.ts

If a file is not found, the loadfile callback now returns an empty array rather than null, which kmcmplib interprets as a missing file. This means a zero-byte file will have the same outcome but as it is also generally invalid, I think that is acceptable.
The 17.0 compiler has a different callback mechanism, so won't cherry-pick to 17.0.
Fixes: #12546
Fixes: KEYMAN-DEVELOPER-292

fix(developer): handle missing files in kmc-kmn

---

developer/src/kmc-model/src/build-trie.ts
developer/src/kmc-model/src/lexical-model-compiler.ts
developer/src/kmc-model/src/model-compiler-messages.ts
developer/src/kmc-model/test/fixtures/invalid-models/example.qaa.missing-wordlist/example.qaa.missing-wordlist.model.ts
developer/src/kmc-model/test/test-messages.ts

If a file is not found, loadfile returns null, which kmc-model now handles with a clear error message rather than a generic exception. Checks added for missing .model.ts and missing wordlist.tsv files. Added corresponding unit tests.
Fixes: #12553
Fixes: KEYMAN-DEVELOPER-294

fix(developer): handle missing files in kmc-model

---

developer/src/tike/main/KeymanDeveloperOptions.pas

Also use back-off logic for saving in case config file is locked by another process.
Fixes: #12607
Fixes: KEYMAN-DEVELOPER-1Z1

fix(developer): create Server config directory before options save

---

linux/scripts/launchpad.sh

With this change we will also build and provide binaries on Launchpad for the next Ubuntu release, 25.04 Plucky Puffin.

chore(linux): add support for Ubuntu 25.04 Plucky Puffin

---

linux/keyman-config/km-config

The previous implementation didn't work because the import of `download_and_install_package` happened before we checked for the missing dependencies and so the program crashed. This change fixes this and now does the imports after checking for the missing dependencies so that we can display an error message to the user.
Also fix a warning (positional arguments in `Gtk.MessageDialog` are deprecated).

fix(linux): properly check for missing dependencies

---

developer/src/kmc/src/util/getLastGitCommitDate.ts

Relates-to: keymanapp/keyboards#3143
Fixes: #12626
Fixes: KEYMAN-DEVELOPER-2AY

fix(developer): handle merge commits when checking git log date

---

linux/keyman-config/km-config

This works around a problem in webkit2gtk where the download dialog sometimes only renders a blank screen. Setting the environment variable seems to help, not only in the cases that the issue describes (with a NVidia graphics card), but also in my testing in a VM.
Fixes: #12587
Cherry-pick-of: #12616
**TEST_DOWNLOAD_PAGE**: Open Keyman Config and click on the Download Keyboard button. The Download Keyman Keyboards page should show up.

fix(linux): set environment variable for rendering of downloads dialog 🍒 🏠

---

developer/src/kmcmplib/src/debugstore.h

Fixes a regression arising from #12107 in debug store strings.
Three sets of eyes -- developer and two code reviewers and we still managed to miss this!
Relates-to: #12623
Relates-to: #12107

fix(developer): use 'N' for nomatch store debug strings (regression in #12107)

---

developer/src/kmcmplib/tests/get-test-source.sh

masaram_gondi.kmx fixture is built from a known-bad source, which is caught in kmcmplib 18.0.
This failure is because the keyboard source had non-BMP characters in the key part of the rule on line 215, which has been picked up by the 18.0 compiler in #11806:
```
$keymanonly: if(opt1 = 'gondi') any(Vyanjana)"𑵄" + any(Vyanjana)	>	index(Vyanjana,2) U+11D45
```
The trick here is that the compiled fixture developer/src/kmcmplib/tests/fixtures/keyboards-repo/masaram_gondi.kmx is based on a [broken version of the keyboard source](https://github.com/keymanapp/keyboards/blob/965ef1941f20a3bc0cb5d405792b4984cc46cd52/release/m/masaram_gondi/source/masaram_gondi.kmn) in the keyboards repo ([fixed version](https://github.com/keymanapp/keyboards/blob/06cfd2d186c9d5bf2fe2888a4121c746e87f2868/release/m/ma …

chore(developer): skip masaram_gondi in kmcmplib full test

---

developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
developer/src/kmc-kmn/src/kmw-compiler/kmw-compiler-messages.ts
developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts

All messages that reference keys in the touch layout will now give the row+column index of the key with the issue (and longpress/flick/multitap index as well if relevant).
Fixes: #12505

feat(developer): Report key 'address' in validation failures in layout compiler

---

oem/firstvoices/windows/src/inst/build.sh

Addresses a build warning. The path for the output file corresponds to the publish step for Keyman.
Fixes: #12636

fix(windows): correct path to output file in publish step for fv keyboards

---

developer/src/kmc-generate/src/abstract-generator.ts
developer/src/kmc-generate/src/keyman-keyboard-generator.ts
developer/src/kmc-generate/src/ldml-keyboard-generator.ts
developer/src/kmc-generate/src/lexical-model-generator.ts
developer/src/kmc-generate/test/test-abstract-generator.ts
developer/src/kmc-generate/test/test-keyman-keyboard-generator.ts
developer/src/kmc-generate/test/test-ldml-keyboard-generator.ts
developer/src/kmc-generate/test/test-lexical-model-generator.ts
developer/src/kmc-generate/test/test-messages.ts
developer/src/kmc-generate/test/tsconfig.json

Follows the pattern established with kmc copy

refactor(developer): define output path in kmc-generate artifacts

---

windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas

Fixes:#12463
The help link passed to the opening of the keyman help(CHM) on windows was broken for a number of the help links. This updates them.
Note: no help exists for apEntryHelper so it was set to the main `index` instead

fix(windows): help links updated

---

HISTORY.md

Update version history to include 17.0.330 to 17.0.332 stable changes.
For end of sprint A18S14 blogpost

chore(common): Add 17.0.330 - 17.0.332 to version history

---

developer/src/kmcmplib/build.bat
developer/src/kmcmplib/build.sh
developer/src/kmcmplib/commands.inc.sh
developer/src/kmcmplib/src/CompilerInterfaces.cpp
developer/src/kmcmplib/tests/get-test-source.sh
developer/src/kmcmplib/tests/util_callbacks.cpp
resources/build/build-utils-ci.inc.sh

The `--full-test` parameter in kmcmplib build.sh has not been working. This PR reconnects the parameter and also enables it by default for CI test builds (not release builds).
Note: the following keyboards are excluded because the snapshot versions have issues that the compiler now flags (these issues have all been resolved):
* (#12623) masaram_gondi: due to #11806
* (#12631) anii, sil_kmhmu: as ico references have mismatching case
* (#12631) fv_statimcets, fv_nuucaanul: as these include U+2002 which is not treated as whitespace on mac arch
See developer/src/kmcmplib/tests/get-test-source.sh
These keyboards could be included again if we update the snapshot to a later version -- but that requires a rebuild of the fixture expected keyboards with v16.0 compiler, so will necessarily exclude …

fix(developer): reconnect `--full-test` in kmcmplib build and enable for CI

---

linux/ibus-keyman/src/engine.c

Fixes: #12498
**TEST_WORKS**:  Keyman keyboards should still work as before, i.e. switch to a Keyman keyboard and verify that it behaves as expected.

feat(linux): use new km_core_keyboard_load_from_blob API method 🎼

---

developer/src/tike/debug/Keyman.System.Debug.DebugCore.pas
developer/src/tike/main/Keyman.System.KeymanCore.pas

Replaces `km_core_keyboard_load` with `km_core_keyboard_load_from_blob`.
Fixes: #12690

refactor(developer): `km_core_keyboard_load_from_blob` in debugger 🎼

---

common/web/types/src/main-ldml-keyboard.ts
common/web/types/src/main.ts
common/web/types/test/lexical-model-types.tests.ts
developer/src/common/web/utils/src/types/kmx/kmx-plus-builder/build-elem.ts
developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-ldml/src/compiler/compiler.ts
developer/src/kmc-ldml/src/compiler/empty-compiler.ts
developer/src/kmc-ldml/src/compiler/linter-keycaps.ts
developer/src/kmc-ldml/src/compiler/substitution-tracker.ts
developer/src/kmc-ldml/src/compiler/tran.ts
developer/src/kmc-ldml/src/compiler/vars.ts
developer/src/kmc-ldml/test/helpers/index.ts
developer/src/kmc-ldml/test/test-keys.ts
developer/src/kmc-ldml/test/test-tran.ts

refactor(common): move remaining LDML keyboard types into `LdmlKeyboardTypes`

---

android/README.md
android/docs/internal/README.md

Action item from Keyman Team Meetings in November 2024
> Add `/<platform>/docs/internal` for new implemented feature Markdown content in Keyman repo
This adds a README for the new folder and updates existing Keyman for Android README's.

docs(android): Add android/docs/internal/README

---

windows/src/engine/keyman32/K32_load.cpp

Fixes: #12500 
Keyman Engine and one of the old unit tests has been updated to use keyman load.
**TEST_SWITCHING_KEYBOARDS**:  Keyman keyboards should still work as before, i.e. switch to a Keyman keyboard and verify that it behaves as expected. Switch to a second Keyman  keyboard and verify that is behaves as expected.

feat(windows): keyboard load blob 🎼

---

docs/build/linux-ubuntu.md
docs/build/macos.md
docs/build/windows.md

Applying the equivalent changes from the windows.md in #12700
@ermshiperete and @sgschantz  can you verify this as I just copied from Windows and have not tested on linux or macos.

docs(common): linux and macOS emscripten setup

---

developer/src/common/web/utils/build.sh
developer/src/kmc-analyze/build.sh
developer/src/kmc-copy/build.sh
developer/src/kmc-generate/build.sh
developer/src/kmc-keyboard-info/build.sh
developer/src/kmc-kmn/build.sh
developer/src/kmc-ldml/build.sh
developer/src/kmc-model-info/build.sh
developer/src/kmc-model/build.sh
developer/src/kmc-model/package.json
developer/src/kmc-package/build.sh
developer/src/kmc/build.sh

This change adds the mocha-teamcity-reporter which outputs the running tests in a special format that TeamCity can interpret. This allows TC to show which tests run as well as the number of tests run.
Also refactor some of the build scripts to use functions.
Note that we had to explicitly add `--check-coverage=false` (which is the default) to get successful builds when we run on TC.

refactor(developer): output number of tests when running on TC

---

common/web/types/build.sh

This change adds the mocha-teamcity-reporter which outputs the running tests in a special format that TeamCity can interpret. This allows TC to show which tests run as well as the number of tests run.

refactor(common): output number of tests when running on TC

---

linux/ibus-keyman/meson.build
linux/ibus-keyman/src/meson.build

This change uses the G_DISABLE_ASSERT flag to disable assertions for release builds.
See https://docs.gtk.org/glib/func.assert.html
Related: #12715

fix(linux): disable assertions in release builds of ibus-keyman

---

resources/locate_emscripten.inc.sh

This change allows to build with emscripten if offline (when passing the `--offline` parameter). Previously this failed because as part of locating emscripten we try to pull the latest repo version and install the desired emscripten version. With this change when `--offline` is specified we try to use the currently installed version of emsdk. If it isn't installed or if the wrong version is installed we will fail the build.

chore(common): add offline support for emscripten

---

developer/src/common/web/utils/build.sh
developer/src/kmc-analyze/build.sh
developer/src/kmc-copy/build.sh
developer/src/kmc-generate/build.sh
developer/src/kmc-keyboard-info/build.sh
developer/src/kmc-kmn/build.sh
developer/src/kmc-ldml/build.sh
developer/src/kmc-model-info/build.sh
developer/src/kmc-model-info/package.json
developer/src/kmc-model/build.sh
developer/src/kmc-model/package.json
developer/src/kmc-package/build.sh
developer/src/kmc/build.sh
resources/build/builder.md
resources/shellHelperFunctions.sh

refactor(developer): unify test action

---

developer/src/README.md

chore(developer): seed epic/ldml-editor 🗼

---

android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Follows #12125 and fixes #12743
The ENTER key was enhanced in the Keyman system keyboard depending on the type of input field.
This ports the functionality to the FirstVoices for Android and KMSample2 apps.
Copying user tests from the original PR:
**Setup** - On an Android device, install the PR build of FirstVoices for Android and the Android KMSample2 app. Preferably use a physical device instead of emulator because you'll also need additional Android apps installed:
* Google Keep
* Messaging app like Facebook Messenger
* X (twitter)
For the corresponding groups, setup a keyboard and enable as the default corresponding keyboard. 
On FirstVoices, can do Region --> BC Coast --> SENCOTEN keyboard.
* GROUP_FV: Use FirstVoices for Android as system keyboard
* GROUP_SAMPLE2: Use KMSample2 as …

feat(android): Enhance how ENTER key is handled for FV and KMSample2

---

mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreWrapper.m

To load a keyboard using Keyman Core, call `km_core_keyboard_load_from_blob instead` of `km_core_keyboard_load`. This allows for the removal of platform file access from within Core.
Fixes: #12499
* **TEST_LOAD_KEYBOARD**: keyboards load and are usable
1. Install this version of Keyman and switch to the Khmer Angkor keyboard
1. Verify that typing produces Khmer characters

refactor(mac): pass kmx data blob to keyman core instead of file path

---

common/web/types/tests/ldml-keyboard/unicodeset-parser-api.tests.ts

This change renames a new test file and moves it to the new location. This file was overlooked in #12709.

fix(common): rename test file

---

developer/docs/help/reference/kmc/cli/reference.md
developer/src/common/web/utils/src/cloud-urls.ts
developer/src/common/web/utils/src/github-urls.ts
developer/src/common/web/utils/src/index.ts
developer/src/kmc-copy/src/KeymanProjectCopier.ts
developer/src/kmc-copy/src/cloud.ts
developer/src/kmc-copy/src/copier-messages.ts
developer/src/kmc-copy/test/copier.tests.ts
developer/src/kmc-copy/test/fixtures/online/api.keyman.com/#keyboard#khmer_angkor
developer/src/kmc-copy/test/fixtures/online/api.keyman.com/#model#nrc.en.mtnt
developer/src/kmc/src/commands/copy.ts

Cherry-picking to master as epic/shared-fonts may not land in 18.0, and we don't want the new `kmc copy` command to have unnecessarily changes to command line after release.
Fixes: #12746
Cherry-pick-of: #12754

change(developer): use full github url in kmc copy parameters 🍒

---

resources/shellHelperFunctions.sh

This fixes the build on my Windows machine. Previously `nvm install/use` for whatever reason caused Windows to no longer be able to find `node` thus causing the build to fail. Waiting for `nvm use` to finish solves the build failure. This change when run on Windows additionally first checks the current node version and installs and activates it only if it is not installed.

chore(core): only install node on Windows if not available

---

developer/src/kmc-generate/src/template/wordlist-lexical-model/README.md
developer/src/kmc-generate/test/fixtures/lexical-model/sample.en.sample/README.md

Lexical models are not specific to a platform, so the readme should not list supported platforms.
Fixes: #12592

fix(developer): remove platforms from kmc-generate LM readme

---

linux/debian/changelog
linux/scripts/debian.sh
linux/scripts/upload-to-debian.sh

This fixes the `upload-to-debian.sh` script if the `chore/linux/changelog` branch was created a while back while the base branch moved in the meantime. In this case we have to use `--force` instead of `--force-with-lease` otherwise `git` gets confused. This is safe to do since the intention is that we replace the previous commit and we know that there is (should be) only one commit on the `chore/linux/changelog` branch.

fix(linux): pushing of updated changelog branch

---

linux/scripts/debian.sh
linux/scripts/upload-to-debian.sh

This fixes the `upload-to-debian.sh` script if the `chore/linux/changelog` branch was created a while back while the base branch moved in the meantime. In this case we have to use `--force` instead of `--force-with-lease` otherwise `git` gets confused. This is save to do since the intention is that we replace the previous commit and we know that there is (should be) only one commit on the `chore/linux/changelog` branch.
Cherry-pick: #12818 

fix(linux): pushing of updated changelog branch 🍒 🏠

---

linux/Dockerfile
linux/debian/com.keyman.config.appdata.xml
linux/debian/com.keyman.ibus_keyman.metainfo.xml
linux/debian/copyright
linux/debian/libkeymancore2.symbols
linux/ibus-keyman/src/engine.c
linux/ibus-keyman/src/engine.h
linux/ibus-keyman/src/keyman-service.c
linux/ibus-keyman/src/keyman-service.h
linux/ibus-keyman/src/keymanutil.c
linux/ibus-keyman/src/keymanutil.h
linux/ibus-keyman/src/kmpdetails.c
linux/ibus-keyman/src/main.c
linux/ibus-keyman/src/test/testdata/kmp.json
linux/ibus-keyman/src/test/testdata/kmp1.json
linux/ibus-keyman/src/test/testdata/kmp2.json
linux/ibus-keyman/tests/ibusimcontext.c
linux/ibus-keyman/tests/ibusimcontext.h
linux/keyman-config/COPYING
linux/keyman-config/Makefile
linux/keyman-config/buildtools/help2md
linux/keyman-config/keyman_config/keyman_option.py
linux/keyman-config/keyman_config/sentry_handling.py
linux/keyman-config/locale/keyman-config.pot

We only use a C API in Core, so we can safely ignore all C++ symbols that show up in the symbols file. Those come from std template instantiations.
Also update AppStream metadata.
Fixes: #12051 

fix(linux): work around Lintian errors

---

linux/Dockerfile
linux/debian/changelog
linux/debian/com.keyman.config.appdata.xml
linux/debian/com.keyman.ibus_keyman.metainfo.xml
linux/debian/copyright
linux/debian/libkeymancore1.symbols
linux/ibus-keyman/src/engine.c
linux/ibus-keyman/src/engine.h
linux/ibus-keyman/src/keyman-service.c
linux/ibus-keyman/src/keyman-service.h
linux/ibus-keyman/src/keymanutil.c
linux/ibus-keyman/src/keymanutil.h
linux/ibus-keyman/src/kmpdetails.c
linux/ibus-keyman/src/main.c
linux/ibus-keyman/src/test/testdata/kmp.json
linux/ibus-keyman/src/test/testdata/kmp1.json
linux/ibus-keyman/src/test/testdata/kmp2.json
linux/ibus-keyman/tests/ibusimcontext.c
linux/ibus-keyman/tests/ibusimcontext.h
linux/keyman-config/COPYING
linux/keyman-config/Makefile
linux/keyman-config/buildtools/help2md
linux/keyman-config/keyman_config/sentry_handling.py
linux/keyman-config/locale/keyman-config.pot

We only use a C API, so we can safely ignore all C++ symbols that show up in the symbols file. Those come from std template instantiations.
Also update AppStream metadata and change SIL International to SIL Global.
Additionally update the changelog file with the recent changes. Note that this uses a bogus version number that is smaller than the current release. This is because as part of the packaging process we set the version number. This only works if existing entries have a lower version number. Because the top entry has the status UNRELEASED it will be merged with the new entry.
Fixes: #12051 
Cherry-pick: #12815 

fix(linux): work around Lintian errors 🍒 🏠

---

core/include/keyman/keyman_core_api_vkeys.h
core/src/kmx/kmx_plus.h
core/src/ldml/ldml_processor.cpp
core/src/ldml/ldml_vkeys.cpp
core/src/ldml/ldml_vkeys.hpp
core/tests/unit/ldml/keyboards/k_004_tinyshift.xml
core/tests/unit/ldml/ldml.cpp
core/tests/unit/ldml/ldml_test_source.cpp
core/tests/unit/ldml/ldml_test_source.hpp

- Cherry pick of https://github.com/keymanapp/keyman/pull/12644
- Cherry pick of https://github.com/keymanapp/keyman/commit/de3397b47668dd3082e9df095a10d007a3731b98
Fixes: #12298
Please paste in the following LDML keyboard source for testing:
```xml
<?xml version="1.0"?>
<keyboard3 xmlns="https://schemas.unicode.org/cldr/45/keyboard3" locale="arc" conformsTo="45">
<info author="Marc Durdin" name="Test 'other' modifier"/>
<version number="1.0.0"/>
<keys>
<import base="cldr" path="45/keys-Zyyy-punctuation.xml"/>
<import base="cldr" path="45/keys-Zyyy-currency.xml"/>
<key id="a" output="🅐" />
<key id="b" output="🅑" />
<key id="c" output="🅒" />
<key id="d" output="🅓" />
<key id="e" output="🅔" />
</keys>
<layers formId="us">
<layer modifiers="none">
<row keys="grave 1 2 3 4 5 6 7 8 9 0 hyphen …
```

fix(core): implement ldml_processor::get_key_list()  🍒 🙀 🏠

---

core/tests/unit/kmx/fixtures/binary/meson.build
core/tests/unit/kmx/meson.build
core/tests/unit/ldml/invalid-keyboards/meson.build
core/tests/unit/ldml/keyboards/meson.build
core/tests/unit/ldml/meson.build
core/wasm.build.linux.in
core/wasm.build.mac.in
core/wasm.build.win.in
core/wasm.defs.build
developer/src/kmcmplib/tests/meson.build
developer/src/kmcmplib/wasm.build.linux.in
developer/src/kmcmplib/wasm.build.mac.in
developer/src/kmcmplib/wasm.build.win.in
developer/src/kmcmplib/wasm.defs.build

Replace deprecated function calls. Also add `strip` command to wasm build defaults.

chore(core): remove meson warnings for wasm builds

---

android/KMEA/app/src/main/java/com/keyman/engine/KeyboardPickerActivity.java

Fixes: #11714
Fixes: KEYMAN-ANDROID-39S
From the crash reports, it's possible for `KeyboardPickerActivity` to resume, and have the keyboard key `KMKeyboard.currentKeyboard()` be uninitialized (null).
This updates `KeyboardPickerActivity.onResume` to get the keyboard index from the saved preference if `KMKeyboard.currentKeyboard()` is null.

fix(android/engine): Initialize index when resuming KeyboardPicker

---

core/include/keyman/keyman_core_api_bits.h
core/meson.build
core/src/km_core_keyboard_api.cpp
core/src/meson.build
core/src/wasm.cpp
web/src/engine/core-processor/build.sh
web/src/engine/core-processor/src/core-processor.ts

Also rename type library from `km-core-interface.d.ts` to `keymancore.d.ts` to match the name of the target (`keymancore`) to make it more obvious where this comes from and where/how it gets build.
Part-of: #11293 

feat(core): expose `km_core_keyboard_load_from_blob` to WASM 🎼

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
mac/Keyman4MacIM/Keyman4MacIM/OnScreenKeyboard/OSKWindowController.h
mac/Keyman4MacIM/Keyman4MacIM/OnScreenKeyboard/OSKWindowController.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/OSKView.h
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/OSKView.m

The OSK conforms to these rules:
1. The state of the physical keyboard modifier keys takes precedence over the OSK modifiers
a. If an OSK modifier such as shift is unselected, but the shift key is held down, then the OSK will display the shift layer
b. If an OSK modifier is selected, it is reset when the corresponding physical modifier is pressed or released
1. If the OSK is open with a modifier key selected, the modifier will be applied to a character key pressed with the physical keyboard
1. Selected modifiers from the OSK can be combined with physical modifier keys to display a different layer in the OSK. For example with Shift selected in the OSK, if a user holds down the Option/Alt key,  the shift-alt layer will be displayed in the OSK
1. Closing the OSK resets the state of all its …

fix(mac): standardize interaction between OSK and physical keyboard

---

common/include/km_types.h
core/src/kmx/kmx_file.cpp
core/src/kmx/kmx_processevent.h

The data we read from the KMX file is not in all places 32-bit aligned, e.g. `dpGroupArray` will often start at a 16-bit boundary. Emscripten doesn't like this and will abort the program if `SAFE_HEAP=1` is defined.
This change works around the problem by calling `CopyKeyboard` and thus expanding the structure.
See #12844.

fix(core): work around alignment problem when using Emscripten 🎼

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/KMEA/app/src/test/java/com/keyman/engine/KMManagerTest.java
android/KMEA/app/src/test/java/com/keyman/engine/view/FunctionalTestHelper.java

I took a quick look at some KMManager keys for https://github.com/keymanapp/keyman/issues/12767#issuecomment-2573431096
and noticed KMManager had some minor cleanup TODO
* Remove deprecated keys no longer used from #4462 during Keyman 14.0
* Fix typo in `autoCorrectionPrefSuffix`
* Remove addKeyboard API call that should have been deprecated in Keyman 15
* **TEST_ADD_KEYBOARD** - Verifies Keyman app can add keyboard
2. In the Keyman app, verify the default sil_euro_latin keyboard appears
3. In Keyman settings --> "Install Keyboard or Dictionary" --> Install from keyman.com
4. Search for a keyboard and install it
5. In the Keyman app, verify the installed keyboard appears

fix(android/engine): Cleanup KMManager API keys and calls

---

web/src/engine/interfaces/src/prediction/languageProcessor.interface.ts
web/src/engine/interfaces/src/prediction/predictionContext.ts

I had to add the KeymanWeb API for auto-correct first in order to be able to disable it (#12857) :smile: 
Fixes: #12767
**TEST_DISABLED**: with SIL EuroLatin installed for English, type 5 followed by space and verify that the result is `5` instead of `5th`.

chore(web): disable auto-correct

---

web/ci.sh

Also add check for necessary environment variables before trying to upload to Sentry. This allows to run the script on a dev machine.

refactor(web): modernize `web/ci.sh` script

---

web/src/engine/keyboard/src/defaultRules.ts

Addresses part of #12483.
Default-output rules should not take effect for keystrokes that could reasonably trigger shortcuts and/or key commands, but there was no logic enforcing this natural expectation where numpad keys were involved.  
TEST_NUMPAD_ZOOM:  Confirm that numpad-based zooming works as expected.
1. With Keyman Engine for Web active, with an active keyboard, use CTRL with numpad `+`.
2. If the page does not zoom, FAIL this test.
3. If a character appears in the output as a result of step 1, FAIL this test.
4. Repeat steps 1-3 for CTRL with numpad `-`.

fix(web): numpad + and - with zoom shortcut use

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.ts
web/src/engine/predictive-text/worker-thread/src/tests/mocha/cases/edit-distance/context-tracker.js

Fixes: #12494.
Replaces #12860.
The underlying issue was occurring due to a previously unforeseen consequence of default wordbreaker use, combined with some of our custom handling.
Good case:  suppose the text just typed reads `isn'`.  A natural suggestion for English is the word `isn't`.  While end-of-token `'` is cause for wordbreaking, since the text insertion point is adjacent to the `'`, we disable wordbreaking for that `'` to facilitate the `isn't` suggestion.
Bad case:  suppose we just typed `text'` and then add _another_ character that should trigger wordbreaking - like a `"` - gets typed.  At _this_ point, due to our handling for the "good case", we transition from a tokenized context of [`text'`] to [`text`, `'`, `"`].  The "old context" no longer matches - [`text'`] vs [`text`, …

fix(web): Improve predictive-text handling of text wordbreaking transitions

---

developer/docs/help/context/keyboard-editor.md
developer/docs/help/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.md
developer/docs/help/reference/file-types/keyman-touch-layout.md

Updates documentation portion of #12870 about the `U_####[_####]` shortcut
> We may also need to modify the documentation to indicate that the square brackets are not part of the sequence, but an indication of an optional portion.

docs(developer): Clarify square brackets in `U_####[_####]` shortcut

---

android/docs/help/context/gestures.md

I originally put this together at https://github.com/keymanapp/help.keyman.com/pull/1789, but it sounds like this is the correct place to do it now.

docs(android): document longpress up-flick to quick-display shortcut

---

web/docs/engine/guide/adding-keyboards.md

- `kmw` is no longer used on this page, so we don't have to mention it
- the `european2` keyboard is deprecated and the text mentions EuroLatin, so changed the sample to `sil_euro_latin`

docs(web): fix `adding-keyboards.md`

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

🍒 pick of #12871 to stable-17.0 for #12366
@jahorton discovered that
> it would appear that we cannot rely on the `WebView`'s version of `postDelayed`, as apparently that doesn't actually trigger delayed events when the `WebView` has been detached!  We can, however, construct a `Handler` instance and link it to the UI thread's looper in order to achieve our desired effect.
**Setup** - Install the PR build of Keyman for Android on a physical device. Also pair an external keyboard (USB/bluetooth) to the device
**TEST_KEYBOARD** - Verifies external keyboard works when virtual keyboard hidden
2. From "Get Started", enable Keyman as the default system keyboard
3. Launch a separate app where you can type in (ideally a note taking app like Keep or OneNote as reported in the …

fix(android): use main looper to dispatch key events when OSK is hidden 🏠

---

windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas
windows/src/desktop/kmshell/main/UfrmMain.pas
windows/src/desktop/kmshell/main/initprog.pas

The UI checks have been moved outside the state machine. This was clean for the install now case. For the waiting restart case not so. To help a new method ready to install was added to the state machine.
Also made a second commit that makes sure there is a Keyman install before calling DoInstallKeyman on the Install packages process.

feat(windows): UI removed from state machine 💽

---

resources/devbox/macos/keyman.macos.env.sh

I ran into a couple of issues when getting my Mac development laptop set up to build our Android app, some of them related to this script.  One distinctly noticeable item:  we use OpenJDK 11, not Java 8... yet the variables in the script still reference the latter!
Reference (current `master`):
https://github.com/keymanapp/keyman/blob/f268d04a27f4d9ac571f6d7e2ecd4ad6da063080/docs/build/macos.md?plain=1#L156-L161

chore: update macOS environment-variable shell script

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Fixes: #12366
Supersedes: #12381
Alas, it would appear that we cannot rely on the `WebView`'s version of `postDelayed`, as apparently that doesn't actually trigger delayed events when the `WebView` has been detached!  We can, however, construct a `Handler` instance and link it to the UI thread's looper in order to achieve our desired effect.
**Setup** - Install the PR build of Keyman for Android on a physical device. Also pair an external keyboard (USB/bluetooth) to the device
**TEST_KEYBOARD** - Verifies external keyboard works when virtual keyboard hidden
2. From "Get Started", enable Keyman as the default system keyboard
3. Launch a separate app where you can type in (ideally a note taking app like Keep or OneNote as reported in the issue). If those aren't available, …

fix(android): use main looper to dispatch key events when OSK is hidden

---

web/build.sh
web/src/engine/predictive-text/build.sh
web/src/engine/predictive-text/worker-main/build.sh

The main reason I started this PR was the fact that `web/build.sh build:engine/predictive-text` had absolutely no effect.  Calling it when an older version of predictive-text existed on my filesystem would not update it; I had to drill-down into the child projects to get them rebuilt.
I also discovered that web's headless test suite was left disconnected for some reason.  This seems to have been done at some point within the 18.0 filesystem reorganization, but was never undone.  I believe things should be stable enough to reconnect them now.
For the third commit, the reorg has placed things in such a manner that it... kind of makes sense to have a `web/build.sh test` actually trigger them.  We do still have the two separate build configurations though, so this probably shouldn't happen …

chore(web): integrates predictive-text builds to top level script, reconnects headless tests

---

developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts

The font collection code was somewhat wrong in kmc-keyboard-info. It collected all fonts referenced in the package, even for multi-keyboard packages, which meant that the .keyboard_info file listed all fonts for all languages. Furthermore, if a font was referenced in multiple language entries in the .kps, then it would be repeated for each language in the .keyboard_info. This patch addresses both of these bugs.
The good news is that this makes some of the .keyboard_info files smaller. In particular, fv_all.keyboard_info goes from 4675 lines down to 695 lines!
Fixes: #12852

fix(developer): filter incorrect fonts out of .keyboard_info

---

web/src/engine/predictive-text/worker-thread/src/main/predict-helpers.ts
web/src/engine/predictive-text/worker-thread/src/tests/mocha/cases/suggestion-similarity.js
web/src/engine/predictive-text/worker-thread/src/tests/mocha/cases/worker-model-compositor.js

This has been spun off from #12884.
One obstacle toward handling delayed reversions is that our current 'keep' suggestion generation builds transforms that perform as minimal an edit as possible... unlike literally every other suggestion transform we build, which deletes the prefix and re-adds it within the 'insert' section.  As it turns out, the latter case is much more favorable for implementing delayed reversions.  This change will make 'keep' suggestion transforms consistent with those from predictive and corrective suggestions.

change(web): make 'keep' transform pattern match standard suggestion pattern by including the prefix string

---

developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts

The font collection code was somewhat wrong in kmc-keyboard-info. It collected all fonts referenced in the package, even for multi-keyboard packages, which meant that the .keyboard_info file listed all fonts for all languages. Furthermore, if a font was referenced in multiple language entries in the .kps, then it would be repeated for each language in the .keyboard_info. This patch addresses both of these bugs.
The good news is that this makes some of the .keyboard_info files smaller. In particular, fv_all.keyboard_info goes from 4675 lines down to 695 lines!
Fixes: #12852
Cherry-pick-of: #12909

fix(developer): filter incorrect fonts out of .keyboard_info 🍒 🏠

---

windows/src/desktop/kmshell/main/BackgroundUpdateStateDiagram.md

The postinstall state no longer exists due to the way interaction with the microsoft installer works. This PR just updateds the diagram to match.
The side purpose of this PR is to provide a newer build version to test the online upgrade process. 

chore(windows): remove `postinstall` state from mermaid diagram

---

linux/debian/copyright

chore(linux): update copyright year

---

web/src/engine/predictive-text/wordbreakers/src/main/default/index.ts
web/src/engine/predictive-text/wordbreakers/src/main/index.ts
web/src/engine/predictive-text/worker-thread/src/main/predict-helpers.ts
web/src/engine/predictive-text/worker-thread/src/tests/mocha/cases/auto-correct.js

Addresses one item from the auto-correct initial feedback issue (#12648):
> Numbers get autocorrected, e.g. 23 -> 2nd.
This is accomplished by adding a new 'filter' function to the auto-correct logic:  `correctionValidForAutoSelect`.  A relatively simple guideline, at least for numbers, seems simple enough to define.  We can use the standard programming rule for identifiers - starting with a letter.  That is, if a token starts with a non-letter, we probably shouldn't do auto-correction with it.
We may need to refine and polish it once auto-correct is out and we are made aware of tricky cases with different character classes, but this should be a good starting point for any such logic.
I've also added a unit-test to validate that the motivating case no longer triggers auto-correction. …

change(web): add auto-correct filter that requires letter in initial position 🚂

---

web/src/app/browser/src/beepHandler.ts
web/src/app/browser/src/contextManager.ts
web/src/app/browser/src/keymanEngine.ts
web/src/app/webview/src/contextManager.ts
web/src/app/webview/src/passthroughKeyboard.ts
web/src/engine/keyboard-storage/src/stubAndKeyboardCache.ts
web/src/engine/keyboard/build.sh
web/src/engine/keyboard/src/index.ts
web/src/engine/keyboard/src/keyboards/keyboardLoaderBase.ts
web/src/engine/keyboard/src/keyboards/keyboardMinimalInterface.ts
web/src/engine/keyboard/src/keyboards/kmxKeyboard.ts
web/src/engine/main/src/contextManagerBase.ts
web/src/engine/main/src/hardKeyboard.ts
web/src/engine/main/src/headless/inputProcessor.ts
web/src/engine/main/src/keymanEngine.ts
web/src/engine/osk/src/index.ts
web/src/engine/osk/src/views/oskView.ts
web/src/test/auto/dom/cases/keyboard/domKeyboardLoader.tests.ts
web/src/test/auto/dom/kbdLoader.ts
web/src/test/auto/headless/engine/js-processor/kbdInterface.tests.ts
web/src/test/auto/headless/engine/keyboard/keyboard.tests.ts
web/src/test/auto/headless/engine/keyboard/keyboardLoaderBase.tests.ts
web/src/test/auto/integrated/web-test-runner.config.mjs
web/src/tools/testing/bulk_rendering/renderer_core.ts

The `Keyboard` class can be either a JS or KMX keyboard. Also make use of the `Keyboard` class where it makes sense and add TODOs in the places that still need to be implemented for KMX keyboard support.
Part-of: #11293 

feat(web): add `Keyboard` and `KMXKeyboard` classes 🎼

---

developer/src/kmc/src/commands/generate.ts

fix(developer): use correct terms in kmc-generate lexical model help

---

developer/src/kmc/src/commands/generate.ts

fix(developer): use 1.0.0 as default for ldml keyboards in kmc-generate

---

web/src/engine/osk/src/input/gestures/browser/multitap.ts

Fixes: #12963
TEST_NAIJATYPE_CAPS_ON_ANDROID:  Using Keyman for Android..
1.  Double-tap on the default-layer shift key and verify that:
- No error or warning messages appear
- The CAPS layer activates and holds, even after typing a couple of letters
2. Triple-tap the default layer `i` key, verifying that `ị` results and that no errors or warnings occur.
TEST_EUROLATIN:  Using Keyman for Android, verify that the keyboard's caps-lock behavior works properly.

fix(web): prevent warning that occurs when multitapping longpressable modifier keys

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Fixes #12801 and reverts #10806.
#12801 impacts a lot more users (using the keyboard picker menu from the system keyboard) than #10806 (using the Keyman system keyboard within the embedded keyman.com keyboard search)
This restores the KeyboardPickerActivity intent flag `FLAG_ACTIVITY_CLEAR_TASK` to how it's been longstanding since [Keyman for Android 2.8](https://github.com/keymanapp/keyman/blob/2b3fa63cea49f47201226d74d35ad57f25d2385e/android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java#L1661)
I'll either re-open #10806 or re-open as a new issue to chase down this sprint.
* **TEST_KEYBOARD_PICKER_DOESNT_REOPEN_KEYMAN** - Verifies exiting the system keyboard Keyboard Picker menu doesn't transition to Keyman app
1. Launch …

fix(android/engine): Revert how keyboard picker menu launches

---

developer/docs/help/reference/kmc/cli/reference.md
developer/src/kmc-generate/src/abstract-generator.ts
developer/src/kmc-generate/src/keyman-keyboard-generator.ts
developer/src/kmc-generate/test/shared-options.ts
developer/src/kmc/src/commands/generate.ts

As icon generation turns out to be challenging due to limitations or native dependencies in node.js libraries for image generation, icon options are now stubbed out to avoid confusion.
See #12641 for TODO to implement icon support.

chore(developer): stub out icon support in kmc-generate

---

developer/src/kmc-copy/src/KeymanProjectCopier.ts
developer/src/kmc-copy/test/copier.tests.ts
developer/src/kmc/src/commands/copy.ts

An in-place rename is dangerous and destructive, so we won't support it.
Fixes: #12972

chore(developer): remove '--rename' option from kmc-copy

---

developer/src/common/include/kmn_compiler_errors.h
developer/src/common/web/test-helpers/TestCompilerCallbacks.ts
developer/src/common/web/test-helpers/verifyCompilerMessagesObject.ts
developer/src/common/web/utils/src/compiler-interfaces.ts
developer/src/kmc-copy/src/cloud.ts
developer/src/kmc-copy/src/copier-messages.ts
developer/src/kmc-copy/test/copier.tests.ts
developer/src/kmc/src/commands/messageCommand.ts
developer/src/kmc/src/util/NodeCompilerCallbacks.ts
developer/src/tike/compile/Keyman.Developer.System.KmcWrapper.pas

Adds 'verbose' and 'debug' log levels and corresponding error severity levels. This means the internal error severity values have changed to match - 'info' is now 2 instead of 0.
Fixes: #12975

feat(developer): add 'verbose' and 'debug' log levels to kmc

---

resources/docker-images/android/Dockerfile
resources/docker-images/core/Dockerfile
resources/docker-images/linux/Dockerfile
resources/docker-images/web/Dockerfile

We need to run `apt-get update` first before trying to install packages. We did update the package index when we built the base image, but that might have been some time ago so that the index is now outdated.

chore(linux): docker build: update package index before installing packages in Dockerfiles

---

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/CheckPermissions.java
android/docs/help/troubleshooting/grant-storage-permission.md

Fixes #12996  and undoes part of #11299 for Android 13.0+ devices
In order to comply with Google Play Store's "Photo and Video Permission policy"
https://support.google.com/googleplay/android-developer/answer/14115180?hl=en
we have to remove requesting `READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` permissions from the app manifest. This limits Android 13.0+ devices to accessing downloaded .kmp files from the system picker within the Keyman for Android app.
The removal from the app manifest means the user no longer has the option to access device settings --> Privacy --> Photos and Videos permissions to grant Keyman storage permission:
* Also updates the in-app help documentation
**Setup** - Install the PR build of "Keyman for Android on an Android 13.0+ device/emulator. This corresponds to …

fix(android): Remove access to MEDIA storage permissions

---

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/CheckPermissions.java
android/help/troubleshooting/grant-storage-permission.md

:cherries: pick of #12999 for stable-17.0
In order to comply with Google Play Store's "Photo and Video Permission policy"
https://support.google.com/googleplay/android-developer/answer/14115180?hl=en
we have to remove requesting `READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` permissions from the app manifest. This limits Android 13.0+ devices to accessing downloaded .kmp files from the system picker within the Keyman for Android app.
The removal from the app manifest means the user no longer has the option to access device settings --> Privacy --> Photos and Videos permissions to grant Keyman storage permission:
* Also updates the in-app help documentation
**Setup** - Install the PR build of "Keyman for Android on an Android 13.0+ device/emulator. This corresponds to Android API 33+. 
* From …

fix(android): Remove access to MEDIA storage permissions🍒 🏠

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Fixes #11652.
From our current `master`:
https://github.com/keymanapp/keyman/blob/486807fd7d3fe09390154837648093331f85f921/android/docs/help/about/system-requirements.md?plain=1#L11-L15
`DOMRect` has native support starting in Chrome 61.

fix(android): restores DOMRect polyfill for old Chrome support

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Fixes: #11652
Cherry-pick-of: #13012

fix(android): restores DOMRect polyfill for old Chrome support 🏠

---

developer/src/kmc/src/commands/buildClasses/BuildKeyboardInfo.ts

Because the build process for multi-keyboard packages does not deploy .js keyboards to s.keyman.com, it does not make sense to list them, even if the package may contain .js keyboards for mobile platforms.
Fixes: #12853

fix(developer): don't list .js keyboards for multi-keyboard packages in kmc-keyboard-info

---

web/src/engine/js-processor/src/kbdInterface.ts
web/src/test/auto/headless/engine/js-processor/engine/context.tests.js
web/src/test/auto/headless/engine/js-processor/engine/notany_context.tests.js

Fixes #12987.
For some reason, when the "full/extended context" system introduced in KMW 10 was written, contexts prefixed with the `nul` sentinel would be... "simplified", for lack of a better word.  Unfortunately, this simplification also ruined nearly all ability for any rule to actually _match_ such contexts beyond a simple, single-width `nul`.  It's not clear at this point _why_ it was in place or what it sought to remedy.
Four unit tests will fail at the point of the first commit:  three of the new ones and the one that validates their base context, which highlights this.
<details><summary>A copy of my local results</summary>
```
107 passing (54ms)
1 pending
4 failing
1) Engine - Context Matching
properly generates extended context data needed by context-matching checks below: …
```

fix(web): do not simplify nul-prefixed contexts when rule-matching

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/packages/PackageProcessor.java

We have a few Sentry issues for Android regarding attempts to install what _appear_ to be corrupted or malformed KMPs:
https://keyman.sentry.io/share/issue/198fe1ad9e4646a497ff7a0297b741fb/
https://keyman.sentry.io/share/issue/724a9ca295e14e0899827c0786c2d21b/
I'm sure it's a disappointment to users when this occurs, but we don't have any substantial data available to us about _which_ packages / KMPs / files this is occurring for.  So, the obvious next step:  add breadcrumbing.  This way, we can get a sense of what KMP sources are affected and which packages this occurs for.  That, in turn, should give us a better sense of why these two errors occur.

feat(android): add breadcrumbing during package install about package file, source

---

linux/ibus-keyman/tests/scripts/test-helper.inc.sh
resources/docker-images/linux/Dockerfile
resources/docker-images/run.sh

This change fixes two issues in the Linux docker image that showed up when running tests:
- some directories had wrong permissions
- we have to build keyman-system-service in a docker-specific directory as well so that the location of the service executable can be found when running the tests in docker

fix(linux): correct permissions and paths in Linux docker image

---

web/src/engine/dom-utils/src/stylesheets.ts

Fixes: #13018
Fixes: #13022
Our fontface-defining stylesheet format has been using single-quotes to enclose the filename.  Sadly, `encodeURI` doesn't mangle single-quotes - it mangles double-quotes instead.  So, we should adjust the quote type used there.
Fixed stylesheet:
```
@font-face {
font-family:soninke_n_ti;
font-style:normal;
font-weight:normal;
src:url("./N'tiFont.otf") format('truetype');
}
```
When using the KMP loader to diagnose the problem, I found that data URLs were handled... to a point, and then that process was unnecessarily aborted.  That was simple enough to fix with the first commit of this PR.
This is how the default layer of the keyboard looks in desktop-mode Keyman Engine for Web:
- TEST_ANDROID:  Using the Android test build from this PR and the …

fix(web): fix handling of data: url fonts, fonts with single quotes in filename

---

web/src/engine/dom-utils/src/stylesheets.ts

Cherry-pick-of: #13032, but without the data URL components, as that tidbit was added during 18.0-alpha.
This is how the default layer of the keyboard looks in desktop-mode Keyman Engine for Web:
- TEST_ANDROID:  Using the Android test build from this PR and the `soninke_n_ti.kmp` package from https://jahorton.github.io/soninke_n_ti.kmp, verify that the keyboard loads properly and has proper characters for its font.
- TEST_IOS:  Using the Android test build from this PR and the `soninke_n_ti.kmp` package from https://jahorton.github.io/soninke_n_ti.kmp, verify that the keyboard loads properly and has proper characters for its font.

fix(web): fix handling of fonts with single quotes in filename 🍒 🏠

---

android/KMEA/app/src/main/assets/android-host.js
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java

Cherry-pick-of: #13001
TEST_ANDROID_GENERAL_USE:  Do some simple tests with the Keyman for Android app, verifying that the keyboard acts normally.  Just a few keystrokes should be fine.

fix(android): disable early keyboard-loading when not feasible 🏠

---

android/KMEA/app/src/main/assets/android-host.js
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java

Fixes #13000.
I find it quite interesting that the JS-side error "due to Java error" doesn't have any corresponding Java error reports.  Either way, that particular line should be safe to bypass even when such an error occurs.
Said line was originally implemented as an optimization technique in #10022.  That PR helped reduce the 'flashing' behavior seen during keyboard load in which a basic placeholder keyboard was loading before the actually-desired keyboard was able to load.  Allowing that behavior is better than letting the keyboard page crash, though.
TEST_ANDROID_GENERAL_USE:  Do some simple tests with the Keyman for Android app, verifying that the keyboard acts normally.  Just a few keystrokes should be fine.

fix(android): disable early keyboard-loading when not feasible

---

android/KMEA/app/src/main/java/com/keyman/engine/logic/ResourcesUpdateTool.java

Fixes: #13002 
Refer to https://github.com/keymanapp/keyman/issues/13002#issuecomment-2609041009.
It is my belief that the resource update functionality is actually working without issue, though it _is_ generating Sentry event logging that is inflating our error numbers.  It doesn't hurt to polish things up a bit and ensure that any needed notifications don't trigger issues, though.
To be clear, I personally tested the new setup for toasts within the tool (depending on `appContext`) and confirmed that it should work without issue.  (I added a matching setup in the `onBackPressed()` method of `LanguagesSettingsActivity` and had it trigger 4 sec after dismissal, giving plenty of time to return to the app's top level.)
<details><summary>The test setup I used to validate this …

fix(android): improve resource-update tool handling of host Activity's closure

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodLifecycle.m
mac/Keyman4MacIM/Keyman4MacIM/OnScreenKeyboard/OSKWindowController.xib

Show and hide the OSK consistently, according to its saved state, for all keyboards (not just keyboards that include a KVK file).
Fixes #12928 
* GROUP_IPA_SIL: Test with IPA (SIL) as the active keyboard
* GROUP_EUROLATIN_SIL: Test with EuroLatin (SIL) as the active keyboard
* GROUP_KHMER_ANGKOR: Test with Khmer Angkor as the active keyboard
1. Open the OSK while using Keyman
1. Change from Keyman to another input method such as the U.S. Keyboard provided by Apple
1. Confirm that the OSK automatically hides
1. Switch back to the Keyman input method
1. Confirm that the OSK reappears
1. Open the OSK while using Keyman
1. Change between text input applications with OSK open
1. Click on menus in the various applications
1. Confirm that the OSK does not flicker or disappear while switching …

fix(mac): show and hide OSK consistently for all keyboards

---

linux/scripts/dist.sh

PR #12642 tried to fix creating the source tarball so that it didn't ignore files we need. However, that now included way to many files. This change fixes this and results in a smaller tarball again.
Fixes: #13010

fix(linux): remove unnecessary files from source tarball

---

android/KMAPro/kMAPro/src/main/res/values-pt-rPT/strings.xml
android/KMEA/app/src/main/java/com/keyman/engine/DisplayLanguages.java
android/KMEA/app/src/main/res/values-pt-rPT/strings.xml
ios/engine/KMEI/KeymanEngine/pt-PT.lproj/Localizable.strings
mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/pt-PT.lproj/preferences.strings
windows/src/desktop/kmshell/locale/pt-PT/strings.xml
windows/src/desktop/setup/locale/pt-PT/strings.xml

Multiple Crowdin contributors have requested a fix to the display name for Portuguese
from `Português do Portugal`
to `Português de Portugal`. 
Also updates more strings.

chore(common): Update crowdin strings for Portuguese

---

linux/ibus-keyman/meson.build
linux/ibus-keyman/src/KeymanSystemServiceClient.cpp
linux/ibus-keyman/tests/KmDbusTestServer.cpp
linux/ibus-keyman/tests/StopTestServer.cpp
linux/ibus-keyman/tests/meson.build
linux/keyman-system-service/meson.build
linux/keyman-system-service/resources/com.keyman.SystemService1.service.basu
linux/keyman-system-service/resources/com.keyman.SystemService1.service.systemd
linux/keyman-system-service/resources/meson.build
linux/keyman-system-service/src/KeymanSystemService.cpp
linux/keyman-system-service/src/KeymanSystemService.h
linux/keyman-system-service/src/meson.build
linux/keyman-system-service/tests/meson.build

Gentoo doesn't use systemd. `libelogind` or `basu` implement some aspects of systemd, so we use that on Gentoo (or rather when `libsystemd` is not available but `libelogind` or `basu` is).
Patch from https://forums.gentoo.org/viewtopic.php?p=8850566.
See also https://community.software.sil.org/t/keyman-for-gentoo-linux/9615.

chore(linux): improve compatibility with Gentoo Linux 🏠

---

linux/ibus-keyman/meson.build
linux/ibus-keyman/src/KeymanSystemServiceClient.cpp
linux/ibus-keyman/tests/KmDbusTestServer.cpp
linux/ibus-keyman/tests/StopTestServer.cpp
linux/ibus-keyman/tests/meson.build
linux/keyman-system-service/meson.build
linux/keyman-system-service/resources/com.keyman.SystemService1.service.basu
linux/keyman-system-service/resources/com.keyman.SystemService1.service.systemd
linux/keyman-system-service/resources/meson.build.in
linux/keyman-system-service/src/KeymanSystemService.cpp
linux/keyman-system-service/src/KeymanSystemService.h
linux/keyman-system-service/src/meson.build
linux/keyman-system-service/tests/meson.build

Gentoo doesn't use systemd. `libelogind` or `basu` implement some aspects of systemd, so we use that on Gentoo (or rather when `libsystemd` is not available but `libelogind` or `basu` is).
Patch from https://forums.gentoo.org/viewtopic.php?p=8850566. See also https://community.software.sil.org/t/keyman-for-gentoo-linux/9615.
Cherry-pick-of: #12889

chore(linux): improve compatibility with Gentoo Linux 🍒

---

windows/src/desktop/kmshell/kmshell.dproj
windows/src/desktop/kmshell/main/Keyman.Configuration.UI.UfrmStartInstall.dfm
windows/src/desktop/kmshell/main/Keyman.Configuration.UI.UfrmStartInstall.pas
windows/src/desktop/kmshell/main/Keyman.Configuration.UI.UfrmStartInstallNow.dfm
windows/src/desktop/kmshell/main/Keyman.Configuration.UI.UfrmStartInstallNow.pas
windows/src/desktop/kmshell/xml/keyman_update.xsl
windows/src/desktop/kmshell/xml/strings.xml

Fixes: #12887 
Just testing the text that appears on the forms/windows and not just a message id or some other text error.
Install the Keyman from the PR
Open the configuration and go to the updates tab observe the `No Updates are available.`
Then press the `check for updates now`.
Observe the Configuration line if updates are found now shows 
`Updates are available which will be applied when Windows is next restarted.`
Press the `Apply update now button`
Observe both the text message and both buttons have text. Then press `close` button.
Message `Updating now will require a computer restart`
Buttons `Update` and `Close`

feat(windows): add localized button captions and form labels

---

web/src/engine/main/src/headless/languageProcessor.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/distance-modeler.ts
web/src/engine/predictive-text/worker-thread/src/main/predict-helpers.ts
web/src/engine/predictive-text/worker-thread/src/tests/mocha/cases/worker-model-compositor.js

Fixes: #12214.
There were a couple of big key issues in the way of a properly-working "enable/disable corrections" toggle:
1. The worker has literally no access to the state of that value at present.
2. The correction-search is always run for each predict() call.
To address the first point, this PR establishes a state for the worker that allows it to reasonably _infer_ the value of the toggle.  "If all inputs for a word lack fat-finger distribution data, then we don't correct."  From there, the key is then to ensure that the worker doesn't _get_ fat-finger distribution data when the correction state is set to disabled.  We can enforce this within the Web engine's `LanguageProcessor` class.
Note that this also means that when corrections _are_ enabled, we will not offer corrections after a …

fix(web): disabled correction state should prevent predictive corrections

---

web/src/engine/osk/src/banner/suggestionBanner.ts

I've written this PR in such a way that it should be fully compatible with #12893 when merged in.
There was no pre-existing issue for it, but I just realized that we still had a tiny bit of active autocorrect behavior enabled on `master` - the suggestion we _would_ autocorrect to was being highlighted.  It wouldn't trigger, but it could lead to "fun" cases where that suggestion _and_ a touched suggestion would both be highlighted at the same time.
Part of me... actually kind of liked having the autocorrect "hint" active, but this was definitely not intended.
TEST_ANDROID_AUTOHIGHLIGHT:  Using Keyman for Android and `sil_euro_latin` set to English, type `troub` and verify that `trouble` is not automatically highlighted.

fix(web): disabled autoaccept should not autohighlight suggestions

---

web/src/engine/keyboard-storage/src/cloud/queryEngine.ts
web/src/engine/keyboard-storage/src/keyboardRequisitioner.ts
web/src/engine/keyboard-storage/src/keyboardStub.ts
web/src/test/manual/web/sentry-integration/errorhdr.js
web/src/test/manual/web/sentry-integration/index.html

Fixes: #13043.
This PR makes sure that when errors occur during Cloud API use, we always get:
1. actual error objects
2. a bit of data about the keyboard and/or request
Some example cases I triggered during development:
- https://keyman.sentry.io/share/issue/b312db1563fc4d978d7b6fe45a4ec0a2/
- Request info is "breadcrumbed" on this one. 
- https://keyman.sentry.io/share/issue/561abbc6c6094335b06f5154e59fbe47/
- https://keyman.sentry.io/share/issue/9019333c56574ab9aaddbebd3aafcda6/
- https://keyman.sentry.io/share/issue/546fae38088d47d4a587b4af91d0097a/

fix(web): keyboard query error states should always provide informative Error objects, reports

---

windows/src/engine/tsysinfo/si_overview.pas
windows/src/engine/tsysinfo/si_overview.xslt

feat(windows): report on processor type in tsysinfo

---

resources/build/increment-version.sh

Also remove unnecessary `-b master` because PR will automatically target master anyway
Fixes: #13078

fix(common): push branch when creating PR in version history writer

---

common/web/langtags/README.md
common/web/langtags/src/main.ts
developer/src/kmc-generate/build.sh
developer/src/kmc-generate/package.json
developer/src/kmc-generate/src/basic-generator.ts
developer/src/kmc-generate/test/fixtures/keyman-keyboard/sample/source/sample.kps
developer/src/kmc-generate/test/fixtures/ldml-keyboard/sample/source/sample.kps
developer/src/kmc-generate/test/fixtures/lexical-model/sample.en.sample/source/sample.en.sample.model.kps
developer/src/kmc-generate/tsconfig.json
developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts
developer/src/kmc-keyboard-info/test/keyboard-info-compiler.tests.ts
package-lock.json

Also fills out the remaining functionality in @keymanapp/langtags.
Fixes: #13045

chore(developer): use langtags.json for kmc-generate language names

---

windows/src/desktop/kmshell/main/initprog.pas
windows/src/engine/kmcomapi/util/utilkeymanoption.pas

Fixes: #12994
This updates the registry entry run on start-up to use `-boot`, add the `-boot` switch
to initprog. The fmBoot option code allows update state machine code so that
on boot a prompt can let the user the new update is about to install.
1. Install Keyman attached the PR
2. Install the Gff_Amharic 3.1.1 version keyboard.
3. Start Keyman
5. Open the Keyman Configuration dialog.
6. In the `Options tab` 
7. Navigate to the "Keyboard Layouts tab".
8. Verified that the installed keyboard shows an older version.
9. Navigate to the "Update" tab.
10. Open the "C:\Users\"yourusername"\AppData\Local\Keyman\UpdateCache" folder.
11. Open the regedit window (Computer\HKEY_CURRENT_USER\SOFTWARE\Keyman\Keyman Engine). 
<kbd>Win</kbd><kbd>R</kbd> type regedit Go the current user key `update …

feat(windows): add boot switch

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js
web/src/app/webview/src/configuration.ts

In our current Sentry reports coming from within the iOS app's keyboard host-page, we get the following under `keymanState`:
```
{
configReport: {
embeddingApp: AppleTablet,
hostDevice: {
browser: native,
formFactor: tablet,
OS: ios,
touchable: true
},
initialized: true,
keymanEngine: app/webview
}
```
It is certainly helpful to know that the error occurred with the `app/webview` build on an Apple tablet - that tells us it's from some variant of our iOS engine.  But... which one?  This PR fetches the active bundle identifier and ferries that into the Web engine once it loads, which will allow us to have the actual active identifier.
- Is it the Keyman app?  `Tavultesoft.Keyman`.
- Is it the app's system keyboard?  `Tavultesoft.Keyman.SWKeyboard`
- Is it coming from a different app that's …

change(ios): set host-app bundle identifier in embedded Web debug-report

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift

Fixes: KEYMAN-IOS-1J
Fixes: #13036

fix(ios): prevent message-handler collision

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js
web/src/app/webview/src/configuration.ts

Cherry-pick-of: #13105
Not that it _fixes_ anything, but the increased specificity should help further investigate some bug reports we've been receiving.

change(ios): set host-app bundle identifier in embedded Web debug-report 🍒 🏠

---

linux/ibus-keyman/tests/scripts/run-tests.sh
linux/ibus-keyman/tests/scripts/test-helper.inc.sh

This change copies the log files that get created during a test run to the `build/docker-linux/tmp` directory. Also fixes a bug when not running in docker. Also create log file for test server.

chore(linux): preserve log files when running tests under Docker

---

common/web/langtags/src/main.ts

Matches prior behaviour when langtags was part of kmc-keyboard-info.
Fixes: #13116

fix(common): handle undefined input in `@keymanapp/langtags` lookups

---

developer/docs/help/reference/kmc/cli/get-started.md
developer/src/inst/node/dist/Keyman_README.md
developer/src/kmc/README.md

Relates-to: keyman-keyboards/khmer_angkor#1

chore: update docs to reference node 20.0

---

developer/src/common/web/utils/src/utils/KeymanSentry.ts
developer/src/kmc/src/util/TestKeymanSentry.ts
developer/src/kmc/src/util/kmcSentryOptions.ts

In order to reproduce kmc errors, it's very helpful to know how it was instantiated. This change includes the command line call for kmc. This includes things such as a keyboard filename and may include file paths, but does not include private personal information or secrets.
Sample capture:
```
Command Line
argv: C:\Users\marc\AppData\Roaming\nvm\v20.16.0\node.exe D:\Projects\keyman\app\developer\src\kmc --sentry-client-test-exception
```

feat(developer): include command line in kmc sentry reports

---

common/web/types/tests/kmx/kmx-plus/kmx-plus.tests.ts

In PR [#12868](https://github.com/keymanapp/keyman/pull/12868) a new `isEqual()` mathod was added to `StrsItem` to distinguish identity (`===`) and equality (`toEqual()`) checks. This was needed to get correct behaviour from `ElemElement.isEqual()` and `ElementString.isEqual()` which both (now) depend on `StrsItem.isEqual()`.
This PR checks uses of `StrsItem` to identify where `StrsItem.toEqual()` should be used instead of an identity check.
Fixes: #12945 

fix(common/web): replace invalid StrsItem identity checks with isEqual()

---

developer/docs/help/reference/kmc/cli/reference.md
developer/src/common/web/utils/src/compiler-interfaces.ts
developer/src/kmc-copy/src/KeymanProjectCopier.ts
developer/src/kmc-generate/src/abstract-generator.ts
developer/src/kmc-generate/src/basic-generator.ts
developer/src/kmc/src/commands/analyze.ts
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/buildTestData/index.ts
developer/src/kmc/src/commands/buildWindowsPackageInstaller/index.ts
developer/src/kmc/src/commands/copy.ts
developer/src/kmc/src/commands/generate.ts
developer/src/kmc/src/util/baseOptions.ts
developer/src/kmc/src/util/extendedCompilerOptions.ts
developer/src/kmc/test/extendedCompilerOptions.tests.ts
developer/src/kmc/test/generateKmnKeyboard.tests.ts
developer/src/kmc/test/generateLdmlKeyboard.tests.ts
developer/src/kmc/test/generateLexicalModel.tests.ts

Makes the `--log-format`, `--log-level`, and `--color`/`--no-color` options available for all commands and DRYs out some of the options processing for consistency. This has positive impact in particular on the Generator classes which removes the need for several unit tests as the interface can now be checked at compile time.
Fixes: #13072
Fixes: #13110
Unblocks: #13073
We need to test that the logging options work consistently for all commands in kmc. Run tests for each of the commands below:
* GROUP_ANALYZE_OSK_CHAR_USE: `kmc analyze osk-char-use`
* GROUP_ANALYZE_REWRITE_FROM_OSK_CHAR_USE: `kmc analyze osk-rewrite-from-char-use`
* GROUP_BUILD_FILE: `kmc build file`
* GROUP_BUILD_LDML_TEST_DATA: `kmc build ldml-test-data`
* GROUP_BUILD_WINDOWS_PACKAGE_INSTALLER: `kmc build …

fix(developer): make kmc log options consistent across all commands

---

ios/Cartfile
ios/Cartfile.resolved
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js
ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
mac/Keyman4MacIM/Podfile
mac/Keyman4MacIM/Podfile.lock
oem/firstvoices/ios/Cartfile
oem/firstvoices/ios/Cartfile.resolved

Using Xcode 16.2 running on macOS 15.2 (Sequoia) ensure that Keyman for mac and ios builds and runs correctly.
Fixes #12696
Cherry-pick of #13077, #12554, #12570 

chore(mac, ios): build and run with xcode 16 🍒 🏠 

---

mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/Base.lproj/preferences.xib

After removal of the 'Always Show OSK' and 'Use Verbose console Logging' options from the configuration window, the options tab is empty and can be removed. Only 'Keyboards' and 'Support' tabs remain.
(The Options tab may be added back in the future to hold things like hot key configuration.)
Related:
#12431 
#12355 

chore(mac): remove empty options tab from configuration

---

windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas

Only go to the installing state if `apply now` has been set. Otherwise go to WaitingRestart. This can be Revistied in Stage 2 #8993
Fixes: #13155
To Test this PR we need it so there are no newer updates available. If there are let me know and 
I will merge in the lastest master again.
1. Download the Keyman attached to this PR 
2. Start Keyman.
3. Open the Keyman Configuration dialog.
5. Install the euro latin keyboard attached to this PR 3.0.0 [sil_euro_latin.zip](https://github.com/user-attachments/files/18587198/sil_euro_latin.zip)
6. In Options tab under General, check "Automatically check for updates and download"
7. Open Regedit <kbd>Win</kbd><kbd>R</kbd> type regedit 
8. Go to the current user key `update state` found at (Computer\HKEY_CURRENT_USER\SOFTWARE\Keyman\Keyman Engine). …

feat(windows):  background updates go from downloading to waiting for a restart except if the `apply now` flag is set  

---

developer/src/kmc-package/src/compiler/package-compiler-messages.ts
developer/src/kmc-package/src/compiler/package-version-validator.ts
developer/src/kmc-package/test/fixtures/invalid/warn_package_version_is_unrecognized_format.kps
developer/src/kmc-package/test/messages.tests.ts
developer/src/kmc-package/test/versioning.tests.ts

Ensures that version number field is not blank, and is a recognized format matching the pattern 'number[.number[.number]]'. Each number component should be an integer, without leading zeroes.
The format chosen is more restrictive than semver, because much of our existing infrastructure assumes this format anyway. This does lead to a mismatch in version number format for LDML keyboards, which do support semver according to the spec, so this may need to be revisited in the future to allow for full semver formats.
I have tested this against both the lexical models and keyboards repositories.
Fixes: #13067

feat(developer): verify package version number format in kmc-package

---

developer/src/tike/child/Keyman.Developer.UI.Debug.UfrmLdmlKeyboardDebug.pas
developer/src/tike/child/UfrmDebug.pas

Keyman Core expects US English virtual key codes, so make sure that the debuggers translate the key codes they receive from Windows to the hard- coded values for US English, as defined in ScanCodeMap.
Fixes: #13052
TEST_US_ENGLISH_DEBUGGER: Using any Keyman keyboard, open the debugger, make sure US English keyboard is selected in Windows, and try each key on the keyboard and verify that it gives the expected output.
TEST_FRENCH_AZERTY_DEBUGGER: Install the French (AZERTY) keyboard in Windows (under 'French (France)'). Using any Keyman keyboard, open the debugger, make sure French AZERTY keyboard is selected in Windows, and try each key on the keyboard and verify that it gives the expected output based on US English, rather than swapping keys such as A and Q. (You can verify that French …

fix(developer): support non-US base keyboard layouts in debuggers

---

common/windows/delphi/general/Upload_Settings.pas
common/windows/delphi/general/VersionInfo.pas
developer/src/common/web/test-helpers/verifyCompilerMessagesObject.ts
developer/src/common/web/utils/src/compiler-interfaces.ts
developer/src/common/web/utils/src/index.ts
developer/src/kmc-copy/src/copier-messages.ts
developer/src/kmc-generate/src/generator-messages.ts
developer/src/kmc-kmn/src/kmw-compiler/kmw-compiler-messages.ts
developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts
developer/src/kmc/src/commands/messageCommand.ts
developer/src/tike/main/UfrmMessages.dfm
developer/src/tike/main/UfrmMessages.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmCloneLocalProjectParameters.pas

* Add unit test to verify the format of message detail strings (max line length of 80 chars)
* Add unit test to verify non-null, non-empty message strings
* Tidy up a number of messages (to pass unit tests)
* Add message details for all kmw compiler messages
* Add a clickable link for the TIKE message window for each message so that explanations and further message details are more accessible to authors (`kmc message` is already available for command-line users)
* Fixes a number of minor issues with the messages window in TIKE, mostly relating to when popup menu commands are enabled and how messages are selected.
Fixes: #13134
* TEST_MESSAGE_LINKS: Open a keyboard project, compile it, and attempt to click on the KM##### links in the message window that appears. Verify that the links go to …

feat(developer): improve compiler messages and user interface

---

developer/src/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas
developer/src/kmconvert/Keyman.Developer.System.LdmlKeyboardProjectTemplate.pas
developer/src/kmconvert/Keyman.Developer.System.ModelProjectTemplate.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewLDMLKeyboardProjectParameters.dfm

* Links welcome.htm in the package details for all project types
* Uses v17 project file format for new lexical model projects
* Nit: changes shortcut key for 'supported languages' from 'l' to 's' to fix conflict with 'full copyright'.
Fixes: #13135

fix(developer): link welcome.htm in package for new projects; use v17 project format for new models

---

oem/firstvoices/windows/src/xml/strings.xml
windows/src/desktop/kmshell/xml/strings.xml

I missed the english phrase being copied over to the koCheckForUpdates flag.  I only removed the koAutomaticUpdate in the base strings.xml but didn't copy over the phrase.
I did it for the already translated languages but missed the english in the file I committed and pushed.
Install Keyman from this PR
Open Keyman Options and verify the text appears 
see the expected result (which I got by downloading the attached PR :))
"Automatically check for updates and download"

fix(windows): use Automatically check for updates and download for the english xml

---

linux/ibus-keyman/src/KeymanSystemServiceClient.cpp
linux/ibus-keyman/src/KeymanSystemServiceClient.h
linux/ibus-keyman/src/engine.c
linux/ibus-keyman/tests/ibusimcontext.c
linux/ibus-keyman/tests/meson.build
linux/keyman-system-service/src/KeyboardDevice.cpp
linux/keyman-system-service/src/KeyboardDevice.h
linux/keyman-system-service/src/KeymanSystemService.cpp
linux/keyman-system-service/src/KeymanSystemService.h
linux/keyman-system-service/src/OrderedOutputDevice.cpp
linux/keyman-system-service/src/OrderedOutputDevice.h
linux/keyman-system-service/src/com.keyman.SystemService1.System.xml
linux/keyman-system-service/src/meson.build
linux/keyman-system-service/tests/KeyboardDeviceMock.cpp
linux/keyman-system-service/tests/meson.build

This change allows to press F24 as ordered output sentinel from keyman-system-service.
This is part of implementing serialized output with keyman-system-service instead of requiring a patched ibus.
The problem both approaches try to solve is that with non-compliant apps it is not possible to directly delete characters from the context. Instead we have to emit a backspace key before we can commit the new characters. However, the backspace key press goes through a different code path in ibus and so it can happen that the commit gets processed before the backspace which then deletes from the characters we just added instead of from the old content.
The previous implementation solved this by forwarding a F24 ordered output sentinel key to ibus and relying on the patched ibus to send that back …

change(linux): Implement ordered output without patched ibus

---

windows/src/desktop/kmshell/main/initprog.pas
windows/src/desktop/kmshell/startup/UfrmSplash.pas
windows/src/engine/kmcomapi/com/system/keymancontrol.pas
windows/src/global/delphi/general/KeymanMutex.pas

Add a ReleaseOwnership member to TKeymanMutex.
Rename MutexOwned to TakeOwnership.
Fixes: #13167
- Install Keyman from the PR
- Start Keyman and open Keyman Configuration. 
- Open Notepad so that it is in front of the Keyman Configuration Window
- Now attempt to open Keyman Configuration even though it is already open. Right-click on the Keyman Icon in the system tray and choose `Configuration` from the context menu.
Expected Result: the existing Keyman Configuration Window now has focus and not `Notepad`

refactor(windows): rename `TKeymanMutex.MutexOwned` to `TakeOwnership` and add `ReleaseOwnership`

---

linux/ibus-keyman/src/KeymanSystemServiceClient.cpp
linux/ibus-keyman/src/KeymanSystemServiceClient.h
linux/ibus-keyman/src/engine.c
linux/keyman-system-service/src/KeymanSystemService.cpp
linux/keyman-system-service/src/com.keyman.SystemService1.System.xml

This change fixes #13171 where we failed to output after the first keypress because the keyman system service had to be started. This change introduces a new method `Ping` that we call to force keyman-system-service to be started.
Fixes: #13171
Can be tested on Ubuntu with Gnome Shell and X11, e.g. Ubuntu 24.04 Noble with Gnome Shell and X11.
**TEST_TERMINAL_IPA:** Open a terminal, then switch to "IPA (SIL)" keyboard. Type `an>`. Verify that the result is "aŋ".

fix(linux): start system service when switching keyboards

---

.github/workflows/api-verification.yml
.github/workflows/deb-packaging.yml

Our previous version of actions/cache will stop working at the end of February. This change updates to the latest version.
https://github.com/actions/cache/discussions/1510

chore(linux): update actions/cache to non-deprecated version

---

.github/workflows/deb-packaging.yml
docs/linux/README.md
linux/debian/rules
linux/scripts/launchpad.sh

Ubuntu 20.04 Focal will reach EOL in April and GitHub removes the runner images, so we no longer will be able to build packages for Focal. 
Also remove/update some code that is now obsolete with the removal of Focal.
(Added as cherry-pick because of the additional code cleanup which #13202 doesn't have)
Cherry-pick-of: #13202 

chore(linux): remove support of Ubuntu 20.04 Focal 🍒

---

linux/debian/control

Use the `beta` branch while we're in Beta.

chore(linux): update branch that's used for Debian packaging

---

HISTORY.md

Relates to #13138 which fixes tiers in HISTORY.md
17.0.335 should be `stable` instead of `alpha` in the changelog.

chore(common): Fix 17.0.335 tier in HISTORY.md

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeyboardMenuView.swift
ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift

Addresses parts of #12216.
Note that part of this is sort of reversing much of #683's commit 46a6b3013e89f9b7d358e4c020a020cbd95d6b7f.
While I find it interesting that this doesn't resolve #12216, the fact that those parts of the code did not interfere with the results of #6552 at the time, which did fix the memory leaks (for a while?) kind of does hint that these changes weren't likely to be enough.  Still, knocking out potential contributors to memory leaks is still wise.
TEST_IOS_FRESH_INSTALL:  Using the Keyman app for iPhone and iPad, verify that the help bubble tip for fresh installs above the globe key displays when it should.
1. If the test device has a prior installation of the app, remove it completely.
2. Install the test artifact of the app from this PR.
3. When the app …

change(ios): prevent memory leaks from keyboard-related notification observers

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Manager.swift

Related-to: #12216
While we can't fully correct the memory leak identified and analyzed as part of the base issue, our analysis did reveal something promising - we _can_, at least, manually clean up the last reference(s) to our keyboard's internal WebView and ensure _that_ gets garbage-collected.  Its memory use is an order-of-magnitude higher than that of `CustomInputView`, so this is still a notable win.  
This change should greatly reduce the incidence rate of this issue and thus make related crashes far less frequent.

change(ios): mitigate keyboard input-view memory leak by force-discarding WebView

---

developer/src/kmc-copy/src/copier-messages.ts
developer/src/kmc-generate/src/generator-messages.ts
developer/src/kmc/src/commands/copy.ts
developer/src/kmc/src/commands/generate.ts
developer/src/kmc/src/messages/infrastructureMessages.ts
developer/src/kmc/src/util/NodeCompilerCallbacks.ts

Note: these messages are in `kmc`, not in `kmc-copy` or `kmc-generate`, matching the structure for existing `INFO_BuildingProject` and related messages.
Sample messages:
```
$ kmc generate keyman-keyboard wagaga
wagaga - info KM05026: Generating new project 'wagaga' in '.'.
wagaga - info KM05027: New project 'wagaga' generated successfully.
```
```
$ kmc copy /d/Projects/keyman/keyboards/release/a/anii/ -o /c/temp/ano
anii - info KM05023: Copying project 'D:/Projects/keyman/keyboards/release/a/anii' to 'C:/temp/ano'
anii - info KM05024: 'D:/Projects/keyman/keyboards/release/a/anii' copied to 'C:/temp/ano' successfully.
```
Fixes: #13127

chore(developer): add INFO messages for `kmc copy` and `kmc generate`

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustLongpressDelayActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMEA/app/src/main/assets/android-host.js
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Follows #12170 and #12185 re: new menu to adjust the longpress delay
Fixes #13165 
Removes `sendOptionsToKeyboard()` from 18.0 Keyman Engine APi so Keyman Engine handles the responsibility to send the longpress delay value to KeymanWeb.
android-host.js now caches the longpress value, so the call can now work before the keyboard is loaded.
**Setup** - Install the PR build of Keyman for Android. Set and enable Keyman as the default system keyboard.
When the tests ask to adjust the longpress delay value, in Keyman app, go to Settings --> Adjust longpress delay --> 
adjust the slider to the specified time and exit the menu with the back button on the menu
* **TEST_ADJUST_DELAY_MENU** - Verifies the longpress delay value can be adjusted and applied
1. Launch Keyman and dismiss the "Get …

fix(android): Remove sendOptionsToKeyboard function from Engine API

---

web/src/test/auto/dom/web-test-runner.CI.config.mjs

change(web): drop 'dom' unit test concurrency when run in CI mode

---

web/build.sh
web/src/engine/predictive-text/build.sh

Addresses parts of #12735.
Addresses some observations from https://github.com/keymanapp/keyman/pull/13141#issuecomment-2641778131 - namely, that predictive-text tests were running in the Web-test configuration, not just in the predictive-text configuration.

chore(web): ensure /web/build.sh clean triggers all predictive-text child actions

---

resources/docker-images/linux/Dockerfile
resources/docker-images/run.sh

This changes the download URL for the lcov package to the official Ubuntu archive, after it was no longer available at kernel.org.

fix(linux): update location of lcov.deb for Jammy

---

android/KMAPro/kMAPro/build.gradle
oem/firstvoices/android/app/build.gradle

Fixes #13254
Recent Android beta builds fail to publish to the Play Store because we recently removed `System.env.TIER` from the Android CI configurations. Both Keyman and FirstVoices app build.gradle files were using the environment var to determine the tier to publish on the Play Store.
This updates the gradle files to use TIER.md.

fix(android): Use TIER.md to determine Play Store tier

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/res/values/strings.xml
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardDownloaderActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/ModelPickerActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/cloud/CloudDownloadMgr.java
android/KMEA/app/src/main/java/com/keyman/engine/cloud/DownloadManagerDisabledException.java
android/KMEA/app/src/main/java/com/keyman/engine/cloud/impl/CloudLexicalModelMetaDataDownloadCallback.java
android/KMEA/app/src/main/java/com/keyman/engine/data/CloudRepository.java
android/KMEA/app/src/main/java/com/keyman/engine/logic/ResourcesUpdateTool.java
android/KMEA/app/src/main/java/com/keyman/engine/util/DownloadFileUtils.java
android/KMEA/app/src/main/res/values/strings.xml

Fixes: #11568.
At a minimum, failure to check for resource update availability is not something that should crash either our app or our system keyboard.  It's not critical functionality - even if desired - and so we should allow the rest of either program to keep operating without it.
Our analysis has identified that the `DownloadManager` service of the Android OS is likely highly related to the cases that caused our crashes in these areas.  Even if not, that specific pathway includes sufficient logic to gracefully fail for the app-launch and sys-keyboard launch cases.
There are some areas that are a bit more complicated.  Our keyboard-search, model-lookup, and similar operations that are possible from a fully-launched app are constructed in a way in which it is difficult at best to …

fix(android): prevent update-checks from crashing system keyboard and app if `DownloadManager` is disabled

---

docs/settings/linux/launch.json
linux/ibus-keyman/tests/README.md
linux/ibus-keyman/tests/scripts/run-tests.sh

This allows to run the tests in a VM and debug them remotely. Also document debugging the integration tests, and improve the output if dependencies are missing.
Also some cleanup.

feat(linux): add `--remote-debug` flag to `run-tests.sh` script  🕷️

---

android/KMAPro/kMAPro/build.gradle
oem/firstvoices/android/app/build.gradle

Fixes #13265 and follow-on to #13259
I tried to refactor `tier` in the build.gradle files and didn't have the scope high enough to be visible to where the build failed.
This is take-2
The FirstVoices build.gradle only uses tier in once place, so made that one local.

fix(android): Correct the scope of `tier` in build.gradle

---

web/src/app/ui/kmwuibutton.ts
web/src/app/ui/kmwuifloat.ts
web/src/app/ui/kmwuitoggle.ts
web/src/app/ui/kmwuitoolbar.ts

Fixes: #13261
Rather than have the UI module (attempt to) silently fail, it's probably better for site developers if we provide a more clear, informative, and explicit error when such modules fail to load properly.
Granted, this doesn't exactly make the Sentry reports on our own sites in which the engine appears to fail to load (and silently, at that - then fail on attempted engine use) go away.

fix(web): provide informative error + message when loading UI without the engine

---

developer/src/tike/child/UfrmKeymanWizard.pas

When the IDE fills the On Screen Keyboard on the basis of the .kmn rules, it generates a temporary .kmn and builds it. When it does this, it temporarily replaces the `&targets` system store with one that is supposed to ensure that a .kmx is generated. However, previously, for reasons long lost in history, the store was filled with the value 'windows native'.
'native' is not a valid target (this may be due to confusion with `if(&platform)` where 'native' is permitted), and now the compiler verifies `&targets` (as of #11918), so this broke the compile.
Now uses 'desktop' (which encompasses 'windows', 'macos', 'linux').
Fixes: #13256
Relates-to: #11918
* TEST_GENERATE_OSK: Please verify that the issue described in #13256 is resolved with this build.

fix(developer): Use 'desktop' for target in OSK fill temp keyboard

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/res/values/strings.xml
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardDownloaderActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/ModelPickerActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/cloud/CloudDownloadMgr.java
android/KMEA/app/src/main/java/com/keyman/engine/cloud/DownloadManagerDisabledException.java
android/KMEA/app/src/main/java/com/keyman/engine/cloud/impl/CloudLexicalModelMetaDataDownloadCallback.java
android/KMEA/app/src/main/java/com/keyman/engine/data/CloudRepository.java
android/KMEA/app/src/main/java/com/keyman/engine/logic/ResourcesUpdateTool.java
android/KMEA/app/src/main/java/com/keyman/engine/util/DownloadFileUtils.java
android/KMEA/app/src/main/res/values/strings.xml

Fixes: #11568
Fixes: KEYMAN-ANDROID-3AB
Cherry-pick-of: #13218

fix(android): prevent update-checks from crashing system keyboard and app if `DownloadManager` is disabled 🍒  🏠

---

linux/debian/changelog

Turns out that Keyman 18 already compiles with ICU 76, so the only thing left to do is mark the Debian bug as being closed by this change.
Fixes: #12920

fix(linux): address compiling with ICU 76

---

resources/docker-images/base/Dockerfile
resources/docker-images/build.sh
resources/docker-images/run.sh

This allows to build docker images for Debian in addition to Ubuntu. While we usually only develop on/for Ubuntu, this is helpful when tracking down problems that get flagged when uploading to Debian.

chore(linux): allow to build and use Debian docker image

---

windows/src/support/kmdevlink/UfrmMain.pas
windows/src/support/kmdevlink/UfrmOpenCRMRecord.dfm
windows/src/support/kmdevlink/UfrmOpenCRMRecord.pas

This was an evening activity scratching itches on kmdevlink's 'Open Issue' dialog. The search box now supports three different types of strings:
1. `[[repo]#]num` -> open issue/PR #num in repo (if repo omitted, will use 'keyman'):
* `13235` or `#13235` or `keyman#13235` -> opens PR #13235
* `keyman.com#545` -> opens PR keymanapp/keyman.com#545
* `api#172` -> opens PR keymanapp/api.keyman.com#172
2. `[[repo]#]searchtext` -> any non-numeric string does an issue search:
* `label:ios/ font` -> opens an issue search for 'ios/' label and 'font' in keymanapp/keyman repo
* `api#db` -> opens an issue search for 'db' in keymanapp/api.keyman.com repo
3. `[[repo]#]` -> opens issue list for repo (keymanapp/keyman if repo is omitted, or empty box)
A second feature is construction of a HTML snippet of …

feat(windows): hack in some fun features for kmdevlink

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java

Fixes #13245 and follows #11604 in the long line of changes to fix OSK height after an orientation change (portrait <--> landscape)
This moves the SystemKeyboard orientation update from `onStartInput()` (init only) to [`onComputeInsets()`](https://developer.android.com/reference/android/inputmethodservice/InputMethodService#onComputeInsets(android.inputmethodservice.InputMethodService.Insets)) where it's consistently called on configuration changes.
**Setup** - Install the PR build of Keyman for Android. 
* **TEST_OSK_HEIGHT_AFTER_ADJUSTING** - Verifies system keyboard OSK height is correct after adjusting the height and rotating
1. Launch the Keyman app in portrait view.
2. The "Get Started" menu appears, enable Keyman as a system keyboard and set it as the default keyboard.
3. Resize …

fix(android): Update system keyboard height consistently

---

resources/docker-images/build.sh

Passing this parameter causes docker image builds on mac to fail (#13295). Since `amd64` is the default anyways (and we don't support other values), we can simply remove that parameter.
Fixes: #13295

fix(linux): remove `--platform amd64` from docker build script

---

android/KMAPro/kMAPro/build.gradle
oem/firstvoices/android/app/build.gradle

:cherries: pick of #13259 and #13268 to stable-17.0
This is in case we need to do another stable-17.0 build before 18.0 is released
We recently removed `System.env.TIER` from the Android CI configurations. 
Both Keyman and FirstVoices app build.gradle files were using the environment var to determine the tier to publish on the Play Store.
This updates the gradle files to use TIER.md.

cherrypick(android): Use TIER.md to determine Play Store tier 🏠

---

web/src/app/browser/src/debug-main.ts
web/src/app/browser/src/keymanEngine.ts
web/src/app/browser/src/release-main.ts
web/src/app/webview/src/debug-main.ts
web/src/app/webview/src/keymanEngine.ts
web/src/app/webview/src/release-main.ts
web/src/engine/main/src/headless/inputProcessor.ts
web/src/engine/main/src/headless/languageProcessor.ts
web/src/engine/main/src/keymanEngine.ts
web/src/engine/predictive-text/worker-main/src/index.ts
web/src/engine/predictive-text/worker-main/src/node/index.ts
web/src/engine/predictive-text/worker-main/src/web/index.ts
web/src/test/auto/headless/engine/interfaces/prediction/predictionContext.tests.js

Fixes: #13262
Fixes: KEYMANWEB-COM-1VH
Supersedes: #13270.
TEST_ANDROID_PREDICTIONS:  Using the Keyman for Android test artifact, verify that predictive text appears to function as usual.

fix(web): properly support workerless use of Web engine

---

ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html

This change is designed to help further investigate #13312, in which it appears that the main Keyman Engine for Web script is failing to load on occasion.
TEST_SIMPLE_APP_START:  Launch the Keyman app and verify that it functions and types normally.  A simple "everything looks good" check; no need to be detailed here.

change(ios): re-order host page script load so Sentry can report script load failures

---

web/src/app/browser/src/contextManager.ts
web/src/app/browser/src/keymanEngine.ts
web/src/test/manual/web/issue11785/clear-cookies.js
web/src/test/manual/web/issue11785/index.html
web/src/test/manual/web/issue11785/load-keyboards.js

Fixes: #13278
The fallback default keyboard corresponding to an uninitialized cookie is `Keyboard_us:en`.   This should only occur if the site actually registers its stub before initialization - and we weren't checking/filtering for this properly.
The error itself only occurred if there _were_ stubs pre-registered before init - if none existed, the error does not result.
TEST_WEB_PAGE_INIT:  Using the KeymanWeb test page titled "Test OSK loading with early add-keyboard calls (#11785)", verify that the page initializes smoothly, without errors or alerts.
- If an alert pops up saying "No matching stub has been registered", before you've interacted with any KMW elements, FAIL this test.

fix(web): prevent cookie-default behavior from mangling engine init

---

linux/keyman-config/keyman_config/gsettings.py

The `xdg` module got renamed to `xdg_base_dirs`. However, Ubuntu still ships the `python3-xdg` package with the old module, so we'll have to support both so that it'll work with both Ubuntu packages and in a virtual environment.

chore(linux): adjust to renamed xdg module

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/KMEA/app/src/main/res/values/strings.xml

Fixes #13244 and follows #11560
Keyman fails to initialize when WebView is uninstalled/disabled.
Within the Keyman app, a text area tells the user how to fix the issue with WebView/Chrome.
Currently, the Keyman system keyboard silently fails, so this PR prompts the user to switch to another IME.
The UX options are limited since Keyman system keyboard runs as an Input Method Service.
There's no UI thread available to display alerts, Toast notifications, or launch new Activities.
(Modern Android versions restrict launching activities from the background service)
All my attempts to display alert/Toast/Activity only worked when the Keyman app was running in the background
So this leaves using the Input Method Manager keyboard picker.
* Since alert dialog is unavailable, also removed unused …

fix(android): Direct user to switch system IME when WebView fails

---

android/KMEA/app/src/main/java/com/keyman/engine/util/Connection.java

Fixes: KEYMAN-ANDROID-54G
Downgrades socket connection errors (due to timeout) in Sentry from `Exception` to `Info` (with a breadcrumb to the URL).
Tested in an engineering build by overriding  
```java
url = new URL("http://10.255.255.1");
```

fix(android): Filter out SocketTimeoutExceptions

---

developer/src/tike/child/UfrmDebug.pas

With the move to the richedit control, hotkeys such as Ctrl+V are natively managed and we no longer need to handle them separately, as this caused actions to be applied twice.
Fixes: #13335

fix(developer): prevent double action of editor hotkeys in debugger

---

docs/build/windows.md

node.js is required in order to run Emscripten

docs: move node.js before Emscripten

---

linux/keyman-config/keyman_config/dbus_util.py
linux/keyman-config/tests/dbus_util_tests.py
linux/keyman-config/tests/uninstall_kmp_tests.py

Fixes: #12902
Fixes: #13283
Fixes: KEYMAN-LINUX-7J
Fixes: KEYMAN-LINUX-7R
**TEST_INSTALL**: verify that installing a keyboard still works
**TEST_UNINSTALL**: verify that uninstalling a keyboard still works

fix(linux): ignore DBusException during install and uninstall

---

.github/workflows/close-linked-issues-for-merged-prs.yml

Automatically closes issues when PR is merged into beta, epic/* or stable-*

chore: add a workflow to automatically close linked issues

---

linux/keyman-config/keyman_config/install_window.py

Fixes: #13282
Fixes: KEYMAN-LINUX-7S

fix(linux): ignore exception when fcitx5-configtool is not found

---

developer/src/tike/main/Keyman.Developer.System.KeymanDeveloperPaths.pas
developer/src/tike/main/UfrmMain.pas
developer/src/tike/project/Keyman.Developer.UI.Project.ProjectUI.pas

There is a race condition where two processes may both attempt to open the same project file. This appears to happen, for example, if an author double-clicks on a single-click shortcut, launching Keyman Developer twice in quick succession.
This fix adds a .lock file which is deleted automatically on close of the project or on normal or abnormal process termination. If a second process encounters the .lock file, it will simply open the welcome view instead of attempting to open the project.
Fixes: #11584
Fixes: KEYMAN-DEVELOPER-1PR
* TEST_PROJECT_LOADING: In Keyman Developer, verify that opening and closing a variety of projects works correctly, and that creating projects works correctly, and that opening projects from Windows Explorer works correctly. Try opening a project multiple times …

fix(developer): prevent simultaneous opening of the same project by two processes

---

windows/src/desktop/kmshell/main/initprog.pas
windows/src/desktop/kmshell/startup/UfrmSplash.pas

Don't start an install of Keyman Update if the user has not been notified.
This also refactors some of the code into a single helper function which is only called once. However, it visually helps follow the logic. 
I also changed in this PR was the removal of a `background update check` in the actualy Keyman Start function. This is superfluous.
It also makes the testing of this PR watching the state machine changes easier to observe.
Fixes: #13329
We need to test that if Keyman is in `Waiting Restart` and kmshell is started with a `-s` switch for silent mode that we don't install. 
We need to test that if Keyman is in states preceding `Waiting Restart` and kmshell is started with a `-s` switch for a silent mode that the handlekmshell event is passed to the state machine …

fix(windows): if kmshell is "silent" don't start a Keyman update

---

common/windows/delphi/components/build.sh
common/windows/delphi/general/KeymanPaths.pas
common/windows/delphi/tools/build_standards_data/build.sh
common/windows/delphi/tools/buildunidata/build.sh
common/windows/delphi/tools/devtools/build.sh
common/windows/delphi/tools/sentrytool/build.sh
common/windows/delphi/tools/test-klog/build.sh
common/windows/delphi/tools/verify_signatures/build.sh
developer/src/common/delphi/build.sh
developer/src/kmconvert/build.sh
developer/src/kmdbrowserhost/build.sh
developer/src/setup/build.sh
developer/src/tike/build.sh
windows/src/desktop/insthelp/build.sh
windows/src/desktop/kmbrowserhost/build.sh
windows/src/desktop/kmconfig/build.sh
windows/src/desktop/kmshell/build.sh
windows/src/desktop/setup/build.sh
windows/src/engine/insthelper/build.sh
windows/src/engine/keyman/build.sh
windows/src/engine/kmcomapi/build.sh
windows/src/engine/tsysinfo/build.sh
windows/src/engine/tsysinfox64/build.sh
windows/src/global/delphi/build.sh
windows/src/support/oskbulkrenderer/build.sh

This opens up the Delphi IDE with the correct KEYMAN_ROOT environment, which allows for debugging. This is very helpful when working with multiple worktrees, and also helps to avoid editing a project in the wrong tree.

chore: add build.sh edit action for Delphi projects

---

developer/src/tike/child/Keyman.Developer.UI.Debug.UfrmLdmlKeyboardDebug.dfm
developer/src/tike/child/Keyman.Developer.UI.Debug.UfrmLdmlKeyboardDebug.pas
developer/src/tike/child/UfrmDebug.pas
developer/src/tike/debug/Keyman.System.Debug.DebugUtils.pas
developer/src/tike/debug/Keyman.UI.Debug.CharacterGridRenderer.pas
developer/src/tike/debug/debugdeadkeys.pas

Previously, we used U+FFFC as a marker in the debugger (for deadkeys and LDML keyboard markers), which displayed as the letters OBJ in a small dotted square. However, we switched the underlying component to RichEdit, in order to better support rendering of many scripts (EDIT has some problems). The RichEdit control silently converts U+FFFC to U+0020. I switched to U+0001 as this is handled better, but has an unfortunate missing-glyph marker.
In the future, it would be better to use a non-character marker (leveraging RichEdit), but this is a much more complex change, and this fix at least matches previous functionality.
Fixes: #13293
TEST_DEADKEYS: In the keyboard debugger, select a keyboard that includes deadkeys (such as sil_bengali_phonetic). Try typing keys that generate deadkeys, and …

fix(developer): use U+0001 for deadkey markers in the debugger

---

developer/src/tike/child/UfrmPackageEditor.dfm
developer/src/tike/child/UfrmPackageEditor.pas

Requested by @DavidLRowe. Default was either CWD or My Documents, neither of which is helpful.
The initial dir will now be folder of the .kps file, and then will remember last used folder for each additional use of the dialog for that .kps file.

feat(developer): use .kps folder as initial dir for Add Files

---

core/src/kmx/kmx_processevent.cpp
core/src/kmx/kmx_processevent.h

Two separate bugs addressed, with `index()` references and with `context()` references -- both have the same root cause, of not taking `nul` at the start of the context into account (as `nul` is not included in the `m_miniContext` member, being a non-character). We already fixed this issue for `if()` quite a long time ago, and some of the same patterns can be seen with `m_miniContextIfLen` for example.
Fixes: #13304
Fixes: #13316

fix(core): include `nul` in context offset calculations in kmx processor

---

developer/src/kmc-kmn/src/kmw-compiler/javascript-strings.ts
developer/src/kmc-kmn/test/fixtures/kmw/test_index_12980_v10.kmn
developer/src/kmc-kmn/test/fixtures/kmw/test_index_12980_v9.kmn
developer/src/kmc-kmn/test/kmw/kmw-compiler.tests.ts

The cached context comparison for v10 kmw compiler includes the `nul` statement, unlike the comparison in the earlier compiler. This difference was missed in earlier iterations including the recent patch in #13003. This patch fixes the problem for both `context(n)` and `index(store,n)` offset calculations.
The earlier v9 kmw compiler is not impacted by this change.
Fixes: #13306
Fixes: #13307
Follows: #13003
Note: I will do some low-level tests before merging and add results as a comment.

fix(developer): include `nul` in offset calculations for kmw v10 compiler

---

core/build.sh
windows/src/engine/keyman32/build.sh

Add a `:win` meta-target to the /core/build.sh project. This `:win` target triggers both `:x86` and `:x64` targets, and allows us to specify `@/core:win` in the windows/keyman32/build.sh project, in order to build only those two targets, and not `:wasm` target as well (as we don't need WASM Core for Keyman for Windows).
This closely mirrors the pattern we used for `:mac` in /core/build.sh. We could consider using `:arch` instead of `:win` and `:mac` but that needs more careful consideration, as `:arch` implies only the current architecture of the building machine.
This change also sets us up well for when we start doing arm32 and arm64 builds for Windows on ARM in the near future.
Fixes: #13374

chore(windows): ensure dependencies for keyman32 exclude core:wasm

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/KMEA/app/src/main/java/com/keyman/engine/KeyboardPickerActivity.java

Fixes #12991 
For as long as Keyman for Android 2.8, the system keyboard KeyboardPickerActivity has been setting the `Intent.FLAG_ACTIVITY_CLEAR_TASK` flag which becomes the root activity and clears previous tasks (Keyman app).
When using Keyman as a system keyboard within the Keyman app, we don't want this to occur.
TODO:
Add call to  disable/enable when the system keyboard Keyboard Picker clears previous tasks.
**Setup** - Install PR build of Keyman for Android
From "Get Started", set Keyman as the default system keyboard.
* **TEST_INAPP** - Verifies keyboard picker within the Keyman app
2. With the inapp keyboard, hold the globe key to launch the Keyboard Picker
3. Dismiss the keyboard picker
4. Verify the Keyman app is not dismissed
5. From Keyman, access …

fix(android): Control when system keyboard Keyboard Picker clears activity stack

---

android/docs/engine/KMManager/closeParentAppOnShowKeyboardPicker.md
android/docs/engine/KMManager/dontCloseParentAppOnShowKeyboardPicker.md
android/docs/engine/KMManager/index.md

Follows #13313 and documents the KMManager() APIs to control the keyboard picker flag
* closeParentAppOnShowKeyboardPicker()
* dontCloseParentAppOnShowKeyboardPicker()

docs(android): document control flag for system keyboard picker and task

---

resources/build/trigger-builds.inc.sh

Was silently accepting failure in curl api.github.com call, causing a subsequent failure when triggering the deb-packaging GHA. Instead, handle failing subshell call to api.github.com by failing the script, hopefully with some detail provided on the failure.
Fixes: #13401

fix(common): improve resilience of build script trigger

---

android/KMAPro/kMAPro/src/main/res/values-kr-rNG/strings.xml
android/KMEA/app/src/main/java/com/keyman/engine/packages/PackageProcessor.java

Fixes KEYMAN-ANDROID-4G and follows the guidance on #11368
> There's a few causes of this in the Sentry crashes
> * kmp.json is null
> * kmp.json doesn't exist
> * kmp.json doesn't contain keyboards or lexical-models
> in those cases we should be telling the user that the package is not Android-compat, and not logging an error on our end.
Removing these Sentry errors, the user gets Toast notification "~No keyboards or predictive text to install~" "This is not a valid Keyman keyboard or predictive text package."
* Also for more info, added a breadcrumb if the temporary directory can't be made for extracting the kmp file.
**Setup** - Install the PR build of Keyman for Android.
Also download a test keyboard which intentionally doesn't contain kmp.json …

fix(android): Don't report missing kmp.json

---

developer/src/common/web/utils/build.sh
developer/src/kmc-model-info/build.sh
resources/shellHelperFunctions.sh

This is probably my fault, when I consolidated the typescript test scripts, I didn't spot the `--check-coverage=false` flag which meant that although the coverage tests were run, the builds would not fail if they were too low.
I am anticipating some builds failing until I adjust thresholds...
Fixes: #13417

fix(common): fail builds with low test coverage for all typescript projects

---

windows/src/desktop/kmshell/main/Keyman.System.RemoteUpdateCheck.pas
windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas
windows/src/desktop/setup/UfrmRunDesktop.pas
windows/src/engine/keyman/UfrmKeyman7Main.pas
windows/src/engine/kmcomapi/util/utilkeymanoption.pas

Fixes: #13216 
The `SRegValue_CheckForUpdates` was written by `utilkeymanoptions`
to the `Keyman Engine` Key but read from `Keyman Desktop` Key.  
This change moves it to only be read in Keyman Engine Key.
It also move the last update time to this Key for completeness.
I was curious why it seemed to work before.
The logic previously (since I think about version 10) was     
```
if OpenKeyReadOnly(SRegKey_KeymanDesktop_CU) then
begin
if ValueExists(SRegValue_CheckForUpdates) and not ReadBool(SRegValue_CheckForUpdates) then Exit;
if ValueExists(SRegValue_LastUpdateCheckTime) and (Now - ReadDateTime(SRegValue_LastUpdateCheckTime) < 7) then Exit;
TKeymanDesktopShell.RunKeymanConfiguration('-ouc');
end; 
```
It would continue after the second if because `ValueExists(SRegValue_CheckForUpdates)` …

fix(windows): Check for updates registry value stored under the one Key

---

windows/src/desktop/kmshell/xml/keyman_update.xsl

Hide the header for the grid of new updates when
no updates are available. "Updated Component | Old Version | Size "
Fixes: #13069
1. Install Keyman attached this PR
2. Once installed, open Keyman Configuration and the Update tab.
3. Verify that there is no table header of "Updated Component | Old Version | Size "
Got to next test 
Continue from TEST_NO_UPDATES_NO_HEADER
1. Press the `Check for new updates` button
2. If Updates are available verify that the header of now appears "Updated Component | Old Version | Size "
3. If there are no updates available install the old euro latin keyboard attached to this PR
[sil_euro_latin.zip](https://github.com/user-attachments/files/19119646/sil_euro_latin.zip)
5. Once installed, go back into to Keyman Configuration and Updates. Press the `Check …

feat(windows): hide update header if no updates are available

---

ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift

Do not show the Get Started dialog when dismissing the help page. This was only an issue when Keyman is configured to show the Get Started dialog, and it is not set up as the System keyboard.
From the code, it was clear that this was behaving as designed, but it does seem like overkill.
Fixes: #8662
* **TEST_NO_GET_STARTED_ON_HELP_DISMISSAL**: The Get Started dialog does not appear when help page is closed
1. Install and run the Keyman build associated with this PR
1. Confirm that the Get Started dialog is presented when starting Keyman
1. If the Get Started dialog is not presented, then disable Keyman under Settings->Apps->Keyman->Keyboards
1. Confirm that the Get Started dialog is presented when starting Keyman
1. Dismiss the Get Started dialog
1. From the menu in Keyman, choose the …

fix(ios): suppress Get Started dialog when closing help page

---

oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Fixes: FV-ANDROID-5G
FixeS: FV-ANDROID-7N
From the days of stable-12.0 when the FirstVoices for Android app was configured in the main repo, the SystemKeyboard initialized with
https://github.com/keymanapp/keyman/blob/3148aa7b8c8a4b5de574d49bdf6edc80dcb6761a/oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java#L111-L113
In the scenario FV for Android installed and enabled as the system keyboard (from the Android settings menu instead of launching the FV app), the initial usage as a system keyboard would have an uninitialized keyboard key (language and keyboard ID pairing to determine the current keyboard).
This is all managed by KeyboardController() now, so these spurious lines can be removed. (They never existed in the Keyman for Android app)
**Setup** …

fix(oem/fv/android): Avoid resetting keyboard index

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java

Fixes: KEYMAN-ANDROID-65D
Fixes: FV-ANDROID-ZY
Reference:
https://developer.android.com/reference/android/inputmethodservice/InputMethodService#getCurrentInputConnection()
Currently, `insertText()` and `dispatchKey()` log errors if `getCurrentInputConnection()` returns null.
This happens when the current active InputConnection is no longer bound to the Keyman Engine input method
(user switched to another IME) so Keyman Engine for Android should disregard the keystroke.
This can occur if the user is in a single Keyman keyboard and quickly hits keys and the globe key to switch to another IME. By the time KeymanWeb processes the key stroke, the user is now in a different system IME.

fix(android/engine): Ignore key errors if user switched to another IME

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java

Fixes #13125 
> When interacting with the main text input area on keymanweb.com, the active "input type" enum provided to us by Android is `InputType.NULL`
> 
> In this mode, the keyboard has no view into any surrounding text. After all, the keystrokes should be directly interpreted, rather than editing text directly
This PR updates SystemKeyboard to cache the inputType. When starting input, the inputType is checked to see if the physical keystroke should be ignored and passed to the device.
Depends on #12848 to test the interaction with keymanweb.com

fix(android): Cache inputType to determine external keyboard handling

---

developer/src/tike/main/Keyman.Developer.System.LaunchProjects.pas
developer/src/tike/main/UfrmMain.pas

When launching a new instance of TIKE to open a source file that does not have an owning project, use '-' as a placeholder for the project filename, because passing an empty string as a parameter does not work.
Fixes: #13317
To prepare for this test, copy a .kmn file from an existing Keyman Developer projet onto your desktop.
* TEST_OPEN_FILE: Open a project in Keyman Developer. Then, using File|Open, open the .kmn file that is on your desktop. The file should open in a new Keyman Developer instance, in a "temporary project".

fix(developer): use '-' as placeholder for temp project name in cmdline

---

common/windows/delphi/components/OnScreenKeyboard.pas

Fixes: #13106
This only changes the colour of the key caps on the OSK to always be a almost black in colour. Other menus etc in Keyman may still be hard to read depending on the colour theme chosen in for the Windows operating system. This is change is not for full theme support. 
In Windows 10 I had to use High contrast to get the Windows text colour to change. Windows 11 may have more controlability.
1 Install the Keyman from this PR install a keyboard in my test I chose classical greek.
2 Go to Windows settings and search for the `High Contrast` setting turn this on.
3 The default text colour is most likely white; if it is, leave it as is. If it is black, change it to red. 
4 Start Keyman change to the installed keyboard and turn on the OSK. The key caps should be almost black in …

feat(windows): hard code key cap colour

---

mac/Keyman4MacIM/Keyman4MacIM/Privacy/PrivacyWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/en.lproj/Localizable.strings

With macOS 13.0 (Ventura) there were several UI changes in macOS to make the System Settings look more like iOS. A couple of things that were renamed are referenced in a Keyman alert.
The impacting changes are:
- 'System Preferences' was renamed to 'System Settings' 
- 'Security & Privacy' was renamed to 'Privacy & Security'
Change the alert text so that it correctly references the UI elements when running macOS Ventura or later.
**Old Alert** (pre macOS 13.0):
**New Alert** (macOS 13.0 and later):

fix(mac): change text in privacy alert for macOS 13.0 and later

---

developer/src/kmc-ldml/src/compiler/visual-keyboard-compiler.ts
developer/src/kmc-ldml/test/disp.tests.ts
developer/src/kmc-ldml/test/fixtures/sections/disp/not-a-marker.xml
developer/src/kmc-ldml/test/visual-keyboard-compiler.tests.ts

Markers are permitted in key outputs, but when these are used to generate a .kvk, they should be stripped out.
Also added a test for disp to verify that markers are not transformed in `<display display=` attribute values.
Fixes: #13469

fix(developer): strip markers when generating KVK from LDML

---

android/docs/engine/KMManager/getMaySendCrashReport.md
android/docs/engine/KMManager/index.md
android/docs/engine/KMManager/setMaySendCrashReport.md
android/docs/help/about/privacy.md
android/docs/help/basic/config/index.md
docs/build/sentry-cli.md
ios/docs/help/basic/config/index.md
mac/test/EnglishSpanish/README.md

The previous redirect from sentry.keyman.com is long-gone, so this updates all the links.
Keeping an actual link to the Sentry site for Android privacy pages and developer setup.

docs(common): Update Sentry links to keyman.sentry.io

---

android/KMEA/app/src/main/assets/keyboard.html

Parallels #13332, though we haven't seen similar host-page Keyman Engine for Web script-loading issues for Android at this point.
TEST_SIMPLE_APP_START:  Launch the Keyman app and verify that it functions and types normally.  A simple "everything looks good" check; no need to be detailed here.

change(android): re-order host page script load so Sentry can report script load failures

---

web/src/engine/osk/src/input/gestures/specsForLayout.ts

As identified in the analysis for #13344, held backspaces have not been cancelled when receiving new inputs.  It's better and cleaner to have it act similarly to normal keystrokes - receiving a new key input autocompletes any currently-held output keys.
The current, existing behavior also has the potential to get particularly messy with multitaps, which restore the context at their start.  If a backspace is held and then a multitap begins, each new tap of the multitap would undo the backspaces that triggered since the first tap of the multitap.
TEST_BACKSPACE_AUTOCANCEL:  Using Keyman for Android, verify that holding backspace continues to delete characters _until_ a new key is typed.
- It should then stop deleting characters, even without releasing the held backspace.

fix(web): cancel held backspace on new key input

---

developer/src/common/web/utils/package.json
developer/src/common/web/utils/src/xml-utils.ts
developer/src/common/web/utils/test/fixtures/kvks/hex_escape.kvks
developer/src/common/web/utils/test/fixtures/ldml-keyboard/numeric-id.xml
developer/src/common/web/utils/test/fixtures/ldml-keyboard/test-fr.xml
developer/src/common/web/utils/test/kvks/kvks-file.tests.ts
developer/src/common/web/utils/test/ldml/ldml-keyboard-testdata-reader.tests.ts
developer/src/common/web/utils/test/ldml/ldml-keyboard-xml-reader.tests.ts
package-lock.json

fast-xml-reader had a bug with numeric entities. See:
https://github.com/NaturalIntelligence/fast-xml-parser/issues/725
This is a major dependency version bump (4.5.0 to 5.0.9) which we would normally avoid during beta. However, we need the fix https://github.com/NaturalIntelligence/fast-xml-parser/issues/725 for hex escapes in XML, which is incorporated in 5.0.9.
I have assessed the other changes to fast-xml-parser and found no breaking changes for us, but I tightened the types in xml-utils declarations and found some minor inconsistencies which appear to have no impact, and which I have corrected:
* wrong type in unused parameter to `tagValueProcessor`
* reference to unused property `options.emptyTag`
While doing this, I consolidated the common options for the parser in order to verify …

fix(developer): handle non bmp numeric entities in xml reader

---

android/KMEA/app/src/main/java/com/keyman/engine/DisplayLanguages.java
windows/src/desktop/kmshell/locale/ru-RU/strings.xml
windows/src/desktop/setup/locale/ru-RU/strings.xml

Relates to #13519
The original Crowdin strings for Russian language incorrectly used Latin instead of Cyrillic characters.
This updates the strings from incorrect `Pyccĸий` to correct `Русский`.
For #13519, there will be a follow-on PR for sorting the language name UI in English (e.g. "Chinese", "Russian"), and involve a new TBD crowdin string.

fix(android,windows): Update Russian language strings to use Cyrillic script

---

resources/docker-images/base/Dockerfile
resources/docker-images/build.sh
resources/docker-images/run.sh

This PR allows to build and use Debian as base for a docker image. Also initialize variables with default values if the
corresponding parameter is not passed on the command line.
Cherry-pick from master branch to fit in some additional docker related changes.
Cherry-pick-of: #13284

chore(linux): allow to build and use Debian docker image 🍒⛵

---

web/src/engine/main/src/headless/languageProcessor.ts

Fixes: #13512
Fixes: KEYMAN-WEB-QD
Refer to #13290, which added the old version of this check and a match for the new version of check in the same class's `loadModel`.  These should have been consistent and the same, but were not... and as the goal was to support workerless modes of the Web engine, `canEnable` makes much better sense to use here.
TEST_REPRO_13512:  Attempt to reproduce #13512 on an Android device.
1. Important:  make sure the test device has a lock screen with password before starting the repro, as it depends on such a setup.
1. Installed the test artifact for this PR.
2. Launch Keyman for Android
3. From "Get Started" menu, enable Keyman as the default system keyboard
4. Enter a text content.
5. Install a khmer_angkor keyboard by clicking three dots --> Settings --> …

fix(web): model unload and load should use consistent, canEnable check

---

web/src/engine/keyboard/src/keyEvent.ts
web/src/engine/main/src/headless/inputProcessor.ts
web/src/engine/main/src/headless/transcriptionCache.ts
web/src/engine/osk/gesture-processor/src/engine/headless/gestures/matchers/gestureSequence.ts
web/src/engine/osk/gesture-processor/src/engine/headless/touchpointCoordinator.ts
web/src/engine/osk/src/input/gestures/browser/flick.ts
web/src/engine/osk/src/input/gestures/browser/multitap.ts
web/src/engine/osk/src/input/gestures/browser/subkeyPopup.ts
web/src/engine/osk/src/visualKeyboard.ts

To facilitate debugging cases where gestures don't work as intended, this adds sanitized logging for keystrokes resulting for gestures.  These are only to be output when a relevant error or warning is emitted.  They're also pretty handy for obtaining an overview of a gesture's history during code inspection.
This is primarily being added to facilitate investigation of #13344.  An example log that could result for this, though for a properly working state:
```
Context state 31's keystroke:
touch:10 - initial-tap @ 21596.70 ms
Context state 27's keystroke:
touch:9 - modipress-multitap-start @ 19390.00 ms
touch:8 - modipress-multitap-end @ 19271.00 ms
touch:8 - modipress-multitap-start @ 19271.00 ms
<empty> - modipress-end-multitap-transition 
touch:7 - modipress-start @ 19128.00 ms
Context …
```

feat(web): adds gesture 'traces' for warning/error logging

---

.github/workflows/deb-packaging.README.md
.github/workflows/deb-packaging.yml

So far the GHA was called "Ubuntu packaging" but the status reported as "Debian packaging" which was confusing. This change now uses "Ubuntu packaging" in both places.
We still keep the filename `deb-packaging.yml` because we're packaging the .deb format, and because it's shorter.
Fixes: #13497

chore(linux): rename "Debian packaging" to "Ubuntu packaging"

---

windows/src/desktop/kmshell/render/XMLRenderer.pas

This is the same 3 commits from #13467 but based on the beta branch instead of the master branch.

fix(windows): add exception handling for loading xml file in XSL Rendering

---

linux/ibus-keyman/src/engine.c

The new name `initialize_queue_items` makes it clearer that we initialize some items in the queue and not the entire queue (which might still contain items that we do want to keep).

refactor(linux): rename `initialize_queue` method

---

web/src/engine/predictive-text/templates/src/common.ts
web/src/engine/predictive-text/templates/src/index.ts
web/src/engine/predictive-text/templates/src/trie-model.ts
web/src/engine/predictive-text/templates/src/trie.ts

This PR cherrypicks 98ccdef181a695419a4a7cf415c4e6aa5aa1d8c7 (from #12080) to epic/dict-breaker.  It's already part of epic/model-encoding and epic/user-dict, but it turns out we could really use it here too - the dict-breaker needs access to the model's dictionary, and that's Trie-backed.
Note:  it uses the literal same commit as exists in those epics; I worked things out that way to proactively prevent conflicts when the different epics eventually converge in the future.  Note the hash of the second commit below - it's a match.
Realized I needed this when tinkering on the side with how to link the dictionary-based breaker to Trie models; got that PR mostly done while on the wrong base-branch!  (A branch that included these commits.)  Well... aside from its testing.  That's complex …

chore(web): cherry-pick exportable trie from epic/user-dict to epic/dict-breaker 🔬

---

developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
developer/src/kmc-kmn/test/kmw/kmw-messages.tests.ts

In compiler messages, for a long time we have inconsistently used 'command' instead of 'statement' when referring to kmn statements. The kmn language documentation uses 'statement' fairly consistently.

chore(developer): use 'statement' instead of 'command' for messages about kmn statements

---

linux/ibus-keyman/src/engine.c

For some reason when using a LDML keyboard we ended up emitting a keystroke even though Core returned `FALSE` for `emitting_keystroke`. I wasn't able to track down where this happened, but this change seems like an easy way to fix it.
This showed up when debugging why the changes in #13372 didn't work for non-compliant apps.
- The tests can be run on one of these Linux platforms:
- Ubuntu 22.04 Jammy with Gnome Shell and X11
- Ubuntu 24.04 Noble with Gnome Shell and X11
- Ubuntu 24.10 Oracular with Gnome Shell and X11
- Wasta 24.04 with Cinnamon
- Install gedit:
```bash
sudo apt update
sudo apt install gedit
```
- Install Firefox as snap package:
```bash
snap install firefox
```
- Install flatpak
```bash
sudo apt install flatpak
flatpak remote-add --if-not-exists flathub …
```

fix(linux): improve emitting keystrokes

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardWebViewClient.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/docs/engine/KMManager/getPredictionsSuspended.md
android/docs/engine/KMManager/index.md
android/docs/engine/KMManager/setPredictionsSuspended.md
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Fixes #13531 (both bugs)
* A broken image appeared on the lock screen's keyboard.
* Also it seems clear that `KMManager.mayPredictOverride` is set to disable predictions... so it must not be getting unset when the lock screen's conditions are satisfied.
The first bug about the broken image link is fixed with 1 line to SystemKeyboard.java.
```java
BannerController.setHTMLBanner(this, KeyboardType.KEYBOARD_TYPE_SYSTEM);
```
Currently, when the SYSTEM Keyman keyboard is on a password field, the `mayPredictOverride` override is set to true and concurrently disables suggestions for both INAPP Keyman keyboard and SYSTEM Keyman keyboard.
(edited after applying review comments)
This PR refactors undocumented API's so `mayPredictOverride` API calls are independently handled in INAPP and SYSTEM …

fix(android): Handle banner overrides independently when device is locked and unlocked

---

developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts

Suggested by @Nnyny. Give more detail on the semantic version format for keyboard version, as well as details on the limitations to semver imposed by the Keyman toolchain.

chore(developer): improve kmc-ldml 'invalid version' message

---

windows/src/engine/keyman32/hotkeys.cpp
windows/src/engine/keyman32/hotkeys.h
windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp

Fixes: #13440
This refactors the caching of the right modifier key used in the hotkeys option. In the lowlevelhook you couldn't reset the cached value as you could access the static loaded bool value. 
It is now part of the hotkeys class, which is a more logical encapsulation of the logic associated with the hotkeys.
For this test the and right modifier keys will trigger the hotkeys.  It will also test that you can change the option to allow the right modifier key for hotkeys, and it works without requiring a restart of Keyman.
1. Install Keyman
2. Install some keyboard layouts Tamil and IPA SIL
3. Open Configuration and assign hotkeys to Ctrl+G to Tamil and
4. Ctrl+Shift+Ito IPA SIL
5. In Configuration Options tab uncheck the check box for "Use right modifier for hotkeys"
6. Open Notepad …

fix(windows): reload right modifier key option

---

web/src/engine/osk/src/keyboard-layout/oskLayer.ts

Fixes: #13620
Turns out there was actually a final-row pixel offset being applied for the OSK.  I _believe_ this was something originally done for touch-oriented OSKs that ended up applied to all during 17.0's OSK refactoring efforts.
kmwosk.css does define layer-group padding above and below (1 px each) for touch keyboards already.  Furthermore, things look fine when removing this extra 1px offset on the bottom from the last row - there's still a margin below the final row keys that appears to match half the usual gap between rows.  I think we're fine to just drop this minor offset and move on for now.

fix(web): remove extra px offset from last OSK row

---

developer/src/kmc-keyboard-info/src/keyboard-info-compiler-messages.ts
developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts
developer/src/kmc-keyboard-info/test/keyboard-info-compiler-messages.tests.ts
developer/src/kmc-keyboard-info/test/keyboard-info-compiler.tests.ts

This is a workaround for missing 'und' language tag.
`(new Intl.Locale('und')).language` returns `undefined` in V8, as of 31 March 2025. This means we cannot rely on `Intl.Locale` to parse the bcp47 string for us. The implemented workaround is to replace `und` with a known-good language subtag, and then swap it back out in later processing.
Also adds unit test and new warning messages for invalid language tags that were exposed during testing of this.
Fixes: #13610

fix(developer): add special handling for 'und' in kmc-keyboard-info

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift

Adds measures to prevent the state causing #13120, but does not fix it.
TEST_INSTALL_FROM_SEARCH: Using Keyman for iOS, use the in-app keyboard search to install a KMP.  Verify that no errors or error notifications occur.
TEST_INSTALL_FROM_SITE:  Using Keyman for iOS, go to jahorton.github.io and download one of its KMPs.  Open the download with Keyman and verify that no errors or error notifications occur.

change(ios): prevent file erasure during copyWithOverwrite error state

---

ios/engine/KMEI/KeymanEngine/Classes/Manager.swift

Fixes #13120.
Well, fixes the state left by the error, but doesn't prevent it - that part is covered by the predecessor, #13548.
Cross-reference with:
https://github.com/keymanapp/keyman/blob/b77fcfc3da370886faafa79635671851604e92c3/ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift#L286
There are three types of errors here that _could_ be thrown from this method:
https://github.com/keymanapp/keyman/blob/b77fcfc3da370886faafa79635671851604e92c3/ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift#L317
https://github.com/keymanapp/keyman/blob/b77fcfc3da370886faafa79635671851604e92c3/ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift#L342
https://github.com/keymanapp/keyman/blob/b77fcfc3da370886faafa79635671851604e92c3/ …

fix(ios): uninstalls keyboards upon failure to load

---

linux/ibus-keyman/src/keymanutil.c

If the dconf setting for custom keyboards doesn't exist, i.e. we never saved custom keyboards before, the previous code resulted in a warning showing up: `(ibus-engine-keyman:4276): GLib-CRITICAL **: 14:31:16.030: g_hash_table_lookup: assertion 'hash_table != NULL' failed`.
This PR adds a null check before trying to access the custom keyboards hash table and thus removes the warning.

refactor(linux): remove warning if no custom keyboards exist

---

android/KMEA/app/src/main/res/values-land-xhdpi/dimens.xml
android/docs/engine/KMManager/applyKeyboardHeight.md

Fixes #13584
Getting in a crowd-pleaser for @MattGyverLee who reported the default landscape keyboard height on a Pixel 8a device is too small to be usable.
This PR adds dimensions for that pixel density
The Pixel 8a is 430dpi which corresponds to `values-land-xhdpi` (320dpi+ up to 480dpi)
First commit copied values-sw600dp-land as a starting point.
**Reference**
https://developer.android.com/guide/topics/resources/providing-resources.html#table2 (screen pixel density)

fix(android): Add dimensions for 320+dpi phones in landscape

---

common/windows/delphi/packages/PackageInfo.pas
developer/src/common/delphi/packages/Keyman.System.PackageInfoRefreshKeyboards.pas
developer/src/common/web/utils/src/types/kps/kps-file.ts
developer/src/common/web/utils/test/kps/kps-file-reader.tests.ts
developer/src/kmc-generate/src/template/kmn-keyboard/source/keyboard.kps
developer/src/kmc-generate/src/template/ldml-keyboard/source/keyboard.kps
developer/src/kmc-generate/test/fixtures/keyman-keyboard/sample/source/sample.kps
developer/src/kmc-generate/test/fixtures/ldml-keyboard/sample/source/sample.kps
developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas
developer/src/kmconvert/Keyman.Developer.System.LdmlKeyboardProjectTemplate.pas
developer/src/test/auto/package-info/PackageInfoTest.pas
developer/src/tike/child/UfrmPackageEditor.dfm
developer/src/tike/child/UfrmPackageEditor.pas

The fields 'name', 'version', and 'rtl' were defined in the .kps file, but were not actually used by the compiler, as kmc-package reads the metadata from the keyboard file rather than relying on this data, which often is out of date. This led to confusion for keyboard authors, so this change removes that metadata from the package.
The one visible side-effect (apart from the data disappearing from future .kps files) is that the package editor no longer shows this metadata in the Keyboards view (but as it may be out-of-date, this is probably a good thing).
Updated package editor removes these three read-only fields from above/below the 'Files' field:
Fixes: #13576
Fixes: #13593
I ran a full test of recompiling with the change against keyboards repo:
```bash
unset KMC
./build.sh 
mkdir …
```

fix(developer): remove redundant keyboard fields from .kps

---

common/schemas/kps/README.md
common/schemas/kps/kps.xsd
common/windows/delphi/packages/PackageInfo.pas
developer/src/common/web/utils/src/types/kps/kps-file.ts
developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/test/fixtures/example.qaa.sencoten/example.qaa.sencoten.model.kmp.intermediate.json
developer/src/kmc-package/test/fixtures/example.qaa.sencoten/example.qaa.sencoten.model.kmp.json
developer/src/kmc-package/test/fixtures/example.qaa.sencoten/example.qaa.sencoten.model.kmp.zipped.json
developer/src/kmc-package/test/fixtures/withfolders.qaa.sencoten/withfolders.qaa.sencoten.model.kmp.intermediate.json
developer/src/kmc-package/test/fixtures/withfolders.qaa.sencoten/withfolders.qaa.sencoten.model.kmp.zipped.json
developer/src/kmconvert/Keyman.Developer.System.ModelProjectTemplate.pas
developer/src/tike/child/UfrmPackageEditor.dfm
developer/src/tike/child/UfrmPackageEditor.pas

Follows on from the similar changes to `Keyboard` fields in #13600. This deprecates the `RTL` and `Name` fields. `RTL` was never used. `Name` was written but never presented to end users, so effectively irrelevant. `Name` also was present in `File.Description` (already deprecated) for the corresponding model.js _and_ `Info.Name`, so doubly redundant.
Also updates the schema documentation to mark the deprecated fields.
Relates-to: #13600
TEST_COMPILE: Load a lexical model project from the lexical models repository. Open the .kps file, make an inconsequential change, save it, and try and build the entire project. Verify that the project builds. Open the .kps file in a text editor, and verify that the field `Package/LexicalModels/LexicalModel/Name` has been removed.
TEST_NEW_PROJECT: Create …

fix(developer): remove redundant Name and RTL fields from .kps `LexicalModel`

---

common/tools/hextobin/index.ts
common/tools/sourcemap-path-remapper/src/index.ts
core/tools/api-header-extractor/src/index.ts
developer/src/common/web/test-helpers/TestCompilerCallbacks.ts
developer/src/common/web/utils/test/helpers/index.ts
developer/src/kmc-model/tools/create-override-script-regexp.ts
resources/build/version/src/fixupHistory.ts
resources/build/version/src/incrementVersion.ts
resources/build/version/src/index.ts
web/src/engine/keyboard-storage/src/nodeCloudRequester.ts
web/src/engine/predictive-text/wordbreakers/tools/data-compiler/index.ts
web/src/engine/predictive-text/worker-main/src/node/mappedWorker.ts
web/src/tools/building/sourcemap-root/index.ts

This makes it easier for us to enumerate modules that have node dependencies. There may be others I have not yet picked up.
Note: this was pulled out of work on the upcoming kmc-test branch.

chore: use explicit `node:` prefix for node imports

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
mac/Keyman4MacIM/Keyman4MacIM/TextApiCompliance.m

When handling a key down event, reevaluate the compliance of the text input client if a change in context has been detected (such as due to a mouse event or a page down or pressing an arrow key). This addresses problems where one part of an application behaves in a compliant way and another does not.
Also, further check compliance by comparing the context read from the text input client to the most recently inserted text. This helps to find problems with applications that support the selection API correctly but do not accurately read the text at the corresponding location.
Fixes: #13465
**TEST_IPA_MSWORD**: 
1. Open Microsoft Word on the Mac and create a new document
1. Switch to the IPA(SIL) keyboard 
1. Type <kbd>u</kbd><kbd><</kbd>
1. Verify that the output is ʊ …

fix(mac): reevaluate API compliance for each change in context

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustKeyboardHeightActivity.java

Follows #13635 and fixes #13634
* Adds back button and handler to the "Adjust Keyboard Height" menu
* `setWidth()` removed to center the title
**Setup** - Install the PR build of Keyman for Android on device/emulator
* **TEST_BACK_BUTTON** - Verifies back button exits "Adjust Keyboard Height" menu
1. Launch Keyman for Android and dismiss Get Started menu
2. From Keyman Settings --> Adjust keyboard height
3. Verify the "Adjust keyboard height" titlebar has back button on the left
4. Drag the keyboard to adjust the keyboard height and let go
5. Observe the keyboard height 
6. On the title bar, hit the back button --> and exit back to the Keyman app
7. Verify the keyboard height now matches what was set in the menu

fix(android): Add back button to "Adjust Keyboard Height "menu

---

linux/ibus-keyman/src/engine.c

This change fixes a bug introduced in #13372. Before that `engine.c` determined if keys are handled or not. For keys that we didn't handle we returned `FALSE`. However, that didn't allow the Core to adjust the context where necessary, so #13372 moved that to Core. However, this caused `ibus_keyman_engine_process_key_event` to return `TRUE` even if we didn't handle the key. Instead we called `ibus_engine_forward_key_event` with the non-handled key. This worked in most applications, but not in the Text Editor.
This change now does no longer call `ibus_engine_forward_key_event` for compliant apps but instead returns `FALSE` from `ibus_keyman_engine_process_key_event` for unhandled keys, allowing the app to see and act on the key event.
An 'unhandled' key here is a key that doesn't match a …

fix(linux): allow unhandled keys to pass through to compliant apps

---

developer/src/common/web/utils/src/compiler-interfaces.ts
developer/src/common/web/utils/src/developer-utils-messages.ts
developer/src/common/web/utils/src/index.ts
developer/src/common/web/utils/src/types/kps/kps-file-reader.ts
developer/src/common/web/utils/src/types/ldml-keyboard/ldml-keyboard-xml-reader.ts
developer/src/common/web/utils/test/kps/kps-file-reader.tests.ts
developer/src/common/web/utils/test/ldml/ldml-keyboard-xml-reader.tests.ts
developer/src/kmc-package/src/compiler/package-compiler-messages.ts
developer/src/kmc/src/messages/messageNamespaces.ts

Renames common-messages.ts to developer-utils-messages.ts. This was split from /common/web/types, but the messages module retained the old name, which was confusing (two modules with same name).
This is more groundwork coming out of the upcoming kmc-test epic.

refactor(developer): rename developer/web/utils/common-messages.ts to developer-utils-messages.ts

---

ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift

Fixes: #13629
Fixes: #11953
Fixes: #6387
This change makes sure that upon app re-entry, the keyboard only displays when the main view will be the active view.  If the app had been in a menu or in the picker, the keyboard will no longer show up on top of it.  Additionally, if the app is re-entered to directly install a KMP from a file, the keyboard will not overlay the package installer.
The core of the problem is that upon app re-entry, the WebView reloads the keyboard, which in turns triggers the `keyboardLoaded` internal notification.  That notification did not check if the main view was the currently-visible view or not, and would always display the keyboard.
TEST_STANDARD_USE:  Use the test build from this PR and verify that the keyboard is displayed and hidden at normal times.
1. …

fix(ios): prevent re-display of keyboard when re-entering app to its menus

---

ios/engine/KMEI/KeymanEngine/Classes/SettingsViewController.swift

Fixes: #13443
Slide-dismissal of the settings menu, and of the keyboard-height setting view in particular, should apply changes after dismissal... not only after backing out via navigation buttons.
Certain aspects of the iOS API didn't make it easy, though.  After some searching, I found that "presentation controllers" and related can be leveraged to ensure we can detect Settings menu dismissal.  With that detection in place, we can use the same method that's been working fine for us when backing out of Settings via button.  This also ensures the keyboard will immediately display after dismissal, too!
TEST_REPRO_13443:  Use this PR's test artifact and verify that slide-dismissal of the keyboard-height adjuster automatically displays the keyboard at the newly-set size.
1. Open Keyman …

fix(ios): slide dismissal of keyboard-height adjuster will properly resize the keyboard

---

linux/keyman-config/keyman_config/keyboard_details.py

Fixes: #13647 
Fixes: KEYMAN-LINUX-80

fix(linux): fix crash if kmp doesn't have name field

---

web/src/engine/predictive-text/worker-main/src/lmlayer.ts

Previously logging an error resulted in two Sentry issues to be created. This change now combines the log message and the error into one call to `console.error`, thus resulting in only one Sentry issue being created.

chore(web): improve error logging in predictive-text worker message validation

---

android/KMEA/app/src/main/res/values-hdpi/dimens.xml
android/KMEA/app/src/main/res/values-land-hdpi/dimens.xml
android/KMEA/app/src/main/res/values-land/dimens.xml
android/docs/engine/KMManager/applyKeyboardHeight.md

Addresses mdpi (160dpi using the baseline `values`) and hdpi (240 dpi using `values-hdpi`) devices for #13609
Trying to squeeze into a table for side by side comparison. Dimensions should be the same - GH just scaling the previews.
no change - shown for comparison
Made keyboard a little taller and banner smaller to be usable
| Before | New (latin ) | New (Khmer) | New ( Lao ) |
|-----------|------------------------------|---------------------|----------------|
------
| Before | New (latin ) | New (Khmer) | New ( Lao ) |
|-----------|------------------------------|---------------------|----------------|
| ![hdpi-portait](https://github.com/user-attachments/assets/ba317aed-4247-4fea-9227-c4f210acda0a) | ![hdpi-portrait-adjusted](https://github.com/user-attachments/assets/545f558d-7bc7-4793-b …

fix(android): Adjust keyboard and banner heights for mdpi and hdpi devices

---

android/KMEA/app/src/main/res/values-xhdpi/dimens.xml
android/docs/engine/KMManager/applyKeyboardHeight.md

Follows #13651 and #13592 in addressing #13609 for xhdpi (320+ dpi) devices in portrait orientation
Currently, the dimensions fall back to this in portrait
(landscape already set in #13592)
| latin | khmer | lao |
|--------|------------|-------|
| ![adjusted-portrait](https://github.com/user-attachments/assets/36a655c5-8524-4272-8bc6-42fc07ff3ea9) | ![adjusted-portrait-khmer](https://github.com/user-attachments/assets/6c77e2b4-2c1c-4c93-90c7-ba2ce8b9cb2d) | ![adjusted-portrait-lao](https://github.com/user-attachments/assets/162bd5f9-32bc-4c19-8233-5f1a5795b841) |

fix(android): adjust keyboard and banner height for xhdpi portrait

---

android/KMEA/app/src/main/res/values-sw600dp-land/dimens.xml
android/docs/engine/KMManager/applyKeyboardHeight.md

Follows #13655 in addressing #13609 for sw600 (7" tablet) devices adjusting keyboard and banner height for landscape orientation
| latin | khmer| lao |
|-------|-----------|-------|
| ![default-portrait](https://github.com/user-attachments/assets/5fddfed8-474a-49db-83db-68b9a6cf7276) | ![default-portrait-khmer](https://github.com/user-attachments/assets/d22cc73a-58cb-4794-b72a-c8965396811a) | ![default-portrait-lao](https://github.com/user-attachments/assets/73116416-0cf5-4541-a329-93cce18bd3d1) |
-----
**Original**
| latin | khmer| lao |
|-------|-----------|-------|
| ![default-land](https://github.com/user-attachments/assets/48ebc05d-7978-4af8-aee0-b9f57d87f05e) | ![default-land-khmer](https://github.com/user-attachments/assets/7e1b3399-f69e-4d70-bea5-5bbc4c7d1f80) | …

fix(android): Adjust keyboard and banner height for 7" tablet landscape

---

android/KMEA/app/src/main/res/values-sw720dp-land/dimens.xml
android/docs/engine/KMManager/applyKeyboardHeight.md

Follows #13657 in addressing #13609 for sw720 (10" tablet) devices adjusting keyboard height for landscape orientation
| latin | khmer| lao |
|-------|-----------|-------|
| ![default-portrait](https://github.com/user-attachments/assets/2ae1d33e-7cbc-459d-9674-acae2a8218ff) | ![defualt-portrait-khmer](https://github.com/user-attachments/assets/ff45166a-09c2-4252-955a-4765a944f341) | ![default-portrait-lao](https://github.com/user-attachments/assets/afb331dc-69f5-4538-8210-7570d6143cda) |
-----
**Original**
| latin | khmer| lao |
|-------|-----------|-------|
| ![default-land](https://github.com/user-attachments/assets/f5a7c8f5-3650-49e9-b326-20ba7f146472) | ![default-land-khmer](https://github.com/user-attachments/assets/846bdf28-aa87-4ae5-a7c0-566511dfce32) | …

fix(android): Adjust keyboard height for 10" tablet landscape

---

web/src/engine/keyboard/src/keyboards/keyboard.ts
web/src/engine/osk/src/visualKeyboard.ts

I've tested locally and verified no ill effects result from these changes.

chore(web): remove dead methods regarding keyboard state

---

ios/engine/KMEI/KeymanEngine/Classes/SettingsViewController.swift

I happened to notice, while polishing up #13631, that our keyboard-height might not take effect properly if it were being used in certain setups.  Those setups don't occur within our Keyman app, but we can't guarantee that no uses will occur for Keyman Engine for iPhone and iPad as used by third-parties.

fix(ios): ensure keyboard height is set when engine settings view is used in a NavigationController

---

android/docs/engine/KMManager/applyKeyboardHeight.md

Follows #13668 and relates to #13609
No change to portrait or landscape keyboard heights for xxxhdpi devices, so just documenting in the table
Using Nexus 6 (obsolete) emulator to generate the screenshots
| latin | khmer | lao |
|--------|-----------|------|
| ![default portrait](https://github.com/user-attachments/assets/b2e08ec6-55fb-4322-a039-e1f1a809cf22) | ![default-portrait-khmer](https://github.com/user-attachments/assets/7311221a-b6c3-4a38-9a9b-e25a0b435b4d) | ![default-portrait-lao](https://github.com/user-attachments/assets/f313ed99-da28-4d32-866a-650e8cdaf54c) |
| latin | khmer| lao |
|--------|-----------|------|
| ![default-land](https://github.com/user-attachments/assets/536d0ad1-9bca-41ee-8255-814d2ceff2fc) | ![default-land-khmer](https://github.com/user-attachments/assets/a …

docs(android): Document default keyboard height for xxxhdpi devices

---

ios/engine/KMEI/KeymanEngine/Classes/SettingsViewController.swift

This tweaks the recently-merged https://github.com/keymanapp/keyman/pull/13631, which accidentally introduced a bug in which _any_ downward swiping motion on the Settings view would always dismiss it, even should the user attempt to cancel dismissal.
Turns out the `presentationControllerWillDismiss` method triggers on _any_ downward motion, rather than immediately before a confirmed dismissal takes effect (like the `viewWillAppear` method for view lifecycles).  We want `presentationControllerDidDismiss`, which only triggers on (though, after) actual dismissal.
Our `settingsDismissed` method contains a line that has the side-effect of forcing dismissal while enforcing effects we do want; we shouldn't call it until we're sure that we're dismissing Settings.
TEST_CANCELED_SWIPE:  Use this …

fix(ios): allow swipe-dismissal of Settings to be cancelled

---

ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift

Fixes: #12590
If we're already showing the package-installer for a keyboard the user found via search... then we clearly downloaded it successfully.  Why double-notify?
There's actually a good reason _not_ to double-notify - it turns out that #12590 itself was due to our usage of a TabBarController outside the prescribed safe use cases.  We're actually fine most of the time... but it seems the tab area doesn't play nicely with a NavigationController toolbar, which is what displays download + update notifications.  Rather than find a way to force that to work, it's simpler to just... not show the toolbar, **ever**, when the package installer is displayed.
See write-up in this comment for more details: https://github.com/keymanapp/keyman/issues/12590#issuecomment-2785200199 …

fix(ios): do not show notification for downloaded keyboard when showing its installer

---

android/KMEA/app/src/main/java/com/keyman/engine/util/Connection.java

Fixes KEYMAN-ANDROID-51P
Similar to #13353 where `SocketTimeoutExceptions` were filtered out.
Client with sporadic network connectivity could cause `UnknownHostException` errors. This PR filters those exceptions to the info level. (`originalUrl` are valid keyboard downloads from downloads.keyman.com)

fix(android): Downgrade UnknownHostException error to info

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/docs/engine/KMManager/setHTMLBanner.md
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Follows the in-app keyboard pattern of refreshing banner theme when the keyboard is shown
Fixes: #13693
**Setup**
* Install the PR build of Keyman for Android on device/emulator
* **TEST_BANNER_REFRESHES** - Verifies banner theme displays after keyboard install
1. Accept all the Android permission requests for storage.
2. Open the Keyman app.
3. On the "Get Started" dialog.
* Check the "Enable Keyman as system-wide keyboard" box.
* Check the "Set the keyboard as the default keyboard" box.
3. Navigate to the settings page and then select "Installed Languages"
4. Add a "EuroLatin" keyboard for an "Albanian" keyboard by clicking the "+" button.
5. Return to the Keyman app.
6. Observed that the Albanian keyman appeared and the keyman banner appeared.
7. Observed that the back line appeared on …

fix(android): Fix system  keyboard banner on reload

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeyboardScaleMap.swift

This PR updates the database that KeymanEngine uses to determine what size of keyboard to use for each device.  This should ensure the default size for the keyboard matches the system keyboard's dimensions.
Data was recorded via the KeyboardCalibrator tool after its update in #13689.

chore(ios): update keyboard-size data for current iOS devices

---

ios/engine/KMEI/KeymanEngine/Classes/ResourceDownloadStatusToolbar.swift

Fixes: #12589
Fixes: #13688
It appears that in iOS 15.0, Apple seems to have enacted behavior that will cause a toolbar to go translucent/transparent in certain scenarios - such as when it would cover up the bottom of a fully-scrolled view.  This has been triggering on our keyboard-search page, directly causing the behavior seen in #12589.
Reference: https://stackoverflow.com/a/71985231
It appears fixing this thoroughly _also_ addresses #13688, so... yay for "two birds, one stone"!
TEST_KEYBOARDS_LIST_OVERLAY:  Using the iOS build artifact for this PR, verify that update notifications always display properly and consistently on the "installed languages" list.
1. Install the Keyman app.
2. Install at least 10 keyboards, or enough to fill the initial view for the "Installed Languages" list. …

fix(ios): ensure update notification does not go translucent/transparent

---

ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/KeyboardSwitcherViewController.swift

Fixes: #13699
This change ensures that swipe-dismissal of the in-app keyboard picker is properly handled, resummoning the keyboard once it closes.  The underlying issue was much the same as for #13443.
TEST_PICKER_DISMISSAL: Verify that down-swipe dismissal of the in-app keyboard picker automatically redisplays the keyboard.  (There may be a delay of a second or two due to iOS animations.)

fix(ios): resummon keyboard when keyboard picker is dismissed

---

resources/build/builder.inc.sh

Without the export we had the case where a web test relied on `KEYMAN_ROOT` to get the path, but it was undefined. I have no idea why this suddenly showed up with changes that just renamed a file and a class (#13710), but exporting it fixes it.

fix(common): export `KEYMAN_ROOT` so that it is available in subprocesses 🎼

---

android/build.sh

late CI requirement change from @mcdurdin who requested:
> we use `RELEASE_OEM` to control whether or not the OEM folder is touched at all -- build, clean, publish, everything
This updates the Android builder scripts to verify that
`RELEASE_OEM` is set
`RELEASE_OEM_FIRSTVOICES` is `true`
before adding `:fv` as a child target
Devs and CI would need the above set to build FirstVoices Android.
Prior art from how core/build.sh defines archtargets
https://github.com/keymanapp/keyman/blob/4a0238c16c2206d727456bba0ffc99eb65edb1e4/core/build.sh#L23-L72

fix(android): Require RELEASE_OEM env vars to build FirstVoices Android

---

linux/keyman-system-service/build.sh
linux/keyman-system-service/tests/meson.build
linux/keyman-system-service/tests/testfixture.cpp

Previously keyman-system-service didn't have any unit tests. With the gcov/lcov versions available for Ubuntu 24.04 Noble this suddenly caused a failure when trying to generate the test coverage report, although it worked fine with older versions.
This change adds a do-nothing unit test stub for keyman-system-service. This allows to generate the coverage reporting with Ubuntu 24.04 Noble.

chore(linux): add a stub unit test to allow successful coverage reporting

---

linux/keyman-system-service/build.sh
linux/keyman-system-service/tests/meson.build
linux/keyman-system-service/tests/testfixture.cpp

Previously keyman-system-service didn't have any unit tests. With the gcov/lcov versions available for Ubuntu 24.04 Noble this suddenly caused a failure when trying to generate the test coverage report, although it worked fine with older versions.
This change adds a do-nothing unit test stub for keyman-system-service. This allows to generate the coverage reporting with Ubuntu 24.04 Noble.
Cherry-pick-of: #13740

chore(linux): add a stub unit test to allow successful coverage reporting 🏠🍒

---

.github/labeler.yml
resources/scopes/scopes.json

Note: m:predictive-text and m:developer-ide mark a change where we have some modules with fuzzy boundaries and where it may not be easy to automatically determine all changes by pathname. I am not altogether comfortable with these so we may iterate a bit further yet.

chore: update labels for v19

---

.github/workflows/crowdin.yml

Part of maintenance sprint
This is the action that automatically updates the Crowdin project as new strings get added to the master branch

chore(common): Update dependencies in crowdin GitHub action

---

.github/labeler.yml
.github/multi-labeler.yml
resources/scopes/scopes.json

renaming m:predictive-text to web/predictive-text/ and m:developer-ide to developer/ide/ (matching other module names).

chore: additional tweaks to scopes/labels

---

.github/multi-labeler.yml
CONTRIBUTING.md
resources/scopes/commit-types.json

During the "M3: Maintenance Sprints" session of the April 2025 planning conference we discussed that we'd rename the `chore` GH label to `maint`.
However, this change doesn't remove the existing `chore` label because that is also used for merge commits.

chore(common): rename `chore` GH label to `maint`

---

web/build.sh

While dependency build infrastructure ensures that the web-utils module is built, it does nothing to run its existing unit tests.  Those appear to have been disconnected when the module was relocated - an issue this PR rectifies.

fix(web): reconnect unit tests for low-level web utility classes/methods 🧶 

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java

Currently, Toast notifications displayed to the user are also sent as errors to Sentry. (#7189)
User attempts to install a keyboard package where no languages are associated with the keyboard
This PR changes the Toast notification to an alert dialog that doesn't send the error (really warning) to Sentry.
Keyman already displays a similar alert dialog if the keyboard package doesn't contain a touch layout keyboard.
This way we don't clutter Sentry with noise.
Fixes: #13782
Fixes: KEYMAN-ANDROID-251
Will :cherries: pick to stable-18.0
**Setup** - On an Android device/emulator, install the PR build of Keyman for Android. Also download a test keyboard [ge.kmp](https://darcywong00.github.io/examples/invalid/ge.kmp) which has no languages associated with the keyboard.
* **TEST_NO_LANGUAGES** - …

fix(android): Change Alert Dialog instead of Toast if package missing languages

---

docs/CODEOWNERS

These remain commented out, but status.keyman.com will parse all lines starting with `#/<path>/` in order to find the platform owners.

maint(common): remove platform advocates from CODEOWNERS

---

linux/build.sh
linux/keyman-config/tests/bcp47tag_tests.py
linux/keyman-config/tests/canonical_language_code_utils_tests.py
linux/keyman-config/tests/custom_keyboards_tests.py
linux/keyman-config/tests/dbus_util_tests.py
linux/keyman-config/tests/dconf_util_tests.py
linux/keyman-config/tests/get_kmp_tests.py
linux/keyman-config/tests/gnome_keyboards_util_tests.py
linux/keyman-config/tests/gsettings_tests.py
linux/keyman-config/tests/handle_install_tests.py
linux/keyman-config/tests/ibus_util_tests.py
linux/keyman-config/tests/install_kmp_tests.py
linux/keyman-config/tests/kvk2ldml_tests.py
linux/keyman-config/tests/lang_tags_map_tests.py
linux/keyman-config/tests/package_install_completion_tests.py
linux/keyman-config/tests/uninstall_kmp_tests.py

This changes the shebang at the top of the file to allow use Python from a virtual environment instead of hard-coding the path. This might not be strictly necessary the way we run the tests, but reduces confusion and doesn't hurt.

chore(common): allow to run tests in virtual environment

---

android/KMAPro/build.sh
android/KMEA/build.sh
android/Samples/KMSample1/build.sh
android/Samples/KMSample2/build.sh
android/Tests/KeyboardHarness/build.sh
android/build.sh
oem/firstvoices/android/build.sh

Fixes #12640
* ~Remove builder flag `--ci`~ Deprecated `--ci` build option to remove in 20.0
* Use `builder_is_ci_build` check instead.

chore(android): Use `builder_is_ci_build` rather than `--ci` flag

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java

:cherries: pick of #13786 to stable-18.0
Currently, Toast notifications displayed to the user are also sent as errors to Sentry. (#7189)
User attempts to install a keyboard package where no languages are associated with the keyboard
This PR changes the Toast notification to an alert dialog that doesn't send the error (really warning) to Sentry.
Keyman already displays a similar alert dialog if the keyboard package doesn't contain a touch layout keyboard.
This way we don't clutter Sentry with noise.
Fixes: #13782
Fixes: KEYMAN-ANDROID-251
**Setup** - On an Android device/emulator, install the PR build of Keyman for Android. Also download a test keyboard [ge.kmp](https://darcywong00.github.io/examples/invalid/ge.kmp) which has no languages associated with the keyboard.
* …

fix(android): Use Alert Dialog if keyboard pkg missing languages 🏠

---

docs/builder.md

Noted the deps flags were missing from documentation when responding to #13814, and thought it a good idea to move builder.md into /docs at the same time so that it is with the rest of our repo documentation.
Test-bot: skip

docs: add `--deps` flags and move builder.md into /docs

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeyboardScaleMap.swift

Fixes: #13769
This restores some of the older entries deleted by #13697.  At the time, I'd tried to set up Simulator targets to get current settings for most of these devices, but Xcode stated "no simulator runtimes available" for them - and without that, I couldn't recalibrate... and incorrectly inferred that they were no longer supported.  (I'd even downloaded iOS 15 Simulator runtimes!)
On a related note, it seems that with minimum support set at 15.6, Xcode won't offer a 15.5 Simulator runtime as an option.  Seems kind of obvious now, in hindsight.  Sadly, it doesn't offer _any_ iOS 15.6 runtime whatsoever - at least not with Xcode 16.2.  So, I simply _can't_ use my usual routine to update our settings the devices being restored here.  But, at least I can restore the old entries we …

fix(ios): restore keyboard-scale settings for older, still-supported iOS devices

---

core/tests/unit/kmx/keyboards.kpj.in
core/tests/unit/kmx/meson.build
core/tests/unit/ldml/keyboards/keyboards.kpj.in
core/tests/unit/ldml/keyboards/meson.build

Build all the .kmx files used for kmn and ldml unit tests in batch rather than one at a time. The ldml-test-data builds remain unbatched for now (and are visibly slow!).
Fixes: #13495

maint(core): batch build kmx in tests for performance

---

mac/build.sh

The mac build started to lose rewritten info.plist metadata in #11444 when tests were run after the build completed. When the tests were run, xcodebuild would rewrite the info.plist, losing the rewritten metadata.
This patch updates the build script to write the metadata after unit tests (if any) are run.
Fixes: https://github.com/keymanapp/keyman/issues/13791
Test-bot: skip

fix(mac): add version metadata after building tests

---

.eslintrc.cjs

In #13788, I aimed to address a TODO about adding `eslint:recommended` as a lint setting, but missed that the following line would override it instantly.
After some testing, I realized _why_ we hadn't done it before - the `eslint:recommended` setting is designed for raw JS, not TS.  For example, it doesn't like TS type definition for function parameters or function type definitions.  We should probably just drop `eslint:recommended` against TS files.
Test-bot: skip

maint(common): remove `eslint:recommended` configuration for .ts

---

resources/shellHelperFunctions.sh

Relates to #11595 that I needed to make progress on #12373
Update write_download_info() to be cross-platform (currently used by iOS build)
https://github.com/keymanapp/keyman/blob/73dcf200859c6692591ad856da1d0da2af86a34d/ios/tools/prepRelease.sh#L131-L132
* Handle stat flags based on `BUILDER_OS` (macOS differs from win/Linux)
* Change from md5 (macOS only) to md5sum (all)
Test-bot: skip

maint(common): Update write_download_info() to be cross-platform

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeyboardScaleMap.swift

Fixes: #13769
Fixes: KEYMAN-IOS-JC
Fixes: KEYMAN-IOS-JG
Fixes: KEYMAN-IOS-JH
Fixes: KEYMAN-IOS-JJ
Fixes: KEYMAN-IOS-JY
Fixes: KEYMAN-IOS-JS

fix(ios): restore keyboard-scale settings for older, still-supported iOS devices 🍒  🏠

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeyboardScaleMap.swift

Cherry-pick-of: #13806
Warnings about known devices without predefined keyboard-scale map entries will be limited to once per startup of the app and/or app-extension.
Test-bot: skip
See-also: #13769

change(ios): limit reports about devices without predefined scaling entries 🍒  🏠

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeyboardScaleMap.swift

Relates to #13769.
Warnings about known devices without predefined keyboard-scale map entries will be limited to once per startup of the app and/or app-extension.
Test-bot: skip

change(ios): limit reports about devices without predefined scaling entries

---

web/src/engine/common/web-utils/.eslintrc.cjs
web/src/engine/common/web-utils/build.sh
web/src/engine/common/web-utils/src/deepCopy.ts
web/src/engine/common/web-utils/src/priority-queue.ts
web/src/engine/common/web-utils/src/version.ts

Now that the PR linking web-utils to the main web/ build (#13714) is merged in, we can start connecting it to linting as well.  This change does not include kmwstring.ts for linting, though, as that has an existing rework.  A separate PR will be added as a followup to the refactor PR (#13726) to handle its final version.

change(web): lint engine/common/web-utils 🧶 

---

common/web/types/src/lexical-model-types.ts
common/web/types/tests/lexical-model-types.tests.ts
web/src/engine/predictive-text/templates/src/tokenization.ts
web/src/engine/predictive-text/templates/src/trie-model.ts
web/src/engine/predictive-text/types/message.d.ts
web/src/engine/predictive-text/worker-main/src/lmlayer.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/distance-modeler.ts
web/src/engine/predictive-text/worker-thread/src/main/model-compositor.ts

Fixes: #12046
It was only ever an alias (for `string`!) for its intended use, with actual `USVString` typing being unavailable in the browser.

change(web): replace USVString with string in predictive-text engine

---

web/src/engine/predictive-text/worker-main/unit_tests/test.sh

I just realized that #13807 basically eliminates the need for worker-main's `test:libraries` action.  Between that and old BrowserStack-oriented code, worker-main's test script can be considerably simplified.

maint(web): simplify worker-main test.sh

---

web/src/engine/osk/src/lengthStyle.ts
web/src/engine/osk/src/views/oskView.ts

Fixes: #13766
It seems that at some point, Developer has been compiling raw "12" values in the touch-layout JSON as a numeric 12 for the fontsize field.  This clearly happened for the [inuktitut_pirurvik keyboard](https://github.com/keymanapp/keyboards/blob/37829949e6883cf39ee0cd13e1b2939f3f5a54bd/release/i/inuktitut_pirurvik/source/inuktitut_pirurvik.keyman-touch-layout#L512); we should also inspect [urdu_phonetic](https://github.com/keymanapp/keyboards/blob/37829949e6883cf39ee0cd13e1b2939f3f5a54bd/release/u/urdu_phonetic/source/urdu_phonetic.keyman-touch-layout#L647), which has the same raw "12".
See the version hosted on s.keyman.com: https://s.keyman.com/keyboard/inuktitut_pirurvik/1.4/inuktitut_pirurvik-1.4.js - it clearly has `12`, not `"12"`, for that field.
This change ensures …

fix(web): add robustness for bad touch-layout fontsize specs

---

web/src/engine/osk/src/lengthStyle.ts

Forgot about having developed #13774 and #13787 in parallel.  I just merged #13774 earlier without having merged `master`'s changes in first, which caused a linter issue:  what was once possible to declare with `const` no longer is, and thus needs to be changed from `const` (from the linter work) back to `let`.
Test-bot: skip

fix(web): fix var declaration affected by linter strictness + length-style fix

---

oem/firstvoices/keyboards.csv

keymanapp/keyboards#3474 rebuilt inuktitut_pirurvik keyboard to version 1.4.1.
This addresses part of keymanapp/keyboards#3478 in updating keyboards.csv with the new inuktitut_pirurvik version.
The file is still used by FirstVoices for iOS.
Will need to :cherries: pick to stable-18.0
Test-bot: skip

chore(ios): Update inuktitut_pirurvik to 1.4.1

---

oem/firstvoices/keyboards.csv

:cherries: pick of #13840 to stable-18.0
This addresses part of keymanapp/keyboards#3478 in updating keyboards.csv with the new inuktitut_pirurvik version.
The file is still used by FirstVoices for iOS.
Test-bot: skip

chore(ios): Update inuktitut_pirurvik to 1.4.1 🏠

---

linux/keyman-config/run-tests.sh
resources/tools/check-markdown/build.sh

This change overrides a check added in Ubuntu 24.04+ that prevents mixing Python packages installed through apt and through pip. This allows to install the necessary Python package for TC which isn't available as Debian package. This change allows builds on Ubuntu 24.04 based TC agents.

chore(common): override check when running on TC

---

resources/build/test/debug-deps/test.sh
resources/build/test/test.sh
resources/builder.inc.sh

Fixes: #11106
This is performed by checking our `$VERSION_ENVIRONMENT` and seeing if it reports "local".  If this is the case, and `--debug` isn't already set, it will be automatically added as a selected option in builder-scripts.
Example run:
Note how both child builds and dependency builds also receive the automatically-set `--debug` flag from the top-level script.
So long as we don't mess up our scripting toolchain in a manner that makes CI agents look "local", this should be enough to accomplish the goals of the base issue.
------
There may be a little more work needed here - such as determining the best way to handle builder tests when run locally:
```
[resources/build/test] Local build environment detected:  setting --debug
[resources/build/test] test.sh parameters: <clean:app …
```

maint(common): automatically set --debug option for local-environment builder-script uses

---

web/docs/internal/keystroke-lifecycle.md
web/docs/internal/keystroke-processing.md

Fixes: #12732
This represents a first-pass attempt to provide a keystroke-lifecycle doc for Keyman Engine for Web, making this our first such doc.  
We may want to refine this further, as this may naturally be used as a reference when developing the other docs when the time comes.  Some refinements have already happened thanks to code-review suggestions - the lifecycle "sequence diagram" in particular arose from those interactions.

docs(web): add a Web engine keystroke lifecycle internal doc

---

common/web/types/build.sh
common/windows/delphi/general/DUnitX.Loggers.TeamCity.pas
resources/shellHelperFunctions.sh
web/src/test/manual/web/regression-tests/test-builder.js

This change makes use of the new builder script function to detect if the script is running on TeamCity. Also use the
`TEAMCITY_GIT_PATH` environment consistently to check if we're running on TC.
Test-bot: skip

maint(common): use function to detect if running on TC

---

windows/src/desktop/kmshell/main/Keyman.System.DownloadUpdate.pas
windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas

This adds keyboard URL which will identify the name of the keyboard that has failed to download.
It will do the same for the keyman update URL. This will give insight into if it is certain keyboards that are failing to download.
It also add checks to see if it\the system is online before attempting downloads. Adding breadcrumbs for this also.

fix(windows): add breadcrumb to download failures

---

mac/build.sh

The mac build started to lose rewritten info.plist metadata in #11444 when tests were run after the build completed. When the tests were run, xcodebuild would rewrite the info.plist, losing the rewritten metadata.
This patch updates the build script to write the metadata after unit tests (if any) are run.
Fixes: #13791
Cherry-pick-of: #13818
Test-bot: skip

fix(mac): add version metadata after building tests 🍒 🏠 

---

resources/build/test/test.sh
resources/builder.inc.sh

If we're not running on TC we should output the start/end messages as headings unless it's a child build. This was the previous behavior before we added support for TC blocks.
Test-bot: skip

maint(common): output start/end messages if not running on TC

---

docs/builder.md
resources/builder.inc.sh

This adds the two additional functions `builder_is_running_on_docker`, and `builder_is_running_on_gha` to be able to detect if the build is running in a CI or CI-like container environment.
Test-bot: skip

maint(common): add two more functions to detect if running on CI 🌇

---

resources/docker-images/run.sh

PR #13861 missed the fact that docker-images' `run.sh` script also contains code that got re-added during a faulty merge. This change cleans this up.
Test-bot: skip

maint(common): remove obsolete code from docker-images `run.sh`

---

linux/scripts/upload-to-debian.sh

With this change we wait two seconds after creating the PR before trying to get the number of the PR so that GitHub can catch up. Previously recently it wasn't able to get the PR#.
Also adjust the commit message and use the new header for skipping tests.
Test-bot: skip

maint(linux): improve getting PR# in `upload-to-debian.sh`

---

.github/workflows/deb-packaging.yml

This allows to build packages for Keyman 18 without having to backport the change that renames `VERSION` → `KEYMAN_VERSION`.
Test-bot: skip

fix(linux): fallback to `VERSION` if `KEYMAN_VERSION` isn't set during package build

---

docs/builder.md
resources/build/build-utils-ci.inc.sh
resources/builder.inc.sh

This change moves the `build_is_ci_*` functions from `resources/build/build-utils-ci.inc.sh` → `resources/builder.inc.sh`.
It also adds documentation for them.
Fixes: #13885 
Fixes: #13886
Test-bot: skip

maint(common): move and document `builder_is_ci_*` functions

---

android/KMAPro/build-play-store-notes.inc.sh

PR #13854 missed (at least) one place when renaming the variables from `TIER` to `KEYMAN_TIER`. This change fixes the release builds for Android.
Follow-up-of: #13854
Fixes: #13896
Test-bot: skip

maint(android): use new variable name `KEYMAN_TIER`

---

mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMPackageReader.m
mac/Keyman4MacIM/Keyman4MacIM/en.lproj/Localizable.strings
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMXFile.m

When reading the kmp.inf file, if the [Info] section is not available, then check for a [PackageInfo] section which should contain the same required fields.
Also, if no package name can be found in the kmp.inf, then fail gracefully with a placeholder for the package name.
Fixes: #13718
- **TEST_SANSKRIT_UNICODE**: all rows of configuration window are visible after installing keyboard
1. install the build for this PR
1. install the Sanskrit Unicode keyboard
1. confirm that you can type with the keyboard
1. open the Keyman Configuration window
1. confirm that the Sanskrit Unicode keyboard appears in the keyboard list
1. close the Configuration window and confirm that Keyman still operates as expected

fix(mac): handle PackageInfo section in kmp.inf file

---

LICENSE.md
linux/debian/control
linux/debian/copyright
linux/debian/ibus-keyman.manpages
linux/debian/keyman-system-service.manpages
linux/debian/source/lintian-overrides
linux/ibus-keyman/COPYING
linux/ibus-keyman/man/ibus-engine-keyman.8
linux/keyman-config/COPYING
linux/keyman-system-service/.gitignore
linux/keyman-system-service/man/keyman-system-service.8
linux/keyman-system-service/meson.build
linux/keyman-system-service/resources/systemd-keyman.service
linux/scripts/dist.sh

This fixes Lintian warnings and other comments from the Debian review of the package. It also removes unnecessary files from the source package.
Note: this PR uses `Expat` instead of `MIT` in the `debian/license` file since that is the term that Debian uses and that the Debian tools output. It doesn't really matter since the term serves only as a key in the `license` file that links the files to the full text of the license further down in the `license` file.
Fixes: #13905
Test-bot: skip

maint(linux): address comments from Debian package review

---

linux/scripts/launchpad.sh

This adds the next Ubuntu version, 25.10 Questing Quokka, to the launchpad package builds.
Test-bot: skip

maint(linux): add Questing to launchpad package builds

---

linux/scripts/deb-packaging.sh

Until now we accidentally included three files `linux/keyman_build_deps*` in the source package that get created during installing dependencies. This change deletes the files after installing the dependencies before we create the source package.
Test-bot: skip

maint(linux): remove temporary files created during dependency installation

---

web/src/engine/js-processor/src/jsKeyboardProcessor.ts

Preparation for epic/web-core, clarify which members of `JSKeyboardProcessor` are private and which will need equivalent implementations in `CoreKeyboardProcessor`.
Note: some of the publicly accessed members are not immediately obvious, because they are accessed via interfaces declared in other modules (for example `baseLayout` is referenced in `KeyboardState` type in hardwareEventKeyboard.ts).
Test-bot: skip

chore(web): add accessor annotations for `JSKeyboardProcessor` 🎼

---

web/src/engine/main/src/keymanEngineBase.ts

This change renames the generic type variables in `KeymanEngineBase` to make it clearer that they are generic types rather than the actual types.
Test-bot: skip

refactor(web): rename generic type variables 🎼

---

web/src/engine/osk/src/views/oskView.ts
web/src/engine/osk/src/visualKeyboard.ts

Fixes: #13908
Fixes: KEYMAN-WEB-RK
Cherry-pick-of: #13959
Fun fact:  `Number('')` returns 0, not NaN!  I thought it would do the latter in #13838, which is what led to the issue this PR addresses.
TEST_THAI_KEDMANEE: Using Keyman for Android, install and load the Thai Kedmanee Basic keyboard and verify that no errors result.

fix(web): empty layout fontSize property should default to 1em 🍒  🏠

---

.github/actions/build-binary-packages/action.yml

This updates the `gha-ubuntu-packaging` dependency which itself updates some dependencies and so hopefully eliminatese some confusing warnings.
Test-bot: skip

maint(linux): update gha-ubuntu-packaging dependency

---

linux/keyman-system-service/src/OrderedOutputDevice.h

fix(linux): use correct header guard define in OrderedOutputDevice.h

---

web/src/engine/predictive-text/worker-main/unit_tests/test.sh
web/src/engine/predictive-text/worker-thread/build.sh
web/test.sh

This is a followup to the recent #13827, which automatically adds --debug to local-environment builds.  For web/ test scripts involving browser-based scripts, that same flag had been used to enable an _inspectable_ test mode that doesn't auto-return, which doesn't match the semantics of --debug for build configurations.  As test scripts still use the common builder patterns, this "overloading" of the --debug option is now causing issues.
To rectify this, those scripts now have their --debug option renamed to --inspect, allowing them to be optionally turned on, but not automatically enabled.
Test-bot: skip

fix(web): inspectable test-script mode should not be auto-enabled in local-env tests

---

package-lock.json

All changes in this PR were automatically generated by a simple run of `npm audit fix` (no `--force` option) run from the repository's root folder.
This addresses a number of the Dependabot alerts currently visible at https://github.com/keymanapp/keyman/security/dependabot, though not all.  There are certainly a few extra changes needed to remedy all the audit-detected issues.
Original audit:
```
29 vulnerabilities (3 low, 13 moderate, 13 high)
```
Remaining:
```
13 vulnerabilities (7 moderate, 6 high)
```
Some developer-server dependencies are updated by this, as are some `octokit` modules.  `npm audit fix` deliberately didn't update some of the other `octokit` modules, though.
TEST_DEVELOPER_SERVER:  Using Keyman Developer on a Windows machine, verify that the keyboard test page …

maint(common): evaluate and apply npm audit fix (without forced changes)

---

package-lock.json
resources/build/version/package.json
resources/build/version/src/fixupHistory.ts
resources/build/version/src/index.ts
resources/build/version/src/reportHistory.ts

A large portion of the remaining `npm audit` / Dependabot security alerts after #13897 and #13899 were not automatically fixable due to breaking changes in the `@actions/github` package.  After a little work, I think I've got something that'll help resolve the issues there.
Original (after #13899):
```
10 vulnerabilities (6 moderate, 4 high)
```
Remaining:
```
3 vulnerabilities (1 moderate, 2 high)
```

maint: update @actions/github + @octokit references

---

package-lock.json
package.json

The `fast-json-parser` package is needed by `ajv-cli`, which is used during common/web/types/build.sh configure.
Found this approach via a comment on https://github.com/ajv-validator/ajv-cli/issues/237.
Remaining `npm audit` issues after this fix:
```
@sentry/browser  <7.119.1
Severity: moderate
Sentry SDK Prototype Pollution gadget in JavaScript SDKs - https://github.com/advisories/GHSA-593m-55hh-j8gv
fix available via `npm audit fix --force`
Will install @sentry/browser@9.17.0, which is a breaking change
node_modules/@sentry/browser
1 moderate severity vulnerability
```
... and updating Sentry (for web/) is potentially something far more involved.
Test-bot: skip

maint(common): update fast-json-patch to ^3.1.1

---

web/src/engine/osk/src/views/oskView.ts
web/src/engine/osk/src/visualKeyboard.ts

Fixes: #13908
Fixes: KEYMAN-WEB-RK
Fun fact:  `Number('')` returns 0, not NaN!  I thought it would do the latter in #13838, which is what led to the issue this PR addresses.  (A plain '' for font-size style has the same effect as '1em'.)
TEST_THAI_KEDMANEE:  Using Keyman for Android, install and load the Thai Kedmanee Basic keyboard and verify that no errors result.

fix(web): empty layout fontSize property should default to 1em

---

mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMPackageReader.m
mac/Keyman4MacIM/Keyman4MacIM/en.lproj/Localizable.strings
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMXFile.m

When reading the kmp.inf file, if the [Info] section is not available, then check for a [PackageInfo] section which should contain the same required fields.
Also, if no package name can be found in the kmp.inf, then fail gracefully with a placeholder for the package name.
Cherry-pick-of: #13876 
Fixes: #13718
- **TEST_SANSKRIT_UNICODE**: all rows of configuration window are visible after installing keyboard
1. install the build for this PR
1. install the Sanskrit Unicode keyboard
1. confirm that Keyman has not crashed and typing with the keyboard causes characters to be output (no need to confirm that the output matches the keyboard documentation)
1. open the Keyman Configuration window
1. confirm that the Sanskrit Unicode keyboard appears in the keyboard list and Keyman has not crashed

fix(mac): handle PackageInfo section in kmp.inf file 🍒 🏠 

---

core/build.sh
core/commands.inc.sh
linux/build.sh
linux/ibus-keyman/build.sh
linux/keyman-system-service/build.sh

By default we add the `--werror` option to meson builds. This might cause problems when compiling with a different compiler, so this option adds the `--no-werror` option to our build scripts. This enables integrators to compile with other compiler versions. 
Fixes: #13970
Test-bot: skip

maint(linux): add `--no-werror` option to not report warnings as errors

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/KMEA/app/src/main/java/com/keyman/engine/util/KMLog.java

To facilitate code investigation and issue repro attempts, we should log the engine's current keyboard, language code, lexical model, and installed keyboard count when reporting errors.
As this adds Sentry logging, I needed a reliable error with inspectable logs for development; example reports with the new logging can be found for the issue noted below.
Fixes: KEYMAN-ANDROID-71V
Example report, as visible within Sentry:
| Additional Data                |                         |
|---------                           | -------             |
| installedKeyboardCount  | 5                      |
| keyboardId                       | khmer_angkor |
| languageCode                 | km                    |
| modelId                            | sil.km.gcc        |
<details><summary>Screenshot …

feat(android): log active keyboard, model IDs with reported errors 

---

common/windows/delphi/tools/test-klog/test_klog.dpr
windows/src/desktop/kmshell/main/Keyman.System.DownloadUpdate.pas
windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas

The state machine method [TState] for Exiting a state was overriding the Delphi system Exit. This meant that any intended early returns inside the TState method were just calling the TState.Exit method [or the overridden method for states that override the method.]   Then continuing execution within the method.
The `Enter` method has been updated to `EnterState` for symmetry.
Note: The downloading process would have also been affected by the Exit override. In the case when a second process was attempted to be downloaded when the mutex failed it would have still started a new download process. It may be what is occurring for #13831. My local testing doesn't do this though.
https://github.com/keymanapp/keyman/blob/2b53497046261d4fe23dfe0952d9f5ab6d3efcef/windows/src/desktop/kmshell/main/Keym …

fix(windows): rename Enter and Exit methods TState

---

windows/src/desktop/kmshell/main/Keyman.System.DownloadUpdate.pas
windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas

Be more precise by matching the file name in the cache.json file with the downloaded file in the cache folder. This will mean any older installation versions that were not correctly cleaned up will not be installed.
fixes #13831
This test needs there to be a newer build available on the server when doing check for updates
The aim of this test is that when there a two versions of keyman in the UpdateCache one the current version and one a newer version. The newer version should be installed.
1. Install the Keyman from this PR
2. Copy the Keyman executable from this PR to `C:\Users\UserName\AppData\Local\Keyman\UpdateCache`
3. Open Keyman Configuration and go to the updated tab
4. Press the "check for updates" button.
5. If an update for Keyman is found you can proceed with this test, …

fix(windows): use json file name against cache folder

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/KMEA/app/src/main/java/com/keyman/engine/util/KMLog.java

Cherry-pick-of: https://github.com/keymanapp/keyman/pull/13983
To facilitate code investigation and issue repro attempts, we should log the engine's current keyboard, language code, and model when reporting errors.
Test-bot: skip

feat(android): log active keyboard, model IDs with reported errors 🍒  🏠

---

linux/keyman-system-service/resources/com.keyman.SystemService1.service.basu
linux/keyman-system-service/resources/meson.build.in
linux/keyman-system-service/resources/systemd-keyman.service.in

This makes the path in `com.keyman.SystemService1.service` configurable when using basu (e.g. Gentoo Linux).
Cherry-pick-of: #13980
Test-bot: skip

fix(linux): configurable path in `.service` file when using basu 🏠🍒

---

core/build.sh
core/commands.inc.sh
linux/build.sh
linux/ibus-keyman/build.sh
linux/keyman-system-service/build.sh

By default we add the `--werror` option to meson builds. This might cause problems when compiling with a different compiler, so this option adds the `--no-werror` option to our build scripts. This enables integrators to compile with other compiler versions. 
Fixes: #13970
Cherry-pick-of: #13988
Test-bot: skip

maint(linux): add `--no-werror` option to not report warnings as errors 🏠🍒

---

resources/teamcity/includes/tc-actions.inc.sh
resources/teamcity/keyman-linux-release.sh
resources/teamcity/keyman-linux-test-integration.sh
resources/teamcity/keyman-linux-test.sh

In addition to all the other dependencies we also need quilt installed in order to be able to create a source package. Additionally renamed a function to clarify its purpose.
Test-bot: skip

maint(linux): add quilt to release build configuration

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java

Display a Toast notification if network is unavailable before downloading from the keyboard page
This should cut down on `UnknownHostException` errors
Fixes: #13977
Fixes: KEYMAN-ANDROID-420
**Setup** - Install PR build of Keyman for Android on emulator/device
* **TEST_NETWORK_CHECK** - Verifies network check when downloading keyboards
1. On the Android device, verify network access (wifi or cell data) is enabled (e.g. Airplane mode off)
2. Launch Keyman for Android and dismiss the "Getting Started" menu
3. From Keyman settings --> Install keyboard or dictionary --> Install from keyman.com
4. Search for "khmer_angkor" , and install the keyboard
5. Verify the keyboard package downloads and installs
6. From Keyman settings --> Install keyboard or dictionary --> Install from keyman.com
7. …

fix(android): Check network access before trying to download keyboard

---

developer/src/server/package.json
package-lock.json

Looks like dependabot did not cleanly upgrade multer (#13982). Possibly a bug with workspaces? Removed from package.json, npm install, re-added, npm install to fix the issue.
Apologies for the re-test on this! (I think @Meng-Heng did the last test?)
**TEST_SERVER_UPLOAD:** Open Keyman Developer, start Keyman Developer Server, open http://localhost:8008/, and in the Hamburger menu, select Upload file. Attempt to upload a keyboard .js. Verify that the keyboard and/or package uploads successfully, and is accessible in the Keyboard dropdown.
See-also: #13982

maint(developer): update multer to v2.0.0

---

common/windows/delphi/tools/test-klog/test_klog.dpr
windows/src/desktop/kmshell/main/Keyman.System.DownloadUpdate.pas
windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas

Cherry-Pick to stable-18.0
#13831 
and 
#13920

fix(windows): cherry use json file name against cache folder and ename Enter and Exit methods for TState Object 🍒  🏠

---

windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas

If the configuration is set to not automatically downloadupdates and then from the configuration tab the check for update button is clicked. If an update is found the upgrade statemachine is now in state UpdateAvailable. If a updated keyman installer file is then downloaded direclty from keyman.com. Then installed by running the self installer then on firstrun the statemachine will still be in the UpdateState. This is should be fine, but it will be good to breadcrumb incase we start to see some crashes on firstrun with this interaction.
The setup executable could modify the registry state directly but it is cleaner to have the one master of the registry state value.
Fixes: #13771
Not sure the testers can do this test due to the sentry requirement.
1. Download …

fix(windows): only breadcrumb unexpected state on first run

---

windows/src/desktop/kmshell/main/initprog.pas

Before we only skipped the handlekmshell checks if we were in installing state and the FMode was related to upgrading or installing the keyboard packages. However like as seen in #13984 if an upgrade is started from the standalone installer the statemachine state could be in UpdateAvailable instead of the Installing State. Due to this limitation we will skip handlekmshell when in these FModes in any state.
Fixes: #13770
The aims of these tests is regression tests ensuring the installation of keyboards and keyman is still working correctly. 
1. Install the Keyman from this PR
2. Install an old version of a Keyman Keyboard like euro latin keyboard  PR 3.0.0 [sil_euro_latin.zip](https://github.com/user-attachments/files/18587198/sil_euro_latin.zip)
3. Open Keyman Configuration and go to the …

fix(windows): skip sending handle kmshell events to upgrade state machine  for keyboard install modes

---

windows/src/desktop/kmshell/main/Keyman.System.RemoteUpdateCheck.pas
windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas
windows/src/desktop/kmshell/main/initprog.pas

The sending of the value of the string FErrorMessage to sentry was incorrect use of quotes. It was just sending the literal string `FErrorMessage`. This has been updated. Also the pattern was never used in the module `TUpdateStateMachine` instead breadcrumbs and error messages are sent as they occur. Therefore removed it from `TUpdateStateMachine`.  
Also there was an unused variable in initprog.pas that has been removed. 
[KEYMAN-WINDOWS-4VR](https://keyman.sentry.io/issues/6227588380/events/7bd438cf47e44a0b605ac94a4c0d0d7e/?environment=beta&project=5983518&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=next-event&stream_index=0)

fix(windows): fix sentry error message reporting

---

windows/src/desktop/kmshell/main/initprog.pas

Cherry-pick-of: #13989
Test-bot: skip

fix(windows): skip sending handle kmshell events to upgrade state machine for keyboard install modes 🍒  🏠

---

web/src/app/ui/kmwuibutton.ts
web/src/app/ui/kmwuifloat.ts
web/src/app/ui/kmwuitoggle.ts
web/src/app/ui/kmwuitoolbar.ts

Cherry-pick of changes in #12291. Addresses [code review comment](https://github.com/keymanapp/keyman/pull/12291/files/130e697d40d60c9f5a7767f5c574772548ac8cea#r1976381710) made in in #12291. 
This marks async methods in UI components with the `async` keyword. Also explicitly mark them as being `private`.
Test-bot: skip

chore(web): mark async methods in UI components

---

resources/build/trigger-definitions.inc.sh

This are a little early but good to have in place. Per release process wiki, this should have been done at time of 18.0 stable release but was missed (by me).
Test-bot: skip

maint: add stable-19.0 triggers

---

common/test/resources/package.json
common/web/keyman-version/package.json
core/include/ldml/package.json
core/tools/api-header-extractor/package.json
developer/src/tike/xml/app/package.json
resources/gosh/package.json
resources/tools/check-markdown/package.json

Also removes './' from front of gosh.js to address another npm cleanup (from `npm pkg fix`).
Fixes: #13833
Test-bot: skip

maint: add empty 'scripts' tag to package.json to silence warning

---

linux/keyman-config/build.sh
linux/keyman-config/keyman_config/version.py.in
linux/scripts/reconf.sh

This fixes the version numbers in `km-config` which broke with #13854. This also fixes opening the download page in `km-config` because that uses a version number in the URL. 
Fixes: #14031
Follow-up-of: #13854
**TEST_VERSION**: Run `km-config --version` in a terminal.  Verify that the displayed version number looks similar to 
`km-config version 19.0.47-alpha (package version 19.0.47-1~sil1~noble)`
**TEST_DOWNLOAD**:
- Open the "Configuration" window using the "km-config" command in the terminal.
- Open the "Download Keyman Keyboards" dialog by clicking the "Download Keyboard" button.
- Verify that the search page appears in the "Download Keyman Keyboards" dialog..

fix(linux): fix version variable references in kmconfig

---

resources/build/_builder_nvm.sh

Previously, if we had to install a new node version, we activated it in the same subshell as the installation. This had the effect that `NVM_BIN` was set to the new version only in the subshell, but otherwise it still had the wrong value. This caused build failures. Subsequent builds would succeed because the node version was now available.
This change fixes things by using an explicit `if` instead of the construct with parens which opened another subshell. 
Fixes: #14056
Test-bot: skip

fix(common): properly use newly installed node version

---

developer/src/kmc-ldml/src/compiler/compiler.ts

- there's no public API for validate()
- kmc calls `.run()`
- but `.run()` doesn't call validate() and then compile(), it only calls `compile()`
- so it needs to call compile() with postValidation=true
Fixes: #14067

fix(developer): ensure that kmc doesn't skip validate phase of kmc-ldml 🙀 

---

developer/src/kmc-ldml/src/compiler/compiler.ts

- .run() doesn't call validate() and then compile(), so it needs to call compile() with postValidation=true
Fixes: #14067
(cherry picked from commit c70464e23f59505b409989e7d46349a7a47d08a8) and #14068
- TEST_COMPILE: Download [developer/src/kmc-ldml/test/fixtures/sections/strs/invalid-illegal.xml](https://github.com/keymanapp/keyman/blob/master/developer/src/kmc-ldml/test/fixtures/sections/strs/invalid-illegal.xml).  Open Keyman Developer. (May need to make a new LDML project.)  Open `invalid-illegal.xml` as a file.  Choose Compile Keyboard.   Compilation should FAIL with something like `error KM00025: File contains 5 illegal character(s), including Illegal (U+FDD0)`

fix(developer): ldml: make sure .run() calls compile() for validation 🍒  🏠

---

linux/scripts/package-build.inc.sh

Since we have write access to the directory we don't need `sudo` for removing the temporary dependency files if we pass `-f` to `rm`.
Cherry-pick-of: commit 4f27f6e256995e4513c700eba9fa7c7b3cec0a33
Cherry-pick-of: #14085
Test-bot: skip

maint(linux): `sudo` not required for removing temporary files 🍒

---

.github/actions/build-binary-packages/action.yml

Version 2.0 of gha-ubuntu-packaging retries 5 times to install the packages, so hopefully this will improve the reliability. 
Test-bot: skip

maint(linux): update to new version of gha-ubuntu-packaging

---

web/src/engine/sentry-manager/src/index.ts

This change marks the functions of `KeymanSentryManager` as public or private, depending on whether or not they are used outside of the module. 
Test-bot: skip

refactor(web): clarify API of KeymanSentryManager

---

common/web/types/src/kmx/kmx-plus/element-string.ts
common/web/types/src/ldml-keyboard/unicodeset-parser-api.ts
developer/src/common/web/utils/src/compiler-interfaces.ts
developer/src/common/web/utils/src/index.ts
developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts

- Push CompilerMessageObjectSpec up into developer-utils
- add mx() to the unicodeset functions in kmc-kmn
- add an optional context object to unicodeset 
Fixes: #14091

feat(developer): ldml: update errors for unparseable reorder

---

resources/teamcity/includes/tc-helpers.inc.sh
resources/teamcity/web/keyman-web-release.sh
resources/teamcity/web/keyman-web-test.sh
resources/teamcity/web/zip-and-upload-artifacts.ps1

This matches the existing TC configuration as closely as possible. It also puts the scripts in `resources/teamcity/web`, but doesn't relocate the Linux scripts ~~until we decide where things should go~~.
Test-bot: skip

maint(web): move TC configuration for Web to script 🔗

---

resources/teamcity/web/keyman-web-release.sh
resources/teamcity/web/zip-and-upload-artifacts.ps1

This fixes the Keyman for Web release builds - the script expects to be run from `${KEYMANROOT}/web`.
Test-bot: skip

maint(web): fix working directory for zipping artifacts for Web release

---

web/src/app/browser/src/configuration.ts
web/src/app/browser/src/defaultBrowserRules.ts
web/src/app/webview/src/contextManager.ts
web/src/engine/attachment/src/outputTargetForElement.ts
web/src/engine/interfaces/src/prediction/languageProcessor.interface.ts
web/src/engine/interfaces/src/prediction/predictionContext.ts
web/src/engine/js-processor/src/jsKeyboardInterface.ts
web/src/engine/js-processor/src/jsKeyboardProcessor.ts
web/src/engine/js-processor/src/outputTargetBase.ts
web/src/engine/keyboard/src/defaultRules.ts
web/src/engine/keyboard/src/index.ts
web/src/engine/keyboard/src/keyboards/jsKeyboard.ts
web/src/engine/keyboard/src/outputTargetInterface.ts
web/src/engine/main/src/contextManagerBase.ts
web/src/engine/main/src/engineConfiguration.ts
web/src/engine/main/src/headless/inputProcessor.ts
web/src/engine/main/src/headless/languageProcessor.ts
web/src/tools/testing/recorder-core/src/index.ts
web/src/tools/testing/recorder-core/src/nodeProctor.ts
web/src/tools/testing/recorder-core/src/proctor.ts
web/src/tools/testing/recorder/browserProctor.ts

refactor(web): rename `OutputTarget` interface → `OutputTargetInterface` 🎼

---

web/src/engine/keyboard/src/index.ts
web/src/engine/keyboard/src/keyboards/jsKeyboard.ts
web/src/engine/keyboard/src/keyboards/stateKeyMap.ts

refactor(web): make `StateKeyMap` a named export 🎼

---

common/test/keyboards/build.sh
common/test/keyboards/zip-excludes

Fixes: #14135
Updates the test keyboards build.sh script to use the refactored zip.inc.sh
Test-bot: skip

fix(common): Use zip.inc.sh for common test keyboards

---

resources/build/run-required-test-builds.sh

The `grep` available on macOS doesn't have the `--perl-regexp` option, so the changes introduced in #14047 caused a regression. This change directly makes use of Perl which is available on macOS.
Fixes: #14146
Follow-up-of: #14047
Test-bot: skip

maint(resources): fix regression on mac triggering builds

---

resources/teamcity/web/keyman-web-release.sh
resources/teamcity/web/zip-and-upload-artifacts.ps1

Previously rsync used some TC variables. Now with the build step being a script the TC variables are no longer accessible from the script, so we add new arguments to the build script and then use these when calling rsync. A similar changer was already made previously for the developer release build.
Follow-up-of: #14049
Related: #14059
Test-bot: skip

maint(web): add some more arguments for web release build script

---

windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas

There will be no `firstrun` for kmshell.exe if it is a keyboard only install. We can therefore return to the idle state in the current process.
**For this test to work we need the latest alpha to the same decimal version number as this PR.**
1. Download Keyman attached the PR
2. Open the Keyman Configuration dialog.
3. 3. Install the euro latin keyboard attached to this PR 3.0.0 [sil_euro_latin.zip](https://github.com/user-attachments/files/18587198/sil_euro_latin.zip)
4. Go to the update tab and press the check for updates button. The table should populate with the new eurolatin keyboard version and the keyman version. 
5. Open Regedit <kbd>Win</kbd><kbd>R</kbd> type regedit 
6. In the Regedit window verify the `update state` has advanced to either `usUpdateAvailable` ->  `usDownloading` …

fix(windows): keyboard only install return idle

---

.github/workflows/auto-merge-keyman-server-pr.yml
resources/build/ci/pull-requests.inc.sh
resources/build/increment-version.sh

Prevents PRs from keyman-server from being merged unless they already have the 'automerge' label. This supports the upcoming epic-master-merge infrastructure, where we would like to automatically approve the PRs but allow maintainers to merge when ready.
We cannot specify required status checks at this point, because we don't necessarily know which status checks will be required for a given PR. A future improvement would be to define a new status check which verifies that all the expected builds for a given PR have passed, and then make that into a required status check for all master,beta,stable-x.y,epic/ branches. This status check would need to be updated automatically whenever another status check completes. Probably should be implemented as a GHA.
In the future, we could move to …

maint(resources): only automatically merge keyman-server PRs with automerge label

---

resources/teamcity/developer/download-symbol-server-index.ps1
resources/teamcity/developer/publish-new-symbols.ps1
resources/teamcity/developer/publish-to-downloads-keyman-com.ps1
resources/teamcity/web/zip-and-upload-artifacts.ps1

This changes variable references in the powershell scripts to use braces (`${FOO}` instead of `$FOO`). This solves the problem where powershell considers the colon in the rsync command as being part of a variable. This should fix release builds for Web and Developer.
Also commented some unused variables.
Follow-up-of: #14167,#14168
Test-bot: skip

maint(developer,web): use braces for variables in powershell scripts

---

resources/teamcity/developer/download-symbol-server-index.ps1
resources/teamcity/developer/publish-new-symbols.ps1
resources/teamcity/developer/publish-to-downloads-keyman-com.ps1
resources/teamcity/web/zip-and-upload-artifacts.ps1

However, we have to use double quotes inside of the string as well so that it gets treated as a command with parameters instead of a single command with spaces.
Follow-up-of: #14168
Test-bot: skip

maint(developer,web): use double quotes inside `--rsync-path` again

---

windows/src/desktop/kmshell/main/Keyman.System.RemoteUpdateCheck.pas
windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas

Basing of [fix/windows/cherry-pick/not-downloaded-after-3-attempts](https://github.com/keymanapp/keyman/tree/fix/windows/cherry-pick/not-downloaded-after-3-attempts)
As it makes it easy to review that it is the same cherry-pick as #14123
Test-bot: skip
Cherry-pick-of: #14123

fix(windows): add values wucUpdateAvailable and wucNotChecked to TRemoteUpdateCheckResult enum 🍒 🏠

---

resources/teamcity/developer/developer-actions.inc.sh
resources/teamcity/includes/tc-actions.inc.sh
resources/teamcity/includes/tc-helpers.inc.sh
resources/teamcity/includes/tc-linux.inc.sh
resources/teamcity/web/web-actions.inc.sh

This change prefixes functions with `ba_` that are intended to be run on a Linux build agent. That should make it easier to distinguish them from functions that deal with building Keyman for Linux.
Test-bot: skip

refactor(linux): rename linux agent specific functions

---

web/ci.sh

This fixes a deployment problem which seems have been around since 17.0. We also have to deploy the `web/build/publish` folder which contains all the files necessary to load and run the test keyboards.
The fix can only be tested after a release build has happened and the files have been deployed.
Fixes: #14234
Test-bot: skip

fix(web): deploy `web/build/publish` folder

---

web/ci.sh

The build agents have the env variable `SEVENZ_HOME` set instead of `SEVEN_Z_HOME`. That name is also used elsewhere, so this PR changes it to the more widespread name.
Fixes: #14242
Follow-up-of: #14225
Test-bot: skip

fix(web): change env variable name

---

web/ci.sh

This fixes a deployment problem which seems have been around since 17.0. We also have to deploy the `web/build/publish` folder which contains all the files necessary to load and run the test keyboards.
The fix can only be tested after a release build has happened and the files have been deployed.
Fixes: #14234
Cherry-pick-of: #14237
Test-bot: skip

fix(web): deploy `web/build/publish` folder 🍒 🏠

---

resources/teamcity/android/android-actions.inc.sh
resources/teamcity/android/keyman-android-release.sh
resources/teamcity/android/keyman-android-test-samples.sh
resources/teamcity/android/keyman-android-test.sh
resources/teamcity/includes/tc-helpers.inc.sh

There is one difference compared to the old build configurations on TC: previously we had a separate build step to build and test FV that would run only if environment variables were set.
This change combines building and testing FV with building the engine and the app. If the environment variables are set we pass an additional parameter to the TC build script.
Fixes: #14188
Build-bot: release android
Test-bot: skip

maint(android): add TC build scripts for Keyman for Android 🪶

---

resources/teamcity/macos/keyman-macos-release.sh

Skipping builds since the changed code only affects TC release builds.
Test-bot: skip

maint(mac): rename `_do_publish` function to `do_publish` to fix release build

---

resources/teamcity/ios/keyman-ios-release.sh

We did already cd into that directory a few lines above.
Test-bot: skip

maint(ios): remove extra `cd` command from ios release builds

---

resources/teamcity/android/android-actions.inc.sh
resources/teamcity/developer/developer-actions.inc.sh
resources/teamcity/includes/tc-actions.inc.sh
resources/teamcity/includes/tc-download-info.inc.sh
resources/teamcity/includes/tc-helpers.inc.sh
resources/teamcity/includes/tc-linux.inc.sh
resources/teamcity/includes/tc-mac.inc.sh
resources/teamcity/includes/tc-windows.inc.sh
resources/teamcity/ios/ios-actions.inc.sh
resources/teamcity/macos/macos-actions.inc.sh
resources/teamcity/web/web-actions.inc.sh
resources/teamcity/windows/windows-actions.inc.sh

Include files are not directly executable, so it doesn't make sense to have the shebang line. However, shellcheck needs to know what shell we use. Turns out there is a shellcheck line that we can add instead of the shebang line.
Follow-up-of: #14253
Test-bot: skip

refactor(resources): replace shebang for TC include files

---

resources/build/run-required-test-builds.sh

If the PR only contains files that we ignore, we previously failed to finish the trigger build. This PR fixes the problem.
The problem can be observed in #14271 which only changed a file in `resources/teamcity/common` which gets ignored in `find_platform_changes`.
Test-bot: skip

fix(common): fix triggering builds if no builds to start

---

resources/teamcity/android/android-actions.inc.sh
resources/teamcity/android/keyman-android-release.sh
resources/teamcity/android/keyman-android-test.sh

This will fix the Android release builds. Previously we did a debug build but then tried to copy files from the release build folder.
The original build config passed `--release` when doing a release build, which lost when moving to build scripts.
Fixes: #14302
Build-bot: release android
Test-bot: skip

maint(android): use `--release` for release builds

---

resources/teamcity/android/keyman-android-release.sh
resources/teamcity/developer/keyman-developer-release.sh
resources/teamcity/linux/keyman-linux-release.sh
resources/teamcity/web/keyman-web-release.sh
resources/teamcity/windows/keyman-windows-release.sh

This fixes the release builds.
Follow-up-of: #14270
Test-bot: skip

maint(common): remove include of deleted `tc-download-info.inc.sh`

---

developer/docs/help/context/package-editor.md

A short explanation of the Description field is added to the Details section of the page.
I think adding these will avoid user-test-missing messages.
Test-bot: skip

docs(developer): explanation of the Description field added in Details section.

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeyboardScaleMap.swift

fix(ios): restore keyboard scale map for iPad Air 2

---

resources/teamcity/android/keyman-android-release.sh

PR #14264 removed the `--ci` parameter from Android builds, but forgot to remove it for release builds. This PR fixes this.
Follow-up-of: #14264
Test-bot: skip

maint(android): remove `--ci` parameter from Android release builds 🩹

---

resources/shellHelperFunctions.sh

The .download_info files use the platform `win` instead of `windows`. This PR changes this, and also renames the `_verify_project` function to `_verify_platform` to better match what it's checking. Fixes Windows release builds.
Follow-up-of: #14270 
Test-bot: skip

maint(windows): fix platform name for Windows 🩹

---

resources/teamcity/developer/keyman-developer-release.sh
resources/teamcity/windows/keyman-windows-release.sh

Only touches release build files, so skipping PR test builds.
Fixes: #14202
Test-bot: skip

maint(windows): replace hardcoded `symbols` paths with parameters

---

web/src/engine/predictive-text/templates/src/common.ts
web/src/engine/predictive-text/templates/tests/common.tests.js
web/src/engine/predictive-text/worker-thread/src/tests/mocha/cases/edit-distance/context-tracker.js

While working on some epic/autocorrect work, I found that some unit tests got notably harder to write due to the current behavior of `buildMergedTransform`, which always emits a value for `deleteRight` even if the input transforms lack a value for it.
As some upcoming epic/autocorrect work is likely to split constructed transforms to better help track changes to the context and delayed reversion metadata (see #12884), it's best to change the behavior and only write out a `deleteRight` value when it's actually merited.
Test-bot: skip

change(web): do not set deleteRight when merging Transforms without it 🚂

---

linux/debian/control

Until Ubuntu 24.10/Debian 12 `python3-pkg-resources` got installed as a dependency of `python3-numpy`. With numpy version 2 (Ubuntu >= 25.04/ Debian >= 13) this is no longer the case, so we have to explicitly add it as a runtime dependency. It might be a bug that this dependency doesn't get automatically added, but this workaround will do.
Fixes: #14349
Fixes: KEYMAN-LINUX-82
Please run the tests on Ubuntu 25.04 Plucky.
**TEST_DEP**: 
- Reboot
- verify that you can open `km-config`

fix(linux): add `python3-pkg-resources` as explicit dependency

---

resources/build/test/zip.inc.tests.sh
resources/build/zip.inc.sh

Previously `add_zip_files` didn't work if the zip filename was not specified as first parameter. This change allows it to come after flags.
This will fix web release and other builds.
Test-bot: skip

maint(common): fix `add_zip_files` if flags come before zip filename

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.ts
web/src/engine/predictive-text/worker-thread/src/tests/mocha/cases/edit-distance/context-tracker.js

This adds one new method within the predictive-text worker space:  `isSubstitutionAlignable`.  The method is designed to report whether or not two words are "related enough" to consider as an appropriate word-level "substitution" when matching the incoming context against previously-seen contexts - a process useful for facilitating delayed reversions, among other things.
This work arose to address needs for future components that will be useful in resolving #12884.  Note that the new method isn't actually _integrated_ into the worker yet, though; this is to keep this PR's changes more reasonably-reviewable.

feat(web): add `isSubstitutionAlignable` to assist validating context matches after edits 🚂

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.ts
web/src/engine/predictive-text/worker-thread/src/tests/mocha/cases/edit-distance/context-tracker.js

Following from #14364, this PR integrates the new method with the main predictive-text context-tracking code, significantly reworking the `attemptMatchContext` method in the process.  While further refactoring of the latter method is planned, this step allows us to verify that the new methods integrate properly with the main codebase in their current form, before higher-level changes are added to the pile.
This also comes with the benefit of simplifying `attemptMatchContext` _significantly_ - large parts of its code were refactored into `attemptTokenizedAlignment`, and the new logic patterns are generally more straightforward to parse and understand.
For reviewers:  note that this PR leverages the following unit tests specifically: …

refactor(web): rework `attemptMatchContext` to use new `attemptTokenizedAlignment` method 🚂

---

resources/builder.inc.sh

`resources/builder.inc.sh` is designed to be used on other non-builder scripts, so not all variables can be assumed to be set. This change fixes some "unbound variable" errors.
Test-bot: skip

maint(common): fix standalone use of `resources/builder.inc.sh`

---

resources/teamcity/includes/tc-windows.inc.sh

A recent change (#14324) consolidated (and thus renamed) some functions that were in several places. A PR that got created earlier but merged later (#14267) added new functionality that still used the old function names. This lead to release build failures on Windows and Developer.
This change fixes the names of the called functions.
Fixes: #14412
Follow-up-of: #14324
Follow-up-of: #14267
Test-bot: skip

maint(windows): fix calls of renamed functions

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

:cherries: pick of #14472 to stable-18.0
Relates to #14455 with @chrisvire's code suggestions. 
> I needed to move the last 4 lines of code above the call to initKeyboard. This seems like a legitimate bug (order of initialization) in KMEA.
This way the keyboard sizes are retrieved from preferences before the inapp and system keyboards are initialized.
I think this contributed to intermittent reports from FirstVoices about a squished keyboard (but couldn't get a repro).
The keyboard harness test app seems to be a good repro, so I will include for user testing
**Setup** - Install the PR builds of Keyman for Android and the KeyboardHarness test apps on the Android device/emulator (I suggest API 34)
* **TEST_KEYMAN** - Verifies default keyboard heights work
1. Launch Keyman for Android and …

fix(android): cherry-pick getting default sizes before initializing keyboard 🍒 🏠

---

android/Tests/KeyboardHarness/app/build.gradle
android/Tests/KeyboardHarness/build.gradle
android/Tests/keycode/app/build.gradle
android/Tests/keycode/app/src/test/java/com/keyman/android/tests/keycode/ExampleInstrumentedTest.java
android/Tests/keycode/app/src/test/java/com/keyman/android/tests/keycode/ExampleUnitTest.java
android/Tests/keycode/build.gradle
android/Tests/keycode/gradle.properties

Related to #13858
The keycode test app is a standalone test project for displaying key codes. (Does not use Keyman Engine for Android).
Hence, this project doesn't really get maintained when updating project dependencies.
THis PR updates the project's dependencies so it will compile in Android Studio. No test-bot artifacts since the project doesn't get attached.
Part of the cleanup is also updating the stubbed tests to use RobolectricTestRunner (conforms to our other Android projects)
Test-bot: skip

chore(android): Update keycode test app dependencies

---

package-lock.json

```
brace-expansion  1.0.0 - 1.1.11 || 2.0.0 - 2.0.1
brace-expansion Regular Expression Denial of Service vulnerability - https://github.com/advisories/GHSA-v6h2-p8h4-qcjw
brace-expansion Regular Expression Denial of Service vulnerability - https://github.com/advisories/GHSA-v6h2-p8h4-qcjw
fix available via `npm audit fix`
node_modules/brace-expansion
node_modules/mocha/node_modules/brace-expansion
form-data  4.0.0 - 4.0.3
Severity: critical
form-data uses unsafe random function in form-data for choosing boundary - https://github.com/advisories/GHSA-fjxv-7rqg-78g4
fix available via `npm audit fix`
node_modules/form-data
2 vulnerabilities (1 low, 1 critical)
```

maint(common): update npm modules brace-expansion to 1.1.12, form-data to 4.0.4

---

.github/workflows/auto-merge-keyman-server-pr.yml
resources/build/increment-version.sh

Note: this does not remove auto merge from the auto-merge-keyman-server-pr.yml GHA at this time, because that would require us to use graphql to mark PRs as auto-merge, and we are not quite ready to do that. So we'll continue to use the automerge action for now.
The scope for pull request events has been expanded on auto-merge-keyman-server-pr.yml so that updates to build status trigger the automerge as needed.
Fixes: #14502
Test-bot: skip

maint(resources): add build-bot commands to increment-version auto PRs

---

web/ci.sh

Skip Sentry upload for non-release builds. Add TODO to merge ci.sh content with resources/teamcity/web.
Fixes: #14289
Build-bot: build
Test-bot: skip

maint(web): skip unnecessary steps for `build` buildLevel

---

web/src/engine/common/web-utils/src/rewindable-cache.ts
web/src/engine/common/web-utils/src/tests/rewindableCache.tests.js
web/src/engine/main/src/headless/inputProcessor.ts
web/src/engine/main/src/headless/languageProcessor.ts
web/src/engine/main/src/headless/transcriptionCache.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.ts
web/src/engine/predictive-text/worker-thread/src/main/model-compositor.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/worker-model-compositor.tests.ts

This patches #14442 with an alternate specification for its `RewindableCache` class.
The class is notably simplified after the changes.  It does coerce the key type to be simply `number`, but this allows us to test against key (id) values, which is especially relevant since transform / transition IDs are monotonically increasing as new keystrokes occur.

change(web):  simplify RewindableCache 🚂

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Addresses part of #14533
Android emulator on API 36 (Android 16.0 Baklava) has a new behavior where the system On-Screen Keyboard doesn't appear because the physical keyboard of the host computer is connected. The Gboard keyboard has a preference toggle to "Show on-screen keyboard while using physical keyboard" (default false)
This PR overrides the SystemKeyboard handler to display the OSK while using physical keyboard (on the Keyman, Sample2, and FirstVoices apps)
We'll probably :cherries: -pick this PR to stable-18.0 since Android API 36 will roll out to more devices over the year.
A separate follow-on PR will address the long-term plan of having a Keyman preference toggle to show on-screen keyboard while using physical keyboard (default false)
**Setup** - Setup Android emulator for API …

fix(android): Show system OSK when physical keyboard connected on Android API 36 👁️

---

android/KMAPro/build.sh
android/build.sh
oem/firstvoices/android/build.sh
resources/teamcity/android/android-actions.inc.sh
resources/teamcity/android/keyman-android-release.sh
resources/teamcity/android/keyman-android-test.sh

Refactor the publish action for Android to ensure that symbols are published to Sentry for any 'release' buildLevel -- test releases and alpha/beta/stable releases.
Splits the publish action into `publish-symbols` and `publish-play-store` so that they can be run separately as needed, as symbols can be published for test builds, but play store is only touched for actual releases.
Note: examining the build logs and Sentry server state, it looks like the publish to Sentry has not been happening for quite a while, so this commit refactors the Sentry publishing code and establishes the fv-keyboards publish target also.
Fixes: #14284
Blocked-by: #14506
Build-bot: release
Test-bot: skip

maint(android): publish symbols to Sentry on release buildLevel 🦌

---

resources/teamcity/linux/keyman-linux-release.sh

This allows to pass the path to help.keyman.com in the TC build config rather than as an environment variable.
Test-bot: skip

maint(linux): add missing `--help.keyman.com` option

---

linux/scripts/dist.sh

During a package build a  patch directory (`.pc`) might get created. That can't and shouldn't be part of the source package. This change excludes any `.pc` directories.
Test-bot: skip

maint(linux): ignore generate patch directories

---

android/KMAPro/build.gradle
android/KMAPro/build.sh
android/KMAPro/kMAPro/build.gradle
android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample2/app/build.gradle
android/Tests/KeyboardHarness/app/build.gradle
oem/firstvoices/android/app/build.gradle

Fixes #13724 about Gradle warnings
> WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.
This basically involves using newer Gradle syntax when bringing in the internal material-stepper and keyman-engine .aar libraries. I verified local builds no longer generate the flatDir warning.
Impacts the Android projects that consume keyman-engine.aar
**Setup** - Install the PR build of the specified apps on an Android emulator/device (API 34 good)
* **TEST_KEYMAN** - Verifies keyboard installation and keyboard works
1. Install and launch Keyman for Android
2. Dismiss the Get Started menu and from Keyman settings, install sil_cameroon_qwerty keyboard from keyman.com
3. Verify keyboard installation has the steps to pick a language for the keyboard (this uses the …

fix(android): Update Gradle files to remove flatDir warnings

---

resources/builder.inc.sh

Turns out that in some cases, REPO_ROOT had relative ../ path components, which is not what we want. Now uses readlink to resolve path completely.
Test-bot: skip

maint(resources): ensure REPO_ROOT is fully resolved

---

developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/package-compiler-messages.ts
developer/src/kmc-package/test/fixtures/invalid/missing_model_id.kps
developer/src/kmc-package/test/package-compiler.tests.ts

If a `<LexicalModel>` element is found with a missing or empty `<ID>` element, the compiler will now report `ERROR_MissingModelId` instead of crashing. The corresponding check for missing `<ID>` for `<Keyboard>` element has been updated to match this, and now reports a clearer error message of `ERROR_MissingKeyboardId` rather than depending on the side-effect of looking up the keyboard in the `<File>` elements.
Fixes: #13783
Fixes: KEYMAN-DEVELOPER-2X7
Test-bot: skip

fix(developer): handle missing model id in package with compiler error

---

android/KMEA/app/src/main/java/com/keyman/engine/BaseActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

:cherries: pick of #14619 to stable-18.0
This PR incorporates the pattern of fixes in AlphaTiles/AlphaTiles#237
specifically https://github.com/AlphaTiles/AlphaTiles/pull/237/files#diff-ffa9782556981f30f50417410a12d591b1659c2b19873327147a9330bbc1982e changing from `setLayoutParams()` to `setPadding()`
To keep the in-app keyboard from being obscured by the bottom navigation bar, I still needed to keep the `applyInsetsToKeyboard()` call. 
**Setup** - Install the PR build of Keyman for Android on an Android emulator/device of Android API 34
From the Keyman "Get Started" menu, set Keyman as the default system keyboard
* **TEST_NO_BLANK_SPACE** - Verifies no blank space between the bottom navigation bar and OSK (as reported in the issue)
1. Open the Keyman app
2. On "Get Started": Checked the …

fix(android): Fix insets for in-app vs system keyboard 🏠

---

resources/docker-images/linux/Dockerfile
resources/docker-images/run.sh

Fixed some errors found during tests for #13954 when running resources/docker-images/run.sh with targets ":linux" and ":web".
Test-bot: skip

fix: fixing some issues for bulding and testing with Docker containers

---

linux/scripts/dist.sh
linux/scripts/upload-to-debian.sh

This change creates a temporary worktree for creating Debian packages. This will allow us to work from a clean state of the source repo. Also exclude any generated patch directories (`.pc`).
Test-bot: skip

maint(linux): create temporary worktree for packaging

---

android/KMEA/app/src/main/res/layout/activity_list_layout.xml
android/KMEA/app/src/main/res/layout/list_layout.xml
android/KMEA/app/src/main/res/layout/list_toolbar.xml
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/KeyboardListActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/RegionListActivity.java

Follow-on cleanup from #14248
I was preparing to :cherries: the Samples and FirstVoices layout changes to stable-18.0 when I noticed the last row in FirstVoices Region/Keyboard lists were covered by the navigation bar.
In the BC Coast keyboards list, the bottom entry **’Wuìk̓ala** was obscured by the navigation bar
*Screenshot of fixed keyboard list*
* Cleaned up unnecessary level of ConstraintLayout in list_toolbar
* Add bottom padding to the list layout so list layout isn't covered by the navigation bar
* Apply the `BaseActivity.setupEdgeToEdge()` calls in FirstVoices (missed in #14514) 
**Setup** - Install the PR builds for the corresponding tests on Android device/emulator 
* **TEST_KEYMAN** - Verifies lists appear fine on Keyman app
1. With the device in portrait orientation, install …

fix(android): Cleanup list layout in Engine and FirstVoices for edge to edge 🪟

---

linux/scripts/dist.sh
linux/scripts/upload-to-debian.sh

This change creates a temporary worktree for creating Debian packages. This will allow us to work from a clean state of the source repo. Also exclude any generated patch directories (`.pc`).
Cherry-pick-of: #14598
Test-bot: skip

maint(linux): create temporary worktree for packaging 🍒 🏠

---

web/src/engine/main/src/headless/languageProcessor.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-token.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-tokenization.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-transition.ts
web/src/engine/predictive-text/worker-thread/src/main/model-compositor.ts
web/src/engine/predictive-text/worker-thread/src/main/test-index.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-token.tests.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-tokenization.tests.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-tracker.tests.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-transition.tests.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/worker-model-compositor.tests.ts

As noted on https://github.com/keymanapp/keyman/pull/14427#discussion_r2248721150, part of the new design calls for applied suggestions to be tracked at the `ContextState` level, rather than the `ContextToken` level.  Remedying this issue also provides us with a great opportunity to fix the issue that arose in #14442's handling of a few unit tests and provide a better model for tracking applied suggestions moving forward.
Sadly, we'll need to improve this model later - we need a few more improvements to actually track the intermediate context-state (before the whitespace, after the word) and to revert from that intermediate target later.  This gets us _far_ closer than we were before, though.
I also investigated exactly what `ModelCompositor.acceptReversion` needs - for all known use …

change(web): rework applied-suggestion tracking + reversions 🚂

---

web/src/engine/predictive-text/worker-thread/src/main/correction/alignment-helpers.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-tokenization.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-transition.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/transform-tokenization.ts
web/src/engine/predictive-text/worker-thread/src/main/index.ts
web/src/engine/predictive-text/worker-thread/src/main/model-compositor.ts
web/src/engine/predictive-text/worker-thread/src/main/predict-helpers.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-tracker.tests.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/worker-model-compositor.tests.ts

In order to transition to the context-reuse strategy specified in the [Correction-Search + Context-Tracking design doc](https://docs.google.com/document/d/1RYwgW8zI8A7VLMq40BpWYkfJJQ-i6K0MIs4QcAMxglE/edit?tab=t.0), this PR changes context-transition caching behavior to now only save the most recent transition and transitions caused by applied suggestions.  [This section in particular](https://docs.google.com/document/d/1RYwgW8zI8A7VLMq40BpWYkfJJQ-i6K0MIs4QcAMxglE/edit?tab=t.0#heading=h.c91x4fdrtk8) should provide a useful reference.  
Of note:  I was able to implement this _without_ requiring (or even _allowing_) that the base context ID be specified on incoming prediction requests, even for multitap key input!  That said, it might be wise to add the ID anyway for validation and …

change(web): do not cache context states that will no longer be referenced 🚂

---

web/src/engine/predictive-text/worker-thread/src/main/correction/alignment-helpers.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-tokenization.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/alignment-helpers.tests.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-tokenization.tests.ts

Addresses https://github.com/keymanapp/keyman/pull/14476#issuecomment-3201650684 - I found that applying a suggestion immediately after backspacing would trigger a JS error.  There's a decent chance this relates to a unit test error.
Given the scale of the change was above just a few lines, it felt right to make the fix its own PR.

fix(web): handle suggestion application after backspacing 🚂

---

web/src/engine/main/src/headless/inputProcessor.ts
web/src/engine/osk/src/input/gestures/browser/flick.ts
web/src/engine/osk/src/input/gestures/browser/multitap.ts
web/src/engine/osk/src/input/gestures/browser/subkeyPopup.ts
web/src/engine/osk/src/visualKeyboard.ts
web/src/engine/predictive-text/worker-thread/src/main/model-compositor.ts

Due to recent internal changes, the context-caching engine now needs the effects for the actual input keystroke to be in the initial position within the fat-finger distribution.  This removes a few places where the distribution has been sorted up 'til now, as there are cases where a different key can have higher probability than the one actually tapped - displacing the actual input from the lead position.

fix(web): always place true input at lead of fat-finger distribution 🚂

---

android/KMEA/app/src/main/res/layout/activity_list_layout.xml
android/KMEA/app/src/main/res/layout/list_layout.xml
android/KMEA/app/src/main/res/layout/list_toolbar.xml
android/README.md
android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample1/app/src/main/java/com/keyman/kmsample1/MainActivity.java
android/Samples/KMSample1/app/src/main/res/layout/activity_main.xml
android/Samples/KMSample2/app/build.gradle
android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/MainActivity.java
android/Samples/KMSample2/app/src/main/res/layout/activity_main.xml
android/Tests/KeyboardHarness/app/build.gradle
android/Tests/KeyboardHarness/app/src/main/java/com/keyman/android/tests/keyboardHarness/MainActivity.java
android/Tests/KeyboardHarness/app/src/main/res/layout/activity_main.xml
oem/firstvoices/android/app/build.gradle
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVKeyboardSettingsActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/KeyboardListActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/RegionListActivity.java
oem/firstvoices/android/app/src/main/res/layout/activity_main.xml
oem/firstvoices/android/app/src/main/res/layout/fv_keyboard_settings_list_layout.xml

:cherries: pick to stable-18.0 for #14248
* Cleanup list layout in Engine and FirstVoices (ensures Wuìk̓ala is available at the bottom of the FirstVoices BC Coast region list)
* Update Sample, Test, and FirstVoices apps for edge to edge
* Update Sample1 for rotation
**Setup** - Install the PR build of the corresponding app on an Android emulator/device of Android API 34
* **TEST_KMSAMPLE1** - Verifies KMSample1 app is not obstructed by system insets
1. Install the KMSample1 app and launch it
2. Verify the in-app keyboard is not obstructed by bottom navigation bar
3. Verify the top menu bar is not obstructed by the top status bar or camera notch
4. Rotate the device from Portrait to Landscape orientation
5. Verify the sides of the in-app keyboard is not obstructed by navigation bar, status …

fix(android): Cleanup layouts for Engine, Sample apps, and FirstVoices apps for edge to edge 🍒 🏠

---

android/Samples/KMSample1/app/src/main/java/com/keyman/kmsample1/MainActivity.java

Fixes #14677 
This updates the KMSample1 app with several of the fixes in the Keyman for Android app for handling device orientation changes. (notably part of #8704)
The text area also needs to be resized to accommodate banner/keyboard dimensions which are different between portrait and landscape orientation.
**Setup** - Install the PR build of KMSample1 on an Android device/emulator
* **TEST_ROTATION** - Verifies text area not covered when rotating device
1. Start KMSample1 with the device in portrait orientation
2. Verify text area visible and keyboard and suggestions work
3. Rotate the device to landscape
4. Verify text area visible and keyboard and suggestions work]

fix(android): Update KMSample1 layout when changing orientation

---

web/src/engine/osk/src/visualKeyboard.ts

The new warning for missing fat-finger data was being thrown for keys that should not generate corrections or predictions; this will help prevent that.

fix(web): do not warn for missing fat-fingers on frame keys 🚂

---

web/src/engine/osk/src/visualKeyboard.ts
web/src/test/auto/headless/engine/osk/visualKeyboard.tests.ts

PR #13860 fixed a similar error by adding a check for NaN. However, it missed doing it for `layoutWidth` and only changed `layoutHeight`. This PR adds a similar check to `layoutWidth` and  `internalHeight` and will thus fix the error we're still seeing in Sentry.
Also add unit tests for all three methods.
TEST_INUKTITUT_KEYBOARD: Using Keyman for Android, install the `inuktitut_pirurvik` and verify that no error notifications appear.
Fixes: #14108
Fixes: [KEYMAN-WEB-RA](https://keyman.sentry.io/issues/6579536471/?referrer=github_integration)
Cherry-pick-of: #14684

fix(web): fix error trying to calculate style scaling effects 🍒 🏠

---

web/src/engine/interfaces/build.sh
web/src/engine/interfaces/src/modelSpec.ts
web/src/engine/main/build.sh
web/src/test/auto/headless/engine/interfaces/pathConfiguration.tests.ts
web/src/test/auto/headless/engine/interfaces/prediction/predictionContext.tests.ts
web/src/test/auto/headless/engine/main/inputProcessor.tests.ts
web/src/test/auto/headless/engine/main/languageProcessor.tests.ts

I'm hoping to add new unit tests and integration tests for some of the new autocorrect enhancements.  Before I do so, I'd like to convert the test suites to be extended over to TypeScript.
Test-bot: skip

change(web): convert engine/main, engine/interfaces tests to TS 🚂

---

mac/Keyman4MacIM/make-km-dmg.sh
mac/build.sh

Note: corresponding change for test bot is on its way..
Relates-to: #10521
Test-bot: skip
Build-bot: skip release:mac
Fixes: #10521 (last in the series)

maint(mac): use versioned filenames for PR artifacts

---

common/windows/delphi/packages/PackageInfo.pas

When loading package files generated by kmc or edited on non-Windows systems, the Package Editor will now convert any forward slashes in the path to backslashes. This is necessary because the path manipulation functions in Keyman Developer work only with backslashes.
Fixes: #14719
Test-bot: skip
Cherry-pick-of: #14721

fix(developer): transform slashes to backslashes in paths in Package Editor 🍒 🏠

---

linux/keyman-config/keyman_config/install_kmp.py
linux/keyman-config/keyman_config/kvk2ldml.py

Using `if var := func():` syntax outputs a warning `FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.` in Python 3.12. This change works around this warning.
Test-bot: skip

refactor(linux): remove warning

---

.github/workflows/deb-packaging.README.md
.github/workflows/deb-packaging.yml

By default we skip package builds if run on a non-Keyman repo. This makes it harder to test changes, so this PR allows to pass the parameter `force: true` when triggering the build.
Test-bot: skip

maint(linux): allow to force package build on non-Keyman repo

---

linux/debian/changelog
linux/debian/control

`onboard-keyman` isn't available on Debian/Ubuntu and doesn't work properly with Wayland. This change removes the `onboard-keyman` recommends which used to cause `onboard-keyman` to be installed automatically together with `keyman`. The user can still manually install `onboard-keyman`.
Fixes: #14769
Fixes: #5214
Cherry-pick-of: #14772
Test-bot: skip

chore(linux): remove automatic installation of `onboard-keyman` 🍒 🏠

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java

Fixes #14070 and follows #13702
The reported System keyboard issue was:
> The banner appears in black when removing a keyboard from the keyboard picker
This change ensures when a keyboard is changed (removed from the keyboard picker), the banner is refreshed.
**Setup** - Install the PR build of Keyman for Android on a device/emulator
* **TEST_BANNER** - Verifies banner functions when removing a keyboard from the keyboard picker
1. Install the PR build of Keyman for Android on an Android device or emulator
2. Accept all the Android permission requests for storage.
3. Open the Keyman app.
4. On the "Get Started" dialog.
5. Check the "Enable Keyman as system-wide keyboard" box.
6. Check the "Set the keyboard as the default keyboard" box.
7. Navigate to the settings page and then select …

fix(android): Refresh the banner theme when system keyboard is changed

---

resources/build/increment-version.sh

The original `$KEYMAN_VERSION` variable was cherry-picked from 19.0, but we should have been using `$VERSION` for the 18.0 code.
Note: I will manually generate the PR to update HISTORY.md for 18.0.241.
Fixes: #14778
Follows: #14614
Test-bot: skip

maint(resources): use VERSION variable in increment-version.sh 🏠

---

linux/ibus-keyman/src/test/meson.build

`meson.build_root()` is deprecated in Meson 1.0+.
Test-bot: skip

refactor(linux): remove a meson deprecation warning

---

linux/scripts/upload-to-debian.sh

With this change we wait two seconds after creating the PR before trying to get the number of the PR so that GitHub can catch up. Previously recently it wasn't able to get the PR#.
Also adjust the commit message and use the new header for skipping tests.
Cherry-pick-of: #13890
Test-bot: skip

maint(linux): improve getting PR# in `upload-to-debian.sh` 🍒 🏠

---

.shellcheckrc
docs/settings/linux/settings.json
linux/ibus-keyman/tests/scripts/find-tests.sh
linux/ibus-keyman/tests/scripts/run-single-test.sh
linux/ibus-keyman/tests/scripts/run-tests.sh
resources/docker-images/run.sh

This change improves our `.shellcheckrc` file so that several directives are no longer needed and source files are still found. Also remove some directives that are no longer necessary, either because the changes to `.shellcheckrc` makes them obsolete, or because the lines changed so that they no longer contain the problem.
Test-bot: skip

maint(linux): remove several shellcheck directives

---

.github/workflows/cleanup-ghcr.yml
resources/docker-images/docker-build.inc.sh

No longer dryrun for the registry clean-up GHA workflow
docker run doesn't use a terminal in GHA (erasing -t flag)
Test-bot: skip

fix(common): registry clean-up enabled, no terminal in github action

---

web/src/engine/predictive-text/worker-thread/src/main/correction/classical-calculation.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/segmentable-calculation.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/correction-search/classical-calculation.tests.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/correction-search/segmentable-calculation.tests.ts

Reviewing the edit-distance types and their uses, I noticed that their encapsulation was... rather loose, with `diagonalWidth`'s usage being particularly egregious.  That really belongs more as an initialization parameter.
This PR seeks to improve encapsulation and allow specifying initialization options, such as how wide the edit-distance algorithm will search for alternative paths for optimal edit distance.
Note that #14726 adds an extra initialization option for the types, tied to an added feature that also motivated the encapsulation improvements.
Test-bot: skip

refactor(web): improve encapsulation for edit-distance calculation objects 🚂

---

windows/src/desktop/inst/keymandesktop.wxs

Change Keyman shortcuts to standard Windows shortcuts, rather than advertised shortcuts, to work around the issue described in #14791.
This PR is an alternate to #14809. The problem is related to [advertised shortcuts](https://learn.microsoft.com/en-us/windows/win32/msi/advertisement) in Windows Installer. When you have an advertised shortcut, the first use of the shortcut triggers a repair to prepare the app for use in the new user's context.
So PR disables advertising of shortcuts with [`DISABLEADVTSHORTCUTS`](https://learn.microsoft.com/en-us/windows/win32/msi/disableadvtshortcuts). This means that the shortcuts will be regular Windows shortcut files rather than advertised shortcuts, and are added to `%ProgramData%\Microsoft\Windows\Start Menu\Programs\Keyman for Windows` (so, …

fix(windows): disable MSI shortcut advertisement

---

resources/build/zip.inc.sh

Also cleans up a number of possible quoting issues and shellcheck directives.
Note: we need to do release builds everywhere to verify that zip changes are not going to break things.
Test-bot: skip
Build-bot: release

maint(resources): lookup 7z on path on Windows if SEVENZ_HOME is not set

---

android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Relates to #14794 and follows #14808
This updates KMSample2 and FirstVoices for Android system keyboards to account for padding and offsets due to navigation bar height.
**Setup** - Install the PR build as directed on an Android emulator /device of Android API 35. In device settings --> display --> set navigation to use 3 buttons
* **TEST_KMSAMPLE2** - Verifies KMSample2 system keyboard is not obscured
1. Install the PR build of KMSample2
2. Launch KMSample2 and follow the menus to set KMSample2 as the default system keyboard
3. Launch Chrome app and select a text area
4. With KMSample2 as the system keyboard, verify the keyboard functions:
a. base keys
b. longpress keys
c. suggestion banner
* **TEST_FV** - Verifies FirstVoices system keyboard is not obscured
1. Install the PR build of …

fix(android): Fix bottom insets for Sample and FirstVoices apps

---

android/docs/engine/KMManager/getNavigationBarHeight.md
android/docs/engine/KMManager/index.md

Documents the `KMManager.getNavigationBarHeight()` API call added in #14808 to offset the Keyman keyboard for the navigation bar height.
Test-bot: skip

docs(android): Document getNavigationBarHeight API

---

linux/debian/source/lintian-overrides

It looks like we no longer need these lintian overrides: - `package-contains-documentation-outside-usr-share-doc` got resolved   by excluding these directories from our source package - the other one was a false positive that looks like it got fixed in   Debian
Cherry-pick-of: #14810
Test-bot: skip

chore(linux): remove no longer needed lintian overrides 🍒 🏠

---

windows/src/desktop/inst/keymandesktop.wxs

Change Keyman shortcuts to standard Windows shortcuts, rather than advertised shortcuts, to work around a problem with advertised shortcuts, elevated custom actions, and non-admin users, as described in #14791.
The problem is related to advertised shortcuts in Windows Installer. When you have an advertised shortcut, the first use of the shortcut triggers a repair to prepare the app for use in the new user's context. And now, with Aug 2025 Windows security patch KB5063878, tweaked in Sep 2025, this triggers an elevation dialog, which the non-admin user cannot work around.
This means that the shortcuts will be regular Windows shortcut files rather than advertised shortcuts, and are added to `%ProgramData%\Microsoft\Windows\Start Menu\Programs\Keyman for Windows` (so, available for all users …

fix(windows): disable .msi shortcut advertisement 🍒 🏠

---

web/src/test/auto/dom/cases/core-processor/basic.tests.ts
web/src/test/auto/dom/web-test-runner.config.mjs
web/src/test/auto/integrated/web-test-runner.config.mjs

Webkit on Windows doesn't support WASM, so several tests fail. This change disables the webkit tests when running on Windows.
Fixes: #14859
Test-bot: skip

chore(web): disable DOM tests for webkit on Windows 🎼

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-state.ts
web/src/engine/predictive-text/worker-thread/src/main/test-index.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-state.tests.ts

To be explicit:  the method is designed to compare the context after applying a context transition's edit with the context state after a window slide takes effect, but before the next transition's edit takes effect.
Test-bot: skip

feat(web): add method to determine the change to context resulting from a context window slide 🚂

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-token.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-tokenization.ts
web/src/engine/predictive-text/worker-thread/src/main/test-index.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-tokenization.tests.ts

These windows are designed for use in detecting tokenization shifts both at the start and the end of the context.  Rather than constantly retokenize the whole available context, we can be more efficient by limiting the range we permit for retokenization.
Relates-to: #14679
The following two dependent PRs leverage this method:
- #14754
- #14790
Test-bot: skip

feat(web): build token-aligned edge windows 🚂

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-tokenization.ts
web/src/engine/predictive-text/worker-thread/src/main/test-index.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-tokenization.tests.ts

This PR adds a method that can determine which parts of a `Transform`'s `.insert` component landed within each post-application "token" of the context. 
When updating our context state information in order to attempt reuse of prior calculations, we need to know where the input's components align with them so that they affect the predictive-text process correctly.
Note that the `.deleteLeft` component is instead determined when building the edge window, as it takes effect on the _original_ state and tokenization of the context.  (Of particular note here:  if a token is fully deleted, there's no reason to preserve it - we can delete it instead [or replace it, if new text is set in the same place].)
Relates-to: #14679
Test-bot: skip

feat(web): add helper for tokenizing Transform.insert via tokenization of applied context 🚂

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-tokenization.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-tokenization.tests.ts

Handling merges and splits can get a little tricky, so this PR adds a new helper method that will help determine what effects any merges and splits should have when updating context state and tokenization data during a context transition.  Of particular note is `split` - it is _incredibly_ helpful to precompute the character index within the original token at which each split-off token should begin.
Relates-to: #14679
Test-bot: skip

feat(web): add helper for aligning tokens after merges, splits 🚂

---

common/test/resources/mocha-teamcity-reporter/README.md
common/test/resources/mocha-teamcity-reporter/teamcity.cjs
common/tools/sourcemap-path-remapper/package.json
linux/ibus-keyman/src/test/run-tests.sh
linux/ibus-keyman/tests/scripts/test-helper.inc.sh
package-lock.json
package.json
resources/build/pr-build-status/package-lock.json
resources/build/pr-build-status/package.json
resources/build/typescript.inc.sh
resources/teamcity/includes/tc-linux.inc.sh
web/common.inc.sh
web/src/engine/common/web-utils/build.sh
web/src/engine/common/web-utils/package.json
web/src/engine/osk/gesture-processor/package.json
web/src/engine/predictive-text/templates/package.json
web/src/engine/predictive-text/wordbreakers/build.sh
web/src/engine/predictive-text/wordbreakers/package.json
web/src/engine/predictive-text/worker-main/package.json
web/src/engine/predictive-text/worker-main/unit_tests/test.sh
web/src/engine/predictive-text/worker-thread/package.json

This adds a modified `mocha-teamcity-reporter` that allows to nest the unit tests under the parent block.
Fixes: #14839
Test-bot: skip

maint(resources): nest unit tests under parent block ☕

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-tokenization.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-tokenization.tests.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/transform-tokenization.tests.ts

This PR's change set introduces a new method - `precomputeTokenizationAfterInput` - designed to facilitate context transitions for cases that we currently do not support properly.
This method determines _both_ the tokenization for the input `Transform` _and_ its effects on the tokenization of existing context at the same time and can detect when two (or more) tokens are either merged or the result of a split edit.  The returned metadata - especially within the `tokenMapping` object and its properties - are designed to facilitate grouping cases together when they have matching effects for their transforms and final tokenizations.  
Notable advantages this PR's new method and its helpers have over the `tokenizeTransform` and `computeAlignment` methods:
- Can handle `split` and `merge` edits …

feat(web): precompute transform tokenization while handling when existing boundaries shift 🚂

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-tokenization.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-tokenization.tests.ts

Once we start supporting multiple tokenization paths, a very important question arises - are there scenarios in which we can safely treat tokenization paths identically?  After a significant amount of brainstorming, I have come to the conclusion that yes, there are such cases.  The main requirement:
- The _current_ (i.e. "last") token in both versions of the context (and tokenization) started due to the same keystroke.  
- In particular, it started at the same index within that keystroke's `Transform.insert` string.
- Note the implication - all inputs _since_ that keystroke are also part of the token.  The two versions thus were created from the same keystrokes and are safe to correct to each other.
- However, if they did not start at the same position within the initial keystroke's …

feat(web): track source input ranges for the edit-boundary source token 🚂

---

web/src/engine/predictive-text/worker-thread/src/main/correction/context-token.ts
web/src/engine/predictive-text/worker-thread/src/main/correction/context-tokenization.ts
web/src/engine/predictive-text/worker-thread/src/main/test-index.ts
web/src/test/auto/headless/engine/predictive-text/worker-thread/context/context-token.tests.ts

As there are known cases in which one token may be split into two due to change of word-boundary behavior as new input is received, this PR establishes a method that may be used to properly split tokens into their constituent pieces.  
This is greatly helped by the method added in #14806, which is able to determine where the raw text for each newly split-off token begins within the original token.  Combined with our tracking of input-transform ranges - and particularly, the `inputStartIndex` field added in #14756 - these pieces combined give us what is necessary to properly map the inputs to the new tokens as if they'd always been separate.
Note that this assumes that all input transforms for a tokenization share the same 'subset' pattern - the same deleteLeft count + insert length.  This …

feat(web): add class method for splitting ContextToken instances 🚂
