keymanapp/keyman

- source/kmwosk.js
Also removed unused touchMenuPos (only used in embedded, not web)
> Need to trap errors in some OSK functions when load is slow #15

- web/.gitignore
- web/README.md
- web/source/build.bat
- web/source/kmwembedded.js
Takes the previously out-of-repo KMEA/KMEI module build path and merges it into this repository.  The build.bat files are now merged, where a plain 'build' corresponds to a build for all.
All paths within build.bat are now set with constants, allowing ease of filepath relocation should that be desired at a later point.
> Merge embedded build path

- web/source/keymanweb.js
Noticed a console error after #80 was merged; we missed one variable and its location.  Just a quick, simple fix.
> Fix for console log error; one variable was improperly located.

- web/source/keymanweb.js
> [Fix] Disabled element reformatting no longer occurs on desktop implementations.

- web/source/keymanweb.js
- web/source/kmwnative.js
- web/source/kmwuitoggle.js
Fixes issues with setting the keyboard via API calls that were discovered while updating the help documentation.
> Web set keyboard api fix

- web/source/kmwembedded.js
> Fixes support for embedded solutions using hardware keyboards.

- web/source/keymanweb.js
- web/source/kmwbase.js
- web/source/kmwcallback.js
- web/source/kmwdebug.js
- web/source/kmwinit.js
- web/source/kmwkeymaps.js
- web/source/kmwlegacy.js
- web/source/kmwnative.js
- web/source/kmwosk.js
- web/source/kmwuibutton.js
- web/source/kmwuifloat.js
- web/source/kmwuitoggle.js
- web/source/kmwuitoolbar.js
Addresses both issues #108 and #109.
> Bookmarklet support

- android/KMEA/app/src/main/assets/keyboard.html
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
- web/.gitignore
onResume() Javascript functions are defined in keyboard.html and need the window loaded before they can be called.
-Also cleaned up formatting in keyboard.html
> Fix KMEA uncaught javascript references

- web/source/keymanweb.js
- web/source/kmwbase.js
- web/source/kmwembedded.js
- web/source/kmwnative.js
Addresses #106.  Also includes a touch of code file reformatting.
> [Web] Embedded code-path clarification.

- ios/build.sh
- ios/engine/KMEI/KeymanEngine/Classes/KMInputViewController.m
- ios/history.md
See also separate PR #225 for merge into 2.6 release. This one should be merged first.
> Ios iphone 7 system keyboard width regression

- README.md
- ios/README.md
- ios/Readme.md
- web/README.md
root README
- Add iOS CI build status
- Organize according to desktop and web/mobile platforms
web/README
- Reorder content to a *Minimum Web Requirements* section
ios/README
- Add some formatting
> Update README files

- ios/README.md
Modifies README.md with instructions on physical device testing for the iOS app.
> [iOS] Instructions for testing on physical devices

- android/README.md
Clarified the part in README how to use built or downloaded keyman engine.
> Add reference to keyman engine binary

- windows/src/Defines.mak
- windows/src/Makefile
- windows/src/README.md
- windows/src/desktop/insthelp/Makefile
- windows/src/desktop/kmshell/Makefile
- windows/src/desktop/setup/Makefile
- windows/src/developer/TIKE/Makefile
- windows/src/developer/kmcmpdll/Makefile
- windows/src/developer/kmcomp/Makefile
- windows/src/engine/keyman/Makefile
- windows/src/engine/keyman32/Makefile
- windows/src/engine/keyman64/Makefile
- windows/src/engine/keymanx64/Makefile
- windows/src/engine/kmcomapi/Makefile
- windows/src/engine/kmtip/Makefile
- windows/src/engine/mcompile/Makefile
- windows/src/engine/tsysinfo/Makefile
* Update some makefiles which were pointing to old paths
* Add instructions on how to run Keyman after building
> Windows set up

- web/source/keymanweb.js
In reference to #311.  Reverts to previous behavior, pending redesign necessary for proper integration of such a feature.
Also includes a bit of tidying up and a few pieces of code to help with an eventual proper implementation.
> Disables physical keyboard input for touch devices in native mode.

- windows/src/desktop/history.md
Used a slightly wrong formatting on a few of the version headers.
> Windows history.md formatting fix.

- windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
- windows/src/test/web-chirality/web-chirality.kpj.user
> Fixup regression for debug-mode keyboards using touch keys (hexadecimal format error)

- web/history.md
- web/source/keymanweb.js
- web/source/kmwbase.js
Addresses #352, which was detected during work on #353.
> Corrects KMW auto-attach behavior.

- ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
Addresses the iOS portion of #349.
> [iOS] KMW core refactoring

- web/source/keymanweb.js
- web/testing/index.html
- web/testing/issue005/header.js
- web/testing/issue005/index.html
Fixes #5.
Includes code style formatting fix - reviewing the KeymanWeb code component on Github may be easier with the `?w=1` flag.
> `removeKeyboards` API function validation + enhancement.

- web/history.md
- web/source/keymanweb.js
Addresses post-merge comments on #395.
> Tweaks the new return value's behavior.

- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
Partially fixes #407 but not the visual artifacts.
> Fix keyboard status check

- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/engine/KMEI/KeymanEngine/Classes/Extension/JSONDecoder.DateDecodingStrategy+ISO8601Fallback.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngine/Classes/Model/Keyboard.swift
- ios/engine/KMEI/KeymanEngine/Classes/Model/KeyboardAPICall.swift
- ios/keyman/Keyman/Keyman/MainViewController.swift
Fixes #411.
Tested on `keyman://localhost/open?direct=true&url=https://marc.durdin.net/wp-content/uploads/2015/11/khmer10-1.2.json` and `keyman://localhost/open?keyboard=hebrew&language=heb`
> Fix custom keyboard download

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/JSONParser.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/Connection.java
- android/history.md
For the first portion of resolving #370 
Fix KMManager and JSONParser HttpURLConnection calls so HTTP:// to HTTPS:// redirects are properly followed.
> Update HttpURLConnections to follow HTTPS redirects

- ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
There was no merge conflict between #406 and #434 but a variable name changed and the PR agent doesn't build merged against master.
> Use the correct delegate variable name

- web/source/keymanweb.js
- web/source/kmwbase.js
- web/source/kmwcallback.js
- web/source/kmwdebug.js
- web/source/kmwembedded.js
- web/source/kmwosk.js
> Keystroke processing engine refactoring

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
> Fix text insert when dn < 0

- windows/src/global/delphi/general/CompilePackage.pas
Depends on #454, so will rebase once it is accepted.
> Add support for kmp.json to Developer package compiler

- ios/.gitignore
- ios/Cartfile
- ios/Cartfile.resolved
- ios/README.md
- ios/build.sh
- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/history.md
- ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
This is a rebuild of the [ios-carthage](https://github.com/keymanapp/keyman/pull/471).  I wanted to do a fresh pass on the Carthage implementation with the nested dependencies to make sure I didn't do anything unnecessary.  
This should have all of the feedback implemented from the previous PR without the muck of an unnecessary merge and I feel better about the overall implementation.
> Ios carthage redeux

- android/KMEA/app/src/main/assets/keyboard.html
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
- ios/engine/KMEI/KeymanEngine/Classes/Constants.swift
- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
- web/source/keymanweb.js
- web/source/kmwembedded.js
d145a89 fixes #467 and the rest is cleanup.
> Fix keyboard path

- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/engine/KMEI/KeymanEngine/Classes/Extension/UserDefaults+Types.swift
- ios/engine/KMEI/KeymanEngine/Classes/FontManager.swift
- ios/engine/KMEI/KeymanEngine/Classes/HTTPDownloader.swift
- ios/engine/KMEI/KeymanEngine/Classes/KeyboardRepository/APIKeyboardRepository.swift
- ios/engine/KMEI/KeymanEngine/Classes/KeymanURLProtocol.swift
- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/KeyboardInfoViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/Log.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngine/Classes/Notification/NotificationCenter+Typed.swift
- ios/engine/KMEI/KeymanEngine/Classes/TextField.swift
- ios/engine/KMEI/KeymanEngine/Classes/TextView.swift
- ios/engine/KMEI/KeymanEngineDemo/AppDelegate.swift
- ios/engine/KMEI/SystemKeyboard/KeyboardViewController.swift
- ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
- ios/keyman/Keyman/Keyman/AppDelegate.swift
- ios/keyman/Keyman/Keyman/InfoViewController/InfoViewController.swift
- ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift
- ios/keyman/Keyman/Keyman/Log.swift
- ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift
- ios/keyman/Keyman/SWKeyboard/KeyboardViewController.swift
- ios/samples/KMSample1/KMSample1.xcodeproj/project.pbxproj
- ios/samples/KMSample1/KMSample1/AppDelegate.swift
- ios/samples/KMSample1/KMSample1/ViewController.swift
- ios/samples/KMSample2/KMSample2.xcodeproj/project.pbxproj
- ios/samples/KMSample2/KMSample2/AppDelegate.swift
- ios/samples/KMSample2/KMSample2/ViewController.swift
- ios/samples/KMSample2/SWKeyboard/KeyboardViewController.swift
* Further removes functionality out of `Manager`
* Log messages now give more context
```
2017-12-07 14:43:34.244 [Info] [APIKeyboardRepository.swift:91] apiCompletionHandler(data:response:error:fetchCompletionHandler:) > Request completed -- 451 languages.
```
> Use XCGLogger instead of kmLog

- windows/src/developer/TIKE/child/UfrmPackageEditor.pas
- windows/src/developer/TIKE/project/kmnProjectFileUI.pas
This depends on #478 and will be rebased against master once we merge #478.
> Update 'package for distribution' command to bundle both js and kmx

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
Fixes #474.
The popup is never shown for the system keyboard so code related to that was removed.
This is how the popup appears now:
> Fix help popup positioning

- ios/engine/KMEI/KeymanEngine/Classes/Constants.swift
- ios/engine/KMEI/KeymanEngine/Classes/FontManager.swift
- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngine/Classes/Storage.swift
> Properly set OSK font for subkeys

- README.md
- android/KMAPro/build.sh
- android/KMEA/build.sh
- android/Samples/KMSample1/build.sh
- android/Samples/KMSample2/build.sh
- android/Tests/KeyboardHarness/build.sh
- android/build.sh
-Also updated link to logo2 and copyright date in root readme
> [Android] Stop warnings being reported during CI builds

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
Starting with Android 6.0 Marshmallow (API 23), apps need to request permissions for "dangerous" (Storage) access at runtime. Previous versions of Android granted permissions at installation. Normal permissions declared in the manifest are granted automatically.
This doesn't affect Keyman running on older versions of Android
[Reference](https://developer.android.com/training/permissions/requesting.html)
[Runtime Permissions Sample](https://github.com/googlesamples/android-RuntimePermissions) provided by Google
> [Android] Request storage permissions at runtime to install local KMP file

- web/source/resources/osk/kmwosk.css
Follow-on to #559, this adds styling for `kmw-key-special-on` to follow `kmw-key-shift-on`
> [Web] Also add styling for kmw-key-special-on

- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
These were changes I made but failed to stage in my final commit for the PR #550 .
> [Mac] Removed commented out code

- windows/src/developer/TIKE/xml/kmw/index.html
This is a feature change that I implemented to smooth debugging of an unrelated Keyman compatibility issue. The web debug window now shows a character grid, similar to that shown in the Keyman Developer integrated debugger.
> Add extra feedback in the web debug window

- mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj
- mac/Keyman4MacIM/Keyman4MacIM/Info.plist
- mac/Keyman4MacIM/Keyman4MacIM/InfoPlist.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
- mac/Keyman4MacIM/Keyman4MacIM/KMInputController.m
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
- mac/Keyman4MacIM/Keyman4MacIM/KMPackage.h
- mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m
> [Mac] support double clicking kmp

- android/KMEA/build.sh
Unit Test results will be reported on the Test PR configurations
> [Android] Report Unit tests back to Teamcity

- mac/history.md
Added a 10.0 alpha section to history.md
> [Mac] Update history.md for alpha 10.0

- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngine/Classes/Model/KMPKeyboard.swift
- ios/engine/KMEI/KeymanEngine/Classes/Model/KeymanPackage.swift
- ios/history.md
- ios/keyman/Keyman/Keyman-Info.plist
- ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
- ios/keyman/Keyman/Keyman/AppDelegate.swift
Creating this PR on behalf of @jacobbullock to get the review comments rolling
> [iOS] Add feature for ad-hoc keyboard distribution via KMP

- windows/src/developer/TIKE/xml/kmw/index.html
This is just a slight improvement to the web debugger to show the cursor position and avoid the character preview wrapping on mobile and overlapping the text field.
> In web debugger, keep character preview content in view and show cursor position

- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
- mac/Keyman4MacIM/KeymanTests/KMInputMethodBrowserClientEventHandlerTests.m
The improved behavior can be seen in Chrome Google Docs. Test using step #3 of "Special Google Docs/Word Online Compatibility Issues" (https://github.com/keymanapp/keyman/wiki/User-testing-for-Mac).
> [Mac] Detect context changes caused by low level events

- windows/src/desktop/kmshell/xml/downloadkeyboard.xsl
- windows/src/desktop/kmshell/xml/keyman_keepintouch.xsl
- windows/src/desktop/kmshell/xml/keyman_support.xsl
- windows/src/developer/TIKE/xml/project/distribution.xsl
- windows/src/developer/TIKE/xml/project/keyboards.xsl
- windows/src/global/delphi/general/Upload_Settings.pas
This goes with an update to keyman.com to publish the new endpoints
> Update keyman.com endpoints to use better namespacing

- windows/src/desktop/kmshell/xml/config.js
- windows/src/desktop/kmshell/xml/elements.xsl
- windows/src/desktop/kmshell/xml/keyman_keyboardlist.xsl
- windows/src/global/delphi/general/UfrmScriptError.dfm
- windows/src/global/delphi/ui/UfrmWebContainer.dfm
- windows/src/global/delphi/ui/UfrmWebContainer.pas
Fixes sillsdev/keyman-issues#5581
I can't say this solution thrills me, but rewriting large chunks of Keyman Configuration UI to avoid the problem is worse at this point. I can see us rewriting it later as pure HTML/JS with a local webserver, which would be far cleaner.
> Fixes errors with Mike's-DevU.kmx keyboard in Keyman Configuration, and bonus improves script error dialog a smidge

- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
Fixes crashing whilst installing kmp packages
> [iOS] Fix force unwrap of optional kmp params for fonts

- windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
- windows/src/global/delphi/general/compile.pas
- windows/src/test/manual-tests/mnemonic-layouts-on-web/mnemonic_layouts_on_web-layout.js
- windows/src/test/manual-tests/mnemonic-layouts-on-web/mnemonic_layouts_on_web.kmn
- windows/src/test/manual-tests/mnemonic-layouts-on-web/mnemonic_layouts_on_web.kpj
Fixes #265 
Note: K_ virtual keys are not impacted by this change.
> Rework test for virtual keys in mnemonic layouts. Still not completely supported but a step in the right direction

- windows/src/README.md
- windows/src/buildtools/help-keyman-com.sh
This script uses much the same structure as the help-keyman-com.sh script in the keyboards repo.
> Upload keyboard documentation to help.keyman.com

- windows/src/developer/TIKE/project/kmnProjectFileUI.pas
- windows/src/developer/TIKE/web/UmodWebHttpServer.pas
- windows/src/developer/TIKE/xml/kmw/index.html
> Rework the [Install into app] infrastructure and fix bugs

- android/history.md
- ios/history.md
- mac/history.md
- resources/historyUtils.sh
- resources/validateHistory.sh
- web/history.md
- web/testing/attachment-api/utilities.js
- windows/src/desktop/history.md
- windows/src/developer/history.md
> Merge 10.0 beta work from P2S15 into 11.0 alpha

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/ConfirmDialogFragment.java
- android/history.md
Fixed call for finishing activity when cancelling keyboard download dialog
> Fixes #786

- windows/src/developer/TIKE/main/UframeOnScreenKeyboardEditor.pas
Fixes sillsdev/keyman-issues#5563 - crash after save or source view change in OSK Editor
> [developer] Fixes crash after save or source view change in OSK Editor

- ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift
@mcdurdin this is a clean PR without the extra commits attached.  I made a new  PR off of master,  because rebasing was not  working.
> [ios] Search Google if an unqualified url is entered

- mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/preferences.xib
- mac/Keyman4MacIM/Keyman4MacIM/KMDownloadKeyboard/KMDownloadKBWindowController.m
- mac/Keyman4MacIM/Keyman4MacIM/KMDownloadKeyboard/KMDownloadKBWindowController.xib
- mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/KMInfoWindowController.xib
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
- mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/KMKeyboardHelpWindowController.xib
- mac/history.md
#705 : Download keyboard should show search window instead of list
#709 : "Go to keyman.com" should open the page in default browser
#791 : Pages displayed in Configuration windows do not allow user to type into web forms.
> [Mac] 705/709/791 Fixes to configuration/download windows

- windows/src/developer/TIKE/actions/dmActionsMain.pas
- windows/src/developer/history.md
- windows/src/global/delphi/online/OnlineUpdateCheck.pas
Fixes sillsdev/keyman-issues#5597
> [developer] Avoid crash if online update already running

- windows/src/developer/TIKE/main/KeymanDeveloperUtils.pas
- windows/src/global/delphi/general/KeymanPaths.pas
Fixes sillsdev/keyman-issues#5447
> Trap errors if Keyman Desktop is not installed when trying to install a keyboard

- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodBrowserClientEventHandler.m
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandlerProtected.h
Still need to do more local testing to make sure everything is good and it didn't break any other apps.
> [Mac] Issue 175: Solved compatibility problem with Open Office

- windows/src/developer/TIKE/project/kmnProjectFile.pas
> Ensure that visual keyboard is correctly associated with kmx at compile time

- windows/src/developer/TIKE/actions/dmActionsMain.pas
- windows/src/developer/TIKE/main/UfrmMain.pas
> [developer] Don't create a blank project on 'opening' a project, either on startup or via menu

- windows/src/global/delphi/comp/KMDActions.pas
> [developer] Scroll editor into view after undo

- windows/src/developer/TIKE/child/UfrmKeymanWizard.pas
- windows/src/developer/TIKE/child/UfrmPackageEditor.pas
- windows/src/developer/TIKE/project/kmnProjectFileUI.pas
> [developer] Correctly show messages window after compile.

- web/history.md
- web/source/kmwosk.ts
> [Web] Case-insensitive virtual keys

- windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas
Fixes sillsdev/keyman-issues#5607 sporadic crash in Keyman when updating keyboard icon in OSK
> [windows] Fix sporadic crash in Keyman when updating keyboard icon in OSK

- android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
- android/KMEA/app/src/main/assets/keyboard.html
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/Connection.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java
- android/history.md
Fixes #748 
* Remove nearly all uses of `Log.d()`
* Disable `window.console.log()` calls in `keyboard.html`
> [android] cleanup console log

- windows/src/desktop/setup/RunTools.pas
- windows/src/desktop/setup/SetupStrings.pas
- windows/src/desktop/setup/UfrmRunDesktop.pas
Fixes #374, Keyman Desktop restarting Windows pathway is a little unclear if user chooses not to restart
> [windows] Keyman Desktop Setup restarting Windows pathway is a little unclear if user chooses not to restart

- mac/.gitignore
- mac/Cartfile
- mac/Cartfile.resolved
- mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj
- mac/Keyman4MacIM/Keyman4MacIM/Info.plist
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
- mac/build.sh
- mac/history.md
> [Mac] #769 Added error reporting via Fabric/Crashlytics

- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/engine/KMEI/KeymanEngine/Classes/Errors/KeyboardError.swift
- ios/engine/KMEI/KeymanEngine/Classes/KeyboardMenuView.swift
- ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/KeyboardInfoViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/KeyboardPickerViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngine/Classes/TextField.swift
- ios/engine/KMEI/KeymanEngine/Classes/TextView.swift
- ios/keyman/Keyman/Keyman/AppDelegate.swift
- ios/keyman/Keyman/Keyman/MainViewController.swift
> [ios] unused calls

- windows/src/developer/TIKE/child/UfrmPackageEditor.dfm
- windows/src/developer/TIKE/child/UfrmPackageEditor.pas
> [Developer] Open packages page now opens browser

- windows/src/desktop/kmshell/xml/keyman_keyboardlist.xsl
- windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboardlanguageprofiles.pas
> [Windows] Untitled keyboards will now show the filename of the keyboard in Keyman UI

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/InfoActivity.java
- android/KMAPro/kMAPro/src/main/res/layout/activity_info.xml
- android/history.md
Fixes #960
Previously, the InfoActivity was displaying the app version in one view, and launching the help content in another Activity.
> [Android] Consolidate "Info" views

- ios/engine/KMEI/KeymanEngine/Classes/Extension/JSONDecoder.DateDecodingStrategy+ISO8601Fallback.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
> [ios] If a keyboard.json has no timezone in the last modified date string, then it will still install

- ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
> [ios] merge frozen keyboard fix to 11.0 alpha

- windows/src/engine/keyman/UfrmKeyman7Main.pas
- windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboardlanguageprofiles.pas
> [windows] Installation of keyboards in Windows avoids some side effects with refresh and additional system keyboards

- windows/src/desktop/history.md
- windows/src/desktop/kmshell/xml/help.xsl
- windows/src/desktop/kmshell/xml/keyman.xsl
- windows/src/desktop/kmshell/xml/locale.xml
- windows/src/developer/history.md
> [windows] Getting Started links are no longer relevant.

- windows/src/buildtools/build_standards_data/Keyman.System.BuildLibPalasoAllTags.pas
> [developer] Script subtags are now appended for more scripts in the Keyboard languages dialog.

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java
> [android] updateKMText was called with unescaped string in some contexts.

- web/source/kmwembedded.ts
- web/source/kmwosk.ts
> [web] Nextlayer property not transferred from base to prepended popup key.

- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.h
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m
- mac/history.md
> [Mac] Fixes #894 - Fixed invocation of keyAction (missing self param)

- mac/KeymanEngine4Mac/KeymanEngine4Mac.xcodeproj/project.pbxproj
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KMkeyViewProtocol.h
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.h
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/OSKView.h
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/OSKView.m
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KeymanEngine4Mac.h
- mac/history.md
The code itself is ready for review. I've marked this WIP because I'm not sure whether we want to target this for master (Keyman 11), stable (Keyman 10), or some kind of staging "beta" or "alpha" for Keyman 10.1 or whatever. Because this is just a refactoring, the priority is low. Once we decide what to do, the history.md file will need to be edited accordingly.
> [Mac] Refactored target-action call from keyView

- android/history.md
- ios/history.md
- web/history.md
- web/source/kmwembedded.ts
- web/unit_tests/CI.conf.js
- web/unit_tests/test.sh
> [web] If a layer has lower row count to default layer in embedded mode, then Keyman throws an error.

- ios/history.md
- ios/keyman/Keyman/Keyman/KMWebBrowser/BookmarksViewController.swift
> [iOS] #1060 - Bookmark add button enabled only when title/url have text

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/history.md
This cherry picks the commits from #1103 onto master
> [Android] Fix crashes when input connection or package name is null

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java
- android/history.md
Cherry-pick of #1121 onto master
> [Android] Validate keyboard ID when downloading keyboard from Keyman cloud

- windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.pas
- windows/src/developer/TIKE/main/UframeTextEditor.pas
- windows/src/global/delphi/general/UserMessages.pas
Arising from todo list in #1097 
(some commands not yet implemented; this is infrastructure)
> [Developer] Support context menu in text editor

- windows/src/developer/TIKE/actions/dmActionsTextEditor.dfm
- windows/src/developer/TIKE/actions/dmActionsTextEditor.pas
- windows/src/developer/TIKE/main/UframeTextEditor.pas
Arising from todo list in #1097
Wait on: #1135 (rebase)
> [Developer] Remove old popup menu and attach command event for new menu for text editor

- windows/src/developer/TIKE/actions/dmActionsMain.dfm
- windows/src/developer/TIKE/actions/dmActionsMain.pas
- windows/src/developer/TIKE/child/UfrmEditor.pas
- windows/src/developer/TIKE/child/UfrmKeymanWizard.pas
- windows/src/developer/TIKE/main/UframeTextEditor.pas
- windows/src/developer/TIKE/xml/app/editor/editor.js
Arising from todo list in #1097
> [Developer] Support printing from ACE text editor

- windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.App.pas
Just a missing test in the back end for path with empty string == new untitled project
> [Developer] Project window needs to support untitled projects

- windows/src/developer/TIKE/child/UfrmDebug.dfm
- windows/src/developer/TIKE/child/UfrmDebug.pas
- windows/src/developer/TIKE/debug/debugdeadkeys.pas
- windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.App.pas
- windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas
Arises from todo in #1097
Also fixes a couple of minor edge case issues with untitled projects and unused touch layout files
> [Developer] Track deadkeys more reliably in debugger

- windows/src/developer/TIKE/actions/KMDActionInterfaces.pas
- windows/src/developer/TIKE/actions/dmActionsTextEditor.pas
- windows/src/developer/TIKE/main/UframeTextEditor.pas
- windows/src/developer/TIKE/xml/app/editor/editor.js
> [Developer] Re-implement Convert-to-character command in web text editor

- windows/src/developer/TIKE/main/UframeTextEditor.pas
> [Developer] Show selected character range in character preview window, not just first character

- windows/src/developer/TIKE/child/UfrmKeymanWizard.pas
- windows/src/developer/TIKE/main/UframeTextEditor.pas
- windows/src/developer/TIKE/xml/app/editor/editor.js
> [Developer] Maintain selection in web editor when saving or refreshing text

- windows/src/README.md
- windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas
- windows/src/developer/history.md
- windows/src/developer/mk.bat
- windows/src/global/delphi/general/kmxfile.pas
- windows/src/global/delphi/general/utilfiletypes.pas
This is a cherry pick of PR #1158 to stable-10.0
> [Developer] Refactor merge keyboard info (stable)

- linux/keyman-config/keyman_config/install_kmp.py
caught in PR1202 after merge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1204)
> [linux] PR1202 typo should be KM_KMX

- linux/scripts/dist.sh
and updated PR test builds to make the tarballs to catch things like this before merge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1205)
> [linux] remove version call that snuck in to dist.sh

- linux/scripts/version.sh
bit of a hiccup when it found the android tag at similar number
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1215)
> [linux] only get the version from linux tags

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
- android/history.md
> [Android] (11.0) Fix crash when displaying preview key 

- linux/.gitignore
- linux/keyman-config/keyman_config/downloadkeyboard.py
- linux/keyman-config/keyman_config/install_window.py
- linux/keyman-config/keyman_config/list_installed_kmp.py
- linux/keyman-config/keyman_config/view_installed.py
- linux/keyman-config/keyman_config/welcome.py
- linux/keyman-config/km-config
Fixes : #1181 
new gui for km-config
based on look of ibus-setup
* listview of kmp on left
* buttons on right
tweak button positioning on the windows
title changed  to Keyman Configuration
after downloading and clicking install the download window now closes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1231)
> [linux] gui refresh

- windows/src/developer/TIKE/main/KeyboardParser.pas
- windows/src/developer/TIKE/project/Keyman.Developer.System.Project.kmnProjectFileAction.pas
- windows/src/global/delphi/general/UKeymanTargets.pas
> [Developer] Support Linux targets when building .kmx

- windows/src/developer/TIKE/actions/dmActionsMain.pas
- windows/src/developer/TIKE/child/UfrmMDIEditor.pas
- windows/src/developer/TIKE/main/Keyman.Developer.UI.ImportWindowsKeyboardDialogManager.pas
- windows/src/developer/TIKE/main/UfrmMain.pas
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProject.pas
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas
This PR also refactors a bit of repetitive code around opening projects and reduces some incidences of spaghetti referencing.
> [Developer] Opening or creating a new project saves and closes open editor files

- windows/src/desktop/history.md
- windows/src/desktop/inst/keymandesktop.wxs
- windows/src/desktop/kmshell/locale/kan-Knda-IN/locale.xml
> [Windows] Add Kannada localization (10.0 stable)

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/history.md
Fixes #1312
Cherry-pick of #1313
> [Android] Swap TextView positions when end < start

- web/package-lock.json
- web/package.json
- web/source/kmwbase.ts
- web/source/kmwdomevents.ts
- web/source/kmwexthtml.ts
- web/source/kmwkeyboards.ts
- web/source/kmwutils.ts
It's been a while since some of our development dependencies were properly updated; this PR seeks to fill that need.  Updating TypeScript from 2.9.x -> 3.1.x resulted in some new compilation errors that needed addressing.
> [Web] Development environment update

- linux/keyman-config/debian/control
- linux/keyman-config/keyman_config/downloadkeyboard.py
- linux/keyman-config/keyman_config/install_window.py
- linux/keyman-config/keyman_config/keyboard_details.py
- linux/keyman-config/keyman_config/welcome.py
use WebKit2 instead of WebKit
the changed signals ended up being simpler
Closes: #1201 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1349)
> [linux] migrate from webkit to webkit2

- windows/src/developer/TIKE/actions/dmActionsMain.pas
- windows/src/developer/TIKE/main/UfrmMain.pas
> [Developer] Current project should be shown in Developer title bar

- windows/src/developer/TIKE/child/UfrmKeymanWizard.pas
- windows/src/developer/TIKE/child/UfrmPackageEditor.pas
- windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.App.pas
- windows/src/developer/TIKE/main/UfrmMain.pas
- windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectFile.pas
- windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectLoader.pas
- windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectSaver.pas
- windows/src/developer/TIKE/project/Keyman.Developer.System.Project.kpsProjectFile.pas
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.ProjectFileUI.pas
- windows/src/developer/TIKE/xml/project/project.js
- windows/src/global/delphi/general/utilfiletypes.pas
1. Fixes #1306: MRU gets out of order because project view was not re-loading
2. Fixes #1146: Fixup untitled project and project display state persistence issues
3. Fix crash compiling a keyboard that isn't part of a project from keyboard editor
> [Developer] Fix bugs and regressions in Project Window

- linux/scripts/deb.sh
- linux/scripts/dist.sh
- linux/scripts/jenkins.sh
- linux/scripts/reconf.sh
This should allow the keyman-keyboardprocessor and ibus-keyman packages to build on jenkins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1364)
> [linux] update build scripts for jenkins for ibus-keyman and keyman-keyboardprocessor

- linux/keyman-config/km-package-install
gets lists of all languages
then gets new keyboards from each language
Closes: #1373 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1379)
> [linux] use search API to get list of keyboards for bash completion

- ios/history.md
Updates the iOS history.md file, since I forgot to properly curate it with a couple of recent PRs.
> [iOS] Changelog update

- web/source/kmwosk.ts
> [Web] Fixes accidental virtual-key case sensitivity.

- linux/ibus-keyman/src/keymanutil.c
This is particularly to handle where a multikmx kmp is installed and the individual kmp is also installed, especially when the versions don't match.
When processing a keyboard this iterates through keyboards already processed and checks if any are same kmx file and higher or same version. If so then don't install.
This will potentially slow things down for anyone with a lot of keyboards installed.
An alternative is to try to stop people installing multiple kmx esp at different versions, but people are liable to find ways around that so I've gone for this instead.
Also renames ibus_keyman_engine_new to ibus_keyman_engine_desc_new to make that less confusing because it returns a IBusEngineDesc, change some g_message to g_debug and fix a message typo
Closes: #1253 
Closes: #1211
---
This …
> [linux] check if kmx already processed at >= version

- windows/src/developer/TIKE/main/UframeBitmapEditor.pas
> [Developer] Large icons cause Keyman Developer to crash (unsupported icon format in Delphi / windows)

- linux/scripts/dist.sh
- linux/scripts/launchpad.sh
update launchpad.sh and fix dist.sh for keyman-keyboardprocessor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1419)
> [linux] build scripts update launchpad,fix dist

- windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.dfm
- windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.pas
Many references online (google 'cef prevent focus on loadurl'), e.g. https://stackoverflow.com/questions/29062426/dcef3-how-disable-focus-after-load-page?rq=1
> [Developer] Improve handling around overly enthusiastic focus changes with CEF

- linux.code-workspace
- linux/ibus-keyman/src/engine.c
adds `platform "linux desktop hardware native"`
`baselayout "kbdus.dll"`
`baselayoutAlt "en-US"`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1446)
> [linux] Linux options

- web/history.md
- web/source/kmwbase.ts
- web/source/kmwembedded.ts
- web/source/kmwnative.ts
- web/source/kmwosk.ts
- web/source/kmwrotation.ts
Puts the changes of #1452 into our alpha branch.
> [Web] alignInputs() API cherry-pick

- linux/Makefile
- linux/keyman-config/Makefile
- linux/keyman-config/keyman_config/get_info.py
- linux/keyman-config/keyman_config/ibus_util.py
- linux/scripts/reconf.sh
Closes: #1464 
also improves cleaning of keyman-config so that new files will be included in dist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1467)
> [linux] add missing files get_info and ibus_util

- web/source/kmwosk.ts
> [Web] Cherry-picks OSK layer logic fix

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Here are some default issue templates that I suggest we try using for 3rd parties to submit helpful issue reports. There are a bunch of repos that do a lot more than this -- and we could learn from them -- so am happy to tweak if anyone else has ideas.
> [meta] Update issue templates

- windows/src/developer/TIKE/child/UfrmPackageEditor.pas
> [Developer] Ensure button enabled state is updated after compiling package

- linux/.pbuilderrc
- linux/ibus-keyman/src/Makefile.am
- linux/scripts/cow.sh
test file missing for released source tarball
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1572)
> [Linux] missing dist testfile

- android/history.md
Classic case of software developer being "off by 1". This cleans up the recent history
> [android] Fix versions in history

- windows/src/desktop/history.md
- windows/src/desktop/setup/UfrmRunDesktop.pas
- windows/src/developer/history.md
> [Windows] Upgrading from 9 to 11 failed to upgrade keyboards and settings

- windows/src/developer/history.md
- windows/src/developer/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas
> [Developer] New Project Wizard wasn't adding metadata files to project

- windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.AppSource.pas
- windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas
- windows/src/developer/TIKE/xml/layoutbuilder/builder.js
> [Developer] Switching pages in touch layout editor now maintains selected platform, layout, etc

- windows/src/developer/TIKE/xml/project/project.js
- windows/src/developer/history.md
> [Developer] Project state was not being maintained between project page loads

- windows/src/developer/TIKE/main/Keyman.Developer.UI.UframeCEFHost.pas
- windows/src/developer/TIKE/xml/app/editor/editor.js
- windows/src/developer/history.md
> [Developer] Adjust focus to correct window when loading web view and editor

- windows/src/desktop/kmshell/locale/kan-Knda-IN/locale.xml
changed the font to "Noto Sans Kannada"
and shortened the text to fix the buttons
> [windows] Kannada localization file update

- windows/src/desktop/kmshell/locale/kan-Knda-IN/locale.xml
> [Windows] Changed to Kannada font and also short the text to fit in the buttons

- windows/src/developer/TIKE/xml/app/editor/editor.js
> [Developer] Ensure text editor resizes when window does

- windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas
Fixes sillsdev/keyman-issues#5835.
> [Developer] Crash when creating new touch layout in certain circumstances.

- windows/src/developer/TIKE/child/UfrmEditor.pas
- windows/src/developer/TIKE/main/UfrmMain.pas
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmProject.pas
Fixes #1589.
Note, due to line ending changes in one file, best to compare with ignore whitespace on.
> [Developer] Buttons in Distribution tab now work.

- linux/README.md
This updates the readme for getting setup for launchpad
> [linux] Update launchpad instructions

- mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj
- mac/Keyman4MacIM/Keyman4MacIM/Info.plist
- mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutWindowController.m
- mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutWindowController.xib
Issue [Mac] About box is stuck and has no controls #1529
I'd like feedback on the new look that I needed to use to make it visible.
> [Mac] Beta About Box seems stuck

- linux/scripts/launchpad.sh
In preparation for Keyman for Linux 11 stable release
This is staging to be merged right before creating `stable-11.0` branch
> [Linux] Have launchpad watch stable for Keyman 11 release

- web/history.md
- web/source/kmwosk.ts
Fixes #1628 for 11.0's stable version.
> [Web] OSK key layer assignment fix

- mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutBGView.m
- mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutWindowController.xib
Same as #1642 but doesn't start with "stable-", which apparently TC hates.
> [Mac] Mac stable about dark

- linux/keyman-config/README.md
Further cleanup to match keymanapp/help.keyman.com#23
> [Linux] Clean up readme about km-package in the command line

- android/KMAPro/kMAPro/build.gradle
- android/KMAPro/kMAPro/src/main/res/xml/file_paths.xml
* Fix master build failing on linter of file_paths.xml
* Fix nightly build failing due to syntax of applying the play-publisher plugin
(Reference Example 4 on https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block)
> [Android] Fix build issues (part 2)

- web/source/kmwembedded.ts
- web/source/kmwkeyboards.ts
- web/source/text/processor.ts
Corrects the following regressions within the current alpha:
* Longpress keys on embedded were often not being processed correctly.
* Desktop-based layouts on touch form factors were not changing layer properly.
> [Web] Alpha OSK regressions

- android/README.md
Just documenting some permissions for using the Android emulator in Linux
> [Android] Update readme for using emulator in Linux

- web/source/text/prediction/modelManager.ts
This small PR is designed to provide hooks for use in development of suggestion-selection UI toward our predictive text goals.  Nothing's actually providing input to the `ModelManager.predict` method yet.
> [Web] Sets up event infrastructure for predict/suggest messages.

- web/source/osk/visualKeyboard.ts
> [Web] Keycap interference fix

- web/source/kmwosk.ts
An 11.0-stable friendly version of #1676.
> [Web] Keycap interference fix (cherry-pick)

- linux/scripts/jenkins.sh
this should allow the jenkins builds to work
also should allow them to use the correct tier
If this works correctly I'll cherry-pick for beta and stable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/1670)
> [linux][master] jenkins and different tiers

- android/KMEA/app/src/main/res/values/dimens.xml
- web/source/kmwembedded.ts
- web/source/kmwnative.ts
- web/source/osk/banner.ts
- web/source/osk/bannerManager.ts
- web/source/osk/oskManager.ts
- web/source/osk/visualKeyboard.ts
- web/source/resources/osk/kmwosk.css
This PR is a starting point for creating suggestion elements to display in the suggestion banner. It borrows heavily from `OSKKey.generateKeyText()`
* Attach event listeners `invalidatesuggestions` and `suggestionsready` (untested)
* ~Add a test option `setPrediction` to manually insert suggestions from the KMW console~
(outdated screenshots removed. See further down on PR)
> [Web] Create suggestion elements

- web/source/osk/banner.ts
- web/source/osk/bannerManager.ts
- web/source/osk/oskManager.ts
- web/source/text/prediction/modelManager.ts
This should help address a few of the PR comments on #1677.
> [Web] ModelManager tweaks

- web/testing/regression-tests/.gitignore
- web/testing/regression-tests/README.md
- web/testing/regression-tests/index.html
- web/testing/regression-tests/interactive.js
- web/testing/regression-tests/karma.conf.js
- web/testing/regression-tests/node_src/config.js
- web/testing/regression-tests/node_src/keyname.js
- web/testing/regression-tests/node_src/test-host.js
- web/testing/regression-tests/node_src/util.js
- web/testing/regression-tests/package-lock.json
- web/testing/regression-tests/package.json
- web/testing/regression-tests/src/known-failures.js
- web/testing/regression-tests/src/test-runner.js
- web/testing/regression-tests/src/ui.js
- web/testing/regression-tests/test-builder.js
- web/testing/regression-tests/test.html
- web/testing/regression-tests/test.js
Replaces #1682 to remove dependency on if/else ladder fix.
Fixes #1652.
> [Web] Add regression test suite

- common/predictive-text/package-lock.json
I accidentally merged #1701 and #1700 into _my_ branch, and not `master`. This one merges those changes into master.
> [LMLayer] Merge two previous PRs into master >.<

- windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
- windows/src/developer/TIKE/main/KeymanDeveloperOptions.pas
- windows/src/developer/history.md
- windows/src/global/delphi/general/RegistryKeys.pas
Fixes #183, cherry-picked to stable 11.0
> [Developer] Workaround Chrome if/else ladder limitations

- windows/src/developer/TIKE/xml/layoutbuilder/builder.js
> [Developer]  Edits to subkey caps in Developer 11 would not apply.

- windows/src/developer/TIKE/xml/layoutbuilder/builder.js
Cherry pick of #1730 for stable-11.0
> [Developer] Fixes #1718. Edits to subkey caps in Developer 11 would not apply.

- windows/src/developer/history.md
- windows/src/developer/kmcmpdll/Compiler.cpp
> [Developer] Calls to non-Unicode versions of ctype functions could cause instability

- web/history.md
- web/source/kmwcallback.ts
> [Web 11.0] Adds upper-cased variant of showPinnedHelp API

- web/history.md
- web/source/text/kbdInterface.ts
> [Web] Adds upper-cased variant of showPinnedHelp API

- common/test/predictive-text/index.js
Small PR that fixes a bug that assumes an empty array will be coerced to
false. An empty array is actually true!
> [LMLayer-CLI] Fix argument parsing bug.

- ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngine/Classes/TextField.swift
- ios/engine/KMEI/KeymanEngine/Classes/TextView.swift
- ios/history.md
Fixes #1212. (11.0 stable)
A cherry-picked version of #1756.
> [iOS 11.0] Patches issue with LTR/RTL codepoints in context.

- developer/js/index.ts
Arose from bug found in keymanapp/lexical-models#34
> [Developer] Lexical model compiler should validate model ids found in packages while building

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
As noted in #1825, somewhere during this alpha process longpresses got broken.  Testing against master showed that it had nothing to do with #1825 (whew); it's actually been on master for a while.  (Yikes!)
At any rate, here's a fix for the underlying issue, along with a bit of extra robustness code to prevent outright crashes if similar issues arise in the future.  There was probably a somewhat recent change to lines 204-205 in KMKeyboard.java that triggered the break, though it'd take a bit of hunting to do a proper `git blame` assessment and find out exactly when and where it occurred.
Edit:  Looks like it happened in #1778 - there had been some extra work intended for a separate branch that looks to have been committed onto the fat-finger PR's branch instead.  As kind of expected, …
> [Android] Fixes Android longpress, adds robustness.

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/history.md
Cherrypick of #1709 into master
> [Android] Allow user to switch keyboard on lock screen (cherrypick)

- developer/js/lexical-model-compiler/build-trie.ts
- developer/js/tests/test-compile-trie.ts
Fixes #1866 
Side node: the `tsconfig.json` in that file needs some work; that or the file structure needs to be organized some so that the packages can use the compiled version properly.
> [Developer] Remove Object.values() in favour of Object.keys().

- mac/Keyman4MacIM/Keyman4MacIM/KMInputController.m
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/Categories/NSArray+Action.m
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/Categories/NSString+XString.m
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMCompStore.h
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMCompStore.m
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.h
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMXFile.h
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMXFile.m
- mac/history.md
> [mac] [cherry-pick] [11.0] Merge fixes for #1838, #1839, #1840 into 11.0

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsFragment.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- common/predictive-text/package-lock.json
- web/package-lock.json
Adds a small bit of infrastructure to enable a nice UI tweak.  We now report the actual language count in the Settings UI for the "Installed languages" button, where before it was actually a 'keyboard count'.
> [Android] Corrects 'installed language' count.

- ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelInfoViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
You can now even delete the last one
>  [ios] remove restrictions on deleting lexical models

- common/predictive-text/unit_tests/headless/worker-predict-trie.js
- common/predictive-text/worker/models/trie-model.ts
- web/history.md
- web/package-lock.json
Might have forgotten one small thing with #1897...
Fixes #1929.
> [LMLayer] Fixes double-space bug.

- ios/engine/KMEI/KeymanEngine/Classes/Settings/SettingsViewController.swift
Fixes #1950 which was "1 languages"
> [ios] one language or count languages

- ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/Settings/Settings.storyboard
- ios/engine/KMEI/KeymanEngine/Classes/Settings/SettingsViewController.swift
- ios/history.md
Fixes #1910.
Turns out we just needed to add a few constraints to the toggles, though there was a little extra necessary to make that possible.
> [iOS] UI Toggle Constraints

- ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelPickerViewController.swift
> [iOS] Download error failure handling

- oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj
This needs to merge to beta in order to be properly tested as part of the CI work.
> [iOS] Tweak certificate configuration for FirstVoices keyboards

- oem/firstvoices/ios/exportAppStore.plist
> [iOS] Add export plist detail for FV Keyboards

- developer/js/tests/test-punctuation.ts
- windows/src/test/unit-tests/Makefile
> [Developer] Include kmlmc tests in Developer build.

- web/history.md
- web/source/osk/banner.ts
> [Web] Reversion logic fix for predictive banner

- web/source/kmwutils.ts
> [Web] Error logging for internal events

- web/history.md
- web/source/kmwutils.ts
> [Web] Adds handling for pt and unitless font size specs

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
> [iOS] Fixes app intro keyboard picker tooltip

- windows/src/developer/TIKE/xml/kmw/index.html
- windows/src/developer/history.md
Fixes #1972.
This is because the code used an internal KeymanWeb function which was refactored in 12.0.
> [Developer] Character preview was not updating in mobile web touch test.

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
- android/history.md
Fixes #1538 
Fixes crashlytics [issue](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5673e410280a3dd14e9a4bb8e3717da0?time=last-seven-days&sessionId=5D72BB94009D00013924744D54540779_DNE_0_v2)
Recent refactoring has the JSON parsing in CloudRepository.java
This PR catches null-pointer exceptions.
> [Android] Update exception handling for CloudRepository

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
- ios/history.md
> [iOS] Fix for OSK scaling on app re-entry

- linux/history.md
- linux/keyman-config/keyman_config/install_kmp.py
Fix #1789 
Remove `download_source` (originally started in #1679)
> [Linux] remove download source

- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewModelProjectParameters.dfm
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewModelProjectParameters.pas
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.dfm
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas
- windows/src/developer/history.md
> [Developer] Clarify the project filename that will be created and simplify the mental model for Browse button in Project Template dialogs.

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
- ios/history.md
Fixes #2090.
Fixes #2093.
Reverts #2055.  The changes within it were the cause of #2093, so a better fix was put in place this time.
> [iOS] Fixes for system keyboard issues

- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProject.pas
Screenshot in keymanapp/help.keyman.com#44 will need to be updated once this is merged!
> [Developer] Fix typo: "mdoel" -> "model"

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
Slipped up a slight bit with the fix for #2093; this corrects the fix.
> [iOS] Fixes popup key misalignment

- ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift
> [iOS] Disables correct toggle when predict disabled

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/InfoActivity.java
- android/history.md
Fixes #1961 
Parse and use the major minor version string for online help.
* Remove unnecessary keyboard strings
> [Android] Use versioned help links

- windows/src/developer/TIKE/Tike.dpr
- windows/src/developer/TIKE/Tike.dproj
- windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmWordlistEditor.dfm
- windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmWordlistEditor.pas
- windows/src/developer/TIKE/help/Keyman.Developer.System.HelpTopics.pas
- windows/src/developer/TIKE/main/TextFileFormat.pas
- windows/src/developer/TIKE/main/UframeTextEditor.pas
- windows/src/developer/TIKE/main/UfrmMain.pas
- windows/src/developer/TIKE/project/Keyman.Developer.System.Project.modelTsProjectFile.pas
- windows/src/developer/TIKE/project/Keyman.Developer.System.Project.wordlistTsvProjectFile.pas
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.wordlistTsvProjectFileUI.pas
- windows/src/developer/TIKE/xml/app/editor/editor.js
- windows/src/developer/TIKE/xml/project/distribution.xsl
- windows/src/developer/TIKE/xml/project/models.xsl
- windows/src/developer/history.md
- windows/src/developer/kmconvert/Keyman.Developer.System.ModelProjectTemplate.pas
- windows/src/global/delphi/lexicalmodels/Keyman.System.WordlistTsvFile.pas
> [Developer] Basic Wordlist Editor

- web/source/kmwuitoolbar.ts
> [Web] Better subtag handling in Toolbar UI

- windows/src/developer/TIKE/xml/layoutbuilder/template-basic.keyman-touch-layout
> [Developer] Shift layer in basic touch layout template has incorrect modifier for period.

- windows/src/developer/TIKE/xml/layoutbuilder/builder.js
> [Developer] Adding or deleting a platform or layer and making no other changes does not stick in touch layout editor.

- developer/js/.npmignore
- developer/js/README.md
- developer/js/build.sh
- developer/js/package-lock.json
- developer/js/package.json
- docs/npm-packages.md
- resources/shellHelperFunctions.sh
This PR sets up `@keymanapp/lexical-model-compiler` for publishing by the TeamCity server.
It should be the following steps on the server:
1.  `./build.sh -test`
2. `./build.sh -version 12.0.${BUILD_NUMBER} -tier ${tier}`
3. `./build.sh -publish-to-npm -tier ${tier}`
See package uploaded here under the `dev` tag:
- https://www.npmjs.com/package/@keymanapp/lexical-model-compiler
Addresses #1995.
> [Developer] npm publishing (without lerna)

- web/history.md
- web/source/kmwdom.ts
- web/source/kmwdomevents.ts
Fixes issue noted during investigation of solutions for https://community.software.sil.org/t/do-not-hide-keyboard-on-blur/2598.
> [Web] Fixes setLastActiveElement for touch form factors

- developer/js/source/package-compiler/kmp-compiler.ts
- developer/js/source/package-compiler/kmp-json-file.ts
- developer/js/source/package-compiler/kps-file.ts
- developer/js/tests/fixtures/example.qaa.sencoten/example.qaa.sencoten.model.kmp.json
- windows/src/developer/TIKE/child/UfrmPackageEditor.dfm
- windows/src/developer/TIKE/child/UfrmPackageEditor.pas
- windows/src/developer/history.md
- windows/src/developer/kmconvert/Keyman.Developer.System.ModelProjectTemplate.pas
- windows/src/global/delphi/general/CompilePackage.pas
- windows/src/global/delphi/general/PackageInfo.pas
- windows/src/global/delphi/packages/Keyman.System.PackageInfoRefreshLexicalModels.pas
> [Developer] Remove model version from package metadata.

- windows/src/developer/TIKE/xml/layoutbuilder/builder.js
> [Developer] Dropping character from Character Map onto Touch Layout Editor now saves the change.

- web/history.md
- web/source/text/kbdInterface.ts
Fixes #2162.
Predictive text support within an engine supporting highly configurable keyboards is "fun."
> [Web] Blocks fat-finger calculations from changing OSK layers

- common/lexical-model-types/README.md
I made the primary documentation in the [@keymanapp/lexical-model-types](https://www.npmjs.com/package/@keymanapp/lexical-model-types) slightly more accessible to newbies trying to write their first custom model or word breaker.
> [Developer] Document @keymanapp/lexical-model-types

- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/history.md
> [iOS] Model installation - use of package version (12.0 stable)

- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
> [iOS] Model installation - use of package version

- web/history.md
- web/source/kmwdomevents.ts
- web/source/kmwkeyboards.ts
- web/source/text/kbdInterface.ts
- web/source/text/processor.ts
> [Web] Updates notifyKeyboard and uses of KNS (12.0 stable)

- windows/src/developer/TIKE/web/UmodWebHttpServer.pas
> [Developer] Fix netbios reference when retrieving list of addresses

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/LexicalModelPackageProcessor.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java
- android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/LexicalModelPackageProcessorTest.java
- android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/PackageProcessorTest.java
- android/history.md
> [Android] Use package version for lexical model version

- README.md
- android/.gitignore
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
> [Android] If analytics is disabled, the app may crash.

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Just trying to push up my PR count ;-)
Relates to #2203.
Already picked onto #2204 for stable-12.0
> [Android] One more check in another file for analytics

- windows/src/desktop/history.md
- windows/src/desktop/inst/keymandesktop.wxs
- windows/src/desktop/setup/RunTools.pas
> [Windows] [12.0] Upgrades from 11.0 and 12.0 were losing installed keyboards and settings.

- linux/Jenkinsfile
This allows to use a different approach for building packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2263)
> chore(linux): Add Jenkinsfile for package building

- android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
- android/KMEA/app/src/main/assets/keyboard.html
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/history.md
Fixes #2251
This disables predictions when system keyboard is entering a password
> fix(android): Cherrypick #2255 to master

- linux/Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2290)
> chore(linux): Pass parameters in Jenkinsfile

- linux/build/agent/dependencies.config
Also fix a typo in section name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2320)
> chore(linux): Update dependencies for Linux packaging

- linux/scripts/reconf.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2325)
> fix(linux): Fix Linux package build

- web/source/text/processor.ts
A simple `git rebase -i` 🍒 of #2287 - no code changes needed.
> cherry(web): Fixes mnemonic code handling issues

- windows/src/desktop/history.md
- windows/src/engine/keyman/UfrmKeyman7Main.pas
- windows/src/engine/keyman/keyman.dpr
- windows/src/engine/keyman/main.pas
- windows/src/engine/keyman32/K32_DBG.CPP
- windows/src/engine/keyman32/Keyman32.cpp
- windows/src/engine/keyman32/hookutils.cpp
- windows/src/engine/keyman32/hotkeys.cpp
- windows/src/engine/keyman32/hotkeys.h
- windows/src/engine/keyman32/k32_dbg.cpp
- windows/src/engine/keyman32/k32_globals.cpp
- windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp
- windows/src/engine/keyman32/keyboardoptions.cpp
- windows/src/engine/keyman32/kmhook_callwndproc.cpp
- windows/src/engine/keyman32/serialkeyeventclient.cpp
- windows/src/global/delphi/general/klog.pas
- windows/src/global/inc/keyman64.h
This is a cherry pick of #2297 and #2316 for stable-12.0
> fix(windows): Keyman crash and interop with Metro-style apps 🍒

- ios/engine/KMEI/KeymanEngine/Classes/SubKeysView.swift
Fixes #2299 for 12.0 stable
Cherry-pick of #2306 to stable-12.0
history.md will get updated on another PR
> fix(ios): System keyboard popup-key positioning confinement 🍒

- .editorconfig
Follow-up of code review comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2336)
> chore(common): Update .editorconfig

- windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas
If the On Screen Keyboard was closed when on a monitor other than the
primary monitor, it would restore to the primary monitor in the top-
left corner instead of the previous location.
This fix allows the OSK to be restored to another monitor, but still
avoids positioning the window off screen if the monitor has been
disconnected.
Fixes #2270.
> fix(windows): OSK restores to wrong monitor

- windows/src/desktop/history.md
- windows/src/developer/history.md
Yep, cherry-picking commits off cherry PRs. My head is going all twisty.
> chore: history.md 🍒🍒

- android/Samples/KMSample1/app/build.gradle
- android/Samples/KMSample1/build.gradle
- android/Samples/KMSample1/gradle.properties
- android/Samples/KMSample1/gradle/wrapper/gradle-wrapper.properties
- android/Samples/KMSample2/app/build.gradle
- android/Samples/KMSample2/build.gradle
- android/Samples/KMSample2/gradle.properties
- android/Samples/KMSample2/gradle/wrapper/gradle-wrapper.properties
- android/Tests/KeyboardHarness/app/build.gradle
- android/Tests/KeyboardHarness/build.gradle
- android/Tests/KeyboardHarness/gradle.properties
- android/Tests/KeyboardHarness/gradle/wrapper/gradle-wrapper.properties
- android/Tests/keycode/app/build.gradle
- android/Tests/keycode/build.gradle
- android/Tests/keycode/gradle.properties
- android/Tests/keycode/gradle/wrapper/gradle-wrapper.properties
- oem/firstvoices/android/app/build.gradle
- oem/firstvoices/android/build.gradle
- oem/firstvoices/android/gradle.properties
- oem/firstvoices/android/gradle/wrapper/gradle-wrapper.properties
This applies the updates from  #2279 and #2361 to the all the other Android projects: Sample and Test projects, and `/oem/firstvoices/android`.
> fix(android): Update build dependencies for Sample and Test projects

- web/unit_tests/CI.conf.js
> change(web): Updates unit test browser targets for CI

- web/package-lock.json
- web/package.json
- web/source/kmwdevice.ts
- web/source/kmwexthtml.ts
- web/source/osk/visualKeyboard.ts
- web/source/utils/version.ts
> [Web] Toolchain update (cherrypick)

- ios/engine/KMEI/KeymanEngine/Classes/KeyboardRepository/APIKeyboardRepository.swift
This should prevent another :fire: from occurring like the one triggered by the issues addressed by https://github.com/keymanapp/api.keyman.com/pull/20.
The app will now handle the failure state, rather than crashing when attempting to create a `Dictionary` with duplicate ids.  Unfortunately, Swift does not allow `try`-`catch`ing that particular error, so the language `Dictionary`'s initialization had to be rewritten accordingly.
Should the scenario ever arise again, we'll be able to see the following text in the app's log messages:
```
2019-11-22 10:54:29.435 [Error] [APIKeyboardRepository.swift:100] apiCompletionHandler(data:response:error:fetchCompletionHandler:) > Corrupt data detected in API returns - duplicate language codes: [en-us, fr-ca]
```
(Of course, the language codes in the …
> fix(ios): Crash prevention for (some) malformed language data from API

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/JSONUtils.java
- android/history.md
This PR fixes a few issues involving the Cloud Repository
1. Add some null checking to prevent crashes
2. This addresses an issue where a custom .kmp package is installed (which currently associates the first language listed in kmp.json). Trying to install additional languages listed in the kmp.json failed because the package ID info wasn't being propagated.
1. Install apk and launch Keyman
2. Install custom sil_tchad.kmp package (associates the first listed language Babalia Creole Arabic language)
3. Go to "Settings" --> Installed Languages, and cancel the keyboard catalog download
4. Hit the "plus" sign and select "Chadian Arabic" and install
5. Verify that language/keyboard pair is added
> [Android] Fix a few CloudRepository issues

- web/source/kmwdevice.ts
- web/unit_tests/CI.conf.js
- web/unit_tests/base.conf.js
- web/unit_tests/cases/attachmentAPI.js
- web/unit_tests/cases/basics.js
- web/unit_tests/cases/element_interfaces.js
- web/unit_tests/cases/touch_aliases.js
- web/unit_tests/test.sh
- web/unit_tests/test_init_check.js
- web/unit_tests/test_utils.js
Fixes #2379.
Follows up on issues noted in #2372.
A 🍒 of #2381.
> cherry(web): macOS Firefox detection/fire + test stability

- android/KMAPro/kMAPro/build.gradle
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/JSONParser.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtil.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDownloadMgr.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
- android/history.md
This PR is to improve the stability on app startup by preventing misc exceptions:
* Add null checks
* Don't throw `IllegalStateException` when a download ID isn't valid
* Per Firebase [release notes](https://firebase.google.com/support/release-notes/android#2019-01-31), replace `com.google.firebase:firebase-core` with `com.google.firebase:firebase-analytics`
> fix(android): Add checks to avoid exceptions

- android/KMEA/app/src/main/assets/keyboard.html
- common/predictive-text/index.ts
- common/predictive-text/message.d.ts
- common/predictive-text/package-lock.json
- common/predictive-text/package.json
- common/predictive-text/promise-store.ts
- common/predictive-text/worker/index.ts
- web/bulk_rendering/renderer_core.ts
- web/package-lock.json
- web/package.json
- web/source/build.sh
- web/source/dom/utils.ts
- web/source/kmwbase.ts
This is a 🍒 of #2358, now targeted against master.  (The original was against stable-12.0.)
> [Android] [Cherry] ES6 & API 19-23 compatibility changes

- ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableKeyboard.swift
- ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableLexicalModel.swift
- ios/history.md
Cherry pick of #2403.
Fixes #2418.
> fix(ios): prevents lowercased API returns from causing mismatches 🍒

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/history.md
Fixes StringIndexOutOfBoundsException on [Crashlytics](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/74f8209642c77218cc473098ee294ceb?time=last-seven-days&sessionId=5DEFABD703CE000144559FADAEE45C9D_DNE_0_v2)
Originally
```
if (sequence != null && Character.isLowSurrogate(sequence.charAt(0))) {
```
An exception was thrown where sequence had length = 0, and accessed index = 0.
> [Android][Stable]: Check substring length

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/history.md
Cherrypick of #2444 to master to fix `StringIndexOutOfBoundsException` on [Crashlytics](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/74f8209642c77218cc473098ee294ceb?time=last-seven-days&sessionId=5DEFABD703CE000144559FADAEE45C9D_DNE_0_v2)
> fix(android): Check substring length

- ios/history.md
- ios/keyman/Keyman/Keyman/AppDelegate.swift
> cherry(ios): Adhoc resource overwrite/file-replacement

- android/KMEA/build.sh
- web/source/build.sh
> fix(android): Removes Closure's auto-polyfills, adds test case bypass

- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngine/Classes/Settings/SettingsViewController.swift
Fixes #2464.
May also remedy or mitigate #2418.
> fix(ios): Prevents in-menu display / reset of keyboard

- ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LexicalModelPickerViewController.swift
> feat(ios): clean message + auto-return when no dictionaries available

- developer/js/source/model-info-compiler/model-info-compiler.ts
- windows/src/developer/history.md
Cherry-pick of #2388 to stable-12.0
> fix(developer): check if author email exists 🍒

- linux/scripts/jenkins.sh
This is an attempt to fix the Linux packaging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2515)
> chore(linux): fix Linux packaging

- windows/src/developer/TIKE/actions/Keyman.Developer.UI.dmActionsModelEditor.pas
- windows/src/developer/TIKE/actions/dmActionsKeyboardEditor.pas
- windows/src/developer/TIKE/main/KeyboardParser.pas
- windows/src/developer/TIKE/main/UframeOnScreenKeyboardEditor.pas
- windows/src/developer/TIKE/main/mrulist.pas
- windows/src/developer/kmconvert/Keyman.Developer.System.ModelProjectTemplate.pas
- windows/src/developer/kmconvert/data/wordlist-lexical-model/source/model.ts
Fixes #2525.
The following commits (one per problem) address the checklist issues discovered during testing.
> fix(developer): Address pre-beta checklist issues

- resources/build/build-utils.sh
- resources/build/increment-version.sh
- resources/build/version/.gitignore
- resources/build/version/README.md
- resources/build/version/package-lock.json
- resources/build/version/package.json
- resources/build/version/src/fixupHistory.ts
- resources/build/version/src/graphql/queries.ts
- resources/build/version/src/incrementVersion.ts
- resources/build/version/src/index.ts
- resources/build/version/src/util/spawnAwait.ts
- resources/build/version/tsconfig.json
- resources/build/version/tsconfig.production.json
The increment-version.sh script in this PR creates a pull request with updated history and version automatically. It searches for new PRs on keymanapp/keyman (since the last version increment) and will merge the titles into the appropriate version section of HISTORY.md; existing entries are left untouched.
The PR titles are used without changes; when the title is added to HISTORY.md, the increment-version.sh script will add ` (#<number>)` to the end of the line; these PR numbers are what it matches on when deciding whether to add new entries or not. Thus, we can tweak wording in HISTORY.md at any time without the effort of figuring out which PRs need to be present manually.
After merging in new pull request titles, if *any* HISTORY.md entries are found for the current version (whether or …
> chore(ci): increment version final

- linux/.pbuilderrc
- linux/scripts/cow.sh
- linux/scripts/launchpad.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2589)
> fix(linux): cherry-pick packaging changes from beta branch

- linux/scripts/jenkins.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2591)
> fix(linux): Display the script name in log output

- HISTORY.md
- resources/build/increment-version.sh
- resources/build/version/src/fixupHistory.ts
* Ensure latest history is uploaded in CI (was always uploading previous version only because new changes were in a branch).
* Add bullet points for HISTORY.md so it formats more nicely.
> chore(ci): Tweak history management

- .editorconfig
- linux/keyman-config/README.md
- linux/keyman-config/debian/control
- linux/scripts/jenkins.sh
This change checks that the required packages are installed and
if necessary installs them before trying to build a source
package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2599)
> fix(linux): Install requirements before packaging

- resources/build/build-utils.sh
- resources/build/run-required-test-builds.sh
- resources/build/trigger-builds.sh
- resources/build/trigger-definitions.sh
This is a beta 'cherry pick' of #2611. (Manually constructed 
because too many commits across multiple PRs)
> chore(ci): add build scripts for beta tests 🍒

- common/engine/keyboardprocessor/src/km_kbp_context_api.cpp
> fix(common/core): buffer overrun in context api 🍒

- .editorconfig
- linux/keyman-config/README.md
- linux/keyman-config/debian/control
- linux/scripts/jenkins.sh
Cherrypick linux packaging fixes from #2591, #2599, #2609 into beta
> fix(linux): Cherrypick linux packaging fixes 

- ios/history.md
- ios/keyman/Keyman/Keyman/MainViewController.swift
> fix(ios): Fixes invalid keyboard display when backing out of sharing text

- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
The `handleEvent` function call tree has "somewhat" convoluted logic around emitting the final transform to the client application. This starts to refactor that code to move all client interaction to a single point at the end of the event sequence.
Next phase will be to update delete and insert events to turn them into a single action where possible.
Deliberately putting this into master with the intent of making smaller refactors that we can more safely approve as not changing functionality. It's too late into the beta cycle to try and fix this in beta.
This is a start on the issues with start-of-context in several apps, e.g., from https://github.com/keymanapp/keyman/issues/2526:
>  b) New message in existing conversation, such that the message area has grayed out text: "iMessage") …
> refactor(mac): initial steps of input pathway

- windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas
Fixes sillsdev/keyman-issues#6231.
Fixes sillsdev/keyman-issues#6125.
Fixes sillsdev/keyman-issues#5914.
Fixes sillsdev/keyman-issues#5902.
Relates to #2656.
If you attempt to import a blank OSK into the touch layout editor,
nothing happens, but behind the scenes the state was corrupted, meaning
when you attempt to continue work at some point the app will crash.
> fix(developer): crash importing blank OSK

- configure-repo.sh
- resources/git-hooks/commit-msg
- resources/git-hooks/prepare-commit-msg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2701)
> refactor(common): Simplify and improve getting hook directory

- resources/build/run-required-test-builds.sh
- resources/build/trigger-builds.sh
- Output the result when triggering a Jenkins job
- Indent the output of triggering TeamCity jobs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2706)
> chore(ci): Improve output when triggering Jenkins jobs

- windows/src/developer/TIKE/Tike.dpr
- windows/src/developer/TIKE/Tike.dproj
- windows/src/developer/TIKE/child/UfrmKeymanWizard.dfm
- windows/src/developer/TIKE/child/UfrmKeymanWizard.pas
- windows/src/developer/TIKE/dialogs/Keyman.Developer.UI.UfrmMessageDlgWithSave.dfm
- windows/src/developer/TIKE/dialogs/Keyman.Developer.UI.UfrmMessageDlgWithSave.pas
- windows/src/developer/TIKE/dialogs/UfrmOptions.dfm
- windows/src/developer/TIKE/dialogs/UfrmOptions.pas
- windows/src/developer/TIKE/main/KeymanDeveloperOptions.pas
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.kmnProjectFileUI.pas
- windows/src/global/delphi/general/RegistryKeys.pas
Allow user to automatically save changes before compiling and similar options.
Fixes #2727.
> feat(developer): always save options

- web/history.md
- web/source/kmwutils.ts
> fix(web): support otf extension for truetype fonts 🍒

- web/unit_tests/CI.conf.js
> fix(web): Web CI fix 🍒

- ios/engine/KMEI/KeymanEngine/Classes/Model/Version.swift
- ios/keyman/Keyman/Keyman/InfoViewController/InfoViewController.swift
- ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift
A :cherries:-pick of #2773 for stable-13.0.
> fix(ios): Fixes online help link versioning

- ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
- ios/history.md
> fix(ios/engine): Fixes iOS char-delete context bug on newlines

- web/history.md
- web/source/kmwbase.ts
- web/source/osk/visualKeyboard.ts
- web/testing/build-visual-keyboard/index.html
- web/testing/index.html
Fixes #2784.  A 🍒-pick of #2802.
> fix(web): updating BuildVisualKeyboard

- android/KMAPro/kMAPro/src/main/AndroidManifest.xml
- android/KMAPro/kMAPro/src/main/res/layout/activity_info.xml
- android/KMAPro/kMAPro/src/main/res/layout/activity_package_installer.xml
- android/KMAPro/kMAPro/src/main/res/layout/activity_web_browser.xml
- android/KMAPro/kMAPro/src/main/res/layout/add_bookmark_dialog_layout.xml
- android/KMAPro/kMAPro/src/main/res/layout/bookmarks_list_layout.xml
- android/KMAPro/kMAPro/src/main/res/layout/bookmarks_row_layout.xml
- android/KMAPro/kMAPro/src/main/res/layout/get_started_list_layout.xml
- android/KMAPro/kMAPro/src/main/res/layout/get_started_row_layout.xml
- android/KMAPro/kMAPro/src/main/res/layout/get_started_toolbar.xml
- android/KMAPro/kMAPro/src/main/res/layout/text_size_controller.xml
- android/KMAPro/kMAPro/src/main/res/layout/update_count_view.xml
- android/KMAPro/kMAPro/src/main/res/layout/web_browser_bar_layout.xml
- android/KMEA/app/build.gradle
- android/KMEA/app/src/main/res/layout/keyboard_picker_list_layout.xml
- android/KMEA/app/src/main/res/layout/list_row_layout1.xml
- android/KMEA/app/src/main/res/layout/list_row_layout2.xml
- android/KMEA/app/src/main/res/layout/list_row_layout3.xml
- android/KMEA/app/src/main/res/layout/list_row_layout4.xml
- android/KMEA/app/src/main/res/layout/models_list_row_layout.xml
- oem/firstvoices/android/app/build.gradle
This PR starts to adjust layouts for RTL
Generally:  Left attributes --> Start attributes, Right attributes --> End attributes.
TODO on a separate PR
> feat(android): Start adding RTL to layouts

- web/source/osk/visualKeyboard.ts
> fix(web): applies base key layer property to unassigned subkeys 🍒

- common/predictive-text/worker/models/trie-model.ts
> fix(common/lmlayer): fixes word lookup from Tries for SMP script-based languages 🍒

- web/source/dom/contentEditable.ts
- web/source/dom/designIFrame.ts
- web/source/dom/utils.ts
- web/source/kmwdom.ts
- web/source/kmwdomevents.ts
- web/source/kmwuitoggle.ts
- web/source/osk/oskManager.ts
> fix(web): fixes design mode and content editable issues 

- ios/history.md
- web/history.md
- web/source/osk/banner.ts
- web/source/osk/visualKeyboard.ts
- web/source/resources/osk/kmwosk.css
> fix(ios): corrects OSK height adjustment, banner display issues

- .gitignore
- common/core/desktop/meson.build
- linux/keyman-config/MANIFEST.in
- linux/scripts/dist.sh
- linux/scripts/reconf.sh
This fixes `keyman-config` and `keyboardprocessor` package builds.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/2843)
> fix(linux): Fix failing Linux package builds

- windows/src/engine/tsysinfo/UfrmRemoteExceptionHandler.dfm
- windows/src/engine/tsysinfo/UfrmRemoteExceptionHandler.pas
- windows/src/engine/tsysinfo/sysinfo_main.pas
- windows/src/engine/tsysinfo/tsysinfo.dpr
- windows/src/engine/tsysinfo/tsysinfo.dproj
- windows/src/ext/sentry/Sentry.Client.pas
- windows/src/global/delphi/general/Keyman.System.KeymanSentryClient.pas
- windows/src/global/delphi/general/Upload_Settings.pas
This dialog is shown after an exception is processed and sent through to sentry.keyman.com. There are hidden hotkeys for tech info:
1. Ctrl+C - copy details to clipboard
2. Ctrl+Shift+C - copy more details to clipboard
3. Alt+DblClk on icon - open sentry site to event
4. Ctrl+DblClk on icon - show more details in message box
Example of what this looks like:
> feat(windows): new error notification dialog

- web/source/keyboards/kmwkeyboards.ts
- web/source/kmwbase.ts
- web/source/recorder_KeyboardScripts.js
- web/source/text/kbdInterface.ts
- web/testing/index.html
- web/testing/options-with-save/index.html
- web/testing/options-with-save/options_with_save.js
- web/unit_tests/CI.conf.js
- web/unit_tests/cases/engine.js
- web/unit_tests/json/engine_tests/options_with_save_1.json
- web/unit_tests/json/engine_tests/options_with_save_2.json
- web/unit_tests/json/keyboards/options_with_save.json
- web/unit_tests/resources/keyboards/options_with_save.js
Yeah... these have been broken for quite a while.
Fixes #2874.
Includes unit tests, since this feature never had any to begin with.  Note that it hasn't yet been refactored; this is only a fix.  Those make up the bulk of this PR's changes.
> fix(web): fixes variable stores

- web/source/dom/domEventHandlers.ts
- web/source/dom/domManager.ts
- web/source/keymanweb.ts
- web/source/kmwbase.ts
- web/source/text/kbdInterface.ts
- web/source/text/outputTarget.ts
- web/source/text/processor.ts
A bit of near-final prep before some of the bigger design-change refactoring takes place.
> refactor(web/engine): KeyboardInterface/Processor cleanup and prep

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
A 🍒-pick of #2951.  I've certain I've seen some of the issues it addresses in stable.
> fix(ios): prevents in-app keyboard resets

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
- ios/engine/KMEI/KeymanEngine/Classes/SubKeysView.swift
- web/source/kmwembedded.ts
> fix(ios): iOS 13.4 subkey menu workaround 

- common/predictive-text/unit_tests/in_browser/cases/worker-trie-integration.js
- common/predictive-text/unit_tests/in_browser/resources/models/naive-trie.js
- common/predictive-text/worker/models/trie-model.ts
- web/history.md
> fix(common/lmlayer): use searchTermToKey() on input

- web/testing/regression-tests/karma.conf.js
- web/testing/regression-tests/src/test-runner.js
There are a few notable API changes already that had broken regression testing; this PR fixes them up while resolving another issue or two I experienced on my local machine when trying to resolve them.
> fix(web):  repairs Web regression test suite

- developer/js/source/lexical-model-compiler/lexical-model-compiler.ts
- developer/js/source/lexical-model-compiler/lexical-model.ts
- developer/js/tests/test-compile-trie.ts
This cleans up the word breaker compilation code a little bit. This is some work to get ready to tackle #2753.
> refactor(common/lmlayer): word breaker compilation

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
- android/history.md
Cherrypick #3140 to stable-13.0
> fix(android): Fix system keyboard globe button override

- linux/ibus-keyman/debian/postinst
- linux/ibus-keyman/debian/postrm
This fixes #2183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/3169)
> fix(linux): Don't fail (un-)install if running multiple ibus

- common/core/desktop/debian/control
- common/core/desktop/debian/copyright
- linux/ibus-keyman/debian/control
- linux/ibus-keyman/debian/copyright
- linux/ibus-kmfl/debian/control
- linux/keyman-config/debian/control
- linux/keyman-config/debian/copyright
- linux/kmflcomp/debian/control
- linux/kmflcomp/debian/copyright
- linux/libkmfl/debian/control
Also some other small improvements in package metadata.
This fixes #2628.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/3168)
> chore(linux): Update maintainer in package metadata

- linux/ibus-keyman/debian/com.github.ibus.ibus-keyman.metainfo.xml
- linux/ibus-kmfl/debian/com.github.ibus.ibus-kmfl.metainfo.xml
- linux/keyman-config/debian/com.keyman.config.appdata.xml
- linux/keyman-config/debian/control
Closes #1596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyman/3176)
> feat(linux): Improve appstream metadata

- windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
- windows/src/developer/history.md
> fix(developer/compilers): normalise touch layout on compile

- windows/src/ext/sentry/Sentry.Client.pas
This updates Sentry integration to use the exception object which gives better tracking and consolidation over time, once we learned how to report the call stack more reliably.
> fix(windows): sentry exception reports

- windows/src/global/delphi/comp/KMDActions.pas
Fixes #2676. The Delphi shortcuts for copy/paste were overriding the
default shortcuts in the editor and focus control was not being recognised.
Fixes #2746. Undo and redo are now working again also with this fix. The drag and drop may be a little sensitive still, but given this fix, will consider that enough for now.
> fix(developer/ide): fix copy and paste in touch editor

- .gitignore
- linux/README.md
- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/run-tests.sh
- linux/keyman-config/tests/python.env
- linux/keyman-config/tests/test_ibus_util.py
- linux/keyman-config/tests/test_install_kmp.py
Also fix the indentation in `install_kmp.py`
> chore(linux): Add some unit tests for keyman_config

- .gitignore
- linux/build/agent/dependencies.config
Also contains a follow-up change of #3250
> chore(linux): Update automatically installed dependencies

- resources/web-environment/build.sh
Fixes #3258.
Implements the fix noted by @complinger [here](https://github.com/keymanapp/keyman/issues/3258#issuecomment-646418882).
> fix(common/resources): shebang for lerna-based Linux builds

- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngineDemo/MainViewController.swift
Cleans out a bit more notification-related stuff from the iOS project.
> refactor(ios/engine): more notification rework prep

- ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadManager.swift
- ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceDownloadQueue.swift
At present, KeymanEngine for iOS is entirely reliant on the iOS-provided `NotificationCenter` to distribute messages about successful and unsuccessful download attempts.  Unfortunately, this has led to quite a bit of decentralization for our download handlers, though recent PRs have cleaned this aspect up dramatically.
A better strategy moving forward - allow any download requests to specify an asynchronous callback.  This will come with a number of benefits:
- Download requests and downloaded-resource processing code can be implemented in the same function or method, rather than in separate areas of the code base.
- Unit testing will become much easier.
- Related classes will become more easily mockable.
To _start_ support for this, this PR performs a lot of type-reworking on the objects …
> refactor(ios/engine): reworks download queue objects

- .flake8
- linux/keyman-config/keyman_config/accelerators.py
- linux/keyman-config/keyman_config/convertico.py
- linux/keyman-config/keyman_config/dconf_util.py
- linux/keyman-config/keyman_config/downloadkeyboard.py
- linux/keyman-config/keyman_config/get_info.py
- linux/keyman-config/keyman_config/get_kmp.py
- linux/keyman-config/keyman_config/ibus_util.py
- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/keyman_config/install_window.py
- linux/keyman-config/keyman_config/keyboard_details.py
- linux/keyman-config/keyman_config/kmpmetadata.py
- linux/keyman-config/keyman_config/kvk2ldml.py
- linux/keyman-config/keyman_config/list_installed_kmp.py
- linux/keyman-config/keyman_config/options.py
- linux/keyman-config/keyman_config/uninstall_kmp.py
- linux/keyman-config/keyman_config/view_installed.py
- linux/keyman-config/keyman_config/welcome.py
This change adds a config file for flake8 Python linter and fixes
the problems the linter identified.
> refactor(linux): cleanup code

- windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas
- windows/src/desktop/setup/Keyman.Setup.System.OnlineResourceCheck.pas
- windows/src/desktop/setup/Keyman.Setup.System.ResourceDownloader.pas
- windows/src/desktop/setup/RunTools.pas
- windows/src/desktop/setup/UfrmRunDesktop.pas
- windows/src/desktop/setup/bootstrapmain.pas
Fixup constant strings; remove old dependencies; add update param
> chore(windows): code cleanup

- developer/js/source/lexical-model-compiler/build-trie.ts
- developer/js/tests/test-parse-wordlist.ts
A follow-up from a TODO in #3338.
> refactor(developer): hashmap-based wordlist compilation

- developer/js/source/lexical-model-compiler/build-trie.ts
- developer/js/tests/test-parse-wordlist.ts
> fix(developer/compilers): merge duplicate words during compile 🍒

- windows/src/desktop/setup/UfrmInstallOptions.pas
> feat(windows): disable defaults options when Keyman already installed

- windows/src/desktop/setup/SetupStrings.pas
- windows/src/desktop/setup/TntDialogHelp.pas
- windows/src/desktop/setup/UfrmInstallOptions.pas
- windows/src/desktop/setup/bootstrapmain.pas
> feat(windows): setup will retry if offline during initial install steps

- windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas
- windows/src/desktop/setup/Keyman.Setup.System.OnlineResourceCheck.pas
- windows/src/desktop/setup/SetupStrings.pas
- windows/src/desktop/setup/TntDialogHelp.pas
- windows/src/desktop/setup/UfrmHTML.dfm
- windows/src/desktop/setup/UfrmHTML.pas
- windows/src/desktop/setup/UfrmInstallOptions.pas
- windows/src/desktop/setup/UfrmRunDesktop.pas
- windows/src/desktop/setup/bootstrapmain.pas
- windows/src/desktop/setup/setup.dpr
- windows/src/desktop/setup/setup.dproj
- windows/src/global/delphi/general/Keyman.System.MITLicense.pas
- windows/src/unit-tests/windows-setup/Keyman.System.Test.InstallInfoTest.pas
> fix(windows): re-add license to setup

- linux/keyman-config/keyman_config/install_window.py
- linux/keyman-config/keyman_config/view_installed.py
- linux/keyman-config/setup.py
- fix import of GTK related modules
- improve setup.py
> refactor(linux): Small refactorings

- windows/src/desktop/setup/UfrmInstallOptions.pas
> fix(windows): hide unavailable options in Setup

- windows/src/desktop/setup/Keyman.Setup.System.OnlineResourceCheck.pas
- windows/src/desktop/setup/Keyman.Setup.System.ResourceDownloader.pas
- windows/src/desktop/setup/RunTools.pas
- windows/src/desktop/setup/UfrmDownloadProgress.pas
- windows/src/global/delphi/general/httpuploader.pas
> fix(windows): make sure silent is actually silent for setup

- windows/src/desktop/kmshell/xml/locale.xml
- windows/src/test/i18n-check-unused-strings/.gitignore
- windows/src/test/i18n-check-unused-strings/i18n-check-unused-strings.sh
This is in two parts:
1. A script to identify the unused strings
2. Removing the strings from the source locale.xml only (translated locale.xml will be dealt with when we import into Crowdin)
Note that there are a few strings that I have chosen not to remove (mostly Font Helper) because there are some unlocalized strings still present in the code. A couple of others I left because they are generic (e.g. "Close" button) and we will probably use them again soon.
Fixes part of #1200.
The report below was generated by i18n-check-unused-strings.sh; I have removed most of the **Not found** entries. Yes, there was a lot of legacy :smile:
Collected at: Tue, Jul 28, 2020  9:21:31 AM
Count | String | Flag
-------|--------|------
**0** | **S_LocaleAuthors** | **Not found**
21 | SK_UIFontName
3 | …
> feat(windows): Removes unused strings from locale.xml

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/InfoActivity.java
- android/build-help.sh
* Update build-help.sh to have option of getting content from local, staging, or production help site
* Update Info Activity to choose help.keyman host from tier
> feat(android): Use staging help site for pre-release builds

- windows/src/desktop/help/advanced/locale_edit.xml
- windows/src/desktop/help/start/locale.xml
I am not making any attempt to cleanup the formatting, etc, because that's a much bigger job. We'll need to revisit the formatting and preparation of the documentation in the future.
> feat(windows): docs on editing translations

- docs/settings/README.md
- docs/settings/linux/c_cpp_properties.json
- docs/settings/linux/extensions.json
- docs/settings/linux/launch.json
- docs/settings/linux/settings.json
While these files don't cover everything and all situations they
might provide at least some hints and can be adjusted or enhanced
as needed.
> chore: Add sample vscode settings files

- crowdin.yml
- linux/.gitignore
- linux/keyman-config/.editorconfig
- linux/keyman-config/Makefile
- linux/keyman-config/README.md
- linux/keyman-config/keyman_config/__init__.py
- linux/keyman-config/keyman_config/downloadkeyboard.py
- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/keyman_config/install_window.py
- linux/keyman-config/keyman_config/keyboard_details.py
- linux/keyman-config/keyman_config/options.py
- linux/keyman-config/keyman_config/view_installed.py
- linux/keyman-config/keyman_config/welcome.py
- linux/keyman-config/locale/keyman-config.pot
- resources/build/l10n/README.md
The first round on adding internationalization and localization on Linux.
> feat(linux): Add i18n for Linux

- windows/src/developer/kmconvert/data/basic-keyboard/source/readme.htm
- windows/src/developer/kmconvert/data/basic-keyboard/source/welcome.htm
- windows/src/developer/kmconvert/data/wordlist-lexical-model/source/readme.htm
- windows/src/developer/kmconvert/data/wordlist-lexical-model/source/welcome.htm
> feat(developer): add viewport to html templates

- windows/src/buildtools/signtime.bat
> fix(windows): use new signtime.bat on build agents 🍒

- windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.Debugger.pas
- windows/src/developer/TIKE/xml/kmw/packages.html
- windows/src/global/delphi/general/Upload_Settings.pas
Part of #3394.
Fixes two hard-coded URLs in the web debugger.
> fix(developer): hardcoded urls in debugger

- windows/src/Defines.mak
- windows/src/README.md
- windows/src/buildtools/getfilelocks/getfilelocks.vcxproj
- windows/src/developer/kmcmpdll/kcframe.vcxproj
- windows/src/developer/kmcmpdll/kmcmpdll.vcxproj
- windows/src/developer/kmdecomp/kmdecomp.vcxproj
- windows/src/developer/samples/imsample/IMSample.vcxproj
- windows/src/engine/keyman32/Keyman32.vcxproj
- windows/src/engine/keyman64/keyman64.vcxproj
- windows/src/engine/keymanx64/keymanx64.vcxproj
- windows/src/engine/kmtip/kmtip.vcxproj
- windows/src/engine/mcompile/mcompile.vcxproj
- windows/src/ext/tds2dbg/tds2dbg.vcxproj
- windows/src/support/enumtsfcpp/enumtsfcpp/enumtsfcpp.vcxproj
- windows/src/test/mnemonic-to-positional/importkeyboard/importkeyboard/importkeyboard.vcxproj
- windows/src/test/unit-tests/shared-data/cpp/cppshareddata.vcxproj
This removes the requirement for the Windows 8.1 SDK.
> chore(windows): Move to Windows SDK 10.0.17763.0

- windows/src/global/delphi/general/utilexecute.pas
Fixes #3679.
If keyman.exe is running with a non-elevated token, then it would fail to launch kmshell.exe non-elevated. This is a regression from the work in #3604.
> fix(windows): launch configuration non-elevated

- windows/src/engine/kmcomapi/com/languages/keymanlanguages.pas
> fix(windows): disabled keyboards listed in hotkeys

- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas
Fixes #3715.
This is a regression introduced in #1720.
> fix(developer): crash creating basic project

- common/core/web/keyboard-processor/src/text/defaultOutput.ts
- common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
- web/source/dom/domManager.ts
Extends #3664, fixing an issue noted there within embedded Android contexts.
> fix(web): K_SPACE handling for embedded mode, hardware keystrokes

- windows/src/global/delphi/ui/UfrmWebContainer.pas
Fixes #3755.
Help button in title bar of web apps will now do the same thing as F1.
> fix(windows): Make help button work

- windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas
- windows/src/desktop/kmshell/util/UfrmDownloadProgress.dfm
- windows/src/global/delphi/general/Keyman.System.UpdateCheckResponse.pas
- windows/src/global/delphi/general/Upload_Settings.pas
- windows/src/global/delphi/general/httpuploader.pas
> fix(windows): use new windows url for online update check

- windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas
- windows/src/desktop/kmshell/main/UfrmMain.pas
- windows/src/developer/TIKE/main/UfrmHelp.pas
- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmProject.pas
- windows/src/global/delphi/chromium/Keyman.UI.UframeCEFHost.pas
Fixes #3756.
Fixes KEYMAN-WINDOWS-5F.
Fixes KEYMAN-WINDOWS-5E.
> fix(windows): Crash in Keep in Touch external link

- windows/src/desktop/kmshell/main/UfrmMain.pas
- windows/src/desktop/kmshell/util/UILanguages.pas
- windows/src/desktop/kmshell/xml/elements.xsl
- windows/src/desktop/kmshell/xml/keyman.xsl
- windows/src/desktop/kmshell/xml/menu.css
- windows/src/desktop/kmshell/xml/menu.js
- windows/src/global/delphi/cust/CustomisationMessages.pas
Fixes #3750.
You may wish to review this commit-by-commit. The changes are related but scattered among multiple components. See commit messages for details on changes.
> fix(windows): Fix multiple issues with UI locales

- windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas
> fix(windows): error reading kmp.inf in setup

- common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
Fixes #3820.  Well, its underlying error.
> fix(common/core/web): adds missing null-check

- windows/src/developer/TIKE/update/Keyman.Developer.UI.TikeOnlineUpdateCheck.pas
- windows/src/developer/setup/UfrmRun.pas
- windows/src/global/delphi/general/Upload_Settings.pas
See also keymanapp/api.keyman.com#123
> feat(developer): support major version upgrades

- linux/.pbuilderrc
- linux/Jenkinsfile
- linux/scripts/cow.sh
- linux/scripts/launchpad.sh
> chore(linux): Additionally build packages for Ubuntu 20.10 (Groovy)

- android/Samples/KMSample1/app/build.gradle
- android/Samples/KMSample2/app/build.gradle
> fix(android/samples): Remove use of version.gradle in Sample projects

- mac/build.sh
Instead of updating the source plist files with version information, do this on the built artifacts so that the source files do not get continually clobbered.
> chore(mac): rewrite plists after build

- web/source/osk/visualKeyboard.ts
Fixes #3934.
From `testing/unminified.html`:
vs
> chore(web): adds LTREnter, LTRBkSp, and associated layout mapping

- web/source/kmwrotation.ts
- web/source/osk/preProcessor.ts
> fix(web): adds null guards for two Sentry errors

- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
Was using `NSString` instead of `NSURL`. Also tweaked debug logging.
> fix(mac/engine): wrong variable type

- resources/scopes/README.md
This documents keeping changes in resources/scopes with downloads.keyman.com/api/history
Per https://github.com/keymanapp/downloads.keyman.com/pull/30#discussion_r531206510
> chore(common/resources): Document keeping scopes in sync

- windows/src/buildtools/buildpkg/buildpkgmain.pas
- windows/src/desktop/setup/Makefile
- windows/src/developer/inst/kmdev.wxs
- windows/src/global/delphi/general/CompilePackageInstaller.pas
- windows/src/test/test_i3633/verify.dpr
> fix(windows): bootstrap installer not signed

- web/source/osk/visualKeyboard.ts
> fix(web/engine): findNearestKey erroneously returned key child

- windows/src/desktop/help/Makefile
Missed this during the help deployment changes
> chore(windows): also build web help

- web/source/osk/visualKeyboard.ts
Fixes #4102 
Fixes KEYMAN-WEB-19
This fixes  the linked Sentry issue
> fix(web/ui): Fix check on indexOf

- resources/build/trigger-definitions.inc.sh
These changes are made to force an update build
> chore: re-trigger beta

- windows/src/desktop/setup/UfrmRunDesktop.dfm
Fixes #4000.
Super important one this time.
> fix(windows): exit button position on setup

- web/source/resources/osk/kmwosk.css
This pull request attempts to solve the issues mentioned in https://github.com/keymanapp/keyman/issues/4153
> fix(web): Solving kmwosk color inconsistency

- windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas
- windows/src/global/delphi/chromium/Keyman.UI.UframeCEFHost.pas
Fixes #4001.
Stops navigation while holding Ctrl or Shift key taking over the whole dialog rather than staying within the iframe.
> fix(windows): prevent modifier key from navigating in download dialog

- windows/src/desktop/kmshell/web/Keyman.Configuration.System.HttpServer.App.ConfigMain.pas
- windows/src/global/delphi/web/Keyman.System.HttpServer.Base.pas
Keyboard icons were not showing in Keyman Configuration.
> fix(windows/config): keyboard icons missing

- windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas
Fixes #3000.
The model editor would save .model.ts files with Windows-1252 (aka ANSI) encoding, losing non-ANSI characters in the process.
While fixing this, noted that the class member `model` was not being used apart from in Load (no longer in Save), so reduced its scope accordingly.
> fix(developer): Encoding for .model.ts files

- web/source/resources/osk/kmwosk.css
Cherry-pick of #4154 into beta.
> fix(web): Solving kmwosk color inconsistency 🍒

- docs/linux-packaging.md
- linux/scripts/launchpad.sh
Also use new `alpha` ppa instead of previous `daily`.
> chore(linux): Allow to push to the `keyman-beta` ppa

- resources/build/trigger-builds.inc.sh
> fix(linux): only pass tag if we just created one

- common/predictive-text/worker/correction/classical-calculation.ts
- common/predictive-text/worker/correction/context-tracker.ts
- ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift
- web/source/dom/domEventHandlers.ts
#4208 and #4210 were meant to be applied against the `beta` branch, but it appears they were merged with `master` instead.
> chore: bugfix cherrypick (#4208, #4210)

- common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
Closes #3744.
Turns out `sil_philippines` is a mnemonic keyboard; related code paths were at fault.  While key-down events still triggered OSK changes, this was because of this block:
https://github.com/keymanapp/keyman/blob/e445e3d034162ab525c9adc9f696b391ed8bda96/common/core/web/keyboard-processor/src/text/keyboardProcessor.ts#L662-L665
Said block _immediately_ follows the adjusted, previously-bug-affected section and does _not_ need a backing `Lkc.Lcode` value.
> fix(common/core/web): mnemonic modifier key-up handling

- windows/src/engine/keyman/KeymanTrayIcon.pas
- windows/src/engine/keyman/UfrmKeyman7Main.pas
- windows/src/engine/keyman/UfrmKeymanMenu.dfm
- windows/src/engine/keyman/UfrmKeymanMenu.pas
- windows/src/engine/keyman/debug-manifest.in
Fixes #4013.
This turned out to be a lot more complicated than I expected, mostly due to limitations in the Windows Shell API with regard to multiple monitors and per-monitor DPI awareness (which we don't yet do in Keyman -- a task for another day). Some of the Shell API functions are also re-entrant, which is dangerous, so I avoided using those.
We now popup the menu relative to the Keyman icon far more precisely which gives a much nicer feel to the menu interaction.
This also fixes the menu popping up on the screen where the visual keyboard is visible, rather than the screen next to the icon.
Apologies for the number of screenshots below, but there were a lot of permutations to test. I tested on my Macbook with High DPI (2560x1600 @ 175%) on the laptop screen, and dual 1920x1080 …
> fix(windows): fix menu popup position

- web/source/kmwuibutton.ts
- web/source/kmwuifloat.ts
- web/source/kmwuitoggle.ts
- web/source/osk/visualKeyboard.ts
Fixes #99.
Note that this only affects the desktop UIs, as mobile form factors currently require an active keyboard to be present.
> fix(web): default kbd ui name is now generic

- windows/src/desktop/help/TODO.md
- windows/src/desktop/help/advanced/locale_edit.md
- windows/src/desktop/help/basic/config_tasks/hotkeys_tab.md
- windows/src/desktop/help/basic/config_tasks/keyboards_tab.md
- windows/src/desktop/help/basic/config_tasks/options_tab.md
- windows/src/desktop/help/basic/config_tasks/support_tab.md
- windows/src/desktop/help/basic/keyboard_tasks/enable_keyboard.md
- windows/src/desktop/help/basic/keyboard_tasks/uninstall_keyboard.md
- windows/src/desktop/help/basic/languageswitcher.md
- windows/src/desktop/help/basic/text_editor.md
- windows/src/desktop/help/basic/toolbox_tasks/charactermap.md
- windows/src/desktop/help/basic/toolbox_tasks/fonthelper.md
- windows/src/desktop/help/basic/toolbox_tasks/osk.md
- windows/src/desktop/help/basic/toolbox_tasks/toolbox.md
- windows/src/desktop/help/basic/traymenu.md
- windows/src/desktop/help/common/os.md
- windows/src/desktop/help/start/configure_computer.md
This cleans up the Keyman for Windows help in standardizing the markings for
* **Note:**
* **Tip:**
> chore(windows/resources): Cleanup Notes and Tips in help

- ios/exportAppStore.plist
> fix(ios): renew distribution certificate 🍒

- windows/src/desktop/kmshell/util/Keyman.System.KeymanStartTask.pas
Fixes #4116.
Fixes KEYMAN-WINDOWS-5T.
If we get an 'access denied' error, we won't report it to Sentry. This error is of minor consequence as it arises in normal configurations only if the task was already present, created by an elevated instance of kmshell under the same user name. In that situation, the task works fine; it just cannot be updated by a non-elevated instance of kmshell. If there are other reasons for receiving access denied, we won't be able to distinguish them anyway, so the best response is to suppress this message.
An alternative would have been to either (a) avoid creating the task as an elevated user, or (b) only ever create the task as an elevated user. However, this adds extra unnecessary complexity and means that the task may not always be present when we want it …
> fix(windows): Ignore Access Denied error creating task

- windows/src/desktop/kmshell/install/UfrmInstallKeyboard.pas
Fixes #3936.
This is a trial change as I am not able to reproduce the problem on my machine, probably due to timing.
@makarasok, can you please test if this resolves the UAC window not coming to foreground on your test scenario for #3936?
> fix(windows): Ensure UAC window comes to foreground

- windows/src/global/delphi/general/httpuploader.pas
Fixes #4385.
Chrome has ignored certificate revocation for many years. If it's good enough for Chrome, it's good enough for us. Right?
More seriously, sometimes Windows has trouble with its certificate revocation cache, and it seems to be difficult to predict when this will happen. This results in error 12057.
https://knowledge.broadcom.com/external/article/169185/ssl-visibility-how-to-resolve-the-certi.html
https://www.imperialviolet.org/2012/02/05/crlsets.html
> fix(windows): setup should ignore cert revocation

- linux/keyman-config/setup.py
Tell the Python build that we have a new module in a subdirectory.
Part of the improvements for #3399.
> fix(linux): Fix packaging

- linux/keyman-config/buildtools/build-langtags.py
- linux/keyman-config/keyman_config/bcp47tag.py
- linux/keyman-config/keyman_config/canonical_language_code_utils.py
- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/tests/test_bcp47tag.py
- linux/keyman-config/tests/test_canonical_language_code_utils.py
This is based on #4425. Also a few additional bug fixes that showed up on the way.
> fix(linux): improve BCP 47 canonicalization

- ios/engine/KMEI/KeymanEngine/Classes/Settings/SettingsViewController.swift
> chore(ios): Settings case-statement cleanup

- oem/firstvoices/common/build_keyboards.sh
- oem/firstvoices/ios/FVShared/FVShared.swift
- oem/firstvoices/ios/FirstVoices/FVKeyboardList.swift
- oem/firstvoices/ios/FirstVoices/ViewController.swift
- oem/firstvoices/ios/build.sh
> change(oem/fv/ios): FV keyboards now package-based

- windows/src/Makefile
- windows/src/desktop/history.md
Fixes #4484.
Cherry-pick of #4486.
> fix(windows): tsysinfox64 signature 🍒

- linux/keyman-config/km-package-list-installed
> feat(linux): Improve output of km-package-list-installed

- common/predictive-text/worker/model-compositor.ts
> fix(common/models): merges identical suggestions after casing

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
> chore(ios): web-side sentry enablement try-catch

- web/source/osk/oskManager.ts
> fix(web): removes package namespacing from kbd's CSS class

- web/history.md
- web/source/osk/visualKeyboard.ts
> fix(web): mobile layouts for static keyboards now %-based

- android/help/about/whatsnew.md
* List available display languages
* ~Add KMEA breaking changes (Most of the items from https://github.com/keymanapp/keyman/wiki/Keyman-13.0-to-14.0-Migration#android)~
> chore(android/app): Update whatsnew with available display languages

- windows/src/developer/TIKE/actions/dmActionsMain.pas
- windows/src/developer/TIKE/main/UfrmMain.pas
> fix(developer): Expand filenames before load

- android/KMAPro/kMAPro/src/main/res/values-km-rKH/strings.xml
- android/KMEA/app/src/main/res/values-km-rKH/strings.xml
- ios/engine/KMEI/KeymanEngine/km.lproj/Localizable.strings
- ios/keyman/Keyman/Keyman/km.lproj/Localizable.strings
- linux/keyman-config/locale/km_KH.po
- windows/src/desktop/kmshell/locale/km-KH/strings.xml
- windows/src/desktop/setup/locale/km-KH/strings.xml
Supersedes #4650 
Note iOS *.strings now diffed as UTF-8
> chore(common): Update crowdin for km

- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
Fixes #4058.
Fixes #4528.
Prevents duplicate keyboards from appearing in the list. If there are already duplicates in the list, they will be cleaned up the next time a keyboard is added or removed in Configuration.
> fix(mac): prevent duplicate keyboards in list

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Fixes #4688 and reverts part of #3825 to send embedded KMW console errors to Sentry
This will help provide additional info for tracking down Sentry errors.
Tested in chrome://devices with
```javascript
window.setTimeout( function() { throw "error";}, 10);
```
> chore(android/engine): Send KMW console errors to Sentry

- windows/src/desktop/kmshell/install/Keyman.Configuration.UI.KeymanProtocolHandler.pas
- windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas
> fix(windows): Download keyboard dialog TLS protocol support

- web/source/text/prediction/modelManager.ts
Fixes #4685.
A minor optimization was getting in the way... minor enough that it's better to just drop it than attempt to keep it and force a workaround.
> fix(web): allows refresh of currently-loaded model

- windows/src/desktop/kmshell/main/Keyman.Configuration.System.UImportOlderVersionKeyboards11To13.pas
> fix(windows): ensure profiles are reinstalled during setup

- windows/src/desktop/setup/RunTools.pas
- windows/src/desktop/setup/UfrmRunDesktop.pas
- windows/src/global/delphi/general/Keyman.System.UpgradeRegistryKeys.pas
> fix(windows): Avoid double start during setup

- ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift
> fix(ios): fixes sys-kbd setup help link for iOS 9 and 10 🍒

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java
🍒 -pick of #4790 for stable-14.0
Fixes NullPointerException in package installation
and improves UX of error messages during package installation
> fix(android): Fix NullPointerException in package installation

- ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
> fix(ios): ensures JS keyboard set after page load 🍒 

- windows/src/global/delphi/general/utilsystem.pas
> fix(developer): open containing folder was not opening correct folder

- windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
> fix(developer): requote font names

- android/help/start/installing-keyboards.md
Went off directions from @jahorton From step 5 I rewrote the sentence after "once the download is complete..." to make the wording less awkward and instructions more concrete. then "A" I rewrote to make it less jarring and more clearer transition to "B". Part "C" was rewritten with the same intention. Less jarring and more clarity.
> docs(android): Update installing-keyboards.md

- windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
Fixes #4810.
Cherry-pick of #4814.
> fix(developer): requote font names 🍒

- android/KMAPro/kMAPro/src/main/res/values-ff-rZA/strings.xml
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java
- android/KMEA/app/src/main/res/values-ff-rZA/strings.xml
- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/engine/KMEI/KeymanEngine/Classes/ff.lproj/ResourceInfoView.strings
- ios/engine/KMEI/KeymanEngine/ff.lproj/Localizable.strings
- ios/engine/KMEI/KeymanEngine/ff.lproj/Localizable.stringsdict
- ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
- ios/keyman/Keyman/Keyman/ff.lproj/Localizable.strings
- linux/keyman-config/locale/ff_ZA.po
- windows/src/desktop/kmshell/locale/ff-ZA/strings.xml
- windows/src/desktop/setup/locale/ff-ZA/strings.xml
Cherry-pick of #4822 checking in crowdin strings for Fulah into `master`.
> chore(common): Check in crowdin for Fulah 🍒 

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java
Cherrypick of #4858 for stable-14.0
Renames the display language from "Fula" to "Pulaar"
> chore(android/engine): Rename "Fula" to "Pulaar" 🍒 

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java
Cherrypick of #4865 to stable-14.0
> chore(android/engine): Rename "Pulaar" to "Pulaar-Fulfulde" 🍒 

- windows/src/global/delphi/packages/Keyman.System.PackageInfoRefreshLexicalModels.pas
cherrypick of #4863 to stable-14.0
> fix(developer): Reduce non-canonical BCP 47 tag warning in PackageInfo to Info 🍒 

- android/KMEA/app/src/main/res/values-fr-rFR/strings.xml
- ios/engine/KMEI/KeymanEngine/fr.lproj/Localizable.strings
- ios/keyman/Keyman/Keyman/fr.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/fr/strings.xml
- windows/src/desktop/setup/locale/fr/strings.xml
Cherrypick of #4895 to stable-14.0
> chore(common): Update crowdin for French 🍒 

- android/KMAPro/kMAPro/src/main/res/values-in-rID/strings.xml
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java
- android/KMEA/app/src/main/res/values-in-rID/strings.xml
- crowdin.yml
- windows/src/desktop/kmshell/locale/id-ID/strings.xml
- windows/src/desktop/setup/locale/id-ID/strings.xml
cherrypick of #4829 to stable-14.0
> chore(android,windows): Check in crowdin for Indonesian 🍒 

- web/source/dom/domEventHandlers.ts
- web/source/dom/touchAliasElement.ts
> change(web): adds error + console logs usable for Sentry reporting targeting 🍒

- common/core/web/keyboard-processor/src/keyboards/activeLayout.ts
- web/source/osk/visualKeyboard.ts
> fix(web): fixes subkey lookup for fat-finger processing 🍒

- web/source/osk/oskManager.ts
- web/testing/index.html
- web/testing/osk-movement/index.html
- web/testing/unminified.html
> fix(web): publish restorePosition() function 🍒

- common/core/web/keyboard-processor/src/keyboards/keyboard.ts
- ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
- web/source/keyboards/kmwkeyboards.ts
- web/source/keymanweb.ts
> fix(web, ios): better SMP, emoji handling with frequent keyboard swaps 🍒

- web/source/osk/bannerManager.ts
This is a patch-PR intended to modify/enhance the changes of #4961.
> change(web): tightens call signature for banner selection

- linux/keyman-config/keyman_config/handle_install.py
- linux/keyman-config/keyman_config/install_kmp.py
> fix(linux): Don't crash if kmp file vanishes (fixes #4907) 🍒

- linux/keyman-config/keyman_config/kmpmetadata.py
> fix(linux): Fix crash with incomplete metadata (#4908) 🍒

- web/source/dom/touchAliasElement.ts
> chore: disable findTouchAliasElement logging 🍒

- .github/multi-labeler.yml
> chore: Add cherry-pick label for cherry-pick PRs 🍒

- android/KMEA/app/src/main/assets/keyboard.html
- android/help/about/whatsnew.md
Fixes #4990 by checking for null string in toHex()
* Also as a chore, update the display language list in whatsnew.md
> fix(android/engine): Fix toHex() for null string

- android/KMEA/app/src/main/assets/keyboard.html
- android/help/about/whatsnew.md
Cherry-pick of #4991 to stable-14.0
> fix(android/engine): Fix toHex() for null string 🍒 

- mac/Keyman4Mac/Keyman4Mac.xcodeproj/project.pbxproj
- mac/Keyman4Mac/Keyman4Mac.xcodeproj/xcshareddata/xcschemes/Keyman4Mac.xcscheme
- mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj
- mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/xcshareddata/xcschemes/Keyman.xcscheme
- mac/Keyman4MacIM/Podfile
- mac/Keyman4MacIM/Podfile.lock
- mac/KeymanEngine4Mac/KeymanEngine4Mac.xcodeproj/project.pbxproj
- mac/KeymanEngine4Mac/KeymanEngine4Mac.xcodeproj/xcshareddata/xcschemes/KeymanEngine4Mac.xcscheme
- mac/README.md
> chore: support for xcode 12

- mac/Keyman4Mac/Keyman4Mac.xcodeproj/project.pbxproj
- mac/Keyman4Mac/Keyman4Mac.xcodeproj/xcshareddata/xcschemes/Keyman4Mac.xcscheme
- mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj
- mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/xcshareddata/xcschemes/Keyman.xcscheme
- mac/Keyman4MacIM/Podfile
- mac/Keyman4MacIM/Podfile.lock
- mac/KeymanEngine4Mac/KeymanEngine4Mac.xcodeproj/project.pbxproj
- mac/KeymanEngine4Mac/KeymanEngine4Mac.xcodeproj/xcshareddata/xcschemes/KeymanEngine4Mac.xcscheme
- mac/README.md
Fixes #4994.
Cherry-pick of #4995.
> chore: support for xcode 12 🍒

- HISTORY.md
> chore(common): update stable history for 14.0.273

- linux/.pbuilderrc
- linux/Jenkinsfile
- linux/scripts/cow.sh
- linux/scripts/launchpad.sh
> chore(linux): Add support for Ubuntu 21.04 (hirsute)

- linux/.pbuilderrc
- linux/Jenkinsfile
- linux/scripts/cow.sh
- linux/scripts/launchpad.sh
> chore(linux): Add support for Ubuntu 21.04 (hirsute) 🍒

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/InfoActivity.java
🍒 -pick of #5047 to stable-14.0
Only updating InfoActivity since the help documentation remains 14.0.
> chore(android/app): Always use offline help 🍒 

- android/KMAPro/kMAPro/src/main/res/values-az-rAZ/strings.xml
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java
- android/KMEA/app/src/main/res/values-az-rAZ/strings.xml
- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/engine/KMEI/KeymanEngine/Classes/az.lproj/ResourceInfoView.strings
- ios/engine/KMEI/KeymanEngine/az.lproj/Localizable.strings
- ios/engine/KMEI/KeymanEngine/az.lproj/Localizable.stringsdict
- ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
- ios/keyman/Keyman/Keyman/az.lproj/Localizable.strings
- linux/keyman-config/locale/az_AZ.po
- windows/src/desktop/kmshell/locale/az-AZ/strings.xml
- windows/src/desktop/setup/locale/az-AZ/strings.xml
Cherry-pick of #4992 to stable-14.0
> chore(common): Check in crowdin files for Azerbaijani 🍒 

- linux/ibus-keyman/README.md
- linux/ibus-keyman/src/engine.c
> fix(linux): Fix Caps Lock

- common/core/desktop/debian/changelog
- linux/ibus-keyman/debian/changelog
- linux/ibus-kmfl/debian/changelog
- linux/keyman-config/debian/changelog
- linux/keyman-config/debian/control
- linux/kmflcomp/debian/changelog
- linux/libkmfl/debian/changelog
> fix(linux): Swap order of dependencies for Debian package 🍒

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Cherry-pick of #5071 for stable-14.0
> fix(android/engine): Check lexical-model file exists before using 🍒 

- HISTORY.md
> chore(common): Update stable history for 14.0.274

- web/source/osk/visualKeyboard.ts
> fix(web): position popups correctly in landscape mode on Android and during Chrome emulation 🍒

- common/core/desktop/src/kmx/kmx_processevent.cpp
> fix(common/core/desktop): Don't segfault on invalid .kmx file

- android/KMAPro/kMAPro/src/main/res/values-am-rET/strings.xml
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java
- android/KMEA/app/src/main/res/values-am-rET/strings.xml
- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/engine/KMEI/KeymanEngine/Classes/am.lproj/ResourceInfoView.strings
- ios/engine/KMEI/KeymanEngine/am.lproj/Localizable.strings
- ios/engine/KMEI/KeymanEngine/am.lproj/Localizable.stringsdict
- ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
- ios/keyman/Keyman/Keyman/am.lproj/Localizable.strings
- linux/keyman-config/locale/am_ET.po
- windows/src/desktop/kmshell/locale/am-ET/strings.xml
- windows/src/desktop/setup/locale/am-ET/strings.xml
This adds the crowdin strings for `am` - Amharic.
TODO
> chore(common): Check in crowdin strings for Amharic

- android/KMAPro/kMAPro/src/main/res/values-am-rET/strings.xml
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java
- android/KMEA/app/src/main/res/values-am-rET/strings.xml
- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/engine/KMEI/KeymanEngine/Classes/am.lproj/ResourceInfoView.strings
- ios/engine/KMEI/KeymanEngine/am.lproj/Localizable.strings
- ios/engine/KMEI/KeymanEngine/am.lproj/Localizable.stringsdict
- ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
- ios/keyman/Keyman/Keyman/am.lproj/Localizable.strings
- linux/keyman-config/locale/am_ET.po
- windows/src/desktop/kmshell/locale/am-ET/strings.xml
- windows/src/desktop/setup/locale/am-ET/strings.xml
Cherry-pick of #5102 to stable-14.0
* Checks in crowdin strings for `am` - Amharic.
> chore(common): Check in crowdin strings for Amharic 🍒 

- linux/keyman-config/debian/control
This was already partially done in 695ee6fde (PR #5070), but we missed this line.
🍒 of PR #5113
> chore(linux): Swap order of dependency 🍒

- linux/keyman-config/README.md
- linux/keyman-config/debian/control
> chore(linux): Remove unnecessary dependency on kmflcomp

- oem/firstvoices/ios/exportAppStore.plist
> chore(ios): update fv cert ref 🍒

- android/README.md
- android/Samples/KMSample1/.idea/runConfigurations.xml
- android/Samples/KMSample1/app/build.gradle
- android/Samples/KMSample1/build.gradle
- android/Samples/KMSample1/build.sh
- android/Samples/KMSample1/gradle/wrapper/gradle-wrapper.properties
- android/Samples/KMSample2/.idea/runConfigurations.xml
- android/Samples/KMSample2/app/build.gradle
- android/Samples/KMSample2/build.gradle
- android/Samples/KMSample2/gradle/wrapper/gradle-wrapper.properties
- android/Tests/KeyboardHarness/app/build.gradle
- android/Tests/KeyboardHarness/build.gradle
- android/Tests/KeyboardHarness/gradle/wrapper/gradle-wrapper.properties
- oem/firstvoices/android/app/build.gradle
- oem/firstvoices/android/build.gradle
- oem/firstvoices/android/gradle/wrapper/gradle-wrapper.properties
Follow-on to #5098 and #5126
This updates the dependencies to the Android Sample apps and FV Android app.
* Also update targetSDKVersion to 30
> chore(android/samples,oem/fv/android) Update dependencies

- web/source/dom/domEventHandlers.ts
- web/source/dom/touchAliasElement.ts
> fix(web): multi touch handling 🍒

- ios/tools/prepRelease.sh
Mirrors #5140 for 14.0 stable, importing the original version of the script from our TeamCity configuration.
> chore(ios): artifact prep script now in-repo

- windows/src/desktop/README.md
- windows/src/developer/README.md
- windows/src/engine/README.md
Fixes #5118
This adds 3 README.md to /windows/src/desktop/ , windows/src/developer/ and /windows/src/engine. With the goal of giving a brief description of the build artifacts to assist in understanding the source layout and the architecture of the system.
> docs(windows): Initial commit - README.md

- linux/README.md
- remove mention of `scim_kmfl_imengine` which we recently removed
- reformat list of required packages
> docs(linux): Update readme

- common/core/desktop/debian/changelog
- linux/ibus-keyman/debian/changelog
- linux/ibus-kmfl/debian/changelog
- linux/keyman-config/debian/changelog
- linux/kmflcomp/debian/changelog
- linux/libkmfl/debian/changelog
🍒 from `stable-14.0` branch
It doesn't really matter what we have in the `changelog` in the `master` branch, but it makes things easier if we have it at least at the same version as in the `stable-14.0` branch.
> chore(linux): Update changelogs 🍒

- ios/help/about/history.md
- ios/help/index.md
- ios/keyman/Keyman/Keyman/InfoViewController/InfoViewController.swift
Fixes #4780.
While not dependent upon #5157, that PR makes me feel a _lot_ better about implementing this one.
> change(ios): help always offline

- ios/.gitignore
- ios/tools/prepRelease.sh
A 🍒-pick of #5160.
Once approved, I'll wait until a successful nightly before merging.
> fix(ios): artifact upload preparation 🍒

- android/KMAPro/kMAPro/build.gradle
- android/build.sh
- oem/firstvoices/android/app/build.gradle
🍒 -pick of #5145 to stable-14.0
This is so the Android CI configs can be updated to build on the Linux build agent
> chore(android): Add -clean flag to build script 🍒 

- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/keyman_config/keyboard_details.py
- linux/keyman-config/keyman_config/view_installed.py
Also fix two bugs introduced by recent refactoring.
Fixes #5184
> fix(linux): Don't crash on invalid metadata

- resources/build/jq.inc.sh
- web/tools/s_keyman_com.sh
🍒 -pick of #5150 to stable-14.0
This converts the CI PowerShell to Bash script for deploying KeymanWeb release to s.keyman.com
> feat(web): Add script to deploy KeymanWeb release to s.keyman.com 🍒 

- ios/keyman/Keyman/Keyman/MainViewController.swift
A 🍒-pick of #5173.  Please wait until an overnight `master` confirms that it properly addresses the issue with Apple.
> chore(ios): renames problematic app selectors 🍒

- windows/src/engine/keyman/UfrmKeyman7Main.pas
- windows/src/engine/keymanx64/keymanx64.cpp
Fixes #5196.
Fixes KEYMAN-WINDOWS-5K.
It is complicated to start a `UIAccess=true` process with `CreateProcess`, so instead we'll use `ShellExecute`. This means passing a PID instead of a process handle to keymanx64.
I took the opportunity to refactor slightly the main function in keymanx64, as the failure modes were pretty WET.
> fix(windows): start keymanx64 with ShellExecute

- linux/README.md
- linux/keyman-config/README.md
- linux/keyman-config/debian/control
- linux/keyman-config/keyman_config/fcitx_util.py
- linux/keyman-config/keyman_config/ibus_util.py
- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/keyman_config/install_window.py
- linux/scripts/jenkins.sh
This change implements the Keyman side of the fcitx5 integration. Also remove the big loop waiting for ibus.
Closes #4910.
> feat(linux): Integrate with fcitx5

- windows/src/developer/TIKE/debug/RegressionTest.pas
Fixes #5216.
A `<text>` element in the regression text xml which contained only whitespace would cause the import to crash as this would be ignored by the XML parser, leading to a `Null` `nodeValue` for that element. To solve this, we need to:
1. Use `xml:space="preserve"` attribute on `<text>` elements
2. Update the DTD to allow `xml:space` on `<text>` elements
3. While we are at it, move the DTD from `www.tavultesoft.com` to `api.keyman.com`.
See also:
* keymanapp/tavultesoft.com#4
* keymanapp/api.keyman.com#155
> fix(developer): support spaces in regression tests

- windows/src/developer/TIKE/debug/RegressionTest.pas
Cherry-pick of #5217.
Fixes #5216.
A `<text>` element in the regression text xml which contained only whitespace would cause the import to crash as this would be ignored by the XML parser, leading to a `Null` `nodeValue` for that element. To solve this, we need to:
1. Use `xml:space="preserve"` attribute on `<text>` elements
2. Update the DTD to allow `xml:space` on `<text>` elements
3. While we are at it, move the DTD from `www.tavultesoft.com` to `api.keyman.com`.
See also:
* keymanapp/tavultesoft.com#4
* keymanapp/api.keyman.com#155
> fix(developer): support spaces in regression tests 🍒

- web/source/build_kill_browserstack.sh
Follow-on to #5152 
This 🍒 -picks #5234 to stable-14.0
> fix(web): Always pass kill_browserstack 🍒 

- ios/README.md
- web/README.md
> docs(ios): minor readme tweak regarding prerequisites

- common/core/web/keyboard-processor/src/text/outputTarget.ts
- common/core/web/keyboard-processor/tests/cases/transcriptions.js
> fix(common/core/web): optimizes transform construction 🍒

- android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
- android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java
- oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java
> fix(android): rotation is not updating keyboard

- android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
- android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java
- oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java
Fixes #5211.
Cherry-pick of #5247.
> fix(android): rotation is not updating keyboard 🍒

- android/KMAPro/kMAPro/src/main/AndroidManifest.xml
- android/KMAPro/kMAPro/src/main/java/com/keyman/android/CheckInstallReferrer.java
- android/KMAPro/kMAPro/src/main/java/com/keyman/android/DownloadIntentService.java
- android/KMAPro/kMAPro/src/main/java/com/keyman/android/KmpInstallMode.java
- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/DownloadResultReceiver.java
- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadIntentService.java
Relates to #5230, #5219.
Cherry-pick of #5240.
> feat(android): silent install for referred kbd 🍒

- common/predictive-text/worker/correction/distance-modeler.ts
> fix(common/models): predictive-text engine use of NFD input 🍒

- common/core/web/keyboard-processor/src/keyboards/activeLayout.ts
- web/source/osk/visualKeyboard.ts
Turns out there was a fair amount of redundant recalculation that's very easy to eliminate.
> refactor(web): OSK layout calculations - simplification

- resources/build/run-required-test-builds.sh
This allows the script to run on macOS with brew-installed bash.
> chore(common): bash version for run-required-test-builds.sh

- ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
This is an attempt to address #5200.  Unfortunately, we lack a direct reproduction for the issue, so it's hard to know whether or not this will fix it.
> change(ios): setText now uses JSON serialization

- android/KMEA/app/src/main/assets/keyboard.html
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
> fix(android): fixes application of nextlayer for subkeys with customized layer setting 🍒

- common/core/web/input-processor/src/text/contextWindow.ts
- common/core/web/input-processor/src/text/inputProcessor.ts
- common/core/web/input-processor/src/text/prediction/languageProcessor.ts
- common/core/web/input-processor/tests/cases/inputProcessor.js
- common/core/web/keyboard-processor/src/text/outputTarget.ts
> feat(common/core/web): engine correction-prep optimizations 🍒

- linux/keyman-config/debian/changelog
- linux/keyman-config/debian/control
> fix(linux): Add libglib2.0-bin to keyman Depends

- linux/keyman-config/debian/changelog
- linux/keyman-config/debian/control
> fix(linux): Add libglib2.0-bin to keyman Depends 🍒

- windows/src/global/delphi/comp/OnScreenKeyboard.pas
Font scaling on individual keys would ignore the vertical axis if the horizontal axis reached the key width threshold, rather than calculating the minimum of the two axes. This lead to weird effects, such as adding characters to a key could make the font larger rather than smaller!
Before:
After:
Reported by @jmdurdin.
> fix(windows): osk scaling mismatch on horz axis

- windows/src/global/delphi/comp/OnScreenKeyboard.pas
Cherry-pick of #5341.
Font scaling on individual keys would ignore the vertical axis if the horizontal axis reached the key width threshold, rather than calculating the minimum of the two axes. This lead to weird effects, such as adding characters to a key could make the font larger rather than smaller!
Reported by @jmdurdin.
> fix(windows): osk scaling mismatch on horz axis 🍒

- linux/keyman-config/debian/keyman.bash-completion
- linux/keyman-config/km-config
- linux/keyman-config/km-config.bash-completion
- linux/keyman-config/km-kvk2ldml.bash-completion
- linux/keyman-config/km-package-get.bash-completion
- linux/keyman-config/km-package-install.bash-completion
- linux/keyman-config/km-package-uninstall.bash-completion
> fix(linux): fix tab completion for command line tools

- linux/keyman-config/keyman_config/keyboard_details.py
> fix(linux): Save QR code in temporary directory

- common/core/web/input-processor/tests/cases/inputProcessor.js
A handwritten 🍒-pick of #5404.
> change(common/core/web): fat-finger-performance unit-test threshold 🍒

- linux/keyman-config/keyman_config/keyboard_details.py
Fixes #5310. Partial 🍒-pick of #5373.
> fix(linux): Save QR code in temporary directory 🍒

- web/source/osk/oskManager.ts
Addresses #5296 for `stable-14.0`.
> fix(web): fixes osk resize-popping effect

- windows/src/buildtools/buildpkg/buildpkg.dpr
- windows/src/buildtools/buildpkg/buildpkg.dproj
- windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.App.pas
- windows/src/developer/TIKE/main/RedistFiles.pas
- windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectFile.pas
- windows/src/global/delphi/general/Keyman.System.Settings.pas
- windows/src/test/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dpr
- windows/src/test/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dproj
After the path refactor, here are some assumed paths that needed fixing.
> chore(developer): fixup devtime paths

- ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
> fix(ios): keyboard swapping 🍒

- common/core/desktop/include/keyman/keyboardprocessor_debug.h
- common/core/desktop/src/debug.hpp
- common/core/desktop/src/kmx/kmx_debugger.cpp
- common/core/desktop/src/kmx/kmx_debugger.h
- common/core/desktop/src/kmx/kmx_processevent.cpp
- common/core/desktop/tests/unit/kmnkbd/debug_api.cpp
Adds a first_action index to each debug event (not all debug events need it). This allows the debugger to partially execute a rule including the possibility of multiple updates to context.
> feat(common/core): debug action index 🐞

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Relates to #5509 - improve error log so we can clarify what is going wrong.
> chore(android): log fontpath error

- ios/kmbuild.sh
- ios/tools/prepRelease.sh
- oem/firstvoices/ios/build_common.sh
> feat(ios): adds option for Simulator-compatible testing artifact

- linux/keyman-config/keyman_config/view_installed.py
> fix(linux): Handle corrupt icon file

- linux/keyman-config/keyman_config/view_installed.py
Fixes #5584.
(🍒-picked from #5585)
> fix(linux): Handle corrupt icon file 🍒

- linux/debian/changelog
- linux/scripts/package-build.inc.sh
> fix(linux): Fix uploading to launchpad 📦

- windows/src/developer/TIKE/child/UfrmDebug.pas
- windows/src/developer/TIKE/debug/RegressionTest.pas
- windows/src/developer/TIKE/debug/debugdeadkeys.pas
- windows/src/developer/TIKE/debug/debugkeyboard.pas
> chore(developer): debug deadkey 1-based values 🐞

- windows/src/developer/TIKE/child/UfrmDebug.pas
This eliminates the confusing `SetForceKeyboard` function and `ForceKeyboard` function, and moves the keyboard loading into `SetupDebug`, where it should be. Doing this removes another state variable, simplifying the debugging state machine a little.
> chore(developer): refactor forcekeyboard in debug 🐞

- linux/scripts/package-build.inc.sh
> fix(linux): Fix uploading to launchpad for legacy projects 📦

- docs/linux-packaging.md
- linux/scripts/debian.sh
- allow to specify distribution
- document packaging for Debian
> chore(linux): Improve debian package script

- docs/linux-packaging.md
- linux/scripts/debian.sh
- allow to specify distribution
- document packaging for Debian
🍒-pick of #5624
> chore(linux): Improve debian package script  🍒

- windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
Relates to #4889.
Adds extra diagnostics to try and trace why we are getting a crash in rare cases when installing a keyboard language.
> test(windows): investigate TIP crash

- common/core/desktop/include/keyman/keyboardprocessor.h
- common/core/desktop/include/keyman/keyboardprocessor_version.h.in
- common/core/desktop/include/keyman/meson.build
- common/core/desktop/src/version.rc
> chore(common/core): cleanup version headers

- web/testing/index.html
- web/testing/inline-osk/index.html
Adds a page to experiment with the inline osk.
> chore(web): inline osk test page 🧵

- resources/build/run-required-test-builds.sh
This change allows branches from forked repos to trigger test builds.
Note: this will not be run automatically, but only when we manually tell it to run in TeamCity.
> chore(common): support forked repos when triggering test builds

- resources/build/help-keyman-com.sh
Ensures that the destination folder is cleaned before deployment.
> fix: help.keyman.com script file cleanup

- windows/src/desktop/help/advanced/proxy_config.md
- windows/src/desktop/help/context/index.md
> chore(windows): fix broken links in help

- windows/src/desktop/help/advanced/proxy_config.md
- windows/src/desktop/help/context/index.md
> chore(windows): fix broken links in help 🍒

- linux/scripts/debian.sh
> fix(linux): Fix debian package script

- linux/scripts/debian.sh
(:cherries: -picked from PR #5771)
> fix(linux): Fix debian package script 🍒 

- mac/help/start/install-keyman.md
Add a note on installing Keyman for macOS with homebrew
> docs(mac): Add note about installing with homebrew

- android/KMAPro/kMAPro/src/main/AndroidManifest.xml
- common/core/web/tools/sentry-manager/src/index.ts
- ios/engine/KMEI/KeymanEngine/Classes/Errors/SentryManager.swift
- linux/keyman-config/keyman_config/__init__.py
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
- oem/firstvoices/android/app/src/main/AndroidManifest.xml
- oem/firstvoices/windows/src/xml/sentry.init.js.in
- web/source/build.sh
- windows/src/desktop/kmshell/xml/sentry.init.js.in
- windows/src/developer/TIKE/xml/app/lib/sentry/init.js.in
- windows/src/ext/sentry/test/Sentry.Client.Test.SentryClientTestMain.pas
- windows/src/global/delphi/general/Keyman.System.KeymanSentryClient.pas
- windows/src/global/vc/keymansentry.cpp
Updates all the DSNs for sentry.io for all Keyman apps. Will cherry-pick
> chore: sentry.io dsn 👮‍♂️

- android/KMAPro/kMAPro/src/main/AndroidManifest.xml
- common/core/web/tools/sentry-manager/src/index.ts
- ios/engine/KMEI/KeymanEngine/Classes/Errors/SentryManager.swift
- linux/keyman-config/keyman_config/__init__.py
- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
- oem/firstvoices/android/app/src/main/AndroidManifest.xml
- oem/firstvoices/windows/src/xml/sentry.init.js.in
- web/source/build.sh
- windows/src/desktop/kmshell/xml/sentry.init.js.in
- windows/src/developer/TIKE/xml/app/lib/sentry/init.js.in
- windows/src/ext/sentry/test/Sentry.Client.Test.SentryClientTestMain.pas
- windows/src/global/delphi/general/Keyman.System.KeymanSentryClient.pas
- windows/src/global/vc/keymansentry.cpp
> chore: sentry.io dsn 👮‍♂️ 🍒

- web/unit_tests/cases/engine.js
> chore(web): disable registerstub test

- common/core/desktop/tests/unit/kmx/kmx.cpp
- common/core/desktop/tests/unit/kmx/kmx_test_source.cpp
- common/core/desktop/tests/unit/kmx/kmx_test_source.hpp
- common/core/desktop/tests/unit/kmx/meson.build
Extract common code to separate file so that the common code can be used in ibus-keyman tests.
> chore(common/core): refactor kmx unit tests 🎫

- linux/ibus-keyman/tests/ibusimcontext.c
Remove unnecessary functionality from test client. Part of #5613.
> chore(linux): Cleanup 🎫

- resources/devbox/iis-https/README.md
- resources/devbox/iis-https/v3.ext
> chore: add keyman-local.com to iis https setup

- linux/ibus-keyman/.gitignore
- linux/ibus-keyman/configure.ac
- linux/ibus-keyman/src/Makefile.am
- linux/ibus-keyman/src/keymanutil.c
- linux/ibus-keyman/src/keymanutil.h
- linux/ibus-keyman/src/test/Makefile.am
- linux/ibus-keyman/src/test/keymanutil_tests.c
> chore(linux): Update method comments

- common/core/desktop/debian/changelog
- linux/ibus-keyman/debian/changelog
- linux/ibus-kmfl/debian/changelog
- linux/keyman-config/debian/changelog
- linux/kmflcomp/debian/changelog
- linux/libkmfl/debian/changelog
> chore(linux): Update changelogs for 14.0.283 :package: 

- linux/debian/changelog
- linux/legacy/ibus-kmfl/debian/changelog
- linux/legacy/kmflcomp/debian/changelog
- linux/legacy/libkmfl/debian/changelog
> chore(linux): Update changelogs for 14.0.283 :package:  :cherries: 

- common/core/desktop/src/kmx/kmx_file.h
- common/core/desktop/tests/unit/kmnkbd/test_kmx_xstring.cpp
> refactor(common/core): Use defines in all xstring tests

- linux/.pbuilderrc
- linux/Jenkinsfile
- linux/scripts/cow.sh
- linux/scripts/launchpad.sh
> feat(linux): Add support for Ubuntu 22.04 Jammy

- linux/keyman-config/keyman_config/__init__.py
Fixes #5817.
(:cherries:- picked from PR #6052)
> fix(linux): fix release version number for Sentry reporting :cherries: 

- linux/debian/com.keyman.config.appdata.xml
- linux/debian/com.keyman.ibus_keyman.metainfo.xml
- linux/debian/control
- linux/debian/km-config.desktop
Also improve wording for Debian packages.
Fixes #5940.
> fix(linux): Fix package description

- windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.kpsProjectFileUI.pas
- windows/src/developer/TIKE/xml/kmw/packages.html
- windows/src/developer/TIKE/xml/kmw/packages.js
- windows/src/developer/TIKE/xml/kmw/test.css
Merges into #6033.
Tidies up the package download page in the web test view, making it clearer and less verbose, while offering more detail.
I think the screenshot is sufficient for testing :grin:
> feat(developer): tidy up package list in web test view 🛒

- windows/src/developer/TIKE/project/Keyman.Developer.System.Project.WelcomeRenderer.pas
> fix(developer): project_mru.xml path

- windows/src/ext/browse4folder/Browse4Folder.pas
- windows/src/global/delphi/keyman_components.dpk
- windows/src/global/delphi/keyman_components.dproj
> chore(developer): add browse4folder to components

- windows/src/Makefile
- windows/src/buildtools/devtools/Makefile
- windows/src/buildtools/sentrytool/Makefile
- windows/src/engine/keyman32/Makefile
- windows/src/engine/keyman64/Makefile
- windows/src/engine/tsysinfox64/Makefile
- windows/src/global/delphi/Makefile
Only comments formatted per earlier request from @ermshiperete.
> chore(windows): nmake makefile cleanup

- docs/build/linux-ubuntu.md
> docs: Enhance Linux build setup doc

- ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
- ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
> fix(mac): use xcframework to support m1

- docs/build/macos.md
> chore: update docs

- linux/legacy/kmflcomp/debian/changelog
- linux/legacy/libkmfl/debian/changelog
> fix(linux): Fix lintian errors

- linux/kmflcomp/debian/changelog
- linux/libkmfl/debian/changelog
(:cherries:-picked from PR #6106)
> fix(linux): Fix lintian errors :cherries: 

- web/source/kmwembedded.ts
Follow-on to #5651 and 🍒 -pick of #6100 to stable-14.0
This uses a regex to parse `keyName` which contains:
[display layer]-[virtual key name]+[optional function layer].
The 14.0 code doesn't have the KMW refactoring so `displayLayer` and `functionalLayer` are separately used later in kmwembedded.ts (ll. 439-440).
(The original PR just used the `matches[]` components without saving off `displayLayer` / `functionalLayer`)
Setup:
For each platform test, install the following keyboards (some were used in testing #5651):
1. ukwuani (zip of [source](https://github.com/keymanapp/keyman/files/7845806/ukwuani.zip))
2. sil_madi
3. sil_cameroon_qwerty
2. Test and verify sil_euro_latin keyboard:
a. Use the globe key to switch to sil_euro_latin keyboard
b. On the …
> fix(web): Use regex to determine display layer and functional layers 🍒 

- linux/debian/upstream/metadata
> chore(linux): Add metadata file for packaging

- web/source/osk/layouts/titleBar.ts
> fix(web): crash in setTitleFromKeyboard when no keyboard active

- common/core/desktop/debian/changelog
- linux/ibus-keyman/debian/changelog
- linux/ibus-kmfl/debian/changelog
- linux/keyman-config/debian/changelog
- linux/kmflcomp/debian/changelog
- linux/libkmfl/debian/changelog
> chore(linux): Update changelogs for 14.0.284

- linux/debian/changelog
- linux/legacy/ibus-kmfl/debian/changelog
- linux/legacy/kmflcomp/debian/changelog
- linux/legacy/libkmfl/debian/changelog
> chore(linux): Update changelogs for 14.0.284 :cherries: 

- .github/workflows/auto-merge-keyman-server-pr.yml
> fix: only auto-merge if `auto:` prefix in title

- .github/workflows/auto-merge-keyman-server-pr.yml
> fix: only auto-merge if `auto:` prefix in title 🍒

- linux/keyman-config/keyman_config/kmpmetadata.py
> chore(linux): Add comment for clarification of code behaviour

- linux/Jenkinsfile
> feat(linux): Replace hirsute with impish

- windows/src/engine/testhost/README.md
> chore(windows): testhost readme

- ios/exportAppStore.plist
> chore(ios): certificate update

- ios/exportAppStore.plist
> chore(ios): certificate update 🍒

- linux/Jenkinsfile
- linux/README.md
- linux/help/about/welcome.md
- linux/help/common/index.md
- linux/help/reference/index.md
- linux/scripts/build.sh
- linux/scripts/deb.sh
- linux/scripts/dist.sh
- linux/scripts/install.sh
- linux/scripts/jenkins.sh
- linux/scripts/package-build.inc.sh
- linux/scripts/reconf.sh
> chore(linux): stop releasing KMFL together with Keyman

- linux/debian/control
This will make it easier to upgrade or downgrade since all packages will be the same version.
> chore(linux): Improve dependencies in Linux package

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #6175 ; Follow-on to #1887, #5834
Change to Keyman Engine for Android API
* Add enum `GlobeKeyAction.GLOBE_KEY_ACTION_ADVANCE_TO_PREVIOUS_SYSTEM_KEYBOARD`
This way, when only 1 Keyman keyboard is installed as a system IME, the user can tap the globe key to revert to the previous system IME.
| Duration | # Keyman Keyboards Installed | Behavior |
|-----------|----------------------------------|------------|
| Short       | 1                                              | Switch to previous IME |
| Short       |  2+                                           | Switch to next Keyman keyboard |
| Long        |  1                                             | Keyboard picker menu |
| Long        |  2+                                          | Keyboard picker menu |
No change to globe-key …
> feat(android/engine): Single tap globe switch to previous system IME

- docs/CODEOWNERS
> chore(common): Add CODEOWNERS file

- linux/keyman-config/keyman_config/install_kmp.py
This change catches the exception we're getting if we try to create a directory but e.g. there is already a file with that name. In this case we now output an error message. This change also gracefully handles failures when linking files.
Fixes #6285.
- The Linux version doesn't matter for these tests.
- Install build artifacts of this PR
- Simulate the corrupt environment by running:
```bash
mv ~/.local/share/fonts ~/.local/share/fonts.bak
touch ~/.local/share/fonts
```
After running the tests if you don't restore a snapshot, you might want to run the following command to get things back into a working state:
```bash
rm ~/.local/share/fonts
mv ~/.local/share/fonts.bak ~/.local/share/fonts
```
**TEST_KB_INSTALL**: Install a keyboard
- On the command line run `km-config`, click "Download", …
> fix(linux): Gracefully handle makedirs failures

- docs/CODEOWNERS
> chore(common): tweak CODEOWNERS

- windows/src/developer/TIKE/xml/layoutbuilder/builder.xsl
> fix(developer): rename Code to ID in Touch Layout Editor ✂

- windows/src/developer/TIKE/actions/dmActionsMain.dfm
- windows/src/developer/TIKE/actions/dmActionsMain.pas
- windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.dfm
- windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas
- windows/src/developer/TIKE/child/UfrmKeymanWizard.dfm
- windows/src/developer/TIKE/child/UfrmPackageEditor.dfm
- windows/src/developer/TIKE/child/UfrmPackageEditor.pas
- windows/src/developer/TIKE/dialogs/Keyman.Developer.UI.UfrmServerOptions.dfm
- windows/src/developer/TIKE/dialogs/UfrmOptions.dfm
- windows/src/developer/TIKE/dialogs/UfrmOptions.pas
- windows/src/developer/TIKE/main/UfrmMain.dfm
Fixes #6326.
Tweaks wording and layout of screens relating to Keyman Developer Server for consistency.
> chore(developer): Keyman Developer Server terminology

- web/source/keyboards/kmwkeyboards.ts
We are seeing this error thrown in some logs but it masks the underlying error.
> fix(web): stop masking error

- web/source/keyboards/kmwkeyboards.ts
Cherry-pick of #6331.
We are seeing this error thrown in some logs but it masks the underlying error.
> fix(web): stop masking error 🍒

- LICENSE.md
- windows/src/LICENSE.md
- windows/src/desktop/help/about/license.md
- windows/src/desktop/inst/license.html
> chore(windows): Update license date

- linux/debian/changelog
- linux/debian/control
- linux/debian/copyright
- linux/ibus-keyman/tests/ibusimcontext.c
- linux/ibus-keyman/tests/ibusimcontext.h
> chore(linux): Update changelog and copyright 🐧

- common/core/desktop/debian/changelog
- linux/ibus-keyman/debian/changelog
- linux/ibus-kmfl/debian/changelog
- linux/keyman-config/debian/changelog
- linux/kmflcomp/debian/changelog
- linux/libkmfl/debian/changelog
> chore(linux): Update changelogs for 14.0.287 🐧

- .editorconfig
- linux/debian/copyright
> chore(linux): Address a few more lintian warnings 🐧

- linux/scripts/cow.sh
- linux/scripts/launchpad.sh
> chore(linux): Remove versions that are no longer supported 🐧

- ios/keyman/Keyman/Keyman/AppDelegate.swift
- ios/keyman/Keyman/Keyman/Classes/KMWebBrowser/BookmarksViewController.swift
- ios/keyman/Keyman/Keyman/Classes/LogoBackgroundView/KMUnderscoreView.swift
> chore(ios): stop lint complaints

- common/models/wordbreakers/package.json
> fix(common): wordbreakers package.json main field

- common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
> chore(web): remove unused `selectLayer` parameter

- windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas
- windows/src/developer/TIKE/xml/layoutbuilder/builder-charmap.js
- windows/src/developer/TIKE/xml/layoutbuilder/builder.js
- windows/src/developer/TIKE/xml/layoutbuilder/builder.xsl
Fixes #4854.
Adds some intelligence to the drag + drop integration with the Touch Layout Editor, so that we always drop a character onto a key cap, we always drop a code onto a ID field, and can drop both character + code together (if the key id is T_new_..., or holding Ctrl key).
Hovering over any key for 0.25 sec while dragging will select that key. You can then continue dragging down to the subkey array and drop onto any of those keys. Note that you do not need to hover for 0.25 sec before you drop onto a key -- the drop operation will select the key under the cursor when dropping.
Double-clicking will update the selected key or subkey; Ctrl will do both the key cap and the ID.
Demo video: https://youtu.be/qoLpuah72kw
This feature is conceptually fairly simple, but has a lot of nuance …
> feat(developer): improve Touch Layout Editor and Character Map integration

- web/source/keyboards/kmwkeyboards.ts
Cherry-pick of #6442
This is a follow-up for #6331. We still did not have enough detail to be able to trace the root cause of the load errors. This adds a little more diagnostics.
> fix(web): track load error detail 🍒

- android/help/about/system-requirements.md
Update in-app help to document the minimum required version of Chrome
> chore(android): Document minimum required version of Chrome

- linux/README.md
> docs(linux): Update testing section in readme

- mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
Fixes #6253. This will only show a message indicating failure to install but will not give a reason, which would require significantly more engineering.
Note, you may want to enable "Debug Logging" in Keyman Configuration / Options tab, and capture process:Keyman messages from Console, if there are issues completing these tests.
* **TEST_99:** Try installing package [the_99.kmp](https://downloads.keyman.com/developer/beta/15.0.219/keyboards/the_99.kmp). It should not be installable
* **TEST_KHMER:** Try installing Khmer Angkor -- it should install successfully
> fix(mac): check package fileVersion during install

- windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
> fix(developer): handle exception on unpaired surrogate

- mac/help/about/whatsnew.md
Update the Keyman help for 15.0
> chore(mac): Update whatsnew for 15.0

- ios/engine/KMEI/KeymanEngine/Classes/Constants.swift
- ios/engine/KMEI/KeymanEngine/Classes/Resource Data/Version.swift
Follow-up for #6486, fixes completely broken app...
> fix(ios): use CFBundleShortVersionString for version

- ios/engine/KMEI/KeymanEngine/Classes/Constants.swift
- ios/engine/KMEI/KeymanEngine/Classes/Resource Data/Version.swift
> fix(ios): use CFBundleShortVersionString for version 🍒

- windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
Fixes #6504.
Will cherry-pick to stable-14.0
> fix(windows): don't log before checking nil when installing keyboard

- windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
Fixes #6504.
Cherry-pick of #6505.
> fix(windows): don't log before checking nil when installing keyboard 🍒

- linux/debian/changelog
- linux/debian/control
This change updates the changelog to match what got uploaded to Debian.
> chore(linux): Update changelog file

- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/tests/test_install_kmp.py
Fixes #6256.
- The tests can be run on any Linux platforms
- Reboot
- Download the [the_99.kmp](https://build.palaso.org/repository/download/KeymanDesktop_TestPullRequests/315373:id/keyboards/index.html) keyboard package
- Download the [u_xxxx_yyyy_2858.kmp](https://build.palaso.org/repository/download/KeymanDesktop_TestPullRequests/315373:id/keyboards/u_xxxx_yyyy_2858/build/u_xxxx_yyyy_2858.kmp) keyboard package
**TEST_INST_CLI_NEW**: `km-package-install` refuses to install a keyboard for a newer Keyman version
- Run `km-package-install -f the_99.kmp` (in the directory where you downloaded `the_99.kmp`
- This should output an error: …
> fix(linux): test fileVersion during package install

- linux/debian/changelog
Add an entry to match what got uploaded to Debian.
> chore(linux): Update Debian changelog

- linux/debian/changelog
> chore(linux): Update changelog

- docs/settings/linux/tasks.json
- linux/build/agent/dependencies.config
Also update vscode task sample to configure ibus-keyman.
> chore(linux): Update Linux dependencies

- windows/src/desktop/help/about/requirements.md
- windows/src/desktop/help/about/whatsnew.md
- windows/src/desktop/help/common/old_version.md
- windows/src/desktop/help/common/os.md
Updates in-app help to include OS support for Windows 11.
Also updates whatsnew to reflect 15.0 changes according to the wiki on [new 15.0 functionality](https://github.com/keymanapp/keyman/wiki/Keyman-15.0-New-Functionality).
> docs(windows): Update OS and whatsnew in help

- developer/js/source/lexical-model-compiler/join-word-breaker-decorator.ts
- developer/js/source/lexical-model-compiler/script-overrides-decorator.ts
> chore(developer): fixup kmlmc imports 🎡

- common/predictive-text/build.sh
- resources/web-environment/build.sh
- web/source/build.sh
- web/source/build_dev_resources.sh
- web/source/tsconfig.dev_resources.json
- web/unit_tests/base.conf.js
Fixes the build for unit tests (and fixes corresponding bug in KMW build) to eliminate Lerna dependencies.
> chore(web): cleanup unit tests 🎡

- common/predictive-text/build.sh
- common/predictive-text/unit_tests/headless/edit-distance/classical-calculation.js
- common/predictive-text/unit_tests/headless/edit-distance/context-tracker.js
- common/predictive-text/unit_tests/headless/edit-distance/distance-modeler.js
- common/predictive-text/unit_tests/headless/worker-custom-punctuation.js
- common/predictive-text/unit_tests/headless/worker-dummy-integration.js
- common/predictive-text/unit_tests/headless/worker-initialization.js
- common/predictive-text/unit_tests/headless/worker-model-compositor.js
- common/predictive-text/unit_tests/headless/worker-predict-dummy.js
- common/predictive-text/unit_tests/headless/worker-predict.js
- common/predictive-text/unit_tests/in_browser/base.conf.js
- common/web/lm-worker/build.sh
> chore(web): fixup lmlayer test paths 🎡

- developer/js/.gitignore
- developer/js/build.sh
- developer/js/package.json
- developer/js/source/lexical-model-compiler/model-definitions.ts
- developer/js/tests/helpers/index.ts
- developer/js/tests/test-compile-model-with-pseudoclosure.ts
- developer/js/tests/test-join-word-breaker.ts
- developer/js/tests/test-override-script-defaults.ts
- developer/js/tests/test-punctuation.ts
- developer/js/tests/tsconfig.json
- developer/js/tsconfig.json
> chore(developer): build web-environment during js build 🎡

- developer/server/.gitignore
- developer/server/build-addins.inc.sh
- developer/server/build.sh
- developer/server/tsconfig.json
- resources/build/jq.inc.sh
> chore(developer): fixup server build without lerna 🎡

- developer/js/bundle.sh
> chore(developer): lexical model compiler bundling cleanup 🎡

- oem/firstvoices/ios/exportAppStore.plist
> chore(ios): FV certificate hash

- oem/firstvoices/ios/exportAppStore.plist
> chore(ios): FV certificate hash 🍒

- HISTORY.md
> chore: add 14.0 entries to beta HISTORY.md

- HISTORY.md
> chore: stable version

- resources/build/version/src/index.ts
> chore: fix version increment for force parameter

- resources/build/trigger-definitions.inc.sh
> chore: add trigger definitions for stable-15.0

- resources/build/trigger-definitions.inc.sh
- resources/build/version/src/index.ts
Cherry-picked from stable-15.0 release build process in #6773, #6774.
> chore: add trigger definitions for stable-15.0 and fixup force param for increment-version.sh 🍒

- common/test/keyboards/build.sh
- developer/src/Makefile
- developer/src/inst/Makefile
- developer/src/inst/download.in.mak
- developer/src/inst/node/dist/Keyman_README.md
- developer/src/kmlmc/Makefile
- developer/src/server/Makefile
- developer/src/server/build-addins.inc.sh
- developer/src/server/build.sh
- developer/src/server/postbuild.sh
- developer/src/server/src/win32/README.md
- developer/src/server/src/win32/console/README.md
- developer/src/server/src/win32/trayicon/README.md
- developer/src/server/tsconfig.json
- developer/src/tike/main/Keyman.Developer.System.KeymanDeveloperPaths.pas
- package.json
- tsconfig.json
Adds kmlmc and server to the Developer makefile
> chore(developer): fixup server paths and build 🎢

- common/windows/delphi/Defines.mak
- common/windows/mkver.sh
- windows/src/Defines.mak
> chore(windows): move mkver.sh to common 🎢

- linux/debian/changelog
> chore(linux): Update Debian changelog 🐧

- linux/debian/changelog
> chore(linux): Update Debian changelog 🍒 🐧

- ios/exportAppStore.plist
- oem/firstvoices/ios/exportAppStore.plist
> chore(ios): add manageAppVersionAndBuildNumber=false 🍒

- web/tools/check-build-size.sh
> chore(web): shorten check/web/file-size check message

- ios/keyman/Keyman/SWKeyboard/KeyboardViewController.swift
> fix(ios): eliminates conditional height for banner image 🍒

- web/source/osk/visualKeyboard.ts
> fix(web): clears repeating bksp on keyboard reload ⬅️ 🍒

- web/source/osk/oskView.ts
A 🍒-pick of #6854.  I just picked a different name that might be a bit more meaningful for the stable changelog.
The user tests on the base branch should easily be sufficient here; the codebase hasn't diverged much since release and the scope of changes is extremely constrained here.
> fix(web): better stability during transient OSK load state 🍒 

- web/README.md
Leftover work from last time I booted to macos ;-)
> chore(web): update readme

- windows/src/developer/TIKE/child/UfrmPackageEditor.pas
Fixes #6922.
Cherry-pick of #6926.
> fix(developer): QR Code for Package Editor had wrong path 🍒

- developer/src/common/delphi/compiler/compile.pas
- developer/src/kmcmpdll/Compiler.cpp
- developer/src/kmcomp/main.pas
If `-no-compiler-version` is specified, then we skip the embedding of the `TSS_COMPILEDVERSION` and `TSS_KEYMANCOPYRIGHT` stores. This is intended for use with regression test builds of keyboards when we want to verify changes to the compiler.
This patch introduces the new export `SetCompilerOptions` in kmcmpdll, which should make it easier to include new options like this in future versions.
> feat(developer): Option to skip embed of compiler version 🚦

- common/core/web/input-processor/src/text/prediction/languageProcessor.ts
> chore(web): remove invalid warning msg 🍒

- linux/keyman-config/buildtools/build-langtags.py
- linux/keyman-config/keyman_config/accelerators.py
- linux/keyman-config/keyman_config/canonical_language_code_utils.py
- linux/keyman-config/keyman_config/check_mime_type.py
- linux/keyman-config/keyman_config/convertico.py
- linux/keyman-config/keyman_config/downloadkeyboard.py
- linux/keyman-config/keyman_config/fcitx_util.py
- linux/keyman-config/keyman_config/get_info.py
- linux/keyman-config/keyman_config/get_kmp.py
- linux/keyman-config/keyman_config/gnome_keyboards_util.py
- linux/keyman-config/keyman_config/gsettings.py
- linux/keyman-config/keyman_config/handle_install.py
- linux/keyman-config/keyman_config/ibus_util.py
- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/keyman_config/install_window.py
- linux/keyman-config/keyman_config/keyboard_details.py
- linux/keyman-config/keyman_config/kmpmetadata.py
- linux/keyman-config/keyman_config/kvk2ldml.py
- linux/keyman-config/keyman_config/list_installed_kmp.py
- linux/keyman-config/keyman_config/options.py
- linux/keyman-config/keyman_config/uninstall_kmp.py
- linux/keyman-config/keyman_config/view_installed.py
- linux/keyman-config/keyman_config/welcome.py
- linux/keyman-config/km-package-install
> chore(linux): Code cleanup

- linux/keyman-config/keyman_config/uninstall_kmp.py
> fix(linux): Fix uninstallation when using fcitx5

- linux/keyman-config/keyman_config/uninstall_kmp.py
Fixes #6962
(:cherries:  picked from #6963)
> fix(linux): Fix uninstallation when using fcitx5 :cherries: 

- linux/debian/changelog
(:cherries:  picked from #6972)
> chore(linux): Update Debian changelog :cherries: 

- linux/.pbuilderrc
- linux/Jenkinsfile
- linux/scripts/cow.sh
- linux/scripts/launchpad.sh
And remove builds for outdated Impish.
> chore(linux): Add support for Ubuntu 22.10 "Kinetic Kudu"

- windows/src/developer/TIKE/Tike.dpr
- windows/src/developer/TIKE/main/UfrmMain.pas
Cherry-pick of #6941.
Fixes #6928.
> fix(developer): crash on exit when checking for updates 🎾 🍒

- developer/src/tike/compile/CompileKeymanWeb.pas
Relates to https://community.software.sil.org/t/rule-for-touch-layout-question/6482/6
> fix(developer): improve error message for multi-part key ids on <15.0 🎾

- windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
Relates to https://community.software.sil.org/t/rule-for-touch-layout-question/6482/6
> fix(developer): improve error message for multi-part key ids on <15.0 🎾 🍒

- linux/debian/changelog
> chore(linux): Update debian changelog 🍒

- docs/linux-packaging.md
- linux/scripts/upload-to-debian.sh
- resources/build/build-utils.sh
- resources/shellHelperFunctions.sh
- Create and sign source package
- Upload to mentors.debian.net
- Create (and optionally push) commit with updated changelog file based on stable branch
- Create (and optionally push) commit with updated changelog file based on master branch
> chore(linux): Add script to upload to debian

- linux/scripts/upload-to-debian.sh
> chore(linux): Add code comment

- developer/src/server/src/index.ts
Some models are larger than 10MB.
Ref: https://community.software.sil.org/t/text-suggestion-not-working-in-some-cases/6490
> fix(developer): increase maximum file size for server 🎾

- developer/server/src/index.ts
> fix(developer): increase maximum file size for server 🎾 🍒

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Just incorporates some additional fields and instructions that I have noted over time.
> chore(common): GitHub issue template tweaks

- docs/linux-packaging.md
- linux/scripts/upload-to-debian.sh
- resources/build/build-utils.sh
- resources/shellHelperFunctions.sh
- Create and sign source package
- Upload to mentors.debian.net
- Create (and optionally push) commit with updated changelog file based on stable branch
- Create (and optionally push) commit with updated changelog file based on master branch
This change also slightly modifies `echo_heading` and outputs a mark. This will show to the left of the line as well as in the
scroll bar in a terminal in VSCode [[1]] and will help to find the headings if you have a lot of output in between.
[1]:https://code.visualstudio.com/updates/v1_69#_setmark-sequence-support
(🍒-picked from PRs #6997 and #7009)
> chore(linux): Add script to upload to debian 🍒

- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/keyman_config/install_window.py
- linux/keyman-config/km-package-install
Fixes #6955.
:cherries:-pick of PR #7051.
Testing covered by #7051.
> feat(linux): Replace deprecated distutils :cherries: 

- linux/scripts/dist.sh
> chore(linux): Adjust Linux source package to restructured code

- windows/src/engine/keyman32/appint/aiTIP.cpp
Fixes: #7074
This PR removes the saving of context and keyboard options
on the non-updateable call to process hook when using the core processor.
The windows Text Input Processor calls twice for each keystroke the first call is not updatable. With the core integration we run
the processor only once - the actions and the context are available to be applied on the updatable call.
Saving and restoring the options meant that the stores values were overwritten and seeing as the process event call was not called again the stores changed value was lost.
> fix: remove saving and restoring context kbd options

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java
- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeyboardSettingsActivity.java
- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
- android/KMAPro/kMAPro/src/main/res/values/strings.xml
- android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java
- android/KMEA/app/src/main/res/values/strings.xml
- oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVShared.java
- oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java
- oem/firstvoices/android/app/src/main/res/values/strings.xml
> fix(android): verify browser before starting activity

- windows/src/engine/keyman32/appint/aiTIP.cpp
Cherry Pick from #7077
Remove the saving of context and keyboard options
on the non updateable call to process hook.
The windows Text Input Processor calls twice one call
is not updateable. With the core integeration we run
the processor only once, preserving the actions and
context to be applied on the updatable call.
> fix(windows): remove saving and restoring context kbd options 🍒
