keymanapp/keyman

windows/src/.gitignore
windows/src/Makefile
windows/src/developer/kmanalyze/kmanalyze.cpp
windows/src/developer/kmcmpdll/Compiler.cpp
windows/src/developer/kmdecomp/kmdecomp.cpp
windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/appint/appint.cpp
windows/src/engine/keyman32/kmprocess.cpp
windows/src/engine/mcompile/mc_syskbdnt32.cpp
windows/src/engine/mcompile/mc_syskbdnt64.cpp
windows/src/test/mnemonic-to-positional/m-to-p/m-to-p/syskbdnt32.cpp
windows/src/test/mnemonic-to-positional/m-to-p/m-to-p/syskbdnt64.cpp

Fixes #3084.
This does two things:
1. Cleans up a bunch of places where we used to use `(int)` typecasts for pointer math, which was problematic. We now use `(INT_PTR)` per MSDN https://docs.microsoft.com/en-us/windows/win32/winprog64/rules-for-using-pointers and then cast that down to `(int)` where necessary, e.g. when storing string lengths which are never going to be more than a few hundred characters! Doing this explicitly helps to clarify that we are aware of the typecast and believe it to be safe.
2. Adds in some build infrastructure for future use of Coverity Scan https://scan.coverity.com/ which we plan to use for further code quality updates. I have submitted the project to Coverity and are now waiting for approval so we can check results. Once we have approval, I do plan to add …

fix(windows): cleanup pointer to int typecasts

---

windows/src/developer/TIKE/Tike.dpr
windows/src/developer/TIKE/Tike.dproj
windows/src/developer/TIKE/dialogs/UfrmAboutTike.dfm
windows/src/developer/TIKE/dialogs/UfrmAboutTike.pas
windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectFile.pas
windows/src/developer/TIKE/project/Keyman.Developer.System.Project.UrlRenderer.pas
windows/src/developer/TIKE/project/Keyman.Developer.System.Project.WelcomeRenderer.pas
windows/src/developer/TIKE/xml/project/distribution.xsl
windows/src/developer/TIKE/xml/project/globalwelcome.xsl
windows/src/developer/TIKE/xml/project/keyboards.xsl
windows/src/developer/kmcomp/kmcomp.dpr
windows/src/developer/kmcomp/kmcomp.dproj
windows/src/developer/kmconvert/kmconvert.dpr
windows/src/developer/kmconvert/kmconvert.dproj
windows/src/global/delphi/general/Upload_Settings.pas
windows/src/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dpr
windows/src/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dproj

Relates to #3394.
Fixes all remaining hardcoded URLs in the Project / Welcome and the About window in Keyman Developer.

fix(developer): Project window and About window hardcoded urls

---

windows/src/engine/keyman/Menu_KeyboardItems.pas
windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.dfm
windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas

Fixes #1659.
If there are too many keyboards to fit in the OSK toolbar, the toolbar will now show a dropdown menu button and excess keyboards will be visible there.
First keyboard selected:
Overflowed keyboard selected:
Overflow menu:

feat(windows): overflow menu for osk toolbar

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeyboardSettingsActivity.java

Keyman has checks to prevent the default keyboard (sil_euro_latin) from being uninstalled. 
We should still allow non-default language IDs to be uninstalled with sil_euro_latin.

fix(android/app): Allow uninstalling sil_euro_latin for non-default languages

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Fixes #3521
Update `KMManager.copyAssets` so asset kmp files only get copied if they don't exist. This avoids unzipping the packages on every startup.

fix(android/app): Only copy asset .kmp file if it doesn't exist

---

windows/src/ext/sentry/Sentry.Client.pas
windows/src/global/delphi/general/Keyman.System.UILanguageManager.pas

Fixes #3633.
Memory allocation was half its required size due to missing
`sizeof(Char)` calculation.
Also added extra tags to Sentry events for command line and executable,
which made tracing this issue so much easier.

fix(windows): Buffer overrun in firstrun

---

windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboard.pas

Relates to #3561.
If a keyboard is installed for a transitional profile but another keyboard is already installed for that profile, then Keyman would crash, expecting the transitional profile to be missing.
Note that this does not introduce support for upgrading transitional language profiles, but simply resolves the related crash. Upgrading transitional language profiles (and disabled keyboards) will be added in an upcoming PR.

fix(windows): upgrading transitional profiles

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java

This addresses the Sentry error [invalid package ID](http://sentry.keyman.com/organizations/keyman/issues/898/?project=7&query=is%3Aunresolved)
One side effect of keymanapp/api.keyman.com#105 is that "packageFilename" no longer ends in "model.kmp". This cleans up the logic in determining the lexical model package ID.

fix(android/engine): Fix undetermined lexical model package ID

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift

Already-installed resources from a package were previously set to be installable upon download / install-from-file.  These should be pre-marked.  (Note the greyed options.)
Additionally, if a package supports multiple languages for a resource and the first language is already installed, the default selection shifts to the first language not currently paired with the resource.
Previously-installed language pairings may be selected for reinstallation:
This _should_ reinstall _all_ possible resource pairings for that language, even if some were manually removed.  Otherwise, only currently-installed resource pairings will be updated.  If the resource is then deselected, the grayed-out formatting will be restored.
"Install" will still be selectable even if no _new_ selections have been made... …

fix(ios/engine): package installation language-picker improvements

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java
android/KMAPro/kMAPro/src/main/res/values/strings.xml

This is in the category of unpleasant mitigations for #1963 
Until we get a better grasp of why there's lag using a Keyman system keyboard in our internal WebView (e.g. embedded keyboard search), this PR has the Keyman system keyboard switch to another system keyboard.

fix(android/app): Switch system keyboard in KMPBrowserActivity

---

windows/src/desktop/kmshell/main/Keyman.Configuration.System.UImportOlderVersionKeyboards11To13.pas
windows/src/global/delphi/general/Keyman.System.CanonicalLanguageCodeUtils.pas

Relates to #3561.
If a keyboard has languages installed under one of the four transient language profiles, then we need to jump through some additional hoops to upgrade it to the 14.0 model.
This does not yet handle all scenarios around installed but non-loaded keyboards.

fix(windows): Upgrading keyboards with transient profiles

---

windows/src/desktop/kmshell/main/Keyman.Configuration.System.UImportOlderVersionKeyboards11To13.pas
windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.Process.KPInstallKeyboardLanguage.pas

Fixes #3561.
Resolves issues with upgrading disabled keyboards, and fixes a secondary issue where Windows was giving us invalid LANGIDs for locales, which was causing trouble with transient LANGIDs.

fix(windows): upgrading disabled keyboards

---

windows/src/Makefile
windows/src/developer/kmcmpdll/Compiler.cpp
windows/src/developer/kmcmpdll/NamedCodeConstants.cpp
windows/src/developer/kmcmpdll/kcframe.cpp
windows/src/developer/kmcmpdll/kmcmpdll.h
windows/src/developer/kmcmpdll/versioning.cpp

Addresses Coverity reports for compiler.cpp and other files.
Note that whitespace was reformatted on this PR. You may want to compare with ignore-whitespace.

fix(developer): coverity reports for compiler

---

resources/git-hooks/prepare-commit-msg

If no scope is found in the branch name, then don't include the parentheses around the scope, as this breaks automatic merge messages and the parentheses are unnecessary.

chore: exclude parens if no scope in commit msg

---

web/source/kmwembedded.ts

Fixes #3569
The touch layout keyboard in the issue accesses `ctrl-alt` and `shift-ctrl-alt` layers on some long-presses (e.g. "numeric" layer on the <kbd>[</kbd> key). KMW was just doing a `split('-')` to separate the layer from the key name.
This PR fixes that to account for layers that may contain '-'.
Q: Do we 🍒-pick to stable-13.0? 
Jotting a list of some touch-layout keyboards that contain `-` in the layer ("shift-alt", "shift-ctrl", "ctrl-alt", "rightalt-shift", etc)
* bangla_joy
* on "rightalt" layer, press <kbd>৲</kbd>. This is `rightalt-shift-K_4`
* on "rightalt" layer, press <kbd>৺</kbd>. This is `rightalt-shift-K_7`
* on "rightalt" layer, press <kbd>৹</kbd>. This is `rightalt-shift-K_0`
* bangla_probhat
* basic_kbdarmph
* basic_kbdarmty
* basic_kbdcher
* basic_kbdcz1
* on the …

fix(web): Fix how layer is separated from key name

---

windows/src/engine/keyman/main.pas

Fixes #3665.
Cherry-pick of #3667.
On some systems, subkeys of HKCU\Software\Keyman could have incorrect permissions and these would not be corrected with earlier fixes such as in #2316. This fix resolves the problem by recursively correcting permissions on all subkeys, rather than just the top two levels.
This issue caused Metro-style applications (Windows Store apps) to fail to accept Keyman keyboard input.

fix(windows): Some registry keys could have incorrect permissions 🍒

---

developer/js/build.sh
windows/src/developer/inst/copydev.in

Previously, the build would take the TeamCity TIER and VERSION, which are eliminated in favour of the repo sources (the details are populated correctly for alpha but are not needed given we have TIER.md and VERSION.md).

fix(developer): ci uses repo tier and version

---

windows/src/buildtools/help-keyman-com.sh

This updates the build script to use the version data available in the repository rather than relying on environment.

fix(windows): update CI for publishing desktop help

---

common/models/types/build.sh

Previously, the build would take the TeamCity TIER and VERSION, which are eliminated in favour of the repo sources (the details are populated correctly for alpha but are not needed given we have TIER.md and VERSION.md).
This is analogous to #3670.

fix(web): ci uses repo tier and version

---

windows/src/Defines.mak
windows/src/README.md
windows/src/buildtools/getfilelocks/getfilelocks.vcxproj
windows/src/desktop/history.md
windows/src/developer/kmcmpdll/kcframe.vcxproj
windows/src/developer/kmcmpdll/kmcmpdll.vcxproj
windows/src/developer/kmdecomp/kmdecomp.vcxproj
windows/src/developer/samples/imsample/IMSample.vcxproj
windows/src/engine/keyman/main.pas
windows/src/engine/keyman32/Keyman32.vcxproj
windows/src/engine/keyman64/keyman64.vcxproj
windows/src/engine/keymanx64/keymanx64.vcxproj
windows/src/engine/kmtip/kmtip.vcxproj
windows/src/engine/mcompile/mcompile.vcxproj
windows/src/ext/tds2dbg/tds2dbg.vcxproj
windows/src/test/mnemonic-to-positional/importkeyboard/importkeyboard/importkeyboard.vcxproj
windows/src/test/unit-tests/shared-data/cpp/cppshareddata.vcxproj

Fixes #3665.
On some systems, subkeys of HKCU\Software\Keyman could have incorrect
permissions and these would not be corrected with earlier fixes such as
in #2316. This fix resolves the problem by recursively correcting
permissions on all subkeys, rather than just the top two levels.
This issue caused Metro-style applications (Windows Store apps) to fail
to accept Keyman keyboard input.
- chore(windows): Move to Windows SDK 10.0.17763.0 🍒
- fix(windows): Some registry keys could have incorrect permissions

fix(windows): metro application compatibility

---

developer/js/README.md
oem/firstvoices/windows/src/inst/download.in
oem/firstvoices/windows/src/localedef.dtd.in
windows/src/buildtools/inst/copydebug.in
windows/src/buildtools/inst/srcbackup.in
windows/src/desktop/help/install.in
windows/src/desktop/inst/download.in
windows/src/desktop/insthelp/manifest.in
windows/src/desktop/kmbrowserhost/manifest.in
windows/src/desktop/kmshell/localedef.dtd.in
windows/src/desktop/kmshell/manifest.in
windows/src/desktop/setup/debug-manifest.in
windows/src/desktop/setup/manifest.in
windows/src/developer/TIKE/manifest.in
windows/src/developer/inst/copydev.in
windows/src/developer/kmcomp/manifest.in
windows/src/developer/kmconvert/manifest.in
windows/src/developer/setup/manifest.in
windows/src/engine/inst/download.in
windows/src/engine/keyman/debug-manifest.in
windows/src/engine/keyman/manifest.in
windows/src/engine/keymanx64/manifest.in
windows/src/engine/kmcomapi/manifest.in
windows/src/engine/mcompile/manifest.in
windows/src/engine/tsysinfo/manifest.in
windows/src/engine/tsysinfox64/manifest.in
windows/src/global/help/version.in
windows/src/support/kmkb0045/manifest.in

Release build executables should have 3 component version numbers with the version tag appended, e.g. keymandesktop-14.0.155-alpha-local.exe.
Potentially coming later, rename keymandesktop-version.exe to keyman-version.exe.

fix(windows): improve version numbers

---

.gitignore
oem/firstvoices/windows/src/inst/download.in
windows/src/desktop/inst/download.in
windows/src/developer/inst/Makefile
windows/src/developer/inst/download.in
windows/src/engine/inst/download.in

While it might be nice to add the tag to versions in filenames, this creates a lot of work on the website where we make some filename assumptions. So, this PR winds that detail of filename changes back, and renames copydev.in to download.in to make it consistent with the other download.in files.

chore: don't add tag to version in filenames

---

windows/src/desktop/setup/SetupStrings.pas
windows/src/desktop/setup/UfrmInstallOptions.dfm
windows/src/desktop/setup/UfrmInstallOptions.pas
windows/src/desktop/setup/locale/en/strings.xml
windows/src/global/delphi/general/Keyman.System.UpdateCheckResponse.pas

Fixes #3680.
Fixes #3636.
Note that because the installer version may differ from the Keyman version that will actually be installed, the installer version number is a bit hidden away in the Options dialog, to try and reduce potential for confusion.
For example, if a user already has the installer downloaded, but a new version of Keyman is available, then by default the installer will try and download the new version rather than install the current version.

fix(windows): show version with tag in setup

---

windows/src/desktop/inst/download.in

For now, we rename the final output executable to keyman-a.b.c.exe, and don't change the constructed filename during the build (there's no need). We also do not change the .msi filename because that has a bunch of cascading dependencies, and again it isn't that important.

fix(windows): keyman desktop setup filename

---

common/core/web/input-processor/src/text/prediction/languageProcessor.ts
common/models/templates/src/common.ts
common/models/templates/test/test-common.js
common/models/types/index.d.ts
common/predictive-text/docs/worker-communication-protocol.md
common/predictive-text/index.ts
common/predictive-text/message.d.ts
common/predictive-text/unit_tests/headless/worker-dummy-integration.js
common/predictive-text/unit_tests/headless/worker-model-compositor.js
common/predictive-text/unit_tests/headless/worker-predict.js
common/predictive-text/unit_tests/in_browser/cases/worker-dummy-integration.js
common/predictive-text/worker/index.ts
common/predictive-text/worker/model-compositor.ts
common/predictive-text/worker/worker-interfaces.ts
web/source/osk/banner.ts

Feature:
- The 'reversion' option for undoing applied suggestions now uses the current lexical model's punctuation settings.
Other notes:
- Adds unit tests for the generated reversion
- Adds unit tests for `Transform` merging, given the new `buildMergedTransform` signature and implementation.
To demonstrate the principle feature, I made a temporary and slightly edited version of the MTNT model, as seen here:
Note the "<<" and ">>" syntax, instead of the MTNT model's original use of double-quotes.  Previously, 'revert' options always used double-quotes, so this provides the visual distinction necessary to see the difference at a glance.
Selecting the highlighted suggestion, as usual, displays new suggestions:
Hitting BKSP then triggers the option to revert:

feat(common/models): 'revert' now uses model's punctuation

---

common/models/types/index.d.ts
common/predictive-text/worker/model-compositor.ts
web/source/osk/banner.ts

Fixes #3056.
Disables display of the "keep" suggestion except when the suggestion matches a model prediction.
Not a model prediction:
When it is a model prediction:
For these examples, note "tying" is a far less frequent word than "thing" and "think", which is why the prediction engine wants to 'correct' away from it.  However, once the word is fully typed, the fact that the word is a perfect match "overrides" that probability, as it's now a "keep" suggestion.
--------
As usual, since the suggestion matches an entry in the `LexicalModel`, no quote-style marks are displayed for the "keep" in this scenario.

feat(common/models): disables "keep" when word is not suggestion otherwise

---

common/core/web/input-processor/src/text/prediction/languageProcessor.ts
common/models/types/index.d.ts
common/predictive-text/docs/worker-communication-protocol.md
common/predictive-text/worker/index.ts
common/predictive-text/worker/model-compositor.ts
web/source/osk/banner.ts

Fixes #2851.
As it turns out, the space-swallowing code has actually been broken since the KMW core refactor, as the newer event-handling style (the Node-style `.emit` stuff) doesn't actually return the response value from its handlers.  So, this includes a bug fix for that aspect, too.
Now for the main purpose of this PR.  Whenever a model is loaded, it now returns a flag indicating whether or not it appends wordbreak characters after suggestions as _part_ of the `Configuration` object we've always been returning.  This flag may then be used by KMW to selectively enable wordbreak-squashing behavior in predictive contexts.
I've tested this with a local modification to one of the test models; `K_SPACE` is no longer squashed when the model does not append extra characters to suggestions via …

feat(common/core/web): selective wordbreak swallowing after accepting suggestions

---

common/models/templates/src/common.ts
common/models/templates/src/trie-model.ts
common/models/types/index.d.ts
common/predictive-text/worker/model-compositor.ts

`& { p?: number }` was being used often enough, I thought it might as well be its own type. This is `Outcome` — but perhaps it should be named `Sample`? `WithOutcome` is the same type, but the `p` is _required_.

refactor(common/models): extract Outcome type

---

common/core/web/input-processor/src/text/prediction/languageProcessor.ts

Fixes an error reported from Sentry:
```
TypeError: null is not an object (evaluating 'a.shouldSwallow=!1')
at None (source/osk/banner.ts:671:7)
at None ([native code])
at None (source/osk/preProcessor.ts:86:21)
at None (source/osk/preProcessor.ts:64:22)
at None (source/osk/visualKeyboard.ts:961:9)
...
(4 additional frame(s) were not displayed)
```
This was because I overlooked something in #3702, a recently-accepted PR.  Figured I'd address it quickly before my memory of it went cold.

fix(common/core/web): fixes revert event bug

---

web/source/kmwembedded.ts
web/source/osk/visualKeyboard.ts

Fixes #1113 
atm, Keyman for Android on phones includes the base key in the list of popup keys.
This PR standardizes the popup keys by not pre-pending the base key in the popup array.
This also fixes #3092 because now Keyboard creators can control if/where the base key appears in the popup keys.

fix(web): Remove base key from popup keys

---

common/core/web/input-processor/src/text/prediction/languageProcessor.ts
common/models/types/index.d.ts
common/predictive-text/unit_tests/headless/edit-distance/context-tracker.js
common/predictive-text/unit_tests/headless/worker-model-compositor.js
common/predictive-text/worker/correction/context-tracker.ts
common/predictive-text/worker/model-compositor.ts
common/predictive-text/worker/worker-interfaces.ts

This PR adds internal tracking of user manipulations to the context state.  In particular, whenever a user 'accepts' a `Suggestion`, this will be noted within the `ContextTracker` to provide enhanced information to subsequent prediction efforts.  (All such tracking is worker-internal and only for the user's local use.)  This was previously part of #3647, but the changes were distinct enough to merit splitting it in twain - hence this now being reviewable separately.
- Tracked context now notes any accepted suggestions and the resulting token text, maintaining both the original and replaced versions of each token.
- Fixes some related internal context tracking bugs that hadn't yet been caught due to lack of external impact.  (Arguably, it may be more of an "incomplete implementation" …

feat(common/models):  context tracking of accepted Suggestions

---

common/core/web/input-processor/src/text/prediction/languageProcessor.ts
common/predictive-text/docs/worker-communication-protocol.md
common/predictive-text/index.ts
common/predictive-text/message.d.ts
common/predictive-text/unit_tests/headless/worker-model-compositor.js
common/predictive-text/worker/correction/context-tracker.ts
common/predictive-text/worker/index.ts
common/predictive-text/worker/model-compositor.ts
common/predictive-text/worker/worker-interfaces.ts
web/source/kmwembedded.ts
web/source/osk/banner.ts

This PR will get reversion working fully with the newer correction algorithm while also providing a nice new benefit:
- Reversions restore the original state of the input, even remembering the probability of each keystroke for use in further predictions after extra typing.
- The tracked context state will be fully rewound to before the reverted Suggestion was applied.
Note:  to simplify the implementation, I dropped unused code that was intended to support suggestion rotation.  Let me know if that's an issue and I can look at restoring it in a cleaner way.

feat(common/models): context reversion modeling

---

windows/src/engine/keyman32/Keyman32.cpp

When loading transient language profiles, RefreshKeyboards would reset the list of profiles (and in so doing, also leak memory). Instead, the list should be cleared before the initial language profile list load.

fix(windows): RefreshKeyboards loses some profiles

---

windows/src/desktop/kmshell/main/UfrmMain.pas

Fixes #3692.
Icons were missing in Configuration because the XML template was initialised out of order.

fix(windows): icons missing in Configuration

---

windows/src/engine/keyman/UfrmKeymanMenu.pas

Fixes #3694.
The keyboard menu would sometimes scroll too far, which could be confusing for the end user. This fix stops the scroll once the last item is in view; it also tweaks the down arrow key handler to ensure that the current item is correctly scrolled into view.

fix(windows): tweak scrolling in keyboard menu

---

android/KMAPro/kMAPro/build.gradle
android/KMEA/app/build.gradle
android/README.md
android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample2/app/build.gradle
android/Tests/KeyboardHarness/app/build.gradle
android/history.md
oem/firstvoices/android/app/build.gradle
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java
web/source/kmwembedded.ts

Cherry-pick of #3659 to stable-13.0 by fixing how the layer is separated from the key name.
In order for stable-13.0 to build, I also had to remove the deprecated Crashlytics SDK

fix(web): Fix layer how layer is separated from key name

---

windows/src/desktop/setup/RunTools.pas
windows/src/desktop/setup/SetupStrings.pas
windows/src/desktop/setup/locale/en/strings.xml

Fixes #3690.
This applies an 'Installing Keyman' label during the install. While Windows Installer does supply some status messages, at present we are not using those. Also fixed a missing i18n string.

fix(windows): setup status showed only 'removing older versions'

---

windows/src/engine/tsysinfo/UfrmEmail.pas

If tsysinfo fails to upload a diagnostic report, give more detail on what happened.

fix(windows): improve tsysinfo upload messages

---

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebBrowserActivity.java

While checking Sentry logs for #3721, I noticed a large amount of [MalformedURLExceptions](http://sentry.keyman.com/organizations/keyman/issues/484/?project=7&query=is%3Aunresolved).
(edited)
This PR adds the following fixes to `WebBrowserActivity`:
* Don't log `MalformedURLExceptions` since it may be a query
* URLEncode the string if it seems to be a URL
* Set `android:usesCleartextTraffic="true"` which allows http traffic (API 23+)

fix(android/browser): Improve how embedded browser handles input

---

windows/src/desktop/setup/UfrmRunDesktop.dfm
windows/src/desktop/setup/UfrmRunDesktop.pas

Fixes #3666.
Due to an issue in Delphi with 'modal' dialogs without a parent window, Setup would not restore after being minimized, e.g. with Win+D.

fix(windows): restore Setup after minimize

---

windows/src/desktop/setup/RunTools.pas
windows/src/desktop/setup/UfrmDownloadProgress.pas

Fixes #3688.
If a user cancelled the download dialog, a blank error dialog would be shown.

fix(windows): download error dialog could be blank

---

windows/src/engine/keyman32/Keyman32.cpp
windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/k32_globals.cpp

Both the win32 and the win64 keyman engine libraries would receive a refresh notification, and then they'd both broadcast the change. This change limits the broadcast responsibility to the 32-bit engine.

fix(windows): Remove double refresh

---

windows/src/desktop/kmshell/help/UfrmHelp.pas
windows/src/desktop/kmshell/install/UfrmInstallKeyboard.pas
windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas
windows/src/desktop/kmshell/main/UfrmKeepInTouch.pas
windows/src/desktop/kmshell/main/UfrmMain.pas
windows/src/desktop/kmshell/main/UfrmOnlineUpdateNewVersion.pas
windows/src/desktop/kmshell/main/initprog.pas
windows/src/desktop/kmshell/startup/UfrmSplash.pas
windows/src/desktop/kmshell/util/utilkmshell.pas
windows/src/desktop/kmshell/xml/config.css
windows/src/desktop/kmshell/xml/keyman_footer.xsl
windows/src/desktop/kmshell/xml/strings.xml
windows/src/engine/kmcomapi/com/system/keymancontrol.pas
windows/src/engine/kmcomapi/com/system/keymansysteminfo.pas
windows/src/engine/kmcomapi/processes/kpbase.pas
windows/src/engine/kmcomapi/util/internalinterfaces.pas
windows/src/global/delphi/hints/UfrmHint.pas
windows/src/global/delphi/ui/UfrmWebContainer.pas

Fixes #3518.
This is a multi-part PR, with base cleanup in separate commits. Recommend reviewing each commit separately as that will clarify the intent of the changes.
---
Changes in Keyman Configuration will now apply immediately. This removes the OK and Cancel buttons from the dialog and means that all actions are consistent in when they are applied, unlike previously. This also matches the Windows 10 Settings metaphor and metaphors for most modern apps and devices.
For now, I have placed a message where the OK and Buttons were previously, to help existing users understand the change. In time, I expect us to be able to remove that message entirely.
---
Cleanup includes: removing reboot check, removing unused file dialogs, deleting unreachable code, removing unused parameters.
For future …

fix(windows): Keyman Configuration changes apply instantly

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Helps improve startup-time for #2811 
On app startup, we want to avoid parsing kmp.json files if we can.
This updates `KMManager.prepareKeyboardSwitch()` and `KMKeyboard.setKeyboard()` to only determine the keyboard version for `cloud/` keyboards (since the version string is only appended to cloud/ keyboard files). This avoids the JSON overhead of parsing kmp.json files to get a keyboard version that isn't used.
While there's a lot of similarity between KMKeyboard.prepareKeyboardSwitch() and KMKeyboard.setKeyboard() from #2296, I'm not planning to refactor that at this time.

fix(android/engine): Only get keyboard version for cloud/

---

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebBrowserActivity.java
android/KMAPro/kMAPro/src/main/res/values/strings.xml

This fixes #1963 where typing in the embedded browser (a WebView) with the SystemKeyboard (also a WebView) was timeout out between each keystroke.
The fix from https://stackoverflow.com/questions/40650643/timed-out-waiting-on-iinputcontextcallback-with-custom-keyboard-on-android was to put extra WebViews in a separate process. (this affects WebBrowserActivity and KMPBrowserActivity where a user interacts with the webview).
Having the webViews in a separate process also brought up a complication in Android P (API 29+) where the data directory also needs to be separate.
Ref: https://stackoverflow.com/questions/51843546/android-pie-9-0-webview-in-multi-process
Finally, with a responsive system keyboard in the webView, we can revert the workaround in #3648 (no longer need to override the …

fix(android/browser): Fix slow input in embedded browser (WebViews)

---

common/predictive-text/worker/correction/context-tracker.ts

While working on other stuff, I caught note of this low-hanging TODO.
This helps the context tracking system better match contexts after suggestions are accepted.

chore(common/models): fixes context tracking with accepted suggestions

---

windows/src/engine/.gitignore
windows/src/engine/keyman32/Keyman32.cpp
windows/src/engine/keyman32/Keyman32.vcxproj
windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/k32_globals.cpp
windows/src/engine/keyman32/k32_tsf.cpp
windows/src/engine/keyman32/k32_tsf.h
windows/src/engine/keyman32/kmhook_callwndproc.cpp
windows/src/engine/keyman32/kmhook_getmessage.cpp
windows/src/engine/keyman32/selectkeyboard.cpp
windows/src/global/inc/keyman64.h

Fixes #3650.
This removes the bad call to `FreeLibrary` that was still present in a callee of `DllMain` in keyman32. The refactor moves responsibility for loading TSF to the `SelectKeyboard` functions and gets rid of the associated thread globals.
The `TSFINTERFACES` struct is of course a future candidate for a class.
In the process I removed a lot of cruft from keyman32.cpp which was either obsolete, irrelevant or just plain wrong. None of which had material impact on the running code.

fix(windows): remove msctf free from DllMain

---

windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas
windows/src/desktop/setup/RunTools.pas
windows/src/desktop/setup/SetupStrings.pas
windows/src/desktop/setup/UfrmInstallOptions.dfm
windows/src/desktop/setup/UfrmInstallOptions.pas
windows/src/desktop/setup/UfrmRunDesktop.pas
windows/src/desktop/setup/bootstrapmain.pas
windows/src/desktop/setup/locale/en/strings.xml

Where more than one source of a file is available, e.g. a local keymandesktop.msi which is older than the current published version online, then Setup will choose the newer, online version by default, but allows the user to change the install source in the Options dialog to have an offline setup if they prefer.
This means that the 'best' location is now chosen at startup, and then the user can override that.
Relates to #3689.
(Note some options are hidden because they are not relevant)

fix(windows): setup now allows choice of source

---

windows/src/desktop/setup/SetupStrings.pas
windows/src/desktop/setup/UfrmDownloadProgress.dfm
windows/src/desktop/setup/UfrmDownloadProgress.pas
windows/src/desktop/setup/bootstrapmain.pas
windows/src/desktop/setup/locale/en/strings.xml
windows/src/desktop/setup/setup.dpr
windows/src/desktop/setup/setup.dproj

When Setup is starting, it can sometimes take a few seconds to show the main form because it is querying an online server and unzipping various files. This shows a small progress bar window so that the user doesn't wonder what is going on.
The progress bar is fairly basic: it has only 4 steps, and because all actions are happening on the main thread, does not animate well or smoothly. In my view, it is not worth redesigning into a multi-threaded process for the sake of this progress bar dialog.
Relates to #3689.

fix(windows): show bootstrap progress in setup

---

windows/src/desktop/setup/UfrmRunDesktop.dfm
windows/src/desktop/setup/UfrmRunDesktop.pas

If the list of actions that Setup will perform is too long, a scrollbar will now be shown. This will probably not arise frequently but certainly helps if it does.
Fixes #3689.

fix(windows): cleanup setup action list

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudCatalogDownloadCallback.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudCatalogDownloadReturns.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Dataset.java

This is the low-hanging-fruit 🍏  portion of #3777 by removing the use of the lexical-model catalog. `CloudRepository.prepareLexicalModelUpdateQuery` is also no longer needed.
* Also clarify deprecation comments since `KMManager.KMFilename_LexicalModelsList` is still in use.
* Fix typo `prepareResourcesUpdateQuerty` to `prepareResourcesUpdateQuery`
This change does affect ModelPickerActivity since there's no longer a lexical-model catalog available to display available models to install. The UX will be updated in a separate PR.
As a test, I verified I could install the fv_sencoten keyboard, and the app would find the associated dictionary and download it.

chore(android/engine): Remove use of lexical-model catalog

---

windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguage.pas
windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguageinstalled.pas
windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.Process.KPInstallKeyboardLanguage.pas
windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboard.pas

Transient language profiles would get the wrong language association when they were disabled and re-enabled.
Fixes #3798.

fix(windows): disabling/enabling a profile could have wrong association

---

windows/src/engine/keyman/Menu_KeyboardItems.pas

Fixes #3725.
Fixes #3783.
In some situations, the keyboard menu would either display empty or would not refresh to get all installed keyboards.

fix(windows): keyboard menu could get out of sync

---

windows/src/desktop/kmshell/install/UfrmInstallKeyboard.pas
windows/src/engine/kmcomapi/com/keyboards/keymankeyboardfile.pas
windows/src/engine/kmcomapi/com/keyboards/keymankeyboardinstalled.pas
windows/src/global/delphi/general/utilxml.pas

Fixes #3801.
Fixes #3802.
Fixes KEYMAN-WINDOWS-5M.
Fixes KEYMAN-WINDOWS-5N.
This is a two-part fix for Keyman Configuration where it appears there was a race with creating a temporary file, and which caused a cascading exception.
The first part resolves the race; the second part (in UfrmInstallKeyboard.pas) adds a little extra robustness (probably not totally necessary).

fix(windows): crash installing package with a race

---

windows/src/desktop/kmshell/util/Keyman.System.KeymanStartTask.pas
windows/src/global/delphi/general/Keyman.System.KeymanSentryClient.pas

Fixes #3797.
Fixes KEYMAN-WINDOWS-5H.
Report unexpected errors creating or deleting scheduled task, and ignore expected errors better, handling a potential race condition where two processes both attempt to create a folder at the same time.
Note that creating the task should not be a race because we use the `TASK_CREATE_OR_UPDATE` flag.

fix(windows): Handle failure on task creation

---

resources/build/README.md

The background reason for this is to test a fix to the web build, where s.keyman.com resources were not being updated since we refactored the build configurations (sadly, the build did not die when it should have).

chore(common): improve build README.md

---

windows/src/developer/TIKE/dialogs/languages/Keyman.Developer.UI.UfrmSelectBCP47Language.pas

Fixes #1584.
In the "Select BCP 47 Tag" dialog, when the user starts typing a language tag, e.g. "hi" for Hindi, the "h" would match "ha" for Hausa, and set the script to "Latn". When the "i" was then typed, the script box would not be cleared, giving an incorrect result of "hi-Latn" instead of just plain "hi".
The earlier issue of "yo-Brai" has already been resolved.

fix(developer): Incorrect script:language map

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/GetStartedActivity.java

I was reviewing the [User Testing for Android](https://github.com/keymanapp/keyman/wiki/User-Testing-for-Android) procedures for Friday's test meeting.
Originally, the **Get Started** menu option "Add a keyboard for your language" required network access to keyman.com to install a keyboard.
The option now accesses the Keyman Settings menu "Install Keyboard or Dictionary" which offers two options for installing offline keyboard packages. (The first option "Install from keyman.com" has the check for network).
This small PR just removes the network check on the "Get Started" menu.

fix(android/app): Remove network check on "Get Started" menu

---

windows/src/developer/TIKE/child/UfrmDebug.pas
windows/src/developer/TIKE/child/UfrmKeymanWizard.pas

Fixes #3827.
The debugger was not inheriting the editor font -- this is a regression from when we replaced TPlusMemo with Monaco editor.

fix(developer): debug window inherits editor font

---

windows/src/developer/setup/SetupStrings.pas
windows/src/developer/setup/UfrmRun.pas

Fixes #3832.
Removes the now-unneeded Internet Explorer dependency from Developer Setup, and corresponding strings (plus a couple of other unused strings).
I18n of these strings is a future project.

fix(developer): Remove IE dependency from Developer Setup

---

windows/src/developer/kmconvert/Keyman.Developer.System.ImportKeyboardDLL.pas

Fixes #3810.
Importing a Windows keyboard would not produce correct OSK for European layouts because it was based on virtual key instead of scan code. Mapping through the scan code back to "US" base layout resolves the issue.
Note that there is a slight difference between Import Windows Keyboard and Fill from Layout results, as deadkeys have slightly more information in the Import process, and can display the base deadkey, whereas Fill from Layout will result in a blank deadkey. This difference is by design.
This now also detects the presence of the 102nd key. Note that here also Fill from Layout may have a slightly different result, as the 102nd key is defined by kbdus.dll, and Fill from Layout will see the resulting rule in the .kmn and enable the 102nd key. This difference is also by …

fix(windows): Import OSK wrong for European layouts

---

windows/src/buildtools/build_standards_data/build_standards_data.dproj
windows/src/buildtools/buildpkg/Makefile
windows/src/buildtools/buildpkg/buildpkg.dproj
windows/src/buildtools/sentrytool/sentrytool.dproj
windows/src/desktop/insthelp/Makefile
windows/src/desktop/kmbrowserhost/Makefile
windows/src/desktop/kmbrowserhost/kmbrowserhost.dproj
windows/src/desktop/kmconfig/Makefile
windows/src/desktop/kmconfig/kmconfig.dproj
windows/src/desktop/kmshell/Makefile
windows/src/desktop/setup/Makefile
windows/src/desktop/setup/setup.dproj
windows/src/developer/TIKE/Makefile
windows/src/developer/kmanalyze/Makefile
windows/src/developer/kmcomp/Makefile
windows/src/developer/kmconvert/Makefile
windows/src/developer/kmconvert/kmconvert.dproj
windows/src/developer/setup/Makefile
windows/src/engine/inst/insthelper/Makefile
windows/src/engine/keyman/Makefile
windows/src/engine/kmcomapi/Makefile
windows/src/engine/kmcomapi/kmcomapi.dproj
windows/src/engine/tsysinfo/Makefile
windows/src/engine/tsysinfox64/Makefile
windows/src/ext/sentry/test/Makefile
windows/src/ext/sentry/test/SentryClientTest.dproj
windows/src/ext/sentry/test/SentryClientVclTest.dproj
windows/src/support/oskbulkrenderer/Makefile
windows/src/support/oskbulkrenderer/oskbulkrenderer.dproj
windows/src/support/unload_keyboards/unloadkeyboards.dproj

Fixes #3831.
This fixes both issues reported in the bug (dproj changes ensure separate .tds, and Makefile changes fix order of execution so that dbg is generated after sentryprep's cleanup).
Note that unit tests and other unpublished executables do not need updating for this.

fix(windows): SizeOfImage header was wrong for dbg

---

windows/src/ext/sentry/Sentry.Client.pas

This replaces vectored exception handler code which fixed up the 8087 CW with a thread-safe version of Set8087CW that avoids the global variable Default8087CW. We would get occasional situations where exceptions were raised on 2 threads simultaneously, which could lead to a race where the first thread set Default8087CW to $1340, and then the second thread would read that and think that is the default to keep. We want to avoid touching Default8087CW altogether here.
I believe that this could sometimes be visible to users with blank browser pages on reload (based on debugging experiences and noting floating point exceptions happening). Let's wait and see if that resolves that sporadic issue.
See also https://stackoverflow.com/a/39684636/1836776 and …

fix(windows): sporadic 8087 control word corruption

---

common/core/web/keyboard-processor/src/text/defaultOutput.ts

Fixes the Windows aspect of #3814.
The core of the issue was a mishandled return value.  As it turns out, `'' != null`, despite `! '' == true`.  (Thank you, JS.)  Noting this, `DefaultOutput.forAny` should return `null` instead of `''` so that its return value is handled properly within `KeyboardProcessor`.  This also better matches the other key-code output/handling checks of `DefaultOutput`.
The code block affected by this return value:  https://github.com/keymanapp/keyman/blob/866e12481ffb9a2e0bff2f0e625d53ddcfd53bf8/common/core/web/keyboard-processor/src/text/keyboardProcessor.ts#L152-L169
Since we were returning `''` for "no default output", the condition on line 153 was always `true`, meaning the `else` block from 162-164 was never evaluated.  That `else` block is the pathway needed …

fix(common/core/web): fixes no-output logic check, arrow keys

---

web/source/osk/visualKeyboard.ts

Addresses a sub-issue noted on #1111.
As noted in [this comment](https://github.com/keymanapp/keyman/issues/1111#issuecomment-589977307) from that issue:
> In Chrome emulation, they [_blank/hidden keys_] do still show the popup pentagon [_key preview_].
The preview is pretty simple to turn off, and we were already disabling it for a few CSS classes.  This PR just adds a few extra to the blacklist.
With these changes in place, key previews for blank/hidden keys now know their place, even during Chrome emulation, and no longer appear.

fix(web/engine): blocks key previews for blank/hidden keys

---

common/core/web/keyboard-processor/src/text/kbdInterface.ts
common/core/web/keyboard-processor/test.sh
common/core/web/keyboard-processor/tests/cases/engine/context.js

Fixes #3841.
Also fixes a bug discovered while implementing the changes specified by #3841, which had actually neutered a number of the unit tests.  Fortunately, the only ones that failed when re-enabled... did so because of an error in the test spec, not in the actual engine code.  Whew!

fix(common/core/web): Fixes engine-level context tests, adds notany cases

---

windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas
windows/src/desktop/setup/Keyman.Setup.System.OnlineResourceCheck.pas

Relates to #1635.
This goes with keymanapp/api.keyman.com#122, and ensures that major upgrades are offered regardless of the rollout schedule, if they are available, when the user manually checks for an update.

feat(windows): major version upgrades

---

common/core/desktop/src/kmx/kmx_file.h
common/core/web/keyboard-processor/src/text/codes.ts
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMBinaryFileFormat.h
web/source/dom/preProcessor.ts
windows/src/global/inc/Compiler.h

Fixes #3814.
Following the work in #3848, I noted that the shortcuts were failing for a different reason on Mac, where they are command-key based instead of CTRL-based.  On that platform, the engine does nothing to note when the `metaKey` is currently active; tracking this is enough to allow mac-based hotkeys to pass through.  Do let me know if the new `META` modifier code needs to be changed to something else.
As keyboard rules require exact modifier state matches to succeed, applying the `META` modifier code to keystrokes will bypass any rules not explicitly targeting modifier states that include the `Meta` state.

fix(common/core/web): meta key handling

---

common/models/types/index.d.ts
common/predictive-text/unit_tests/headless/worker-model-compositor.js
common/predictive-text/worker/index.ts
common/predictive-text/worker/model-compositor.ts

When combined with #3770, implements most of the spec defined within #3720.
The new `applyCasing` function may now be utilized to enhance suggestions.  The predictive engine will now detect the casing pattern used by the current context (when `languageUsesCasing == true`) and will transform suggestion text to match said casing when is not the default (`lower`) casing pattern or an unknown one.
-----
While this does need a proper set of compiled-model unit tests, that's best left to a follow-up PR.  It would be a _very_ good idea to maintain some integration tests for the new feature, as the compilation infrastructure involved is definitely _not_ trivial.  (The "pseudoclosure" thing seen in #3770, in particular.)  The issue is that #3836 adds infrastructure needed to facilitate the tests, …

feat(common/models): use of applyCasing for suggestions

---

common/models/types/index.d.ts
common/predictive-text/unit_tests/headless/worker-model-compositor.js
common/predictive-text/worker/model-compositor.ts

As noted by https://github.com/keymanapp/keyman/pull/3770#discussion_r520108961, initial implementation for adaptively casing predictions was made easier by assuming that any suggestions a model produces replace the entire word.  (That assumption holds true for the `TrieModel`.)  With a little extra work, we can relax the assumption and restore the original `predict` spec to its original form.
To facilitate unit testing, I've also moved the casing-application code into its own, isolated function.  Integrated tests will come later with their own pathway, but at least this provides some initial LMLayer test coverage for the new feature.

feat(common/models): casing for suggestions with partial replacement

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java

Fixes #3809
This fixes the race condition where the in-app TextView would load before the in-app keyboard is loaded. The TextView would fail to get existing context.
* Consolidates some WET code to `updateTextContext()`

fix(android/engine): Update in-app TextView context on pageLoaded

---

web/source/osk/visualKeyboard.ts

Fixes #1111.
The OSK's touch handlers and `findNearestKey` algorithm now ignores `kmw-key-blank`-marked keys during its search for a nearest key.  Previous distance thresholds still apply.
@MakaraSok 
This image from the original issue provides a good hint for testing:
> Lost in spacing:
> ![image](https://user-images.githubusercontent.com/986339/44294895-9d0f6680-a26c-11e8-855b-8de8980a05c7.png)
Use of the standard `web/testing/unminified.html` test page is sufficient.
Keyboard:  `sil_cameroon_qwerty` (use "Add a keyboard by keyboard name")
- Use the 'abc' key to access the displayed layer.
- Try pressing a "key" about half a key's width away from a key that actually exists.
- Keys on the same row within that distance should activate from such a keypress.
- Keys on different rows will …

feat(web/engine): allows touch aliasing away from blank keys

---

mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj
mac/build.sh

This PR tries to make codesign more resilient to failure, by retrying a build step that falls over with code 65. This code is not limited to codesign but most frequently happens with it.
A more complete answer would be to do the codesigning step in build.sh instead of in the project, which would give us more control of the outcome, and maybe simplify the build process somewhat, but I will leave that for now, because it is usually better to leave that to XCode.

fix(mac): codesign resilience

---

mac/Keyman4Mac/Keyman4Mac/Info.plist
mac/Keyman4MacIM/Keyman4MacIM/Info.plist
mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMDownloadKeyboard/KMDownloadKBWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/KMInfoWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/Info.plist
mac/build.sh

Fixes #3849.
* Uses keyman-staging.com when on alpha or beta
* Updates copyright year at build time
* Fixes link to help documentation (/mac, not /macosx)

fix(mac): support page and copyright

---

oem/firstvoices/android/app/build.gradle
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Follow-on to #3825 
I missed updating the Sentry library for the FV Android app. This fixes #3906

fix(android/oem): Update Sentry library in FV app

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java

Fixes #3873
The stepper adapter determines how many steps (dots) are involved in the .kmp keyboard package installation.
In the case of a 1-step install (only 1 associated language, no readme.htm or welcome.htm included), the "Install" button was registering as `onCompleteClicked` and the WebViewFragment finished the activity without installing the keyboard.
This adds a check to handle the 1-step scenario.
Verified keyboard packages install for these scenarios:
Engineering package of chirality keyboard (1 language, no readme.htm or welcome.htm) - 1 step
khmer_angkor (1 language, contains welcome.htm) - 2 steps
sil_cameroon_qwerty (multiple languages to select, contains welcome.htm) - 3 steps
After all the packages installed, I went back to the "Add languages to installed keyboard" menu …

fix(android/app): Install keyboard packages w/o welcome.htm

---

android/KMEA/app/src/main/assets/keyboard.html
common/core/web/keyboard-processor/src/keyboards/keyboard.ts
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
web/source/keyboards/kmwkeyboards.ts
web/source/kmwrotation.ts

Fixes #3049.
In my zeal to make OSK rendering more efficient during the KMW core refactor, the optimizations kind of neglected how OSK rotation works when deciding to reuse layout calcuations; a rebuild of the OSK layer group had always been required to properly adjust OSK dimensions.  This PR provides a pathway to restore recomputation/reconstruction of the layer group whenever a rotation occurs:  `Keyboard.refreshLayouts()`.
Once this method is called on a keyboard, the next `VisualKeyboard._Load()` call against an OSK for it will be forced to recalculate its layout information and thus will readjust its dimensions to the currently-expected values in the same manner it always did before.  While 'better' approaches may be possible in the future, this is a simple and safe way to fix the …

fix(web/engine): fixes OSK rotation

---

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift

Fixes #2836.
The "image banner" will now only display when "Always show banner" is selected _**and**_ the system keyboard is active.
Honestly, I was surprised at just how simple the change turned out to be.  I get the feeling that #3909 may have prevented would-be complications.
In regard to #2907, key previews / popup keys seem to display properly, though sometimes the predictive-text banner will not display upon initial load of the system keyboard.  So, that issue isn't fully resolved yet, though at least #2836 will be.

fix(ios/engine): changes image-banner display logic

---

mac/Keyman4MacIM/Keyman4MacIM/KMDownloadKeyboard/KMDownloadKBWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m

Fixes #3898.
This reworks the keyboard download window to use the new keyboard install page and url pattern. Some refactoring of the downloadKeyboard method was required to handle the new download patterns.
We need to start looking at moving the Configuration dialog into a model where it runs as a separate process, so it does not need to be floating and can be accessed through the dock or Cmd+Tab etc. Right now, clicking an external link opens in the browser, but the browser is stuck behind the window. This is a separate job though.

chore(mac): use new keyboard install page

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/AssociatingPackageInstaller.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/KeyboardSearchViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
ios/engine/KMEI/KeymanEngineTests/AssociatingPackageInstallerTests.swift
ios/engine/KMEI/KeymanEngineTests/TestUtils/Keyboards.swift

Fixes #3404.  Naively, but it should probably be enough for now.  (A better solution would be far more BCP-47 aware, but that would require a significantly more complex solution.)
Also fixes a bug / omission that prevented the default language code from actually being preselected.

fix(ios/engine): allows some language-code incomplete matches during package installation

---

ios/engine/KMEI/KeymanEngine/Classes/PackageWebViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/KeyboardSearchViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/UniversalLinks.swift
ios/keyman/Keyman/Keyman/AppDelegate.swift

Designed to parallel #3602... assuming I interpreted its changes correctly.  I'm not 100% sure that I did.
This is more complicated than might be desired due to Swift restrictions on the method for launching URLs externally.  Those complications motivated the `private static var` approach as a workaround.

feat(ios/engine): launches external links outside the app

---

.gitignore
common/core/desktop/debian/watch
linux/ibus-keyman/debian/watch
linux/ibus-kmfl/debian/watch
linux/keyman-config/debian/watch
linux/kmflcomp/debian/watch
linux/libkmfl/debian/watch
linux/scripts/launchpad.sh
linux/scripts/watch.in

This change fixes the launchpad build script and also improves updating the watch file.
If we use the variables that `uscan` provides we don't have to hard-code the package name in the watch file. This makes it possible to use a generic one for all packages.

chore(linux): Fix launchpad build (closes #3875)

---

linux/ibus-keyman/debian/postinst
linux/ibus-keyman/debian/postrm

If (re-)starting ibus fails for whatever reason we should simply ignore the failure instead of failing the entire installation/uninstallation.
This fixes #3902.

fix(linux): Don't fail installation if restarting ibus fails (v13)

---

windows/src/ext/sentry/Sentry.Client.pas

In some circumstances, Sentry would get a range check error while processing the call stack due to `DWORD` being defined as `NativeInt`, not `NativeUInt`, in old JWA libraries. This would mask the original exception, and could cause the app to hang.

fix(windows): sentry range check error

---

HISTORY.md

In preparation for the Beta announcement, we will be updating help.keyman.com to use the new history file for 14.0+ histories (keymanapp/help.keyman.com#106).
This PR is a preliminary attempt to clean up the commit types to match those defined in `/resources/scopes/commit-types.json`.

chore(common): Clean up commit types in HISTORY.md

---

android/KMEA/app/src/main/assets/keyboard.html
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html

Fixes [this Sentry error report](https://sentry.keyman.com/organizations/keyman/issues/1866/?environment=local&project=11&referrer=alert_email).
Basically, I forgot to add a null-guard to some of the new lines in #3909.  (Within both `keyboard.html` files)

fix(android, ios): adds null guard to refreshLayouts call

---

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
web/source/osk/visualKeyboard.ts

Fixes #2907.
These changes ensure that the banner always displays correctly upon initial load of the keyboard.

fix(ios/engine): banner inconsistency

---

HISTORY.md

Follow-on to #3926
* Use `oem/fv/ios` and `oem/fv/android` for FV changes
* Add missing commit types
* Changes `deps` to use scopes (dependabot changes)
* Use `common/resources` for `ci` changes

chore(common): additional cleanup to HISTORY.md

---

mac/Keyman4MacIM/Keyman.Debug.entitlements
mac/KeymanEngine4Mac/KeymanEngine4Mac.xcodeproj/project.pbxproj
mac/build.sh

Cleans up a bunch of bits and pieces around the build process and makes sure that files are re-signed after we update the Info.plist file.

fix(mac): re-sign files post plist update

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m

Relates to #3935, #174, #458, #3243. (Not marking as fixed because it depends on external changes.)
This switches Java apps into legacy mode. However, Java itself will need patching to support Keyman, as it makes assumptions about input methods, including matching specific input methods by name, before enabling its complex text support.
I think we should consider backporting to 13.0 if the Java fix is accepted in reasonable time.
I have submitted a bug report but submitting a patch to the OpenJDK project looks [tiresome and convoluted](https://stackoverflow.com/questions/29379425/where-to-report-issues-of-openjdk-when-youre-not-a-openjdk-developer). It requires a change to a single file, [AWTView.m](https://github.com/openjdk/jdk/blob/6329de45045da3ce937cd22d82e74c3f142ea3f2/src/java.deskt …

fix(mac): turn on legacy mode for Java apps

---

web/source/dom/domManager.ts

As noted on https://help.keyman.com/DEVELOPER/ENGINE/web/13.0/reference/core/init#init_options, the default attachment style on touch devices is supposed to be `'manual'`, not `'auto'`.  This is handled by `this.keyman.setDefaultDeviceOptions(opt)`:
https://github.com/keymanapp/keyman/blob/285319ba37f39d56b967d09930462b59639994be/web/source/kmwnative.ts#L27-L34
Caught during acceptance testing according to https://github.com/keymanapp/keyman/wiki/User-Testing-for-Web#tests in prep for Beta.

fix(web): default attachment behavior

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m

Fixes #3939.
Arrow keys, function keys and a handful of other keys should trigger a context reload (for legacy apps, that means a context flush). This means that deadkeys are also flushed when any of these keys are pressed, in the same way as a Command key or a mouse click already did.

fix(mac): arrow keys now reset context

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m

Fixes #1953.
Makes it possible to specify additional apps that need 'legacy' handling without requiring an updated build of Keyman for Mac. The list should be stored in user defaults under the `KMLegacyApps` key. It can be viewed with the command:
```
defaults read keyman.inputmethod.Keyman KMLegacyApps
```
And updated with:
```
defaults write keyman.inputmethod.Keyman KMLegacyApps -array value1 value2 ...
defaults write keyman.inputmethod.Keyman KMLegacyApps -array-add value1 value2 ...
```
Each entry should be a regex that matches the client app id.
For example:
```
defaults write keyman.inputmethod.Keyman KMLegacyApps -array com.microsoft.Word '^com.github.atom$'
```
(Note for purity, the `.` should be escaped in the regex but it'll actually be fine without...)
This commit also adds …

feat(mac): user-controllable legacy app list

---

mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/MacVKCodes.h

Turns out that these codes are the standard mac mVk_ codes, so just needed to look up the appropriate code in a table. Hmm.

chore(mac): fix iso section key code

---

HISTORY.md

Part 3 of cleaning up HISTORY.md following #3942 and #3926
* Fix scopes that were `lmlayer` and `web/utils`
* Cleanup `common` scopes to be more specific (if possible)

chore(common/resources): Part 3 of additional HISTORY.md cleanup

---

oem/firstvoices/android/.editorconfig
oem/firstvoices/android/app/src/main/assets/setup/android-instructions.css
oem/firstvoices/android/app/src/main/assets/setup/main.html
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java
oem/firstvoices/android/app/src/main/res/values/strings.xml

Fixes #3922
Currently, the FV UX allows a user to set FV as a system keyboard before a keyboard has been selected.
This was causing a lot of Sentry issues as the app had to fallback to the sil_euro_latin keyboard.
This PR adds disables the "Setup" button until a keyboard is selected.
CSS updated to fix button and text layout
**2 Setup** button disabled when a language isn't selected
**2 Setup** button enabled when a language has been selected
**2 checkbox** after setup complete

fix(android/oem): Check keyboard selected  before allowing setup

---

linux/scripts/launchpad.sh

- We have to provide env variable to be able to select correct
dependencies at build time
- Add focal and groovy and remove xenial and eoan
- We need to build once before creating the source package so that
the man pages get generated. In v14 we do that during the binary
build, but that requires additional build dependencies, so for v13
we do it this way.

chore(linux): Fix launchpad script (v13)

---

mac/build.sh

Fixes #3331.
Handles temporary failures calling altool where Apple servers return "Could not find the RequestUUID" for a few minutes post-upload.
Example log we are handling:
```
[04:50:44][Step 5/5] Zipping Keyman.app for notarization to /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/mac/Keyman4MacIM/build/Release/Keyman.zip
[04:50:44][Step 5/5] Uploading Keyman.zip to Apple for notarization
[04:51:23][Step 5/5] <?xml version="1.0" encoding="UTF-8"?>
[04:51:23][Step 5/5] <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
[04:51:23][Step 5/5] <plist version="1.0">
[04:51:23][Step 5/5] <dict>
[04:51:23][Step 5/5] 	<key>notarization-upload</key>
[04:51:23][Step 5/5] 	<dict>
[04:51:23][Step 5/5] 		<key>RequestUUID</key> …
```

fix(mac): improve robustness of altool call

---

mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m

If multiple copies of a package are saved by a browser, the browser will typically append a ` (#)` to the filename, where `#` is a number. This should be stripped off before installation to prevent duplicates of the package being installed.
Fixes #2488.

fix(mac): Handle duplicate filenames for packages

---

common/models/templates/src/quote-behavior.ts
common/models/templates/test/test-quote-behavior.js

Fixes the output ordering of quotation-style punctuation characters for RTL languages.

fix(common/models): proper RTL quote ordering

---

mac/history.md

I was reviewing existing help.keyman.com product version histories and noticed mac never got updated for stable-13.0.
I changed this on `master` cause I didn't want to trigger a stable-13.0 build...

chore(mac/resources): Catch up mac history for 13.0 releases

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
android/KMAPro/kMAPro/src/main/res/values/strings.xml
android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java

Fixes #3958 
Some of the legacy keyboard packages are invalid because they
* don't include .JS touch-optimized keyboard
* don't have languages assigned in kmp.json
This adds additional checks during a package installation and provides the notification when a keyboard package fails
Test by attempting to install "mbsindhi" keyboard.

fix(android/engine,android/app) Notify when invalid keyboard package fails to install

---

linux/history.md

Similar to cleanup in #3977 
This fixes the formatting for the Keyman for Linux 13.0 releases in history.md

chore(linux/resources): Cleanup formatting in  history.md

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java

Fixes #3997
This sanitizes the Sentry navigation breadcrumbs so they don't include key information.
For testing the breadcrumb, I manually created breadcrumbs in `KMManager.shouldOverrideUrlLoading()` for "showKeyPreview"
```
Breadcrumb breadcrumb = new Breadcrumb();
breadcrumb.setCategory("navigation");
breadcrumb.setType("navigation");
breadcrumb.setData("from", url);
breadcrumb.setData("to", url);
breadcrumb.setLevel(SentryLevel.INFO);
Sentry.addBreadcrumb(breadcrumb);
```
Reference

fix(android/app,oem/fv/android): Sanitize Sentry navigation breadcrumbs

---

windows/src/desktop/desktop.groupproj
windows/src/desktop/insthelp/Keyman.System.InstHelp.KeymanStartTaskUninstall.pas
windows/src/desktop/insthelp/insthelp.dpr
windows/src/desktop/insthelp/insthelp.dproj
windows/src/desktop/insthelp/main.pas
windows/src/desktop/kmshell/util/Keyman.System.KeymanStartTask.pas

Fixes #3994.
Fixes #3780.
Fixes #3864.
Fixes KEYMAN-WINDOWS-5T.
Task creation was failing for some users because Windows Tasks are all stored in a shared folder, so attempts to use the same task name by different users were failing, especially if the user was a non-admin user.
Furthermore, attempts to execute the trigger would fail because Windows treats keyman.exe as needing elevation in this context (even though it doesn't, actually), and so I changed the trigger to call `kmshell -s`, which then does the needful.
Finally, the uninstaller now attempts to remove all the scheduled tasks in the Keyman folder. It doesn't care if it fails -- it's just cleanup and doesn't impact the system adversely if the tasks hang around.

fix(windows): Task creation and deletion cleanup

---

windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboard.pas

Fixes #4005.
Fixes #3938.
Fixes KEYMAN-WINDOWS-5V.
The wrong object was being freed which caused an access violation internally.

fix(windows): crash with package online update

---

windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas

Fixes #3563.
When a keyboard is updated in an online update check, keep the existing language assocations. This is fixed by using the new install paradigm which does not change the user's language associations, and so it also happens to fix issues with non-elevated users who do an update and would end up with no languages installed.

fix(windows): Keep language associations when updating keyboard

---

windows/src/desktop/kmshell/install/Keyman.Configuration.UI.KeymanProtocolHandler.pas
windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas

Fixes #3993.
Fixes KEYMAN-WINDOWS-4P.
Handles network errors which caused an exception, e.g. connection timed out, or 12030 The connection with the server was terminated abnormally.

fix(windows): Handle network errors when downloading keyboards

---

windows/src/engine/keymanx64/keymanx64.cpp
windows/src/global/delphi/general/Keyman.System.KeymanSentryClient.pas
windows/src/global/vc/keymansentry.cpp

We used the 'Started' event when testing Sentry integration. We no longer need it, but I left it in as commented code so we can re-enable if/when we do Sentry updates in the future and need to re-test.

chore(windows): disable Sentry 'Started' event

---

ios/engine/KMEI/KeymanEngine/Classes/PackageWebViewController.swift

Turns out that #3889 had some rather unexpected interactions with the display of package welcome.htm pages; welcome.htm was being improperly detected as an 'external' link, which consistently resulted in the display of a blank welcome screen.

fix(ios): package-internal links should be considered internal

---

ios/engine/KMEI/KeymanEngine/Classes/KeyboardMenuView.swift
ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift

Fixes #4018.
The scroll indicator's flash lasts about a second - plenty of time to indicate the potential to scroll.  It flashes regardless of whether or not there's a need to scroll, as seen here:
It's nothing intrusive or ugly, so I think that having it flash in these scenarios is "fine."

feat(ios/engine): keyboard-menu scroll indicator now flashes when opened

---

ios/engine/KMEI/KeymanEngine/Classes/PackageWebViewController.swift

Fixes #3984.
Based upon https://stackoverflow.com/questions/26295277/wkwebview-equivalent-for-uiwebviews-scalespagetofit#comment46936857_26583062.
This approach appears far more consistent than the original approach, likely since the injection is happening before the load process completes.  (See https://developer.apple.com/documentation/webkit/wkuserscriptinjectiontime)

fix(ios): better meta viewport consistency

---

crowdin.yml
resources/build/l10n/README.md

This is in preparation of updating our UI strings via crowdin.
Refer to resources/build/l10n/README.md
Some cleanup first in `crowind.yml`
* ~Use the "master" folder on translate.keyman.com for Alpha pre-release strings~
* Fix paths for windows and ios
@jahorton and @mcdurdin are the "translation" paths still correct for your platforms?
TODO:

chore(common/resources): Fix dest paths for crowdin strings

---

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html

Fixes #3985.  Likely by working around some sort of iOS bug... that I haven't found any online mention of.  Yay.
After identifying a 100% reproduction-rate sequence for #3985 (see [this comment](https://github.com/keymanapp/keyman/issues/3985#issuecomment-736274186) for details), I was finally able to start reliably debugging the issue.  After diving through the related call stacks, I noticed some _very_ peculiar behavior going on.
When the error occurs, it's because the system keyboard's constructors and `loadView` functions... were never called.  They're new and distinct instances, but our code never constructed them.  I thoroughly documented reference values and exact breakpoint locations to come to this conclusion, as it's a pretty serious accusation to make against iOS and/or the …

fix(ios/engine): adds check for keyboard load success, auto-reset on load failure

---

resources/build/increment-version.sh
resources/build/trigger-builds.inc.sh
resources/build/version/src/index.ts

Fixes #4061.
Four things:
1. Reorder the script steps so that builds are triggered before the PR is created. This should not really be necessary, but I am seeing some evidence that TeamCity is not respecting the commit sha we request to build. (This arose with 14.0.194 where a build agent became unavailable during a build and TC cancelled and restarted the build, but from a later revision... which this particular fix may not help, I guess...)
2. Add debug logging so we can see exactly which commit sha that we send to TeamCity
3. Handle errors in version increment by aborting the script with an error.
4. Add a -f force mode which we can use to trigger a build even if no changes are detected. This will need a corresponding patch in TC.

fix(common): improve increment-version robustness

---

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift

Fixes #4020.
I looked at using a JavaScript command queue as an alternative, but that approach conflicts pretty nastily against #4054 because of the unknown aspects of the bug it works around.

fix(ios/engine): preserves early context-setting effects

---

linux/keyman-config/debian/control

This change implements the Keyman part of #3966. The `keyman` package now recommends the installation of `onboard-keyman` instead of `onboard`.

feat(linux): Rename onboard package

---

common/core/web/tools/sentry-manager/src/index.ts

Fixes #4063 by sanitizing the embedded KMW event before it gets sent to Sentry
* breadcrumb
* request.url (fragment)
See Sentry issue [2027](http://sentry.keyman.com/organizations/keyman/issues/2027/?project=11)

fix(common/core/web): Sanitize embedded KMW Sentry events

---

windows/src/desktop/kmshell/install/Keyman.Configuration.UI.InstallFile.pas

Fixes #4068.
If a keyman://download/keyboard/ link contains an `=` sign (e.g. for BCP 47 tag), then kmshell was treating it as a parameterised local filename rather than giving it the property url protocol handler treatment.

fix(windows): keyman: link with = sign is mishandled

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java

From https://github.com/keymanapp/keyman/pull/4071#issuecomment-737704988
> can you remove the java code that is unnecessary?
> ...sentry-android is not going to receive navigation events to sanitize.
Since Sentry navigation breadcrumbs are handled by embedded KMW sentry-manager, the sentry-android change in #4025 need to be reverted.

chore(android/app,oem/fv/android): Revert #4025

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Fixes #3922
Currently, we've been sending a Sentry report if KMManager doesn't have an installed keyboard to start. Some apps (like FV) don't install a keyboard until the user chooses to. FV also doesn't use the in-app keyboard.
@mcdurdin adds:
> The only time we want to know about falling back is if there is an error in another keyboard. If there's no default keyboard we probably don't need an error report
* Removes the in-app keyboard Sentry log about not having a keyboard installed (left the system keyboard Sentry log at l. 2087)
* Send a Sentry log when having to fallback to a default keyboard (FV example in this Sentry [log](https://sentry.keyman.com/organizations/keyman/issues/2081/?project=21))

fix(android/engine): Remove in-app keyboard Sentry log about fallback keyboard

---

android/KMEA/app/src/main/assets/keyboard.html
common/core/web/input-processor/src/text/inputProcessor.ts
common/core/web/input-processor/src/text/prediction/languageProcessor.ts
common/predictive-text/docs/worker-communication-protocol.md
common/predictive-text/index.ts
common/predictive-text/worker/index.ts
common/predictive-text/worker/model-compositor.ts
common/predictive-text/worker/worker-interfaces.ts
ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
web/source/kmwbase.ts
web/source/osk/banner.ts

Fixes #3981.
May have "interesting" interactions with Android; extra user testing is advised.
- Test against "Clear Text" operations within the mobile apps.  Do reasonable predictions (as if the text had always been blank) occur, or does it seem like old, cleared text is still remembered?  Or something else entirely?
- Test against cursor / caret movement
- On the system keyboard level, find an app (or web page) with 2+ input fields.  Type text in both, then swap between them mid-word.  What sort of predictions arise then?

fix(common/core/web): predictive context reset

---

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift

Fixes #3986.
Sad that it doesn't work before iOS 11, but it gets the job done pretty nicely.  I don't see any way to double-check that there is pre-existing selected text otherwise.

fix(ios/engine): deletion for selected text at the context start

---

windows/src/Target.mak
windows/src/buildtools/help-keyman-com.sh
windows/src/desktop/help/build.sh

Reworks help-keyman-com.sh and brings help build.sh in line with it so that it opens a PR now on help.keyman.com.
Also fixes the failed Windows build.
Tested locally; the automatic PR merge will not happen yet. I want to apply these same changes to the keyboards repository so that help deployment from keyboards is not direct to master.
See sample PR at https://github.com/keymanapp/help.keyman.com/pull/269

fix(windows): help deployment

---

web/source/osk/banner.ts

Fixes #4079
This fixes the issue where clicking on a blank suggestion would throw the linked Sentry error.
``` javascript
Cannot read property 'tag' of null
```
* Launch Keyman for Android (with the default English keyboard and nrc.en.mtnt model)
* Start typing
* For valid suggestions, click and verify suggestions are inserted
* Continue typing gibberish until 1-3 blank suggestions appear in the banner
* Click on a blank suggestion and verify nothing happens
I'm still unclear how reversions work. If I backspace enough times to get blank suggestions, it seems like I get in a state where suggestions are no longer generated
Scenario
1. Type "qwerty", <kbd>enter</kbd> "noooo"
2. Backspace to "noo", and suggestions become blank
3. If I backspace all of "noooo", suggestions are still blank
4. …

fix(web/ui): Add check for suggestion.tag

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift
ios/keyman/Keyman/Keyman/MainViewController.swift
ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift

As seen at https://developer.apple.com/documentation/uikit/view_controllers/adding_a_document_browser_to_your_app:
> Important
>
>Always assign the document browser as your app's root view controller. Don't place the document browser in a navigation controller, tab bar, or split view, and don't present the document browser modally.
>
>If you want to present a document browser from another location in your view hierarchy, use a `UIDocumentPickerViewController` instead. 
The implementation we've been using until now was based on the `UIDocumentBrowserViewController` instead.  This PR contains the necessary tweaks for using the "correct" classes & patterns.  There was also a bit of an issue backing out of the document picker in iOS 12 (at least when run in the Simulator), so I've added a …

refactor(ios/engine): changes "install from file" to better match Apple guidelines

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift

Recently, it seems that our "Install From File" functionality stopped working correctly.  After a bit of digging, it turns out this is due to how file-system security in iOS now (?) works, and it seems this may be more stringent on actual devices than on Simulator.
This fixes the issues my test devices had when attempting to address [this Community site issue](https://community.software.sil.org/t/ios-keyboard-package-cannot-be-installed-in-the-keyman-app-keyboard-testable-properly-in-phone-browser/4112/14).  It's not yet clear whether or not the root cause of that issue matches that from my repro attempts.
Note that this is currently a dependent PR of #4089.  I ran into an interesting issue when attempting to rebase against `master` that _might_ be due to new Swift / Xcode requirements on …

fix(ios/engine): requests security for imported files

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/DownloadResultReceiver.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java
android/KMAPro/kMAPro/src/main/res/values/strings.xml
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Fixes #3895 where the user could interrupt a keyboard package installation by clicking the globe "keyboard picker" in between the package downloading and before the Stepper renders for the package installation.
This moves the Progress Dialog cleanup to block the user from accessing the keyboard picker until the package installation finishes or the package download fails.
This PR also guards against accidentally trying to install the same keyboard package multiple times in succession.
These involve searching for "sil_cameroon_qwerty" from keyman.com, before clicking the green button to install
1. From the Android settings, disable network connection
2. Click the green button to install
3. Verify keyboard download fails and the in-app keyboard is usable (not blocked by the progress dialog) …

fix(android/app) Change UX to ensure package installation finishes

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift
ios/keyman/Keyman/Keyman/MainViewController.swift
ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift

A tale of two devices, before & after style:
**Before**:
**After**:
And for the device / OS version that _really_ motivated this...
**Before**:
**After**:
The main UI for file-system navigation was broken in iOS 11 & 12; apparently there are some rough edges in Apple's implementation of its `UIDocumentPickerViewController` class.
There's also the plus that the altered code is "simpler" than the original.

fix(ios): fixes nav bar issues when using "Install From File"

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/AssociatingPackageInstaller.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift

This fixes a regression from 13.0 stable that resulted from the installation rework.
Fixes #3982.

fix(ios): autosets + autodisplays keyboard after a package install

---

web/source/osk/visualKeyboard.ts

(Updated)
Mitigates #3991 
The linked Sentry error on the issue shows that occasionally, `_Box` is null when used for `yMin` calculations.
This adds a simple null check

fix(web/ui): Add null check for calculations when canceling touch

---

ios/engine/KMEI/KeymanEngine/Classes/Migrations.swift

Should something go wrong in the migration process, it's (unfortunately) possible for the results to report a package without either a keyboard or a lexical model.  This can cause startup crashes within the Keyman app and may be related to #4051, though it's hard to say for certain.
I'll need a repro for creating the erroneous state in order to address the root issue, but that's currently lacking.  It's likely possible to find one, but _that_ looks to be a quite time-consuming process... and there are currently higher priorities to address.

fix(ios): prevents crash from failed legacy-resource-wrapping attempt

---

web/source/osk/oskManager.ts

Fixes #3996.
This is a tentative fix: it merely prevents `_Hide` from having any effect when in embedded mode. Tested on Android and could not force any issues.
However, it addresses the symptom and is probably sufficient but does not actually fix the root issue of the problem, which is that the `_Hide` method should never be called for embedded mode, as keyboard visibility is controlled by the host Keyman Engine on the device. Digging out those code paths is a much bigger job, and as the keyboard continues to function correctly if the effect of the hide (opacity=0) is undone by hand using web inspector, I am reasonably confident that this won't break other things.
@jahorton, would you be able review this and give me feedback on the appropriateness of this fix please?

fix(web): sporadic blank keyboard on Android

---

android/version.gradle

We now generate a versionCode directly from the release version number, and this is what we use for Google Play Store to ensure that we have an always-incrementing version number.

chore(android): rework versionCode system

---

windows/src/engine/keyman/UfrmKeymanMenu.pas

Fixes #4112.
Glitch in keyboard menu from scrollable buttons being drawn at top-left -- when the menu was not scrollable.

fix(windows): glitch in keyboard menu

---

windows/src/engine/keyman/UfrmKeymanMenu.pas

Fixes #4012.
If the menu previously was scrollable, then it would potentially show items at the wrong offset because the offsets were not reset when the menu popup was called if no scroll was needed.

fix(windows): menu scroll positions need reset at popup

---

windows/src/desktop/kmshell/xml/keyman_options.xsl

Fixes #4113.
The option "Switch to On Screen Keyboard/Help automatically when a keyboard is selected" is obsolete and we should remove it from the UI.
Note that this does not remove the API surface, just hides the option from view, as there may be apps relying on the API value.
Not touching help just now as that will be addressed in a help update in the future.

fix(windows): remove obsolete option 'Switch to OSK/Help'

---

windows/src/desktop/kmshell/install/UfrmInstallKeyboard.pas

Fixes #4111.
The keyboard tag passed in from search would  often be missing a region tag which is required on Windows.

fix(windows): Canonicalize BCP 47 tag on keyboard download

---

windows/src/desktop/kmshell/help/UfrmHelp.dfm

Fixes #4004.
Centres the help window when it first appears.
There is still a small resizing event but that will be handled with a separate PR for #3765.

fix(windows): help window centred on load

---

HISTORY.md

Add `common` scope to 14.0.209 so the beta release will show in the version history.

chore(common): Update history for 14.0 beta release

---

resources/build/version/src/fixupHistory.ts
resources/build/version/src/graphql/queries.ts

The version history collector got confused because of commits on two branches and needs to differentiate when asking for the latest PR on a branch.
This will be 🍒-picked to master.

fix(common): increment version needs to check base

---

resources/build/version/src/fixupHistory.ts
resources/build/version/src/graphql/queries.ts

The version history collector got confused because of commits on two branches and needs to differentiate when asking for the latest PR on a branch.
See #4155 for beta branch PR.

fix(common): increment version needs to check base 🍒

---

windows/src/desktop/kmshell/xml/config.css

Fixes #4009.
Brings the uninstall language button above the text so it is clickable even when the text overlaps.

fix(windows): uninstall language button z-index

---

windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas
windows/src/desktop/kmshell/xml/onlineupdate.xsl

Fixes #4040.
Also now prevents the spurious "no updates are available" message from appearing when the user cancels the update dialog.

fix(windows): Online Update dialog layout was messy

---

windows/src/buildtools/sentrytool/Keyman.System.AddPdbToPe.pas
windows/src/buildtools/sentrytool/sentrytool.dpr
windows/src/desktop/kmconfig/Makefile

Fixes #4002.
Examining the logs shows that sentrytool is failing with an access violation when running on the build agent, although it works on my local machine. 
Fixes three separate issues relating to sentrytool:
1. Build should be failing if sentrytool fails.
2. Access violation when rewriting executable in some cases (originally missed due to point 1).
3. Typo in sentrytool call meant it wasn't working for kmconfig.exe (originally missed due to point 1).

fix(windows): sentrytool should fail build on exception and access violation when rewriting executables

---

windows/src/desktop/kmshell/util/Keyman.System.KeymanStartTask.pas

Relates to #4116. This may not yet fix the issue; I don't have enough detail to be sure of what the precise problem is. I have added one change to add a username to the task definition, which may make a difference; and I will be monitoring the more fine-grained exception reporting if that doesn't fix the problem.

fix(windows): create task fails

---

windows/src/desktop/kmshell/help/UfrmHelp.pas

Fixes #4057.
Keyboard help link was missing from the help dialog when instantiated from Keyman menu or OSK.

fix(windows): keyboard help missing

---

windows/src/desktop/kmshell/main/UfrmProxyConfiguration.dfm
windows/src/desktop/kmshell/xml/proxyconfiguration.xsl

Fixes #4007.
Proxy Configuration window is now the right size and focuses the Server text box appropriately.

fix(windows): Proxy Configuration window size

---

windows/src/engine/keyman32/Keyman32.cpp
windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/kmhook_callwndproc.cpp
windows/src/engine/keyman32/kmhook_getmessage.cpp
windows/src/global/inc/keyman64.h

When a keyboard is installed, Keyman will now only refresh its internal state on a given thread when that thread receives focus and/or input, rather than immediately. This will dramatically reduce the chatter caused by Keyman Engine when a keyboard is installed or settings are changed.
@MakaraSok, after installing this version, we need to verify that keyboards are correctly activated and usable in a target application after installing the keyboard, or when any settings are changed.

fix(windows): Improve refresh performance

---

windows/src/engine/kmcomapi/com/hotkeys/keymanhotkeys.pas
windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguagesinstalled.pas
windows/src/engine/kmcomapi/com/keyboardoptions/keymankeyboardoptions.pas
windows/src/engine/kmcomapi/com/keyboards/keymanpackagecontentkeyboards.pas
windows/src/engine/kmcomapi/com/languages/keymanlanguages.pas
windows/src/engine/kmcomapi/com/options/keymanoptions.pas
windows/src/engine/kmcomapi/com/packages/keymanpackagecontentfiles.pas
windows/src/engine/kmcomapi/com/packages/keymanpackagecontentfonts.pas
windows/src/engine/kmcomapi/com/packages/keymanpackagesinstalled.pas

Fixes #4006.
Fixes KEYMAN-WINDOWS-4C.
This fixes the list error exception which was masking the actual cause of #4006, which is already fixed by #4164.
Related issue #4119 is also fixed by #4164.

fix(windows): exception handling list error

---

windows/src/engine/keyman/UfrmKeyman7Main.dfm
windows/src/engine/keyman/UfrmKeyman7Main.pas
windows/src/engine/keyman/langswitch/LangSwitchManager.pas

As Keyman now monitors the Windows keyboard list from Control Panel, it is no longer sufficient to refresh the toolbar only when a Keyman keyboard is updated, as at that point Windows has not refreshed its own language list in the registry. Instead, we need to monitor changes to the relevant registry key and then refresh when those changes are 'complete'.
There is a problem: there does not appear to be a good way to monitor for changes to Windows language settings. `WM_SETTINGCHANGE` is sent when a language is added by the user in Settings, but the actual change happens asynchronously, and we are not notified when the changes are complete.
We also do not get notifications when languages are added via APIs.
Given the async nature of the language profile changes, this leads to race …

fix(windows): OSK toolbar sync

---

windows/src/desktop/inst/download.in
windows/src/desktop/inst/keymandesktop.wxs
windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas
windows/src/desktop/setup/Keyman.Setup.System.MsiUtils.pas
windows/src/desktop/setup/Keyman.Setup.System.OnlineResourceCheck.pas
windows/src/desktop/setup/UfrmInstallOptions.pas
windows/src/desktop/setup/UfrmRunDesktop.pas
windows/src/global/delphi/general/Keyman.System.UpdateCheckResponse.pas

Fixes #4041.
Show the version with tier and build flags in Setup so that it is clear which version of Keyman will be installed, as the Keyman version can be distinct from the setup.exe version.
Constructs the version tag from `version`+`stability` data in the `UpdateCheckResponse` and uses a new MSI property called `VersionWithTag` for Windows Installers. Older MSIs will still show `a.b.c.d` versions instead of the tagged version if they are checked locally (as opposed to online), because the new `VersionWithTag` property will not be present.

fix(windows): Show full version with tag in Setup

---

windows/src/engine/kmcomapi/com/system/keymancontrol.pas

This change has three fixes to improve the reliability of notifying Keyman Engine of updates to settings or keyboard installs:
1. It removes the closure pattern of the refresh thread, because that was closing on a variable on a different thread (`RefreshHandle`) and that could cause races and/or exceptions in the case of early free. What's more, the closure was actually unnecessary as the variable was really only used by the refresh thread!
2. It moves responsibility for setting the refresh token to the calling thread so that the caller can depend on the token being the one that is actually sent, removing a race.
3. Most important, the refresh thread now flushes all messages in its queue, as there may be multiple messages relating to the window construction that need to be processed …

fix(windows): Improve refresh reliablilty

---

windows/src/global/delphi/chromium/Keyman.System.CEFManager.pas

Fixes #4110.
CEF will create a debug.log file in the current folder if it encounters an error. Instead, it should be written to Keyman's diag folder. This fix is for both Keyman Developer and Keyman for Windows.

fix(developer): debug.log created unexpectedly

---

windows/src/developer/TIKE/xml/layoutbuilder/builder.js

Fixes #4015.
Maps `*LTREnter*` and `*LTRBkSp*` to the correct symbols on the touch layout builder.

fix(developer): Map symbols for *LTREnter* and *LTRBkSp*

---

resources/build/version/src/fixupHistory.ts
resources/build/version/src/index.ts

Fixes #4201.
This adds a comment to pull requests with information about which build a particular PR will be landing in, based on the HISTORY.md we have already updated.
Note: there will be a corresponding update to keyman.com shortly for the downloads/releases/tier/version page that is linked by these comments.

feat(common): annotate PRs with build links

---

windows/src/developer/TIKE/child/UfrmKeymanWizard.dfm
windows/src/developer/TIKE/child/UfrmKeymanWizard.pas
windows/src/developer/TIKE/main/UframeOnScreenKeyboardEditor.dfm
windows/src/developer/TIKE/main/UframeOnScreenKeyboardEditor.pas
windows/src/developer/TIKE/xml/app/editor/editor.js

Fixes #1724.
Note: character font in touch layout source editor uses charFont from phone layout only at present.

fix(developer): make touch layout editor source view fonts consistent

---

web/source/dom/domEventHandlers.ts

`LanguageProcessor.invalidateContext()` takes an optional parameter that KMW is generally able to supply, but had neglected to.
Prevents the warning defined here: https://github.com/keymanapp/keyman/blob/eefb21320d251d39fd36f75f7edb60ae7cbe20e2/common/core/web/input-processor/src/text/prediction/languageProcessor.ts#L164-L169
I've seen this warning appear in Sentry breadcrumbs, so this should reduce (if not eliminate) the frequency of that.  This should _also_ make predictive text a bit more stable; default suggestions can only be provided by said code block when the `if`-condition holds `true`, instead of the `false` that generates the warning.

fix(web): supplies missing (optional) argument to prevent warnings

---

ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift

The notifications that trigger the altered methods can be triggered from background threads, but contain code that manipulates the UI.  This does not follow good practices and can result in fatal errors within the iOS app.  Fortunately, Swift provides a pretty straightforward fix for that.
The `restoreNavigation` method pictured above is called by each of the three altered methods within their `DispatchQueue.main.sync` blocks, as those methods contain additional UI-altering code.

fix(ios): moves Settings notification UI code to main thread

---

resources/build/trigger-builds.inc.sh

This change is part of a fix for #4160 so that we build the tag instead of the next version.

chore(linux): pass tag to Jenkins build (#4160)

---

web/source/osk/oskManager.ts

Fixes #3697.
One of the handlers failed to update two important fields:  `OSKManager.width` and `OSKManager.height`.  _These_ are the fields that are used to set OSK cookie properties... which are then used to reload the properties whenever focus shifts between (DOM) controls.

fix(web): osk size & position after focus changes

---

windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguageinstalled.pas
windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguagesfile.pas
windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguagesinstalled.pas
windows/src/engine/kmcomapi/com/keyboards/keymankeyboardfile.pas
windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.MitigateWin10_1803LanguageInstall.pas
windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.Process.KPInstallKeyboardLanguage.pas
windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboard.pas
windows/src/global/delphi/general/kmxfile.pas

Fixes #1285.
Fixes #4184.
First, the keyboard profile and registration strategy was not taking into account the mitigation for Win10 1803 (#1285) and this meant that the Amharic, Tigrigna and Sinhala keyboards would not install correctly.
Second, with Windows 10 build 19597, the installation should work correctly for all three languages.

fix(windows): Update mitigation for Keyman 14 and Windows 10 19597

---

windows/src/engine/keyman32/kmprocess.cpp

Fixes #2690.
Fixes #3082.
In the debugger, key events such as <kbd>Enter</kbd>, <kbd>Ctrl</kbd>+<kbd>C</kbd>, <kbd>Ctrl</kbd>+<kbd>V</kbd> were being swallowed by the debug engine if they did not have rules within the keyboard. This change emits the key events so the debug memo can process them normally.
A sample keyboard which allows us to test the various scenarios:
```
store(&VERSION) '10.0'
store(&NAME) 'test debug default keys'
store(&TARGETS) 'any'
begin Unicode > use(main)
group(main) using keys
'a' + [K_ENTER] > 'axb'
'b' + [K_ENTER] > 'bx' use(emit)
+ 'c' > 'xyz'
group(emit) using keys
```
1. Handled key: press <kbd>c</kbd>: should emit `xyz`
2. Unhandled key: press <kbd>Enter</kbd>: should emit `\n` (where `\n` is a new line)
3. Handled key which is sometimes unhandled: press …

fix(developer): Allow unhandled keys to go through to debugger memo

---

web/source/osk/visualKeyboard.ts

Fixes #3953.
This changes the key preview positioning logic to better parallel the subkey-display positioning logic, as only the former was affected by the bug being fixed.

fix(web): OSK key preview positioning

---

web/source/dom/domOverrides.ts

Also, other browsers without access to the WebWorker `Worker` constructor.
Fixes #4242.
Fixes KEYMANWEB-COM-V.

fix(web): disables predictive text on Opera mini

---

android/KMAPro/kMAPro/src/main/res/values-ann/strings.xml
android/KMEA/app/src/main/res/values-ann/strings.xml

Manually check in Android files from crowdin for Obolo (`ann-latn`).
Can't use crowdin CLI because it doesn't handle custom languages
https://support.crowdin.com/api/language-codes/
Due to how Android localization only handles language and region codes. So we'll configure these as `ann`.
The code for Keyman for Android to change display language to Obolo will be handled on a separate PR.

chore(android/app): Add Obolo language from crowdin

---

web/source/dom/uiTouchHandlerBase.ts
web/source/osk/visualKeyboard.ts

Fixes #3991.
As noted by https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent,
> `offsetParent` returns null in the following situations:
>
>    * The element or its parent element has the `display` property set to `none`.
>    * The element has the position property set to fixed (firefox returns `<body>`).
>    * The element is `<body>` or `<html>`.
The `_Box` element certainly uses the `fixed` position property, and noting that we've seen cases with opacity at 0, it's not a _huge_ stretch to imagine that said cases could be treated the same way as `display = 'none'` from the first point above.
Both the banner and the keyboard layer group elements are direct children of `_Box`, so we'd be better off relying on that fact and just using `parentElement` instead of …

fix(web): unexpected errors in OSK / banner position calculations

---

linux/scripts/debian.sh
linux/scripts/package-build.inc.sh
linux/scripts/watch.in

This change switches the package version number for packages that are intended for the Debian package repo to match the Debian policies.
It also removes the comment from the watch file.

chore(linux): Improve version number for debian package

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Fixes #4019.
Rolls back #3009 and fixes base issue in alternative manner.
The core issue here was twofold:
1. We needed to set the window size to the whole screen in order for the popups to visible and touchable. We implement this in `onConfigureWindow`.
2. Once our window size is the whole screen, we need to tell the apps which part of the window is our keyboard UI, in `onComputeInsets`. This is the only part of the window which impacts the layout of the underlying app. We had not set the `visibleTopInsets` property and this caused the WeChat problems.
Finally, in order for this to work, we roll back the original fix in #3009 as that one breaks the full-screen layout requirement.
Tested with a wide range of apps on Android 10, including WeChat and Telegram. If @kienwt, @ericjding have …

fix(android): Popup misalignments and compatibility with WeChat, Telegram

---

android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample1/build.gradle
android/Samples/KMSample2/app/build.gradle
android/Samples/KMSample2/build.gradle
android/Tests/KeyboardHarness/app/build.gradle
android/Tests/KeyboardHarness/build.gradle

The Sample apps were migrated from Crashlytics to Sentry in #2778
I don't know when it started happening, but a user tried to build the latest 14.0.222 beta KMSample2 project and got runtime exceptions
```
Process: com.keyman.kmsample2, PID: 13914
java.lang.NoClassDefFoundError: Failed resolution of:
Lio/sentry/Sentry;
```
It seems only KMSample1 and KMSample2 are affected.

fix(android/samples): Fix Sentry dependencies

---

web/source/osk/visualKeyboard.ts

Fixes #4285.
While the explicit `fontDefined` and `oskFontDefined` variables are unnecessary, they do help with clarity when debugging.

fix(web): better font-wait null guards

---

web/source/osk/visualKeyboard.ts

Fixes #4026.
A quick comparison via Chrome's device emulation mode:
**Before**
**After**
Note:  I used an artificially low-res device to replicate the scenario reported in #4026 without any code/resource modifications to the testing page.
Shrinking the page further:
**Before**
**After**
Note how the resulting OSK is an, uh, "equal-opportunity offender", chopping off the tops of tall characters as well as the bottom of characters with 'descenders' in this scenario.
And, for a particularly extreme example:
**After**
----
This change ensures that the text on a key is always vertically centered... even if that means letting the text "overflow" past the key's boundaries in all directions.  Since the OSK's code directly _prescribes_ the height of its keys, we can set the text's `line-height` to …

fix(web): uses CSS line-height to vertically center oversized OSK keycaps

---

windows/src/ext/sentry/Sentry.Client.pas
windows/src/global/delphi/general/Keyman.System.KeymanSentryClient.pas

Under WINE, on macOS at least, `TSentryClient` is crashing at startup, e.g. when calling `SymInitialise`. In order to have a working kmcomp.exe on macOS/Linux, we'll just disable Sentry altogether for now.
I have tested this succesfully on Catalina with version 4.1.2 of WINE. Version 5.0 and 5.7 continue to struggle with other crashes. We need to do more investigation to find out why later versions are crashing.
Furthermore, WINE by default still does not include wine32on64 which is needed for kmcomp.exe, so we should add kmcomp.x64.exe to the keyboards repository and use that instead (see corresponding fix keymanapp/keyboards#1439 which adds that as well as fixing the modification date calculation). I'll add kmcomp.x64.exe (and latest version of kmcomp.exe) in a separate PR on keyboards …

fix(developer): disable TSentryClient on WINE

---

web/source/osk/visualKeyboard.ts

Pretty much what the title says.
Fixes #3443.
A good, already-released test keyboard for this is `khmer_angkor`; it uses custom keycaps for the numeric layer and another special layer.

fix(web): no key previews for special keys reliant on keyboard-specific OSK font

---

resources/shellHelperFunctions.sh

Fixes #4288.
This reworks the `set_npm_version` resource script function to affect _all_ packages in the repo, not just the currently-active one.  As the `@keymanapp/lexical-model-compiler` package is dependent upon the `@keymanapp/models-types` package, it's important that `beta` versions of the former link to the matching `beta` version of the latter.  Otherwise... well, #4288.

fix(developer/compilers): fixes dependency versioning on alpha, beta tiers

---

windows/src/test/unit-tests/Makefile

Took quite a bit of digging, but I finally found the culprit.  Turns out, the big change from #4291 is actually a better solution to a problem addressed within https://github.com/keymanapp/keyman/pull/3836#issuecomment-727717729.  Unfortunately... the two solutions conflict with each other.  This is the "better solution" that [this comment](https://github.com/keymanapp/keyman/pull/3836#issuecomment-727791848) on the same PR was looking for:
> Wouldn't it be better to locate and fix the root cause of the version variance so that the version information being used is the same in all circumstances?
Now that _all_ in-repo packages are given identical versioning shifts during a Developer build, nothing breaks so long as those versions are kept consistent... which means no more package.json …

fix(developer/compilers): fixes developer build breakage from #4291

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMPLink.java

Fixes #4247 and reverts some of a0d1cb0307891fa469064a62228f6450773263c0
* This updates the app to handle `keyman://` links from the internal and external (Chrome) browser.
* This involves converting the legacy `keyman://localhost` link to a kmp install link.
Follow the steps from the reported issue:
> Attempting to install the Keyman Amharic keyboard does not work from https://keyman.com/amharic or https://keyman-staging.com/amharic
> To Reproduce
>
>Go to either url above
>Click on 'Download for Android'
>Select 'Yes - Install Keyboard'

fix(android/app): Handle keyman protocol from external browser

---

web/source/osk/oskManager.ts
web/source/osk/visualKeyboard.ts

Upon investigation of #4240, I noticed that a large amount of time was being spent constantly reloading OSK properties via KMW's web cookie.  This PR reworks those parts of the code, greatly reducing the amount of time spent cookie-parsing.
In terms of before-and-after feel, the OSK now loads much faster than before; I'd say the load time is halved at a minimum.
May also help mitigate https://github.com/keymanapp/keyman/issues/3294 a bit.  Definitely not a full fix, though.

fix(web): OSK loading efficiency

---

web/source/keyboards/kmwkeyboards.ts
web/source/kmwbase.ts
web/source/kmwuitoolbar.ts

There are a number of changes here to improve the performance of KeymanWeb and the toolbar and reduce unnecessary requests:
1. (kmwbase.ts and kmwkeyboards.ts) Added option `setActiveOnRegister`, default `'true'`; if set to `'false'` then will never attempt to activate the first registered keyboard. Note that this property is a string because the `options` object currently supports only string types, which is not ideal, but out of scope for this PR.
2. (kmwuitoolbar.ts) fixed issue with toolbar not matching correctly on full BCP 47 code (line 960) after keyboard change notification.
3. (kmwuitoolbar.ts) fixed issue with toolbar not showing active keyboard if the keyboard is activated before init is complete (see `ui.lastSelectedKeyboard` references).
4. (kmwuitoolbar.ts) avoided …

fix(web): toolbar and loading optimisations

---

android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample2/app/build.gradle
android/Tests/KeyboardHarness/app/build.gradle

Well this is slightly embarrassing 😞 
Right after fixing the Sentry dependency for sample apps in #4267, I introduced a globe-button crash when 
#4261 adds a dependency on `implementation 'androidx.preference:preference:1.1.1'` for KMEA consumers.
I've added a note in the 13.0 to 14.0 migration (wiki), and this PR updates the Sample and Test apps.
Fortunately, FV already has the dependency.

fix(android/samples): Add dependency on androidx.preference

---

web/source/osk/visualKeyboard.ts

When reviewing this PR, it may be helpful to revisit #3718:
> This PR standardizes the popup keys by not pre-pending the base key in the popup array.
When we stopped prepending the base key for phone-oriented form factors... we forgot to stop auto-selecting the first subkey.  Before we disabled said prepending behavior, this had been intended to indicate that the base key was still selected... just as a subkey.
Of course, we still want to preserve this functionality if the keyboard specifies a subkey matching its base key.  However...
Also from #3718:
> This also fixes #3092 because now Keyboard creators can control if/where the base key appears in the popup keys.
So, we're given no guarantee for where the base key lies within the subkey array.
----
That said, there was an interesting …

fix(web): default popup key selection, space highlight after popup

---

web/source/osk/visualKeyboard.ts

Fixes point 3 of #2990.
I'm kind of surprised the fix turned out to be so small.  I expected there to be extra changes required to drop the highlighting after the language menu is dismissed... but in my tests, this seems to automatically be handled?  Quite a pleasant surprise, assuming this holds on all affected platforms.
@MakaraSok 
I've tested a fair bit with iOS and through Chrome's mobile device emulation, but could also use some extra tests - especially for the Android app.  (Both in-app and as system keyboard)
Main things to check:
- Does globe key highlighting 'feel' right?
- Does it go away after the language-selection menu has been dismissed?

fix(web): language menu key highlighting

---

windows/src/developer/TIKE/child/UfrmDebug.dfm
windows/src/developer/TIKE/child/UfrmDebug.pas

The character grid in the debugger would become very slow as the number of characters increased, with substantial flickering. This refactor removes the unnecessary recalculations of the grid cell count and thus resolves performance problems.

fix(developer): Debug character grid performance

---

android/Samples/KMSample1/app/src/main/java/com/keyman/kmsample1/MainActivity.java
android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java

This cleans up `onKeyboardLoaded()` in the Android sample apps .
1. The old keyboard id `tamil99m` is no longer used when the sample apps changed from `tamil99m` to `basic_kbdtam99.kmp` (#2935)
2. The sample onKeyboardLoaded() code actually interferes with the globe button if the user adds more than 1 keyboard in the app. (First keyboard index always gets selected)
KMManager already sets the keyboard when it's added.

chore(android/samples): Remove old sample keyboard loaded code

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsFragment.java

Fixes #4260 so the preference screen titles (checkboxes) aren't truncated. 
* Enable Keyman as system-wide keyboard
* Set Keyman as default keyboard
Fortunately, we don't need to support Holo theme anymore
Android 5,0 (API 21)
Android 9.0 (API 28)

fix(android/app): Wrap preference screen titles

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift

Fixes #4281.
Rework of #4095, which was not properly implemented.  Turns out not everything needs to be security-scoped.

fix(ios): better handling of scoped vs non-scoped package URLs

---

web/bulk_rendering/README.md
web/bulk_rendering/compare.html
web/bulk_rendering/index.html
web/bulk_rendering/renderer_core.ts
web/bulk_rendering/tsconfig.json
web/package-lock.json
web/package.json

Instead of using html2canvas which is only an approximation of the DOM, we now use the video capture API to get an exact capture of the OSK.
Removes html2canvas from web package.json as this is no longer used anywhere.
Sample results using compare.html:

fix(web): bulk renderer using video stream capture

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java

Fixes item 2 of #4252 
> 2. We should be able to left-swipe an update notification to dismiss it -- there's no reason for it to be persistent :)
Yah for 1-line changes
I tested with a custom build that had an older version of sil_euro_latin.kmp (version 1.8.1).
When the app loaded, the update notification appeared.
I could then swipe to dismiss it.

change(android/engine): Allow swipe to dismiss update notifications

---

windows/src/desktop/kmshell/help/UfrmHelp.pas
windows/src/desktop/kmshell/web/Keyman.Configuration.System.HttpServer.App.pas

Fixes #4205.
Avoids encoding UTF-8 in the URL which has patchy support in some of our libraries.

fix(windows): invalid character in text content opening help

---

windows/src/desktop/kmshell/xml/installkeyboard.css

fix(windows): align title to top in Install Keyboard

---

ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift

Fixes #2757.
- Re-installing a package that has already been previously installed will automatically load the newly re-installed version, regardless of identical package filenames, relative package versions, etc.
----
With the first commit, the severity of the bug is downgraded for both cases:
> If I take care to ensure no automatic [package filename] renaming occurs behind the scenes, this does reproduce exactly. It gets tricky though, as various ways of importing .kmp files for testing will result in automatic `-1`, `-2`, etc renaming by iOS / Simulator / whatever.
- Now only requires swapping in and out of the keyboard.  There's no need to force-close & restart the app.
> If I slip up and let automatic renaming occur, merely swapping in and out of the keyboard is sufficient for a …

fix(ios): reloads keyboard after package updates

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift
ios/keyman/Keyman/Keyman/MainViewController.swift
ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift

Fixes #4328.
The issue arose due to the view hierarchy in which the package installer was being displayed when using "Install From File" for package installation.  The old implementation had a "hard requirement" that it be displayed from the top-level view, which isn't ideal.  Reworking it to fully and properly accept an arbitrary `UINavigationView` root and then using the Settings menu's instance allows us to keep the top-level-only logo away from the package installer.
I've tested the UX via all three standard install paths:
1. Opened a .kmp from outside the Keyman app.  (Safari download, iOS Files app)
2. Used our "install from file" menu option from within the app
3. Downloaded from keyboard search
There was also an issue with the 'activity spinner' not displaying during installation …

fix(ios): fixes accidental logo / cancel button overlap during package installation

---

web/source/build.sh

Fixes #4303.
Fortunately, for any CI builds before this, CI builds would have still failed - the bug was only for local builds.  `build.sh` has long looked for the existence of the UI modules' output files; as CI clears the output folders, those checks would have worked.  Local builds don't auto-clean, hence the bug.

fix(web/ui): propagates UI module build failures

---

.github/labeler.yml
.github/multi-labeler.yml
.github/workflows/labeler.yml

This PR adds the labeler-action GH action that applies labels based on the PR title or description. This allows to automatically assign labels based on our conventional commit message.

chore: Enhance PR labeling based on PR title

---

windows/src/desktop/kmshell/xml/splash.css

Fixes #4265.
This adjusts the button sizes of the splash screen to accommodate longer strings such as found in the Khmer translation. We could go to a more flexible layout model to allow for the buttons to stretch as needed, but that's a lot more work and I don't really want to try for that right now.
(ignore the missing Version string -- that's not related and not a problem, only on my dev machine)

fix(windows): Splash button sizes

---

.github/labeler.yml
.github/multi-labeler.yml
.github/workflows/labeler.yml

This PR adds the labeler-action GH action that applies labels based on the PR title. This allows to automatically assign labels based on our conventional commit message.
Cherry-pick from the master branch (PR #4226).

chore(common): Enhance PR labeling based on PR title

---

common/core/web/input-processor/src/build.sh
common/core/web/keyboard-processor/src/build.sh
common/core/web/utils/build.sh
web/source/build.sh

> We've been gradually having more of our build scripts `set -e` to fail on errors. Ideally, we can `set -u` too to flag unset vars
>
> _Originally posted by @darcywong00 in https://github.com/keymanapp/keyman/issues/4352#issuecomment-768082989_
Took a couple of tweaks on the main web script, but this'll put that in place for most of the Web-related scripts.

change(web): set -eu for web scripts

---

linux/scripts/package-build.inc.sh

If uscan fails (e.g. because there is no new version available because the workspace is in a dirty state) we now output an error message instead of silently failing.

chore(linux): Improve launchpad.sh script

---

linux/keyman-config/keyman_config/__init__.py
linux/keyman-config/tests/python.env

When running unit tests we try to install some keyboards with invalid URLs which normally results in an issue being reported on
Sentry.
This change detects when we're running unit tests and in that case doesn't initialize Sentry reporting.

chore(linux): Don't report on Sentry when running unit tests

---

windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/appint/aiWin2000Unicode.cpp
windows/src/engine/keyman32/appint/appint.cpp
windows/src/engine/keyman32/kmprocess.cpp
windows/src/global/inc/Compiler.h
windows/src/global/vc/xstring.cpp

Fixes #4196.
When deleting characters in a TSF-aware app, we must delete both halves of a surrogate pair. This behaviour differs from legacy apps, where a single backspace is usually sufficient to delete both characters.
Truly ancient apps that do not know about Unicode surrogate pairs are not going to delete both halves with a single backspace event. Fortunately, these are few and far between; we would handle them on a case-by-case basis if support questions for them arise.
When we come to integrating Keyman Core into Keyman for Windows, there will need to be some careful checking of surrogate pair support, as it is likely that the handling will need to change.

fix(windows): SMP-aware deletion in TSF-aware apps

---

windows/src/desktop/kmshell/xml/menu-frame.js

Fixes #4186.
Fixes #4183.
Fixes [KEYMAN-WINDOWS-7X](https://sentry.keyman.com/organizations/keyman/issues/2802/?referrer=github_integration).
Fixes [KEYMAN-WINDOWS-6Y](https://sentry.keyman.com/organizations/keyman/issues/2305/?referrer=github_integration).
The Enter and Spacebar key handlers had not been updated for the new layout and so threw errors in use.

fix(windows): Enter and Spacebar handling in Configuration

---

web/source/osk/oskManager.ts
web/source/osk/visualKeyboard.ts

Intended to replace #4317.
Proactively removes stylesheets whenever throwing out old OSK (`VisualKeyboard`) instances, rather than relying on a static variable referenced whenever a new one is loaded.

fix(web): removes stylesheets from unloaded keyboards

---

android/KMEA/app/src/main/assets/keyboard.html
common/core/web/input-processor/src/text/prediction/languageProcessor.ts
web/source/osk/banner.ts
web/source/osk/bannerManager.ts

Fixes #3294.
- Keyboards with associated dictionaries will now load more smoothly.
There will still be a small amount of layout calibration / FOUC-ish behavior on the initial load of each keyboard during the app / app extension's lifetime.  The egregious shift caused by the banner appearing late has been fixed.  (The banner's suggestions, on the other hand, will arrive at the original, 'late', time.)
Further keyboard swapping will be 100% smooth for as long as the system keeps the app/keyboard/extension alive.
@MakaraSok (or others, if so inclined)
Could use a user test on Android; I've already tested with iOS.
- While I _doubt_ it'll matter, a bit of testing with the keyboard-based keyboard-swapping shortcuts may not be a bad idea, just in case.
- Be sure to test that keyboard swapping …

fix(android, ios): eliminates OSK layout flashing from predictive text banner display

---

windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.MitigateWin10_1803LanguageInstall.pas

Fixes #4337.
The Sinhala language installation mitigation needed the BCP 47 code as well as the language code with the new language installation process.

fix(windows): crash for Sinhala mitigation

---

resources/build/trigger-builds.inc.sh

This is necessary to be able to distinguish between a newly triggered tagged build and a retriggered tagged build. The first tag param gets saved between builds, but then we need a second parameter that doesn't get saved that tells us if this build is a retriggered one.

chore(linux): Pass second tag parameter to Jenkins build

---

windows/src/desktop/kmshell/locale/de/strings.xml
windows/src/desktop/kmshell/locale/fr/strings.xml
windows/src/desktop/kmshell/locale/kan-Knda-IN/strings.xml
windows/src/desktop/kmshell/locale/km-KH/strings.xml
windows/src/desktop/kmshell/locale/my/strings.xml
windows/src/desktop/kmshell/locale/pt-BR/strings.xml
windows/src/desktop/kmshell/locale/qqq/strings.xml
windows/src/desktop/kmshell/locale/ta/strings.xml
windows/src/desktop/kmshell/locale/tr/strings.xml
windows/src/desktop/kmshell/locale/vec/strings.xml
windows/src/desktop/kmshell/xml/keyman_hotkeys.xsl
windows/src/desktop/kmshell/xml/strings.xml
windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas
windows/src/global/delphi/general/InterfaceHotkeys.pas

Fixes #4336.
Removes the "Show Keyboard Usage Page" hotkey entry as it has no effect, and cleans up Keyboard Usage and OSK Hint strings from all the current locales.

fix(windows): remove Show Keyboard Usage hotkey

---

windows/src/desktop/kmshell/install/UfrmInstallKeyboardLanguage.pas
windows/src/engine/kmcomapi/com/keyman_implementation.pas
windows/src/engine/kmcomapi/keymanapi_TLB.pas
windows/src/engine/kmcomapi/kmcomapi.ridl
windows/src/global/delphi/general/Keyman.System.CanonicalLanguageCodeUtils.pas

Fixes #4343.
This patch makes all language codes from the langtags.json dataset visible through the Add Language dialog. This avoids situations where an incomplete code such as "cmo" can result in an error (a script is required for "cmo" as it is written in either Latn or Khmr).

fix(windows): avoid invalid language codes in Add Language dialog

---

windows/src/global/delphi/general/CompilePackageInstaller.pas

Fixes #4354.
The redistributable build should be checking for the existence of either setup.exe or setup-redist.exe. Note that the only difference between the two is whether or not the file has a digital signature (as we should not put a digital signature on an executable that will later have a .zip appended, rather the final file should be signed).

fix(developer): don't check both setup.exe and setup-redist.exe

---

windows/src/developer/TIKE/main/KeyboardParser.pas
windows/src/developer/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas
windows/src/developer/kmconvert/Keyman.Developer.System.ModelProjectTemplate.pas
windows/src/developer/kmconvert/Keyman.Developer.System.ProjectTemplate.pas
windows/src/global/delphi/general/UKeymanTargets.pas

Fixes #2679.
If web is specified but not a touch platform, exclude touch layout from a generated project. Also, fixup list of supported platforms in the generated README.md.

fix(developer): Generate platforms correctly from template

---

windows/src/developer/TIKE/main/Keyman.Developer.UI.ImportWindowsKeyboardDialogManager.pas
windows/src/developer/kmconvert/Keyman.Developer.System.ImportWindowsKeyboard.pas

Fixes #2657.
Importing a Windows Keyboard had an option to select default targets for the imported keyboard, but the option was ignored. This propagates the option setting through the import process.

fix(developer): Import Keyboard support for Targets

---

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
ios/engine/KMEI/KeymanEngineTests/AssociatingPackageInstallerTests.swift
ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/URLSessionDataTaskMock.swift
ios/engine/KMEI/KeymanEngineTests/TestUtils/Downloading/URLSessionDownloadTaskMock.swift
ios/keymanios.xcworkspace/xcshareddata/xcschemes/Keyman.xcscheme

Updates our unit tests for compatibility with Xcode 12.2 & fixes a test bug.
The trickiest part was realizing that while the original `URLSessionTask`-related mocks were previously sufficient, later Xcode / Swift versions (not sure which) require a bit more mocking.  The original superclass `cancel` method was causing asynchronous errors on an unexpected thread.  (This is likely because the `resume` method would normally start a separate thread when not mocked, which `cancel` was unable to find as a result.)
Sadly, that means the test bug wasn't related to #4382 after all, _but_ this will facilitate diagnosing and fixing said bug substantially.

fix(ios): fixes unit test mocking, test init

---

ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift

May mitigate #4387. 
From https://developer.apple.com/documentation/dispatch/dispatchqueue/1452870-sync:
> Unlike dispatch_async(_:_:), this function does not return until the block has finished. Calling this function and targeting the current queue results in deadlock.
After a bit of tracing, it turns out that `InstalledLanguageViewController`'s package-notification-event handling methods are called on `DispatchQueue.main` - and two of those events - the less-frequently called ones - are using `.sync`, not `.async`.  The affected code blocks may safely be run asynchronously.
Alas, there's no guarantee at the moment that this is the only issue behind the crash log, but this change needs to happen anyway, given Apple's documentation on the methods involved.

fix(ios): fixes package-install/update event concurrency management

---

common/predictive-text/worker/correction/context-tracker.ts

🤦‍♂️
Fixes an issue with #4206, allowing that workaround to work for more than just the first word of the context.

fix(common/models): bksp workaround now works beyond first word

---

windows/src/global/delphi/general/Keyman.System.UILanguageManager.pas
windows/src/test/unit-tests/androidstringtokeymanlocalestring/Keyman.Test.AndroidStringToKeymanLocaleStringTest.pas
windows/src/test/unit-tests/group-helper-rsp19902/Keyman.Test.RegExGroupHelperRSP19902Test.pas
windows/src/test/unit-tests/model-ts-parser/Keyman.System.Test.LexicalModelParserTest.pas
windows/src/unit-tests/jsonutil/Keyman.System.Test.JsonUtilTest.pas
windows/src/unit-tests/keyboard-js-info/Keyman.Test.System.KeyboardJSInfoTest.pas
windows/src/unit-tests/keyboard-package-versions/Keyman.Test.System.CompilePackageVersioningTest.pas
windows/src/unit-tests/kmx-file-languages/Keyman.Test.System.KMXFileLanguagesTest.pas
windows/src/unit-tests/package-info/PackageInfoTest.pas
windows/src/unit-tests/standards-data/Keyman.Test.System.CanonicalLanguageCodeUtilsTest.pas
windows/src/unit-tests/standards-data/Keyman.Test.System.Standards.LangTagsRegistryTest.pas
windows/src/unit-tests/ui-language-manager/Keyman.System.Test.UILanguageManagerTest.pas
windows/src/unit-tests/windows-setup/Keyman.System.Test.InstallInfoTest.pas

DUnitX by default does case-insensitive string equality assertions, and we don't really want to make that assumption.
There was one minor fail uncovered in Keyman.System.UILanguageManager as a result of this -- it now returns a matching entry as found in the list of UI languages, rather than the input, to get same case as the UI language list entry.
Thank you @ermshiperete.

chore(windows): tests should be case-sensitive

---

windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas
windows/src/developer/TIKE/project/Keyman.Developer.System.Project.modelTsProjectFile.pas

Fixes #4393.
Fixes [KEYMAN-DEVELOPER-46](https://sentry.keyman.com/organizations/keyman/?query=KEYMAN-DEVELOPER-46).
Fixes [KEYMAN-DEVELOPER-45](https://sentry.keyman.com/organizations/keyman/?query=KEYMAN-DEVELOPER-45).
This arose because deleting a tab caused Delphi VCL to switch to another tab in the page control, which is IMHO a bug in the `TPageControl` VCL component. Furthermore, when the active page is changed under these circumstances, the normal `OnChange` and `OnChanging` events are not fired, which means that the Source tab (which is the lucky tab to be activated) never gets initialised. This cascades eventually to a crash due to the Source tab's text editor not being properly loaded.
Two parts to this fix:
1. Restore the active page when we delete a wordlist tab …

fix(windows): crash deleting wordlist

---

windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas

fix(windows): Use forward slashes in wordlist paths

---

linux/keyman-config/keyman_config/gnome_keyboards_util.py

If a Keyman keyboard is the only installed/selected keyboard in Gnome and the user uninstalls this in km-config, we have to set the value for `sources` to an empty array variant. Previously this crashed.
Fixes #4375.

fix(linux): Don't crash if uninstalling last keyboard

---

windows/src/desktop/help/index.md

I noticed an extra "Keyman" when incorporating the line towards Android and Linux help

chore(windows/resources): Fix typo about Community Forum link

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageFragment.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/StepperAdapter.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/HelpFile.java

Fixes #4021
Currently, linked assets in welcome.htm aren't viewable during package installation because the content is instantiated while the package resides in a temporary location (The package folder gets moved to the final path after the "INSTALL" button is clicked).
This PR separates displaying welcome.htm from the package installation process. This way, when the welcome.htm is viewed in the MainActivity handler: 
* Can reuse the HelpFile intent (already handles File Provider permissions and is used for displaying keyboard help)
* The package is in the final destination
We do lose out on the niceity of having an "OK" button to exit out of the welcome.htm page.
User will just have to hit the back button (same for closing keyboard help)
Some sample screens
khmer_angkor welcome.htm …

change(android/app): Separate displaying welcome.htm from keyboard installation

---

android/KMEA/app/src/main/AndroidManifest.xml

Follow-on to #4170 which removed usage of WRITE_EXTERNAL_STORAGE permission
The permission was removed from the main app's manifest, but also needs to be removed from KMEA.
I also checked the sample and test apps, and FV manifest; they're not affected.

fix(android/engine): Remove WRITE_EXTERNAL_STORAGE from manifest

---

windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectFile.pas
windows/src/developer/TIKE/project/Keyman.Developer.System.Project.kmnProjectFileAction.pas
windows/src/global/delphi/general/CompileErrorCodes.pas
windows/src/global/delphi/general/compile.pas
windows/src/global/inc/Comperr.h

Fixes #4250.
This implements @jahorton's suggestion of including the original name in a comment alongside the munged name, as well as appending the unique integer identifier of each symbol.
Note: the error reporting code needed a massage to support Unicode error strings; in the future we should update the C++ compiler to emit Unicode error strings also.

fix(developer): debug information with unicode identifiers

---

windows/src/developer/kmcmpdll/Compiler.cpp
windows/src/developer/kmcmpdll/Compiler.rc
windows/src/global/delphi/general/CompileErrorCodes.pas
windows/src/global/inc/Comperr.h
windows/src/test/unit-tests/kmcomp/test.bat
windows/src/test/unit-tests/kmcomp/test_4280_if_start_1.kmn
windows/src/test/unit-tests/kmcomp/test_4280_if_start_2.kmn
windows/src/test/unit-tests/kmcomp/test_4280_nul_start_1.kmn
windows/src/test/unit-tests/kmcomp/test_4280_nul_start_2.kmn
windows/src/test/unit-tests/kmcomp/tests.kpj

Fixes #4280.
Adds checks to verify that `if()`, `platform()`, `baselayout()` and `nul` are at the start of the context in the appropriate order.
Adds unit tests to validate these checks.
These are conditions that have been present in earlier versions of Keyman but not enforced until now. Keyboards that do not meet these conditions would not work correctly in all circumstances and should be updated to meet the requirements.
An alternative would have been to reorder the context string but that is much more complex as manipulation would also have been required for the output string. The enforced order is logical and reduces confusion in any case.
Updated documentation coming along shortly.

fix(developer): Compiler check for if and nul at start of context

---

windows/src/desktop/insthelp/insthelp.dpr
windows/src/desktop/insthelp/insthelp.dproj
windows/src/desktop/insthelp/main.pas
windows/src/developer/kmcomp/kmcomp.dproj

Fixes #4185.
Make sure Keyman is shut down during the uninstall so that it isn't left in a weird state with missing files. This also reduces the need for a reboot after uninstall.

fix(windows): When uninstalling, exit Keyman

---

common/predictive-text/unit_tests/headless/edit-distance/distance-modeler.js
common/predictive-text/worker/correction/context-tracker.ts
common/predictive-text/worker/correction/distance-modeler.ts
common/predictive-text/worker/model-compositor.ts

Fixes a situation where no suggestions were presented after moving the caret via UI.
For example, having just typed the text seen below:
and then moving the caret to the end of the second word, "quick":
Before, no suggestions would be displayed here.  These changes make it possible.
Note that, at this time, selecting one of those suggestions will apply the suggestion at the caret's position and will not delete any excess characters to the right... kind of like what the system iOS predictive text does.  The one difference:  it will also emit a space, even if one is immediately to the right of the current caret.  I'm now working on a child PR to address these issues, along with some other related behavior.
Turns out that this change brought some underlying issues in the correction-search …

fix(common/models): predictions after context reset / caret shift

---

resources/build/help-keyman-com.sh

Follow-on to #4433 and fixes failing CI builds
CI fails to checkout new help.keyman.com branches off of `staging`.
```
fatal: 'staging' is not a commit and a branch 'auto/windows-help-14.0.240-beta' cannot be created from it
```
We'll simplify just having help docs update the master branch on help.keyman.com

fix(common/resources): Just use master branch for help.keyman.com

---

windows/src/desktop/kmshell/xml/keyman_hotkeys.xsl

Fixes #4426.
After removing the hotkey for the Keyboard Usage pane, the hotkey `index` value was now offset from the hotkey `Target` value, which uncovered a bug where the two values were conflated.
Note that the parameter passed to the `keyman:hotkey_set` command is still called `index` -- this does not need to change.

fix(windows): hotkeys offset in config list

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Keyboard.java

This fixes a bug I found while checking out the FV Android 14.0 beta app. Those keyboards are bundled in the fv_all.kmp keyboard package, so the keyboard helps use the online links to `https://help.keyman.com/keyboard/`
* This fixes the logic in KeyboardInfoActivity so the keyboard help link is only disabled for local help where the FileProvider isn't available. (This might be addressed in #4421)
* Also deprecates a `KMManager.KMKey_HelpLink` key to avoid future confusion (All the remaining code uses KMManager.KMKey_CustomHelpLink for the key). The keys aren't documented on help.keyman.com, so nothing to update there.

fix(android/engine): Display online keyboard help

---

windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/kmhook_getmessage.cpp

Fixes #4369.
When Keyman is not handling a particular virtual key, it does not preserve the virtual key (TSF terminology, essentially reserves that virtual key + modifier for Keyman). In this situation, Keyman still receives and processes the virtual key event, but the modifier state is not passed through by kmtip to keyman32. This is normally okay, because our `GetMessage` hook is responsible for tracking modifiers.
However, in UWP apps, our `GetMessage` hook does not get run, and so we lose the modifier keys. Thus, this update ensures that the modifier keys are processed when received by the TSF TIP.
It does not hurt to process modifier events twice.

fix(windows): Track modifier changes in UWP apps

---

resources/build/help-keyman-com.sh

Act 3 of the help-keyman-com.sh refactor, follows #4433 #4459
My local testing had full paths for the environment var `$HELP_KEYMAN_COM` so that's why it worked for me, but not CI (uses relative paths)
l. 133 already did `pushd HELP_KEYMAN_COM`

fix(common/resources): Fix help.keyman.com path for commit

---

resources/build/version/src/fixupHistory.ts

This is a suggested approach for addressing the rate limit issues we were experiencing. We'll try it and see.
Have I got the `promise` mechanism correct here? It looks right to me but hard to test...

fix(common): create GitHub comments serially

---

common/core/web/keyboard-processor/src/text/outputTarget.ts
resources/build/trigger-definitions.inc.sh

Fixes #4463.
The bug directly fixed by these changes triggered a context desync when embedded in the Android and iOS apps, which is what caused #4463.

fix(common/core/web): mock construction with caret at index 0

---

linux/keyman-config/debian/control

The way we previously specified the Sentry library doesn't work when building on ppa because the build process there doesn't set the flags.

fix(linux): Fix dependencies on packages

---

resources/build/version/src/fixupHistory.ts
windows/src/Makefile

Fixes #4484.
tsysinfox64 was being signed, but too late in the build process as it is embedded into tsysinfo.exe. There was code to sign it earlier, but that was being skipped due to a missing build flag. This has been a problem for some time.
It is possible to test this by doing a full release build locally, but I will test on the next beta anyway once it merges, which might be a more efficient approach.

fix(windows): tsysinfox64 not signed

---

ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift
ios/keyman/Keyman/Keyman/MainViewController.swift

Fixes #3980.
While technically not 100% direct - it does present the Installed Languages view first - that's only with a short delay.  The keyboard search will automatically present immediately afterward.  This isn't exactly a bad thing either; this clearly demonstrates where a user can find the keyboard search if not using the "Getting Started" tutorial.

fix(ios): tutorial's link to "Add a Keyboard" links directly to keyboard search

---

web/source/kmwdevice.ts

fix(web): macOS 11 agent string parse

---

web/source/kmwdevice.ts

Fixes #4496.
Was caused by a suboptimal regex expression.

fix(web): macOS 11 agent string parsing

---

ios/engine/KMEI/KeymanEngine/Classes/Log.swift
ios/engine/KMEI/KeymanEngineDemo/AppDelegate.swift
ios/engine/KMEI/SystemKeyboard/KeyboardViewController.swift
ios/keyman/Keyman/Keyman/AppDelegate.swift
ios/keyman/Keyman/Keyman/Log.swift
ios/keyman/Keyman/SWKeyboard/KeyboardViewController.swift

This fixes an issue that had been interfering with my ability to properly assess #4126.
In short, up until now, our error logging never actually output log messages to a device's system logs.  That's 'fine' when debugging through Xcode, but there are some situations where that's not an available option.

fix(ios): app logging messages were transient, never stored

---

common/core/web/input-processor/src/text/inputProcessor.ts
common/core/web/keyboard-processor/src/text/ruleBehavior.ts

`null` is still permitted, of course.
Fixes #3695.

fix(common/core/web): core key-processing now always returns RuleBehavior type.

---

developer/js/source/lexical-model-compiler/build-trie.ts

... JS, I love you, but sometimes...
Fixes a 'fun' error that destroyed all wordlist weighting during some of my predictive text testing.  Its probable underlying cause is a `node` version update, which results in the following spot of fun:
So, for an English wordlist including the word "constructor", there's actually a pre-existing entry in the wordlist map-object.  Said entry is (obviously) "not a number," and in JS, NaN + any number = NaN.  This, in turn, causes a cascading failure that effectively destroys all wordlist weighting for the model.  For funsies, take a look at the result of said failure cascade:
This has near-certainly affected our recently-distributed versions of the MTNT model, unfortunately - we've got a [checked-in …

fix(developer/compilers): fixes error when "constructor" is in wordlist

---

web/source/dom/domDefaultOutput.ts
web/source/dom/targets/touchAlias.ts

fix(web): hides touch-alias caret when keystroke causes focus change

---

resources/build/increment-version.sh
resources/build/version/src/fixupHistory.ts
resources/build/version/src/index.ts

Allows us to manually run a version increment, for example if there is a problem with a release build such as running out of space on the download server.
When triggering from TeamCity, we need to manually set the force parameter to `-f`. This is a little bit of a failsafe.

chore(common): allow forced version increment

---

web/source/osk/visualKeyboard.ts

Fixes #4436.
Also fixes a minor, 14.0-only issue caused by some of the Web-core work that would have broken things on the beta -> stable transition.
Before:
After:
The test page above was introduced by #2802, the previous PR to patch up documentation keyboards.
If viewing the static keyboards on desktop, even mobile-oriented layouts will now dynamically rescale (their width) when the window is resized.  To facilitate this, static keyboard layouts are now always styled with percentage values, never exact pixels.
Since this is for a 'static' keyboard, font scaling may take additional work to get perfect.  Of note, though:  in the above images, font-scaling is set to a standard `1em`.  (Will not dynamically rescale with window resizes.)  Simply adding CSS styling to the root element returned …

fix(web): keyboard documentation patch-up

---

android/history.md
web/source/osk/oskManager.ts

A 🍒-pick of #4516.
While not _strictly_ necessary and not targeted at a major :fire: of any sort, I figure we may as well slip it in while a few other bugfixes are cherry-picked.  Having the fix land in 13.0 stable instead of 14.0 stable should allow any workarounds for the underlying bug to be removed earlier by any affected keyboard designers.
If we'd rather just leave it to 14.0, I understand.

fix(web): removes package namespacing from kbd's CSS class

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
ios/history.md

🍒-pick of #4095 and #4327.  (The latter is the 'final' version of the fix, as it wasn't handled perfectly the first time.)

fix(ios): now handles security-scoped files

---

windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/kmhook_getmessage.cpp
windows/src/global/inc/keyman64.h

Fixes #4525.
This is a regression from #4468, which inadvertently added modifier checks for `VK_CAPITAL` and `VK_NUMLOCK`, when it should not have done so, as the flag was then being reset when the key was released rather than toggled.
`ProcessModifierChange` pretended that it could handle `VK_CAPITAL` and `VK_NUMLOCK` but it would never have worked, and the other caller (the GetMessage hook) never passed those key events through, only Shift, Ctrl and Alt, so that's now what the TIP handler does as well.
This leaves the rest of the fix from #4468 in place as that appears correct.
I took the opportunity to move a repeated function declaration into keyman64.h.

fix(windows): Handle Caps Lock event correctly from TIP

---

windows/src/global/delphi/general/Keyman.System.KeymanSentryClient.pas

Fixes #4451.
If sentry.dll is missing, we should continue without error reporting, rather than crashing out.

fix(developer): run even if sentry unavailable

---

windows/src/global/delphi/lexicalmodels/Keyman.Developer.System.LexicalModelCompile.pas

Fixes #4221.
When the Keyman Developer IDE calls out to the lexical model compiler, it receives UTF-8 compiler message strings back but they are treated as Windows-1252 strings. This fixes that.

fix(developer): UTF-8 messages in LM compiler

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/AssociatingPackageInstaller.swift

Fixes #4493.
When asked to use an interactive language picker, the package installation system will now require the user to finish all installer-UI interaction before the installation system will signal completion of package installation to other components of KeymanEngine.  (There was a critical piece of concurrency code missing.)
There's one piece of post-install code that has UI effects, which is what was triggering the early welcome-dismissal.

fix(ios): package installer completion requires welcome dismissal

---

windows/src/engine/keyman32/Keyman32.cpp
windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/k32_globals.cpp

Fixes #4289.
Some settings changes would not apply immediately for 64-bit apps, as the refresh was not being processed until keymanx64 received focus (i.e. never, as keymanx64 does not have a visible window!)

fix(windows): Refresh settings on 64-bit apps

---

windows/src/desktop/kmshell/main/Keyman.Configuration.System.UImportOlderVersionKeyboards11To13.pas

Fixes #4445.
When upgrading from 11.0, 12.0 or 13.0, Keyman needs to re-register the TIPs so that we use the new registration model for 14.0. However, if we do this on a 14.0 version install, we end up registering TIPs for every single suggested language for a keyboard, which is definitely not what we want.
This fix simply looks to see if we have a 14.0-style installation already, as evidenced by the presence of a `Transient Language Profiles` key, and if found, does not continue the 11to13 upgrade process.

fix(windows): prevent re-registration of TIPs on 14.0 upgrade

---

common/core/web/keyboard-processor/src/text/keyMapping.ts
web/source/dom/preProcessor.ts

Fixes #1125.
Looks like the browser-based keymapping was done too late during keystroke analysis.
Note that moving said keymapping to earlier within the same function may slightly affect a few `.vkCode` values in the legacy path.  That said... the only use I see for `.vkCode` in further processing is a `> 255` check, which would _not_ be affected.  It's also quite possible that if there are side-effects, they're good ones - given how niche the scenario is, I wouldn't be surprised if this actually fixed a similar bug on that legacy path that simply hasn't yet been discovered.

fix(web): mnemonic keystrokes w FF keymapping

---

ios/help/basic/index.md
ios/help/basic/installing-custom-keyboards-dictionaries.md
ios/help/basic/sharing-keyboards.md
ios/help/index.md

Fixes keymanapp/help.keyman.com#158
* Clarifies the iOS help page title so users will know it's for installing custom keyboards/dictionaries

chore(ios/app): Adjust help titles for installing custom dictionaries

---

resources/build/help-keyman-com.sh

OK, hopefully this is the final nail in the coffin for getting the CI to upload in-app documentation to help.keyman.com
Refactors the destination path for `iphone-and-ipad`.

fix(common/resources): Fix help.keyman.com path for CI

---

windows/src/developer/kmcmpdll/Compiler.cpp
windows/src/developer/kmcmpdll/NamedCodeConstants.cpp
windows/src/developer/kmcmpdll/NamedCodeConstants.h
windows/src/developer/kmcmpdll/kmcmpdll.h
windows/src/developer/kmcmpdll/kmcmpdll.vcxproj
windows/src/test/unit-tests/kmcomp/test.bat
windows/src/test/unit-tests/kmcomp/test_namedcodeconstants.kmn
windows/src/test/unit-tests/kmcomp/test_namedcodeconstants.txt
windows/src/test/unit-tests/kmcomp/tests.kpj

Fixes #4423.
Using a named character constant with a store name that included characters outside ascii could cause kmcmpdll to crash with an assertion failure.
This fix allows store names defined in the .kmn file to use characters outside ascii.
Note that more work needs to be done on which characters are acceptable to use, as this is somewhat implementation-specific according to the C++ specification for `iswalpha`.
Added a test case to verify various named code constant examples.
Also removes dead code for `IsCJKUnifiedIdeograph` as this was never used and somewhat pointless in any case.
NamedCodeConstants.cpp could stand to be rewritten using `std::map` or equivalent. Current implementation is pretty icky.

fix(developer): Improve stability of named code constants

---

developer/js/build.sh
developer/js/source/package-compiler/kmp-compiler.ts
developer/js/source/package-compiler/kmp-json-file.ts
developer/js/tests/fixtures/example.qaa.sencoten/example.qaa.sencoten.model.kmp.json

Fixes #3199.
Ensures that the model package compiler passes schema validation for kmp.json. Three problems were corrected:
1. `followKeyboardVersion` is a source-only property; it should not be in deployable kmp.json.
2. `copyLocation` should have been a number not a string (in XML everything is a string... but JSON has more control here)
3. `fileType` is a source-only property; it also should not be in deployable kmp.json.
I have checked that the resulting files validate against the package kmp.json schema version 1.1.0 defined at https://github.com/keymanapp/api.keyman.com/blob/master/schemas/package/1.1.0/package.json.
None of these fixes should impact the use of these packages in target apps. `followKeyboardVersion` and `fileType` are used only in the source at package development …

fix(developer): schema conformance for model package compiler

---

windows/src/developer/TIKE/oskbuilder/TouchLayoutDefinitions.pas

Fixes #2740.
The definitions for several of the combined modifiers was incorrect, which led to a mismatch when attempting to import those layers from a visual keyboard into the touch layout editor.

fix(developer): touch layout osk import handling of multiple modifiers

---

windows/src/global/delphi/general/CompilePackage.pas
windows/src/global/delphi/packages/Keyman.System.PackageInfoRefreshKeyboards.pas

Fixes #2998.
Fixes #4509.
Three parts to this:
* The package compiler will now give a warning if a keyboard in a package does not contain any language metadata.
* Removed old canonicalization check during compile which is now handled better in `TPackageInfoRefreshKeyboards`.
* Reduced non-canonical BCP 47 tag warnings in `TPackageInfoRefreshKeyboards` to "info" so they do not block the build.
Point 3 above is one part of the outcome of our BCP 47 discussion at: https://docs.google.com/document/d/1N5CkTX7tlLlmUB9Mbd-LblY1ch1e642XxlTasC_WE_Q/edit#heading=h.fiy983iliay5

fix(developer): require language tag when compiling keyboard package

---

windows/src/developer/TIKE/dialogs/UfrmVisualKeyboardImportKMX.pas
windows/src/developer/TIKE/main/UframeOnScreenKeyboardEditor.pas

Fixes #3011.
Keys that have only whitespace will no longer generate separate key data for the on screen keyboard, as they have no visual presentation anyway.

fix(developer): Avoid blank keys when importing KMX to KVKS

---

windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.dfm
windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas
windows/src/developer/TIKE/main/Keyman.Developer.System.LexicalModelParser.pas

Fixes #2556.
This adds support for `isRTL`, `insertAfterWord`, and `quotesForKeepSuggestions` punctuation options for lexical models, both in the parsing and in the user interface. A number of options are presented to the user for the quotes and word breaking characters.
The parser continues to be a regex-based typescriptish parser. Expect it to be gross. It's too big a job to do properly right now, so it is somewhat limited and will bail if it finds structures it can't understand.
I would hope to use something a bit smarter in the future to interface with the editor. Probably when we are actually fully web-based and can depend on a Typescript compiler directly.
Please don't get mad at me! 😟😟😟

feat(developer): isRTL support for lexical model editor

---

windows/src/developer/TIKE/child/Keyman.Developer.UI.UframeWordlistEditor.pas
windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas
windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmWordlistEditor.pas

Fixes #3337.
In some situations, the wordlist editor was not tracking modified state 100% correctly, which meant that edits could be lost. This resolves that by simplifying the modification state tracking.

fix(developer): track modified state in wordlist editor better

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/AssociatingPackageInstaller.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/KeyboardSearchViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift

Fixes #4339.
Nobody likes a lack of feedback or when something instinctively feels broken.  It's better to let a user know that progress is happening... even if so.  So, toward that end... a batch of mini-features and fixes designed to better inform users of the app's progress during a keyboard search.
Something that may be worth keeping in mind:  the package installer uses asynchronous code that makes it quite possible for associated lexical model queries to still be ongoing when the user reaches a package's welcome page.  Commits 2 and 3 are about improving the UX in such conditions.
------
First commit:  the keyboard search now displays a progress bar while loading relevant pages.
That little bit of blue makes a _world_ of difference.  Without it... the search feels outright broken, …

chore(ios): better visual feedback for keyboard search during poor internet connectivity

---

windows/src/developer/TIKE/Tike.dpr
windows/src/developer/inst/kmdev.wxs
windows/src/global/delphi/general/KeymanPaths.pas
windows/src/global/delphi/lexicalmodels/Keyman.Developer.System.LexicalModelCompile.pas

Fixes #4278.
When Keyman Developer is installed without Keyman for Windows, the program silently crashes, because it is looking for libcef.dll in the Keyman Desktop install folder rather than using its own copy of it.
This improves the search for libcef.dll and kmbrowserhost.exe, and includes kmbrowserhost.exe with the Keyman Developer installation.
In the future, we could consider moving kmbrowserhost.exe into a common folder (perhaps when we split Keyman for Windows and Keyman Developer projects in 15.0).
I threw in a one-liner addressing a deprecated function warning in the Developer build.

fix(developer): improve CEF location search stability

---

windows/src/developer/TIKE/dialogs/UfrmKeyboardFonts.dfm
windows/src/ext/scfontcombobox/scFontCombobox.pas

Fixes #2789.
The Keyboard Fonts dialog skipped some fonts which it did not recognise as valid TrueType fonts. As a bonus, I've rewritten a few parts of it to make it significantly faster to load.
I also turned off the font formatting for the list, as it was not very helpful and hurt performance considerably.

fix(developer): Support all fonts in Keyboard Fonts dialog

---

windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.dfm
windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas
windows/src/developer/TIKE/child/UfrmKeymanWizard.dfm
windows/src/developer/TIKE/child/UfrmKeymanWizard.pas
windows/src/developer/TIKE/child/UfrmPackageEditor.dfm
windows/src/developer/TIKE/child/UfrmPackageEditor.pas
windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmProject.pas
windows/src/developer/TIKE/xml/project/keyboards.xsl
windows/src/developer/TIKE/xml/project/models.xsl
windows/src/developer/TIKE/xml/project/packages.xsl
windows/src/developer/TIKE/xml/project/welcome.xsl
windows/src/global/delphi/general/utilsystem.pas

Fixes #4314.
Adds 'Open Source Folder', 'Open Build Folder', and 'Open Project Folder' actions to various parts of Keyman Developer.
Note that the File actions box is also new in all three editors -- a rearrangement of existing controls, however.

feat(developer): Add different Open Containing Folder buttons

---

common/core/web/keyboard-processor/src/keyboards/defaultLayouts.ts
common/core/web/keyboard-processor/src/keyboards/keyboard.ts
web/source/osk/visualKeyboard.ts

Fixes #3950.
Yeah, I missed the mark on my understanding of `KDU` and `displayUnderlying` while doing the Web-core refactor.  This should patch it all up.
Not noted on #3950 - `KDU` was completely ignored when displaying desktop layouts; it was being overridden to `true` for them.

fix(web): fixes lack of respect for underlying-key display settings

---

common/predictive-text/unit_tests/headless/worker-model-compositor.js
common/predictive-text/worker/model-compositor.ts

Fixes #3616.
In particular, its final issue as mentioned in https://github.com/keymanapp/keyman/issues/3616#issuecomment-777987194:
> The issue is, unless we delete a character from the existing word [after a backspace], keyman will not replace the word, instead add the [full] suggestion to the context. This is wrong.
Also adds some unit tests for this case, along with a more normal-case test that's useful as a comparison.

fix(common/models): fixes application of suggestions immediately after a backspace

---

linux/keyman-config/keyman_config/__init__.py

When the environment variable KEYMAN_NOSENTRY is set we'll skip reporting to Sentry. This is helpful on development machines.

chore(linux): Don't report to Sentry in dev environment

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java
android/KMEA/app/src/main/AndroidManifest.xml
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/WebViewUtil.java

Fixes #4511 where the welcome.htm page in the webView is unresponsive and can't be closed (either back button or "OK" button)
* Remove extra keyboard package install notification (this was triggering the help file to be displayed twice)
* Use separate process names
* Fix `appendChild()` exception in viewport injection
* Improve the cleanup onDestroy() so that
* webView is blanked (avoids spurious keyboard downloads
* webView is then cleaned up
* Allow back button to finish activity
Note:
There's still lag when displaying sil_cameroon_qwerty.htm with Chrome 88 (as listed on the issue).
Since Chrome is also unresponsive with the large page, I can't address that on this PR.
@makarasok
1. For each of the Android SDK devices (emulator or physical device), load a clean install of the test build …

fix(android/app): Fix welcome.htm responsiveness

---

windows/src/developer/TIKE/help/kwhelp.pas
windows/src/developer/kmcmpdll/CasedKeys.cpp
windows/src/developer/kmcmpdll/CasedKeys.h
windows/src/developer/kmcmpdll/CharToKeyConversion.cpp
windows/src/developer/kmcmpdll/CharToKeyConversion.h
windows/src/developer/kmcmpdll/Compiler.cpp
windows/src/developer/kmcmpdll/Compiler.rc
windows/src/developer/kmcmpdll/kmcmpdll.vcxproj
windows/src/developer/kmcmpdll/kmcmpdll.vcxproj.filters
windows/src/developer/kmdecomp/kmdecomp.cpp
windows/src/developer/kmdecomp/savekeyboard.cpp
windows/src/global/delphi/general/CompileErrorCodes.pas
windows/src/global/inc/Comperr.h
windows/src/global/inc/Compiler.h
windows/src/test/unit-tests/kmcomp/test.bat
windows/src/test/unit-tests/kmcomp/test_casedkeys.kmn
windows/src/test/unit-tests/kmcomp/test_casedkeys_chars.kmn
windows/src/test/unit-tests/kmcomp/test_casedkeys_invalid_1.kmn
windows/src/test/unit-tests/kmcomp/test_casedkeys_invalid_2.kmn
windows/src/test/unit-tests/kmcomp/test_casedkeys_mnemonic_1.kmn
windows/src/test/unit-tests/kmcomp/test_casedkeys_mnemonic_2.kmn
windows/src/test/unit-tests/kmcomp/tests.kpj

Fixes #2241.
The `&CasedKeys` system store is a compiler feature that reduces the repetitive nature of keyboard rules for `CAPS` and `NCAPS`. The `&CasedKeys` system store defines a list of virtual keys for which 'normal' Caps Lock rules apply. This store has no default value, for backward compatibility.
Once this store is defined, then you can define just the unshifted and shifted versions of a rule, and Keyman Developer will synthesize the `CAPS` and `NCAPS` versions of the rule. For example, you may have the following rules:
```
store(&CasedKeys) [K_A]
+ [K_A] > 'α'
+ [SHIFT K_A] > 'Α'
```
These would be replaced by the compiler with:
```
store(&CasedKeys) [K_A]
+ [NCAPS K_A] > 'α'
+ [SHIFT CAPS K_A] > 'α'
+ [CAPS K_A] > 'Α'
+ [SHIFT NCAPS K_A] > 'Α'
```
You can also use this …

feat(developer): &CasedKeys system store

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/DownloadResultReceiver.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/BaseActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudApiTypes.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudCatalogDownloadCallback.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudKeyboardPackageDownloadCallback.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudLexicalModelMetaDataDownloadCallback.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudLexicalPackageDownloadCallback.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/HelpFile.java
android/KMEA/app/src/main/res/values-de-rDE/strings.xml
android/KMEA/app/src/main/res/values-fr-rFR/strings.xml
android/KMEA/app/src/main/res/values/strings.xml

Follow-on to #4261 and fixes #4475
Currently, overriding string resources to use the chosen display language only work for classes that extend `BaseActivity` (`AppCompatActivity`). For the remaining classes, Toast notifications end up using the device's default locale.
This PR adds a helper method `BaseActivity.makeToast()` so the Toast messages will be consistent with the display language. ~I had to simplify some Toast strings to avoid `makeToast` needing to `String.format` with variable parameters.~
(updated): The Toast strings optionally handle formatted strings. Note, messages to Sentry aren't localized.
* Remove unused string `failed_to_access_downloaded_file`
@MakaraSok , please test with the scenarios you reported in the issue

fix(android): Localize Toast notifications

---

windows/src/engine/keyman32/preservedkeymap.cpp

I discovered this while working on #4586. The code in question was updating `*puKey` and then trying to dereference the array on the basis of its new value, which (a) would give the wrong result, and (b) could be reading off the end of the array (although not crashing it seems), e.g. for `"` -> `VK_QUOTE`, which has a value of `0xDE`.
I am guessing that the reason we have not seen any bug reports on this is that the keystroke handler falls back to an alternate code path, so in the vast majority of cases, keyboards would continue to work correctly. Furthermore, the test was just for truthiness of the `BOOL` so probably at least 50% of the time we'd have been okay anyway. Or something. Anyway, I reckon this is better.

fix(windows): PreservedKeyMap::MapUSCharToVK line order bug

---

common/core/desktop/src/kmx/kmx_xstring.cpp
windows/src/engine/mcompile/mc_crc32.cpp
windows/src/engine/mcompile/mc_import_rules.cpp
windows/src/engine/mcompile/mc_kmxfile.cpp
windows/src/engine/mcompile/mc_savekeyboard.cpp
windows/src/engine/mcompile/mc_syskbd.cpp
windows/src/engine/mcompile/mc_syskbdnt32.cpp
windows/src/engine/mcompile/mc_syskbdnt64.cpp
windows/src/engine/mcompile/mc_unicode.cpp
windows/src/engine/mcompile/mcompile.cpp
windows/src/engine/mcompile/mcompile.vcxproj
windows/src/engine/mcompile/mcompile.vcxproj.filters
windows/src/engine/mcompile/pch.cpp
windows/src/engine/mcompile/pch.h
windows/src/engine/mcompile/stdafx.cpp
windows/src/global/vc/VKScanCodes.cpp
windows/src/test/mnemonic-to-positional/importkeyboard/importkeyboard/importkeyboard.cpp
windows/src/test/mnemonic-to-positional/m-to-p/m-to-p/m-to-p.cpp

Fixes #4591.
I fixed incxstr in 4 places:
1. Common/Core: kmx_xstring.cpp
2. Engine: xstring.cpp
3. Test project importkeyboard importkeyboard.cpp
4. Test project m-to-p m-to-p.cpp
I updated mcompile to remove its own copy of incxstr (identical to that in xstring.cpp) to reduce WETness but opted not to do so for the test apps, which are pretty much throwaway anyway.
I note that there is more work we could do here; we need to check every character as we increment so we don't miss a `U+0000` end of string with malformed data. But I would like to tackle that as a separate job at some point in the future after Core integration.

fix(windows): incxstr could run over buffer with malformed data

---

web/source/kmwuitoolbar.ts

Fixes #4566.
When the toolbar shows a differentiation for the language code, it was not using the correct minification-safe property name, which resulted in `[undefined]` being displayed instead.

fix(web): use language code correctly in toolbar

---

windows/src/engine/kmtip/keys.cpp
windows/src/engine/kmtip/tmgrsink.cpp

Fixes #4557.
Fixes #4453.
When focus changes, we need to re-run `_PreserveAltKeys` as settings may have changed, meaning we have to preserve a different set of keys. I also made the `_PreserveAltKeys` function idempotent so that we don't have to worry about cleanup before calling it -- by calling the cleanup function internally instead.

fix(windows): represerve keys on setfocus

---

windows/src/desktop/setup/UfrmInstallOptions.pas

Fixes #4409.
If a user attempts to install an older version of Keyman, they need to be able to choose to install the older version, and not the newer one offered to them from online. However, the selector was hidden in the Install Options dialog, even when it should have been accessible.
This screenshot shows how the user can choose to install the bundled version (in this case 14.0.250-beta) in the Install Options dialog.
Note that the Setup version title at the bottom of the Install Options dialog (snipped off in this screenshot though) is referring to the version of setup.exe only and is informational only.

fix(windows): show version selector for Keyman in installer

---

windows/src/engine/kmcomapi/com/options/keymanoptions.pas
windows/src/engine/kmcomapi/kmcomapi.dpr
windows/src/engine/kmcomapi/kmcomapi.dproj
windows/src/engine/kmcomapi/util/Keyman.System.BaseKeyboard.pas
windows/src/engine/kmcomapi/util/utilkeyman.pas

Fixes #4437.
Makes sure that we don't end up with a base layout that is not using Latin script at install time.

fix(windows): ensure valid base layout on install

---

common/core/web/keyboard-processor/src/keyboards/defaultLayouts.ts

Fixes #4639 
on Keyman for Android during a keyboard installation, there's a transitory period causing KMW to throw a null exception on
```typescript
layout["displayUnderlying"] = !!keyboard.scriptObject['KDU'];
```
This adds a keyboard check for displayUnderlying (and minor cleanup on the function preamble)
@MakaraSok 
1. Load the test build
2. From the Settings menu, install sil_cameroon_qwerty keyboard
3. Verify there's no Toast notification of "fatal keyboard error"
4. Exit the Settings menu and verify keyboard works

fix(common/core/web): Add keyboard check for scriptObject

---

windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp
windows/src/engine/keyman32/kmhook_keyboard.cpp
windows/src/global/inc/Compiler.h

Fixes #4619.
The hotkey check in keyman32 would ignore right modifier keys, but the behaviour was not quite right: it actually needs to take the modifier into account, but just not treat it as a valid modifier.
While fixing this, I noticed that some of the tests in the `KeyLanguageSwitchPress` function were using the wrong modifier flags. I wish I had fewer different modifier flag sets but that ship has probably sailed.
Oh yes, and the hotkey test for the undifferentiated modifier key actually flipped the result of the `extended` bit test previously. Didn't really matter as Windows sends the differentiated modifier key in most cases but yeuuch.

fix(windows): hotkeys correctly ignore right modifier keys

---

windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguageinstalled.pas
windows/src/engine/kmcomapi/com/keyboardlanguages/keymankeyboardlanguagesinstalled.pas
windows/src/engine/kmcomapi/processes/keyboard/Keyman.System.Process.KPInstallKeyboardLanguage.pas

Fixes #4490.
Fixes #4435.
There are three parts to this:
1. Ensure that transient language profiles associated with a disabled keyboard are enumerated correctly
2. Stop trusting `LocaleNameToLCID` when it returns a transient language id, as it sometimes reports out-of-date values. We don't need to trust it in these cases anyway, because we have already collected the relevant transient language data from Win8Languages.
3. Finally, setting the profile GUID to `GUID_NULL` is simply tidyup, which does not have impact on the running code currently but makes state consistent.
I believe that part 2 fixes #4435 because the symptoms are identical. But as I am unable to repro that particular issue on my machine thus far, that is an assumption. Hopefully we can get a good test result from …

fix(windows): Handle disabled profiles and invalid language ids

---

web/source/dom/domEventHandlers.ts
web/source/dom/touchAliasElement.ts

Fixes #4614.
Took a lot of tracing to work out, but I finally managed to find the root of the errors - the simulated caret presented by `TouchAliasElement`s.  When the blinking element receives touch-related events due to being a child of the element, KMW isn't properly finding the touch alias's root element as expected, which leads to the bugs reported there.

fix(web): event handling for TouchAliasElement's blinking caret

---

common/predictive-text/worker/model-compositor.ts

fix(common/models): prevents "undefined" reversion display string

---

web/source/dom/domManager.ts

So, #4242 ([Sentry error](https://sentry.keyman.com/share/issue/5e15c60b00ac41efb9af69fec920fc90/)) has continued occurring... this time, with the `MutationObserver` type.  (Fortunately, the `Worker` check has been holding well; its console message appears as a breadcrumb.)  Time to fix up the `MutationObserver` check to work better in "strict" modes.

fix(web): better check for missing MutationObserver type

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java

Fixes #4575 and follow-on to #3867
* Reset in-app context when selection changes.
* chore using `s.length()` instead of `!s.isempty()` for consistency between in-app and system keyboard `insertText()`
* When nothing to delete (`dn <= 0`), only insert text if `s.length() > 0` 
@MakaraSok , reproduce the steps you reported in the issue

fix(android/engine): Reset in-app context when selection changes

---

linux/scripts/package-build.inc.sh

This will take care of another lintian warning on Debian.

chore(linux): Move signature files as well

---

windows/src/desktop/kmshell/util/Keyman.System.KeymanStartTask.pas
windows/src/engine/kmtip/kmkey.cpp
windows/src/engine/kmtip/kmtip.cpp
windows/src/engine/kmtip/kmtip.h
windows/src/engine/kmtip/registryw.h
windows/src/global/delphi/general/Keyman.System.Settings.pas

If the registry setting `HKCU\Software\Keyman Engine\Debug:Flag_UseAutoStartTask[REG_WORD]` is not `0`, then the this will enable the restart task. Otherwise, all aspects of it are disabled.
For Keyman 14.0 initial release, we will have this flag disabled. If we can improve stability of it, we'll consider turning it on.

chore(windows): fully disable auto start task

---

windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas
windows/src/desktop/kmshell/main/UfrmMain.pas
windows/src/desktop/kmshell/main/UfrmOnlineUpdateIcon.pas
windows/src/desktop/kmshell/main/initprog.pas

Fixes #4554.
The Online Update form did not have the correct owner window for some operations, meaning that the elevation dialog would not get foreground.

fix(windows): keep online update in focus

---

windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas
windows/src/desktop/setup/RunTools.pas
windows/src/desktop/setup/bootstrapmain.pas
windows/src/unit-tests/windows-setup/Keyman.System.Test.InstallInfoTest.pas

Fixes #4467.
In some scenarios, e.g. files in use, Setup must restart before it completes. This is particularly the case if kmcomapi.dll is locked and Windows will move the new version into place after a restart. In this scenario, we would end up calling the old version of kmcomapi.dll to install keyboards, etc, which is definitely not desirable.
Setup was not saving complete state before the restart, so when it resumed post-restart, would get a blank slate to work from, losing command-line options passed in and any choices that the end user may have made during the installation.
This PR adds serialization of the `TInstallInfo` state data, so that the install state can be saved to disk before restart, and reloaded after the restart. This also means that the `-c` parameter now takes a …

fix(windows): setup must save install state for restarts

---

mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m

Fixes #3945.
When the configuration window is opened via `showPreferences`, we were not aware that the configuration window had been opened, so subsequent references to it would recreate it.

fix(mac): register configuration window on load

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeyboardSettingsActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/MapCompat.java
android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/MapCompatTest.java

Fixes #4269 
After some spelunking in the Sentry crash reports, this PR fixes the following:
* ~Disable Sentry on unit tests~
* Throw NullPointerException if null HashMap passed to MapCompat
* Ignore null HashMap when clicking on QR code (KeyboardSettingsActivity). Note, the QR code is also displayed in KeyboardInfoActivity, but that doesn't involve a null HashMap.
1. Load app
2. From the "Settings" menu, install "Tohono O'odham" keyboard (from the linked Sentry report)
3. After keyboard installs, go Settings --> Installed Languages --> Tohono O'odham (Latin) --> Tohono O'odham --> settings menu
4. Click on the QR code and verify nothing happens

fix(android/app): Fix crash when clicking QR code

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/adapters/NestedAdapter.java
android/build-help.sh

Fixes #3200.
Yep.  Turns out that some of NestedAdapter's constructor calls were receiving unmodifiable lists... which, honestly, is a reasonable expectation.  So, the "proper" way forward is to shift to a perspective where the class _expects_ unmodifiable lists and creates its own editable copy.
Also throws in a minor couple of fixes for `build-help.sh`.  A tweak not easily seen by reviewing the code: it lacked the executable bit needed to run on *nix systems.

fix(android): fixes errors within lists used for UI

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m

Fixes #3972.
Ensure that window references are released when we close the window, so that we are starting again when we want to use the window again in the future.
There are a number of ugly patterns in this code, but fixing those is outside scope for the beta.

fix(mac): release window resources on close

---

mac/.gitignore
mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj
mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/preferences.xib
mac/build-help.sh
mac/build.sh

Fixes #3979.
Instead of loading help.keyman.com in the support frame, we now load a local copy of the help. External links within the help will open in the user's browser. This avoids issues of navigation to keyboard download and other sites which won't work well.
Also, adds Back, Forward and Home buttons to the window so the user can navigate more easily with mouse.
Finally, this means that the local help will always be synchronised with the app version and brings the macOS help in line with the other platforms.
While the help could be formatted more beautifully and we may be able to improve search, index, etc, we should do this as a separate PR.

fix(mac): show local help in app

---

windows/src/engine/Makefile
windows/src/engine/engine.sln
windows/src/engine/inst/components.wxs
windows/src/engine/kmcomapi/com/keyboards/keymankeyboardsinstalled.pas
windows/src/engine/kmrefresh/Makefile
windows/src/engine/kmrefresh/kmrefresh.cpp
windows/src/engine/kmrefresh/kmrefresh.vcxproj
windows/src/engine/kmrefresh/kmrefresh.vcxproj.filters
windows/src/engine/kmrefresh/version.in
windows/src/global/delphi/general/Keyman.System.Settings.pas
windows/src/global/delphi/general/RegistryKeys.pas
windows/src/global/delphi/general/utilexecute.pas

Fixes #4447.
Fixes #4222.
The symptoms for these two issues are related: the language associations change and keyboards stop functioning correctly. The issue is described in detail in #4447.
Although this fix should be considered 'experimental', we should probably include it in the release of 14.0, because it fixes a longstanding issue with Keyman and Windows languages.
Note that this is required even if sync is switched off: the sync task still runs on login and resets language settings from its local cache.

fix(windows): Trigger language sync after changes

---

linux/scripts/dist.sh

`buildtools/build-langtags.py` gets executed before creating the source tarball, so we don't need it in the source package. Excluding it reduces confusion because the files it requires are not found in the source package.

chore(linux): Ignore buildtools in keyman-config tarball

---

ios/engine/KMEI/KeymanEngine/Classes/Resource Management/KeyboardSearchViewController.swift

While #4573 added good visual feedback for progress in the case of _slow_ internet connections, it did not incorporate anything for _inability to_ progress whenever there is no available internet.
This adds an alert for such cases, notifying the user of their lack of internet and auto-dismissing the search once "OK" is clicked.

fix(ios): keyboard search did not alert for lack of net

---

windows/src/desktop/setup/RunTools.pas

Fixes #4520.
Start Keyman after Setup finishes only if Keyman is not already running.
The pattern in this code change is found in a few places. It would be nice to centralise that in a unit somewhere but I don't want to do that much refactoring at this point in beta.

fix(windows): start Keyman after setup only if not running

---

windows/src/developer/kmcmpdll/CasedKeys.cpp
windows/src/developer/kmcmpdll/Compiler.cpp
windows/src/developer/kmcmpdll/kmcmpdll.h
windows/src/test/unit-tests/kmcomp/test.bat
windows/src/test/unit-tests/kmcomp/test_casedkeys_mnemonic_3.kmn
windows/src/test/unit-tests/kmcomp/tests.kpj

The test for `&mnemoniclayout` was incorrectly failing to check the actual state of `&casedkeys`, which broke all mnemonic layouts.

fix(developer): &CasedKeys and &MnemonicLayout are not compatible together

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudApiTypes.java

This fixes a Sentry [crash ](http://sentry.keyman.com/organizations/keyman/issues/2699/?project=7&query=is%3Aunresolved)
> Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
when a cloud downloaded file fails to copy to cache. This would cause an exception in 
```
DownloadFileUtils.Info info = DownloadFileUtils.cacheDownloadFile(context, data);
```

fix(android/engine): Fix crash when download file fails to copy to cache

---

windows/src/developer/TIKE/compile/ValidateKeyboardInfo.pas

This does not trigger a build failure; validation warnings currently always pass. Info messages are currently suppressed with -s which also suppresses the banner, which is more plumbing than we should change just now.
This is a follow-on from #4689.

chore(developer): upgrade bcp 47 canonicalisation to warning

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Fixes #4695 
This fixes the race condition when the System Keyboard is created (outside of the Keyman app).
`Keyboard kbInfo = KMManager.getCurrentKeyboardInfo(appContext);` would check for the current keyboard info (and index)
before the system keyboard had loaded.

fix(android/app): Load system keyboard before checking overrides

---

common/core/web/keyboard-processor/src/keyboards/activeLayout.ts
web/source/kmwembedded.ts
web/source/osk/preProcessor.ts
web/source/osk/visualKeyboard.ts
web/testing/prediction-mtnt/index.html

Fixes #4617.
Implements the spec suggested within https://github.com/keymanapp/keyman/issues/4617#issuecomment-799907262, additionally noting a few different _kinds_ of ID needed at various levels of keyboard processing:
- `baseKeyIdentifier`:  this is the key ID as known to the Keyman keyboard language.  No modifiers, no layer information, etc.  _**Just**_ the base key.
- `coreID`: `baseKeyIdentifier` + the _modifier_ layer, if different from the key's _display_ layer.
- "Modifier layer":  the layer representing a modifier set that would be accessible to the Keyman keyboard language, as set by keyboard developers within the touch-layout designer on a per-key basis as an override.
- Check against https://github.com/keymanapp/keyman/issues/4617#issuecomment-799907262 for further …

fix(common/core/web): disambiguation of keys sharing same base key ID

---

web/source/osk/visualKeyboard.ts

Mitigates severity of #4698.  A "proper" solution would likely be too complex to implement this close to release, but this should provide a decent, centralized stop-gap that we can use for now.
If KMW detects that a subkey array is actively displayed (and popup key handling hasn't been delegated to a host app when in an embedded context), it will proactively insert the selected popup key (with weighting @ 60%) and the base key of the subkey array (@ 20%), ensuring that both keys are more likely than any of the other base keys from the layer.
There are no 'corrections' toward any of the other subkeys here; we lack the geometrical data to compute that easily at the moment.  While a semi-uniform weighting may be possible, that would add extra burdens to the popup-key-vs-base-key …

fix(web): first-pass workaround for popup-key corrections

---

common/core/web/input-processor/src/text/prediction/languageProcessor.ts

Resolves an issue noted on #4694 where toggling predictions off... failed to hide the banner and still allowed predictions in specific scenarios, at least within the iOS app.  It's actually a core-web bug.
I'm near-positive the break occurred in #4370; at minimum, a _part_ of the break did.  The signal used to display the banner was being called whether or not predictions were supposed to be active.
The bit about context invalidation was likely from a different 14.0 PR, as I do remember some work in that area being necessary after the newer correction algorithm was implemented.
----
There _is_ a remaining behavior that's not 100% intended.  I... might have forgotten to add a kill-switch to the correction algorithm's, uh... tendency to correct.  That setting was never passed into the …

fix(common/core/web): predictive banner activation logic

---

ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/KeyboardSearchViewController.swift

Addresses an issue noted during iOS user acceptance testing (see #4694).
In its current state, the iOS engine caches the result of update queries and notes whether or not each installed package is one that we've published.  Before the first search _update_ query may occur, the QR code for a newly-installed package wasn't showing.  Of course, if we installed the package from keyboard search... we should already know exactly how the package was published - we got it from the official source!

fix(ios): kbd search now caches publishing data for result

---

common/core/desktop/tests/unit/kmx/kmx.cpp
linux/ibus-keyman/src/engine.c

Don't re-set context if it changed because the cursor location was wrong. When the user switches to the EuroLatin keyboard in the middle of the line, we're getting a wrong cursor location. This will be fixed with the next keypress, but it leads to the context string suddenly having more characters added to the front. If we re-set the context because it's different now we will loose the information we previously added to the context.
We now compare the end of the string. If the new context string ends with the old context string we assume that the cursor position got updated and don't re-set the context.
This fixes #4678.

fix(linux): Fix switching to keyboard in middle of line (#4678)

---

windows/src/desktop/kmshell/util/Keyman.System.KeymanStartTask.pas
windows/src/engine/keyman/UfrmKeyman7Main.pas

Fixes #4751.
Fixes KEYMAN-WINDOWS-76.
Fixes KEYMAN-WINDOWS-79.
Fixes KEYMAN-WINDOWS-7B.
Fixes KEYMAN-WINDOWS-7E.
Fixes KEYMAN-WINDOWS-7F.
Fixes KEYMAN-WINDOWS-7K.
Fixes KEYMAN-WINDOWS-7N.
Fixes KEYMAN-WINDOWS-80.
This resolves an issue where the `TLangSwitchRefreshWatcher` thread would
terminate early on Win7 (as it had no work to do), and free itself, but then the
main form would reference it post-free. 
This would result in various exceptions as state is corrupted at this point.
Responsibility for free has been moved to the main form.

fix(windows): Change TLangSwitchRefreshWatcher ownership from thread to form

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Follow-on to #4692 where we resume sending embedded KMW errors to Sentry
This re-incorporates a pattern from #4025 to sanitize the breadcrumb going to Sentry
See http://sentry.keyman.com/organizations/keyman/issues/4198
Will cherry-pick to stable-14.0

fix(android/engine): Sanitize embedded KMW Sentry error

---

ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift

While we did think to fix the `InfoViewController` class, we'd simply forgotten to make the same changes for the `SetUpViewController`.
Fixes #4770.

fix(ios): fixes sys-kbd setup help link for iOS 9 and 10

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java

Fixes #4789 from the Sentry logs where some users were experiencing NullPointerException during package installation.
This also improves the UX on errors:
* the download dialog can be dismissed (when errors occur)
* change from Error dialog to Toast notifications so they'll be displayed when the package activity finishes.
Will cherry-pick to stable-14.0

fix(android): Fix NullPointerException in package installation

---

ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift

Fixes something that broke _in-app only_ from #4771.
Took me a while to narrow down the approach, but this will ensure that the keyboard is always force-set when the keyboard host page is reloaded.  This wasn't happening due to the following check when combined with the change to `shouldReloadKeyboard`'s initial value:
https://github.com/keymanapp/keyman/blob/0cf8750a1b7c143e751544631e26e25c3e328bab/ios/engine/KMEI/KeymanEngine/Classes/Manager.swift#L282-L286
Fortunately, `currentKeyboardID` is an optional, so we can set it to `nil` to bypass the check for cases where we need to guarantee that the JS keyboard must be loaded (like... due to page reloads).
The same approach has long been taken here:
https://github.com/keymanapp/keyman/blob/0cf8750a1b7c143e751544631e26e25c3e328bab/ios/engine/ …

fix(ios): ensures JS keyboard set after page load

---

linux/keyman-config/keyman_config/handle_install.py

fix(linux): Fix crash if query doesn't contain bcp47 tag 🍒 (#4800)

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeyboardSettingsActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelInfoActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Keyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LanguageResource.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMPLink.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMString.java

Fixes #4812 by adding a wrapper for String.format calls that need to be kept in `Locale.ENGLISH` (needed for JS calls, URLs, and generating lookup keys)
@MakaraSok 
1. On the device, set the system locale to non-English (like Khmer or Arabic)
2. Load the test build
3. Verify you can install `farsiman` keyboard from keyman.com
4. Verify the globe keyboard picker successfully can switch keyboards between sil_euro_latin and farsiman
5. Type some random text in the Keyman app, and then select a portion of the text
6. In the currently selected keyboard, type a key and verify the substring gets replaced.
7. Click the globe keyboard picker and display a keyboard info page for sil_euro_latin
8. Verify QR code is generated
9. Exit back to the main screen
10. From the Keyman app, click the "Share" …

fix(android/engine): Add KMString wrapper for formatting Strings

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Fixes #4819.
If the web page reloads after KMManager is initialised, it now resets the keyboard and lexical model so they remain in sync.

fix(android): ensure keyboard is always set after pageLoaded

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Fixes #4819.
Cherry-pick of #4840.
If the web page reloads after KMManager is initialised, it now resets the keyboard and lexical model so they remain in sync.

fix(android): ensure keyboard is always set after pageLoaded 🍒

---

linux/keyman-config/keyman_config/keyboard_details.py

fix(linux): Fix crash if `<kbd>.json` doesn't contain description

---

windows/src/developer/kmcmpdll/Compiler.cpp

Fixes #4830.
There remain some additional buffer size checks we should be doing in `GetXString` but this will address the current issue by using the standard maximum buffer size.

fix(developer): buffer size for range expansions

---

windows/src/developer/kmcmpdll/Compiler.cpp

Fixes #4830.
There remain some additional buffer size checks we should be doing in `GetXString` but this will address the current issue by using the standard maximum buffer size.

fix(developer): buffer size for range expansions 🍒

---

android/KMAPro/kMAPro/src/main/res/values-ff-rZA/strings.xml
android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java
android/KMEA/app/src/main/res/values-ff-rZA/strings.xml
ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
ios/engine/KMEI/KeymanEngine/Classes/ff.lproj/ResourceInfoView.strings
ios/engine/KMEI/KeymanEngine/ff.lproj/Localizable.strings
ios/engine/KMEI/KeymanEngine/ff.lproj/Localizable.stringsdict
ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
ios/keyman/Keyman/Keyman/ff.lproj/Localizable.strings
linux/keyman-config/locale/ff_ZA.po
windows/src/desktop/kmshell/locale/ff-ZA/strings.xml
windows/src/desktop/setup/locale/ff-ZA/strings.xml

This adds the Windows strings for Fulah (ff).
Will need to cherry-pick to master too.
(update)
Since there was a flurry of  activity on translate.keyman.com I've added the other platforms too.
On translate.keyman, Fulah is listed as "Fula" so that's the name I used in the Android menu

chore(common): Check in crowdin strings for Fulah

---

linux/keyman-config/keyman_config/keyboard_details.py

This fixes #4823. 🍒 of PR #4835.
(cherry picked from commit ebe49cfc6f4b571c641e92adfe61af4bf67a626b)

fix(linux): Fix crash if `<kbd>.json` doesn't contain description 🍒

---

resources/build/trigger-builds.inc.sh

Triggering the Jenkins build from the Stable release trigger on TC
fails. This change outputs the data we're actually sending.

chore(linux): Debug triggering Jenkins build

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java

Fixes #4858 to rename the Display Language from "Fula" to "Pulaar".

chore(android/engine): Rename "Fula" to "Pulaar"

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java

Follow-on to #4859 
From the community site [discussion](https://community.software.sil.org/t/language-settings-translation/4611/8), it turns out
> Since the language has two names in Fulah, Pulaar in the West, Fulfulde in the East, in software localizations, we mostly adopt Pulaar-Fulfulde for simplicity, but more importantly, for **unity**!
At this moment, I'm not sure how the Android app could re-use the Windows string name `ssLanguageName`
* That string identifier is already used by Keyman for Windows
* If all the language names on the "Change Display Language" menu used `ssLanguageName`, wouldn't they all list the same language in the chosen locale?

chore(android/engine): Rename "Pulaar" to "Pulaar-Fulfulde"

---

windows/src/global/delphi/packages/Keyman.System.PackageInfoRefreshLexicalModels.pas

Fixes #4862
In `PackageInfoRefreshLexicalModels.pas`. reduce non-canonical BCP 47 tag warning to "info" so they do not block the build.
Mirrors change in `PackageInfoRefreshKeyboards.pas` from 1f87c7608c7c8246c59260326c4e076dd5d82760
Tested that the modified Tike.exe could compile the package from keymanapp/lexical-models#122
TODO

fix(developer): Reduce non-canonical BCP 47 tag warning in PackageInfo to "Info"

---

linux/keyman-config/keyman_config/install_window.py

If we encounter a legacy non-Unicode file we now simply ignore the file instead of crashing.
This fixes #4876.

fix(linux): don't crash on legacy non-Unicode files

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Fixes #4896 where loading .woff fonts on Android N (7.0 / 7.1) devices throws runtimeexceptions
Reference from SO
https://stackoverflow.com/questions/42342572/android-runtime-exception-font-asset-not-found-for-woff-font-files-in-android

fix(android/engine): Don't load woff fonts on Android N

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Cherry-pick of #4905 to stable-14.0
This avoids loading .woff fonts on Android 7.0 / 7.1

fix(android/engine): Don't load woff fonts on Android N 🍒 

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java

Fixes #4925 
This prevents the `NullPointerException` in CloudRepository.prepareResourcesUpdateQuery() when the list of installed lexical models doesn't exist.
With this change, when the package update query is generated, the empty lexical model list just becomes an empty string for the lexical model portion of the query
```java
String lexicalModelQuery = "";
for(HashMap<String, String> hashMap : KMManager.getLexicalModelsList(aContext)) {  // <-- this is the affected line
if (hashMap != null && hashMap.containsKey(KMManager.KMKey_LexicalModelID)) {
...
}
}
String queryURL = String.format(API_PACKAGE_VERSION_FORMATSTR, getHost(), keyboardQuery, lexicalModelQuery);
```

fix(android/engine): Change getList() to return an empty list instead of null

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java

Follow-on to #4926
My bad 🤦 
When I was removing test code, I forgot to include this removed line on the original PR.
This way, the initialized empty list of lexical models gets returned instead of null.

fix(android/engine): Don't set lexical model list to null

---

linux/keyman-config/keyman_config/install_window.py

If we encounter a legacy non-Unicode file we now simply ignore the file instead of crashing.
This fixes #4876. Cherry-pick of PR #4878.
(cherry picked from commit 59c45c46718ec68c1eb37e043b98fe4f878d5175)

fix(linux): don't crash on legacy non-Unicode files 🍒

---

linux/keyman-config/keyman_config/get_kmp.py
linux/keyman-config/keyman_config/handle_install.py

If the network is down or the server name can't be resolved we shouldn't crash. This change logs an error instead.

fix(linux): Don't crash on network problem (fixes #4911)

---

linux/keyman-config/keyman_config/get_kmp.py
linux/keyman-config/keyman_config/handle_install.py

If the network is down or the server name can't be resolved we shouldn't crash. This change logs an error instead.
🍒-pick of #4912

fix(linux): Don't crash on network problem (fixes #4911) 🍒

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java

Cherry-pick of #4926 and #4927 to stable-14.0
This prevents the NullPointerException when an empty lexical model list is then used to query for package updates.

fix(android/engine): Change getList() to return an empty list instead of null 🍒 

---

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas
windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas
windows/src/desktop/setup/Keyman.Setup.System.OnlineResourceCheck.pas
windows/src/desktop/setup/RunTools.pas

Fixes #4886.
Fixes KEYMAN-WINDOWS-8S.
Fixes KEYMAN-WINDOWS-8T.
This patch includes 5 separate fixes for the various scenarios we encountered during package installation.
1. RunTools.pas: don't attempt to install TIPs if package is not also being installed.
2. Keyman.Setup.System.OnlineResourceCheck.pas, OnlineUpdateCheck.pas: handle online update check for packages with spaces or periods in the id (legacy packages only). See also keymanapp/api.keyman.com#150
3. Keyman.Setup.System.InstallInfo.pas: Handle browsers renaming downloaded files with `(n)` and `[n]` patterns as well as the current ` (n)` pattern.
4. Keyman.Setup.System.InstallInfo.pas: Handle browsers renaming downloaded files with `_n` pattern. See code comments for details.
5. Keyman.Configuration.System.TIPMaintenance.pas: …

fix(windows): handle invalid package names during install

---

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas
windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas
windows/src/desktop/setup/Keyman.Setup.System.OnlineResourceCheck.pas
windows/src/desktop/setup/RunTools.pas

Fixes #4886.
Cherry-pick of #4887.
This patch includes 5 separate fixes for the various scenarios we encountered during package installation.
1. RunTools.pas: don't attempt to install TIPs if package is not also being installed.
2. Keyman.Setup.System.OnlineResourceCheck.pas, OnlineUpdateCheck.pas: handle online update check for packages with spaces or periods in the id (legacy packages only). See also keymanapp/api.keyman.com#150
3. Keyman.Setup.System.InstallInfo.pas: Handle browsers renaming downloaded files with `(n)` and `[n]` patterns as well as the current ` (n)` pattern.
4. Keyman.Setup.System.InstallInfo.pas: Handle browsers renaming downloaded files with `_n` pattern. See code comments for details.
5. Keyman.Configuration.System.TIPMaintenance.pas: Avoid crashing if `kmshell …

fix(windows): handle invalid package names during install 🍒

---

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
windows/src/global/delphi/general/RegistryKeys.pas

May fix #4889.
May fix KEYMAN-WINDOWS-53.
May fix KEYMAN-WINDOWS-54.
In some situations, Keyman is unable to precisely match the user's default language with its own keyboard settings. In this situation, Keyman may crash when attempting to install the TIP, or may give a spurious error such as "Too many transient languages" or similar.
I have been unable to reproduce the crash described in #4889 on my machines so this is an attempted fix.
This does fix a bug with default languages in any case so is a good fix to include: if the user's default language is not found in Keyman's LCID table, then Keyman would fail to install the TIP when the keyboard is installed and would return an error message (but not crash).
I will mark these issues as resolved when this PR is merged and we will see if we …

fix(windows): crash when installing TIP in some rare situations

---

windows/src/desktop/kmshell/main/KeyboardTIPCheck.pas
windows/src/desktop/kmshell/main/initprog.pas

Fixes #4893.
Fixes KEYMAN-WINDOWS-50.
Fixes KEYMAN-WINDOWS-4Z.
Profile repair was using legacy code for re-establishing Keyman TIP profiles after they had been modified by a third party app or Windows. However, with Keyman 14's new profile registration pattern, this is both less likely to occur and also easier to resolve (just disabling and re-enabling the keyboard should do it).
Thus, I have opted to disable the profile repair code as, with the way it stands at present, it may well make things worse, even aside from the crash, because of disparities between user and admin TSF settings.

chore(windows): disable profile repair

---

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
windows/src/global/delphi/general/RegistryKeys.pas

Cherry-pick of #4890.
May fix #4889.
May fix KEYMAN-WINDOWS-53.
May fix KEYMAN-WINDOWS-54.
In some situations, Keyman is unable to precisely match the user's default language with its own keyboard settings. In this situation, Keyman may crash when attempting to install the TIP, or may give a spurious error such as "Too many transient languages" or similar.
I have been unable to reproduce the crash described in #4889 on my machines so this is an attempted fix.
This does fix a bug with default languages in any case so is a good fix to include: if the user's default language is not found in Keyman's LCID table, then Keyman would fail to install the TIP when the keyboard is installed and would return an error message (but not crash).

fix(windows): crash when installing TIP in some rare situations 🍒

---

windows/src/desktop/kmshell/main/initprog.pas
windows/src/desktop/kmshell/startup/help/UfrmTextEditor.pas

Fixes #4848.
This error arose because the form was destroyed after kmshell.dpr completes, which meant that sentry had already been destroyed. The sentry call was simply to record a breadcrumb of the form being closed.
The fix is to move the lifecycle of the form into the `OpenTextEditor` function. `OpenTextEditor` is used only by `initprog.RunKMCOM` and so it is safe to remove the ApplicationRunning path of the code, which simplifies the lifecycle of the form.

fix(windows): access violation closing text editor

---

windows/src/desktop/kmshell/main/initprog.pas
windows/src/desktop/kmshell/startup/help/UfrmTextEditor.pas

Cherry-pick of #4920.
Fixes #4848.
This error arose because the form was destroyed after kmshell.dpr completes, which meant that sentry had already been destroyed. The sentry call was simply to record a breadcrumb of the form being closed.
The fix is to move the lifecycle of the form into the `OpenTextEditor` function. `OpenTextEditor` is used only by `initprog.RunKMCOM` and so it is safe to remove the ApplicationRunning path of the code, which simplifies the lifecycle of the form.

fix(windows): access violation closing text editor 🍒

---

windows/src/engine/keyman/UfrmKeyman7Main.pas

Fixes #4874.
Opening product help from the tray menu would end up at a broken page.
Given the title of the link is "Help Contents", I have opted to open at the help contents... (rather than the alternative of context/tray-menu).

fix(windows): help contents broken from tray menu

---

windows/src/engine/keyman/UfrmKeyman7Main.pas

Cherry-pick of #4922.
Fixes #4874.
Opening product help from the tray menu would end up at a broken page.
Given the title of the link is "Help Contents", I have opted to open at the help contents... (rather than the alternative of context/tray-menu).

fix(windows): help contents broken from tray menu 🍒

---

windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectLoader.pas

Fixes #4917.
Fixes KEYMAN-DEVELOPER-6F.
This updates `TProjectLoader` to use the same exception handling pattern for loading the .kpj.user file as we use for the .kpj file.

fix(developer): avoid crash if .kpj.user file is malformed

---

windows/src/developer/TIKE/project/Keyman.Developer.System.Project.ProjectLoader.pas

Cherry-pick of #4918.
Fixes #4917.
This updates `TProjectLoader` to use the same exception handling pattern for loading the .kpj.user file as we use for the .kpj file.

fix(developer): avoid crash if .kpj.user file is malformed 🍒

---

windows/src/developer/TIKE/child/UfrmKeymanWizard.dfm
windows/src/developer/TIKE/child/UfrmKeymanWizard.pas

Fixes #4803.
This fixes part of #4803 - namely the obtrusive warning flagging that there are mismatched modifier types in the keyboard. Instead of making the change during tab switching, it simply shows a warning message in the design view of the keyboard, which the developer can choose to ignore.
This does not address the removal of comments or the switch of character formats which is part of that conversion routine. That is a more complex change to the parser.
The following is the panel that is shown when mismatched modifiers are found:
Note that mismatched modifiers are not necessarily an error -- they just cannot be viewed in the designer as it works only with all or nothing in terms of chirality.

fix(developer): chiral mismatch warning is disruptive

---

windows/src/developer/TIKE/child/UfrmKeymanWizard.dfm
windows/src/developer/TIKE/child/UfrmKeymanWizard.pas

Cherry-pick of #4934.
Fixes #4803.
This fixes part of #4803 - namely the obtrusive warning flagging that there are mismatched modifier types in the keyboard. Instead of making the change during tab switching, it simply shows a warning message in the design view of the keyboard, which the developer can choose to ignore.
This does not address the removal of comments or the switch of character formats which is part of that conversion routine. That is a more complex change to the parser.

fix(developer): chiral mismatch warning is disruptive 🍒

---

windows/src/desktop/kmshell/main/KeyboardTIPCheck.pas
windows/src/desktop/kmshell/main/initprog.pas

Cherry-pick of #4899.
Fixes #4893.
Fixes KEYMAN-WINDOWS-50.
Fixes KEYMAN-WINDOWS-4Z.
Profile repair was using legacy code for re-establishing Keyman TIP profiles after they had been modified by a third party app or Windows. However, with Keyman 14's new profile registration pattern, this is both less likely to occur and also easier to resolve (just disabling and re-enabling the keyboard should do it).
Thus, I have opted to disable the profile repair code as, with the way it stands at present, it may well make things worse, even aside from the crash, because of disparities between user and admin TSF settings.

chore(windows): disable profile repair 🍒

---

windows/src/engine/kmcomapi/com/system/keymancontrol.pas

Cherry-pick of #4940.
Fixes #4939.
Fixes KEYMAN-WINDOWS-70.
Fixes KEYMAN-WINDOWS-71.
Fixes KEYMAN-WINDOWS-BR.
Fixes KEYMAN-WINDOWS-6J.
I am speculating a little here, because the root cause is not visible in the crash report, but it appears that if keyman32.dll is renamed, that the UnregisterControllerWindows function attempts to reload keyman32.dll which means that (a) it no longer has a list of registered controllers, and (b) it may fail to reload.
Instead of throwing an exception, we now only log this error in development mode. The error is not likely to cause significant trouble for end users as they are shutting down Keyman anyway at this point.
The resolution if there is any uncertainty during an upgrade is to restart Windows. This is less than ideal but avoids file locks and …

fix(windows): avoid error if keyman32.dll renamed 🍒

---

windows/src/engine/kmcomapi/com/system/keymancontrol.pas

Fixes #4939.
Fixes KEYMAN-WINDOWS-70.
Fixes KEYMAN-WINDOWS-71.
Fixes KEYMAN-WINDOWS-BR.
Fixes KEYMAN-WINDOWS-6J.
I am speculating a little here, because the root cause is not visible in the crash report, but it appears that if keyman32.dll is renamed, that the UnregisterControllerWindows function attempts to reload keyman32.dll which means that (a) it no longer has a list of registered controllers, and (b) it may fail to reload.
Instead of throwing an exception, we now only log this error in development mode. The error is not likely to cause significant trouble for end users as they are shutting down Keyman anyway at this point.
The resolution if there is any uncertainty during an upgrade is to restart Windows. This is less than ideal but avoids file locks and problems with in-memory …

fix(windows): avoid error if keyman32.dll renamed

---

web/source/dom/domEventHandlers.ts
web/source/dom/touchAliasElement.ts

Sadly, I'm currently unable to reproduce #4797, despite the fact that we're usually seeing at least a couple counts of it per day from keymanweb.com's Sentry logs.  So, to better assist diagnosis of the cause, this PR adds 'breadcrumbs' that will provide extra information about the error's context.
While `target.innerHTML` (or `target.parent.innerHTML`, or the like) might seem to be a more simple, straightforward solution... that would also include the user's typed input, which is obviously a privacy concern.  Rather than attempt complicated regex to scrub it out at all levels... I instead opted to manually collate relevant info using the current approach.
Will need to be 🍒-picked to stable in order for keymanweb.com to provide us anything useful, of course.
Example resulting log: …

change(web): adds error + console logs usable for Sentry reporting targeting #4797

---

oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVShared.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java

Fixes #4950
In 14.0, the FV app changed from including individual keyboard files (packageID = keyboard ID) to bundling fv_all.kmp (packageID = fv_all).
This PR migrates "keyboards_list.dat" so KMW can load the keyboards by updating packageID to "fv_all" and including OSK font.
To test the migration, I build the FV app from stable-12.0 and saved off the keyboard file "keyboards_list.dat". With this PR build I re-uploaded the file to app_userdata/keyboards_list.dat

fix(oem/fv/android): Migrate keyboard list from 12.0 to 14.0

---

web/source/osk/oskManager.ts
web/testing/index.html
web/testing/osk-movement/index.html
web/testing/unminified.html

This makes the `osk.restorePosition()` function public and makes it work even if the OSK is not presently visible. Also DRY out the repeated implementation.
Also fixes #4948.
Inspired by https://community.software.sil.org/t/keyboard-location/4655/10 and will cherry-pick to stable-14.0 upon approval. Will also update help.keyman.com shortly and reference this PR there.
Note, I have not tried to DRY out the rest of the `_TitleBarInterior()`/`controlBar()` chaos but certainly worth doing.

fix(web): publish restorePosition() function

---

common/core/web/keyboard-processor/src/keyboards/activeLayout.ts
web/source/osk/visualKeyboard.ts

Fixes one part of #4953 - from the third screenshot onward.
Turns out that subkeys couldn't be "looked up" during fat-finger alternate computation, so their entries were never available as prediction roots.  This is easily fixed by 'namespacing' popup key IDs in order to forward the lookup operation appropriately.

fix(web): fixes subkey lookup for fat-finger processing

---

oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVShared.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java

Cherry-pick #4951 to stable-14.0 for the FV Android app
This migrates the packageID to "fv_all" and OSK font of the installed keyboards list.

fix(oem/fv/android): Migrate keyboard list from 12.0 to 14.0 🍒 

---

common/core/web/keyboard-processor/src/keyboards/keyboard.ts
ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
web/source/keyboards/kmwkeyboards.ts
web/source/keymanweb.ts

Fixes #4868.  No Android-specific changes appear to be needed, though extra testing in that regard would be wise.
------
When in scenarios where users may frequently swap keyboards - especially between keyboards where some use SMP characters but some don't - attempting to backspace into context typed by previous keyboards can prove tricky if trying to optimize out SMP logic.  This was done far in the past for performance reasons, but the additional complexity it brings (and the resulting bugs, like #4868) is no longer worth it.  For comparison, while testing the iOS changes, I noted that Apple's default backspace handling function near-certainly always makes SMP checks.
Permanently enabling KMW's SMP processing logic is the first step.  However, within our iOS engine, it turns out …

fix(web, ios): better SMP, emoji handling with frequent keyboard swaps

---

linux/keyman-config/keyman_config/__init__.py
linux/keyman-config/keyman_config/convertico.py
linux/keyman-config/keyman_config/handle_install.py
linux/keyman-config/keyman_config/kmpmetadata.py
linux/keyman-config/keyman_config/kvk2ldml.py

- don't log regular errors - those are handled and we report them
to the user, but don't want to create a Sentry error
- report some errors, which we want to see on Sentry, as critical
- log hash of username in crash report
(🍒 of PR #4914)

feat(linux): Improve Sentry crash reporting 🍒

---

ios/kmbuild.sh
mac/build.sh
oem/firstvoices/ios/build_common.sh
resources/build/carthage-workaround.sh

Formally adds https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md as a resource script to assist with our CI transition to Xcode 12.
Also makes a tweak to iOS's build script:  packages are auto-downloaded if no local copy exists, rather than failing the build and forcing a re-run with `-download-resources`.
----
Note that the macOS build script does make a Carthage call here: https://github.com/keymanapp/keyman/blob/03c230c4e7c6e53320921ed91e15e11d8abe8fcc/mac/build.sh#L293-L295
I'm not sure if that one needs to be adjusted, so I've left that decision to a Mac-oriented PR.  There's a good chance it's not needed, since the macOS app shouldn't need to run within the Simulator.

chore(ios): prep for CI transition to Xcode 12, build script tweak

---

resources/build/trigger-builds.inc.sh

Previously we tried to trigger on the wrong, non-existing branch `PR-stable-14.0`.

chore(linux): Fix triggering of Jenkins builds for stable branch

---

resources/build/trigger-builds.inc.sh

Previously we tried to trigger on the wrong, non-existing branch `PR-stable-14.0`.
(🍒 of PR #4968)

chore(linux): Fix triggering of Jenkins builds for stable branch 🍒

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Follow-on to #4813 where the KMString wrapper ensures some string formats are kept in English locale.
Some Sentry error [messages](http://sentry.keyman.com/organizations/keyman/issues/4670/?project=7&query=is%3Aunresolved) are unintentionally getting localized. So this PR just uses the literal string instead of `getString(R.string.fatal_keyboard_error` to pass to KMString().

chore(android/engine): Don't use localized string for Sentry errors

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Cherry-pick of #4978 to stable-14.0 so Sentry messages stay in English.

chore(android/engine): Don't use localized string for Sentry errors 🍒 

---

web/source/dom/touchAliasElement.ts

The `elementLogger()` function was causing a large number of events so I am
disabling this at least until we have time to investigate further.

chore: disable findTouchAliasElement logging

---

web/source/osk/bannerManager.ts

Cherry-pick of #4961 to stable-14.0
Makes banner initialization more robust to fix several Sentry issues

fix(web): Make banner initialization more robust 🍒 

---

windows/src/engine/keymanx64/keymanx64.cpp

Fixes #4988.
Fixes KEYMAN-WINDOWS-3F.
This relates to #4976 and is a stop-gap until we implement that. It will reduce the number of reported errors (both to us and the end user) but does not address the core issue, which requires a more significant refactor.

fix(windows): handle errors starting keymanx64

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/InfoActivity.java
android/help/about/whatsnew.md
android/help/index.md

Fixes #5043 
This changes InfoActivity to always use offline help.
* Also updated help docs for 15.0
Also to 🍒 -pick to stable-14.0 (InfoActivity but not the help docs)

chore(android/app): Always use offline help

---

windows/src/engine/kmtip/debug.cpp
windows/src/engine/kmtip/globals.h
windows/src/engine/kmtip/kmtip.cpp
windows/src/engine/kmtip/kmtip.h
windows/src/engine/kmtip/tmgrsink.cpp

Fixes #4965.
Fixes #4856.
When speech recognition is enabled, it sometimes activates after a Keyman keyboard is selected. This would cause Keyman to think it is being deactivated. We needed to check in `CKMTipTextService::OnActivated` that it was a keyboard-type TIP that was being activated, and only deactivate the Keyman hooks in that situation.
This commit also adds a little logging helper function, and removes an unused variable `guidActiveProfile`.
I will cherry-pick to stable-14.0 once approved.

fix(windows): avoid disabling Keyman when speech recognition starts

---

windows/src/global/delphi/chromium/Keyman.System.CEFManager.pas
windows/src/global/delphi/chromium/Keyman.UI.UframeCEFHost.pas

Relates to #4700.
This simply adds some debug logging so that when the current crash occurs, we can discover which windows have failed to automatically close, which should give us enough detail to be able to reproduce the problem, hopefully, and fix it.

chore(windows): add telemetry to trace crash on exit

---

windows/src/global/delphi/chromium/Keyman.System.CEFManager.pas
windows/src/global/delphi/chromium/Keyman.UI.UframeCEFHost.pas

Cherry-pick of #5007.
Relates to #4700.
This simply adds some debug logging so that when the current crash occurs, we can discover which windows have failed to automatically close, which should give us enough detail to be able to reproduce the problem, hopefully, and fix it.

chore(windows): add telemetry to trace crash on exit 🍒

---

windows/src/engine/kmtip/debug.cpp
windows/src/engine/kmtip/globals.h
windows/src/engine/kmtip/kmtip.cpp
windows/src/engine/kmtip/kmtip.h
windows/src/engine/kmtip/tmgrsink.cpp

Cherry-pick of #5000.
Fixes #4965.
When speech recognition is enabled, it sometimes activates after a Keyman keyboard is selected. This would cause Keyman to think it is being deactivated. We needed to check in `CKMTipTextService::OnActivated` that it was a keyboard-type TIP that was being activated, and only deactivate the Keyman hooks in that situation.
This commit also adds a little logging helper function, and removes an unused variable `guidActiveProfile`.

fix(windows): avoid disabling Keyman when speech recognition starts 🍒

---

windows/src/engine/keyman/UfrmKeyman7Main.pas
windows/src/engine/keyman32/k32_globals.cpp
windows/src/engine/keymanx64/keymanx64.cpp
windows/src/global/delphi/general/UserMessages.pas

Fixes #4976.
Fixes KEYMAN-WINDOWS-2K.
Fixes KEYMAN-WINDOWS-3F.
Fixes KEYMAN-WINDOWS-5A.
Fixes KEYMAN-WINDOWS-3E.
This fix reworks keymanx64's lifecycle, moving responsibility for process shutdown from keyman.exe to keymanx64.exe.
This eliminates the need for interprocess communication, and simplifies the startup and shutdown of keymanx64.exe. Removing this means that we can more safely handle situations where two instances of keymanx64 may be started, as one of them will rapidly terminate when it discovers that its parent process has disappeared.
I will cherry-pick this to stable-14.0 once we have run this on alpha 15 for a short while. It is a bit of a change in design and while I believe the changes are robust, better safe than sorry.

fix(windows): make keymanx64 responsible for its own lifecycle

---

windows/src/global/delphi/ui/UFixupMissingFile.pas

UFixupMissingFile referred to an old MSI component code, which meant that it would never actually fix the installation. This now refers to a current component code.
I may backport this to stable-14.0 but would like to assess its stability over time first.

chore(windows): FixupMissingFile needed current component code

---

linux/ibus-keyman/src/engine.c

Cherry-pick of #5054.
Fixes #4542.
While #5054 will use a constant, for this backport I am just going to hard code the value, at least for now.

fix(linux): Enable caps lock support 🍒

---

windows/src/developer/kmdecomp/kmdecomp.vcxproj
windows/src/developer/kmdecomp/savekeyboard.cpp

1. build paths when loaded as part of solution were incorrect
2. decompiling `if` statements did not work for `!=`

fix(developer): two small issues in kmdecomp

---

windows/src/engine/keyman/UfrmKeyman7Main.pas
windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas
windows/src/engine/keyman32/KEYMAN32.DEF
windows/src/engine/keyman32/Keyman32.cpp
windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/k32_globals.cpp
windows/src/engine/keyman32/kmhook_callwndproc.cpp
windows/src/engine/keyman32/kmhook_getmessage.cpp
windows/src/engine/keyman32/kmhook_keyboard.cpp
windows/src/engine/keymanx64/keymanx64.cpp
windows/src/engine/kmcomapi/com/system/keymancontrol.pas
windows/src/global/delphi/general/KeymanEngineControl.pas

Fixes #5004.
This cleans up the use of controller windows. A single window is now given the responsibility of being the master controller, which receives messages from Keyman32 and other components around UI activation, active keyboard, etc.
The master controller is keyman.exe's `TApplication` window, which does not get destroyed and recreated, unlike the main form window.
Any thread which has responsibility for Keyman UI (keyman.exe main thread, keymanx64.exe main thread) is also registered as a controller thread. A controller thread has special handling for interactions with keyman32 around focus tracking.
Caveats:
* While keymanx64 does not have a visible window and thus probably does not need to be registered as a controller thread, it doesn't really hurt.
* Note that keymanx64 …

fix(windows): refactor controller windows

---

windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/kmhook_getmessage.cpp
windows/src/global/delphi/general/KeymanControlMessages.pas
windows/src/global/inc/keyman64.h
windows/src/global/inc/keymancontrol.h

The `KMC_CHANGEUISTATE` flag for `wm_keyman_control` is no longer processed anywhere. Removes it and the `UpdateKeymanUI` function which called it.
The `#define` for the flag has been left, commented out, to clarify what would otherwise be a gap in identifiers (use `git blame` to learn more).

chore(windows): remove KMC_CHANGEUISTATE

---

linux/keyman-config/debian/control

It turns out that the Debian package build system only considers the first alternative; `python3-raven` isn't available on the current
Debian version, however we still need it on Ubuntu 18.04 Bionic where `python3-sentry-sdk` is not available. This change swaps the alternatives and so should work both on Debian as well as for Bionic.

fix(linux): Swap order of dependencies for Debian package

---

windows/src/engine/keyman/UfrmKeyman7Main.pas
windows/src/engine/keymanx64/keymanx64.cpp

With the recent refactor in #5060, we no longer need the main form window handle parameter in keymanx64.

chore(windows): remove unused keymanx64 parameter

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Fixes #4944 
This update checks that a lexical-model file exists before attempting to use it. We'll also get a Sentry log that the file is missing.
Setup:
1. Install the debug app
2. From the Settings menu, install gff_amharic keyboard (dictionary also installs in the background)
3. From Android Studio, delete the `nrc.en.mtnt.model.js` file from the device.
Steps:
1. Restart the app and switch to sil_euro_latin keyboard
2. Verify keyboard functions and suggestion banner is disabled
3. Switch to gff_amharic
4. Verify keyboard functions and suggestion banner is on (context may need to be cleared for new suggestions to appear. e.g. non-Latin characters)
5. Switch back to sil_euro_latin keyboard
6. Verify keyboard functions and suggestion banner is disabled
Question: Should we give a Toast …

fix(android/engine): Check lexical-model file exists before using

---

windows/src/Target.mak
windows/src/developer/kmcomp/kmcomp.dpr
windows/src/developer/kmconvert/Keyman.Developer.System.KMConvertParameters.pas
windows/src/developer/kmconvert/Keyman.Developer.System.KeymanConvertMain.pas
windows/src/developer/kmconvert/Makefile
windows/src/developer/kmconvert/kmconvert.dpr

A few fixes and improvements:
* kmconvert was missing a command line parameter for `-target` to specify the platform targets for a project
* kmconvert should avoid throwing unhandled exceptions, rather if sentry is not present then just write to console.
* Include kmconvert and its data files in the deployment of kmcomp.zip, which is done on the build agent (just need to make sure files are in the right place here.)
* Side fix: also made sure kmcomp would emit the exception message to console if sentry is not present.

fix(developer): kmconvert commandline and deploy

---

windows/src/Target.mak
windows/src/developer/kmcomp/kmcomp.dpr
windows/src/developer/kmconvert/Keyman.Developer.System.KMConvertParameters.pas
windows/src/developer/kmconvert/Keyman.Developer.System.KeymanConvertMain.pas
windows/src/developer/kmconvert/Makefile
windows/src/developer/kmconvert/kmconvert.dpr

Cherry-pick of #5082.
A few fixes and improvements:
* kmconvert was missing a command line parameter for `-target` to specify the platform targets for a project
* kmconvert should avoid throwing unhandled exceptions, rather if sentry is not present then just write to console.
* Include kmconvert and its data files in the deployment of kmcomp.zip, which is done on the build agent (just need to make sure files are in the right place here.)
* Side fix: also made sure kmcomp would emit the exception message to console if sentry is not present.

fix(developer): kmconvert commandline and deploy 🍒

---

web/source/osk/visualKeyboard.ts

Fixes #4930.
To ensure this doesn't break anything for Android...
@MakaraSok 
I'm requesting two sets of tests.  That said, I'd only expect an issue from the second (non-embedded) set if any issue occurs.
Just fire up the Android app (from this PR's build) and ensure subkeys work as expected in landscape mode, both in-app and in system-keyboard mode.  Behavior should be unaffected and match your default expectations.
This one's going to be a bit more involved, but reflects the actually-changed parts of the code.
1. Ensure that KeymanWeb's test pages are accessible through `localhost` on your machine.
- In case you don't yet have a localhost setup:  [instructions](https://github.com/sillsdev/keyman/wiki/How-to-set-up-a-local-web-server-for-the-Keyman-web-pages) 
2. In your local copy of …

fix(web): position popups correctly in landscape mode on Android and during Chrome emulation

---

common/core/desktop/src/kmx/kmx_file.cpp
common/core/desktop/src/kmx/kmx_processor.h

Compiling on armhf outputs two warnings:
- NULL used in arithmetic [-Wpointer-arith] (line 289 and 290)
- unused parameter ‘dwFileSize’ [-Wunused-parameter] (line 264)
(related to #5072)

fix(common/core/desktop): Fix warnings when compiling for armhf

---

common/core/desktop/src/kmx/kmx_file.cpp
common/core/desktop/src/kmx/kmx_processor.h

Compiling on armhf outputs two warnings:
- NULL used in arithmetic [-Wpointer-arith] (line 289 and 290)
- unused parameter ‘dwFileSize’ [-Wunused-parameter] (line 264)
(related to #5072)
🍒 of PR #5099

fix(common/core/desktop): Fix warnings when compiling for armhf 🍒

---

linux/keyman-config/keyman_config/install_kmp.py
linux/keyman-config/tests/test_install_kmp.py

- Introduce `InstallKmp` class
- Remove unused `list_files` method
- Extract common method that `install_kmp_shared` and `install_kmp_user` use
- Make internal methods protected

refactor(linux): Refactor `install_kmp.py`

---

linux/keyman-config/debian/control

This was already partially done in 4dd0a48b2 (PR #5064), but we missed this line.

chore(linux): Swap order of dependency

---

windows/src/developer/TIKE/main/Keyman.Developer.UI.ImportWindowsKeyboardDialogManager.pas
windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewModelProjectParameters.dfm
windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewModelProjectParameters.pas
windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.dfm
windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas
windows/src/developer/kmconvert/Keyman.Developer.System.ImportWindowsKeyboard.pas
windows/src/developer/kmconvert/Keyman.Developer.System.KMConvertParameters.pas
windows/src/developer/kmconvert/Keyman.Developer.System.KeymanConvertMain.pas
windows/src/developer/kmconvert/Keyman.Developer.System.ProjectTemplate.pas
windows/src/developer/kmconvert/data/basic-keyboard/LICENSE.md
windows/src/developer/kmconvert/data/basic-keyboard/README.md
windows/src/developer/kmconvert/data/basic-keyboard/source/welcome.htm
windows/src/developer/kmconvert/data/wordlist-lexical-model/LICENSE.md
windows/src/developer/kmconvert/data/wordlist-lexical-model/README.md

Fixes #4807.
We want to differentiate between a short copyright message and a longer one that also contains a date. The long one is only needed in one place in a typical keyboard project. This reduces maintenance when making keyboard updates.
As a little side tweak, the New Keyboard Project Parameters dialog now prefills the copyright fields with the author's name as they type it, to reduce the amount of data
entry required.

feat(developer): Add 'full copyright' field to templates

---

windows/src/developer/TIKE/main/UframeTextEditor.pas

Fixes #5095.
If the text editor was loaded, `SetText` would not be synchronous because it executed some Javascript to make the text change, so setting the text and immediately reading it again would give the old text. This is what the On Screen Keyboard editor was doing (it would synchronize the visual editor and text editor at save). This fix updates `SetText` to update the backing store as well as the front end editor.

fix(developer): TframeTextEditor.SetText was not synchronous

---

windows/src/developer/TIKE/main/UframeTextEditor.pas

Fixes #5095.
Cherry-pick of #5096.
If the text editor was loaded, `SetText` would not be synchronous because it executed some Javascript to make the text change, so setting the text and immediately reading it again would give the old text. This is what the On Screen Keyboard editor was doing (it would synchronize the visual editor and text editor at save). This fix updates `SetText` to update the backing store as well as the front end editor.

fix(developer): TframeTextEditor.SetText was not synchronous 🍒

---

android/KMAPro/.idea/runConfigurations.xml
android/KMAPro/build.gradle
android/KMAPro/gradle/wrapper/gradle-wrapper.properties
android/KMAPro/kMAPro/build.gradle
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/InfoActivity.java
android/KMEA/.idea/runConfigurations.xml
android/KMEA/app/build.gradle
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMPLink.java
android/KMEA/app/src/test/java/com/tavultesoft/kmea/KMManagerTest.java
android/KMEA/app/src/test/java/com/tavultesoft/kmea/logic/ResourcesUpdateToolTest.java
android/KMEA/app/src/test/java/com/tavultesoft/kmea/view/FunctionalTestHelper.java
android/KMEA/app/src/test/java/com/tavultesoft/kmea/view/KeyboardPickerTest.java
android/KMEA/build.gradle
android/KMEA/gradle.properties
android/KMEA/gradle/wrapper/gradle-wrapper.properties

Fixes #4603 of updating Gradle and other dependencies. (Samples and OEM FV app addressed in a future PR)
Some general notes about the changes:
* Future Gradle versions will deprecate the jcenter() repo. The KMAPro app depends on it for the material-stepper library, and the jcenter() maintainer says they'll keep the repo available "indefinitely". [link](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)
* sentry-android updated and verified events still get [sent](http://sentry.keyman.com/organizations/keyman/issues/6254/?project=7)
* Since KMEA is a library, Gradle strips out BuildConfig.VERSION_CODE and BuildConfig.VERSION_NAME (the final merge exists in application projects). So I've renamed internal references to BuildConfig.KEYMAN_VERSION_NAME
* Gradle …

chore(android): Update Gradle and other dependencies

---

web/testing/ckeditor/index.html
web/testing/ckeditor/inline.html
web/testing/ckeditor/utilities.js
web/testing/index.html

Ref https://community.software.sil.org/t/asp-net-keyman-web-with-ckeditor/4801
It seems to me that it would be good to have these kinds of pages available as online examples as well on help.keyman.com, but tidied up with the intention of them being good clean samples of the best ways to integration kmw.

chore(web): add test page for playing with CKEditor

---

android/KMAPro/kMAPro/build.gradle
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/InfoActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebBrowserActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java
android/KMEA/app/build.gradle
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Fixes #5088
To comply with upcoming Play Store requirement, this updates targetSDKVersion to 30.
* Also sets appropriate webView permissions to access local file (except for WebBrowserActivity, the in-app browser).

chore(android): Update targetSDKVersion to 30

---

ios/kmbuild.sh
oem/firstvoices/ios/build_common.sh

As noted during development of #5107, moving to Carthage 0.38 had one minor hiccup that will affect stable builds - it chooses the wrong workspace within the DeviceKit repo when building the framework.  Fortunately, we can simply delete that workspace after it's fetched, after which things will work fine like before.

chore(ios): works around wrong-workspace Carthage 0.38 lookup issue

---

android/.gitignore
android/build-help.sh
android/help/about/whatsnew.md

Addresses #4686
From the Gradle Play Publisher [Reference](https://github.com/Triple-T/gradle-play-publisher#uploading-release-notes), this PR updates build-help.sh to copy the release note info from `whatsnew.md` to the txt file the Gradle Play Publisher expects (`tier`.txt or default.txt if unspecified).
For now, our markdown preamble gets included 
```
---
title: What's New
---
```
Will verify the release notes on the alpha build get published before closing the issue.

feat(android/app): Auto-generate Play Store release notes

---

web/source/dom/domEventHandlers.ts
web/source/dom/touchAliasElement.ts

Fixes #4797.
According to MDN's notes on browser compatibility, there should be no loss of compatibility with these changes.
- `touches`: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/touches#browser_compatibility
- `changedTouches`: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/changedTouches#browser_compatibility
Note:  this will require testing on a live touch device; Chrome emulation does not support multiple touches.  As such, you'll likely need a test setup using a service similar to `ngrok` to properly 'serve' the testing page for your device.
As for the actual test... it's best to refer to the repro notes in #4797.  Note that you'll need to use developer mode and open the console view to verify that no errors occur; the user-visible effect (broken …

fix(web): active element selection in multi-touch scenarios

---

ios/tools/prepRelease.sh

Facilitates the final bullet-point of #5107.  We'll need to update the CI config for release builds to use this script directly, rather than the original one within TeamCity.

chore(ios): imports iOS artifact-upload script for CI use

---

web/source/build_kill_browserstack.sh

🍒 -pick of #5136 to stable-14.0
This way, the KeymanWeb Test-14.0 CI configuration can call `npx ../../resources/gosh/gosh.js ./build_kill_browserstack.sh` on either 14.0 or 15.0 builds (and use the Linux build agent)
TODO

chore(web): Add CI script to kill BrowserStack tunnel 🍒 

---

ios/.gitignore
ios/kmbuild.sh
ios/tools/prepRelease.sh

I made one mistake when importing the artifact-prep script in #5140 - TeamCity's build variables are managed by TC itself and replaced _before_ the script is sent to a build agent to run.  So, `%build_number%` is not available for the in-repo version of the script.
Fortunately... we already have access to `$BUILD_NUMBER`.  It's a simple replacement.  I then added a few tweaks to use our standard shell-script headers and such.
Finally, I added one tweak to the iOS build script, just to be sure Xcode doesn't fail an .xcarchive build for code-signing weirdness, as it's not required for that file type.  This is a small tweak to something from #5155 from yesterday; this part will be 15.0-only.

fix(ios): artifact upload preparation

---

ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj

Because Xcode build configurations are hard.
Fixes an issue with the implementation of #5107 when attempting to upload to the App Store:
```
[10:45:38]
[Transporter Error Output]: ERROR ITMS-90206: Invalid Bundle. The bundle at 'Keyman.app/PlugIns/SWKeyboard.appex' contains disallowed file 'Frameworks'.
[10:45:38]
[Transporter Error Output]: Return status of iTunes Transporter was 1: ERROR ITMS-90685: CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.sil.Keyman.ios.Engine' under the iOS application 'Keyman.app'.
[10:45:38]
\nERROR ITMS-90205: Invalid Bundle. The bundle at 'Keyman.app/PlugIns/SWKeyboard.appex' contains disallowed nested bundles.
[10:45:38]
\nERROR ITMS-90206: Invalid Bundle. The bundle at …
```

fix(ios): link, but NOT embed KeymanEngine.xcframework in app exs

---

android/build-help.sh
ios/build-help.sh
mac/build-help.sh
resources/build/offline-help-style-spec.txt
windows/src/desktop/help/build.sh

This PR adds a new common resource file:  `resources/build/offline-help-style-spec.txt`.  This defines custom CSS wrapped in a <style> tag as needed for compatibility with `pandoc -H`:
-H FILE, --include-in-header=FILE|URL
Include  contents  of  FILE, verbatim, at the end of the header.
This can be  used,  for  example,  to  include  special  CSS  or
JavaScript in HTML documents.  This option can be used repeated-
ly to include multiple files in the header.  They  will  be  in-
cluded in the order specified.  Implies --standalone.
This can then be directly imported into all pages converted from markdown.
Also, a fun detail:  if we need project-specific CSS, this approach will support that as well:
> This option can be used repeatedly to include multiple files in the header.  They will be …

feat(common): offline help css

---

ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
ios/engine/KMEI/KeymanEngine/Classes/Colors+Extension.swift
ios/engine/KMEI/KeymanEngine/Classes/Colors.swift
ios/engine/KMEI/KeymanEngine/Classes/Extension/JSONDecoder.DateDecodingStrategy+ISO8601Fallback.swift
ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Settings/InstalledLanguagesViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Settings/LanguageSettingsViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Settings/SettingsViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/TextField.swift
ios/engine/KMEI/KeymanEngine/Classes/TextView.swift
ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
ios/keyman/Keyman/Keyman/AppDelegate.swift
ios/keyman/Keyman/Keyman/GetStartedViewController/GetStartedViewController.swift
ios/keyman/Keyman/Keyman/MainViewController.swift
ios/samples/KMSample1/KMSample1.xcodeproj/project.pbxproj
ios/samples/KMSample2/KMSample2.xcodeproj/project.pbxproj
oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj

Fixes #5018.
Also removes conditional check branches that addresses version of iOS that will no longer be supported, along with some of the deprecations.
------
There is one major work item left undone by this PR:
Of course, we _could_ just use iOS 11 instead of 12 and avoid the deprecation for now, but... we should probably still address this.  Also, if memory serves, iOS 11 is the point where XIBs against WKWebView become properly supported, so this PR will facilitate converting our old XIBs against UIWebView, making this remaining work item far less of a pain point than it used to be.

change(ios): minimum iOS version -> 12.1

---

ios/keyman/Keyman/Keyman/MainViewController.swift

Because 🍎:
Note the mention of "selectors" - this implies that our KeymanEngine method on Manager isn't at fault - it's the `@objc` app-only selector methods changed here.

chore(ios): renames problematic app selectors

---

android/KMAPro/kMAPro/build.gradle
android/build.sh
oem/firstvoices/android/app/build.gradle

Infrastructure update to add `-clean` flag to build script
Also update app Gradle files to check if key store files exists (in support of running Test-14.0 builds on the Linux build agent)
TODO:

chore(android): Add -clean flag to build script

---

linux/keyman-config/Makefile
linux/keyman-config/README.md

Building km-config now requires an additional step so that
generates `lang_tags_map.py`. During a package build this happens in
`reconf.sh`. This change updates the documentation, and also adds
this build step to the Makefile, so that the file gets generated
when building from the command line.
Closes #5074.

fix(linux): Fix Makefile and instructions for building

---

android/KMAPro/build.sh
android/KMEA/build.sh
android/Samples/KMSample1/build.sh
android/Tests/KeyboardHarness/build.sh
android/build-publish.sh
common/core/web/keyboard-processor/test.sh
common/predictive-text/unit_tests/in_browser/browser-test.sh
ios/kmbuild.sh
ios/samples/build_common.sh
mac/Keyman4MacIM/make-km-dmg.sh
mac/Keyman4MacIM/write-download_info.sh
mac/build.sh
oem/firstvoices/android/build.sh
oem/firstvoices/android/build_common.sh
oem/firstvoices/common/build_keyboards.sh
oem/firstvoices/ios/build_common.sh
web/source/build.sh
web/unit_tests/test.sh
windows/src/desktop/locale/crowdin-control.sh

When working on a new build script, I tripped over the `-?` question mark help parameter here, as it needs to be escaped. Opted to fix all the instances in our scripts, although AFAICT there would not have been current bugs arising from this, as there were no conflicting one character options lower in the case list.

fix(common): build script help param

---

common/core/desktop/src/kmx/kmx_file.cpp
windows/src/engine/keyman32/K32_load.cpp

Matches work completed in #5169 for Keyman Core, kmx_file.cpp.
While this code will hopefully disappear in 15.0, it's good to make sure we aren't diverging beforehand.
Also tidies up a couple of other cases in `CopyKeyboard` in Keyman Core.

fix(windows): cleanup edge cases in k32_load

---

windows/src/desktop/kmshell/startup/UfrmSplash.dfm
windows/src/global/delphi/chromium/Keyman.System.CEFManager.pas
windows/src/global/delphi/chromium/Keyman.UI.UframeCEFHost.dfm
windows/src/global/delphi/chromium/Keyman.UI.UframeCEFHost.pas
windows/src/global/delphi/ui/UfrmWebContainer.pas

Fixes #5195.
Fixes KEYMAN-WINDOWS-M0.
The splash screen for Keyman would crash on start with the latest Chromium update. This fix resolves the issue, which related to the resize-to-content code, by removing the resize-to-content code and instead hardcoding the window size in the .dfm.
This is a significant simplification of the browser host and I think it is worthwhile. The only place the resizing code was still used was in the splash screen.

fix(windows): fix size of splash

---

linux/ibus-keyman/debian/control

ibus-keyman depends on keyman-keyboardprocessor which we don't build for s390x because we currently don't support big-endian. We only build for the same architectures as keyman-keyboardprocessor.

fix(linux): Exclude s390x from package builds for ibus-keyman

---

linux/ibus-keyman/debian/control

ibus-keyman depends on keyman-keyboardprocessor which we don't build for s390x because we currently don't support big-endian.
We only build for the same architectures as keyman-keyboardprocessor.
🍒-pick of #5213

fix(linux): Exclude s390x from package builds for ibus-keyman 🍒

---

web/source/build_kill_browserstack.sh

Follow-on to #5136
The CI test build step of cleaning up Browserstack can fail because the task BrowserStackLocal doesn't always exist.
This PR forces the step to always pass.

fix(web): Always pass kill_browserstack

---

windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas
windows/src/desktop/kmshell/xml/downloadkeyboard.xsl

The Escape key does not work in the search iframe when in the parent web document. However, it is easy to test for it in the hosting form.

fix(windows): support Esc key in Download Keyboard dialog

---

android/KMAPro/kMAPro/build.gradle
android/KMAPro/kMAPro/src/main/java/com/keyman/android/CheckInstallReferrer.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java

Resolves #5219.
Uses the Google Play Install Referrer API to automatically discover the keyboard to install together with Keyman; this keyboard is passed in a `referrer` parameter to the Play Store page for the Keyman app from the Keyman website.
When the app launches for the first time, the Get Started screen appears and then a moment later, the Install Keyboard process starts for the associated keyboard. Once that completes, the first checkbox in Get Started is automatically checked.
This can be a little tricky to test because it only runs first-time after installing the app from the Play Store (by design). But the test version is not yet in the Play Store. However, you can test on an Android device by:
1. Uninstall the Keyman app
2. Open a link to the play store with an embedded …

feat(android): Automatically install keyboard through Play Store

---

android/KMAPro/kMAPro/build.gradle
android/KMAPro/kMAPro/src/main/java/com/keyman/android/CheckInstallReferrer.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java

Resolves #5219.
Cherry-pick of #5230.
Uses the Google Play Install Referrer API to automatically discover the keyboard to install together with Keyman; this keyboard is passed in a `referrer` parameter to the Play Store page for the Keyman app from the Keyman website.

feat(android): Automatically install keyboard through Play Store 🍒

---

oem/firstvoices/ios/FirstVoices/Info.plist

Fixes #5225 and #5228 for 15.0.

fix(oem/fv/ios): app encryption flag for app store uploads (15.0)

---

common/core/web/input-processor/src/text/inputProcessor.ts
common/core/web/keyboard-processor/src/keyboards/activeLayout.ts
common/core/web/keyboard-processor/src/text/defaultOutput.ts
common/core/web/keyboard-processor/src/text/keyEvent.ts
common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
common/core/web/keyboard-processor/src/text/ruleBehavior.ts
common/core/web/tools/recorder/src/nodeProctor.ts
web/source/dom/domDefaultOutput.ts
web/source/dom/domEventHandlers.ts
web/source/dom/domOverrides.ts
web/source/dom/preProcessor.ts
web/source/kmwembedded.ts
web/source/osk/preProcessor.ts

After some investigation and analysis, I noticed that in KMW 12 we started tracking the active output target as part of the key event object.  Storing it on the key event object would cause said objects to have a rather awkward construction process once Web OSK-Core stuff is well under way.
The issue:  the OSK itself won't track the active OutputTarget whatsoever, which makes it quite hard for the OSK to specify this property for the event.  The object would be near-fully constructed, with this one property `undefined` until much later with little in the object's design signaling the need to fill it in before passing it to the `KeyboardProcessor` part of Core.  (It's _just_ that single field - `Ltarg` - that's the issue.)
But... there's little need for it to _actually be_ on that object; …

refactor(common/core/web, web): target-agnostic key events

---

oem/firstvoices/ios/FirstVoices/Info.plist

fix(oem/fv/ios): app encryption flag for app store uploads (14.0)

---

resources/shellHelperFunctions.sh

When building packages on ppa the TERM environment variable is set to "unknown", which isn't a valid value but which we didn't account for previously.

fix(linux): Fix packaging on ppa

---

common/core/web/keyboard-processor/src/text/outputTarget.ts
common/core/web/keyboard-processor/tests/cases/transcriptions.js

Addresses #5246.
In an isolated, headless unit test environment, this didn't seem to get that much improvement despite changing a particularly inefficient part of the algorithm from O(N^2) to O(N).  (Maybe there were caching effects somehow?)
That said... it _did_ make a remarkable difference in responsiveness when I used the KMW "predictive text: robust testing" page; keystroke processing as a whole took less time than focusing operations as a result.
I want to test it out a bit more before leaving draft, but it does seem to yield some significant improvement.  Things still struggle with _very_ long text, of course.

fix(common/core/web): optimizes transform construction

---

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMAPro/kMAPro/src/main/java/com/keyman/android/CheckInstallReferrer.java
android/KMAPro/kMAPro/src/main/java/com/keyman/android/DownloadIntentService.java
android/KMAPro/kMAPro/src/main/java/com/keyman/android/KmpInstallMode.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/DownloadResultReceiver.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadIntentService.java

Relates to #5230, #5219.
Adds an `installMode` parameter to the `downloadKMP` function and makes the install `welcomeOnly` for referred keyboards.
1. We need to be able to control silent levels:
* Completely silent
* Only welcome
* Full install
2. When `silentInstall` was true, currently welcome was still shown, but the paging controls are not configured correctly and a blank screen (an incomplete `PackageActivity`) was shown after install, because the `PackageActivity` was never `finish()`ed.

feat(android): silent install for referred kbd

---

windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp
windows/src/global/delphi/general/Keyman.System.Settings.pas

Disables the new modifier check added in #5189.

fix(windows): disable new hotkey modifier check

---

common/core/desktop/debian/rules
linux/ibus-keyman/debian/control

Debian defines multiple similar environment variables. On most architectures the results are the same.
But on i386 libraries are expected in `/usr/lib/i386-linux-gnu`. `DEB_TARGET_MULTIARCH` gives that value (`i386-linux-gnu`), whereas the previous `DEB_TARGET_GNU_TYPE` gives `i686-linux-gnu` which then results in our libraries not being found.

feat(linux): Fix Linux packaging on i386

---

web/source/kmwutils.ts
web/source/osk/utils.ts
web/source/osk/visualKeyboard.ts

A small stepping-stone toward #5023.
There are no real user-facing benefits to speak of here, but this eliminates nearly all references to the root `com` namespace and the KMW root `window.keyman` object from within the OSK key classes; the few remaining references (solely to the former) are supported by the Web-core module.  This will be necessary for modularizing the OSK, which won't have access to things like `window.keyman.util`.
There's also some code centralization and consistency work.  I'm fine with having a number of OSKKey (+ subclass) methods require a `VisualKeyboard` reference as parameter, as they'll only ever be called by the `VisualKeyboard` class to begin with.  (The OSKKey classes are effectively internal classes of `VisualKeyboard`.)
I plan to follow this PR up with …

refactor(web): polishes management of OSK keys

---

web/source/kmwbase.ts
web/source/kmwembedded.ts
web/source/kmwutils.ts
web/source/osk/oskManager.ts
web/source/osk/visualKeyboard.ts

Another small stepping-stone toward #5023.  Nothing noteworthy from the user perspective here; it's prep work to enable features down the line.
Some noteworthy references:
Now that we don't need to worry about IE, the `classList` property can replace the old `util.hasClass` method.
- https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/contains#browser_compatibility
See the base PR (#5257) for notes on replacement of `util._CreateElement`.
I avoided use of `node.parentElement` due to concerns that some browsers may not provide this property on text nodes, as text nodes could conceivably be targeted an the event.
Most of the other code alterations are in service of removing references to …

refactor(web): Visual Keyboard disentanglement - pass 1

---

web/source/osk/oskManager.ts
web/source/osk/visualKeyboard.ts

The height of the layer-group container (the portion of the OSK that directly represents a keyboard) is now _consistently_ set as part of `VisualKeyboard.kbdDiv`'s styling.  This matches pre-existing behavior for most scenarios aside from one case:  before this, on touch devices, the height styling was set on the layer group instead.

refactor(web): VisualKeyboard height styling consistency

---

common/predictive-text/worker/correction/distance-modeler.ts

When text provided to the correction-search algorithm uses NFD input, it is possible for a keystroke to correspond to an unattached diacritic.  Search-term keying this results in an empty string; empty strings should _not_ correspond to correction-search graph edges.
(Fixes a user-reported issue with custom search-term keying for a `bcc-arab` model; the keyboard they used emits NFD text.)

fix(common/models): predictive-text engine use of NFD input

---

linux/ibus-keyman/debian/control

This change updates the version number for the keyman-keyboardprocessor dependency of ibus-keyman to a version that doesn't have wrong path for i386.

fix(linux): Adjust version of dependency for ibus-keyman

---

web/source/osk/visualKeyboard.ts

Fixes an issue accidentally introduced by commit https://github.com/keymanapp/keyman/pull/5278/commits/d582e69b73abef05cee27b44a846ea1584fe2a88 of #5278.
Changing the styling property of the `VisualKeyboard` root to fixed caused the `yMin` calculation to receive markedly different values than it did before, causing `touchMove`s before the appearance of popup keys to instantly break the touch gesture.  I found it simplest to maintain the 'spirit' of the original logic, opting for a threshold of 1/3 a row's height above the top of the layer group.
@MakaraSok 
Please load up Keyman on Android and ensure that touch-based behaviors still work as expected.  In particular, try moving your finger to a side immediately after touching a key - does the keytip or highlighting (whichever occurs on the …

fix(web): touch-move cancellation

---

windows/src/developer/kmconvert/Keyman.Developer.System.KMConvertParameters.pas

kmconvert built-in help was missing `-targets`, misspelled `-full-copyright`, and the parameter checking was skipping the last parameter (which only mattered if the last parameter was `-nologo`, but still...).

fix(developer): kmconvert help match reality

---

windows/src/developer/kmconvert/Keyman.Developer.System.KMConvertParameters.pas

Cherry-pick from #5298.
kmconvert built-in help was missing `-targets`, and the parameter checking was skipping the last parameter (which only mattered if the last parameter was `-nologo`, but still...).

fix(developer): kmconvert help match reality 🍒

---

common/core/desktop/debian/changelog
linux/ibus-keyman/debian/changelog
linux/ibus-kmfl/debian/changelog
linux/keyman-config/debian/changelog
linux/kmflcomp/debian/changelog
linux/libkmfl/debian/changelog

The changelogs should match what got uploaded (and accepted) to Debian so that the changelog reflects the upload history to Debian.

chore(linux): Update changelogs to match Debian

---

common/core/desktop/debian/changelog
linux/ibus-keyman/debian/changelog
linux/ibus-kmfl/debian/changelog
linux/keyman-config/debian/changelog
linux/kmflcomp/debian/changelog
linux/libkmfl/debian/changelog

The changelogs should match what got uploaded (and accepted) to Debian so that the changelog reflects the upload history to Debian.
🍒-pick of #5303

chore(linux): Update changelogs to match Debian 🍒

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m

Cherry-pick of #5328.
Relates to #5316.
Keyman for mac is still reading from kmp.inf, but was treating it as UTF-8. However, it is windows-1252 encoding. This was stopping Keyman from loading the file due to the presence of a (C) symbol.
Keyman for mac *should* be loading kmp.json. This needs to be addressed as a separate issue.

fix(mac): kmp.inf is windows-1252 🍒

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m

Relates to #5316.
Keyman for mac is still reading from kmp.inf, but was treating it as UTF-8. However, it is windows-1252 encoding. This was stopping Keyman from loading the file due to the presence of a (C) symbol.
Keyman for mac *should* be loading kmp.json. This needs to be addressed as a separate issue.

fix(mac): kmp.inf is windows-1252

---

resources/build/run-required-test-builds.sh
windows/src/engine/keyman32/KEYMAN32.DEF
windows/src/engine/keyman32/k32_globals.cpp
windows/src/engine/kmcomapi/com/system/keymancontrol.pas
windows/src/global/delphi/general/KeymanEngineControl.pas

Fixes #5245 on 15.0-alpha.
Interfaces should remain stable between versions of Keyman, so that an upgraded kmcomapi.dll or keyman32.dll will not crash older clients, even if they may not behave entirely as expected.

fix(windows): restore endpoints for interface stability

---

windows/src/engine/keyman/UfrmKeyman7Main.pas
windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas
windows/src/engine/keyman32/KEYMAN32.DEF
windows/src/engine/keyman32/Keyman32.cpp
windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/k32_globals.cpp
windows/src/engine/keyman32/kmhook_callwndproc.cpp
windows/src/engine/keyman32/kmhook_getmessage.cpp
windows/src/engine/keyman32/kmhook_keyboard.cpp
windows/src/engine/keymanx64/keymanx64.cpp
windows/src/engine/kmcomapi/com/system/keymancontrol.pas
windows/src/global/delphi/general/KeymanControlMessages.pas
windows/src/global/delphi/general/KeymanEngineControl.pas
windows/src/global/delphi/general/UserMessages.pas
windows/src/global/inc/keyman64.h
windows/src/global/inc/keymancontrol.h

Fixes #5067.
Fixes #5066.
Cherry-pick of #4989, #5002, #5060, #5061, #5062, #5202.
Fixes KEYMAN-WINDOWS-3F.
Fixes KEYMAN-WINDOWS-5A.
Fixes KEYMAN-WINDOWS-3E.
Fixes KEYMAN-WINDOWS-AC.
Fixes KEYMAN-WINDOWS-F5.
Probably fixes KEYMAN-WINDOWS-EH.
Probably fixes KEYMAN-WINDOWS-HH.
Probably fixes KEYMAN-WINDOWS-6M.

fix(windows): improve keymanx64 start stability 🍒

---

common/core/desktop/debian/changelog
common/core/desktop/debian/control
linux/ibus-keyman/debian/changelog
linux/ibus-keyman/debian/control

Seemingly Ubuntu builds for more architectures than Debian.
This change reflects a change that was made in Debian.

chore(linux): Build also on riscv64 to facilitate migration on Ubuntu

---

common/core/desktop/debian/changelog
common/core/desktop/debian/control
linux/ibus-keyman/debian/changelog
linux/ibus-keyman/debian/control

chore(linux): Build also on riscv64 to facilitate migration on Ubuntu 🍒

---

web/source/osk/browser/oskSubKey.ts
web/source/osk/browser/subkeyPopup.ts
web/source/osk/oskKey.ts
web/source/osk/visualKeyboard.ts

Follows from #5291.
This allows the osk-key classes to encapsulate highlighting behavior and logic for whether or not a key should be "previewable".

refactor(web): osk key highlighting/preview behavior

---

android/KMEA/app/src/main/assets/keyboard.html
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Fixes #5339.
This change is necessary due to changes implemented within #4703.  The issue _is_ pretty niche, so I can understand how it was missed at the time - _especially_ since `executePopupKey` was robust enough to prevent total breakage of such subkeys.
@MakaraSok
The effective changes are most easily noted with "before and after" testing using the `sil_cameroon_qwerty` keyboard, following the repro on #5339.  The subkeys for `W` and `E` (on the shift layer) only go back to the default layer with these changes in place, while (for comparison) the subkey for `U` (same layer) works as expected both before and after.
As only subkeys are affected, testing with other keyboards that utilize subkeys isn't a bad idea.
- `gff_amharic` is often recommended for subkey testing... though I didn't …

fix(android): fixes application of nextlayer for subkeys with customized layer setting

---

common/core/web/input-processor/src/text/contextWindow.ts
common/core/web/input-processor/src/text/inputProcessor.ts
common/core/web/input-processor/src/text/prediction/languageProcessor.ts
common/core/web/input-processor/tests/cases/inputProcessor.js
common/core/web/keyboard-processor/src/text/outputTarget.ts

An alternate approach from #5314.
Rather than outright turning off base fat-finger modeling, why not just threshold it within a tight time window?  As seen here, it's quite simple to do.
Furthermore, after a bit of investigation as to what could _possibly_ be responsible for #5314's point 3 making such a huge difference... I realized that the core `Mock.from` function was likely responsible.
1. `Mock.from` did _not_ get the sliding-context-window treatment
2. `Mock.from` relies on the kmwstring.ts utility functions.
The thing is... there's no reason for point 2 to be necessary if provided an initial Mock.  Which _**is**_ the case for modeling potential fat-fingers, even before applying engine rules - so this "simple" optimization should actually have a very significant impact.
In testing, …

feat(common/core/web): engine correction-prep optimizations

---

linux/keyman-config/keyman_config/install_kmp.py

When we update/reinstall an existing keyboard we don't want to add a new entry to the list of keyboards.
Fixes #5308.

fix(linux): Don't add duplicate entries when reinstalling keyboard

---

web/source/dom/domManager.ts
web/source/keyboards/kmwkeyboards.ts
web/source/kmwbase.ts
web/source/kmwembedded.ts
web/source/kmwnative.ts
web/source/kmwutils.ts
web/source/osk/oskManager.ts
web/testing/attachment-api/index.html
web/testing/promise-api/index.html

Follow-on to #5260 and addresses this point in spec #5044
> ### C5044.1.1.3 Changes to init
> Init needs to add a flag `useAlerts` (default true) to determine whether or not KeymanWeb should display its own alert messages if a keyboard fails to download or run. Modern consumers of the API will probably prefer to implement their own reject promise handler for `addKeyboards`, and we may also need to add an onalert callback event for other async errors
This also updates the "Promise API" test page to enable/disable alerts.

feat(web): Add option useAlerts to control alerts()

---

linux/keyman-config/keyman_config/install_kmp.py

When we update/reinstall an existing keyboard we don't want to
add a new entry to the list of keyboards.
Fixes #5308.
🍒-pick of #5363

fix(linux): Don't add duplicate entries when reinstalling keyboard 🍒

---

android/KMEA/app/src/main/assets/keyboard.html

Relates to #5258.
Unnecessary layout recalc eliminated by hiding the backing
textarea with `display:none`. This improved performance by roughly
20%.

feat(android): hide textarea for perf

---

windows/src/global/inst/data/keyboard_info/README.md
windows/src/global/inst/data/keyboard_info/keyboard_info.source.json

Brings this file up to date with the version found on [api.keyman.com](https://api.keyman.com/schemas/keyboard_info.source/1.0.6/keyboard_info.source.json)

chore: keyboard_info.source.json 1.0.6

---

windows/src/global/inst/data/keyboard_info/README.md
windows/src/global/inst/data/keyboard_info/keyboard_info.source.json

Cherry-pick of #5379.
Brings this file up to date with the version found on [api.keyman.com](https://api.keyman.com/schemas/keyboard_info.source/1.0.6/keyboard_info.source.json)

chore: keyboard_info.source.json 1.0.6 🍒

---

android/KMEA/app/src/main/assets/keyboard.html
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

This refactors the cross-boundary call to `setKeymanLanguage` to use JSON wrapping for the content. This is (a) safer, and (b) less mucking around anyway.

refactor(android): setKeyboard and setKeymanLanguage

---

linux/keyman-config/keyman_config/ibus_util.py
linux/keyman-config/keyman_config/install_kmp.py

When installing in the shared area the user has to run `km-package-install` with sudo so that he has sufficient permissions.
In that case we have to do extra work to restart ibus for the logged-in user instead of root.
Fixes #5309.
Also fixes a crash in `km-package-install -p foo`.

 fix(linux): Fix restarting ibus when running with sudo 

---

linux/keyman-config/keyman_config/deprecated_decorator.py
linux/keyman-config/keyman_config/get_kmp.py
linux/keyman-config/keyman_config/install_kmp.py
linux/keyman-config/keyman_config/install_window.py
linux/keyman-config/keyman_config/list_installed_kmp.py
linux/keyman-config/keyman_config/uninstall_kmp.py
linux/keyman-config/keyman_config/view_installed.py
linux/keyman-config/km-package-list-installed

Introduce methods to get paths instead of hard-coding the values. This also deprecates four methods (`user_keyman_dir`,
`user_keyman_font_dir`, `user_keyboard_dir`, and `get_isntall_area_path`).
This change also fixes a crash trying to install a package in the shared area.

refactor(linux): Centralize paths

---

android/KMEA/app/src/main/assets/keyboard.html

Relates to #5258.
Unnecessary layout recalc eliminated by hiding the backing textarea with `display:none`. This improved performance by roughly 20%.

feat(android): hide textarea for perf 🍒

---

ios/engine/KMEI/KeymanEngine/Classes/Extension/UserDefaults+Types.swift
ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
ios/engine/KMEI/KeymanEngine/Classes/SettingsViewController.swift
oem/firstvoices/ios/build_common.sh

This is a patch PR for #5365.
The main thing here is refactoring the enum into something that leverages Swift-style `enum`s, which come with a lot of nice benefits.  We can use built-in features instead of the helper methods that were there before.

feat(ios): refinement of spacebar-captioning PR

---

web/source/osk/oskManager.ts

Noticed this odd behavior when using KMW with a desktop form factor and `sil_euro_latin` - console errors occur when using hardware modifier keys, as there are no actual OSK layers to shift among due to use of "help text" instead of the `VisualKeyboard` class in that mode.

fix(web): console errors when using SHIFT w help-text 'osk'

---

windows/src/developer/TIKE/xml/app/editor/editor.js
windows/src/developer/TIKE/xml/layoutbuilder/builder.js

As we changed the User Agent string to have 'Keyman' instead of 'TIKE', the builder and editor commands were being ignored. This meant that changes to files would not be saved, among other terrible things.
This change was introduced with the Chromium update.

fix(developer): builder and editor commands were ignored

---

windows/src/developer/TIKE/Tike.dpr
windows/src/developer/TIKE/main/UfrmMain.pas

This function is no longer necessary as we no longer use the Trident (IE) engine for hosting web pages.

chore(developer): remove obsolete InitClasses

---

linux/keyman-config/keyman_config/convertico.py

Converting some bitmaps fail with a truncation error. This change
allows to successfully convert the bitmap files.
Fixes #5400.

fix(linux): Improve bitmap conversion

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeymanSettingsFragment.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/res/values/strings.xml
android/KMEA/app/src/main/assets/keyboard.html
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Keyboard.java
android/KMEA/build.sh
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVShared.java

Relates to #949.
* Adds setSpacebarText() API to Keyman Engine for Android
* Adds displayName API to Keyman Engine for Android
* Adds Preference for spacebar text to Keyman for Android
* Sets default spacebar text to keyboard name for FirstVoices Keyboards
New settings preference:
Touching that preference shows:
Result:

feat(android): Spacebar text controls

---

linux/keyman-config/keyman_config/convertico.py

Converting some bitmaps fail with a truncation error. This change
allows to successfully convert the bitmap files.
Fixes #5400. 🍒-pick of #5401.

fix(linux): Improve bitmap conversion 🍒

---

linux/keyman-config/keyman_config/ibus_util.py

When installing in the shared area the user has to run `km-package-install` with sudo so that he has sufficient permissions. In that case we have to do extra work to restart ibus for the logged-in user instead of root.
Fixes #5309. Partial 🍒-pick of #5371.

fix(linux): Fix restarting ibus when running with `sudo` 🍒

---

linux/keyman-config/keyman_config/install_window.py

If we try to install a keyboard that's missing some metadata we shouldn't crash.
Fixes #5384, #5385.

fix(linux): Don't crash with corrupt keyboard

---

linux/keyman-config/keyman_config/install_window.py

If we try to install a keyboard that's missing some metadata we shouldn't crash.
Fixes #5384, #5385. 🍒-pick of #5414.

fix(linux): Don't crash with corrupt keyboard 🍒

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Fixes #5418 and will need to get added to #5407 for stable-14.0
`setKeyboardRoot(packageID)` sets up the full filepaths for keyboard assets, so it needs to be called before any font path handling.
(Refer to comment https://github.com/keymanapp/keyman/pull/5338/files#r663754313)
1. On clean build, install sil_cameroon_qwerty keyboard
2. Show sil_cameroon_qwerty and verify OSK ok (no tofu on the diacritics)
3. Close app, and restart Keyman
4. When sil_cameroon_qwerty OSK appears, verify OSK ok (no tofu on the diacritics)

fix(android/engine): Fix font file path

---

web/testing/regression-tests/package-lock.json
web/testing/regression-tests/package.json

Pretty much... the title.  This simply brings the regression-tests subpackage up to speed with main KMW's updates from #5092.  Those changes have been working quite swimmingly for KMW as part of our CI, so there's a very strong chance they'll also be fine for the regression-tests suite.
This is also a two-birds, one-stone scenario:  there are a _lot_ of NPM audit issues here, and this update will remedy them all.

chore(web): updates regression test-deps to same versions as web

---

common/models/types/package.json

Looks like something in the npm audit fix PRs caused the default settings used by the "test" script to change, which caused a breakage on our `master` build.  This small tweak seems to be enough to fix it.

fix(common/models/types): fixes test script config

---

common/core/desktop/src/km_kbp_keyboard_api.cpp
common/core/desktop/src/kmx/kmx_actions.cpp
common/core/desktop/src/kmx/kmx_capslock.cpp
common/core/desktop/src/kmx/kmx_consts.cpp
common/core/desktop/src/kmx/kmx_context.cpp
common/core/desktop/src/kmx/kmx_debug.cpp
common/core/desktop/src/kmx/kmx_environment.cpp
common/core/desktop/src/kmx/kmx_file.cpp
common/core/desktop/src/kmx/kmx_modifiers.cpp
common/core/desktop/src/kmx/kmx_options.cpp
common/core/desktop/src/kmx/kmx_processevent.cpp
common/core/desktop/src/kmx/kmx_processevent.h
common/core/desktop/src/kmx/kmx_processor.cpp
common/core/desktop/src/kmx/kmx_processor.hpp
common/core/desktop/src/kmx/kmx_xstring.cpp
common/core/desktop/tests/unit/kmx/kmx.cpp

- rename source files for `kmx_processor` -> `kmx_processor.*`
- rename class `KMX_Processor` -> `KMX_ProcessEvent` with source   files `kmx_processevent.*`
Closes #5436.

refactor(common/core/desktop): Fix file and class names 🚧

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

🍒 pick of #5439 to stable-14.0
This fixes the following in switchToNextKeyboard
* Check for valid keyboard index
* register associated lexical model
Note: This contains temporary globe action `GlobeKeyAction.GLOBE_KEY_ACTION_SWITCH_TO_NEXT_KEYBOARD` which must be reverted before merging.
@keymanapp/testers
2. Install the following keyboards: khmer_angkor, gff_amharic, sil_cameroon_qwerty
3. Wait for the keyboards to install and the associated dictionary for gff_amharic
4. In the Keyman app press the globe key several times (switches to next keyboard w/o KeyboardPicker)
* Verify sil_euro_latin shows suggestions
* Verify khmer_angkor does not show suggestions
* Verify gff_amharic shows suggestions
* Verify sil_cameroon_qwerty does not show suggestions

fix(android/engine): register lexical model in switchToNextKeyboard 🍒 

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java

Fixes #5426 
Resolve some trivial TODOs so that dictionary help links (welcome.htm) can be displayed.
2. Install gff_amharic keyboard
3. After a while, the associated dictionary will download and install (the lexical model package includes a welcome.htm file while the default nrc.en.mtnt does not)
4. Go to Settings --> Languages --> Amharic --> Dictionary --> GFF Amharic --> Help Link
5. Verify the welcome.htm page displays
Ignore the styling issue with the help arrow #4715

fix(android/engine): Display dictionary help link

---

android/KMEA/app/src/main/assets/keyboard.html
web/source/keyboards/kmwkeyboards.ts

Will need to 🍒 pick to #5407
From comment https://github.com/keymanapp/keyman/pull/5437#discussion_r664965071
> If this is an unrelated fix, can we extract it into a separate PR for testing and rebase this PR on it?
Originally this PR adjusted `KI` passed to KeymanWeb for registration.
Per review comments, this PR now has KeymanWeb make a copy of stubs that can be mutated and used for registration.
In `setKeymanLanguage()`, the KeymanWeb call `registerStub()` is handling the package namespacing adds the k.KP+:: prefix to `k.KI`.
This caused weirdness when installing or switching keyboards (where the OSK didn't match selected or the associated lexical model didn't appear). (Comment https://github.com/keymanapp/keyman/pull/5407#issuecomment-874397635)
1. Install the PR …

fix(web): Copy the keyboard stubs for registration

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Split out from #5437 and follow-on #5438
This fixes the following in switchToNextKeyboard
* Check for valid keyboard index
* register associated lexical model
Note: This contains temporary globe action `GlobeKeyAction.GLOBE_KEY_ACTION_SWITCH_TO_NEXT_KEYBOARD` which  must be reverted before merging.
2. Install the following keyboards: khmer_angkor, gff_amharic, sil_cameroon_qwerty
3. Wait for the keyboards to install and the associated dictioanry for gff_amharic
4. In the Keyman app press the globe key several times (switches to next keyboard w/o KeyboardPicker)
* Verify sil_euro_latin shows suggestions
* Verify khmer_angkor does not show suggestions
* Verify gff_amharic shows suggestions
* Verify sil_cameroon_qwerty does not show suggestions

fix(android/engine): register lexical model in switchToNextKeyboard

---

web/source/keyboards/kmwkeyboards.ts
web/source/kmwbase.ts
web/source/osk/visualKeyboard.ts
web/testing/index.html
web/testing/spacebar-text/index.html
web/testing/spacebar-text/rac_balti.js

Cherry-pick of #5348.
Relates to #949.
* Adds optional `displayName` property to keyboard stubs: if present,
this will override the name on the spacebar.
* Adds optional `spacebarText` member to `keyman.options`. This defaults
to `SpacebarText.LANGUAGE_KEYBOARD`, and can be one of:
```
SpacebarText.LANGUAGE
SpacebarText.KEYBOARD
SpacebarText.LANGUAGE_KEYBOARD
SpacebarText.BLANK
```
* Sets the display pattern for LANGUAGE_KEYBOARD to be
"language - keyboard" instead of "language (keyboard)", which
reduces the number of parentheses visible on the spacebar.

feat(web): spacebar text controls 🍒 🌌

---

ios/engine/KMEI/KeymanEngine/Classes/Constants.swift
ios/engine/KMEI/KeymanEngine/Classes/Extension/UserDefaults+Types.swift
ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
ios/engine/KMEI/KeymanEngine/Classes/Model/InstallableKeyboard.swift
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
oem/firstvoices/ios/FirstVoices/AppDelegate.swift
web/source/osk/visualKeyboard.ts

Cherry-pick of #5365.
Relates to #949.
Mirror of #5349 (Android), for iOS.
* Adds setSpacebarText() API to Keyman Engine for iOS
* Adds displayName API to Keyman Engine for iOS
* Sets default spacebar text to keyboard name for FirstVoices Keyboards
* Does not add preference UI

feat(ios): add spacebar text controls 🍒 🌌

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Cherry-pick of #5468.
Reports the actual error message instead of 'sendKMWError' as the primary message to Sentry.

chore(android): improve error reporting for kmw 🍒

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Reports the actual error message instead of 'sendKMWError' as the primary message to Sentry.
A further improvement would be to capture the details of the error as data on the error rather than as a breadcrumb.
Yet further would be if we could report the error back from the web browser itself, giving us source context rather than Android context...

chore(android): improve error reporting for kmw

---

ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html

Turns out #5438 accidentally broke keyboard swapping for iOS.  Fortunately, the fix is pretty simple.
Since `.registerStub` is no longer pass-by-reference, we have to manually construct the value that used to result from the call.  No biggie.
I've already done what's needed, I believe.
But, if you _really_ want it tested...
- If it works, success!  (`master` currently fails here.)

fix(ios): keyboard swapping

---

common/core/web/input-processor/src/text/inputProcessor.ts
common/core/web/input-processor/src/text/prediction/languageProcessor.ts
common/predictive-text/worker/model-compositor.ts

Fixes #5467.
No wonder it was an elusive little bugger.  I knew something smelled like a race condition as I started investigating... turns out it's probably a race condition caused by the interaction of standard OS context-swapping (or garbage collection) with that of a timer based on the system clock.  Hence why a direct repro is nigh-impossible to find or construct.
I should note that some of the Sentry issues do indicate occasions where they arose before [14.0.277](https://github.com/keymanapp/keyman/blob/stable-14.0/HISTORY.md#140277-stable-2021-06-29), which was when #5352 landed.  That said, the lion's share of the reports for the tagged issues are indeed since that release, which is why it's become as prominent now as it is.
So, while it's not exactly _perfect_ to just give up …

fix(common/core/web): error from early fat-finger termination due to OS interruptions

---

common/core/web/input-processor/src/text/inputProcessor.ts
common/core/web/keyboard-processor/src/keyboards/activeLayout.ts
common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
web/source/osk/oskManager.ts
web/source/osk/visualKeyboard.ts

Ran into this one while testing related aspects of #5451... turns out it was actually a bug on `master` _and_ `stable-14.0`.  (So, it'll need a 🍒-pick.)
Using either keymanweb.com (for stable) or the standard unminified test page:
1. Load a KMW-enabled page in your preferred Desktop browser.
- The bugs are browser-independent.
2. Choose an input area (in order to display the OSK)
3. Press your keyboard's caps lock key:  it won't update.
4. Type an 'a' keypress - still no CAPS update.
5. Press the SHIFT key:  _now_ the OSK's caps key updates.
Then:
1. Refresh the page
2. Choose an input area (in order to display the OSK)
3. Press the OSK's caps-lock key:  it won't update
4. Press the OSK's 'a' key:  still no update
4. Press the OSK's SHIFT key:  still no update.  (So, broken OSK …

fix(common/core/web): OSK state-key management

---

windows/src/buildtools/devtools/DevDelphiCompileWrapper.pas
windows/src/buildtools/devtools/DevDelphiStarterCompileWrapper.pas
windows/src/buildtools/devtools/DevIncludePaths.pas
windows/src/buildtools/devtools/DevInstallPackages.pas
windows/src/buildtools/devtools/SourceRootPath.pas
windows/src/buildtools/devtools/UfrmCompilerErrors.pas
windows/src/developer/samples/imsample/IMSample.vcxproj
windows/src/ext/jedi/jcl/jcl/source/windows/JclCLR.pas
windows/src/ext/jedi/jcl/jcl/source/windows/JclSvcCtrl.pas
windows/src/ext/mbcolor/mxs.inc
windows/src/global/delphi/comp/FixedTrackbar.pas
windows/src/global/delphi/general/CleartypeDrawCharacter.pas
windows/src/global/delphi/general/utilicon.pas

Updates Keyman for Windows and Keyman Developer sources so that they build under Delphi 10.4. No validation has been performed to ensure that there are no other issues. The intent here is to get a baseline build working.
Note also IMSample.vcxproj which has its WinSDK version updated for VS2019.
This will not allow us to build in Delphi 10.4 Community Edition because of the missing command line compiler. That will be handled separately.

chore(windows): patches for Delphi 10.4

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/Keyboard.java

Fixes an accidental discrepancy in the 🍒-pick of #5349 in #5407; somehow, one of the changes didn't get ported to `stable-14.0` properly, and that's affecting some 3rd party users of our Android `KeymanEngine` library.

fix(android): displayName for keyboard was not optional

---

linux/Jenkinsfile
linux/scripts/launchpad.sh

- **Groovy** is EOL
- llso is not yet capable of processing **Impish** packages because of an too old version of _reprepro_ (which currently can't be 
updated because of an tool old version of the OS). Therefore Jenkins builds for Impish fail, so this change removes Impish from 
Jenkins builds. We continue to build for Impish on Launchpad.

chore(linux): Remove Groovy and Impish builds

---

linux/Jenkinsfile
linux/scripts/launchpad.sh

**Groovy** is end-of-life.
(🍒-pick of #5502)

chore(linux): Remove Groovy builds 🍒

---

linux/ibus-keyman/debian/control

Keyman 15 introduces breaking changes. When building Keyman 14 we need to use the Keyman 14 dependencies to avoid broken builds.

chore(linux): Fix dependency versions

---

common/core/web/input-processor/src/text/inputProcessor.ts
common/core/web/input-processor/src/text/prediction/languageProcessor.ts
common/predictive-text/worker/model-compositor.ts

A 🍒-pick of #5479.
It's literally the same set of tests that was used for #5479.
Much of this is taken from standard KMW acceptance testing and adapted toward the aspects of KMW modified by this PR, though we'll only worry about testing against a single platform here.
**Platform**:  Chrome emulation / Android
Ensure that you see the "Console" tab while performing these tests.
- Ignore anything seen elsewhere mentioning "Issues" or within a small "Issues" tab - there are a few entries we know about, but they're not affected by this PR.  I'm looking for "Console" log messages.
Console tab:
It should resemble Windows' `CMD` prompt and the macOS Terminal.
Utilize the "Test unminified Keymanweb" testing page to ensure the following:
- **Attempt to add the following …

fix(common/core/web): error from early fat-finger termination due to OS interruptions 🍒

---

common/core/desktop/src/kmx/kmx_actions.cpp
common/core/desktop/src/kmx/kmx_file.h
common/core/desktop/src/kmx/kmx_processevent.cpp
common/core/desktop/src/kmx/kmx_processor.cpp

Moves the responsibility for deletion of markers when the users presses the backspace key, from `kmx_processor::process_event` to `KMX_ProcessEvent::ProcessGroup`. This has no effect on usage of Keyman Core, but:
1. Simplifies the association between context and action further
2. Ensures that `m_actions` and `state->actions` will always be the same length, making future refactoring of these simpler
3. Allows us to use the index into the m_actions array for Debug events, which simplifies the interleaving of these for the upcoming Debugger.
When the user presses backspace at start of context (where there may be markers in the cached context, but no characters), the kmx processor will delete any markers prior to insertion point before requesting that the consumer emit the backspace virtual …

chore(common/core): refactor backspace handling 🐞

---

windows/src/engine/keyman32/Keyman32.vcxproj
windows/src/engine/keyman32/Keyman32.vcxproj.filters
windows/src/engine/keyman32/keyman-engine.vcxproj
windows/src/engine/keyman32/keyman-engine.vcxproj.filters
windows/src/engine/keyman32/pch.h
windows/src/engine/keyman32/tests/keyman32-tests/pch.h
windows/src/engine/keyman64/keyman64.vcxproj
windows/src/engine/keyman64/keyman64.vcxproj.filters
windows/src/global/inc/keyman64.h
windows/src/global/inc/keymanengine.h

Ground work for #5011 . This PR breaks out the include files and definitions from keyman64.h into keymanengine.h This will allow for projects like kmanalyze to just include keyman64.h and not keymanengine.h and therefore the whole keyman core library.

chore(windows): split keyman64 header to keymanengine

---

ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
ios/samples/KMSample2/KMSample2/AppDelegate.swift

A 🍒-pick of #5484.
- Verify that all previously-installed keyboards are still installed.
- Swapping among the keyboards via the picker is enough to tell us what we need.
- There are two ways to do this:
- Set Xcode to target a device that you have not previously used for any tests.
- Reset a simulated device that you have previously used:
Run that to reset a simulated device, which will erase all existing Keyman settings on said simulated device.

fix(ios/engine): engine migration always precedes installs 🍒

---

ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
ios/samples/KMSample2/KMSample2/AppDelegate.swift

Fixes an issue reported through other channels by a third-party KeymanEngine user that seemed to obliterate keyboards installed on their app's first launch (and _only_ during that first launch).  Should be 🍒-picked, as the underlying issue can cause similar unintuitive issues for other 3rd-party framework users.
------
The changes to resource installation in 14.0 did a lot to disentangle the process for installing keyboards and models from KeymanEngine's `Manager` monolith-class.  Unfortunately, it turns out there was one subtle but critical strand of entanglement that wasn't quite removed.
While resource installation itself isn't dependent on a `Manager` instance existing, the `Migrations` system called early on in `Manager`'s init _must_ run _before_ any resources are installed; …

fix(ios/engine): engine migration always precedes installs

---

.clang-format

This allows vscode to format C++ files according our [coding style guideline](https://github.com/keymanapp/keyman/wiki/Keyman-Code-Style-Guide).

chore(common): Add C++ formatting rules

---

common/core/web/input-processor/src/text/inputProcessor.ts
common/core/web/keyboard-processor/src/keyboards/activeLayout.ts
common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
web/source/osk/preProcessor.ts
web/source/osk/visualKeyboard.ts

A 🍒-pick of #5456.
This fixes issues with the caps and numlock state management, mostly for the desktop OSK.  There are some core-internal effects though, especially in regard to complications with layer management for mnemonic keyboards' touch OSKs.
The 🍒-pick process was a bit complicated this time because some of the affected code blocks were in different files in 14.0 than they currently are in 15.0.  Made sure to inspect the resulting changeset and compare the results directly.
**IF** we want them, we can just use the same set of tests that was used for #5456.
And, well, knowing the way things usually go... yeah, @keymanapp/testers.  (But prioritize #5491 first!)
<details>
<summary>Instructions & Tests</summary>
Using the "Test unminified KeymanWeb" test page:
<details> …

fix(common/core/web): OSK state-key management 🍒

---

windows/src/developer/TIKE/compile/CompileKeymanWeb.pas

Fixes #5440.
Currently, the behavior of `use()` and `match` for KeymanWeb compiled keyboards is not identical to the Windows (or Core) behavior. The example keyboard in #5440 generates 'foo' instead of 'abc' on web.
This fixes that by ensuring that `match` is not called when `use()` is found in a group rule match.
Take note of https://github.com/keymanapp/keyman/issues/5440#issuecomment-889624379 when finishing this.
Given this keyboard (from #5440):
```
group(Main) using keys
+ [K_1] > 'a'
'b' + [K_2] > context use(b)
match > use(a)
```
The following code block shows the differences in the compiled code to ensure that we match the Windows behavior:
```diff
this.gs=function(t,e) {
return this.g_Main_0(t,e);
};
this.g_Main_0=function(t,e) {
var k=KeymanWeb,r=0,m=0;
if(k.KKM(e, …
```

fix(developer): compiler use and match behavior for Web should be same as Core

---

linux/keyman-config/keyman_config/keyboard_details.py

Fixes #5526.
The bug got introduced in #5411 while fixing #5310.

fix(linux): fix crash trying to display QR code

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Fixes #5509.
If a keyboard has empty font data string, then we should avoid attempting to parse it.

fix(android): avoid error with empty font data

---

web/source/osk/visualKeyboard.ts

Looks like something slipped through the cracks in one of the previous OSK PRs; it's possible for keys to receive 'stuck' highlighting during a touch-move operation.  (First noticed when testing a different, branch-local issue on #5462.) Fortunately... it's an easy fix.
The test below also serves as a repro on the current state of `master`.  Happens for both 'phone' and 'tablet' form-factors, though it's worse for tablets since they don't use key previews.
@keymanapp/testers
**Platform**
- Use the KeymanWeb "Test unminified Keymanweb" test page on any platform/browser combination that allows emulation of a touch device.
- For example, Windows / Chrome _or_ macOS / Chrome.  Whichever is more convenient for you.
- Be sure to enter Developer mode and actually turn on mobile device emulation …

fix(web): stuck key highlighting from touchpoint movement

---

android/build-help.sh

Fixes #5533 
#5132 copied `whatsnew.md` to use as Play Store release notes. However, there's a 500 character limit.
This updates `build-help.sh` to: 
* Only use lines starting with `*` or indented `*`
* Check the character count < 500. If more, then add a general note `* Additional bug fixes and improvements`

fix(android/app): Check Play Store release notes less than 500 chars

---

linux/keyman-config/keyman_config/uninstall_kmp.py

Previously uninstalling of a keyboard failed if the directory was a symlink (e.g. with keyboards from unit tests). This change treats
symlinks differently.
Fixes Sentry issue KEYMAN-LINUX-32.

fix(linux): Improve uninstallation

---

linux/keyman-config/keyman_config/__init__.py
linux/keyman-config/keyman_config/downloadkeyboard.py
linux/keyman-config/keyman_config/install_kmp.py
linux/keyman-config/keyman_config/install_window.py
linux/keyman-config/keyman_config/kmpmetadata.py
linux/keyman-config/keyman_config/uninstall_kmp.py
linux/keyman-config/keyman_config/view_installed.py
linux/keyman-config/km-kvk2ldml

This change imports `os` instead of `os.path`. This is the recommended way. It also reduces confusion whether to use `os.path.whatever()` or just `path.whatever()`.

refactor(linux): Cleanup import of os.path

---

common/core/desktop/tests/unit/kmx/meson.build

This change allows to build the keyboards on Linux if a `kmcomp` script can be found in PATH. Otherwise we check for and use `wine` and `kmcomp.exe`.

chore(common/core): Allow shell script for kmcomp

---

ios/engine/KMEI/KeymanEngine/az.lproj/Localizable.strings
ios/engine/KMEI/KeymanEngine/az.lproj/Localizable.stringsdict
ios/keyman/Keyman/Keyman/Classes/GetStartedViewController/GetStartedViewController.swift
ios/keyman/Keyman/Keyman/az.lproj/Localizable.strings
windows/src/desktop/kmshell/locale/az-AZ/strings.xml

One of the translators on translate.keyman.com flagged 3 Windows strings for Azerbaijani as incorrect. Here's the 3 strings.
*Update:*
It's grown to 40+ strings. Per Ken
> I read through several of the issues, and I think his translation is okay.
We generally haven't done any special testing when updating Crowdin strings. You can:
* Get the test build installer and select "Azerbaycanca" (closest resemblance  of  typing "Azerbaijani") during Setup
* After Setup finishes, open Keyman Configuration --> Display In --> Azerbaijani
* Spot check the Keyman UI
* This probably involves building the app from this branch. I'm not familiar with how you'd set the locale for Azerbaijani

chore(ios,windows): Update crowdin strings for Azerbaijani

---

android/KMAPro/build.gradle
android/KMAPro/kMAPro/build.gradle
android/README.md
android/Samples/KMSample1/build.gradle
android/Samples/KMSample2/build.gradle
android/Tests/KeyboardHarness/app/build.gradle
android/Tests/KeyboardHarness/build.gradle
oem/firstvoices/android/app/build.gradle
oem/firstvoices/android/build.gradle

Fixes #5347
Gradle warnings during build of FV app
```
getMappingFile(): Cannot query the value of this property because it has no value available.
AGPBI: {"kind":"warning","text":"API 'variant.getMappingFile()' is obsolete and has been replaced with 'variant.getMappingFileProvider()'.\nIt will be removed in version 7.0 of the Android Gradle plugin.\nFor more information, see https://d.android.com/r/tools/task-configuration-avoidance.\nTo determine what is calling variant.getMappingFile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.","sources":[{}]}
getMappingFile(): Cannot query the value of this property because it has no value available.
AGPBI: {"kind":"warning","text":"Using flatDirs should be avoided because it doesn't support any meta-data …
```

chore(android): Update sentry-android-gradle-plugin to 2.1.0

---

web/source/kmwnative.ts
web/testing/index.html
web/testing/issue5455/index.html

#5302 added an option useAlerts that controlled whether internal alerts are displayed.
This fixes #5455 by having util.wait also check the option.
* Also added a test page to display util.wait and then dismiss

fix(web): Have util.wait check useAlerts option

---

android/KMEA/app/src/main/assets/keyboard.html
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/res/values/strings.xml

Fixes #5397.
This disables the fallback to default keyboard in Keyman Engine for Android, and prevents a toast from appearing more than once for a given error. The first five errors will be reported to Sentry and then subsequent errors will be ignored, until a different keyboard is selected, to prevent spamming the error log and wasting bandwidth for the user.

fix(android): gracefully handle errors in KMW keyboards

---

linux/ibus-keyman/src/keyman-service.c

This change replaces the deprecated `g_type_class_add_private` and `G_TYPE_INSTANCE_GET_PRIVATE` with `G_DEFINE_TYPE_WITH_PRIVATE` and the generated method `km_service_get_instance_private`.

chore(linux): Remove compiler warning in ibus-keyman

---

windows/src/desktop/kmshell/xml/installkeyboard.css

Fixes #4883.
keyboard installation prompt wordwrap
Before:
After:

fix(windows): wrap text in keyboard installation dialog

---

windows/src/engine/tsysinfo/Makefile
windows/src/engine/tsysinfo/base.xslt

Minor fix to make the module list format correctly with chromium browser instead of mshtml, plus a tweak to build to copy xsl files as well to bin.

fix(windows): tsysinfo format grid correctly

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/DownloadIntentService.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/DownloadResultReceiver.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/LanguagesSettingsActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/res/values/strings.xml
android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java

Fixes #5242
When the progress dialog for downloading a kmp is cancelled, sometimes it gets left in a state preventing further kmp's from being downloaded.
* This sets the cancel handler on progressDialog to do cleanup.
* Also cleaned up imports on LanguagesSettingsActivity (when I was searching for references of progressDialog)
Initially putting the PR in draft since I haven't been able to repro the reported issue.

fix(android/app): Fix cleanup when progress dialog cancelled

---

common/predictive-text/unit_tests/headless/worker-model-compositor.js
common/predictive-text/worker/model-compositor.ts

Fixes #5429.
The original behavior that caused the bug was implemented before 14.0, which introduced the `languageUsesCasing` flag.  So, before 14.0, `searchTermToKey` performed double-duty, modeling case-insensitivity _and_ diacritic-insensitivity.  But now... now, those have been split into separate functions.  When de-duplicating the "keep" string and a possible suggestion, we want diacritic-_sensitivity_ but case-_insensitivity_.  Fortunately, we now have the tools for that.
In the lexical model, words are always stored in lower-case.  If a user typed in initial-case, and the only difference is _casing_, that should match.  If, however, the user typed an extra diacritic... that's not a perfect match, and so we shouldn't de-duplicate.
------
Post-change samples:
The latter case is to …

fix(common/models): keep/suggestion diacritic sensitivity when de-duping

---

common/predictive-text/unit_tests/headless/worker-model-compositor.js
common/predictive-text/worker/model-compositor.ts

fix(common/models): keep/suggestion diacritic sensitivity when de-duping 🍒

---

web/source/osk/visualKeyboard.ts
web/testing/spacebar-text/index.html

Fixes #5524 and follow-on to #5349 (Adding controls for the spacebar caption)
In the reported issue, a blank display name `""` was still showing a spacebar caption. This is because when activeStub['displayName'] is `""`, the check for displayName was falsy.
This PR changes the check to 
`if (activeStub['displayName'] != null) {`
Wait until other developers get a chance to review and comment
* load web/testing/spacebar-text/index.html
* If not already selected, set the keyboard to RAC Balti 
* Verify the spacebar text is "My Custom Name"
* Set the keyboard to Lao 2008 Basic
* Verify the spacebar text is blank
* Set the keyboard to US
* Verify the spacebar text adjust according to the radio button setting
* Load the test app
* Install a keyboard
* Verify the Keyboard and …

fix(web): Blank spacebar text when displayName is empty string

---

linux/ibus-keyman/README.md

Turns out setting `KEYMAN_PROC_CFLAGS` isn't sufficient to use header files from source repo.

docs(linux): Fix readme for ibus-keyman

---

web/README.md

This is work arising from the spacebarText postmortem. The only changes in this are to the readme, just to give us a pull request to play with. Remaining changes are to the **Test-14.0 (Keyman - Web)** build configuration to publish the KeymanWeb testing, sample and tools folders. This gives us build artifacts on build.palaso.org which should be sufficient for testing and no longer require build of KeymanWeb by testers.
For example, please view the artifacts for [Test-14.0 (Keyman - Web)](https://build.palaso.org/viewLog.html?buildId=285239&buildTypeId=Keymanweb_TestPullRequests&tab=artifacts), and click on the index.html link there -- this should give testable version of KeymanWeb, instantly. So good. 😁

feat(web): setup build artifacts for manual tests

---

common/predictive-text/package-lock.json
ios/kmbuild.sh
ios/tools/prepRelease.sh
oem/firstvoices/ios/build_common.sh

I may need some guidance ensuring things are handled properly on the build-agent side, but I've added the `-all-artifacts` build option to both the Keyman app and FV app build scripts.  This produces an extra artifact - a `.app` version that can be dragged and dropped straight to the Simulator.  This'll _greatly_ facilitate testing... once we can direct our tester(s) to the artifact.
(This is one of our postmortem actions from spacebarText)

feat(ios): adds option for Simulator-compatible testing artifact

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java

Fixes #5252.
I figured out the solution while working on embedded keyboard layout issues in #5459 after asking @darcywong00 how the WebView sets its height.
----------
Gonna be kinda lazy with this one.
- Rotate the phone and confirm that the layout looks correct.
- Rotate the phone back to its original orientation and confirm that the layout looks correct.

fix(android): keyboard's black bar bug

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

#5459 included the #5521's fix among its changes due to affecting similar areas.  Unfortunately, the location was off by a few lines - just enough for `git merge` to not conflate the two changes and thus result in duplicate lines.  As one of these lines includes a variable declaration, this is enough to cause the Java build to fail with an error.
Fortunately, it's a simple fix.

fix(android): removes duplicated line

---

linux/keyman-config/keyman_config/handle_install.py
linux/keyman-config/km-package-install
linux/keyman-config/tests/test_gnome_keyboards_util.py
linux/keyman-config/tests/test_handle_install.py

Before trying to install we now check if it's a valid zip file.
This fixes #5575.

fix(linux): Check for valid kmp file

---

windows/src/desktop/kmshell/main/UfrmHTML.dfm
windows/src/desktop/kmshell/main/UfrmHTML.pas
windows/src/desktop/kmshell/startup/UfrmSplash.dfm
windows/src/desktop/kmshell/startup/UfrmSplash.pas
windows/src/global/delphi/ui/UfrmKeymanBase.pas

Fixes #5574.
When a user presses Win+M, Win+D, or clicks the desktop button on the taskbar, all windows get minimized, even those that do not have the `WS_MINIMIZE` flag. Delphi modal dialog forms are not expecting this, and do not restore correctly later.
This scenario arises only when a form is created with a `nil` owner and then `form.ShowModal` is called.
The fix was already implemented on Splash and HTML forms, but differently; I have chosen to use the implementation from the Splash form as it is simpler and seems to work correctly.

fix(windows): handle restoring modal dialogs consistently

---

ios/engine/KMEI/KeymanEngine/az.lproj/Localizable.strings
ios/engine/KMEI/KeymanEngine/az.lproj/Localizable.stringsdict
ios/keyman/Keyman/Keyman/GetStartedViewController/GetStartedViewController.swift
ios/keyman/Keyman/Keyman/az.lproj/Localizable.strings
windows/src/desktop/kmshell/locale/az-AZ/strings.xml

🍒 -pick of #5486 to stable-14.0
This updates 40 crowdin strings for iOS and Windows per one of the translators on translate.keyman.com
The iOS "Get Started" title should also be localized now.
@keymanapp/testers
We generally haven't done any special testing when updating Crowdin strings. You can:
* Get the test build installer and select "Azerbaycanca" (closest resemblance of typing "Azerbaijani") during Setup
keyman setup - az
* After Setup finishes, open Keyman Configuration --> Display In --> Azerbaijani
* Spot check the Keyman UI
This probably involves building the app from this branch. I'm not familiar with how you'd set the locale for Azerbaijani

chore(ios,windows): Update crowdin strings for Azerbaijani 🍒 

---

linux/keyman-config/keyman_config/handle_install.py
linux/keyman-config/km-package-install
linux/keyman-config/tests/test_gnome_keyboards_util.py
linux/keyman-config/tests/test_handle_install.py

Before trying to install we now check if it's a valid zip file.
This fixes #5575.
(🍒-picked from PR #5583)

fix(linux): Check for valid kmp file 🍒

---

windows/src/developer/TIKE/Tike.dpr
windows/src/developer/TIKE/Tike.dproj
windows/src/developer/TIKE/child/UfrmDebug.dfm
windows/src/developer/TIKE/child/UfrmDebug.pas
windows/src/developer/TIKE/debug/Keyman.System.Debug.DebugEvent.pas
windows/src/developer/TIKE/debug/Keyman.UI.Debug.CharacterGridRenderer.pas
windows/src/developer/TIKE/debug/debugdeadkeys.pas
windows/src/global/delphi/comp/KeymanDeveloperDebuggerMemo.pas

Before starting on new functionality in the debugger, I wanted to
cleanup a bunch of bits and pieces, including:
1. Correct handling of text selection and deletion
2. Refactor of character grid at bottom of debug window
3. Deadkey realignment after text changes
4. Correct tracking of cursor position between events
5. Handling a few destruction edge cases

fix(developer): debugger cleanup 🐞

---

windows/src/developer/TIKE/actions/dmActionsKeyboardEditor.pas
windows/src/developer/TIKE/child/UfrmDebug.pas
windows/src/developer/TIKE/child/UfrmKeymanWizard.pas
windows/src/developer/TIKE/dialogs/UfrmMustIncludeDebug.dfm
windows/src/developer/TIKE/dialogs/UfrmMustIncludeDebug.pas

This resolves the broken Test Mode with Keyman Core. Previously, Test Mode just dumped the keyboard into Keyman for Windows, and let it do its thing. Given that we no longer have the dependency on Keyman for Windows, the Test window must use Keyman Core to process keystrokes, and that means there are some differences in how Test Mode operates in 15.0:
* Behind the scenes, the Test mode is just the Debug mode with breakpoints and single step disabled, and the Debug Status window hidden
* Test mode requires debug information in the keyboard (see note below)
* You can always switch between Test and Debug mode
* Deadkeys are always shown in the debug window
Test Mode now requires debug information to be included in the keyboard in order for deadkeys to be tracked correctly …

fix(developer): get Test Mode working again 🐞

---

windows/src/developer/TIKE/child/UfrmDebugStatus.pas
windows/src/developer/TIKE/main/UfrmMain.dfm
windows/src/developer/TIKE/main/UfrmMain.pas

Hide the debug events panel by default, and add a Tools menu item to make it visible for dev purposes (Ctrl+Shift+click on Tools menu to view).

chore(developer): hide debug events panel 🐞

---

common/core/web/input-processor/src/text/inputProcessor.ts
common/core/web/keyboard-processor/src/text/defaultOutput.ts
common/core/web/keyboard-processor/src/text/kbdInterface.ts
common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
common/core/web/keyboard-processor/src/text/ruleBehavior.ts
common/core/web/keyboard-processor/tests/cases/engine/unmatched_final_group.js
common/core/web/tests/resources/fixtures/singleTextArea.html
common/core/web/tests/resources/json/engine_tests/ghp_enter.json
common/core/web/tests/resources/json/keyboards/galaxie_hebrew_positional.json
common/core/web/tests/resources/keyboards/galaxie_hebrew_positional-2.2.js
web/source/dom/domDefaultOutput.ts
web/source/dom/preProcessor.ts
web/source/osk/preProcessor.ts
web/source/osk/visualKeyboard.ts
web/tools/recorder/recorder_KeyboardScripts.js
web/unit_tests/cases/engine.js

Fixes an error reported here: https://community.software.sil.org/t/tab-key-on-touch-layout/4291
When KeymanWeb is run in embedded mode, TAB should no longer function as a DOM-oriented command.  These changes allow us to disable that logic path when embedded, enabling `'\t'` output instead.
In-app appearance after a single press of TAB:
I don't believe it's possible for iOS to support TAB key commands - Apple's pretty strict with what it allows keyboards to do.  While the [official documentation](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/CustomKeyboard.html) doesn't explicitly state anything about tab commands, [this StackOverflow post](https://stackoverflow.com/a/28637083) states it to be impossible.
Compatibility of `\t` with predictive …

fix(web, android, iOS): OSK 'tab' support when embedded

---

windows/src/buildtools/sentrytool/Keyman.System.SentryTool.SentryToolMain.pas

The maximum command line length in Windows is 2047 characters. In Delphi it appears to be 1024 characters. In debugging, I hit that 1024 character limit which was pretty annoying.
So this patch allows us to use an `@file` parameter to put command line parameters into a text file and read from that instead. It's probably a little hacked together and could be turned into a class that we could usefully reuse in all our other command line apps.
I looked around for a generic Delphi solution but did not find an existing one that was any good.
Low priority, not required for beta, but putting it up because I've done the work already.

chore(windows): sentrytool param file support

---

windows/src/developer/TIKE/actions/dmActionsKeyboardEditor.dfm
windows/src/developer/TIKE/actions/dmActionsKeyboardEditor.pas
windows/src/global/delphi/chromium/Keyman.UI.UframeCEFHost.pas

If user presses F6 in the debugger (while not in run mode), will now switch to editor view, and vice-versa.
Also fixes the inversion of the focus test in CEF so that focus controls work correctly for web hosts.

fix(developer): F6 in debugger and cef focus 🐞

---

resources/build/report-history.sh
resources/build/version/src/index.ts
resources/build/version/src/reportHistory.ts

Relates to #5172.
* Adds support for reporting historical release ranges (--from, --to)
* Filters emoji out of titles
* Uses HISTORY.md formatting for report-history
Note: once approved, I'll cherry-pick this and #5527 to stable-14.0

chore(common): more on report-history 🏰

---

android/KMEA/app/src/main/assets/keyboard.html
web/source/kmwembedded.ts

Follow-on to #5351 and fixes #5610
Some longpress keys on the shift layer weren't working on Keyman for Android (e.g. sil_madi).
This fixes how the "functional" layer and "display" layers are determined in kmwembedded.ts.
This fills out `kLayer` and `kbdLayer` so it matches what KeymanWeb on desktop uses
The keyboards seem to work in 15.0 (`master`) so maybe don't need to 🍒 pick?
<details><summary>Setup</summary>
1.  Install the test build
2.  Install sil_madi and sil_cameroon_qwerty keyboards
</details>
* **TEST_MADI:** Longpress on shift layer
1. Change the keyboard to sil_madi
2. On the default layer, longpress on a vowel and select it
3. Verify the correct character is output
4. Press <kbd>Shift</kbd> to switch to the "Shift" layer
5. Longpress on the <kbd>A</kbd> and select one of …

fix(web): Fix layers for embedded longpress keys

---

linux/keyman-config/keyman_config/gnome_keyboards_util.py

This fixes a bug introduced in #3290 where we added using the language from search. Unfortunately that broke things in a lot of other places because we didn't test for the empty string.
- **TEST_LANG_1**: keyboard installed with double clicking on .kmp file appears in system keyboard dropdown list
<details><summary>Steps</summary>
- download a .kmp file, e.g. Dzongkha (SIL) keyboard
- install the .kmp file by double clicking the file (if double clicking opens the .kmp file in another application, you'll have to
right-click the file, select "Open With Other Application" and select "Keyman Keyboards" from the list.
- verify that "Dzongkha (Dzongkha (SIL))" appears in the system keyboard dropdown list. If no Keyman keyboards appear in the
dropdown you might have to restart gnome-shell (press …

fix(linux): Use first keyboard language if none given

---

linux/Jenkinsfile
linux/keyman-config/keyman_config/gnome_keyboards_util.py

This fixes a bug introduced in #3290 where we added using the language from search. Unfortunately that broke things in a lot of
other places because we didn't test for the empty string.
(:cherries:  picked from #5655)
- **TEST_LANG_1**: keyboard installed with double clicking on .kmp file appears in system keyboard dropdown list
<details><summary>Steps</summary>
- download a .kmp file, e.g. Dzongkha (SIL) keyboard
- install the .kmp file by double clicking the file (if double clicking opens the .kmp file in another application, you'll have to
right-click the file, select "Open With Other Application" and select "Keyman Keyboards" from the list.
- verify that "Dzongkha (Dzongkha (SIL))" appears in the system keyboard dropdown list. If no Keyman keyboards appear in the
dropdown you might …

fix(linux): Use first keyboard language if none given 🍒

---

android/KMEA/app/src/main/assets/keyboard.html

Fixes #5576
The internal textarea that KeymanWeb uses was hidden in #5376 for performance (avoid redundant layout calculations).
On Android 5.0 (Lollipop) devices with WebView 37.0 though, hiding the textarea prevents KeymanWeb from getting `selectionStart` and `selectionEnd` positions (they remain at 0). 
Note, Android 5.1 (also Lollipop) devices have WebView 39.0 and function fine with the hidden textarea.
This PR updates keyboard.html to check the WebView version. If <= 37, it will revert #5576. Even though we take a performance hit, it's more important that KeymanWeb can remain in sync with the context.
Will need to 🍒 pick to stable-14.0
Setup: Install the test build
Devices needed: 
* phone emulator with Android 5.0 Lollipop (SDK 21)
* tablet emulator with Android 5.0 Lollipop (SDK …

fix(android/engine): Fix backspace on Android 5.0

---

android/KMEA/app/src/main/assets/keyboard.html

Cherry-pick of #5660 to stable-14.0
Addresses #5576 for 14.0
The internal textarea that KeymanWeb uses was hidden in #5376 for performance (avoid redundant layout calculations).
On Android 5.0 (Lollipop) devices with WebView 37.0 though, hiding the textarea prevents KeymanWeb from getting `selectionStart` and `selectionEnd` positions (they remain at 0). 
Note, Android 5.1 (also Lollipop) devices have WebView 39.0 and function fine with the hidden textarea.
This PR updates keyboard.html to check the WebView version. If <= 37, it will revert #5576. Even though we take a performance hit, it's more important that KeymanWeb can remain in sync with the context.
Setup: Install the test build
Devices needed: 
* phone emulator with Android 5.0 Lollipop (SDK 21)
* tablet emulator with Android 5.0 …

fix(android/engine): Fix backspace on Android 5.0 🍒 

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/ContextUtils.java

Fixes #5540 
Android Studio doesn't provide an emulator SDK for Android 6.0.1, so I can't repro the issue.
This PR is for @keymanapp/testers to try the PR build on a physical device with Android 6.0.1 
Setup: Load the PR build on an Android 6.0.1 device
* **TEST_LOCALE** Test that the Android UI language can change to different locales
1. Load Keyman for Android
2. Go to "Settings" and change the Display Language to Khmer
3. Exit the menus and go back to "Settings"
4. Verify the UI uses Khmer
5. Repeat with other Display Languages and verify the UI updates accordingly

fix(android/engine): Fix localization on Android M

---

resources/build/report-history.sh
resources/build/version/package-lock.json
resources/build/version/src/fixupHistory.ts
resources/build/version/src/index.ts
resources/build/version/src/reportHistory.ts

Effective cherry-pick of #5527, #5603, to bring report-history.sh into the stable-14.0 tree for reporting purposes and consistency.

chore(common): report-history 🍒

---

windows/src/developer/TIKE/Makefile
windows/src/developer/inst/kmdev.wxs
windows/src/developer/kmanalyze/Makefile
windows/src/test/test_i3633/verify.dpr

Fixes #5648.
Includes kmnkbp0-0.dll in the installer for Keyman Developer.
* TEST_BASIC: Load a keyboard in Keyman Developer, and press F5 to start debugging. It should start!

fix(developer): include Keyman Core in Keyman Developer 🐞

---

windows/src/developer/TIKE/oskbuilder/UframeTouchLayoutBuilder.pas

Fixes #5577.
Cherry-pick of #5676.
This ensures that the touch layout file is marked as modified after running Import From Layout in Keyman Developer, so that changes are not lost when you save.
@keymanapp-test-bot skip: user testing done in #5676.

fix(developer): ensure file modified after import from layout 🍒

---

.github/workflows/crowdin.yml
resources/build/l10n/README.md

This PR adds an action to upload sources per https://support.crowdin.com/github-crowdin-action/
The source files are organized at a top level folder named "master".
For now, I've set the action to trigger every two weeks (one sprint cycle) which should suffice.

chore(common): Add GitHub action to upload sources to crowdin

---

windows/src/engine/kmcomapi/com/keyboards/keymankeyboardfile.pas
windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboard.pas
windows/src/engine/kmcomapi/util/utilkeyman.pas
windows/src/global/delphi/general/RegKeyboards.pas

Fixes #5683.
If `store(&name)` is missing from a keyboard, then fallback to the filename of the keyboard (sans extension). This fixes a regression in 14.0 keyboard registration.
I opted not to make this change in kmxfile but rather in places which use it in the Keyman Engine COM API, because I wanted kmxfile to remain truthful about all details of what it is reading from the file.
Given that the COM API will now never return an empty string for the name of the keyboard, there are  mitigations for this in Keyman Configuration which are unnecessary, but it is not harmful for them to remain there.
Will cherry-pick to stable-14.0.
TEST_NO_NAME: Verify that keyboards with no `&name` store work correctly.
1. Create a keyboard that has no `store(&name)` header. Install it.
2. The keyboard should …

fix(windows): fallback to filename if `&name` not set

---

ios/engine/KMEI/KeymanEngine/Classes/Errors/SentryManager.swift

While this doesn't address the actual error, I noticed an issue in the logs for this logged error in Sentry: https://sentry.keyman.com/share/issue/07929f28738c4be9861f858cec3363d8/
This is happening for 15.0 when the errors are logged from the system keyboard, as `Bundle.main` for the app extension is _separate_ from the main app's `Bundle.main`.  We don't set version info on the app-extension's bundle, which leads to the tag seen above.
Fortunately, we also put the version information on the framework's bundle, so we'll get more consistent tagging if we base off of that instead.
----
The actual error has been documented at #5694.

fix(ios): version-tagging for errors logged from the system keyboard

---

web/source/osk/oskBaseKey.ts
web/source/osk/oskLayer.ts

Fixes a bug detected during testing of #5633.  Turns out it's a bug on `master` that began in 15.0.96, literally one alpha version after the previous spacebar caption fix.  This one was actually my fault this time, rather than the result of the configurable spacebar caption change.
The bug only affects scenarios like the following:
(From `khmer_angkor`'s numeric layer.)
As the spacebar's "functional layer" (its modifier set) doesn't match its display layer, the key-finding method wasn't actually matching the `K_SPACE` lookup.  This actually could have been affecting other related operations, the most prominent alternative being the layer's globe key... though I think there are extra checks in place there that avoided the problem.
Use Chrome's remote-device emulation mode to test the …

fix(web): spacebar caption when functional layer differs from display layer

---

web/source/osk/bannerManager.ts
web/source/osk/emptyView.ts
web/source/osk/helpPageView.ts
web/source/osk/keyboardView.interface.ts
web/source/osk/layouts/resizeBar.ts
web/source/osk/layouts/targetedFloatLayout.ts
web/source/osk/layouts/titleBar.ts
web/source/osk/oskManager.ts
web/source/osk/oskViewComponent.ts

This relatively lightweight PR adds an abstraction for use by the OSK and its subcomponents.  By having each subcomponent implement a common interface, this increases nomenclature consistency and should facilitate code readability and maintenance.
Follows #5530.  (The 👆 set.)
This PR also polishes up some of the internal layout calculations, using thematically-named fields and methods that better describe the purpose of the values being used.  There _is_ a mild shift in the values' source when it comes to `.computedWidth` and `.computedHeight`, which are intended to serve as the "master" layout value for active OSKs and are recalculated during layout-refreshes.  (Refer to changes made in https://github.com/keymanapp/keyman/pull/5462.)
- These changes also include fixes for desktop OSK …

refactor(web): OSK modularization - view components, layout cleanup ✂️

---

windows/src/engine/kmcomapi/com/keyboards/keymankeyboardfile.pas
windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboard.pas
windows/src/engine/kmcomapi/util/utilkeyman.pas
windows/src/global/delphi/general/RegKeyboards.pas

Fixes #5683.
Cherry-pick of #5684.
If `store(&name)` is missing from a keyboard, then fallback to the filename of the keyboard (sans extension). This fixes a regression in 14.0 keyboard registration.
I opted not to make this change in kmxfile but rather in places which use it in the Keyman Engine COM API, because I wanted kmxfile to remain truthful about all details of what it is reading from the file.
Given that the COM API will now never return an empty string for the name of the keyboard, there are  mitigations for this in Keyman Configuration which are unnecessary, but it is not harmful for them to remain there.
(Same test as with Keyman 15.0 in #5684)
TEST_NO_NAME: Verify that keyboards with no `&name` store work correctly.
1. Create a keyboard that has no `store(&name)` header. …

fix(windows): fallback to filename if `&name` not set 🍒

---

common/core/desktop/include/keyman/keyboardprocessor_version.h.in
common/core/desktop/include/keyman/meson.build
common/core/desktop/src/meson.build
common/core/desktop/src/version.rc
windows/src/test/test_i3633/verify.dpr

Fixes #5672.
* Adds version information to meson build for Keyman Core DLL
* Removes verify.dpr patch added in #5649 so it will be tested at build

fix(developer): add version info to Core 🐞

---

common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
common/predictive-text/package-lock.json
web/package-lock.json

Fixes #5635.
On the first physical keystroke after using the OSK, the OSK's layer management will reset to track all incoming physical keystrokes.
The underlying cause:  the `updateLayer` function did not properly update Web-core's tracked modifier state.  For non-'desktop' form factors, other aspects of the control flow were able to fill in the gaps, but since modifier keys can't output to the context for 'desktop' form-factor layouts, those don't run for 'desktop' due to short-circuiting optimizations.  Fortunately, all we need is a simple, focused fix.
TEST_DESKTOP_REPRO:  Confirm that the original error no longer reproduces.  (Your choice of desktop browser.)
<details><summary>Repro instructions + expected behavior</summary>
**To Reproduce**
1. Use KeymanWeb's unminified test page on …

fix(common/core/web): layer reset on physical keystroke after OSK interaction

---

ios/engine/KMEI/KeymanEngine/Classes/KeyboardKeymanPackage.swift
ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift
ios/engine/KMEI/KeymanEngine/Classes/LexicalModelKeymanPackage.swift
ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
ios/engine/KMEI/KeymanEngine/en.lproj/Localizable.strings
ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift

Fixes #5694.
Also fixes up how package-opening errors are handled and forwarded.  The package parser wasn't actually surfacing errors that arose internally, causing any error condition to report a "corrupted package," even when the cause was different.
Adds two new strings that'll need localization - these provide better, more specific messages for package problems:
- A "package is missing" message.  Shouldn't ever be seen from the app, but then again, most errors "shouldn't ever be seen".  It's best to keep it around "just in case."
- A "package is only for desktop" message.  (See `TEST_HIEROGLYPHIC` below.)
TEST_HIEROGLYPHIC:  Attempt to install the hieroglyphic package from https://keyman.com/keyboards/hieroglyphic.
You should see a popup message like the following:
But with this text …

fix(ios): prevents installation of packages without JS

---

windows/src/developer/TIKE/child/UfrmDebug.pas

The ralt, rctrl, lalt, lctrl modifiers were not working correctly in the debugger.
* **TEST_CHIRALITY:** test various rules with chiral modifiers
1. Start a new keyboard.
2. Chiral modifiers are `LALT`, `LCTRL`, `RALT`, `RCTRL`. Add rules to test these, along with the non-chiral modifier `SHIFT`, and verify that the rules can be matched in the debugger. For example:
```
+ [RALT K_A] > 'RightAlt+A works!'
```
3. Try and test combinations of the modifiers as well as modifiers on their own.
**Note:** you should not mix chiral and non-chiral versions of the same modifier (e.g. ALT and RALT) in the same keyboard, for the avoidance of confusion.
* **TEST_NONCHIRALITY:** test various rules with non-chiral modifiers.
1. Start a new keyboard.
2. Add rules to test various …

fix(developer): support chiral modifiers in debugger 🐞

---

common/core/desktop/src/km_kbp_options_api.cpp
common/core/desktop/tests/unit/kmnkbd/meson.build
common/core/desktop/tests/unit/kmnkbd/options_api.cpp

There was a bug in `km_kbp_options_list_size` which meant it would never exit if there was at least 1 item in the list. 
The option_api unit tests are incomplete so this was not picked up.

fix(common/core): insure list pntr is incremented

---

web/source/kmwembedded.ts

Fixes #5725 and Sentry issue [#4292](http://sentry.keyman.com/organizations/keyman/issues/4292/?project=7)
> Uncaught TypeError: Cannot read property 'lgKey' of null
Load the PR build in an Android 5.1 or Android 6.0 emulator
* **TEST_GLOBE** Tests that there's no exceptions getting the globe key position
1. Start the app in portrait orientation
2. Verify no Toast notifications appear about keyboard error
3. Rotate the device between portrait and landscape orientation several times
4. Verify after each rotation no keyboard errors appear

fix(web): Null check for calculating globe key position

---

windows/src/developer/TIKE/Tike.dpr
windows/src/developer/TIKE/Tike.dproj
windows/src/developer/TIKE/main/Keyman.Developer.System.KeymanDeveloperPaths.pas
windows/src/developer/kmcomp/kmcomp.dpr
windows/src/developer/kmcomp/kmcomp.dproj
windows/src/global/delphi/lexicalmodels/Keyman.Developer.System.LexicalModelCompile.pas

Makes it possible to run the kmlmc.cmd compiler wrapper script from Keyman Developer while debugging from source.
Adds a new class `TKeymanDeveloperPaths` which is similar to `TKeymanPaths`, to provide a future single location for all Keyman Developer path-related functions. There are a number scattered through the source at present, e.g. in `RedistFiles.pas`, so this is just a starting point.

fix(developer): run kmlmc from Keyman source path

---

mac/.gitignore
mac/setup/build.sh
mac/setup/textinputsource/Makefile
mac/setup/textinputsource/build.sh

Fixes #5700.
Cherry pick of #5701.
Adds support for arm64 (M1) to textinputsource in the Keyman app. All other executables are already fat with support for both x86_64 and arm64.
Note: https://help.keyman.com/knowledge-base/107 needs to be updated once this and a cherry-picked to 14 version are released.
* TEST_INSTALL_M1: Make sure Keyman installs on an M1 mac (I will run this test as I have the M1 mac on my desk).
* TEST_INSTALL_INTEL: Make sure Keyman installs and runs on Intel-based mac.

fix(mac): add support for M1 processor 🍒

---

docs/build/macos.md
mac/.gitignore
mac/README.md
mac/setup/build.sh
mac/setup/textinputsource/Makefile
mac/setup/textinputsource/build.sh

Fixes #5700.
Adds support for arm64 (M1) to textinputsource in the Keyman app. All other executables are already fat with support for both x86_64 and arm64.
Note: https://help.keyman.com/knowledge-base/107 needs to be updated once this and a cherry-picked to 14 version are released.
* TEST_INSTALL_M1: Make sure Keyman installs on an M1 mac (I will run this test as I have the M1 mac on my desk).
* TEST_INSTALL_INTEL: Make sure Keyman installs and runs on Intel-based mac.

fix(mac): add support for M1 processor

---

common/core/desktop/src/km_kbp_options_api.cpp
windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/keyboardoptions.cpp
windows/src/engine/keyman32/keyboardoptions.h
windows/src/engine/keyman32/tests/keyman-engine-tests/gtest_main.cpp
windows/src/engine/keyman32/tests/keyman-engine-tests/keyboardoptionstests.cpp
windows/src/engine/keyman32/tests/keyman-engine-tests/keyman-engine-tests.vcxproj
windows/src/engine/keyman32/tests/keyman-engine-tests/kmprocessactionstests.cpp
windows/src/engine/keyman32/tests/keyman-engine-tests/pch.cpp

Fixes #5653 
Three functions are added  `SaveKeyboardOptionsCore` `UpdateKeyboardOptionsCore` and  `RestoreKeyboardOptionsCore`. 
To facilitate in saving the keyboard processors keyboard options and then also restoring them.
Unit tests have also been added to test the added functions.

feat(windows): preserving keyboard options in engine

---

resources/build/help-keyman-com.sh

Cherry-pick of #5750.
Ensures that the destination folder is cleaned before deployment.

fix: help.keyman.com script file cleanup 🍒

---

.github/multi-labeler.yml

So far we only check for the :cherries: emoji character to add the cherry-pick label. GitHub now also supports emoticons as text
in PR titles. This change adds the detection of the `:cherries:` text.

chore(common): Enhance cherry-pick labeling

---

windows/src/developer/TIKE/xml/layoutbuilder/builder.js

Fixes #5327.
This is in the touch layout editor.
* **TEST_BASELINE**: Run through basic editing scenarios for any touch layout, and make sure that files continue to load and save and be editable.
* **TEST_CLEANUP**: Verify that empty rows are removed.
1. Using the afghan_turkmen.zip attached to #5327, look at afghan_turkmen_1_1.keyman-touch-layout **in a text editor**.
2. In the text editor (not in Keyman Developer), verify that the `phone` layout has a blank first row:
```json
{
"id": 1,
"key": []
},
```
3. Load afghan_turkmen_1_1.kmn, make a single change to the touch layout, and save.
4. In the text editor, reload the file, and verify that the `phone` layout in afghan_turkmen.keyman-touch-layout no longer has a blank first row.

fix(developer): remove empty touch rows on save

---

android/KMAPro/kMAPro/src/main/res/values-b+shu+latn/strings.xml
android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java
android/KMEA/app/src/main/res/values-b+shu+latn/strings.xml
crowdin.yml
ios/engine/KMEI/KeymanEngine/Classes/shu-latn-n.lproj/ResourceInfoView.strings
ios/engine/KMEI/KeymanEngine/shu-latn-n.lproj/Localizable.strings
ios/engine/KMEI/KeymanEngine/shu-latn-n.lproj/Localizable.stringsdict
ios/keyman/Keyman/Keyman/shu-latn-n.lproj/Localizable.strings
linux/keyman-config/locale/shu_latn.po
windows/src/desktop/kmshell/locale/shu-latn/strings.xml
windows/src/desktop/kmshell/xml/elements.xsl
windows/src/desktop/kmshell/xml/keyman_menu.xsl
windows/src/desktop/setup/locale/shu-latn/strings.xml

This checks in the crowdin strings for Shuwa Latin. The locale is set up on crowdin as `shu-latn-NG`. Updated crowdin.yml so Android will sync the strings to `b+shu+latn`.
1.Load the Keyman app for each platform
2. In the app, change the UI language to "Shuwa Latin"
3. Note whether the UI strings change to Shuwa Latin.
Sample screenshot of Settings menu
* **TEST_IOS**

chore(common): Check in crowdin strings for Shuwa Latin

---

windows/src/developer/TIKE/xml/layoutbuilder/template-basic.keyman-touch-layout
windows/src/developer/TIKE/xml/layoutbuilder/template-traditional.keyman-touch-layout

Fixes #5702.
On the phone layout for two templates, ampersand (`&`) was on <kbd>Shift</kbd>+<kbd>6</kbd> instead of on <kbd>Shift</kbd>+<kbd>7</kbd>.
TEST_IMPORT: Follow the steps in #5702 to import a template and confirm that the ampersand is on <kbd>Shift</kbd>+<kbd>7</kbd> on phone and tablet layouts, numeric layer. Check this in both Basic and Traditional templates.

fix(developer): move ampersand to shift+7 on touch

---

.github/multi-labeler.yml

So far we only check for the :cherries: emoji character to add the cherry-pick label. GitHub now also supports emoticons as text
in PR titles. This change adds the detection of the `:cherries:` text.
(:cherries:-picked from PR #5759)

chore(common): Enhance cherry-pick labeling 🍒 

---

.github/multi-labeler.yml
.github/workflows/labeler.yml

My previous commit escaped the parens which should be part of the regex.
(:cherries:-picked from PR #5782)

fix(common): Fix cherry-pick labeling (:cherries:)

---

.github/multi-labeler.yml
.github/workflows/labeler.yml

My previous commit escaped the parens which should be part of the regex.

fix(common): Fix cherry-pick labeling

---

android/KMAPro/kMAPro/src/main/res/values-am-rET/strings.xml
android/KMEA/app/src/main/res/values-am-rET/strings.xml
ios/engine/KMEI/KeymanEngine/am.lproj/Localizable.strings
windows/src/desktop/kmshell/locale/am-ET/strings.xml

This updates the latest strings for Amharic
Install the PR build of Keyman for Android on an Android 5.0 emulator
* **TEST_ANDROID** - Tests for new Amharic strings
1. Start the app
2. From the "Settings" menu --> Display Language -> Amharic
3. Verify the app refreshes with Amharic strings. The Android 5.0 device will have a banner with a blue button prompting the user to upgrade WebView. This is one of the new Amharic strings
* **TEST_IOS**  - Tests for new Amharic strings
1. Start the app
2. Change the UI to Amharic locale
3. Verify the app refreshes with Amharic strings

chore(ios,android,windows): Update crowdin strings for Amharic

---

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
windows/src/desktop/kmshell/install/Keyman.Configuration.UI.InstallFile.pas
windows/src/desktop/kmshell/install/UfrmInstallKeyboard.pas
windows/src/desktop/kmshell/main/initprog.pas
windows/src/engine/kmcomapi/com/keyman_implementation.pas
windows/src/engine/kmcomapi/keymanapi_TLB.pas
windows/src/engine/kmcomapi/keymancontext.pas
windows/src/engine/kmcomapi/kmcomapi.dproj
windows/src/engine/kmcomapi/kmcomapi.ridl
windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboard.pas
windows/src/global/delphi/general/Keyman.System.CanonicalLanguageCodeUtils.pas
windows/src/global/delphi/general/klog.pas
windows/src/test/unit-tests/standards-data/GetOsVersion.pas
windows/src/test/unit-tests/standards-data/standardsdata.dpr
windows/src/test/unit-tests/standards-data/standardsdata.dproj

Fixes #5091.
Will cherry-pick to stable-14.0 after approval.
If the user has a default language that is not a minimal BCP47 tag, such as `zh-Hans-CN` vs `zh-CN`, or if the default language does not have a mapping in our `TLanguageCodeUtils.TranslateWindowsLanguagesToBCP47` function, then kmshell would crash on install of a keyboard that had no language metadata specified (i.e. neither legacy metadata in .kmx nor modern metadata in .kmp).
This crash arose because the elevated instance of kmshell would install a local-machine reference to `zh-CN` (as it back-translated from a LangID), but the current user install would look for `zh-Hans-CN`, read from the Windows registry `HKCU\Control Panel\International\User Profile`.
To further complicate matters, it is possible for the current user to …

fix(windows): handle edge cases using default language

---

linux/keyman-config/keyman_config/install_window.py

If a user tries to a install a model .kmp file, we now display a message box instead of crashing.
Fixes #5753.
(:cherries:-picked from #5754)
New message box:
- TEST_FIX: verify message box appears when trying to install model file
- download a model file, e.g. https://downloads.keyman.com/models/aozcq.rar-latn.cook_islands_maori/1.2/aozcq.rar-latn.cook_islands_maori.model.kmp
- try to install the model file by running `km-config -i $HOME/Downloads/aozcq.rar-latn.cook_islands_maori.model.kmp` (you might have to adjust the path to the .kmp file)
- verify a message box similar to the above one is shown

fix(linux): Don't crash with non-keyboard package file 🍒

---

linux/keyman-config/keyman_config/keyboard_details.py

At least one user got a crash trying to click on the "About" button to display keyboard details for the ekwtamil99uni keyboard. I can't reproduce the problem, but this change adds additional code that should prevent the crash from happening.
Fixes #5756.
- TEST_TAMIL: "About" doesn't crash for ekwtamil99uni keyboard
- install ekwtamil99uni keyboard
- open keyman-config
- select 'Thamizha Tamil99' keyboard and click "About" button
- verify that the keyboard details dialog shows
- TEST_OTHER: "About" doesn't crash for keyboard that contains a description
- install a keyboard that does contain a package description, e.g. gff_amharic
- follow similar steps as above

fix(linux): Don't crash displaying keyboard details

---

linux/keyman-config/keyman_config/keyboard_details.py

At least one user got a crash trying to click on the "About" button to display keyboard details for the ekwtamil99uni keyboard. I can't reproduce the problem, but this change adds additional code that should prevent the crash from happening.
Fixes #5756.
- TEST_TAMIL: "About" doesn't crash for ekwtamil99uni keyboard
- install ekwtamil99uni keyboard
- open keyman-config
- select 'Thamizha Tamil99' keyboard and click "About" button
- verify that the keyboard details dialog shows
- TEST_OTHER: "About" doesn't crash for keyboard that contains a description
- install a keyboard that does contain a package description, e.g. gff_amharic
- follow similar steps as above
(:cherries:-picked from #5757)

fix(linux): Don't crash displaying keyboard details 🍒

---

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMEA/app/src/main/AndroidManifest.xml
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java
oem/firstvoices/android/app/src/main/AndroidManifest.xml

Starts to address #5396 
The Keyman Engine for Android classes for `cloud/`, `data/`, and `logic/` are too entangled to move from Keyman Engine to the Keyman app.
As a stopgap, this PR removes the unnecessary permissions from the engine's Android_Manifest.xml file:
*  INTERNET
* READ_EXTERNAL_STORAGE
* ACCESS_NETWORK_STATE (per review comment)
Some internal calls also updated to handle when those permissions aren't available.
Apps using Keyman Engine for Android can then add those permissions back in their Manifest file (e.g. Keyman and FirstVoices).
* **TEST_KEYMAN_SDK_21** - Tests Keyman on Android 5.0
1. Start an Android 5.0 emulator (SDK 21) and disable network access
2. Load the PR build of Keyman
3. On the "Get Started" menu -->Add a keyboard for your language
4. On the next menu, …

fix(android/engine): Remove unnecessary permissions from Manifest

---

common/core/desktop/debian/changelog
linux/ibus-keyman/debian/changelog
linux/ibus-kmfl/debian/changelog
linux/keyman-config/debian/changelog
linux/kmflcomp/debian/changelog
linux/libkmfl/debian/changelog

This updates the changelog files to match what got uploaded into Debian unstable (sid).

chore(linux): Update changelog files for 14.0.282

---

linux/debian/changelog
linux/legacy/ibus-kmfl/debian/changelog
linux/legacy/kmflcomp/debian/changelog
linux/legacy/libkmfl/debian/changelog

This updates the changelog files to match what got uploaded into Debian unstable (sid).
(:cherries:-picked from #5793)

chore(linux): Update changelog files for 14.0.282 :cherries: 

---

linux/keyman-config/keyman_config/install_window.py

If a user tries to a install a model .kmp file, we now display a message box instead of crashing.
Fixes #5753.
New message box:
- TEST_FIX: verify message box appears when trying to install model file
- download a model file, e.g. https://downloads.keyman.com/models/aozcq.rar-latn.cook_islands_maori/1.2/aozcq.rar-latn.cook_islands_maori.model.kmp
- try to install the model file by running `km-config -i $HOME/Downloads/aozcq.rar-latn.cook_islands_maori.model.kmp` (you might have to adjust the path to the .kmp file)
- verify a message box similar to the above one is shown

fix(linux): Don't crash with non-keyboard package file

---

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
windows/src/desktop/kmshell/install/Keyman.Configuration.UI.InstallFile.pas
windows/src/desktop/kmshell/install/UfrmInstallKeyboard.pas
windows/src/desktop/kmshell/main/initprog.pas
windows/src/engine/kmcomapi/com/keyman_implementation.pas
windows/src/engine/kmcomapi/keymanapi_TLB.pas
windows/src/engine/kmcomapi/keymancontext.pas
windows/src/engine/kmcomapi/kmcomapi.dproj
windows/src/engine/kmcomapi/kmcomapi.ridl
windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboard.pas
windows/src/global/delphi/general/Keyman.System.CanonicalLanguageCodeUtils.pas
windows/src/global/delphi/general/klog.pas
windows/src/unit-tests/standards-data/GetOsVersion.pas
windows/src/unit-tests/standards-data/standardsdata.dpr
windows/src/unit-tests/standards-data/standardsdata.dproj

Fixes #5091.
Cherry-pick of #5709.
If the user has a default language that is not a minimal BCP47 tag, such as `zh-Hans-CN` vs `zh-CN`, or if the default language does not have a mapping in our `TLanguageCodeUtils.TranslateWindowsLanguagesToBCP47` function, then kmshell would crash on install of a keyboard that had no language metadata specified (i.e. neither legacy metadata in .kmx nor modern metadata in .kmp).
This crash arose because the elevated instance of kmshell would install a local-machine reference to `zh-CN` (as it back-translated from a LangID), but the current user install would look for `zh-Hans-CN`, read from the Windows registry `HKCU\Control Panel\International\User Profile`.
To further complicate matters, it is possible for the current user to have a different default …

fix(windows): handle edge cases using default language 🍒

---

linux/ibus-keyman/src/Makefile.am
linux/ibus-keyman/src/engine.c
linux/ibus-keyman/src/keycodes.h

This will allow to use the array in unit tests.

chore(linux): Extract keycode_to_vk[] to separate header file 🎫

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeyboardSettingsActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/KeyboardController.java
android/help/basic/uninstalling-keyboards.md

Fixes #5828
Keyman for Android doesn't allow the user to uninstall the default sil_euro_latin keyboard partly because it was used as a fallback keyboard whenever KeymanWeb exceptions happen. #5423 disabled the fallback behavior.
Also, for feature-party with Keyman for iPhone and iPad, this PR allows the user to uninstall the sil_euro_latin keyboard (as long as another keyboard remains)
Setup for each of the tests:
* Load the PR build
* Install 2 additional keyboards (khmer_angkor and sil_cameroon_qwerty)
* **TEST_KEYBOARD_PICKER_UNINSTALL** - Tests sil_euro_latin can be uninstalled from the keyboard picker menu
1. Load Keyman for Android
2. Long-press the globe key to display the keyboard picker menu
3. Hold down on the default sil_euro_latin keyboard until the "DELETE" popup appears
4. …

feat(android): Allow uninstall of sil_euro_latin keyboard

---

common/core/desktop/tests/meson.build
common/core/desktop/tests/unit/kmx/meson.build
common/core/desktop/tests/unit/kmx/template/keyboard.kmn.in
common/core/desktop/tests/unit/kmx/template/keyboard.kpj.in
common/core/desktop/tests/unit/kmx/template/keyboard.kps.in
common/core/desktop/tests/unit/meson.build

This change adds package templates to the test folder and compiles a keyboard package for each of the test keyboards. These
packages are useful for manual testing in addition to the automated tests.

chore(common/core): Compile test keyboards to .kmp 🎫

---

crowdin.yml

Follow-on to #5869 
This updates the common crowdin.yml configuration file so we can incorporate the Keyman for macOS strings for other languages (as they get translated).
I already uploaded the Khmer strings @MakaraSok provided, and they round-trip with the download:
```
crowdin.bat download -b master -l km
```
Note, there's some newer Khmer strings on the other platforms to check in - for a separate PR.

feat(mac): Add Keyman for macOS files to crowdin.yml

---

linux/ibus-keyman/.gitignore
linux/ibus-keyman/src/keymanutil.h
linux/ibus-keyman/tests/Makefile.am
linux/ibus-keyman/tests/ibusimcontext.c
linux/ibus-keyman/tests/run-tests.sh
linux/ibus-keyman/tests/testfixture.cpp
linux/ibus-keyman/tests/testmodule.h

This change fixes the ibus-keyman test client so that now all tests pass.

chore(linux): fix failing ibus-keyman tests 🎫

---

windows/src/developer/TIKE/child/UfrmDebug.pas
windows/src/developer/TIKE/main/RedistFiles.pas
windows/src/global/delphi/comp/KeymanDeveloperDebuggerMemo.pas

Fixes #5718.
The debugger memo control will now filter out action shortcut keys such as Ctrl+A, Ctrl+O, so that the keyboard being debugged can get the first chance to look at them and handle them if it wishes.
If the keyboard does not handle the keystroke, then a set of editor shortcut keys will be handled by the debugger, namely:
* Ctrl+A - select all
* Ctrl+C - copy
* Ctrl+V - paste
* Ctrl+X - cut
* Ctrl+Z - undo
Note that undo semantics are a little weird with the debugger, but that is not related to this fix. By a little weird, I mean that characters emitted by the keyboard being debugged do not flow into the undo buffer, so undo often has no effect. I am not planning to fix this idiosyncrasy at this time.
All these tests should be performed in the debugger.
* **TEST_BASELINE:** Make …

fix(developer): handle shortcut keys in debugger

---

android/KMEA/app/src/main/res/layout/list_row_layout3.xml

Fixes #5876 
This updates list_row_layout3 to truncate the keyboard language name so it doesn't collide with the help icon.
Setup:
Load the PR build in an Android emulator with a small/medium screen (e.g. Nexus 5 with Android API 23)
* **TEST_KEYBOARD_PICKER**
1. Start Keyman for Android
3. From the "Settings" menu, search and install the "khmer_angkor" keyboard
4. Proceed through the installation wizard until khmer_angkor is installed
5. In the Keyman app, long-press on the globe key to display the keyboard picker
6. Verify the language name does not collide with the help icon

fix(android/engine): Truncate language name in list

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java

Fixes #5848 and will need to 🍒 pick to stable-14.0
This checks that the downloaded kmp file exists before attempting to extract it.
---
**Note for reviewers, this contains test code in https://github.com/keymanapp/keyman/commit/6fb6238ea9f772bf6f5742a8bc8a1ac51f1472d6 
After user testing, I will revert the test code before merging to production**
---
Note: This will only pass while the test code above is in.
* **TEST_KMP_EXISTS** - Checks kmp file exists before PackageActivity() attempts to extract it
2. From the "Settings" menu, search for the "basic_kbdsora" keyboard and download to install
3. Verify a Toast notification briefly appears saying "Failed to extract" (The kmp file no longer exists, so the PackageActivity finishes)

fix(android/app): Check KMP file exists before attempting to extract

---

web/source/dom/domManager.ts

Fixes #5873 by checking that `parentElement` isn't `null` before assigning.
Follows the pattern from 
https://github.com/keymanapp/keyman/blob/ce7a08f30fecdf29ef216da598ae2f11f629d487/web/source/dom/domManager.ts#L1728
* **TEST_MOBILE_VIEW**
Uses Chrome in mobile viewport with the developer console (F12)
1. Load the web/testing/prediction-ui/index.html test page
2. Click on the area from the screenshot below
3. Verify no console errors appear
r

fix(web): Check parent element is defined before assigning

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java

Reverts test code from #5849 that inadvertently got merged to master.

fix(android/app): Revert test code

---

windows/src/global/delphi/comp/OnScreenKeyboard.pas

Fixes #5609.
If a user attempted to export the OSK to a BMP or PNG, and their base keyboard was a European layout (102 key), then Keyman Developer would crash as it attempted to recalculate and redraw the keyboard when constructing the OSK object, and there would be no window for the OSK object to draw to (or measure dimensions against).
This fix uses a temporary off-screen canvas to facilitate calculation of dimensions, and avoids drawing or invalidating if no window is available.
To export an OSK, load or create a keyboard with an OSK in Keyman Developer. On the OSK tab, click Export, select file type .png, and enter a filename.
* TEST_US: With a US English base keyboard selected, export the OSK in Keyman Developer to a .png file. Ensure that the file is exported and Developer doesn't …

fix(developer): crash exporting OSK on European keyboard

---

common/schemas/kps/README.md
common/schemas/kps/kps.xsd
windows/src/developer/TIKE/Makefile
windows/src/developer/TIKE/Tike.dpr
windows/src/developer/TIKE/Tike.dproj
windows/src/developer/TIKE/project/Keyman.Developer.System.Project.kpsProjectFileAction.pas
windows/src/developer/inst/kmdev.wxs
windows/src/developer/kmcomp/kccompilepackage.pas
windows/src/developer/kmcomp/kmcomp.dpr
windows/src/developer/kmcomp/kmcomp.dproj
windows/src/developer/kmcomp/main.pas
windows/src/global/delphi/general/Keyman.Developer.System.ValidateKpsFile.pas
windows/src/test/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dpr
windows/src/test/unit-tests/keyboard-package-versions/KeyboardPackageVersionsTestSuite.dproj

Fixes #5464.
The keyboards repository already has code to validate .xsd files, using xmllint. This adds the same functionality directly into kmcomp and TIKE.
* TEST_SCHEMA: Verify that existing .kps files compile correctly -- choose at random!
* TEST_DODGY_SCHEMA: Manually edit a .kps file in a text editor to introduce an unsupported XML element, for example, add a `<Foo />` element somewhere. The compile of this file should fail with a "helpful" error message.

feat(developer): validate .kps files during compile

---

web/source/keyboards/kmwkeyboards.ts

Relates to #5904.
If a call to api.keyman.com takes longer than 10 seconds, the timerid would no longer be valid, even if the call returns successfully. This threw a cascade of errors.
There was a secondary issue where keymanweb.com was passing in an invalid timerid, causing the same error cascade. This is fixed in keymanapp/keymanweb.com#38.
We'll do user testing on keymanapp/keymanweb.com#38 when it merges. This particular PR is not particularly easy to user-test, although you could force it with a breakpoint and delay in KeymanWeb unminified test page if you were really keen.

fix(web): avoid error if timerid not valid

---

web/source/kmwembedded.ts
web/source/osk/visualKeyboard.ts
web/source/resources/osk/kmwosk.css

Fixes #5831.
Cherry-pick of #5915.
iOS 15 has a significant crashing bug whereby use of a canvas element completely crashes the browser in some contexts. In particular, we have observed this when using a WKWebView in a keyboard extension without 'Allow Full Access' switched on.
Keyman uses canvas element to draw a nice looking key preview (key tip) on iPhones. This is a critical issue for Keyman for iPhone. Keyman for iPad is not affected because the iPad version does not use key previews.
The resolution here is to remove use of the canvas drawing for key tips and use a simplified pure HTML/CSS shape. I have not conditioned this fix on platform; I have currently opted to apply this to all platforms.
This fix will be backported to Keyman 14.0-stable.
This issue will be reported to Apple …

fix(web): remove canvas use for iOS compatibility 🍒

---

web/source/osk/browser/keytip.ts
web/source/resources/osk/kmwosk.css

Fixes #5831.
iOS 15 has a significant crashing bug whereby use of a canvas element completely crashes the browser in some contexts. In particular, we have observed this when using a WKWebView in a keyboard extension without 'Allow Full Access' switched on.
Keyman uses canvas element to draw a nice looking key preview (key tip) on iPhones. This is a critical issue for Keyman for iPhone. Keyman for iPad is not affected because the iPad version does not use key previews.
The resolution here is to remove use of the canvas drawing for key tips and use a simplified pure HTML/CSS shape. I have not conditioned this fix on platform; I have currently opted to apply this to all platforms.
This fix will be backported to Keyman 14.0-stable.
This issue will be reported to Apple for resolution. The …

fix(web): remove canvas use for iOS compatibility

---

mac/Cartfile.private
mac/Cartfile.resolved
mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj
mac/build.sh

@keymanapp-test-bot skip﻿
This allows us to build Keyman for macOS on an M1

fix(mac): use xcframework to support m1

---

windows/src/developer/TIKE/xml/kmw/index.html
windows/src/developer/TIKE/xml/kmw/test.css

Fixes #5926.
This gives space for the popups to appear, even if they are large.

fix(developer): move web osk beneath text area

---

web/source/osk/oskView.ts

Fixes #5907.
The state machine for the Hide transition for the OSK was very complex, and had some peculiarities which caused it to sometimes fail to correctly hide. Once I simplified the state machine, it seems that those edge cases have gone away, and the keyboard always hides correctly.
Note: There is an unrelated issue with focus timeout which can be confusing when testing this; see #5909. **To avoid this:** wait at least one second before clicking outside a text box.
* GROUP_DESKTOP: run this test in Chrome on Windows.
* GROUP_TOUCH: run this test on iOS or Android device.
* TEST_KEYBOARD: in the unminified test page, repeatedly switch between controls and ensure that the OSK shows and hides exactly as expected. Try clicking elsewhere in the document to hide the keyboard. Once the …

fix(web): simplify hide transition

---

web/source/osk/browser/keytip.ts

Fixes #5935.
Takes parent element's position into account when calculating keytip location.
I don't think this warrants a separate user test.

fix(web): inline osk keytip position

---

linux/ibus-keyman/tests/ibusimcontext.c
linux/ibus-keyman/tests/ibusimcontext.h

This change removes the pre-edit related test methods since we don't use the pre-edit option.

chore(linux): Remove unused test methods 🎫

---

web/source/dom/domEventHandlers.ts
web/source/dom/domManager.ts
web/testing/index.html
web/testing/scrolling/index.html

Fixes #5313.
This is a reasonably straightforward fix, for once!
* TEST_SCROLL: In the KeymanWeb testing/scrolling/ test page, on an iPhone or Android phone (simulator / chrome emulator acceptable), test that scrolling the input area using your finger works acceptably, multiple times.

fix(web): reset scroll anchor on touchend

---

web/source/osk/browser/pendingLongpress.ts
web/source/osk/visualKeyboard.ts

Fixes #5950.
If a user starts a longpress gesture and then flicks up, that immediately brings up the longpress menu, and the timeout for display of the menu should be cancelled -- otherwise the end result is a key that stays 'stuck' on.
1. Test longpress menus in a keyboard such as sil_euro_latin, both by waiting for the menu to appear, and also by flicking up.
2. Try various combinations to get it to leave a highlighted key.
3. These tests pass if no key is ever left highlighted after ending the touch gesture.
* TEST_IOS: Run the test above in Keyman for iOS (system and/or in-app keyboard).
* TEST_ANDROID: Run the test above in Keyman for Android (system and/or in-app keyboard).
* TEST_WEB: Run the test above in KeymanWeb (testing/unminified), on a mobile device or emulating in Chrome.

fix(web): clear longpress timeout if user does a flick up

---

web/source/osk/visualKeyboard.ts

Fixes #5912.
Corresponds loosely to #5949.
* TEST_ANDROID: Verify that popup keys work correctly on Keyman for Android. Try various ways of using them and sliding on/off them
* TEST_IOS: Verify that popup keys work correctly on Keyman for iPhone and iPad. Try various ways of using them and sliding on/off them
* TEST_WEB: Verify that popup keys work correctly on KeymanWeb in touch mode (Chrome emulation okay). Try various ways of using them and sliding on/off them. Use the testing/unminified page.

fix(web): popupBaseKey null check

---

windows/src/engine/keyman32/keyboardoptions.cpp
windows/src/engine/keyman32/keyboardoptions.h

Fixes #5951 
LoadKeyboardOptionsCore no longer frees the memory that has not been allocated.
**TEST_KEYBOARDOPTIONS_CHANGE**:  make sure changing the default keyboard options don't cause a crash.
This test requires IPA (SIL) keyboard to be installed (or a keyboard that has modifiable keyboard options).
Step 1. Go to `Keyman Configuration`, select the IPA (SIL) keyboard, click on `Keyboard options` and choose `Before`. You may need to exit Keyman configuration before the default behaviour changes.  
Step 2. Open Notepad, start typing anything and notepad should NOT crash.
Note: `Before` `After` setting. This will change the sequence to produce the IPA character for example `>b` => `ɓ`  for before and if the setting is after it is `b>` => `ɓ`

fix(windows): fix loadkeyboardoptions core memory error

---

web/source/osk/uiTouchHandlerBase.ts

Fixes #5912.
Corresponds loosely to #5948.
The variable `popupBaseTarget` is never set. Removing.
* TEST_ANDROID: Verify that popup keys work correctly on Keyman for Android. Try various ways of using them and sliding on/off them
* TEST_IOS: Verify that popup keys work correctly on Keyman for iPhone and iPad. Try various ways of using them and sliding on/off them
* TEST_WEB: Verify that popup keys work correctly on KeymanWeb in touch mode (Chrome emulation okay). Try various ways of using them and sliding on/off them. Use the testing/unminified page.

fix(web): remove obsolete popupBaseTarget

---

android/KMEA/app/src/main/assets/keyboard.html
web/source/osk/oskView.ts
web/source/text/prediction/modelManager.ts

Summary of these changes:
Two targeted improvements; more optimization is possible but IMO this is a significant enough improvement to go through test:
1. In oskView.ts, avoid calling `VisualKeyboard.refreshLayout` twice from `OSKView.refreshLayout`. This roughly halves the time spent in `VisualKeyboard.refreshLayout` for a keyboard switch.
2. In modelManager.ts, we avoid a very expensive `unloadModel` / `loadModel` sequence from `registerModel` by checking to see if the model spec we are passed is already registered. This avoids an expensive callback to Keyman for Android which causes the banner to 'bounce'.
Longer notes:
So `VisualKeyboard.refreshLayout` is called 20+ times during a keyboard switch. It is a very expensive call. It is the bulk of the time spent when you press the globe …

fix(web): improve keyboard switch performance

---

windows/src/developer/TIKE/xml/kmw/index.html
windows/src/developer/TIKE/xml/kmw/test.css
windows/src/developer/TIKE/xml/kmw/test.js

Fixes #5905.
Touch devices now use a touch keyboard only in the web debugger; desktop browsers continue to present the option to switch between device types. Given the limited real estate on phones, and the trickiness of navigating a mouse-oriented environment with fingers, I've opted not to allow users to test desktop keyboard OSKs on touch devices.
* TEST_DEBUGGER_DESKTOP: Load the web debugger in Chrome and verify that each of the OSK device modes render correctly.
* TEST_DEBUGGER_MOBILE: Load the web debugger on a mobile device (or in emulation in Chrome) and verify that the only OSK presented is the touch mobile one, at the bottom of the screen.

fix(developer): render OSK nicely on touch devices

---

windows/src/developer/kmdecomp/kmdecomp.vcxproj
windows/src/developer/kmdecomp/savekeyboard.cpp

Picked up in development of #5963.
Replaces #5969 (wrong base)

fix(developer): kmdecomp string overflow

---

web/source/dom/domEventHandlers.ts

Relates to #5947.
I resolved a merge conflict in #5947 in the wrong direction and accidentally deleted the `dragEnd` function. This restores it.

fix(web): restore `dragEnd` function 🔥

---

windows/src/developer/TIKE/child/UfrmKeymanWizard.dfm

Relates to https://community.software.sil.org/t/why-does-the-details-tab-in-keyman-developer-still-refer-to-keyman-10/5612/3

chore(developer): tweak language metadata message

---

linux/Makefile

The test targets got added on the `master` branch and the TC configuration adjusted so that PR builds run the tests. This change
adds these targets (but without running ibus-keyman tests) to the stable branch, so that TC builds for PRs will work.

fix(linux): Add test targets to Makefile 🎫

---

common/core/desktop/tests/unit/kmx/041 - long context and deadkeys.kmn
common/core/desktop/tests/unit/kmx/042 - long context and split deadkeys.kmn
linux/ibus-keyman/tests/testfixture.cpp

Previously we overwrote our test data, so we basically ran the same test repeatedly under different names.
Properly running them showed some failures which this change also fixes or skips.
Part of #5613.

fix(linux): Fix ibus-keyman integration tests 🎫

---

android/KMEA/app/src/main/AndroidManifest.xml
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
android/KMEA/app/src/main/res/layout/ime_list_layout.xml
android/KMEA/app/src/main/res/layout/keyboard_picker_list_layout.xml
android/KMEA/app/src/main/res/layout/list_row_layout5.xml
android/KMEA/app/src/main/res/values-land/dimens.xml
android/KMEA/app/src/main/res/values/dimens.xml
android/KMEA/app/src/main/res/values/strings.xml

Fixes #5834 by making the following changes to the Keyman system keyboard "keyboard picker" menu (no change to the in-app keyboard picker):
* Allows other system IME's to be selected
* Remove the "Close Keyman" button previously used to switch to other IME
Screenshot from system keyboard "Keyboard Picker" menu
Note on the screenshot: "Google" refers to Google's voice-activated keyboard, which is separate from "Gboard".
Note, due to how Android 11 handles privacy, this PR also adds the permission to query for other IME's in the AndroidManifest.xml.
Reference: https://developer.android.com/training/package-visibility/declaring#intent-filter-signature
Setup:
1. Install test build of Keyman on Android 11 device (actual device preferable)
2. In Keyman, install sil_cameroon_qwerty keyboard for …

feat(android/engine): Add other IME's to the Keyboard Picker menu

---

android/README.md
android/Samples/KMSample2/app/build.gradle
oem/firstvoices/android/app/build.gradle

While Android Studio Gradle plugin should automatically use a default version of build tools, we can specify it:
https://developer.android.com/studio/releases/build-tools
Attempting to resolve lint exceptions on the build agent.

chore(android): Specify build tools version on other projects

---

windows/src/developer/TIKE/debug/debugkeyboard.pas

As the array length properties are unsigned integers, taking -1 from them resulted in an integer overflow when the array was empty. A gotcha with Delphi-style for loops!

fix(developer): debugger crash with empty group

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

Fixes #5914 
During the 14.0 refactoring of keyboard info (keyboard controller, Keyboard data object), the font info already contains the full paths to the .ttf files.
This fixes the font paths in KMKeyboard.
Setup: Install on Android emulator with SDK 21
* **TEST_FONT_PATHS** - Verifies font is applied for OSK keys and subkeys
1. Load the PR build of Keyman
2. Launch Keyman and exit the "Get Started" menu
3. Verify the keys and subkeys for the default sil_euro_latin keyboard are correct
3. From the "Settings" menu, install keyboards that use a TTF font. For example
a. Test [U_xxxx_yyyy](https://darcywong00.github.io/examples/u2858/u_xxxx_yyyy_2858.kmp) keyboard 
b. khmer_angkor (this verifies font is applied in reported issue #5985)
4. After the keyboard installs, verify the OSK is …

fix(android/engine): Fix font paths

---

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java

🍒 pick of #5987 to stable-14.0
This fixes the font paths since they already contain the full path.
Setup: Install on Android emulator with SDK 21
* **TEST_FONT_PATHS** - Verifies font is applied for OSK keys and subkeys
1. Load the PR build of Keyman
2. Launch Keyman and exit the "Get Started" menu
3. Verify the keys and subkeys for the default sil_euro_latin keyboard are correct
4. Note how the sil_euro_latin OSK is rendered (for comparison later)
5. From the "Settings" menu, install keyboards that use a TTF font. For example
a. sil_cameroon_qwerty (Not using test U_xxxx_yyyy keyboard because 14.0 will crash trying to render those subkeys)
b. khmer_angkor (this verifies font is applied in reported issue bug(android): the base keys and the subkeys are in different font face #5985)
6. …

fix(android/engine): Fix font paths 🍒 
