linux/ibus-keyman/debian/rules, linux/ibus-kmfl/debian/rules, linux/kmflcomp/debian/rules, linux/libkmfl/debian/rules
Lintian complained "missing-build-dependency-for-dh-addon" which I'm not entirely sure is correct. However, there is an easy
workaround by removing an unnecessary parameter.
=> chore(linux): Remove lintian warning

windows/src/developer/kmcomp/Keyman.Developer.System.Project.ProjectLogConsole.pas, windows/src/developer/kmcomp/main.pas
Picked up during #5963 development.
If you ran `kmcomp <file.kmn> <out.js>`, compiler messages were passed to a function with an incorrect signature, resulting in an exception. This was a mode that was not widely used, which is why we haven't picked it up earlier.
=> fix(developer): building kmw keyboard had wrong message callback signature

windows/src/developer/TIKE/help/kwhelp.pas, windows/src/developer/TIKE/xml/app/editor/language.keyman.js
Relates to #3621.
Adds `&layoutChanged`, `begin newcontext`, `begin postkeystroke` support to IDE editor and keyword help.
=> feat(developer): support for start-of-sentence in IDE 🍆

common/core/desktop/src/kmx/kmx_context.h, windows/src/engine/keyman32/appint/appint.h
Add more description to Buf method. As its behaviour was not correctly documented 
Also updated the doxy to remove the brief tag.
Made mirror change to appint.h
=> chore(common): add more description to Buf method

linux/scripts/debian.sh
This change allows to specify the debian revision when creating source packages for Debian.
=> chore(linux): Allow to specify debian revision

linux/scripts/debian.sh
This change allows to specify the debian revision when creating source packages for Debian.
:cherries:-pick from #5998.
=> chore(linux): Allow to specify debian revision :package:  :cherries: 

linux/legacy/ibus-kmfl/debian/rules, linux/legacy/kmflcomp/debian/rules, linux/legacy/libkmfl/debian/rules
Lintian complained "missing-build-dependency-for-dh-addon" which I'm not entirely sure is correct. However, there is an easy
workaround by removing an unnecessary parameter.
:cherries:-pick of #5993.
=> chore(linux): Remove lintian warning :package:  :cherries: 

common/core/desktop/src/kmx/kmx_context.h, windows/src/engine/keyman32/appint/appint.h
remove comment about it splitting surrogate pairs and
deadkeys
This address a review comment that was made after the PR was already merged.
=> chore(common): buf now uses decxstr so remove comment

windows/src/Defines.mak, windows/src/engine/keyman/Makefile, windows/src/engine/keymanx64/Makefile, windows/src/test/unit-tests/compile-supplementary-support/Makefile
Merges into #6020.
Removes one more dependency on Delphi tools
=> chore(windows): use findstr instead of Borland grep ✈

docs/build/windows.md, windows/src/Defines.mak, windows/src/Makefile, windows/src/README.md, windows/src/buildtools/Makefile, windows/src/desktop/Makefile, windows/src/developer/Makefile, windows/src/engine/Makefile, windows/src/ext/Makefile, windows/src/global/Makefile, windows/src/support/Makefile, windows/src/test/Makefile
This makes it possible to run `set NODELPHI=1`, `nmake build` and then only non-Delphi projects will be built.
=> chore(windows): build without delphi ✈

windows/src/global/delphi/comp/OnScreenKeyboard.pas
The build was failing due to unused variable error.
=> fix(windows): remove unused variable

linux/ibus-keyman/tests/testfixture.cpp
This change will hopefully help some tests that occasionally fail on TC. After setting the options during the test setup we sync the
settings before running the test scenario.
@keymanapp-test-bot skip because this change affects tests only.
=> fix(linux): Improve ibus-keyman tests

linux/help/common/index.md
=> docs(linux): Document how to disable error reporting

linux/keyman-config/keyman_config/__init__.py
=> fix(linux): fix release version number for Sentry reporting

windows/src/developer/TIKE/xml/kmw/test.js
Emerges from ELTW demos.
Remembers the user's selected model and device when they refresh the page.
* **TEST_MODEL_MEMORY:** Load a model in the web keyboard debugger in Developer. Switch the model on, and press F5 to refresh the page. Verify that the model is still selected. (Do this a couple of times with model selected or off.)
* **TEST_DEVICE_MEMORY:** Switch between various devices in the device picker. Verify that the device stays selected after you refresh the page.
=> feat(developer): remember test page preferences on reload 🛒

windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.Debugger.pas, windows/src/developer/TIKE/xml/kmw/packages.js, windows/src/developer/TIKE/xml/kmw/test.js
Merges into #6033.
Adds polling for changes to keyboards or models under test in the web debugger. When changes are detected, the keyboards and/or models are instantly reloaded automatically.
* **TEST_WEB_DEBUGGER:** Follow the steps below
1. Check interactions in the web debugger continue to work as before.
2. Verify that making changes to the keyboard and recompiling (F7) cause the keyboard to reload automatically. (You can probably observe these most easily by changing the OSK or touch keyboard)
3. Verify that making changes to a lexical model and recompiling (F7) cause the model to reload automatically.
(You can probably observe these most easily by changing the most frequent word offered)
4. Make sure that the keyboard and model selection is correct with reloads.
=> feat(developer): live reload of web debugger 🛒

windows/src/developer/TIKE/Tike.dpr, windows/src/developer/TIKE/actions/dmActionsMain.dfm, windows/src/developer/TIKE/actions/dmActionsMain.pas, windows/src/developer/TIKE/http/Keyman.Developer.System.HttpServer.Debugger.pas, windows/src/developer/TIKE/web/UmodWebHttpServer.pas, windows/src/global/delphi/general/KeyboardFonts.pas
Merges into #6035.
Keyman Developer now remembers the 10 most recently debugged keyboards, models and packages in the web debugger, across sessions. It determines the recency of use by the last access time of the object, and caches at most 10 of each type of object when the IDE session ends.
The cache data is stored in %appdata%\Keyman\Keyman Developer\WebDebugCache.json.
The web debugger is now always available when Keyman Developer is running, even if the user has not yet clicked 'Start Web Debugging', as otherwise cached web debug objects would not be immediately available.
Keyman Developer will verify that files listed in the cache are still available, and will remove them on startup if the file disappears.
* **TEST_CACHING:** Load a keyboard in the web debugger, close and restart …
=> feat(developer): cache web debug objects across sessions 🛒

windows/src/desktop/help/start/download-and-install-keyboard.md
If the computer has split user/admin accounts, then language association may not be completed automatically, and the user may need to add a language association themselves.
Ref https://community.software.sil.org/t/what-security-permissions-are-needed-to-install-a-keyboard-configuration-in-keyman/5695/10
Note: the topic `configure-computer` has a terrible url but I won't fix that here. Suggested future fix -- turn `configure-computer` into a redirect to `link-keyboard-to-language` or `associate-keyboard-with-language`?
=> docs(windows): Add note on split user/admin accounts

mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m
Increases the size of character labels in the Keyman for Mac onscreen keyboard by 50% (from using 0.3 of the key height to 0.45 of the key height). The font size for labels on modifier and special keys remains as is. Fixes #5600 
* TEST_MAC: load keyboards for a variety of languages and view the OSK for each to verify that characters fit cleanly within the bounds of the key
=> fix(mac): increase OSK character size by 50%

developer/js/.npmignore, developer/js/bundle.sh, windows/src/developer/inst/download.in
Relates to https://github.com/npm/cli/issues/2921
This issue arises after moving from npm 6.x to 7.x or later. As the build agents are still on 6.x, we have not yet seen this issue there.
As part of the release build for Keyman Developer, we bundle up some files and do some work in a temp folder to prepare folders for release. Even though we are only working with `dependencies` (e.g. using `npm install --production`), packages under `devDependencies` are still wrongly being checked by NPM. As we have two modules present in `devDependencies` that are only available when in the repo path, we need to remove them before attempting to continue. Yuck!
ref: https://github.com/npm/cli/issues/3975#issuecomment-985305678
ref: https://github.com/npm/cli/issues/2921
=> fix(developer): work around devDependencies bug in npm

android/KMAPro/kMAPro/src/main/res/values-b+es+419/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java, android/KMEA/app/src/main/res/values-b+es+419/strings.xml, crowdin.yml, ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/es-419.lproj/ResourceInfoView.strings, ios/engine/KMEI/KeymanEngine/es-419.lproj/Localizable.strings, ios/engine/KMEI/KeymanEngine/es-419.lproj/Localizable.stringsdict, ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj, ios/keyman/Keyman/Keyman/es-419.lproj/Localizable.strings, linux/keyman-config/locale/es_419.po, windows/src/desktop/kmshell/locale/es-419/strings.xml, windows/src/desktop/setup/locale/es-419/strings.xml
🍒 -pick of #5269 to stable-14.0
Translators Without Borders requested the Spanish (Latin America) localization be released in 14.0 for their users.
As with the original PR, this won't include macOS localization.
Load the PR builds
Verify the Spanish (Latin America) strings can be displayed
1. Use Android emulator for SDK 29
* **TEST_IOS**
1. start Keyman configuration with: LANGUAGE=es_419 km-config
=> chore(common): Check in crowdin strings for Spanish (Latin America) 🍒 

android/KMEA/app/src/main/res/values-am-rET/strings.xml, ios/engine/KMEI/KeymanEngine/am.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/am.lproj/KMAboutWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/am.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/am.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/am.lproj/KMKeyboardHelpWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/am.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/am.lproj/MainMenu.strings
This adds Amharic localization for macOS.
Also updates Amharic strings for Android and iOS.
Only testing macOS platform, since other platforms are just updating strings
* **TEST_MAC** - Tests Amharic localization on Keyman for macOS
1. Load the macOS PR build
2. Set the system language to Amharic
3. Launch Keyman for macOS
4. Verify strings are in Amharic.
=> chore(common): Update crowdin strings for Amharic 📜

linux/keyman-config/keyman_config/__init__.py
Forgot to change the second occurrence of the version number for older Sentry SDK.
:cherries:-pick of #6068.
=> fix(linux): fix release version number for Sentry reporting :cherries: 

android/Samples/KMSample2/build.sh
Fixes #6075 and follow-on to #603
#603 added a `-no-daemon` build flag for the sample projects to build on CI, but KMSample2/build.sh inadvertently wasn't updated.
This PR updates KMSample2 so hopefully will stop the CI from hanging.
Will need to 🍒-pick to stable-14.0
* TEST_KMSAMPLE2 - Tests KMSample2 project still runs
1. Load the test build and launch KMSample2
2. Using the menus, set KMSample2 as a system IME
3. Launch a separate app (e.g. Chrome) and select a text field to type
4. When KMSample2 is the selected IME, verify it can type
=> chore(android/samples): Add -no-daemon flag to KMSample2 build script

android/Samples/KMSample2/build.sh
🍒 pick of #6082 to stable-14.0
This PR updates KMSample2 so hopefully will stop the CI from hanging.
* TEST_KMSAMPLE2 - Tests KMSample2 project still runs
1. Load the test build and launch KMSample2
2. Using the menus, set KMSample2 as a system IME
3. Launch a separate app (e.g. Chrome) and select a text field to type
4. When KMSample2 is the selected IME, verify it can type
=> chore(android/samples): Add -no-daemon flag to KMSample2 build script 🍒 

linux/keyman-config/Makefile, linux/keyman-config/README.md, linux/keyman-config/keyman_config/gnome_keyboards_util.py, linux/keyman-config/keyman_config/gsettings.py, linux/keyman-config/keyman_config/ibus_util.py, linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/uninstall_kmp.py, linux/keyman-config/tests/test_gnome_keyboards_util.py, linux/keyman-config/tests/test_gsettings.py, linux/keyman-config/tests/test_ibus_util.py
This change fixes the installation of shared packages, so that they show up in the list of the installed keyboards.
Fixes #5311.
- Install a keyboard to the shared area using the command line (e.g. `sudo km-package-install -s -p isis_bangla`). Check that the new keyboard appears in the dropdown with installed keyboards:
**TEST_INSTALL_PKG_GNOME:** Use a Linux version that uses Gnome (e.g. Ubuntu).
**TEST_INSTALL_PKG_IBUS:** same test on Wasta Linux
- Uninstall the keyboard installed above with `sudo km-package-uninstall -s isis_bangla`. This should remove the keyboard from the dropdown.
**TEST_UNINSTALL_PKG_GNOME:**  Use a Linux version that uses Gnome (e.g. Ubuntu).
**TEST_UNINSTALL_PKG_IBUS:** same test on Wasta Linux
- Similar to the previous tests, but with a .kmp file already …
=> fix(linux): Fix installation of shared packages

linux/keyman-config/keyman_config/convertico.py, linux/keyman-config/keyman_config/handle_install.py, linux/keyman-config/keyman_config/kmpmetadata.py, linux/keyman-config/keyman_config/kvk2ldml.py
We don't want to send events to Sentry for errors that we handled.
=> feat(linux): Don't create Sentry events for errors

linux/keyman-config/keyman_config/get_kmp.py
Newer versions of requests-cache (>= 0.6) restructure some code so that the _core_ namespace is no longer available. However, it turns out that we don't need to specify that namespace at all, so this change will work with both older and newer versions of
`requests-cache`.
This will fix #6085.
**TEST_OLD**: install a keyboard while `python3-requests-cache` package is installed (<0.6)
- open a terminal window
- start Keyman Configuration by typing `km-config`
- install any keyboard
- verify that the command line didn't print a line similar to `AttributeError: module 'requests_cache' has no attribute 'core'`   during the installation of the keyboard
- verify that the keyboard gets properly installed
**TEST_NEW**: install a keyboard with a newer requests-cache version
- open a terminal window …
=> fix(linux): Fix attribute error

linux/keyman-config/keyman_config/get_kmp.py
Newer versions of requests-cache (>= 0.6) restructure some code so that the _core_ namespace is no longer available. However, it turns out that we don't need to specify that namespace at all, so this change will work with both older and newer versions of
`requests-cache`.
This will fix #6085.
:cherries:-pick from #6086.
**TEST_OLD**: install a keyboard while `python3-requests-cache` package is installed (<0.6)
- open a terminal window
- start Keyman Configuration by typing `km-config`
- install any keyboard
- verify that the command line didn't print a line similar to `AttributeError: module 'requests_cache' has no attribute 'core'`   during the installation of the keyboard
- verify that the keyboard gets properly installed
**TEST_NEW**: install a keyboard with a newer requests-cache …
=> fix(linux): Fix attribute error :cherries: 

developer/js/bundle.sh
Fixes a build failure after #6074 was merged. The final grep statement in the line
cat package.json | grep -v "@keymanapp/models-templates" | grep -v "@keymanapp/models-wordbreakers" > package.json
would fail to find anything to exclude, and return an error value, so the script would fail, as we use `set -e`. We didn't care that it didn't find anything to exclude... so we will ignore the return value.
=> fix(developer): bundle.sh must succeed

linux/debian/control
This is a follow-up for #5325.
=> fix(linux): Update minimum sentry-sdk version

android/KMAPro/kMAPro/src/main/res/values-mrt-rNG/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java, android/KMEA/app/src/main/res/values-mrt-rNG/strings.xml, ios/engine/KMEI/KeymanEngine/Classes/mrt.lproj/ResourceInfoView.strings, ios/engine/KMEI/KeymanEngine/mrt.lproj/Localizable.strings, ios/engine/KMEI/KeymanEngine/mrt.lproj/Localizable.stringsdict, ios/keyman/Keyman/Keyman/mrt.lproj/Localizable.strings, linux/keyman-config/locale/mrt_NG.po, windows/src/desktop/kmshell/locale/mrt-NG/strings.xml, windows/src/desktop/setup/locale/mrt-NG/strings.xml
This checks in the crowdin strings for the locale `mrt` for Marghi. Does not include macOS.
For the listed platforms:
2. Set the UI/locale to Marghi
3. Verify the UI is Marghi
Note: The crowdin translator left some strings in English, so that's out of our control
1. Verify Marghi strings are like the screenshot
* **TEST_IOS** - Wait until Shawn addresses the XCode TODO before testing
1. start Keyman configuration with: `LANGUAGE=mrt_NG km-config`
=> chore(common): Check in crowdin strings for Marghi 📜

android/KMAPro/kMAPro/src/main/res/values-hia-rNG/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java, android/KMEA/app/src/main/res/values-hia-rNG/strings.xml, ios/engine/KMEI/KeymanEngine/Classes/hia.lproj/ResourceInfoView.strings, ios/engine/KMEI/KeymanEngine/hia.lproj/Localizable.strings, ios/engine/KMEI/KeymanEngine/hia.lproj/Localizable.stringsdict, ios/keyman/Keyman/Keyman/hia.lproj/Localizable.strings, linux/keyman-config/locale/hia_NG.po, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/hia.lproj/KMAboutWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/hia.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/hia.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/hia.lproj/KMKeyboardHelpWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/hia.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/hia.lproj/MainMenu.strings, windows/src/desktop/kmshell/locale/hia-NG/strings.xml, windows/src/desktop/setup/locale/hia-NG/strings.xml
This checks in the crowdin strings for the locale `hia` for Waha
For the listed platforms:
2. Set the UI/locale to Waha
3. Verify the UI is Waha
Note: The crowdin translator left some strings in English, so that's out of our control
1. Verify Waha strings are like the screenshot
* **TEST_IOS** - Wait until Shawn addresses the XCode TODO before testing
1. start Keyman configuration with: `LANGUAGE=hia_NG km-config`
* **TEST_MAC**
=> chore(common): Check in crowdin strings for Waha 📜

common/core/web/input-processor/src/text/prediction/languageProcessor.ts, web/source/osk/banner.ts
Relates to #3621.
Merges into #5963.
Ensures that the `begin postKeystroke` entry point is called when the user accepts a suggestion.
We'll do testing separately later on this.
=> fix(web): call postKeystroke on banner touch 🕊

android/KMAPro/kMAPro/src/main/res/values-ckl-rNG/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java, android/KMEA/app/src/main/res/values-ckl-rNG/strings.xml, ios/engine/KMEI/KeymanEngine/Classes/ckl.lproj/ResourceInfoView.strings, ios/engine/KMEI/KeymanEngine/ckl.lproj/Localizable.strings, ios/engine/KMEI/KeymanEngine/ckl.lproj/Localizable.stringsdict, ios/keyman/Keyman/Keyman/ckl.lproj/Localizable.strings, linux/keyman-config/locale/ckl_NG.po, windows/src/desktop/kmshell/locale/ckl-NG/strings.xml, windows/src/desktop/setup/locale/ckl-NG/strings.xml
This checks in the crowdin strings for the locale `ckl` for Kibaku. Does not include macOS.
For the listed platforms:
2. Set the UI/locale to Kibaku
3. Verify the UI is Kibaku
Note: The crowdin translator left some strings in English, so that's out of our control
1. Verify Kibaku strings are like the screenshot
* **TEST_IOS** - Wait until Shawn addresses the XCode TODO before testing
1. start Keyman configuration with: `LANGUAGE=ckl_NG km-config`
1. start Keyman configuration and select UI language 'Nya Nasara'
=> chore(common): Check in crowdin strings for Kibaku 📜

mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/km.lproj/KMAboutWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/en.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/km.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/KMInfoWindowController.m, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/en.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/km.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/km.lproj/KMKeyboardHelpWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/en.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/km.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/km.lproj/MainMenu.strings
fixes #6081
The Package Information window in Keyman for Mac is composed with HTML and could not be localized because label strings were still hard-coded in HTML. This change externalizes the labels so that this window can be included with localization.
I also changed some of the terminology in the related UI for consistency and simplicity:
"Keyboard Layouts" to "Keyboards", in the Configuration tab and within the Package Information window
"Keyboard/Package Info" window title to "Package Information"
Previous naming:
New naming:
=> fix(mac): externalize strings for package info window localization

developer/js/bundle.sh
The previous patch in #6091 was not _quite_ correct. Unfortunately, this code path is not executed when we do a test build, but only on release builds, because we don't want to be publishing to npm for test builds...
=> fix(developer): repatch #6074

android/KMEA/app/src/main/assets/keyboard.html, web/source/kmwembedded.ts
fixes #6089
> A longpress key with reference to a key with Shift+RightAlt in the computer layout does not output anything.
It works just fine though when testing on Chrome emulator.
I initially started porting the changes in #5651 from stable-14.0, but Makara reported seeing the issue in 14.0 too. Thus, portions of this PR will need to be 🍒 picked back to stable-14.0
The complication in kmwembedded.ts comes from parsing `keyName` which contains:
[display layer]-[virtual key name]+[optional function layer] where display layer and function layer can contain multiple `-` delimiters.
For example: 'ctrl-shift' or 'rightalt-shift'
The virtual key name  can also be T_* , K_* , U_*, ~or ISO 9995 format~
In @MakaraSok 's issue, the displayLayer is 'shift' while the functional layer is …
=> fix(web): Use regex to determine display layer and functional layers

docs/build/linux-ubuntu.md, linux/README.md
=> docs(linux): Add missing dependency

windows/src/engine/keyman32/KEYMAN32.DEF, windows/src/engine/keyman32/appint/aiWin2000Unicode.cpp, windows/src/engine/keyman32/globals.h, windows/src/engine/keyman32/k32_globals.cpp, windows/src/engine/keyman32/keyboardoptions.cpp, windows/src/engine/testhost/testhost.cpp
In order to avoid the test host interfering too badly with the debugger, we will bypass SendInput and instead post all input to the local edit window. This can result in out-of-sequence input for rapid typing, but for a test host this is not important -- it's better that the input doesn't end up in the debugger window due to focus changes!
=> feat(windows): handle key output in testhost

windows/src/developer/TIKE/child/UfrmKeymanWizard.pas
Fixes #6149.
**TEST_CLICK:** Verify that the crash from #6149 is resolved.
1. Start Keyman Developer. Select Project/Close Project, and exit Keyman Developer.
2. Start Keyman Developer by double-clicking on a .kmn file.
3. Go to the Build tab, select Test Keyman on web.
=> fix(developer): prevent crash on build dblclicked file

developer/js/.npmignore, developer/js/bundle.sh, windows/src/developer/inst/download.in
=> fix(developer): work around devDependencies bug in npm 🍒

windows/src/developer/TIKE/child/UfrmDebug.dfm, windows/src/developer/TIKE/child/UfrmDebug.pas, windows/src/developer/TIKE/debug/Keyman.System.Debug.DebugCore.pas
If Core fails to load when starting the debugger, avoid a crash and report details of the error back to the user.
=> fix(developer): handle Core failure to load

linux/Jenkinsfile, linux/ibus-keyman/src/engine.c
This allows to use Keyman with the Wayland display server. 
One thing that doesn't yet work completely with this change is caps-lock.
Partially implements #4273.
Use Ubuntu 21.10 Impish with Gnome shell and Wayland
- when login in, click the cog and select "Ubuntu" (not "Ubuntu on Xorg")
- verify that you're using Wayland by running the following command in a terminal:
```
echo $XDG_SESSION_TYPE
```
This should output `wayland`.
**TEST_WAYLAND:** Keyman keyboards work with Wayland
- install any Keyman keyboard
- verify that the keyboard works as expected
**NOTE:** Turning caps-lock on and off doesn't yet work on Wayland (**shiftfreescaps**, **capsononly** and **capsalwaysoff** stores in Keyman).
=> feat(linux): add support for Wayland

mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m
Fixes #6168.
This does not any support for changing any system store values, but does ensure that the statement will be correctly handled when emitting text.
* **TEST_INDONESIAN:** Verify that this resolves the <kbd>.</kbd><kbd>spacebar</kbd> ==> `. "` issue, and that it now generates only `. `.
=> fix(mac): Check for CODE_SETSYSTEMSTORE

mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m
Fixes #6168.
Cherry-pick of #6169.
This does not any support for changing any system store values, but does ensure that the statement will be correctly handled when emitting text.
* **TEST_INDONESIAN:** Verify that this resolves the <kbd>.</kbd><kbd>spacebar</kbd> ==> `. "` issue, and that it now generates only `. `.
=> fix(mac): Check for CODE_SETSYSTEMSTORE 🍒

linux/keyman-config/keyman_config/__init__.py, linux/keyman-config/keyman_config/convertico.py, linux/keyman-config/keyman_config/get_info.py, linux/keyman-config/keyman_config/get_kmp.py, linux/keyman-config/keyman_config/gnome_keyboards_util.py, linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/keyman_config/keyboard_details.py, linux/keyman-config/keyman_config/kmpmetadata.py, linux/keyman-config/keyman_config/kvk2ldml.py, linux/keyman-config/keyman_config/list_installed_kmp.py, linux/keyman-config/km-package-install
Also deal with other file I/O related exceptions and report them as warnings. Also improve general robustness if we encounter a corrupt file.
This fixes #6171.
This will be tested as part of the pre-beta acceptance testing.
=> fix(linux): Don't crash if we lack permissions

linux/keyman-config/keyman_config/gnome_keyboards_util.py, linux/keyman-config/keyman_config/gsettings.py, linux/keyman-config/keyman_config/ibus_util.py, linux/keyman-config/tests/test_gsettings.py, linux/keyman-config/tests/test_ibus_util.py
Fixes #6158.
(this got introduced in #6015).
- **GROUP_IMPISH:** Ubuntu 21.10 Impish with Gnome shell and X11
- **GROUP_WASTA:** Wasta 20.04
**TEST_ADD_KEYBOARD**: install a Keyman keyboard
- install a Keyman keyboard in km-config
- verify that the new Keyboard shows up in the keyboard dropdown
=> fix(linux): Don't crash when installing keyboards in Wasta

oem/firstvoices/keyboards.csv
The OEM FirstVoices apps use keyboards.csv to map the FirstVoices keyboards with their Regions.
The keyboard package fv_all.kmp includes fv_haisla, but keyboards.csv needs an entry added in order for the Haisla keyboard to appear in the Regions list.
Note, the fv_haisla keyboard doesn't have a legacy 9.0 KeymanWeb keyboard (-9.0.js), so I'm just using fv_haisla.js for the entry. The actual value isn't used in 15.0.
1. Load the Android FirstVoices app
2. In "Setup" go to "BC Coast" region
3. Verify "Haisla" is an available keyboard and select it
4. Continue the FV Setup as a System keyboard
5. Launch a separate app (e.g. Chrome) and select a text area to type
6. Select FirstVoices as the system keyboard
7. Verify Haisla keyboard is available to use
* **TEST_IOS**
1. Load …
=> chore(oem/firstvoices): Add fv_haisla keyboard

linux/scripts/cow.sh, linux/scripts/launchpad.sh
We no longer build for Hirsute which is EOL and so no longer available for building on ppa.
=> chore(linux): Remove obsolete Ubuntu 21.04 Hirsute

ios/exportAppStore.plist
The iOS distribution certificate was revoked, so this references the replaced certificate.
=> chore(ios): certificate update again

android/KMAPro/kMAPro/build.gradle, oem/firstvoices/android/app/build.gradle
This is an attempt to address #6216 where the FV Android app failed to publish to the Play Store.
Will see after the next alpha build goes to the Play Store.
Upgrading to 3.6.0+ will involve more pain since those 
> release are only compatible with the Android Gradle Plugin v7.x.
=> chore(android): Update Play publishing plugin to 3.5.0

linux/debian/ibus-keyman.postinst, linux/debian/ibus-keyman.postrm, linux/keyman-config/keyman_config/ibus_util.py
When we try to restart ibus and that fails and ibus isn't running afterwards we directly try to start ibus-daemon.
<details>
<summary>Expand to see user tests</summary>
- install the current alpha version of Keyman
- install a second system keyboard, e.g. French
- install a Keyman keyboard
- verify that the keyboard shows up in the keyboards dropdown
- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome shell and X11
- **GROUP_IMPISH**: Ubuntu 21.10 Impish with Gnome shell and X11
- when login in, click the cog and select "Ubuntu on Xorg"
- once logged in, open a terminal window and verify that running `echo $XDG_SESSION_TYPE`  outputs `x11`.
- **GROUP_IMPISH_WAYLAND**: Ubuntu 21.10 Impish with Gnome shell and Wayland
- when login in, click the cog and select "Ubuntu"
- once logged in, open …
=> feat(linux): Try to start ibus if not running

android/KMAPro/gradle/wrapper/gradle-wrapper.properties, android/KMEA/gradle/wrapper/gradle-wrapper.properties, android/Samples/KMSample1/gradle/wrapper/gradle-wrapper.properties, android/Samples/KMSample2/gradle/wrapper/gradle-wrapper.properties, android/Tests/KeyboardHarness/gradle/wrapper/gradle-wrapper.properties, oem/firstvoices/android/gradle/wrapper/gradle-wrapper.properties
Follow-on to #6217 
Turns out updating the Play store publishing plugin to 3.5.0 also needed a bump in the gradle-wrapper version to 6.8.
Reference
https://github.com/Triple-T/gradle-play-publisher/issues/969#issuecomment-868712031
Fixes the failing alpha build.
=> chore(android): Upgrade gradle-wrapper version to 6.8

windows/src/engine/keyman32/calldll.cpp, windows/src/engine/keyman32/globals.h, windows/src/engine/keyman32/kmhook_getmessage.cpp, windows/src/engine/keyman32/kmprocess.cpp, windows/src/engine/keyman32/kmprocessactions.cpp
Fixes #6205
For the Text Services Frame (TSF) applications in most cases for keystrokes, there is no test parse with updatable=false. In these cases, we need to call the core process event function and process the actions in one call. A bool flag has been added `CoreProcessEventRun` to track if the core process event has been called for the current keystroke. 
In the case of legacy apps or the `OnPreservedKey` for TSF. That is in the case where it is called twice once with `updateable=false` the core process event is called in the first pass and the bool `CoreProcessEventRun` is set. 
This means on any call with `updateable=true` if `CoreProcessEventRun=false` we know we need to call the core processor to process the keystroke. 
The Processing of the core actions will clear …
=> fix(windows): add flag to track core process event

windows/src/desktop/setup/RunTools.pas
Fixes #6221.
Cherry-pick of #6222 (14.0-stable) to 15.0-alpha.
If Keyman is being installed under the SYSTEM profile, e.g. when using
tools such as SCCM or Intune, then the installer runs with a redirected
folder for %LocalAppData%, under C:\Windows\SysWow64\config, but is given
the name C:\Windows\System32\config\....
Keyman Setup then creates %LocalAppData%\Keyman\Diag, which it thinks is in
C:\Windows\System32\config\... But in reality it is in SysWow64\... Keyman
Setup passes a file under this folder to Windows Installer, running as 64
bit, which immediately falls over because the path does not exist to it, in
the real System32\config folder.
This patch disables redirection temporarily just to create the folder under
both 32 and 64 bit versions of the profile. It has no effect on …
=> fix(windows): create Keyman/Diag folder in redirected profile 🍒

android/help/about/whatsnew.md, android/help/basic/switching-between-keyboards.md
Clarifies in-app help on switching keyboards. Similar to keymanapp/help.keyman.com#499
=> chore(android/app): Clarify help on switching keyboards

web/source/osk/oskView.ts
If the OSK had a non-integer width or height stored in the OSK cookie, then the width and height would be parsed incorrectly and the OSK would fail to be sized correctly on first load; this also caused a script error and made the OSK impossible to interact with.
@keymanapp-test-bot skip This would be somewhat difficult to test, involving manual editing of cookies...
=> fix(web): Non-integer OSK sizes

common/models/types/build.sh, developer/js/build.sh
Fixes #6209.
Regression introduced in #6073. Cleanup of tier information in these build scripts accidentally also deleted the setup of npm_dist_tag variable.
=> fix(developer): npm publish with correct tier

resources/devbox/macos/macos.sh
- turn on echoing when we start doing stuff
- it is not too noisy, and tells the user what is really happening
- also, note the script name which added certain lines to ~/.bashrc
- fix appending to the ~/.bashrc
Fixes: #6244
=> feat(common): echo in macos.sh setup script

windows/src/desktop/setup/RunTools.pas
Fixes #6221.
If Keyman is being installed under the SYSTEM profile, e.g. when using tools such as SCCM or Intune, then the installer runs with a redirected folder for %LocalAppData%, under C:\Windows\SysWow64\config, but is given the name C:\Windows\System32\config\....
Keyman Setup then creates %LocalAppData%\Keyman\Diag, which it thinks is in C:\Windows\System32\config\... But in reality it is in SysWow64\... Keyman Setup passes a file under this folder to Windows Installer, running as 64 bit, which immediately falls over because the path does not exist to it, in the real System32\config folder.
This patch disables redirection temporarily just to create the folder under both 32 and 64 bit versions of the profile. It has no effect on normal user accounts (apart from verifying that the …
=> fix(windows): create Keyman/Diag folder in redirected profile

common/core/desktop/src/kmx/kmx_file.h, common/core/desktop/src/kmx/kmx_processevent.cpp, windows/src/engine/keyman32/kmprocess.cpp
Fixes #6204
This change removes the `K_MODIFIERFLAG` from the windows platforms call to the core processor's process_event call.
It then adds a mask for num and scroll lock to the `VKeyToChar` function.
=> fix(common/core/desktop): Add num and scroll lock mask to VKeyToChar

linux/keyman-config/km-package-install
This change will fix a bug with comparing version numbers with more than two sections (e.g. '1.2.3').
Fixes #6182.
- The Linux version doesn't matter for these tests
- Install build artifacts of this PR
- Download and unzip the attached **gff_amharic.kmp** file
- Install the unzipped gff_amharic keyboard in the attached older version:
```bash
cd Downloads # (or wherever you unzipped the .kmp file)
km-package-install -f gff_amharic.kmp
```
- run `km-package-list-installed` and verify that the "GFF Amharic Keyboard" shows up with version 1.9.1 and id `gff_amharic`.
- **TEST_UPDATE**: Update to new version of gff_amharic
- from the command line, run:
```bash
km-package-install -p gff_amharic
```
- verify that this outputs a message saying that a newer version is available and that the old …
=> fix(linux): Properly compare versions in km-package-install

common/core/web/input-processor/src/text/inputProcessor.ts, common/core/web/input-processor/src/text/prediction/languageProcessor.ts, common/core/web/keyboard-processor/src/text/kbdInterface.ts, common/core/web/keyboard-processor/src/text/keyboardProcessor.ts, common/core/web/keyboard-processor/src/text/outputTarget.ts, common/core/web/keyboard-processor/src/text/ruleBehavior.ts, web/source/dom/domOverrides.ts, web/source/osk/banner.ts
Relates to #5853, #6177.
Two things happened here:
1. Construction of Mocks made an assumption that the selection should always be deleted. However, for NewContext and PostKeystroke processes, we don't want to change anything. https://github.com/keymanapp/keyman/blob/ee14b17b12dafc2b99149dfc67c93da12e19946a/common/core/web/keyboard-processor/src/text/outputTarget.ts#L365-L367
2. Even if nothing is changed, the transcription would emit what is in theory a no-op ruleTransform (insert="", deleteLeft=0, deleteRight=0). But apps would treat this as deleting the selection.
This fix goes a little broader than I would have preferred, but adds a readonly mode to the transcription and mock model, so that we can control explicitly when changes are applied to the text store.
I think we still have …
=> fix(web): add readonly mode for rule behavior finalization 🎢

android/KMEA/app/src/main/assets/android-host.js, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Part of #5853.
Fixes #6261.
Fixes #6177 (Android).
Building on the fixes in KeymanWeb in #6272, we do similar patches for Android.
I think it is likely that the iOS tests will fail -- in which case, I will work through similar patches for iOS.
(Note: these tests are very good candidates for general acceptance tests!)
Where requested, these tests should be run using the attached [web_context_tests keyboard](https://drive.google.com/file/d/1C1I39AxR9egfuQKXRbwwyK4T9YBw6Ji-/view?usp=sharing).
* **GROUP_ANDROID_INAPP:** Test on Keyman for Android, in-app
* **GROUP_ANDROID_SYSTEM:** Test on Keyman for Android, system keyboard
**TEST_BASELINE:** Using a keyboard with some complex behaviours, such as Khmer Angkor, verify that input sequences are correct. For example, type …
=> fix(android): properly handle selection 🎢

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift
Relates to #5853
~~Fixes 6041~~ Looks like this is still a separate issue (per discussion with @sgschantz)
This deals with deleting the selection with the new interface for KeymanWeb. It also ensures that the selection is always correctly sent to KeymanWeb.
(Note: these tests are very good candidates for general acceptance tests!)
Where requested, these tests should be run using the attached [web_context_tests keyboard](https://drive.google.com/file/d/1C1I39AxR9egfuQKXRbwwyK4T9YBw6Ji-/view?usp=sharing).
* **GROUP_IOS_INAPP:** Test on Keyman for iPhone and iPad, in-app
* **GROUP_IOS_SYSTEM:** Test on Keyman for iPhone and iPad, system keyboard
**TEST_BASELINE:** Using a keyboard with some complex behaviours, such as Khmer Angkor, verify that input sequences are correct. For example, type …
=> fix(ios): properly handle selection 🎢

developer/server/src/data.ts, developer/server/src/handlers/api/debugobject/register.ts, developer/server/src/handlers/api/font/register.ts, developer/server/src/handlers/inc/keyboards-css.ts, developer/server/src/routes.ts
Fixes #6297.
Five issues fixed from #6297. Note that the fix for point 5 (`font-family` should be keyboard-specific, and it is not being used per-keyboard in the keyboard registration yet) opts to use a cleaned identifier for the font filename, but not one that is keyboard-specific, at this time.
=> fix(developer): server font support

developer/server/src/config.ts, windows/src/developer/TIKE/dialogs/Keyman.Developer.UI.UfrmServerOptions.pas
Fixes #6303.
Moves ngrok.exe to %appdata%/Keyman/Keyman Developer/Server/bin/
(I have already tested locally and this is a low-risk change, furthermore we don't have the documentation ready, which makes writing the test instructions a bit challenging!)
=> fix(developer): move ngrok to Server/bin/

linux/keyman-config/keyman_config/handle_install.py
In the past we already gracefully handled keyboard download failures when the user triggered the download from the km-config UI. This change deals with the command line side of things, most often when the user clicks on the "Install keyboard" button on keyman.com. If the download fails we already output an error message and now don't try to install the non-existing .kmp file.
Fixes #6284.
=> fix(linux): Gracefully handle keyboard download failure

windows/src/developer/kmcomp/main.pas
Fixes #5415.
This adds `-h` and `-help` command line parameters to kmcomp. As kmcomp uses only single-hyphen parameters currently, I opted not to support the common `--help`, just for consistency.
While doing this, I noted that `halt` was used rather than `ExitCode`, so swapped to using `ExitCode` as `Halt` is an abnormal program termination.
=> feat(developer): kmcomp -h and -help ✂

windows/src/developer/TIKE/actions/dmActionsKeyboardEditor.dfm, windows/src/developer/TIKE/actions/dmActionsKeyboardEditor.pas, windows/src/developer/TIKE/child/UfrmKeymanWizard.dfm, windows/src/developer/TIKE/child/UfrmKeymanWizard.pas, windows/src/developer/TIKE/child/UfrmPackageEditor.pas, windows/src/developer/TIKE/main/UfrmMain.dfm, windows/src/developer/TIKE/main/UfrmMain.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.ProjectFileUI.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.kmnProjectFileUI.pas
Fixes #4168.
This button no longer makes sense when we have template projects, as it encourages keyboard developers to create multiple packages. The template project should already have a package.
It is also not hard to create a package if you don't already have one; this does not reduce the complexity significantly, apart from the mini feature of adding both the .js and the .kmx in a single step (the .kvk is added also by virtue of the .kmx being added, but that is done in any case if you manually add a .kmx to a package).
=> chore(developer): remove Package for Distribution action ✂

web/source/osk/floatingOskView.ts
This fixes an issue that arises when loading the Keyman Developer Server home page and there are registered keyboards, but no keyboards active. The floating osk view would throw an exception because it would attempt to set the title of the view from the active keyboard, which is `null`.
=> fix(web): error in floating osk view when no keyboard active ✂

developer/server/src/routes.ts, developer/server/src/site/packages.js, developer/server/src/site/test.js, developer/server/src/site/upload.js
Fixes #6299.
Moved some of the init to test.js from packages.js. If not on localhost, then the UI for upload is disabled -- note that backend for upload is already disabled for non-localhost.
This is necessary to prevent non-local site users uploading arbitrary files to the cache, which could lead to security bypass.
On localhost:
When running not on localhost, the Upload menu item, and the file drop target, are both disabled.
=> chore(developer): disable upload for server except localhost

windows/src/developer/TIKE/xml/layoutbuilder/builder.js
Fixes #6077.
Refactor all the text field event handlers to have consistent structure for edits, pastes and keyboard events. This fixes Ctrl+V paste as well as tidying up the relevant code.
* **GROUP_TYPING:** the change to make is to type a letter.
* **GROUP_PASTE:** paste text into the text field.
Follow the same process for each group: for each text field, verify that it marks changes as 'modified' correctly:
1. Open the touch layout editor view of any keyboard. Verify that the file tab does not have a '*' indicating file changes (highlighted in green in the image below).
2. Press F12 to open the Developer Console, and move it out of the way (you'll use this later to check for errors).
3. Choose the text field indicated in the test (fields are highlighted in yellow in the image below). …
=> fix(developer): handle paste event in touch layout editor

windows/src/global/delphi/comp/CloseButtonPageControl.pas, windows/src/global/delphi/comp/LeftTabbedPageControl.pas
Fixes #845.
Fixes #3224.
Makes the active tab more visible both in the horizontal file tabs, and in the vertical activity tabs by changing the background colour to Keyman Light Blue (css: `#79C3DA`).
=> fix(developer): Improve active tab visibility ✂

windows/src/developer/TIKE/child/Keyman.Developer.UI.UframeWordlistEditor.pas, windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas, windows/src/developer/TIKE/child/UfrmPackageEditor.pas
Fixes #6029.
Allows the user to specify the character and/or code font (where applicable) for the Package and Model Editors.
* **TEST_MODEL_EDITOR_FONT:** Verify that changing the Code and Character fonts (Edit menu) for the Model Editor applies as expected to the views in the editor.
* **TEST_PACKAGE_EDITOR_FONT:** Verify that changing the Code and Character fonts (Edit menu) for the Package Editor applies as expected to the views in the editor.
=> fix(developer): font for Package and Model Editors ✂

web/source/kmwutils.ts
Fixes #6072.
Stops the kmwosk.css stylesheet from being repeatedly inserted into the DOM.
* TEST_SINGLE_STYLESHEET: Test that the stylesheet is only inserted once.
(This test may be better performed by a developer?)
1. Open Keyman Developer web test window in Chrome.
2. Press F12 to view the Developer Console.
3. Use the Arrow tool in Developer Console (Ctrl+Shift+C) to select any part of the On Screen Keyboard.
4. In the Styles pane of the Developer Console, note how it shows styles coming from kmwosk.css.
5. There should be only one copy of each style (see image).
6. Switch to a different device in the KeymanWeb test window (perhaps do this two or three times).
7. Select an element of the On Screen Keyboard using the Arrow tool.
8. There should still be only one copy of each style.
You …
=> fix(web): stop repeated CSS injection ✂

developer/js/source/lexical-model-compiler/build-trie.ts, windows/src/developer/TIKE/child/Keyman.Developer.UI.UframeWordlistEditor.pas, windows/src/global/delphi/lexicalmodels/Keyman.System.WordlistTsvFile.pas
Fixes #3174.
Google Sheets can export TSV files with formatted numbers, including having commas as thousands separators. Let's ignore those commas.
* **TEST_COMMAS_IMPORT:** Verify that numbers with commas in them import into the Model Editor.
1. In the Model Editor, import a wordlist .TSV with commas in the frequency column, such as from Google Sheets.
2. Verify that the numbers appear in the grid view in the Model Editor.
* **TEST_COMMAS_COMPILE:** Verify that the compiled frequencies are correct.
1. Create a wordlist with one or two entries in it, with commas in the frequency column, and compile the model.
2. Load the compiled .model.js file and examine the trie data model therein to verify that the frequency data is correct.
For example, I had a wordlist with the word `the` in it, …
=> feat(developer): support commas in frequency in wordlists ✂

android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java, android/KMEA/app/src/main/res/layout/models_list_row_layout.xml, oem/firstvoices/android/.editorconfig, oem/firstvoices/android/.gitignore, oem/firstvoices/android/app/src/main/AndroidManifest.xml, oem/firstvoices/android/app/src/main/java/com/firstvoices/android/FVKmpInstallMode.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVDownloadResultReceiver.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVKeyboardListAdapter.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVKeyboardSettingsActivity.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVShared.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/PackageActivity.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java, oem/firstvoices/android/app/src/main/res/layout/fv_keyboard_settings_list_layout.xml, oem/firstvoices/android/app/src/main/res/layout/fv_list_row_layout.xml, oem/firstvoices/android/app/src/main/res/layout/keyboard_row_layout.xml, oem/firstvoices/android/app/src/main/res/values/strings.xml, oem/firstvoices/android/app/src/main/res/xml/file_paths.xml, oem/firstvoices/android/build.sh
This adds a feature to the FirstVoices Android app for keyboard and dictionary management. 
Several of these "new" files are direct copies from the Keyman for Android app (kmapro) to handle the kmp download, installation, and settings menus. The dictionary kmp installations are hard-coded to "silent" install (doesn't display help documentation).
Changed workflow:
The current FV app has checkboxes in the keyboard list to add/remove keyboards during setup. These have been replaced with forward arrows that go to keyboard settings menu. Enabling the toggle there will add the keyboard and check for associated dictionary to download. If there's a matching dictionary from api.keyman.com, the kmp will download in the background and silently install.
This also incorporates changes from #2255 and …
=> feat(oem/fv/android): Add keyboard and dictionary controls

windows/src/developer/TIKE/xml/app/editor/editor.js
When using Keyman Developer Debugger, each key pressed would reset the cursor location to the top of the .kmn file. Super annoying!
This fixes that! (This was also completed during The Great Tasmanian Internet Outage of 2022, so it gets the ✂ theme)
=> fix(developer): prevent execution point breaking editor location ✂

resources/build/trigger-builds.inc.sh
This change adds temporary debug code to track down why the beta build didn't get triggered by outputting the OUTPUT string.
It also counts the lines we're outputting so that we can output a newline in case we're not outputting anything.
=> chore(linux): Debug why Beta build didn't get triggered

windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.UfrmProject.pas
When starting Keyman Developer, you might try and switch back to another app, only to have it jump back to Developer as the Project window finishes loading. How rude!
This fixes that.
(This was also completed during The Great Tasmanian Internet Outage of 2022, so it gets the ✂ theme)
=> fix(developer): project should not steal focus on load ✂

android/KMEA/app/src/main/res/layout/list_row_layout1.xml, android/KMEA/app/src/main/res/layout/list_row_layout2.xml, android/KMEA/app/src/main/res/layout/list_row_layout3.xml, android/KMEA/app/src/main/res/layout/list_row_layout4.xml, android/KMEA/app/src/main/res/layout/list_row_layout5.xml, android/KMEA/app/src/main/res/layout/models_list_row_layout.xml
Relates to upcoming follow-on work to #6282 (consolidating FV Android dictionary list into the Keyboard settings menu)
Conforming to the Material Design guideline examples which only use bold in headings/titles, this removes the Bold typeface currently used in lists.
https://material.io/components/lists#interactive-demo
Also changed subtext color from black to grey
Updated keyboard picker
Updated installed languages (subtext in grey)
=> chore(android/engine): Remove bold styling in lists

resources/build/trigger-builds.inc.sh
The previous PR #6337 introduced a bug when run with `set -e` which this change fixes.
=> fix(linux): Fix trigger script

common/test/keyboards/build.bat, common/test/keyboards/build.sh
Relates to #5815.
build.sh is a new script that builds any or all of the keyboards in the common/test/keyboards folder. build.bat is a wrapper for build.sh, just for Windows CMD.
Assumes that kmcomp.exe has already been built or allows you to specify your own kmcomp.exe if necessary.
These keyboards will be built as part of the Windows/Developer build and be available as artifacts on that build. Later, may add them to downloads.keyman.com.
=> feat(common): build test keyboards via script

oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVKeyboardSettingsActivity.java
Fixes pre-launch report crash for FV Android and follow-on to #6282 
The Predictions toggle was checking if the active keyboard matched the current language before registering the lexical model.
During setup before a keyboard is enabled, this would cause a null pointer exception.
Note, a separate  follow-on PR will disable predictions by default until a dictionary is installed.
* **TEST_NO_ACTIVE_KEYBOARD**
1. Install the PR build of "FirstVoices for Android" and launch the app
2. On the main Setup menu, click "Select keyboards" --> BC Coast --> SENCOTEN
3. Before enabling the Sencoten keyboard, disable the toggle for "Enable predictions"
4. Verify the app does not crash
=> fix(oem/fv/android): Check keyboard exists before registering a model

common/core/web/input-processor/test.sh, common/core/web/keyboard-processor/test.sh, common/predictive-text/testing/one-stage-embedded-webworker/build.sh, common/predictive-text/testing/two-stage-embedded-webworker/build.sh, ios/i18n-export.sh, ios/kmbuild.sh, mac/bashHelperFunctions.sh, resources/shellHelperFunctions.sh, web/bulk_rendering/build.sh, web/source/build.sh, web/unit_tests/test.sh
Some of the global color variables in shellHelperFunctions.sh were a little dangerously named. This cleans that up and removes a couple of redundant functions from other locations.
mac/bashHelperFunctions.sh should be removed and replaced with references to shellHelperFunctions.sh -- but I wanted to leave that for a separate branch.
=> chore(common): cleanup sh global color variables

windows/src/developer/samples/imsample/IMSample.txt, windows/src/developer/samples/imsample/imsample.cpp, windows/src/engine/keyman32/calldll.cpp
tl;dr  add null ptr checks to pointers before access.
The tester discovered crashed when loading the imsample keyboard after installing it.    I went through and added checks throughout the code. I built in and attached to the PR the tester was verifying. I am just now checking in this branch.
Note: I made the coding style the current Keyman style. Normally on an old project like this, I would be happy to make the new code match the current code. If that is what you prefer please comment and I will change it.
=> fix(windows): add null pointer checks imsample keyboard

common/test/keyboards/build.sh, common/test/keyboards/the_99/build.sh
This allows for custom builds of keyboards, e.g. where a keyboard is manually constructed for testing purposes.
=> fix(common): allow custom keyboard builds

common/test/keyboards/.gitignore, common/test/keyboards/build.sh
Adds `--index` and `--zip-sources` parameters. These will be used by the Developer test-14.0 build to produce easily accessible keyboard artifacts on TeamCity, which the test bot will then link to.
=> feat(common): zip and index keyboard artifacts

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Addresses #6267 for 15.0 beta.
This updates the globekey longpress logic to trigger the keyboard picker menu before the globe key is released.
We still want to block the keybard picker menu for system keyboard on lock screen.
~Question: Should we make `KMManager.doGlobeKeyLongpressAction()` a public API?~
I ended up making `KMManager.handleGlobeKeyAction()` a public API
Setup 
1. On an Android device or emulator, install PR build of Keyman
2. From the Android settings menu, also set a simple password (e.g. `1234` as password, not PIN). If using a physical device, I 
recommend adding a second unlock like fingerprint
3. From Keyman, install another Keyman keyboard (e.g. Khmer Angkor)
* **TEST_GLOBE_SHORTPRESS**
1. In the Keyman app, short press the globe key and release
2. Verify Keyman …
=> fix(android/engine): Activate menu on globe longpress before release

web/source/osk/oskKey.ts, web/testing/unminified.html
Fixes #5964.
It seems that the test for subkey position was incorrect when the document had been scrolled. Removing the test for `fixed` positioning resolves the issue.
This needs to be tested on more than one device type.
* **GROUP_IPHONE:** Test on Safari on latest iOS
* **GROUP_ANDROID:** Test on Chrome on recent version of Android
* **GROUP_EMULATOR:** Test on Chrome on Windows, using mobile emulation
* **TEST_SCROLL:** Verify that longpress when the document is scrolled is working correctly
1. Load the keymanweb/testing/unminified test page.
2. Select the SIL Euro Latin keyboard (Swedish).
3. Longpress on various letters and make sure that the coloured key tracks the finger correctly.
4. Scroll the document down from the top.
5. Refocus the text field, and perform the same longpress …
=> fix(web): subkey touch position after scroll

android/KMAPro/build-play-store-notes.sh, android/build-help.sh, android/build-publish.sh, android/help/about/whatsnew.md
In preparation for cleaning up build.sh across the platforms, this moves the "Play Store" specific portion of `android/build-help.sh` into a separate `build-play-store-notes.sh` script. This way, we can refactor build-help.sh for all the platforms since they're essentially the same.
=> chore(android): Separate CI step to generate Play Store notes

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java, android/KMEA/app/src/main/res/values/strings.xml, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVKeyboardListAdapter.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVKeyboardSettingsActivity.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVRegionListAdapter.java, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java, oem/firstvoices/android/app/src/main/res/layout/fv_keyboard_settings_list_layout.xml, oem/firstvoices/android/app/src/main/res/layout/fv_list_row_layout.xml, oem/firstvoices/android/app/src/main/res/layout/keyboard_row_layout.xml, oem/firstvoices/android/app/src/main/res/layout/region_row_layout.xml, oem/firstvoices/android/app/src/main/res/values/strings.xml
Follow-on to #6282
For the FV Android app, this consolidates the model picker with the Keyboard settings menu so the user has less clicks.
Keyman Engine API change:
* make deleteLexicalModel() public
Tagging @madebybridget
* **TEST_MENU**
1. Load the PR build of the FirstVoices Android app and launch
2. On the main setup page, click "Select keyboards" --> BC Coast --> SENCOTEN
3. On the "SENCOTEN Settings" page, enable the keyboard
4. Wait for the associated dictionary to download and install (this could take a minute)
5. Verify the "SENCOTEN Settings" menu updates to show
* Keyboard is enabled
* Predictions is enabled
* Corrections is enabled
* SENCOTEN dictionary is installed (left blue checkmark)
6. Click on "SENCOTEN dictionary"
7. Verify the "SENCOTEN dictionary" info page appears
8. …
=> fix(oem/fv/android): Consolidate dictionary and keyboard settings

linux/keyman-config/keyman_config/ibus_util.py, linux/keyman-config/km-config
This change adds a 1s sleep after restarting ibus before checking that it actually runs. Hopefully this will solve the problem. Since
this bug is hard to reproduce, we also log a critical error for the other code path this could happen.
Fixes #6237.
- Since this bug is hard to reliably reproduce, the tests should be run on all Linux platforms:
- GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11
- GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11
- GROUP_IMPISH_X11: Ubuntu 21.10 Impish with Gnome Shell and X11
- GROUP_IMPISH_WAYLAND: Ubuntu 21.10 Impish with Gnome Shell and Wayland
- GROUP_WASTA: Wasta 20.04 with Cinnamon
- Reboot
- …
=> fix(linux): Don't start ibus-daemon multiple times 🚌

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift
Fixes #6041.
This may also fix #5300 and #5888
In-app keyboard was causing Keyman to crash when the user backspaced over multiple lines of text
* TEST_BACKSPACE: backspace in-app over multiple lines without crashing
1. Run Keyman and use the in-app keyboard for typing
2. tap 'a', then tap the return key
3. tap 'b', then tap the return key
4. tap 'c', then tap the return key
5. tap the backspace key mutlpile times until only the letter a remains
6. confirm that you can continue to use the keyboard and tap other keys
=> fix (ios) backspace crashes in app

common/core/desktop/build.bat, common/core/desktop/meson.build, common/core/desktop/src/debug.hpp, common/core/desktop/src/kmx/kmx_context.cpp, common/core/desktop/src/kmx/kmx_file.cpp, common/core/desktop/src/kmx/kmx_processevent.h, common/core/desktop/src/kmx/kmx_xstring.h, common/core/desktop/src/meson.build, common/core/desktop/src/state.hpp, common/core/desktop/src/utfcodec.hpp, common/core/desktop/tests/unit/kmnkbd/action_items.hpp, common/core/desktop/tests/unit/kmnkbd/debug_api.cpp, common/core/desktop/tests/unit/kmnkbd/debug_items.hpp, common/core/desktop/tests/unit/kmnkbd/meson.build, common/core/desktop/tests/unit/kmnkbd/state_api.cpp, common/core/desktop/tests/unit/kmnkbd/test_kmx_xstring.cpp, common/core/desktop/tests/unit/kmx/kmx.cpp, common/core/desktop/tests/unit/kmx/kmx_test_source.cpp, common/core/desktop/tests/unit/kmx/meson.build, common/core/desktop/tests/unit/utftest/utftest.cpp
Based on the suggestions of @eli-schwartz (in #5797).
Unfortunately we currently still have to support meson 0.45 (because that's what ships with Ubuntu 18.04), so we can't
implement everything suggested.
Also fixed some warnings triggered by the changes.
=> chore(common/core/desktop): Improve meson build file 🏗️

web/source/keymanweb.ts
Fixes the following crash noted when testing on keymanweb.com, focusing during the load process on a slow network.
Fixes KEYMANWEB-COM-5M.
```
helpers.ts:111 Uncaught TypeError: Cannot read properties of null (reading 'vkbd')
at g.pageFocusHandler (keymanweb.ts:125:44)
at sentryWrapped (helpers.ts:87:17)
```
=> fix(web): crash on focus before init

windows/src/ext/sentry/Sentry.Client.pas
=> chore(windows): move crash metadata to extra

windows/src/ext/sentry/Sentry.Client.pas
Fixes #6396.
Cherry-pick of #6397.
=> chore(windows): move crash metadata to extra 🍒

web/source/osk/visualKeyboard.ts
Fixes #6140.
When embedding the On Screen Keyboard into a page, the calculation for the bounding rectangle only took into account the first offsetParent, which meant it would get the offset incorrect when there were multiple layers of offsetParents.
Once I changed to using getAbsoluteX / getAbsoluteY, this also corrects for scroll with window.pageOffsetY, so we can eliminate that special case for fixed positioning.
This was observable in the Web Developer test window, where interaction with the bottom row of the keyboard in touch mode was not working correctly, in 15.0.210-beta.
For this test, you can use any keyboard that has both touch and desktop modes (e.g. Khmer Angkor).
**TEST_WEB_DEBUGGER:** Test that keys on every row of the On Screen Keyboard work correctly in the Developer Web …
=> fix(web): bounding rect offset was incorrect

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/res/layout/ime_list_layout.xml, android/KMEA/app/src/main/res/layout/list_row_layout5.xml, android/KMEA/app/src/main/res/values-sw720dp/dimens.xml, android/KMEA/app/src/main/res/values/dimens.xml
Fixes #6361 
This updates the styling for the Keyman keyboard picker menu to remove the stray lines.
The gap at the top was from the inadvertent `fab_margin` in `ime_list_layout.xml`.
Specifying a height dimension for `list_row_layout5` also fixed the stray lines at the bottom.
* **TEST_KEYBOARD_PICKER**
2. From the "Get Started" menu, enable Keyman as a system keyboard and set as a default system keyboard
3. Launch a separate app (e,g. Chrome) and select a textfield to display the Keyman system keyboard
4. Long-press the globe button to bring up the keyboard picker menu
5. Verify there's no display artifacts in the menu (before "Other Input methods" or at the end)
=> chore(android/engine): Remove visual gaps in keyboard picker menu

windows/src/developer/TIKE/xml/layoutbuilder/builder.js
Fixes #6386.
The touch layout editor would not reliably detect changes if using the mouse to select an item in a dropdown 'autocomplete'.
**TEST_SELECTOR:** Verify that selecting an item in a dropdown works correctly.
1. In the Touch Layout Editor, select a key, select the ID edit control.
2. Type `K_S`. Use the mouse to choose an item from the dropdown that is presented.
3. Verify that the selected item is shown in small letters at the bottom of the selected on the key cap.
See the video in #6386 for comparison with the original issue.
=> fix(developer): detect changes in dropdowns in builder

web/source/kmwembedded.ts
Observed while debugging another issue on iOS. The VisualKeyboard.waitForFonts function sets up a busy timer to wait for font loading. This functionality is not even needed on the iOS app, because it's really only used for the touch alias elements.
However, it was being called, potentially multiple times, leading to the timer never being removed. On Android, the timer was correctly removed.
This aligns the iOS code path with the Android code path.
=> fix(ios): remove busy 100ms waitForFonts timer on iOS

docs/build/macos.md, resources/devbox/macos/keyman.macos.env.sh, resources/devbox/macos/macos.sh
Python2.7 is excluded from macOS Monterey, and is not available directly via brew any longer. We still need it for now. pyenv does the job...
=> chore(mac): update build env for monterey

web/source/dom/touchAliasElement.ts
Fixes #5942.
The touch alias element position was not consistent across all browsers, leading to misalignment in some situations. Identified missing CSS to make the positioning consistent, as far as I can tell, which led to the additional benefit of reducing the per-browser special cases.
This will need to be tested in several environments.
GROUP_CHROME_ANDROID_MOBILE_EMULATION: Test in Google Chrome, mobile emulation, Android
GROUP_CHROME_IOS_MOBILE_EMULATION: Test in Google Chrome, mobile emulation, iOS
GROUP_CHROME_ANDROID: Test in Google Chrome, on Android device or emulator
GROUP_FIREFOX_ANDROID: Test in Firefox, on Android device or emulator
GROUP_SAFARI_IOS: Test in Safari, on iOS device or simulator
The test should be run on the KeymanWeb Unminified test page, available from the …
=> fix(web): adjust touch alias element positioning

windows/src/developer/kmcmpdll/kcframe/kcframe.cpp, windows/src/global/delphi/general/compile.pas
~~I am not sure how this was ever working.~~ Okay, looked at history, and this was broken by #5963 (commit e24b7561c6a69b9cdd5f16b2c1858f1a5ce159be), of all things, which added structure size sanity checks... but neglected to remember that struct sizes may differ between 32-bit and 64-bit code.
This just adds the specific structure sizes for x64 and verifies that the Delphi sizes are the same as the reported sizes from C++ (as reported by `kcframe.exe --sizeof`)
Minor tweak to printf format args for kcframe to assist in this, sorting a compiler warning.
=> fix(developer): structure sizes for kmcomp x64

resources/build/version/src/reportHistory.ts
Relates to #6391.
Adds some logging so we may be able to find out why we are getting strange results for some PRs.
=> fix(common): report more log detail in increment-version

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java, android/KMAPro/kMAPro/src/main/res/values/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java
Addresses #6254 for stable-14.0. This is a 🍒 -pick of the Keyman Engine for Android portion of #6355.
This updates PackageActivity() to check kmp.json that the minimum keyboard version (system.fileVersion) is supported by the current Keyman version.
Since 14.0 doesn't have common/ test keyboards, I didn't include the_99.kmp files on this PR. Test steps modified to reference the_99.kmp from #6355. 
The test keyboard "the_99.kmp" is a standard keyboard created from template where fileVersion is manually edited to "99.0". 
Keyman Developer currently (as of 15.0.210 beta) doesn't allow `store(&VERSION)` to define version greater than '15.0'.
Also updated full_caps_3620_3621 to use `store(&VERSION) '15.0'`
Setup
1. On an Android device/emulator, load the PR build of Keyman for Android
2. Also …
=> fix(android/engine): Test fileVersion during package install 🍒 

windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp
Fixes: #6422
#5190 removed using cache for the hotkeys but had a cut and paste bug for the VK_LMENU key.  This meant that hotkeys with ALT didn't work.  It also meant the alt key could match and ctrl hot key combo.  eg. `shift` + `ctrl` + `y` could also be activated by `shift` + `alt` + `y`
=> fix(windows): put correct HK_ALT flag for modifier

mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
Fixes #4877.
If a keyboard is invalid for any reason (missing, wrong version), then it would not appear in Configuration, which would break the row indexing, causing crashes.
@keymanapp-test-bot skip (We'll test on beta)
=> fix(mac): invalid keyboard breaks configuration

mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m, mac/Keyman4MacIM/Keyman4MacIM/en.lproj/Localizable.strings
Fixes #4877.
If a keyboard is invalid for any reason (missing, wrong version), then it would not appear in Configuration, which would break the row indexing, causing crashes.
Cherry-picked from stable-14.0 branch.
TEST_BROKEN_KEYBOARD: Verify that a broken keyboard is still listed, shown as "(error loading keyboard)" and UI functions as expected.
1. Start a Terminal and run `cd ~/Documents/Keyman-Keyboards`.
2. Type `ls` and press Enter. Choose one of the keyboards listed there, e.g. "khmer_angkor" (replace the name as needed below).
3. Type `cd khmer_angkor` and press Enter.
4. Type `rm khmer_angkor.kmx` and press Enter.
5. Type `cp kmp.json khmer_angkor.kmx` and press Enter.
6. Ensure Keyman is not running by typing `killall Keyman` and pressing Enter.
7. Start Keyman, open Keyman …
=> fix(mac): invalid keyboard breaks configuration 🍒

windows/src/desktop/kmshell/Makefile, windows/src/desktop/kmshell/xml/keyman.xsl, windows/src/desktop/kmshell/xml/menu.css, windows/src/desktop/kmshell/xml/menu.js
Fixes #6098.
If the list of languages is too long to fit, the menu now dynamically adds a scroll bar.
As a bonus:
* The language names are sorted (non-Latin scripts at bottom for now)
* `nmake install` works again (in kmshell, presence of `install` folder was confusing it)
Side note: the JS/CSS/HTML/XSL in Keyman Configuration is somewhat archaic and filled with anachronisms. Fun project for an intern to rewrite it?
TEST_MENU: Verify that the User Interface Language menu scrolls when it is too long, in Keyman Configuration.
=> fix(windows): make long menus scroll in Configuration

web/source/osk/browser/keytip.ts, web/source/osk/browser/subkeyPopup.ts, web/source/osk/oskKey.ts, web/source/resources/osk/kmwosk.css
Fixes #5929.
Fixes #6381.
This fixes four separate issues with the longpress popups and key previews:
1. The key preview was offset by a couple of pixels (unreported issue).
2. The background 'shim' did not cover the key caps, which caused them to look startlingly white when the rest of the background greyed down (#5929).
3. The popup menu was incorrectly wrapping to two rows due to sizing model mismatches (#6381).
4. The popup menu would be realigned incorrectly for the in-app keyboard, when moving it to keep it in the keyboard area (#5929).
Longpress iOS (Chrome simulation):
Key preview iOS (Chrome simulation): 
* We need to verify the behaviour of the longpress menu and the key preview. If possible, capture screenshots of both of these elements when running the tests, so we can …
=> fix(web): ios popup positioning and style

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #6292 
When overwriting an existing keyboard package with the same version, we need to clear the webView cache and reload for the updated keyboard to show.
**Setup**
On the Android emulator/device, save this modified keyboard package file [sil_cameroon_qwerty.kmp](https://darcywong00.github.io/examples/sil_cam_qwerty_azerty/sil_cameroon_qwerty.kmp) to the device's "Downloads" folder. This matches the current (at the time of creating this PR) version of [sil_cameroon_qwerty](https://downloads.keyman.com/keyboards/sil_cameroon_qwerty/6.0.6/sil_cameroon_qwerty.kmp) (version 6.0.6), but the keyboard file is replaced with a modified copy of sil_cameroon_azerty. The ID was also modified to remain `sil_cameroon_qwerty`, but the OSK will display *azerty* on the default layer.
* …
=> fix(android/engine): Clear WebView cache on package install

web/source/osk/oskKey.ts, windows/src/developer/TIKE/xml/layoutbuilder/builder.js
Changes `*Shifted*` from ![image](https://user-images.githubusercontent.com/4498365/160302858-47196b40-bca9-43c8-a865-f763f7ae5cb5.png) (same as `*Shift*`) to ![image](https://user-images.githubusercontent.com/4498365/160302866-7780fe4c-da93-4d2a-b264-6724872156c6.png).
While this was done in code as a global override, probably following Apple stylistic changes, it is better to leave this to the keyboard developer to decide on.
=> fix(web): *Shifted* showed unshifted key cap

web/source/keyboards/kmwkeyboards.ts
This is a follow-up for #6331. We still did not have enough detail to be able to trace the root cause of the load errors. This adds a little more diagnostics.
=> fix(web): track load error detail

windows/src/developer/TIKE/child/Keyman.Developer.UI.UframeWordlistEditor.pas, windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas, windows/src/developer/TIKE/main/Keyman.Developer.System.LexicalModelParser.pas
Fixes #2185.
If a wordlist file is not in the same folder as the .model.ts file, Keyman Developer will now ask the user if they want it copied into the folder.
Also minor fix: if the user deletes a row in a wordlist, it marks the file as modified.
Also very minor: the initial folder for the Add Wordlist dialog is now the same as the .model.ts file.
**TEST_COPY_WORDLIST:** Verify that Keyman Developer correctly copies a wordlist into the right folder.
1. Create a new model project and open the .model.ts file in Keyman Developer.
2. Click Add button in the Wordlists section to add a wordlist to the project, and select a wordlist that is in another folder.
3. You should be prompted to copy the wordlist into the .model.ts folder. Accept the prompt by clicking Yes.
4. The wordlist should be …
=> fix(developer): Add Wordlist button now copies into source folder

oem/firstvoices/android/app/build.gradle, oem/firstvoices/android/build.gradle
Fixes failing CI build of stable-14.0 on Android
🍒 -pick of #5127 to stable-14.0
This is a follow-on to #6224 which missed updating build gradle other dependencies for the FV Android build.
The plugin syntax for publishing to the Play Store is also updated.
=> chore(oem/fv/android): Update dependencies 🍒 

windows/src/developer/TIKE/debug/UfrmKeyTest.pas
Fixes #5063.
It can be useful to be able to insert multiple keys into the active keyboard source file. With this tweak, the dialog no longer closes with the Insert button, only with the Close button.
=> feat(developer): keep Virtual Key Identifier dialog open on Insert

common/core/web/input-processor/src/text/inputProcessor.ts, common/core/web/input-processor/tests/cases/inputProcessor.js, common/core/web/keyboard-processor/src/text/keyboardProcessor.ts, common/core/web/tools/recorder/src/nodeProctor.ts
Fixes #6405.
If the layer is reset to default, e.g. by switching fields, then the state key bitmask was not always kept in sync with the layer change.
This does not attempt to keep Caps Lock on when switching tabs.
=> fix(web): track stateKeys changes with layer changes

linux/ibus-keyman/src/engine.c, linux/ibus-keyman/tests/run-tests.sh, linux/ibus-keyman/tests/testfixture.cpp
This change modifies the `run-tests.sh` script so that tests run on both Wayland (if supported) and X11 unless `--no-wayland` or `--no-x11` is specified.
This change also adds the new argument `--wayland` to the `ibus-keyman-tests` executable which runs the tests under
Wayland.
Note that running Wayland tests is only possible in Ubuntu 21.10+ because it requires a version of `mutter` that supports the headless option which got added in mutter 40.
=> feat(linux): Allow to run ibus tests on Wayland 🛤️

windows/src/developer/TIKE/xml/help/contexthelp.xml, windows/src/developer/TIKE/xml/help/help.xsl
Fixes #2750.
This tweaks the More Help link to open the correct part of the Keyboard Editor help page.
Goes together with keymanapp/help.keyman.com#526.
The context help data needs a consolidated rewrite. This does not attempt to touch that, nor does it attempt to add more contextual help links for any other part of the Developer IDE. That is work for another day...
=> fix(developer): improves More Help link for icon tool

ios/help/about/whatsnew.md, linux/help/about/whatsnew.md, mac/help/about/requirements.md, mac/help/common/keyboards.md, mac/help/common/os.md, mac/help/index.md, windows/src/desktop/help/basic/config/options.md, windows/src/desktop/help/index.md
This updates some of the in-app help to Keyman 15.0.
Also updates the supported macOS to include Big Sur
=> chore(common): Update in-app help versions to 15.0

windows/src/developer/TIKE/main/UframeBitmapEditor.dfm, windows/src/developer/TIKE/main/UframeBitmapEditor.pas
Fixes #2749.
Adds a Clear All button which does the same as Edit/Clear Selection.
At the same time, fixes the Clear code for transparent background colours; previously, clear all with transparent background gave a black fill.
=> feat(developer): add Clear All button to icon editor

windows/src/developer/TIKE/dialogs/UfrmBitmapEditorText.dfm, windows/src/developer/TIKE/dialogs/UfrmBitmapEditorText.pas, windows/src/developer/TIKE/main/UframeBitmapEditor.pas
Fixes #2748.
Note that transparent text is not supported for ClearType or antialiased modes.
=> fix(developer): icon editor font color now follows fgcolor

ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Data/Version.swift, ios/engine/KMEI/KeymanEngine/en.lproj/Localizable.strings
Fixes #6255
When a package is being installed, checks the fileVersion field to find the minimum version of Keyman that the package supports. If this minimum version is greater than the version of Keyman , then the package installation fails and an alert is presented to the user.
* **TEST_FUTURE_VERSION:** Try installing package [the_99.kmp](https://downloads.keyman.com/developer/beta/15.0.219/keyboards/the_99.kmp). It should not fail to install and display the following alert:
* **TEST_KHMER:** Try installing Khmer Angkor -- it should install successfully
=> fix(iOS): check version during package install

ios/help/about/system-requirements.md, ios/help/about/whatsnew.md
Documents the change from #5168 of the minimum iOS version to 12.1
=> chore(ios): Document minimum iOS version 12.1

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java, android/KMEA/app/src/main/assets/android-host.js, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #5277 and possibly fixes #5965
Update SystemKeyboard to show the keyboard after a keyboard change.
Setup
1. Install the the PR build of Keyman for Android
2. Dismiss the "Getting Started" menu and enable Keyman as the default system keyboard
* **TEST_ROTATION** - Verifies the Keyman keyboard is visible after rotating device and the layer can change
1. Launch a separate app (e.g. Twitter or Chrome)
2. With the Keyman keyboard, start typing. Note, any stuck popup keys are addressed separately by #6494
3. Select the "Shift" layer and continue typing
4. Rotate the device
5. Verify after rotation, the Keyman keyboard refreshes and is visible. Note, the layer reverts to Default layer.
6. Continue typing
7. Verify the keyboard continues to output text in the current field and it's …
=> fix(android/engine): Show keyboard after rotating

android/KMAPro/kMAPro/src/main/res/values-az-rAZ/strings.xml, android/KMEA/app/src/main/res/values-az-rAZ/strings.xml, ios/engine/KMEI/KeymanEngine/az.lproj/Localizable.strings, linux/keyman-config/locale/az_AZ.po, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/az.lproj/KMAboutWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/az.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/az.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/az.lproj/KMKeyboardHelpWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/az.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/az.lproj/MainMenu.strings, windows/src/desktop/kmshell/locale/az-AZ/strings.xml, windows/src/desktop/setup/locale/az-AZ/strings.xml
Addresses the English strings in #5531 
All the iOS strings for Azerbaijani should be complete. there's still a few missing macOS.
=> chore(common): Update Crowding strings for Azerbaijani

linux/keyman-config/km-package-get.bash-completion, linux/keyman-config/km-package-install, linux/keyman-config/km-package-install.bash-completion
This is done by replacing the deprecated `imp` module. Also extract common code into a separate method.
Fixes #6227.
- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_IMPISH_X11**: Ubuntu 21.10 Impish with Gnome Shell and X11
- Reboot
**TEST_PKG_GET**: Tab completion works in `km-package-get` without warning
- open a terminal window
- type `km-package-get a` and then press the `<tab>` key twice
- expected result: this should display a list of Keyman packages starting with _a_, without displaying a warning …
=> fix(linux): Remove tab completion warning

android/KMAPro/kMAPro/src/main/java/com/keyman/android/CheckInstallReferrer.java
For investigating [Sentry report](https://sentry.io/organizations/keyman/issues/2700298447/?project=5983520&query=is%3Aunresolved&statsPeriod=14d)
```
onInstallReferrerSetupFinished: Unexpected code: 4
```
This was added in [Play Install Referrer API Library 2.2](https://developer.android.com/google/play/installreferrer/release-notes#2_2) which added the response `PERMISSION_ERROR`
Unfortunately the documentation is sparse on how to fix non-OK responses (the Android [sample code](https://developer.android.com/google/play/installreferrer/library#connecting) isn't even updated to include the new response).
All the non-OK responses seem to get lumped in the same Sentry issue.
=> chore(android/app): Add description for referrer response error

web/source/keyboards/kmwkeyboards.ts, web/testing/promise-api/eventLogging.js, web/testing/promise-api/index.html
Fixes #5730.
A `kmw.keyboardchange` event should only occur once the keyboard has been successfully changed.  For initial loads of a keyboard, this is an asynchronous process - so it must interact with the `Promise` system.  Fortunately, `Promise`s (and our `setActiveKeyboard()` implementations of them) make this fairly simple.
Note that it _is_ currently expected that on a keyboard's first load, `beforekeyboardchange` will be called twice - once for the initial change attempt, then another once the keyboard's script has actually been loaded:
https://github.com/keymanapp/keyman/blob/bb4887387729a2ea5761e4e0d7d19c118eac6d9f/web/source/keyboards/kmwkeyboards.ts#L753-L757
(More context may prove useful, but I didn't want it to overwhelm this description.)
------
To facilitate testing these …
=> fix(web): keyboardchange event should defer until successful

linux/debian/rules, linux/ibus-keyman/tests/run-tests.sh
Debian reproducibility testing runs a slightly different package build that seemingly doesn't set the `DEB_BUILD_MULTIARCH` variable. 
This change introduces our own environment variable to detect package builds so that we can skip the ibus-keyman integration tests that require running an X server.
=> chore(linux): Fix failure in Debian reproducibility testing 🐧

web/source/keyboards/kmwkeyboards.ts
Fixes #2238.
Adds two new properties to the return values of [`keyman.getKeyboard()`](https://help.keyman.com/DEVELOPER/ENGINE/WEB/14.0/reference/core/getKeyboard) and `keyman.getKeyboards()`:
- `HasLoaded`:  a boolean indicating whether or not KMW has actually loaded the keyboard.
- necessary for the following property to be set
- thus, is surfaced to the site developer so that they can condition upon this if necessary.
- doesn't matter whether or not the keyboard is _active_ - only that it has been fully _loaded_ by KMW, usually by having been active at one point in the past.
- `IsRTL`:  a 'boolean' indicating whether or not the keyboard is used for a language written right-to-left.
- Is `.HasLoaded` is `false`, this will be ~`undefined`~ `null` instead.  Hence the quotes on 'boolean'. …
=> feat(web): adds .getKeyboard().IsRTL, .HasLoaded

android/KMEA/app/src/main/java/com/tavultesoft/kmea/ConfirmDialogFragment.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java, android/KMEA/app/src/main/res/values-km-rKH/strings.xml, android/KMEA/app/src/main/res/values/strings.xml
Fixes #4875
Turns out some of the Toast notifications were using English-only strings. This updates some of them to be localizable.
I've manually edited `values-km-rKH` to include the Khmer string @MakaraSok provided for "Keyboard deleted".
Setup
* **TEST_KEYBOARD_DELETED** - Tests the Toast notification is localized when keyboard deleted
1. Start Keyman and dismiss the "Get Started" menu 
2. From the Keyman Settings --> Search for and install a keyboard package (e.g. khmer_angkor)
3. When the keyboard finishes installing, go to Keyman Settings --> Display language --> Set the UI to Khmer
4. Return to Keyman text area and verify the menu UI is in Khmer (may need to click the overflow icon)
5. From Keyman Settings --> Installed languages --> …
=> fix(android/engine): Localize some Toast notifications

common/core/web/tools/sentry-manager/src/index.ts
Fixes Sentry [report](https://sentry.io/organizations/keyman/issues/2798359833/?project=5983524&query=is%3Aunresolved) of `Cannot read properties of undefined (reading 'forEach')`
=> fix(common/core/web): Fix forEach loop in SentryManager

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #6554
The keyboard picker contains logic in `prepareKeyboardSwitch` to determine if the suggestion banner needs to be enabled/disabled. We need to do the same after installing a keyboard / setting new keyboard to determine if the suggestion banner needs to be enabled/disabled.
Setup
1. Load the PR build of "Keyman for Android"
* **TEST_BANNER_TOGGLE** - Tests suggestion banner is enabled/disabled
1. Start Keyman and dismiss the "Get Started" menu
2. Verify the default sil_euro_latin keyboard has suggestions visible
3. From Keyman Settings, search for and install a keyboard that doesn't have a dictionary (e.g. khmer_angkor)
4. Finish the keyboard package installation and verify the keyboard changes to the installed keyboard
5. Verify the suggestion banner is no longer visible
6. …
=> fix(android/engine): Check suggestion banner after setting keyboard

android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDownloadMgr.java
Cleans up [Sentry log](https://sentry.io/organizations/keyman/issues/2699309698/events/eeb999c5f4eb46e3831205385b38990a/?project=5983520&query=is%3Aunresolved) involving DownloadManager() notifications we can ignore.
From the comment in 
https://github.com/keymanapp/keyman/blob/30c3276ce851e014463bc65a2d870a23fd4c51d4/android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDownloadMgr.java#L92-L99
it appears we get notifications from DownloadManager whenever a download finishes. They may not be Keyman downloads, so we ignore those download IDs.
=> chore(android/engine): Ignore DownloadManager if ID not found

windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp
Cherry-pick of #6425.
Backporting to support https://community.software.sil.org/t/bug-with-left-alt/6219
=> fix(windows): put correct HK_ALT flag for modifier 🍒

windows/src/desktop/setup/RunTools.pas, windows/src/desktop/setup/UfrmRunDesktop.pas, windows/src/desktop/setup/bootstrapmain.pas, windows/src/desktop/setup/setup.dproj
Fixes #1864
There was a time,  up to version 11 when the Product version GUID was the same between versions. That is no longer the case.
Now we only set defaults if no previous installed version exists.
There were a few snags along the way if the MSI installer requests a reboot after installing a previous version of Keyman, then on reboot the `FInstallInfo.InstalledVersion.Version` will be empty. 
Added switch of `-d` to the command line which if it is set the defaults will be set. 
When msi installer requests a reboot the command to run after reboot can be set to include `-d`.
It would be good to move the checking of the `FInstallInfo.InstalledVersion.Version` into `bootstrapmain.pas`  however the version is not available at this point. So it needs to be checked in the `RunTool.pas` …
=> fix(windows): Don't reset defaults on Keyman upgrade

android/KMAPro/kMAPro/src/main/res/values-it-rIT/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java, android/KMEA/app/src/main/res/values-it-rIT/strings.xml, ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/it.lproj/ResourceInfoView.strings, ios/engine/KMEI/KeymanEngine/it.lproj/Localizable.strings, ios/engine/KMEI/KeymanEngine/it.lproj/Localizable.stringsdict, ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj, ios/keyman/Keyman/Keyman/it.lproj/Localizable.strings, linux/keyman-config/locale/it_IT.po, mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/it.lproj/KMAboutWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/it.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/it.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/it.lproj/KMKeyboardHelpWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/it.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/it.lproj/MainMenu.strings, windows/src/desktop/kmshell/locale/it-IT/strings.xml, windows/src/desktop/setup/locale/it-IT/strings.xml
This pulls in the crowdin strings for Italian (language tag `it`).
**TODO before testing**
Note, the overall crowdin progress on Italian is 98%, so there will still be a few untranslated strings that show in English.
2. From the Keyman "Settings" menu, change the "Display Language" to "Italiana"
3. Return to the Keyman app and verify the strings are in Italian
* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the device locale to Italian
3. Return to Keyman and verify strings are in Italian
* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. Set the device locale to Italian
3. Return to Keyman and verify strings are in Italian.
=> chore(common): Add crowdin strings for Italian

oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVKeyboardSettingsActivity.java
Fixes crash from FirstVoices pre-launch report in version 1500245 
```
Process: com.firstvoices.keyboards, PID: 20671
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.tavultesoft.kmea.data.Keyboard.getLanguageID()' on a null object reference
at com.firstvoices.keyboards.FVKeyboardSettingsActivity$4.onItemClick(FVKeyboardSettingsActivity.java:310)
at android.widget.AdapterView.performItemClick(AdapterView.java:318)
at android.widget.AbsListView.performItemClick(AbsListView.java:1333)
```
Refactors the repeated block of code into `registerMatchingLexicalModel()` which has null checks on the current keyboard.
Setup - Load the PR build of "FirstVoices for Android"
* **TEST_DICTIONARY**
1. Launch the FirstVoices app
2. On the Setup menu, click **Select …
=> fix(oem/fv/android): Check current keyboard before registering model

android/KMEA/app/src/main/assets/android-host.js
Fixes #6603
This update refreshes the OSK when changing the spacebar caption text.
Setup - Install the PR build of "Keyman for Android"
* **TEST_SPACEBAR_TEXT** - Verifies the spacebar caption refreshes on user selection
2. Observe the default spacebar caption on sil_euro_latin is "Language + Keyboard" (e.g. **English - EuroLatin (SIL)**)
3. From Keyman Settings --> Spacebar caption --> Select an option and verify the keyboard caption updates accordingly:
* Language
* Keyboard
* Language + Keyboard
* Blank
=> fix(android/engine): Refresh OSK when changing spacebar text

windows/src/engine/keyman32/kmhook_getmessage.cpp
Fixes #6571
Fixes #6576 
The check to see if the active keyboard was a Keyman keyboard was using the wrong API call `GetAtomName` instead of `GlobalGetAtomName`. So it was never going to find the str associated with the atom.
This had the effect of turning off the pipeline. It also it broke IMX, [ Ctl Alt ] key combinations in some applications as well as the 
right ALT combinations in Khmer Angkor
=> fix(windows): use GlobalGetAtomName to access global list

ios/keyman/Keyman/Keyman/AppDelegate.swift
Fixes #6413.
In iOS 15 Apple introduced a new default behavior for navigation bars where they become transparent when the edge of the scrollable content aligns with the edge of the navigation bar. This would cause the background view to bleed through and interfere with presentation of the view in the foreground. 
This was most noticeable when installing a new keyboard and could also be seen in the info window.
This fix changes the appearance back to the pre-iOS 15 default behavior so that the navigation bar is translucent white as originally designed.
- **TEST_MAIN_SCREEN**:  Open Keyman and confirm that the navigation bar is white and not yellow.
- **TEST_INSTALL_KEYBOARD**:  Install a keyboard from within the Keyman and see that the navigation bar of the install dialog looks correct …
=> fix(ios): disables transparent nav bar for ios 15

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
fixes #6547 
Rotation of the Keyman system in iOS was causing the app to leak memory as the old web view instances used to implement the system keyboard were not being deallocated. This would cause the Keyman keyboard extension to consume more memory and potentially become unstable.
Before this fix, memory consumption increases with each rotation and is not released:
After this fix, memory is quickly reclaimed after many rotations as shown in Xcode:
=> fix(ios): stops leaking memory on system keyboard rotation

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Fixes #6636
The logic to clear popup keys depends on GestureDetector triggering `MotionEvent.ACTION_UP`. This PR pulls the handling out of the if/else because sometimes, the `ACTION_UP` event goes through the if() block.
https://github.com/keymanapp/keyman/blob/1747722ebdd264587a876b73a2c253801ef0fdcc/android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java#L285-L289
Setup - A physical Android device. Don't use emulator because the scenario involves typing fast on the OSK (e.g. two thumbs)
* **TEST_BETA_STICKY_KEYS** - Verify beta build can have long-press keys stuck
1. On the Android device, install 15.0.249 beta of Keyman for Android
https://downloads.keyman.com/android/beta/15.0.249/keyman-15.0.249.apk
2. Dismiss the "Get Started" menu 
3. In the Keyman app, quickly type …
=> fix(android/engine): Fix sticky long-press keys

ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/keyboard.html
Fixes #6595.
It turns out that with iOS 15, Apple decided that the page content of WebViews should always respect the "safe area guidelines".  (A reference with a similar issue: https://developer.apple.com/forums/thread/685727)  This, in combination with an interesting bug, appears to force our host page's allotted area to be smaller than its viewport... even when it's not actually disrespecting that safe area.
This has the net effect of the host page's viewport being bumped vertically up the page.  Web's mobile OSK uses `fixed` positioning, which is viewport-relative.  It's also directly told a target size from the Swift side, meaning that the OSK still expected to use the full page... causing the top part of the 'oversized' OSK up and out of the viewport.
Fortunately, JavaScript has …
=> fix(ios): fixes OSK mispositioning bug in iOS 15

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas, windows/src/desktop/kmshell/util/utilkmshell.pas
#6648 introduced logging around keyboard install. Unfortunately, a code formatting issue meant that it introduced a bug causing all elevated installs to fail. This fixes that and tweaks the logging.
=> fix(windows): unbreak keyboard install

common/core/web/input-processor/src/tsconfig.json, common/core/web/keyboard-processor/src/tsconfig.json, common/core/web/tools/recorder/src/build.sh, common/core/web/tools/recorder/src/tsconfig.json, common/core/web/tools/sentry-manager/src/build.sh, common/core/web/tools/sentry-manager/src/tsconfig.json, common/core/web/utils/build.sh, common/core/web/utils/tsconfig.json, common/models/templates/tsconfig.json, common/models/wordbreakers/.gitignore, common/models/wordbreakers/tsconfig.json, common/web/es6-shim/tsconfig.json, common/web/keyman-version/build.sh, common/web/keyman-version/tsconfig.json, common/web/lm-worker/tsconfig.json, developer/js/tsconfig.json, developer/server/build.sh, developer/server/src/win32-tray.ts, developer/server/tsconfig.json, package-lock.json, resources/shellHelperFunctions.sh, resources/web-environment/.gitignore, resources/web-environment/tsconfig.json, web/source/build.sh
Update all web component build paths to use ./build/ instead of current variety of ./, ./dist/, ./build/
Does not touch build paths for server components yet (that'll come much later).
=> chore(web): make build paths consistent 🎡

developer/js/tests/helpers/index.ts, resources/build/build-utils.sh, web/bulk_rendering/build.sh, web/bulk_rendering/renderer_core.ts, web/bulk_rendering/tsconfig.json
Changes the bulk renderer build script to the new standard build script format and updates to use `tsc -b`. Cleans up final external `<reference>`s.
=> chore(web): bulk renderer tsc cleanup 🎡

common/models/types/build.sh, developer/js/build.sh, developer/js/bundle.sh, developer/server/build.sh, docs/npm-packages.md, resources/shellHelperFunctions.sh
Note that the version entry will be added to the local package.json which will then be dirty. This version entry should not be committed.
=> chore(web): update npm version refs for publishing packages 🎡

common/core/web/input-processor/test.sh, common/core/web/input-processor/tests/cases/languageProcessor.js, developer/js/bundle.sh
Uses "Poor Man's Modules" until we have ES6, just so we can get passing
tests.
=> chore(web): fixup languageProcessor text unit tests 🎡

common/web/input-processor/src/tsconfig.json, common/web/keyboard-processor/src/tsconfig.json, common/web/lm-worker/src/correction/distance-modeler.ts, common/web/lm-worker/src/index.ts, common/web/lm-worker/src/worker-interfaces.ts, web/source/tsconfig.base.json
Addresses review comments in #6525:
* There were a few temporary type patches I had made earlier in the refactor chain in order to get a build to pass. After completing the refactor, I was able to return them to their more proper types.
* revert PostMessage and ImportScripts types
* reintroduce sourceRoot in tsconfig files
=> chore(web): reintroduce sourceRoot and revert types 🎡

common/predictive-text/unit_tests/in_browser/CI.conf.js, common/web/keyman-version/package.json, developer/js/bundle.sh, developer/js/source/kmlmc.ts, developer/js/source/kmlmi.ts, developer/js/source/kmlmp.ts, developer/js/source/lexical-model-compiler/model-definitions.ts, developer/server/build.sh, developer/server/src/environment.ts, oem/firstvoices/ios/exportAppStore.plist, package-lock.json, web/source/build_dev_resources.sh
As KEYMAN-VERSION changed from being a type to a class, this broke the bundling and referencing strategies in Developer/Server and Developer/kmlmc. This updates the bundling process and fixes the references in both projects.
Note that keyman-version no longer depends on gosh. Given we are currently manually calling the build for this in all projects (or should be!), it's better that we keep the build of this explicit for now.
If we want to restore the postinstall/postci steps in the future, the gosh dependency would need to be manually removed from package.json in order for the bundling builds to work for Developer/Server and Developer/kmlmc.
=> chore(web): adapts keyman-version bundling in Developer products 🎡

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift, ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift
Fixes #6536.
So... it turns out that simply deferring the first display of the keyboard in-app (triggered by `.becomeFirstResponder`) until after the currently dispatched message on app's internal main loop is complete, the keyboard loads correctly!
While this doesn't clarify _which_ part of keyboard and app UI initialization are the source of the underlying conflict, it's pretty apparent.  The now-deferred `.becomeFirstResponder` call was triggered by a notification from the initializing `KeymanWebViewController` that the host page has loaded, before the keyboard was ever displayed.  Still isn't displayed when it's triggered, though.
- GROUP_IPHONE_SE:  Test on the (notchless) iPhone SE (2nd gen) through Simulator
- GROUP_IPHONE_12:  Test on the (notched) iPhone 12 Pro Max through …
=> fix(ios): keyboard height on app load

ios/help/about/welcome.md, ios/keyman/Keyman/Keyman/Classes/InfoViewController/InfoViewController.swift, ios/keyman/Keyman/Keyman/Classes/InfoViewController/InfoViewController_iPad.xib, ios/keyman/Keyman/Keyman/Classes/InfoViewController/InfoViewController_iPhone.xib, ios/keyman/Keyman/Keyman/Classes/KMWebBrowser/WebBrowserViewController.xib, ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift
Fixes #6599.
Fixes #6653.  (The bug was discovered during testing and is a one-liner to fix.)
In a couple of screenshots...
Note the new bar at the bottom.  Since we've long had the bar at the top where it is, how it is... I felt it better to add something simple at the bottom.  This also mimics the in-app browser a bit, though with fewer toolbar options.  While the final, right-most option is redundant... the bar feels much better with that option, rather than having a whole bar _just_ for "back" and "forward".  I did consider a "top" / return-to-TOC... but then there's the matter of finding a reasonable icon / image for that.
I may have been a touch lazy and not implemented the safe-area buffer seen on phones for tablets, as there are not currently any notched iPads.  There's no …
=> feat(ios): adds back and forward navigation buttons for in-app help

web/source/osk/anchoredOskView.ts, web/source/osk/oskLayer.ts, web/source/osk/visualKeyboard.ts
Fixes #5646.
The reason that the black border line was appearing in the iOS keyboard is that before these changes, the OSK may shrink itself slightly during its initialization.  The reason for this?  From `VisualKeyboard.computedAdjustedOskHeight`:
https://github.com/keymanapp/keyman/blob/2d0fed11d37aec94875054413a335d94fdefc69d/web/source/osk/visualKeyboard.ts#L1290-L1300
Note:  that's a `Math.floor`.  As a result, this will never adjust to a greater total height, but may adjust it - rather, shrink it - if it would otherwise result in keyboard rows with fractional height.
The thing is... there's no need to shrink the main container (`_Box`) of the OSK.  We can round the rows to even integer heights and just keep an extra pixel or two at the top, rather than ending the element early... …
=> fix(web): osk shrinkage from rounding

android/KMAPro/kMAPro/src/main/res/values-b+es+419/strings.xml, android/KMEA/app/src/main/res/values-b+es+419/strings.xml, ios/engine/KMEI/KeymanEngine/es-419.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/es-419.lproj/KMAboutWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/es-419.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/es-419.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/es-419.lproj/KMKeyboardHelpWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/es-419.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/es-419.lproj/MainMenu.strings
This updates the crowdin strings for Spanish (Latin America) for Android, iOS, and macOS.
macOS strings are new, so 
TODO
These strings will then be used as a "pivot translation" in translate.keyman.com for Qom.
Setup
Install PR build of Keyman for macOS
* **TEST_MACOS_STRINGS** - Verifies macOS localized for Spanish (Latin America)
1. Set the system locale to Spanish (Latin America). (`es-419`)
2. Restart the device
3. Launch Keyman for macOS
4. Verify UI is in Spanish (Latin America)
=> chore(android,ios,mac): Update crowdin strings for Spanish (Latin America)

common/core/desktop/tests/unit/kmx/028 - smp.kmn, common/core/desktop/tests/unit/kmx/meson.build, windows/src/global/delphi/general/CompilePackage.pas
Fixes a race condition when compiling multiple packages, where the temp path may be re-used before the compiler has finished with it.
To take advantage of this fix, I wanted to make sure I was using the right kmcomp.exe when building unit tests for Keyman Core. This uncovered a couple of other things:
* Updates Keyman Core build infrastructure to use the current kmcomp.exe rather than a system-installed one.
* Corrects a bug that was identified by the 15.0 version of kmcomp in one unit test (duplicate `&NAME` stores -- the meson test script prepends a `&NAME` store to each source file during build).
=> fix(developer): kmcomp package compiler race condition

web/source/osk/visualKeyboard.ts
Fixes [KEYMAN-WEB-X](https://sentry.io/organizations/keyman/issues/2846706970/?project=5983524&query=is%3Aunresolved).
Relates to #6541.
`TypeError: Cannot read properties of undefined (reading 'indexOf')`
@jahorton I have not identified a root cause for this. There may be something deeper going on? But this mitigates the crash report I think.
~~Once this is approved I will cherry-pick to beta (which will then flow through to alpha eventually).~~
@keymanapp-test-bot skip (I cannot think of any applicable tests)
=> fix(web): crash in highlightKey

windows/src/developer/TIKE/main/KeymanDeveloperUtils.pas
In many cases, this would have worked fine. But if there was pathing ambiguity, it could have failed with strange errors.
=> fix(developer): install keyboard call should quote kmshell.exe path

common/predictive-text/unit_tests/in_browser/CI.conf.js, common/predictive-text/unit_tests/test.sh, web/unit_tests/CI.conf.js
Per support case with BrowserStack, am turning on deeper reporting for BrowserStack-based testing in karma.
=> chore(web): switch on additional BrowserStack reporting

web/source/kmwuifloat.ts, web/source/kmwuitoolbar.ts, web/source/osk/floatingOskView.ts
Fixes #6685.
As it turns out, both the Float and Toolbar UI modules were broken by changes made during the `InlinedOSK` work for 15.0.
1. The OSK is no longer initialized immediately, meaning the file-level variable for the `osk` had to be eliminated.  The adjustments were fine with minification disabled, but not when enabled.
- Refer to #5412.
2. The encapsulated modeling of OSK hide vs show behavior caused the OSK to be hidden (via `Promise`-deferment) on loss of focus when users interacted with certain UI elements, as the two modules didn't make full use of `keyman.activatingUI` to note when the active element should be preserved on temporary loss of focus.
- As the hiding operation was via `Promise`-deferment, any "show" commands would actually work... and then would instantly be …
=> fix(web): fixes OSK-interaction issues in Float, Toolbar UI modules 

android/KMEA/app/src/main/assets/android-host.js, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardJSHandler.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Follow-on to #6626 and fixes #6665
This updates KMManager to not vibrate the device when processing hardware keystrokes.
**Setup**
1. Pair a physical Android device with an external keyboard
2. Install the PR build of "Keyman for Android"
3. Start Keyman 
4. On the "Get Started" menu, enable Keyman as a system-wide keyboard and set Keyman as default keyboard
5. Clear the checkbox for **Show "Get Started" on startup** and dismiss the "Get Started" menu
* **TEST_INAPP_KEYBOARD** - Verifies haptic feedback with the in-app keyboard
1. Start Keyman
2. In the Keyman app, type with the OSK a mixture of base keys, longpress keys, and suggestions
6. Verify the device **does not** vibrate when outputting text (haptic feedback defaults to off)
7. In the Keyman app, type with the external keyboard
8. …
=> fix(android/engine): Disable haptic feedback on hardware keystrokes

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas
Fixes: #6619 
`TTIPMaintenance.GetUserDefaultLanguage` now returns a Canonicalized user tag using kmcomapi Interface to ensure consitency in the conversion. 
For full details on see the issue #6619 History
=> fix(windows): Install TIP crash with inconsistent bcp47tag

web/source/osk/oskLayer.ts, web/source/osk/visualKeyboard.ts
Fixes #6646.
GROUP_IN_APP:  Test using the main Keyman app on a physical iPhone or iPad.
GROUP_IN_MOBILE_BROWSER:  Using a physical iPhone or iPad, use Safari and navigate to the "Prediction - robust testing" manual test page through the "KeymanWeb Test Home" link below.
For both, select the "EuroLatin" keyboard.  (It has lots of subkeys.)  In app, this is the default keyboard.
TEST_QUICK_YOU_TYPING:  Rapidly type `you ` at least 10 times in a row.  Fail if a subkey is emitted more than once for every ten tries.
- Do try to be a bit precise, but the focus _is_ on rapidly typing.
TEST_LONGPRESS_FLICK: 
1. Press and hold the `i` key and _quickly_ move your finger in an upward motion.  Select a subkey.
2. Press and hold the `i` key, keeping your finger still.
- The subkey menu should display …
=> change(web): adjusts minimum distance needed for quick-display of subkeys

common/predictive-text/unit_tests/in_browser/CI.conf.js, web/unit_tests/CI.conf.js
Since we've been occasionally seeing flakiness during browser-based testing due to occasional failure-to-'capture' (BrowserStack term), this PR seems to alleviate that somewhat by upping the allowed number of retries per test suite.  To ensure this doesn't cause a build to run too far over... and also because things don't tend to recover after a minute or so on connection failures, this decreases the timeout allowances.
A follow-up to #6707.
=> change(web): browser test timeout tweaks

web/source/osk/oskBaseKey.ts, web/source/osk/oskLayer.ts, web/source/osk/oskRow.ts, web/source/osk/visualKeyboard.ts
Fixes #6699.
It looks like I may have missed something small and subtle related to row-height layout calculations in the big OSK refactoring batch last year.  For touch OSKs, our CSS applies light top and bottom padding... but this wasn't being considered in layout calculations.  This resulted in it being applied twice-over at the top, with very-slightly oversized keys to boot - the net effect of which caused the bottom row's keys to appear lightly cropped.
- GROUP_ANDROID:  test on an Android device.  Emulated should be fine.
- GROUP_IOS:  test on an iOS device.  Emulated should be fine.
- It may be best to use an un-notched device - something like the iPhone SE.  One aspect of the test may be trickier to confirm otherwise.
- TEST_OSK_PADDING:  load the keyboard and verify that the …
=> fix(web): row height layout calcs now consider layer-group padding

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/KeyboardController.java
Since the root cause behind #6703 remains pretty elusive, rather than continue to endlessly chase it, perhaps some additional logging may be in order.  I'm basing this on #6704, adding onto its changes.
For one of the logs:  I found it quite interesting how all of the call stacks I randomly checked (>10, for at least 7 affected users) matched; the error for each of them always happened with `SystemKeyboard.onStartInput` on the call stack.  It doesn't seem to be occurring in any other circumstance.  Therefore, I feel it's safe to add (well-documented) log messages to `getCurrentKeyboardInfo` under the assumption that the corresponding `-1` always corresponds to an erroneous internal state... and to #6703's underlying issue.
For the other one - we kinda forgot to Sentry-log something that …
=> chore(android): adds diagnostic logging to assist a fix for #6703

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/LanguageSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/KeyboardController.java
Fixes #6703.
This issue was first reported in 14.0.282-stable. I have done a careful review of changes in 14.0.282 (and 14.0.281) but have been unable to find any changes that could have bearing on this.
The basic issue is that there appears to be some circumstances where `KMManager` thinks that it has a keyboard loaded (ref `SystemKeyboardLoaded` variable), but `KMKeyboard.currentKeyboard` is still `null`.
The crash has been reported for only a very small set of users, 119 at time of fix, but average reports per user is over 100. As is usual with this type of thing, a small fraction of those users are reporting the majority of crashes. I have not found any real commonality across the error reports -- they are geographically dispersed, across multiple device types and Android versions. …
=> fix(android): check index validity in getCurrentKeyboardInfo

web/samples/index.html, web/testing/index.html, web/tools/index.html
We need a '../index.html' link rather than '../' on the three second-level KeymanWeb test pages, in order to get to the index page for artifacts when the test pages are hosted on build.palaso.org -- otherwise TeamCity returns a 404. (This is probably also good for file-system-based navigation.)
We don't need the same reference on other directories, just for the top-level index.html.
Identified at https://github.com/keymanapp/keyman/pull/6557#issuecomment-1157526326
@keymanapp-test-bot skip I think we can skip testing on this...
=> chore(web): add 'index.html' to parent links in test pages

common/core/web/input-processor/src/text/inputProcessor.ts
Fixes #6788.
Fixes KEYMAN-WEB-22.
Fixes KEYMAN-DEVELOPER-BQ.
Fixes KEYMAN-ANDROID-160.
Fixes a crash introduced in #6473 which was trying to prevent modifier keys from triggering "fat finger" alternate lookups, due to incomplete nullish coalescing.
Related to this, from what I can see, a secondary side-effect of the fix in #6473 was that some key events may have never had their ruleBehaviors finalized if they matched the `isOnlyLayerSwitchKey` heuristic, leading to potential issues with edge case 'deadkey+layer switch' keys or keys that set store values, for example. So this fix also makes the `isOnlyLayerSwitchKey` test more targeted.
Identified this when adding a Caps Lock layer to sil_euro_latin and testing the layer switching. At time of fix, the error had been raised in KeymanWeb, …
=> fix(web): crash on custom modifier keys

common/web/input-processor/src/text/inputProcessor.ts
Cherry-pick of #6789.
Fixes #6788.
Fixes KEYMAN-WEB-22.
Fixes KEYMAN-DEVELOPER-BQ.
Fixes KEYMAN-ANDROID-160.
Fixes a crash introduced in #6473 which was trying to prevent modifier keys from triggering "fat finger" alternate lookups, due to incomplete nullish coalescing.
Related to this, from what I can see, a secondary side-effect of the fix in #6473 was that some key events may have never had their ruleBehaviors finalized if they matched the `isOnlyLayerSwitchKey` heuristic, leading to potential issues with edge case 'deadkey+layer switch' keys or keys that set store values, for example. So this fix also makes the `isOnlyLayerSwitchKey` test more targeted.
Identified this when adding a Caps Lock layer to sil_euro_latin and testing the layer switching. At time of fix, the error had been …
=> fix(web): crash on custom modifier keys 🍒

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java, android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/LanguageSettingsActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelPickerActivity.java
Cherry-pick of #6704. Fixes #6703.
This issue was first reported in 14.0.282-stable. I have done a careful review of changes in 14.0.282 (and 14.0.281) but have been unable to find any changes that could have bearing on this.
The basic issue is that there appears to be some circumstances where `KMManager` thinks that it has a keyboard loaded (ref `SystemKeyboardLoaded` variable), but `KMKeyboard.currentKeyboard` is still `null`.
The crash has been reported for only a very small set of users, 119 at time of fix, but average reports per user is over 100. As is usual with this type of thing, a small fraction of those users are reporting the majority of crashes. I have not found any real commonality across the error reports -- they are geographically dispersed, across multiple device types …
=> fix(android): check index validity in getCurrentKeyboardInfo 🍒

windows/src/buildtools/sentrytool/Keyman.System.JclMapScanner.pas, windows/src/buildtools/sentrytool/Keyman.System.MapToSym.pas, windows/src/buildtools/sentrytool/sentrytool.dpr, windows/src/buildtools/sentrytool/sentrytool.dproj
For Keyman for Windows, TJCLMapScanner (originally in jcldebug.pas) was the only class used in the entire JCL, in the build-time project sentrytool. For now, I have copied this class plus its handful of dependent functions into Keyman.System.JclMapScanner so that we can remove JCL as a dependency for Keyman for Windows.
There is no need to review the code in the JCLMapScanner unit -- it is copied from existing code and it's not our code anyway.
We do not plan to use JCL in the future.
For Keyman Developer, we currently depend on the JVCL docking components. These import a huge range of JCL and JVCL units. Therefore, we'll move these units into Developer in the next PR.
=> chore(windows): remove JCL library dependency 🎢

web/source/osk/browser/keytip.ts, web/source/resources/osk/kmwosk.css
A 🍒-pick of #6784.
Fixes two issues:
- When using the iOS version of keyman, key previews for the top row will no longer be cropped.
- When using KeymanWeb in a browser on Android devices, the bottom part of the key preview is no longer missing.
=>  fix(web): key preview styling, positioning issues 🍒 

web/source/osk/browser/keytip.ts, web/source/resources/osk/kmwosk.css
Fixes #6783.
Key tips should properly remain within the OSK's bounds again after this fix.
As this is a top-row key preview, note that its base key is completely obscured by the preview.
This fixes a regression introduced in #6383.  (Gotta test the top row _without_ predictive-text!)
These tests are derived from those of #6383, but they're a bit more precise and targeted than before.
In-app groups:
- GROUP_IPHONE_13_APP - use the Keyman app with a (simulated or real) iPhone 13.
- GROUP_IPHONE_SE_2_APP - use the Keyman app with a (simulated or real) iPhone SE 2nd gen.
- GROUP_ANDROID_APP - use the Keyman app with a (simulated or real) Android device - your pick.
In-browser groups:
- GROUP_IPHONE_13_BROWSER - use Safari on a (simulated or real) iPhone 13.
- GROUP_IPHONE_SE_2_BROWSER - use …
=> fix(web): key tip constraint logic requires .bottom CSS 

ios/keyman/Keyman/SWKeyboard/KeyboardViewController.swift
Fixes #6806.
So, it turns out that there's a very simple case in which we should _expect_ there not to be a constructable banner image - whenever one of the potential banner-image's dimensions will be zero:
https://github.com/keymanapp/keyman/blob/88e18db690407ae807d0419fa6d5da3d3fb2924b/ios/keyman/Keyman/SWKeyboard/ImageBannerViewController.swift#L45-L48
As width = 0 can occur as a temporary state during view initialization, we should probably filter this case out.  The original log message was only ever meant to capture when the image-banner's rendering outright failed to produce an image.
The only functional change is that the Sentry log count will be dramatically reduced, if not eliminated.  If the function returns because of the new condition, it would have …
=> fix(ios): overzealous error about missing banner image

linux/keyman-config/keyman_config/install_kmp.py
This change deals with files that are referenced in the keyboard package but don't actually exist.
Fixes #6811.
=> fix(linux): Deal with non-existing files

linux/keyman-config/km-config
When the user cancels km-config by pressing Ctrl-C we don't want this to be reported on Sentry.
Fixes #6813.
=> fix(linux): Catch KeyboardInterrupt

package-lock.json, web/package.json
Fixes #6516.
As it turns out, the version of `@sentry/cli` we'd been using had a neat little issue inside of it.  From its `bin/sentry-cli` file:
```
child.on('error', err => {
console.error('error: failed to invoke sentry-cli');
console.error(err.stack);
});
```
Note:  there's no notion of a `process.exit` call here, or even tracking of error state to be reported at the script's end.  So... no exit code.  Cute.
In the version we're updating to:
```
.on('error', (err) => {
console.error(err); // eslint-disable-line no-console
process.exit(1);
})
```
Much better.
--------
Now, something possibly of note is that this locks down the version of `@sentry/cli` to be used with Web.  As per the authors' notes at https://www.npmjs.com/package/@sentry/cli:
> We do however, encourage you to pin the …
=> chore(web): updates error-reporting lib uploader

developer/src/tools/sentry-upload-difs.sh, windows/src/buildtools/sentry-upload-difs.sh
Splits the script into separate scripts for each platform. Note that this is only ever called from TeamCity builds.
=> chore(windows): split sentry-upload-difs.sh to Developer 🎢

web/package-lock.json, web/package.json
Fixes #5616.
This parallels #6818 for 15.0.
It's not exactly a 🍒-pick because of all the changes to our dependency infrastructure brought about by the big 🎡 PR-chain (see #6525, et al).  Instead, I just re-implemented the changes directly in 15.0's package.json and used the results from that.
But do make sure that Web's CI build log indicates that no errors occurred with the upload to Sentry... on the following stable build.  Because the Sentry upload doesn't run on PR builds.
=> chore(web): updates error-reporting lib uploader (pseudo-🍒)

.gitignore, ios/exportAppStore.plist, ios/kmbuild.sh, ios/samples/build_common.sh, ios/scripts/kme-universal.sh, mac/build.sh, oem/firstvoices/ios/build_common.sh, oem/firstvoices/ios/exportAppStore.plist, resources/build/build-utils.sh, resources/build/xcode-utils.sh
Fixes the clobbering of build_version values. For some reason, this was only happening on ba-macos-ext-hba-01 and not on ba-macos-ext-hba-03, despite there being little difference between the two agents. However, writing `manageAppVersionAndBuildNumber` to the export plist makes the behaviour consistent between the two agents. `manageAppVersionAndBuildNumber` does not appear to be documented anywhere that I can find on apple.com -- only discussion in forums and [StackOverflow](https://stackoverflow.com/questions/68237292/xcode-manage-version-and-build-number-option#comment122517504_68237292).
Thank you yet again Apple for introducing a yet another new undocumented build behaviour with the most recent forced xcode update...
This also rewrites some of the scripts …
=> chore(ios): log script actions and fixup export settings to avoid version being clobbered

ios/keyman/Keyman/Keyman/Classes/InfoViewController/InfoViewController.swift, ios/keyman/Keyman/Keyman/Classes/InfoViewController/InfoViewController_iPad.xib, ios/keyman/Keyman/Keyman/Classes/InfoViewController/InfoViewController_iPhone.xib, ios/keyman/Keyman/Keyman/Classes/SetUpViewController/SetUpViewController.swift, ios/keyman/Keyman/Keyman/Classes/SetUpViewController/SetUpViewController.xib
Apple's official view is that the `UIWebView`, which is used by various parts of the app, is considered deprecated in favor of the `WKWebView`.  We've... been a bit lazy about this in the past, but after a little investigation and effort, it turns out that this use of it, at least, is pretty easy to modernize.
As this does affect the layout specification used by our in-app help, it'd be best to make sure the help "looks right" across a few different iOS devices.
Feel free to test against any version of an Apple device matching the name of the "groups" listed below; whichever is most convenient for our testers should be 100% fine.
- GROUP_IPHONE_SE
- GROUP_IPHONE_13
- GROUP_IPAD_AIR
- TEST_APP_HELP:  simply open the Keyman app's "Info" section and make sure it works intuitively.
- If it's …
=> chore(ios): modernizes app-help's internals

linux/keyman-config/keyman_config/install_kmp.py
This change deals with files that are referenced in the keyboard package but don't actually exist.
Fixes #6811.
(🍒-picked from #6812)
=> fix(linux): Deal with non-existing files 🍒

ios/keyman/Keyman/SWKeyboard/KeyboardViewController.swift
Fixes #6807, for real this time.
There's no reason to condition the height for the banner's image when building it.
So, let's just use the non-conditional version.
=> fix(ios): eliminates conditional height for banner image

web/source/osk/visualKeyboard.ts
Fixes #6735.
May also fix #1930, but I have been unable to repro it on (emulated) Android using #6735's repro.
------
Turns out a very natural assumption for us to make actually isn't valid - for iOS, at least, it is possible for the OSK itself to be reloaded _during_ a backspace event.  (I haven't been able to succesfully reproduce this with emulated Android yet.)  With how KMW is structured, a reload results in the OSK being rebuilt from the ground up.
When this occurs - a backspace at the same time as an OSK reload, with the old OSK's final event being a 'touchstart' on `K_BKSP` - we get a permanently-sticky backspace key, as the new OSK has no reference for the repeating `K_BKSP`'s timer.
Note that we'll want a more comprehensive rework to prevent the event that's causing the full OSK …
=> fix(web): clears repeating bksp on keyboard reload ⬅️

web/source/osk/oskView.ts
Fixes #6853.
Looks like someone (probably me) over-optimized a check here, causing the second rung of the affected `if`-`else` ladder to be active in a scenario that was intended for the final rung.  Oops!
We could probably skip here, but...
- TEST_ANDROID_LOAD:  Make sure the Android app loads smoothly and that its keyboard rotates normally.
- TEST_IOS_LOAD:  Make sure that the iOS app loads smoothly and that its keyboard rotates normally.
- TEST_BASE_WEB:  In Chrome, use the "Test unminified Keymanweb" test page _in desktop mode_ and ensure that the OSK displays normally when each text area is clicked, moving underneath the current input element.
=> fix(web): null-guard for refreshLayout

windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
Fixes #6846.
Cherry-pick of #6865.
For KeymanWeb compiled keyboards, readonly groups should never emit any output. Rules in these groups permitted only to:
* `use` other readonly groups
* `call` external functions (which MUST NOT emit output)
* `set`, `reset` or `save` store values
The problem solved here is that the compiler would generate a `k.KO()` the first time any statement such as `set()` was encountered when emitting the rule output, which is just wrong for a `readonly` group. For safety, we make sure that all other output is omitted here also for readonly groups.
The base kmx compiler can emit output for rules in readonly groups (e.g. when it encounters a 'context' statement). Thus, the KeymanWeb compiler, when it transpiles from the generated .kmx, needs to omit output for any …
=> fix(developer): readonly groups should never emit output 🍒

common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
Fixes #6799.
Cherry-pick of #6849.
Caps Lock state management for touch layouts was not quite right -- it touched the base Caps state variables rather than just the event Lstates property. This meant that it was impossible to track the physical Caps Lock key separately to the touch layout layer, and that the two states would interfere with each other.
This PR changes that behaviour and separates the physical caps lock and touch caps lock states. The physical caps lock state is tracked in the `this.stateKeys['K_CAPS']` variable, but is completely ignored for touch layouts. Rules use the Caps Lock state replicated in the `Levent.Lstates` property, which was already being set correctly for the touch layout in the `ActiveKey.constructBaseKeyEvent` function.
=> fix(web): Maintain separate Caps Lock states for touch and physical 🍒

resources/build/trigger-builds.inc.sh
stable-15.0 builds were not triggering for test PRs. I think this is because a test build had never run on that branch in TeamCity, and so its locator didn't match. Removing the buildType appears to have resolved this.
=> fix(common): trigger builds correctly for stable builds

windows/src/desktop/kmshell/render/SupportXMLRenderer.pas, windows/src/engine/tsysinfo/sysinfo_main.pas
Updated various places in Keyman for Windows to show the full VersionWithTag rather than the short version number we had been previously showing:
- Support tab
- System Information, About dialog
* TEST_SUPPORT_TAB: Verify the version number shows correctly in the Support tab.
* TEST_DIAGNOSTICS: Verify the version number shows correctly in the Diagnostics, About dialog.
=> fix(windows): show full version number

resources/build/trigger-builds.inc.sh
Cherry-pick of #6847.
stable-15.0 builds were not triggering for test PRs. I think this is because a test build had never run on that branch in TeamCity, and so its locator didn't match. Removing the buildType appears to have resolved this.
=> fix(common): trigger builds correctly for stable builds 🍒

web/source/osk/banner.ts
Fixes #6885 for `stable-15.0`.  We'll likely want equivalent changes in #6849 before it merges as well.
TEST_PRED_TEXT:  On a desktop device, using Chrome's developer mode on the "Prediction - robust testing" Web test page...
1. Use the "Toggle device toolbar" button to _emulate_ a mobile device.
2. Refresh the page.
3. Click one of the textboxes.
4. Click any default suggestion.
- If the selected suggestion is not applied properly, _**FAIL**_ this test.
5. Check the developer-mode "Console" tab (it's usually visible by default).  If there are _any_ errors (with red text!) in the console log, report them and _**FAIL**_ this test.
- Unless they were already in the console before step 4.
6. Type a few letters and click another suggestion.
- If the selected suggestion is not applied …
=> fix(web): post-keystroke processing after use of pred. text selection

web/source/osk/banner.ts
Ooh, a rare inverse-🍒 - and to an active PR at that!
This fixes an issue noted in PR #6849 that was detected when its 🍒 to stable-15.0 got merged in first and started generating Sentry events.
TEST_PRED_TEXT:  On a desktop device, using Chrome's developer mode on the "Prediction - robust testing" Web test page...
1. Use the "Toggle device toolbar" button to _emulate_ a mobile device.
2. Refresh the page.
3. Click one of the textboxes.
4. Click any default suggestion.
- If the selected suggestion is not applied properly, _**FAIL**_ this test.
5. Check the developer-mode "Console" tab (it's usually visible by default).  If there are _any_ errors (with red text!) in the console log, report them and _**FAIL**_ this test.
- Unless they were already in the console before step 4.
6. Type a few …
=> fix(web): properly binds 'suggestionApplied' event handler

developer/src/server/build.sh
Fixes #6859.
Addresses the test blocks encountered in #6848, #6849. ~~Note that I have now rebased those two PRs off this PR chain, so that they can be tested and merged independently.~~ It turns out that this fix is needed for those PRs, because this broke with the removal of Lerna in #6525 (we postponed regression testing of Developer on that PR because we knew we needed to do it anyway). So I am going to do some more rebasing so we can get these all tested.
The production path needed to have all files under the build/dist/ folder, not just the build/ folder. This was broken in the refactor in #6630.
This 🎢 reorganisation chain impacts Windows and Developer. This means we need to run regression tests on the impacted products. I do not anticipate serious issues but there is potential for …
=> fix(developer): dist path for server 🎢

common/web/keyboard-processor/src/text/keyboardProcessor.ts, web/source/osk/banner.ts
Fixes #6799.
Caps Lock state management for touch layouts was not quite right -- it touched the base Caps state variables rather than just the event Lstates property. This meant that it was impossible to track the physical Caps Lock key separately to the touch layout layer, and that the two states would interfere with each other.
This PR changes that behaviour and separates the physical caps lock and touch caps lock states. The physical caps lock state is tracked in the `this.stateKeys['K_CAPS']` variable, but is completely ignored for touch layouts. Rules use the Caps Lock state replicated in the `Levent.Lstates` property, which was already being set correctly for the touch layout in the `ActiveKey.constructBaseKeyEvent` function: …
=> fix(web): Maintain separate Caps Lock states for touch and physical

common/schemas/keyman-touch-layout/README.md, common/schemas/keyman-touch-layout/keyman-touch-layout.clean.spec.json, common/schemas/keyman-touch-layout/keyman-touch-layout.spec.json
Does not tighten the spec for legacy data -- that should probably be a separate schema file.
See also #5029 (C5029.1 File Formats: .keyman-touch-layout changes). This doesn't 100% match what we have in #5029, so perhaps I should go back and update that, but would prefer eyes on this before I update that feature spec.
=> feat(developer): add flick and multitap to touch layout schema and doc 🙊

linux/debian/ibus-keyman.postinst
This change fixes the ibus-keyman post install script which previously failed if for whatever reason `SUDO_USER` is not set.
Fixes #6893
=> fix(linux): Fix post-install script

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, common/web/sentry-manager/src/index.ts, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js, web/source/dom/domManager.ts
Currently Keyman for Android reports errors sent to the console via `console.error()` into Sentry but sentry-manager itself does not. This means that Keyman for iPhone and iPad and other users of sentry-manager do not report these errors. Many of these errors are important.
What's worse is that Keyman for Android's error reporting here (via the `sendKMWError()` function in Keyman Engine for Android) does not capture stack traces, and so many of the errors we get do not have enough information to resolve them.
Furthermore, by having `sendKMWError()` in Keyman for Android, we capture exceptions and other program errors twice -- once on the web side, and once on the Java side -- this adds noise to our error reporting. Sentry also tends to lump many unrelated `sendKMWError()` events together, …
=> fix(web): improve `console.error()` reporting

developer/src/server/src/site/test.js
With the fix in fix/web/context-only-device, we need to ensure that the debugger correctly tells KeymanWeb which device is active.
=> fix(developer): set contextDevice in web debugger 🖇️

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
This is a follow-up to #6890 and already cherry-picked to #6904.
Turns out that we were getting *three* reports of JS errors on Android. These are also pretty useless for the same reason as for `sendKMWError`, and in fact conflated the JS errors with other kinds of errors. This makes it very hard to pick out the non-JS errors from the noise.
=> chore(android): disable sendError for js errors

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, common/core/web/tools/sentry-manager/src/index.ts, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js, web/source/dom/domManager.ts
Cherry-pick of #6890 and #6905.
Only change is to add `//@ts-ignore` for Sentry calls, required for 15.0 branch, not needed in 16.0.
=> fix(web): improve `console.error()` reporting 🍒

common/web/keyboard-processor/src/text/keyboardProcessor.ts
Fixes #6910.
Regression introduced in #6874 / #6849 (which themselves were improving the Caps Lock situation).
Ensures that either `NO_CAPS` or `CAPS` is always set in the modifier flags.
* **TEST_DEGA:** Test that typing <kbd>a</kbd><kbd>a</kbd> on the Dega keyboard on mobile web, iOS or Android, on the touch keyboard, gives the expected `â`.
* **TEST_KHMER:** Test that typing on the Khmer Angkor keyboard on mobile web, iOS or Android, on the touch keyboard, gives expected results (e.g. type xEjmr gives the right result).
=> fix(web): ncaps rules not matching on touch 🔥

common/core/web/keyboard-processor/src/text/keyboardProcessor.ts
Fixes #6910.
Cherry-pick of #6911.
Regression introduced in #6874 / #6849 (which themselves were improving the Caps Lock situation).
Ensures that either `NO_CAPS` or `CAPS` is always set in the modifier flags.
@keymanapp-test-bot skip.
=> fix(web): ncaps rules not matching on touch 🔥 🍒

common/web/keyboard-processor/src/text/kbdInterface.ts, common/web/keyboard-processor/tests/cases/chirality.js
Fixes #6792.
Up until now, KeymanWeb hasn't bothered comparing a keyboard's chirality with the corresponding OSK's key "layer" property - it's simply assumed consistency between the two.  Should a keyboard developer specify a chiral "layer" property when the keyboard itself isn't actually chiral, that unchecked assumption would cause the key not to match in the expected way.  For the price of a little extra overhead, we can remove that assumption.
Note that there is no matching keyboard for the user test; instead, I've added numerous unit tests to handle the important part of the changes for the original issue.  However, it's still best to test other keyboards to make sure that others aren't affected.
- TEST_NORMAL_CHIRALITY:  Using the "Chirality testing/bootstrapping" test page...
- …
=> fix(web): maps touch-layout chiral alt, ctrl to non-chiral when non-chiral keyboard is active

developer/src/tike/child/UfrmPackageEditor.pas
Fixes #6922.
Path changed in Keyman Developer 15.0, but was not updated here.
=> fix(developer): QR Code for Package Editor had wrong path

ios/engine/KMEI/KeymanEngine/Classes/Constants.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Data/Version.swift
Fixes #6932.
Use KeymanVersionWithTag from .plist instead of CFBundleShortVersionString when checking version information, because XCode can rewrite bundle version of frameworks.
@keymanapp-test-bot skip.
=> fix(ios): ignore CFBundleShortVersionString

ios/engine/KMEI/KeymanEngine/Classes/Constants.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Data/Version.swift
Cherry-pick of #6934.
Fixes #6932.
Use KeymanVersionWithTag from .plist instead of CFBundleShortVersionString when checking version information, because XCode can rewrite bundle version of frameworks.
=> fix(ios): ignore CFBundleShortVersionString 🍒

common/windows/cpp/src/keymansentry.cpp, developer/src/inst/download.in.mak, developer/src/kmdecomp/savekeyboard.cpp
This is part of a larger set of PRs coming which will automate the build of keyboards during the Keyman Developer build.
See also:
* keymanapp/keyboards#1913
* keymanapp/keyboards#1914
Adds kmdecomp to kmcomp-<version>.zip and fixes a couple of stability issues:
* Increase buffer sizes (this fix very much a hack)
* Ensures that .bmp/.ico files are saved to correct output folder
* Don't create zero byte .bmp if there is no .bmp embedded in the .kmx
* Disable loading sentry.dll when running on WINE
=> fix(developer): kmdecomp stability tweaks 🚦

common/windows/cpp/src/keymansentry.cpp, developer/src/common/delphi/compiler/compile.pas, developer/src/inst/download.in.mak, developer/src/kmcmpdll/Compiler.cpp, developer/src/kmcomp/main.pas, developer/src/kmdecomp/savekeyboard.cpp, developer/src/server/build.sh, developer/src/tools/sentry-upload-difs.sh
Replaces the script building kmcomp-$version.zip in TeamCity. Will be used for more automated keyboard testing shortly.
Means kmcomp-$version.zip will be available as an artifact in all test builds.
I have adjusted the TeamCity release build configuration for Developer to only build kmcomp-$version.zip if it needs to. Once this merges, I will cleanup the old code in that build configuration as it is 16.0+ (the older build is part of Keyman for Windows 14.0 build and that won't change for now).
Note: also moves the distribution point for Keyman Developer Server from src/server/build to bin/server (where it really belongs and can be included in the archives more easily).
=> feat(developer): compiler regression support (build kmcomp-$version.zip during release build) 🚦

ios/engine/KMEI/KeymanEngine/Classes/Manager.swift, ios/keyman/Keyman/Keyman/Classes/KMWebBrowser/BookmarksViewController.swift, ios/keyman/Keyman/Keyman/Classes/KMWebBrowser/WebBrowserViewController.swift, ios/keyman/Keyman/Keyman/Classes/KMWebBrowser/WebBrowserViewController.xib, ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift
This fulfills a similar role to #6836, just for the in-app browser instead of the in-app help.  To quote part of its description:
> Apple's official view is that the UIWebView, which is used by various parts of the app, is considered deprecated in favor of the WKWebView.
There was a bit more involved here, as this section is meant for general-purpose web-browsing, but it wasn't too rough to handle.
Fortunately, as these are two completely separate parts of the app... there's no need for us to actually _base_ this PR on #6836.  They can be merged separately and in either order without issue.
Feel free to test with _any_ iOS device.
TEST_6836_SUCCESS:  This test passes when - and only when - #6836 has passed all of its tests.
- The main layout changes are similar enough that I believe those …
=> chore(ios): updates core internals for the in-app browser

common/web/input-processor/src/text/inputProcessor.ts, common/web/input-processor/tests/cases/inputProcessor.js, common/web/keyboard-processor/src/text/keyboardProcessor.ts, common/web/keyboard-processor/src/text/systemStores.ts, developer/src/server/src/site/test.js
It turns out that postkeystroke rules weren't being processed correctly if they were following a physical keystroke.  The reason?  Internally, to detect the "context device" the rules should be applied to, the Web engine's keyboard API relies on the device supplied by the attached key event object.  Unfortunately, while we created a separate object for it... we were reusing the triggering event's device setting, not the one actually matching the host device.
Now, postkeystroke rules will consistently apply on touch devices, as they'll always be aware that they're _on_ touch devices for context processing.
----
Note that the text sequences below are very precisely defined.  When told to type something, type _exactly_ what is shown - no more and no less.
TEST_ANDROID_EXTERNAL:  Using an …
=> fix(web): postkeystroke processing should ignore key-event source🖇️

common/web/input-processor/src/text/inputProcessor.ts, common/web/keyboard-processor/src/text/kbdInterface.ts, common/web/keyboard-processor/src/text/keyboardProcessor.ts, web/source/keymanweb.ts, web/source/kmwbase.ts
Based on #6901.
Fixes two related issues:
1.  On a desktop platform, it's rather odd to have postkeystroke and newcontext rules auto-shifting the layer.  The user's using a physical keyboard; stay matched to that.
2.  Our current design says that hardware keystroke events should not affect the OSK's behavior in any way.
- Caveat:  _aftereffects_ of that keystroke - namely, postkeystroke and newcontext rules - may still affect the OSK.
For point 2 above, we've been stating this design for a while, but we never actually filtered out such layer-changing effects until now.
Use the standard "Test unminified Keymanweb" test page and the "English > Obolo Chwerty" keyboard for the following tests:
TEST_DESKTOP:  in standard desktop Chrome:
1. Release any pressed keyboard keys before swapping to …
=> fix(web): layer-setting ops should not trigger for hardware keystroke processing 🖇️

developer/src/kmdecomp/savekeyboard.cpp
Virtual character keys were being written as garbage, for example:
```
store(store17) [RALT ""] [RALT SHIFT ""] [RALT ""] [RALT SHIFT ''] [RALT SHIFT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT ""] [RALT SHIFT ""] [RALT ""] [RALT ""] [RALT ""] [RALT SHIFT ""]
store(store18) [RCTRL ""] [RCTRL SHIFT ""] [RCTRL ""] [RCTRL SHIFT ''] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL ""] [RCTRL SHIFT ""] [RCTRL ""] [RCTRL ""] [RCTRL ""] [RCTRL SHIFT ""]
```
Picked up in regression testing the compiler.
=> fix(developer): kmdecomp virtual character key output 🎾

developer/src/tike/Tike.dpr, developer/src/tike/main/UfrmMain.pas
Fixes #6928.
This was due to the main form not being destroyed in time during shutdown.
=> fix(developer): crash on exit when checking for updates 🎾

developer/src/tike/actions/dmActionsMain.pas
In rare circumstances, Keyman Developer can crash during startup if you try and switch back to a tab which is not yet available (Ctrl+Shift+Tab).
=> fix(developer): crash when switching back a tab 🎾

common/web/input-processor/src/text/prediction/languageProcessor.ts
Addresses a number of Sentry events (now merged into [KEYMAN-WEB-42](https://sentry.io/organizations/keyman/issues/3410147810/)) that started appearing after #6904 was merged.
Upon inspection of several events, it appears that we'll generally have an unset `OutputTarget` within that method during any keyboard swap.  The culprit: 
https://github.com/keymanapp/keyman/blob/04b8ae1ed1001680fdb177594616276a77ce2e57/common/web/input-processor/src/text/inputProcessor.ts#L47-L53
As you can't exactly pass two parameters into a property setter, there's not really any way around this... and it's not like this scenario is causing users any issues.  May as well just nix it, as it's not worth the Sentry noise.
Fixes KEYMAN-WEB-42.
=> chore(web): remove invalid warning msg

common/core/web/input-processor/src/text/inputProcessor.ts, common/core/web/input-processor/tests/cases/inputProcessor.js, common/core/web/keyboard-processor/src/text/kbdInterface.ts, common/core/web/keyboard-processor/src/text/keyboardProcessor.ts, common/core/web/keyboard-processor/src/text/systemStores.ts, developer/server/src/site/test.js, web/source/keymanweb.ts, web/source/kmwbase.ts
A combo-🍒 for both #6901 and #6902 - so, the full 🖇️ set.
There is one notable change from #6902, based on this comment: https://github.com/keymanapp/keyman/pull/6902#discussion_r916426897
Just in case we'd rather split this into two separate 🍒s, commit https://github.com/keymanapp/keyman/pull/6949/commits/9ffca15f643ead60efc810d454d2335c343d14ea is the final one from the first PR.
=> fix(web): context-only rule effects, set(&layer) from physical keystrokes 🖇️ 🍒

core/src/kmx/kmx_file.cpp, core/src/kmx/kmx_options.cpp
GCC 12 will output an error if the wrong `delete` is used.
Fixes #6930
=> fix(common): Fix `delete`

common/core/desktop/src/kmx/kmx_file.cpp, common/core/desktop/src/kmx/kmx_options.cpp
GCC 12 will output an error if the wrong `delete` is used.
Fixes #6930
(:cherries: picked from #6965)
=> fix(common): Fix `delete` :cherries: 

linux/debian/ibus-keyman.postinst
When the installation runs from `unattended-upgrade`, `$SUDO_USER` and `$USER` will probably not be set.
Fixes #6893
=> fix(linux): Another attempt at fixing postinst script

linux/debian/ibus-keyman.postinst
When the installation runs from `unattended-upgrade`, `$SUDO_USER` and `$USER` will probably not be set.
Fixes #6893
(:cherries:  picked from #6960)
=> fix(linux): Another attempt at fixing postinst script :cherries: 

linux/keyman-config/keyman_config/install_kmp.py
If the user doesn't have the permission to create a directory we now log an error.
Fixes #6967
=> fix(linux): Catch PermissionError exception

linux/keyman-config/keyman_config/install_kmp.py
If the user doesn't have the permission to create a directory we now log an error.
Fixes #6967
(:cherries: picked from #6968)
=> fix(linux): Catch PermissionError exception :cherries: 

developer/src/tike/Tike.dpr, developer/src/tike/Tike.dproj, developer/src/tike/actions/dmActionsMain.dfm, developer/src/tike/actions/dmActionsMain.pas, developer/src/tike/http/Keyman.Developer.System.ServerAPI.pas, developer/src/tike/http/Keyman.Developer.UI.ServerUI.pas, developer/src/tike/main/UfrmMain.dfm, developer/src/tike/main/UfrmMain.pas, developer/src/tike/project/Keyman.Developer.UI.Project.kmnProjectFileUI.pas, developer/src/tike/project/Keyman.Developer.UI.Project.kpsProjectFileUI.pas, developer/src/tike/project/Keyman.Developer.UI.Project.modelTsProjectFileUI.pas
Fixes #6897.
If Server is shut down, Keyman Developer now handles this better and offers to restart it in UI interactions, and backs out quietly in non-UI processes.
=> fix(developer): reduce timeouts if server shut down 🎾

windows/src/developer/kmdecomp/savekeyboard.cpp
Cherry-pick of #6940.
Virtual character keys were being written as garbage, for example:
```
store(store17) [RALT ""] [RALT SHIFT ""] [RALT ""] [RALT SHIFT ''] [RALT SHIFT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT SHIFT ""] [RALT ""] [RALT SHIFT ""] [RALT ""] [RALT ""] [RALT ""] [RALT SHIFT ""]
store(store18) [RCTRL ""] [RCTRL SHIFT ""] [RCTRL ""] [RCTRL SHIFT ''] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL SHIFT ""] [RCTRL ""] [RCTRL SHIFT ""] [RCTRL ""] [RCTRL ""] [RCTRL ""] [RCTRL SHIFT ""]
```
Picked up in regression testing the compiler.
=> fix(developer): kmdecomp virtual character key output 🎾 🍒

windows/src/developer/TIKE/actions/dmActionsMain.pas
Cherry-pick of #6942.
In rare circumstances, Keyman Developer can crash during startup if you try and switch back to a tab which is not yet available (Ctrl+Shift+Tab).
=> fix(developer): crash when switching back a tab 🎾 🍒

windows/src/developer/TIKE/Tike.dpr, windows/src/developer/TIKE/Tike.dproj, windows/src/developer/TIKE/actions/dmActionsMain.dfm, windows/src/developer/TIKE/actions/dmActionsMain.pas, windows/src/developer/TIKE/http/Keyman.Developer.System.ServerAPI.pas, windows/src/developer/TIKE/http/Keyman.Developer.UI.ServerUI.pas, windows/src/developer/TIKE/main/UfrmMain.dfm, windows/src/developer/TIKE/main/UfrmMain.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.kmnProjectFileUI.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.kpsProjectFileUI.pas, windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.modelTsProjectFileUI.pas
Cherry-pick of #6943.
Fixes #6897.
If Server is shut down, Keyman Developer now handles this better and offers to restart it in UI interactions, and backs out quietly in non-UI processes.
=> fix(developer): reduce timeouts if server shut down 🎾 🍒

linux/keyman-config/keyman_config/dbus_util.py, linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/uninstall_kmp.py, linux/keyman-config/keyman_config/view_installed.py
This will refresh the list of installed keyboards even when we install a keyboard from a command line tool, or from a second `km-config` instance.
Closes #6785.
- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
- **GROUP_WASTA**: Wasta 20.04 with Cinnamon
- Reboot
- open a terminal window and start Keyman Configuration by running `km-config`
- open a second terminal window and start a second instance of Keyman Configuration by running `km-config`
- take …
=> fix(linux): Implement refresh after keyboard installation

common/schemas/keyman-touch-layout/README.md, common/schemas/keyman-touch-layout/keyman-touch-layout.clean.spec.json, common/schemas/keyman-touch-layout/keyman-touch-layout.spec.json, developer/src/tike/oskbuilder/TouchLayout.pas, developer/src/tike/oskbuilder/TouchLayoutDefinitions.pas, developer/src/tike/xml/layoutbuilder/builder-charmap.js, developer/src/tike/xml/layoutbuilder/builder.css, developer/src/tike/xml/layoutbuilder/builder.js, developer/src/tike/xml/layoutbuilder/builder.xsl, developer/src/tike/xml/layoutbuilder/platform-controls.js, developer/src/tike/xml/layoutbuilder/prepare-key.js, developer/src/tike/xml/layoutbuilder/view-controls.js
I ended up with all the changes in one PR to support hints in Keyman Developer and the schema.
I reworked the touch layout editor to support hints, including moving the main control toolbar so that additional properties could be neatly fit into the design.
Green coloured hint text indicates that the hint has been customised:
I moved the delete button off the key cap itself so that it doesn't overlap the hint text:
I moved the controls off the top and into a left-hand-side toolbar, moving some functions into Edit dialogs so we have more flexibility for future functionality:
Hint text shows a placeholder of the default hint (in this case from the longpress) if no custom hint has been applied:
Platform properties dialog:
View options dialog:
Note that the "Show all …
=> feat(developer): add hint support to Touch Layout Editor and schema 🙊

android/KMEA/.idea/.gitignore, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Fixes #6981.
Cherry-pick of #6984.
Longpress menus were being triggered on any detected movement on keys on Android. This would cause rapid typing to periodically fail as the user would make a single-pixel movement while typing, which would then block subsequent key events.
This issue was introduced in #6637, which resolved a somewhat related problem with sticky longpress menus.
The fix is in three parts:
1. Remove the touch movement detection which caused the primary problem
2. Address some logic issues around visibility of `subkeysWindow` which meant that the longpress delay trigger was never fired.
3. Introduce a new 'scroll' gesture handler which detects a negative-y movement above a 5px threshold, to open the longpress menu.
The 5px threshold is the minimum default used by Keyman …
=> fix(android): rework longpress movement trigger 🎁 🍒

android/KMEA/.idea/.gitignore, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Fixes #6981.
Longpress menus were being triggered on any detected movement on keys on Android. This would cause rapid typing to periodically fail as the user would make a single-pixel movement while typing, which would then block subsequent key events.
This issue was introduced in #6637, which resolved a somewhat related problem with sticky longpress menus.
The fix is in three parts:
1. Remove the touch movement detection which caused the primary problem
2. Address some logic issues around visibility of `subkeysWindow` which meant that the longpress delay trigger was never fired.
3. Introduce a new 'scroll' gesture handler which detects a negative-y movement above a 5px threshold, to open the longpress menu.
The 5px threshold is the minimum default used by Keyman Engine for Web. However, …
=> fix(android): rework longpress movement trigger 🎁

linux/Jenkinsfile, linux/debian/changelog
This change updates the changelog to keep it in sync with Debian where PR #6966 got applied to the current stable version.
Also remove outdated impish and add kinetic.
=> chore(linux): Update changelog

linux/debian/changelog
This change updates the changelog to keep it in sync with Debian where PR #6966 got applied to the current stable version.
(🍒-picked from PR #6987)
=> chore(linux): Update changelog 🍒

developer/src/tike/child/Keyman.Developer.UI.UfrmModelEditor.dfm, developer/src/tike/child/Keyman.Developer.UI.UfrmModelEditor.pas, developer/src/tike/main/Keyman.Developer.System.LexicalModelParser.pas
Fixes #7007.
While the LexicalModelParser is not a pretty class, I don't want to spend lots of energy on it at this time, given we hope to rewrite in Typescript at some point.
@keymanapp-test-bot skip (I have verified sufficiently myself, I think.)
=> feat(developer): add languageUsesCasing to Model Editor

developer/src/server/package.json, developer/src/server/src/handlers/api/debugobject/get.ts, developer/src/server/src/handlers/api/debugobject/unregister.ts
When rebuilding a model, Keyman Developer would query for the registered model, but a missing simplifyId call meant that it never matched the model name (due to `.` vs `_`).
=> fix(developer): rebuilding a model would not refresh it in server 🎾

developer/server/package.json, developer/server/src/handlers/api/debugobject/get.ts, developer/server/src/handlers/api/debugobject/unregister.ts
Cherry-pick of #7015.
When rebuilding a model, Keyman Developer would query for the registered model, but a missing simplifyId call meant that it never matched the model name (due to `.` vs `_`).
=> fix(developer): rebuilding a model would not refresh it in server 🎾 🍒

web/unit_tests/cases/attachmentAPI.js, web/unit_tests/cases/basics.js, web/unit_tests/cases/engine.js, web/unit_tests/cases/engine_chirality.js, web/unit_tests/cases/events.js, web/unit_tests/cases/text_selection.js, web/unit_tests/test_utils.js
Based on #7024.
Fixes #5799.
Much of Keyman Engine for Web's unit test setup code was written when we still supported IE (which lacked Promise support) and had no use for `Promise`s (that is, before version 12.0).  What we've had until now has worked "well enough", but it appears there may be some possible "holes" in that concurrency logic that might be behind some of the unit-test instability we see in our automated checks from time to time.
So, it's time to retire some tech-debt and make those unit tests more stable and clearer to read by converting relevant code over to `Promise`-based synchronization.  This also allows some aspects of the setup to execute in parallel via `Promise.all()`.  Not only does that make waiting for dual script loads _way_ cleaner and clearer... it should help …
=> refactor(web): converts test_utils funcs to Promise use 🤝

core/build.sh, core/src/kmx/kmx_debugger.cpp, core/tests/unit/kmnkbd/debug_api.cpp, core/tests/unit/kmnkbd/meson.build, core/tests/unit/kmx/meson.build, docs/build/macos.md, docs/build/windows.md, resources/build/trigger-definitions.inc.sh
Updates search for emscripten if not on path, and fixes up unit test infrastructure for wasm builds for new tests.
Note that Linux config instructions do not currently list details on how to configure dependencies such as emscripten. This is a separate project!
=> chore(core): get wasm core building again

common/web/keyman-version/build.sh, core/build.sh, core/gettier.sh, mac/setup/build.sh, resources/build/build-utils.sh, resources/build/build-utils.test.sh, resources/shellHelperFunctions.sh
Fixing up a number of minor bits and pieces identified during demo:
* invalid action or :target would not be picked up if paired with a valid one (e.g.: build:foo should not have worked)
* colors defined in both shellHelperFunctions and build-utils were problematic; able to remove them from shellHelperFunctions because all references included both scripts
* builder_has_action and builder_report now allow both `action:target` and `action :target`
* keyman-version/build.sh did not have working test action...
=> chore(common): build-utils.sh minor tweaks

windows/src/developer/TIKE/project/Keyman.Developer.UI.Project.kmnProjectFileUI.pas
Cherry-pick of #7031.
Fixes #7030.
Prevents a stack overflow / loop when the web target is removed from a keyboard and it has already been tested on web, and the user presses the Compile button.
=> fix(developer): stack overflow when compiling non-web keyboard 🎾 🍒

windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
Cherry-pick of #7033.
Fixes #7032.
=> fix(developer): prevent crash attempting to compile ansi keyboard 🎾 🍒

web/source/kmwutils.ts, web/source/osk/anchoredOskView.ts
Based on #6787, as its user test issues motivated development of this PR.
So, it turns out there there are some very strange issues with how `window.innerWidth` updates on mobile devices, and these issues were behind the failed user tests.  It appears that the best approach for detecting screen width (what the mobile-form OSK uses) is actually `document.documentElement.clientWidth`.  (Minor reference: https://stackoverflow.com/a/54812656)
Relying upon that, along with some other shifts to how the mobile-form OSK computes its preferred height, appear to stabilize the base PR's issues.  That said, these are some notable shifts to how the calculations are done, and there may be noteworthy history behind why things were the way that they were, so I expect some scrunity in the review & in the …
=> change(web): updates mobile screen dimension detection code ⬅️

common/windows/cpp/include/legacy_kmx_file.h, common/windows/delphi/keyboards/kmxfile.pas, core/src/kmx/kmx_file.h
Part of #7045.
Indicates that the .kmx file has additional header structure immediately following the COMP_KEYBOARD header. Used by KMXPlus file format for supporting LDML keyboards. Requires VERSION_160 or higher in keyboard file.
=> chore(common): add KF_KMXPLUS dwFlag value 🙀

linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/km-package-install, linux/keyman-config/tests/test_uninstall_kmp.py
Fixes #6955.
- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
- Reboot
- **TEST_CLI_INST:** Run `km-package-install`. Verify that you get an error message, but no deprecation warning.
- **TEST_CLI_INST_PKG:** Run `km-package-install -p sil_korda_jamo`. Verify that this adds the "Korean KORDA Jamo (SIL)" keyboard to the keyboard dropdown.
- **TEST_CLI_INST_PKG2:** Run `km-package-install -p sil_korda_jamo` a second time. Verify that it shows the message _"km-package-install: Version 3.0 of the sil_korda_jamo keyboard …
=> feat(linux): Replace deprecated distutils

core/include/keyman/keyboardprocessor.h
=> docs(core): cleanup in keyboardprocessor.h

common/include/km_types.h, common/include/kmx_file.h, common/web/keyboard-processor/src/text/codes.ts, common/windows/cpp/include/legacy_kmx_file.h, core/include/keyman/keyboardprocessor.h, core/include/keyman/keyboardprocessor_bits.h, core/include/meson.build, core/meson.build, core/src/kmx/kmx_base.h, core/src/kmx/kmx_processevent.h, core/src/meson.build, core/tests/unit/kmnkbd/meson.build, core/tests/unit/kmnkbd/test_kmx_xstring.cpp, docs/settings/linux/c_cpp_properties.json, docs/settings/linux/tasks.json, linux/debian/rules, linux/ibus-keyman/README.md, linux/ibus-keyman/tests/Makefile.am, linux/scripts/build.sh, linux/scripts/dist.sh, windows/src/engine/keyman32/Keyman32.vcxproj, windows/src/engine/keyman64/keyman64.vcxproj
Part of the kmcompx refactor. We want the definitions in kmx_file.h rather than continuing to use legacy_kmx_file.h.
=> chore(core): refactor kmx_file.h to common 🚑

developer/src/tike/project/Keyman.Developer.UI.Project.kmnProjectFileUI.pas
Fixes #7030.
Prevents a stack overflow / loop when the web target is removed from a keyboard and it has already been tested on web, and the user presses the Compile button.
* **TEST_COMPILE:** Make sure the compiler no longer goes into a loop and crashes.
1. Create a new keyboard project, targeting 'all'
2. Compile the keyboard, and start a web test on it.
3. Change the `store(&targets)` line to `store(&targets) 'windows'`
4. Press Compile again.
5. The compiler should only compile once!
(Note: you may want to test this procedure in 15.0.267 to observe it going wrong!)
=> fix(developer): stack overflow when compiling non-web keyboard 🎾 

developer/src/tike/compile/CompileKeymanWeb.pas
Fixes #7032.
* **TEST_COMPILE:** Make sure compiler no longer crashes when building an ANSI keyboard for web
1. Create a new keyboard project, targeting 'web' platform
2. Change the `begin Unicode` line in the .kmn to `begin ANSI > use(main)`
3. Compile the keyboard: the compiler should give an error message: 'A "begin unicode" statement is required to compile a KeymanWeb keyboard' but should not crash Keyman Developer.
=> fix(developer): prevent crash attempting to compile ansi keyboard 🎾

linux/scripts/jenkins.sh
- use standard Keyman include scripts
- remove package build support for legacy projects
- install dependencies from `debian/control` file instead of maintaining a separate list
=> chore(linux): Refactor `jenkins.sh`

developer/src/tike/compile/CompileKeymanWeb.pas
Picked up while reviewing code for conversion to C++. The compiler could, in some circumstances emit garbage code for readonly groups because we weren't testing all scenarios correctly. In practice, this would have been rare as readonly groups don't emit characters, but it should be fixed!
=> fix(developer): compiler emitting garbage for readonly groups 🎾

windows/src/developer/TIKE/compile/CompileKeymanWeb.pas
Picked up while reviewing code for conversion to C++. The compiler could, in some circumstances emit garbage code for readonly groups because we weren't testing all scenarios correctly. In practice, this would have been rare as readonly groups don't emit characters, but it should be fixed!
=> fix(developer): compiler emitting garbage for readonly groups 🎾 🍒

web/source/kmwuibutton.ts, web/source/kmwuifloat.ts, web/source/kmwuitoolbar.ts
Cleans up some code that's proving problematic for some of our unit tests; there's some cross-UI-module pollution happening on occasion that turns into a race condition of sorts.
=> fix(web): button, float init timer cleanup

core/include/keyman/keyboardprocessor.h, core/python/keyman/keyboardprocessor/_api.py, core/python/keyman/keyboardprocessor/api.py, core/src/km_kbp_processevent_api.cpp, core/src/kmx/kmx_processor.cpp, core/src/kmx/kmx_processor.hpp, core/src/ldml/ldml_processor.cpp, core/src/ldml/ldml_processor.hpp, core/src/mock/mock_processor.cpp, core/src/mock/mock_processor.hpp, core/src/processor.hpp, core/tests/unit/kmnkbd/debug_api.cpp, core/tests/unit/kmnkbd/state_api.cpp, core/tests/unit/kmx/kmx.cpp, core/tests/unit/kmx/kmx_imx.cpp, core/tests/unit/ldml/ldml.cpp, developer/src/tike/child/UfrmDebug.pas, developer/src/tike/main/Keyman.System.KeymanCore.pas, developer/src/tike/main/Keyman.System.VisualKeyboardImportKMX.pas, linux/ibus-keyman/src/engine.c, windows/src/engine/keyman32/kmprocess.cpp
- Width: uint16_t
- defined `km_kbp_event_flags` to define the bitfield
- bitfield has value `KM_KBP_EVENT_FLAG_TOUCH` for touch events
- ignored everywhere, currently
Fixes: #7046 
=> feat(core): add event_flags to process_event #7046 🙀 

docs/CODEOWNERS
As discussed, we are changing some of the platform advocates for (a) geographical, and (b) platform familiarity reasons. This will be reflected in the automatic assignment of reviewers on PRs.
We are pretty much all affected in this shuffle!
=> chore: Change platform advocates per discussion

windows/src/engine/keyman32/kmprocess.cpp, windows/src/engine/keyman32/kmprocessactions.cpp, windows/src/engine/keyman32/kmprocessactions.h
Fixes #7078 
Rename ProcessActionsTestParse to NonUpdatable parse as it does more than just test. Add handling for the invalidate context action to this parse. In the case when an emit keystroke is in the action list it will be emitted and the Updateable round will never occur so we need to invalidate the context now in the non-updatable parse.
Install the keyman for windows build associated with this PR
The key referred to as "enter" also has key cap labelled "return" on many keyboards.
**TEST_ENTER_INVALIDATE**
1. Install gff_ethiopic_7 from Keyman.com [Ethiopic - (Language Neutral)](https://keyman.com/keyboards/gff_ethiopic_7) 
2. Open Notepad
3. Select  Ethiopic - (Language Neutral) as the current keyboard.
4. Type <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd><kbd>Enter</kbd><kbd>a< …
=> fix(windows): Add invalidate context action to non-updatable parse

resources/build/build-utils.sh, resources/build/build-utils.test.sh
This PR is cherry-picked from #7101, to bring new build-utils.sh functionality into alpha outside of the feature-ldml branch timeline.
The changes here allows you to define variables for parameters, where you need to pass additional data on the command line.
First, use `builder_describe` to add an option, with a variable name, for example (cut down example here from the original PR):
```
builder_describe "Build Keyman LDML Keyboard Compiler kmldmlc" \
"bundle                   Creates a bundled version of kmldmlc" \
"--build-path=BUILD_PATH  Build directory for bundle"
```
Adding `=VAR` to the option definition means that the builder_ utils will expect a second parameter after the option, for example:
```
./build.sh bundle --build-path /tmp/foo
```
This new option will be made available …
=> feat(common): add parameter variable support to `builder_` functions

core/include/ldml/.gitignore, core/include/ldml/package.json, core/include/ldml/tsconfig.build.json, core/tools/ldml-const-builder/build.sh, developer/src/kmldmlc/src/keyman/kmx/kmx-plus.ts, developer/src/kmldmlc/tsconfig.json, package-lock.json, package.json
Splits the building of keyboardprocessor_ldml.h into a separate tsconfig.build.json, and designates keyboardprocessor_ldml.ts as a new Typescript/Node module @keymanapp/ldml-keyboard-constants.
Includes an example usage in the (currently unused) kmx-plus.ts.
=> feat(core): turn @keymanapp/ldml-keyboard-constants into a module 🙀

docs/CODEOWNERS
As discussed, we are changing some of the platform advocates for (a) geographical, and (b) platform familiarity reasons. This will be reflected in the automatic assignment of reviewers on PRs.
We are pretty much all affected in this shuffle!
This 🍒-pick is necessary so that PRs for `stable-15.0` will assign the "new" reviewers.
(🍒-picked from PR #7096 )
=> chore: Change platform advocates per discussion 🍒

windows/src/engine/keyman32/kmprocess.cpp, windows/src/engine/keyman32/kmprocessactions.cpp, windows/src/engine/keyman32/kmprocessactions.h
Cherry Pick from #7089 
Rename ProcessActionsTestParse to NonUpdatable parse as it does more than just test. Add handling for the invalidate context action to this parse. In the case when an emit keystroke is in the action list it will be emitted and the Updateable round will never occur so we need to invalidate the context now in the non-updatable parse.
=> fix(windows): Add invalidate context action to non-updatable parse 🍒

android/KMEA/app/src/main/res/values-land/dimens.xml, android/KMEA/app/src/main/res/values-sw600dp-land/dimens.xml, android/KMEA/app/src/main/res/values-sw720dp-land/dimens.xml
Fixes #7085
The maximum keyboard heights in landscape orientation from #5606 are too high, making the in-app keyboard unusable at max height. If the suggestion banner is enabled, the in-app keyboard even fails to display.
This PR lowers the maximum heights so that keyboards with suggestion banners can be used.
**Setup for each test** - Have Android Emulator for the following devices (SDK can be any version between 21 <= 30
TEST_PIXEL2_DEFAULT - Tests landscape orientation on phones
1. On Pixel 2 emulator, install the PR build of Keyman for Android
2. Rotate the device to landscape orientation and launch the Keyman app (you may need to hit the system icon on the bottom taskbar for the screen to rotate to landscape)
3. In the Keyman app, go to Settings --> Adjust Keyboard Height
4. In the …
=> fix(android/engine): Lower the max height for landscape orientation

android/KMEA/app/src/main/res/values-land/dimens.xml, android/KMEA/app/src/main/res/values-sw600dp-land/dimens.xml, android/KMEA/app/src/main/res/values-sw720dp-land/dimens.xml
Cherry-pick of #7119 to stable-15.0 
The maximum keyboard heights in landscape orientation from #5606 are too high, making the in-app keyboard unusable at max height. If the suggestion banner is enabled, the in-app keyboard even fails to display.
This PR lowers the maximum heights so that keyboards with suggestion banners can be used.
**Setup for each test** - Have Android Emulator for the following devices (SDK can be any version between 21 <= 30
TEST_PIXEL2_DEFAULT - Tests landscape orientation on phones
1. On Pixel 2 emulator, install the PR build of Keyman for Android
2. Rotate the device to landscape orientation and launch the Keyman app (you may need to hit the system icon on the bottom taskbar for the screen to rotate to landscape)
3. In the Keyman app, go to Settings --> Adjust …
=> fix(android/engine): :cherries: Lower the max height for landscape orientation

docs/build/linux-ubuntu.md, linux/Dockerfile
- add Dockerfile in linux/Dockerfile, referencing linux/debian/control
- add docs in docs/build/linux-ubuntu.md
Fixes: #7102
=> feat(linux): Dockerfile for linux builder

.github/labeler.yml
Move core/ to its own top-level label (not common/core/ any more.)
=> chore: update core/ label

core/src/kmx/kmx_plus.h, developer/src/kmldmlc/package.json, developer/src/kmldmlc/src/kmldmlc.ts, developer/src/kmldmlc/test/README.md, developer/src/kmldmlc/test/fixtures/basic.txt, developer/src/kmldmlc/test/fixtures/basic.xml, developer/src/kmldmlc/test/helpers/index.ts, developer/src/kmldmlc/test/test-base.ts, developer/src/kmldmlc/test/test-compiler-e2e.ts, developer/src/kmldmlc/test/tsconfig.json, developer/src/kmldmlc/tsconfig.json
Establishes a basic set of unit and e2e tests for the LDML keyboard compiler, giving me a place to put additional tests.
I'm using hextobin for the binary generation of .kmx for comparison for test. It's a lot of work to hand-craft. But doing it automatically or including binary fixtures has the downside of probably failing to actually check that the generated file is valid!
=> feat(developer): unit test framework for kmldmlc 🙀

core/src/kmx/kmx_plus.cpp, core/src/kmx/kmx_plus.h, core/src/ldml/C7043_ldml.md, core/src/ldml/ldml_processor.cpp, core/src/ldml/ldml_processor.hpp
- don't reparse structs on each keydown, read into memory
- improve validation
- move validation into constructor
- validate length of data
- don't retain the raw .kmx data at runtime
#5015 
and of course,
=> feat(core): ldml: improve file reading/validation 🙀

linux/scripts/jenkins.sh
When install the keyman-build-deps_*.deb file it can happen that we end up with a lower version number than what we previously
built. This change allows downgrades so that the build dependencies can be installed.
=> fix(linux): Allow downgrades for installing build deps

core/wasm.build.linux.in
This is a cherry-pick of 0057b7d95c23d3314b847e88a5738641ef7ed18d (from #7129) just so we can get WASM tests passing for other PRs before we merge feature-ldml.
=> chore(core): emcc off path for linux

core/include/ldml/keyboardprocessor_ldml.ts, developer/src/kmldmlc/src/keyman/compiler/compiler.ts, developer/src/kmldmlc/src/keyman/compiler/keys.ts, developer/src/kmldmlc/src/keyman/compiler/loca.ts, developer/src/kmldmlc/src/keyman/compiler/meta.ts, developer/src/kmldmlc/src/keyman/compiler/section-compiler.ts, developer/src/kmldmlc/src/keyman/kmx/kmx-plus.ts, developer/src/kmldmlc/src/keyman/ldml-keyboard/ldml-keyboard-xml-reader.ts, developer/src/kmldmlc/src/kmldmlc.ts, developer/src/kmldmlc/test/test-compiler-e2e.ts
Makes each section compiler a pure function. Good for testing in the future.
Well, almost. There are still callback side-effects for messages. These may in future be returned as an array as well, eliminating the need for a message callback.
But restructures each section compiler so that it is self-contained and responsible only for writing its own section. Also tightens up the types for the sections constants.
Last, but not least, moves responsibility for writing the output .kmx out of compiler.ts and into its callers -- removing one dependency from the compiler. Reading input files still needs to be done in the compiler, as there may be multiple input files with `<import>` that we cannot know about until we start parsing xml.
=> refactor(developer): each section compiler is a pure function 🙀

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
:cherries: pick of #7156 to stable-15.0
When the subkeys window is dismissed, the subKeysList isn't cleared, so holding backspace key or globe key would end up displaying the previous longpress menu.
We need to re-run the main test from #6984, first, to verify that this does not re-introduce new bugs.
Setup - A physical Android device. Don't use emulator because the scenario involves typing fast on the OSK (e.g. two thumbs)
* **TEST_POPUPS** - Verify popup keys don't get stuck on
1. On the Android device, install the PR build of Keyman for Android
3. In the Keyman app, start typing with the default sil_euro_latin.
4. Type on the OSK using the following scenarios and verify expected output:
* Clicking a suggestion on the suggestion banner - should insert …
=> fix(android/engine): :cherries: Cleanup list of subkeys when dismissing window

developer/src/kmldmlc/src/keyman/compiler/errors.ts, developer/src/kmldmlc/src/keyman/compiler/loca.ts, developer/src/kmldmlc/src/keyman/ldml-keyboard/ldml-keyboard-xml-reader.ts, developer/src/kmldmlc/src/keyman/ldml-keyboard/ldml-keyboard-xml.ts, developer/src/kmldmlc/test/fixtures/sections/loca/invalid-locale.xml, developer/src/kmldmlc/test/fixtures/sections/loca/minimal.xml, developer/src/kmldmlc/test/fixtures/sections/loca/multiple.xml, developer/src/kmldmlc/test/test-loca.ts, developer/src/kmldmlc/tsconfig.json
Note: bumps target to es2020 for better Intl.* support. Verified as supported by Node 16+ and modern browsers.
Adds support for multiple locales and basic canonicalization. Does not support normalization of locales.
=> feat(developer): add loca tests 🙀

developer/src/kmldmlc/src/keyman/compiler/callbacks.ts, developer/src/kmldmlc/src/keyman/compiler/errors.ts, developer/src/kmldmlc/src/keyman/compiler/keys.ts, developer/src/kmldmlc/src/keyman/compiler/loca.ts, developer/src/kmldmlc/src/keyman/compiler/meta.ts, developer/src/kmldmlc/src/kmldmlc.ts, developer/src/kmldmlc/test/helpers/index.ts, developer/src/kmldmlc/test/test-loca.ts, developer/src/kmldmlc/test/test-meta.ts
Yeah two for the price of one:
- minimize locales at compile time
- cleans up the list of errors to make it easier to maintain and use
TODO -- on follow-up PRs:
- Add kmldmlc test to developer test build -> see #7180
- Ensure that DTD is used when verifying XML files -> see #7181
=> feat(developer): loca minimization + cleanup kmldmlc error list 🙀

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudLexicalModelMetaDataDownloadCallback.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java
Fixes #7170
To minimize UX distractions, this PR removes Toast notifications when nothing new is happening (installed/updated).
The dictionary query on the Language Settings menu will still notify the app is "Checking for associated dictionary to download" to give the user feedback on the menu.
* **TEST_REDUCED_TOAST_NOISE** - Verifies the number of Toast notifications are reduced
2. Launch the app and observe the "Get Started" menu is displayed
3. Verify there's no Toast notification about checking the cloud catalog for updates
4. Dismiss the "Get Started" menu and  go to Keyman settings --> Installed Languages
5. Click on "+" and search for "afade" language keyboard to install (install a keyboard that has no associated dictionary)
6. Install …
=> chore(android): Reduce Toast notification noise

linux/debian/ibus-keyman.postinst
When installing ibus-keyman it could happen that we got an (ignored) error "user name does not exist". This change tries to work around this problem.
=> chore(linux): Fix ibus-keyman.postinst script

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Fixes #7069, fixes #7172, and fixes #7155 and follow-on to #6984
When the subkeys window is dismissed, the subKeysList isn't cleared, so holding backspace key would end up displaying the previous longpress menu.
We need to re-run the main test from #6984, first, to verify that this does not re-introduce new bugs.
Setup - A physical Android device. Don't use emulator because the scenario involves typing fast on the OSK (e.g. two thumbs)
* **TEST_POPUPS** - Verify popup keys don't get stuck on
1. On the Android device, install the PR build of Keyman for Android
3. In the Keyman app, start typing with the default sil_euro_latin.
4. Type on the OSK using the following scenarios and verify expected output:
* Clicking a suggestion on the suggestion banner - …
=> fix(android/engine): Fix Backspace key to delete without errant subkeys

developer/src/kmlmc/Makefile, developer/src/test/auto/Makefile
Fixes #7180.
Also removes `-test` from normal `make build` for kmlmc, moving that responsibility to `make test` (but uses `-tdd` to avoid rebuild).
=> feat(developer): add kmlmc and kmldmlc to `make test` 🙀

developer/src/kmldmlc/build.sh, developer/src/kmldmlc/package.json, developer/src/kmldmlc/src/keyman/compiler/callbacks.ts, developer/src/kmldmlc/src/keyman/compiler/errors.ts, developer/src/kmldmlc/src/keyman/ldml-keyboard/ldml-keyboard-xml-reader.ts, developer/src/kmldmlc/src/kmldmlc.ts, developer/src/kmldmlc/test/fixtures/invalid-conforms-to.xml, developer/src/kmldmlc/test/fixtures/invalid-structure-per-dtd.xml, developer/src/kmldmlc/test/helpers/index.ts, developer/src/kmldmlc/test/ldml-keyboard/test-ldml-keyboard-xml-reader.ts, developer/src/kmldmlc/test/test-compiler-e2e.ts, developer/src/kmldmlc/test/test-loca.ts, developer/src/kmldmlc/test/test-meta.ts, package-lock.json, resources/standards-data/ldml-keyboards/readme.md, resources/standards-data/ldml-keyboards/techpreview/ldml-keyboard.schema.json, resources/standards-data/ldml-keyboards/techpreview/ldmlKeyboard.xsd
Fixes #7181.
As we do not appear to have access to a good DTD validation library in Node.js, we will instead convert the DTD to a JSON schema file and use that for validation.
I have not verified every aspect of the JSON schema at this point, but will incrementally do so as I implement further aspects of the compiler.
This updates all the testing to use the schema. As the schema validation is slow, I have increased the 'normal' time for tests.
=> feat(developer): use json schema to verify source file 🙀

common/tools/hextobin/hextobin.ts, common/tools/hextobin/index.ts, common/tools/hextobin/package.json, core/tests/unit/ldml/invalid-keyboards/ik_000_null_invalid.txt, developer/src/kmldmlc/test/fixtures/basic.txt
This makes it easier to write a binary file which contains offsets and size values. Using this for unit tests for the LDML keyboard compiler.
Example kmldmlc basic.txt is updated and included.
Future enhancement suggestion: include count() for repeated blocks and index() for block indices within these repeated blocks. Would be very useful for string tables in the example ref.
The real benefit can be seen in the follow-up PR #7187 with far fewer changes required to basic.txt fixture for an additional field.
=> feat(common): add size and offset calculators to hextobin 🙀

core/src/ldml/C7043_ldml.md, developer/src/kmldmlc/src/keyman/kmx/kmx-plus-builder.ts, developer/src/kmldmlc/test/fixtures/basic.txt
Per C7043_ldml.md:
> The first string in the string table MUST always be the zero-length string. A zero-length string is considered the same as a null string. For metadata fields, references to this zero-length string will have the dword index value 0, which can safely be interpreted as "not set". There may be other locations which have required strings, but for which a zero-length string is permissible, and this index value of 0 can be used for that purpose.
>
> A distinction between zero-length string and optional should be avoided (e.g. the difference between "" and null in Javascript). If this is truly required, a separate flag field must be used to denote the difference.
The second commit is just formatting on C7043_ldml.md.
=> chore(core): define zero length string vs null string for kmxplus 🙀

common/tools/hextobin/hextobin.ts, common/tools/hextobin/index.ts, developer/src/kmldmlc/test/fixtures/basic.txt
Adds an `index` command as suggested by #7186.
> Future enhancement suggestion: include ... index() for block indices within these repeated blocks. Would be very useful for string tables in the example ref.
Turns out the also suggested `count()` can be done with `index()` so didn't add that.
Uses `index()` for string references and count of strings in basic.txt.
Reformat basic.txt to make it more readable as it will get less 'basic' over time!
=> feat(common): hextobin `index` command 🙀

developer/src/kmldmlc/src/keyman/compiler/errors.ts, developer/src/kmldmlc/src/keyman/compiler/loca.ts, developer/src/kmldmlc/test/test-loca.ts
If a loca entry is either formatted wrongly (e.g. wrong case), or is not minimal, then the compiler will now report a hint.
=> feat(developer): add compiler hint for non-minimal loca 🙀

developer/src/kmldmlc/src/keyman/compiler/keys.ts, developer/src/kmldmlc/src/keyman/compiler/loca.ts, developer/src/kmldmlc/src/keyman/compiler/messages.ts, developer/src/kmldmlc/src/keyman/compiler/meta.ts, developer/src/kmldmlc/src/keyman/ldml-keyboard/ldml-keyboard-xml-reader.ts, developer/src/kmldmlc/src/kmldmlc.ts, developer/src/kmldmlc/test/ldml-keyboard/test-ldml-keyboard-xml-reader.ts, developer/src/kmldmlc/test/test-loca.ts, developer/src/kmldmlc/test/test-meta.ts
Just wanted to rename this to make it clearer. Also added a prefix to each message generator to indicate the type of message, as otherwise it is not obvious within the compiler which messages are going to cause the compiler to fail.
Note that the message generator function prefixes are Title Cased whereas the message identifier constant prefixes are CAPS. I guess this could be confusing but I think it works okay in practice.
=> refactor(developer): kmldmlc - rename `CompilerErrors` to `CompilerMessages` 🙀

developer/src/kmldmlc/src/keyman/compiler/compiler.ts, developer/src/kmldmlc/src/keyman/compiler/messages.ts, developer/src/kmldmlc/src/keyman/compiler/section-compiler.ts, developer/src/kmldmlc/src/keyman/compiler/vkey.ts, developer/src/kmldmlc/src/keyman/ldml-keyboard/ldml-keyboard-xml-reader.ts, developer/src/kmldmlc/src/keyman/ldml-keyboard/ldml-keyboard-xml.ts, developer/src/kmldmlc/src/keyman/ldml-keyboard/us-virtual-keys.ts, developer/src/kmldmlc/test/fixtures/basic.txt, developer/src/kmldmlc/test/fixtures/basic.xml, developer/src/kmldmlc/test/fixtures/sections/vkey/invalid-from-vkey.xml, developer/src/kmldmlc/test/fixtures/sections/vkey/invalid-repeated-vkey.xml, developer/src/kmldmlc/test/fixtures/sections/vkey/invalid-to-vkey.xml, developer/src/kmldmlc/test/fixtures/sections/vkey/minimal.xml, developer/src/kmldmlc/test/fixtures/sections/vkey/redundant.xml, developer/src/kmldmlc/test/fixtures/sections/vkey/same-target.xml, developer/src/kmldmlc/test/test-vkey.ts, resources/standards-data/ldml-keyboards/techpreview/ldml-keyboard.schema.json
vkeyMaps table compiler, unit test, and fixes to json schema. Adds a vkeyMaps entry to the basic e2e test.
us-virtual-keys.ts has a new mapping for CLDR VKey Enums, but I will tweak this in an upcoming commit to use constants instead of hard-coded values.
=> feat(developer): add vkey support 🙀

developer/src/kmldmlc/test/test-compiler-e2e.ts, developer/src/kmldmlc/test/test-messages.ts
The purpose of these tests is to ensure that our slightly WET constant definitions for compiler errors are consistent in their usage:
* that names are consistent between the message functions and constants
* that constants have unique codes
* that constants have the right error mask for their type
This means we don't have to worry about DRYing out the constants, which would probably require us to have a preprocessing step, which has its own negatives.
Also, added more reporting to e2e test in case of failures.
=> chore(developer): add test for compiler messages and cleanup e2e test 🙀

common/models/templates/package.json, common/models/templates/test/helpers.js, common/models/templates/test/test-common.js, common/models/templates/test/test-priority-queue.js, common/models/templates/test/test-quote-behavior.js, common/models/templates/test/test-tokenization.js, common/models/templates/test/test-trie-model.js, common/models/templates/test/test-trie-traversal.js, common/models/templates/tsconfig.bundled.json, common/models/wordbreakers/package.json, common/models/wordbreakers/src/default/index.ts, common/models/wordbreakers/test/test-ascii-word-breaker.js, common/models/wordbreakers/test/test-default-word-breaker.js, common/models/wordbreakers/test/test-placeholder-word-breaker.js, common/predictive-text/unit_tests/test.sh, common/web/utils/package.json, package-lock.json
So, it turns out that during the big 🎡 chain in which we reorganized much of the Web-related part of the repo, there were a few sets of unit tests that never got reconnected.  Heck, even I missed 'em at the time.
Ran into this while investigating the wordbreaker via unit tests - I quickly realized that they were disconnected, which led me to this.  Any work on enhancing the wordbreaker needs these tests fixed first.
=> fix(common/models): reconnects unit tests for worker-internal submodules 🎡

common/models/wordbreakers/src/default/index.ts, common/models/wordbreakers/test/test-default-word-breaker.js
As I'm looking at predictive text issues for non-Roman script languages this sprint, and this may lead me to add features to the wordbreaker... I felt we should probably get some more explicit and directed unit tests in place for our main wordbreaker.  This will help verify that any to-be-done modifications don't break things by mistake.
I did crib a test or two from https://github.com/eddieantonio/unicode-default-word-boundary/blob/master/test/test-split-words.ts, but I tried to go more robust where possible, aside from the emoji-flag case.  Those tests are MIT-licensed, so no worries there.
=> feat(common/models): extra Unicode-based wordbreaker unit tests

core/src/kmx/kmx_plus.cpp, core/src/kmx/kmx_plus.h, core/src/kmx/kmx_xstring.cpp, core/src/kmx/kmx_xstring.h, core/src/ldml/ldml_processor.cpp, core/tests/unit/kmnkbd/test_kmx_xstring.cpp, core/tests/unit/ldml/test_kmx_plus.cpp
- remove hacky utf-32 processing
- add utf-32 test case to test_kmx_plus.cpp
- change kmx_plus to return std::u16string
- kmx_xstring: add Uni_IsBMP() macro
Fixes: #7134
=> fix(core): ldml: improve utf-32 handling 🙀

core/src/kmx/kmx_actions.cpp, core/src/kmx/kmx_processor.cpp, core/src/kmx/kmx_xstring.cpp, core/src/kmx/kmx_xstring.h, core/tests/unit/kmx/kmx.cpp, core/tests/unit/ldml/ldml.cpp
- move Utf32CharToUtf16 to inline
- remove Is_SMP and call sites, use Utf32CharToUtf16 instead.
For: #7134
I did not modify call sites that are using the windows unicode.h
=> chore(core): improve xstring macros 🙀

android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMPLink.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/KMPLinkTest.java, common/windows/delphi/general/Upload_Settings.pas, ios/engine/KMEI/KeymanEngine/Classes/KeymanHosts.swift, linux/keyman-config/keyman_config/__init__.py, mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
Fixes #7227.
We want to use keyman.com for now even for alpha builds, as keyman-staging.com is going to be used for transition to Docker-based hosting, and it will be problematic to try and share that process with alpha builds.
* **TEST_LINK_WINDOWS:** Verify that you can install a keyboard from the "Download Keyboard..." button in Keyman Configuration.
* **TEST_LINK_MACOS:**  Verify that you can install a keyboard from the "Download Keyboard..." button in Keyman.
* **TEST_LINK_LINUX:**  Verify that you can install a keyboard from the "Download Keyboard..." button in Keyman.
* **TEST_LINK_ANDROID:**  Verify that you can install a keyboard from the cloud in Keyman.
* **TEST_LINK_IOS:**  Verify that you can install a keyboard from the cloud in Keyman.
=> chore: use keyman.com instead of keyman-staging.com

core/include/keyman/keyboardprocessor.h, core/src/km_kbp_processevent_api.cpp, core/src/processor.hpp
Pair coded with @rc-swag.
Adds infrastructure required to support caps lock control on keyboard activation per #5822.
Keyboardprocessor implementation is currently a stub, and engines will need corresponding updates to support the new API.
=> feat(core): add `km_kbp_event` API endpoint

windows/src/engine/keyman32/kmprocessactions.cpp
Fixes: #7231
When the windows platform receives the action for a backspace it will check to see if the character being deleted is a surrogate pair. If it is and the app is TSF aware app it will need to set the BK_SURROGATE flag in the platform action queue This will result in two backspaces to remove both parts of the surrogate pair. For legacy apps, this is not required.
Issue: #7251 will add some windows unit tests.
Using a public available keyboard.
**Setup Text Services Framework(TSF) testing with Keyman for Windows**
1. Install Keyman Developer version 15 or greater. 
2. Open the Keyman Developers Test page in Firefox. **It must be [`Firefox Browser`](https://www.mozilla.org/en-US/firefox/new/)** 
a. By default this is at localhost:8008 so you could type in to the firefox address bar …
=> fix(windows): Delete both code units when deleting surrogate pairs in TSF-aware apps

common/web/lm-worker/src/correction/distance-modeler.ts
Hopefully addresses some aspects of #6985.
This PR is primarily designed to address some CI unit testing stability issues.  Since our browser-based unit testing is handled via an external service, it's quite possible that our unit tests may be run alongside others in a manner that causes context-switching.  Noting that we've had issues arise from context switching before - see #5467 / #5479 - it's quite possible that some of our prediction instability is arising from the same underlying problem - a user often _does_ have background threads and processes running on their mobile device, after all.
Noting the similarity between this and intermittent failures for predictive text to produce no results when it often otherwise produces _something_ with identical text, if my suspicions are …
=> fix(web): enhanced timer for prediction algorithm

windows/src/engine/keyman32/kmprocessactions.cpp
Fixes: #7231 
This a cherry-pick of the fix made in PR #7243. Fixing the deletion of half a surrogate pair in an application using the TSF.
=> fix(windows): TSF apps delete all of smp 🍒

windows/src/engine/keyman32/keyman-engine.vcxproj, windows/src/engine/keyman32/kmprocessactions.cpp, windows/src/engine/keyman32/kmprocessactions.h, windows/src/engine/keyman32/tests/keyman-engine-tests/keyman-engine-tests.vcxproj, windows/src/engine/keyman32/tests/keyman-engine-tests/kmprocessactionstests.cpp
Fixes: #7251
This is just updating the Visual Studio Code project properties to have the correct include paths. Adding `kmtip_guids.cpp` to the test project. 
A unit test was added for testing backspace on a surrogate pair in `processactions`. However, this would not test issue #7231. For that, we need to be able to test the output of  `PostKeys()`.
=> fix(windows) Update unit tests for tsf bkspace

developer/src/kmc/src/keyman/compiler/bksp.ts, developer/src/kmc/src/keyman/compiler/compiler.ts, developer/src/kmc/src/keyman/compiler/keys.ts, developer/src/kmc/src/keyman/compiler/loca.ts, developer/src/kmc/src/keyman/compiler/meta.ts, developer/src/kmc/src/keyman/compiler/name.ts, developer/src/kmc/src/keyman/compiler/ordr.ts, developer/src/kmc/src/keyman/compiler/section-compiler.ts, developer/src/kmc/src/keyman/compiler/tran.ts, developer/src/kmc/src/keyman/kmx/element-string.ts, developer/src/kmc/src/keyman/kmx/kmx-plus-builder/build-elem.ts, developer/src/kmc/src/keyman/kmx/kmx-plus-builder/build-keys.ts, developer/src/kmc/src/keyman/kmx/kmx-plus-builder/build-loca.ts, developer/src/kmc/src/keyman/kmx/kmx-plus-builder/build-meta.ts, developer/src/kmc/src/keyman/kmx/kmx-plus-builder/build-name.ts, developer/src/kmc/src/keyman/kmx/kmx-plus-builder/build-ordr.ts, developer/src/kmc/src/keyman/kmx/kmx-plus-builder/build-strs.ts, developer/src/kmc/src/keyman/kmx/kmx-plus-builder/build-tran.ts, developer/src/kmc/src/keyman/kmx/kmx-plus-builder/kmx-plus-builder.ts, developer/src/kmc/src/keyman/kmx/kmx-plus.ts, developer/src/kmc/test/fixtures/basic.txt, developer/src/kmc/test/helpers/index.ts, developer/src/kmc/test/test-bksp.ts, developer/src/kmc/test/test-finl.ts, developer/src/kmc/test/test-loca.ts, developer/src/kmc/test/test-meta.ts, developer/src/kmc/test/test-name.ts, developer/src/kmc/test/test-ordr.ts, developer/src/kmc/test/test-tran.ts
Fixes #7235.
Encapsulates all strings in the in-memory compile so that we can binary sort them for build. This means that finalization of strs and elem is no longer needed -- it's part of setup of build_strs and build_elem -- so that is factored away. Renamed alloc_string and alloc_element_string.
It may be worth renaming some of the ELEM_STRING objects / interfaces as currently they are a little confusing.
=> refactor(developer): kmc - encapsulate strs and elem items for sort 🙀

windows/src/engine/testhost/README.md
This just adds some workflow steps to testhost/README.md. These are the steps that I have found work consistently and very quickly (no windows restarts or rebuilds) to debug Keyman for windows and Keyman core.
=> docs(windows): add steps for using testhost debugging

developer/src/kmcmpdll/DeprecationChecks.cpp, developer/src/kmcmpdll/UnreachableRules.cpp
Fixes #7122.
The compiler was updating currentLine when checking for unreachable rules, but not restoring it afterwards. This led to mismatches in the debugger and in compiler warnings.
TEST_SINGLE_STEP: Verify that single step in the debugger no longer ends up on the wrong line
1. Load khmer_angkor.kmn in Keyman Developer, and start debugging (<kbd>F5</kbd>).
2. Type <kbd>x</kbd><kbd>E</kbd><kbd>j</kbd>
3. Turn on the Single Step mode from Debug menu.
4. Type <kbd>m</kbd>, and step through with Debug/Step Forward.
5. Step forward through to the `normalise` group, and then verify that the next step shows the correct rule that is applied, not a blank line.
=> fix(developer): compiler mismatch on currentLine

windows/src/developer/kmcmpdll/DeprecationChecks.cpp, windows/src/developer/kmcmpdll/UnreachableRules.cpp
Fixes #7122.
Cherry-pick of #7190.
The compiler was updating currentLine when checking for unreachable rules, but not restoring it afterwards. This led to mismatches in the debugger and in compiler warnings.
=> fix(developer): compiler mismatch on currentLine 🍒

developer/src/common/delphi/compiler/CompileErrorCodes.pas, developer/src/kmcmpdll/comperr.h, developer/src/tike/compile/CompileKeymanWeb.pas
Fixes #7216.
The warning message 0x209A 'The rule will never be matched because its key code is never fired.' was being generated multiple times for a single line because the `JavaScript_Key` function it is generated by is used for various purposes.
This PR keeps a cache of reported key rules to ensure that the message is reported only once for a given key rule, and also improves the reporting to clarify which specific key is unreachable, which makes it easier to diagnose when using `any(k)` style messages, for example:
```
lao_phonetic.kmn (237): Hint: 109A The rule will never be matched for key 'ñ' because its key code is never fired.
```
This also reduces the warning to a hint, as this should not be a blocking issue for a keyboard, rather just a place the keyboard author can tidy up. …
=> fix(developer): suppress repeated warnings about unreachable code

common/test/resources/karma-browserstack-config.js
We're still getting sporadic test failures with BrowserStack. So per one discussion online, attempting to run without concurrency to see if it improves stability.
I note that the video from tests where we "fail to capture" shows a browser with an error: "Safari Can't Connect to the Server" "Safari can't open the page "localhost:9879/?id=75185158" because Safari can't connect to the server "localhost".
https://automate.browserstack.com/dashboard/v2/builds/419c59decb8e12303e45e1f4bad1b945252df532/sessions/19712158833ce57592b66a50433965e4146fc972
Browserstack log entries from the [build in question](https://build.palaso.org/viewLog.html?buildId=337060&buildTypeId=Keymanweb_TestPullRequests&tab=buildLog):
```log
08 09 2022 19:14:15.905:DEBUG [launcher.browserstack]:  Starting …
```
=> chore:  try disabling concurrency for browserstack tests

common/predictive-text/unit_tests/test.sh, resources/build/build-utils-ci.inc.sh, resources/build/build-utils-ci.test.sh, web/unit_tests/test.sh
Because BrowserStack tests are unreliable, I am disabling them for any builds that are not specifically targeting web. Two ways that the tests can be enabled:
1. Include '(web)' in the PR title
2. Include the label test-browserstack
This only impacts builds in the CI test environment, not anything else.
See build-utils-ci.inc.sh for helper functions for accessing PR metadata, and build-utils-ci.test.sh for unit tests for this functionality.
=> chore(web): disable browserstack on non-web-specific builds

windows/src/developer/TIKE/compile/CompileKeymanWeb.pas, windows/src/global/delphi/general/CompileErrorCodes.pas, windows/src/global/inc/Comperr.h
Fixes #7216.
Cherry-pick of #7219.
The warning message 0x209A 'The rule will never be matched because its key code is never fired.' was being generated multiple times for a single line because the `JavaScript_Key` function it is generated by is used for various purposes.
This PR keeps a cache of reported key rules to ensure that the message is reported only once for a given key rule, and also improves the reporting to clarify which specific key is unreachable, which makes it easier to diagnose when using `any(k)` style messages, for example:
```
lao_phonetic.kmn (237): Warning: 209A The rule will never be matched for key 'ñ' because its key code is never fired.
```
This also reduces the warning to a hint, as this should not be a blocking issue for a keyboard, rather just a place the …
=> fix(developer): suppress repeated warnings about unreachable code 🍒

core/src/kmx/kmx_file.cpp
This is the first baby step in good verification of a .kmx file. A place
to add more tests.
=> chore(core): verify StartGroup in kmx load 🙀

developer/src/tike/xml/layoutbuilder/builder.css, developer/src/tike/xml/layoutbuilder/builder.js, developer/src/tike/xml/layoutbuilder/constants.js
Fixes #7028.
Note that the desktop layout is not currently used by KeymanWeb. The designer has a number of additional issues, as the .keyman-touch-layout format is not well suited to describing a fixed hardware layout, but fixing this is outside the scope of this issue.
Key Size information is not relevant for desktop view, so I have chosen to hide it.
Test according to #7028 problem description:
**TEST_DESKTOP_LAYOUT:** Verify that the key size information is no longer visible in desktop view.
1. Open .kpj project using Keyman Developer. (eg., cameroon qwerty.kpj)
2. Click on Touch Layout view.
3. Verify that the 'tablet' option appears under the Platform field.
4. Click the '+' plus button.
5. Verify that the desktop option appears against the Platform dropdown list.
6. Click the OK …
=> fix(developer): hide key-sizes when in desktop layout in touch layout editor

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageFragment.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/BCP47.java
:cherries: pick of #7239 to stable-15.0
Standardize language ID in language picker menu to compare language tags in the lists.
Setup - Use any Android device / emulator of Android SDK >= 21
* **TEST_ASSOCIATED_LANGUAGE_WORKS** - Verifies existing functionality of installing keyboard and associated lexical-model
1. On the Android device, install the PR build of Keyman for Android
3. In Keyman Settings --> Install Keyboard or Dictionary --> Install from keyman.com --> Search for sil_jarai
4. Install the **sil_jarai** keyboard package
5. Wait a few minutes for the associated dictionary to install (for jra-Latn language)
6. Verify suggestions appear on top of the sil_jarai keyboard
* **TEST_ADD_LANGUAGE** - Verifies existing functionality of adding a language …
=> fix(android/engine):  Standardize language ID in language picker 🍒

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
Fixes #6733 
If removing the currently selected keyboard from the Keyman settings menu, Keyman Engine for Android wasn't switching to another keyboard.
Prior to adding the Keyman settings menus,  keyboard management (adding/removing) was handled in `KeyboardPickerActivity`, where deleting a keyboard involved long-pressing on a keyboard in the list to remove it (`listView` was used to display the keyboard picker menu).
Since the keyboard settings menu also uses `KeyboardPickerActivity.deleteKeyboard()` under the hood, we don't need to check listView anymore.
Setup
2. On the "Get Started" menu, enable Keyman as a system keyboard and set it as the default system keyboard.
* **TEST_KEYBOARD_PICKER_MENU** - Verifies keyboard switches when deleting …
=> fix(android/engine): Switch keyboard if uninstalling current one

common/web/lm-worker/src/correction/distance-modeler.ts
Fixes #7283.
When checking how long something has waited... it usually helps when you subtract the smaller value from the larger value.  🤦   The "enhanced prediction timer"'s maximum wait threshold wasn't triggering because of this.
That said, the fact that predictions would lag that much without it says something about how much context-switching the worker thread is having to contend with...
Revisiting this, I've noticed that each prediction queues up and cannot be interrupted.  Since there's a forced wait there... allowing too much extra wait time can really start to add up when there's a significant amount of context switching.  There's no 'interrupt' system to cancel the current predictive-text ops when receiving a new prediction request within the worker itself.  Addressing _that_, …
=> fix(common/models): max prediction wait check

developer/src/kmc/build.sh, developer/src/kmc/src/keyman/compiler/compiler-options.ts, developer/src/kmc/src/keyman/compiler/compiler.ts, developer/src/kmc/src/keyman/compiler/metadata-compiler.ts, developer/src/kmc/src/kmc.ts, developer/src/kmc/test/fixtures/basic.txt, developer/src/kmc/test/fixtures/basic.xml, developer/src/kmc/test/helpers/index.ts, developer/src/kmc/test/test-compiler-e2e.ts, developer/src/kmc/test/test-metadata-compiler.ts, developer/src/kmc/test/tsconfig.json
Fixes #7273.
Adds 4 kmx system stores to allow existing configuration tools to load and process KMXPlus files without modification:
* `TSS_NAME` (first `<name>`)
* `TSS_COMPILEDVERSION` (only if `options.addCompilerVersion == true`)
* `TSS_KEYBOARDVERSION` (from `<version number>`)
* `TSS_TARGETS` (currently always 'desktop', will later include more targets)
In order for `TSS_COMPILEDVERSION` to be handled correctly, needed to plumb in the new `CompilerOptions` interface. This could be a separate PR, but the changes are not huge, so opted to append the changes here.
Updates related tests and fixtures. Refactored some of the e2e helpers into helpers/index.ts for use with the metadata-compiler tests.
=> feat(developer): add kmx metadata to kmxplus compiles 🙀

.github/multi-labeler.yml, .github/workflows/labeler.yml, developer/src/kmc/src/keyman/compiler/compiler.ts, developer/src/kmc/src/keyman/compiler/keys.ts, developer/src/kmc/src/keyman/compiler/loca.ts, developer/src/kmc/src/keyman/compiler/messages.ts, developer/src/kmc/src/keyman/compiler/meta.ts, developer/src/kmc/src/keyman/compiler/section-compiler.ts, developer/src/kmc/src/keyman/compiler/vkey.ts, developer/src/kmc/src/keyman/ldml-keyboard/ldml-keyboard-xml-reader.ts, developer/src/kmc/test/fixtures/sections/keys/hardware.xml, developer/src/kmc/test/fixtures/sections/keys/invalid-hardware-too-many-keys.xml, developer/src/kmc/test/fixtures/sections/keys/invalid-hardware-too-many-rows.xml, developer/src/kmc/test/fixtures/sections/keys/invalid-missing-layer.xml, developer/src/kmc/test/fixtures/sections/keys/invalid-undefined-key.xml, developer/src/kmc/test/fixtures/sections/keys/minimal.xml, developer/src/kmc/test/fixtures/sections/meta/invalid-version-1.0.xml, developer/src/kmc/test/fixtures/sections/meta/invalid-version-v1.0.3.xml, developer/src/kmc/test/helpers/index.ts, developer/src/kmc/test/ldml-keyboard/test-ldml-keyboard-xml-reader.ts, developer/src/kmc/test/test-keys.ts, developer/src/kmc/test/test-loca.ts, developer/src/kmc/test/test-meta.ts, developer/src/kmc/test/test-vkey.ts
* Add a bunch of tests for keys
* Add tests for version. (improves meta test coverage to 100%)
* A bit more consistency cleanup also of error message functions.
* Adds a compiler failure (FATAL) if compile fails after validate passes.
* Overall test coverage now 93.5% lines. Biggest gap still kmx-builder. All compiler units are >90%.
Finally, throws in a tweak to the auto labelling: if 'epic-ldml' is in the branch name, we'll get that label automatically.
=> chore(developer): improve kmc validation and corresponding tests 🙀

common/web/input-processor/src/text/inputProcessor.ts, common/web/keyboard-processor/src/keyboards/activeLayout.ts, common/web/keyboard-processor/src/text/codes.ts
Mitigates #7240 by more strongly weighting keys close to the touch point.
**Also** fixes interference that was being caused from 'hidden'-property keys, which resemble padding areas on the OSK.  If one of these was 'most likely', default suggestions would be displayed instead of suggestions for the most likely actual key.
**Additionally**, this fixes a bug with determining how far a touchpoint is from the center of the right-most key of each row of the on-screen-keyboard - this bug was causing overcorrections in favor of the key immediately to the left in most cases.
Previously, we were using an inverse-linear relationship for a key's probability based on its distance from the touchpoint; I now believe inverse-quadratic to be more appropriate.  In relation to #7201 (and [this …
=> change(web): better fat-finger key weighting ✏️

web/source/osk/banner.ts
Fixes #7167.
While we've never really "turned it on", there are parts of the predictive text pathway that were designed to facilitate auto-correct behaviors.  (See #1747)  This one is the most noteworthy:
https://github.com/keymanapp/keyman/blob/52e9a39a8575a88368808dba9b0eb4380d5f275f/common/web/input-processor/src/text/inputProcessor.ts#L121-L127
While we rewired `tryRevertSuggestion` to simply _display_ the reversion rather than automatically doing it (#1851), we never bothered modifying `tryAcceptSuggestion`.  After all, we never automatically 'select' any suggestion, so there's nothing to be auto-applied.
... except for this one little edge case.  Even then, it's not like we auto-selected anything... we just forgot to _clear_ a previous suggestion's selected state.  This is what …
=> fix(web): fixes unintended auto-acceptance of suggestion after reverting

common/models/templates/test/test-tokenization.js, common/models/wordbreakers/src/default/data.ts, common/models/wordbreakers/src/default/index.ts, common/models/wordbreakers/test/test-default-word-breaker.js
Addresses #3347.  If nothing else, this should help prompt some nice discussion toward a better solution.
Note the addition of unit tests to cover almost every base case of the standard Unicode word-breaking implementation, then extra ones to verify that customization can work for a few decent sample cases.
To be clear, any custom rules will have priority over all rules after WB4 from the wordbreaker spec.  Furthermore, reclassifying any character is absolute - each character may only match a single word-breaking property value.
These changes don't make any direct changes to the lexical model compiler, so testing may be needed to be sure there are no issues with specifying the customizations to the word-breaking function.  (That said, it appears to be 100% fine when using command-line …
=> feat(common/models): wordbreaker customization

common/web/lm-worker/src/model-compositor.ts
Fixes a post-merge issue caused when merging both of the following two PRs:
- #7241 
- #7205
From #7205:
Note the original line 165:
```typescript
let contextTokens = contextState.tokens;
```
This line is referenced by #7241:
Due to the way the changes were made, this was not detected as a merge conflict, allowing this to slip through:
Fortunately, it's a very easy "conflict" to resolve. 
=> fix(common/models): fixes reference dropped by git merge

common/tools/hextobin/index.ts, common/tools/hextobin/tsconfig.json, developer/src/kmc-keyboard/package.json, developer/src/kmc-keyboard/src/kmx/kmx-builder.ts, developer/src/kmc-keyboard/test/fixtures/basic.txt, package-lock.json
Fixes #7301.
(Note: hextobin changes are due to es2020 asynciterable feature in `load` function: `for await (const l of reader) {`. Generally it builds fine separately but trouble can arise with project builds.)
=> chore(developer): remove crc generation from kmc-keyboard

web/testing/regression-tests/README.md, web/testing/regression-tests/package.json, web/testing/regression-tests/src/test-runner.js, web/testing/regression-tests/test.js
* Updates `got` from ^9.6.0 to ^11.8.5. (10.0.0 had [significant breaking changes](https://github.com/sindresorhus/got/releases/tag/v10.0.0), 11.0.0 [less problematic](https://github.com/sindresorhus/got/releases/tag/v11.0.0))
* Also fixes paths referencing developer, and tweaks command line help.
=> chore(web): update `got` dependency for regression tests

core/include/ldml/package.json, core/include/ldml/tsconfig.json, tsconfig.cjs.json, tsconfig.esm.json
Also splits the root tsconfig.json into tsconfig.cjs.json and tsconfig.esm.json. These are not typically used at present but in theory you could do a `tsc -b <tsconfig.x.json>` and build all modules. In practice, we still have some prebuild steps that make that a bit of a pain.
I have noted some inconsistency with `tsc -b` when referenced modules have different module modes, so splitting them seems wise. Also helpful for a simple index of which modules are in which format...
=> chore(core): changes ldml tsconfig to es2020 🙀

core/build.bat, core/build.sh, core/commands.inc.sh, core/tests/unit/ldml/keyboards/meson.build, linux/debian/rules, resources/build/build-utils.sh, resources/build/build-utils.test.sh
This fixes the failing Core tests in #7054 -- broke in #7286, but wasn't picked up
there because Core build didn't run on that PR.
This update also allows use of `./build.sh configure -- --param-one=foo ...`.
Updates Core build to support `--` (including build.bat wrapper for Windows builds). Fixes Linux debian rules to pass additional parameters in with this format again, and adds `:arch` to only build current architecture, not wasm as well...
Note that when using `--` you should typically avoid multiple actions in a single command, as each action may interpret the additional parameters differently!
=> chore(core): `kmc --outFile` to `kmc --out-file` (and `--` rider) 🙀

core/build.sh
Fixes https://github.com/keymanapp/keyman/pull/7311#discussion_r974957397
I could add a trap for this to build-utils.sh but that's more work for little benefit for an internal tool.
=> fix(core): add hyphen to d parameter 🙀

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
Follow-on to #7291
This :cherries: picks commit https://github.com/keymanapp/keyman/pull/7304/commits/0ff9946ff92fd5707a917a07e984877380582a87 to master
When Keyman is launched without entering the Keyboard picker menu, the listview is uninitialized. This adds the check for setting the keyboard selection.
Setup
2. On the "Get Started" menu, enable Keyman as a system keyboard and set it as the default system keyboard.
* **TEST_KEYBOARD_PICKER_MENU** - Verifies keyboard switches when deleting current keyboard from Keyboard Picker menu
1. Launch Keyman for Android and verify the current keyboard is sil_euro_latin 
2. Launch another app (e.g. Chrome) and verify the system keyboard is sil_euro_latin
3. In the Keyman app, go to Settings, search for …
=> fix(android/engine): Check listview for setting keyboard selection

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
:cherries: -pick of #7291 to stable-15.0
Relates to #6733 
If removing the currently selected keyboard from the Keyman settings menu, Keyman Engine for Android wasn't switching to another keyboard.
Prior to adding the Keyman settings menus,  keyboard management (adding/removing) was handled in `KeyboardPickerActivity`, where deleting a keyboard involved long-pressing on a keyboard in the list to remove it (`listView` was used to display the keyboard picker menu).
Since the keyboard settings menu also uses `KeyboardPickerActivity.deleteKeyboard()` under the hood, we don't need to check listView anymore.
Setup
2. On the "Get Started" menu, enable Keyman as a system keyboard and set it as the default system keyboard.
* …
=> fix(android/engine): Switch keyboard if uninstalling current one :cherries: 

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/Samples/KMSample1/app/src/main/java/com/keyman/kmsample1/MainActivity.java, android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java
Fixes #7326 
I don't think this is a recent regression, but a scenario uncovered from the Keyman 15 change #5838 of allowing the default sil_euro_latin keyboard to be uninstalled.
1. The language list in the Languages settings menu is backed by a legacy filtered Dataset structure (introduced a long time ago to generate the  list of installed languages). This dataset is sourced by the list of installed keyboard languages and installed lexical-model languages.
2. Including the language name with the lexical-model data structure was optional since we are only checking language ID's for association. So we haven't had to bother including the language name when installing the default English lexical-model.
3. When the English keyboard for sil_euro_latin is uninstalled,
4. The underlying Dataset …
=> fix(android): Add language name when installing default lexical-model

HISTORY.md
I was filling out a monthly report and noticed the 15.0 stable entries were missing for each platform on
https://help.keyman.com/version-history
The entries do exist on the stable-15.0 branch
=> chore(common): Add 15.0 stable entries to HISTORY.md :cherries: 

developer/src/kmc-keyboard/src/compiler/compiler.ts, developer/src/kmc-keyboard/src/kvk/kvks-file-reader.ts, developer/src/kmc-keyboard/src/ldml-keyboard/ldml-keyboard-xml-reader.ts, developer/src/kmc-keyboard/test/helpers/index.ts, developer/src/kmc-keyboard/test/kvk/test-kvk-round-trip.ts, developer/src/kmc-keyboard/test/kvk/test-kvks-file.ts, developer/src/kmc-keyboard/test/ldml-keyboard/test-ldml-keyboard-xml-reader.ts
This is a minor refactor to prepare for moving the file readers into common/web/types, rather than keeping them as part of the compiler.
=> refactor(developer): move compiler callbacks out of readers 🙀

developer/src/kmc-keyboard/src/compiler/visual-keyboard-compiler.ts, developer/src/kmc-keyboard/src/main.ts, developer/src/kmc-keyboard/test/fixtures/basic-kvk.txt, developer/src/kmc-keyboard/test/helpers/index.ts, developer/src/kmc-keyboard/test/test-visual-keyboard-compiler-e2e.ts, developer/src/kmc/package.json, developer/src/kmc/src/kmc.ts, developer/src/kmc/tsconfig.json, package-lock.json
Adds support for building .kvk files to kmc. At present, .kvk will always be generated, even if the .xml does not have a hardware layer.
Adds visual-keyboard-compiler and corresponding e2e test.
=> feat(developer): visual keyboard compiler for LDML 🙀

developer/src/kmcomp/main.pas
Fixes #7090.
Fixes #7091.
While kmcomp loads most files just fine when paths with forward slashes are passed in, it fails to parse target path correctly when building one file out of a project.
For example, if the user runs:
```
kmcomp.exe -t khmer_angkor.kmn release/k/khmer_angkor/khmer_angkor.kpj
```
Then the following error arises:
```
khmer_angkor.kps: Error: 0001 Validation error: The system cannot find the path specified.
khmer_angkor.kps: Failure: Package C:\Projects\keyman\keyboards\source\khmer_angkor.kps had validation errors.
```
This patch ensures all paths passed in as command-line parameters are converted to backslashes, matching the expected Windows format. While I only needed to fix the `FParamTarget` parameter in order to address the reported issues, for consistency I …
=> fix(developer): ensure backslash in paths passed to kmcomp

android/KMEA/app/src/main/assets/android-host.js, web/source/osk/oskView.ts
Fixes #6603 and ~possibly addresses #7228~ (edit - fails to fix #7228)
(The original PR description explored changing the Android namespace call from `keyman` to `kmw` `.correctOSKTextSize()`; which turned out to have no impact on the issue. The description has now been edited after further investigating the cause in KeyamnWeb)
It seems the KeymanWeb call to refresh the layout was missing a call to ensure the spacebar caption was updated as well.
I don't understand why the issue doesn't happen when only the default sil_euro_latin keyboard is installed...
* **TEST_SPACEBAR_CAPTION_ANDROID** - Verifies issue #6603 on Android is fixed
*Spacebar caption menu*
2. From Keyman Settings, search for and install another keyboard (e.g. sil_cameroon_qwerty …
=> fix(web): Update spacebar caption when refreshing layout

common/schemas/kvks/kvks.schema.json, common/web/types/src/kvk/kvks-file-reader.ts, common/web/types/src/kvk/kvks-file-writer.ts, common/web/types/src/kvk/kvks-file.ts, common/web/types/src/kvk/visual-keyboard.ts, common/web/types/test/kvk/test-kvks-file.ts
Fixes #7379.
Relates to #7238.
Also splits attributes from sub-elements in kvks-file in order to make round-trip writing more pleasant.
Adds new round-trip test for kvks writer.
Removes incorrect property keybitmap, adds missing property layout.
=> feat(common): kvks writer for TypeScript 🙀

web/source/osk/uiTouchHandlerBase.ts
Fixes #7382 
In certain instances, KeymanWeb is attempting to un-highlight a suggestion when `this.pendingTarget` is null.
This causes the suggestion banner to crash (t = this.pendingTarget = null => t.className is undefined)
https://github.com/keymanapp/keyman/blob/a3dde68d52c9f84c5181b54da7eba6a054810c46/web/source/osk/banner.ts#L460-L461
* **TEST_SUGGESTION_NO_CRASH** - Verifies issue #7382 is fixed
Setup: Install the PR build of Keyman for Android on a physical device. (The test involves multi-touch typing)
1. In the Keyman app with the default sil_euro_latin keyboard and nrc.en.mtnt lexical-model
2. Type enough characters until all 3 suggestions in the banner are blank (e.g. the text "Jjjjnnn")
3. Restart Keyman and observe all 3 suggestions are still blank
4. With one thumb, hold on …
=> fix(web): Only unhighlight suggestion if there's a pending one

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/BaseActivity.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/impl/CloudLexicalModelMetaDataDownloadCallback.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java
Fixes #7189
This updates the KMLog error handling to also display a Toast notification of the error message (provides user additional info about errors)
* Some classes aren't an AppCompatActivity, so they'll need BaseActivity.makeToast() to display the notification.
* Also updated the error string when downloads fail to use the destinationFilename, since filename could be blank.
* Found that api.keyman returns a valid empty array if no matching lexcal-model for a language is found. So I've removed that LogError.
Note: with this change, the localized strings used for Toast notifications are passed on to Sentry logging...
**Setup**
Install the PR build of Keyman for Android, and start the test with the device having network access
* **TEST_LOG_ERROR** - Verifies KMLog.LogError displays …
=> chore(android/engine): Display Toast notifications on Sentry errors

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Possibly addresses #6978
Keyman Engine for Android currently isn't set up to robustly handle multi-touch. If the user starts a long-press with one finger and switches layer with a second finger, it can cause KeymanWeb to process a subkey that doesn't match the base key anymore.
This PR causes subkeys to get dismissed when a multi-touch is detected.
**Setup**
1. Needs a physical Android device for multi-touch typing (two thumbs)
2. Install the PR build of Keyman for Android
* **TEST_MULTI_TOUCH_DISMISSES_LONGPRESS** - Verifies long-press keys aren't generated when multi-touch detected
1. Start Keyman for Android with the default sil_euro_latin keyboard.
2. Observe the OSK is on the Shift layer (upper-case)
3. With the right thumb, start long-press on G and hold. Immediately with the left …
=> fix(android/engine): Dismiss subkeys on multi-touch

developer/src/inst/node/kmc.cmd, developer/src/inst/node/kmlmc.cmd, developer/src/inst/node/kmlmi.cmd, developer/src/inst/node/kmlmp.cmd, developer/src/tike/kmlmc.cmd, developer/src/tike/kmlmi.cmd, developer/src/tike/kmlmp.cmd
Fixes #7408.
For kmc*.cmd, enables source maps. If you are running kmc from node on your own system, you may need to enable source maps in other ways.
Note that error reports should be going through to Sentry, and source maps should already be used for those.
=> chore(developer): enable source maps for kmc commands 🙀

web/source/dom/targets/contentEditable.ts, web/source/dom/targets/designIFrame.ts
I happened to notice this one while dev-testing #7345; on occasion I'd see the following:
This happened there while preparing a `Mock` for use with predictive-text based on a content-editable element type.  Now, that precise tidbit isn't allowed before #7345 is implemented, _but_ the fact remains that it's a bug.  (Content-editables don't interact with KMW in current builds b/c we don't support touch-aliasing for them.)  It's possible this may arise in other scenarios as well, though.
It could conceivably occur for design-mode iframes, though I haven't managed to reproduce that case yet.
=> fix(web): possible error on change of context to a contextEditable

web/unit_tests/cases/engine.js, web/unit_tests/cases/engine_chirality.js, web/unit_tests/cases/events.js, web/unit_tests/cases/text_selection.js, web/unit_tests/test_utils.js
This should help make Web's unit testing a little 'snappier', especially when things fail.
Changes made:
1. Keyboard sequence reproduction has been retooled to operate based on `Promise`s, allowing unhandled `Promise`-internal errors to be caught by the test framework.
- I noticed that when a test dependent on reproducing a keystroke sequence failed, sometimes the test's full timeout would be enforced- likely because we weren't triggering the test-function's callback.  In particular, if the error was raised within a `Promise`'s operation, and not within the synchronous test-setup process.
- I have seen a few occasions where KMW builds have timed out; this may help mitigate such cases.  No guarantees though, as those builds didn't actually report _any_ failed tests.
- Like this one: …
=> chore(web): unit test polishing pass

common/web/gesture-recognizer/src/constructingSegment.ts, common/web/gesture-recognizer/src/cumulativePathStats.ts, common/web/gesture-recognizer/src/pathSegmenter.ts, common/web/gesture-recognizer/src/segment.ts, common/web/gesture-recognizer/src/segmentClassifier.ts, common/web/gesture-recognizer/src/subsegmentCompatibilityAnalyzer.ts, common/web/gesture-recognizer/src/trackedPath.ts
Continuing from #7058, this PR seeks to construct & publish "proper" Segment objects to the `TrackedPath` object that may be used for later stages of gesture recognition.  These are synthesized by examining the sequence of "subsegments" produced by the segmentation algorithm and recombining them as appropriate based on a few common patterns and rules.
This implements "stage one" from [our "Gesture Recognition" design doc](https://docs.google.com/document/d/1i7WI7iGD0FI2nGx7T65Yu32LgLCaGfIaZN3EPMhlTog/edit?usp=sharing).
Additionally, this PR's changes seek to provide a better, more long-term-maintenance-friendly set of debugging functions, logging methods, etc - rather than maintaining the slew of raw `console.log()` statements its predecessor had.  Accordingly, any debug-logging …
=> feat(web): touchpath segment objects 🐵

linux/ibus-keyman/src/engine.c
[Quick link to the test results](https://github.com/keymanapp/keyman/pull/7079#issuecomment-1218025741)
This change implements a commit queue which allows to control the order of the output. This ensures that any backspace we generate will be processed before the character we're adding.
**Requires changes in ibus** ([surrounding text fix](https://github.com/ibus/ibus/pull/2436) (see #7072) and [prefilter change](https://github.com/ibus/ibus/pull/2440)).
* Fixes #1489.
* Fixes #4028.
* Fixes #4029.
* Fixes #4030.
* Fixes #4505.
* Fixes #5510.
* Fixes #6639.
- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome …
=> fix(linux): Fix reordering of output

linux/Dockerfile
- used in feature-ldml
Relates to #7102
=> chore(linux): Add Node.js to the docker container

common/predictive-text/build.sh, common/predictive-text/unit_tests/test.sh, common/web/input-processor/build.sh, common/web/keyboard-processor/build.sh, common/web/keyman-version/build.sh, common/web/lm-worker/build.sh, common/web/recorder/build.sh, common/web/utils/build.sh, resources/build/tests/builder-deps.test.sh, resources/build/tests/builder.inc.test.sh, resources/builder.inc.sh, resources/shellHelperFunctions.sh, web/unit_tests/test.sh
Internal dependencies are other projects within the keyman repo. External dependencies are not really a part of this discussion.
[Original design document](https://docs.google.com/document/d/1xoQaO7ZcICNm2q_C35Cm7Z9TgYq8d2XErSJblVPXM28/edit#heading=h.f0emrhxutzki)
We have a complex web of internal dependencies, but we want to be able to have our build scripts manage them without us having to figure out what needs building. At the same time, we don't want unnecessary builds.
We want to:
1. Simply and cleanly define dependencies in build.sh and continue to avoid boilerplate in these scripts **Maintenance**
2. Define dependencies in just one place in each project **Maintenance**
* Sadly, it is recognised that we _will_ need to define them both in build.sh and in the build system e.g. …
=> feat(common): builder dependency support

core/src/ldml/ldml_processor.cpp, core/tests/unit/ldml/keyboards/k_002_tinyu32.xml, core/tests/unit/ldml/keyboards/meson.build
- also a test case with a 🙀 key on the tiny keyboard
For #7418
Note this will currently conflict with #7437 and following
=> feat(core): ldml: Use new UTF-16 to UTF-32 function 🙀

core/src/kmx/kmx_plus.cpp, core/src/kmx/kmx_plus.h, core/src/kmx/kmx_processevent.h, core/src/ldml/ldml_processor.cpp, core/tests/unit/ldml/test_kmx_plus.cpp
- add accessors and tests for `elem` and related data structures
- other refactor and cleanup in kmx_plus, change to use kmx_debug debugging instead of printf/cerr
for #7234
=> feat(core): kmx_plus: add accessors for elem 🙀

.gitignore
During Linux packaging some files get put in the root of the source directory. This change limits these files in `.gitignore` to the root directory. It would be better to not generate these files in the root directory in the first place, but that's not trivial and a separate task.
=> chore(linux): Adjust Linux specific files in `.gitignore`

resources/builder.inc.sh
Part of #7455. It seems that there are not yet any builder scripts that use `--debug` on `master` branch (there are some on `feature-ldml` branch, which I'll update once I merge this into that branch.)
=> chore(common): `--debug` standard flag for builder

oem/firstvoices/ios/SWKeyboard/Info.plist
fixes #7391 
Due to an undocumented change in iOS 16, the FirstVoices Keyboard was blank and unusable. This change adds the ability to set Allow Full Access under Settings > General > Keyboard > Keyboards > First Voices:
After tapping Allow Full Access, an alert will be displayed:
Select the Allow button to proceed.
* **TEST_ALLOW_FULL_ACCESS_IOS_16:**
1. On an iPhone running iOS 16, enable 'Allow Full Access' under Settings > General > Keyboard > Keyboards > First Voices
2. Switch to the Notes app and tap on a blank document page
3. Tap the globe key on the keyboard and then tap FirstVoices from the keyboard list.
4. Verify that the keyboard is displayed as normal rather than being blank
=> fix(ios):  Allow Full Access enabled to fix ios 16  invisible keyboard

oem/firstvoices/ios/SWKeyboard/Info.plist
🍒 -pick of #7459 to stable-15.0
relates to #7391 
Due to an undocumented change in iOS 16, the FirstVoices Keyboard was blank and unusable. This change adds the ability to set Allow Full Access under Settings > General > Keyboard > Keyboards > First Voices:
After tapping Allow Full Access, an alert will be displayed:
Select the Allow button to proceed.
* **TEST_ALLOW_FULL_ACCESS_IOS_16:**
1. On an iPhone running iOS 16, enable 'Allow Full Access' under Settings > General > Keyboard > Keyboards > First Voices
2. Switch to Safari and tap on the URL editor field to bring up the virtual keyboard
3. Tap the globe key on the keyboard and then tap FirstVoices from the keyboard list.
4. Verify that the keyboard is displayed as normal rather than being blank
=> fix(ios): Allow Full Access enabled to fix ios 16 invisible keyboard 🍒 

developer/src/common/delphi/lexicalmodels/Keyman.Developer.System.LexicalModelCompile.pas, developer/src/tike/child/Keyman.Developer.UI.UframeWordlistEditor.pas, developer/src/tike/child/Keyman.Developer.UI.UfrmModelEditor.pas, developer/src/tike/child/Keyman.Developer.UI.UfrmWordlistEditor.pas, developer/src/tike/kmlmc.cmd, developer/src/tike/main/UframeTextEditor.pas, developer/src/tike/main/UfrmMain.pas
Relates to #4324 (but slightly orthogonal.)
We wanted some message classes to be handled in the lexical model editor more cleanly, including drill-down to line of error. A few changes required to make this work well:
1. Parse error messages from kmlmc. This is not perfect but works while the two projects are kept in sync, which they always are for Keyman Developer. Note that at this stage, .ts warnings are not captured in this parser, as they are generated by tsc.
2. Drill-down in Wordlist Editor Frame to find line of error
3. Model editor reports ownership of .tsv files so they can be loaded
4. In case of model editor not open (e.g. building from project view), the TSV standalone editor was not displaying the frame, so it never actually worked.
5. If the text editor had never loaded, …
=> fix(developer): Handle hints and warnings cleanly

developer/src/tike/child/UfrmKeymanWizard.dfm, developer/src/tike/child/UfrmKeymanWizard.pas, developer/src/tike/child/UfrmMDIEditor.pas, developer/src/tike/child/UfrmOSKEditor.pas, developer/src/tike/main/UframeOnScreenKeyboardEditor.pas, developer/src/tike/main/UfrmMain.dfm, developer/src/tike/main/UfrmMain.pas
Fixes #7425.
In the layout editor, the "Select Key" dialog was being shown sometimes when using shortcuts such as Ctrl+V. The reason this happened was that the shortcut handler in Delphi was capturing the keydown of the V key, so the Ctrl event handler never saw it. Then, if you pressed Ctrl+V, and released the Ctrl key before releasing the V key (which often happens when you press a shortcut rapidly), the Ctrl event handler would receive notification of the Ctrl key release and trigger the "Select Key" dialog.
This fix shifts the Ctrl key event handler out of the keyboard editor and into the top-level application events handler -- this is the best place where we can preview key events before they are passed to the shortcut handler and controls for processing.
This necessitated adding a …
=> fix(developer): Ctrl key to select key was conflicting with shortcuts

android/KMEA/app/src/main/assets/android-host.js
Fixes #6568 updating the Keyman references in android-host.js
**Setup** - Install the PR build of Keyman for Android onto Android device/emulator
**TEST_KMEA** - Verifies Keyman Engine functions still work
2. In the Keyman app with the default sil_euro_latin keyboard, short-press on key and release
3. Verify the key popup appears, disappears, and the key is output
4. Long-press on key and select one of the long-press options and release
5. Verify the long-press key is output
6. Go to Keyman Settings --> Adjust keyboard height
7. Change the OSK height and exit all the Settings menus
8. In the Keyman app, verify the OSK height is changed the adjusted height.
9. Go to Keyman Settings --> Installed Languages --> English --> English Settings --> Dictionary --> …
=> chore(android/engine): Update Keyman references in android-host.js

common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts, resources/standards-data/ldml-keyboards/techpreview/3.0/fr-t-k0-azerty.xml, resources/standards-data/ldml-keyboards/techpreview/cldr_info.json, resources/standards-data/ldml-keyboards/techpreview/dtd/ldmlKeyboard.dtd, resources/standards-data/ldml-keyboards/techpreview/dtd/ldmlKeyboard.xsd, resources/standards-data/ldml-keyboards/techpreview/dtd/ldmlKeyboardTest.dtd, resources/standards-data/ldml-keyboards/techpreview/dtd/ldmlKeyboardTest.xsd, resources/standards-data/ldml-keyboards/techpreview/fixup-schema.js, resources/standards-data/ldml-keyboards/techpreview/ldml-keyboard.schema.json, resources/standards-data/ldml-keyboards/techpreview/ldml-keyboardtest.schema.json
With this, kmc is at least able to load mt.xml and fr-t-k0-azerty.xml but runs into issues from #7402  and also lack of import support.
for #7411 
includes an update to CLDR data from PR https://github.com/unicode-org/cldr/pull/2469
=> fix(developer): support CLDR sample keyboards 🙀

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
Fixes #7424 
similar to #  , this dismisses key previews and subkeys when the Globe key is handled.
Setup - Install PR build of Keyman for Android on physical Android device. (Not an emulator because test involves multi-touches on the OSK)
**TEST_GLOBE_KEY_DISMISSES_KEYS** - Verifies key previews and subkeys are dismissed on Globe key action
1. Launch Keyman and dismiss the Get Started menu
2. With the default sil_euro_latin keyboard, long-press and hold a key with one finger 
3. While holding the long-press, use another finger to short-press the globe key
4. Verify nothing happens with th eglobe key and the long-press keys are still visible
5. Release the long-press key
6. With the default sil_euro_latin keyboard, first short-press a key with one finger, and then short-press the globe …
=> fix(android/engine): Dismiss key preview and subkeys on globe action

developer/src/tike/main/UframeBitmapEditor.dfm, developer/src/tike/main/UframeBitmapEditor.pas
Fixes #7419.
If the user attempts to add an invalid graphic (e.g. a .png file saved with a .ico extension), Keyman Developer will no longer crash when trying to load the file.
Note that while the keyboard will still compile with an invalid graphic, Keyman for Windows will refuse to install it. I have not tested other platform handling of such a situation.
All tests in the Keyboard Editor. To complete these tests, add a new, blank icon in the keyboard editor, save the keyboard, close the editor, replace the saved icon file with another one via Windows Explorer, and then reopen the keyboard editor.
**TEST_VALID_ICON:** Verify that adding a normal, 16x16 valid icon file to a keyboard causes no problems, and that the icon editor is displayed.
**TEST_VALID_ICON_MULTI:** Verify that adding a …
=> fix(developer): Handle invalid graphics in icon editor

web/source/osk/layouts/targetedFloatLayout.ts, web/source/osk/layouts/titleBar.ts, web/source/osk/oskView.ts, web/source/resources/osk/kmwosk.css, web/testing/index.html, web/testing/osk-event-buttons/index.html, web/testing/osk-event-buttons/oskButtonSrc.js
Fixes #7226.
Disables the two buttons highlighted by the green square in the following image unless a related event has (or has had) a listener:
Their only use in KMW at this point:
https://github.com/keymanapp/keyman/blob/1f573231c0fd54b117e40f5b90bea00b2f9db298/web/source/osk/layouts/titleBar.ts#L57-L73
So, they only exist to trigger events that a site designer has decided to handle; KMW itself does not use the two buttons in any way.
- TEST_REMOVED_BUTTONS: On any desktop or laptop computer, verify that the two buttons above no longer appear.
1. Pick and launch a browser (say, Chrome).
2. Use the standard "Test unminified Keymanweb" test page found under the "KeymanWeb Test Home" link below.
3. Click one of the two main text areas at the top ("Type here", "or here").
4. Verify that the …
=> change(web): removes unused config, help buttons from OSK

resources/build/tests/build-utils-traps.test.sh, resources/build/tests/builder-deps.test.sh, resources/builder.inc.sh
Fixes #7455.
If a builder script defines outputs for configure or build actions, builder will figure out if configure and/or build need to be run for any dependent actions for the script.
At present, these are not configurable per-script. I would like to see how we go with this fixed model before making it more generic. The defined per-script internal dependencies are:
`configure` <-- `build` <-- (`test`,`install`,`publish`)
=> chore(common): automatically run internal dependencies on builder

web/source/osk/languageMenu.ts
Fixes #6638.
For _**all**_ user tests below, perform the following test setup:
1. On a mobile device (real or emulated), go to the "Test unminified Keymanweb" test page found under "KeymanWeb Test Home" below.
2.  Under "Add a keyboard by keyboard name", type `sil_cameroon_azerty` and then press the "Add" button beside it.
3. Touch either of the first two text areas ("Type here", "or here") to display the OSK.
**TEST_DEFAULT_POSITION**: Verify that the language menu displays an entry for the active keyboard when first launched.
4. Press the globe key to launch the language menu.
5. Verify that "English" is visible near the top of the language menu, without any need for scrolling.
- There may be one half-visible entry before it; this is expected and not a test failure.
**TEST_INDEX_A**:
4. …
=> fix(web): touch-platform language menu initial scrolling + index scrolling

resources/builder.inc.sh
Fixes #7512.
Dependencies were being added to list of parameters, which caused the help formatting to be overly spaced out. Given deps are not parameters, we should never have been adding them anyway.
=> fix(common): ignore deps when formatting help

linux/ibus-keyman/src/engine.c
The previous method name `ibus_keyman_engine_commit_string` suggests that this method is overridden from ibus-engine class. However, while it is true that ibus-engine has a `ibus_engine_commit_string` method it can't be overridden. This change renames the method to make it clearer that this is an internal method that won't be called by ibus.
=> chore(linux): Rename internal method to `commit_string`

linux/ibus-keyman/src/engine.c
Both `ibus_keyman_engine_reset` and `ibus_keyman_engine_focus_in` are methods that get called by ibus. Having `ibus_keyman_engine_reset` call `ibus_keyman_engine_focus_in` makes it much harder to see in log files which methods get really called by ibus.
This change replaces the call of `...focus_in` with `reset_context`, which is what `...focus_in` does as well. The only other thing that `ibus_keyman_engine_focus_in` does in addition to that is calling `ibus_engine_register_properties` - which shouldn't be necessary on a reset (besides that we don't seem to do anything with the one status property we register).
=> chore(linux): call `reset_context` instead of `...focus_in`

windows/src/desktop/kmshell/main/UfrmChangeHotkey.dfm
Fixes: #7536
Change the label on the radio button for the "Change Hotkey" dialogue to "No Hotkey" to match the change to the windows configuration.
=> feat(windows): Change "None" to "No Hotkey" matching new config

common/web/keyboard-processor/src/keyboards/activeLayout.ts, common/web/keyboard-processor/src/keyboards/defaultLayouts.ts, web/source/osk/browser/oskSubKey.ts, web/source/osk/oskBaseKey.ts, web/source/osk/oskKey.ts
Fixes #119.
**TEST_BASIC_LOAD_DESKTOP**:  With a desktop or laptop running Chrome, use the "Test unminified Keymanweb" test page and verify that the OSK displays correctly.
- The default keyboard displayed - "English - English" in the keyboard menu - should look like this:
**TEST_BASIC_LOAD_MOBILE**:  With an Android phone (real or emulated), use the "Test unminified Keymanweb" test page and verify that the OSK displays correctly.
- The default keyboard displayed - marked simply as "English" on the space bar - should look like this:
**TEST_MOBILE_FOUR_ROW**:  With an Android phone (real or emulated) running Chrome...
1. Use the "Test unminified Keymanweb" test page.
2. Change keyboard to Norwegian.
3. Verify that the layout looks correct.  It should have a layout similar to this: …
=> feat(web): keyboard layout spec now allows numeric width, pad, sp

.github/workflows/auto-merge-keyman-server-pr.yml, .github/workflows/crowdin.yml, .github/workflows/labeler.yml
Note: GH-sourced actions use tags; 3rd party actions use commit hashes.
Fixes #7521.
=> chore(common): update actions to node16

web/source/kmwbase.ts
Fixes #7467.
Since we've documented it as taking a string, but it was expecting the keyboard script object.
https://help.keyman.com/developer/engine/web/15.0/reference/core/isChiral
=> fix(web): allow `isChiral()` to accept string name parameter of keyboard

android/KMAPro/kMAPro/src/main/res/values-nl-rNL/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java, android/KMEA/app/src/main/res/values-nl-rNL/strings.xml, ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/nl.lproj/ResourceInfoView.strings, ios/engine/KMEI/KeymanEngine/nl.lproj/Localizable.strings, ios/engine/KMEI/KeymanEngine/nl.lproj/Localizable.stringsdict, ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj, ios/keyman/Keyman/Keyman/nl.lproj/Localizable.strings, linux/keyman-config/locale/nl_NL.po, mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/nl.lproj/KMAboutWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/nl.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/nl.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/nl.lproj/KMKeyboardHelpWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/nl.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/nl.lproj/MainMenu.strings, windows/src/desktop/kmshell/locale/nl-NL/strings.xml, windows/src/desktop/setup/locale/nl-NL/strings.xml
This adds the crowdin strings for Nederlands (Dutch) - locale nl-NL
TODO for @sgschantz 
Load the PR build for each platform and set the UI / Locale to Dutch
There may be a handful of strings still in English, but most are in Dutch
* **TEST_ANDROID** 
2. In the Keyman app, go to Settings --> Display Language --> Nederlands (Dutch)
3. Return to the Keyman app 
4. Verify the UI is in Dutch (prompt, Settings strings, etc.). 
* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the device locale to Dutch
3. Return to the Keyman app
4. Verify the UI is in  Dutch
1. Start Keyman configuration with: LANGUAGE=nl_NL km-config
2. Verify Keyman UI is in Dutch
* **TEST_MACOS**
1. Load the PR build of Keyman for macOS
2. …
=> chore(common): Add crowdin strings for Dutch

developer/src/tike/actions/dmActionsKeyboardEditor.dfm, developer/src/tike/actions/dmActionsKeyboardEditor.pas, developer/src/tike/child/UfrmDebug.pas, developer/src/tike/main/UfrmMain.dfm
Fixes #7506.
In the keyboard debugger, we need to mask out <kbd>LControl</kbd> when <kbd>AltGr</kbd> is pressed by the user, because Windows will generate LControl + <kbd>AltGr</kbd> for European layouts.
Note: have also hidden the System Keyboard debug setting in this commit, given it is not currently implemented; see #1225.
A follow-up issue is #7529.
**TEST_ALTGR:** Verify that the <kbd>LControl</kbd> modifier is not set when <kbd>AltGr</kbd> is pressed.
1. Open a keyboard, and start debugging (<kbd>F5</kbd>).
2. Set the debugger into Single Step Mode.
3. In the **Windows language selector**, choose a European keyboard layout such as French or English (UK).
4. In the debugger, press <kbd>AltGr</kbd>+<kbd>X</kbd> (any other letter is okay).
5. The debug status window should show …
=> fix(developer): handle LControl being set by Windows when AltGr pressed

windows/src/engine/keyman32/Keyman32.cpp, windows/src/engine/keyman32/globals.h, windows/src/engine/keyman32/k32_dbg.cpp, windows/src/engine/keyman32/k32_globals.cpp, windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp, windows/src/engine/keyman32/kmhook_getmessage.cpp, windows/src/engine/keyman32/serialkeyeventcommon.h, windows/src/engine/keyman32/serialkeyeventserver.cpp
Fixes #7458 
`wm_keyman_keyevent` and `wm_keyman_modifierevent` have been converted to use the `WM_USER` message range and no longer globally registered messages.
**GROUP_WIN10**  - Run the tests in a Windows 10 OS
**GROUP_WIN11** - Run the tests in Windows 11 OS
**TEST_ALTGR_IN_RULES** 
This is to test the key rules which contain <kbd>AltGr</kbd> or <kbd>Shift</kbd> + <kbd>AltGr</kbd> still work correctly.
* Load a keyboard `khmer_angkor` 
* Open LibreOffice or Notepad 
* Type a <kbd>AltGr</kbd> + <kbd>o</kbd> 
* Observe output of  ឱ​
* Type a <kbd>Shift</kbd> + <kbd>AltGr</kbd> + <kbd>o</kbd> 
* Observe output of ᧨
**TEST_HOTKEYS**
This is to test switching between non-keyman and keyman keyboards using hotkeys. To make sure this PR has not broken Hotkeys that use modifiers 
* Install …
=> chore(windows): convert `wm_keyman_keyevent` and `wm_keyman_modifierevent` to private `WM_USER` messages

ios/help/about/whatsnew.md, ios/help/index.md, linux/help/about/whatsnew.md, linux/help/index.md, linux/help/reference/index.md, mac/help/about/requirements.md, mac/help/about/whatsnew.md, mac/help/common/keyboards.md, mac/help/common/os.md, mac/help/index.md, windows/src/desktop/help/about/whatsnew.md, windows/src/desktop/help/basic/config/options.md, windows/src/desktop/help/index.md
In prep for Beta release, this updates in-app help verbiage from Keyman 15.0 to 16.0 (Android already done in #7507 )
We'll update whatsnew for each platform separately.
=> chore(common): Update help references from 15.0 to 16.0

core/include/keyman/keyboardprocessor.h
Fixes #7487.
`KMN_API` defines only import/export/static modifiers for functions, so it makes no sense to apply it to a typedef. (Previously, I thought it also included a calling convention, but it doesn't.)
=> fix(core): remove `KMN_API` from callback spec

windows/src/developer/TIKE/actions/dmActionsKeyboardEditor.dfm, windows/src/developer/TIKE/actions/dmActionsKeyboardEditor.pas, windows/src/developer/TIKE/child/UfrmDebug.pas, windows/src/developer/TIKE/main/UfrmMain.dfm
Fixes #7506.
Cherry-pick of #7530.
In the keyboard debugger, we need to mask out LControl when AltGr is pressed by the user, because Windows will generate LControl + AltGr for European layouts.
Note: have also hidden the System Keyboard debug setting in this commit, given it is not currently implemented; see #1225.
A follow-up issue is #7529.
=> fix(developer): handle LControl being set by Windows when AltGr pressed 🍒

developer/src/tike/xml/layoutbuilder/constants.js
Fixes #7551.
@keymanapp-test-bot skip I've already tested this to my satisfaction. I don't think we need a user test.
=> fix(developer): exclude `nocaps` from layer id modifier components

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Similar to #7388 and #7472
While trying to get a repro of #7412, I noticed subkeys can get stuck when dismissing/hiding the Keyman system keyboard
1. Install PR build of Keyman for Android on a physical device
* **TEST_LONGPRESS_DISAPPEARS_ON_HIDE** - Verifies longpress keys aren't stuck after hiding system keyboard
2. On the "Get Started" menu, enable Keyman as the default system keyboard
3. Launch a separate app (e.g. Chrome) and touch the search bar
4. Switch system keyboard so Keyman is visible
5. With the right thumb, long-press and hold a key, select a long-press option, and continue holding
6. With the left thumb, press the down arrow on the system taskbar  to dismiss/hide the system keyboard
7. Verify the OSK disappears
8. Release all keyboard presses …
=> fix(android/engine): Dismiss subkeys when hiding keyboard

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java
Follows #7554 and 🍒 pick of #7555 to stable-15.0
I noticed subkeys can get stuck when dismissing/hiding the Keyman system keyboard
1. Install PR build of Keyman for Android on a physical device
* **TEST_LONGPRESS_DISAPPEARS_ON_HIDE** - Verifies longpress keys aren't stuck after hiding system keyboard
2. On the "Get Started" menu, enable Keyman as the default system keyboard
3. Launch a separate app (e.g. Chrome) and touch the search bar
4. Switch system keyboard so Keyman is visible
5. With the right thumb, long-press and hold a key, select a long-press option, and continue holding
6. With the left thumb, press the down arrow on the system taskbar to dismiss/hide the system keyboard
7. Verify the OSK disappears
8. Release all keyboard presses
9. Touch the …
=> fix(android/engine): Dismiss subkeys when hiding keyboard 🍒

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java
🍒 pick of #7388 and #7472 to stable-15.0
Fixes #7510 (16.0 master should already contain the fixes)
This PR causes subkeys to get dismissed when a multi-touch is detected (either another key or globe key)
1. Needs a physical Android device for multi-touch typing (two thumbs)
2. Install the PR build of Keyman for Android
* **TEST_MULTI_TOUCH_DISMISSES_LONGPRESS** - Verifies long-press keys aren't generated when multi-touch detected
1. Start Keyman for Android with the default sil_euro_latin keyboard.
2. If the OSK doesn't start on the Shift layer, press the Shift key change to the Shift layer (upper-case)
3. With the right thumb, start long-press on <kbd>G</kbd> and hold. Immediately with the left thumb press and release the shift button to switch to Default layer
4. With the right thumb …
=> fix(android/engine): Dismiss key previews and subkeys on multi-touch 🍒

android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java
I know we're limiting the changes before going to Beta.
I was trying to get a repro for issue #7412 with the following setup:
Android 12.0 emulator
Older version of sil_euro_latin (1.9.4) to trigger resource update
Keyman 16.0 92 alpha.local
After setting Keyman as the default system keyboard from the "Get Started" menu, and then going to menu --> "Install Updates"
It triggered a crash
```
Process: com.tavultesoft.kmapro.debug, PID: 16261
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:952)
```
This PR just adds the required flag.
Since the CI builds include the latest keyboard …
=> fix(android/engine): Add FLAG_ACTIVITY_NEW_TASK flag for resource update

web/bulk_rendering/README.md, web/bulk_rendering/renderer_core.ts
The old bulk-renderer subproject for OSK regression testing doesn't seem to have been updated in a while.  It _definitely_ seems to rely on patterns from before the big OSK refactor that resulted in the "inlined" OSK mode used by Developer.
So far, I've gotten the desktop-OSK mode working pretty flawlessly, but mobile's an entirely different matter.  The screen-capturing system it's utilizing doesn't seem to play nice with mobile device emulation.  I can get it close, but any zoom factor to the emulation will break the OSK scaling used for its snapshots.  Things will be a bit off even with 99% scaling (Chrome defaults to 99% for iPhone SE emulation with 125% OS UI scaling @ 1080p).
To highlight the previous point, here's a screenshot of the bulk-renderer running in that scenario:
Note how …
=> fix(web): bulk renderer update

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift, ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js, web/source/kmwembedded.ts
Fixes #7517.
Cherry-pick of #7563 for stable-15.0.
Cleans up the setDeviceType code which was attempting to set the device type far too late in the init sequence, and moves responsibility for detection from kmwembedded.ts to ios-host.ts, as this device test is iOS-specific.
=> fix(ios): iPad was not recognised as tablet device 🍒

android/KMAPro/build-play-store-notes.sh
The latest 17.0.1 alpha build failed because the Google Play Store release notes are empty. (The CI script `build-play-store-notes.sh` has a grep that exits if whatsnew.md doesn't contain any line items of changes (e.g.)
```
* TBD
```
This updates the script to continue if the grep fails and fill in default release notes
I tested the script with
* an empty whatsnew.md
* a single entry in whatsnew.md
* a really long (>500 character) whatsnew.md file
=> fix(android): Handle empty Play Store release notes

developer/src/tike/child/UfrmDebug.pas
Fixes #7529.
We must always use the US base layout for the debugger, as positional keyboards are not affected by the active Windows system keyboard. This fix ensures that the behaviour in the debugger matches what the user experiences in Keyman for Windows.
Note that this does not address support for mnemonic layouts, tracked in issue #1074.
For these tests, we want to ensure that every key emits the expected US English key, no matter what the underlying keyboard is. To do this:
1. Create a brand new basic keyboard with no rules.
2. Compile the keyboard (F7), and start the debugger (F5).
3. Press each key in turn on the keyboard: the character emitted should match the character for the US English hardware keyboard.
**TEST_US:** Select the English (US) keyboard in the Windows language …
=> fix(developer): Use US base layout for debugger

developer/src/common/delphi/compiler/CompileErrorCodes.pas, developer/src/kmcmpdll/Compiler.cpp, developer/src/kmcmpdll/Compiler.rc, developer/src/kmcmpdll/comperr.h
Fixes #3784.
Only one type of each `begin` statement should be allowed in any given keyboard source file.
**TEST_NORMAL:** Try compiling a variety of keyboards to ensure they continue to compile successfully.
**TEST_REPEATED:** Create a keyboard with multiple `begin unicode` statements. Try and compile it; it should report an error.
=> fix(developer): prevent repeated `begin` statements

common/windows/delphi/ui/Keyman.System.Util.RenderLanguageIcon.pas, developer/src/kmconvert/Keyman.Developer.System.GenerateKeyboardIcon.pas, developer/src/kmconvert/Keyman.Developer.System.ImportWindowsKeyboard.pas, developer/src/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas, developer/src/kmconvert/Keyman.Developer.System.KeymanConvertMain.pas, developer/src/tike/Tike.dpr, developer/src/tike/Tike.dproj, developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas
Fixes #2803.
The new basic project template will now include a default icon, generated either from the first BCP 47 tag, or else from the first 3 letters of the filename of the keyboard.
The icon will not be included if the keyboard does not target desktop platforms, as web/touch do not currently support the icon.
**TEST_BASIC:** Test that creating a new basic keyboard project includes an icon by default, with the first 3 letters of the BCP 47 tag or the filename. Once the keyboard is created, you can verify the icon in the keyboard editor, Icon tab. The text should usually fit within the icon square (`WWW` may be
difficult!)
**TEST_NO_ICON:** Test that creating a new basic keyboard project that targets only 'web' does not include an icon.
=> fix(developer): generate a default icon for basic keyboard projects

developer/src/tike/main/KeyboardParser.pas
Fixes #298.
**TEST_SAVE:** Create a keyboard source file, with `store(&visualkeyboard)` indented. Make a change to the file and save it. The indent should remain.
**TEST_CHANGE:** With the same keyboard source file, remove the visual keyboard feature from the Details page, then re-add it. The `store(&visualkeyboard)` line should be reformatted, and may change its position in the file. The primary thing we want to ensure is that it is added correctly to the file in this situation.
=> fix(developer): avoid reformatting unchanged system stores

common/web/keyman-version/.npmignore, common/web/keyman-version/build.sh, developer/src/kmlmc/.npmignore, developer/src/kmlmc/build.sh, resources/build/build-utils-ci.inc.sh
Fixes #7582.
Because of https://github.com/npm/cli/issues/3466, we must publish our internal dependency `@keymanapp/keyman-version`. This change adds a common builder function builder_publish_to_npm in build-utils-ci.inc.sh to help with that task, which should be adopted by other scripts that need to publish to npm, in the future.
For now, responsibility for publishing keyman-version is delegated to kmlmc. In the future, we will move this to a single top-level build action that publishes all npm modules across the entire repo for the given version.
We will need to verify whether this is working correctl when we publish the next beta release post-merge. The change will percolate down to alpha with our normal beta-to-alpha merge process.
=> fix(developer): publish `@keymanapp/keyman-version` to npm

HISTORY.md
Due to the order that I merged #7554 and #7562 to stable-15.0, the change from #7554 got missed in HISTORY.md
(both are in the 15.0.272 stable release)
=> chore: Add #7554 to HISTORY.md

developer/src/tike/child/Keyman.Developer.UI.UfrmModelEditor.dfm, developer/src/tike/child/Keyman.Developer.UI.UfrmModelEditor.pas, developer/src/tike/child/UfrmKeymanWizard.dfm, developer/src/tike/child/UfrmKeymanWizard.pas, developer/src/tike/child/UfrmPackageEditor.dfm, developer/src/tike/child/UfrmPackageEditor.pas
Fixes #5238.
The Details and Build tabs have fixed positional content in the Keyboard Editor, Model Editor, and Package Editor. Sizing the window too small can cause content to be outside the bounds of the tab. This patch moves these tabs into scrollboxes (except for Details tabs on Keyboard and Model editors, which were already in scrollboxes). The remaining tabs have resizable content. The tabs will still become fairly unusable if they become too small, but this should be less of a problem than before.
For all these tests, make sure the Keyman Developer window is not maximized, or alternatively, that the Message window is large enough that it causes scrollbars to appear on tabs.
* **TEST_KEYBOARD_DETAILS_TAB:** Verify that the Keyboard Editor Details tab gets a vertical scrollbar when …
=> fix(developer): Make Details and Build tabs scrollable

common/windows/delphi/general/Glossary.pas
Fixes #7599.
MSKLC HKLs have high bit set, which means that we need to explicitly cast from Integer to DWord to avoid range check errors.
=> fix(developer): handle high-bit-set HKL correctly

resources/build/build-utils-ci.inc.sh
Follow-up for #7595 after build failed with:
```
[17:44:32][Step 8/8] ## [common/web/keyman-version] publish starting...
[17:44:34][Step 8/8] v16.0.95-beta
[17:44:34][Step 8/8] /c/BuildAgent/work/deb663ed6681f452/keyman/resources/build/build-utils-ci.inc.sh: line 101: dry_run: unbound variable
[17:44:34][Step 8/8] ## [common/web/keyman-version] publish failed
```
Relates to #7582.
=> fix(common): always define dry_run variable

web/source/osk/browser/pendingMultiTap.ts
Applies proposed feature https://community.software.sil.org/t/testing-caps-on-touch/6849/5:
1. A `caps` layer must still exist in the keyboard.
2. If there is at least one multitap subkey defined on the Shift key on the active layer, then the `nextlayer` property of the first multitap subkey for the Shift key will be used instead of the default `caps`.
3. This does not change the behavior of the Shift key otherwise.
For example, the following defines a valid multitap key on Shift on the `rightalt` layer to switch to a custom extended `rightalt-shift-caps` layer.
```
{
"id": "K_SHIFT",
"text": "*Shift*",
"width": 150,
"sp": 1,
"nextlayer": "rightalt-shift",
"layer": "default",
"multitap": [
{
"text": "",
"id": "T_new_694",
"sp": "1",
"nextlayer": "rightalt-shift-caps"
}
]
},
```
This does …
=> feat(web): Custom layer targets for Shift double-tap

android/KMEA/app/src/main/java/com/tavultesoft/kmea/JSONParser.java
Fixes #7564 
I'm not sure the circumstances, but from the Sentry logs it appears there's times the Cloud catalog queries return `[]` and the Keyman Engine JSON parsing code throws an exception treating it as a JSONObject.
This updates the JSON parser to treat `[]` as an empty JSON Object.
=> fix(android/engine): Handle parsing empty JSONArray as JSONObject

common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts
- make it clearer what the exact issue is by extracting params from the Ajv error
Old message: 
> ERROR 300007: The source file has an invalid structure: Error: data/keyboard must NOT have additional properties
New message: 
> ERROR 300007: The source file has an invalid structure: Error: /keyboard: additionalProperties: must NOT have additional properties {"additionalProperty":"layerMaps"}
err objects are documented https://ajv.js.org/api.html#error-objects so this is depending on stable API
=> feat(developer): improve err msg from Ajv 🙀

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/GetStartedActivity.java
Fixes #5229 and will impact Acceptance testing of Keyman for Android
Currently on a clean installation, the "Get Started" menu will appear until the user unchecks the last box (onCheckedChanged() saves the state as a user preference)
This PR changes it so if the user preference doesn't exist and the user completes steps 2-3
* Enable Keyman as a system-wide keyboard
* Set Keyman as default keyboard
the checkbox will automatically get unchecked and gets saved as a user preference.
Note, if the user has actively set the checkbox (which saves the user preference), this override won't happen.
* **Setup** - Clean installation of the PR build of Keyman for Android on emulator or device on English locale
* **TEST_CLEAN_INSTALL** - Verifies the "Get Started" menu defaults to appear on startup
1. …
=> fix(android/app): Don't show "Get Started" after setting Keyman as default system keyboard

windows/src/desktop/kmshell/kmshell.dproj
Should allow us to get line numbers for kmshell.exe crash reports.
This seems to have been broken some time between 14.0 and 15.0. Not yet clear if it is an issue here or elsewhere.
=> fix(windows): include debug info in kmshell build

core/src/debuglog.cpp
maybe a clang upgrade did this, not sure.
Anyway, snprintf is a good idea.
```
../../../src/debuglog.cpp:351:3: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only. 
Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. 
[-Werror,-Wdeprecated-declarations]
sprintf(windowinfo,
^
```
=> fix(core): sprintf to snprintf

android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java
Fixes some of the Sentry crashes in #6862 where the temporary kmp file during a package installation suddenly isn't available.
We still haven't found what can cause the temporary kmp file to be removed...
=> fix(android/engine): Check temporary kmp file is valid

developer/src/server/src/site/test.js
Fixes #7622.
The first commit addresses the core issue. The second commit ensures that Keyman is initialized before interactions can happen with the device menu.
=> fix(developer): set keyman.osk immediately after switching device type

developer/src/tike/xml/app/editor/editor.js, developer/src/tike/xml/app/package-lock.json, developer/src/tike/xml/app/package.json
Updates Monaco editor from 0.14.3 to 0.15.6, incorporating microsoft/vscode#57617 to fix #7625.
The changes to editor.js are required because `editor.model` was not a public property and we should have been using `editor.getModel()` all along.
I have not updated to the latest version of monaco (0.35.1 at time of writing this), as I wish to minimize the changeset during beta.
While I prefer not to update dependencies in beta, this seems to be a fairly clean update. Will monitor and can roll back if it leads to instability.
* **TEST_FIXES_7625:** In a .kmn source file for a new basic keyboard project, press F12 to open the Developer console. Return to the editor and type `V` on a new line. A popup should appear with, e.g. `VERSION`, `VISUALKEYBOARD`. Select the second item in the list with …
=> fix(developer): update monaco editor to 0.15.6

developer/src/tike/actions/dmActionsKeyboardEditor.pas
Fixes #7641.
If you close the active project and have the Welcome window visible, it was possible for the Compile action to still be enabled, even though there was nothing to compile.
=> fix(developer): disable Keyboard|Compile if no project loaded

developer/src/kmlmc/package.json
This is blocking usage via npm. To test next version:
```
npm init
npm install @keymanapp/lexical-model-compiler
./node_modules/.bin/kmlmc
```
=> fix(developer): kmlmc has runtime dependency on keyman-version

common/web/input-processor/src/text/inputProcessor.ts, common/web/keyboard-processor/src/text/keyboardProcessor.ts
Fixes #7636.
When using the touch 'system' keyboard, the modifier keys are reset by the kbdMismatch logic introduced in #7543. This is evident in the web debugger of Keyman Developer, where the system keyboard is easily accessible.
This maintains the fix from #7543, but removes the `resetContext()` side-effect. That may have negative consequences for the original fix, but given the original fix is targeted for the rare keyboard switch scenario, it seems manageable.
I am not convinced that this is the most appropriate place to fix the problem. There may be a better fix in terms of when `activeKeyboard=null`, which is what is triggering the `kbdMismatch` flag, because internally there is a implicit synthetic system keyboard that KMW uses in this situation, and that is what is being switched …
=> fix(web): avoid reset for touch system keyboard

common/web/keyboard-processor/src/text/defaultOutput.ts, developer/src/tike/xml/layoutbuilder/builder.js, developer/src/tike/xml/layoutbuilder/prepare-key.js, developer/src/tike/xml/layoutbuilder/subkeys.js, web/source/osk/oskKey.ts
Fixes #7616.
Fixes a crash when attempting to infer key cap text from key id, and cleans up the support for inferred key text so that it works correctly in the designer.
When using `U_xxxx` style key ids, and where the key text is empty, the key cap should dynamically reflect the Unicode value of the key id. This has always been supported in KeymanWeb, but the implementation in the editor was somewhat unstable in the past.
Also adds a safeguard to KMW to stop invalid key ids causing a crash.
* **TEST_INFERRED_ID:** In touch layout editor, select a key, delete the key text, and set the key ID to `U_1234` or similar. The key should show the new character on the key cap, but the key text field should remain empty. Switch layers and ensure that the key text field remains empty for that key.
* …
=> fix(developer): improve support for inferred key cap text

common/web/lm-worker/build.sh, common/web/lm-worker/src/polyfills/array.findIndex.js
Follow-on to #7646 - this adds a polyfill for Array.findIndex() needed for the wordbreaker update in #7279 
The user test involves installing a modified sil.jra-khmr.jarai,model dictionary with custom word breaking based on
https://github.com/keymanapp/keyman/files/9553911/sil.jra-khmr.jarai.model.kmp.zip from PR #7279.
with the following modifications in the model.js file for Android 5.0 compatibility:
* Change `let` to `var`
* Change array functions
**Setup**
1. Install the PR build of Keyman for Android on an Android 5.0 (API 21) emulator/device.
2. Launch a browser and download the modified copy of [sil.jra-khmr.jarai.model](https://darcywong00.github.io/examples/jra/sil.jra-khmr.jarai.model.kmp) (Should save to the Downloads folder)
3. Return to Keyman, from the Keyman Settings menu …
=> fix(web): Add polyfill for Array.findIndex()

developer/src/tike/http/Keyman.Developer.System.HttpServer.AppSource.pas, developer/src/tike/oskbuilder/UframeTouchLayoutBuilder.pas
Relates to #6928 and KEYMAN-DEVELOPER-74.
Fixes one more potential pathway for assertions being raised, and adds some extra debugging in case there are additional pathways we are not capturing.
=> fix(developer): handle edge cases for app sources

developer/src/tike/Tike.dpr, developer/src/tike/main/UfrmMain.pas, developer/src/tike/update/Keyman.Developer.UI.TikeOnlineUpdateCheck.pas
Fixes #4757.
Fixes #6928.
This may also fix some other Developer crashes relating to CEF, as some of those are probably due to unclean shutdown.
Three separate ways shutdown is more robust:
1. Destroy main form before web server -- this ensures that all main form routines have deregistered app sources from web server.
2. In some situations, `FormClose` can be skipped by shutdown routines, for example, if you call `Application.Terminate`. This change ensures that we get a second chance to cleanup in the form destructor with `DoCloseCleanup`.
3. In the Online Update Check, instead of `Application.Terminate`, we now use `Application.MainForm.Close`, which is much more polite, as it ensures that changed files are saved, etc, and does proper cleanup. This particular change may make the other …
=> fix(developer): handle shutdown cleanup more cleanly

common/windows/delphi/general/Keyman.System.KeymanSentryClient.pas
Fixes #7656.
If Keyman Developer is installed, but not Keyman for Windows, then tsysinfo.exe is not present. If a crash occurs, this causes a secondary crash when trying to display the error handler dialog. In this situation, we now just show a dialog box with a short message rather than the more friendly dialog available via tsysinfo.exe.
We could consider adding tsysinfo.exe into Keyman Developer for a future release.
=> fix(developer): handle crash reports without Keyman Engine installed

developer/src/tike/xml/app/editor/editor.js
Fixes #7658.
When manipulating text that contains an unpaired surrogate, the text editor could throw an exception trying to encode the text to send through to the token command. This simply masks that error.
=> fix(developer): handle unpaired surrogate

windows/src/desktop/kmshell/main/UfrmWebContainer.pas
Hopefully fixes KEYMAN-WINDOWS-1MR, and probably many related crash reports. Will monitor on alpha before porting to stable/beta.
This changes the form destruction sequence to make sure that it doesn't close the form until CEF has been shutdown correctly.
We are going to need to do a full regression on this, but that can wait until we exit beta.
=> fix(windows): Cleanup CEF more correctly in shutdown

core/src/kmx/kmx_actions.h, core/src/kmx/kmx_options.cpp, core/src/kmx/kmx_options.h, core/src/kmx/kmx_processevent.cpp, core/src/kmx/kmx_processor.cpp, core/tests/unit/kmnkbd/debug_api.cpp
Fixes #7643.
The kmn statement `save()` action was being written directly to the state queue, bypassing the internal kmx action queue. This caused two issues:
1. `save()` actions were out-of-order with other actions on the same key event.
2. The number of items in the internal action queue became out of sync with the debug item queue, which would cause the debugger to fail with an assertion.
The new test in debug_api.cpp validates this second issue as the number of items in the action queue now matches the expected count in the corresponding debug item.
* **TEST_SAVE_ACTION:** Using the keyboard in #7643, test it in the Keyman Developer debugger. Press <kbd>s</kbd> and verify that `save` is emitted, and that Developer doesn't crash 🤣
=> fix(core): `save()` should be on internal kmx action queue

core/src/kmx/kmx_actions.h, core/src/kmx/kmx_processor.cpp, core/tests/unit/kmnkbd/action_items.hpp, core/tests/unit/kmnkbd/debug_api.cpp, developer/src/tike/debug/Keyman.System.Debug.DebugEvent.pas, developer/src/tike/main/Keyman.System.KeymanCore.pas, developer/src/tike/main/Keyman.System.KeymanCoreDebug.pas
Fixes #7649.
emit_keystroke code path in kmx processor was writing directly to the core queue instead of to the internal kmx processor queue. This caused it to be out-of-order in the actions sent to the engine/debugger.
Engines didn't really care but it broke the debugger, for example if only a deadkey was in the buffer and backspace was pressed, Developer would assert as it would get unexpected context for the deletions.
**TEST_REGRESSION:** I would like to ensure that this is covered in the Linux, Developer, and Windows regression tests in Beta. I don't know if it needs a separate test.
The test we should aim for is to ensure that backspace is working correctly in all contexts, including with rule processing, particularly when deadkeys/markers are involved.
=> fix(core): emit keystroke was writing to wrong queue

android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java
Follow-on to #7390 which generates Toast notifications on errors and exceptions.
This updates KMLog so the Toast notifications appear only on pre-release builds.
I verified locally that the beta build shows a Toast error along with the [Sentry error](https://sentry.io/organizations/keyman/issues/3731201459)
=> chore(android/engine): Don't show Toast errors on stable tier

common/windows/delphi/general/Keyman.System.KeymanSentryClient.pas, windows/src/engine/keyman/UfrmKeyman7Main.pas, windows/src/engine/keyman/kmint.pas
Relates to KEYMAN-WINDOWS-B.
While this doesn't address the root cause of the exception, it should prevent this unhandled exception, and adds breadcrumbs to help us see which code path might be triggering the issue.
=> fix(windows): Improve shutdown robustness

windows/src/engine/keyman32/CoreEnvironment.cpp, windows/src/engine/keyman32/K32_load.cpp, windows/src/engine/keyman32/Keyman32.cpp, windows/src/engine/keyman32/Keyman32.vcxproj, windows/src/engine/keyman32/Keyman32.vcxproj.filters, windows/src/engine/keyman32/keymanengine.h, windows/src/engine/keyman64/keyman64.vcxproj, windows/src/engine/keyman64/keyman64.vcxproj.filters
While Keyman Core already supported the base layout flags, they were not being passed in from Keyman Engine for Windows. This meant that any rules that used `baselayout` would fail, such as in sil_ipa with <kbd>AltGr</kbd>+<kbd>0</kbd> for `}`: https://github.com/keymanapp/keyboards/blob/0bf72bed74f563f823b1af002f6a8ccef8510ebf/release/sil/sil_ipa/source/sil_ipa.kmn#L348-L350
This patch adds support for the following properties:
* `KM_KBP_KMX_ENV_BASELAYOUT`: the legacy base layout name, e.g. kbdus.dll
* `KM_KBP_KMX_ENV_BASELAYOUTALT`: the BCP 47 base layout name, e.g. en-US
* `KM_KBP_KMX_ENV_SIMULATEALTGR`: whether the user has selected to emulate AltGr with Ctrl+Alt, for example on laptops without a right alt key.
* `KM_KBP_KMX_ENV_BASELAYOUTGIVESCTRLRALTFORRALT`: whether the system …
=> fix(windows): base layout support in Keyman Core

common/windows/delphi/general/utilhttp.pas, common/windows/delphi/web/Keyman.System.HttpServer.Base.pas, developer/src/tike/http/Keyman.Developer.System.HttpServer.App.pas, developer/src/tike/http/Keyman.Developer.System.HttpServer.AppSource.pas
Fixes #7628.
Indy components do not treat URLs as UTF-8. Our legacy `URLEncode()` function (sourced from Indy components) was the same. Discovered we needed to fixup the parsing of URLs as well as the construction of them; there may be other places we need to fix, although I did do a search for the relevant types in TIKE source.
* **TEST_NON_ASCII_PATHS:** Create a folder that contains non-ASCII letters, e.g. Khmer, Tamil or European diacritics. Create a new keyboard project within that folder. In the Project view, press F12 to verify that no errors are raised in the Developer console. Do a basic regression test on working with the keyboard project, including editing, compiling.
=> fix(developer): URL parameters should be UTF-8

android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
:cherries: pick of #7664 to stable-15.0
Rather than applying for the QUERY_ALL_PACKAGES permission, we'll handle NameNotFoundExceptions as follows
> Quick fix seems like would be we handle NameNotFoundExceptions and just use the package name in that case?
So we'll fallback to display the packageName (not the descriptive keyboard name) on the keyboard picker.
Setup
1. Install the PR build of Keyman for Android on an Android 11+ device/emulator. You'll need to be signed into the Google Play Store for the other setup step
2. From the Google Play Store, install another IME (e.g "dominicweb african keyboard" is the one from some Sentry logs)
3. Setup the IME as an enabled system keyboard
* **TEST_PACKAGE_NAME_LISTED** - Verifies NameNotFound exception isn't thrown and other IME's appear on the …
=> fix(android/engine): Use IME package name if query permission denied 🍒

android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardPickerActivity.java
Fixes #7664 
Rather than applying for the QUERY_ALL_PACKAGES permission, we'll handle NameNotFoundExceptions as follows
> Quick fix seems like would be we handle NameNotFoundExceptions and just use the package name in that case?
So ~on Android 11+ devices,~ we'll fallback to display the packageName (not the descriptive keyboard name) on the keyboard picker.
Setup
1. Install the PR build of Keyman for Android on an Android 11+ device/emulator. You'll need to be signed into the Google Play Store for the other setup step
2. From the Google Play Store, install another IME (e.g "dominicweb african keyboard" is the one from some Sentry logs)
3. Setup the IME as an enabled system keyboard
* **TEST_PACKAGE_NAME_LISTED** - Verifies NameNotFound exception isn't thrown and other IME's appear on the …
=> fix(android/engine): Use IME package name if query permission denied

linux/ibus-keyman/src/keymanutil.c
Show the keyboard specific icon in the system tray on Wasta instead of the generic keyman one.
Fixes #7547.
- The test should be run on Wasta 20.04 with Cinnamon
- Install the Khmer Angkor keyboard
- Reboot
**TEST_ICON**: keyboard specific icon shows
- switch to Khmer Angkor keyboard by clicking on the icon in the system tray:
- verify that the keyboard specific icon shows instead of the generic Keyman icon:
=> fix(linux): Fix keyboard icon in system tray

linux/debian/control
This removes a warning on the Debian package page (https://tracker.debian.org/pkg/keyman).
=> chore(linux): Update Debian standards version

windows/src/desktop/kmshell/kmshell.dpr
Fixes #7690.
When kmshell.dpr is being shut down by Windows via `WM_ENDSESSION`, the order of termination of units through `finalization` sections means that `IdStackWindows` was finalizing while components were still depending on it, causing a cascade of exceptions resulting eventually in the crash visible in #7690.
We saw this when there were message loops before `Application.Run` had ever been called. For example, message box/dialog, ShellExecute (yep... this can do a `PeekMessage`), `THttpUploader` (which calls `Application.ProcessMessages`) and probably others.
Ideally, it would be better to always call `Application.Run`, but it is not safe to call `Application.Run` more than once, because it ends up adding multiple `DoneApplication` exit procs, which would likely cause other …
=> fix(windows): make sure IdStackWindows finalizes after Vcl.Forms

android/KMAPro/kMAPro/build.gradle, android/KMAPro/kMAPro/src/main/res/values/strings.xml, android/version.gradle
Addresses #7364 by appending the tier to the app name. For stable, we'll keep the default 'Keyman'.
Developers likely aren't going to have `TIER` defined as an environment variable though so I'm updating version.gradle to include VERSION_TIER. (CI only sets it for Release- and not Test- builds anyway)
Setup - Install the PR build of Keyman for Android 
* **TEST_APP_NAME** - Verifies the app name shows the tier
1. From the device launcher, show all apps
2. Browse to Keyman and verify the name is "Keyman Beta-test-7674"
3. Launch Keyman 
4. On the "Get Started" menu, enable Keyman as a system keyboard
5. Verify the Android system keyboard list has "Keyman Beta-test-7674"
6. On the Keyman "Get Started" menu, set Keyman as default keyboard
7. Verify the Android "Choose input method" list …
=> fix(android/app): Append tier to app name

windows/src/engine/keyman/langswitch/UfrmLanguageSwitch.pas
Fixes #7698.
Due to a `>` instead of a `>=` check, there was a one pixel high box at the bottom of each list of input methods for each language which would reuslt in an invalid value for `FNewHoverKeyboard` (`lang.KeyboardCount`).
As well as fixing this, I changed the result for clicking below the input method list to the more logical last item in the list rather than the first.
=> fix(windows): click in 1 pixel high box in Language Switch window caused crash

windows/src/desktop/kmshell/xml/config.js, windows/src/desktop/kmshell/xml/menu-frame.js, windows/src/desktop/kmshell/xml/menu.js
Adds Sentry breadcrumbs for the following crash reports:
* KEYMAN-WINDOWS-62
* KEYMAN-WINDOWS-6H (? no reports in recent releases, so may be resolved)
* KEYMAN-WINDOWS-7J
* KEYMAN-WINDOWS-4R
The source of these crashes is hard to pinpoint, so hoping that this additional data sheds some light.
=> chore(windows): add sentry traces for unsolved crashes

windows/src/engine/kmcomapi/com/system/keymancontrol.pas, windows/src/engine/kmcomapi/util/internalinterfaces.pas, windows/src/global/delphi/cust/custinterfaces.pas
This makes it easier to track what is happening for errors where otherwise we found that exception messages were being cropped; for example:
* [KEYMAN-WINDOWS-X](https://sentry.io/organizations/keyman/issues/2700324563/?project=5983518&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d)
* [KEYMAN-WINDOWS-BR](https://sentry.io/organizations/keyman/issues/2830726485/?project=5983518&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d)
The error messages were being cropped because the exception handler was in the exe module, but the exception was being raised in kmcomapi module. When the exception was handled, the handler tested to see if the exception object inherited from exemodule.Exception, but it was inheriting from kmcomapi.Exception instead, and so …
=> chore(windows): Add safecall for internal CustomisationStorage API interface

windows/src/desktop/kmshell/install/Keyman.Configuration.UI.InstallFile.pas, windows/src/engine/kmcomapi/processes/package/kpinstallpackage.pas
Fixes #6412
The fix addresses the crash by testing for file existence before continuing, in the admin account run, it show a message to the user if not in Silent mode. 
Testing this is quite tricky. The way I was able to test this was to have a mapped network drive that was accessed with a different user than the user of my local machine.  See. [windows troubleshooting note](https://learn.microsoft.com/en-us/troubleshoot/windows-client/networking/mapped-drives-not-available-from-elevated-command)
I can run this test if you are not able to replicate it. 
**TEST_INSTALL_KMP_MAPPED_DRIVE**
1. Install the Keyman associated with this PR.
2. Download a Keyboard file `sil_ipa.kmp` and copy it to a folder on a mapped network drive.
3. Double-click the `sil_ipa.kmp` file on the mapped network …
=> fix(windows): check if permissions for thread to access file

linux/ibus-keyman/src/engine.c
This refactoring makes use of the already defined strings. It also simplifies setting the values by directly specifying an UTF-16 string.
Motivated by the changes in PR #7667.
=> refactor(linux): Use consts instead of strings

android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/KeyboardController.java
For analyzing #7712 
This adds an additional log to try to get more insight on why some users can't load en_sil_euro_latin
=> chore(android/engine): Add more logging for keyboard restart

linux/keyman-config/km-config
The help text for `km-config` mentioned a `keyman://` URL but we nowhere explained how that URL should look like. This change adds an example keyman:// URL with a bcp47 tag which should make things clearer.
=> docs(linux): Add example for keyman:// URL format

linux/debian/rules
DEB_VERSION is used to set `pkgversion` in the `override_dh_auto_build` build step. When we moved to the consolidated source package and thus could no longer use the default debhelper build tools we lost the automatic setting of DEB_VERSION, so this change adds the relevant definitions.
Fixes #7724.
=> fix(linux): set DEB_VERSION

linux/keyman-config/keyman_config/canonical_language_code_utils.py
Fixes #7723.
**TEST_NOCRASH**: install  a keyboard from the command line, specifying `bcp47=und`
- open a terminal and run
```
km-config -i keyman://download/keyboard/sil_el_ethiopian_latin?bcp47=und
```
- verify that no crash shows in the terminal (i.e. no call stack shows up)
=> fix(linux): Don't crash if `und` is specified without `fonipa`

windows/src/engine/keyman32/CoreEnvironment.cpp
Fixes #7687.
We'll want to build a keyboard to test that the platform is set correctly. The keyboard should have a single rule:
```
platform('windows hardware desktop native') + 'a' > 'Success!'
```
* **TEST_PLATFORM:** Install and activate the keyboard that you just built above. Press <kbd>a</kbd> and the result should be `Success!`.
=> chore(windows): set platform core env explicitly

android/version.gradle
See #7736 for same change applied to master/alpha. This PR and https://github.com/keymanapp/keyman/pull/7736 should be merged at the same time.
Accidental publish of beta 17.0.6 during 16.0 beta cycle has forced a version_major bump, which is a permanent change. Relates to issue #7705.
---
Version code is, for 17.1.33: 1810033. This supports up to 9999 builds for a given major.minor version. We only support up to 9 minor versions for a given major version but at present we are not using minor versions at all.
Despite this calculation, the version_code should be treated as an opaque integer, used only for Play Store publishing.
=> fix(android): bump version_code major calculation

android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java, android/KMEA/app/src/test/java/com/tavultesoft/kmea/packages/PackageProcessorTest.java
While investigating this [Sentry issue](https://sentry.io/organizations/keyman/issues/3738919593/?project=5983520) I saw the user was attempting to install a keyboard package of packageID `obolo_chwerty-1`.
Since packageID is determined by the filename of the .kmp file, it seems to be a case where a .kmp file is downloaded multiple times, and the system appended `-1` to make the filename `obolo_chwerty-1.kmp` (On my Samsung device, it appends ` (1)` so it would be `obolo_chwerty (1).kmp`).
This updates PackageProcessor to strip out the extra numbers in the filename (packageID should never contain spaces or hyphens).
In addition to adding a unit test, I verified with Android Studio that installing "khmer_angkor-1.kmp" and "khmer_angkor (1).kmp" results in the correct packageID …
=> fix(android/engine): Remove duplicate file suffix when installing .kmp

linux/keyman-config/keyman_config/fcitx_util.py
=> fix(linux): Ignore dbus exception when testing for fcitx

linux/keyman-config/km-package-install
This change adds a `--bcp47 <TAG>` parameter to km-package-install. This allows to specify a language tag which will be used to install the keyboard for that language.
Closes #7725.
- Reboot
**TEST_INSTALL**: Install keyboard for specific language from command line
- open terminal window and run
```
km-package-install -p sil_el_ethiopian_latin --bcp47 ssy-latn
```
- verify that this installed `Saho - SIL EL Ethiopian Latin` keyboard
=> feat(linux): Add optional bcp47 parameter to km-package-install

windows/src/desktop/kmshell/xml/downloadkeyboard.xsl
=> fix(windows): Download Keyboard blue footer

web/source/osk/oskRow.ts, web/source/osk/oskView.ts, web/source/osk/visualKeyboard.ts, web/testing/build-visual-keyboard/index.html
Fixes #7691.
Also provides some initial exploration & experimentation toward #4881.
Addresses a couple of points from #7268.
There are four total bugs addressed by this PR:
1.  Keyboard documentation elements were not being given their appropriate styling.
a. The top-level keyboard-documentation object was not marked with a CSS class corresponding to the keyboard.
b. Even if it were, the corresponding CSS stylesheet was never applied; it had only ever been inserted as part of a live, non-static OSK.  (The code was in `OSKView`, not `VisualKeyboard`, and so the doc-keyboard functionality never touched it.)
2. Row height was not being properly set for documentation keyboards, leaving an ugly 'blank row" on four-row layouts.
3.  The layer ID specified for documentation keyboards was never …
=> fix(web): documentation keyboard style application + layout

windows/src/desktop/kmshell/xml/config.css, windows/src/desktop/kmshell/xml/help.xsl, windows/src/desktop/kmshell/xml/hint.css
Fixes #7748
Also fixed the help dialogue which had the same issue. Fixed the over colour for the ok button.
=> fix(windows): fix checkbox and hint help button styles

linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/keyman_config/list_installed_kmp.py, linux/keyman-config/km-package-install
Fixes #7722.
- Reboot
- install a shared keyboard
```
sudo km-package-install -s -p sil_el_ethiopian_latin
```
**TEST_INSTALL**: Install the same keyboard for a different language
- open a terminal window and run
```
km-config -i keyman://download/keyboard/sil_el_ethiopian_latin?bcp47=ssy-latn
```
- verify that the dialog "Keyboard is installed already. Do you want to uninstall then reinstall it?" doesn't show up
- verify that there is no error `ERROR:Keyboard directory for sil_el_ethiopian_latin does not exist. Aborting` output in the terminal window
=> fix(linux): Fix installation if shared kbd already installed

linux/ibus-keyman/src/engine.c
`size_t` is defined as `unsigned int`, not as a long.
=> fix(linux): Fix a warning

android/KMAPro/kMAPro/build.gradle, android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMEA/app/build.gradle, android/KMEA/app/src/main/AndroidManifest.xml, android/Samples/KMSample1/app/build.gradle, android/Samples/KMSample1/app/src/main/AndroidManifest.xml, android/Samples/KMSample2/app/build.gradle, android/Samples/KMSample2/app/src/main/AndroidManifest.xml, android/Tests/KeyboardHarness/app/build.gradle, android/Tests/KeyboardHarness/app/src/main/AndroidManifest.xml, oem/firstvoices/android/app/build.gradle, oem/firstvoices/android/app/src/main/AndroidManifest.xml
Fixes #7745 
Normally these updates are done at the start of alpha development, but the Play Store blocked the latest build
> "Your app currently targets API level 30 and must target at least API level 31."
This updates the Gradle files to use SDK version 31, which involves some AndroidManifest.xml changes involving
https://developer.android.com/about/versions/12/behavior-changes-12#exported
* Activities, services, and broadcast receivers that use intent filters require the attribute: `android:exported="true|false"`
* Only updating androidx.test.ext:junit dependency to 1.1.3 (fixes those "exported" calls in the merged manifest)
Setup - Install PR build of Keyman for Android on an Android emulator/device of Android 12 (SDK version 31)
* **TEST_KEYMAN_FUNCTIONALITY** - Verifies Keyman can …
=> chore(android): Update Target SDK Version to 31

windows/src/desktop/kmshell/xml/config.css, windows/src/desktop/kmshell/xml/keyman_keyboardlist.xsl
Revert the MS CSS style for the add-remove language pop dialogue in the keyman configuration.
=> fix(windows): backout ms button style for add lang pop up

android/KMAPro/kMAPro/src/main/java/com/keyman/android/CheckInstallReferrer.java
Addresses a significant proportion of the Sentry errors [onInstallReferrerSetupFinished:FEATURE_NOT_SUPPORTED](https://sentry.io/organizations/keyman/issues/2700298447/?project=5983520&query=is%3Aunresolved+FEATURE_NOT_SUPPORTED&referrer=issue-stream&statsPeriod=90d)
#5230 added the feature to automatically install keyboard through Google Play Store. The API is only supported when Keyman is installed directly from the Google Play Store.
This updates CheckInstallReferrer to return before the Install Referrer API is called when Keyman is installed via:
* side loaded install (which includes nearly all local and test builds)
* package manager other than Google Play Store ("com.android.vending")
Unfortunately, we can't really do user-testing until the app is available on the pre-release Play …
=> fix(android/app): Only check Install Referrer API with Play Store installs

windows/src/desktop/kmshell/kmshell_project.tvsconfig, windows/src/desktop/kmshell/xml/config.css
Fixes #7747 
Version 15 is also broken (possibly the update libcef as chrome use to inherit the behaviour).
I have added the user-select: none property to `#keepintouch_frame` for completeness however the embedded webpage overrides it. Using the developer tools I could set the property for the embedded page and the text was no longer selectable. So we need to update the source web page property for embedded. 
* TEST_SELECT_TEXT
Open Windows Configuration.
Select the Support Tag.
Verify you can no longer select the text in the header, the side tabs or the footer. (as seen in issue #7747)
The mouse pointer stays as a pointer and does not turn to a text cursor. 
Repeat for the other tabs.
Note for the `Keep in touch tab` you can still select the webpage text this is a separate issue.
=> fix(windows): Fix text selectable configuration

developer/src/kmlmc/source/lexical-model-compiler/model-defaults.ts, developer/src/kmlmc/tests/test-model-definitions.ts
Fixes the following issue listed under https://github.com/keymanapp/lexical-models/issues/143#issuecomment-1096934795:
> If the lexical model uses U+0027 "apostrophe", what will happen when this model is used with a keyboard that changes apostrophe (U+0027) to "right single quotation mark" (U+2019) [?]
Note:  this is implemented within the lexical model compiler.  Models will only receive a fix when they are recompiled using an up-to-date version after this is merged.
=> feat(common/models): directional quote insensitivity

common/windows/delphi/chromium/Keyman.UI.UframeCEFHost.pas
Noted while debugging locally. Probably rare. (WPARAM is unsigned)
=> fix(developer): cast to prevent ERangeError for failed http reqs in CEF

HISTORY.md, resources/build/version/src/fixupHistory.ts
Cleans up history -- some entries missing due to way they were merged into master.
Fixes #7627.
=> chore: cleanup history

android/KMAPro/kMAPro/build.gradle, android/KMAPro/kMAPro/src/main/AndroidManifest.xml, android/KMEA/app/build.gradle, android/KMEA/app/src/main/AndroidManifest.xml, android/Samples/KMSample1/app/build.gradle, android/Samples/KMSample1/app/src/main/AndroidManifest.xml, android/Samples/KMSample2/app/build.gradle, android/Samples/KMSample2/app/src/main/AndroidManifest.xml, android/Tests/KeyboardHarness/app/build.gradle, android/Tests/KeyboardHarness/app/src/main/AndroidManifest.xml, oem/firstvoices/android/app/build.gradle, oem/firstvoices/android/app/src/main/AndroidManifest.xml
🍒 pick of #7761 for beta since the Play Store is failing beta builds too.
This updates the Gradle files to use SDK version 31, which involves some AndroidManifest.xml changes involving
https://developer.android.com/about/versions/12/behavior-changes-12#exported
* Activities, services, and broadcast receivers that use intent filters require the attribute: `android:exported="true|false"`
* Only updating androidx.test.ext:junit dependency to 1.1.3 (fixes those "exported" calls in the merged manifest)
Setup - Install PR build of Keyman for Android on an Android emulator/device of Android 12 (SDK version 31)
* **TEST_KEYMAN_FUNCTIONALITY** - Verifies Keyman can download keyboards and be used as system keyboard
2. On the "Get Started" menu, add a keyboard for your language from …
=> chore(android): Update Target SDK Version to 31 🍒

android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtil.java
These lines were originally in #7781, but since I still have to investigate a few things on that PR, I'm splitting this to a separate one.
Fixes null pointer exception in `CloudDataJsonUtil` when the update KMP filename is null.
Sentry issue: [KEYMAN-ANDROID-20Y](https://sentry.io/organizations/keyman/issues/3659638286/?referrer=github_integration)
=> fix(android/engine): Add null check on kmp filename

ios/keyman/Keyman/Keyman/AppDelegate.swift, ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift
Fixes #7185 
Modified the way that the text size setting is initialized during the creation of Keyman's in-app editor view so that it is always in sync with the user's saved value and the text size slider.
* **TEST_IPHONE_IN_APP_EDITOR:**
1. Run Keyman on an iPhone or simulator with no user data saved so that no previous text or installed keyboards appear in the app
2. Type some text in the in-app editor
3. The text should appear in a 16 point font, but it may be difficult to see if it is the correct size
4. Go to the three dots menu and choose Text Size, confirm that it is set to 16
5. While carefully watching the text you typed to make sure that it does not change size, tap on the slider control without moving it
* **TEST_IPAD_IN_APP_EDITOR:**
1. Run Keyman on an iPad or simulator with …
=> fix(ios): make text size of in-app editor consistent with slider

mac/Keyman4MacIM/Keyman4MacIM/Privacy/PrivacyConsent.m
Fixes #7476 
When typing the right option key (Mac equivalent for the Alt key) ensure that it produces the correct character for the active Keyman keyboard.
* **TEST_RIGHT_ALT:** - Verify that the right option key with Keyman for Mac produces the correct character
1. Remove old version of Keyman **after** first removing its permissions from Security & Privacy > Privacy > Accessibility
2. Install the Keyman build for this PR
3. Restart the system
4. Select Keyman from the system input source menu
5. Enable privacy settings as prompted
6. Restart the system (again)
7. Install the Khmer Angkor keyboard 
8. Switch to a text editor like TextEdit or Pages
9. With Keyman running, hold down the right option key and type the K key
10. Verify that the character ឝ is emitted
* …
=> fix(mac): Enable right-alt/option key mapping

linux/ibus-keyman/src/engine.c
This reverts commit acab920de86a3fec1771bfd030bc13536c300000 (#7746).
I'm confused - now we're getting the same warning again - claiming that `size_t` is defined as `long unsigned int` and so we have to use `%lu`!? Is this related to the platform we're compiling on? This time, the warning we get is when compiling for x86_64:
```
engine.c: In function ‘get_current_context_text’:
engine.c:224:15: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 5 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
224 |     g_message("%s: current context is:%u:%lu:%s:", __FUNCTION__, km_kbp_context_length(context), buf_size, current_context_utf8);
|               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| …
```
=> fix(linux): Revert "fix(linux): Fix a warning"

android/help/about/whatsnew.md, ios/help/about/whatsnew.md, linux/help/about/whatsnew.md, mac/help/about/whatsnew.md, windows/src/desktop/help/about/whatsnew.md
Follow-on to #7558 
This adds some more detail to the whatsnew pages. (And removes 15.0 content for some products)
=> chore(common): Update whatsnew for 16.0

android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtil.java
Well, I was troubleshooting why I was having difficulties getting keyboard update notifications for #7781 and I traced it down to me missing a `!` in a botched merge-conflict from e21b50a2d5a8ee6309ce3a829c1a3c5c8d18d863
Comparison from what's on master
https://github.com/keymanapp/keyman/blob/086557e089ec07bcd07062fdf75e109573dbb93e/android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudDataJsonUtil.java#L155-L159
=> fix(android/engine): Fix logic error for updateKMP

linux/ibus-keyman/configure.ac, linux/ibus-keyman/src/engine.c
This change makes it possible to compile even when the updated ibus version is not installed. Of course ordered output won't work in that case, but at least it will compile and the rest of Keyman will work.
Fixes #7774.
=> fix(linux): Allow to build without patched ibus version

ios/help/start/installing-system-keyboard.md
Fixes #7763
Update [help page](https://help.keyman.com/products/iphone-and-ipad/current-version/start/installing-system-keyboard) text due to iOS 16 issue. Advise users to keep Allow Full Access enabled for normal Keyman operation.
=> docs(ios): Update help documentation about Install and Allow Full Access

linux/ibus-keyman/src/engine.c
🍒-picked from #7686. Necessary for my next PR to make merging of beta into master easier because that PR will refactor and use some of the code that this PR modifies.
=> refactor(linux): Use consts instead of strings ⚙️ 🍒

resources/build/run-required-test-builds.sh, resources/build/trigger-builds.inc.sh
While release builds need to build a specific commit hash, test builds should always build the HEAD of the branch. This stops multiple merges and/or pushes generating multiple test builds in the queue.
=> fix: test builds should always run latest changes

android/help/about/whatsnew.md
While updating a 16.0 retrospective for upcoming planning meetings, I noticed we actually do have release note for a 16.0 Keyman for Android feature.
=> docs(android/app): Add note of haptic feedback to whatsnew

developer/src/tike/main/mrulist.pas
Fixes #7808.
If a project is moved, then the MRU, which has absolute path names, will probably have references to files that don't exist. Rather than leave these in the list, to be opened and potentially recreated in the wrong place, we should just remove them entirely from the list.
=> fix(developer): remove missing files from MRU list

mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMBinaryFileFormat.h, mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m
Fixes #7632.
If Caps Lock was on, rules that did not specify Caps Lock state were not matched, for example:
```
+ [K_SLASH] > 'foo'
```
The truth table for matches is:
Event    |    Rule     | Result
---------|-------------|-----------
`NCAPS`  |    `0`      | match
`NCAPS`  |    `CAPS`   | no match
`NCAPS`  |    `NCAPS`  | match
`CAPS`   |    `0`      | match
`CAPS`   |    `CAPS`   | match
`CAPS`   |    `NCAPS`  | no match
(Internally, Keyman for Mac currently maps `0` to `NCAPS` on the event for simplicity.)
The fix is to ignore the Event Caps Lock state if the rule specifies neither `CAPS` nor `NCAPS`. If the rule specifies either of these state masks, then the Caps component of the state mask must match.
The tests for this use this keyboard: …
=> fix(mac): Caps processing was not consistent with core

windows/src/desktop/kmshell/main/UfrmWebContainer.pas
Cherry-pick of #7661. Fixes #7824.
Hopefully fixes KEYMAN-WINDOWS-1MR, and probably many related crash reports.
This changes the form destruction sequence to make sure that it doesn't close the form until CEF has been shutdown correctly.
Will monitor this on beta before release and roll it back if other issues arise.
Please do a regression test on Keyman Configuration (just the user interface portions).
- **TEST_KEYBOARD_INSTALLATION_REMOTE**:
- Start Keyman Configuration
- Click Download Keyboard, select a keyboard from the download dialog and install it
- If the package includes a readme file, verify that it appears in the install window.
- If the package includes a welcome file, verify that it appears after installation.
- Click OK to close Keyman Configuration
- Start Notepad
- Verify …
=> fix(windows): Cleanup CEF more correctly in shutdown 🍒

linux/ibus-keyman/src/engine.c, linux/ibus-keyman/tests/run-tests.sh
- set keyboard options in a call to `km_kbp_state_options_update` separate from setting the environment options
- output status value if method fails
- if any of the methods fails we now return NULL
- split setting the options in multiple methods
Fixes #7717.
=> refactor(linux): Refactor setting keyboard options ⚙️

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMAPro/kMAPro/src/main/res/menu-land/main.xml, android/KMAPro/kMAPro/src/main/res/menu-sw600dp/main.xml
Fixes #6731
Previously, the Keyman notification of keyboard updates could appear on 3 form factors:
* phone (portrait orientation) - notification on overflow menu
* phone (landscape orientation) - notification on menu
* tablet (> 600dp, either orientation) - notification on menu
The landscape and tablet layouts had a complexity of a dynamic layout "update_count_view" which turned out to be un-clickable.
This PR removes the usage of "update_count_view", and toggles the update icon when updates are available. (This removes the feature of a dynamic count of updates available). The minor loss in feature should be acceptable since long-term we plan to just automatically download keyboard/dictionary updates as they're available (#7171).
Setup - For each group, use the Android device and …
=> fix(android/app): Toggle keyboard update notifications for landscape and tablets

android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java
Fixes #7843 
Starting with Android S+ (API 31), we need to use `FLAG_IMMUTABLE` for the PendingIntent used to download package updates.
From the Sentry crash report
```
IllegalArgumentException: com.tavultesoft.kmapro.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
at android.app.PendingIntent.getActivitiesAsUser(PendingIntent.java:593)
at android.app.PendingIntent.getActivities(PendingIntent.java:575)
at …
```
=> fix(android/engine): Use FLAG_IMMUTABLE for PendingIntent for Android S+

developer/src/tike/update/Keyman.Developer.UI.TikeOnlineUpdateCheck.pas
Fixes #7829.
Fixes [KEYMAN-DEVELOPER-9J](https://sentry.io/organizations/keyman/issues/3251936542/?project=5983519&referrer=regression_activity-email).
The online update check could crash on shutdown because the thread destructor would run from the wrong thread. This caused the main form destruction, which happens if the user chooses to install the update, to be triggered from the worker thread, leading to much pain.
=> fix(developer): OnlineUpdate crash on shutdown

common/windows/delphi/general/utilhttp.pas, common/windows/delphi/web/Keyman.System.HttpServer.Base.pas, developer/src/tike/http/Keyman.Developer.System.HttpServer.App.pas, developer/src/tike/http/Keyman.Developer.System.HttpServer.AppSource.pas
Fixes #7810.
This addresses a regression introduced in #7631, where URL parameters with spaces would be encoded into `+` instead of `%20`. Looking a bit deeper at the Delphi `TNetEncoding.URL.Encode` function I realised that it was entirely inadequate. Some guy named Marc Durdin wrote a [blog](https://marc.durdin.net/2015/08/an-update-for-encodeuricomponent/) a good few years ago about the problem, and that's what I ended up using to fix this.
This encoding issue caused filenames with spaces (by default, project paths in Developer have spaces) to give a 404 when editing a touch layout, which meant that the touch keyboards could not be saved.
Also fixes [KEYMAN-DEVELOPER-74](https://sentry.io/organizations/keyman/issues/3081965404/?project=5983519), where the `+` encoding caused multiple …
=> fix(developer): EncodeURL was not handling spaces

docs/CODEOWNERS
This changes the platform advocates for web and android as discussed at the planning meeting.
=> chore: Change platform advocates

linux/ibus-keyman/src/test/run-tests.sh
During package builds on Debian servers the build often failed with an error related to X11 when running the tests. This change skips the tests in `linux/ibus-keyman/src/test` when building packages, similar to the way we already do it for the tests in `linux/ibus-keyman/tests`.
=> chore(linux): Improve package build

developer/src/kmc-model/package.json
The node_modules path is relative to the build output, not package.json. This was causing the web tests to fail due to dependence on the lexical-model-compiler.cjs.
=> fix(developer): kmc-model esbuild node_modules path 🙀

windows/src/desktop/kmshell/xml/config.css, windows/src/desktop/kmshell/xml/config.js, windows/src/desktop/kmshell/xml/elements.xsl, windows/src/desktop/kmshell/xml/keyman_keyboardlist.xsl
The Keyboard layouts tab: When a keyboard is disabled just the details text on the right is now 'greyed' out. The buttons on the left are no longer greyed out except for 'Add/remove' which is now disabled.  The disabled background and foreground text colours are from the Keyman design approach manual. See the screenshot for how it looks now.
* **TEST_ADD_REMOVE_DISABLED**
Pre-requests at least one keyboard layout needs to be installed
1. Open the Keyman Configuration 
2. Select the Keyboard Layouts tab
3. Select a Keyboard Layout
4. Click the `Disable` Button
5. Observe that: 
- The details on the left are `greyed out`
- The buttons are not `greyed out` except for `Add\remove languages...`
- Clicking on `Add\remove languages...` does NOT pop up the add\remove languages.. dialog.
- The …
=> fix(windows): modify disable keyboard display

common/windows/delphi/charmap/UfrmCharacterMapNew.pas
Fixes #7879.
If we enter a search string that results in zero results, the grid resize to one row attempts to select row zero. However, we prevent this. This leaves the current row outside the range of valid rows, which means the grid is in an invalid state.
This later causes a crash if the user attempts to mousewheel up. There may be other similar crashes in this situation, but I haven't found any yet.
Fix is to allow selection of row zero when there is only one row. I have not found any problems caused by allowing this.
=> fix(developer): invalid charmap cell selection when updating to empty search result

android/KMAPro/build.gradle, android/KMAPro/gradle/wrapper/gradle-wrapper.properties, android/KMAPro/kMAPro/build.gradle, android/KMEA/app/build.gradle, android/KMEA/app/src/main/AndroidManifest.xml, android/KMEA/app/src/test/java/com/tavultesoft/kmea/util/FileUtilsTest.java, android/KMEA/build.gradle, android/KMEA/gradle/wrapper/gradle-wrapper.properties, android/README.md, android/Samples/KMSample1/app/build.gradle, android/Samples/KMSample1/build.gradle, android/Samples/KMSample1/gradle/wrapper/gradle-wrapper.properties, android/Samples/KMSample2/app/build.gradle, android/Samples/KMSample2/build.gradle, android/Samples/KMSample2/gradle/wrapper/gradle-wrapper.properties, android/Tests/KeyboardHarness/app/build.gradle, android/Tests/KeyboardHarness/build.gradle, android/Tests/KeyboardHarness/gradle/wrapper/gradle-wrapper.properties, android/Tests/keycode/.idea/.gitignore, android/Tests/keycode/app/build.gradle, android/Tests/keycode/app/src/main/AndroidManifest.xml, android/Tests/keycode/build.gradle, android/Tests/keycode/gradle/wrapper/gradle-wrapper.properties, oem/firstvoices/android/app/build.gradle, oem/firstvoices/android/build.gradle, oem/firstvoices/android/gradle/wrapper/gradle-wrapper.properties
This PR is updating our Android Gradle dependencies for the start of 17.0 development.
Since we're remaining on Java 8, this limits what version of Android Gradle Plugin (AGP) we can upgrade to, which then limits some of the other dependencies.
The targetSDKVersion is also bumped to 33, which necessitates adding the `POST_NOTIFICATIONS` permission to the Android Manifest.
Updating junit impacted `FileUtilsTest.java`, where the expected log now contains 3 items instead of 4.
We'll also need to see if the nightly build successfully publishes (after PR merge) to verify the triplet.play plugin.
Some follow-on work could be done in #7896 to remove Sentry dependencies in the Sample/test apps.
**Setup** - Install the PR build on an Android emulator/device (minimum SDK version of 21)
* …
=> chore(android): Update Gradle dependencies; targetSDKVersion to 33

linux/debian/libkmnkbp0-0.symbols
When we added the API check we introduced a mis-spelled dependency which lead to Keyman being uninstallable. This change fixes things.
**TEST_INSTALLATION**: 
- It doesn't matter on which Linux platform these tests are run.
- Verify that there are no errors shown in the terminal window
=> fix(linux): Fix dependency of ibus-keyman 🚑

linux/debian/libkmnkbp0-0.symbols
When we added the API check we introduced a mis-spelled dependency which lead to Keyman being uninstallable. This change fixes things.
(🍒-picked from PR #7917)
=> fix(linux): Fix dependency of ibus-keyman 🚑 🍒

oem/firstvoices/android/app/src/main/res/values/strings.xml
Fixes #7905 
This removes the extraneous "$1%s" string on the version title of Keyboard List menu.
**Setup** - Install the PR build of FV for Android on an Android device/emulator of SDK 33.
* **TEST_KEYBOARD_INFO** - Verifies version string is fixed
1. Launch FV for Android
2. On the start page, click "Select keyboards" --> Select a region --> Select a keyboard --> Enable the keyboard
3. Return to the start page, click "Setup" --> Enable FirstVoices and choose FirstVoices as the current input method
4.  Launch a separate app (e.g. Chrome) and click on a text field
5. With the FV keyboard as a system keyboard, long-press the globe key to display the keyboard picker menu
6. On the keyboard picker menu, click the "i" icon to display the keyboard info
7. Verify the keyboard info menu is …
=> fix(oem/fv/android): Cleanup version title

windows/src/desktop/kmshell/xml/keyman_keyboardlist.xsl
The purpose of the red colouring of the Languages: label was to warn the user when no languages were installed for the current keyboard layout. It was suffering from dirty cache, this actually made it more  confusing the helpful. 
The red colouring of the "Languages:" label was driven by an xml element which was taken from a registry value whose cache is not refreshed without restarting the app. The new xml element is driven by a registry language value that is refreshed straight away. 
* **TEST_LANG_RED_PT1**
1. Open Keyman Configuration and install `Tamil 99 Basic`
2. Click on the `Add/remove languages...` button
3. In the `Add/remove language` dialog pop up click the `x` to the right of the only language installed [ta-IN]. If there are other languages remove them also. This takes a …
=> fix(windows): no languages warning source changed

windows/src/desktop/kmshell/main/UfrmWebContainer.pas
Regression introduced in #7661 (17.0 alpha), #7825 (16.0 beta).
When shutting down CEF cleanly, we needed to pause the form destruction sequence in order for CEF to complete its shutdown tasks. However, for a dialog form, it will commonly be closed by setting `ModalResult` to a non-zero value. In our fix, we inadvertently lost any `ModalResult` value by calling `Close` after CEF was finished, which sets `ModalResult` to `mrCancel` (value of 2).
This fix caches the `ModalResult` value, and if non-zero, uses it instead after CEF shuts down, to achieve the same result.
Applying this fix to beta channel first, will cherry-pick to master.
**TEST_START_KEYMAN:** Do a clean install of Keyman for Windows, and verify that the Start Keyman button in the Splash screen actually starts Keyman. …
=> fix(windows): shutdown fix masked modal result 🔥

windows/src/desktop/kmshell/main/UfrmWebContainer.pas
Cherry-pick of #7932.
Regression introduced in #7661 (17.0 alpha), #7825 (16.0 beta).
When shutting down CEF cleanly, we needed to pause the form destruction sequence in order for CEF to complete its shutdown tasks. However, for a dialog form, it will commonly be closed by setting `ModalResult` to a non-zero value. In our fix, we inadvertently lost any `ModalResult` value by calling `Close` after CEF was finished, which sets `ModalResult` to `mrCancel` (value of 2).
This fix caches the `ModalResult` value, and if non-zero, uses it instead after CEF shuts down, to achieve the same result.
**TEST_START_KEYMAN:** Do a clean install of Keyman for Windows, and verify that the Start Keyman button in the Splash screen actually starts Keyman.
**TEST_STOP_KEYMAN:** Select Exit Keyman from the …
=> fix(windows): shutdown fix masked modal result 🔥 🍒

oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVKeyboardSettingsActivity.java, oem/firstvoices/android/app/src/main/res/values/strings.xml
Fixes #7939 and follow-on to #7908
It turned out the we need two keyboard version strings
* one with a version number (on the keyboard enable page)
* one without a version number (on the keyboard info page - "i" from the keyboard picker menu)
**Setup** - Install the PR build of "FV for Android" on an Android device/emulator
* **TEST_VERSION_STRINGS** - Verifies version strings are correct
1. Launch FV for Android
2. On the setup page, click "Select keyboards" --> BC Coast --> Diidiitidq
3. On the "Diidiitidq Settings" page, verify the version subtitle appears with a valid keyboard version
4. Enable the keyboard and return to the setup page
5. On the setup page, click "Setup" --> Enable FirstVoices and choose FirstVoices as the current input method
6. On the device, launch a separate app …
=> fix(oem/fv/android): Fix keyboard version title (again)

oem/firstvoices/android/app/src/main/AndroidManifest.xml, oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVShared.java
Fixes #7907 and follow-on to #7897
On higher SDK versions of Android, the Manifest needs a query permission for the intent to launch.
[Reference](https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30)
**Setup** - Install the PR build of FV for Android on an Android device/emulator of SDK version 33
* **TEST_HELP_LAUNCHES** - Verifies online help launches in a separate browser
1. Launch FV for Android
2. On the start page, click "Select keyboards" --> Select a region
3. On the keyboards list of the Region page, click on a question mark to display the online help
4. Verify a separate browser launches the keyboard  help page from help.keyman.com
=> fix(oem/fv/android): Add view permission of online help

windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp
Fixes #7716 
PR #7449 added a `modifier event` to make ensure modifier events
were sent to the serializer even if the keystroke was determined
not to need serializing. However, a logic error was made
trying to use the existing 'Flag' however this was not set in the
!UseCachedHotkeyModifierState case. This change adds a helper function
to simply check if the key is a modifier key and send it to the
event serializer in that case. Separating from the other logic which
is more concerned with handling hotkeys.
PR #7779  was used in this investigation. The extra logging enabled the observation that modifier event was not being sent when not using cached hotkeys.  It also showed that for some users when cycling through the open applications using `ALT` + `Tab`  the initial pressing of  `ALT` is …
=> fix(windows): modifer event is always serialized

developer/src/kmlmc/source/lexical-model-compiler/lexical-model-compiler.ts, developer/src/kmlmc/source/util/util.ts
Fixes #7926.
Android 5.0 (Chrome 37) only supports ES3. Thus, we should transpile our lexical models to ES3 rather than ES2015, for now at least.
For example, this forces constructs such as `const` to be replaced with `var`.
(I have verified that the code generation is correct; this will require version bumps on all affected LMs in order to deploy an updated version with the new version of the compiler once it lands.)
=> fix(developer): force ES3 code generation for LMs

linux/scripts/jenkins.sh, linux/scripts/reconf.sh
This change removes the unused JENKINS environment variable from `reconf.sh`. The code got refactored some time ago to use the common scripts to retrieve the version. That made the JENKINS variable obsolete.
=> chore(linux): Remove unused JENKINS parameter

linux/ibus-keyman/tests/ibusimcontext.c
see #7774 
apply the same change to engine.c as to linux/ibus-keyman/tests/ibusimcontext.c so that we can build without IBUS_HAS_PREFILTER
=> fix(linux): add IBUS_HAS_PREFILTER ifdef to linux/ibus-keyman/tests

docs/build/linux-ubuntu.md
Follow-on to #7102 
Document how to do a full linux build in docker.
Note: instructions will fail until #7958 is merged due to ibus dep
=> docs(linux): document fullbuild using docker

common/web/types/test/fixtures/invalid-conforms-to.xml, core/src/kmx/kmx_plus.cpp, core/tests/unit/kmnkbd/test_kmx_xstring.cpp, core/tests/unit/ldml/keyboards/k_001_tiny.xml, core/tests/unit/ldml/keyboards/k_002_tinyu32.xml, developer/src/kmc-keyboard/test/fixtures/basic.txt, developer/src/kmc-keyboard/test/fixtures/basic.xml
- maqtua should be maqtugħa (cut) but spelled as maqtugha where used as an NMTOKEN
-----
Minor, just an embarrassing typo…
=> fix(core): ldml: fix spelling of maqtugħa 🙀

windows/src/desktop/kmshell/install/UfrmInstallKeyboardLanguage.pas
Fixes #7670 
the `-ikl` sets up the language registration for the keyboard for the user whos shell runs the command. 
This calls a `InstallKeyboardLanguage` when following the command chain all the way through will update the windows registry
in Line 560 of `Keyman.System.Process.KPInstallKeyboardLanguage` builds a registry key for the `KeyboardID` String Name under `Active Keyboards` and adds the BCP47Tag under the `Languages` path. It does not enable the keyboard. 
As reported in #7670, no KeymanID is written directly under `Active Keyboards` nor the corresponding `Active Keyboards\KeyboardId\keymanid` with the integer value. 
`InstallKeyboardLanguage` will now enable the just-installed active keyboard.  - I am not 100% sold on this solution either it works but it would probably be …
=> fix(windows): kmshell -ikl install language and enable keyboard

linux/keyman-config/keyman_config/handle_install.py
We can directly use `logging.error` instead of `logging.log`. Then we don't need the `severity` variable.
=> chore(linux): Remove unnecessary variable

linux/keyman-config/keyman_config/downloadkeyboard.py
Fixes #4828
Before:
After:
- start km-config
- click Downloads button
**TEST_CLOSE_BTN**: Close button closes dialog
- click Close button
- verify that the "Download Keyman keyboards" dialog gets closed
**TEST_BACK_INITIAL_DISABLED**: Back button is disabled on the initial search page
- with the "Keyboard search" page showing (directly after opening the dialog), verify that the "Back" button is disabled
**TEST_BACK_ENABLED**: Back button works on keyboard page
- search for a language and click on a keyboard
- on the page that shows the keyboard details, verify that the "Back" button is enabled
- click the Back button and verify that it takes you back to the search page
=> feat(linux): Add Back button to "Download Keyman Keyboards" dialog

linux/keyman-config/keyman_config/kmpmetadata.py, linux/keyman-config/keyman_config/view_installed.py
Fixes #3501
Before:
After:
**TEST_UNINSTALL_FONTS_SHOWN**: fonts are shown in uninstall confirmation dialog
- select installed "khmer angkor" keyboard
- click uninstall button
- verify that the fonts are shown in the uninstall confirmation dialog
**TEST_UNINSTALL_NO_FONTS**: uninstall works if no fonts are included in keyboard
- select installed "US Basic" keyboard
- click uninstall button
- verify that uninstall works
=> feat(linux): List fonts in the uninstall confirmation dialog

linux/keyman-config/keyman_config/downloadkeyboard.py, linux/keyman-config/keyman_config/uninstall_kmp.py, linux/keyman-config/keyman_config/view_installed.py
Adds message dialogs in the UI for errors when downloading a keyboard and uninstalling a keyboard
Fixes #6288
- start km-config
**TEST_DOWNLOAD_ERROR**: shows message dialog when download fails
- click "Downloads" button
- search for a language and click on a keyboard
- turn off the internet connection
- click "Install keyboard" button
- verify a message dialog is shown
**TEST_UNINSTALL_ERROR**: shows message dialog when uninstalling fails
- select installed "khmer angkor" keyboard
- click uninstall button
- delete the folder `~/.local/share/keyman/khmer_angkor`
- click "Yes" on the verification dialog
- verify a message dialog is shown
=> feat(linux): Display error messages in the UI

linux/keyman-config/keyman_config/install_kmp.py
Fixes #8004
- start km-config
- don't have "khmer_angkor" keyboard installed
**TEST_FAILED_INSTALLATION**: verify there is no bugged 'empty' keyboard after failed installation
- click "Downloads" button
- search for "khmer" and click on the "khmer_angkor" keyboard
- click "Install keyboard" button
- delete ~/.cache/keyman/khmer_angkor
- click "Install" button
- click "OK" on the message dialog
- verify that "Keyman Configuration" is shown and there is no bugged 'empty' keyboard in the list
=> bug(linux): Empty keyboard after failed installation

linux/debian/control
The reason for the crash is the missing file `dbus-launch` which gets called when running with `sudo`. This change adds a dependency to `dbus-x11` which provides `dbus-launch`.
Fixes #8012.
(🍒-picked from #8019)
=> fix(linux): Fix crash (un-)installing shared keyboard 🍒

linux/keyman-config/keyman_config/__init__.py
When the user presses Ctrl-C we don't want to create a Sentry issue. This change ignores that exception.
=> chore(linux): Don't report KeyboardInterrupt to Sentry

linux/keyman-config/keyman_config/__init__.py
When the user presses Ctrl-C we don't want to create a Sentry issue. This change ignores that exception.
(Should have cherry-picked from `beta` to `master`, but thought too late that it would be good to have this change in 16.0)
(🍒-picked from #8021)
=> chore(linux): Don't report KeyboardInterrupt to Sentry 🍒

linux/debian/control
The reason for the crash is the missing file `dbus-launch` which gets called when running with `sudo`. This change adds a dependency to `dbus-x11` which provides `dbus-launch`.
Fixes #8012.
=> fix(linux): Fix crash (un-)installing shared keyboard

linux/keyman-config/km-package-install, linux/keyman-config/km-package-install.bash-completion, linux/keyman-config/km-package-list-installed.bash-completion, linux/keyman-config/tests/test_package_install_completion.py
This change adds tab completion for the bcp-47 parameter in km-package-install.
Fixes #5361
**TEST_NO_COMP**: shows no completions without specifying package or keyboard first
- open terminal window
- type `km-package-install -l ` (ending with a space)
- press tab-key. If nothing happens after a few seconds, press the tab-key again.
- verify that no completions are shown
**TEST_PKG_NOT_EXISTING**: shows completions if file doesn't exist previously
- delete `~/.cache/keyman/khmer_angkor` and `khmer_angkor.kmp` if they exist
- open terminal window
- type `km-package-install -p khmer_angkor -l ` (ending with a space)
- press tab-key. If nothing happens after a few seconds, press the tab-key again.
- verify that `km` is shown
**TEST_PKG_EXISTING**: shows completions if file does exist …
=> feat(linux): Enhance tab completion in km-package-install

linux/keyman-config/keyman_config/keyboard_details.py
This change fixes the vertical alignment of the "Package description" label in the keyboard details dialog so that it shows at the top instead of vertically centered. Also simplification of some other code.
=> chore(linux): Fix vertical alignment of label

linux/ibus-keyman/src/engine.c
This change fixes a bug where we the context was wrong after putting the IP in a new location by mouse-click.
Fixes #8024.
- Reboot
- Install **IPA (SIL)** keyboard
**TEST_SETS_CONTEXT**: Correctly gets surrounding text of current cursor location
- open gedit
- switch to IPA (SIL) keyboard
- Type
```
an
m
```
- click after `n`
- type `>`
- verify that the output is
```
aŋ
m
```
=> fix(linux): Properly set context after changing IP

linux/ibus-keyman/src/engine.c
This change fixes a bug where we the context was wrong after putting the IP in a new location by mouse-click.
Fixes #8024.
(🍒-picked from PR #8025)
=> fix(linux): Properly set context after changing IP 🍒

linux/ibus-keyman/src/engine.c
This changes a zero-length string check to a more efficient way of checking.
Fixes #7541
=> chore(linux): use faster zero-length string check

linux/ibus-keyman/src/engine.c
This change adds behavior when setting the context fails. It then clears the context and logs the failure. 
Fixes #7540
=> chore(linux): log failures to `km_kbp_context_clear(context)`

docs/settings/linux/extensions.json
The previously recommended extension is no longer available.
=> chore(linux): Update recommended extension

ios/engine/KMEI/KeymanEngine/Classes/PackageWebViewController.swift, ios/engine/KMEI/KeymanEngine/Classes/Resource Management/KeyboardSearchViewController.swift
Fixes #7915.
On iPadOS 16, it seems that WKWebView defaults to lying about its user agent to servers. We can switch this behaviour by using .mobile for the preferredContentMode.
We should also update the website to work around this, so that users always get the right downloads for their device, but the website currently uses server-side determination of user agent for this particular aspect of the keyboard search, so that's a much more significant refactor, to make it client-side, with greater risk and much more testing required.
This PR is a candidate for back-porting to 16.0-beta/stable.
TEST_INSTALL_MESOBE: Try installing the Amharic Mesobe Fidelat keyboard on an iPad (or simulator) running iOS 16.0 or later. The keyboard should be installable.
=> fix(ios): use mobile mode for keyboard download pages

linux/keyman-config/keyman_config/get_kmp.py, linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/km-package-install, linux/keyman-config/tests/test_install_kmp.py
This change fixes a bug where a JSON file containing the package description was missing after initial installation.
For that it disposes of the `online` argument in `install_kmp`. 
Fixes #8017
- delete all files in `~/.cache/keyman/` (especially `keyman_cache.sqlite`)
- download "EuroLatin" (SIL) package into `~/.cache/keyman/` (https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
- don't have "khmer_angkor" or "sil_euro_latin" keyboard installed
**TEST_DOWNLOAD**: JSON file gets downloaded and package description is shown
- start `km-config`
- click "Download" button
- search for "khmer" and click on the "khmer_angkor" keyboard
- click "Install keyboard" button
- click "Install" button
- click "OK" on the message dialog
- select "Khmer Angkor" keyboard and …
=> fix(linux): JSON File missing after installation

.gitignore, common/web/types/package.json, developer/src/kmc-keyboard/package.json, developer/src/kmc-model-info/package.json, developer/src/kmc-model/package.json, developer/src/kmc-package/package.json, developer/src/kmc/package.json
- generate coverage/lcov.info files in several places that were already using c8
- change kmc-package's 'npm test' to include coverage, leave 'coverage' as alias
- gitignore the lcov files
Fixes https://github.com/keymanapp/keyman/issues/8060
[coverage-gutters](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) and others work well with this change.
=> chore(developer): ldml setup for visual code coverage 🙀

android/KMAPro/kMAPro/src/main/res/values-kn-rIN/strings.xml, android/KMEA/app/src/main/java/com/tavultesoft/kmea/DisplayLanguages.java, android/KMEA/app/src/main/res/values-kn-rIN/strings.xml, ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj, ios/engine/KMEI/KeymanEngine/Classes/kn.lproj/ResourceInfoView.strings, ios/engine/KMEI/KeymanEngine/kn.lproj/Localizable.strings, ios/engine/KMEI/KeymanEngine/kn.lproj/Localizable.stringsdict, ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj, ios/keyman/Keyman/Keyman/kn.lproj/Localizable.strings, linux/keyman-config/locale/kn_IN.po, mac/Keyman4MacIM/Keyman4MacIM.xcodeproj/project.pbxproj, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/kn.lproj/KMAboutWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/kn.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/kn.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/kn.lproj/KMKeyboardHelpWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/kn.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/kn.lproj/MainMenu.strings, windows/src/desktop/kmshell/locale/kn-IN/strings.xml, windows/src/desktop/setup/locale/kn-IN/strings.xml
Fixes #7952 
This adds the crowdin strings for Kannada - locale kn-IN
TODO for @sgschantz 
Load the PR build for each platform and set the UI / Locale to "ಕನ್ನಡ" (and/or Kannada)
* **TEST_ANDROID** 
2. In the Keyman app, go to Settings --> Display Language --> ಕನ್ನಡ (Kannada)
3. Return to the Keyman app 
4. Verify the UI is in Kannada (prompt, Settings strings, etc.). Note, the globe tip string stays in English and is a separate issue #7975
* **TEST_IOS**
1. Load the PR build of Keyman for iPhone and iPad
2. Set the device locale to Kannada
3. Return to the Keyman app
4. Verify the UI is in  Kannada
1. Start Keyman configuration with: LANGUAGE=kn_IN km-config
2. Verify Keyman UI is in Kannada
* **TEST_MACOS** …
=> chore(common): Add crowdin strings for Kannada

linux/keyman-config/keyman_config/uninstall_kmp.py, linux/keyman-config/tests/test_uninstall_kmp.py
Even if the directory doesn't exist, we can still remove the keyboard from the keyboard list.
- start km-config
- install "Khmer Angkor" keyboard
- verify that it shows up in the language/keyboard dropdown in the taskbar
**TEST_UNINSTALL**: Uninstallation with unavailable keyboard directory still removes keyboard from language dropdown
- start km-config
- in a terminal window, run the command `rm -rf ~/.local/share/keyman/khmer_angkor` (don't close km-config!)
- in km-config, select installed "khmer angkor" keyboard
- click uninstall button
- click "Yes" on the verification dialog
- verify a message dialog is shown that the keyboard directory doesn't exist
- verify that the Khmer Angkor keyboard no longer shows up in the language/keyboard dropdown in the taskbar
=> feat(linux): Improve uninstallation

common/web/types/src/consts/virtual-key-constants.ts, core/tests/unit/ldml/keyboards/k_003_transform.xml, core/tests/unit/ldml/keyboards/k_010_mt.xml, core/tests/unit/ldml/keyboards/meson.build, developer/src/kmc-keyboard/test/fixtures/sections/keys/invalid-hardware-too-many-rows.xml
comon/web/types:
- the USVirtualKeyMap was actually somewhat ISO-ish. Correct it.
- also, add the spacebar row.
- create a new ISOVirtualKeyMap, but not linked in anywhere.
core/tests:
- add a new test keyboard, k_010_mt.xml which is Maltese 47-key
- update k_003 which was impacted by this
For: #7965
=> fix(common): update USVirtualKeyMap to actually be US🙀

common/web/types/build.sh, common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts, common/web/types/test/ldml-keyboard/test-ldml-keyboard-xml-reader.ts, common/web/types/tsconfig.json, core/include/ldml/keyboardprocessor_ldml.h, core/include/ldml/keyboardprocessor_ldml.ts, core/include/ldml/ldml-const-builder.ts, core/tools/ldml-const-builder/build.sh, developer/src/kmc-keyboard/src/compiler/compiler.ts, developer/src/kmc-keyboard/test/helpers/index.ts, developer/src/kmc/build.sh, package-lock.json, package.json
supports #7964
- change importer to use callbacks for fs
- see #7402 for the grandparent PR - feature complete, but needs refactor
=> feat(common): ldml: refactor imports 🙀

linux/scripts/jenkins.sh, linux/scripts/package-build.inc.sh
This fixes the build on Jenkins and TC that got broken by including the wildcard in the quoted string (which causes it to be interpreted literally), introduced in #8102.
=> fix(linux): Fix CI build 🩹

android/KMAPro/kMAPro/src/main/res/values-b+shu+latn/strings.xml, android/KMEA/app/src/main/res/values-b+shu+latn/strings.xml, ios/engine/KMEI/KeymanEngine/shu-latn-n.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/shu-latn-n.lproj/KMAboutWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/shu-latn-n.lproj/preferences.strings, mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/shu-latn-n.lproj/KMInfoWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/shu-latn-n.lproj/KMKeyboardHelpWindowController.strings, mac/Keyman4MacIM/Keyman4MacIM/shu-latn-n.lproj/Localizable.strings, mac/Keyman4MacIM/Keyman4MacIM/shu-latn-n.lproj/MainMenu.strings, windows/src/desktop/kmshell/locale/shu-latn/strings.xml, windows/src/desktop/setup/locale/shu-latn/strings.xml
This updates some crowdin strings for Shuwa (Latin) - locale shu-Latn.
Strings are all new for macOS.
This adds the crowdin strings for Shuwa (Latin)
TODO for @sgschantz (unsupported on macOS)
~- [ ] Run XCode for macOS~
=> chore(common): Update crowdin strings for Shuwa (Latin)

windows/src/engine/tsysinfo/si_language.pas
Adds the following registry keys to the report:
* `HKCU\Software\Microsoft\CTF`
* `HKCU\Control Panel\International\User Profile`
=> feat(windows): add additional registry keys to report

developer/src/tike/main/RedistFiles.pas
Adds the src build path in for kmcmpdll.dll for debugging purposes, when running from any subdirectory of the KEYMAN_ROOT path.
=> chore(developer): kmcmpdll debug src path

web/build.sh, web/ci.sh
This PR seeks to partially implement two Web release steps within in-repo shell scripting - in particular, the file-shuffling / archiving commands that prepare the artifacts we publish.  This is a fit for the 📜 PR chain because of all the pieces that are moved around; those configurations actively need an update to finalize all the changes... and #7474 provides a wonderful signal-file that may be conditioned upon so that the old and new build patterns may be handled by the actual configuration.
This should be the final piece needed to complete the 📜 PR set; kinda need to keep the build chain and the release artifact uploads properly connected before merging to `master`, which was the last remaining part left unhandled 'til now.
So, the two new action-target pairs defined within …
=> feat(web): implements shell scripting for CI release-build configurations 📜

common/windows/delphi/packages/PackageInfo.pas, developer/src/common/delphi/compiler/CompilePackage.pas, developer/src/tike/child/UfrmPackageEditor.pas
Fixes #8119.
**GROUP_KEYBOARD:** Test with a keyboard package
**GROUP_LEXICAL_MODEL:** Test with a lexical model package
**TEST_PACKAGE_EDITOR_ADD:** In the keyboard/lm tab of the package editor, attempt to add two languages with the same BCP 47 tag. It should not add the second one.
**TEST_PACKAGE_EDITOR_EDIT:** In the keyboard/lm tab of the package editor, add a few different languages. Then, edit one of the languages to the same text as another one in the list. The language you edited should disappear from the list, and the selection should move to the duplicate.
**TEST_PACKAGE_COMPILE:** Go to the source tab of the package editor, and duplicate a `<Language>` tag in the `<Languages>` list for the keyboard or LM section of the file. Attempt to compile the package -- it should warn you …
=> feat(developer): check for duplicated language codes in package editor and compiler

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
More KMManager refactoring for #7881 
This cleans up  KMManager.showKeyboardPicker()
From the Intent documentation, I also saw that [FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET) is deprecated in API 21 and replaced by FLAG_ACTIVITY_NEW_DOCUMENT.
Setup - Install the PR build of Keyman for Android
* **TEST_INAPP** - Verifies keyboard picker works for inapp keyboard
3. In the Keyman app, long-press on the globe button
4. Verify Keyboard Picker menu appears
5. Verify other system keyboards **do not** appear on the keyboard picker menu
6. Click the "i" icon to display keyboard info for sil_euro_latin
* **TEST_SYSTEM** - Verifies keyboard …
=> refactor(android/engine): Consolidate Keyboard picker intent 🛋

common/web/types/src/consts/virtual-key-constants.ts, core/tests/unit/ldml/keyboards/k_011_mt_iso.xml, core/tests/unit/ldml/keyboards/meson.build, developer/src/kmc-keyboard/src/compiler/keys.ts, developer/src/kmc-keyboard/src/compiler/messages.ts, developer/src/kmc-keyboard/src/compiler/visual-keyboard-compiler.ts, developer/src/kmc-keyboard/src/util/util.ts, developer/src/kmc-keyboard/test/fixtures/sections/keys/hardware_iso.xml, developer/src/kmc-keyboard/test/fixtures/sections/keys/hardware_us.xml, developer/src/kmc-keyboard/test/fixtures/sections/keys/invalid-bad-modifier.xml, developer/src/kmc-keyboard/test/test-keys.ts, developer/src/kmc-keyboard/test/test-utils.ts
- add HardwareToKeymap in common/web/types
- add a mt-iso keyboard, very close to stock mt.xml
- add machinery for parsing modifier key sequences
- more test machinery
- add assertions against invalid modifier sequences
Fixes: #7965
Note: followups:
- #8160 
- #8161 
=> feat(common): ldml different hardware support 🙀

common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts, common/web/types/src/util/compiler-interfaces.ts, common/web/types/test/fixtures/import-minimal.xml, common/web/types/test/fixtures/import-minimal1.xml, common/web/types/test/fixtures/import-minimal2.xml, common/web/types/test/fixtures/import-symbols.xml, common/web/types/test/fixtures/invalid-conforms-to.xml, common/web/types/test/fixtures/invalid-import-base.xml, common/web/types/test/fixtures/invalid-import-path.xml, common/web/types/test/fixtures/invalid-import-readfail.xml, common/web/types/test/fixtures/invalid-import-wrongroot.xml, common/web/types/test/helpers/index.ts, common/web/types/test/helpers/reader-callback-test.ts, common/web/types/test/ldml-keyboard/test-ldml-keyboard-xml-reader.ts, common/web/types/test/tsconfig.json, developer/src/kmc-keyboard/src/compiler/compiler.ts, developer/src/kmc-keyboard/test/helpers/index.ts, developer/src/kmc/src/kmc.ts
For: #7534
- move the import related Errors into messages
- comprehensive test cases for import/implied
=> feat(common): ldml: import error messages from the compiler   🙀

linux/debian/control, linux/debian/tests/control, linux/debian/tests/test-build
Autopkgtests couldn't find pkg-config, so this change adds that as test dependency.
(🍒 picked from PR #8180 )
=> fix(linux): Fix autopkgtests 🍒

windows/src/desktop/kmshell/locale/pt-BR/strings.xml
Relates to #8075 
> Note: English language also appears twice in the list.
The pt-BR localization incorrectly listed English as the locale name. This updates the string in Crowdin.
I'm unclear why pt-BR was added in the first place. Likely the localization existed pre-Crowdin, but currently it's only 29% complete. Hence some of the imported strings are still in English.
* **TEST_WINDOWS_LANGUAGE_LIST** - Verifies English doesn't appear twice
1. Install the PR build of Keyman for Windows
2. Open Keyman Configuration dialog.
3. Click the 'Display in' list box.
4. Scroll down and verify "English" is only listed once
5. Verify "Português do Brasil" is also on the list
6. Select "Português do Brasil"
7. Verify **some** of the UI is in Portuguese - Brazil. As noted on the PR, the localization …
=> chore(windows): Fix Portuguese UI language name

windows/src/desktop/kmshell/xml/keyman_keyboardlist.xsl
Fixes #8185
The id node taken from the keyman_keyboardlist.xsl was using the packgage id name rather than the keyboard id name. This change corrects that.
=> fix(windows): add remove lang id uses correct keyboard id 

windows/src/desktop/kmshell/locale/pt-BR/strings.xml
Relates to #8075 and 🍒 pick of #8184 to stable-16.0
> Note: English language also appears twice in the list.
The pt-BR localization incorrectly listed English as the locale name. This updates the string in Crowdin.
I'm unclear why pt-BR was added in the first place. Likely the localization existed pre-Crowdin, but currently it's only 29% complete. Hence some of the imported strings are still in English.
* **TEST_WINDOWS_LANGUAGE_LIST** - Verifies English doesn't appear twice
1. Install the PR build of Keyman for Windows
2. Open Keyman Configuration dialog.
3. Click the 'Display in' list box.
4. Scroll down and verify "English" is only listed once
5. Verify "Português do Brasil" is also on the list
6. Select "Português do Brasil"
7. Verify **some** of the UI is in Portuguese - Brazil. As …
=> cherrypick(windows): Fix Portuguese UI language name 🍒

linux/debian/control, linux/debian/tests/control, linux/debian/tests/test-build
Autopkgtests couldn't find pkg-config, so this change adds that as test dependency.
=> fix(linux): Fix autopkgtests

linux/debian/changelog, linux/debian/tests/control
This overlaps with PR #8180, but it updates the changelog to a patched version on Debian, so we still need this change.
=> chore(linux): Update changelog from Debian

windows/src/desktop/kmshell/xml/keyman_keyboardlist.xsl
Cherry pick from #8186 fixing issue #8185
The id node taken from the keyman_keyboardlist.xsl was using the packgage id name rather than the keyboard id name. This change corrects that.
=> fix(windows): add remove lang id uses correct kbd 🍒

common/windows/delphi/general/BCP47Tag.pas, developer/src/tike/dialogs/languages/Keyman.Developer.UI.UfrmSelectBCP47Language.pas
Fixes #8157.
There are some limitations in this dialog as it stands; we will rework it completely when we revisit BCP 47 tagging.
However, for now, this addresses some strange behaviours around the Reset button and the displayed output:
* The Reset button will only be enabled if you change the text in the Language Name field.
* The messaging around a missing language subtag is clearer -- tells the user that they need to enter something there.
* The Reset button will now never insert default text strings into the Language Name field.
One example of something that is slightly weird, is if you enter a two-letter region subtag into the script box, it will show what looks like a valid tag in the output box (e.g. `en-Au`), but it will be considered invalid, because that two letter subtag needs …
=> fix(developer): Select BCP47 Code dialog inconsistencies

common/predictive-text/build.sh, common/web/input-processor/build.sh, common/web/keyboard-processor/build.sh, resources/build/build-utils.md, resources/builder.inc.sh, web/build.sh, web/src/engine/build.sh, web/test.sh
`builder_check_color()` is now an internal function, called automatically, and should never need to be called from a `build.sh` script. All scripts updated accordingly.
=> chore(common): automatically apply _builder_check_color

resources/build/run-required-test-builds.sh
This works around a problem where status.keyman.com keeps a PR in the "Waiting for build" status because no status messages appear in the PR because no files changed that affect any platform (e.g. changes in GHA or [documentation](https://github.com/keymanapp/keyman/pull/8202)) which causes no platform builds to be triggered.
**Edit:** #8209 is no longer an example where this happens because I had to change additional files that triggered a build.
=> chore(common): Report status if no platform needs build

linux/debian/changelog, linux/debian/tests/control
We don't build the binaries on s390x so it doesn't make sense trying to run the autopkg tests on s390x. This change imports the changes made on Debian in pkg version 16.0.138-4.
Co-authored-by: Gunnar Hjalmarsson <gunnarhj@ubuntu.com>
(🍒-picked from PR #8217)
=> chore(linux): Exclude autopkg tests on s390x 🍒

linux/debian/changelog, linux/debian/tests/control
We don't build the binaries on s390x so it doesn't make sense trying to run the autopkg tests on s390x. This change imports the changes made on Debian in pkg version 16.0.138-4.
Co-authored-by: Gunnar Hjalmarsson <gunnarhj@ubuntu.com>
=> chore(linux): Exclude autopkg tests on s390x

common/web/types/build.sh, common/web/types/src/main.ts, common/web/types/src/util/compiler-interfaces.ts, common/web/types/test/helpers/reader-callback-test.ts, core/tests/unit/ldml/keyboards/k_001_tiny-test.xml, core/tests/unit/ldml/keyboards/meson.build, developer/src/kmc-keyboard/build.sh, developer/src/kmc-keyboard/src/compiler/compiler.ts, developer/src/kmc-keyboard/test/fixtures/test-fr.json, developer/src/kmc-keyboard/test/fixtures/test-fr.xml, developer/src/kmc-keyboard/test/helpers/index.ts, developer/src/kmc-keyboard/test/test-testdata-e2e.ts, developer/src/kmc/build.sh, developer/src/kmc/src/kmc.ts
- developer: add a `-T` option that reads/emits test json instead of kmx
- core: add a mechanism for generating .json test data for xml source files that have them - not used yet.
for #7535 
=> feat(developer): ldml emit test data from kmc, integrate into core 🙀

windows/src/desktop/kmshell/xml/installkeyboard.css
Fixes #8077 
Changed `#tabs div` in `installkeyboards.css` from using a fixed width to min-width this allows the tab label to grow to accommodate much longer strings. There is plenty of horizontal real estate, no need to wrap the text.
1. Install Keyman from this PR
2. Open Keyman Configuration dialog.
3. Change the UI language into 'Kannada'.
4. Click the 'Download keyboard' button.
5. In Download Keyboard From keyman.com dialog, enter 'Khmer_Angkor' in the Keyboard search bar.
6. Click the 'Khmer Angkor' language from the results.
7. Click 'Khmer Angkor' link.
8. Click Install Keyboard button.
9. Here, I noticed that the Readme label name no longer wraps and the the tab is properly aligned containing the full text.
Expected behavior
Kannada 'Readme' label name should appear inside the …
=> fix(windows): use min-width allow to expand

web/build.sh
This is a very minor refactor and cleanup of web/build.sh, mostly removing some redundant globals which had different names to the folders they were referring to, which was confusing (for example `$INTERMEDIATE` for `obj`, `$SOURCE` for `src`), and removing the `output_path` function which just obfuscated what was a clean straightforward output path. :grin:
I also did not see any purpose in keeping the constants `$DEBUG` == `debug` or `$RELEASE` == `release`. The presence of these two environment variable names in particular is also often interpreted used by build tools so prefer not to use them in this way.
=> chore(web): minor cleanup of web/build.sh

web/build.sh
Fixes #8255. (Doesn't attempt to address the idea of `--debug` vs `--no-minify`, which I think we need to consider more carefully.)
=> fix(web): `--no-minify`, not `--skip-minify`

common/predictive-text/unit_tests/test.sh, common/test/resources/test_kill_browserstack.sh, core/build.sh, resources/build/build-utils.sh, resources/devbox/iis-https/setup-iis-https.sh, resources/shellHelperFunctions.sh, web/test.sh
Continues consolidation of various 'helper' functions:
* Removes unused function `get_platform_folder`
* Renames `os_id` to `BUILDER_OS`
=> chore: cleanup some of shellHelperFunctions.sh

.github/workflows/deb-packaging.yml, linux/scripts/deb-packaging.sh
This reduces the noise on the GHA summary page.
=> chore(linux): Output results of API verification on stderr

.github/workflows/deb-packaging.yml
We need to check out the source code before we can run the apt-install action in the packaging GHA.
=> fix(linux): Checkout before  running apt-install

developer/src/kmcmpdll/Compiler.cpp
Long ago, ESC was a useful way to stop the compiler. These days, it's so fast that it's hard to break it that way anyway. It's also watching in the background, so that's bad... because if you have keyboard compiles happening in the background and hit Esc at the wrong time, you cancel the build. So... delete it!
=> chore(developer): ignore Esc key when compiling

linux/ibus-keyman/src/engine.c
When using Wayland `im-wayland.so` (which is part of libgtk) gets loaded into the client app instead of `im-ibus.so`. This means that our ordered output doesn't work with Wayland.
This change works around a problem with keyboards that use multiple consecutive backspace actions. Because method calls get processed asynchronously some backspaces get lost. In clients that support surrounding text we can count the consecutive backspaces and then do one call to delete surrounding text with the appropriate number of characters.
This can be tested with "Khmer Angkor" keyboard by typing `xEjmr`, or with "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard by typing `shrI`.
Part of #4273. See https://github.com/keymanapp/keyman/issues/4273#issuecomment-1241703095 in particular. …
=> fix(linux): Collect consecutive backspaces

.github/workflows/deb-packaging.yml
`deb_signing` only runs for release builds, so it doesn't make sense that `set_status` (which only runs for non-release builds) depends on it.
=> chore(linux): Cleanup GHA

ios/engine/KMEI/KeymanEngine/Classes/Resource Data/InstallableKeyboard.swift, ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPKeyboard.swift
Fixes #8118.
When loading kmp file, Keyman will load successfully if there are duplicate entries in the languages array of the keyboard.
* **TEST_KMP_FILE_WITH_DUPLICATE_LANGUAGE**
1. On the iOS Simulator, install Keyman
2. Install the Khmer Angkor keyboard
3. Remove the default Euro Latin keyboard
4. In its place, install this [Euro Latin keyboard version 2.0.1 with duplicate languages](https://downloads.keyman.com/keyboards/sil_euro_latin/2.0.1/sil_euro_latin.kmp)
5. Verify that Keyman loads this keyboard OK and runs normally
=> fix(ios): allow duplicate languages in kmp file

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
Fixes #8229
This issue was quite puzzling. Only on newer Android SDKs, the in-app keyboard width failed to refresh when rotating the device from portrait to landscape. System Keyboard wasn't affected so I compared `MainActivity.onConfigurationChanged` and `SystemKeyboard.onConfigurationChanged`.
I add this line, and OSK rotation works. I take revert, and the issue is reprod. afaict, the issue **not** appear on stable-16.0.
Setup - Use Android emulator/device with SDK >= 31
* **TEST_OSK_ROTATION** - Verifies OSK refreshes width on rotation
1. Install the PR build of Keyman for Android in portrait orientation
2. Observe the in-app keyboard fills the device width
3. Rotate the device to landscape (you may need to toggle the Android setting to auto-rotate)
4. Observe the in-app keyboard …
=> fix(android/app): Fix OSK width when rotating

docs/build/macos.md
Symptom:
```
$ cd core ; ./build.sh build:arch
realpath: illegal option -- -
usage: realpath [-q] [path ...]
```
By the way, if this was done everywhere, we could use `readlink` instead of `greadlink` in the scripts.  I note that it says 'M1 only' but it might be Ventura only?
=> chore(docs): update docs due to Mac Ventura

web/src/engine/dom-utils/src/cookieSerializer.ts, web/src/engine/dom-utils/src/index.ts, web/src/engine/namespaced-main/kmwutils.ts, web/src/engine/osk/src/index.ts, web/src/engine/osk/src/views/floatingOskCookie.ts, web/src/engine/osk/src/views/floatingOskView.ts, web/src/test/auto/dom/cases/dom-utils/cookies.js
Modularizes Web's longstanding `loadCookie` and `saveCookie` utility functions as a serialization object with far better type-checking capabilities + Intellisense compatibility. 
Passing a compatible `interface` definition into the type parameter of the new `CookieSerializer` class allows it to type check inputs and provide automatic type-casting convenience on its loaded outputs.  The class's internal logic is also more thoroughly type-specified as well.  Furthermore, noting that some of our cookies need encoding of some kind - be it into strings or into `encodeURIComponent` forms of strings - it can also apply the necessary transforms during save and load operations.
The main motivations here:
- it'll be far, far easier to encapsulate any persistent-storage boilerplate code and logic
- …
=> refactor(web): cookie serialization + deserialization 🧩

resources/builder.inc.sh, resources/shellHelperFunctions.sh
Example:
Actual build output: `common/web/keyboard-processor/build/index.js` (no second `s`)
The warning is only omitted when the action "succeeds" _**and**_ the described output is missing.
----
I just opted for the behavior seen above because it is the least intrusive.  Feel free to tweak the behavior as desired - it'd just be a nice check to have, one way or the other.
=> feat(common): adds warning if described output does not exist

linux/ibus-keyman/tests/scripts/setup-tests.sh
With recent work the location where we generate the test files changed, but the test setup script didn't completely work.
=> chore(linux): Improve detecting presence of test files

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
Reverts #8291 and fixes #8306
I will have to re-open #8229 for investigation...
This reverts commit dc7603a97d9ee383effe73b6d43cf9a42136ae3a.
Setup - install the PR build of Keyman for Android
* **TEST_INSTALL** - Verifies reported issue does not appear
2. Open Keyman In-App.
3. Open Settings menu.
4. Enable Keyman as system-wide keyboard. 
5. Enable 'Set Keyman as default keyboard'.
6 Add 'Khmer Angkor' Keyboard using 'Install Keyboard or Dictionary' option. 
7. Verify blank screen does **not** appear
=> chore(android/app): Revert #8291

core/tests/unit/ldml/keyboards/meson.build, developer/src/kmc-model/package.json, developer/src/kmc/README.md, developer/src/kmc/build.sh, developer/src/kmc/package.json, developer/src/kmc/src/activities/buildLdmlKeyboard.ts, developer/src/kmc/src/activities/buildTestData.ts, developer/src/kmc/src/commands/build.ts, developer/src/kmc/src/commands/buildTestData.ts, developer/src/kmc/src/kmc.ts, developer/src/kmc/src/kmlmc.ts, developer/src/kmc/src/kmlmi.ts, developer/src/kmc/src/kmlmp.ts, developer/src/kmc/src/util/NodeCompilerCallbacks.ts, package-lock.json
Starts the refactor of `kmc` to support the `build` command. In this PR, only supports building LDML keyboards. But infrastructure is in place to add different types of builds.
I have moved `-T` option to `build-test-data` command for now. Not sure exactly how this fits, and even if it should be in kmc at all. But it'll do as a start.
This file layout is intended to help keep options and commands under control and modular:
* commands/ contains all the command-line processing for each command
* activities/ contains all the logic and file processing, wrapping file input/output from the corresponding kmc-* module.
It's going to grow substantially!
=> feat(developer): kmc build command 🙀

developer/src/kmc/src/activities/buildKmnKeyboard.ts, developer/src/kmc/src/activities/buildLdmlKeyboard.ts, developer/src/kmc/src/activities/buildTestData.ts, developer/src/kmc/src/commands/build.ts, developer/src/kmc/src/util/getDeveloperBinPath.ts
Uses existing kmcomp.exe to build .kmn files. Requires kmc to be in a subfolder of the Keyman Developer binary folder.
=> feat(developer): support build of .kmn from kmc 🙀

common/web/types/src/util/compiler-interfaces.ts, developer/src/kmc-keyboard/build.sh, developer/src/kmc-keyboard/test/helpers/index.ts, developer/src/kmc/build.sh, developer/src/kmc/src/activities/buildKmnKeyboard.ts, developer/src/kmc/src/activities/buildProject.ts, developer/src/kmc/src/commands/build.ts, developer/src/kmc/src/util/NodeCompilerCallbacks.ts, developer/src/kmcomp/main.pas
Adds support for building .kpj projects. Required minor tweak to kmcomp to allow it to build both .kmx and .js from .kmn command line. Currently, calls kmcomp.exe to build .kmn files, until we support a cross-platform kmc-kmn C++ project.
=> feat(developer): kmc .kpj support 🙀

resources/build/tests/builder.inc.test.sh, resources/build/tests/dependencies/app/build.sh, resources/build/tests/dependencies/error/build.sh, resources/builder.inc.sh
Fixes #8322.
This issue was arising due to subshells masking the exit code.
[set -e is not really to be trusted](http://mywiki.wooledge.org/BashFAQ/105).
Also, avoid -v for testing arrays in builder.
=> chore(common): fix child build error handling

linux/debian/rules
=> chore(linux): disable node-based core tests when testing during packaging

linux/ibus-keyman/build.sh
Paths that describe outputs are supposed to be relative to root, not absolute. Also, it turns out we don't use the `--output` parameter, so this change removes it.
=> fix(linux): Fix ibus-keyman/build.sh

linux/debian/ibus-keyman.postinst
The ibus-keyman post-installation script could fail, causing the entire installation to fail. This change removes `set -e` so that we try to run the rest of the commands even when one command should fail. Also accounts for ibus-daemon being started with the full path, and start ibus-daemon with fill path as well.
(🍒-picked from PR #8294)
- **GROUP_JAMMY_X11:** Ubuntu 22.04 Jammy with Gnome Shell and X11 ("Ubuntu on Xorg")
- **GROUP_KINETIC_X11:** Ubuntu 22.10 Kinetic with Gnome Shell and X11 ("Ubuntu on Xorg")
- Download package build artifacts for this PR
- **TEST_INSTALL:** Install keyman and onboard
- in a terminal window, run the following commands in the directory where the packages got extracted (this might show errors):
```
sudo …
```
=> fix(linux): Fix debian postinst script 🍒

resources/build/tests/builder-deps.test.sh, resources/build/tests/builder.inc.test.sh, resources/builder.inc.sh
We should not attempt to build dependencies when running `clean`. Note: if your `clean` action requires dependencies, then something is very, very wrong and you should fix that!
This should resolve the failed Keyman Developer build on master.
=> fix(common): builder: skip dependency build for clean action

web/build.sh
This captures @mcdurdin 's fixes from 244962bf09d21e60b18f21690d7a3876d1b26da0 to web/build.sh 
* Additional module outputs 
Splitting this out of #7407 so it will trigger less CI builds while I troubleshoot that PR
=> chore(web): fixup dependencies in web build script

common/windows/delphi/general/RegistryKeys.pas, developer/src/tike/dialogs/UfrmOptions.dfm, developer/src/tike/dialogs/UfrmOptions.pas, developer/src/tike/main/KeymanDeveloperOptions.pas, developer/src/tike/project/Keyman.Developer.System.Project.kmnProjectFileAction.pas, developer/src/tike/project/Keyman.Developer.UI.Project.kmnProjectFileUI.pas
**TEST_LEGACY_COMPILE:** In Keyman Developer Tools/Options, check the option 'Use legacy compiler'. Load a keyboard project, compile it, and verify that the message 'NOTE: Using legacy compiler' shows up in the compiler output log.
**TEST_MODERN_COMPILE:** In Keyman Developer Tools/Options, uncheck the option 'Use legacy compiler'. Load a keyboard project, compile it, and verify that the message 'NOTE: Using legacy compiler' does _not_ show up in the compiler output log.
=> feat(developer): add 'Use Legacy Compiler' option to TIKE 🚑

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardWebViewClient.java
Fixes #8305 and fixes #8337 which were regressions introduced in the #7993 refactoring
During my refactoring of KMKeyboardWebViewClient.java, I haphazardly left all the members `static`, which meant there were collisions when both InApp and System keyboards updated themselves.
Setup - Install the PR build of Keyman for Android
* **TEST_GLOBE_KEY_WORKS_AFTER_SYSTEM_KEYBOARD** - Verifies #8337 is fixed
2. Open Keyman In-App
3. Click the Globe key
4. May notice that the Keyboard picker menu opens on the screen
5. Open Settings menu
6. Enable Keyman as the "System-wide keyboard" and "Default keyboard"
7. Revert to OSK
8. Click the globe key
9. Dismiss keyboard picker and verify keyboard area is **not** blank
* …
=> fix(android/engine): Fix various OSK bugs due to refactor 🛋

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
Fixes #8229 and re-implements #8291
I believe the concerns from #8306 are actually fixed by #8349 which fixed a few issues about interactions between InApp and System keyboard.
Setup - Install the PR build of Keyman for Android
* **TEST_OSK_ROTATION** - Verifies OSK correctly rotates #8229
1. Install the PR build of Keyman for Android on portrait orientation
2. Open the Keyman app
3. Change the mobile view into landscape.
4. Verify the OSK readjusts to fill the entire width
* **TEST_INSTALL_SECOND_LANGUAGE** - Verifies #8306 is still fixed
2. Open Keyman In-App.
3. Open Settings menu.
5. Enable Keyman as system-wide keyboard.
6. Enable 'Set Keyman as default keyboard'.
6 Add 'Khmer Angkor' Keyboard using 'Install Keyboard or Dictionary' …
=> fix(android/app): Another attempt at fixing OSK rotation

common/web/keyman-version/build.sh, common/web/utils/build.sh, resources/build/build-utils.md, resources/builder.inc.sh
Makes the output of log messages from builder scripts more consistent, and uses color more effectively to highlight specific parts of lines.
Note: updates documentation for builder_describe_internal_dependency from parent PR #8342.
Sample:
* Highlights top-most script with bright-white+bold identifier
* Dependencies have grey identifiers
* Blue for headings
* Purple for dependency/parameter info
* Yellow for warnings
* Red for errors
=> chore(common): cleanup build.inc.sh echo

linux/ibus-keyman/src/engine.c, linux/ibus-keyman/src/engine.h, linux/ibus-keyman/src/keyman-service.c, linux/ibus-keyman/src/keyman-service.h, linux/ibus-keyman/src/main.c
This new DBus method allows an OSK to output a junk of text.
See [keyman-osk-poc-x11](https://github.com/ermshiperete/keyman-osk-poc-x11) for a simple POC client.
=> feat(linux): Add DBus method `SendText`

core/commands.inc.sh, core/src/meson.build, linux/debian/libkmnkbp-dev.install
This change creates both dynamic and static libs on Linux. 
=> chore(core): Create both dynamic and static libs on Linux

common/predictive-text/unit_tests/test.sh, core/build.sh, linux/ibus-keyman/build.sh, resources/build/build-utils.md, resources/builder.inc.sh, web/ci.sh, web/test.sh
Fixes #8373.
Replaces #8378 (basing on master; android script updates will be added to #7407).
Note that the core functionality requested in #8373 is already in place; this commit just does some cleanup to make this easier to maintain in the future:
* Uses `builder_is_debug_build` function to test for debug build (instead of `builder_has_option --debug`, which would also work but using the other function avoids typo issues with the option name).
* Renames `$_builder_debug` to `$_builder_debug_internal` to reduce naming confusion
* Documents `$builder_debug`, `builder_is_debug_build`, and clarifies usage of `--debug` option.
* Logs command line for dep builds (we could hide this in the future, but it certainly doesn't hurt for now!)
=> chore(common): clean up `--debug` usage in build scripts

developer/src/kmcmplib/src/Compiler.cpp
fixes: #8355
In kmcompdll we use \r\n as line ending which works for windows. We need to ensure that this works on Linux as well ( as there is no \r) 
see https://github.com/keymanapp/keyman/pull/6980#discussion_r975516282 cross-platform kmx compiler 🚑 https://github.com/keymanapp/keyman/pull/6980, [#7330](https://github.com/keymanapp/keyman/pull/7330)
=> chore(developer): use consistent line endings \r\n

resources/build/build-utils.md, resources/builder.inc.sh
Appending a `+` to a builder option will automatically pass that option to child scripts.
I wanted to apply #8371 to master branch so #7407 can remain strictly Android changes. (This can replace #8371)
TODO on #7407 - add inheritable options syntax.
=> feat(common): builder.inc.sh inheritable options

developer/src/kmcmpdll/Compiler.cpp, developer/src/kmcmplib/include/kmcmplibapi.h, developer/src/kmcmplib/include/kmcompx.h, developer/src/kmcmplib/src/CasedKeys.cpp, developer/src/kmcmplib/src/Compiler.cpp, developer/src/kmcmplib/src/json-validation.cpp, developer/src/kmcmplib/src/virtualcharkeys.h, developer/src/kmcmplib/tests/kmcompxtest.cpp
Introduces kmcmplibapi.h which declares all external functions and types for kmcmplib, and updates kmcmplib and kmcmpdll to use these declarations consistently.
Note that kmcmp_CompileKeyboardToBuffer declares a void* instead of PFILE_KEYBOARD, because this is a large and complex type defined in both kmcmpdll and kmcmplib. In the future, when kmcmpdll existing legacy compiler is removed, we can make the kmcmplib type more public.
=> chore(developer): cleanup API interfaces and types for kmcmplib

developer/src/kmcmplib/src/xstring.cpp
fixes: #8082
In developer/src/kmcmplib/src/xstring.cpp (l. 24) 
```
// UC_SENTINEL(FFFF) with UC_SENTINEL_EXTENDEDEND(0x10) == variable length
if (*(p + 1) == CODE_EXTENDED) {
p += 2;
while (*p && *p != UC_SENTINEL_EXTENDEDEND)
```
We probably should check for *p != NULL as well in case we have invalid data.
and from line 57 :
```
p--;
if(*p == UC_SENTINEL_EXTENDEDEND) {
int n = 0;
while (p >= pStart && *p != UC_SENTINEL && n < 10) {
```
It would be better to test for `p > pStart` and change the line after the block below to `if(p <= pStart)`. That way we wouldn't have to decrement the pointer to an unallocated memory location which some machines don't like.
see comment [#6980 (comment)](https://github.com/keymanapp/keyman/pull/6980#discussion_r1068199232) and [#6980 …
=> chore(developer): check for *p != NULL and test for p > pStart

developer/src/ext/json-schema-validator/json-validator.cpp, developer/src/kmcmplib/commands.inc.sh, developer/src/kmcmplib/include/kmcompx.h, developer/src/kmcmplib/src/CasedKeys.cpp, developer/src/kmcmplib/src/CheckFilenameConsistency.h, developer/src/kmcmplib/src/CheckNCapsConsistency.h, developer/src/kmcmplib/src/Compiler.cpp, developer/src/kmcmplib/src/DeprecationChecks.h, developer/src/kmcmplib/src/Edition.cpp, developer/src/kmcmplib/src/NamedCodeConstants.cpp, developer/src/kmcmplib/src/compfile.h, developer/src/kmcmplib/src/kmx_u16.cpp, developer/src/kmcmplib/src/kmx_u16.h, developer/src/kmcmplib/src/versioning.h, developer/src/kmcmplib/tests/get_test_source_exclude_some_kmn.bat
This is not enough for building to WASM, but wanted to split out the bigger changes into their own PRs. This is mostly busy-work.
One serious bug fix:
* u16string_from_string was not converting from UTF-16 correctly
Apart from that, just tidies up a few bits and pieces in kmcmplib:
* type coercion for json-validator.cpp (probably already fixed upstream)
* cleanup of build scripts for new builder variable names
* various compatibility macros for MSVC vs clang
* safer math expressions
* file name casing in headers
* replacement of various ms-only std funcs
* removed some unused variables and consts
* tightened up search for keyboards to get only keyboards in /source/ folders (may be possible to improve further in the future?)
=> chore(developer): cross-platform fixups pre-wasm build of kmcmplib 🚑

developer/src/common/delphi/compiler/compile.pas, developer/src/kmcmpdll/Compiler.cpp, developer/src/kmcmpdll/compfile.h, developer/src/kmcmplib/src/Compiler.cpp, developer/src/kmcmplib/src/compfile.h
This fixes two issues:
1. `COMP_KEY` structure had padding that was not always zeroed out. Made this explicit.
2. Rule sorting could be inconsistent when re-sorting rules that use `+ any() > ...`, which are expanded at compile time into multiple rules, and which ended up with identical sort keys due to lack of precision. This relates to #8381 but only adds differentiation for the otherwise ambiguous rule sort keys, and does not fix that issue, which requires further investigation.
=> fix(developer): improve .kmx output consistency for cross-platform 🚑

web/build.sh
Relates to #8255, just fixes the misnomer but doesn't change to debug vs release which needs more work.
Hoping this fixes the Developer release build.
=> fix(web): --no-minify, not --skip-minify

core/build.sh, linux/.gitignore, linux/Makefile, linux/ibus-keyman/tests/scripts/run-tests.sh, linux/ibus-keyman/tests/scripts/setup-tests.sh, linux/scripts/build.sh, linux/scripts/dist.sh, linux/scripts/install.sh
Linux package builds no longer require a different target path, so we can remove the `--target-path` parameter.
=> chore(core): Remove obsolete `--target-path` option

core/wasm.build.linux.in, core/wasm.build.mac.in, core/wasm.build.win.in, core/wasm.defs.build
Fixes #8010.
Note that #8398 moves other settings into a shared resources folder, and once that hits master, it would be good to do another round of consolidation to share the wasm defs in resources as well.
=> refactor(core): consolidate wasm defs

common/web/keyman-version/package.json, common/web/types/package.json, common/web/types/src/keyman-touch-layout/keyman-touch-layout-file-reader.ts, common/web/types/src/kpj/kpj-file-reader.ts, common/web/types/src/kvk/kvks-file-reader.ts, common/web/types/src/kvk/visual-keyboard.ts, common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts, common/web/types/src/main.ts, common/web/types/test/ldml-keyboard/test-ldml-keyboard-xml-reader.ts, developer/src/kmc-keyboard/package.json, developer/src/kmc-keyboard/src/compiler/metadata-compiler.ts, developer/src/kmc-keyboard/test/test-metadata-compiler.ts, developer/src/kmc-model-info/package.json, developer/src/kmc-model-info/src/model-info-compiler.ts, developer/src/kmc-model-info/src/model-info-file.ts, developer/src/kmc-model/src/model-definitions.ts, developer/src/kmc-model/src/script-overrides-decorator.ts, developer/src/kmc-package/package.json, developer/src/kmc-package/src/kmp-compiler.ts, developer/src/kmc-package/src/kmp-json-file.ts, developer/src/kmc-package/src/kps-file.ts, developer/src/kmc-package/test/test-package-compiler.ts, developer/src/kmc/package.json, developer/src/kmc/src/kmc.ts, developer/src/kmc/src/kmlmc.ts, developer/src/kmc/src/kmlmi.ts, developer/src/kmc/src/kmlmp.ts, package-lock.json, tsconfig.esm-base.json
Note: supersedes #8427.
Also note:  assumes that #8419 won't conflict and will resolve failing tests under `common/web/types`.  (These are not currently run by CI, so go unnoticed by our checks at the moment anyway.)
Fixes #8420.
Accomplishes the following goals:
- A few new modules from `feature-ldml` had their TS version updated.
- Some were set to use precisely TS `4.6.3` for some reason, not `^4.6.3`... and certainly not `^4.9.5` like the rest of our TS-reliant modules. 
- Some were set to `^4.5.4`, but this didn't really affect the package-lock.json - especially not like the rigid `4.6.3` did.
- Establishes export mapping for `common/web/keyman-version`, making the differentiated namespace vs module build product setup invisible when importing the package.
- Yay, cleaner import …
=> chore(common): TS updates to non-sync'd packages, feature-esmodule merge conflict prevention

common/linux/build.sh, common/mac/build.sh, common/web/build.sh, common/web/keyman-version/build.sh, common/web/utils/build.sh, common/windows/build.sh, resources/build/trigger-definitions.inc.sh, resources/builder.inc.sh
Note 4 new build configs:
These run corresponding `common/___/build.sh configure build test`. For now, mac, linux and Windows have no tests. But this provides hooks for them.
Web has a couple of tests.
=> chore(common): add common test build configurations

developer/src/kmc/package.json
Fixes #8433.
It sounds like `esbuild` is looking for the most selective ES-version target, and since `common/web/keyman-version` is set to ES5 in its tsconfig.json, it runs with that... despite the top level products targeting ES2022.  (ES5 will be needed when KMW is modularized due to our back-compat on older Android devices.)  Setting the option above will tell `esbuild` we know better, that the final product is ES2022-compatible - and will bypass the issue.
=> fix(developer/compilers): locks esbuild target detection for kmc building

web/build.sh
I was following the web and Keyman Engine for Android build log for investigating #8442 and saw some stray formatting
After applying changes similar to #8334 to web/build.sh the version correctly appears in purple:
=> chore(web): Cleanup build echo

developer/src/common/delphi/lexicalmodels/Keyman.Developer.System.LexicalModelCompile.pas
Fixes #8443.
Fixes KEYMAN-DEVELOPER-12X.
Will cherry-pick to stable-16.0.
The regex for matching error messages has an optional section for the file/line detail (line 54):
https://github.com/keymanapp/keyman/blob/9db4cf23799b4e528d4333db9d7f509d977a0bc4/developer/src/common/delphi/lexicalmodels/Keyman.Developer.System.LexicalModelCompile.pas#L54
The first part of that regex:
```regex
^(?:(.+) \((\d+)\): )?
```
The code that parses the results did not account for this being optional, which would cause a crash if the error message did not include this information.
=> fix(developer): lm compiler handle missing line no in errors

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java, android/KMAPro/kMAPro/src/main/res/menu-land/main.xml, android/KMAPro/kMAPro/src/main/res/menu-sw600dp/main.xml, android/KMAPro/kMAPro/src/main/res/menu/main.xml
🍒 of #8428 to 17.0 alpha
Intermediary step towards #2159 
This PR temporarily disable access to the in-app browser (Keeps the Keyman app account agonistic)
**Setup** 
Install the PR build of Keyman for Android 
* **TEST_BROWSER_DISABLED** - Verifies Keyman browser can't be accessed
1. Launch Keyman for Android in portrait orientation
2. Observe the menu icons and verify the browser icon is not visible
3. Rotate the device to landscape orientation
4. Observe the menu icons and verify the browser icon is not visible
=> fix(android/app): Temporarily disable Keyman browser 🍒

android/KMEA/build.sh, android/Samples/KMSample1/build.sh, android/Samples/KMSample2/build.sh, android/Tests/KeyboardHarness/build.sh
Follow-on to #7407 
@bharanidharanj was getting exceptions loading test builds of "Keyman for Android". Turns out the KMEA builder configure step wasn't consistently triggering, so the engine got built missing the embedded KeymanWeb dependencies.
* **TEST_KEYMAN** - Verifies Keyman app runs fine
2. Verify OSK appears behind the "Get Started" menu
3. Verify exceptions **do NOT** appear about being unable to copy an asset file
[Screenshot of an exception](https://user-images.githubusercontent.com/19683143/225273142-d7f6221b-c5b2-41e1-9f81-40fa1c31d5b1.png) as reported
=> fix(android/engine): Add builder output for configure

android/README.md
This updates the Android README with the updated build script syntax from #7407
=> chore(android): Document builder script steps

resources/build/tests/builder.inc.test.sh, resources/build/tests/trees/build.sh, resources/build/tests/trees/child1/build.sh, resources/builder.inc.sh
Fixes #8471.
Ensures that `npm take-forever` (aka `npm ci`, `npm install`) only runs once during a parent/child build script run.
Note that this also works even where build scripts manually call other build scripts (e.g. input-processor as it is currently calling kmc build manually) -- though this is not a recommended practice.
=> chore(common): prevent multiple npm ci runs in child scripts

linux/debian/changelog, linux/debian/control
This reverts commit 07ae306fd41e1c7d0e4274020e3656ac2c7afed8 which got merged in PR #6500 after a [discussion on the Debian mailing list](https://lists.debian.org/debian-input-method/2022/03/msg00095.html).
However, Keyman currently doesn't work on s390x architecture because we don't support big-endian (#5111). This shows in test failures during package build (cf [build log](https://buildd.debian.org/status/fetch.php?pkg=keyman&arch=s390x&ver=16.0.138-4&stamp=1676139609&raw=0)).
=> chore(linux): Prevent building on s390x

linux/debian/changelog, linux/debian/control
This reverts commit 07ae306fd41e1c7d0e4274020e3656ac2c7afed8 which got merged in PR #6500 after a discussion on the Debian mailing list.
However, Keyman currently doesn't work on s390x architecture because we don't support big-endian (#5111). This shows in test failures during package build (cf [build log](https://buildd.debian.org/status/fetch.php?pkg=keyman&arch=s390x&ver=16.0.138-4&stamp=1676139609&raw=0)).
(🍒-picked from #8476)
=> chore(linux): Prevent building on s390x 🍒

linux/keyman-config/keyman_config/install_kmp.py, linux/keyman-config/keyman_config/install_window.py, linux/keyman-config/keyman_config/view_installed.py
If the user tries to install a corrupt .kmp file we now display an error message instead of just logging to the console and Sentry.
Fixes #8478.
(🍒-picked from PR #8479)
- The test can be run on any Linux platform.
- Create an empty .kmp file by opening a terminal window and running: `touch /tmp/corrupt.kmp`
- Reboot
**TEST_MSG**: 
- open km-config
- click "Install" button
- select `/tmp/corrupt.kmp` file
- verify that a message box with an error is shown
=> fix(linux): Display error message for corrupt .kmp file🍒

linux/debian/changelog, linux/debian/tests/control, linux/debian/tests/test-build
This change allows the autopkgtests to run on s390x architecture but immediately exits the test with a successful return code.
=> chore(linux): Run and ignore autopkgtests on s390x

mac/Keyman4MacIM/write-download_info.sh, resources/shellHelperFunctions.sh
I am not 100% sure that this changed due to the macOS upgrade, but stat was now finding the coreutils version rather than the macOS version.
Later, we should probably standardize on the coreutils version so we can use it on all platforms.
=> chore(common): use mac /usr/bin/stat rather than homebrew version

common/web/keyboard-processor/src/text/outputTarget.ts, common/web/keyboard-processor/tests/node/mocks.js, common/web/keyboard-processor/tests/node/transcriptions.js, web/src/engine/element-wrappers/src/contentEditable.ts, web/src/engine/element-wrappers/src/designIFrame.ts, web/src/engine/element-wrappers/src/input.ts, web/src/engine/element-wrappers/src/textarea.ts, web/src/test/auto/dom/cases/element-wrappers/target_mocks.js, web/src/test/auto/integrated/cases/element_interfaces.js, web/src/test/auto/integrated/manual.conf.cjs
While `app/webview` shouldn't need a webpage element to serve as an intermediary for context management, there is the little issue that the best-suited `OutputTarget` type to use - `Mocks` - has not supported text selection up until now.
So, the obvious path forward:  resolve that issue and have `Mocks` support text-selection - including the ability to clone selected text when constructing them from other `OutputTarget` types.
Note:  this may be of use when resolving #7865 and #7866, though it should not be necessary - especially in regard to 16.0-stable.  Either way, it's work on this PR that led to the recent analyses I wrote for those two issues.
=> feat(common/web): mocks may now model selected text 🧩

common/web/input-processor/src/text/prediction/languageProcessor.ts, common/web/input-processor/src/text/prediction/predictionContext.ts, common/web/input-processor/tests/cases/predictionContext.js
With the direction that the modularization design is heading, things look to be significantly cleaner if `PredictionContext` can be specified and initialized once early on, rather than constantly reinitialized on every change of the context.  That way, a single instance of this class can be passed off as part of a `ContextManager`'s implementation to encapsulate the prediction-related aspects of context, which involve references to objects that `ContextManager` would otherwise not need to access.  
There's way less event-handler churn this way, and it also makes integration with the OSK (see #8466) simpler too.
=> refactor(common/web): context-swapping for PredictionContext 🧩

linux/help/common/index.md
- add Ubuntu 18.04 as being last supported in Keyman 16
- clarify that km-config needs to be started from command line in order to disable error reporting
Follow-up of https://github.com/keymanapp/keyman/pull/8526#issuecomment-1486067004.
=> docs(linux): Update common questions

developer/src/kmcmplib/src/filesystem.cpp, developer/src/kmcmplib/src/filesystem.h
=> chore(developer): move cassert ref to filesystem.cpp

linux/debian/control
Fixes #8468.
**TEST_SMOKE**: Install this PR, then run a quick smoke test: install a keyboard, verify it's working, remove it. Doesn't matter on which Ubuntu version this is tested.
=> chore(linux): Remove dependency on `sudo`

linux/keyman-config/keyman_config/view_installed.py
Fixes #8454.
- Can be run on any Linux platform
- Reboot
**TEST_NO_WARNING**: When closing the dialog, no error or warning shows
- Start km-config from the command line.
- In the Keyman Configuration dialog, click the Close button which appears at the bottom right of the dialog.
- Verify that no warning or error message appears in the terminal window.
=> fix(linux): Remove warning after pressing Close button

windows/src/desktop/kmshell/xml/config.css
Fixes: #8525 
The fixed layout of the popup means we need to use a specified starting point for the child div that contains the `add language` and `close` button. However, it needs to be right justified instead of left justified to allow for the variable-sized buttons. The buttons will be longer based on the locale text chosen.
1. Install Windows build from this PR
2. Open Keyman Configuration dialog.
3. Install any Keyboard. (eg., Khmer Angkor)
4. Change the UI language into Deutsch (German).
5. In the Keyboard Layouts tab, Click Add/remove language button.
6. Verify that the `Add Language` and `Close` Button now align inside the pop-up box.
7. Change the UI to other Languages and verify steps 5-6. for those languages.
=> fix(windows): use right instead of left alignment for popup buttons

ios/samples/build_common.sh, mac/Keyman4MacIM/localdeploy.sh, mac/Keyman4MacIM/make-km-dmg.sh, mac/setup/build.sh, oem/firstvoices/ios/build_common.sh
Fixes https://github.com/keymanapp/keyman/issues/8533 after build agent maintenance put GNU coreutils cp on path ahead of macOS /bin/cp. This subtly changed the behaviour of the `-R` flag such that it copied the folder into a subfolder rather than copying the contents of the folder into the destination folder:
Original layout:
```
Install Keyman.app/Contents/MacOS/
applet
textinputsource
Keyman.app/
```
Corrupted layout:
```
Install Keyman.app/Install Keyman.app/Contents/MacOS/
applet
textinputsource
Keyman.app/
```
Query: should we be rolling back the path changes so that /bin is first on the path? I am concerned about other subtle changes in behaviour in the macOS and iOS builds. Otherwise it feels like we may need to audit the scripts in /mac, /ios (and possibly /common, /core, /web, …
=> fix(mac): fix corrupt installer

developer/src/kmc/build.sh
Fixes #8574.
Also ensures that kmc is published after its dependencies.
=> fix(developer): add DRY_RUN variable to build.sh

resources/build/xcode-utils.sh
Looks like we haven't done much development-debugging for the iOS platform in a while.
While trying to diagnose issues with the ES module feature branch (see #8544), I found I was unable to build Keyman within Xcode, which is a prerequisite for launching/testing the app via Simulator and for locally installing on a test device without TestFlight.  It turns out... it was simply because of a missing environment variable definition when certain custom scripts were being triggered by top-level Xcode builds.
As best as I can tell, the git-blame for this likely lies within #7365 and #8344 - the original  `_builder_setBuildScriptIdentifiers` function (in #7365) silently failed when the environment variable was undefined, but the new version it introduced produced warnings.  This, in turn, was …
=> fix(ios): fixes xcode-triggered debug, run builds

windows/src/engine/README.md
This links to FAQ page on the Windows architecture. A developer reading the summary architecture Readme.MD is most likely to find a FAQ page on these components useful. 
=> docs(windows): link to wiki architecture faq page

developer/src/kmc/src/activities/BuildLdmlKeyboard.ts
Fixes #8512.
Note: the compile phase is identical to the validation phase at this point, so no need to run validate prior to compile:
https://github.com/keymanapp/keyman/blob/b34cdb9c8405eb0cb5a3803c16f7ceb4f6f92338/developer/src/kmc-keyboard/src/compiler/compiler.ts#L113-L121
=> fix(developer): kmc should not validate as well as compile keyboard

developer/src/kmc/src/commands/build.ts
Fixes #8508.
Now shows:
```
$ node . build does-not-exist.xml
Building does-not-exist.xml
File does-not-exist.xml does not exist
```
(Note, full error message cleanup and consolidation is a separate issue, part of #5283)
=> fix(developer): improve 'does not exist' error message

common/models/types/.build-builder, common/models/types/build.sh, common/web/keyman-version/build.sh, common/web/types/build.sh, developer/src/kmc-keyboard/build.sh, developer/src/kmc-kmn/build.sh, developer/src/kmc-model-info/build.sh, developer/src/kmc-model/build.sh, developer/src/kmc-model/package.json, developer/src/kmc-package/build.sh, developer/src/kmc/build.sh, docs/npm-packages.md, resources/build/build-utils-ci.inc.sh
Fixes #8586.
Fixes #7310.
Four fixes all centred around npm publish:
* Sets dependency versions when publishing npm packages
* All npm publish actions in the repository are now run as part of the Developer release build, hosted at present by kmc, until we setup a higher-level build script to do it.
* Adds a 'pack' action which mirrors 'publish' for all npm packages.
* Removes unnecessary dev dependencies of models-templates and models-wordbreakers from kmc-model.
The Web Release build CI step has been updated to check for presence of .build-builder for models-types.
=> fix(common): consolidate npm publishing

docs/build/linux-ubuntu.md
Updating the Linux dev environment to build Keyman for Android with Java 11.
I didn't update the underlying dependencies (core/web) from Windows --> Linux
=> docs(android): Update Linux dev environment for Java 11

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java, android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
Split out the following from #8608
> 1. Since our minimum SDK is 21 (Lollipop 5.0), this cleans up some of the logic checking for SDK version (always greater than KITKAT and never less than JELLY_BEAN_MR1)
=> chore(android/engine): Cleanup old SDK calls
