keymanapp/keyman

- common/include/km_types.h
- core/src/kmx/kmx_plus.cpp
- core/src/kmx/kmx_plus.h
- core/src/ldml/ldml_processor.cpp
- core/tests/unit/ldml/test_kmx_plus.cpp
fix breaks in #7111 and prior
#7098
> fix(core): fixes for kmx_file rearrangement 🙀

- core/src/kmx/kmx_plus.cpp
- core/src/kmx/kmx_plus.h
- core/src/ldml/ldml_processor.cpp
- core/src/ldml/ldml_processor.hpp
- core/tests/unit/ldml/002_null_invalid.xml
- core/tests/unit/ldml/ldml.cpp
- core/tests/unit/ldml/meson.build
- also update test case, 002_null_invalid is expected to not validate
#7097
> feat(core): ldml: validator for kmxplus 🙀

- linux/.pbuilderrc
- linux/scripts/cow.sh
- linux/scripts/launchpad.sh
And remove builds for outdated Impish.
(🍒-picked from #6975)
> chore(linux): Add support for Ubuntu 22.10 "Kinetic Kudu" 🍒

- core/src/ldml/ldml_processor.cpp
- allow keys section to exactly fit in data size, as in #7140
> fix(core): ldml: fix validator 🙀

- developer/src/kmldmlc/src/keyman/compiler/compiler.ts
- developer/src/kmldmlc/src/keyman/compiler/keys.ts
- developer/src/kmldmlc/src/keyman/compiler/loca.ts
- developer/src/kmldmlc/src/keyman/compiler/meta.ts
- developer/src/kmldmlc/src/keyman/compiler/section-compiler.ts
> refactor(developer): separate files for kmldmlc sections 🙀

- core/meson.build
- core/src/kmx/kmx_plus.h
- set -DDEBUG for 'debug' meson builds
- default KXPLUS_DEBUG  to 1 for -DDEBUG
#7136
Approach via https://stackoverflow.com/a/73546001/185799
> feat(core): set -DDEBUG for debug 🙀

- core/src/kmx/kmx_plus.cpp
- core/src/kmx/kmx_plus.h
- core/src/ldml/ldml_processor.cpp
> chore(core): split out validators 🙀

- developer/src/kmldmlc/test/fixtures/sections/name/minimal.xml
- developer/src/kmldmlc/test/fixtures/sections/name/multiple.xml
- developer/src/kmldmlc/test/test-name.ts
> feat(developer): add unit tests for 'name' compiler 🙀

- developer/src/kmldmlc/.gitignore
- developer/src/kmldmlc/package.json
- package-lock.json
Implements code coverage per question at https://github.com/keymanapp/keyman/pull/7203#pullrequestreview-1096827531.
- Pass threshold for lines is 90% coverage, which we just sneak over right now (that's my happy place).
- Reporter is just text for now (teamcity is an option, also consider if we want to do a PR comment in future)
> feat(developer): add nyc to kmldmlc for test coverage 🙀

- core/include/keyman/keyboardprocessor.h
> chore(core): fixup km_kbp_event docs

- core/build.sh
- developer/src/kmc/build.sh
- developer/src/kmc/test/helpers/index.ts
> chore(developer): kmc - use local reference for json schema 🙀

- common/windows/delphi/keyboards/kmxfile.pas
- core/src/kmx/kmx_file.cpp
- core/tests/unit/kmx/fixtures/binary/b_000_zero_checksum.kmn
- core/tests/unit/kmx/fixtures/binary/b_000_zero_checksum.txt
- core/tests/unit/kmx/fixtures/binary/meson.build
- core/tests/unit/kmx/fixtures/meson.build
- core/tests/unit/kmx/meson.build
- core/tests/unit/ldml/invalid-keyboards/meson.build
- core/tests/unit/ldml/meson.build
- core/tests/unit/meson.build
- developer/src/kmanalyze/kmanalyze.cpp
- developer/src/kmdecomp/kmdecomp.cpp
- mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMXFile.m
- windows/src/engine/keyman32/K32_load.cpp
- windows/src/engine/mcompile/mc_kmxfile.cpp
Fixes #7222.
Includes a unit test for zero checksum file (not produced by the compiler, so we have to manually generate it)
> chore: make checksum optional 🙀

- common/windows/delphi/setup/SFX.pas
Fixes #7261.
Low severity; no user test required. This should work for both Developer and Desktop. Note that there are other scenarios where the installer may run out of space which are not covered by this, such as downloading additional media, running Windows Installer, etc. But this should handle the obscure 'Stream write error' messsage better!
> fix(developer): show more useful error if out of space during Setup

- common/include/kmx_file.h
- core/src/kmx/kmx_file.cpp
- core/src/kmx/kmx_file_validator.hpp
- core/src/kmx/kmx_processevent.h
- core/src/ldml/ldml_processor.cpp
- move VerifyKeyboard into COMP_KEYBOARD::VerifyKeyboard
- change call sites in kmx_file.h
Fixes: #7220
> fix(core): VerifyKeyboard() on kmxplus files 🙀

- linux/ibus-keyman/src/engine.c
> chore(linux): Remove unused IBusLookupTable

- .github/multi-labeler.yml
- .github/workflows/labeler.yml
> chore: improve auto labeling

- .github/multi-labeler.yml
- .github/workflows/labeler.yml
> chore: improve auto labeling 🍒

- web/source/osk/banner.ts
A 🍒-pick of #7305.
The original PR's test should be enough due to how specific and highly-targeted this is, no?
Otherwise... I guess it's not much trouble to just copy its test here.
> fix(web): fixes unintended auto-acceptance of suggestion after reverting 🍒

- .github/labeler.yml
Cherry-pick of 39bca05 from #7299.
> chore(common): update auto labeler configuration 🍒

- resources/build/build-utils.sh
- resources/build/build-utils.test.sh
Cherry-picked from `feature-ldml`.
> chore(common): builder extra params support 🏗 🍒

- developer/src/kmc/src/kmc.ts
> fix(developer): kmc was overwriting kmx with kvk 🙀

- developer/src/tike/project/Keyman.Developer.System.Project.kpsProjectFile.pas
> fix(developer): handle invalid kps xml when loading project view

- linux/ibus-keyman/src/engine.c
Previously `process_unicode_char_action` checked for `action_item->character` being a surrogate. This should never happen because `action_item->character` is a 32-bit character. This change removes the unnecessary check and the `keyman->firstsurrogate` field.
Fixes #6385.
> chore(linux): Cleanup unnecessary surrogate check

- developer/src/tike/kmc.cmd
Fixes #7408.
Follow-up for #7413. Yes, I forgot to save one file...
> chore(developer): enable sourcemaps for kmc 🙀

- common/web/gesture-recognizer/build.sh
- common/web/gesture-recognizer/src/test/test.sh
> chore(web): feature-gesture builder script updates 🐵

- common/predictive-text/build.sh
- common/web/input-processor/build.sh
Rewrite of remaining new build.sh scripts will come in a subsequent PR.
> chore(common): fixup broken kmlmc script dependency 🙀

- core/src/kmx/kmx_xstring.h
- core/tests/unit/kmnkbd/test_kmx_xstring.cpp
> feat(core): kmx_xstring: New UTF-16 to UTF-32 function 🙀

- core/src/kmx/kmx_xstring.h
- core/src/ldml/ldml_processor.cpp
- core/tests/unit/kmnkbd/test_kmx_xstring.cpp
For: #7418
Co-authored-by: Eberhard Beilharz <ermshiperete@users.noreply.github.com>
includes suggestions from PR  https://github.com/keymanapp/keyman/pull/7403#discussion_r994256628
> fix(core): xstring/utf32 review feedback

- common/tools/hextobin/build.sh
- common/web/keyman-version/build.sh
- common/web/types/build.sh
- core/build.sh
- core/commands.inc.sh
- developer/src/kmc-keyboard/build.sh
- developer/src/kmc-model-info/build.sh
- developer/src/kmc-model/build.sh
- developer/src/kmc-package/build.sh
- developer/src/kmc/build.sh
See #7455 for additional work on these
> chore(common): update build.sh dependencies for epic-ldml 🙀

- docs/settings/README.md
- docs/settings/linux/.devcontainer/Dockerfile
- docs/settings/linux/.devcontainer/devcontainer.json
- linux/README.md
- add use of Dev Containers to sample settings
- update installation requirements in README.md
> docs(linux): Update readmes

- linux/scripts/upload-to-debian.sh
> fix(linux): Fix upload script

- docs/settings/linux/c_cpp_properties.json
- docs/settings/linux/extensions.json
- docs/settings/linux/settings.json
> docs(linux): Update sample vscode settings

- linux/ibus-keyman/src/engine.c
> refactor(linux): Cleanup whitespace

- linux/ibus-keyman/src/engine.c
> chore(linux): Improve debug output

- linux/ibus-keyman/src/engine.c
> refactor(linux): Comment unused methods

- android/help/about/whatsnew.md
- android/help/index.md
Just starting the ball rolling on Keyman for Android 16.0 release notes.
> chore(android): Update help whatsnew for 16.0

- configure-repo.sh
> chore(common): update configure-repo.sh to include pre-commit hook

- common/predictive-text/index.ts
- common/predictive-text/unit_tests/in_browser/cases/top-level-lmlayer.js
- common/predictive-text/unit_tests/in_browser/cases/worker-dummy-integration.js
- common/predictive-text/unit_tests/in_browser/cases/worker-trie-integration.js
- common/web/lm-worker/src/index.ts
- common/web/lm-worker/src/model-compositor.ts
- common/web/lm-worker/src/worker-interfaces.ts
> change(common/models): prevent integration test flakiness due to prediction-search timeouts

- windows/src/developer/TIKE/child/UfrmDebug.pas
Fixes #7529.
Cherry-pick of #7531.
We must always use the US base layout for the debugger, as positional keyboards are not affected by the active Windows system keyboard. This fix ensures that the behaviour in the debugger matches what the user experiences in Keyman for Windows.
Note that this does not address support for mnemonic layouts, tracked in issue #1074.
> fix(developer): Use US base layout for debugger 🍒

- developer/src/tike/child/UfrmPackageEditor.pas
Fixes #6974.
GIF images were not supported in the Details tab, Image file, because we didn't link in GIF file support. After linking it in, we also needed to change over the picture rendering to have an intermediate render step, as the existing model only worked with .bmp images.
At the same time, added warnings for wrongly-sized images to the image size information.
**TEST_IMAGE_FILE:** Load various keyboard packages that includes a splash image, such as khmer_angkor, or any of the keyboards below from the keyboards repository. Verify that the image displays correctly and that size information is presented helpfully. Try and test at least one of each of .png, .gif, .jpg, and .bmp formats.
```
experimental\k\koreguaje\source\koreguaje.kps:  default.png …
```
> fix(developer): support gif preview images in Package Editor

- core/include/ldml/ldml-const-builder.ts
- core/include/ldml/tsconfig.build.json
- fix config
- Add .js to the import statement (not a great fix)
Fixes #7566
( but dont' worry bot, i'm sure i'll have plenty for you soon…)
> fix(core): move ldml const builder to es modules 🙀

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
> fix(android/app): Add check if bundle to PackageActivity is null

- core/src/kmx/kmx_plus.cpp
- minor cleanup in the .cpp
#5015
> chore(core): ldml: cleanup   🙀

- common/web/types/src/ldml-keyboard/ldml-keyboard-xml.ts
- developer/src/kmc-keyboard/src/compiler/keys.ts
- developer/src/kmc-keyboard/src/compiler/messages.ts
- developer/src/kmc-keyboard/test/fixtures/sections/keys/gap-switch.xml
- developer/src/kmc-keyboard/test/fixtures/sections/keys/invalid-key-missing-attrs.xml
- developer/src/kmc-keyboard/test/test-keys.ts
- keys: error if to, gap, AND switch are missing
- add parts to LKKey
- add err message and test case
Somehow part of #7401 
> feat(developer): improve validation and gap/switch handling  🙀

- developer/src/tike/child/Keyman.Developer.UI.UfrmModelEditor.dfm
- developer/src/tike/child/UfrmPackageEditor.dfm
> fix(developer): tweak captions for consistency

- developer/src/tike/http/Keyman.Developer.UI.ServerUI.pas
- developer/src/tike/project/Keyman.Developer.System.Project.WelcomeRenderer.pas
> chore(developer): tidy up compile hints

- developer/src/tike/main/UframeTextEditor.pas
> fix(developer): handle EEncodingError loading text file

- common/windows/delphi/charmap/UfrmCharacterMapNew.pas
Fixes #7639.
It appears that components within a docking form are unable to be focused in some, rare contexts. We don't want to crash, and the end result of not focusing is not really all that tragic, so let's just mask the exception.
> fix(developer): prevent exception in charmap when unable to focus

- web/source/osk/browser/pendingMultiTap.ts
> fix(web): Handle undefined keyId in multi-tap

- linux/help/about/whatsnew.md
Just updating whatsnew for Keyman for Linux
> chore(linux): Update whatsnew

- docs/history-and-versioning.md
Just tweaking history-and-verisoning.md to match the HISTORY.md format since 14.0
> chore: Update history-and-versioning to match history

- linux/debian/changelog
(:cherries:-picked from PR #7680)
> chore(linux): Update debian changelog :cherries:

- android/KMAPro/kMAPro/build.gradle
Follow-on to #7674 
> Did you do this?
I forgot to cleanup debugging code before merging 😞 
> chore(android/app): Remove debugging info on build.gradle

- TIER.md
> chore: fix TIER.md for master

- windows/src/desktop/kmshell/install/Keyman.Configuration.UI.KeymanProtocolHandler.pas
Fixes #7708.
Fixes [KEYMAN-WINDOWS-1VP](https://sentry.io/organizations/keyman/issues/3555212554/events/24f26bf8f16943cc809d195fe9a52f34/?project=5983518).
> fix(windows): handle timeout in downloads

- windows/src/engine/keyman/keyman.dproj
Same as #7600, but for keyman.dpr.
> chore(windows): include debug info in keyman build

- core/src/ldml/C7043_ldml.md
- add layers, rows, display
This is a draft, feedback appreciated…
Note that I use `.x` in the numbering for the new sections, will renumber if these are accepted
for #7532 
> feat(core): ldml: add `layr`, `disp`, `key2`, `list` sections to C7043.1 spec 🙀

- core/src/mock/mock_processor.cpp
- windows/src/engine/keyman32/keyman-engine.vcxproj
- windows/src/engine/keyman32/keyman-engine.vcxproj.filters
- windows/src/engine/keyman32/tests/keyman-engine-tests/keyboardoptionstests.cpp
This is just a simple test for SetupCoreEnvironment.  Now actually covered by the keyman developer test.
> chore(windows): add unit test for SetupCoreEnvironment

- .github/ISSUE_TEMPLATE/config.yml
> chore: github issue template config.yml

- common/windows/delphi/ext/sentry/Sentry.Client.pas
This is deliberately pushed to 17.0 alpha.
> chore(windows): tweak sentry client for cross-module messages

- resources/build/increment-version.sh
- resources/build/version/src/fixupHistory.ts
- resources/build/version/src/index.ts
Fixes #7278.
This will need a cherry-pick to beta, once approved, so we get the benefit for stable-16.0.
> fix: automatically merge changes to history back to master

- resources/build/increment-version.sh
- resources/build/version/src/fixupHistory.ts
- resources/build/version/src/index.ts
Cherry-pick of #7777.
Fixes #7351.
> fix: automatically merge changes to history back to master 🍒

- common/web/types/src/kmx/kmx-plus.ts
- common/web/types/src/kmx/string-list.ts
- core/src/ldml/C7043_ldml.md
- core/src/ldml/C7532_ldml_updating.md
- developer/src/kmc-keyboard/src/compiler/compiler.ts
- developer/src/kmc-keyboard/src/compiler/key2.ts
- developer/src/kmc-keyboard/test/fixtures/sections/key2/maximal.xml
- developer/src/kmc-keyboard/test/helpers/index.ts
- developer/src/kmc-keyboard/test/test-key2.ts
> ~WIP Key2~

- linux/ibus-keyman/configure.ac
> chore(linux): Update autotools configuration

- web/source/osk/oskView.ts
- web/source/text/prediction/modelManager.ts
Fixes a couple of recent unit test issues.
> fix(web): unit test breakages

- linux/scripts/upload-to-debian.sh
While we're in beta phase we need to modify `changelog` in beta branch instead of `master`.
> chore(linux): Fix upload-to-debian script

- android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java
🍒 pick of #7844 to stable-15.0 
It may be another week till 16.0 gets released, so this prevents keyboard updates from crashing on Android S+ devices.
Setup - For each group, use the Android device, orientation, and Android OS as specified in the group. Do **not** install Keyman for Android until instructed in Setup step
1. On the device, download the old version [1.0 of sil_nko Keyman keyboard](https://downloads.keyman.com/keyboards/sil_nko/1.0/sil_nko.kmp)
2. On the device, turn on airplane mode (sets device offline)
3. On the device Settings, manually set the date/time to 1 year  past (~Oct 2021)
4. Install the PR build of Keyman for Android
5. Launch Keyman for Android
6. From Keyman Settings, install the old version of sil_nko from local file. (Install for "Mandingo" language)
7. …
> fix(android/engine): Use FLAG_IMMUTABLE for PendingIntent for Android S+ 🍒

- linux/Jenkinsfile
- linux/scripts/cow.sh
- linux/scripts/launchpad.sh
> chore(linux): Remove building for Bionic

- linux/scripts/cow.sh
> chore(linux): Remove some shellcheck warnings

- docs/settings/linux/c_cpp_properties.json
- docs/settings/linux/extensions.json
- docs/settings/linux/settings.json
- docs/settings/linux/tasks.json
> chore(linux): Update vscode settings for Linux

- linux/ibus-keyman/tests/ibusimcontext.c
This change adds the upstream changes to ibusimcontext.c to our test ibusimcontext.c file up to commit
https://github.com/ibus/ibus/commit/506ac9993d5166196b7c4e9bfa9fb0f9d3792ffa plus [our two prefilter commits](https://github.com/ibus/ibus/pull/2440).
> refactor(linux): Update ibusimcontext.c

- linux/keyman-config/setup.py
> chore(linux): Fix `make install`

- resources/build/run-required-test-builds.sh
- resources/build/trigger-builds.inc.sh
> chore(common): Fix shellcheck warnings

- resources/build/run-required-test-builds.sh
- resources/build/trigger-builds.inc.sh
Reverts keymanapp/keyman#7910.
See https://github.com/keymanapp/keyman/pull/7910#issuecomment-1356867900 for details. Opting to revert all changes and we can try again if it seems important, with more checks on the build outcomes.
> chore: Revert "chore(common): Fix shellcheck warnings"

- docs/websites/README.md
Action item from the Keyman December planning meetings was to capture the info from our evening Docker-fest into a README.md
> chore(common/resources): Add Docker readme

- common/web/types/src/kvk/kvk-file-writer.ts
- kvk processor should skip keys with no source text
For #7842
> fix(common): ldml: kvk should skip empty keys 🙀

- linux/keyman-config/km-config.bash-completion
- linux/keyman-config/km-kvk2ldml.bash-completion
- linux/keyman-config/km-package-get.bash-completion
- linux/keyman-config/km-package-install.bash-completion
- linux/keyman-config/km-package-list-installed.bash-completion
- linux/keyman-config/km-package-uninstall.bash-completion
> chore(linux): Refactor completion script

- docs/settings/linux/extensions.json
- docs/settings/linux/launch.json
- docs/settings/linux/tasks.json
> chore(linux): Update sample settings

- core/src/kmx/kmx_plus.cpp
- core/src/ldml/ldml_processor.cpp
- found a logic bug in kmx_plus.cpp
Fixes #7984
> fix(core): ldml: add asserts to C++ 🙀

- resources/build/increment-version.sh
> chore: git tag with release@semver

- docs/websites/README.md
This updates the Docker readme to reflect the changes to the `build.sh configure` step from keymanapp/help.keyman.com#681 and keymanapp/keymanweb.com#63
> docs(common/resources): Update configure step in Docker readme

- linux/ibus-keyman/src/engine.c
- linux/ibus-keyman/src/kmpdetails.c
- linux/ibus-keyman/src/print_kmp.c
- linux/ibus-keyman/tests/ibusimcontext.c
- linux/ibus-keyman/tests/testfixture.cpp
- linux/ibus-keyman/tests/testmodule.c
- linux/ibus-keyman/tests/testmodule.h
This warnings showed up when building with Meson.
> chore(linux): Fix warnings

- linux/debian/changelog
- linux/debian/control
Specify the path to the Debian package in the Vcs-Git header
> Specify the path to the Debian package in the Vcs-Git header

- linux/debian/changelog
- linux/debian/control
> chore(linux): Include packaging path in Vcs-Git header 🍒

- HISTORY.md
> chore(common): stable 16.0 history

- resources/build/trigger-definitions.inc.sh
> chore: add new developer build trigger

- developer/src/kmc-keyboard/src/compiler/key2.ts
- developer/src/kmc-keyboard/src/compiler/keys.ts
- developer/src/kmc-keyboard/src/util/util.ts
- developer/src/kmc-keyboard/test/test-base.ts
- developer/src/kmc-keyboard/test/test-utils.ts
- move some shared code out of key2/keys and into util.ts
- add unit tests
- delete a null test-base.ts
For: #8069
> fix(developer): todo cleanup, common code, tests  🙀

- common/web/types/package.json
- common/web/types/src/kvk/kvk-file-writer.ts
- common/web/types/src/kvk/visual-keyboard.ts
- common/web/types/test/kvk/test-kvk-round-trip.ts
- common/web/types/test/ldml-keyboard/test-ldml-keyboard-xml-reader.ts
- package-lock.json
- use hexy and git-diff to show a rich diff when files are changed
- add additional round trip tests
- initialize the underlyingLayout to undefined to promote round tripping
- fix an issue with the CompilerCallbacks in the xml tests (broken in #8107)
- fix an issue with the kvk file writer where it should set strings irregardless (#7955)
Fixes #7967, again
Learning a bit about kvk…
> fix(common): make common/web/types kvk tests pass 🙀

- resources/build/trigger-builds.inc.sh
> chore: Fail TC build if triggering Jenkins build fails

- resources/build/trigger-builds.inc.sh
> chore: Fail TC build if triggering Jenkins build fails 🍒

- common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts
- common/web/types/src/main.ts
- common/web/types/src/util/common-events.ts
- common/web/types/src/util/compiler-interfaces.ts
- common/web/types/test/ldml-keyboard/test-ldml-keyboard-xml-reader.ts
- developer/src/kmc-keyboard/src/compiler/compiler.ts
- developer/src/kmc-keyboard/src/compiler/messages.ts
- developer/src/kmc-keyboard/src/main.ts
- developer/src/kmc-keyboard/test/helpers/index.ts
- developer/src/kmc-keyboard/test/test-layr.ts
- developer/src/kmc-keyboard/test/test-messages.ts
- more refactor into common/web/types
- refactor test harness
- move throw into Errors
For: #7534 / #7964
> feat(common): ldml: error messages from the compiler   🙀

- ios/exportAppStore.plist
> chore(ios): update certificate

- ios/exportAppStore.plist
> chore(ios): update certificate 🍒

- common/predictive-text/build.sh
- common/predictive-text/unit_tests/test.sh
- common/web/input-processor/build.sh
- common/web/keyboard-processor/build.sh
- resources/build/build-utils.md
- resources/builder.inc.sh
- web/build.sh
- web/test.sh
Adds `builder_term` and updates relevant references.
> chore(common): add `builder_term` function

- linux/debian/changelog
> chore(linux): Update changelog from Debian 🍒

- linux/debian/changelog
- linux/debian/tests/README.md
- linux/debian/tests/test-build
> fix(linux): Fix autopkgtests

- linux/debian/changelog
- linux/debian/tests/README.md
- linux/debian/tests/test-build
> fix(linux): Fix autopkgtests 🍒

- .github/workflows/deb-packaging.yml
- resources/build/trigger-builds.inc.sh
> fix(linux): Fix Verify-API step of GHA

- docs/linux/packaging.md
- remove obsolete `packageName` variable
- add section on how to build with Docker, similar to how the package build is done on GHA
- updated "uploading to Debian" section
- some reformatting
> docs(linux): Update packaging documentation

- .github/workflows/deb-packaging.yml
- resources/build/trigger-builds.inc.sh
This allows to see which GHA build ran on which branch/PR.
> feat(linux): Pass PR# in the event type

- .github/workflows/deb-packaging.yml
> feat(linux): Implement uploading of packages in packaging GHA

- resources/build/trigger-builds.inc.sh
> fix(linux): Fix GHA package build

- .github/workflows/deb-packaging.yml
- resources/build/trigger-builds.inc.sh
> fix(linux): Another fix for GHA package build

- core/src/kmx/kmx_plus.cpp
- core/src/kmx/kmx_plus.h
- need helper objs still
For: #7985
> feat(core): ldml C++ validate list / key2  🙀

- .github/workflows/deb-packaging.yml
> fix(linux): Another iteration to fix packaging GHA

- common/web/types/build.sh
- common/web/types/src/ldml-keyboard/ldml-keyboard-testdata-xml.ts
- common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts
- common/web/types/src/main.ts
- common/web/types/src/util/common-events.ts
- common/web/types/src/util/compiler-interfaces.ts
- common/web/types/test/fixtures/test-fr.xml
- common/web/types/test/helpers/index.ts
- common/web/types/test/helpers/reader-callback-test.ts
- common/web/types/test/ldml-keyboard/test-ldml-keyboard-testdata-reader.ts
- core/tests/unit/ldml/keyboards/k_001_tiny-test.xml
- core/tests/unit/ldml/keyboards/meson.build
- developer/src/kmc-keyboard/build.sh
- developer/src/kmc-keyboard/src/compiler/compiler.ts
- developer/src/kmc-keyboard/test/fixtures/test-fr.json
- developer/src/kmc-keyboard/test/fixtures/test-fr.xml
- developer/src/kmc-keyboard/test/helpers/index.ts
- developer/src/kmc-keyboard/test/test-testdata-e2e.ts
- developer/src/kmc/build.sh
- developer/src/kmc/src/kmc.ts
- early scaffolding
- with some basic tests
#7535
> feat(common): ldml read keyboard testdata 🙀

- core/src/kmx/kmx_plus.cpp
- core/src/kmx/kmx_plus.h
> feat(core): ldml C++ helper for list / key2  🙀

- developer/src/kmc-keyboard/build.sh
> fix(developer): always copy schemas during build

- web/test.sh
> chore(web): Actually skip browser-stack for non-web builds

- linux/scripts/upload-to-debian.sh
> chore(linux): Create draft PR after updating changelog

- developer/src/inst/node/dist/CHANGELOG.md
- developer/src/inst/node/dist/Keyman_README.md
- developer/src/inst/node/dist/LICENSE
- developer/src/inst/node/dist/README.md
> chore(developer): update bundled node to 18.14.1 LTS

- resources/build/build-utils.md
- resources/builder.inc.sh
> docs: builder.inc.sh improved documentation around dependencies

- .github/workflows/deb-packaging.yml
> fix(linux): Fix paths in upload action of packaging GHA

- core/build.bat
Fixes #8076.
This page was helpful: https://renenyffenegger.ch/notes/development/tools/scripts/personal/vsenv_bat
> chore: move from vcvarsall.bat to vsdevcmd.bat

- .github/workflows/deb-packaging.yml
Missed a fairly important step :-).
> fix(linux): Fix upload in packaging GHA

- developer/src/kmc-package/src/kmp-compiler.ts
- developer/src/kmc/src/activities/buildKmnKeyboard.ts
- developer/src/kmc/src/activities/buildLdmlKeyboard.ts
- developer/src/kmc/src/activities/buildPackage.ts
- developer/src/kmc/src/commands/build.ts
- developer/src/kmc/src/kmc.ts
Adds basic support for compiling .kps files using kmc-package to kmc.
> feat(developer): kmc compile .kps files 🙀

- developer/src/kmc/src/activities/buildModel.ts
- developer/src/kmc/src/commands/build.ts
Adds basic support for compiling .model.ts files using kmc-model to kmc.
> feat(developer): kmc compile .model.ts file 🙀

- core/src/ldml/ldml_processor.hpp
- developer/src/kmc-keyboard/src/compiler/keys.ts
- developer/src/kmc-keyboard/src/compiler/messages.ts
- developer/src/kmc-keyboard/test/fixtures/sections/keys/invalid-missing-flick.xml
- developer/src/kmc-keyboard/test/test-keys.ts
- add check for missing flicks
- remove a tray #include
chore(common): ldml TODO-LDML cleanup 🙀  #8069
> fix(developer): ldml TODO-LDML cleanup 🙀

- linux/debian/rules
> chore(linux): disable core tests for build 🙀

- .github/workflows/deb-packaging.yml
- linux/scripts/deb.sh
- add trust for GPG key
- set release for source package
> chore(linux): Improve and fix packaging GHA

- linux/debian/rules
cf #8331, #8333
Starting to feel a bit repetitive...
> chore(linux): disable tests for core install also

- .github/workflows/deb-packaging.yml
> chore(linux): More debug output

- resources/build/npm-publish.inc.sh
> fix(common): fixup npm publish

- developer/src/kmcmplib/build.sh
- developer/src/kmcmplib/commands.inc.sh
> chore(developer): cleanup kmcompx build scripts per recent builder changes

- .github/workflows/deb-packaging.yml
> chore(linux): More GHA debugging

- .github/workflows/deb-packaging.yml
> chore(linux): Remove debug output from packaging GHA

- common/windows/cpp/include/legacy_kmx_file.h
- developer/src/kmcmpdll/Compiler.cpp
- developer/src/kmcmpdll/json-validation.cpp
- developer/src/kmcmplib/src/Compiler.cpp
- developer/src/kmcmplib/src/json-validation.cpp
> refactor(developer): kmcmplib json-validation.cpp remove windowsisms

- developer/src/kmcmplib/src/meson.build
- developer/src/kmcmplib/tests/meson.build
> chore(developer): remove unused version library reference

- developer/src/kmcmplib/build.sh
> chore(developer): kmcmplib breadth-first-build 🚑

- resources/builder.inc.sh
> chore(common): support shorthand for build.sh

- common/web/types/test/helpers/reader-callback-test.ts
- common/web/types/test/kpj/test-kpj-file-reader.ts
> fix(common): fix broken common/web/types cases 🙀

- common/web/types/test/helpers/reader-callback-test.ts
- core/src/kmx/kmx_plus.cpp
- core/src/ldml/C7043_ldml.md
- core/tests/unit/ldml/ldml_test_source.cpp
- core/tests/unit/ldml/ldml_test_source.hpp
- drop some TODO-LDMLs
- document others
> fix(core): ldml more TODO-LDML fixes 🙀

- docs/settings/linux/tasks.json
- linux/ibus-keyman/build.sh
> chore(linux): Use dependency on core in ibus-keyman/build.sh

- common/predictive-text/unit_tests/test.sh
> chore(common): die early when --ci and --debug passed to test.sh

- core/build.sh
- core/commands.inc.sh
- resources/build/build-utils.md
- resources/builder.inc.sh
> chore(common): define BUILDER_CONFIGURATION env var

- linux/debian/changelog
- linux/debian/tests/control
- linux/debian/tests/test-build
This reverts commit 468bb37ddfa12f8bf00c0f006fd936c5ba025f9a (PR #8492).
(🍒-picked from PR #8505)
> chore(linux): Revert "Run and ignore autopkgtests on s390x" 🍒

- docs/build/linux-ubuntu.md
> docs(linux): Update minimum required Ubuntu version

- linux/ibus-keyman/tests/scripts/run-tests.sh
- linux/ibus-keyman/tests/scripts/setup-tests.sh
> chore(linux): Improve robustness of test cleanup

- resources/build/build-utils.md
> docs: clarify dependency meanings in build-utils

- developer/src/kmc/src/commands/build.ts
> chore(developer): tweak build of extension list in kmc

- developer/src/kmc-keyboard/package.json
- developer/src/kmc/package.json
> fix(developer): add missing dependencies

- developer/src/kmc/src/activities/BuildActivity.ts
- developer/src/kmc/src/activities/BuildKmnKeyboard.ts
- developer/src/kmc/src/activities/BuildLdmlKeyboard.ts
- developer/src/kmc/src/activities/BuildModel.ts
- developer/src/kmc/src/activities/BuildPackage.ts
- developer/src/kmc/src/activities/BuildProject.ts
- developer/src/kmc/src/util/escapeRegExp.ts
> fix(developer): kmc no longer emits double file extension for models

- android/KMAPro/kMAPro/src/main/res/values-zh-rCN/strings.xml
- mac/Keyman4MacIM/Keyman4MacIM/zh-Hans.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/zh-CN/strings.xml
- windows/src/desktop/setup/locale/zh-CN/strings.xml
Updating crowdin strings for Simplified Chinese (zh-CN).
> chore(common): Update crowdin strings for Simplified Chinese

- common/web/types/src/consts/virtual-key-constants.ts
> fix(developer): kmc: fix jis/abnt2 scan codes 🙀

- common/windows/delphi/packages/PackageInfo.pas
Fixes #8595.
Cherry-pick of #8606.
> fix(developer): package editor no longer loses RTL flag for LMs 🍒

- developer/src/ext/json-schema-validator/json-validator.cpp
- developer/src/kmcmplib/include/kmcompx.h
- developer/src/kmcmplib/src/Compiler.cpp
- developer/src/kmcmplib/src/NamedCodeConstants.cpp
- developer/src/kmcmplib/src/kmx_u16.cpp
- developer/src/kmcmplib/src/versioning.cpp
- developer/src/kmcmplib/tests/api-test.cpp
- failing build on XCode
- fix sprintf, tmpnam, others
Fixes: #8688
> fix(developer): warning fixes in kmcmplib 🙀 

- docs/build/windows.md
Verify the build tools for  VS 2019 c++ x64/x86 are installed.
> docs(windows): Add verify vs build tools

- .github/workflows/deb-packaging.yml
- linux/Jenkinsfile
Add building and upload to llso/pso now that this is possible.
> chore(linux): Build for Lunar on all platforms

- common/test/keyboards/.gitignore
- linux/debian/rules
- linux/ibus-keyman/src/kmpdetails.c
- linux/ibus-keyman/tests/meson.build
- linux/ibus-keyman/tests/scripts/run-single-test.sh
- linux/ibus-keyman/tests/scripts/run-tests.sh
- linux/ibus-keyman/tests/scripts/setup-tests.sh
- linux/ibus-keyman/tests/scripts/teardown-tests.sh
- linux/ibus-keyman/tests/scripts/test-helper.sh
> fix(linux): Fix linux tests

- linux/scripts/launchpad.sh
- linux/scripts/package-build.inc.sh
This fixes some uninitialized variables.
> chore(linux): Fix uploading to launchpad

- linux/ibus-keyman/tests/scripts/setup-tests.sh
- linux/ibus-keyman/tests/scripts/test-helper.sh
> chore(linux): bring kmp.json for unit test up to spec

- android/KMAPro/kMAPro/src/main/res/values-am-rET/strings.xml
- android/KMEA/app/src/main/res/values-am-rET/strings.xml
- mac/Keyman4MacIM/Keyman4MacIM/am.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/am-ET/strings.xml
- windows/src/desktop/setup/locale/am-ET/strings.xml
End of sprint task updating crowdin strings for Amharic (am).
> chore(common): Update crowdin strings for Amharic

- developer/src/kmc-package/src/compiler/messages.ts
- developer/src/kmc-package/src/compiler/package-validation.ts
- developer/src/kmc-package/test/fixtures/invalid/warn_file_in_package_does_not_follow_filename_conventions.kps
- developer/src/kmc-package/test/fixtures/invalid/warn_file_in_package_does_not_follow_filename_conventions_2.kps
- developer/src/kmc-package/test/test-package-compiler.ts
> feat(developer): validate content file names in packages

- developer/src/kmc-package/src/compiler/messages.ts
- developer/src/kmc-package/src/compiler/package-validation.ts
- developer/src/kmc-package/test/fixtures/invalid/error_package_name_cannot_be_blank.kps
- developer/src/kmc-package/test/fixtures/invalid/error_package_name_cannot_be_blank_2.kps
- developer/src/kmc-package/test/fixtures/invalid/error_package_name_cannot_be_blank_3.kps
- developer/src/kmc-package/test/test-package-compiler.ts
> feat(developer): validate package name in compiler

- windows/src/support/texteditor/Makefile
> fix(windows): add wrap-symbols to Text Editor Makefile

- resources/builder.inc.sh
> fix(common): ensure child builds don't rebuild dependencies unnecessarily

- android/README.md
- docs/build/linux-ubuntu.md
Some small changes to dev documentation with additional info that I found out while trying to get Android to build on my Linux machine.
> docs(android): Update documentation for building Android on Linux

- resources/build/build-utils.sh
> fix(android): Fix typo in build-utils.sh

- developer/src/kmcmplib/src/CompilerInterfaces.cpp
Fixes #8853.
The `SetError` macro emitted `return FALSE;` which was confusing for reviewing code flow. Replaced with explicit `AddCompileMessage()` and `return FALSE;`.
> chore(developer): remove SetError macro

- linux/debian/rules
- linux/keyman-config/Makefile
- linux/keyman-config/build.sh
- linux/keyman-config/run-tests.sh
- linux/keyman-config/tests/test_gnome_keyboards_util.py
- linux/keyman-config/tests/test_install_kmp.py
- linux/keyman-config/tests/test_package_install_completion.py
- linux/scripts/install.sh
- linux/scripts/package-build.inc.sh
- linux/scripts/reconf.sh
> chore(linux): Move build steps to build.sh

- oem/firstvoices/ios/exportAppStore.plist
Note: wait for install of cert on build agents before merging.
> chore(ios): replace fv cert

- linux/keyman-config/keyman_config/view_installed.py
Follow-up of #8631 where I forgot to add one of the changed files.
> feat(linux): Rename column and add tooltip

- oem/firstvoices/ios/exportAppStore.plist
> chore(ios): replace fv cert 🍒

- core/doc/hotdoc.json
- core/doc/meson.build
- core/include/keyman/keyboardprocessor.h
:cherries:-pick of #8912 
Partially fixes #8880 (part A).
> fix(core): Fix compilation if hotdoc is installed :cherries: 

- core/commands.inc.sh
- developer/src/kmcmplib/commands.inc.sh
- resources/locate_emscripten.inc.sh
Relates to #8913.
@ermshiperete, can you verify that the shellcheck directive does what we want here for SC2148?
> chore(core): look for emcc.py, not emcc

- web/src/tools/testing/bulk_rendering/build-bundler.js
- web/src/tools/testing/bulk_rendering/build.sh
- web/src/tools/testing/bulk_rendering/renderer_core.ts
- web/src/tools/testing/bulk_rendering/tsconfig.json
This tool turned out to be relatively simple to update to a modularized form, fortunately.
> fix(web): restores bulk_rendering tool 🧩

- common/tools/hextobin/hextobin.ts
- common/tools/hextobin/index.ts
- developer/src/kmc-ldml/test/fixtures/basic.txt
- developer/src/kmc-ldml/test/test-compiler-e2e.ts
- re-enable e2e
- fix basic.txt to match
tools (hextobin):
- support diff(block1,block2,divisor)
- document the comma rule
For: https://github.com/keymanapp/keyman/issues/7377
> feat(developer): fix e2e test 🙀

- developer/src/kmc-analyze/src/osk-character-use/index.ts
> chore(developer): prevent recursion when analyzing projects 🗜

- common/web/types/src/main.ts
- developer/src/kmc-analyze/src/osk-character-use/index.ts
- developer/src/kmc-kmn/src/main.ts
- developer/src/kmc/src/commands/analyze.ts
> chore(developer): complete error checking in kmc-analyze 🗜

- resources/build/help-keyman-com.sh
Fixes [help.keyman.com #725](https://github.com/keymanapp/help.keyman.com/issues/725).
> fix(linux): Fix creation of markdown help files for Linux

- developer/src/kmc-kmn/src/main.ts
> chore(developer): fixup merge bump 🗜

- common/web/types/src/main.ts
- common/web/types/src/osk/osk.ts
- developer/src/kmc-analyze/src/index.ts
- developer/src/kmc-analyze/src/osk-character-use/index.ts
- developer/src/kmc-analyze/src/osk-rewrite-pua/index.ts
- developer/src/kmc-analyze/src/util/get-osk-from-kmn-file.ts
- developer/src/kmc/src/commands/analyze.ts
- developer/src/kmc/src/commands/build.ts
- developer/src/kmc/src/commands/buildTestData.ts
- developer/src/kmc/src/kmc.ts
- developer/src/kmc/src/messages/messages.ts
- developer/src/kmc/src/util/baseOptions.ts
- developer/src/kmc/src/util/projectReader.ts
This continues the osk-font-use tooling related to dotted circle issues. Now generates a file that can be used by https://github.com/silnrsi/palaso-python/blob/master/scripts/font/ttkbdfont.py to generate a .ttf.
> feat(developer): support to rewrite kvk and touch layout with pua 🗜

- common/web/types/build.sh
- common/web/types/src/osk/osk.ts
- common/web/types/src/util/compiler-interfaces.ts
- developer/src/inst/download.in.mak
- developer/src/kmc-analyze/src/osk-rewrite-pua/index.ts
- developer/src/kmc-kmn/src/compiler/compiler.ts
- developer/src/kmc/build.sh
> chore(developer): validate displaymap schema 🗜

- windows/src/engine/testhost/README.md
Just adding some extra steps to the testhost readme. 
> docs(windows): add more steps for clarity

- common/web/types/package.json
- common/web/types/src/keyman-touch-layout/keyman-touch-layout-file-reader.ts
- common/web/types/test/helpers/TestCompilerCallbacks.ts
> chore(common): fixup tests for common/web/ci 🗜

- developer/src/kmc-kmn/src/compiler/compiler.ts
Improves performance, and also resolves warning from node:
```
(node:21032) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```
I noticed this while doing tests for kmc-kmn.
> chore(developer): load wasm module only once per process 🗜

- mac/help/about/requirements.md
> docs(mac): Update requirements.md

- developer/src/kmc-kmn/src/compiler/compiler.ts
Fixes #9125.
Running kmc on a set of keyboards would sporadically fail after some time. It turns out this was related to memory allocation, specifically, resizing the WASM module's memory buffer caused `TypedArray` views into the memory to be reset!
By default, when a `Uint8Array` is created from an `ArrayBuffer` (e.g. `Module.HEAP8.buffer`), it is a dynamic view into that buffer. This module buffer can be dynamically reallocated at any time, which can happen when allocating memory in WASM code (so the change will look _really_ weird in a stack trace). Thus, to ensure we don't trip over ourselves, we need to copy the buffer. Fortunately, creating a `Uint8Array` from a `Uint8Array` copies the data, and is pretty quick.
> fix(developer): kmcmplib was clobbering previous output 🗜

- .github/workflows/deb-packaging.yml
> fix(linux): Fix GHA package builds for non-Jammy dists

- developer/src/kmc-kmn/src/compiler/compiler.ts
> fix(developer): strip .kvk extension 🗜

- .github/workflows/deb-packaging.yml
Next iteration of fixing packaging GHA.
> fix(linux): Fix packaging GHA

- linux/keyman-config/keyman_config/gnome_keyboards_util.py
- linux/keyman-config/keyman_config/gsettings.py
- linux/keyman-config/keyman_config/ibus_util.py
> refactor(linux): Code refactoring

- linux/keyman-config/keyman_config/keyboard_details.py
> refactor(linux): Extract methods

- developer/src/kmc-ldml/src/compiler/compiler.ts
- developer/src/kmc-ldml/src/compiler/disp.ts
- developer/src/kmc-ldml/src/compiler/keys.ts
- skip coverage on some actual internal errors
- add todos where coverage is needed
for: #8069
> fix(developer): improve coverage, add todos 🙀

- common/web/types/src/ldml-keyboard/pattern-parser.ts
- common/web/types/src/util/util.ts
- common/web/types/test/ldml-keyboard/test-pattern-parser.ts
- common/web/types/test/util/test-unescape.ts
- developer/src/kmc-ldml/src/compiler/compiler-options.ts
- developer/src/kmc-ldml/src/compiler/compiler.ts
- developer/src/kmc-ldml/src/compiler/keys.ts
- developer/src/kmc-ldml/src/compiler/layr.ts
- developer/src/kmc-ldml/src/compiler/loca.ts
- developer/src/kmc-ldml/src/compiler/section-compiler.ts
- developer/src/kmc-ldml/src/compiler/tran.ts
- developer/src/kmc-ldml/src/compiler/vkey.ts
- developer/src/kmc-ldml/test/fixtures/sections/vars/fail-badref-6.xml
- developer/src/kmc-ldml/test/test-compiler-e2e.ts
- developer/src/kmc-ldml/test/test-layr.ts
- developer/src/kmc-ldml/test/test-vars.ts
- remove SectionCompiler.required as unused
- remove other unused functions
- minor fixes to common setSplitter
- add edge case tests
for: #8069
> chore(common): improve coverage, fix todos 🙀

- android/KMAPro/kMAPro/src/main/res/values-ckl-rNG/strings.xml
- mac/Keyman4MacIM/Keyman4MacIM/ckl.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/ckl-NG/strings.xml
End of sprint task for updating crowdin strings for Kibaku (ckl).
> chore(common): Update crowdin strings for Kibaku

- resources/build/run-required-test-builds.sh
> chore: authenticate github request when triggering test builds

- common/windows/delphi/Makefile
- common/windows/delphi/tools/build_standards_data/Keyman.System.BuildLangTags.pas
- linux/keyman-config/tests/test_canonical_language_code_utils.py
- resources/standards-data/iso639-3/.gitattributes
- resources/standards-data/iso639-3/iso639-3.tab
- resources/standards-data/iso639-3/readme.md
- resources/standards-data/langtags/readme.md
- resources/standards-data/language-subtag-registry/language-subtag-registry
- resources/standards-data/language-subtag-registry/readme.md
- resources/standards-data/ldml-keyboards/readme.md
- resources/standards-data/readme.md
- resources/standards-data/unicode-character-database/readme.md
- windows/src/test/unit-tests/standards-data/Keyman.Test.System.CanonicalLanguageCodeUtilsTest.pas
- windows/src/test/unit-tests/standards-data/Keyman.Test.System.Standards.LangTagsRegistryTest.pas
Also add source of files to readme.
> chore: Update standards data

- developer/src/kmc/src/messages/NodeCompilerCallbacks.ts
- developer/src/kmc/src/messages/messages.ts
> chore(developer): suppress excessive messages in kmc 🗜

- linux/keyman-config/keyman_config/convertico.py
> refactor(linux): Refactor image loading

- developer/src/kmc/build.sh
> chore(developer): remove old copy_schema call kmc build.sh

- common/web/types/src/kpj/keyman-developer-project.ts
> fix(developer): don't add .keyboard_info twice 🗜

- linux/ibus-keyman/build.sh
- linux/ibus-keyman/meson.build
- linux/ibus-keyman/src/bcp47util.c
- linux/ibus-keyman/src/bcp47util.h
- linux/ibus-keyman/src/keymanutil.c
- linux/ibus-keyman/src/meson.build
- linux/ibus-keyman/src/test/bcp47util_tests.c
- linux/ibus-keyman/src/test/meson.build
- linux/ibus-keyman/src/test/run-single-test.sh
- linux/ibus-keyman/src/test/run-tests.sh
- linux/ibus-keyman/src/test/setup-tests.sh
- linux/ibus-keyman/tests/meson.build
- linux/ibus-keyman/tests/scripts/run-single-test.sh
- linux/ibus-keyman/tests/scripts/run-tests.sh
- linux/ibus-keyman/tests/scripts/setup-tests.sh
- linux/ibus-keyman/tests/scripts/teardown-tests.sh
- linux/ibus-keyman/tests/scripts/test-helper.inc.sh
- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/tests/test_install_kmp.py
We now use the canonical tag without appending the script (unless necessary).
Also minimize bcp47 language tags in engine before adding the keyboards to ibus so that it matches the tags `km-config` installs.
Fixes #8620.
- The tests can be run on any Linux version
- Reboot
**TEST_INST_MUL**: Installation of keyboard with lang tag `mul`
- Download the attached keyboard ([itrans_devanagari_sanskrit_vedic.kmp.zip](https://github.com/keymanapp/keyman/files/11766968/itrans_devanagari_sanskrit_vedic.kmp.zip)) to your Downloads folder
- unzip the keyboard
- open a terminal window and run
```
km-package-install -f …
```
> fix(linux): Fix installation of keyboards with lang tag `mul`

- ios/samples/build_common.sh
- mac/Keyman4MacIM/localdeploy.sh
- mac/Keyman4MacIM/make-km-dmg.sh
- mac/setup/build.sh
- oem/firstvoices/ios/build_common.sh
Cherry-pick of #8565 to stable-16.0.
TEST_INSTALL: Download and attempt to install. It should install.
> chore(mac): fix corrupt installer 🍒

- common/web/types/src/util/compiler-interfaces.ts
- developer/src/kmc-model-info/src/messages.ts
- developer/src/kmc-model-info/src/model-info-compiler.ts
- developer/src/kmc-model-info/tsconfig.json
- developer/src/kmc/src/commands/buildClasses/BuildModelInfo.ts
- developer/src/kmc/src/kmlmi.ts
- developer/src/kmc/src/messages/messages.ts
> chore(developer): use kmc messages for kmc-model-info 🗜

- linux/Jenkinsfile
In #9340 I overlooked one place where we mention Kinetic...
> chore(linux): Stop building Kinetic on Jenkins 🏠

- linux/debian/changelog
- linux/debian/meson/no-exe-wrapper.ini
- linux/debian/rules
> chore(linux): Work around build failure on Debian mips64el 🏠

- linux/.pbuilderrc
- linux/Jenkinsfile
- linux/scripts/cow.sh
- linux/scripts/deb.sh
- linux/scripts/launchpad.sh
- remove Ubuntu 22.10 Kinetic which is no longer supported
- add future Ubuntu 23.10 Mantic
> chore(linux): Update supported Ubuntu versions

- linux/debian/changelog
> chore(linux): Update debian changelog 🏠

- linux/scripts/upload-to-debian.sh
> chore(linux): Fix creation of PRs after uploading to Debian

- .github/workflows/deb-packaging.yml
- linux/README.md
> chore: add run-name to deb-packaging 🗜

- docs/build/linux-ubuntu.md
- docs/linux/README.md
- linux/Dockerfile
- linux/keyman-system-service/README.md
> docs(core): Document how to build Core on Linux

- developer/src/kmc-kmn/src/compiler/compiler.ts
- developer/src/kmc-kmn/test/test-wasm-uset.ts
- While i'm in the neighborhood..
- use 'free' besides just 'malloc' (sure enough..)
- move wasmExports into this
- add code coverage for failed sizes
- cleanup
Related to #7375 
> fix(developer): more wasm uset fixes 🙀

- .github/workflows/deb-packaging.yml
- linux/README.md
> chore: add run-name to deb-packaging

- .github/workflows/deb-packaging.yml
> chore: try another variable for reporting

- developer/src/kmc/src/messages/messages.ts
- developer/src/kmc/src/util/projectLoader.ts
> chore(developer): add Error_NotAProjectFile 🗜

- linux/ibus-keyman/src/keymanutil.c
- linux/ibus-keyman/src/main.c
> fix(linux): fix memory leaks and method name

- resources/stats/stats.sh
Someone asked for this last time I worked on stats. So a small sidetrack later, here 'tis.
> chore: stats script parameters

- common/web/gesture-recognizer/docs/web-reintegration.md
- common/web/gesture-recognizer/src/engine/headless/gestureSource.ts
- common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureMatcher.ts
- common/web/gesture-recognizer/src/engine/headless/gestures/matchers/pathMatcher.ts
- common/web/gesture-recognizer/src/engine/headless/inputEngineBase.ts
- common/web/gesture-recognizer/src/engine/headless/touchpointCoordinator.ts
- common/web/gesture-recognizer/src/engine/index.ts
- common/web/gesture-recognizer/src/engine/inputEventEngine.ts
- common/web/gesture-recognizer/src/engine/mouseEventEngine.ts
- common/web/gesture-recognizer/src/test/auto/headless/gestures/gestureMatcher.spec.ts
- common/web/gesture-recognizer/src/test/auto/headless/gestures/pathMatcher.spec.ts
- common/web/gesture-recognizer/src/test/resources/simulateMultiSourceInput.ts
- common/web/gesture-recognizer/src/tools/unit-test-resources/src/headlessInputEngine.ts
- common/web/gesture-recognizer/src/tools/unit-test-resources/src/inputRecording.ts
- common/web/gesture-recognizer/src/tools/unit-test-resources/src/inputSequenceSimulator.ts
- common/web/gesture-recognizer/src/tools/unit-test-resources/src/sequenceRecorder.ts
> chore(web): SimpleGestureSource => GestureSource 🐵

- common/web/types/test/ldml-keyboard/test-pattern-parser.ts
- common/web/types test lacked update from #9448
#9119
> fix(common): marker test 🙀

- linux/keyman-config/keyman_config/dconf_util.py
Follow-up of #4999 (which mentions different warnings, but this change fixes warnings that we were still getting).
> refactor(linux): Fix warning

- linux/keyman-config/keyman_config/ibus_util.py
> fix(linux): Prevent exception if neither USER, LOGNAME nor SUDO_USER set

- linux/ibus-keyman/src/main.c
> refactor(linux): Reformat file

- linux/ibus-keyman/src/keymanutil.c
- linux/ibus-keyman/src/keymanutil.h
- linux/ibus-keyman/src/test/keymanutil_tests.c
- linux/keyman-config/.editorconfig
> refactor(linux): Rename defines to clarify purpose 🏘️

- docs/settings/linux/tasks.json
> docs(linux): Update sample tasks.json for Linux

- developer/src/kmc-keyboard-info/src/index.ts
- developer/src/kmc/src/commands/buildClasses/BuildKeyboardInfo.ts
- developer/src/kmc/src/util/getLastGitCommitDate.ts
- developer/src/kmc/test/test-getLastGitCommitDate.ts
> feat(developer): use git's last commit date for keyboard_info 🎺

- developer/src/kmc/src/commands/build.ts
- developer/src/kmc/src/commands/buildWindowsPackageInstaller/index.ts
> chore(developer): normalize case on input filenames in kmc 🎺

- developer/src/kmc-model/src/build-trie.ts
- developer/src/kmc-model/src/model-compiler-errors.ts
- developer/src/kmc-model/test/test-parse-wordlist.ts
> chore(developer): reduce duplicate words warning to hint

- developer/src/kmc/build.sh
> chore(developer): switch on code coverage reporting for kmc

- core/commands.inc.sh
> fix(core): clean cached ICU in core

- common/tools/hextobin/build.sh
- common/tools/hextobin/hextobin.ts
- common/tools/hextobin/package.json
- common/tools/hextobin/tsconfig.json
- developer/src/kmc-ldml/test/test-compiler-e2e.ts
- developer/src/kmc-ldml/test/test-visual-keyboard-compiler-e2e.ts
- tsconfig.esm.json
> chore(common): convert hextobin to ES Modules

- ios/exportAppStore.plist
> chore(ios): renew certificate

- common/web/types/src/kmx/kmx-plus.ts
- common/web/types/src/ldml-keyboard/pattern-parser.ts
- common/web/types/test/ldml-keyboard/test-pattern-parser.ts
- core/src/ldml/C9134_ldml_markers.md
- core/tests/unit/ldml/keyboards/k_210_marker-test.xml
- core/tests/unit/ldml/keyboards/k_210_marker.xml
- developer/src/kmc-ldml/src/compiler/tran.ts
- add a regex form that matches any marker
For: #9119
> feat(core): match any marker 🙀

- resources/standards-data/ldml-keyboards/techpreview/cldr_info.json
- resources/standards-data/ldml-keyboards/techpreview/fixup-schema.js
- resources/standards-data/ldml-keyboards/techpreview/ldml-keyboardtest3.schema.json
- keyboardTest3 didn't get a fix that had applied to keyboard[3]
- regenerate using the exact same CLDR
Fixes: #9683
> fix(common): fix schema fixer 🙀

- common/web/types/src/schema-validators.ts
- developer/src/common/web/utils/tsconfig.json
- tsconfig.base.json
> chore: allowJs for imported schemas 🎺

- linux/ibus-keyman/src/engine.c
- linux/ibus-keyman/src/keymanutil.c
- linux/ibus-keyman/src/keymanutil_internal.h
- linux/ibus-keyman/src/kmpdetails.c
- linux/ibus-keyman/src/kmpdetails.h
- linux/ibus-keyman/src/main.c
- linux/ibus-keyman/src/test/keymanutil_tests.c
- linux/ibus-keyman/src/test/print_kmpdetails.c
- linux/ibus-keyman/tests/meson.build
- linux/ibus-keyman/tests/scripts/run-single-test.sh
- linux/ibus-keyman/tests/scripts/test-helper.inc.sh
> refactor(linux): Use auto cleanup

- common/schemas/keyboard_info/README.md
(wish I had implemented the keymanapp-skip-builds controls for this one!)
> chore: update readme for keyboard_info schema

- linux/keyman-config/tests/test_ibus_util.py
10s faster because we now simulate sleep...
> chore(linux): Speed up ibus-util tests

- common/web/types/src/kpj/keyman-developer-project.ts
- developer/src/kmc/src/messages/infrastructureMessages.ts
- developer/src/kmc/src/util/projectLoader.ts
> fix(developer): handle invalid project folders cleanly

- common/schemas/kmp/README.md
- common/schemas/kmp/kmp.schema.json
- common/schemas/kps/README.md
> chore: update kmp.schema.json and docs for kps schema

- docs/build/macos.md
> docs(common): macos build update

- ios/exportAppStore.plist
> chore(ios): renew certificate 🍒 🏠

- linux/scripts/deb-packaging.sh
> chore(linux): Fix build by adding one character

- HISTORY.md
> chore(common): Add entries from 16.0 HISTORY.md

- common/web/types/src/kpj/kpj-file-reader.ts
- developer/src/kmc/src/util/projectLoader.ts
> chore(common): handle invalid XML in kpj-file-reader

- resources/build/help-keyman-com.sh
> chore: include ci/pull-requests.inc.sh for help uploads

- web/source/osk/oskLayerGroup.ts
- web/source/osk/visualKeyboard.ts
> fix(web): fixes doc-kbd display of default layer when it's not defined first 🍒 🏠

- common/web/types/build.sh
- common/web/types/src/schema-validators.ts
- common/web/types/src/schemas.ts
- common/web/types/tools/schema-bundler.js
- developer/src/inst/download.in.mak
- developer/src/inst/kmdev.wxs
- developer/src/kmc-package/src/compiler/kmp-compiler.ts
> chore(developer): verify kmp.json output from kmc-package

- common/web/types/src/keyman-touch-layout/keyman-touch-layout-file-reader.ts
- common/web/types/src/kpj/kpj-file-reader.ts
- common/web/types/src/kvk/kvks-file-reader.ts
- common/web/types/src/osk/osk.ts
> chore(common): fixup SchemaValidators error handling

- developer/src/tike/dialogs/relatedPackages/Keyman.Developer.UI.UfrmEditRelatedPackage.dfm
> chore(developer): change field label to 'Related Package ID' in Related Packages dialog

- developer/src/tike/main/UframeTextEditor.pas
- developer/src/tike/xml/app/editor/editor.js
Fixes #9849.
* **TEST_HYPERLINK:** Follow the steps in #9849 and verify that the link opens in your browser and that the editor continues to function normally.
> fix(developer): open editor links in new window

- developer/src/tike/main/UfrmMain.dfm
- developer/src/tike/main/UfrmMain.pas
> feat(developer): Compile button in TIKE toolbar

- .github/workflows/deb-packaging.README.md
- .github/workflows/deb-packaging.yml
- resources/build/trigger-builds.inc.sh
Some improvements to repository_dispatch, and documentation how to trigger GHA build manually for testing purposes.
Closes #9548.
> chore(linux): Improve repository_dispatch 🎬

- developer/src/kmcmplib/build.sh
> chore(developer): common/include dep for kmcmplib

- core/tests/unit/ldml/keyboards/meson.build
- resources/standards-data/ldml-keyboards/techpreview/3.0/bn.xml
- resources/standards-data/ldml-keyboards/techpreview/3.0/fr-t-k0-optimise-test.xml
- resources/standards-data/ldml-keyboards/techpreview/3.0/fr-t-k0-optimise.xml
- resources/standards-data/ldml-keyboards/techpreview/3.0/fr-t-k0-test-test.xml
- resources/standards-data/ldml-keyboards/techpreview/3.0/fr-t-k0-test.xml
- resources/standards-data/ldml-keyboards/techpreview/test/bn-test.xml
- bn-bengali with a basic test
- fr-optimise
- note: disabling bengali reorders for now, not working properly due to tertiary reordering feat(core): tertiary reorders 🙀  #9707
For: #9916
> feat(common): ldml update to WIP cldr data 🙀

- resources/build/trigger-definitions.inc.sh
When the baseline tests change we want to trigger a Linux build.
> fix(linux): Fix trigger for baseline tests

- docs/CODEOWNERS
Signing @ermshiperete for more notifications :smile: 
> docs(common): Update CODEOWNERS for web

- developer/src/kmc-package/src/compiler/kmp-compiler.ts
- developer/src/kmc-package/test/fixtures/withfolders.qaa.sencoten/withfolders.qaa.sencoten.model.kmp.intermediate.json
> fix(developer): path separator for kmc-package

- core/src/km_core_state_api.cpp
Determine the best way to check for null termination all compilers
> fix(core): check for null termination

- developer/src/common/web/utils/README.md
- developer/src/common/web/utils/build.sh
- developer/src/common/web/utils/package.json
- developer/src/kmc-keyboard-info/package.json
- developer/src/kmc-model-info/package.json
- developer/src/kmc/build.sh
- developer/src/kmc/package.json
- developer/src/server/package.json
- package-lock.json
- package.json
> fix(common): publish @keymanapp/developer-utils as npm module

- linux/keyman-config/keyman_config/install_kmp.py
> chore(linux): Small refactoring to make it easier to read

- android/KMAPro/kMAPro/src/main/res/values-ckl-rNG/strings.xml
- mac/Keyman4MacIM/Keyman4MacIM/ckl.lproj/Localizable.strings
> chore(android,mac): Update Kibaku crowdin strings

- android/KMAPro/kMAPro/src/main/res/values-mnw-rMM/strings.xml
- mac/Keyman4MacIM/Keyman4MacIM/mnw.lproj/Localizable.strings
> chore(android,mac): Update Mon crowdin strings

- developer/src/kmc/src/commands/buildClasses/BuildProject.ts
- developer/src/kmc/src/messages/infrastructureMessages.ts
- developer/src/kmc/test/test-project-build.ts
> feat(developer): kmc emit hint if project file is old version 🦕

- oem/firstvoices/ios/exportAppStore.plist
> chore(ios): FV certificate key

- oem/firstvoices/ios/exportAppStore.plist
Fixes #10225.
Cherry-pick of #10228.
> chore(ios): FV certificate key 🏠

- web/src/app/browser/src/keymanEngine.ts
- web/src/engine/main/src/contextManagerBase.ts
- web/src/engine/package-cache/src/stubAndKeyboardCache.ts
Fixes https://github.com/keymanapp/keymanweb.com/issues/96.
> fix(web): fixes null-stub keyboard lookups, related 'keyboardchange' event niche case

- mac/build.sh
- mac/mac-utils.inc.sh
- mac/setup/build.sh
> fix(mac): improve code signing robustness

- HISTORY.md
Update the master HISTORY.md with the last 2 16.0 releases
> chore(common): Add entries from 16.0.144 HISTORY.md

- package-lock.json
- web/build.sh
- web/common.inc.sh
- web/package.json
- web/src/engine/attachment/.c8rc.json
- web/src/engine/attachment/build.sh
- web/src/test/auto/.mocharc.json
- web/src/test/auto/headless/engine/attachment/pageContextAttachment.tests.ts
- web/src/test/auto/tsconfig.json
- web/test.sh
> chore(web): Add unit tests for `pageContextAttachment`

- developer/src/common/web/utils/index.ts
- developer/src/common/web/utils/src/options.ts
- developer/src/kmc/src/commands/buildClasses/BuildProject.ts
- developer/src/kmc/test/test-build.ts
- developer/src/kmc/test/test-infrastructureMessages.ts
- developer/src/kmc/test/test-project-build.ts
> chore(developer): honor prompt to upgrade in kmc

- .github/workflows/deb-packaging.yml
Occasionally name resolution temporarily fails when trying to upload to llso. This change retries 10 times before giving up.
> chore(linux): Retry llso upload

- .github/workflows/deb-packaging.yml
This is an attempt to understand what's going wrong in the gha (e.g. https://github.com/keymanapp/keyman/actions/runs/7465045245/job/20331729843)
> chore(linux): Output dput exit code after upload to llso

- HISTORY.md
> chore: cleanup recent history entries without PR title

- developer/src/tike/actions/dmActionsMain.dfm
- developer/src/tike/actions/dmActionsMain.pas
- developer/src/tike/main/UfrmMain.dfm
- developer/src/tike/main/UfrmMain.pas
> fix(developer): remove unused tools/customise menu

- common/predictive-text/unit_tests/test.sh
- common/web/gesture-recognizer/src/tools/build.sh
> chore(common): builder action launch typos

- android/KMAPro/kMAPro/src/main/res/values-b+es+419/strings.xml
- android/KMAPro/kMAPro/src/main/res/values-de-rDE/strings.xml
- android/KMAPro/kMAPro/src/main/res/values-fr-rFR/strings.xml
- android/KMEA/app/src/main/res/values-de-rDE/strings.xml
- android/KMEA/app/src/main/res/values-fr-rFR/strings.xml
- ios/engine/KMEI/KeymanEngine/de.lproj/Localizable.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/de.lproj/KMAboutWindowController.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/de.lproj/preferences.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/de.lproj/KMInfoWindowController.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/de.lproj/KMKeyboardHelpWindowController.strings
- mac/Keyman4MacIM/Keyman4MacIM/de.lproj/Localizable.strings
- mac/Keyman4MacIM/Keyman4MacIM/de.lproj/MainMenu.strings
- mac/Keyman4MacIM/Keyman4MacIM/es-419.lproj/Localizable.strings
- mac/Keyman4MacIM/Keyman4MacIM/fr.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/de/strings.xml
- windows/src/desktop/setup/locale/de/strings.xml
- windows/src/desktop/setup/locale/es-419/strings.xml
Before going to Beta, this just adds a few more Crowdin strings for:
* French
* German
* Spanish (Latin America
> chore(common): Update crowdin strings for French, German, Spanish (Latin America)

- .github/workflows/deb-packaging.yml
> chore(linux): fix GHA packaging

- linux/ibus-keyman/src/engine.c
Relates to #10365.
Fixes #10378.
> refactor(linux): use `km_core_state_context_debug` 🌱

- windows/src/engine/keyman32/calldll.cpp
- windows/src/engine/keyman32/kmprocess.cpp
> refactor(windows): use `km_core_state_context_debug` 🌱

- linux/debian/libkeymancore.symbols
> chore(core): Update symbols file 🌱

- docs/websites/README.md
Relates to keymanapp/keyman.com#403 on the point
> Update https://github.com/keymanapp/keyman/tree/master/docs/websites#how-to-set-up-a-local-web-server-for-the-keyman-web-pages
* update configure step about downloading _common/ files
* Add info about website-local-proxy
> docs(common): Update website README.md

- core/tests/unit/kmnkbd/test_actions_normalize.cpp
> chore(core): add surrogate pair tests to test_actions_normalize 🌱

- android/help/about/whatsnew.md
Chore of updating Keyman for Android 17.0 release note
> chore(android/app): Update whatsnew for 17.0

- developer/src/inst/kmdev.wxs
Fixes #10485.
Tests will be done on #10459 when this merges in.
> fix(developer): include ldml techpreview imports in msi 🌱

- developer/src/tike/child/Keyman.Developer.UI.Debug.UfrmLdmlKeyboardDebug.pas
- developer/src/tike/debug/debugdeadkeys.pas
> fix(developer): support surrogate pairs in ldml debugger 🌱

- docs/websites/README.md
Update website-local-proxy names
> docs: Update websites README.md

- docs/settings/linux/.devcontainer/Dockerfile
- linux/README.md
- linux/debian/changelog
- linux/debian/control
- linux/keyman-config/keyman_config/downloadkeyboard.py
- linux/keyman-config/keyman_config/install_window.py
- linux/keyman-config/keyman_config/options.py
- linux/keyman-config/keyman_config/welcome.py
> chore(linux): Build with webkitgtk 4.1 instead of 4.0 🍒 🏠

- core/src/ldml/ldml_processor.cpp
- core/src/ldml/ldml_processor.hpp
- report normalization
Fixes #10468
> feat(core): report on (lack of) normalization 🙀

- developer/src/kmc-ldml/build.sh
- developer/src/kmc-ldml/package.json
- package-lock.json
> chore(developer): kmc ldml build - call c8 directly for tests

- .github/workflows/deb-packaging.yml
> chore(linux): Fix the path of downloaded artifacts

- common/web/types/src/ldml-keyboard/pattern-parser.ts
- common/web/types/test/ldml-keyboard/test-pattern-parser.ts
- ts side - see also #10563 
- use an 'end' marker for each NFD
#10516 
> feat(developer):  double markers once again 🙀

- core/src/ldml/ldml_markers.cpp
- core/src/ldml/ldml_markers.hpp
- core/tests/unit/ldml/test_transforms.cpp
- C++ side  of #10541
Fixes: #10516
> feat(core): ldml double marker, C++ side 🙀

- HISTORY.md
Just updating the history.md for master
> chore(common): Add entries from 16.0.145 HISTORY.md

- HISTORY.md
Not sure why this is happening, nothing obvious in logs. Will monitor.
> chore(common): history missing message fixup

- common/web/input-processor/src/text/prediction/predictionContext.ts
- common/web/input-processor/tests/cases/predictionContext.js
> fix(web): banner scroll positioning after reversions

- windows/src/desktop/kmshell/locale/pt-PT/strings.xml
> chore(windows): Update pt-pt translation files

- windows/src/desktop/kmshell/locale/pt-PT/strings.xml
- windows/src/desktop/setup/locale/pt-PT/strings.xml
Follow-on to #10698 to update more PT strings from Crowdin
> chore(windows): Update more PT strings

- android/help/about/whatsnew.md
- ios/help/about/whatsnew.md
> docs(ios): what's new in 17.0

- web/source/dom/targets/contentEditable.ts
> fix(web): fixes content-editable error that occurred on focus changes 🏠

- developer/src/kmc-kmn/src/kmw-compiler/kmw-compiler-messages.ts
- developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts
- developer/src/kmc-kmn/test/kmw/test-kmw-messages.ts
> chore(developer): reduce WARN_TouchLayoutUsesUnsupportedGesturesDownlevel to HINT

- core/tests/unit/ldml/keyboards/ldml_test-test.xml
- core/tests/unit/ldml/keyboards/ldml_test.xml
> chore(core):  update sample ldml keyboard

- linux/scripts/upload-to-debian.sh
> chore(linux): Fix `upload-to-debian.sh` script for beta releases

- developer/docs/api/etc/kmc-analyze.api.md
- developer/docs/api/etc/kmc-kmn.api.md
- developer/src/kmc-analyze/src/index.ts
- developer/src/kmc-analyze/src/messages.ts
- developer/src/kmc-analyze/src/osk-character-use/index.ts
- developer/src/kmc-analyze/src/osk-rewrite-pua/index.ts
> docs(developer): add documentation for kmc-analyze

- developer/src/tike/xml/project/project.css
Fixes #10817.
This fix is a patch rather than a rework to use grid or flex css, which would be better, but should not be done in beta.
> fix(developer): make sure scroll bar appears when needed in global welcome

- developer/docs/api/etc/kmc-model.api.md
- developer/src/kmc-kmn/src/compiler/compiler.ts
- developer/src/kmc-ldml/src/compiler/compiler.ts
- developer/src/kmc-model/src/lexical-model-compiler.ts
- developer/src/kmc-model/src/lexical-model.ts
- developer/src/kmc-model/src/main.ts
- developer/src/kmc-model/src/model-compiler-messages.ts
> docs(developer): kmc-model api documentation

- developer/docs/api/etc/kmc-model-info.api.md
- developer/src/kmc-model-info/src/model-info-compiler-messages.ts
- developer/src/kmc-model-info/src/model-info-compiler.ts
> docs(developer): kmc-model-info api documentation

- developer/docs/api/etc/kmc-keyboard-info.api.md
- developer/src/kmc-keyboard-info/src/keyboard-info-compiler-messages.ts
- developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts
> docs(developer): kmc-keyboard-info api documentation

- android/help/about/index.md
- android/help/about/privacy.md
- android/help/index.md
> docs(android/app): Add data privacy policy page 🏠 🍒

- core/doc/markdown_files/index.md
- core/include/keyman/keyman_core_api.h
- core/include/keyman/keyman_core_api_context.h
- core/tools/api-header-extractor/build.sh
- core/tools/api-header-extractor/package.json
- core/tools/api-header-extractor/src/index.ts
- core/tools/api-header-extractor/tsconfig.json
> chore(core): refresh API docs for 17.0

- developer/src/tike/main/mrulist.pas
Fixes #11041.
If two TIKE processes try to save the MRU at the same time, this can result in a sharing violation. The relevant OLE error code is not saved as a constant in Delphi lib, so I looked it up and added it here.
Note: I have verified this with a small test project locally. IMO: it's not worth adding a unit test.
This is difficult to repro, so we will just watch Sentry for future reports to verify resolution.
> fix(developer): catch sharing violation when saving mru

- android/KMAPro/kMAPro/src/main/res/values-mnw-rMM/strings.xml
- android/KMEA/app/src/main/res/values-mnw-rMM/strings.xml
> chore(android): Update crowdin strings for Mon

- android/KMAPro/kMAPro/src/main/res/values-km-rKH/strings.xml
- android/KMEA/app/src/main/res/values-km-rKH/strings.xml
> chore(android): Update crowdin strings for Khmer

- developer/src/kmc-ldml/src/compiler/keys.ts
- developer/src/kmc-ldml/src/compiler/layr.ts
- developer/src/kmc-ldml/src/util/util.ts
- developer/src/kmc-ldml/test/fixtures/sections/keys/many-modifiers.xml
- developer/src/kmc-ldml/test/test-keys.ts
- developer/src/kmc-ldml/test/test-layr.ts
- developer/src/kmc-ldml/test/test-utils.ts
- improve modifier parsing
- test cases for keys and layr
Fixes: #11040
> feat(developer): support comma in modifiers 🙀

- core/src/ldml/ldml_processor.cpp
> chore(core): optimize ldml_event_state::emit_difference() when no diff 🙀 

- developer/src/tike/xml/layoutbuilder/builder.js
> fix(developer): prevent error when scrolling touch layout editor with no selected key

- common/web/lm-worker/src/main/correction/context-tracker.ts
Fixes #10980.
Predictive-text suggestions should now be much more consistent and stable after multiple spaces and/or newlines, rather than going blank in such scenarios.
Detailed version:  there was an issue when updating our predictive-text worker's context-cache in which two+ whitespaces in a row were not being properly joined together by the cache's best-state lookup operation, causing them to be treated as prefixes to words.  As languages generally don't use whitespaces as letters, this would quite naturally break the engine's ability to predict properly.
TEST_SPACED_SUGGESTIONS:  Attempt to repro the base issue - #10980.
1. Install one of the test artifacts below (for Android or for iOS)
2. Add a Khmer Angkor keyboard. 
3. Switch to English - EuroLatin (SIL) keyboard. 
4. Press the …
> fix(common/models): suggestion stability after multiple whitespaces

- common/web/gesture-recognizer/src/engine/headless/asyncClosureDispatchQueue.ts
This PR merges a split `async` method within the gesture engine, hopefully improving gesture performance a small bit.
By reducing the impact of the JS `async` keyword (and related TS helpers) slightly - paying the cost once, not twice, we can shave off several milliseconds over time when receiving touch events.  (In a 10s profile on an older Android device, I noted approximately 12ms spent on the declaration line of _each_ of the two `async` methods being merged here.)
- Reference: https://madelinemiller.dev/blog/javascript-promise-overhead/
- Downcompiling to ES6 does result in our code using some `tslib` helpers for full `async` support, and that _does_ contribute some overhead - I see its helper functions show up during code profiles, too.
Also, I believe merging the methods helps to …
> change(web): merges split async method in gesture engine 🪠

- web/src/engine/main/src/keymanEngine.ts
- web/src/engine/osk/src/keyboard-layout/oskBaseKey.ts
- web/src/engine/osk/src/keyboard-layout/oskKey.ts
- web/src/engine/osk/src/visualKeyboard.ts
Addresses review comments from #11140 (and one from #11177) post-merge.
> chore(web): simple layout reflow polish 🪠

- developer/src/tike/xml/layoutbuilder/builder.js
> fix(developer): handle invalid Unicode values in touch layout builder

- developer/src/server/src/index.ts
> fix(developer): handle multiple instances of Server starting

- developer/src/tike/main/UfrmHelp.pas
Fixes #11262.
Avoid the crash by reporting missing help pages to Sentry instead of attempting to write to a local .xml file. This gives us more data of which help is missing from Keyman Developer, which is more useful to us.
> fix(developer): report missing help to sentry instead of local xml

- developer/src/server/src/site/chargrid.js
- developer/src/server/src/site/packages.js
- developer/src/server/src/site/test.js
- developer/src/server/src/site/upload.js
- developer/src/server/src/site/websocket.js
> fix(developer): "use strict" for downlevel browsers in Server

- .github/workflows/deb-packaging.yml
> chore(linux): Adjust distros for GHA

- developer/src/kmc-package/src/compiler/kmp-compiler.ts
> fix(developer): handle missing Description element for File element in package compiler

- developer/src/server/src/site/chargrid.js
> fix(developer): define `lastSelLength` variable

- windows/src/desktop/kmshell/locale/km-KH/strings.xml
> chore(windows): Update crowdin string for Khmer

- resources/build/builder.md
- resources/build/test/debug-deps/dep/build.sh
- resources/build/test/debug-deps/dep/child/build.sh
- resources/build/test/ignored-flags/build.sh
- resources/build/test/ignored-flags/child/build.sh
- resources/build/test/ignored-flags/test.sh
- resources/build/test/test.sh
- resources/builder.inc.sh
> feat(common): improve builder parameter passing for child and dep builds

- android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
:cherries: pick of 11481 to stable-17.0
> fix(android/app): Verify extracted text is not null 🍒 🏠

- resources/build/trigger-definitions.inc.sh
> chore(linux): Trigger GHA packaging for stable builds 🏠

- resources/build/trigger-definitions.inc.sh
> chore(linux): Trigger GHA packaging for stable builds :cherries: 

- .github/workflows/api-verification.yml
> fix(linux): Add missing variable to API verification GHA

- windows/src/desktop/kmshell/util/Keyman.System.KeymanStartTask.pas
Fixes: #4038 
Remove the CleanupAlphaTasks that was specific to task schedules created for 15.0 alpha. Scheduled task naming was changed to include a user name in the task. The clean-up function was to make sure the previously named tasks were removed. Now there should be no 15.0 alpha users it can be removed.
> chore(windows): remove schedule task clean up introduced in 15.0 Alpha

- .github/workflows/api-verification.yml
- .github/workflows/deb-packaging.yml
Another iteration to fix the API verification GHA.
> fix(linux): Pass artifacts key to API verification GHA

- .github/workflows/api-verification.yml
Something is still not right. It looks like it can't find the files it is expecting. This change lists the files we have.
> chore(linux): Debugging API verification

- android/KMEA/app/src/main/assets/android-host.js
> fix(android): host-page banner initialization

- android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
> fix(android): Ignore updating invalid selections 🍒 🏠

- web/src/app/browser/src/defaultBrowserRules.ts
> fix(web): fixes error on tab, enter when only a single input element is on the page 🍒 🏠

- common/web/utils/src/managedPromise.ts
- web/src/engine/dom-utils/src/stylesheets.ts
- web/src/engine/osk/src/keyboard-layout/oskLayerGroup.ts
- web/src/engine/osk/src/visualKeyboard.ts
Cherry-pick-of: #11472
Fixes: #11467
> fix(web): correctly handle cross-origin stylesheets when calculating keyboard size and key cap font size 🍒  🏠

- android/KMEA/app/src/main/assets/android-host.js
Fixes: #11507
Cherry-pick-of: #11508
> fix(android): host-page banner initialization 🍒 🏠

- developer/src/tike/xml/help/contexthelp.xml
partial fix of: https://github.com/keymanapp/keyman/issues/2131
> chore(developer): add context/debug

- developer/src/kmc-ldml/test/test-compiler-e2e.ts
> chore(developer): increase timeout for kmc-ldml compiler test

- .github/workflows/api-verification.yml
> chore(linux): More debugging of API verification

- .github/workflows/api-verification.yml
> fix(linux): paths in `uses:` can't use variables

- .github/workflows/api-verification.yml
> fix(linux): include api version as part of package filename

- .github/workflows/api-verification.yml
> fix(linux): add debug output

- .github/workflows/api-verification.yml
> fix(linux): remove debug output and re-enable failures

- web/src/engine/osk/src/visualKeyboard.ts
Fixes: https://github.com/keymanapp/keyman/issues/11650
Cherry-pick-of: https://github.com/keymanapp/keyman/pull/11691
> fix(web): get row-height for flick constraints after performing layout 🍒  🏠

- android/KMEA/app/src/main/java/com/keyman/engine/cloud/CloudDownloadMgr.java
- android/KMEA/app/src/main/java/com/keyman/engine/util/KMLog.java
>  fix(android): handle IllegalArgumentException when initializing CloudDownloadMgr, add logging to check for unhandled side-effects 🍒 🏠

- developer/src/tike/xml/help/contexthelp.xml
partial fix of: https://github.com/keymanapp/keyman/issues/2131
> chore(developer): add context/character-map

- developer/src/tike/xml/help/contexthelp.xml
partial fix of: https://github.com/keymanapp/keyman/issues/2131
> chore(developer): add context/wordlist-editor

- developer/src/tike/child/Keyman.Developer.UI.UframeWordlistEditor.pas
Fixes: #11710
Fixes: KEYMAN-DEVELOPER-1S4
Cherry-pick-of: #11711
> fix(developer): handle encoding errors when loading wordlists 🍒 🏠

- common/predictive-text/src/web/sourcemappedWorker.ts
- web/src/app/webview/src/debug-main.ts
- web/src/app/webview/src/release-main.ts
Also add a comment to `SourcemappedWorker` explaining the difference to `DefaultWorker`.
> refactor(web): Replace deprecated substr with substring

- android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
- android/KMEA/app/src/main/assets/android-host.js
- android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
🍒-picks both #11604 and #11722.
> fix(android): check current orientation, fix keyboard size after system keyboard rotations and resumes 🍒  🏠

- developer/src/tike/xml/layoutbuilder/builder.xsl
- developer/src/tike/xml/layoutbuilder/platform-controls.js
Fixes: #11646
Fixes: KEYMAN-DEVELOPER-1X2
> fix(developer): show message if no more platforms to add to touch layout editor

- developer/src/tike/xml/help/contexthelp.xml
> docs(developer): context help in keyboard-editor section

- developer/src/tike/xml/help/contexthelp.xml
> docs(developer): context help in new-project section

- developer/src/tike/xml/layoutbuilder/builder.xsl
- developer/src/tike/xml/layoutbuilder/platform-controls.js
Fixes: #11646
Fixes: KEYMAN-DEVELOPER-1X2
Cherry-pick-of: #11759
> fix(developer): show message if no more platforms to add to touch layout editor 🍒 🏠

- web/src/engine/osk/src/input/gestures/browser/oskSubKey.ts
> fix(web): fix id of longpress keys with modifier set in touch layout

- common/models/wordbreakers/src/default/index.ts
- common/web/lm-worker/build-polyfiller.js
- common/web/lm-worker/src/polyfills/array.from.js
Fixes: #11502
Fixes: KEYMAN-WEB-K4
Cherry-pick-of: #11732
> fix(web): add limited Array.from polyfill for lm-worker use 🍒 🏠

- core/commands.inc.sh
- docs/build/macos.md
Mitigates: #11794
Cherry-pick-of: #11795
> fix(core): serialize tests for core/wasm on mac agents 🍒 🏠

- developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
Ref: https://community.software.sil.org/t/unhelpful-error-message-in-keyman-developer-17-0/8842
> chore(developer): clarify project upgrade messages about file locations

- developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
> chore(developer): clarify project upgrade messages about file locations 🍒 🏠

- web/src/engine/osk/src/input/gestures/browser/oskSubKey.ts
Fixes: #11782
Cherry-pick-of: #11783
> fix(web): fix id of longpress keys with modifier set in touch layout 🍒  🏠

- package-lock.json
- package.json
Reverts keymanapp/keyman#11798
Will reopen, blocked by #11376
> chore: Revert "chore(common): update base-package node-engine setting"

- .gitignore
- linux/mcompile/keymap/deadkey.cpp
- linux/mcompile/keymap/deadkey.h
- linux/mcompile/keymap/keymap.h
- linux/mcompile/keymap/mc_import_rules.cpp
- linux/mcompile/keymap/mcompile.cpp
fixes parts of PR [#9384](https://github.com/keymanapp/keyman/pull/9384)
This PR addresses and bundles comments made on  [#9384](https://github.com/keymanapp/keyman/pull/9384) for the module deadkey.
https://github.com/keymanapp/keyman/pull/9384#discussion_r1611432668
https://github.com/keymanapp/keyman/pull/9384#discussion_r1611443034
https://github.com/keymanapp/keyman/pull/9384#discussion_r1611465003
https://github.com/keymanapp/keyman/pull/9384#discussion_r1611467489
https://github.com/keymanapp/keyman/pull/9384#discussion_r1611471293
https://github.com/keymanapp/keyman/pull/9384#discussion_r1613231108
> feat(linux): mcompile-linux rework  module deadkey 🐘

- linux/keyman-config/keyman_config/keyman_option.py
- linux/keyman-config/keyman_config/sentry_handling.py
This is in preparation for #7697.
> refactor(linux): add KeymanOption class for options :checkered_flag: 

- linux/ibus-keyman/.gitignore
- linux/ibus-keyman/build.sh
- linux/ibus-keyman/meson.build
- linux/ibus-keyman/tests/meson.build
- linux/keyman-system-service/.gitignore
- linux/keyman-system-service/build.sh
- linux/keyman-system-service/resources/meson.build.in
> chore(linux): use shared meson config

- common/web/input-processor/src/corrections.ts
- web/src/engine/osk/src/visualKeyboard.ts
>  fix(web): use fat-finger data with simple keypresses 🍒  🏠

- linux/mcompile/keymap/mcompile.cpp
- linux/mcompile/keymap/u16.cpp
- linux/mcompile/keymap/u16.h
fixes parts of PR https://github.com/keymanapp/keyman/pull/9384.
Some comments may have been moved into an issue https://github.com/keymanapp/keyman/issues/11802
This PR addresses and bundles comments made on https://github.com/keymanapp/keyman/pull/9384 for the module u16
[double function](https://github.com/keymanapp/keyman/pull/9384#discussion_r1634481739)
[misleading name](https://github.com/keymanapp/keyman/pull/9384#discussion_r1634482671)
[sz naming](https://github.com/keymanapp/keyman/pull/9384#discussion_r1634483963)
[save c_str() call](https://github.com/keymanapp/keyman/pull/9384#discussion_r1634496807)
[start with /0](https://github.com/keymanapp/keyman/pull/9384#discussion_r1634506000)
[wrong comment](https://github.com/keymanapp/keyman/pull/9384#discussion_r1634510090) …
> feat(linux): comments on module u16 🐘

- windows/src/engine/keyman32/build.sh
> chore(windows): correct output file for 64-bit build of keyman32 in build.sh

- android/KMAPro/kMAPro/src/main/res/values-pt-rPT/strings.xml
- android/KMEA/app/src/main/res/values-pt-rPT/strings.xml
- ios/engine/KMEI/KeymanEngine/pt-PT.lproj/Localizable.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/pt-PT.lproj/KMInfoWindowController.strings
- mac/Keyman4MacIM/Keyman4MacIM/pt-PT.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/pt-PT/strings.xml
End of sprint task to update localization strings
> chore(common): Update Crowdin strings for Portuguese

- android/KMAPro/kMAPro/src/main/res/values-pt-rPT/strings.xml
- android/KMEA/app/src/main/res/values-pt-rPT/strings.xml
- ios/engine/KMEI/KeymanEngine/pt-PT.lproj/Localizable.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/pt-PT.lproj/KMInfoWindowController.strings
- mac/Keyman4MacIM/Keyman4MacIM/pt-PT.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/pt-PT/strings.xml
Cherrypick of #11974 to stable-17.0
> chore(common): Update Crowdin strings for Portuguese 🍒 🏠

- developer/src/kmc-kmn/src/kmw-compiler/compiler-globals.ts
- developer/src/kmc-kmn/src/kmw-compiler/javascript-strings.ts
- developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts
> refactor(developer): rename `verifyMinimumKeymanVersion`

- developer/src/kmc-analyze/src/osk-character-use/index.ts
- developer/src/kmc-analyze/src/osk-rewrite-pua/index.ts
- developer/src/kmc-kmn/src/compiler/compiler.ts
- developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
- developer/src/kmc-kmn/src/main.ts
- developer/src/kmc-kmn/test/test-messages.ts
- developer/src/kmc-kmn/test/test-wasm-uset.ts
- developer/src/kmc-ldml/test/test-tran.ts
- developer/src/kmc-ldml/test/test-vars.ts
> chore(developer): remove `CompilerMessages` stub and use `KmnCompilerMessages`

- resources/stats/stats.sh
> chore(common): updated stats script to support end date/sprint

- windows/src/engine/engine.sln
> fix(windows): align engine.sln platforms and configurations

- common/web/lm-worker/src/test/mocha/cases/suggestion-deduplication.js
> feat(web): add unit testing for suggestion deduplication 📚 

- linux/scripts/upload-to-debian.sh
Mention original PR in the body of the cherry-pick PR.
> change(linux): improve changelog PRs after upload to debian

- web/src/engine/main/src/keymanEngine.ts
Fixes: #12038
Cherry-pick-of: #12039
* **TEST_DEVELOPER_SERVER:** Verify that the Keyman Developer web debugger is working correctly.
> fix(web): add nullish test in setOsk 🏠

- common/web/lm-worker/src/test/mocha/cases/suggestion-finalization.js
> feat(web): add unit testing for finalization of generated suggestions 📚 

- common/web/lm-worker/src/test/mocha/cases/predict-from-corrections.js
> feat(web): add unit tests for prediction lookup component 📚 

- common/web/lm-worker/src/main/correction/distance-modeler.ts
- common/web/lm-worker/src/main/predict-helpers.ts
- common/web/lm-worker/src/test/mocha/cases/early-correction-search-stopping.js
The refactor allows this logic to be unit-tested far more easily.  We additionally leverage this fact and add corresponding unit-tests within this PR.
> refactor(web): spin off method for correction-search probability-thresholding check 📚 

- web/src/engine/main/src/keymanEngine.ts
Fixes: #12038
* **TEST_DEVELOPER_SERVER:** Verify that the Keyman Developer web debugger is working correctly.
> fix(web): add nullish test in setOsk

- developer/src/tike/xml/help/contexthelp.xml
partial fix of: https://github.com/keymanapp/keyman/issues/2131
> chore(developer): add language/reference

- HISTORY.md
* Update HISTORY.md from 17.0.328 from Sprint A18S7
* Also clean up `:checked_flag:` emojis
> chore(common): Update history from 17.0.328

- common/web/lm-worker/src/test/mocha/cases/worker-model-compositor.js
> fix(web): fix lm-worker test broken by botched merge conflict resolution

- developer/src/kmc/test/test-getLastGitCommitDate.ts
> fix(developer): update date for last git commit date fixture

- linux/mcompile/keymap/deadkey.cpp
- linux/mcompile/keymap/deadkey.h
- linux/mcompile/keymap/keymap.cpp
- linux/mcompile/keymap/keymap.h
- linux/mcompile/keymap/km_types.h
- linux/mcompile/keymap/mc_import_rules.cpp
- linux/mcompile/keymap/mc_import_rules.h
- linux/mcompile/keymap/mc_kmxfile.cpp
- linux/mcompile/keymap/mc_kmxfile.h
- linux/mcompile/keymap/mcompile.cpp
- linux/mcompile/keymap/mcompile.h
- linux/mcompile/keymap/meson.build
- linux/mcompile/keymap/u16.cpp
- linux/mcompile/keymap/u16.h
fixes parts of PR https://github.com/keymanapp/keyman/pull/9384.
This is a PR for the remaining topics. Mostly formatting/editing things like 
- adding function comments
- format document
- replace codecvt
- set capslock =1
- replace Macro for calculating max
- prevent buffer overrun in u16tok 
- @keymanapp-test-bot skip
> feat(linux): add function comments and remaining comments 🐘

- docs/file-formats/kmx-file-format.md
Addresses: https://github.com/keymanapp/keyman/pull/12163#issuecomment-2287675497 by @DavidLRowe 
> docs: update .kmx documentation around bitmaps, modifier state

- developer/src/README.md
- developer/src/build.sh
- developer/src/common/web/utils/src/compiler-interfaces.ts
- developer/src/kmc-convert/.eslintrc.cjs
- developer/src/kmc-convert/build.sh
- developer/src/kmc-convert/config/api-extractor.json
- developer/src/kmc-convert/package.json
- developer/src/kmc-convert/src/converter-artifacts.ts
- developer/src/kmc-convert/src/converter-class-factory.ts
- developer/src/kmc-convert/src/converter-messages.ts
- developer/src/kmc-convert/src/converter-options.ts
- developer/src/kmc-convert/src/converter.ts
- developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
- developer/src/kmc-convert/src/main.ts
- developer/src/kmc-convert/test/helpers/index.ts
- developer/src/kmc-convert/test/test-converter-messages.ts
- developer/src/kmc-convert/test/test-keylayout-to-kmn-converter.ts
- developer/src/kmc-convert/test/tsconfig.json
- developer/src/kmc-convert/tsconfig.json
- developer/src/kmc/build.sh
- developer/src/kmc/package.json
- developer/src/kmc/src/commands/convert.ts
- developer/src/kmc/src/kmc.ts
- developer/src/kmc/src/messages/messageNamespaces.ts
- developer/src/kmc/tsconfig.json
- developer/src/packages.inc.sh
- developer/src/tools/sentry-upload-difs.sh
- package-lock.json
- package.json
- tsconfig.json
kmc-convert is a new module that will provide keyboard source file conversion classes.
> feat(developer): add kmc-convert to developer source 😎

- linux/build.sh
- linux/mcompile/keymap/meson.build
> chore(linux): add mcompile to linux build.sh 🐘

- web/src/engine/main/src/keymanEngine.ts
- web/src/engine/osk/src/visualKeyboard.ts
> fix(web): disable fat-finger data use when mayCorrect = false 🍒  🏠

- web/src/engine/osk/src/visualKeyboard.ts
> fix(web): fix documentation-keyboard spacebar-text scaling 🍒  🏠

- resources/locate_emscripten.inc.sh
Follows: #12243
Cherry-pick-of: 1b88100394868fc4671e660f984c83df8f6efc7c
> chore(common): use `npm install` in emsdk update

- docs/build/windows.md
> docs: refresh windows.md

- linux/keyman-config/keyman_config/kvk2ldml.py
Make methods private that are only used inside of kvk2ldml.py.
> refactor(linux): cleanup API of kvk2ldml.py

- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
> change(ios): defer registration of fonts past initialization 🍒  🏠

- developer/src/kmc-ldml/src/compiler/visual-keyboard-compiler.ts
Fixes: #12056
Will cherry-pick once approved by @srl295 
> fix(developer): find last matching key in LDML key bag when building KVK

- web/src/engine/js-processor/src/mock.ts
> chore(web): remove obsolete comment

- oem/firstvoices/keyboards.csv
Cherrypick of #12300 to stable-17.0
> chore(android,ios): Update FirstVoices keyboards to 12.15 🏠

- developer/src/kmc-ldml/src/compiler/visual-keyboard-compiler.ts
Fixes: #12056
Cherry-pick-of: #12278
> fix(developer): find last matching key in LDML key bag when building KVK 🍒 🏠

- docs/file-formats/kmx-plus-file-format.md
> docs(core): improve formatting of KMX+ doc

- android/KMAPro/kMAPro/src/main/res/values-cs-rCZ/strings.xml
- android/KMEA/app/src/main/res/values-cs-rCZ/strings.xml
- ios/engine/KMEI/KeymanEngine/cs.lproj/Localizable.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/cs.lproj/preferences.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/cs.lproj/KMInfoWindowController.strings
- mac/Keyman4MacIM/Keyman4MacIM/cs.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/cs-CZ/strings.xml
- windows/src/desktop/setup/locale/cs-CZ/strings.xml
> chore(common): Update crowdin strings for Czech

- HISTORY.md
> chore(common): Fix missing entries in HISTORY.md

- oem/firstvoices/keyboards.csv
Updates the FirstVoices apps to the latest fv_all.kmp 13.0 (keymanapp/keyboards#3067)
> chore(oem/fv): Update to fv_all 13.0

- common/windows/delphi/general/RegistryKeys.pas
- oem/firstvoices/windows/src/xml/strings.xml
- windows/src/desktop/kmshell/kmshell.dpr
- windows/src/desktop/kmshell/kmshell.dproj
- windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas
- windows/src/desktop/kmshell/main/UImportOlderVersionSettings.pas
- windows/src/desktop/kmshell/main/UfrmStartInstallNow.dfm
- windows/src/desktop/kmshell/main/UfrmStartInstallNow.pas
- windows/src/desktop/kmshell/main/initprog.pas
- windows/src/desktop/kmshell/xml/strings.xml
- windows/src/desktop/setup/RunTools.pas
- windows/src/desktop/setup/UfrmRunDesktop.pas
- windows/src/engine/keyman/keyman.dpr
- windows/src/engine/keyman/keyman.dproj
- windows/src/engine/keyman/main.pas
- windows/src/engine/kmcomapi/util/utilkeymanoption.pas
- windows/src/global/delphi/general/KeymanOptionNames.pas
Add an automatic update option to Keyman Options configuration tab. Also add a form to ask the user if they are happy for Windows to restart. 
This is quite a simple change and can be reviewed with the add-apply-update branch
> feat(windows): automatic updates option 💽

- android/help/about/privacy.md
- android/help/about/whatsnew.md
- android/help/basic/config/index.md
- oem/firstvoices/android/app/src/main/assets/setup/main.html
* Update whatsnew for 18.0
* Rename "SIL International" to "SIL Global" (only the user-facing content in the apps. We'll do a mass rename of source files in the repo separately)
* Add link to adjust-longpress-delay page (follows #12359)
> docs(android): Update help docs

- HISTORY.md
Incorporate HISTORY.md from 17.0.329 stable
> chore(common): Update history with 17.0.329 stable

- android/KMAPro/kMAPro/src/main/res/values-it-rIT/strings.xml
- android/KMEA/app/src/main/res/values-it-rIT/strings.xml
- ios/engine/KMEI/KeymanEngine/it.lproj/Localizable.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/it.lproj/preferences.strings
- mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/it.lproj/KMInfoWindowController.strings
- mac/Keyman4MacIM/Keyman4MacIM/it.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/it-IT/strings.xml
- windows/src/desktop/setup/locale/it-IT/strings.xml
> chore(common): Update crowdin strings for Italian

- docs/file-formats/kmx-plus-file-format.md
> fix(common): correct offsets in KMX+ spec

- developer/src/build.sh
> fix(developer): publish developer-utils package during build

- common/web/types/package.json
- package-lock.json
> fix(common): declare dep on @keymanapp/ldml-keyboard-constants 🏠

- developer/src/tike/child/UfrmKeymanWizard.pas
> fix(developer): warn before importing over touch layout

- docs/websites/README.md
Documenting developer note on troubleshooting website PHP errors
I don't think we're at a point where it needs to be a website builder step...
> chore(common): Add note on troubleshooting website errors

- ios/exportAppStore.plist
> chore(ios): renew certificate 🍒 🏠 

- docs/minimum-versions.md
- docs/minimum-versions.md.in
> chore(common): fix links in minimum-versions.md

- .github/workflows/api-verification.yml
- linux/scripts/verify_api.inc.sh
> chore(linux): improve output if `dpkg-gensymbols` fails and run other tests

- developer/docs/help/reference/file-types/kmp.md
- developer/docs/help/reference/file-types/kmx.md
> docs(developer): add refs to Keyman MIME types

- ios/Cartfile
- ios/Cartfile.resolved
updates cartfile to support ios builds with xcode 16
> chore(ios): support xcode 16 build

- android/KMAPro/kMAPro/src/main/res/values-km-rKH/strings.xml
- android/KMEA/app/src/main/res/values-km-rKH/strings.xml
- windows/src/desktop/kmshell/locale/km-KH/strings.xml
End of sprint task updating Crowdin strings submitted by @Meng-Heng 
> chore(android,windows): Update Crowdin strings for Khmer

- developer/src/tike/child/Keyman.Developer.UI.UframeWordlistEditor.pas
When pasting into the wordlist grid, the editor will now check if the clipboard text contains newlines or tabs, and if so, will paste the text as new rows in the wordlist (with a prompt), rather than pasting the whole text into the current cell.
If the clipboard text does not contain NL or TAB then the default in-cell editor paste handling will run.
Fixes: #12517
These tests should be run in the Wordlist grid view in the Lexical Model Editor. Create a new lexical model and open it in the Lexical Model Editor
* **TEST_PASTE_SIMPLE_STRING:** Copy a single word into the clipboard, and then paste it into a cell in the wordlist editor. It should just paste the word in without errors.
* **TEST_PASTE_MULTILINE_STRING:** Copy the text below to the clipboard, and then paste it into a cell in the …
> fix(developer): handle paste of TSV into Wordlist grid

- docs/websites/README.md
Relates-to: keymanapp/keyman.com#494
> docs: Update websites readme with debug info

- developer/src/kmc/src/util/getLastGitCommitDate.ts
Relates-to: keymanapp/keyboards#3143
Fixes: #12626
Fixes: KEYMAN-DEVELOPER-2AY
Cherry-pick-of: #12627
> fix(developer): handle merge commits when checking git log date 🍒 🏠

- resources/build/help-keyman-com.sh
Fixes failing release build https://build.palaso.org/buildConfiguration/Keyman_Build/503630?buildTab=log&linesState=1103.9643&logView=flowAware&focusLine=9841
> fix(windows): correct engine help source path for upload

- docs/CODEOWNERS
update per session
- add several to developer and to core
> chore(common): Update CODEOWNERS

- docs/build/windows.md
Added some steps to setting up and updating emscripten for building on windows. 
> docs(windows): update emscripten bash setup

- CONTRIBUTING.md
This is part of an action item from our Keyman conference.
> chore(common): Add link to onboarding doc to `CONTRIBUTING.md`

- developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts
> fix(developer): honour provided script when checking for matching scripts

- core/docs/api/index.md
This is part of an action item from our Keyman conference.
> chore(core): Add link to Keyman Glossary 🎄 

- android/KMAPro/kMAPro/src/main/res/values-it-rIT/strings.xml
- android/KMEA/app/src/main/res/values-it-rIT/strings.xml
- windows/src/desktop/kmshell/locale/it-IT/strings.xml
> chore(android,windows): Update crowdin for Italian

- android/KMAPro/kMAPro/src/main/res/values-cs-rCZ/strings.xml
- android/KMEA/app/src/main/res/values-cs-rCZ/strings.xml
- windows/src/desktop/kmshell/locale/cs-CZ/strings.xml
> chore(android,windows): Update crowdin for Czech

- developer/src/inst/build.sh
- developer/src/inst/node/dist/CHANGELOG.md
- developer/src/inst/node/dist/LICENSE
- developer/src/inst/node/dist/README.md
The node version must be an exact match at this time. Also updated node.exe accordingly.
Fixes: #12075
> chore(developer): verify bundled node version when building installer

- developer/src/kmc-analyze/src/osk-character-use/index.ts
- developer/src/kmc-kmn/src/compiler/osk.ts
> fix(developer): support hint property in displaymap

- docs/file-formats/kmx-file-format.md
> docs: clarify that sections in KMX file might not be aligned

- android/KMAPro/kMAPro/src/main/res/values-es-rES/strings.xml
- android/KMEA/app/src/main/res/values-es-rES/strings.xml
- ios/engine/KMEI/KeymanEngine/es.lproj/Localizable.strings
- mac/Keyman4MacIM/Keyman4MacIM/es.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/es-ES/strings.xml
> chore(common): Update crowdin strings for Spanish

- ios/engine/KMEI/KeymanEngine/km.lproj/Localizable.strings
Update crowdin strings for Khmer
Adds the strings for the new "Keyboard Height" menu
> chore(ios): Update crowdin strings for Khmer

- developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts
- developer/src/kmc-kmn/test/fixtures/kmw/error_touch_layout_invalid_identifier.keyman-touch-layout
- developer/src/kmc-kmn/test/fixtures/kmw/error_touch_layout_invalid_identifier.kmn
- developer/src/kmc-kmn/test/kmw/kmw-compiler.tests.ts
> fix(developer): detect invalid key ids in touch layout files

- HISTORY.md
- resources/build/increment-version.sh
- resources/build/version/src/fixupHistory.ts
- resources/build/version/src/index.ts
> chore: use GitHub PR titles when writing HISTORY.md

- resources/build/increment-version.sh
- resources/build/version/src/fixupHistory.ts
- resources/build/version/src/index.ts
> chore: use GitHub PR titles when writing HISTORY.md 🍒 🏠

- linux/debian/copyright
> chore(linux): update copyright year 🍒 🏠

- HISTORY.md
> chore(common): Add 17.0.333 to version history

- developer/src/server/build.sh
Fixes: #12950
TEST_DEVELOPER_SERVER: Test that Developer Server starts successfully and that you can test a keyboard in the web browser.
> fix(developer): include developer-utils deps in server build

- windows/src/desktop/kmshell/main/BackgroundUpdateStateDiagram.md
- windows/src/desktop/kmshell/main/Keyman.System.RemoteUpdateCheck.pas
- windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas
- windows/src/desktop/kmshell/main/UfrmMain.pas
These are some key tests for testing the update state machine. 
It also has a few fixes.
- Check now button uses the background update state machine instead of using the RemoteUpdateCheck unit. This now makes sure the state machine state moves to UpdateAvaiable, if there are new updates. (this should have already been checked in on the epic branch)
- The LastUpdateTimeCheck now correctly handles the case for when then the registry key does not exist. Treating it as if the time has expired since the last update.
- 
- Check for actuall class state rather than a the class name as a string.
- 
- Guard for if file has not been downloaded
- 
I am working on a spreadsheet that will be based on the state transition matrix to test more scenarios and failure states. 
1. Install the Keyman build …
> feat(windows): This is to provide a PR build for testing

- developer/src/common/web/utils/src/index.ts
- developer/src/common/web/utils/src/valid-ids.ts
- developer/src/common/web/utils/test/valid-ids.tests.ts
- developer/src/kmc-generate/package.json
- developer/src/kmc-generate/src/generator-messages.ts
- developer/src/kmc-generate/src/keyman-keyboard-generator.ts
- developer/src/kmc-generate/src/ldml-keyboard-generator.ts
- developer/src/kmc-generate/src/lexical-model-generator.ts
- developer/src/kmc-generate/test/generator-messages.tests.ts
> chore(developer): validate keyboard and model IDs in kmc-generate

- web/docs/engine/guide/examples/__auto-control.html
- web/docs/engine/guide/examples/__control-by-control.html
- web/docs/engine/guide/examples/__first-example.html
- web/docs/engine/guide/examples/__full-manual-control.html
- web/docs/engine/guide/examples/__manual-control.html
Part of: https://github.com/keymanapp/help.keyman.com/issues/1790
> chore: adds h1 tags

- developer/src/kmc-generate/test/basic-generator.tests.ts
- developer/src/kmc-generate/test/fixtures/basic/welcome.htm
> chore(developer): add test for basic transform to kmc-generate

- developer/src/kmc-copy/src/KeymanProjectCopier.ts
- developer/src/kmc-copy/src/copier-messages.ts
- developer/src/kmc-copy/test/messages.tests.ts
- developer/src/kmc-generate/src/generator-messages.ts
- developer/src/kmc/src/commands/messageCommand.ts
> chore(developer): validate output folder name in kmc-copy

- android/docs/engine/whatsnew.md
- android/docs/help/about/whatsnew.md
- ios/docs/help/about/whatsnew.md
- linux/docs/help/about/whatsnew.md
- mac/docs/help/about/whatsnew.md
- windows/docs/help/about/whatsnew.md
fixes: https://github.com/keymanapp/keyman/issues/12896.
> chore: add platform to what's new titles

- android/docs/help/about/history.md
- ios/docs/help/about/history.md
- linux/docs/help/about/history.md
- mac/docs/help/about/history.md
- windows/docs/help/about/history.md
fixes: https://github.com/keymanapp/keyman/issues/12896.
> chore: add platforms to version history titles

- android/docs/help/troubleshooting/index.md
- ios/docs/help/troubleshooting/index.md
- mac/docs/help/troubleshooting/index.md
- windows/docs/help/index.md
- windows/docs/help/troubleshooting/index.md
fixes: https://github.com/keymanapp/keyman/issues/12896.
> chore: add platforms to troubleshooting titles and windows to help homepage

- android/docs/help/start/installing-keyboards.md
- mac/docs/help/about/requirements.md
- mac/docs/help/start/install-keyboard.md
- windows/docs/help/about/requirements.md
- windows/docs/help/start/download-and-install-keyboard.md
- windows/docs/help/start/download-and-install-keyman.md
fixes: https://github.com/keymanapp/keyman/issues/12896.
> chore: add platforms to system requirements and download-and-install docs

- mac/docs/help/basic/index.md
- mac/docs/help/troubleshooting/uninstall-keyman.md
This Pull request fix #12896 and is ready for reviews.
> chore: add mac platform to titles

- ios/docs/engine/guides/in-app/index.md
- ios/docs/engine/guides/system-keyboard/index.md
- ios/docs/help/about/index.md
- ios/docs/help/basic/index.md
- ios/docs/help/context/gestures.md
- ios/docs/help/start/index.md
> chore: add ios platform to titles

- resources/build/increment-version.sh
> fix: use correct path for resources/build/version

- web/src/app/browser/src/hardwareEventKeyboard.ts
Fixes: #13011
Fixes: KEYMAN-COM-1MB
Fixes: KEYMAN-COM-1EM
Cherry-pick-of: #13013
> fix(web): add null guard for focusing next element via keystroke 🏠

- resources/build/increment-version.sh
Fixes: #12915
Cherry-pick-of: #13029
> fix: use correct path for resources/build/version 🍒 🏠

- common/web/keyboard-processor/src/text/kbdInterface.ts
- common/web/keyboard-processor/tests/node/engine/context.js
- common/web/keyboard-processor/tests/node/engine/notany_context.js
Cherry-pick-of: #12998.
Fixes: #12987.
> fix(web): do not simplify nul-prefixed contexts when rule-matching 🍒 🏠

- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java
- android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
- android/KMEA/app/src/main/java/com/keyman/engine/packages/PackageProcessor.java
> feat(android): add breadcrumbing during package install about package file, source 🏠

- web/src/app/browser/src/hardwareEventKeyboard.ts
> fix(web): add null guard for focusing next element via keystroke

- android/KMEA/app/src/main/java/com/keyman/engine/logic/ResourcesUpdateTool.java
> fix(android): improve resource-update tool handling of host Activity's closure 🍒 🏠

- ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
Fixes: KEYMAN-IOS-1J
Fixes: #13036
Cherry-pick-of: #13037
> fix(ios): prevent message-handler collision 🍒🏠

- android/KMAPro/kMAPro/src/main/res/values-b+es+419/strings.xml
- android/KMEA/app/src/main/res/values-b+es+419/strings.xml
- ios/engine/KMEI/KeymanEngine/es-419.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/es-419/strings.xml
> chore(common): Update crowdin strings for Spanish (Latin America)

- HISTORY.md
> chore(common): add 17.0.334 to version history

- resources/build/increment-version.sh
> chore: push the branch when creating PR in version history writer 🍒 🏠

- windows/docs/engine/api/index.md
- windows/docs/help/about/credits.md
- windows/docs/help/about/index.md
- windows/docs/help/about/license.md
- windows/docs/help/advanced/index.md
- windows/docs/help/basic/index.md
- windows/docs/help/basic/uninstall-keyboard.md
- windows/docs/help/basic/uninstall.md
- windows/docs/help/basic/update.md
- windows/docs/help/start/index.md
- windows/docs/help/start/tutorial.md
I am pushing my PRs as platform-based instead of multiple platform-based to help ease with reviewing. 
This Pull request consist of:
- Changed *Note* format
- Updated the version
- Updated the license
- Updated the credits
- Fixed #12896
> chore: add the windows platform to titles

- developer/src/tike/child/UfrmPackageEditor.dfm
- developer/src/tike/child/UfrmPackageEditor.pas
> chore(developer): handle forward slashes in paths in package editor

- developer/src/kmc-copy/src/KeymanProjectCopier.ts
- developer/src/kmc-copy/src/copier-messages.ts
> chore(developer): add verbose logs for project copier

- developer/docs/help/whats-new.md
> docs(developer): update what's new for 18.0

- mac/docs/help/about/whatsnew.md
> chore(mac): update whats new for Keyman 18

- ios/docs/help/about/whatsnew.md
> chore(ios): update whats new for Keyman 18

- resources/build/version/src/fixupHistory.ts
> fix: use tier and version from branch when merging history from another branch

- linux/docs/help/about/whatsnew.md
> docs(linux): update what's new for 18.0

- docs/build/linux-ubuntu.md
Small PR - Commit fbab6eb8cfe20fbd5681e2aa4e37357c58c925c0 moved `BUILDING.md`. This PR adjusts sources to changes.
> docs: update keyboard processor build source

- windows/docs/help/about/whatsnew.md
> docs(windows): update keyman for windows 18.0 whats-new

- android/KMAPro/kMAPro/src/main/res/values-mnw-rMM/strings.xml
- android/KMEA/app/src/main/res/values-mnw-rMM/strings.xml
- ios/engine/KMEI/KeymanEngine/mnw.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/mnw-MM/strings.xml
> chore(common): Update crowdin strings for Mon

- ios/engine/KMEI/KeymanEngine/cs.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/cs-CZ/strings.xml
> chore(ios,windows): Update Crowdin strings for Czech

- developer/src/kmc-ldml/src/util/serialize.ts
(cherry picked from commit 9a33a26d5ccbb3a4c1368646e5f466aad8cb3c93) from #13174 
> chore(developer):  XML serializer version bugfix cherrypick 🍒🍒 🗼 

- linux/ibus-keyman/src/test/run-tests.sh
- linux/ibus-keyman/tests/scripts/run-single-test.sh
- linux/ibus-keyman/tests/scripts/run-tests.sh
- linux/ibus-keyman/tests/scripts/test-helper.inc.sh
- update message when running tests
- improve the output if dependencies are missing
> chore(linux): improve output when running tests 🕷️

- linux/ibus-keyman/tests/testfixture.cpp
> refactor(linux): cleanup code of test fixture 🕷️

- web/docs/engine/guide/examples/__manual-control.html
- web/docs/engine/guide/examples/manual-control.md
> docs(web): use promise-chaining in manual-control example

- android/KMAPro/kMAPro/src/main/res/values-b+el/strings.xml
- android/KMEA/app/src/main/res/values-b+el/strings.xml
- ios/engine/KMEI/KeymanEngine/el.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/el-polyton/strings.xml
From follow-on discussion on https://github.com/keymanapp/keyboards/pull/3341#issuecomment-2666324768
User-request to update Polytonic Greek strings 
> chore(common): Update crowdin strings for Polytonic Greek

- .github/workflows/deb-packaging.yml
> fix(linux): add missing dependency for uploading to llso

- .github/workflows/deb-packaging.yml
> fix(linux): add missing dependency for uploading to llso 🍒

- linux/debian/control
> chore(linux): Update to new Debian policy version

- linux/keyman-config/keyman_config/dbus_util.py
- linux/keyman-config/tests/uninstall_kmp_tests.py
Also improve `dbus_util.py` code.
> refactor(linux): extract method for setting up mocks in tests

- linux/debian/control
> chore(linux): update to current Debian policy version

- windows/src/desktop/kmshell/locale/km-KH/strings.xml
> chore(windows): Update crowdin strings for Khmer

- resources/build/builder.md
These did not appear to be working, probably an earlier iteration of the doc, and reorganized some of the links
> docs: clean up links in builder.md

- web/src/app/browser/src/context/pageIntegrationHandlers.ts
- web/src/app/browser/src/debug-main.ts
- web/src/app/browser/src/keyboardInterface.ts
- web/src/app/browser/src/keymanEngine.ts
- web/src/app/browser/src/languageMenu.ts
- web/src/app/browser/src/oskConfiguration.ts
- web/src/app/browser/src/release-main.ts
- web/src/app/browser/src/test-index.ts
- web/src/app/browser/src/utils/rotationProcessor.ts
- web/src/app/browser/src/viewsAnchorpoint.ts
- web/src/app/webview/src/debug-main.ts
- web/src/app/webview/src/keymanEngine.ts
- web/src/app/webview/src/oskConfiguration.ts
- web/src/app/webview/src/release-main.ts
- web/src/engine/main/src/index.ts
- web/src/engine/main/src/keyboardInterface.ts
- web/src/engine/main/src/keymanEngineBase.ts
> refactor(web): rename base `KeymanEngine` to `KeymanEngineBase` 🎼

- developer/src/kmc/README.md
> docs(developer): fix typos in readme and add link

- developer/src/kmc/src/messages/infrastructureMessages.ts
> fix(developer): add folder text to Error_FileDoesNotExist message

- developer/src/common/web/utils/src/utils/options.ts
- developer/src/server/src/index.ts
> fix(developer): load Keyman Developer options in Server before use

- resources/build/trigger-builds.inc.sh
> chore: handle failure to retrieve GitHub PR status in build triggers

- core/src/kmx/kmx_plus.h
- docs/file-formats/kmx-plus-file-format.md
> fix(core): unalign `usetCount` and `rangeCount`

- android/KMAPro/kMAPro/src/main/res/values-b+es+419/strings.xml
- android/KMEA/app/src/main/res/values-b+es+419/strings.xml
- android/KMEA/app/src/main/res/values-es-rES/strings.xml
- windows/src/desktop/kmshell/locale/es-419/strings.xml
- windows/src/desktop/kmshell/locale/es-ES/strings.xml
> chore(android,windows): Update Crowdin for Spanish and Spanish (Latin America)

- common/include/test_assert.h
- core/tests/unit/ldml/kmx_plus.tests.cpp
- core/tests/unit/ldml/meson.build
- resources/build/meson/standard.meson.build
- also update test_assert.h to vector to GTest if present
- relates to #10996
> feat(core): move kmx_plus.tests.cpp to GTest 🙀 

- web/src/engine/osk/src/visualKeyboard.ts
While looking into something else, I happened to notice a few functions that are no longer used within the OSK's code.  
> chore(web): remove dead osk code

- common/windows/delphi/components/OnScreenKeyboard.pas
cherry pick of #13444
feat(windows): hard code key cap colour
> fix(windows): cherry pick hard code key cap 🍒 

- docs/file-formats/README.md
> docs(common): add link to schemas

- resources/docker-images/README.md
- resources/docker-images/base/Dockerfile
- resources/docker-images/build.sh
- resources/docker-images/docker-build.inc.sh
- resources/docker-images/run.sh
Also some general improvements for building and running Docker container.
> fix(linux): fix building in Docker with different Ubuntu/Debian version ⛵

- developer/src/kmc-kmn/README.md
> chore(developer): establish ng-compiler 🤔

- mac/Keyman4MacIM/Keyman4MacIM/it.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/it-IT/strings.xml
> chore(mac,windows): Update Crowdin strings for Italian

- linux/ibus-keyman/src/engine.c
> docs(linux): add function headers for some of the engine methods

- android/KMEA/app/src/main/res/values-cs-rCZ/strings.xml
- mac/Keyman4MacIM/Keyman4MacIM/cs.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/cs-CZ/strings.xml
> chore(android,mac,windows): update Crowdin strings for Czech

- android/KMEA/app/src/main/res/values-km-rKH/strings.xml
- mac/Keyman4MacIM/Keyman4MacIM/km.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/km-KH/strings.xml
> chore(android,mac,windows): update Crowdin strings for Khmer

- android/KMAPro/kMAPro/src/main/res/values-b+es+419/strings.xml
- mac/Keyman4MacIM/Keyman4MacIM/es-419.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/es-419/strings.xml
> chore(android,mac,windows): Update crowdin strings for Spanish Latin America

- common/schemas/kps/kps.xsd
See https://github.com/keymanapp/api.keyman.com/pull/275/commits/53e6367fe59df513df2dfb49ec5f8ab8538f0f8b
> chore: cleanup kps.xsd version typos

- windows/docs/help/common/os.md
- windows/docs/help/common/requirements.md
- windows/docs/help/index.md
- add link to Linux
- reword some questions in the Windows main index
- explicitly mention Windows in `requirements.md` to make it clear that this is for Windows only
- update `os.md` since Windows on Arm is no longer in preview
> docs(windows): update FAQ

- web/src/app/browser/src/contextManager.ts
- web/src/app/browser/src/keyboardInterface.ts
- web/src/app/browser/src/keymanEngine.ts
- web/src/app/browser/src/test-index.ts
- web/src/app/webview/src/keymanEngine.ts
- web/src/engine/main/src/index.ts
- web/src/engine/main/src/keyboardInterfaceBase.ts
- web/src/engine/main/src/keymanEngineBase.ts
> refactor(web): rename `KeyboardInterface` → `KeyboardInterfaceBase` 🎼

- resources/build/history/history-utils.sh
- resources/build/trigger-definitions.inc.sh
> chore: trigger-definitions for 18.0 comment 🏠

- HISTORY.md
> chore: merge beta version 18.0.235 history to master

- docs/CODEOWNERS
> comment out CODEOWNERS

- .github/workflows/deb-packaging.yml
> change(linux): add link to issue

- web/build.sh
- web/src/engine/osk/build.sh
- web/src/engine/osk/gesture-processor/build.sh
- web/src/test/manual/build.sh
- web/src/tools/build.sh
Fixes: #12735
A few cases weren't properly handled, while a few others simply weren't called by the top-level script.  This PR seeks to make the top-level clean action able to fully clean all built components, perhaps save for sample and test pages.
Test-bot: skip
> chore(web): improve clean actions

- web/build.sh
- web/ci.sh
- web/common.inc.sh
- web/src/app/browser/build.sh
- web/src/app/ui/build.sh
- web/src/app/webview/build.sh
- web/src/engine/attachment/build.sh
- web/src/engine/common/web-utils/build.sh
- web/src/engine/dom-utils/build.sh
- web/src/engine/element-wrappers/build.sh
- web/src/engine/events/build.sh
- web/src/engine/interfaces/build.sh
- web/src/engine/js-processor/build.sh
- web/src/engine/keyboard-storage/build.sh
- web/src/engine/keyboard/build.sh
- web/src/engine/main/build.sh
- web/src/engine/osk/build.sh
- web/src/engine/osk/gesture-processor/build.sh
- web/src/engine/predictive-text/build.sh
- web/src/engine/predictive-text/templates/build.sh
- web/src/engine/predictive-text/wordbreakers/build.sh
- web/src/engine/predictive-text/worker-main/build.sh
- web/src/engine/predictive-text/worker-main/unit_tests/test.sh
- web/src/engine/predictive-text/worker-thread/build.sh
- web/src/samples/build.sh
- web/src/test/manual/build.sh
- web/src/tools/build.sh
- web/test.sh
> chore(web): replace --ci flag with builder_is_ci_build

- web/src/engine/common/web-utils/.eslintrc.cjs
- web/src/engine/common/web-utils/src/kmwstring.ts
This removes the exception in #13797 for KMWString, properly including the newly-refactored code in linting as well.
> change(web): lint kmwstring web-utility 🧶 

- linux/ibus-keyman/meson.build
Co-authored-by: Nikita Moor <nikita@lreis.ac.cn>
Fixes: #13814
Test-bot: skip
> change(linux): add ICU dependency needed to build on Arch Linux

- web/src/engine/osk/src/lengthStyle.ts
- web/src/engine/osk/src/views/oskView.ts
Fixes: #13766.
Cherry-pick-of: #13774 
> fix(web): add robustness for bad touch-layout fontsize specs 🍒  🏠

- docs/builder.md
- resources/build/README.md
Follow-up-of: #13810
Test-bot: skip
> docs(common): document new `builder_is_running_on_teamcity` function

- docs/builder.md
> docs(common): update `builder_echo` documentation for TC blocks

- web/src/engine/osk/src/views/oskView.ts
- web/src/engine/osk/src/visualKeyboard.ts
Fixes: #13859
Fixes: KEYMAN-WEB-R4
> fix(web): sustain active batched-layout mode when keyboard is switched

- web/src/engine/osk/src/views/oskView.ts
- web/src/engine/osk/src/visualKeyboard.ts
Fixes: #13859
Fixes: KEYMAN-WEB-R4
Cherry-pick-of: #13860
> fix(web): sustain active batched-layout mode when keyboard is switched 🍒  🏠

- developer/src/server/build.sh
- resources/stats/stats.sh
While ngrok.exe was already removed, ngrok (mac? linux?) was still present in node_modules.
Fixes: #13846
Cherry-pick-of: #13847
Test-bot: skip
> fix(developer): remove ngrok binary at build time 🍒 🏠

- docs/CODEOWNERS
Cherry-pick-of: #13739
Cherry-pick-of: #13801
Test-bot: skip
> maint(common): apply new codeowners from master 🍒 🏠

- resources/build/README.md
> docs(common): update readme link to builder.md

- mac/Keyman4MacIM/Keyman4MacIM/it.lproj/Localizable.strings
- windows/src/desktop/kmshell/locale/it-IT/strings.xml
:cherries: pick of #13871 to stable-18.0 updating Crowdin strings for Italian
Test-bot: skip
> chore(mac,windows): Update Crowdin strings for Italian 🏠

- linux/keyman-system-service/resources/VERSION_WITH_TAG.md
> maint(linux): remove generated file that got accidentally committed

- resources/builder.inc.sh
Sometimes a builder script can be redirected internally and then error messages are lost in the redirect if the script fails. This sidesteps that problem by reporting errors to stderr instead of stdout.
Test-bot: skip
> maint(common): report builder errors to stderr

- developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts
- developer/src/kmc-ldml/src/compiler/meta.ts
- developer/src/kmc-ldml/test/meta.tests.ts
- made the 'x' parameter optional for some cases
Fixes: #10622
> feat(developer):  add line number for MetaCompiler 🙀 

- linux/scripts/deb-packaging.sh
> maint(linux): fix logging in `deb-packaging.sh`

- linux/scripts/package-build.inc.sh
- resources/docker-images/build.sh
- resources/teamcity/README.md
- resources/teamcity/includes/tc-actions.inc.sh
- resources/teamcity/includes/tc-linux.inc.sh
- resources/teamcity/keyman-linux-release.sh
- resources/teamcity/keyman-linux-test-integration.sh
- resources/teamcity/keyman-linux-test.sh
This change adds scripts for the TeamCity build configurations for Linux builds.
> maint(common): move TC build configs for Linux to scripts 🌇

- developer/src/server/build.sh
- resources/stats/stats.sh
While ngrok.exe was already removed, ngrok (mac? linux?) was still present in node_modules.
Fixes: #13846
Test-bot: skip
> fix(developer): remove ngrok binary at build time

- web/src/app/browser/src/context/pageIntegrationHandlers.ts
- web/src/app/browser/src/debug-main.ts
- web/src/app/browser/src/keyboardInterface.ts
- web/src/app/browser/src/keymanEngine.ts
- web/src/app/browser/src/languageMenu.ts
- web/src/app/browser/src/oskConfiguration.ts
- web/src/app/browser/src/release-main.ts
- web/src/app/browser/src/test-index.ts
- web/src/app/browser/src/utils/rotationProcessor.ts
- web/src/app/browser/src/viewsAnchorpoint.ts
- web/src/app/webview/src/debug-main.ts
- web/src/app/webview/src/keymanEngine.ts
- web/src/app/webview/src/oskConfiguration.ts
- web/src/app/webview/src/release-main.ts
- web/src/engine/main/src/index.ts
- web/src/engine/main/src/keyboardInterface.ts
- web/src/engine/main/src/keymanEngineBase.ts
Cherry-pick-of: #13404 
Test-bot: skip
> refactor(web): rename base `KeymanEngine` to `KeymanEngineBase` 🎼🍒

- linux/keyman-system-service/src/OrderedOutputDevice.h
Test-bot: skip
Fixes: #13911
Cherry-pick-of: #13962
> fix(linux): use correct header guard define in OrderedOutputDevice.h 🍒 🏠

- .github/actions/build-binary-packages/action.yml
- .github/workflows/api-verification.yml
- .github/workflows/deb-packaging.yml
> maint(linux): update GHA dependencies for Linux package builds

- oem/firstvoices/ios/exportAppStore.plist
update public key for new FirstVoices certificate
Test-bot: skip
> chore(ios): FirstVoices certificate update

- oem/firstvoices/ios/exportAppStore.plist
update public key for new FirstVoices certificate
Cherry-pick: #13991
Test-bot: skip
> chore(ios): FirstVoices certificate update 🍒 🏠 

- ios/engine/KMEI/KeymanEngine/Classes/Errors/SentryManager.swift
- ios/engine/KMEI/KeymanEngine/Classes/Manager.swift
- ios/engine/KMEI/KeymanEngine/Classes/SettingsViewController.swift
> feat(ios): log active keyboard, model IDs with reported errors 🍒  🏠

- README.md
> docs(common): update README with number of languages and keyboards

- windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas
Cherry-pick of #13984
Fixes: #13771
> fix(windows): only breadcrumb unexpected state on first run 🍒  🏠

- web/src/engine/keyboard/src/keyboards/keyboardLoaderBase.ts
Browsers don't support comparing arrays. 
Test-bot: skip
> fix(web): fix loading of KMX keyboards in browser 🎼

- windows/src/desktop/kmshell/main/Keyman.System.RemoteUpdateCheck.pas
- windows/src/desktop/kmshell/main/Keyman.System.UpdateStateMachine.pas
- windows/src/desktop/kmshell/main/initprog.pas
Cherry-pick-of: #14027
Test-bot: skip
> fix(windows): fix sentry error message reporting 🍒🏠

- developer/docs/internal/developer-messaging.md
> docs(developer): add compiler message internal documentation

- developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts
- developer/src/kmc-ldml/src/compiler/vars.ts
- developer/src/kmc-ldml/test/vars.tests.ts
- some are remaining without errors
This is for #13936 but does not resolve all items
> feat(developer): add line numbers to vars compiler

- developer/src/kmc-ldml/test/compiler-e2e.tests.ts
Adds a unit test for #14068
Fixes: #14068
> fix(developer): ldml: make sure .run() calls compile() with postValidation

- developer/src/kmc-ldml/src/compiler/disp.ts
- developer/src/kmc-ldml/src/compiler/empty-compiler.ts
- developer/src/kmc-ldml/src/compiler/keys.ts
- developer/src/kmc-ldml/src/compiler/layr.ts
- developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts
- developer/src/kmc-ldml/src/compiler/tran.ts
- developer/src/kmc-ldml/test/compiler-e2e.tests.ts
- developer/src/kmc-ldml/test/disp.tests.ts
- developer/src/kmc-ldml/test/helpers/index.ts
- developer/src/kmc-ldml/test/keys.tests.ts
- developer/src/kmc-ldml/test/layr.tests.ts
- developer/src/kmc-ldml/test/messages.tests.ts
- developer/src/kmc-ldml/test/strs.tests.ts
- developer/src/kmc-ldml/test/tran.tests.ts
> chore(developer): ldml: messages cleanup

- web/src/app/browser/src/hardwareEventKeyboard.ts
> docs(web): update function comment for `preprocessKeyboardEvent` 🎼

- .gitattributes
- docs/build/linux-ubuntu.md
- resources/docker-images/README.md
- resources/docker-images/android/Dockerfile
- resources/docker-images/base/Dockerfile
- resources/docker-images/build.sh
- resources/docker-images/core/Dockerfile
- resources/docker-images/developer/Dockerfile
- resources/docker-images/docker-build.inc.sh
- resources/docker-images/linux/Dockerfile
- resources/docker-images/run.sh
- resources/docker-images/web/Dockerfile
Also update build documentation. 
Fixes: #14045
Test-bot: skip
> maint(developer): add docker image to build developer node modules

- resources/teamcity/developer/keyman-developer-release.sh
Export the newly introduced variables so that they are available in the powershell script.
Fixes: #14150
Follow-up-of: #14052
Test-bot: skip
> maint(developer): export environment variables

- .github/workflows/pr-build-status.yml
- resources/build.sh
- resources/build/pr-build-status/build.sh
- resources/build/pr-build-status/pr-build-status.mjs
- resources/build/pr-build-status/pr-build-status.prefix.yml
- resources/build/pr-build-status/pr-build-status.tests.mjs
Also:
* retrieves the correct SHA from each workflow event.
* builds pr-build-status.yml from primary version in resources/build
Test-bot: skip
> maint(resources): support additional workflow events for pr-build-status

- common/web/types/src/kmx/kmx-plus/element-string.ts
- common/web/types/src/kmx/kmx-plus/kmx-plus.ts
- common/web/types/src/ldml-keyboard/unicodeset-parser-api.ts
- common/web/types/src/main.ts
- common/web/types/src/util/types.ts
- common/web/types/src/util/util.ts
- developer/docs/internal/developer-messaging.md
- developer/src/common/web/utils/src/compiler-interfaces.ts
- developer/src/common/web/utils/src/developer-utils-messages.ts
- developer/src/common/web/utils/src/index.ts
- developer/src/common/web/utils/src/symbol-utils.ts
- developer/src/common/web/utils/src/xml-utils.ts
- developer/src/kmc-kmn/src/compiler/compiler.ts
- developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
- developer/src/kmc-ldml/src/compiler/disp.ts
- developer/src/kmc-ldml/src/compiler/empty-compiler.ts
- developer/src/kmc-ldml/src/compiler/keys.ts
- developer/src/kmc-ldml/src/compiler/layr.ts
- developer/src/kmc-ldml/src/compiler/ldml-compiler-messages.ts
- developer/src/kmc-ldml/src/compiler/loca.ts
- developer/src/kmc-ldml/src/compiler/meta.ts
- developer/src/kmc-ldml/src/compiler/substitution-tracker.ts
- developer/src/kmc-ldml/src/compiler/tran.ts
- developer/src/kmc-ldml/src/compiler/vars.ts
- developer/src/kmc-ldml/test/helpers/compareXml.ts
- rename ObjectWithMetadata to ObjectWithCompileContext
- fixup docs in boxXmlArray
- rename 'x' property and parameter to 'compileContext'
Fixes: #14117
> chore(common,developer): expand 'x' to 'compileContext'

- resources/teamcity/developer/keyman-developer-release.sh
Build-bot: build developer
Test-bot: skip
> refactor(developer): use shared `upload_help` function

- resources/teamcity/includes/tc-download-info.inc.sh
- add shebang so that shellcheck knows what shell we use 
- fix line endings
Test-bot: skip
> refactor(common): improve downloads include script

- ios/build.sh
- resources/teamcity/includes/tc-mac.inc.sh
- resources/teamcity/ios/ios-actions.inc.sh
- resources/teamcity/ios/keyman-ios-release.sh
- resources/teamcity/ios/keyman-ios-test-samples.sh
- resources/teamcity/ios/keyman-ios-test.sh
Fixes: #14189
Build-bot: release ios
Test-bot: skip
> maint(ios): add TC build scripts for iOS 🪶

- resources/build/build-utils-ci.test.sh
- resources/build/test/build.sh
- resources/build/test/builder-deps.test.sh
- resources/build/test/debug-deps/child/build.sh
- resources/build/test/debug-deps/child/dep/build.sh
- resources/build/test/debug-deps/dep/build.sh
- resources/build/test/debug-deps/dep/child/build.sh
- resources/build/test/debug-deps/test.sh
- resources/build/test/dependencies/test.sh
- resources/build/test/test.sh
- resources/build/test/trees/build.sh
- resources/build/test/trees/child1/build.sh
- resources/build/test/trees/dep/build.sh
Also adjust scripts to output standard pass message.
Test-bot: skip
> maint(resources): add `build.sh` to run all `resource/build/test` tests

- resources/build/test/zip.inc.tests.sh
Some cleanup and better use of functionality of testing framework.
Test-bot: skip
> test(common): improve zip tests

- linux/ibus-keyman/tests/scripts/run-tests.sh
- linux/ibus-keyman/tests/scripts/test-helper.inc.sh
> refactor(linux): remove shellcheck warnings

- linux/keyman-system-service/tests/README.md
> docs(linux): update readme for test service

- developer/src/server/package.json
- package-lock.json
Relates-to: #14373
Test-bot: skip
> chore(developer): upgrade multer to 2.0.2 🏠

- linux/ibus-keyman/tests/dbus-test-server/KmDbusTestServer.cpp
> maint(linux): fix stopping of test server

- developer/src/common/web/utils/build.sh
- developer/src/kmc-analyze/build.sh
- developer/src/kmc-copy/build.sh
- developer/src/kmc-generate/build.sh
- developer/src/kmc-keyboard-info/build.sh
- developer/src/kmc-kmn/build.sh
- developer/src/kmc-ldml/build.sh
- developer/src/kmc-model-info/build.sh
- developer/src/kmc-model/build.sh
- developer/src/kmc-package/build.sh
- developer/src/kmc/build.sh
- docs/builder.md
- resources/build/typescript.inc.sh
- resources/build/utils.inc.sh
Fixes: #14448
Build-bot: build
Test-bot: skip
> maint(common): move typescript script functions into typescript.inc.sh 🐸

- docs/builder.md
Relates-to: https://github.com/keymanapp/keyman/pull/14449#discussion_r2265813020
Test-bot: skip
> docs(resources): add note on builder-basic vs builder-full

- .github/workflows/deb-packaging.yml
Fixes: #14512
Test-bot: skip
Build-bot: build
> maint(linux): import only one of builder-basic and build-utils in deb-packaging

- .github/workflows/auto-merge-keyman-server-pr.yml
Test-bot: skip
Follows: #14504
> maint(resources): use GH builtin automerge for auto PRs

- .github/workflows/auto-merge-keyman-server-pr.yml
Test-bot: skip
Follows: #14519
Relates-to: #14521
> maint(resources): use GH_TOKEN variable for gh calls

- .github/workflows/auto-merge-keyman-server-pr.yml
Follows: #14522
Test-bot: skip
> maint(resources): specify `keymanapp/keyman` for gh in automerge

- .github/workflows/auto-merge-keyman-server-pr.yml
"--merge, --rebase, or --squash required when not running interactively"
Follows: #14524
Test-bot: skip
> maint(resources): `gh pr merge` requires merge flag in auto-merge GHA

- resources/build/increment-version.sh
Follows: #14526
Test-bot: skip
> maint(resources): add space to test-bot command

- linux/keyman-config/km-package-install
- linux/keyman-config/km-package-install.bash-completion
> refactor(linux): cleanup some code in bash completion script

- resources/build/increment-version.sh
See #14588 for example of working PR.
Test-bot: skip
Cherry-pick-of: #14595
> maint(resources): automatically cherry-pick history updates to master 🏠

- HISTORY.md
> auto: cherry-pick 18.0.241 history to alpha

- windows/src/README.md
> chore(windows): establish epic/win-arm

- android/KMEA/app/src/main/assets/other-polyfills.js
Fixes: #14450
TEST_REPRO_ISSUE:  Attempt to repro the original issue and verify that the keyboard is visible.
- Install on Android device/emulator Android API 28.
- Observe the keyboard is visible after the app launches.
> fix(android): polyfill globalThis for API 28 devices

- resources/build/ci/github/api-pull-commits.mjs
- resources/build/ci/github/package-lock.json
- resources/build/ci/github/package.json
- resources/teamcity/triggers/trigger-test-builds.sh
Test-bot: skip
Build-bot: skip build:common
Cherry-pick-of: #14631 (last commit)
> feat: support pagination in build bot PR commit reading

- linux/scripts/launchpad.sh
- linux/scripts/package-build.inc.sh
- resources/teamcity/linux/keyman-linux-release.sh
> refactor(linux): remove shellcheck warnings and reformat

- oem/firstvoices/windows/src/inst/build.sh
- windows/src/desktop/inst/build.sh
Build-bot: skip build:windows
Test-bot: skip
> maint(windows): for `build` buildlevel, do not publish artifacts

- resources/teamcity/linux/keyman-linux-test-integration.sh
- resources/teamcity/linux/keyman-linux-test.sh
> maint(linux): skip tarball creation for `Build-bot: build` buildLevel

- developer/src/inst/build.sh
Note: corresponding change for test bot is on its way.
Note: see #14703 for a refactor of the filename version string.
Relates-to: #10521
Test-bot: skip
Build-bot: skip release:developer
> maint(developer): use versioned filenames for PR artifacts

- developer/docs/help/reference/file-types/metadata.md
> docs(developer): document `fileVersion`

- linux/keyman-config/keyman_config/__init__.py
- linux/keyman-config/keyman_config/downloadkeyboard.py
- linux/keyman-config/keyman_config/get_kmp.py
- linux/keyman-config/keyman_config/gnome_keyboards_util.py
- linux/keyman-config/keyman_config/handle_install.py
- linux/keyman-config/keyman_config/install_kmp.py
- linux/keyman-config/keyman_config/kmpmetadata.py
- linux/keyman-config/keyman_config/sentry_handling.py
- linux/keyman-config/km-config
- add breadcrumbs with keyboard details 
- add some more information about system 
- some refactorings
Test-bot: skip
> feat(linux): add breadcrumbs and system information to Sentry error reports

- linux/docs/help/about/whatsnew.md
Follows: #14773
Test-bot: skip
> docs(linux): update release notes for stable release 🏠

- resources/docker-images/docker-build.inc.sh
- resources/docker-images/run.sh
> refactor(resources): use array for Docker arguments
