common/windows/delphi/packages/PackageInfo.pas

Fixes #8595.
* **TEST_RTL_CHECKBOX:** Following the steps below, ensure that the "Is Right-to-left" checkbox for the lexical model always matches the source view value for `RTL`.
1. Create a new lexical model and open the .kps file.
2. Go to the "Lexical Models" section/tab.
3. Check "Is Right-to-left" by clicking on it.
4. Go to the "Source" section/tab and verify that `<RTL>True</RTL>` is present in the lexical models section.
5. Return to "Lexical Models", "Is Right-to-left" should remain checked.
6. Repeat these steps, with the RTL checkbox _off_ and confirm that the Source and Lexical Models tabs match up.

fix(developer): package editor no longer loses RTL flag for LMs

---

developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmcmplib/src/CompilerInterfaces.cpp

Fixes #8615.
The msgproc was never being located as we were missing the UTF8ToString wrapper for the context.
This also ensures error message codes are emitted in hexadecimal, and that the return value from the msgproc callback is 1, meaning 'continue build'.

fix(developer): kmc-kmn would abort build on warnings

---

developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/build/BuildActivity.ts
developer/src/kmc/src/commands/build/BuildKmnKeyboard.ts
developer/src/kmc/src/commands/build/BuildLdmlKeyboard.ts

Adds --compiler-warnings-as-errors and --no-warn-deprecated-code options to kmc command line and interfaces.
Note that most compilers do not yet honour these options, only kmc-kmn.
Both of these should be handled in error filtering and reporting rather than at the compiler level, so management of these may be factored out of kmcmplib and into kmc later (although this goal may be blocked by kmcmpdll's need to also use them).

feat(developer): add warning options to kmc

---

common/web/types/src/main.ts
common/web/types/src/util/compiler-interfaces.ts
developer/src/kmc-keyboard/package.json
developer/src/kmc-keyboard/src/compiler/messages.ts
developer/src/kmc-keyboard/test/test-messages.ts
developer/src/kmc-kmn/package.json
developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-kmn/src/compiler/messages.ts
developer/src/kmc-kmn/test/helpers.ts
developer/src/kmc-kmn/test/test-compiler.ts
developer/src/kmc-kmn/test/tsconfig.json
developer/src/kmc-model/package.json
developer/src/kmc-package/package.json
developer/src/kmc/package.json
developer/src/kmc/src/commands/build/BuildKmnKeyboard.ts
developer/src/kmc/src/util/NodeCompilerCallbacks.ts

Moves to using the `reportMessage` callback for reporting all errors in kmc-kmn.
This required some patching to common/web/types in order to get the new constants in place and add support for line numbers to `CompilerEvent`, so at the same time I refactored `compilerErrorSeverityName` into the module.
After the refactor, coverage tests were failing because they included the test/ folder, so cleaned that up at the same time.

feat(developer): use new message infrastructure in kmc-kmn

---

developer/src/kmc-package/src/kmp-compiler.ts
developer/src/kmc-package/src/messages.ts
developer/src/kmc-package/test/fixtures/absolute_path/source/absolute_path.kps
developer/src/kmc-package/test/test-package-compiler.ts
developer/src/kmc/src/commands/build/BuildPackage.ts
developer/src/kmc/src/kmlmi.ts
developer/src/kmc/src/kmlmp.ts

Relates to #8150.
Adds basic infrastructure for CompilerMessages events, along with file-existence check and absolute path warnings. Additional warnings,
errors, and hints to come.

feat(developer): add CompilerMessages support to kmc-package

---

common/web/input-processor/build.sh
web/test.sh

Not sure why both `kmc` and `kmc-model` were being built; only the latter is needed.  Also, now that `kmc-model` has a builder-based script, we can directly use builder dependencies to link it in.

chore(web): sets kmc-model as dependency of input-processor test action

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java
android/KMEA/app/src/main/java/com/keyman/engine/KMTextView.java

Fixes #8556 and continuing refactor in #7881
> The bug was introduced during the consolidation in #8438 where `KMManager.SystemKeyboardShouldIgnoreSelectionChange` gets set, but never `KMManager.InAppKeyboardShouldIgnoreSelectionChange`. This was causing resetContext to trigger on every change.
I also note these are never set to true, but am not addressing on this PR:
* KMManager.InAppKeyboardShouldIgnoreTextChange
* KMManager.SystemKeyboardShouldIgnoreTextChange
*Setup* - Install the PR build of Keyman for Android and also install the Keyman keyboard kbd_basicfr (Basic French) on an Android device/emulator. Set Keyman as the default system keyboard. Note - if pressing the shift layer deletes selected keys, that's already a known issue #7866.
**GROUP_INAPP** - Verifies inapp keyboard. Use …

fix(android/engine): Fix resetContext calls when selection changes

---

developer/src/kmc/src/commands/build/BuildPackage.ts

This was breaking core build due to a broken path ref

fix(developer): kmc-package path reference

---

developer/src/kmcmplib/build.sh
developer/src/kmcmplib/commands.inc.sh
developer/src/kmcmplib/meson_options.txt
developer/src/kmcmplib/tests/README.md
developer/src/kmcmplib/tests/meson.build

If kmcmplib build includes the --full-test flag, then configure and run tests that include pulling in the keyboards repo; otherwise skip all of that.
This will require CI changes to run full tests, relating to #8361.

chore(developer): only run keyboards-repo tests for a full-test

---

common/web/types/src/main.ts
common/web/types/src/util/compiler-interfaces.ts
common/web/types/test/helpers/index.ts
common/web/types/test/helpers/reader-callback-test.ts
common/web/types/test/kpj/test-kpj-file-reader.ts
common/web/types/test/kvk/test-kvk-round-trip.ts
common/web/types/test/kvk/test-kvks-file.ts
developer/src/common/web/test-helpers/index.ts
developer/src/kmc-keyboard/src/compiler/compiler.ts
developer/src/kmc-keyboard/test/helpers/index.ts
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/build/BuildActivity.ts
developer/src/kmc/src/commands/build/BuildKmnKeyboard.ts
developer/src/kmc/src/commands/build/BuildLdmlKeyboard.ts
developer/src/kmc/src/commands/build/BuildModel.ts
developer/src/kmc/src/commands/build/BuildPackage.ts
developer/src/kmc/src/commands/build/BuildProject.ts
developer/src/kmc/src/commands/buildTestData/index.ts
developer/src/kmc/src/kmlmc.ts
developer/src/kmc/src/kmlmi.ts
developer/src/kmc/src/kmlmp.ts
developer/src/kmc/src/messages/NodeCompilerCallbacks.ts
developer/src/kmc/src/messages/messages.ts

Cleans up majority of remaining kmc-* modules to use CompilerEvent messages instead of console.log and friends, adding InfrastructureMessages class for kmc CLI messages.
Consolidates schema loading functions into a single `loadSchema` function in the CompilerCallbacks interface and implementations.
Moves responsibility for instantiating NodeCompilerCallbacks out of each individual BuildActivity and into higher level modules.
Fixes return value for failing builds.

feat(developer): use CompilerEvent for messages in all of kmc

---

developer/build.sh
developer/src/common/web/test-helpers/build.sh
developer/src/kmc-keyboard/build.sh
developer/src/kmc-kmn/build.sh
developer/src/kmc-model/build.sh
developer/src/kmc-model/package.json
developer/src/kmc-model/test/tsconfig.json
developer/src/kmc-package/build.sh
developer/src/kmc-package/package.json
developer/src/kmc-package/test/tsconfig.json

Note: also adds rudimentary top-level developer build script, just for building kmc + friends. Its primary use right now is to run `developer/build.sh test` as that will run tests on all modules (building happens through child dep relationships for kmc anyway)

chore(developer): fixup deps for kmc modules

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Fixes  #8639 and maybe fixes/addresses #8548 too  (part of #7881 refactoring)
Regression introduced in #8483 
It turns out the Keyman app is recreated when changing the Display Language. So we can't reuse the inappInputConnection handle.
Setup - Install PR build of Keyman for Android
* **TEST_CHANGING_DISPLAY_LANGUAGE** - Verifies inapp keyboard works after changing display language
1. Open Keyman In-App.
2. Type a word (eg., Testing) in the text input screen.
3. We may notice that the typed word appears on the screen.
4. Change the Display Language into Amharic.
6. Revert to Home Screen.
7. Type a word (eg., testing) in the text input screen.
8. Verify typed text appears
* **TEST_SETTING_SYSTEM_KETYBOARD** -  Verifies inapp keyboard works after setting Keyman as system keyboard
1. …

fix(android/engine): Update InApp input connection 🛋

---

android/KMAPro/kMAPro/build.gradle
android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMEA/app/build.gradle
android/KMEA/app/src/main/AndroidManifest.xml
android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample1/app/src/main/AndroidManifest.xml
android/Samples/KMSample2/app/build.gradle
android/Samples/KMSample2/app/src/main/AndroidManifest.xml
android/Tests/KeyboardHarness/app/build.gradle
android/Tests/KeyboardHarness/app/src/main/AndroidManifest.xml
android/Tests/keycode/app/build.gradle
android/Tests/keycode/app/src/main/AndroidManifest.xml
oem/firstvoices/android/app/build.gradle
oem/firstvoices/android/app/src/main/AndroidManifest.xml

Addresses a small part of #5272.
Gradle warns that declaring package names in AndroidManifest.xml files are deprecated.
They should now be declared as namespaces in the build.gradle files.

chore(android): Move namespace to Gradle files

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardWebViewClient.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

This addresses a TODO of moving KMManager.currentBanner to KMKeyboard.
**Setup** - Install the PR build of Keyman for Android on an Android emulator/device. From Keyman, also install a keyboard that doesn't have a dictionary (e.g. basic_kbdfr).
* **TEST_INAPP_ADJUST_KEYBOARD_HEIGHT** - Verifies keyboard height can be adjusted
2. From Keyman Settings --> Adjust the keyboard height to the max
3. Return to Keyman
4. Verify the keyboard height is now the adjusted keyboard height. (Note, keyboard height doesn't include the suggestion banner height)
* **TEST_INAPP_BANNER_TOGGLES** - Verifies banner toggles for INAPP keyboard
2. Select sil_euro_latin keyboard
3. Verify suggestion banner appears
4. With the globe button, switch to …

refactor(android/engine): Move currentBanner to KMKeyboard

---

android/KMEA/app/build.gradle

More gradle cleanup
The Robolectric issue seems resolved and jvm workaround can be removed.

chore(android/engine): Remove jvm args

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

More refactoring for #7881 
This moves KMManager.toggleSuggestionBanner to KMKeyboard.
Tests copied from #8671
**Setup** - Install the PR build of Keyman for Android on a device/emulator. From Keyman, also install a keyboard that doesn't have a dictionary (e.g. basic_kbdfr).
* **TEST_INAPP_BANNER_TOGGLES** - Verifies banner toggles for INAPP keyboard
2. Select sil_euro_latin keyboard
3. Verify suggestion banner appears
4. With the globe button, switch to basic_kbdfr
5. Verify the suggestion banner disappears
6. With the globe button, switch to sil_euro_latin
7. Verify suggestion banner reappears
8. From Keyman Settings --> Installed Languages --> English --> Disable predictions
9. Return to Keyman
10. Verify suggestion banner disappears
11. From Keyman …

refactor(android/engine): Move toggleSuggestionBanner to KMKeyboard 🛋

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

More refactoring for #7881
Update `KMManager.isKeyboardLoaded()` with null check and replaces many calls in KMManager to make it easier to read.
from: `InAppKeyboard != null && InAppKeyboardWebViewClient.getKeyboardLoaded()`
to: `isKeyboardLoaded(KeyboardType.KEYBOARD_TYPE_INAPP)`
and from `SystemKeyboard != null && SystemKeyboardWebViewClient.getKeyboardLoaded()`
to: `isKeyboardLoaded(KeyboardType.KEYBOARD_TYPE_SYSTEM)`
**Setup** - Install the PR build of Keyman for Android on device/emulator. Also install keyboard (e.g. basic_kbdfr) that doesn't have a dictionary
* **TEST_INAPP_BANNER_TOGGLES** - Verifies banner toggles for INAPP keyboard
2. Select sil_euro_latin keyboard
3. Verify suggestion banner appears
4. With the globe button, switch to basic_kbdfr
5. …

refactor(android/engine): Use isKeyboardLoaded() on a consistent basis 🛋

---

.eslintrc.cjs
common/web/eslint/eslintNoNodeImports.js
developer/src/.eslintrc.cjs
developer/src/kmc-keyboard/.eslintrc.cjs
developer/src/kmc-keyboard/package.json
developer/src/kmc-kmn/.eslintrc.cjs
developer/src/kmc-kmn/build.sh
developer/src/kmc-kmn/package.json
developer/src/kmc-model-info/.eslintrc.cjs
developer/src/kmc-model-info/package.json
developer/src/kmc-model/.eslintrc.cjs
developer/src/kmc-model/package.json
developer/src/kmc-package/.eslintrc.cjs
developer/src/kmc-package/package.json
developer/src/kmc/.eslintrc.cjs
developer/src/kmc/package.json
package-lock.json
package.json

Adds eslint, effectively disabled, to infrastructure for all of kmc.
Note that eslintNoNodeImports.js will be used in the next commit, for verifying #8644.

chore(developer): add eslint devDependency for kmc

---

common/web/types/src/main.ts
common/web/types/src/util/util.ts
common/web/types/test/util/test-util.ts
developer/src/kmc-keyboard/.eslintrc.cjs
developer/src/kmc-keyboard/src/compiler/keymanweb-compiler.ts

One of a set of updates for kmc-*, as all of them currently have either wasm-fs or node core module references. This is the easiest patch.

chore(developer): kmc-keyboard should not use any node-specific modules

---

resources/builder.inc.sh

If a build script specified, e.g. :kmc-keyboard, :kmc-package, :kmc as three targets, in that order, then passing :kmc as a parameter would fail, because :kmc-keyboard, :kmc-package would be emitted to the match result before finding :kmc.

fix(common): builder parse multi-param order

---

linux/ibus-keyman/build.sh

Previously we didn't correctly change directories which could lead to the error "cd: ../build/x86_64/release: No such file or directory".

chore(linux): Fix build script

---

common/predictive-text/unit_tests/test.sh
ios/tools/prepRelease.sh
linux/scripts/dist.sh
mac/build.sh
resources/build/build-utils.sh

Fixes #8693.
Enforces `-e` (abort script on error) and `-u` (error on unset variable use) on all scripts that source build-utils.sh. This may result in some downstream build failures which we'll need to address before merge to master.

chore(common): `set -eu` in build-utils.sh

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java

Fixes #8550 
When Keyman app is in the foreground and the device is rotated, `onConfigurationChanged()` triggers which handles resizing the OSK.
If Keyman is in the background while the device is rotated, resuming the app does not trigger `onConfigurationChanged()`.
This only affects the in-app keyboard. Note, on old Android devices (e.g. Android 5.0 / SDK 21), the app is recreated so the OSK always appears fine.
This PR adds a check to `onResume()` to handle resizing the OSK if needed.
**Setup** - Install the PR build of Keyman for Android on a recent Android device/emulator (Anything newer than Android Oreo will do). Note, some Android devices use an "orientation" button on the navigation bar to trigger orientation changes. Press the button as necessary when rotating between portrait / …

fix(android/app): Resize OSK when resuming app from background

---

mac/build.sh

Fixes an error in mac/build.sh, arising from work in #8698. Kinda proves that the `-u` flag was worth setting globally!
This error broke release 17.0.101-alpha and 17.0.102-alpha.

fix(mac): `$CONFIG` not `$CONFIGURATION` in build path

---

android/KMAPro/build-play-store-notes.inc.sh
android/KMAPro/build-play-store-notes.sh
android/build-publish.sh

Some minor cleanup to the script that generates Play Store release notes.
This mainly encapsulates build-play-store-notes.sh into a function `generateReleaseNotes()`
A lot of preamble is already handled by the parent script sourcing build-utils.sh

chore(android/app): Cleanup build-play-store-notes script

---

developer/src/kmc-package/package.json
developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/messages.ts
developer/src/kmc-package/src/compiler/package-validation.ts
developer/src/kmc-package/src/main.ts
developer/src/kmc-package/test/fixtures/invalid/ERROR_PackageCannotContainBothModelsAndKeyboards.kps
developer/src/kmc-package/test/fixtures/invalid/WARN_PackageShouldNotRepeatLanguages.kps
developer/src/kmc-package/test/fixtures/invalid/WARN_PackageShouldNotRepeatLanguages.model.kps
developer/src/kmc-package/test/test-messages.ts
developer/src/kmc-package/test/test-package-compiler.ts
developer/src/kmc/src/commands/build/BuildPackage.ts
developer/src/kmc/src/kmlmi.ts
developer/src/kmc/src/kmlmp.ts

Fixes #8730.
Fixes #8731.
Adds a package-validation.ts module, plus adds a call to the validation step in the compilers.
Rearranges the kmc-package files to match other compilers better.
Removes `default` from exports.
And finally, adds ERROR_PackageCannotContainBothModelsAndKeyboards and WARN_PackageShouldNotRepeatLanguages messages, plus tests.

feat(developer): add package validation

---

linux/keyman-config/Makefile

When building on TC we install into a temporary directory. This broke with the recent introduction of build.sh because that now calls `make install` whereas previously we explicitly called `make install-temp` on TC. Instead of adding a `install-temp` action to `build.sh` we now check in the Makefile if sudo is set.

chore(linux): Fix installation build step on TC

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

More refactoring for #7881 
> updateSelectionRange - the if (ic!=null) branch - is there a reason that can't run for the in-app keyboard too?
1. updateSelectionRange() consolidated to update text with inputConnection.
2. Then refactor updateSelectionRange from KMManager to KMKeyboard
**Setup** - Install the PR build of Keyman for Android on device/emulator.
From Keyman, also install basic_kbdfr keyboard (Basic French keyboard uses deadkeys on vowels)
* **TEST_REPLACE_SELECTION_DEADKEYS_INAPP** - Verifies INAPP keyboard replaces selected text and handles deadkeys
2. In Keyman with the sil_euro_latin keyboard, type "the quick brown fox"
3. Select the letters "row" within the word "brown". (keyboard switches to shift layer)
4. Type "H"
5. Verify the text changes …

refactor(android/engine): Consolidate updateSelection 🛋

---

windows/src/support/Makefile
windows/src/support/texteditor/Makefile

- Add text editor to the `windows/src/support/Makefile` 
- Fixed the TextEditor Makefile to copy the debug file to the debug folder.
* Under the `Test Artifacts` heading on this PR click the `Text Editor (32 bit)`
* Expected result: it should download. 
* Under the `Test Artifacts` heading on this PR click the `Text Editor (64 bit)`
* Expected result: it should also download.
* You should be able to run either of these once downloaded.

feat(windows): add text editor to the support makefile

---

developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/messages.ts
developer/src/kmc-package/src/compiler/package-validation.ts
developer/src/kmc-package/test/fixtures/invalid/keyman.en.error_must_have_at_least_one_language.model.kps
developer/src/kmc-package/test/test-package-compiler.ts

Fixes #8780.
Fixes #8781.
Adds `ERROR_MustHaveAtLeastOneLanguage` and corresponding unit test.

feat(developer): verify at least one language in package

---

developer/src/kmc-package/src/compiler/messages.ts
developer/src/kmc-package/src/compiler/package-validation.ts
developer/src/kmc-package/src/compiler/package-version-validation.ts
developer/src/kmc-package/test/fixtures/binary_kvk_file/source/binary_kvk_file.kps
developer/src/kmc-package/test/fixtures/invalid/error_package_must_contain_a_model_or_a_keyboard.kps
developer/src/kmc-package/test/fixtures/invalid/error_package_must_contain_a_package_or_a_keyboard.kps
developer/src/kmc-package/test/fixtures/xml_kvk_file/source/xml_kvk_file.kps
developer/src/kmc-package/test/test-package-compiler.ts

Fixes #8791.
Adds `ERROR_PackageMustContainAPackageOrAKeyboard` and corresponding unit tests. A couple of unit tests tweaked as their fixtures were no longer valid!

chore(developer): verify that package has at least a model or keyboard

---

ios/Cartfile
ios/Cartfile.resolved
ios/engine/KMEI/KeymanEngine/Classes/Errors/SentryManager.swift
oem/firstvoices/ios/Cartfile
oem/firstvoices/ios/Cartfile.resolved

Update Carthage dependencies to versions that will build under XCode 14.3
(adopted from Keyman for iPhone and iPad Acceptance Test Procedures)
---
At this time, Keyman for iOS does not support external keyboard input.
1.  Uninstall previous version of Keyman on the device (on a simulator, "Erase All Content and Settings..." under Device menu)
2. Install test build IPA (on a simulator, "iOS Simulator Image")
3. Disable internet connectivity of the device
4. Start Keyman and select **Add a keyboard for your language**
5. Verify error message "Could not reach Keyman server!" or "The Internet connection appears to be offline." is displayed
6. Click OK to dismiss.  Close Keyman app
7. On device, enable internet connectivity
8. Start Keyman
9. On initial **Get Started** menu, select "Enable …

chore(ios): Changes required for XCode 14.3

---

linux/debian/ibus-keyman.postinst

[Debian Policy section 10.4](https://www.debian.org/doc/debian-policy/ch-files.html#scripts) requires `set -e`.

chore(linux): Make postinst script comply with Debian policy

---

android/build-publish.sh

Fixes #8844 and follow-on to #8749
During the review, we changed the build-play-store-notes.inc.sh script to pushd and popd to preserve the directory.
https://github.com/keymanapp/keyman/pull/8749#discussion_r1190635885
It turns out the popd takes the shell to `$KEYMAN_ROOT/android/` when it needs to be in `$KEYMAN_ROOT/android/KMAPro/` for the ./gradlew call.
The stable-16.0 script for comparison
https://github.com/keymanapp/keyman/blob/fc582339f90a8c9e0c116b4aaea8a9f11bd979c3/android/build-publish.sh#L75-L82
#8844 

fix(android/app): Pathing for publish script

---

web/src/engine/events/src/domEventTracker.ts
web/src/engine/events/src/index.ts
web/src/engine/namespaced-main/kmwutils.ts

Yay, a comparatively simple, narrow, and focused one! 
This converts the old utility `attachDOMEvent` function, `detachDOMEvent` function, and related state management code blocks into their own module (as a component of `engine/events`).  It'll help keep all of that neat, tidy, and centralized.
Equivalent method signatures of `keyman.util`, with a managed instance of the class, will be established in a later PR.  Certain components of the engine (coming first) will utilize their own instances instead in order to facilitate their own encapsulation, rather than having them rely on an externally-managed object to cleanup on their behalf.
- This ended up mattering for some of the unit tests and integration tests down the line.

chore(web): modularizes the keyman.util dom-event tracking components 🧩

---

web/src/app/browser/src/context/focusAssistant.ts
web/src/app/browser/src/contextManager.ts
web/src/engine/attachment/src/pageContextAttachment.ts
web/src/engine/namespaced-main/dom/domEventHandlers.ts
web/src/engine/namespaced-main/dom/domManager.ts

Now that all the prerequisites are in order, it's now possible connect all the pieces from #8801, #8802, #8803, and #8804.  With this, the context-management components of Keyman Engine for Web should now be fully modularized.
In case the design behind those PRs wasn't fully clear before, hopefully this PR makes things clearer.
----
Unfortunately, with the current state of the `app/browser` target... it is not practical to establish unit tests to validate this _at this point_.  `ContextManager` is still fairly entangled with a couple of other Web components:
1. A reference to the active engine configuration object, including the engine-initialization Promise.
2. A reference to a "stub and keyboard" cache (and an associated keyboard loader, for async keyboard-activation ops)
Both are …

chore(web): reconnection of KMW's context-focus event hooks 🧩

---

web/src/app/browser/src/context/pageIntegrationHandlers.ts
web/src/app/browser/src/contextManager.ts
web/src/app/browser/src/keymanEngine.ts
web/src/engine/namespaced-main/dom/domManager.ts
web/src/engine/namespaced-main/keymanweb.ts
web/src/engine/namespaced-main/kmwbase.ts

This modularizes various bits and pieces of "polish" for Web's focus-handling:
- Makes sure that the touch OSK doesn't obscure the active input element
- Handling for when the user "clicks off" of an active element to deactivate it
- Touch's language-menu dismissal - prevention of focus loss (that would otherwise occur because of the prior point)
Note how this could quite easily be integrated within (or simply 'owned by') the class introduced by #8801.  This design will help to resolve the noted "top-level-only" issue noted there once we decide to proceed further in that regard.

chore(web): modularization of Web's page-integration handlers 🧩

---

.github/workflows/deb-packaging.yml

Since we reference `sourcepackage` in the upload-to-llso step it should be listed in the `needs` list.

chore(linux): Add missing dependency to GHA

---

developer/src/kmc-kmn/build.sh
developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/CompilerInterfaces.cpp
developer/src/kmcmplib/src/kmcmplib.h

Relates to #8493.
Stage one of the kmcmplib filesystem refactoring, as we move to writing to buffers and allowing caller to write to disk. Moves responsibility for writing data out of WriteCompiledKeyboard and into kmcmp_CompileKeyboardFile. This means that there are now no file writes in Compiler.cpp, except for the temp UTF16fromUTF8 (which I will also change to a in-memory buffer "real soon now").
Note that responsibility for writing in kmcmp_CompileKeyboardFile is very much temporary as we'll move it out of the library altogether in a subsequent commit.

refactor(developer): move file write out of WriteCompiledKeyboard and CompileKeyboard merge

---

common/web/lm-worker/build-polyfill-concatenator.js
common/web/lm-worker/build-wrap-and-minify.js

The sourcemap data wasn't being passed along properly for 'debug' config builds, as it was only being stored for minify builds... which would throw it out.

fix(common/models): predictive-text sourcemapping linkage

---

common/web/input-processor/tests/cases/inputProcessor.js

I'm not sure exactly when and where the issue arose - probably from some of the rebases that happened before many of the PRs went up - but one input-processor unit test is falling over due to a missing parameter.  
The predictive-text worker is now provided during initialization, rather than initialized by the `InputProcessor` class.  It can also simply be `null`... but that has a side effect causing the final assertion of one unit test to fail.  (No worker, no ability to predict - but the assertion, as previously set, expects enabled predictions.)

fix(web): input-processor unit test - constructor missing a parameter 🧩

---

developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmcmplib/include/kmcmplibapi.h
developer/src/kmcmplib/src/CompilerInterfaces.cpp
developer/src/kmcmplib/src/meson.build
developer/src/kmcmplib/src/uset-api.cpp
developer/src/kmcmplib/tests/uset-api-test.cpp

Relates to #8493.
This moves the remainder of the WASM interfaces in kmcmplib to using emscripten bind. It is a little bit of a step backwards at present for parseUnicodeSet, because I've changed the output buffer type to an int for the purposes of simplifying the binding just now. But that can be improved later, and at least we are consistent with the binding methods.
Next step is to move the filesystem access out of kmcmplib, which requires a significant refactoring of the kmcmpdll connection to the library. Ideally, it will move to using the kmcmp_compile endpoint, and remove the overlapping kmcmp_CompileKeyboard and kmcmp_CompileKeyboardToBuffer functions.

chore(developer): replace cwrap wasm bindings

---

web/ci.sh
web/common.inc.sh
web/src/app/browser/build.sh
web/src/app/ui/build.sh
web/src/tools/building/sourcemap-root/build.sh

Per recent discussion, this PR simply arranges a nice, tidy folder for use with publishing Web builds - `$KEYMAN_ROOT/web/build/publish`.  Underneath that are `debug` and `release` folders, corresponding to the two different build configurations.  
This pattern is a bit different from 16.0 releases, where 'release' was the base folder and 'debug' was a subfolder called 'unminified'.
Now:
- debug
- compiled scripts, resource folders
- release
- compiled scripts, resource folders
Then:
- compiled scripts, resource folders
- unminified
- compiled scripts, resource folders
s.keyman.com tends to only use the 'release' config, while downloads provide both.

chore(web): refines KMW build output organization 🧩

---

resources/build/build-utils-ci.inc.sh

The npm version command started failing when we updated to node 18.16.0, and it looks like it is related to the version numbers (specifically, running `npm version` more than once).
This commit makes the package.json file mangling done during the pack and publish phases idempotent and applies the version data to all package.json files in the repository. (Note, this means you should _always_ run `build.sh pack` and not `npm pack`!)
Once build completes on this PR, we need to verify the logs of the pack phase (in Keyman Developer build), and corresponding outputs. I have locally tested that the .tgz files generated look plausible and the changes applied to the package.json files appear to be correct.

fix(common): tweak pack/publish support for npm 9.5.1 and node 18.16.0

---

.github/workflows/deb-packaging.yml
linux/keyman-config/build.sh
linux/keyman-config/com.keyman.gschema.xml
linux/keyman-config/keyman_config/__init__.py
linux/keyman-config/keyman_config/dconf_util.py
linux/keyman-config/keyman_config/sentry_handling.py
linux/keyman-config/keyman_config/view_installed.py

This change displays tabs at the left and adds an "Options" page. This makes it look closer to the Windows version.
It also implements the option to disable Sentry error reporting (#5027).
New look:
Previously:
- The tests can be run on any Linux platforms.
- Reboot
- In a terminal window, run `unset KEYMAN_NOSENTRY`
- start the following tests from this terminal window!
**TEST_UI_DEFAULT:**
- Start UI with `km-config`
- switch to `Options` tab
- verify that "Automatically report errors to keyman.com" is checked
- in the terminal run `gsettings get com.keyman.options error-reporting` and verify that the output is `true`
**TEST_UI_DEFAULT_PERSIST:** …

feat(linux): Implement Options page and option to disable Sentry error reporting

---

linux/keyman-config/build.sh
linux/keyman-config/keyman_config/get_kmp.py
linux/keyman-config/keyman_config/view_installed.py

Closes #8631.
- The tests can be run on any Linux version
- Reboot
- Install EuroLatin (SIL) keyboard for German into the user area: 
```
km-package-install --package sil_euro_latin --bcp47 de
```
- Install EuroLatin (SIL) keyboard for French into the shared area: 
```
sudo km-package-install --shared --package sil_euro_latin --bcp47 fr
```
- Verify that both German and French show up in the keyboard dropdown in the top bar. Otherwise reboot.
**TEST_LOCATION_COLUMN**: New column exists and shows expected values
- open Keyman Configuration
- verify that EuroLatin (SIL) shows up twice. In the Location column one of these rows should have the value …

feat(linux): Add column for installation location

---

developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/CompilerInterfacesWasm.cpp

Fixes #8885.
Adds some optimization and error checking to the loadFile callback in kmc-kmn. Also handles case of zero-byte bitmap file so we won't crash on it.

chore(developer): loadFile callback error check and optimization

---

common/web/types/src/kvk/kvks-file-writer.ts
common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts
common/web/types/src/main.ts
common/web/types/test/helpers/index.ts
common/web/types/test/helpers/reader-callback-test.ts
common/web/types/test/kpj/test-kpj-file-reader.ts
developer/src/common/web/test-helpers/index.ts
developer/src/kmc-ldml/src/compiler/compiler-options.ts
developer/src/kmc-ldml/src/compiler/compiler.ts
developer/src/kmc-ldml/test/helpers/index.ts
developer/src/kmc-ldml/test/test-compiler-e2e.ts
developer/src/kmc-ldml/test/test-keymanweb-compiler.ts
developer/src/kmc-ldml/test/test-metadata-compiler.ts
developer/src/kmc-ldml/test/test-testdata-e2e.ts
developer/src/kmc-ldml/test/test-visual-keyboard-compiler-e2e.ts
developer/src/kmc/src/commands/build/BuildLdmlKeyboard.ts
developer/src/kmc/src/commands/buildTestData/index.ts
developer/src/kmc/src/messages/NodeCompilerCallbacks.ts

The url module is a node module. We need to move responsibility for resolving the path of the LDML XML <import> statements out of common/web/types, and into the ultimate consumer, so it's now surfaced as an option, along with a helper constant that reports the import.meta.url-relative base path of the standard imports that are compiled into common/web/types.
This hopefully means we can use this module in both browser and node contexts without trouble.

chore(common): remove url module ref from common/web/types

---

common/web/lm-worker/build-bundler.js
common/web/lm-worker/build.sh
web/ci.sh
web/common.inc.sh
web/src/app/browser/build-bundler.js
web/src/app/browser/build.sh

When chasing down some other bug, I happened upon a very neat `esbuild` feature that can provide us with very useful information in regard to our "check/web/file-size" build check:  the ability to generate a "metafile" and use it to determine how much final, minified data each source file contributes to the final build product!
The main caveat:  this does not directly include the polyfills that we prepend to the compiled worker, as those are prepended outside of esbuild.  `esbuild` does not consider sourcemapping when making the profile, so we can't run the profiling operations meaningfully on the result of the concatenation.  That said, the difference between the reported lm-worker filesize from the worker build vs what the final Web engine build states can easily be inferred to …

feat(web): release-configuration filesize profiling 🧩

---

linux/debian/control
linux/debian/keyman-system-service.manpages
linux/keyman-config/km-config.bash-completion
linux/keyman-config/km-kvk2ldml.bash-completion
linux/keyman-config/km-package-get.bash-completion
linux/keyman-config/km-package-install.bash-completion
linux/keyman-config/km-package-list-installed.bash-completion
linux/keyman-config/km-package-uninstall.bash-completion
linux/keyman-system-service/man/keyman-system-service.1

- add rudimentary man page for keyman-system-service
- remove hashbang for bash completion files
- reword description for keyman-system-service
This fixes these lintian warnings:
- keyman-system-service: description-is-pkg-name Keyman system service
- keyman: bash-completion-with-hashbang /usr/bin/env bash
[usr/share/bash-completion/completions/km-config:1]
- keyman-system-service: no-manual-page
[usr/libexec/keyman-system-service]

chore(linux): Fix lintian warnings

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/KMEA/app/src/test/java/com/keyman/engine/KMManagerTest.java

Addresses some of #5125 by re-enabling the disabled KMManager tests.
I still haven't seen how Robolectric accesses resource values from the merged AndroidManifest.xml file, so the other tests remain TODO's.
**Setup** - Install the PR build of Keyman for Android on an Android emualtor/device
* **TEST_KEYMAN** - Verifies Keyman still functions
1. Launch Keyman for Android in portrait orientation and dismiss the Get Started" menu
2. Verify the in-app OSK is displayed with the default sil_euro_latin keyboard

fix(android/engine): Re-enable KMManager tests

---

linux/keyman-config/keyman_config/handle_install.py
linux/keyman-config/keyman_config/install_kmp.py
linux/keyman-config/keyman_config/install_window.py
linux/keyman-config/keyman_config/view_installed.py

When we recently added the new column and changed the model we didn't adjust all the existing references for the model fields.
This change fixes this and also extract some additional methods.
- The tests can be run on any Linux version
- Reboot
- Install Amharic keyboard to shared area:
```
sudo km-package-install --shared --package gff_amharic
```
- Install Khmer Angkor keyboard to user area:
```
km-package-install --package khmer_angkor
```
- Install EuroLatin (SIL) keyboard for French to user area:
```
km-package-install --package sil_euro_latin  --bcp47 fr
```
- Start Keyman Configuration
**TEST_UNINST_DISABLED**: Uninstall button disabled for …

fix(linux): Fix disabling of buttons

---

developer/src/kmc-kmn/.eslintrc.cjs
developer/src/kmc-model-info/build.sh
developer/src/kmc-model-info/package.json
developer/src/kmc/.eslintrc.cjs

Enables eslint checks for eslintNoNodeImports for kmc-kmn. Also enables linting for kmc-model-info, but does not enable eslintNoNodeImports on it at this time.
Relates to #8959.

chore(developer): check for nodejs deps in kmc-kmn

---

web/src/app/browser/src/context/focusAssistant.ts
web/src/app/browser/src/context/pageIntegrationHandlers.ts
web/src/app/browser/src/contextManager.ts
web/src/engine/element-wrappers/src/input.ts
web/src/engine/element-wrappers/src/outputTarget.ts
web/src/engine/element-wrappers/src/textarea.ts

References for the original behavior, intent, and implementation: 
- #2168
- #2514
This corresponds to one of the tracking items on #8560 🧩:
> - Address, then resolve all comments for https://github.com/keymanapp/keyman/pull/8055.
>     - They're loose threads that were unresolvable at the time.
----
TL,DR: forces a scroll on `<input>` element text when the selection expands out of bounds.
- The 'caret' by itself can serve as a selection of width zero and is the most common case.
- Just type a long string; output text should auto-scroll to keep the caret in bounds. 
- Pretty easy to user test, once you know why the code existed in the first place.
Well... the pathway I'd set up previously was looking quite unwieldy, so I reworked it into something more streamlined that still addresses the …

fix(web): restores element text-selection auto-scrolling 🧩

---

developer/src/kmc-kmw/.eslintrc.cjs
developer/src/kmc-kmw/build.sh
developer/src/kmc-kmw/package.json

Relates to #8959.
Also makes build.sh responsible for build rather than package.json.

chore(developer): enable eslint for kmc-kmw 🗜

---

web/src/app/browser/src/oskConfiguration.ts
web/src/engine/osk/src/views/anchoredOskView.ts
web/src/engine/osk/src/views/floatingOskView.ts
web/src/engine/osk/src/views/inlinedOskView.ts
web/src/engine/osk/src/views/oskView.ts
web/src/test/auto/dom/cases/osk/events.js

Follows up on a feature-branch TODO item based on this: https://github.com/keymanapp/keyman/pull/8624#discussion_r1191843605
The problem:
https://github.com/keymanapp/keyman/blob/833f3aed40356eabc7714954c3840d435d80d9ce/web/src/engine/osk/src/views/oskView.ts#L43-L53
has duplicates / near duplicates I made earlier in the process in a "newer" event style:
https://github.com/keymanapp/keyman/blob/833f3aed40356eabc7714954c3840d435d80d9ce/web/src/engine/osk/src/views/oskView.ts#L69-L71
https://github.com/keymanapp/keyman/blob/833f3aed40356eabc7714954c3840d435d80d9ce/web/src/engine/osk/src/views/oskView.ts#L84-L96
https://github.com/keymanapp/keyman/blob/833f3aed40356eabc7714954c3840d435d80d9ce/web/src/engine/osk/src/views/oskView.ts#L103-L118
Nearly pure duplicates:
- onHide
- onShow
- …

chore(web): deduplicates non-distinct osk events 🧩

---

common/web/types/src/util/compiler-interfaces.ts
developer/src/common/web/test-helpers/verifyCompilerMessagesObject.ts
developer/src/kmc-kmn/src/compiler/messages.ts
developer/src/kmc-kmn/test/test-messages.ts
developer/src/kmc-ldml/test/test-messages.ts
developer/src/kmc-model/test/test-messages.ts
developer/src/kmc-package/test/test-messages.ts
developer/src/kmc/test/test-messages.ts

Fixes #8998.
kmc-kmn messages were broken down into sub-namespaces, but the range overlapped the reserved namespace mask range. Fixed the message values, added a new test to the verifyCompilerMessagesObject function to verify that messages don't creep outside their namespace, and defined new masks (in CompilerErrorSeverity enum... hmm) to help.
I opted to remove the leading `0` in the messages for kmc-kmn as I had to correct a number of them anyway, but not the messages in remaining units at this time (it's not an error, but just slightly misleading as we only have 12 bits, not 16 to play with).
It is safe to reassign these messages as they were only assigned in 17.0 alpha.

fix(developer): keep kmc-kmn messages within namespace

---

linux/keyman-config/keyman_config/kmpmetadata.py
linux/keyman-config/keyman_config/list_installed_kmp.py
linux/keyman-config/keyman_config/uninstall_kmp.py
linux/keyman-config/keyman_config/view_installed.py
linux/keyman-config/km-package-list-installed

Previously if there was a newer version available on keyman.com we showed that version number instead of the version number of the installed keyboard.
- The tests can be run on any Linux version
- Reboot
- Download EuroLatin (SIL) version 2.0.1: <https://keyman.com/go/package/download/sil_euro_latin?version=2.0.1&tier=stable>
- Open Keyman Configuration
- If you have any EuroLatin (SIL) keyboards installed, uninstall them
- Install the just downloaded keyboard by clicking the "Install keyboard" button and selecting the downloaded file
**TEST_VERSION_NO**: Correct version number shows
- Verify that the "Version" column shows version 2.0.1 for the …

fix(linux): Fix display of installed keyboard version

---

windows/src/desktop/kmshell/xml/keyman_keyboardlist.xsl

The QR code class and pop-up xml attribute id now uses the keyboard name and not the keyboard package name. However the link if the keyboard is part of a package still uses the package name for the URL.
1. Install build linked in this PR
2. Open Keyman Configuration dialog. 
3. Download and install Syriac/Aramaic keyboard.
4. Notice that three keyboards namely Aramaic (Hebrew layout), Syriac (Arabic layout) and Syriac (Phonetic layout) keyboards are available under Syriac/Aramaic name. 
5. Click 'Aramaic (Hebrew layout)'  keyboard in Keyboard Layouts view. 
6. Click 'Share keyboard' button. 
Expected Result: Just one QR Code is shown.
7. Click 'Syriac (Arabic layout)` keyboard in Keyboard Layouts view. 
8. Click 'Share keyboard' button.
Expected Result:
A QR Code now shows. 
1. Open …

fix(windows): qr code id uses keyboard name and not package name

---

common/web/keyboard-processor/src/text/keyboardProcessor.ts
web/src/app/browser/src/hardwareEventKeyboard.ts
web/src/app/browser/src/languageMenu.ts
web/src/app/browser/src/oskConfiguration.ts
web/src/app/webview/src/oskConfiguration.ts
web/src/app/webview/src/passthroughKeyboard.ts
web/src/engine/events/src/emitterListenerSpy.ts
web/src/engine/events/src/legacyEventEmitter.ts
web/src/engine/main/src/hardKeyboard.ts
web/src/engine/main/src/keyEventSource.interface.ts
web/src/engine/main/src/keymanEngine.ts
web/src/engine/osk/src/components/resizeBar.ts
web/src/engine/osk/src/views/floatingOskView.ts
web/src/engine/osk/src/views/oskView.ts
web/src/engine/osk/src/views/twoStateActivator.ts
web/src/engine/osk/src/visualKeyboard.ts
web/src/engine/package-cache/src/stubAndKeyboardCache.ts
web/src/test/auto/headless/events/emitterListenerSpy.js
web/src/test/auto/headless/osk/activation.js
web/src/test/manual/web/osk/scratchspace/commands.js
web/src/tools/testing/recorder/scribe.ts

From #8560:
> There are some notable inconsistencies with internal event nomenclature, as noted by [...]
From a review comment on #8591:
> Is this [event name] supposed to be camelCase unlike all the other event names?
So... I somehow wasn't fully aware until now that event names in JS are conventionally set to full lowercase, as are our [pre-existing documented API events](https://help.keyman.com/developer/engine/web/17.0/reference/events/), and I'd gone making a number of camel-cased internal event names.  This PR corrects my mistakes and sets them to their lowercase-convention form.  I'm still not personally super-comfortable with it for certain names, but it's best to follow conventions.

change(web): internal-event convention consistency 🧩

---

android/.gitignore
android/Samples/KMSample1/build.sh
android/Samples/KMSample2/build.gradle
android/Samples/KMSample2/build.sh
android/Tests/KeyboardHarness/build.sh

I was setting up a new machine and encountered warnings/errors with `/android/build.sh` (no args for Samples/Tests generate unsigned release apk's)
* Default output is app-release-unsigned.apk instead of app-release.apk. KMAPro not affected because that build has custom version/environment in the apk name
* KMSample2 failed to build due to a linting error (updating Gradle plugin fixed it)

fix(android/samples): Cleanup Sample/Tests apk's

---

.github/workflows/crowdin.yml

The crowdin [workflow](https://github.com/keymanapp/keyman/actions/workflows/crowdin.yml) started failing 2 months ago with the error:
> null: Unrecognized field "customSegmentation" (class com.crowdin.client.sourcefiles.model.OtherFileImportOptions), not marked as ignorable (one known property: "contentSegmentation"])
This is fixed by bumping the crowdin GHA which updates crowdin-cli (fixed in version 3.6.4)
See https://github.com/crowdin/crowdin-cli/issues/379

chore(common): Bump crowdin github action to 1.3.2

---

mac/build.sh
mac/mac-utils.inc.sh
mac/setup/build.sh

Fixes #6881.
References for the transition to `notarytool`:
* https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool?changes=_3_3
* https://keith.github.io/xcode-man-pages/notarytool.1.html

chore(mac): move from altool to notarytool

---

web/src/app/browser/src/keyboardInterface.ts
web/src/app/browser/src/keymanEngine.ts
web/src/app/webview/src/keymanEngine.ts
web/src/engine/main/src/keymanEngine.ts

Wow, totally missed this piece.  The special API functions used by the CJK picker keyboards had been converted, but were fully disconnected from the engine.  I'd also neglected to patch up their connection to the OSK.
I happened to catch this while preparing and double-checking Web's regression test suite in prep for user testing. I realized I hadn't double-checked the functionality in a while, so I took the opportunity to verify everything was working correctly... and as evidenced by this PR... it was not.  

fix(web): properly connects picker interface API 🧩

---

common/models/templates/build.sh
common/predictive-text/build-bundler.js
common/predictive-text/build.sh
common/web/es-bundling/README.md
common/web/es-bundling/build.sh
common/web/es-bundling/src/classTreeshaker.mts
common/web/es-bundling/src/configuration.mts
common/web/es-bundling/src/index.mts
common/web/es-bundling/src/tslibTreeshaking.mts
common/web/es-bundling/tsconfig.json
common/web/input-processor/build-bundler.js
common/web/keyboard-processor/build-bundler.js
common/web/keyboard-processor/build.sh
common/web/lm-worker/build-bundler.js
common/web/lm-worker/build-wrap-and-minify.js
common/web/lm-worker/build.sh
common/web/utils/build.sh
web/src/app/browser/build-bundler.js
web/src/app/ui/build-bundler.js
web/src/app/webview/build-bundler.js
web/src/engine/attachment/build-bundler.js
web/src/engine/device-detect/build-bundler.js
web/src/engine/element-wrappers/build-bundler.js
web/src/engine/events/build-bundler.js
web/src/engine/main/build-bundler.js
web/src/engine/osk/build-bundler.js
web/src/engine/package-cache/build-bundler.js
web/src/engine/package-cache/build.sh
web/src/engine/paths/build-bundler.js
web/src/engine/paths/build.sh

This PR centralizes the main configuration properties among all the esbuild-oriented scripts introduced on the feature-esmodule-web-engine (🧩) feature branch.  There's also some cleanup of unnecessary settings.
I thought about making a package.json and such for the centralized config & utility definitions, but figured we could do without yet another one for now.  (I noticed that `common/web/es-lint` does similarly.)  It would make the import pathing simpler if we did add one, though.

chore(web): esbuild configuration cleanup 🧩

---

resources/build/trigger-definitions.inc.sh

Note: enabling these tests will probably highlight some code coverage issues in some of our branches!

chore: enable common ci for web

---

windows/src/engine/testhost/testhost.cpp

if dwError is 0, don't try to format it
avoid "Error starting Keyman: The operation completed successfully.  [0]"

fix(windows): testhost improve error message

---

developer/src/kmc-kmn/src/kmw-compiler/visual-keyboard-compiler.ts
developer/src/kmc-kmn/src/kmw-compiler/write-compiled-keyboard.ts

chore(developer): cleanup displayUnderlying flag in kmw compiler 🗜

---

developer/src/kmc-kmn/src/kmw-compiler/messages.ts
developer/src/kmc-kmn/src/kmw-compiler/write-compiled-keyboard.ts

Adds support for `&kmw_embedcss`, `&kmw_embedjs`, `&kmw_helpfile`.

chore(developer): support embedded files in kmw compiler 🗜

---

developer/src/kmc-analyze/src/util/get-osk-from-kmn-file.ts
developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-kmn/src/kmw-compiler/write-compiled-keyboard.ts
developer/src/kmc-kmn/test/kmw/test-compiler-manual.ts
developer/src/kmc-kmn/test/kmw/test-compiler.ts
developer/src/kmcmplib/include/kmcmplibapi.h
developer/src/kmcmplib/src/CompileKeyboardBuffer.cpp
developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/CompilerInterfaces.cpp
developer/src/kmcmplib/src/CompilerInterfacesWasm.cpp
developer/src/kmcmplib/src/compfile.h

Reorganizes the data structures passed out of kmcmplib via WASM to make it easier to work with the extra metadata and reduce the number of places we have to touch when we add extra metadata fields.
Preparation for supporting the metadata that the kmw compiler requires.

chore(developer): cleanup data passing from wasm 🗜

---

windows/src/engine/mcompile/mcompile.cpp

mcompile:
- copy keyboards if KMXPlus is detected
- give an error if -u is used on a KMXPlus file
Fixes #9064

fix(windows): support kmxplus in mcompile 🙀 

---

core/src/ldml/ldml_processor.cpp

- document transform calling code in ldml_transform
- remove obsolete portions
- optimize keystroke code when no transforms are present
- also, fix 'enter' and 'delete' breakage, and other keys passed to the OS like 'tab'
#7377

fix(core): fix ldml transforms 🙀

---

developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-kmn/src/kmw-compiler/compiler-globals.ts
developer/src/kmc-kmn/src/kmw-compiler/javascript-strings.ts
developer/src/kmc-kmn/src/kmw-compiler/write-compiled-keyboard.ts
developer/src/kmc-kmn/test/fixtures/kmw/.gitignore
developer/src/kmc-kmn/test/fixtures/kmw/test_readonly_groups.js
developer/src/kmc-kmn/test/fixtures/kmw/test_readonly_groups.kmn
developer/src/kmc-kmn/test/kmw/test-kmw-compiler.ts
developer/src/kmcmplib/include/kmcmplibapi.h
developer/src/kmcmplib/src/CompileKeyboardBuffer.cpp
developer/src/kmcmplib/src/CompilerInterfacesWasm.cpp

Adds support for readonly groups and corresponding unit test. Again required more metadata from kmcmplib; this metadata is now fairly straightforward to patch in without side-effects, which is encouraging.

fix(developer): support readonly groups in kmc-kmn/kmw-compiler 🗜

---

developer/src/kmc-kmn/src/kmw-compiler/javascript-strings.ts

Removes old commented code and fixes surrogate pair check.

chore(developer): cleanup javascript-strings.ts 🗜

---

developer/src/kmc-kmn/src/kmw-compiler/constants.ts
developer/src/kmc-kmn/src/kmw-compiler/messages.ts
developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts

Also removes leftover commented code, and changes an enum to string enum type in order to get constant names for free for an error message.
`Error_TouchLayoutIdentifierRequires15` was split into its own error message because it was overloaded with `CERR_TouchLayoutInvalidIdentifier` previously but had a different message.

chore(developer): handle layout file errors in kmw-compiler

---

web/build.sh
web/ci.sh
web/src/test/manual/build.sh
web/src/tools/build.sh

The [nightly build](https://build.palaso.org/buildConfiguration/Keymanweb_Build/391731?buildTab=log&focusLine=2582&linesState=2558&logView=flowAware) after merging #8560 fell over:
```
01:10:20 
Creating archive: ../../../../build/upload/17.0.130/keymanweb-17.0.130.zip
01:10:20 
01:10:20 
Items to compress: 74
01:10:20 
01:10:20 
01:10:20 
Files read from disk: 58
01:10:20 
Archive size: 2043198 bytes (1996 KiB)
01:10:20 
Everything is Ok
01:10:20 
/c/BuildAgent/work/fb3cd69e22dde528/keyman/web
01:10:20 
01:10:20 
Building `static/` folder for long-term hosting of testing resources...
01:10:22 
[web] ## prepare:downloads.keyman.com completed successfully
01:10:22 
Resolve-Path : Cannot find path
01:10:22 
'C:\BuildAgent\work\fb3cd69e22dde528\keyman\web\build\upload\17.0.130\keymanweb-17.0. …
```

fix(web): fixes Web build zip artifact construction

---

common/web/types/src/kpj/kpj-file-reader.ts
developer/src/kmc-kmn/src/kmw-compiler/kmw-compiler.ts
developer/src/kmc-kmn/src/kmw-compiler/util.ts
developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts
developer/src/kmc-package/src/compiler/package-validation.ts
developer/src/kmc-package/src/compiler/package-version-validation.ts
developer/src/kmc/src/commands/build.ts

Fixes #9097.
Fixes #9098.
Fixes #9101.
Fixes #9102.
Fixes #9103.
Fixes #9104.
Fixes #9105.
Fixes #9106.
Fixes #9108.
Fixes #9109.
This fixes a number of bugs in kmc that were identified by running against the keyboards repository.
Where possible, each bug fix is a separate commit in this PR; you may wish to review each commit separately.
This does not yet get us to 100% identical behaviour on the keyboards repository. There are a number of additional issues to follow up; see #9090, but calling out in particular:
* time and memory complexity issues for the vietnamese_ keyboards currently break kmc-kmw
* a decision needs to be made on `true` vs `True` in hand-edited .kpj files (the 'official' and recently-documented requirement is title case, but the current Delphi loader is lenient)
* some …

fix(developer): various bugs in kmc and related packages 🗜

---

developer/src/kmcmplib/src/CasedKeys.cpp
developer/src/kmcmplib/src/CompileKeyboardBuffer.cpp
developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/NamedCodeConstants.cpp

The kmcmplib compiler source used `delete` instead of `delete[]` in a number of locations where the corresponding allocation was an array.
This doesn't appear to matter on arrays of primitives on most platforms that we are targeting, but it _is_ undefined behaviour so we should correct it.
https://stackoverflow.com/a/2425749/1836776

fix(developer): ensure `delete` uses array semantics where appropriate 🗜

---

developer/src/kmcmplib/src/Compiler.cpp
developer/src/kmcmplib/src/xstring.cpp
developer/src/kmcmplib/src/xstring.h

Picked this up while running `-fsanitize=address` for trying to track down another bug.
This fixes a buffer overrun (normally invisible) in kmcmplib, where `xstrchr` was being called, which takes a string as its second parameter, but being passed a single character. This was incorrect behaviour for two reasons:
1. Passing a single character doesn't have null termination (big bug!)
2. We were not wanting xstring semantics on the token being parsed here
Replaced with `u16chr`, which does do what we want. Note the casting because `u16chr` only has a `const` version of its input/output at present.
Removed `xstrchr` because it is not used anywhere else in kmcmplib.

fix(developer): `GetDelimitedString` was using wrong `strchr` 🗜

---

common/include/kmx_file.h

Picked up by using `-fsanitize=undefined` on kmcmplib build.
When we read .kmx files, they have no alignment guarantees, so we need to tell the compiler to generate unaligned-safe code for accesses to `COMP_` structure members, because typically we point into the buffer and read at any offset.
A .kmx file will generally be 2-byte aligned, as there are no structures or data types with smaller than 2 byte widths. There is no requirement that this be the case per the .kmx spec, though. So we use a 1 byte alignment attribute for the compiler, so it will generate safe code when reading these structs.
Note that we are assuming that `COMP_KEYBOARD` is aligned because it is always the start of the file, so will be at the start of any buffer which will automatically be aligned correctly.
We should …

fix(common): specify alignment for `COMP_` structs 🗜

---

common/web/types/src/kvk/kvks-file-reader.ts
common/web/types/test/kvk/test-kvks-file.ts
developer/src/kmc-package/package.json
developer/src/kmc-package/src/compiler/package-version-validation.ts
developer/src/kmc-package/src/compiler/web-keyboard-metadata.ts
developer/src/kmc-package/test/fixtures/invalid/keyboardcontentfilenotfound.kps
developer/src/kmc-package/test/fixtures/khmer_angkor-debug-build.js
developer/src/kmc-package/test/test-web-keyboard-metadata.ts

Fixes #9111.
Fixes #9124.
Two fixes:
* Give a friendly error when .kvks is in binary format
* Support .js-only packages
We have existing packages which have only .js in them, for touch-only keyboards (mostly legacy but still...), so we need to support the freaky Javascript regex search which we did in the past for extracting metadata. While this is not necessarily going to work with hand-crafted Javascript keyboards, it should work with all kmc- and kmcomp-generated keyboards, so it will suffice to support these legacy packages.
In the future, we will be giving a hint when a package includes a .js but not a .kmx, gradually upgrading this to a warning and finally an error as we attempt to phase out .js-based keyboards in preference for .kmx keyboards.

fix(developer): some more kmc cleanup 🗜

---

common/web/gesture-recognizer/src/engine/headless/subsegmentation/README.md
common/web/gesture-recognizer/src/engine/headless/subsegmentation/constructingSegment.ts
common/web/gesture-recognizer/src/engine/headless/subsegmentation/pathSegmenter.ts
common/web/gesture-recognizer/src/engine/headless/subsegmentation/segment.ts
common/web/gesture-recognizer/src/engine/headless/trackedPath.ts
common/web/gesture-recognizer/src/engine/index.ts
common/web/gesture-recognizer/src/test/auto/headless/recordedSegmentations.js
common/web/gesture-recognizer/src/test/auto/headless/trackedPath.js
common/web/gesture-recognizer/src/tools/unit-test-resources/src/headlessRecordingSimulator.ts

Given our decision to focus on the basic gestures for now in order to prevent further delays for the feature, this PR cuts off the subsegmentation components of the engine.
I didn't outright delete the classes, but they're relegated within a clearly-marked, README-documented folder.  There was a bit of touchup to maintain the unit tests, but nothing too bad; the trickiest aspect was in regard to something I'd have had to rediscover at some point anyway, even without subsegmentation - it's the added 'TODO' tidbit.
I'll still need to touchup the design of `TrackedPath` and such; I'm sure the way forward is via cumulative stats of incoming input coordinates.  Just... the details of that will require further work, as it's a shift from the prior model.

chore(web): disconnects the gesture-oriented touchpath-subsegmentation engine 🐵

---

common/web/gesture-recognizer/build.sh
common/web/gesture-recognizer/src/engine/configuration/gestureRecognizerConfiguration.ts
common/web/gesture-recognizer/src/engine/configuration/zoneBoundaryChecker.ts
common/web/gesture-recognizer/src/engine/gestureRecognizer.ts
common/web/gesture-recognizer/src/engine/headless/cumulativePathStats.ts
common/web/gesture-recognizer/src/engine/headless/inputSample.ts
common/web/gesture-recognizer/src/engine/headless/subsegmentation/pathSegmenter.ts
common/web/gesture-recognizer/src/engine/headless/subsegmentation/segment.ts
common/web/gesture-recognizer/src/engine/headless/trackedPath.ts
common/web/gesture-recognizer/src/engine/headless/trackedPoint.ts
common/web/gesture-recognizer/src/engine/index.ts
common/web/gesture-recognizer/src/engine/inputEventEngine.ts
common/web/gesture-recognizer/src/engine/mouseEventEngine.ts
common/web/gesture-recognizer/src/engine/touchEventEngine.ts
common/web/gesture-recognizer/src/engine/trackedInput.ts
common/web/gesture-recognizer/src/engine/trackedPoint.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/headlessRecordingSimulator.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/hostFixtureLayoutController.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/inputSequenceSimulator.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/sequenceRecorder.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/touchpathTurtle.ts

For many of the gestures we're looking to add, it will be important to know properties of the key...
- underneath the touchpoint at the start
- longpress:  the base key
- flicks:  the base key
- multitap: the original key
- underneath it at a given point in time / the end (once complete)
- longpress (before subkey menu): if not the same key as the original, cancel it
- longpress (with subkey menu):  the selected subkey
- multitap:  if it's not the same key as the original, it can't be part of a multitap with the original.
The changes of this PR seek to enhance support for these needs in a couple of ways:
1.  Each `TrackedPoint` (corresponding to a single touchpoint in an ongoing gesture) now facilitates tracking the 'items' initially and currently underneath it - "hovered items".
- …

change(web): tracking for 'initial' and 'current' UI item per touchpoint 🐵

---

common/web/gesture-recognizer/src/engine/inputEventEngine.ts
common/web/gesture-recognizer/src/engine/mouseEventEngine.ts
common/web/gesture-recognizer/src/engine/touchEventEngine.ts
common/web/gesture-recognizer/src/test/resources/json/segmentation/flick_ne_se.json
common/web/gesture-recognizer/src/test/resources/json/segmentation/nonstationary_hold.json
common/web/gesture-recognizer/src/tools/unit-test-resources/src/headlessRecordingSimulator.ts

On reviewing the old code and when disabling subsegmentation in #9067, I noticed some issues regarding end-of-sequence modeling for automated tests.  By making sure there is always a sample at the _time_ of the touchpath's end, we can avoid the problem.
If the touchpath was in motion at the time, a sample already exists - this was the common case for the existing test sequences.  If it was being held, though... there wasn't a matching sample.  It was easy enough to add "in post," though, and it's easy enough to detect at the time of recording for future test sequences, too.

fix(web): touchpath recordings always sample end of path, even when stationary 🐵

---

.github/workflows/deb-packaging.yml

The previous version of gha-ubuntu-packaging was faulty.

fix(linux): Fix packaging GHA

---

windows/src/desktop/kmshell/main/UfrmChangeHotkey.dfm

Fixes: #9093 
Add an extra row for the change text label to accommodate the German and Kannada translations.
I did try auto-size but wasn't sure how to get the rest of the GUI objects on the form to flow down the page as well. 
* TEST_CHANGE_LBL
With build artifacts with this PR follow the following steps. These have been taken from the original issue #9093
1. Open Keyman Configuration dialog.
2. Download and Install Khmer Angkor keyboard.
3. Change the UI language to Kannada.
4. Click the 'no hotkey' link button in the Keyboard Layouts view.
5. Verify noticed the last line of Kannada text is fully visible.
6. Repeat steps 3-5 selecting Deutsch (German) instead.

fix(windows): adds an extra row for Change Hotkey text label

---

.github/workflows/deb-packaging.yml

This works around the permission problem we got with the previous commit.

fix(linux): Another attempt to fix packaging GHA

---

web/src/test/manual/web/inline-osk/index.html

Looks like I somehow missed fixing this manual test page fully during the ES-module work, but at least it's just a simple fix that's required.

fix(web): fixes up Web's InlinedOSK manual test page

---

web/ci.sh

Fixes #9176.
So, I'd disabled the Sentry sourcemap-uploads a bit before ES module work took place during 17.0-alpha in #7474.  It's been that way since then for 17.0 alpha, but 16.0 alpha still did proper sourcemap-uploading.
This PR seeks to re-establish that uploading so we can get nice stacktraces in our Sentry reports again.

fix(web): re-establishes web srcmap uploading

---

linux/keyman-config/keyman_config/keyboard_details.py

Before this change:
With this change:

fix(linux): Fix vertical alignment of labels in About dialog

---

linux/keyman-config/keyman_config/keyboard_details.py

Fixes #9005.
- The test can be run on any Linux platform
- Reboot
- Download and install Syriac/Aramaic keyboard
**TEST_SCROLLBAR**:
- Open Keyman Configuration and select Syriac/Aramaic keyboard
- Click About button
- verify that a scrollbar is available (if necessary) so that the entire content is accessible

fix(linux): Add scrollbar to About dialog

---

linux/keyman-config/keyman_config/keyboard_details.py

This is a temporary workaround - see discussion on #8057. While this is not the perfect solution it should improve things in most cases.
Fixes #4769.
Before this change:
With this change:
- The tests can be run on any Linux platform.
- Reboot
- Install "Khmer Angkor" keyboard
**TEST_NOTAG**: 
- Open Keyman Configuration and select "Khmer Angkor" keyboard
- click About button
- verify that the package description field doesn't show tags

fix(linux): Remove tags from package description

---

linux/keyman-config/keyman_config/uninstall_kmp.py
linux/keyman-config/tests/test_uninstall_kmp.py

After this change uninstalling a keyboard will remove all installed language/keyboard combinations for that particular keyboard. Previously we only uninstalled for the first language listed in the keyboard.
This will be tested as part of #9017.

fix(linux): Fix uninstalling keyboard for multiple languages with ibus

---

developer/src/kmc-ldml/src/compiler/compiler.ts
developer/src/kmc-ldml/src/compiler/messages.ts
developer/src/kmc-ldml/src/compiler/section-compiler.ts
developer/src/kmc-ldml/src/compiler/tran.ts
developer/src/kmc-ldml/src/compiler/vars.ts
developer/src/kmc-ldml/test/helpers/index.ts

- remove async SectionCompiler.init()  and all callers
- the usetparser lives on the DependencySections, initialized by kmc-ldml (and by the test harnesses)
for: #7377

chore(developer): refactor so KmnCompiler only created once within kmc 🙀

---

common/web/types/src/ldml-keyboard/pattern-parser.ts
common/web/types/test/ldml-keyboard/test-pattern-parser.ts
developer/src/kmc-ldml/test/fixtures/sections/ordr/multi-escape.xml
developer/src/kmc-ldml/test/test-tran.ts

- \u{22 0127} acts like \u{22}\u{0127}
for: #7377

fix(common): support multichar escapes in element sets 🙀

---

docs/build/linux-ubuntu.md
linux/Dockerfile

- add keyman ppa and update to patched ibus
- install nodejs 18
- update documentation
Note that there are still missing dependencies for building Core according to the documentation. See #8913.

chore(linux): Update docker builds

---

ios/build.sh
ios/engine/build.sh
ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
ios/keyman/build.sh
ios/samples/KMSample1/build.sh
ios/samples/KMSample2/build.sh
ios/samples/common.inc.sh

Just a few fixes for odds and ends I ran into with the new script format after it landed.
1.  Looks like I do need to remove the custom `--debug` definition after all; it seems to be incompatible with `builder_is_debug_build` in some scenarios.
- It wasn't propagating to the `:app` build, which failed on code signing when launched with `ios/build.sh --debug build:app`.
2. Found a few missing `#/usr/bin/env bash` headers, and also a few spots it was missing within the Xcode project setup
3. Fixed the sample-app builds not properly detecting their build outputs upon completion.

chore(ios): minor build-script cleanup

---

linux/ibus-keyman/build.sh

This will allow to run the integration tests on TC separately with lower priority.

chore(linux): Allow to run tests without integration tests

---

web/ci.sh

Went to double-check that everything was patched up after #9179... and it's a good thing I did.  Long story short, 
> ```
>   > Bundled 0 files for upload
> ```
So... we ran the tool, but it didn't actually upload anything.  🤦  We obviously want to upload a couple of things, hence round 2 here.
That's from the CI build logs:
```
00:59:24 
Source Map Upload Report
00:59:24 
Upload successful.
00:59:24 
/c/BuildAgent/work/99b311828f4ee7c/keyman/web
00:59:24 
/c/BuildAgent/work/99b311828f4ee7c/keyman/web/build/publish/release /c/BuildAgent/work/99b311828f4ee7c/keyman/web
00:59:24 
Uploading to Sentry...
00:59:25 
> Rewriting sources
00:59:25 
> Adding source map references
00:59:25 
> Bundled 0 files for upload
00:59:25 
> Uploaded release files to Sentry
00:59:25 
> File processing complete …
```

fix(web): sentry sourcemapping round 2 - yesterday's 'fix' unfortunately doesn't upload the maps

---

common/tools/sourcemap-path-remapper/src/index.ts
common/web/sentry-manager/build-bundler.js
web/ci.sh
web/common.inc.sh
web/src/app/browser/build.sh
web/src/app/ui/build.sh
web/src/app/webview/build.sh
web/src/tools/building/sourcemap-root/index.ts

As noted in #9199, from 
https://keyman.sentry.io/share/issue/3f6a18ac8a3d403c9636709278172b25/ ...
The sourcemap `sources` entries are not normalized by Sentry when prepending the `sourceRoot`.  We still get linkage to the original repo source without it, but a little elbow grease and pre-normalization can make the stack-trace paths simpler to read.

chore(web): normalizes sourcemap paths for cleaner Sentry reports

---

linux/keyman-config/keyman_config/install_window.py
linux/keyman-config/keyman_config/uninstall_kmp.py
linux/keyman-config/km-package-install
linux/keyman-config/km-package-install.bash-completion
linux/keyman-config/tests/test_uninstall_kmp.py

This change makes it possible to install the same keyboard again for a different language. It won't be visible in the GUI if the keyboard is installed for more than language, but it will show up for the installed languages in the keyboard dropdown.
We no longer ask the user if he tries to install a keyboard that is already installed with the same version. The only time we ask is for downgrades.
A similar change is implemented in `km-package-install` where we changed the logic to match `install_window.py`. We now silently install the new version unless it's a downgrade in which case we output a error message and exit. This change also introduces the
`--force` parameter which allows to install the downgrade. For upgrades or re-installing the same version it will cause an
uninstall of the …

feat(linux): Allow to install keyboard for multiple languages

---

linux/build.sh
linux/keyman-config/build.sh
linux/keyman-system-service/build.sh

This allows to use the `linux/build.sh` file to specify the `--no-integration` flag which makes it easier to specify jobs on CI because CI then doesn't need to know all subprojects.

chore(linux): Add support for `--no-integration` flag to build files

---

common/web/keyboard-processor/src/keyboards/keyboard.ts
web/src/engine/main/src/keymanEngine.ts

Fixes #8738.
This PR seeks to add additional metadata about the engine-state for logged errors and events:
- the id and version of the active keyboard
- the id of the active model
- the current layer of the OSK
----
Example report with the new enhancements:
```
{
"configReport": {
"hostDevice": {
"browser": "safari",
"formFactor": "phone",
"OS": "ios",
"touchable": true
},
"initialized": true,
"attachType": "auto",
"ui": "",
"keymanEngine": "app/browser"
},
"keyboard": {
"id": "us",
"langId": "en",
"version": ""
},
"model": {
"id": "nrc.en.mtnt"
},
"osk": {
"banner": "suggestion",
"layer": "shift"
}
}
```
The test-page `us` keyboard actually _doesn't_ have a `KBVER` entry, hence the blank `version` field.
Round 2:  same 'test device', different keyboard
```
{
"configReport": { …
```

feat(web): logs enhanced debug info for error reports

---

web/src/engine/osk/src/views/oskView.ts

The warning being silenced here is on a pathway being called by some aspect of the iOS-app's keyboard management, so we're getting a number of Sentry warnings about it.  There are a few loose calls to `setOskHeight`, and it's not clear which is responsible.
In retrospect... the case for this warning is 'standard enough' - if the OSK-consumer hasn't spec'd size, they should at least try to handle that first, even without a warning.

fix(web): silences low-priority warning that shows up in iOS kbd init

---

common/web/keyman-version/package.json
common/web/types/package.json
common/web/types/src/main.ts
common/web/types/src/util/compiler-interfaces.ts
common/web/types/test/helpers/TestCompilerCallbacks.ts
developer/src/common/web/test-helpers/index.ts
developer/src/common/web/test-helpers/package.json
developer/src/common/web/test-helpers/verifyCompilerMessagesObject.ts
developer/src/kmc-analyze/package.json
developer/src/kmc-kmn/package.json
developer/src/kmc-ldml/package.json
developer/src/kmc-model-info/package.json
developer/src/kmc-model/package.json
developer/src/kmc-package/package.json
developer/src/kmc-package/test/test-kmp-inf-writer.ts
developer/src/kmc/package.json
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/buildClasses/BuildProject.ts
developer/src/kmc/src/messages/NodeCompilerCallbacks.ts
developer/src/kmc/src/messages/messages.ts
package-lock.json

Fixes #8795.
Fixes #9230.
Relates to #9090.
Cleans up and makes consistent compiler messages in kmc, and related unit tests.
Adds support for colorized messages.
Standardizes on `KMxxxxx` for the error code format, which should make them reasonably searchable long-term.
After installing chalk for ansi coloring in kmc, @types/node needed to be brought in sync with the Typescript version, per the suggestion of checking against `npm dist-tags @types/node`,found in a discussion at https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64262#discussioncomment-4905069
Additional tidying up includes:
* Deprecating a set of functions in compiler-interfaces, bringing them together under a new CompilerError class. Separating CompilerErrorSeverity and CompilerErrorMask enums.
* Making …

chore(developer): cleanup compiler messages in kmc 🗜

---

common/web/types/src/util/compiler-interfaces.ts
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/messages/NodeCompilerCallbacks.ts

Fixes #9233.
Adds `--color` and `--no-color` switches to kmc command line, with default being determined by console mode.
Also ensures color initialization happens just once in NodeCompilerCallbacks and moves constants to top of file.
Let's try and see if we can do some tests!
1. Install Keyman Developer first.
2. For these tests, locate a keyboard project (.kpj) file and start a console.
3. Use `cd` to move to the folder of the .kpj project, called below `your.kpj`.
**TEST_DEFAULT_COLOR_MODE:** In the console, type `kmc build your.kpj` (replace `your.kpj` with your own project name). The project should build, with colored log text.
**TEST_COLOR_MODE:** In the console, type `kmc build --color your.kpj` (replace `your.kpj` with your own project name). The project should build, with colored …

chore(developer): add `--color` switch to kmc 🗜

---

common/web/types/src/main.ts
common/web/types/src/util/compiler-interfaces.ts
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/buildClasses/BuildProject.ts
developer/src/kmc/src/messages/NodeCompilerCallbacks.ts

Fixes #9100.
The `compilerWarningsAsErrors` option can be passed in as a command-line option or in the project options. Command-line option, if present, takes precedence over the project option. If neither is set, then the value is `false`.
Handling of this is within kmc, rather than individual modules.
TODO:

chore(developer): handle compilerWarningsAsErrors option 🗜

---

common/web/types/src/kmx/kmx-plus-builder/build-vars.ts
common/web/types/src/kmx/kmx-plus-builder/kmx-plus-builder.ts
developer/src/kmc-ldml/test/fixtures/basic.txt

- populate the 'elem' field of set variables
- this will be needed for mapFrom/mapTo
For: #7375
found during a recent TODO sweep

fix(common): set variables need to serialize elementstring 🙀

---

linux/keyman-config/keyman_config/convertico.py

fix(linux): Replace deprecated `Image.ANTIALIAS`

---

developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/buildClasses/BuildProject.ts

fix(developer): use relative paths in kmc messages 🗜

---

common/web/types/.gitignore
common/web/types/build.sh
common/web/types/src/keyman-touch-layout/keyman-touch-layout-file-reader.ts
common/web/types/src/kpj/kpj-file-reader.ts
common/web/types/src/kvk/kvks-file-reader.ts
common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts
common/web/types/src/main.ts
common/web/types/src/osk/osk.ts
common/web/types/src/schemas.ts
common/web/types/src/util/compiler-interfaces.ts
common/web/types/test/helpers/TestCompilerCallbacks.ts
common/web/types/test/helpers/index.ts
common/web/types/test/helpers/reader-callback-test.ts
common/web/types/test/keyman-touch-layout/test-keyman-touch-layout-file-reader.ts
common/web/types/test/kpj/test-kpj-file-reader.ts
common/web/types/test/kvk/test-kvk-round-trip.ts
common/web/types/test/kvk/test-kvks-file.ts
common/web/types/tsconfig.json
developer/src/common/web/test-helpers/index.ts
developer/src/kmc-analyze/src/osk-rewrite-pua/index.ts
developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-ldml/build.sh
developer/src/kmc-ldml/src/compiler/compiler.ts
developer/src/kmc-ldml/test/helpers/index.ts
developer/src/kmc-ldml/test/test-compiler-e2e.ts
developer/src/kmc/build.sh
developer/src/kmc/src/commands/buildClasses/BuildProject.ts
developer/src/kmc/src/util/NodeCompilerCallbacks.ts

Fixes #9253.
Removes the `loadSchema` function and instead resolves schema with import statements. Next commit will do the same work for Developer modules.
Note that this uses "import assertions" which are still experimental, but implemented in Node 17+, and are being renamed to "import attributes". Use of the `@ts-expect-error` hint will help cleanup and checking when we upgrade TS.

refactor(common): bundle schemas into web/types 🗜

---

core/src/ldml/ldml_transforms.cpp
core/src/ldml/ldml_transforms.hpp
core/tests/unit/ldml/test_transforms.cpp

for #9120
- this implements the algorithm, only called by unit tests right now
there are some TODOs:
- does not handle runs properly. That is, more than one cluster may be jumbled
- tertiary is not handled yet
- std::u32string call path is only called by unit tests, whereas the std::u16string call path is used by the processing code to pickup other transforms
- does not load reorders from KMX+

feat(core): implement reorder  🙀

---

core/src/ldml/ldml_transforms.cpp
core/src/ldml/ldml_transforms.hpp
core/tests/unit/ldml/keyboards/k_200_reorder_nod_Lana-test.xml
core/tests/unit/ldml/keyboards/k_200_reorder_nod_Lana.xml
core/tests/unit/ldml/keyboards/meson.build

- load reorder groups and their usets from KMX+
- add a test case matching the nod-Lana spec entry
(the interesting cases commented out for now)
For: #7375
~[I somehow picked up #9259 so will need to rebase once that merges]~ fixed it…

feat(core): load reorder from kmx+, test case 🙀

---

common/windows/delphi/Defines.mak
developer/src/inst/kmdev.wxs
oem/firstvoices/windows/src/inst/firstvoices.wxs
windows/src/Defines.mak
windows/src/desktop/inst/keymandesktop.wxs

Disables compression for .msi build and .exe installer for debug and PR test builds for Windows and Developer.
Single-test comparison of build times and resulting total file sizes for Developer and Windows on the agents:
Build | Before | After
-------|--------|-------
Windows time | 13-18 minutes | 10 minutes
Windows size | 240mb | 485mb
Developer time | 28-35 minutes | 21 minutes
Developer size | 304mb | 597mb

chore(windows): disable wix compression for debug builds

---

developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/util/fileLists.ts
developer/src/kmc/test/fixtures/file-lists/files.txt
developer/src/kmc/test/test-fileLists.ts

Fixes #9162.
Adds support for `@files.txt` parameters in kmc. Files listed in this file, separated by line breaks, will be added to the input file list, relative to the path of files.txt.
The file can include comments in lines starting with '#' and ignores whitespace before and after each filename.

feat(developer): support file lists in kmc

---

developer/src/kmc/src/util/NodeCompilerCallbacks.ts

fix(developer): warning suppression should be per file in kmc 🗜

---

core/src/ldml/C7043_ldml.md

- mapFrom / mapTo are actually strings
#7375
found during review with @rc-swag !

spec(core): minor fix to tran spec  🙀

---

common/web/gesture-recognizer/src/test/auto/browser/CI.conf.cjs
common/web/gesture-recognizer/src/test/auto/browser/cases/recordedCoordSequences.js
common/web/gesture-recognizer/src/test/resources/json/receiver/embeddedBorderCancel.json
common/web/utils/src/test/timeoutPromise.js
web/ci.sh

Up until now, the gesture-recognizer's automated tests haven't actually been run by our CI.  This PR seeks to fix that... along with a few issues that were causing certain test configurations to fail.
While this was originally included as part of #9267, it appears best to have it implemented as its own PR due to "fun" complications, mostly surrounding testing on real Android devices via BrowserStack.  In particular...
https://github.com/keymanapp/keyman/blob/30c23760ae010bfcd59210ed9a533b9ef8746ae9/common/web/gesture-recognizer/src/test/auto/browser/cases/recordedCoordSequences.js#L48-L55
I spent pretty much all of yesterday afternoon trying every angle I could think of to work around the issue described there that _didn't_ involve coercing the "mouse-based" sequences to use "touch-based" …

chore(web): connects gesture-recognizer tests for Web CI testing 🐵

---

common/web/gesture-recognizer/src/engine/headless/cumulativePathStats.ts
common/web/gesture-recognizer/src/engine/headless/gesturePath.ts
common/web/gesture-recognizer/src/test/auto/headless/gesturePath.js
common/web/gesture-recognizer/src/test/auto/headless/pathStats.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/touchpathTurtle.ts

I just realized that in #9261, while I did rename `TrackedPath` to `GesturePath`, I neglected to update the name of its most directly-related unit test specification accordingly.  While I was at it, I took a look at the code-coverage reports and what they identified as being "not covered" and realized that a few of the blocks would be worth unit testing:
1. Serialization and deserialization of `GesturePath` data.  
- While this functionality won't be needed in the live, published version once integrated, it plays a significant role in facilitating many of the automated tests.
2. `CumulativePathStats.buildRenormalized` is fairly mathematically-involved yet lacked a proper test.
- Also, basic zero-sample and single-sample cases, but at least those are super-simple to spec.
Taking a page …

chore(web): gesture-engine unit test touchup 🐵

---

common/web/types/src/util/compiler-interfaces.ts
common/web/types/test/helpers/TestCompilerCallbacks.ts
developer/src/common/web/test-helpers/index.ts
developer/src/kmc-model-info/.eslintrc.cjs
developer/src/kmc-model-info/src/model-info-compiler.ts
developer/src/kmc-model-info/test/test-model-info-compiler.ts
developer/src/kmc/src/commands/buildClasses/BuildModelInfo.ts
developer/src/kmc/src/kmlmi.ts
developer/src/kmc/src/util/NodeCompilerCallbacks.ts

Fixes #9286.
Refactors the use of path and fs into the standard kmc callbacks pattern and adds `callbacks.fileSize()`, which is needed for populating the metadata file.
Turns on eslint test for node dependencies for kmc-model-info.

refactor(developer): remove node dependencies from kmc-model-info 🗜

---

developer/src/kmc-model/.eslintrc.cjs
developer/src/kmc-model/src/build-trie.ts
developer/src/kmc-model/src/lexical-model-compiler.ts
developer/src/kmc-model/src/main.ts
developer/src/kmc-model/test/test-compile-model-with-pseudoclosure.ts
developer/src/kmc-model/test/test-compile-model.ts
developer/src/kmc-model/test/test-punctuation.ts

Fixes #9288.
Tweaks a couple of unit tests to ensure callbacks are available, and stops masking exceptions in one test with `doesNotThrow`... if it's gonna throw then the test is gonna go bang anyway.

refactor(developer): remove node deps from kmc-model 🗜

---

linux/ibus-keyman/man/ibus-engine-keyman.1
linux/ibus-keyman/src/main.c

`ibus-engine-keyman` accepted a `--verbose` and `-v` command line option which didn't do anything. Instead this change adds a comment explaining how to get more verbose output.
This change also updates the man page to reflect the actual options.

docs(linux): Update man page and remove do-nothing option

---

linux/ibus-keyman/tests/meson.build
linux/ibus-keyman/tests/scripts/run-single-test.sh
linux/ibus-keyman/tests/scripts/run-tests.sh
linux/ibus-keyman/tests/scripts/setup-tests.sh
linux/ibus-keyman/tests/scripts/teardown-tests.sh
linux/ibus-keyman/tests/scripts/test-helper.inc.sh

Because we passed in a wrong parameter (`--wayland`) but checked for just `wayland` we never run the tests with Wayland. This change rectifies this.

chore(linux): Fix running tests with Wayland

---

linux/keyman-config/keyman_config/ibus_util.py

`getpass.getuser()` tries several different ways to get the username and is the recommended way of getting the username.

refactor(linux): Use better way to get username

---

linux/keyman-config/keyman_config/ibus_util.py
linux/keyman-config/keyman_config/uninstall_kmp.py

This change reworks the output we show if the user tries to uninstall a non-existing keyboard. This could be trying to uninstall a shared keyboard when a user keyboard exists and vice versa. This change rewords the message to include the area (shared/user), so hopefully this makes it a bit clearer. We also now output this as a warning instead of an error.
Completely suppressing the message as suggested in #9213 doesn't seem to be the right way as that would lead to the user blaming uninstall to not work when the real reason are wrong parameters.
Closes #9213.
- The tests can be run on any Linux platform
- Reboot
**TEST_MULTIPLE_UNINSTALL**: 
- Open …

fix(linux): Reword error if uninstalling non-existent keyboard

---

linux/keyman-config/keyman_config/__init__.py
linux/keyman-config/keyman_config/ibus_util.py
linux/keyman-config/keyman_config/sentry_handling.py
linux/keyman-config/keyman_config/uninstall_kmp.py
linux/keyman-config/km-config
linux/keyman-config/km-kvk2ldml
linux/keyman-config/km-package-get
linux/keyman-config/km-package-install
linux/keyman-config/km-package-list-installed
linux/keyman-config/km-package-uninstall

We can't initialize Sentry during module initialization because our `initialize_sentry` method logs some status info. Setting the logging level later on is then a no-op, breaking verbose and very-verbose logging.
This change fixes this by putting Sentry initialization into a separate method that gets called after we set the log level.
Also refactor some common code into methods that appear in all our executables.

fix(linux): Fix logging

---

common/windows/delphi/chromium/Keyman.UI.UframeCEFHost.pas

Fixes: #9044 
Fixes: #9018
When opening a local pdf with the CEF module it causes prompt to install an extension. This change opens the local pdf in a browser in the same way the external pdf and webpages are loaded.
1. Install Keyman build artifact with this PR
2. Open Keyman Configuration dialog. 
3. Download and Install Khmer Angkor keyboard. 
4. Open Khmer Angkor keyboard in Keyboard Layouts view. 
5. Click the Help button. 
6. Click the blue link `here` under the `Keyboard Documentations` heading. 
Expected Result the pdf should now open in a web browser window.
This should be the same behaviour(open in browser window) as clicking the `Khmer Scripty by Unicode Standard` right at the bottom of the Khmer Ankor help.

fix(windows): open pdf in an external browser

---

common/web/input-processor/tests/cases/languageProcessor.js
common/web/types/src/kpj/keyman-developer-project.ts
common/web/types/src/kpj/kpj-file-reader.ts
common/web/types/src/kpj/kpj-file.ts
common/web/types/src/util/compiler-interfaces.ts
developer/src/common/include/kmn_compiler_errors.h
developer/src/kmc-kmn/src/compiler/messages.ts
developer/src/kmc-kmn/src/kmw-compiler/messages.ts
developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts
developer/src/kmc-model/src/lexical-model-compiler.ts
developer/src/kmc-model/src/main.ts
developer/src/kmc-model/test/test-compile-model-with-pseudoclosure.ts
developer/src/kmc-model/test/test-compile-trie.ts
developer/src/kmc-model/test/test-punctuation.ts
developer/src/kmc-package/src/compiler/package-validation.ts
developer/src/kmc-package/test/test-messages.ts
developer/src/kmc/src/commands/buildClasses/BuildPackage.ts
developer/src/kmc/src/commands/buildClasses/BuildProject.ts
developer/src/kmc/src/kmlmi.ts
developer/src/kmc/src/kmlmp.ts
developer/src/kmc/src/messages/messages.ts
developer/src/kmc/src/util/NodeCompilerCallbacks.ts

* Fixes #9300: respect checkFilenameConventions in kmc
* Fixes #9299: clean up warning KM02093
* Fixes #9298: use relative paths for KM05009
* Fixes #9297: consistently show filename for messages in kmc
* Fixes #9296: reduce KM0208A to info severity
Throws in: warning colour changed to orange to differentiate from line number colour.
Note for #9296: 208A in kmcmplib is the awkwardly-named CWARN_Info. We now have an 'info' severity in kmc, so this tidies that up (we can keep the same flag in kmcmplib for now).

fix(developer): kmc warnings tidyup 🗜

---

web/src/engine/package-cache/src/cloud/queryEngine.ts
web/src/engine/package-cache/src/keyboardRequisitioner.ts

Fixes https://github.com/keymanapp/keymanweb.com/issues/77.
The modularized design for KMW's cloud interactions assumes that there's always a `Promise` for any incoming `keyman.register` calls.  That said, keymanweb.com likes to pre-cache the keyboards query and directly register it in a manner that bypasses cloud queries and the associated Promises.  Since there was no `Promise` bound to the register, KMW had no infrastructure for forwarding the precached stubs.
So, this PR adds in a relatively simple rigging to remedy that issue.

fix(web): allows registering precached keyboards

---

common/web/gesture-recognizer/src/engine/headless/complexGestureSource.ts
common/web/gesture-recognizer/src/engine/headless/gestures/matchers/pathMatcher.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/contactModel.ts
common/web/gesture-recognizer/src/engine/headless/simpleGestureSource.ts
common/web/gesture-recognizer/src/engine/headless/touchpointCoordinator.ts
common/web/gesture-recognizer/src/engine/inputEventEngine.ts
common/web/gesture-recognizer/src/engine/mouseEventEngine.ts
common/web/gesture-recognizer/src/engine/touchEventEngine.ts

Pretty much what the title says - these changes ensure:
- updates from the same touch event have perfectly-matching timestamps
- all active touchpaths are always updated, not just those that changed...
- ... so that `ComplexGestureSource` instances can verify that all component paths have been updated for a multitouch gesture before processing gesture-related updates.  (Running gesture-update logic & calcs while only half-updated could pose problems.)
The latter point was the main motivator, even if it's not needed at the immediate moment.  That said, it's a problem that's been on my mind, repeatedly, for a while - so this helps me reclaim headspace and move on to the other things that need doing.  (Fortunately, it was pretty easy to isolate.)

fix(web): syncs timestamps of active contact points, paths 🐵

---

linux/scripts/launchpad.sh

Ubuntu 22.10 Kinetic is no longer supported, so this change omits it from uploading to Launchpad.

chore(linux): Remove obsolete dist from uploading to launchpad

---

common/web/types/src/kmx/keyman-targets.ts
common/web/types/src/kmx/kmx-file-reader.ts
common/web/types/src/kmx/kmx.ts
common/web/types/src/main.ts
common/web/types/test/kmx/test-keyman-targets.ts
developer/src/kmc-package/src/compiler/package-keyboard-target-validator.ts

Also adds unit test. Prep for use in kmc-keyboard-info.

refactor(developer): move keyman-targets.ts to common/web/types 🗜

---

core/tests/unit/ldml/keyboards/k_020_fr-test.xml
core/tests/unit/ldml/keyboards/k_020_fr.xml
core/tests/unit/ldml/keyboards/meson.build
developer/src/kmc-ldml/src/compiler/messages.ts
developer/src/kmc-ldml/src/compiler/visual-keyboard-compiler.ts
developer/src/kmc-ldml/src/compiler/vkey.ts
developer/src/kmc-ldml/test/test-vkey.ts
resources/standards-data/ldml-keyboards/techpreview/3.0/fr-t-k0-azerty.xml

Note that feat(core): ldml vkey support 🙀 #7135 is future, in the future this may be an Error again.
- also, add an internal error to the visual-keyboard-compiler on missing keys
- also, update fr-t-k0-azerty to fix a missing key (simultaneous fix has been made in CLDR)
- also, reinstate CLDR's fr-t-k0-azerty - now all 'stock' keyboards build in keyman!
- keep the 'internal' azerty as k_020 - it has some additional transform goodies
Fixes: #9236

chore(developer): make unknown vkey a hint, not error 🙀

---

core/src/kmx/kmx_plus.h

fix(core): tag KMXPlus file-based structs with alignment 🙀

---

common/web/gesture-recognizer/package.json
common/web/gesture-recognizer/src/engine/headless/cumulativePathStats.ts
common/web/gesture-recognizer/src/engine/headless/gesturePath.ts
common/web/gesture-recognizer/src/test/auto/headless/gesturePath.js
common/web/gesture-recognizer/src/test/auto/headless/pathStats.ts
common/web/gesture-recognizer/src/test/auto/headless/recordedSegmentations.js
common/web/gesture-recognizer/src/test/auto/tsconfig.json
common/web/gesture-recognizer/src/tools/unit-test-resources/src/touchpathTurtle.ts

This PR largely serves to present a few significant changes first made in #9320 in isolation.  This grouping has a remarkably small line-change count, but there are enough altered details here as it is.
1. The "unit test resources" subproject was being included in headless tests via a nasty, long import path with lots of `../` entries.  I remembered the whole "subpath imports" thing I discovered during ES module (🧩) work and decided to re-use that here.
Turns out to be a bit trickier when developing TS-based unit tests in VS code - it wanted to ignore the import paths for some reason, but only when editing in the IDE.  It's not optimal, but I did find a sufficient workaround, so... yeah.  It's enough to proceed.  
(That random, ultra-light src/test/auto/tsconfig.json is the workaround.) …

chore(web): test/test-resource cleanup & generic typing on stats object 🐵

---

common/web/gesture-recognizer/src/engine/headless/complexGestureSource.ts
common/web/gesture-recognizer/src/engine/headless/cumulativePathStats.ts
common/web/gesture-recognizer/src/engine/headless/gesturePath.ts
common/web/gesture-recognizer/src/engine/headless/gestures/matchers/pathMatcher.ts
common/web/gesture-recognizer/src/engine/headless/simpleGestureSource.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/pathMatcher.spec.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/headlessInputEngine.ts

Continuing from point 3 of #9338, this PR allows the matching algorithm to (effectively) segment the touch-contact paths corresponding to gestures as the paths and/or gestures change state.
1.  During gesture-matching and gesture-selection work, the need to allow "resetting" a path - to observe only the new portions - became quite evident.  Some potential gesture specifications may want this reset while others do not... so the best way forward appears to be providing "subviews" into the path.  
2. These "subviews" will be updated when their base "source" receives updates until "disconnected" at a later time.  This is done via event-handlers attached to the original, base "source" that the "subview" aliases.
3.  When a ContactModel is fully matched, a snapshot of the path segment …

feat(web): gesture path snapshots 🐵

---

linux/scripts/package-build.inc.sh

If another package build runs on the same build agent at the same time and installs dependencies at the same time, previously the build failed because apt/dpkg was already running. This change checks for the existence of the apt/dpkg lock file and waits until the other process is finished before starting the installation of dependencies.

chore(linux): Don't fail on parallel builds

---

windows/src/README.md

Doing a fresh build setup following the Readme.MD noticed the making of certificates had a extra `s`. Also fixed a typo. 
`nmake test-certificate`

docs(windows): corrected nmake cmd for certificates

---

core/src/ldml/ldml_transforms.cpp
developer/src/kmc/src/commands/build.ts

Fixes #9377.
1. ldml_transforms.cpp used emplace_back with char instead of dword values (#9377)
2. import was updated to src/ instead of ../ by vscode in build.ts (no related issue)

chore(developer): minor patches to fix compile issues 🗜

---

docs/build/linux-ubuntu.md
docs/build/windows.md
linux/Dockerfile

This adds the documentation how to build Keyman Web as well as Keyman for Android on Linux. and adds the dependencies to the `Dockerfile` so that it's now also possible to build Keyman Web and Keyman for Android with Docker.

docs(linux): Add build doc for Keyman Web and Android

---

web/src/app/browser/src/contextManager.ts

Fixes https://github.com/keymanapp/keyman/issues/9404.
It turns out that the issue was due to a small mishandling of state management when in a focus-maintenance state.
TEST_TOOLBAR_KEYBOARD_SWAP:  Using the "Desktop UI module testing" test-page link on a desktop form-factor device...
1. Set the page to use the Toolbar UI.
2. Ensure that any KMW keyboard is active and type a couple of keys.
3. Use the toolbar UI to swap to the Khmer language, then select Khmer Angkor from the keyboard-selection dropdown.
4. With no further mouse interaction anywhere on the page, type the `k` key, then the `a` key.  Verify that Khmer characters are output.

fix(web): maintenance of focus when changing keyboard via Toolbar UI

---

.github/workflows/deb-packaging.yml

Don't build Ubuntu 22.10 Kinetic with packaging GHA.
Also prepare for Ubuntu 23.10 Mantic - we can't currently build that because they are trying to get ibus 1.5.29-beta to work on so there are often new packages. We wait until that stabilized before we're providing a new patched ibus version at which point we can enable building for mantic.
See also #9398.

chore(linux): Remove Kinetic from GHA

---

.github/workflows/crowdin.yml

For the upcoming Keyman team planning meeting, there was an action to change the Crowdin GHA to trigger from fortnightly to daily.

chore(common): Update crowdin GHA to trigger daily

---

common/web/lm-worker/build-wrap-and-minify.js

Fixes #9401.
Fixes #9408.
Fixes Sentry issue: [KEYMAN-WEB-DS](https://keyman.sentry.io/issues/4362964860/?referrer=github_integration).
TEST_ANDROID_5:  Using an Android 5.0 (Lollipop) device with its originally-installed version of Chrome...
1. Install and launch the Keyman app for Android
2. Verify that no errors happen on startup
3. Swap to `sil_euro_latin` for English if it is not already the active keyboard/language combination.
4. Type `app`.
5. Verify that the predictive-text banner is visible and shows reasonable suggestions.
This may be easiest to do through Android Studio emulation.

fix(web): forgot to target es5 when minifying polyfilled worker

---

HISTORY.md

Until we get around investigating why the trigger for #9415 isn't working,
this manually adds the 16.0 stable entries to HISTORY.md for master branch. 
I'm also not scrubbing the references to `:cherries:` still in the HISTORY.md log.

chore(common): Update history.md with 16.0 stable entries

---

linux/scripts/launchpad.sh

Mantic builds currently fail because there's a newer ibus version in the official Ubuntu repos that overrides our patched ibus version. Ubuntu is trying to get ibus 1.5.29-beta to work so there are often new packages. We wait until that stabilized before we're providing a new patched ibus version at which point we can enable building for Ubuntu 23.10 Mantic.
Closes #9428.

chore(linux): Disable Mantic builds on Launchpad

---

core/src/km_kbp_processevent_api.cpp
core/src/kmx/kmx_processevent.h
core/src/kmx/kmx_processor.cpp
core/src/kmx/kmx_processor.hpp
core/tests/unit/kmnkbd/action_items.hpp
core/tests/unit/kmx/kmx_external_event.cpp
core/tests/unit/kmx/meson.build
windows/src/engine/keyman32/kmprocessactions.cpp
windows/src/engine/keyman32/kmprocessactions.h
windows/src/engine/keyman32/selectkeyboard.cpp

Add external event processing to the kmx processor. 
At this point, the current modifier state has not been passed with the event. It could be passed as the third object with the void* pointer. Currently, the kmx_processor will queue a action to turn caps lock off, if the just loaded keyboard has the  `CapsAlwaysOff` store set, regardless of the current state of the capslock on the platform. 
Fixes: #5822 
For these tests, use a keyboard with the [`caps_always_off.kmp.zip`](https://github.com/keymanapp/keyman/files/8937257/caps_always_off.kmp.zip) store set. We call this keyboard _capsalwaysoff_ below.
Any keyboard with that store set will work; if you don't have one at hand you can use the `caps_always_off.kmp` keyboard. The *caps_always_off.kmp* keyboard will prevent switching caps lock …

feat(windows): Use Keyboard Activated event API call to turn off caps lock (if required) 🚏

---

common/web/types/src/util/compiler-interfaces.ts
developer/src/kmc-analyze/src/messages.ts
developer/src/kmc-keyboard-info/src/messages.ts
developer/src/kmc-kmn/src/compiler/messages.ts
developer/src/kmc-ldml/src/compiler/messages.ts
developer/src/kmc-model-info/src/messages.ts
developer/src/kmc-model/src/model-compiler-errors.ts
developer/src/kmc-package/src/compiler/messages.ts
developer/src/kmc/src/commands/analyze.ts
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/buildClasses/BuildKeyboardInfo.ts
developer/src/kmc/src/commands/buildClasses/BuildModelInfo.ts
developer/src/kmc/src/commands/buildClasses/BuildProject.ts
developer/src/kmc/src/kmc.ts
developer/src/kmc/src/messages/infrastructureMessages.ts
developer/src/kmc/src/util/KeymanSentry.ts
developer/src/kmc/src/util/NodeCompilerCallbacks.ts
developer/src/kmc/src/util/fileLists.ts
developer/src/kmc/src/util/projectLoader.ts
developer/src/kmc/test/test-infrastructureMessages.ts
developer/src/kmc/test/test-project-build.ts
package-lock.json
package.json

Fixes #8614. (Last step? Earlier work was done in #9243).
Relates to #9438.
kmc already reported unhandled exceptions, but any handled fatal errors were captured and only reported to the user. It is better to report these to Sentry as these are still unexpected.
I have refactored all the fatal exception messages in various kmc modules to use a common mechanism, keeping all the Sentry integration in kmc, now passing exception data up in the `CompilerEvent.exceptionVar` property.
* I took the opportunity to rename messages.ts to infrastructureMessages.ts
* @types/chai was missing which gave intellisense errors in vscode
* normal exit of kmc now provides an opportunity for error reports to Sentry to be finalized
* Added a unit test for fatal errors in kmc
* Added a manual test pathway with …

chore(developer): improve kmc sentry reporting on fatal build errors

---

common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureMatcher.ts
common/web/gesture-recognizer/src/engine/headless/gestures/matchers/index.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/contactModel.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/gestureModel.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/index.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/gestureMatcher.spec.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/isolatedGestureSpecs.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/isolatedPathSpecs.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/pathMatcher.spec.ts
common/web/gesture-recognizer/src/test/resources/assertingPromiseStatus.ts

This PR seeks to allow definition of different types of gestures via a relatively simple specification pattern.  This pattern, in turn, is interpreted by an algorithm capable of matching any legal configuration of the spec.  This yields a generalized gesture matcher.
This PR's features incorporate many aspects of the prospective design seen in #9252.  Some changes occurred as I started actually implementing related logic.
Assumptions:
- A separate layer will handle detection of when a new contact point belongs to the gesture being matched vs when it should remain separate.
- A separate layer (likely the same as the prior point) will manage multiple instances of this class - one per possible gesture - to facilitate gesture _selection_.
- General idea:  first one to be 'resolved' wins; any …

feat(web): gesture modeling + isolated matching 🐵

---

windows/src/desktop/kmshell/xml/config.css

Fixes: #9436
Allow QR box to grow if the caption box is bigger than the English text. Limit of 130px is set if extends further than this then add a vertical scroll for the caption.
In testing no language actually causes the scroll bar to be displayed. However, using dummy text to test the overflow shows that it will handle this should the translation ever reach this length.
Here is just a screen shot to show the vertical scroll when there is a huge amount of extra text which I don't think we will reach but am handling that use case anyway.
1. Install Keyman for Windows Build artfifact
2. Open Keyman Configuration dialog. 
3. Install a keyboard. (eg., EuroLatin(SIL) 
4. Open the Keyboard Layout View. 
5. Change the UI into Kannada. 
6. Click Share Keyboard button. 
The QR share box should …

fix(windows): allow QR share box to grow to edge of default configuration parent window

---

common/web/types/src/kmx/kmx-plus.ts

- UnicodeSetItem was ignoring the error value from sizeUnicodeSet() and calling parseUnicodeSet with an invalid size
- it *is* an error, but should be handled properly.
- an error is already recorded in the callback
This may be to better typechecking in wasm-host.js than we had before?
```
TypeError: Passing a number "-2" from JS side to C/C++ side to an argument of type "unsigned int", which is outside the valid range [0, 4294967295]!
at checkAssertions (file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc-kmn/src/import/kmcmplib/wasm-host.js:2861:17)
at Object.toWireType (file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc-kmn/src/import/kmcmplib/wasm-host.js:2867:11)
at Object.kmcmp_parseUnicodeSet (eval at newFunc …
```

fix(common): don't crash on illegal unicodesets 🙀

---

android/KMAPro/kMAPro/build.gradle
android/KMEA/app/build.gradle
android/KMEA/app/src/main/AndroidManifest.xml
android/README.md
android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample2/app/build.gradle
android/Tests/KeyboardHarness/app/build.gradle
oem/firstvoices/android/app/build.gradle

Fixes #9493 for stable-16.0
Google Play Store is requiring Android apps to target API 33 by August 31, 2023.
This 🍒 -picks portions from #7897.
Setup - Install the PR builds of Keyman for Android and FirstVoices for Android on an Android device/emulator
* **TEST_KEYMAN** - Verifies the Keyman app functions
2. Complete the "Getting Started" steps of installing a Keyman keyboard and setting Keyman as a default system keyboard
3. Verifiy the installed Keyboard functions
4. Launch a separate app (e.g. Google Chrome) and select a text area to type in
5. With Keyman as the system keyboard, verify the keyboard functions.
* **TEST_FV** - Verifies the FirstVoices Android app functions
1. Launch FirstVoices for Android
2. Complete the menu items of selecting an FV keyboard to …

chore(android): Update targetSDKVersion to 33 🏠

---

linux/keyman-config/km-kvk2ldml

This change fixes an exception that occurs if the user specifies an outputfile in a non-existing directory. Also catch several other related exceptions.
Fixes #9522.

fix(linux): Fix exception in km-kvk2ldml

---

linux/debian/meson/no-exe-wrapper.ini
linux/debian/rules

Now that Meson bug [#12017](https://github.com/mesonbuild/meson/issues/12017) is fixed we can revert the workaround.

chore(linux): Remove workaround for mips64el 🏠

---

resources/builder.inc.sh

If you had an option with a parameter, e.g. "--outfile c,b", then the "c,b" was being treated as a parameter for expansion, which caused it to expand to e.g. "configure,build". Oops.

fix(common): builder_parse broke on option parameters

---

docs/build/linux-ubuntu.md
linux/Dockerfile

emscripten 3.1.44 works, but 3.1.45 fails, so this change modifies the documentation to explicitly request `3.1.44` instead of `latest`.

docs(linux): Explicitly specify emscripten version

---

common/schemas/keyboard_info/README.md
common/schemas/keyboard_info/keyboard_info.distribution.json
common/schemas/keyboard_info/keyboard_info.schema.json
developer/src/inst/download.in.mak
developer/src/inst/kmdev.wxs
developer/src/kmc-keyboard-info/src/index.ts
developer/src/kmc-keyboard-info/src/keyboard-info-file.ts
developer/src/test/auto/keyboard-info/test-invalid-language-code.keyboard_info
developer/src/test/auto/keyboard-info/test-non-canonical-language-code.keyboard_info
developer/src/test/auto/keyboard-info/test-valid.keyboard_info
developer/src/test/auto/keyboard-info/test.bat
developer/src/tike/compile/MergeKeyboardInfo.pas
developer/src/tike/compile/ValidateKeyboardInfo.pas

This is the first PR in a chain that addresses #9351.
Removes the following fields:
* legacyId
* documentationFilename
* documentationFileSize
* links
* related[].note
None of these fields are needed any longer; see #9351 for steps to remove data.
Eliminates difference between keyboard_info source and distribution, renaming to keyboard_info.schema.json, and updating the required members of the json accordingly.
This has corresponding PRs against keyman.com, api.keyman.com, help.keyman.com, and keyboards repositories:

chore(common): remove deprecated fields from keyboard_info 🎺

---

common/schemas/kps/kps.xsd
common/web/types/src/package/kmp-json-file.ts
common/web/types/src/package/kps-file.ts
common/windows/delphi/packages/PackageInfo.pas
developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas
developer/src/kmconvert/Keyman.Developer.System.ModelProjectTemplate.pas
developer/src/tike/child/UfrmPackageEditor.dfm
developer/src/tike/child/UfrmPackageEditor.pas

Adds license file to .kps, kmp.json, kmc-package, package editor, and new project templates. The intent is for LICENSE.md to be the file used, and for any keyboards on keymanapp/keyboards, it should always be a standard MIT license.
Note: see below for upcoming enhancement to this:
* #9477
TEST_LICENSE_FIELD: In the package editor, add LICENSE.md to the package. Then, in the Details tab, select LICENSE.md in the License File field. Save the package, close and reopen and ensure that the license file field is still correct. Clear the field, save, and verify that on reloading the field is still empty.

feat(developer): add LicenseFile as property of package 🎺

---

common/schemas/keyboard_info/keyboard_info.schema.json
common/web/types/build.sh
common/web/types/src/schemas.ts
developer/src/kmc-keyboard-info/src/index.ts
developer/src/kmc-keyboard-info/src/keyboard-info-file.ts

* Adds keyboard_info.schema.json to common/web/types
* Removes font size
* Restricts font source to array
* Removes example
* Add examples
* Loosen structure of KeyboardExample

chore(developer): cleanup keyboard_info schema 🎺

---

developer/src/kmc-keyboard-info/package.json
developer/src/kmc-keyboard-info/src/index.ts
developer/src/kmc-keyboard-info/test/fixtures/khmer_angkor/build/khmer_angkor.keyboard_info
developer/src/kmc-package/package.json
developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/markdown.ts
developer/src/kmc-package/test/fixtures/kmp_2.0/kmp.json
developer/src/kmc-package/test/test-markdown.ts
developer/src/kmc/src/commands/buildClasses/BuildKeyboardInfo.ts
package-lock.json

Next part of kmc work, converts the Markdown description field in the .kps into HTML during the .kmp build. This also filters through to the .keyboard_info file.

feat(developer): convert markdown description to html 🎺

---

developer/src/kmc-keyboard-info/src/index.ts
developer/src/kmc-keyboard-info/test/test-keyboard-info-compiler.ts
developer/src/kmc/src/commands/buildClasses/BuildKeyboardInfo.ts

Relates to #9351.
Moves responsibility for loading .kps into kmc-keyboard-info, away from the caller, and removes other fields with kmc-keyboard-info can calculate by itself.
Have not moved project parsing into kmc-keyboard-info, because that's a bigger job, as currently that is mostly happening within kmc itself. A project for a future version I think.

chore(developer): cleanup kmc-keyboard-info interface 🎺

---

linux/ibus-keyman/tests/run-tests.sh

This is a workaround for running the tests on Ubuntu 22.04 Jammy. For 16.0 we don't have everything in place to successfully run the tests with Wayland. Additionally the Wayland support in Keyman is still incomplete. So we disable the Wayland tests in order to be able to get successful builds of 16.0.
This is not a problem with older Ubuntu versions because they don't have Mutter 40.x, but with the new Jammy build agent on TC we're running into this issue. Things work in `master` branch.

chore(linux): Workaround: Don't run Wayland tests 🏠

---

linux/debian/changelog
linux/debian/rules
linux/keyman-config/Makefile
linux/keyman-config/version.sh
linux/scripts/dist.sh

This allows to completely cleanup after a package build. We no longer include `version.py` in the source package. Instead this
change adds a `version.sh` script that allows to create `version.py` during a package build where we don't ship `linux/scripts/*` which contains the scripts that usually create that file. This is a workaround for 16.0 - `master` already generates `version.py` in a different way.
Fixes #9518.
Modified :cherries:-pick of #9531.

chore(linux): Add `clean` target to `rules` 🍒 🏠

---

linux/debian/rules
linux/keyman-config/build.sh
linux/scripts/dist.sh

This allows to completely cleanup after a package build. Also fixes `keyman-config/build.sh` to do a better job with clean.
Fixes #9518.

chore(linux): Add `clean` target to `rules`

---

linux/keyman-config/keyman_config/ibus_util.py

Closes #9542.
(🍒-picked from PR #9543 )

fix(linux): Prevent exception if neither USER, LOGNAME nor SUDO_USER set 🏠🍒

---

linux/scripts/dist.sh
resources/build/build-utils.sh

`environment.sh` is used only on Mac. This change modifies `build.sh` to generate this file only when building on Mac. It also excludes `environment.sh` from the Linux source tarball.

chore(linux): Exclude environment.sh from build

---

linux/ibus-keyman/tests/testfixture.cpp

`k_031___caps_lock` and `k_032___caps_control` tests from `stable-16.0` branch fail when running on ba-jammy-64-ta for unknown reasons. They pass on the `master` branch, so instead of spending a lot of time trying to find the reason we ignore them now.

chore(linux): Ignore tests that fail on ba-jammy-64-ta 🏠

---

linux/ibus-keyman/src/keymanutil.c
linux/ibus-keyman/src/main.c

This change improves the startup method so that it will also work if ibus hasn't started yet. Also fixes two memory leaks.
This is in response to sporadically failing integration tests on ba-jammy-64-ta.

chore(linux): Split startup process

---

docs/settings/linux/tasks.json
linux/ibus-keyman/build.sh

chore(linux): Add coverage action to `ibus-keyman/build.sh`

---

resources/build/build-utils.md
resources/builder.inc.sh

docs(common): Fix documentation for `builder_describe_internal_dependency`

---

linux/keyman-config/keyman_config/welcome.py

This works around the issue where browsers installed as snap package can't access files under `$HOME/.local`. Instead we now only open external links with the browser. Local non-html files we open with the default app, and links to local html file we open in webview (like we did previously with `welcome.htm` files).
Fixes #9600.
**TEST_LOCALLINK**: follow the test steps in #9600 and verify that the "Font license" and "Font documentation" files are displayed.

fix(linux): Correctly open files linked from help page

---

.github/workflows/deb-packaging.yml
linux/debian/rules
linux/ibus-keyman/build.sh
linux/ibus-keyman/src/KeymanSystemServiceClient.cpp
linux/ibus-keyman/tests/KmDbusTestServer.cpp
linux/ibus-keyman/tests/README.md
linux/ibus-keyman/tests/scripts/run-tests.sh
linux/ibus-keyman/tests/scripts/test-helper.inc.sh
linux/keyman-system-service/meson.build
linux/scripts/reconf.sh

- Fix crash if error is not set and we can't access the system service
- Check existence of `services` directory
- Update readme for ibus-keyman tests
- Make ibus-keyman depend on keyman-system-service (needed for integration tests)
- Fix meson version in keyman-system-service

chore(linux): Fix bugs, add dependency and update documentation

---

linux/keyman-config/keyman_config/sentry_handling.py

When running on Ubuntu 20.04 Focal, one of the Python dependencies loads the `unittest` module so that running `km-config` output the message that Sentry would be disabled because unit tests are running.
This change now uses the call stack to check if we're running unit tests.
Fixes #9577.
- The test should be run on Ubuntu 20.04 Focal with Gnome Shell and X11
**TEST_VERIFY**: start `km-config` from the command line and verify that no output is shown

fix(linux): Fix detection of unit tests

---

developer/src/kmc/build.sh
resources/build/build-utils-ci.inc.sh

Works around npm/cli#3466 when bundling internal dependencies using the bundleDependencies package.json property.
This change works in tandem with the npm pack/publish process -- when we run `developer/src/kmc/build.sh publish` (or `pack`), we end up with `npm version` stomping on all our package.json files, so the repo is dirty after this. We need a copy of the top-level package.json before this stomping happens, in order to get a simple map of the location of each of our internal dependencies, from the `dependencies` property (it would be possible to figure this out with a lot more parsing of our package.json files, but this is simpler).
This means, in future, we should avoid publishing our internal dependencies such as those under common/ to npm, as they serve no practical purpose …

chore: workaround npm/cli#3466 when bundling internal deps

---

linux/ibus-keyman/src/test/meson.build
linux/ibus-keyman/src/test/setup-tests.sh
linux/ibus-keyman/tests/meson.build
linux/ibus-keyman/tests/scripts/run-single-test.sh
linux/ibus-keyman/tests/scripts/setup-tests.sh
linux/ibus-keyman/tests/scripts/test-helper.inc.sh

Before we run a test we now check that ibus and the other processes we need are still running. If not we run test setup again.
This will likely fix #9570.

chore(linux): Check and restart background processes

---

web/src/app/browser/build.sh
web/src/app/ui/build.sh

@darcywong00 had a fun error come up as a result of an oversight in Web's build scripts - while two of the `app/` projects output to a `publish` folder to prepare for releases, their `clean` steps did not actually delete any previously-existing entries.  
The error he was getting... resulted from running a post-processing command on an outdated build product that wasn't deleted due to said oversight.  (The build configurations were slightly different when they were built, and the post-processing step couldn't handle the difference.)  It definitely wasn't an intuitive scenario to infer, so it's best we fix the oversight so that it doesn't cause similar issues later down the line.

chore(web): builds that output to web/build/publish should also clean it

---

linux/ibus-keyman/tests/scripts/run-tests.sh
linux/ibus-keyman/tests/scripts/test-helper.inc.sh

This improves reliability if some processes are still running from a previous run, which previously caused the tests to fail.
Also in the case of failed processes, list which ones are missing.
Additionally fixes `run-tests.sh` which I forgot to change in a previous PR.

chore(linux): Dynamically choose display number

---

common/web/types/src/main.ts
common/web/types/src/util/compiler-interfaces.ts
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/buildClasses/BuildProject.ts
developer/src/kmc/src/messages/infrastructureMessages.ts
developer/src/kmc/src/util/NodeCompilerCallbacks.ts
developer/src/kmc/src/util/baseOptions.ts

Adds logFormat of tsv vs formatted for kmc, in order to allow for "porcelain" style log formatting when we interop with TIKE.

feat(developer): add --log-format to kmc 🎺

---

android/KMAPro/kMAPro/src/main/res/values-mnw-rMM/strings.xml
android/KMEA/app/src/main/java/com/keyman/engine/DisplayLanguages.java
android/KMEA/app/src/main/res/values-mnw-rMM/strings.xml
ios/engine/KMEI/KeymanEngine/Classes/mnw.lproj/ResourceInfoView.strings
ios/engine/KMEI/KeymanEngine/mnw.lproj/Localizable.strings
ios/engine/KMEI/KeymanEngine/mnw.lproj/Localizable.stringsdict
ios/keyman/Keyman/Keyman/mnw.lproj/Localizable.strings
linux/keyman-config/locale/mnw_MM.po
mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/mnw.lproj/KMAboutWindowController.strings
mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/mnw.lproj/preferences.strings
mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/mnw.lproj/KMInfoWindowController.strings
mac/Keyman4MacIM/Keyman4MacIM/KMKeyboardHelpWindow/mnw.lproj/KMKeyboardHelpWindowController.strings
mac/Keyman4MacIM/Keyman4MacIM/mnw.lproj/Localizable.strings
mac/Keyman4MacIM/Keyman4MacIM/mnw.lproj/MainMenu.strings
windows/src/desktop/kmshell/locale/mnw-MM/strings.xml
windows/src/desktop/setup/locale/mnw-MM/strings.xml

This adds crowdin strings for Mon (`mnw-MM` written with Burmese script).
Not available for iOS or macOS.
TODO for @sgschantz 
Test the Keyman apps can change to UI in Mon
* **TEST_ANDROID** 
1. On an Android device/emulator, load the PR build of Keyman for Android
2. In the Keyman app, go to Settings --> Display language --> မန် (Mon)
3. Exit the menu and wait for the app to refresh
4. Verify the UI is in Mon
1. Install the PR build of Keyman for Windows
2. In Keyman configuration, change the UI to "မန် (Mon)"
3. Verify the UI is in Mon
1.Start Keyman configuration with: LANGUAGE=mnw_MM km-config
2. Verify Keyman UI is in Mon

chore(common): Add Crowdin strings for Mon

---

windows/src/desktop/kmshell/xml/splash.css

Fixes #9481 
The buttons already had a property to display ellipsis when the text was too big for the buttons. However the other properties such as white-space nowrap needed to be added to work in all cases. This change adds those properties and also extends the ellipsis overflow to the exit button.
Note it was noticed that "Keyman" had been localized when it shouldn't have been a separate issue has been created. #9635
Here is the result for Kannada  
The exit button for Wahu
And a bonus Marghi
1. Install Keyman 17.0.161-alpha build. 
3. Open Keyman Configuration dialog. 
4. Change the UI into Kannada. 
5. Exit Configuration 
6. Go to the Splash Screen
Observe now that the extra-long text is truncated with ellipses  "..."
Repeat for Wahu and Marghi

fix(windows): fix the ellipsis for longer text on buttons

---

common/web/gesture-recognizer/src/engine/configuration/gestureRecognizerConfiguration.ts
common/web/gesture-recognizer/src/engine/gestureRecognizer.ts
common/web/gesture-recognizer/src/engine/headless/gesturePath.ts
common/web/gesture-recognizer/src/engine/headless/gestureSource.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/contactModel.ts
common/web/gesture-recognizer/src/engine/headless/inputEngineBase.ts
common/web/gesture-recognizer/src/engine/headless/inputSample.ts
common/web/gesture-recognizer/src/engine/headless/subsegmentation/pathSegmenter.ts
common/web/gesture-recognizer/src/engine/headless/touchpointCoordinator.ts
common/web/gesture-recognizer/src/engine/inputEventEngine.ts
common/web/gesture-recognizer/src/engine/mouseEventEngine.ts
common/web/gesture-recognizer/src/engine/touchEventEngine.ts

This PR aims to facilitate a resolution to #7173.  It is not a fix at this time, as integration with the OSK will be required for that.
The main addition here:  typing for a "state token", as well as a few related fields.  The idea:  the KMW OSK will be able to set the current "layer ID" as a "state token" on each gesture when the corresponding touchpoint first begins (and thus, the `GestureSource` is first instantiated.  Even if the layer changes before the gesture completes, that data will be accessible and can be used to look up the correct key from the gesture's original starting layer.
Note that this will be useful for more than just #7173 - it will also be useful for multitaps that include layer-switching keys.
In case a gesture's "active layer" ever _should_ be swapped after it …

feat(web): state token tracking, association with gestures 🐵

---

common/web/gesture-recognizer/src/engine/headless/gestureSource.ts
common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureSequence.ts
common/web/gesture-recognizer/src/engine/headless/gestures/matchers/matcherSelector.ts
common/web/gesture-recognizer/src/engine/headless/inputEngineBase.ts
common/web/gesture-recognizer/src/engine/headless/touchpointCoordinator.ts
common/web/gesture-recognizer/src/engine/index.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/gestureSequence.spec.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/matcherSelector.spec.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/touchpointCoordinator.spec.ts
common/web/gesture-recognizer/src/test/resources/simulateMultiSourceInput.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/headlessInputEngine.ts

Adds three new properties:
`TouchpointCoordinator.activeSources` - while `.activeGestures` already exists, reporting active gestures with at least one stage already... there was nothing for cases that do not yet have any stages / matches.  Essentially... `GestureSource`s here correspond well to "roaming touch" inputs, early key highlighting, and key previews - we have a pending input, but it hasn't actually triggered any state changes or key events.
`GestureSource.potentialModelMatchIds` - this allows inspecting the state of `GestureSource`s - like those available on the previous property - to determine what gesture models still have the potential to match for the current stage.  Reading that can be very useful for determining the best hint type for the OSK to display.
- if the key has …

feat(web): adds gesture-engine API properties for integration use 🐵

---

web/src/app/ui/kmwuitoolbar.ts

Fixes #9617.
This PR ensures upon selecting a keyboard, both of the following expectations are met:
- if a text area or input field was active immediately before interacting with the toolbar, it regains focus
- ... and the OSK is redisplayed if it was previously enabled.
It appears that some of the focus-rework that occurred during modularization may have caused a previously-noted concern in Toolbar code to be a little more merited than before.  Simply changing the timing of when the annotated function is called - to be firmly _after_ the keyboard-activation process has completed - appears to be enough to fix the issue.
TEST_REPRO:  Verify that the originally-reported repro no longer triggers the error.
- Using the "Desktop UI module testing" test page, select "Toolbar UI" for testing.
- …

fix(web): fixes toolbar refocus timing after a keyboard change

---

developer/src/kmc-package/test/fixtures/invalid/my_file.PDF
developer/src/kmc-package/test/test-messages.ts

chore(developer): add test for `checkFilenameConventions == false` or unset

---

developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/messages/infrastructureMessages.ts
developer/src/kmc/test/test-infrastructureMessages.ts

Fixes #9610.
If a build fails when "treat warnings as errors" is on, but there are only warnings and no error messages, it can be confusing for the developer. Adds the following `INFO_WarningsHaveFailedBuild` message:
`The build failed because option "treat warnings as errors" is enabled and there are one or more warnings.`
Unit test also added to verify behaviour.

feat(developer): show an INFO message when warnings have failed a build

---

developer/src/kmc-package/src/compiler/messages.ts
developer/src/kmc-package/src/compiler/package-validation.ts
developer/src/kmc-package/test/fixtures/invalid/error_package_must_contain_a_model_or_a_keyboard.kps
developer/src/kmc-package/test/fixtures/invalid/example.txt
developer/src/kmc-package/test/fixtures/invalid/hint_source_file_should_not_be_in_package.kps
developer/src/kmc-package/test/test-messages.ts

Fixes #9325.
Also tweaks unit test for error_package_must_contain_a_model_or_a_keyboard as the fixture had a .kmn, triggering the new hint, which was unhelpful in this case.

feat(developer): issue hint if package includes keyboard source files

---

developer/src/server/Makefile

Fixes broken developer (master).
Two conflicting merges meant that paths diverged:
* #9695 
* #9673
This fixes that.

chore(developer): fixup signcode paths for server

---

linux/keyman-config/km-config

Usually this is done automatically. However, if e.g. no `DISPLAY` variable is set it'll fail. When we explicitly initialize GTK it still fails, but shows a more helpful warning instead of throwing a runtime error.
Fixes #9705.
- The test should be run on any Linux platform with X11:
- Reboot
**TEST_WARNING**: if `DISPLAY` is not set we should get a warning instead of a runtime error
- in a terminal window, run `unset DISPLAY`
- in the same terminal, start Keyman Configuration by typing `km-config`
- Verify that instead of opening the Keyman Configuration window the terminal displays a warning similar to `Gtk-WARNING **: 16:51:19.867: cannot open …

fix(linux): Explicitly initialize GTK

---

linux/keyman-config/keyman_config/sentry_handling.py

- fix the calculation of the user hash so that the same user now always gets the same hash value. Previously we got a different value after restarting the app because the Python `hash` function calculates the hash based on the memory location.
- add additional details to Sentry events so that the "All Events" tab on keyman.sentry.io will show helpful values in the "device" and "os" columns instead of emptry strings.

chore(linux): Improve Sentry reports

---

common/schemas/kps/kps.xsd
common/web/types/src/package/kmp-json-file.ts
common/web/types/src/package/kps-file.ts
common/windows/delphi/packages/PackageInfo.pas
developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/test/fixtures/khmer_angkor/ref/kmp.json
developer/src/kmc-package/test/fixtures/khmer_angkor/source/khmer_angkor.kps
developer/src/tike/child/UfrmPackageEditor.dfm
developer/src/tike/child/UfrmPackageEditor.pas

Fixes #9478.
This adds a property WelcomeFile to .kps and kmp.json, which allows us to move away from the hardcoded welcome.htm filename in the future, and makes transform from Markdown (#9477) a simpler operation, and just generally starts the cleanup of the messiness of hard-coded filenames.
The package compiler will fallback to injecting welcome.htm into this property if (a) welcome.htm is present, and (b) the property does not already have a value. This doesn't buy us much because we still need to support welcome.htm for existing legacy packages, but does mean that our .kmp package metadata will be more consistent for packages compiled with 17.0+ compilers.
**Note:** Keyman itself on all platforms still only supports the welcome.htm filename at this time, so do not expect …

feat(developer): introduce WelcomeFile property to packages 🎺

---

developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/messages.ts
developer/src/kmc-package/src/compiler/package-validation.ts
developer/src/kmc-package/test/fixtures/invalid/hint_language_tag_is_not_minimal.kps
developer/src/kmc-package/test/fixtures/invalid/hint_package_should_not_repeat_languages.kps
developer/src/kmc-package/test/fixtures/invalid/keyman.en.hint_package_should_not_repeat_languages.model.kps
developer/src/kmc-package/test/test-messages.ts

Fixes #9266.
For historical reasons there are many non-minimal BCP 47 tags in package metadata in the repository (over 2500). Furthermore, earlier versions of kmcomp did not fail the build on package compilation warnings. This means it is better to reduce WARN_LanguageTagIsNotMinimal to HINT_LanguageTagIsNotMinimal, so that we can otherwise respect the 'treat warnings as errors' flag on the keyboard projects.
We may be able to upgrade this to a warning again one day in the future.
TODO:

fix(developer): non-minimal BCP 47 tags in kps should be a hint 🎺

---

common/web/types/src/package/kps-file.ts
developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/package-version-validator.ts
developer/src/kmc-package/src/compiler/windows-package-installer-compiler.ts

chore(common): stop using xml2js.processors.firstCharLowerCase 🎺

---

developer/src/kmc-keyboard-info/src/index.ts
developer/src/kmc-keyboard-info/test/test-keyboard-info-compiler.ts
developer/src/kmc-model-info/src/model-info-compiler.ts
developer/src/kmc-model-info/test/test-model-info-compiler.ts
developer/src/kmc-model-info/tsconfig.json
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/buildClasses/BuildKeyboardInfo.ts
developer/src/kmc/src/commands/buildClasses/BuildModelInfo.ts
developer/src/kmc/src/commands/buildClasses/BuildProject.ts
developer/src/kmc/src/util/extendedCompilerOptions.ts

The new `--for-publishing` flag allows us to enforce additional requirements for keyboards and lexical models that are to be published to the keymanapp repositories. This flag will always be switched on in the repository builds. This flag overrides the `skipMetadata` option which is a project-level option.
There is a bit of a delicate balance of requirements here:
1. We want to be able to automatically verify keyboards and package licenses if they are in the repository.
2. We do not want to force license checks on privately built keyboards and models.
3. We want to provide pathways for users to check locally before submitting to the repository.
4. If possible, we want to be able to build the .keyboard_info and .model_info files locally, but this should be up to the user for local builds. …

chore(developer): add --for-publishing to kmc 🎺

---

resources/build/build-utils.sh
resources/builder.inc.sh

- Some uses of `KEYMAN_ROOT` (not cross-repo compatible)
- `set -eu` and `SHLVL` now set there as well
Other Updates:
* https://github.com/keymanapp/shared-sites/pull/3
* https://github.com/keymanapp/keyboards/pull/2393 (https://github.com/keymanapp/keyboards/pull/2393/commits/3e1368dd649631ab1b4e91d5c41b286ef949e669)
* https://github.com/keymanapp/lexical-models/pull/226 (https://github.com/keymanapp/lexical-models/pull/226/commits/28c7506b83074d5b6ff287647265eba5b19d01b8)

chore: clean up a few minor discrepancies in builder.inc.sh

---

resources/build/increment-version.sh
resources/build/version/src/index.ts

* Fixes the path for the increment-version module
* Uses exit code 50 instead of 1 to indicate 'success, but no change', so that low-value error exit codes as used by node.js don't indavertently continue the build
Was causing the alpha build trigger to fail, e.g. https://build.palaso.org/buildConfiguration/Keyman_TriggerReleaseBuildsMaster/413596?buildTab=log&focusLine=259&logView=flowAware&linesState=217:
```log
09:13:28   increment-version.sh: running resources/build/version
09:13:28   /c/BuildAgent/work/99b311828f4ee7c/keyman /c/BuildAgent/work/99b311828f4ee7c/keyman /c/BuildAgent/work/99b311828f4ee7c/keyman
09:13:28   node:internal/modules/cjs/loader:1078
09:13:28     throw err;
09:13:28     ^
09:13:28   
09:13:28   Error: Cannot find module …
```

fix: path for ESM increment-version, and exit code

---

web/build.sh
web/src/tools/build.sh

Fixes #9670.  ~~Addresses #9670.  While it does fix~~ It fixes the _biggest_ concern from the issue, though there are a few other nits that this doesn't outright address.
(As per comments received on this PR, I've updated this to "fix" the issue.)
1. The `android-harness` build.sh is still called directly; it's not on a child-project path related to the build product that triggers it.  That said... it's only called one time.
2. The build scripts for the tools do still get called twice, although they at least don't "lose the environment" now.
```
[web/src/tools] child build, parameters: <build --builder-child --deps>
[web/src/tools/testing/bulk_rendering] child build, parameters: <build --builder-child --deps>
[web/src/tools/testing/bulk_rendering] ## build starting... …
```

chore(web): web build streamlining

---

docs/settings/linux/tasks.json
linux/build.sh
linux/keyman-config/build.sh
linux/keyman-config/run-tests.sh
linux/keyman-system-service/build.sh

This adds the options to create code coverage reports to `build.sh` for keyman-config and keyman-system-service.

chore(linux): Add code coverage reports for keyman-config and keyman-system-service

---

oem/firstvoices/ios/build.sh

Fixes #9764.
Fixes regression introduced in #9092 (b65a80f6f9d735b57015f9bc6e974ac57c25aaf4).

fix(ios): missing backslash in build script

---

linux/ibus-keyman/src/keymanutil.c
linux/ibus-keyman/src/keymanutil.h
linux/ibus-keyman/src/keymanutil_internal.h
linux/ibus-keyman/src/kmpdetails.c
linux/ibus-keyman/src/test/keymanutil_tests.c
linux/keyman-config/resources/com.keyman.gschema.xml

Part of #8598.
User tests will be part of the next PR that implements the necessary changes in keyman-config.

feat(linux): Allow loading of keyboards with arbitrary language 🏘️

---

developer/src/kmc/src/commands/analyze.ts

Fixes #9766.
The issue arose because commander passes different parameters to the callback depending on the spec of the command. Very fragile!

fix(developer): kmc crash on start

---

core/src/debuglog.cpp

- syslog() will automatically add newlines (per mac and linux manpages)
- there's no reason to add NL *AND* add std::endl
- this fix will cause syslog to have no newline going in, and print only one instead of two newlines on other platforms/environments
Just an annoyance now that I'm using DebugLog a lot.

fix(core): don't use double newlines in debuglog

---

docs/linux/README.md
linux/CodeCoverageReports.html
linux/README.md
linux/build.sh
linux/keyman-system-service/build.sh

This change adds an index page that can show the reports for the child projects.
Also fix a path problem in the `keyman-system-service/build.sh` script.

chore(linux): Add code coverage index page

---

linux/keyman-config/keyman_config/custom_keyboards.py
linux/keyman-config/keyman_config/gsettings.py
linux/keyman-config/keyman_config/install_kmp.py
linux/keyman-config/keyman_config/uninstall_kmp.py
linux/keyman-config/tests/test_custom_keyboards.py
linux/keyman-config/tests/test_install_kmp.py
linux/keyman-config/tests/test_uninstall_kmp.py

- during installation add to the list of custom keyboards if necessary
- during uninstallation remove from the list of custom keyboards
- if list of custom keyboards has invalid values, remove those before saving the list
Closes #8598.
- The tests should be run any these Linux platform
- Reboot
**TEST_CLI_INSTALL**: Installing a keyboard with an arbitrary language will add the keyboard to the keyboards drop down
- In a terminal window, run `km-package-install -p sil_euro_latin -l mul`
- Verify that the keyboard dropdown shows a keyboard similar to "Multiple languages (EuroLatin (SIL)) mul" (the exact wording depends on the Linux platform used for …

feat(linux): Allow installing keyboards with arbitrary language 🏘️

---

linux/keyman-config/keyman_config/sentry_handling.py

Ubuntu 20.04 comes with Python 3.8 which doesn't have `platform.freedesktop_os_release()`. This change catches the exception if this happens, as well as other exceptions we might get so that the initialization of Sentry will succeed.
Fixes #9773.
- The tests should be run on Wasta 20.04 or Ubuntu 20.04.
- Reboot
**TEST_CAN_START**: Open a terminal window and run `km-config`. Verify that Keyman Configuration starts.

fix(linux): Fix crash initializing Sentry with Python < 3.10

---

oem/firstvoices/ios/build.sh

Fixes the falling-over iOS build checks in this feature branch's PRs.
I could have done a full merge against master... but this was so narrow and specific that it was easy to extract, and it'll be much simpler and clearer to actually review as a result.  So yeah.

fix(ios): cherrypicks FV ios build script fix 🐵

---

.github/workflows/deb-packaging.yml
linux/scripts/launchpad.sh

Now that we have updated ibus packages in place we can re-enable building for Mantic.
Fixes #9520 and #9398.

chore(linux): Re-enable building for Ubuntu 23.10 Mantic

---

linux/ibus-keyman/src/test/keymanutil_tests.c

This adds (and fixes) two tests that were previously left out by accident.

chore(linux): Add missing tests

---

web/src/app/browser/src/keymanEngine.ts

Fixes https://github.com/keymanapp/keymanweb.com/issues/86.
Refer to #9304, which provides lots of very relevant context for the issue and the needed fix.
Unfortunately, the main way I know to test this fix... is to wait for the next alpha build and try then. 
It should be possible to build a test page with a similar rigging when time permits, come to think of it, but no such test page exists yet.

fix(web): fixes touch form-factor default kbd on cookieless keymanweb.com page load

---

common/web/types/src/main.ts
developer/src/common/web/utils/src/validate-mit-license.ts
developer/src/kmc-keyboard-info/src/index.ts
developer/src/kmc/src/commands/buildClasses/BuildKeyboardInfo.ts
developer/src/kmc/src/commands/buildClasses/BuildProject.ts

Three separate bugs (separate commits):
* handle fv_all keyboard project with no .kmn
* avoid adding null font data to keyboard_info
* ignore whitespace at end of LICENSE.md
Cleanup alongside keymanapp/keyboards#2404.

fix(developer): three kmc .keyboard_info generation bugs

---

docs/linux/README.md
linux/ibus-keyman/build.sh
linux/keyman-system-service/build.sh

Creating the coverage option to ninja previously didn't work reliably. This change re-orders the parameters passed to `meson setup` and seems to work better. Additionally this change refactors the scripts and makes use of `builder_run_action`.

chore(linux): Fix build scripts

---

docs/linux/README.md
linux/keyman-config/build.sh
linux/keyman-config/run-tests.sh

Another iteration trying to get TC create coverage reports.

chore(linux): Allow to collect coverage on TC

---

common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts
common/web/types/test/helpers/reader-callback-test.ts
developer/src/kmc-ldml/test/helpers/index.ts
developer/src/kmc/src/commands/buildClasses/BuildLdmlKeyboard.ts
developer/src/kmc/src/commands/buildTestData/index.ts

Fixes #9788.
@jahorton you should be able to cherry-pick this and then remove the following from ldml-keyboard-xml-reader.ts on #9664:
```
// Enables DOM types, but just for this one module.
///<reference lib="dom" />
```

fix(common): don't use URL in common/web/types

---

mac/Keyman4MacIM/Keyman4MacIM/Base.lproj/MainMenu.xib
mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputController.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.h
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
mac/Keyman4MacIM/Keyman4MacIM/en.lproj/Localizable.strings

Cherry-pick of #9777 to stable-16.0
Previously, Keyman for Mac supported switching of keyboards using a submenu from the Keyman section of the Input Menu:
This  change eliminates the submenu and lists the keyboards at the top of the Keyman section of the Input menu:
It is helpful to make this change now because the Keyboards submenu is not functioning properly with macOS Sonoma, 14.0 (see #9684).
Fixes #9684
- **TEST_KEYBOARD_SELECTION**:
Run Keyman for Mac and verify that a single keyboard is selected in the Keyman section of the Input Menu. Also, confirm that the selected keyboard is actually the one that is processing keystrokes when typing in a text document.
- **TEST_CHANGING_KEYBOARDS**:
Select a different keyboard from the list in the Keyman section of the Input Menu and verify …

fix(mac): move keyboard menu items to main Input Menu from submenu 🔥 🍒 🏠

---

.github/workflows/deb-packaging.yml
linux/scripts/deb-packaging.sh

This enhances the packaging GHA to be able to verify the renamed core library. Since the GHA packaging build always uses the action definition from `master` this change has to land before we can successfully build the PR that does the actual renaming of the core library and Debian package. Later we can remove the references to `libkmnkbp0-0` again.
Part of #9733.

chore(linux): Update packaging GHA 〽️

---

common/include/kmx_file.h
core/include/keyman/keyman_core_api_bits.h
core/meson.build
core/src/kmx/kmx_file_validator.hpp
core/src/kmx/kmx_processevent.h
core/src/meson.build
core/src/path.hpp
core/src/processor.hpp
core/src/version.rc
core/tests/unit/kmnkbd/meson.build
core/tests/unit/kmnkbd/test_kmx_xstring.cpp
core/tools/ldml-const-builder/build.sh
windows/src/engine/keyman32/keyboardoptions.cpp
windows/src/engine/keyman32/keymanengine.h

chore(linux): Rename KBP to CORE 〽️

---

android/KMAPro/kMAPro/build.gradle
android/KMEA/app/build.gradle
android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample2/app/build.gradle
android/Tests/KeyboardHarness/app/build.gradle
oem/firstvoices/android/app/build.gradle

Relates to #7897 for stable-16.0. Just updating targetSdkVersion and none of the dependencies here.
The latest Keyman for Android 16.0 builds fail to publish because the Play Store is requiring a newer target SDK Version.

chore(android): Update targetSdkVersion from 31 to 33 🏠

---

linux/scripts/dist.sh
resources/build/build-utils.sh

`environment.sh` is used only on Mac. This change modifies `build.sh` to generate this file only when building on Mac. It also excludes `environment.sh` from the Linux source tarball.
(cherry picked from #9553)

chore(linux): Exclude environment.sh from build 🍒 🏠

---

developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/messages.ts
developer/src/kmc-package/src/compiler/windows-package-installer-compiler.ts
developer/src/kmc-package/test/fixtures/invalid/error_invalid_package_file.kps
developer/src/kmc-package/test/test-messages.ts

fix(developer): handle xml errors in package compiler

---

developer/src/server/src/site/packages.js
developer/src/server/src/site/test.js

Fixes #9702.
Setup: you will need to have Keyman Developer Server running on your Windows computer for all these tests, in the same way as described in #9702. Then, you will need to locate the appropriate IP address on your local network for your computer, and ensure that the test devices are on the same local network. For example, on my machine, the address I use is http://192.168.129.109:8008:
Then, open that page on the target device and test the Download Keyman link there.
GROUP_WINDOWS: Test on Windows
GROUP_MAC: Test on MacOS
GROUP_ANDROID: Test on MacOS
GROUP_IOS: Test on iOS
GROUP_LINUX: Test on Linux
TEST_LINK: Test ths the Download Keyman link starts a download for Keyman or loads a page appropriate for the device

fix(developer): server download Keyman link

---

developer/src/tike/xml/layoutbuilder/builder.xsl

fix(developer): reduce confusion in Unicode fields in touch layout editor

---

core/build.sh
core/commands.inc.sh

Fixes #9816.
Now allows any of the following. Quote marks are significant for multiple tests with `-t`:
```bash
core/build.sh test:wasm --no-deps -- state-api debug-api
core/build.sh test:wasm --no-deps -- "state-api debug-api"
core/build.sh test:wasm --no-deps -t "state-api debug-api"
core/build.sh test:wasm --no-deps --test "state-api debug-api"
```
The `-t` / `--test` option takes a single string parameter which is passed on to `meson test`, whereas the `--` "end of parameters" marker allows arbitrary remaining parameters to be passed on to `meson test`.

fix(core): build: support -t parameter correctly

---

developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-kmn/src/compiler/messages.ts
developer/src/tike/child/UfrmKeymanWizard.pas

Fixes #9851.
Two fixes:
* errors from loading the displayMap from disk should be handled before passing result to next function
* temp compile of the .kmn for the 'fill from layout' function should be in the same path as the original .kmn, so that referenced files can be located
(User test involves setting up a `&displayMap` which is a bit too involved to be feasible right now...  I have tested locally.)

fix(developer): handle displayMap correctly with 'fill from layout'

---

mac/build.sh
mac/mac-utils.inc.sh
mac/setup/build.sh

Fixes #6881.
Cherry-pick of #9010. Fixed up 17.0-isms in scripts.
Change has been applied to stable-16.0 in order to meet Apple deadline of 1 Nov for shutdown of altool.
References for the transition to notarytool:
https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool?changes=_3_3
https://keith.github.io/xcode-man-pages/notarytool.1.html

chore(mac): move from altool to notarytool 🍒 🏠

---

web/src/engine/osk/src/keyboard-layout/oskLayerGroup.ts
web/src/engine/osk/src/visualKeyboard.ts

fix(web): fixes doc-kbd display of default layer when it's not defined first

---

developer/src/tike/main/UfrmMain.pas
developer/src/tike/main/mrulist.pas

Fixes #9899.
Several problems resolved here:
* project mru did not refresh the welcome screen on first load, so the welcome screen was often showing projects that were no longer relevant
* content saved to registry did not match expectations on load, so mru never worked between sessions (always flushed on reload)
* synchronization between simultaneous sessions of TIKE did not work, because the list was only saved when Keyman Developer exited -- meaning the last exited instance of TIKE would overwrite the MRU from earlier sessions, losing the projects opened in those sessions.
Minor tidyup:
* WideString -> string -- legacy cleanup from when Delphi was non-Unicode.
* Reordered functions to group more clearly.
Note: the issue was not that there was both registry and xml content; the source …

fix(developer): Project MRU now saves correctly

---

developer/src/tike/xml/layoutbuilder/builder.js
developer/src/tike/xml/layoutbuilder/undo.js

Fixes #7852.
When undo is run in the layout builder, it is better to keep the user's selected presentation if possible. (The selected presentation is not stored in the undo stack, but is a view property affected by the currently selected platform.)
* **TEST_UNDO:** In the Touch Layout tab of the keyboard editor, in View Controls, select 'iPad (Portait)' or 'iPhone (Portait)'. Make a change to the layout, and then press Ctrl+Z to undo (or use the Undo toolbar button). The view should remain as a portait view, and not switch back to landscape.

fix(developer): layout builder - maintain presentation during undo

---

developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts
developer/src/kmc-kmn/test/fixtures/invalid-keyboards/warn_touch_layout_unidentified_key.keyman-touch-layout
developer/src/kmc-kmn/test/fixtures/invalid-keyboards/warn_touch_layout_unidentified_key.kmn
developer/src/kmc-kmn/test/test-messages.ts

Fixes #8000.
In earlier versions of KeymanWeb, it was assumed that layer switch keys would not necessarily need an identifier, as they would not be generating a standard KeymanWeb key event. However, this assumption does not really hold, so we should be warning on missing identifiers for layer switch keys.

fix(developer): warn if layer switch key is missing ID

---

developer/src/tike/xml/layoutbuilder/builder.js

Fixes #7851.
Note that this fixes the selection pop issue with duplicate ids in some scenarios but not all. For example, the undo stack doesn't have enough detail at this point to be able to track this. This fix addresses the most egregious issue relating to key size adjustment and similar.
* **TEST_KEY_RESIZE:** Open a touch layout, and give two keys on the same layer the same ID (e.g. `K_Q`). Select each key in turn and resize it by dragging on the right hand border. When you resize, the selected key should remain the same -- previously the selection would jump to the first key with the same ID.

fix(developer): restore selection in layout builder even with duplicate ids

---

developer/src/tike/child/UfrmDebug.pas

Fixes #9444.
* **TEST_DEBUGGER_ENTER_KEY:** In the Keyman Developer keyboard debugger, type text, then press Enter. Verify that a new line is inserted, and that the debugger character grid shows `000D` and `000A` values.
* **TEST_DEBUGGER_BKSP_KEY:** In the Keyman Developer keyboard debugger, type text, then press Enter. Press Bksp to delete the new line. Verify that both `000D` and `000A` values are deleted with a single press of Bksp.

fix(developer): enable line breaks in debugger

---

developer/src/kmc-kmn/src/kmw-compiler/compiler-globals.ts
developer/src/kmc-kmn/src/kmw-compiler/kmw-compiler.ts

Fixes #8147.
Keyboards debug-compiled for web 17.0+ will use `KeymanWeb.Codes.` instead of `keyman.osk.`.
* **TEST_DEBUGGER:** Create a new keyboard in Developer, and set its `store(&VERSION)` line to '17.0'. Compile the keyboard, and test it in the web debugger. Verify that the keyboard loads in Keyman Developer Server in the browser and that there are no Javascript errors (you will need to look at the Javascript console to be certain)

fix(developer): use KeymanWeb.Codes for 17.0+

---

developer/src/server/src/site/index.html
developer/src/server/src/site/test.js

Fixes #9845.
It seems that the logic for `osk-always-visible` is not quite right on touch devices -- the OSK disappears on blur but remains touchable -- so presses in the OSK region emit key events. For Keyman Developer Server, the simple workaround is to only use `<body class="osk-always-visible">` when on desktop devices.
We should review the logic for `osk-always-visible` in KeymanWeb, so that this issue does not arise on touch devices. This patch addresses the issue in Keyman Developer Server, and matches the behaviour we want on touch devices in any case, as we don't really want the OSK visible when blurred, unlike on desktop.
* **TEST_INVISIBLE_OSK_ON_TOUCH_DEVICE:** Open Keyman Developer Server on a touch device (or in touch device emulation in Chrome); ensure there is a Keyman …

fix(developer): don't use osk-always-visible on touch devices

---

linux/scripts/deb-packaging.sh

Make use of builder_run_action.

chore(linux): Refactor deb-packaging.sh script 🎬

---

common/windows/delphi/general/RegistryKeys.pas
common/windows/delphi/general/UserMessages.pas
developer/src/tike/dialogs/UfrmOptions.dfm
developer/src/tike/dialogs/UfrmOptions.pas
developer/src/tike/main/KeymanDeveloperOptions.pas
developer/src/tike/main/KeymanDeveloperUtils.pas
developer/src/tike/main/UfrmMain.pas
developer/src/tike/tike.dpr

Fixes #9925.
Allow Multiple Instances is now always true.
Use Legacy Compiler did nothing (there is no legacy compiler!).

chore(developer): remove obsolete 'Allow Multiple Instances' and 'Use Legacy Compiler' options

---

.github/workflows/deb-packaging.yml
linux/.gitignore
linux/debian/control
linux/scripts/reconf.sh

When didn't set the correct environment when building Debian packages with GitHub actions. The version information wasn't included in the source file but instead was generated at binary package build time, at which time not all necessary environment variables were available. This change will create a patch file on-the-fly which gets included in the source package that contains the correct information.
Fixes #9878.

fix(linux): Fix environment for Debian packages

---

common/web/types/package.json
developer/src/kmc-keyboard-info/package.json
developer/src/kmc-kmn/package.json
developer/src/kmc-ldml/package.json
developer/src/kmc-model-info/package.json
developer/src/kmc-model/package.json
developer/src/kmc-package/package.json
developer/src/kmc/package.json

Given we've just run a build, this (a) seems unnecessary, and (b) seems to go wrong in some circumstances anyway, e.g. https://build.palaso.org/buildConfiguration/Keyman_Developer_Release/421326?buildTab=log&focusLine=19936&linesState=18839&logView=flowAware:
```
07:01:29   > @keymanapp/kmc@17.0.205-alpha prepublishOnly
07:01:29   > npm run build
07:01:29
07:01:31
07:01:31   > @keymanapp/kmc@17.0.205-alpha build
07:01:31   > tsc -b
07:01:31
07:01:35   ../../../common/web/types/build/src/kmx/kmx.d.ts(1,1): error TS1036: Statements are not allowed in ambient contexts.
07:01:35   ../../../common/web/types/build/src/kmx/kmx.d.ts(1,2): error TS1345: An expression of type 'void' cannot be tested for truthiness.
...
```

chore(common): remove prepublish step from package.json

---

developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-kmn/src/kmw-compiler/javascript-strings.ts
developer/src/kmc-kmn/src/kmw-compiler/kmw-compiler-messages.ts
developer/src/kmc-kmn/src/kmw-compiler/kmw-compiler.ts
developer/src/kmc-kmn/test/fixtures/invalid-keyboards/error_not_supported_in_keyman_web_output.kmn
developer/src/kmc-kmn/test/test-messages.ts

Fixes #9931.
Provide additional line and file context for some KeymanWeb compiler messages. This change requires debug data in the intermediate kmx data provided to the kmw compiler, which should have no impact on the final .js if `options.debug==false`.
The following messages have had line number context added:
* `Error_NotSupportedInKeymanWebContext`
* `Error_NotSupportedInKeymanWebOutput`
* `Error_VirtualCharacterKeysNotSupportedInKeymanWeb`
* `Error_VirtualKeysNotValidForMnemonicLayouts`
* `Warn_ExtendedShiftFlagsNotSupportedInKeymanWeb`
* `Hint_UnreachableKeyCode`
* `Warn_HelpFileMissing`
* `Warn_EmbedJsFileMissing`
* `Error_NotAnyRequiresVersion14`
Line number metadata is not easily accessible where the following messages are generated, so these are a potential future improvement:
* …

feat(developer): provide line number for some kmw compiler messages

---

developer/src/server/src/config.ts
developer/src/server/src/data.ts
developer/src/server/src/load-json-file.ts

Fixes #9848.
Root cause of #9848 is unknown, because the cache state file was filled with nul bytes. It is unclear how that could have happened, but seems likely to be external interference.
The cascade was that Server failed to start because it would crash when attempting to load the cache state file. So this fix resolves that by handling invalid file exceptions.

fix(developer): resilience in loading Server config and cache files

---

web/index.html
web/src/samples/index.html
web/src/test/manual/embed/index.html
web/src/test/manual/web/index.html
web/src/tools/testing/index.html

This change adds `index.html` to all links that point to test index pages. This will show the index page instead of the directory listing when opening locally, identical to the behavior on TC.

refactor(web): Link to `index.html` in test pages

---

web/src/engine/osk/src/views/oskView.ts

See also #9917 for the Keyman Developer part.
Fixes #9918.
* **TEST_WEB:** Open Keyman Web on a touch device (or in touch device emulation in Chrome); ensure there is a Keyman keyboard active for testing. Touch on the touch OSK to input some text into the test box. Then touch outside the text box to hide the OSK. Then, touch where the OSK _was_ visible. This should _no longer_ cause text to be inserted into the test box.

fix(web): Ignore `osk-always-visible` on non-desktop devices

---

common/test/keyboards/baseline/k_020___deadkeys_and_backspace.kmn

Change the test to use characters in the context that don't appear in the keyboard.
This fixes builds on `master`.

fix(linux): Fix baseline tests

---

resources/build/trigger-builds.inc.sh

When we build a PR on TC we use `pull/ID/head` for the build, not `pull/ID/merge`, i.e. the tip of the feature branch and not a merge with the base branch. This means that during the build `pull/ID/merge` is unknown. This change modifies the trigger to use `pull/ID/head` for GHA builds as well.
It's still a mystery why `pull/ID/merge` was known to builds in most cases but failed for some PRs.

chore(linux): Fix GHA triggering

---

docs/build/windows.md

* meson 1.2.3 is now available on choco
* emscripten 3.1.40 is currently latest available choco version

docs(windows): update meson and emscripten details

---

web/src/engine/osk/src/keyboard-layout/oskKey.ts
web/src/resources/osk/kmwosk.css

Fixes #7940.
The caption on the spacebar used to be 60% (0.6em). This change increases it to 100%.
One reason for the sometimes small text on the spacebar described in #7940 besides the too small font size on `kmw-spacebar-caption` was that the calculation of the ideal font size added double padding: it added two pixels of
padding to the height, but also multiplied the height value by 0.9 which effectively added more padding. This change removes the 2 pixel padding from the calculation.
Note that it is still possible for the text on the spacebar to become unreasonably small if the keyboard/language name is too long. However, that is outside of the scope of this PR.
**TEST_EMULATOR**: 
- Go to the "Prediction - robust testing" test page in Chrome.
- Launch developer mode and set it to …

fix(web): Increase size of spacebar text

---

android/KMEA/app/src/main/assets/keyboard.html
android/KMEA/app/src/main/assets/other-polyfills.js
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
common/web/gesture-recognizer/src/engine/configuration/paddedZoneSource.ts
common/web/gesture-recognizer/src/engine/configuration/viewportZoneSource.ts
common/web/lm-worker/build-bundler.js
common/web/lm-worker/build-wrap-and-minify.js

Fixes #9443.
Turns out that the `es6-shim` polyfill doesn't actually polyfill quite _everything_ we want:
- `Object.values`, `Object.entries` - requires Chrome 54.  Fortunately, it's also very easy to workaround with minimal code restructuring.
- `Array.includes`:  Chrome 47.
- `DOMRect` with constructor:  [Chrome 61](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect#browser_compatibility).
- This one in particular surprised me, given `getBoundingClientRect` goes as far back as Chrome 18; the gesture engine has components built on this method in particular.
Also disables `keepNames` in the lm-worker's es-build config, as noted here: https://github.com/keymanapp/keyman/pull/9943#discussion_r1384247462

fix(web): restores compat with older Android devices 🐵

---

web/src/engine/osk/src/input/gestures/browser/subkeyPopup.ts
web/src/engine/osk/src/visualKeyboard.ts

I'd forgotten that default subkey selection logic is not available on the gesture-engine level, so KMW longpress handling has to override the gesture's selected-key output when a default subkey should be selected. 
Technically, we _could_ make it override only when the "select default" mode is on; that wouldn't actually be that difficult.  But... it's not really necessary to toggle the `directlyEmitsKey` property, and not doing so results in somewhat simpler code.
TEST_SPECIAL_DEFAULT:  if a subkey exists with an explicitly-marked 'default' subkey, it should be auto-selected when the subkey menu is first displayed.
1. On a mobile device (or when emulating one in a desktop browser), visit the testing page marked "Tests handling of new default-subkey feature (#9430)."
2. Longpress the `d` …

fix(web): default subkey forwarding 🐵

---

windows/src/desktop/inst/download.in
windows/src/desktop/setup/Keyman.Setup.System.InstallInfo.pas

Fixes #10001.
This is a regression coming out of #9616. The new setup.inf generation process is done in a Makefile and inadvertently added significant whitespace, which was not being trimmed by setup.

fix(windows): setup.inf generation had whitespace

---

developer/src/kmconvert/Keyman.Developer.System.ImportWindowsKeyboard.pas
developer/src/kmconvert/Keyman.Developer.System.KMConvertParameters.pas
developer/src/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas
developer/src/kmconvert/Keyman.Developer.System.KeymanConvertMain.pas
developer/src/kmconvert/Keyman.Developer.System.ModelProjectTemplate.pas
developer/src/kmconvert/Keyman.Developer.System.ProjectTemplate.pas
developer/src/kmconvert/data/basic-keyboard/README.md
developer/src/kmconvert/data/basic-keyboard/source/readme.htm
developer/src/kmconvert/data/basic-keyboard/source/welcome.htm
developer/src/kmconvert/data/wordlist-lexical-model/README.md
developer/src/kmconvert/data/wordlist-lexical-model/model.model_info
developer/src/kmconvert/data/wordlist-lexical-model/source/model.ts
developer/src/kmconvert/data/wordlist-lexical-model/source/readme.htm
developer/src/kmconvert/data/wordlist-lexical-model/source/welcome.htm
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewModelProjectParameters.dfm
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewModelProjectParameters.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.dfm
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas

Fixes #9869.
Adds a 'Description' field, tweaks Copyright strings, and tweaks default content for documentation to the New Project wizards and kmconvert.
**TEST_NEW_KEYBOARD_PROJECT:** Create a new keyboard project, and verify that the Description field is visible in the resulting README.md, readme.htm, welcome.htm, and in the Description field of the package. Check also that the Copyright string starts with the word 'Copyright'.
**TEST_NEW_MODEL_PROJECT:** Create a new lexical model project, and verify that the Description field is visible in the resulting README.md, readme.htm, welcome.htm, and in the Description field of the package. Check also that the Copyright string starts with the word 'Copyright'.

feat(developer): New Project - Description field and tweaks 🦕

---

developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProject.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UpgradeProject.pas
developer/src/tike/xml/project/distribution.xsl
developer/src/tike/xml/project/keyboards.xsl
developer/src/tike/xml/project/models.xsl
developer/src/tike/xml/project/packages.xsl

chore(developer): hide 'Remove From Project' for v2.0 projects 🦕

---

developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
developer/src/tike/project/Keyman.Developer.System.Project.xmlLdmlProjectFile.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProject.pas
developer/src/tike/xml/project/distribution.xsl
developer/src/tike/xml/project/keyboards.xsl
developer/src/tike/xml/project/packages.xsl
developer/src/tike/xml/project/welcome.xsl

Identifies .xml keyboards when building file list, then shows those appropriately in the keyboard list. Also enables grouped actions such as keyboard_compileall for those keyboards.
XML keyboards listed in the Keyboards tab:
Note how the empty.xml is correctly identified as _not_ a XML LDML keyboard file:

feat(developer): show .xml LDML keyboards in project 🦕

---

developer/src/kmc/src/commands/buildClasses/BuildLdmlKeyboard.ts

fix(developer): kmc build ldml keyboard should create output folder 🦕

---

developer/src/tike/main/UfrmMessages.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UpgradeProject.pas

Having the project upgrade messages in the Messages panel means that users can refer to them as they clean up their projects to bring them into the v17 format.
https://github.com/keymanapp/keyman/assets/4498365/2ad0f39f-00c3-4eba-bb61-67a3bb5dfc02
(Note near the end of the video: the lingering messages in the messages window are now cleared.)
**TEST_UPGRADE:** Try to upgrade a project to v17 format -- choose a project that has files from various locations, and observe the messages presented during upgrade. Remove the files that are not in the right folder, and then run the upgrade again. The upgrade should succeed and the Upgrade warning message should disappear.

fix(developer): Project upgrade messages now show in Messages panel 🦕

---

developer/src/tike/actions/dmActionsMain.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProjectSettings20.dfm
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProjectSettings20.pas
developer/src/tike/tike.dpr
developer/src/tike/tike.dproj

* **TEST_SETTINGS_FORM:** Upgrade an existing project to the new Keyman Developer 17.0 project format. Open the Project Settings dialog, and go through and change each setting, then check that each setting is saved when you click OK and then re-open the dialog.

feat(developer): Project Settings Form for 17.0+ projects 🦕

---

developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProject.pas

For batch builds (e.g. project/compile all) of v2.0 projects, we only want to build files that are listed in the project's $SOURCEPATH, so that the project can contain extra folders with source file types that won't break a project-level build.
Any source file types in extra folders can still be built one-by-one, which is helpful for investigation and test for keyboard authors, but will not be built if project build is selected.
This commit also formalizes the source/ SourcePath for upgraded projects which contain a source/ folder. If the project to be upgraded does not contain the source/ folder, then no SourcePath is assigned, and any source file in any folder will be built.

chore(developer): only build source files 🦕

---

developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
developer/src/tike/project/Keyman.Developer.System.Project.xmlLdmlProjectFile.pas
developer/src/tike/project/Keyman.Developer.UI.Project.xmlLdmlProjectFileUI.pas

When upgrading a project to v2.0, it is important that all source files are in the same folder. This change makes the upgrade process verify that this is the case and blocks the upgrade if there are source files in multiple folders.
Source files are .kmn, .xml (ldml keyboard), .kps, and .model.ts.
Note: cleanups in other units are removing unused code.

chore(developer): manage SourcePath in project upgrade 🦕

---

developer/src/tike/actions/dmActionsMain.pas
developer/src/tike/main/UfrmMain.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectLoader.pas

Prevents loading of projects other than v1.0, v2.0, and also handles error cases when attempting to load projects.

feat(developer): handle errors loading projects 🦕

---

developer/src/tike/project/Keyman.Developer.System.Project.ProjectSaver.pas
developer/src/tike/xml/project/distribution.xsl
developer/src/tike/xml/project/elements.xsl
developer/src/tike/xml/project/keyboards.xsl
developer/src/tike/xml/project/models.xsl
developer/src/tike/xml/project/packages.xsl

For v2.0 projects, only show .kmn, .kps, .model.ts, .tsv, and .xml files if they are source files within Options.SourcePath.

chore(developer): show only source path files in project views 🦕

---

resources/build/trigger-builds.inc.sh

We now pass the SHA for the base ref. Hopefully this will fix the failures with API verification.

fix(linux): Improve triggering of packaging GHA

---

ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js
web/src/engine/main/src/keymanEngine.ts
web/src/engine/osk/src/banner/banner.ts
web/src/engine/osk/src/banner/bannerController.ts
web/src/engine/osk/src/banner/bannerView.ts
web/src/engine/osk/src/banner/htmlBanner.ts
web/src/engine/osk/src/banner/imageBanner.ts
web/src/engine/osk/src/banner/suggestionBanner.ts

Accomplishes two goals:
1. Adds support for a new `HTMLBanner` type, which allows specifying banner contents to be injected via `innerHTML` property.  For devices that support it, this will take place within an attached "shadow" for the banner in order to facilitate styling isolation.
2. Given the new banner type, I dropped the old 'select type of banner' approach in favor of 'set a Banner for use when inactive' approach.
- This allows direct calls to banner constructors, and thus to use of constructor parameters instead of messy, semi-dissociated "banner options".  Thus, it becomes clear that only data for the requested 'inactive banner' type needs to be specified.
To set the new banner type in motion...
Once KeymanWeb has initialized, make a call like this:
```javascript …
```

refactor(web): inactive banner management 🎏

---

ios/Cartfile
ios/Cartfile.resolved
ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
ios/engine/KMEI/KeymanEngineTests/KeymanPackageTests.swift
ios/engine/KMEI/KeymanEngineTests/ResourceUpdateTests.swift
ios/engine/KMEI/KeymanEngineTests/TestUtils/EngineStateBundler.swift
ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
ios/keymanios.xcworkspace/xcshareddata/xcschemes/Keyman.xcscheme
ios/samples/KMSample1/KMSample1.xcodeproj/project.pbxproj
ios/samples/KMSample2/KMSample2.xcodeproj/project.pbxproj
oem/firstvoices/ios/Cartfile
oem/firstvoices/ios/Cartfile.resolved
oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj

Replacing marmelroy/Zip framework with weichsel/ZIPFoundation due to problems with using the [Zip framework and Carthage](https://github.com/marmelroy/Zip/issues/70). Attempts to use Zip framework were unsuccessful in #9942 
Fixes #8861
(#9819 is specific to Stable 16.0, so that is directly fixed by #9958)
🍒 from #9958

fix(ios): fv: replace Zip framework to prevent crash on startup 🍒 

---

common/web/gesture-recognizer/src/engine/headless/gestures/specs/contactModel.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/gestureModel.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/gestureModelDefs.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/index.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/modelDefValidator.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/pathModel.ts
common/web/gesture-recognizer/src/engine/index.ts
web/src/engine/osk/build.sh
web/src/engine/osk/src/index.ts
web/src/engine/osk/src/input/gestures/specsForLayout.ts
web/src/engine/osk/src/visualKeyboard.ts
web/src/engine/osk/validate-gesture-specs.js

To help prevent accidental breakage during future maintenance of the new gesture engine, I decided to write up a small validator for the gesture-definition ids.  There were a couple of times during development where I messed up the IDs and had to discover that; fortunately, a simple targeted tool is well-able to help prevent future recurrences of such an issue.
This PR also updates some of the lower-level gesture-engine documentation within its first commit.
The validation function will tree-shake out during builds of the main artifacts, so it won't affect Web's file-size.
In the case of a validation issue, here's how it looks during a build of the OSK...
```
[web/src/engine/events] dependency build, started by web/src/engine/osk
[web/src/engine/events] build.sh parameters: <configure …
```

feat(web): basic gesture model validation 🐵

---

ios/Cartfile
ios/Cartfile.resolved
ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj
ios/engine/KMEI/KeymanEngine/Classes/KeymanPackage.swift
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/ResourceFileManager.swift
ios/engine/KMEI/KeymanEngineTests/KeymanPackageTests.swift
ios/engine/KMEI/KeymanEngineTests/ResourceUpdateTests.swift
ios/engine/KMEI/KeymanEngineTests/TestUtils/EngineStateBundler.swift
ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
ios/keymanios.xcworkspace/xcshareddata/xcschemes/Keyman.xcscheme
ios/samples/KMSample1/KMSample1.xcodeproj/project.pbxproj
ios/samples/KMSample2/KMSample2.xcodeproj/project.pbxproj
oem/firstvoices/ios/Cartfile
oem/firstvoices/ios/Cartfile.resolved
oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj

Replacing marmelroy/Zip framework with weichsel/ZIPFoundation due to problems with using the [Zip framework and Carthage](https://github.com/marmelroy/Zip/issues/70). Attempts to use Zip framework were unsuccessful in #9942 
Fixes #9819  

fix(ios): fv: replace Zip framework to prevent crash on startup 🏠

---

windows/src/engine/keyman32/appint/aiTIP.cpp
windows/src/engine/keyman32/appint/aiTIP.h
windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/k32_globals.cpp
windows/src/engine/keyman32/kmhook_getmessage.cpp
windows/src/engine/keyman32/kmprocess.cpp

Fixes #10050.
Removes the following unused identifiers:
* `::wm_kmdebug`
* `::wm_keymandebug`
* `AppInt::DebugControlled()`
* `AITIP::WM_KEYMANDEBUG_CANDEBUG`
* `AITIP::WM_KEYMANDEBUG_GETUNICODESTATUS`
* `AITIP::WM_KEYMANDEBUG_GETCONTEXT`
* `AITIP::WM_KEYMANDEBUG_ACTION`
* `AITIP::WM_KEYMANDEBUG_RULEMATCH`
* `AITIP::DebugControlled()`
* `AITIP::IsDebugControlWindow()`
* `AITIP::GetDebugControlWindow()`
* `AITIP::Debug_FillContextBuffer()`
* `AIDEBUGINFO struct`
* `::FillStoreOffsets()`
* `AIDEBUGKEYINFO struct`
Removes overloads which are now no-ops:
* `AITIP::HandleWindow()`
* `AITIP::IsWindowHandled()`
* `AITIP::QueueAction()`

chore(windows): remove `wm_keymandebug` messages and functions

---

windows/src/engine/keyman32/globals.h
windows/src/engine/keyman32/k32_globals.cpp
windows/src/engine/keyman32/keyman32.cpp
windows/src/engine/keyman32/keymanengine.h

Fixes #10056.
Removes:
* `Globals::miniContext`
* `Globals::miniContextIfLen`
* `Globals::indexStack`
* `Globals::msgbuf`
* `GLOBAL_ContextStackSize`
* `GLOBAL_MsgStackSize`
* `GLOBAL_MaxKeyboards`
* `INI` struct (and commented-out usage of this)

chore(windows): remove unused globals relating to old keyboard debugging

---

core/src/kmx/kmx_actions.cpp
core/src/kmx/kmx_actions.h
core/src/kmx/kmx_processevent.cpp
core/src/kmx/kmx_processor.cpp

Fixes #10049.
vkey output was never supported by Core, so this code effectively was a no-op.

chore(core): remove vkey output from kmx processor

---

common/web/keyboard-processor/src/text/keyboardProcessor.ts
web/src/engine/main/src/keymanEngine.ts

Discovered during user-test development for #9973:  our mobile app context-reset commands were not erasing deadkeys from the context.  This likely was a missed "loose thread" that arose from ES-modularization work.
User test TEST_APP_10_KEY_DIACRITICS  from #9973 covers this sufficiently; this change has been 🍒-picked for `master` from that `feature-gestures` PR.

fix(web): app/webview did not clear deadkeys on context-reset

---

developer/src/common/include/kmn_compiler_errors.h
developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
developer/src/kmc-kmn/test/fixtures/invalid-keyboards/warn_virtual_key_in_output.kmn
developer/src/kmc-kmn/test/test-messages.ts
developer/src/kmcmplib/src/CompMsg.cpp
developer/src/kmcmplib/src/Compiler.cpp

Fixes #10059.
Use of the unsupported and undocumented virtual key output, that doesn't work in recent Keyman versions, at all, now results in a build warning.
Only a warning, because it did kinda work in old versions of Keyman.
Sample output:
```
$ ./build.sh --compiler /c/Projects/keyman/app/developer/src/kmc/build/src/kmc.js build -k release/g/gandhari/
...
gandhari.kmn:118 - warn KM020AF: Virtual keys are not supported in output
...
```

feat(developer): warn on usage of virtual keys in rule output

---

core/src/action.cpp
core/src/option.cpp
core/src/option.hpp
core/tests/unit/kmnkbd/action_api.cpp

Fixes #10067.
Management of memory for persisted options was wrong in the action struct, as the members key and value would be freed immediately after being added to the temporary vector (because the vector was of the struct rather than of the class).
Given the struct is a C struct, we need the memory management to be explicit, so we now release() each option into the vector as we create it, which means that its member values will not be freed when the option is then immediately deleted. (This allows us to use the initial copy of the members of option that option() constructor does.)
Added the release() function as that was a relatively clear way of indicating that the contents of the structure are now owned by the caller, following the pattern from std::unique_ptr.
Finally, the unit test …

fix(core): memory management of options in action struct

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/res/menu-land/main.xml
android/KMAPro/kMAPro/src/main/res/menu-sw600dp/main.xml
android/KMAPro/kMAPro/src/main/res/menu/main.xml
android/help/about/whatsnew.md

@ermshiperete noticed 16.0 updates on the Play Store haven't happened since Jan 2023.
Re-implements #8428 to disable access to the the in-app browser (Keeps the Keyman app account agnostic)
At the time, we  held off on merging #8428 into 16.0 (it's merged in 17.0)
**Setup** 
Install the PR build of Keyman for Android 
* **TEST_BROWSER_DISABLED** - Verifies Keyman browser can't be accessed
1. Launch Keyman for Android in portrait orientation
2. Observe the menu icons and verify the browser icon is not visible
3. Rotate the device to landscape orientation
4. Observe the menu icons and verify the browser icon is not visible

fix(android/app) Disable in-app Browser 🏠

---

common/windows/delphi/general/utildir.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectLoader.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProjectSettings20.pas
developer/src/tike/xml/project/distribution.xsl
developer/src/tike/xml/project/elements.xsl

Restricts enumeration of files for the project to the project folder and the SourcePath folder. This prevents problems where a project may be in a folder with many subfolders which would take a long time to enumerate, and avoids confusion where there are source-type files in other folders.
At the same time, sorts out forward slash vs backslash in paths. While forward slash works in many scenarios, there are several filename manipulation functions, such as ExpandFileName, which would build valid but non-optimal paths when forward slashes were encountered, which cascaded into files appearing to be different and presentation issues.
For the Project view, the Distribution tab now shows file relative paths, which helps with organization. Have opted _not_ to show the relative …

fix(developer): projects 2.0 internal path enumeration 🦕

---

web/src/test/manual/web/attachment-api/utilities.js

This PR fixes an error thrown on the test page because it can't find `kmw`.

fix(web): Fix attachment-api tests

---

common/web/keyboard-processor/build-bundler.js

Previously we renamed `dom-keyboard-loader.mjs` but forgot to move the source map along.

fix(web): Also move source map

---

core/src/km_core_state_api.cpp
core/tests/unit/kmnkbd/action_api.cpp

In the case where the cached context had been cleared the km_core_state_context_set_if_needed call would just compare the null terminations of both strings and not set the cached context to the application context.
I first thought I could just change the decrement of the pointers to occur before the iteration not after e.g.
``` 
for(; context_p > context && cached_context_p > cached_context; --context_p, --cached_context_p) {
if(*context_p != *cached_context_p) {
// The cached context doesn't match the application context, so it is
// invalid
return false;
}
}
```
This skips the comparing the null, however it will still also drop out and return true. It is just quicker to bail if the cached context is an "empty" string. 
I also considered renaming is_context_valid to …

fix(core): set_if_needed updates an empty cached context

---

common/web/gesture-recognizer/src/engine/headless/cumulativePathStats.ts
common/web/gesture-recognizer/src/engine/headless/regressiblePathStats.ts
common/web/gesture-recognizer/src/engine/headless/subsegmentation/constructingSegment.ts
common/web/gesture-recognizer/src/engine/headless/subsegmentation/pathSegmenter.ts
common/web/gesture-recognizer/src/engine/headless/subsegmentation/segment.ts
common/web/gesture-recognizer/src/engine/index.ts
common/web/gesture-recognizer/src/test/auto/headless/pathStats.ts

When looking at Web's filesize-profile with all the feature-gesture changes, I noticed that the path-stats object takes up a notable bit of space.  Simplifying it could yield us a few KB of filesize savings.
Toward that end, the first step is to split the stats object in twain; it's possible to make the full, subsegmentation-compatible version a subclass of a simplified, general base class.  Establishing that properly provides a good base... and it _is_ important to ensure that the unit tests related to the stats object continues to 'pass' properly.
Further simplifications and outright removal of the code will follow in a child PR - partly because doing so gives us a nice anchor point for the final state of the stats object, compatible with the newer version, that we can 'revert' to if …

chore(web): gesture stats simplification 🐵

---

android/KMEA/app/src/main/assets/android-host.js
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardWebViewClient.java
common/web/input-processor/src/text/prediction/languageProcessor.ts

Addresses the issue documented here: https://github.com/keymanapp/keyman/pull/10017#issuecomment-1823764995
The net effect of that issue is that suggestions would appear to be disabled upon swapping to a language with an different 'dictionary' from the most recently-used one.
The full documentation of the underlying cause can be found in that linked comment, but the essence of it is that the banner can't display any suggestions because it's _constantly being deactivated and reactivated_.  This is also generally considered "not good" for performance and device batteries.
TEST_PICKER_SELECTION_ANDROID:  Ensure suggestions are properly displayed after swapping keyboards with different language models.
1. Install the Android Keyman app test build from this PR.
2. Open Keyman App.
3. Install …

fix(android): no suggestions available when swapping pred-text target language ✨

---

developer/src/kmconvert/Keyman.Developer.System.KeyboardProjectTemplate.pas
developer/src/tike/actions/dmActionsMain.dfm
developer/src/tike/actions/dmActionsMain.pas
developer/src/tike/main/UfrmMain.dfm
developer/src/tike/main/UfrmMain.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectLoader.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectSaver.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProject.pas
developer/src/tike/xml/project/globalwelcome.xsl

Reverts some of the version 2.0 project functionality, as there are a number of challenges around populating files for folders that don't have project definitions, particularly if user attempts to load a folder that is not a project folder after all but happens, e.g. to have a source folder in it.
Also: generate version 2.0 keyboard project

chore(developer): require project file to exist 🦕

---

linux/debian/changelog
linux/debian/control
linux/debian/tests/control

Closes Debian bug [#1057134](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057134).

chore(linux): Add support for loong64 architecture 🏠

---

linux/debian/changelog
linux/debian/control
linux/debian/tests/control

Closes Debian bug [#1057134](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057134).
(🍒-picked from PR #10108)

chore(linux): Add support for loong64 architecture 🍒

---

web/src/app/browser/src/hardwareEventKeyboard.ts
web/src/engine/attachment/src/outputTargetForElement.ts

Fixes #10031.
**TEST_FIXED**: follow the repro instructions in #10031 to test if this is fixed. You can use the ["KeymanWeb Sample Page - Tests the new Attachment/Enablement API functionality"](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/426988:id/src/test/manual/web/attachment-api/index.html?mode=auto) (in manual mode) instead of the code listed in #10031.

fix(web): Don't throw errors after detach

---

developer/src/tike/actions/dmActionsMain.pas
developer/src/tike/main/UfrmMain.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectFiles.pas
developer/src/tike/project/Keyman.Developer.UI.Project.ProjectFilesUI.pas

Fixes #10003.
Multiple small fixes required here:
* Add .kpj as an editable file type
* Ensure that when OpenFile returns nil (which it always will for a .kpj), that we don't crash
* Ensure that projects open in a new process rather than replacing the current project session
Adds a TODO for New Project -- this should be opened in a new process if we already have a project open in the current process. Will push this into a separate PR (see #10138).

fix(developer): prevent opening .kpj in multiple processes 🦕

---

common/web/keyboard-processor/src/keyboards/activeLayout.ts
common/web/keyboard-processor/src/keyboards/defaultLayouts.ts
common/web/types/src/keyman-touch-layout/keyman-touch-layout-file.ts
web/src/test/manual/web/keyboards/gesture_prototyping/build/gesture_prototyping.js
web/src/test/manual/web/keyboards/gesture_prototyping/source/gesture_prototyping.keyman-touch-layout

As noted in a recent team trial of the current state of gestures, it felt really odd to not have the default layer as part of the layer rotation for the default shift-caps multitap interaction.  This change restores / enables that.

change(web): default shift-caps multitap inclusion of default layer in rota 🐵

---

web/src/engine/osk/src/banner/bannerGestureSet.ts
web/src/engine/osk/src/input/gestures/specsForLayout.ts
web/src/engine/osk/src/visualKeyboard.ts
web/src/test/manual/web/prediction-mtnt/index.html

Simple taps are no longer auto-cancelled when the touchpoint moves if roaming-touch is disabled; this provides consistency with the handling of keys supporting flicks.

change(web): prevents auto-cancellation of simple-taps for flicked layouts when touchpoint moves 🐵

---

common/web/input-processor/src/text/prediction/languageProcessor.ts

While @darcywong00 was working on the Android app keyboard banner, we discovered that when predictions are turned off, but a model is already loaded, the internal model-management code would still send the `configured` event (from model loading) when turning predictions off.  This should not happen, as that signaled the predictive-text banner to reappear.
TEST_EUROLATIN_PREDICTIONS_OFF:  Using the Keyman for Android app...
1. Set the keyboard to English - EuroLatin (SIL).
2. Using the app menu, navigate to Settings > Installed Languages > English.
3. Toggle "Enable predictions" off.
4. Leave the app menu.
5. Verify that neither a banner or blank space for a banner is shown.
TEST_KEYBOARD_SWAP:  Using the Keyman for Android app...
1.  Download the IPA (SIL) keyboard and install it.
2. …

fix(web): accidental suggestion-banner retoggle when disabling predictions

---

common/web/keyboard-processor/src/keyboards/activeLayout.ts
common/web/keyboard-processor/src/keyboards/keyboard.ts

Fixes #10099.
**TEST_FIXED**: 
- Open the [Unminified Source test page](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/428137:id/src/test/manual/web/unminified.html)
- Load the Armenian keyboard by typing "armenian" in the "Add a keyboard by keyboard name" field and pressing the "Add" button
- click in the "Type here" field and switch to the Armenian keyboard
- Verify that the Armenian OSK is shown, but no error

fix(web): Fix null error with legacy keyboards

---

windows/src/engine/keyman64/keyman64.vcxproj

Fixes: #10072 
Change the additional dependencies to include libcmtd.dll instead of limbcmt.dll for the debug build. Debug for keyman64 now builds.

fix(windows): debug includes libcmtd vs libcmt.dll

---

common/web/gesture-recognizer/src/engine/headless/gestures/matchers/pathMatcher.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/contactModel.ts
common/web/gesture-recognizer/src/engine/headless/touchpointCoordinator.ts
web/src/engine/osk/src/input/gestures/specsForLayout.ts

Fixes #10170.
Fixes #10171.
Longpress validation now occurs when the longpress would trigger, rather than on the initial key-down.  If the timer elapses on a key that doesn't support longpresses and roaming mode is disabled, the gesture-engine will enter a state that restores longpress processing when the base key changes - including a restart of the longpress timer.
TEST_ROAM_FROM_SUBKEYLESS:  Using the "Predictive Text: Robust Testing" KeymanWeb test page...
1. Select the "SIL EuroLatin" keyboard (under English).
2. Swap to the numeric layer.
3. Press and hold the `&` key for at least a second.
4. Move your finger over the `%` key and hold.
5. Verify that after a moment, a subkey menu appears with these options: `‰`, `‱`
In case of bad GitHub rendering: 
TEST_ROAM_TO_SUBKEYLESS:  Using …

fix(web): heterogenous longpress roaming 🐵

---

common/web/keyboard-processor/src/keyboards/activeLayout.ts

Fixes #10099.
(🍒-picked from PR #10141)
**TEST_FIXED**: 
- Open the [Unminified Source test page](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/428624:id/testing/unminified.html)
- Load the Armenian keyboard by typing "armenian" in the "Add a keyboard by keyboard name" field and pressing the "Add" button
- click in the "Type here" field and switch to the Armenian keyboard
- Verify that the Armenian OSK is shown, but no error

fix(web): Fix null error with legacy keyboards 🍒 🏠

---

web/src/engine/osk/src/input/gestures/browser/keytip.ts
web/src/engine/osk/src/input/gestures/browser/multitap.ts
web/src/engine/osk/src/input/gestures/browser/tabletPreview.ts
web/src/engine/osk/src/keyboard-layout/gesturePreviewHost.ts
web/src/engine/osk/src/visualKeyboard.ts
web/src/resources/osk/kmwosk.css

In order to provide better feedback to users, this implements a special key-preview pattern for use during active multitaps:
<details open><summary><strong>Phones</strong> (animated gif dropdown)</summary>
</details>
<details><summary><strong>Tablets</strong> (animated gif dropdown)</summary>
</details>
The key-preview is now kept alive during the multitap process.  Once a user's finger is lifted from a base key that supports multitaps, a "key hint" appears on the top-right for the next key in-line.  Upon receiving each new, incoming tap, the newly-activated key becomes the preview's "key cap", with the key next in rotation appearing as the next "hint".
Thanks to #10102, this works even when multitapping across layers...
<details open><summary>Layer-crossing previews</summary>
Note how …

feat(web): multitap key-previews 🐵

---

linux/keyman-config/keyman_config/fcitx_util.py
linux/keyman-config/keyman_config/install_kmp.py

1. Fcitx does not need to be restarted to load newly installed keyman keyboard
2. Restart fcitx may cause issue on kwin/weston Wayland where input method have to be spawned by compositor process. Manually start fcitx will not have permission to be functional with wayland input method protocol.

fix(linux): Do not restart Fcitx

---

mac/Keyman4MacIM/make-km-dmg.sh

Fixes #10200.
This is a two-part fix. First, with our normal `set -e` build environment, the existing loop never ran more than once, so the 5 second delay pattern we used to use in the dim dark past was no longer being applied. It is likely that in most cases, this will address the failure to detach.
The second part is to escalate our detach with a `-force` parameter, after 5 failed polite attempts. This is new and is addressing the suggestion in #10200, so we'll have to see if it has any impact on build stability.

chore(mac): force detach of disk image during build after 5 failures

---

.github/workflows/auto-merge-keyman-server-pr.yml
.github/workflows/crowdin.yml
.github/workflows/deb-packaging.yml
.github/workflows/labeler.yml

Fixes #10202 
Specifies Keyman repo so GitHub actions don't run on forks.

chore(common): Specify Keyman repo on GitHub actions

---

developer/src/tike/project/Keyman.Developer.System.Project.xmlLdmlProjectFile.pas

fix(developer): crash loading a project when referenced .xml is missing

---

common/web/gesture-recognizer/src/engine/configuration/gestureRecognizerConfiguration.ts
common/web/gesture-recognizer/src/engine/headless/cumulativePathStats.ts
common/web/gesture-recognizer/src/engine/headless/gestureDebugPath.ts
common/web/gesture-recognizer/src/engine/headless/gestureDebugSource.ts
common/web/gesture-recognizer/src/engine/headless/gesturePath.ts
common/web/gesture-recognizer/src/engine/headless/gestureSource.ts
common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureMatcher.ts
common/web/gesture-recognizer/src/engine/headless/gestures/matchers/pathMatcher.ts
common/web/gesture-recognizer/src/engine/headless/inputEngineBase.ts
common/web/gesture-recognizer/src/engine/headless/touchpointCoordinator.ts
common/web/gesture-recognizer/src/engine/index.ts
common/web/gesture-recognizer/src/engine/inputEventEngine.ts
common/web/gesture-recognizer/src/test/auto/headless/gesturePath.js
common/web/gesture-recognizer/src/test/auto/headless/gestureSource.spec.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/gestureMatcher.spec.ts
common/web/gesture-recognizer/src/test/resources/simulateMultiSourceInput.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/hostFixtureLayoutController.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/inputSequenceSimulator.ts
common/web/gesture-recognizer/src/tools/unit-test-resources/src/sequenceRecorder.ts
web/src/engine/osk/src/input/gestures/browser/flick.ts

The default mode for the gesture engine will no longer persistently store all coordinates visited by each touchpoint.  All relevant data is accumulated within the `CumulativePathStats` object and can be obtained from there.  This change thus should reduce runtime memory overhead, particularly for long-lived continuous gestures.  (Intermediate coordinates may now be garbage-collected quite rapidly, even while their touchpoint lives on.)
Accordingly, a new configuration flag has been added: `recordingMode`.  This flag reactivates persistent coordinate storing, which is useful for some of the existing automated tests and for, well, "recording" input sequences.  It might also be of use when debugging gesture-related issues.
I'd always intended for this change to occur at _some_ point... I'd …

feat(web): gesture processing - path memory-use optimization 🐵

---

web/build.sh
web/src/test/manual/build.sh
web/src/test/manual/web/gesture-recognizer/hostConfiguration.mjs

Noticed upon a review of a recent merge of master into the feature-branch - web's  build.sh had "temp" code to ensure the gesture engine was built when it wasn't connected.  It is connected now, via our build-script dependency system, so we no longer need that "temp" code.

chore(web): build script cleanup 🐵

---

core/include/keyman/keyman_core_api.h
core/src/action.cpp
core/src/action.hpp
core/src/km_core_action_api.cpp
core/src/state.hpp
core/tests/unit/kmnkbd/action_api.cpp
core/tests/unit/kmnkbd/action_set_api.cpp
core/tests/unit/kmnkbd/meson.build

Relates to #9999.
Adds `state->set_actions()`. This sets the Core's action list to match the contents of the action struct. Note that markers are not supported and backspace expected_values will be empty, as this information is not available. As the intended consumer of the action struct does not need to know this information, this should be adequate.

feat(core): action struct to action items conversion

---

common/windows/delphi/general/RegistryKeys.pas
developer/src/kmconvert/kmconvert.dpr
developer/src/kmconvert/kmconvert.dproj
developer/src/tike/actions/dmActionsMain.pas
developer/src/tike/dialogs/UfrmOptions.dfm
developer/src/tike/dialogs/UfrmOptions.pas
developer/src/tike/main/KeymanDeveloperOptions.pas
developer/src/tike/main/UfrmMain.pas
developer/src/tike/main/mrulist.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectFiles.pas
developer/src/tike/project/Keyman.Developer.System.Project.UrlRenderer.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProject.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProjectSettings20.pas
developer/src/tike/project/Keyman.Developer.UI.Project.xmlLdmlProjectFileUI.pas
developer/src/tike/xml/project/elements.xsl

A single PR for 4 separate fixes to Keyman Developer, all relating to Projects. The fixes are separated by commit but were small enough and isolated enough that I didn't think I needed to split into separate PRs (yeah, yeah, I know).
* fe772e1008 fix(developer): Validate SourcePath and BuildPath in Project Settings
Fixes #10148.
We now force the SourcePath and BuildPath project properties to be a direct subfolder of the project folder, in order to avoid issues with paths in the future. This is only applied to v2.0 projects, and only enforced via the UI at this point.
* 6c918e6aa8 fix(developer): Option to disable prompting for project upgrade
Fixes #10146.
Some developers may wish to stick with kpj-1.0 for now, and the prompt to upgrade would annoying because it cannot be hidden. This …

fix(developer): various project fixes 🦕

---

developer/src/tike/actions/dmActionsMain.dfm
developer/src/tike/actions/dmActionsMain.pas
developer/src/tike/main/Keyman.Developer.System.LaunchProjects.pas
developer/src/tike/main/Keyman.Developer.System.TikeCommandLine.pas
developer/src/tike/main/Keyman.Developer.System.TikeMultiProcess.pas
developer/src/tike/main/UfrmMain.dfm
developer/src/tike/main/UfrmMain.pas
developer/src/tike/main/mrulist.pas

Fixes #10149.
Adds a Window menu so user can easily switch between Keyman Developer processes or open a new instance.
* **TEST_NEW_WINDOW:** Open Keyman Developer. Use Window|New Window to open a new instance of Keyman Developer, which should open with no project open.
* **TEST_WINDOW_MENU:** Open several instances of Keyman Developer and open projects in each instance. Verify that the windows shown in the Window menu match up with the open projects.

feat(developer): Add Window menu 🦕

---

developer/src/tike/actions/dmActionsMain.pas
developer/src/tike/main/Keyman.Developer.UI.ImportWindowsKeyboardDialogManager.pas
developer/src/tike/main/UfrmMain.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewModelProjectParameters.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewProjectParameters.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProject.pas

Fixes #10138.
If the current instance of Keyman Developer already has a project open, then the New Project dialog will now open the new project in a new instance of Keyman Developer.
Note: this also moves a couple of functions out of dmActionsMain and into UfrmMain, as their functionality belongs more closely there. The `TmodActionsMain.OpenProject` function has been renamed to `TfrmMain.OpenProjectInCurrentProcess` to clarify its usage and context.
* **TEST_NEW_PROJECT:** Open Keyman Developer, and open a project. Create a new project, and verify that the new project opens in a new instance of Keyman Developer.
* **TEST_NEW_PROJECT_NO_PROJECT_OPEN:** Open Keyman Developer, and make sure no project is open (Project|Close Project). Create a new project, and verify that the project opens in …

feat(developer): New Project opens in new process 🦕

---

developer/src/tike/xml/layoutbuilder/builder.js

Fixes #10194: error when rescaling touch layout editor keys.
Fixes #10091: touch layout editor wedges don't scroll
Note: when scrolling the selected key off screen, the wedges will appear above toolbars, while the key scrolls under. This is a separate stylistic issue which I don't intend to address at this time.
I have tested these locally and am satisfied that the results are good.

fix(developer): two errors in touch layout editor

---

common/web/gesture-recognizer/src/engine/headless/gestures/matchers/pathMatcher.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/pathModel.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/isolatedPathSpecs.ts
web/src/engine/osk/src/input/gestures/specsForLayout.ts

change(web): prep for enhanced flick-resets - alters the contact-path evaluation signature 🐵

---

common/web/gesture-recognizer/src/engine/headless/cumulativePathStats.ts
common/web/gesture-recognizer/src/engine/headless/gesturePath.ts
common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureMatcher.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/contactModel.ts
common/web/gesture-recognizer/src/engine/inputEventEngine.ts
web/src/engine/osk/src/input/gestures/browser/flick.ts
web/src/engine/osk/src/input/gestures/specsForLayout.ts
web/src/engine/osk/src/visualKeyboard.ts

Rather than requiring a user to remember exactly where their initial touch location was for a flick during resets, this set of changes allow for flicks to 'change' their start location when reset.  A location nearish the center of the base key will always be chosen in a manner that also favors the actual location of the active contact-point when reasonable.
Deliberately _not_ picking the actual center, but an off-center location with a moderate radius of it toward the actual location of a touch, it becomes far easier to swap flick direction intuitively after a reset.
**TEST_FLICK_LOCKING**:  Using the standard "Test unminified KeymanWeb" test page from a mobile device...
1. Select "English...", then "Gesture Prototyping".
2. Tap and hold the `u` key.
3. For the following steps, pay …

feat(web): enhanced flick resetting via path base-coord replacement 🐵

---

core/src/ldml/ldml_transforms.cpp

- needed to declare the pointer properly
Fixes: bug(core): Build failures in LDML code on newer Ubuntu versions #10249

fix(core): ldml: fix bad usage of unique_ptr 🙀

---

common/web/input-processor/README.md
common/web/keyboard-processor/README.md
docs/build/linux-ubuntu.md
docs/build/old/web-notes.md
linux/Dockerfile

🐋 
- fix the Node.js install script deprecation 
- fix the user-facing docs to just point people to <https://github.com/nodesource/distributions#ubuntu-versions> for installing.
- also make items configurable such as Ubuntu version and Node version
Fixes: chore(linux): script deprecation warning from nodesource #10024

chore(linux): docker: fix Node.js install, make customizable

---

web/src/test/auto/dom/cases/browser/contextManager.js

Glad I double-checked the final build check status & investigated.
There was a unit test that expected the wrong behavior.  Behavior was corrected in #10245, but not the test... which means test failures will occur without this test-fix.

fix(web): unit test for null-null keyboard switch event from #10245

---

web/src/test/manual/embed/android-harness/host.js

#10022 broke Web's test page that emulates an Android WebView, as it added a new method to the interface (in Android code) that did not get a mocked version in the test page.  This rectifies that.

fix(web): fixes android-webview emulation Web test page

---

web/src/engine/attachment/src/pageContextAttachment.ts
web/src/engine/element-wrappers/src/input.ts

This changes `isKMWInput` so that it accepts the same `HTMLInputElement` types that `listInputs` accepts. 
Closes #8848.

fix(web): Fix types that listInputs and isKMWInput accept

---

mac/KeymanEngine4Mac/KeymanEngine4MacTests/KMEngineTests.m

Fix two units that are expecting the context to be unchanged after a tab and enter keys are processed by core. These keys invalidate the context and should cause the core to clear the context.

fix(mac): unit tests should expect core context clear after invalidate

---

web/src/engine/osk/src/input/gestures/heldRepeater.ts

Fixes #10263.
The backspace key will now receive special-key highlighting when held, regardless of the duration and number of triggered BKSP repetitions while held.
TEST_SIMPLE_BACKSPACE:  Using the Keyman for Android app artifact from this PR, verify that a simple backspace-tap acts as expected.
1. Using the "EuroLatin (SIL)" keyboard...
2. Type `text`.
3. Tap the BKSP key once.
- Verify that the BKSP key was highlighted when your finger was on it.
- Verify that the BKSP key is no longer highlighted after the tap.
TEST_HELD_BACKSPACE:  Using the Keyman for Android app artifact from this PR, verify that a simple backspace-tap acts as expected.
1. Using the "EuroLatin (SIL)" keyboard...
2. Type `text`.
3. Press and hold the BKSP key - do not release it at this time.
4. Verify that the BKSP …

feat(web): adds highlighting to BKSP while held

---

common/web/types/src/kmx/string-list.ts
common/web/types/src/osk/osk.ts

fix(web): unbreak some ts paths

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
mac/Keyman4MacIM/Keyman4MacIM/TextApiCompliance.m

This addresses two cases with non-compliance:
1) apps that report a seemingly valid selection (location and length) but the selection does not change after a character is inserted
2) apps for which the compliance varies when the context changes from one text field to another within the same application (e.g. Safari, switching from the URL field to the content area of Google Docs)
Fixes #10247

fix(mac): Improve detection of non-compliant apps

---

common/web/keyboard-processor/src/keyboards/activeLayout.ts
common/web/keyboard-processor/src/keyboards/defaultLayouts.ts
common/web/types/src/keyman-touch-layout/keyman-touch-layout-file.ts

Fixes #10272.
When on the shift layer, our default 'caps' layer multitap logic should act as follows:
1. First tap:  default layer
2. Second tap:  caps layer
3. Third tap: return to shift layer
4. Return to step 1 - default layer.  (Things rotate from here.)
In 16.0, steps 1 and 2 (at a minimum) were in place... and I missed this fact when migrating the default multitap logic to the new gesture engine.  This PR fixes the regression.  (Rota behavior - steps 3+ - wasn't expected or implemented at the time, though.)
**NOTE**: The fact that _both_ the `default` and `shift` layer SHIFT keys get multitaps when relying on Keyman multitap defaults suggests to me that we should condition on both SHIFT keys, not just one of them - and so I moved the logic to a location that can check against the …

fix(web): default multitap logic for shift-layer shift multitaps

---

oem/firstvoices/keyboards.csv

Similar to #10269 
While auditing keyboards.csv with the kmp.json file from fv_all.kmp, I saw the mobile apps need an entry for fv_kwadacha_tsekene.
Will need to :cherries: pick to stable-16.0 (or add to #10285)
Tagging @caforbes
**Setup** - Install the PR build of FV for Android or FV for iPhone and iPad
* **TEST_ANDROID** - Verifies fv_kwadacha_tsekene can be installed
1. Install the PR build of FirstVoices for Android on an Android device/emulator
2. Launch the FV App
3. From the Setup menus, install the following keyboards (regions in parenthesis):
* fv_kwadacha_tsekene (BC Interior)
4. From the FV setup menu, set FirstVoices as the default system keyboard
5. Launch a separate app
6. Switch through the FV keyboards and verify the following version:
* fv_kwadacha_tsekene (1.0)
* …

fix(oem/fv): Add fv_kwadacha_tsekene

---

resources/locate_emscripten.inc.sh

- change the common emscripten locator to warn if $EMCC  or $EMSCRIPTEN_BASE/emcc.py is present but not executable
- emscripten v3.1.50 via homebrew seems to be not executable

fix(common): give warning if emcc.py is present but not executable

---

common/web/types/src/util/compiler-interfaces.ts
developer/src/common/web/test-helpers/index.ts
developer/src/kmc-ldml/src/compiler/compiler.ts
developer/src/kmc-ldml/test/helpers/index.ts
developer/src/kmc-ldml/test/test-tran.ts

- when a required section is missing, only throw an internal error IF we haven't already flagged a problem.  for example, if 'vars' fails to compile because of a problem, and we already have an error on file, then don't throw an internal error that 'bksp' depends on uninitialized 'vars'.
- mimic this flow in the test helpers.
- add a test case for this in the test helpers, in test-tran
- add a strictError flag to say that no additional errs are allowed.
Fixes: #10291

fix(developer): quell internal error when  a section fails 🙀

---

mac/KeymanEngine4Mac/KeymanEngine4Mac.xcodeproj/xcshareddata/xcschemes/KeymanEngine4Mac.xcscheme
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreWrapper.m
mac/KeymanEngine4Mac/KeymanEngine4MacTests/KMEngineTests.m

Consume the persisted options action returned from Keyman Core and persist it to the User Defaults for Keyman. 
Fixes #10273
**TEST_ARMENIAN_OPTION_CHANGE**: 
- Open the Stickies app on the Mac and create a new note
- Switch to the Armenian Mnemonic keyboard 
- Type <kbd>e</kbd><kbd>w</kbd>
- Confirm that this produces the output: եւ
- Type option-v, w (this toggles a setting within Keyman for this specific keyboard)
- Type <kbd>e</kbd><kbd>w</kbd>
- Confirm that this same input as earlier now produces the output: և
**TEST_ARMENIAN_OPTION_PERSISTED**: 
- Restart the computer after the above test is completed
- Open the Stickies app on the Mac and create a new note
- Switch to the Armenian Mnemonic keyboard 
- Type <kbd>e</kbd><kbd>w</kbd>
- Confirm that this produces the output: և
- This …

fix(mac): write persisted options returned from Core

---

windows/src/desktop/kmshell/kmshell.dpr
windows/src/desktop/kmshell/kmshell.dproj
windows/src/desktop/kmshell/main/Keyman.System.RemoteUpdateCheck.pas
windows/src/desktop/kmshell/main/RemoteUpdateCheck.pas
windows/src/desktop/kmshell/main/initprog.pas
windows/src/desktop/kmshell/render/UpdateXMLRenderer.pas

This is just first step in #10038 
Fixes:   #10119
I discovered
Not going to use call backs at all at this stage.
For now I have this testing with `kmshell.exe -buc` I will have this separated more in the next PR
This I think can be done I just have a question around `old version` it seems that we don't want to use the old version in the Response. Probably because it is just the "previous" version. Where as the version currently installed could be even older. We could make the Fparams of type `TUpdateCheckResponse`  as the only other piece of data we would lose is a`TRemoteUpdateCheckResult` which I will not be using.
This was just flat file for recording the file names of the packages in the temporary data location in the case when the elevated call was required.  We now have all the …

feat(windows): Remove UI com online-update check 📲 💽

---

web/src/engine/osk/src/input/gestures/specsForLayout.ts

Should there not be a selectable key at an active touchpoint (say, due to blank keys), we should prevent `null` errors when checking for triggering longpresses.  In such a case, we'd fail to lookup subkeys on a `null`/`undefined` key.
Assuming we have a valid, non-null object for the key, the rest of the properties should be exist, save perhaps for the final one (`.sk`).  If they don't, that's a separate error and would be worth much more of an investigation.

fix(web): adds null-guard for longpress-key validation

---

web/src/engine/osk/src/visualKeyboard.ts

Fixes #10280.
While we don't show key previews for 'special' keys, we should still show highlighting when they're pressed.
TEST_ENTER_HIGHLIGHT_DESKTOP: Using the "Test Inline OSK" test page for KeymanWeb, verify that the ENTER key receives highlighting when pressed.
1. Click on the first text area (with placeholder text "Type here").
2. Hit the ENTER key once.
3. Verify that the key was highlighted when pressed and is no longer highlighted once released.
TEST_ENTER_HIGHLIGHT_IOS: Using the "Test Inline OSK" test page for KeymanWeb, verify that the ENTER key receives highlighting when pressed.
1. At the bottom of the page, click the button labeled "setOSK(ios)".  The OSK should change to that of a touch keyboard.
- Note:  the keyboard's globe key may not function.  This is fine.
- The key …

fix(web): special key highlighting when pressed

---

android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java

Fixes #10132
> When installing a keyboard package that is missing a touch-optimized .js keyboard file, a toast appears indicating that there is an error, but it is truncated and disappears too quickly. It should be a message box because it's an error the user should respond to.
This changes the error message from a Toast notification that disappears to an alert dialog that remains until the User closes it.
**Setup**
1. Install the PR build of Keyman for Android on Android device/emulator.
2. On the device/emulator, download a keyboard package (.kmp) file that's missing a touch-optimized .js keyboard file. An example .kmp file is at https://darcywong00.github.io/examples/invalid/sil_ethiopic.kmp
* **TEST_ALERT_DIALOG** - Verifies alert dialog is displayed when keyboard package is missing a …

fix(android): Use alert dialog when package is missing touch keyboards

---

windows/src/desktop/kmshell/web/Keyman.Configuration.System.HttpServer.App.pas

Fixes #10308.
When a file is requested without a tag parameter, we need to look to the referer to find out what the tag is, so we can associate it with the correct readme file.
TEST_INSTALL_README: Try and install the package in readme_images_10308.zip from #10308. Verify that the flag image shows in the Readme tab.

fix(windows): serve images for readme files in Keyboard Install

---

developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/tike/child/UfrmKeymanWizard.pas

Fixes #10315.
When filling from layout, if the .kvks file did not exist, an obscure error was generated:
Error: 2908 Error encountered parsing eo_plus.kvks: TypeError: Cannot read properties of null (reading 'byteLength')
Fixed this by checking for file existence before attempting to process, which then reports a more understandable error of 'file not found'.
Then, needed to tweak the caller in Keyman Developer IDE to remove the reference to the .kvks file before attempting to build (chicken-and-egg).

fix(developer): cleanly handle filling a new osk file from layout

---

developer/src/tike/actions/dmActionsMain.pas
developer/src/tike/dialogs/UfrmNew.pas
developer/src/tike/dialogs/UfrmNewFileDetails.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmProject.pas

Fixes #10276.
Adding new files to a v2.0 project was unsupported. This requires a little bit of a logic change to the two new File New dialogs:
1. The New File Details dialog does not allow changing from the SourcePath of the project.
2. The New File dialog does allow changing to any path. If you select a path outside the project path, it will open in a new window.
* **TEST_NEW_FILE_10:** Open an existing v1.0 project file, click File|New, and create a new file (any type). Verify that it creates correctly.
* **TEST_NEW_FILE_DETAILS_10:** Open an existing v1.0 project file, click `New Keyboard...`` in the Project tab, Keyboards view, and create a new keyboard file. Verify that it creates correctly.
* **TEST_NEW_FILE_20:** Create a v2.0 project file, click File|New, and create a new file …

fix(developer): new file support for project 2.0

---

developer/src/server/src/site/test.js
web/src/engine/package-cache/src/modelCache.ts
web/src/test/manual/web/issue3701/index.html
web/src/test/manual/web/issue9469/index.html
web/src/test/manual/web/prediction-mtnt/index.html
web/src/test/manual/web/prediction-ui/index.html

It would appear that ever since KeymanWeb got modularized, the Developer test-page hooks for loading models have been broken.  With #8472, `keyman.modelManager` was reworked into `keyman.modelCache`. 
The prediction and correction toggle properties... weren't even available there in 16.0, so the Web test-page toggles have likely been dead for a little while.  I went ahead and patched them up while I was at it.
TEST_PREDICTIVE_TOGGLES:  Using the "Prediction - robust testing" for **_KeymanWeb_** **on a mobile device**, verify that the toggles have the indicated effect.
1. Click on a text area.
2. Verify that the predictive-text banner is visible.
3. Click on a blank part of the page (to dismiss the OSK)
4. Click the "Disable predictions" button.
5. Click on the original text area (from …

fix(developer): test-page model loading

---

developer/src/tike/main/Keyman.System.KeymanCore.pas
developer/src/tike/main/Keyman.System.VisualKeyboardImportKMX.pas
linux/ibus-keyman/src/engine.c
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreWrapper.m

Relates to #10365.
Use `km_core_state_context_clear()` instead of `km_core_context_clear()` as part of eliminating use of `km_core_state_context()`.

refactor(core): use `km_core_state_context_clear` where possible

---

ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift

The drop down menu in Keyman should be positioned so that it is not obstructed by the notch that appeared beginning with the iPhone X or the dynamic island that appeared beginning with the iPhone 14 Pro.
Fixes #8168 
**TEST_DROP_DOWN_MENU_PORTRAIT**: 
- Install the attached version of Keyman on an iPhone 14 Pro simulator
- Click on the Keyman dropdown menu represented by three dots on the menu bar
- Verify that the menu is completely visible when it drops down
**TEST_DROP_DOWN_MENU_LANDSCAPE**: 
- Click on the Keyman dropdown menu represented by three dots on the menu bar
- Rotate the phone to the landscape orientation with the notch/dynamic island on the right side
- Verify that the menu is completely visible when it drops down

fix(ios): use safe area to position Keyman menu correctly

---

core/include/keyman/keyman_core_api.h
developer/src/tike/main/Keyman.System.KeymanCore.pas
developer/src/tike/main/Keyman.System.VisualKeyboardImportKMX.pas
linux/ibus-keyman/src/engine.c
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreWrapper.m

Also update comment on `km_core_state_context_set_if_needed` to make it clearer that it's expecting a UTF-16 string.
Closes #10212.
- The tests can be run on any Linux platform
- Reboot
- **TEST_IPA_WRITER:** Open LibreOffice Writer. Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_IPA_GEDIT:** Open gedit. Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_KO_WRITER:** Open LibreOffice Writer. Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_KO_GEDIT:** Open gedit. Switch to "Korean KORDA Jamo (SIL)" keyboard. Type …

refactor(linux): Use `km_core_state_context_set_if_needed`

---

core/tests/unit/kmnkbd/action_api.cpp
core/tests/unit/kmnkbd/meson.build
core/tests/unit/kmnkbd/state_context_api.cpp

It was fairly surprising to have the unit tests for `km_core_state_context_*` methods in `action_api.cpp`, so this change moves them to a separate file.

refactor(core): Move `km_core_state_context_*` tests to separate file

---

developer/src/kmc-kmn/build.sh
developer/src/kmc-kmn/src/kmw-compiler/kmw-compiler-messages.ts
developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts
developer/src/kmc-kmn/test/fixtures/kmw/validate_gesture.keyman-touch-layout
developer/src/kmc-kmn/test/fixtures/kmw/validate_gesture.kmn
developer/src/kmc-kmn/test/kmw/test-kmw-messages.ts

Fixes #10191.
Reports a compiler warning for the first multitap or flick gesture found, if keyboard does not target 17.0+. Does not treat this as an error (unless 'treat warnings as errors' is enabled, of course).

feat(developer): warn on gesture support for downlevel

---

web/src/engine/osk/src/input/gestures/browser/multitap.ts
web/src/engine/osk/src/keyboard-layout/gesturePreviewHost.ts
web/src/engine/osk/src/keyboard-layout/oskBaseKey.ts
web/src/engine/osk/src/keyboard-layout/oskKey.ts

The OSK render would always use the key cap font for hint text, but for special text strings which are replaced by symbols from the KMW OSK font (e.g. `*Shift*`) we need to both transform this, and use the correct font.
---
In a picture:
That hint is from the special-key shortcut `*Symbol*`.  While subkeys were already being adequately styled, I recently realized that _hints_ were not considering such shortcuts.  For the record, Developer doesn't either:
While I was at it, I also considered the case where such use might appear in a multitap-gesture preview hint.  This shouldn't happen for most of our defined *Special* cases, but we do support *ZWNJ* and a few other special keycodes in a similar manner, so it's conceivable this could matter for some keyboard yet to be defined.
There are …

fix(web): use KMW OSK font for "**" special-text in key hints

---

docs/settings/linux/extensions.json
docs/settings/linux/settings.json

The previous settings are now deprecated, so this change replaces them.

docs(linux): Update sample settings

---

.github/workflows/deb-packaging.yml
linux/debian/libkeymancore.symbols
linux/scripts/deb-packaging.sh

We have a C API, but (internal) C++ template instantiations are visible and so get flagged by `dpkg-gensymbols`. This change ignores the one use of C++ by marking it optional. This is listed as a usage scenario in the dpkg-gensymbols man page.
Note this requires a change how we call dpkg-gensymbols: if the `-O` parameter is specified, the file is not treated as being a template file (see man deb-src-symbols) and so the tags are not interpreted. Additionally the file gets overwritten with the non-tag version. So this change removes the `-O` parameter, and changes the archiving of the generated file.

chore(core): Ignore C++ symbols

---

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustKeyboardHeightActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Fixes #10241 
Fixes #9978 
Fixes #9191 
There were multiple bugs related to OSK not filling the full width or not appearing after rotating the device orientation.
The main two fixes on this PR:
* Disable multi-window (where modern Android devices try to split the screen so dimensions are "half"
* The existing device orientation code would sporadically report PORTRAIT when the device was LANDSCAPE. Changing to getRotation() seems to have more consistent behavior.
**Setup** - Install the PR build of Keyman for Android on the device/emulator. Some tests specify a specific Android SDK level
* **TEST_LANDSCAPE_KEYBOARD_PICKER** - Verifies menu to adjust keyboard height works
1. Install the PR build of Keyman for Android on an Android device/emulator
2. with the device in Landscape mode, Launch …

fix(android): Fix OSK rotation issues

---

mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreWrapper.h
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreWrapper.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.h
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m
mac/KeymanEngine4Mac/KeymanEngine4MacTests/CoreWrapperTests.m
mac/KeymanEngine4Mac/KeymanEngine4MacTests/KMEngineTests.m

Relates to #10365.
Ensures that the only uses of the Core context are for unit tests. Renames accordingly to clarify usage.

refactor(mac): remove unused context calls 🌱

---

web/src/engine/osk/src/input/gestures/browser/subkeyPopup.ts

Fixes #10286 
When rapidly typing with longpress keys and switching keyboards, a null exception would get thrown on `(<HTMLElement>e.offsetParent).offsetLeft`.
This adds a check to use an offset of 0 if e.offsetParent is null.
**Setup**
1. Install the PR build of Keyman for Android on an Android device (needs to be a physical device in order to rapidly type longpress keys and globe key switches
2. From Keyman for Android, install a second Keyman keyboard (e.g. khmer_angkor). This way, the pressing the globe key switches between Keyman keyboards
* **TEST_TYPING_AND_SWITCHING_KEYBOARDS** - Verifies error not shown when changing the keyboard during typing
2. In the Keyman app with both hands, rapidly type longpress keys and …

fix(web): Add null check for changing the keyboard during typing

---

docs/core-api-verification.md

docs(linux): Add documentation for Core API verification

---

web/src/engine/osk/src/keyboard-layout/gesturePreviewHost.ts

... thought I could get away with not double-checking numerical errors on the trig functions related to flick angles, but alas... nope.  The trig function used to detect north-ish flicks reported a change of y-coordinate for 'e' flicks on the order of -1e-18... which is less than zero, and the negative sign caused this to be interpreted as "northish".
If you put this...
```
Math.cos(Math.PI/2)
```
into a JS terminal, you don't get `0` - you get `6.12e-17`, despite cos(90 degrees) = 0 being a known trig property (with 90 degrees = pi/2 radians).  Add a little numerical approximation error on top of that... and you get the source of the 'e'-flick error.
With this change, 'e' flicks now use the upward-positioned gesture previews as originally intended.

fix(web): right-flick gesture-preview positioning

---

mac/Keyman4MacIM/KeymanTests/TestAppDelegate.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreWrapper.h
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreWrapper.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.h
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMEngine.m
mac/KeymanEngine4Mac/KeymanEngine4MacTests/CoreWrapperTests.m

refactor(mac): remove legacy Core context API calls 🌱

---

ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js

Fixes #9990.
If an "image banner" is set in place before its image is ready, setting the image will refresh the image banner with the newly-available image.
It appears that either during ES module (🧩) or gesture (🐵) work, the order of the two internal image-banner related methods changed.  This update should allow things to work and update properly regardless of method ordering.
TEST_SYSTEM_IMAGE_BANNER:  Using the Keyman for iPhone and iPad app, verify that the image banner works as intended when enabled.
1. Test Setup
1. Using the `Settings` menu, enable the "Show Banner" toggle.
2. Using "Settings" > "Installed Languages" > "+", serach for and install the `sil_ipa` keyboard.
3. Ensure that Keyman is enabled as a system keyboard.
- Use "System Keyboard Settings" if needed to enable …

fix(ios): banner image management

---

android/KMAPro/kMAPro/build.gradle
android/KMEA/app/build.gradle
android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample2/app/build.gradle
android/Tests/KeyboardHarness/app/build.gradle
android/Tests/keycode/app/build.gradle
oem/firstvoices/android/app/build.gradle

Typically, we just update the Android apps' targetSdkVersion at the beginning of the Alpha cycle.
I figure the minor update now will save us some Play Store hassle later this year.
Also `compileSdkVersion` got replaced with `compileSdk`
Reference
https://developer.android.com/reference/tools/gradle-api/8.2/com/android/build/api/dsl/CommonExtension#compileSdkVersion(kotlin.String)
**Setup** - Install the PR builds on an Android device/emulator
* **TEST_KEYMAN** - Verifies Keyman for Android works
1. Install Keyman for Android
2. Verify Keyman app launches fine
3. Verify the inapp keyboard works fine
* **TEST_FV** - Verifies FirstVoices for Android works
1. Install FirstVoices for Android
2. Verify FV app launches fine
3. Use the FV setup menus to install FV keyboard and enable as default …

chore(android): Update targetSdkVersion to 34

---

common/web/gesture-recognizer/src/engine/gestureRecognizer.ts
web/src/engine/osk/src/visualKeyboard.ts

Fixes the underlying problem that motivated #10346.
This is intended to act as a patch-PR for #10346, contributing to a more complete, comprehensive solution.
Just realized the base branch had a user test.  The least we could do it run that one here, too.
**Setup**
1. Install the PR build of Keyman for Android on an Android device (needs to be a physical device in order to rapidly type longpress keys and globe key switches
2. From Keyman for Android, install a second Keyman keyboard (e.g. khmer_angkor). This way, the pressing the globe key switches between Keyman keyboards
* **TEST_TYPING_AND_SWITCHING_KEYBOARDS** - Verifies error not shown when changing the keyboard during typing
2. In the Keyman app with both hands, rapidly …

fix(web): cancels active gestures on globe-key use

---

web/src/engine/osk/src/visualKeyboard.ts

TEST_KBD_DOCS:  Visit the "Tests keyboard documentation rendering" Web test page and wait.  Verify that the following keyboards get rendered:
- Amharic
- EuroLatin (SIL)
- Lao Basic (once for a tablet touch-layout, then once for a desktop-layout [including CAPS, TAB, ... keys])
- Cameroon AZERTY
- Khmer Angkor

fix(web): keyboard-documentation rendering mode

---

ios/engine/KMEI/KeymanEngine/Classes/TextField.swift
ios/engine/KMEI/KeymanEngine/Classes/TextView.swift

Heavily mitigates #9211.
While there will still be a very slight bit of layout-shift that still occurs, this eliminates the multiple slide-in animations for the keyboard that appear at app start.
How it looks now, in Simulator:
Notice the subtle shift in the keys near the end of the GIF - that's the "slight bit of layout shift" I was referring to.
The likely reason for this:
Note the timing of `kmwosk.css` in the Network tab; it loads relatively late in the process... as does the OSK font.  Though... symbols from the font are actually showing up _before_ the shift, so I'm not fully confident that this delay is the cause.  Using the same debugger, it appears that the shift actually happens solely within the "Layout & Rendering" section at a time that doesn't overlap with _any_ network …

fix(ios): multiple keyboard slide-in animations on app start

---

common/web/keyboard-processor/src/keyboards/activeLayout.ts
web/src/engine/osk/src/keyboard-layout/oskKey.ts

During the addition of gesture features, I failed to handle `U_` key ID processing for key text associated with previews of the new gesture types.  This change will address that.
Relates to #10383 - and is likely a reasonable resolution to that issue, given that the behavior already existed in Web for longpress subkeys.  (See sil_euro_latin numeric layer `%` subkeys - those have no defined key-cap text.)
It also handles this in the keyboard-layout preprocessing stage, ensuring that it's universally applied for all OSK keys and subkeys before touch-keyboard construction even begins.  (This helps ensure DRY-ness.)

fix(web): U_ key id -> text for all subkeys; is now preprocessed

---

core/src/context.hpp
core/src/context_helpers.cpp
core/src/km_core_state_context_set_if_needed.cpp
core/src/meson.build
core/tests/unit/kmnkbd/test_actions_normalize.cpp

refactor(core): move context helpers to a new module 🌱

---

core/src/ldml/ldml_processor.cpp
core/src/ldml/ldml_processor.hpp

- move the emit_ and context functions into an ldml_event_state object
For: #10410 
Note: rebased to make non-changes more clear.

chore(core): ldml shuffle some deck chairs 🌱

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
common/web/lm-worker/build.sh
ios/engine/KMEI/KeymanEngine/Classes/Resource Management/Storage.swift
ios/engine/build.sh
web/src/app/webview/build.sh
web/src/tools/building/sourcemap-root/index.ts

It turns out that sourcemaps don't work during Chrome-based inspection of a mobile app's webview... unless those sourcemaps are inlined.  So, the natural thing to do - inline 'em!
The worker sourcemaps helped me discover this, though I noticed that the source paths reported within Chrome weren't quite right.  The first commit aims to fix that aspect.

chore(web): worker sourcemap cleanup, mobile app webview sourcemap compat

---

android/KMEA/app/src/main/java/com/keyman/engine/cloud/CloudDownloadMgr.java

Fixes [Sentry crash](https://keyman.sentry.io/issues/4892768528/?environment=local&project=5983520&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0) and follows #10393 which updates the Android targetSDKVersion to 34.
Per Android Developer guide about apps targeting Android 14
https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported
> Apps and services that target Android 14 and use [context-registered receivers](https://developer.android.com/guide/components/broadcasts#context-registered-receivers) are required to specify a flag to indicate whether or not the receiver should be exported to all other apps on the device: either RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED
**Setup** - Install the PR build of Keyman for Android on …

fix(android/engine): Add RECEIVER_EXPORTED flag for broadcast receiver

---

common/web/types/tsconfig.json
developer/src/kmc-kmn/tsconfig.json
tsconfig.base.json

Fixes #10486.
Note: we are not enabling this globally, because KeymanWeb can break on some of its modules. Something for us to consider for the future.
I audited usage of const enum elsewhere and found it only in common/web/types and developer/src/kmc-kmn.

fix(common): preserve const enums in tsc build 🌱

---

developer/src/server/package.json
developer/src/server/src/config.ts
developer/src/server/src/index.ts
developer/src/tike/dialogs/Keyman.Developer.UI.UfrmServerOptions.dfm
developer/src/tike/dialogs/Keyman.Developer.UI.UfrmServerOptions.pas
developer/src/tike/main/KeymanDeveloperOptions.pas
package-lock.json

Fixes #10357.
TEST_NGROK_UPGRADE: In Keyman Developer, Tools|Options|Server, Configure Server, click `Download or update ngrok`. Once the download completes, the label to the right of the button should show "ngrok version 3.5.0" or similar (it must be version 3.2 or later to pass).
TEST_NGROK_WORKING: In Keyman Developer, verify that you have enabled ngrok in Keyman Developer Server Options. Open a keyboard, and test it on web. Verify that a URL appears in the list of server web addresses, and that when you select it to Open in browser, the test web site works correctly.
Note: your ngrok entry will look different to this but will be a public website:

chore(developer): upgrade ngrok to v3

---

common/web/types/src/util/common-events.ts

- stray dot in the pathname, it's not a regex

fix(common): ldml: fix typo in kmc error message 🙀

---

developer/src/kmc/build.sh

Fixes #10490.
Note that the default is to inject into .js, .mjs, .cjs, so we don't need to override that.

fix(developer): sentry-cli no longer injects into .d.ts 🌱

---

developer/src/inst/node/kmc.cmd

Fixes #10487.
In Keyman Developer's wrapper of kmc, we now accept `--enable-source-maps` as the first parameter to pass on to node. We do not enable source maps by default because they have a performance penalty.

chore(developer): `--enable-source-maps` parameter for kmc wrapper

---

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustKeyboardHeightActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMEA/app/src/main/AndroidManifest.xml
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Follows #10373 and fixes #10241
This applies two things to fix OSK width to be full screen
* Disables multi-window mode for the entire Keyman app
* Refactors detection of device orientation so MainActivity.onResume() has the correct dimensions for the OSK
**Setup** - Install the PR build of Keyman for Android on an Android 12.0 device /emulator (SDK 31)
* **TEST_OSK** - Verifies OSK is full width after using keyboard picker
1. Launch Keyman for Android in landscape
2. Type some letters on the input text screen. 
3. Longpress the globe key to open the Keyboard picker menu. 
4. Click the default keyboard. 
5. Verify the app shows the OSK full-width.

fix(android/engine): Fix OSK widths

---

web/src/engine/osk/src/banner/banner.ts
web/src/engine/osk/src/banner/bannerView.ts
web/src/engine/osk/src/banner/suggestionBanner.ts
web/src/engine/osk/src/views/oskView.ts

Fixes #10477.
The predictive banner's suggestions are now automatically resized when rotating device orientation.  It's more complex than it was before #7934, when basic width-% styling was sufficient.   Fortunately, the fancy-banner layout logic was relatively easy to separate from the suggestion-update logic for use in layout refreshes.
TEST_BANNER_ROTATION:
1. Open Keyman In-App.
2. Verify that the predictive texts appear from left to right, filling the width of the suggestion banner.
3. Change the Mobile Orientation from Portrait to Landscape. 
4. Verify that suggestions extend to the full width of the suggestion banner with comparatively even padding/width for each (with more on longer words).

fix(web): banner suggestion resizing after device rotation

---

web/src/engine/osk/src/visualKeyboard.ts

Fixes #10444 for standard use cases.  To reach "all use cases" will take a bit more work.
TEST_BALOCHI_PHONETIC:  Using the Keyman app on an iPhone - preferably on an iPhone SE (emulated or real) - verify that key caps are sufficiently large.
1. Install the  `balochi_phonetic` keyboard.
2. Load the `balochi_phonetic` keyboard.
3. Verify that multiple keys have key caps spanning nearly the entire width of their respective keys.
- Good keys to inspect:
- 'g': `گ`
- 'k': `ک`
- 'e': `ے`
- 't': `ت`
Example of the keyboard properly rendered:
How it looks on the current `master`, for comparison:
It may be wise to run the test a second time, with the latest `alpha` build, for comparison.
(This keyboard's touch-layout requests a font-size boost of +40%.)

fix(web): touch-layout fontsize property use ⛲

---

developer/src/kmconvert/Keyman.Developer.System.LdmlKeyboardProjectTemplate.pas
developer/src/tike/project/Keyman.Developer.System.Project.xmlLdmlProjectFile.pas

fix(developer): use keyboard3 tag rather than DTD to identify LDML keyboard xml files 🌱

---

developer/src/kmconvert/Keyman.Developer.System.LdmlKeyboardProjectTemplate.pas

fix(developer): tidy up LDML keyboard project template 🌱

---

core/src/ldml/ldml_markers.cpp
core/tests/unit/ldml/keyboards/k_008_transform_norm-test.xml
core/tests/unit/ldml/keyboards/k_008_transform_norm.xml
core/tests/unit/ldml/test_transforms.cpp

- decomp the 'glued' char before storing in map
For: #10516

feat(core): ldml marker normalization fix 🙀

---

linux/ibus-keyman/src/engine.c

Implements #10353.
- The tests can be be run on any Linux platforms (running with X11). Note that Firefox and Chromium have to be installed from .deb, the snap version won't work because it's missing the ibus patch.
- Install Anki
- Download [Qt5 version of Anki](https://apps.ankiweb.net/#linux)
- Run the following commands
```bash
sudo apt update
sudo apt install zstd
tar xaf Downloads/anki-2.*-linux-qt5.tar.zst
cd anki-2.*-linux-qt5
sudo ./install.sh
sudo apt install libxcb-xinerama0
```
- When testing in Anki, select e.g. "Tools"/"Study Deck"
- Install patched ibus by running these commands:
```
sudo add-apt-repository ppa:keymanapp/keyman-alpha
sudo apt upgrade
```
- afterwards running `dpkg -l ibus` should show a version number with `sil` in the version string, e.g. …

refactor(linux): Use `km_core_actions` struct instead of queue 🌱

---

docs/linux/keyman-config.md
docs/settings/linux/.devcontainer/Dockerfile
linux/debian/changelog
linux/debian/control
linux/keyman-config/keyman_config/downloadkeyboard.py
linux/keyman-config/keyman_config/install_window.py
linux/keyman-config/keyman_config/keyboard_options_view.py
linux/keyman-config/keyman_config/welcome.py

webkitgtk 4.1 is the same API as 4.0 except that it uses libsoup3 instead of libsoup 2.4.
Fedora has [stopped](https://fedoraproject.org/wiki/Changes/Remove_webkit2gtk-4.0_API_Version) building the 4.0 API (in preparation for Fedora 40 in a few months). Debian and Ubuntu will also stop building the 4.0 API soon.
webkitgtk 4.1 should exist in currently mainatained distros. It is in Debian 12, Ubuntu 22.04 LTS, etc.

chore(linux): Build with webkitgtk 4.1 instead of 4.0

---

core/include/keyman/keyman_core_api.h
core/src/action.cpp
core/src/km_core_action_api.cpp
core/tests/unit/kmnkbd/action_api.cpp
core/tests/unit/kmnkbd/action_set_api.cpp
core/tests/unit/kmnkbd/meson.build
core/tests/unit/kmnkbd/test_actions_get_api.cpp
developer/src/tike/main/Keyman.System.KeymanCore.pas

Fixes #10530.
Adds the `deleted_context` member to the `km_core_actions` struct, and associated unit tests. Simplifies integration by providing the consumer with all the data they need in order to execute the transform, specifically around number of delete operations required, without needing to query the target application context again. The number of delete operations will vary according to application compliance and selected encoding; for example a UTF-16 string may require 2 delete-backs for surrogate pairs in the text buffer for a compliant app, whereas there will be a single delete-back key event for a non-compliant app.
The `deleted_context` member should also be used for debug assertions.

feat(core): add `deleted_context` to `km_core_actions` struct 🌱

---

linux/ibus-keyman/src/engine.c

chore(core): `process_output_action` needs const `output_utf32` parameter 🌱

---

linux/debian/rules
linux/ibus-keyman/meson.build
linux/ibus-keyman/meson_options.txt
linux/ibus-keyman/src/engine.c
linux/ibus-keyman/tests/ibusimcontext.c

When building packages warnings are treated as errors. When building on Ubuntu and Debian servers we don't have a patched ibus version but still want to build the packages. So this change outputs a message instead of a warning when building packages.

fix(linux): packaging on Ubuntu and Debian servers should give message instead of warning because we don't have patched ibus there

---

web/src/engine/dom-utils/src/stylesheets.ts
web/src/engine/osk/src/visualKeyboard.ts

Enhances the `Promise` setup used to await OSK resource loading to also properly wait for a keyboard's fonts to load.
Rather than use techniques from KMW's past, I've instead utilized a (comparatively) newer Web feature:  [`FontFace`](https://developer.mozilla.org/en-US/docs/Web/API/FontFace).  It's newer than when the setup we _previously_ used was first written, but it's supported on all browser versions KMW currently supports and provides a _much_ cleaner way to achieve the same goals - it even directly provides a Promise for font-loading completion!
This changeset includes a tweak to ensure that there's always a layout-refresh once the keyboard's fonts load; what's small in one font can be large in another, after all.  
This admittedly corresponds better to the original design/logic …

fix(web): OSK resource-loading promise's font-wait ⛲

---

web/src/app/browser/src/keymanEngine.ts
web/src/engine/osk/src/views/oskView.ts
web/src/engine/osk/src/visualKeyboard.ts
web/src/test/manual/web/build-visual-keyboard/index.html

Fixes #10444.  (Covers remaining cases.)
As the keyboard-documentation element structure removes the layer group from the main element of a `VisualKeyboard`, font-size handling requires specialized logic to ensure all relevant bits land in the correct location.
This PR admittedly also includes some specialized handling for one of the documentation-keyboard Web test pages, looking forward to #4881:
- There had been a regression here from 16.0 related to the notes about @font-face within Shadow DOM, causing the fonts to not display properly on the test page.
- Stylesheet management is now better-structured for transition to Shadow DOM hosting.
- Before, if kmwosk.css wasn't properly available within the Shadow DOM setup at the time that the layout-refresh was called, it was possible for …

fix(web): documentation-keyboard font size, font scaling ⛲

---

web/src/engine/osk/src/keyboard-layout/oskKey.ts
web/src/engine/osk/src/views/oskView.ts
web/src/engine/osk/src/visualKeyboard.ts
web/src/resources/osk/kmwosk.css

As noted on #10534, special-key size has some odd CSS that can contribute to bad key scaling in some scenarios:
Granted, this case _is_ pretty extreme... largely because the layout's font-size is set to `4em` - not exactly a conventional multiplier.  But still.
Starting from there, I found a few other oddities that were causing issues; this PR should adequately clean nearly all of them up.
Result after the changes:
- Note that the spacebar's caption has proper vertical centering.
- The special keys no longer overflow the keys' width, while fitting snugly inside.
- While subtle, the key caps are now _truly_ vertically centered - there was actually a small offset at the top preventing this.
- Note the key before backspace - the hint dot hasn't moved, but the main key-cap has.
- …

fix(web): proper await for special-osk font, use of it in key scaling ⛲

---

developer/src/common/web/utils/src/KeymanSentry.ts
developer/src/kmc/src/commands/analyze.ts
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/buildWindowsPackageInstaller/index.ts
developer/src/kmc/src/kmc.ts
developer/src/kmc/src/util/sysexits.ts

Fixes #10488:
1. Use a consistent `exitProcess()` function so that we always wait for Sentry to do its thing.
2. Make `KeymanSentry.isEnabled()` non-async because it is synchronous.
3. Remove duplicate initialization of `KeymanSentry` in kmc.ts.

fix(developer): kmc exit needs to wait for Sentry

---

developer/src/kmc/src/util/calculateSourcePath.ts

Fixes #10542.
The `sourcePath` attribute should only be added to a .keyboard_info file if the file is actually in an expected folder matching a pattern like `(release|legacy|experimental)/k/keyboard`.
If the path does not match that pattern, then we just omit the field in the emitted .keyboard_info or .model_info file.

fix(developer): make sourcePath calculation for kmc-keyboard-info more lenient

---

developer/src/kmc-ldml/src/compiler/compiler.ts

Fixes #10547.
In order to prevent confusion, the stubbed and incomplete .js files generated by the LDML keyboard compiler are no longer emitted for version 17.0 release.

chore(developer): disable .js output for LDML keyboard compiler for 17.0

---

.github/workflows/deb-packaging.yml
linux/.pbuilderrc
linux/scripts/cow.sh
linux/scripts/deb.sh
linux/scripts/launchpad.sh

This change removes Ubuntu 23.04 Lunar and adds support for Ubuntu 24.04 Noble.

chore(linux): Replace Lunar with Noble

---

linux/ibus-keyman/src/test/keymanutil_tests.c

ICU 73 comes with CLDR 43 which contains various corrections. This means that we get different results when we minimize `bmf-Latn`. This change sets the test expectations based on the ICU version and so allows tests to pass on Ubuntu 24.04 which comes with ICU 74.

chore(linux): Adjust test expectations for ICU >= 73

---

developer/src/inst/kmdev.wxs
developer/src/kmc/build.sh
developer/src/kmc/package.json
resources/standards-data/ldml-keyboards/readme.md
resources/standards-data/ldml-keyboards/unicode-license.txt

Fixes #10491.
Called unicode-license.txt in order to disambiguate.
This PR packs the license with kmc, not kmc-ldml for now (even though kmc-ldml is available as a separate npm package). Up for discussion.

chore(developer): add unicode-license.txt for ldml keyboards data

---

core/src/ldml/ldml_markers.cpp
core/src/ldml/ldml_markers.hpp
core/src/ldml/ldml_transforms.cpp
core/tests/unit/ldml/keyboards/k_201_reorder_esk-test.xml
core/tests/unit/ldml/keyboards/k_201_reorder_esk.xml

- reorders don't interact with markers, but must transit them
- add updated tests
- simplify reorder_group::apply(): the 'common prefix' discussion
was out-of-date as std::mismatch is handled by the ldml_processor
and the core context.
- add_back_markers() promoted to SPI so it can be called from reordering.
Fixes: #10516

feat(core): ldml reorder marker processing 🙀 

---

web/src/engine/main/src/keymanEngine.ts

Fixes #8947.
We weren't seeing this on iOS because of a iOS-side `resetContext` call that occurred after the keyboard loads; this only occurs after dismissing the "Get Started" menu within the Android app.
**TEST_ANDROID_GET_STARTED_INIT**:  Using Keyman for Android as a fresh installation, verify that `sil_euro_latin` displays properly at all relevant points of initialization.
1. Remove any previous installation of Keyman.
2. Open Keyman In-App.
3. The Get Started dialog should automatically open.
4. Verify that the keyboard, if visible, is on the `shift` layer and any suggestions have a capital first letter.
5. Dismiss the Get Started dialog. 
6. Verify that the keyboard is (still) on the `shift` layer and any suggestions have a capital first letter.

fix(web): app/webview control flow for initial layer

---

.github/workflows/deb-packaging.yml

- Upgrade upload-artifact to v4.3.0
- Upgrade download-artifact to v4.1.1
- Upgrade checkout to v4.1.1
- Upgrade gha-deb-signing to v0.6
Closes #10385.

chore(linux): Upgrade artifacts to v4

---

resources/build/ci/cancel-builds/cancel-test-builds.mjs
resources/build/ci/cancel-builds/trigger_definitions.mjs
resources/build/run-required-test-builds.sh
resources/build/trigger-definitions.inc.sh

Fixes #10590.
Cancels existing running or queued test builds on TeamCity when a new build is started for the same 'branch' (aka branch or PR).
Does not touch release builds or other projects -- only touches recognized test build configurations.
I'm not sure why this isn't a standard parameter for TeamCity builds, but cannot find anything about it anywhere.

chore(common): cancel earlier builds when new test builds triggered

---

linux/ibus-keyman/src/engine.c

The package build on armhf failed because of the wrong format specifier which expects a `size_t` instead of `glong` that `g_utf8_strlen` returns.

chore(linux): Use correct format specifier for `g_utf8_strlen`

---

linux/ibus-keyman/src/keymanutil.c
linux/ibus-keyman/src/keymanutil_internal.h
linux/ibus-keyman/src/test/keymanutil_tests.c

Implement proper comparison of versions so that 1.10 is newer than 1.9.
Fixes #9593.

fix(linux): Fix version comparison

---

.github/workflows/deb-packaging.yml

With the new download-artifact version when using `merge-multiple:true` all artifacts end up in the same directory. This change adjusts for that.
Another follow-up of #10577.
Fixes #10613.

fix(linux): Fix path to artifacts when uploading to llso

---

linux/.gitignore
linux/scripts/.editorconfig
linux/scripts/deb-packaging.sh
linux/scripts/test/deb-packaging.tests.sh

If lines got removed in the .symbols file we won't find the current version number in the .symbols file. This change fixes the expectations.
Also, if a major API change happens during the Alpha cycle we don't expect another API version increment if one already happened since we released the stable version.
This change also adds some unit tests for the new functionality. These can be run manually and won't run during CI builds.
Fixes #10453.

chore(linux): Fix API check if lines got removed in .symbols file

---

web/src/tools/building/sourcemap-root/index.ts

When inlining a sourcemap, it's important to inline the _map_, not just one narrow field of it.
Not sure how I missed the error back when making and merging #10413, which introduced the inlining code, but at least this should fix it moving forward.

fix(web): app/webview sourcemap inlining

---

windows/src/engine/keyman32/DebugEventTrace.cpp
windows/src/engine/keyman32/k32_dbg.cpp
windows/src/engine/keyman32/keyman32.def
windows/src/engine/keyman32/keymanengine.h
windows/src/engine/kmtip/debug.cpp
windows/src/engine/kmtip/globals.h
windows/src/engine/kmtip/keyman32interface.cpp
windows/src/engine/kmtip/kmtip.h
windows/src/support/etl2log/load.cpp

Fixes #10604.
Introduces the following wide-string macros corresponding to existing macros:
* `SendDebugMessageFormatW`
* `SendDebugMessageW`
External (private use) API added, corresponding to existing private API:
* `Keyman_WriteDebugEventW`
Also includes minimal patch to etl2log to support emitting Unicode characters, in UTF-8.

fix(windows): support unicode strings properly in logs

---

linux/keyman-config/keyman_config/bcp47tag.py

This change fixes a syntax warning with Python 3.12. See https://stackoverflow.com/a/50504635/487503 and
https://docs.python.org/3/whatsnew/3.12.html#other-language-changes.

fix(linux): Use raw string for regex

---

windows/src/engine/keyman32/kmprocess.cpp

Relates to #10604: "Note also wstrtostr crashes if you pass it surrogate pairs because they won't convert ... ouch."

fix(windows): `wstrtostr` should use `WideCharToMultiByte`

---

windows/src/engine/keyman32/kmprocessactions.cpp

renamed a variable for clarity and added a description to make clear that a null-terminated string is the expected input.

chore(windows): rename actionItem to outputString for clarity 

---

common/web/keyboard-processor/src/text/keyboardProcessor.ts
common/web/keyboard-processor/tests/node/specialized-backspace.js

Addresses the core aspect of #10204 on the Web side - the fact that backspaces weren't being passed through when Web sees an empty app-context.
This is also enough to heavily mitigate the main issue; a personal test of the test-artifact from this PR was able to delete the _entirety_ of the following text with a single held backspace.  (Keyman system keyboard, Notes app - just to be clear.)
```
Testing testing one two three one two three
Even more random text typed here. Lots and lots and lots of text. Like, way too much text. I want to trigger a context window, and we're going to make certain of it.
And yeah, another one to be safe. Gonna start within this one, so I can fall back on the last one and see if it triggers across THOSE boundaries. That could totally happen, right?
```
Before, …

fix(web): handling of backspaces when left-context is empty

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift
web/src/app/webview/src/contextManager.ts

Fixes #10204.  Continues from #10584.
While this isn't a 100% perfect fix, it should present a marked improvement in the iOS Keyman app's handling of large-scale text deletion.  That said, there's no reasonably simple way to reach 100% perfection with the interfaces Apple gives us due to the internal mechanisms at play and the limited API.
Known remaining issues:
- When deleting large amounts of text...
- ... within a large paragraph, on rare occasions the keyboard may change layer as if the context were empty, even when it isn't.  
- ... on rare occasions, a backspace may not properly delete a character (for keyboards with scripts in the Unicode SMP range).
- Similarly, keyboard rules with special backspace handling may occasionally not trigger if large amounts of text was deleted …

fix(ios): long-held backspace handling

---

web/src/engine/osk/src/banner/bannerController.ts
web/src/engine/osk/src/banner/suggestionBanner.ts

When I was modularizing KMW (the 🧩 chain during 17.0), the banner was the trickiest thing to disentangle.  As such, I believe that I originally set event-raising structures in place as a potential "way forward" to re-link everything.
As it turns out... we didn't need the event-raising structures _on the banner_ whatsoever.  The `PredictionContext` object (currently within `InputProcessor`, introduced in #8056) is where all the actual event-raising happens, with the banner itself consuming those events.  It does appear the stuff being removed here was _also_ introduced in that PR - it was a large PR, so I probably just didn't realize at the time that I'd already made it redundant.
Then again, it may have only _actually_ become redundant once the gesture rework (🐵) had _also_ landed; before …

chore(web): removes unused banner events

---

linux/ibus-keyman/src/engine.c

If we process keys that have the (Super/Meta/Windows) IBUS_MOD4_MASK modifier set we ignore the key. Core doesn't handle the Meta modifier state and so would treat it as regular key. This fixes switching keyboards in Ubuntu 23.10/24.04 on Wayland.
Fixes #10476.
This should be tested on Ubuntu 23.10 or 24.04 with Wayland with at least one Keyman keyboard installed.
**TEST_SWITCH_KBD**:
- Open a terminal window.
- Press <kbd>Super</kbd><kbd>Space</kbd> to switch to the Keyman keyboard. 
- Press <kbd>Super</kbd><kbd>Space</kbd> again to switch back to the first keyboard
- Verify that the keyboard switch actually happens.

fix(linux): Ignore keys with IBUS_MOD4_MASK set

---

resources/build/build-utils.sh

Previously we didn't detect that we were building a .deb package on Launchpad or a Debian server, so we set VERSION_TAG to end in `-local`. This change now checks the `KEYMAN_PKG_BUILD` environment variable which will be set during .deb package builds (set in `debian/rules`). The downside of this solution is that now `-local` also gets omitted if we build a .deb package on a local dev machine, but that probably doesn't happen too often, and even less often with modified source code. The majority of builds where we want `-local` are local builds that get installed locally, and those cases are covered by this change. And what is more important is that for release builds we no longer append `-local`.
Similar to #9400 but for Debian/Launchpad.

chore(linux): Don't set VERSION_TAG to …-local in .deb packages

---

web/src/resources/osk/kmwosk.css

Fixes #7158.
With the new gesture engine in place, most of the instability has already been handled, but there was one last detail that evaded us until now.  
The explanation is pretty simple, too - touches on banner suggestions would often register against the suggestion text.  We _also_ happened to _replace_ suggestion text _elements_ when updating suggestions.  So, when we swapped out the element that was the main touch target **_before_** the touch-interaction was completed... we'd lose all further touch-event updates for that interaction, causing gestures to go uncompleted.
**TEST_BANNER_RAPID_TOUCH**:  Rapidly touch the predictive-text banner and ensure its behavior remains stable and acts as would be expected.
1. Using the Keyman for Android app...
2. Adjust the Keyboard height to …

fix(web): banner robustness when touched 2+ times at once

---

developer/src/tike/child/UfrmKeymanWizard.pas
developer/src/tike/project/Keyman.Developer.System.Project.kmnProjectFile.pas
developer/src/tike/project/Keyman.Developer.System.Project.kmnProjectFileAction.pas
developer/src/tike/project/Keyman.Developer.UI.Project.kmnProjectFileUI.pas

Fixes #10655.
Fixes #10663.
If a .kmn file had only a .js target, then Keyman Developer would return an empty string for the target (based on .kmx). This meant that the path for the compiler was an empty string, the path for opening the build folder was an empty string.
Refactored the relevant code to simplify the logic a little.
* **TEST_OPEN_BUILD_FOLDER:** Create a new mobile-only keyboard, open the .kmn, compile the keyboard, and then click Open Build Folder in the Build tab. Verify that the correct build folder opens, and that it contains only a .js file.
* **TEST_KEYBOARD_ON_WEB:** Create a new mobile-only keyboard, open the .kmn, compile the keyboard, and then click Test Keyboard on web in the Build tab. Verify that the web test starts, and that you can test the keyboard …

fix(developer): keyboard that targets only web can cause crashes and other problems

---

android/KMEA/app/src/main/java/com/keyman/engine/cloud/impl/CloudLexicalModelMetaDataDownloadCallback.java

For investigating #10673
Currently, the Android app just downloads whatever lexical-model is listed first for a specific language (`lmData.getJSONObject(0)`).
Now that there are two Khmer lexical-models, this updates the Cloud download callback to download all associated lexical-models (should only be a few).
Will fix the UI and banner refresh on separate PR
* **TEST_KHMER_DICTIONARIES** - Verifies both Khmer lexical-models are downloaded.
2. From Keyman settings, install khmer_angkor keyboard
3. Finish the keyboard installation and wait for associated dictionaries to download/install
4. After the dictionaries have installed, on the device turn on Airplane mode (this …

fix(android/engine): Download multiple dictionaries

---

common/windows/cpp/include/registry.h
common/windows/cpp/src/registry.cpp
windows/src/engine/keyman32/keyboardoptions.cpp
windows/src/engine/keyman32/keyboardoptions.h
windows/src/engine/keyman32/kmprocessactions.cpp
windows/src/engine/kmtip/registryw.cpp
windows/src/engine/kmtip/registryw.h
windows/src/test/manual-tests/test_i3619/i3619tip/i3619tip/i3619tip/registryw.cpp
windows/src/test/manual-tests/test_i3619/i3619tip/i3619tip/i3619tip/registryw.h

Updated the call stack to keep a const string for the value parameter being written to the registry.
SaveKeyboardOptionCoretoRegistry calls
IntSaveKeyboardOptionCoretoRegistry which calls
RegistryFullAccess::WriteString which calls
RegSetValueExW, which takes a const data parameter.
* **TEST_PERSITING_OPTIONS**
1. Install k_022___options_with_preset.kmx
2. Open Notepad 
3. Type <kbd>a</kbd> 
4. Expected reasult "no. foo"
5. Type <kbd>1</kbd> 
6. Type <kbd>a</kbd> 
7. Expected reasult "foo"
8. Type <kbd>Win</kbd> +<kbd>r</kbd> 
9. In the run Window type regedit
10. Find the registry key for the k_022___options_with_preset.kmx keyboard under active keyboards\options  veriy that "foo" key is there and the value is `1`.  Full path for the registry key is …

chore(windows): add const to argument definition

---

common/web/gesture-recognizer/src/engine/headless/gestures/matchers/pathMatcher.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/contactModel.ts
web/src/engine/osk/src/input/gestures/specsForLayout.ts

Fixes #10640.
When I put together #10172, I rightly considered how the changes would be affected for standard longpress timeouts... but wrongly forgot to apply the same sort of filtering whenever the longpress up-flick shortcut is executed.  
By making the item-validator a full-on path-model property, rather than a path-model timer-only property, we can validate all finalizations, rather than only timer-based ones.  The same filtering should apply for both cases, after all, so it makes sense as a configurable parameter on its new level.
**TEST_SIMPLE_KEY_UP_FLICK**:
1. Load up the standard "Test unminified Keymanweb" test page while on (or emulating) a mobile device.  (Chrome emulation is fine.)
2. Using the default keyboard ("English")...
3. Press any non-special key.  (For example, the …

fix(web): prevent invalid longpress shortcut triggers

---

linux/keyman-config/keyman_config/get_kmp.py
linux/keyman-config/tests/test_get_kmp.py

If we can't create the cache dir, e.g. if `~/.cache` doesn't exist or if we don't have enough permissions, we now return a temporary directory.
Fixes #10033.

fix(linux): Use temp dir if we can't create cache dir

---

common/web/types/src/kmx/element-string.ts
common/web/types/src/kmx/kmx-plus.ts
developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-ldml/src/compiler/messages.ts
developer/src/kmc-ldml/src/compiler/tran.ts
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-bad-reorder.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-bad-tran-1.xml
developer/src/kmc-ldml/test/test-tran.ts

- also, make sure NFD-incompliant ranges get mapped to escaped chars
- also, propagate UnicodeSet errs out
For: #10389

feat(developer): errs on unparseable regex 🙀

---

HISTORY.md

I was updating 17.0 release notes in the wiki and noticed a ton of missing PR titles in our HISTORY.md.
Haven't chased down why the nightly history-utils.sh script sporadically fails to get the titles

docs(common): Fill in missing HISTORY.md entries

---

resources/build/version/src/fixupHistory.ts
resources/build/version/src/index.ts

Fixes #10721.
This arose partly because of the change from release- to release@ in at 17.0.30-alpha (triggered by sentry req). Will require a corresponding patch to CI script to pass the --from and --to parameters.

chore: workaround release inc build block

---

resources/build/increment-version.sh

chore: add from and to params to increment-version

---

web/src/engine/osk/src/banner/suggestionBanner.ts

Fixes #10694.
When no suggestions are available, the banner should be non-interactive.  However, at present (17.0.265), you can select an "empty suggestion".  This can lead to other unintended interactions, such as #10642, and feels a bit unpolished - it _is_ weird to "select nothing" and have that be acknowledged.
TEST_NO_SUGGESTIONS:  Using the Android test artifact, verify that the banner is not interactive when no suggestions are present.
- Suggested keyboard: EuroLatin (SIL)
- Simply type a long bit of random text until no suggestions are available, then try to interact with the banner.
- When touching a suggestion, drag your finger side to side for a bit, then up and down for a bit. 
- If any part of the banner highlights during the attempted interaction, FAIL this test.
- If any …

fix(web): disables banner interaction when suggestions are absent

---

web/src/engine/osk/src/input/gestures/specsForLayout.ts

Fixes #10640.
The model-validation function for longpresses wasn't specified properly; it is supposed to validate based on the touch's _base_ key, not most recent key underneath the finger.  It is possible for the two to differ on lower-performance devices, as confirmed by https://github.com/keymanapp/keyman/issues/10640#issuecomment-1943080633.
TEST_SPACEBAR_UP_FLICK:  Using the Keyman for Android app (emulated or otherwise), ensure that no errors occur when dragging a touch rapidly from the spacebar to the banner.
1. Type a long word, such that there are no suggestions available in the banner. 
2. Starting a touch on the space bar, drag your finger from the space bar to the suggestion banner in different directions.
3. If any error notifications pop up, FAIL this test.
4. Do _not_ fail …

fix(web): longpress validation by base key, not current location

---

web/src/engine/osk/src/visualKeyboard.ts

Fixes #10687.
Fixes #10703.
TEST_STICKY_SPECIAL_HIGHLIGHTS:  Verify that special key highlighting is no longer 'sticky'.
1. Using the EuroLatin (SIL) keyboard within the Keyman for Android app...
2. Start a touch on the space bar...
3. ...and drag it over the globe and shift keys before reaching the banner leaves those keys highlighted.
4. Verify that no keys are highlighted at the end of this sequence.
5. Verify that there was no point in time where two keys were simultaneously highlighted.

fix(web): sticky special-key highlighting

---

web/src/engine/osk/src/input/gestures/specsForLayout.ts

Fixes #10742.
I'm not sure it's the _ideal_ solution, as it does cause such keys to behave noticeably different from layer-switch keys without subkeys... but it does resolve the main issue in which certain parts of the keyboard became wholly inaccessible.
If naught else, that caveat is simply one more push toward not designing longpresses on layer-switch keys.

fix(web): disables modipress for layer-switch keys with subkeys

---

web/src/app/browser/src/contextManager.ts
web/src/engine/main/src/keymanEngine.ts
web/src/test/manual/web/index.html
web/src/test/manual/web/init-race-10743/index.html

Fixes #10743.
It was possible for a user to experience a race condition against KMW's initialization process if they attempted to start typing too quickly.  While we won't defer keystrokes that occur before initialization, we can at least prevent them from triggering errors.
TEST_MAIN:  Using the new "Test page interaction + engine-initialization race condition handling (#10743)" KeymanWeb test page, verify that the OSK displays under the following condition:
1. Go to the new "Test page interaction + engine-initialization race condition handling (#10743)" KeymanWeb test page on a desktop device.
2. Quickly select either of the two first text-accepting page elements ("Type here", "or here")
3. Type random text for at least 10 seconds.  Do not change to a different element or press TAB.
4. …

fix(web): handling of page-elements focused before engine initialization

---

docs/websites/README.md

Now that the Keyman websites have migrated from IIS to Apache, this does some minor cleanup of the websites/README.md.

docs(common): Update website README

---

web/src/resources/osk/kmwosk.css

Fixes #10755
Back in #4153 the Android tablet OSK styling was changed to match the phone OSK styling.
To fix the tablet suggestion banner contrast, this PR changes the tablet suggestion banner styling to match the phone.
**Setup** - Install the PR build of Keyman for Android and a tablet emulator/device
* **TEST_TABLET_BANNER** - Verifies tablet suggestion banner text is visible
2. Verify the default English suggestion banner shows black background and white text
3. Press and hold a suggestion
4. Verify the touched suggestion has a gray background with white text

fix(android): Match phone suggestion banner styling on tablet

---

developer/src/kmc-ldml/src/compiler/disp.ts
developer/src/kmc-ldml/src/compiler/keys.ts
developer/src/kmc-ldml/src/compiler/substitution-tracker.ts
developer/src/kmc-ldml/src/compiler/tran.ts
developer/src/kmc-ldml/src/compiler/vars.ts
developer/src/kmc-ldml/test/fixtures/sections/disp/invalid-var.xml
developer/src/kmc-ldml/test/fixtures/sections/keys/invalid-undefined-var-1.xml
developer/src/kmc-ldml/test/fixtures/sections/keys/invalid-undefined-var-1b.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-missing-var-1.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-missing-var-2.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-missing-var-3.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-missing-var-4.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-missing-var-5.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-missing-var-6.xml
developer/src/kmc-ldml/test/test-disp.ts
developer/src/kmc-ldml/test/test-keys.ts
developer/src/kmc-ldml/test/test-tran.ts

Fixes #10731
- renamed MarkerTracker to SubstitutionTracker - with an expanded role
- tests for missing variables
- fixes for tests for missing variables

fix(developer): missing variables tests. everywhere. 🙀 

---

developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewProject.dfm

fix(developer): prevent renaming of new project types in New Project dialog

---

developer/src/kmc/src/commands/buildTestData/index.ts

Fixes #10752.
Also removes `console.log()` call and replaces with appropriate call to `callbacks.reportMessage()`.

fix(developer): return an error code if build-test-data fails

---

developer/src/inst/node/kmc.cmd

Fixes #10751.
* **TEST_DEBUGGER:** Try to debug a keyboard in Keyman Developer, in the same way as described in #10751. The debugger should start without the error now.

fix(developer): allow more parameters in kmc.cmd

---

linux/debian/libkeymancore.symbols

The new API methods landed in `master` with the merge of the epic branch. This change updates the version numbers to the current version.
Closes #10567.

chore(linux): Update symbols file with current version 🏥

---

.github/workflows/deb-packaging.yml

This change adds the `isTestBuild` flag to the workflow title to make it easier to find the release builds.

chore(linux): Add testbuild info to workflow title

---

linux/scripts/debian.sh

We want `EXTRA_ARGS` to be split so that we end up with different arguments.

chore(linux): Fix `debian.sh` by removing quotes

---

developer/src/tike/main/UfrmMessages.pas
developer/src/tike/project/Keyman.Developer.System.Project.ProjectLog.pas

Fixes #10546.
Format compiler messages in the same way as kmc, and match the colors from kmc's console log messages.
* **TEST_MESSAGE_FORMATTING**: Compile a keyboard, and examine the message pane to verify that the colors and formatting of the messages correspond to the image below of kmc's output (the exact messages may be different, but the messages should look similar in style and format).

fix(developer): match kmc console formatting for messages in IDE

---

common/test/keyboards/invalid/README.md
developer/src/common/include/kmn_compiler_errors.h
developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
developer/src/kmc/src/util/NodeCompilerCallbacks.ts
developer/src/kmcmplib/src/CompMsg.cpp

Fixes #10678.
Some messages have been reduced to ERROR instead of FATAL, as they are not internal compiler errors.
Where fatal messages are raised, the message will now be reported through correctly to Sentry.

fix(developer): ensure fatal errors report message or made non-fatal

---

developer/src/tike/actions/dmActionsKeyboardEditor.pas
developer/src/tike/child/Keyman.Developer.UI.UfrmLdmlKeyboardEditor.pas

fix(developer): reset debugger after ldml keyboard compile

---

developer/src/tike/project/Keyman.Developer.System.Project.ProjectFile.pas

Fixes #10684.
If a project .kpj file was not saved in UTF-8 or ANSI, or had a BOM, then Keyman Developer would crash with an access violation due to an uninitialized variable.

fix(developer): crash opening invalid project

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardWebViewClient.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/KMEA/app/src/main/java/com/keyman/engine/data/KeyboardController.java

Fixes #7712
The 4 sets of Sentry reports stem from the following scenario (obscure)
1. User installs Keyman (but doesn't launch the app). Hence, sil_euro_latin never gets "added" (done in MainActivity)
2. From the Android settings --> Languages menus, the user enables Keyman as a system keyboard
3. User then attempts to use Keyman as a keyboard
4. SystemKeyboard initializes (--> KMManger.initialize() which extracts sil_euro_latin.kmp so it can be "used). Since the keyboard sees no keyboards installed (index is -1), we get a bunch of Sentry reports from attempting to fallback.
This PR quiets the Sentry noise so we only log if the key is **not** for the default sil_euro_latin keyboard.
**Setup** - This involves modifying Android Studio configuration so the IDE will install the PR build of …

fix(android/engine): Remove logs for uninitialized default keyboard

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/CheckInstallReferrer.java

Fixes #10762 
We're not using Install referrer details in Sentry, so remove logging

chore(android/app): Remove logging for install referrer details

---

common/web/sentry-manager/src/index.ts

To facilitate Sentry's efforts in lining up our sourcemaps with the KMW bundled inside our mobile apps, part of our setup "chops off" nearly all of the scripts' actual paths... assuming the filename matches certain expected values.  I just happened to notice that this was never updated to include the ES5 versions of KMW.  (The ES6 versions inherited the original filenames.)

chore(web): proper reporting of errors from es5 KMW

---

android/KMEA/app/src/main/assets/android-host.js

After the changes made in #10728, it appears that the _first_ keystroke entered via the keyboard on Android may sometimes be ignored - specifically if the context is also empty at the time.  It's a simple fix, fortunately - there's no harm in resetting the context when it is empty, after all.

fix(android): first keystroke when context is empty

---

core/meson.build
developer/src/tike/Makefile

Fixes #10737.
Two parts to this: first, Keyman Core release build needs to generate the .pdb file, and second, the build needs to put it and the .dll into a place where the sentry-cli scan will find it.

fix(developer): publish keymancore-1.dll symbols

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Fixes #9456
By removing the intent flag [FLAG_ACTIVITY_CLEAR_TASK](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_CLEAR_TASK), this fixes the issue of the keyboard picker clearing the previous task. Hence, the keyboard search within the Keyman app isn't cleared. (in the reported issue)
**Setup** - Install the PR build of Keyman for Android on an Android device/emulator
* **TEST_KEYBOARD_PICKER** - Verifies keyboard picker menu doesn't clear the previous task
1. Open Keyman app
2. Set Keyman as the system-wide keyboard and default keyboard.
3. Click 'Install Keyboard or Dictionary' option from the Settings menu.
4. Click 'Install from keyman.com' option.
5. Click the Search bar to enter a keyboard name.
6. Long press the 'globe key' from the keyman keyboard …

fix(android/engine): Fix how keyboard picker menu exits

---

linux/scripts/deb-packaging.sh
linux/scripts/test/deb-packaging.tests.sh

Due to Debian policy the `libkeymancore` package will now include the `SONAME` (API version number) in the package name (PR #10800). This change adjusts the API verification checks to be able to cope with the modified .symbols file.

chore(linux): Fix API verification after adding SONAME

---

docs/linux/packaging.md

The previous command failed if there was more than one *.dsc file. This change now uses the one with the highest version number.

docs(linux): Update how to build binary package with docker

---

.github/workflows/deb-packaging.yml

The autopkgtests run on Debian servers after building a package on Debian. Until now we didn't notice test failures until we uploaded a source package to Debian. This change adds the autopkg tests to the packaging GHA so they run regularly.

chore(linux): Add running autopkgtests on GHA

---

linux/debian/tests/test-build

Recent changes removed the `km_core_context` struct which caused the autopkg tests to fail.

chore(linux): Fix autopkg tests

---

.github/workflows/deb-packaging.yml

Turns out this doesn't work with gha the way I thought it would. I'll add a working solution, but in order not to keep the builds broken I'll disable the autopkg tests until then.

chore(linux): Temporarily disable autopkgtests gha

---

windows/src/desktop/help/about/whatsnew.md

Fixes: #10717  
Added two points for what is new in version 17.0 of Keyman for Windows.
@mcdurdin or @darcywong00 is this the correct repo for Windows help files still after the big migration?

docs(windows): add whats new Keyman for Windows  17.0

---

common/web/types/src/main.ts
developer/src/common/web/utils/index.ts
developer/src/common/web/utils/src/osk.ts
developer/src/kmc-analyze/package.json
developer/src/kmc-analyze/src/osk-character-use/index.ts
developer/src/kmc-analyze/src/osk-rewrite-pua/index.ts
developer/src/kmc-analyze/tsconfig.json
developer/src/kmc-kmn/package.json
developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-kmn/src/kmw-compiler/validate-layout-file.ts
developer/src/kmc-kmn/tsconfig.json
package-lock.json

This module is used only by Keyman Developer compiler. It was originally in common-types because we didn't have a shared module for Developer.
Moving it to @keymanapp/developer-utils in order to improve its documentation.

refactor(developer): move osk module from common-types to developer-utils 📚

---

common/web/types/src/util/compiler-interfaces.ts
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/messages/infrastructureMessages.ts

Fixes #10396.
Instead of `--message 20ae 5006`, which is ambiguous, because 5006 could be a filename, you must now specify the parameter option flag each time: `--message 20ae --message 5006` (or `-m 20ae -m 5006`).
Turns out this is documented as an example in Commander, just not very visible.
Should we also support `-m 20ae,5006`? This would be a fairly straightforward tweak.

fix(developer): repeated options in kmc must now be fully specified

---

linux/help/about/whatsnew.md

docs(linux): Updated whatsnew for Keyman for Linux 17

---

android/KMEA/app/src/main/assets/android-host.js
web/src/app/webview/src/contextManager.ts

Heavily mitigates #10835. In particular, this outright _fixes_ the increased frequency with which the error happens in 17.0-beta.  
Alas, as the increased frequency can be traced to a recent PR, this likely does not fix the long-running cause behind the pre-17.0 Sentry reports.  It does fix all of our current known repros.
To be precise, the increased frequency of the bug with 17.0-beta can be traced to changes made in #10728.  KMW gained a new context-synchronization method now used by iOS - a method which includes saving a snapshot of the context and comparing against it at later points.  
**That 'snapshot' aspect was _not_ integrated into the codepath for the original sync method**, which is still used by Android; as a result, when the caret is moved, that snapshot doesn't get updated …

fix(web): context save-state on reset

---

android/KMEA/app/src/main/java/com/keyman/engine/cloud/impl/CloudLexicalPackageDownloadCallback.java
android/KMEA/app/src/main/java/com/keyman/engine/logic/ResourcesUpdateTool.java
android/KMEA/app/src/main/res/values/strings.xml

Fixes #10812
Per user request, remove remove Toast notifications for:
* Dictionary download is finished
* Resources successfully updated
This reduces the noise when installing a keyboard+dictionary set.
**TEST_LESS_TOASTS** - Verifies only 2 Toasts seen (previously 4)
2. On the "Get Started" menu --> "Add a keyboard for your language" --> "Install from keyman.com" --> search for khmer_angkor and install
3. Observe Toast notifications are displayed when 
* khmer_angkor keyboard is done installing
* Download of Khmer dictionary started in the background
4. Verify Toasts do **not** appear for
* Dictionary download is finished
* Resources successfully updated

chore(android/engine): Reduce toast notifications after installations

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java

For investigation of #10835
Currently the Keyman Android context gets out of sync with KeymanWeb when the cursor is moved. This causes [charSequence.subSequence()](https://developer.android.com/reference/java/lang/CharSequence#subSequence(int,%20int)) to throw IndexOutOfBoundsException when:
* start or end are negative
* end is greater than length()
* start > end
This adds checks so I can continue to investigate why the selection gets out of sync.
Note, for now it's logged to Sentry, which causes the errors to appear as Toast notifications. I'm not sure we want a full confirmation dialog to appear each time this happens...
**Setup** - Install the PR build of Keyman for Android on an Android device/emulator.
* **TEST_INAPP** - Verifies inapp keyboard doesn't crash
1. Start Keyman and …

fix(android/engine): Check selection indexes

---

linux/debian/changelog
linux/debian/control
linux/debian/tests/control
linux/debian/tests/test-build

This change adds `libicu-dev` as a dependency for `libkeymancore-dev`. While it is possible to dynamically build without ICU it is required when doing a static build.
Closes #10864 and [Debian bug #1064915](
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064915).

fix(linux): Fix libkeymancore-dev dependencies

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Fixes [an issue](https://github.com/keymanapp/keyman/pull/10873#issuecomment-1968522738) noted while validating #10873.
This change prevents backspaces and context-deletions from keyboard rules from mishandling the context after moving the text insertion point and/or selecting text.
Recent changes to the codebase have resulted in a need to consistently specify selection ranges with non-BMP indexing.  #10662 recognized the need to keep non-BMP processing enabled as part of a different Android bug fix, and #10728 took things a bit further (for iOS) while further validating this position.  Until now... we missed that Android was actually specifying the selection range with code _unit_ (BMP) indexing, which does not account for surrogate pairs.
TEST_POST_EMOJI_ROTATION:   
1. Go to …

fix(android): handle surrogate pairs in selection range indexing

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift

Fixes #10761.
Turns out my concerns in that issue were well-founded; rules crossing a context-window boundary were not being properly applied.  Fortunately, it only takes a couple of small tweaks to fix that... as well as can be done under iOS constraints given 17.0.
Limitations:
- If a surrogate pair exists out-of-context that would be deleted by such a rule, an extra character will be deleted.
- If a combining character exists out-of-context that would be deleted by such a rule, an extra character will be deleted.
To "do better" would require us to track our own version of a context window manually on the iOS side that slides, rather than "jumping" upon a new paragraph start.  _**This**_ is only an idea at this stage, though; it's also certainly too big a project to tackle during the …

fix(ios): cross-paragraph keyboard rules

---

developer/src/kmc/build.sh
resources/build/help-keyman-com.sh

Fixes #10889.
This involved a bit more refactoring to help-keyman-com.sh in order to allow for multiple paths to be uploaded.
I opted _not_ to move the entire Keyman Developer documentation into this repository, partly because a number of pages are still in PHP rather than Markdown.

chore(developer): deploy compiler messages to help site

---

developer/src/tike/xml/layoutbuilder/builder.js

Fixes #10372.
* **TEST_HINT_TEXT:** In the touch layout editor, add a special hint text to a key, such as `*Shift*`, and verify that the hint displays as the Shift icon, not the text.

fix(developer): hint text special characters

---

developer/docs/api/etc/kmc-analyze.api.md
developer/docs/api/etc/kmc-keyboard-info.api.md
developer/docs/api/etc/kmc-kmn.api.md
developer/docs/api/etc/kmc-ldml.api.md
developer/docs/api/etc/kmc-model-info.api.md
developer/src/kmc-kmn/src/compiler/compiler.ts
developer/src/kmc-kmn/src/kmw-compiler/kmw-compiler-messages.ts
developer/src/kmc-ldml/src/compiler/compiler.ts
developer/src/kmc-ldml/src/compiler/ldml-compiler-options.ts
developer/src/kmc-ldml/src/compiler/messages.ts
developer/src/kmc-ldml/src/main.ts

Relates to #10207.
Note: reduces the API surface by removing members which should be internal. Fixes a few minor typos in other API docs. Adds missing docs for kmc-kmn also.

docs(developer): kmc-ldml api documentation

---

developer/src/common/web/utils/index.ts
developer/src/common/web/utils/src/keyman-urls.ts
developer/src/kmc-analyze/src/messages.ts
developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts
developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
developer/src/kmc-model-info/src/model-info-compiler.ts
developer/src/kmc/src/commands/messageCommand.ts
developer/src/server/src/handlers/inc/packages-json.ts

Establishes keyman-urls.ts as a single place for any links to external websites.
I searched all .ts files in Keyman Developer source and replaced references to websites with function calls here. Note that the names of individual functions within this class can be easily changed as needed, as the hard part was the consolidation.

chore(developer): consolidate external links in Developer messages

---

developer/src/kmc/src/commands/messageCommand.ts

Triggered failure seen in https://github.com/keymanapp/help.keyman.com/pull/1085.

fix(developer): message export filename was title case

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java
android/KMEA/app/src/main/java/com/keyman/engine/util/CharSequenceUtil.java
android/KMEA/app/src/test/java/com/keyman/engine/util/CharSequenceUtilTest.java

Fixes #10776.
Backspaces leading up to a heavily-repeated character in the context will no longer replicate the repeated character.  Backspacing the last instance of that character will also function as expected, rather than being blocked.
The method being updated here was tailored to resolve a specialized bug in older versions of Chrome - as such, there is notable potential for regression of #2250.  (Thanks, `git blame`!)  I've made sure to include its original user test as part of the testing suite specified below.  The original test keyboard from back then has been overwritten, but I've reconstructed it from scratch and found it quite useful in getting everything "just right" here.
This PR has a dedicated test keyboard.  It may be downloaded from https://jahorton.github.io/ - you want …

fix(android): fixes context-change detection for repeated-char cases

---

developer/src/kmc-model/src/model-defaults.ts

Noted this one while working on https://github.com/keymanapp/lexical-models/pull/244.
Should a single word contain multiple directional quotes and/or apostrophes, all should be corrected - not just the first.

fix(developer): search-term quote replacement was not global

---

developer/src/kmc-ldml/src/compiler/tran.ts
developer/src/kmc-ldml/test/fixtures/sections/tran/tran-escape.xml
developer/src/kmc-ldml/test/test-tran.ts

- check for user-produced \uXXXX errors BEFORE we actually (re)introduce \uXXXX into the stream
Fixes: #10937

fix(developer): fix for errant \uXXXX error

---

developer/src/kmc-ldml/test/helpers/index.ts
developer/src/kmc-ldml/test/test-helpers.ts
developer/src/kmc-ldml/test/test-tran.ts

Fixes: feat(developer): tests CompilerMessage  matching should be loose #10943
(also gets us working on Node 20)

fix(developer): support loose match for CompilerEvents

---

oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/DefaultLanguageResource.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Follows #10794 and applies it for FV Android app - addresses some of the instances for Sentry crashes in #7412
If users use the Android settings to enable (FV) as a system keyboard without adding keyboards through the FV app, 
it could create a scenario where the Javascript file isn't available
Similar to tests from #10794
**Setup** - This involves modifying Android Studio configuration so the IDE will install the PR build of Keyman for Android, without launching the app.
1. From Android Studio --> Run --> Edit Configurations
2. In the Run/Debug Configurations dialog, change "Launch Options --> Launch" dropdown from "Default Activity" to "Nothing". 
3. **For each test** on an Android device/emulator, do a clean install of the PR build of FirstVoices for Android. (If FirstVoices was …

refactor(oem/fv/android): Install fallback keyboard

---

android/KMAPro/kMAPro/src/main/AndroidManifest.xml
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/CheckPermissions.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMAPro/kMAPro/src/main/res/values/strings.xml

Relates to #10659
Android keeps limiting how external storage permissions are granted, which breaks how we currently use READ_EXTERNAL_STORAGE 
Per the documentation,
> Starting in API level 33, this permission has no effect:
https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE
This PR refactors the current permission checks out of MainActivity. There's still remaining TODO's on getting them to work for Android 12.0+
For now, the alert prompt is updated to try installing the KMP from Keyman Settings - Install from local file
**Setup** - Install the PR build of Keyman for Android for the specified Android version on a device/emulator. For each test, also have downloaded khmer_angkor.kmp locally (usually in the Downloads folder). Download from …

refactor(android/app): Move storage permission checks

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js

Fixes #10847.
This PR ensures that the banner displays consistently when it is supposed to do so, and in its intended manner.  The image banner should no longer be distorted or smaller than intended at any time.
**TEST_SYSTEM_KBD**:  Attempt to reproduce the errors documented in #10847 and verify that they are now fixed.
1. Install this PR's test artifact.
2. Open Keyman In-app. 
3. Download and Install sil_ipa or any other keyboard that does not have a dictionary feature. 
4. Enable as a system-wide keyboard. 
5. Open any browser. 
6. Change the Orientation into Landscape. 
7. Long the press the globe key. Switch Keyman Keyboard. 
8. Switch to sil_ipa keyboard.

fix(ios): delayed banner

---

web/src/engine/osk/src/visualKeyboard.ts

Fixes #10658.
**TEST_IOS_IN_APP**: Using the Keyman app on an iOS device, verify that a keyboard's globe key is highlighted when touched and de-highlighted after interactions with the language-picker are complete.

fix(web): globe key highlighting

---

ios/samples/KMSample1/KMSample1.xcodeproj/project.pbxproj
ios/samples/KMSample1/KMSample1/ViewController.swift
ios/samples/KMSample2/KMSample2.xcodeproj/project.pbxproj
ios/samples/KMSample2/KMSample2/ViewController.swift
ios/tools/prepRelease.sh

Changed the script responsible for creating the ios sample app zip file so that the sample apps will find their frameworks and build successfully.
fixes #10844 

fix(ios): changed build script prepRelease to fix sample builds 🏠

---

developer/src/tike/child/UfrmDebug.pas

Fixes #10915.
Note that a more systemic fix to keyman core will involve ensuring that the debug list is always properly terminated, but that does not need to happen in beta.
* **TEST_DEBUG_MODIFIERS:** In the Keyman Developer integrated debugger, verify that _none_ of the keys on the keyboard cause Keyman Developer to crash as shown in #10915.

fix(developer): Treat Right Shift as Shift in debugger

---

developer/docs/api/etc/kmc-package.api.md
developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/package-compiler-messages.ts
developer/src/kmc-package/src/compiler/package-validation.ts
developer/src/kmc-package/src/compiler/windows-package-installer-compiler.ts
developer/src/kmc-package/src/main.ts

Relates to #10207 (hopefully final PR)
Note: WindowsPackageInstallerSources fields are not yet documented. I may try and do this at a later time, low priority because it won't be widely used.

docs(developer): kmc-package api documentation

---

windows/src/desktop/kmshell/install/Keyman.Configuration.System.TIPMaintenance.pas

fixes: #10793 
1. Install Keyman for Windows from this PR build
2. Install the BJCreeUNI keyboard
3. Open a command prompt and change to the path of kmshell.exe. 
`cd %ProgramFiles(x86)%\Keyman\Keyman Desktop`
4. Type: `kmshell.exe  -s -ikl bj_cree-east crj-Cans-CA` 
Observe that no crash report is generated. Nothing observable should happen. 
Note: the error here is the hyphen in the keyboard id `bj_cree-east` instead of an underscore.
Now test the command still works for valid keyboard ids.
1. Install Keyman for Windows from this PR build
2. Install the BJCreeUNI keyboard
3. Open a command prompt and change to the path of kmshell.exe. 
`cd %ProgramFiles(x86)%\Keyman\Keyman Desktop`
4. Type: `kmshell.exe  -s -ikl bj_cree_east crj-Cans-CA` 
5. Observe that no crash report is generated. …

fix(windows): GetKeyboardLanguage exits early on an invalid keyboard ID 

---

web/src/resources/osk/kmwosk.css

I found the hints too hard to see on my phone, so this ~~increases size of the hint from 0.5em to 0.75em, and~~ changes color from #aaa to ~~#ccc~~ #eee, on Android.
Font size changes rolled back, because they overlapped with base char on small key sizes. Can be more creative in future versions.

chore(web): improve the clarity of hints on OSK for Android

---

android/help/about/index.md
android/help/about/privacy.md
android/help/index.md

This is an attempt to sate the Play Store data policy
https://support.google.com/googleplay/android-developer/answer/10144311#safetysection
* Developer information and a privacy point of contact or a mechanism to submit inquiries.
* Disclosing the types of personal and sensitive user data your app accesses, collects, uses, and shares; and any parties with which any personal or sensitive user data is shared.
* Secure data handling procedures for personal and sensitive user data.
* The developer’s data retention and deletion policy.
* Clear labeling as a privacy policy (for example, listed as “privacy policy” in title).
When this merges back to master, the link will also be available at
https://help.keyman.com/products/android/current-version/about/privacy
**Setup** - Install the PR build …

docs(android/app): Add data privacy policy page

---

common/web/types/src/kmx/kmx-builder.ts
developer/src/kmc-ldml/test/fixtures/basic.txt

fix(developer): min Keyman version for LDML is 17.0

---

resources/build/test/debug-deps/child/build.sh
resources/build/test/debug-deps/child/dep/build.sh
resources/build/test/debug-deps/dep/build.sh
resources/build/test/debug-deps/test.sh
resources/build/test/test.sh

Fixes #10957. The builder --debug flag appears to be passed correctly, according to this test. This is a good test to keep, so won't remove it, but there is something else going on in the base #10953 PR.

fix(common): add unit test for --debug flag for builder

---

ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js
web/src/app/webview/src/contextManager.ts

Fixes corrections and predictions after recently-typed paragraph breaks.
So... I forgot to properly remap the selection-range coordinates when updating the internal web-engine's context across paragraph boundaries in #10728.  Fortunately, the mapping calculations are pretty simple - we only avoid resetting context if there's a very specific relation between the old and new left-hand contexts, after all.
To easily navigate to this page from a mobile device:
Sample text:
```
Almost half of all people in the world today speak an Indo-European language.
Over the last couple of hundred years, linguists have figured out a lot about the first Indo-European language including many
```
**TEST_NEW_PARAGRAPH_PREDICTIONS**:  Using the sample text specified above as existing context, verify that …

fix(ios): selection range sync for long contexts

---

oem/firstvoices/keyboards.csv

The FV folks have been busy and the keyboards.csv we're using to build the mobile FV apps is out of date on keyboard versions. (Some language tags have been simplified too - using the first listed language tag).
This is from running /oem/firstvoices/common/build_csv_languages.sh

chore(oem/fv): Update keyboard versions in keyboards.csv

---

common/windows/delphi/packages/PackageInfo.pas

Fixes #11002.
The fields `<RelatedPackages/>` and `<Examples/>` should not be emitted if they have no content, to improve file backward-compatibility.

fix(developer): suppress emission of new empty fields in package editor

---

developer/src/kmc/src/commands/analyze.ts
developer/src/kmc/src/commands/build.ts
developer/src/kmc/src/commands/buildWindowsPackageInstaller/index.ts

Because exitProcess is async, static analysis of the function does not show process termination, even though it returns `Promise<Never>`. This can lead to compiler warnings when it gets confused about missing return values. So have moved to always returning the value from exitProcess, even though it will never actually return!

fix(developer): return after calling await exitProcess

---

android/KMAPro/kMAPro/src/main/res/values-fr-rFR/strings.xml
android/KMEA/app/src/main/res/values-fr-rFR/strings.xml
windows/src/desktop/kmshell/locale/fr/strings.xml

@MattGyverLee raised an issue on Crowdin to update one of the Windows French strings.
The Crowdin CLI also pulled in the filler string on Android.

chore(android,windows): Update crowdin strings for French

---

HISTORY.md

We haven't investigated the cause of issue #10351 yet, so this is a manual update to fix missing entries in HISTORy.md

chore(common): Fix missing entries in HISTORY.md

---

developer/src/tike/child/Keyman.Developer.UI.Debug.UfrmLdmlKeyboardDebug.pas
developer/src/tike/child/UfrmDebug.pas

Fixes #11036.
Also removes unused function ShortcutDisabled from both debuggers, to avoid confusion.

fix(developer): capture alt shortcuts in LDML keyboard debugger

---

developer/src/tike/child/Keyman.Developer.UI.UfrmLdmlKeyboardEditor.pas
developer/src/tike/help/Keyman.Developer.System.HelpTopics.pas
developer/src/tike/main/UframeTextEditor.pas
developer/src/tike/project/Keyman.Developer.UI.Project.UfrmNewLDMLKeyboardProjectParameters.pas

Fixes #10550.
Also fixes an inadvertent issue where F1 was not opening context help in the text editor anywhere in Keyman Developer. This means that pressing F1 while a keyword is highlighted in a .kmn keyboard will not re-open the context help for that keyword once more (yay!)
Wait for keymanapp/help.keyman.com#1090 to be merged before doing this test.
* TEST_NEW_PROJECT_HELP: In the New Project, New LDML Keyboard Project window, press F1. The help for the window should open in your browser.
* TEST_LDML_EDITOR_HELP: Open an LDML XML keyboard and press F1. The help for the LDML editor window should open in your browser.
* TEST_LDML_DEBUGGER_HELP: Open an LDML XML keyboard, compile and start testing (F5) and press F1. The help for the LDML debug window should open in your browser.
* …

docs(developer): add help site links

---

developer/src/kmc-model/src/build-trie.ts
developer/src/kmc-model/test/fixtures/example.qaa.wordlist-ordering/example.qaa.wordlist-ordering.model.ts
developer/src/kmc-model/test/fixtures/example.qaa.wordlist-ordering/wordlist.tsv
developer/src/kmc-model/test/test-compile-trie.ts

Fixes #11073.
This fixes an issue where less-frequent words that match the start of higher-frequency words were inaccessible to the predictive-text engine and thus could never be suggested.  This effectively suggested to users that the word doesn't exist, which is certainly less than ideal when spelling assistance is desired.  Also, this is something that would certainly affect auto-correction efforts if and when the time comes.
A unit test is included.  The first commit (with the unit test) fails CI checks with 17.0.294-beta's current state and passes with the fix included (commit 2).
**Note**:  as this is a compiler bug, _all_ models will likely need recompilation so that they may receive the fix's effects.
**TEST_MTNT_THIN**:  Using the Keyman Developer test artifact, recompile the …

fix(developer): in model compiler, give correct key to shorter prefix words when a longer, higher-frequency word is also present

---

oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/DefaultLanguageResource.java

Fixes #11079 - Checks no keyboards are installed before installing the fallback keyboard.
**Setup** - Install the PR build of FV for Android on a device/emulator
* **TEST_FV** - Verifies extra EuroLatin keyboard isn't installed
1. Launch FV for Android
2. From the FV setup, add the keyboard BC --> BC Coast --> Sencoten
3. From the FV setup, set FV as the default system keyboard
4. Launch a separate app (e.g. Chrome)
5. Select a text area to type to bring up FV as the system keyboard
6. Long-press on the globe key to bring up the Keyboard Picker menu
7. Verify EuroLatin (SIL) is **not** installed

fix(oem/fv/android): Only add default keyboard if no keyboards exist

---

ios/engine/KMEI/KeymanEngine/Classes/Constants.swift
ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeyboardMenuView.swift
ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/SettingsViewController.swift
ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js

Fully removes the "Show Banner" settings option.  We've elected to force the banner to always be on in 17.0 due for multiple reasons:
- (For phones) This provides space for a key tip for keys in the top row.
- (Phones and tablets) This facilitates upward flicks for keys in the top row.
- (For phones) This provides better visibility of the flick preview for flicks in non-upward directions for keys in the top row.
- (Phones and tablets) This makes subkey menu interactions less awkward for such keys as well.
After piecing together my other two PRs today, I noticed that we hadn't actually removed the "Show Banner" option from the iOS app yet - something we already _have_ done in the Android app.  We've already stated our intent to remove it internally, so I figured I'd go ahead and knock this …

chore(ios): removes the "Show Banner" settings option

---

oem/firstvoices/keyboards.csv

Cherry pick of #11013 (done on 17.0 beta)  to stable-16.0.
@hopsandhops reported the FV apps listed older FV keyboard versions:
> fv_anishinaabemowin release: 10.0.1 app: 9.1.1
fv_cree_latin release: 10.0 app: 9.1.1
fv_plains_cree release: 11.0 app: 10.0.2
fv_dakelh release: 9.1.5 app: 9.1.4
fv_klahoose release: 10.1 app: 9.2
fv_henqeminem release: 10.0 app: 9.1.3
fv_nsilxcen release: 9.3 app: 9.2
fv_statimcets release: 9.1.4 app: 9.1.3
fv_gitsenimx release: 10.0.1 app: 9.1.1
fv_hailzaqvla release: 9.5.1 app: 9.4.1
fv_hlgaagilda_xaad_kil release: 9.3 app: 9.2
fv_kashogotine_yati release: 10.0 app: 9.1.1 (edited) 
This PR updates most of the FV keyboard versions reported in the FV app. Note, the original PR only covered reported versions from 2 weeks ago, so some keyboards like …

cherrypick(oem/fv): Update keyboard versions in keyboards.csv 🍒 🏠

---

core/src/km_core_action_api.cpp

Investigating this as part of #11045. May be some internal error, but adding an assert here that `p` doesn't go off the beginning of the array.
I added some context to part 3 of #11067 

fix(core): add an assert on code_points_to_delete 🌱

---

common/web/types/src/kmx/element-string.ts
developer/src/kmc-kmn/src/compiler/compiler.ts

- similar fix to https://github.com/keymanapp/keyman/pull/9492 (a similar error message was seen, perhaps on some versions of wasm?)
- again may be due to a wasm version variant
- also additional rangechecking on the input side
The error message I saw was:
> `TypeError: Passing a number "-2" from JS side to C/C++ side to an argument of type "unsigned int", which is outside the valid range [0, 4294967295]!`

fix(common): properly handle illegal UnicodeSets to prevent crash in kmc-ldml compiler 🙀 

---

common/web/types/src/kmx/kmx-plus.ts
common/web/types/src/util/util.ts
core/tests/unit/ldml/keyboards/k_007_transform_rgx-test.xml
core/tests/unit/ldml/keyboards/k_007_transform_rgx.xml
core/tests/unit/ldml/keyboards/k_210_marker-test.xml
core/tests/unit/ldml/keyboards/k_210_marker.xml
developer/src/kmc-ldml/src/compiler/tran.ts
developer/src/kmc-ldml/src/compiler/vars.ts

Bug: When sets contain markers, the 'map' operation fails, because the matched string was not found in the KMX+ set list.
Cause: inconsistent escaping due to the in-memory set variable being used for regex updating AND also used by core for the runtime match.
Similar for string variables (#11037)
Solution: 
1. The in-memory variables should be string literals, not regex (see #11037)
2. Need to push all escaping down to the regex substitution layer. Don't perform it 'early' in the lists.
Fixes: #11045
Fixes: #11037 

fix(core,developer): variable/marker substitution in sets and strings🙀

---

developer/src/kmc-ldml/src/compiler/messages.ts
developer/src/kmc-ldml/src/compiler/tran.ts
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-matches-nothing-1.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-matches-nothing-2.xml
developer/src/kmc-ldml/test/fixtures/sections/tran/fail-matches-nothing-3.xml
developer/src/kmc-ldml/test/test-tran.ts

- add message and check if the regex matches '' (empty string) and error if so
- add test cases
Fixes: bug(core): assert with vertical pipe #11062

fix(developer):  in ldml compiler, generate compiler error if `from=` regex matches empty string 🙀

---

core/src/actions_normalize.cpp

- output[0] was used as a boolean, but needed to check output.isEmpty() instead
- dead store to actions.code_points_to_delete
For: #11067 parts 1 and 2

fix(core): actions_normalize() length and dead store fix 🙀 

---

developer/src/kmc-model/build.sh
developer/src/kmc-model/package.json
developer/src/kmc-model/test/test-compile-trie.ts
package-lock.json

Per https://github.com/keymanapp/keyman/pull/11074#discussion_r1538598156, this PR allows the new unit test to directly check that all model wordlist entries are accessible.
To do so, it links in `@keymanapp/models-templates` for use in `kmc-model` unit testing.

feat(developer/compilers): better unit test for suggestion accessibility

---

core/src/actions_normalize.cpp
core/src/km_core_action_api.cpp
core/tests/unit/kmnkbd/test_actions_normalize.cpp

- UnicodeString is UTF-16, but can be used with UTF-32 boundaries.
- fix calculation of code_points_to_delete
Fixes: #11067

fix(core): fix pointer math in actions_normalize() 🙀 

---

common/web/keyboard-processor/src/text/outputTarget.ts
common/web/keyboard-processor/tests/node/transcriptions.js
web/src/app/webview/src/contextManager.ts

Fixes #7866.
When the transform generated by a key event results in no changes to the text, this will no longer trigger a change event in the apps. This means that layer switch keys will no longer erase the selection.
Fix proposed by @jahorton.
GROUP_IOS: Run these tests in Keyman for iPhone and iPad
GROUP_ANDROID: Run these tests in Keyman for Android
TEST_BASIC_INPUT: Verify that basic input continues to function correctly.
TEST_BACKSPACE: Type some text, then verify that backspace continues to work as normal.
TEST_CONTEXT_SYNC: Using Khmer Angkor keyboard, type <kbd>ខ</kbd> <kbd>េ</kbd>. Select the numeric/symbol layer, and return to the default layer. Press <kbd>្ម</kbd> (longpress on <kbd>ម</kbd>). Press <kbd>Backspace</kbd> and verify that the output on screen is ខ្ម (and not ខេ). …

fix(web): prevent layer switch key from erasing selection

---

common/web/keyboard-processor/src/text/outputTarget.ts

fix(common): make `isEmptyTransform` return true if passed a nullish transform

---

ios/engine/KMEI/KeymanEngine/Classes/Extension/String+Helpers.swift

Fixes #11093.
Rather than having the directional-mark trimming process swap between two encoding patterns, we should just use one.  While investigating exactly what the context was at the time of the reported error, I noted a few extra String functions that can be used to provide much cleaner-looking String manipulations.
The most likely culprit is a simple, context-initial non-BMP char.  A simple non-BMP emoji, for example, would likely be enough to have triggered the bug.  Within the Keyman app, this _shouldn't_ be possible after initialization is complete due to our insertion of an LTR or RTL mark as the context's prefix... but said mark is only established when editing begins, which is likely _after_ the context itself is initialized.  (So, there would be a "window of vulnerability" …

fix(ios):  address crash by reading full code point rather than code unit when trimming initial directional-mark

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
mac/Keyman4MacIM/KeymanTests/InputMethodTests.m
mac/KeymanEngine4Mac/KeymanEngine4Mac.xcodeproj/xcshareddata/xcschemes/KeymanEngine4Mac.xcscheme
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreKeyOutput.h
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreKeyOutput.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreWrapper.m
mac/KeymanEngine4Mac/KeymanEngine4MacTests/CoreHelperTests.m

When processing keystrokes for compliant apps (which have the ability to replace text while inserting characters from Keyman), the number of characters to delete must be determined correctly whether the context contains BMP code points or surrogate pairs. Also, if there is any text selected when the character is typed, the selection should also be replaced by the newly inserted character.
Fixes #1643 
* **TEST_REPLACE_BMP_CHARACTER**: typing a character with one selected causes it to be replaced
1. Open the Stickies app and create a new Note
1. Switch to the EuroLatin (SIL) keyboard
1. Type <kbd>a</kbd><kbd>b</kbd>
1. Select the letter 'b' that was just typed
1. Type <kbd>x</kbd>
1. Confirm that the b was replaced by x, and the text now reads  'ax'
* …

fix(mac): delete correct number of characters from current context when processing BMP or SMP deletes

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Fixes [Sentry issue](https://keyman.sentry.io/issues/5022225846)
Fixes #11128
When a selection range is reversed (selection "end" is before the selection "start"), this was causing an IndexOutOfBounds exception at
https://github.com/keymanapp/keyman/blob/6864cb32dd7e0513616b4d32decca924869229f9/android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java#L189-L190
where `selStart` was greater than `rawText.length()`.
KMKeyboardJSHandler had code to swap start/end for backward selection, but this happens after the line with the crash.
This PR changes KMKeyboard.updateSelectionRange to swap the selection indexes when the selection is reversed
**Setup** - Install the PR build of Keyman for Android on an Android device/emulator. In Keyman, install a keyboard that has SMP characters (e.g. …

fix(android/engine): Swap selection range if reversed

---

developer/src/common/include/kmn_compiler_errors.h
developer/src/kmc-kmn/src/compiler/kmn-compiler-messages.ts
developer/src/kmc-kmn/test/fixtures/invalid-keyboards/error_character_range_too_long.kmn
developer/src/kmc-kmn/test/fixtures/invalid-keyboards/error_extended_string_too_long.kmn
developer/src/kmc-kmn/test/fixtures/invalid-keyboards/error_outs_too_long.kmn
developer/src/kmc-kmn/test/fixtures/invalid-keyboards/error_virtual_key_expansion_too_long.kmn
developer/src/kmc-kmn/test/test-messages.ts
developer/src/kmcmplib/src/CompMsg.cpp
developer/src/kmcmplib/src/Compiler.cpp

Fixes #11092.
Addresses buffer boundary tests for four cases, so a fatal error is not returned to the user:
* character range too long (`U+1234 .. U+2468`)
* extended string too long (`'abcde...xxxxx'`)
* outs too long (`store(foo)` ... `outs(bar)`)
* virtual key expansion too long (`[K_A] .. [K_Z] ...`)
See #11136 for additional work arising.

fix(developer): handle buffer boundaries in four cases

---

.github/actions/build-binary-packages/action.yml
.github/workflows/deb-packaging.yml

This change splits the package builds into building packages for the released Ubuntu versions and for the next version. A failure to build packages for the next version will no longer fail the packaging GHA.
Closes #11143.

chore(linux): Build packages for next Ubuntu version separately

---

.github/actions/build-binary-packages/action.yml
.github/workflows/deb-packaging.yml

This change splits the package builds into building packages for the released Ubuntu versions and for the next version. A failure to build packages for the next version will no longer fail the packaging GHA.
Closes #11143.
(🍒 picked from PR #11145)

chore(linux): Build packages for next Ubuntu version separately :cherries: 

---

.github/workflows/deb-packaging.yml

Follow-up of #11145 to correct the spelling of the path...

chore(linux): Fix typo in path of `build-binary-packages` action

---

developer/src/kmc/build.sh
developer/src/kmc/package.json
developer/src/tools/sentry-upload-difs.sh
package-lock.json
web/package.json

fix not #11091.
Updating to latest sentry-cli on all projects, reviewed release notes and there do not appear to be any breaking changes.
sentry-cli 2.19.4 had a bug with uploading wasm symbols: https://github.com/getsentry/sentry-cli/issues/1682
It was fixed in 2.20.0: https://github.com/getsentry/sentry-cli/releases/tag/2.20.0

fix(common): upgrade sentry-cli to 2.31.0

---

.github/workflows/deb-packaging.yml

- Checkout source before building binary packages. This is necessary because we use an action that is defined in our source tree.
- Update checkout action to v4.1.1
- Ignore failed package builds for the next Ubuntu version in a different way. Previously failed package builds for the next Ubuntu release showed up with a green check mark. This change allows them to fail, but ignores the failure for the following steps.

chore(linux): More fixes for workaround for failing linux builds

---

mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m

When reading the current context to process keystrokes, load only 80 characters instead of the entire context.
Asking for all of the existing context degrades performance in Pages and appears to cause null to be returned when exceeding a certain limit in Slack.
Fixes #11087
Fixes #10970 
* **TEST_TYPING_IN_PAGES**: typing reasonable amounts of text should not become noticeable slow
1. Open Pages and create a new document
1. Switch to the EuroLatin (SIL) keyboard
1. Type a couple hundred characters
1. Confirm that inserting characters does not become noticeably slower as you continue to type (for comparison try typing with the Apple US keyboard and see if it is equally responsive)
* **TEST_TYPING_IN_SLACK**: keys should continue processing correctly after typing over 100 characters
1. Open …

fix(mac): load only 80 characters from context when processing keystrokes

---

.github/workflows/deb-packaging.yml

This reverts commit 2fe4da7cca369558a5696f82bf618b42d4cd6f8d.
In my tests in a test repo `continue-on-error` worked as desired but also seeds the total result as succeeded if the other jobs succeed. It's possible that we got the behavior we saw because of syntax errors in our file, so this change tries with the original approach again.

chore(linux): Revert "Ignore failed package builds differently"

---

.github/workflows/deb-packaging.yml

We want to run the `deb_signing` job after building binary packages for both released and unreleased Ubuntu versions finished, so we have to specify those in the `needs` field. But that on its own causes the signing job to be skipped if the binary package build for the next Ubuntu version fails. This change adds conditions so that the `deb_signing` job always runs if source package build and the binary package build for the released Ubuntu versions succeeds.

chore(linux): Sign packages even if build for next Ubuntu fails

---

common/windows/delphi/general/Upload_Settings.pas
developer/src/kmconvert/kmconvert.dpr
developer/src/kmconvert/kmconvert.dproj
developer/src/setup/setup.dpr
developer/src/setup/setup.dproj
windows/src/desktop/kmshell/install/Keyman.Configuration.UI.KeymanProtocolHandler.pas
windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas
windows/src/desktop/setup/setup.dpr
windows/src/desktop/setup/setup.dproj

Fixes: #11005  
It fixes the root cause,  that is the Package ID was not decoded correctly and the filesystem would end up with a directory with %20 encoding. Once this was fixed uninstalling worked correctly.
The uri for the downloaded filename is decoded to turn %20 back to spaces etc. For the download location encoding is maintained.
Install the Keyman from this PR
1. Open in the configuration 
2. Select the `Download keyboard...`
3. Install `Greek polytonic SA`
4. Once installed go to Keyboard Layouts Configuration tab
5. Choose any of the Greek keyboards such as `Greek Polytonic LS EZ`
6. Select the Uninstall button.
Expected result: 
All of the Greek Polytonic SA keyboards are uninstalled.

fix(windows): decode uri for Package ID and filename

---

.github/actions/build-binary-packages/action.yml
.github/workflows/deb-packaging.yml

This change shows failed package builds for the next Ubuntu version as failed. With the last change it still showed as green in the overview, despite my experiments. Turns out it depends where you put the `continue-on-error: true` statement: if it's in the `steps` section it'll show up green, if you put it in the job's metadata it'll work as expected and show up as failed.

chore(linux): Show failed job for next Ubuntu version as failed

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/KMEA/app/src/main/java/com/keyman/engine/KMTextView.java

Fixes #11160.
Supersedes #11162.
This PR prevents an error that could randomly occur during quickly-repeated text modifications that could trigger a keyboard crash in the case of repeated backspaces.
Technical details:  we had an invalid assumption that a method signalling text-selection updates and the "source of truth" for app text state were synchronous.  This was untrue, allowing an extra backspace to edit app text state while processing a previous edit's effects.  By relying on a single "source of truth", we can avoid the lack of synchronization between the two.
**Setup** - Install the PR build of Keyman for Android. From the Keyman app, also install basic_kbdosm (Osmonya) keyboard which outputs SMP characters.
Set Keyman as the default system keyboard
* **TEST_REVERSE** - Verifies …

fix(android): atomically updates selection with text

---

web/src/engine/osk/src/keyboard-layout/oskLayerGroup.ts

Fixes #11165.
A simple logic error - forgetting to validate index bounds - resulted in an error during input of certain gestures.
TEST_FLICKS: Verify that flicks work without triggering error messages.
1. Install and open Keyman for Android on a test device.
2. Press and drag a key straight downward direction then release the key to print the special characters. 
3. Repeat step 3 several times. 
4. Press and drag a key straight upward as if it supported a flick.  Drag your finger past the banner.
5. Repeat step 4 several times.

fix(web): fix crash in nearest-key row lookup when touch moves out-of-bounds

---

web/src/engine/osk/src/keyboard-layout/oskLayer.ts
web/src/engine/osk/src/views/oskView.ts
web/src/engine/osk/src/visualKeyboard.ts

To prepare to optimize layout-reflow for Web's OSK, it will help us to rework how spacebar-text and its styling are managed.  They'll be far easier to "batch" with other layout updates if managed by the layer containing the key, rather than set outside of the standard flow.
Also, we had a _lot_ of redundant calls to the `showLanguage()` function, which is what updated the spacebar.  We only need one.
This PR has been spun off of an older state of #11140.  Certain design decisions may make more sense with the whole picture in mind, though I have tried to recontextualize them to make better sense in isolation for this PR.
TEST_ANDROID_SPACEBAR:  Using Keyman for Android, verify that the spacebar is always appropriately captioned (based on user settings in the menu) for the active keyboard, …

refactor(web): OSK spacebar-label updates now managed by layer object 🪠

---

oem/firstvoices/keyboards.csv

Relates to keymanapp/keyboards#2679 and fixes keymanapp/keyboards#2675
> * add fv_sguuxs entry (for BC Coast region / tsi - Tsimshian language) in keyboards.csv
[fv_all.kmp 12.8](https://downloads.keyman.com/keyboards/fv_all/12.8/fv_all.kmp) added the fv_sguuxs keyboard so this PR updates the keyboards.csv file. Also updates reported keyboard versions.

chore(oem/fv): Add fv sguuxs and update keyboard versions

---

resources/build/ci/pull-requests.inc.sh

Fixes #11125 by working around the base issue.
Arising from discussion in #11125. It's unclear exactly what is causing this; the commit is the latest (only) on the branch according to the code:
https://github.com/keymanapp/keyman/blob/02812af97f6fdc312dd83bf0c8b529ed15f28229/resources/build/ci/pull-requests.inc.sh#L103-L107
From the [logs](https://build.palaso.org/buildConfiguration/Keymanweb_Build/452314?buildTab=log&focusLine=1033&logView=flowAware&linesState=1026), we can see that recent changes were pulled into master immediately before the branch and new commit:
```
...
03:45:22   From https://github.com/keymanapp/s.keyman.com
03:45:22    * branch              master     -> FETCH_HEAD
03:45:29   Updating 27a81d24..416d852a
03:45:29   Fast-forward
03:45:30  …
```

fix(common): specify title explicitly when opening PR with hub

---

web/src/engine/main/src/contextManagerBase.ts
web/src/engine/main/src/keymanEngine.ts
web/src/engine/osk/src/views/oskView.ts
web/src/engine/osk/src/visualKeyboard.ts

The set of PRs culminating here heavily restructures how the OSK loads and updates during use - especially after device rotation and when swapping layers.  This should help the OSK load faster and change layers faster.
Based on local profiling experiments, observations, and data, with this PR + #11129... [(details in a comment below)](https://github.com/keymanapp/keyman/pull/11140#issuecomment-2036287502)
- keyboard swapping is approximately 33% faster, and even higher for more complex keyboards
- the embedded Web engine within our Android and iOS keyboards initializes approximately 60% faster.
- layer-swapping during rapid-key input is just over 140% faster than previous versions of 17.0-alpha.
- layer-swapping is likely 50% faster or more than 16.0 stable.
The technical catch-all for …

change(web):  OSK optimization, improved responsiveness 🪠

---

web/src/engine/osk/src/input/gestures/specsForLayout.ts
web/src/engine/osk/src/visualKeyboard.ts

I happened to notice this one yesterday while using `sil_euro_latin` - our up-flick shortcut for quick longpresses wasn't working.
Rather than make things convoluted with special-case handling this close to release, I figured the simplest way forward is to simply parameterize longpresses and flicks in a way that allows the longpress-flick to win when a key supports both.  The old parameterization locked in the start of a full-fledged flick gesture before the longpress up-flick shortcut had a chance to trigger.
TEST_LONGPRESSES_AND_FLICKS:  Using the `sil_euro_latin` keyboard, verify the following:
- A simple longpress on a key.
- Holding a key, then moving upward quickly causes the subkey menu to display early.
- Holding a key, then moving downward quickly triggers the key's flick.

fix(web): fixes up-flick shortcut issue for longpress when keys support downflicks

---

.github/workflows/deb-packaging.yml

The recent merge from `beta` into `master` introduced a problem when resolving merge conflicts, resulting in duplicate definition of `binary_packages_unreleased` which prevents the workflow from loading. This change rectifies the file.

chore(linux): Fix wrong merge

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

This PR exists to facilitate diagnosis of #11186 when it occurs.

chore(android): enables debugging and inspection of mobile app internal webviews

---

common/web/input-processor/src/text/inputProcessor.ts
common/web/keyboard-processor/src/text/deadkeys.ts
common/web/keyboard-processor/src/text/outputTarget.ts

Fixes #11230.
Previously, we _always_ cleared the selection as part of resetting the context-state for multitaps.  Problem is... that has unwanted cross-effects if the _only_ thing the multitap is doing is to layer-switch.
It's possible to shorten the changes with a "naive" fix, but naive solutions don't account for potential deadkey solutions very well.  I figure it's best to nip all such issues in the bud now, especially since I don't think there are related preventative warnings and/or errors for keyboard developers in Developer.
Any Web-based touch-platform will suffice for these tests.
**TEST_CAPS_WITH_SELECTION**:  Verify that selected text is not erased when double-tapping SHIFT to enter a keyboard's caps-lock state.  (A direct repro attempt for #11230.)
**TEST_MULTITAP_ROTA**: …

fix(web): prevents selection-clear for pure layer-switching multitaps

---

web/src/engine/osk/src/keyboard-layout/oskBaseKey.ts
web/src/engine/osk/src/keyboard-layout/oskKey.ts
web/src/engine/osk/src/keyboard-layout/oskLayer.ts
web/src/engine/osk/src/keyboard-layout/oskRow.ts

Addresses post-merge review comments from recent optimization PRs - in particular, for #11177. 
TEST_LIGHT_GESTURES:  Do some light testing of a few gesture-enabled keyboards and make sure things work as well as they did before.  Nothing too rigorous - we'll handle that with regression & platform-acceptance testing.

change(web): drops need for closures to optimize layout-reflow 🪠

---

web/src/engine/osk/src/input/gestures/specsForLayout.ts

This changes the timings for multitap gestures to be far closer to the default settings used for multitaps on Android.
References:
- https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/view/GestureDetector.java#251
- https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/view/GestureDetector.java#871
- https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/ViewConfiguration.java#146
This sets the wait time from key-up to key-down to match their `DOUBLE_TAP_TIMEOUT` and uses the `HOVER_TAP_TIMEOUT` as a key-down to key-up timeout to prevent an ongoing multitap from proceeding further, based on its documentation.
As per https://stackoverflow.com/a/2900851, …

change(web): adjusts multitap timings

---

common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureMatcher.ts
common/web/gesture-recognizer/src/engine/headless/gestures/specs/gestureModel.ts
common/web/gesture-recognizer/src/test/auto/headless/gestures/isolatedGestureSpecs.ts
web/src/engine/osk/src/input/gestures/browser/flick.ts
web/src/engine/osk/src/input/gestures/specsForLayout.ts

Fixes #11221.
Turns out that there was a flag missing on the longpress model; if a second touch started during the longpress timer, it cancelled _both_ the longpress _and_ the new touch as a result, rather than just the longpress.  Fortunately, it's a quite simple fix.
TEST_RAPID_TYPE_WORDS:  Using the Keyman app on an Android device, attempt to reproduce #11221 with normal typing patterns - type rapidly and ensure no keys are unexpectedly dropped.
- Try typing `the quick brown fox jumped over the lazy dog` as fast as possible.  Don't worry about accuracy (aside from avoiding the globe key).
- Feel free to try additional sentences and/or paragraphs.
- Be sure you can compare the results with what you meant to type, so no random keymash.
TEST_RAPID_TYPE_HOME_ROW:  Using the Keyman app on …

fix(web): prevents dropping of input during rapid multitouch typing

---

web/src/engine/osk/src/lengthStyle.ts
web/src/engine/osk/src/visualKeyboard.ts
web/src/test/auto/headless/engine/osk/lengthStyles.js

fix(web): default parse of length styling for empty string

---

developer/src/tike/main/UfrmMain.pas

Fixes #11194.
If the last-used project file no longer exists (e.g. has been renamed), then Keyman Developer would crash as it did not test that the file had been loaded successfully before attempting to reference it.
* **TEST_PROJECT_LOAD:** Follow the steps in #11194 and ensure that Keyman Developer no longer crashes on startup.

fix(developer): test that MRU project exists before attempting to reference on startup

---

developer/src/server/src/site/test.js

Fixes #11273.
On some devices, the fetch() would return faster than the remaining script loads, which caused this script error. Lazy initialization should address this.

fix(developer): lazy initialization of test window

---

web/build.sh

Just a minor bit of cleanup.  `build:engine/osk` still has the gesture-engine as a builder-dependency, which is the proper link.

chore(web): drops redundant builder-dependency from early gesture dev

---

linux/scripts/package-build.inc.sh

On a new machine we need to install python3-dev so that we can access `Python.h`. It shouldn't be in `debian/control`, so we put in our script where we check the requirements.

chore(linux): Install python3-dev

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Fixes #11279.
Fixes #11280.  (By preventing the scenario.)
Reference: https://stackoverflow.com/a/49649302
Device text-size accessibility scaling appears to affect the WebView "text zoom" setting.  Directly setting text-zoom to a specific value bypasses this and locks down our keyboards' font sizes.
TEST_ACCESSIBILITY_FONT_EFFECTS:  Using the Keyman app for Android, verify that system accessibility settings for fonts have no effect on the size of the in-app and system keyboards.
- Note that you will need to force-quit the app after changing system settings in order to properly test this; the app only retrieves font-size data once, when first loaded.

fix(android): fixes kbd text zoom to prevent accessibility cross-effects

---

linux/debian/control

- Adjust branch name
- Update Debian standards version
- Update dependency name (`pkg-config` is deprecated and replaced by `pkgconf`)

chore(linux): Prepare for stable release

---

resources/build/build-download-resources.sh

Fixes #10670 
This updates the curl downloads to try up to 5 times (with 5s delay in between).
Reference
https://curl.se/docs/manpage.html#--retry
Also updated to use long option names. And since the curl still uses `--silent`, the retry statuses aren't output.

fix(common): Retry curl downloads up to 5 times

---

windows/src/desktop/kmshell/xml/strings.xml
windows/src/engine/keyman/viskbd/UfrmOSKFontHelper.pas

Fixes: #10933 
This change is to check the number of fonts found for the keyboard to guard against trying to index it when there are no fonts.
1. In the procedure `FormatGrid` check the font count if it is zero exit straight away. 
```
for i := 0 to grid.RowCount - 1 do
m := System.Math.Max(m, Canvas.TextWidth(FSelectedKeyboard.Fonts[i].FontName) + 6)
```
2. Update the procedure `DisplayKeyboardFonts` to let the user know that no fonts were found as a suggestion.
Note: 
This line in `DisplayKeyboardFonts`
```
grid.RowCount := FKeyboard.Fonts.Count;
```
grid.RowCount cannot be less than 1. Therefore if font count is 0 the row count value will be 1 after this assignment. 
1. Install Keyman for Windows build artifact
2. Using Keyman Configuration install Simplified Chinese, Tamil 99 Basic, …

fix(windows): check font count display none found

---

linux/keyman-config/keyman_config/gnome_keyboards_util.py
linux/keyman-config/keyman_config/ibus_util.py
linux/keyman-config/keyman_config/install_kmp.py
linux/keyman-config/keyman_config/uninstall_kmp.py
linux/keyman-config/tests/test_gnome_keyboards_util.py
linux/keyman-config/tests/test_install_kmp.py
linux/keyman-config/tests/test_uninstall_kmp.py

This change improves the way we detect if we're running a Gnome based UI that needs it's keyboards installed under
`org.gnome.desktop.input-sources`. We use the environment variable `XDG_CURRENT_DESKTOP` and check if it contains the word `gnome`. Additionally this change renames `is_gnome_shell()` to `is_gnome_desktop()`.
Fixes #11225.
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_NOBLE_WAYLAND**: Ubuntu 24.04 Noble with Gnome Shell and Wayland
- **GROUP_WASTA**: Wasta 22.04 with Cinnamon
- Reboot
**TEST_INSTALL**:
- open Keyman Configuration
- install a Keyman keyboard …

fix(linux): Improve detection of Gnome environment

---

common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureMatcher.ts
common/web/gesture-recognizer/src/engine/headless/gestures/matchers/matcherSelector.ts

Fixes #11186.
Adds error-handling for the callbacks of gesture models passed to the gesture engine, adding stability when the models aren't properly defined.  Also prevents a model with invalid initial state from evaluating any further, as that could invalidate assumptions based on said check in the path model.
The gesture engine uses configured callbacks in the specified gesture models to match the needs of the library's consumer.  Should an error arise at critical points in that process, we need to ensure they don't destabilize the general core processes of the gesture engine, even if we do need to cancel the failed gesture-models.

fix(web): gesture-model initial-state, callback failure handling

---

linux/keyman-config/resources/keyman.sharedmimeinfo

It seems some Ubuntu versions ignore the `icon` field and only use `generic-icon`, so this change adds that field. This will fix displaying the icon on newer Ubuntu versions. And since we keep the `icon` field it should still work everywhere else.
Fixes #11144.
- **GROUP_NOBLE_WAYLAND**: Ubuntu 24.04 Noble with Gnome Shell and Wayland
- **GROUP_WASTA**: Wasta 20.04 with Cinnamon
- Reboot
**TEST_ICON**: 
- Download a .kmp file from keyman.com
- Verify that the correct icon shows for the .kmp file in the file manager

fix(linux): Fix icon for .kmp files

---

resources/builder.inc.sh

This fixes the use of colors in the help output when `builder_term` is used inside of `builder_describe` (e.g. `web/test.sh --help`). Previously the escape sequences were not interpreted but directly output.

fix(common): Fix colorization of help output of builder script

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Fixes #11344.
Compare the changes made here against some of the original code changes in #11127 - it appears that a merge conflict got incorrectly applied at some point.  There was originally proper inverted-range handling, but it got overwritten with code that couldn't properly handle it.
TEST_INVERTED_SELECTION_RANGE: Using Keyman for Android as a system keyboard, ensure that backwards selection ranges do not crash the keyboard.
- Select text, then drag one of the end points through and past the other one.
- If the keyboard immediately disappears, or you see an error notification, FAIL this test.

fix(android): inverting a selection range would crash Keyman

---

developer/src/kmc-package/src/compiler/kmp-compiler.ts
developer/src/kmc-package/src/compiler/package-compiler-messages.ts
developer/src/kmc-package/src/compiler/package-keyboard-target-validator.ts
developer/src/kmc-package/src/compiler/package-metadata-collector.ts

fix(developer): handle missing Name element for File element in package compiler

---

web/test.sh

- previously there was an extra `--browsers` flag - `$BROWSERS` already contains the flag
- previously we specified `$KARMA_FLAGS` twice if we set `$KARMA_EXT_FLAGS`
- some cleanup

chore(web): Improve web/test.sh script

---

linux/keyman-config/tests/test_uninstall_kmp.py

This suddenly started failing. I guess there was a deprecated `assertEquals` in older Python libraries, but with the latest version in Ubuntu 24.04 Noble this disappeared. Anyway, with this change we use the same assert method as in the other test files.

chore(linux): Fix typo

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java

Fixes #11337.
It turns out that in the middle of updating Android context after a keystroke, we were triggering a selection-change before the batch-edit process was complete - though only if there was selected text.  It's not clear why that one branch was left out of the "ignore selection change" mode, but including it is enough to fix the issue.
Refer to #8611 and #8682 for related historical context.
TEST_REPRO:  Using an up-to-date version of Android, attempt to reproduce the base issue (#11337).
2. Open Keyman In-app.
3. Type a sentence (eg., All things are beautiful)
4. Select the last word 'beautiful'.
5. Press Backspace key to delete that word.
6. Type the text 'ha..' (eg.,happen)
Verify that predictive text operates normally, instead of breaking as it did in #11337.

fix(android): prevents mid-keystroke desynchronization when deleting selected text

---

web/src/app/browser/src/context/pageIntegrationHandlers.ts
web/src/app/browser/src/hardwareEventKeyboard.ts

Fixes #11364.
Instead of using `className` which may be of type `SVGAnimatedString` if the element is an SVG element, use `getAttribute('class')`. As that function can return `null` if the class attribute is not defined, use optional chaining to avoid a new error...
Uses the same pattern in hardwareEventKeyboard.ts, although I suspect the problem may never arise there.
I audited the uses of className in our KeymanWeb source and found only these three instances which may be problematic. I have not searched elsewhere.

fix(web): support SVG elements when checking className

---

common/web/types/build.sh
common/web/types/package.json
tsconfig.base.json

This improves the dependency linking between core and web. Changes were made while tracking down a failure building wasm core. However, what made it work in the end was to clear the `developer` sub-directory, so I think we're still missing a dependency somewhere...

chore(web): Improve dependencies

---

windows/src/desktop/kmshell/xml/strings.xml

OS font helper UI string had a capital for K it should have been lower case k.

fix(windows): "Keyboard" should be lower case in UI string for font helper tool

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Fixes #11360
@mcdurdin went spelunking in the Android code and found `getSelectionStart()` and `getSelectionEnd()` return -1 if there's no selection or cursor.
Reference https://developer.android.com/reference/android/text/Selection#getSelectionEnd(java.lang.CharSequence
In those cases (likely a race condition), we should no-op on `updateSelectionRange()` since there's no valid selection to pass to KeymanWeb.
**Setup** - Install PR build of Keyman for Android and enable Keyman as the default system keyboard
* **TEST_INVERTED_SELECTION_RANGE**: Using Keyman for Android as a system keyboard, ensure that backwards selection ranges do not crash the keyboard.
1. Select text, then drag one of the end points through and past the other one.
2. If the keyboard immediately disappears, or you see an …

fix(android/engine): Skip updating selection range if invalid

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Relates to #11360 and follows #11384 - 
Applies suggested refactoring of updateSelection
* Eliminate `selStart`, `selEnd`, and `result` vars
* short-circuit checks (to return false)
**Setup** Install PR build of Keyman for Android and enable Keyman as the default system keyboard
* **TEST_INVERTED_SELECTION_RANGE** : Using Keyman for Android as a system keyboard, ensure that backwards selection ranges do not crash the keyboard.
1. Select text (right to left), then drag one of the end points through and past the other one.
2. If the keyboard immediately disappears, or you see an error notification, FAIL this test.
* **TEST_NORMAL_SELECTION_RANGE**: Using Keyman for Android as a system keyboard, ensure that normal (forward) selection ranges do not crash the keyboard
1. Select text (left to …

refactor(android/engine): Refactor updateSelection

---

web/src/app/browser/src/contextManager.ts

fix(web): fixes illegal KMW event state - can't focus a null element

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

We don't really need it, and I am hoping it will be enough to resolve the Play Store policy issues.

fix(android): disable Sentry session tracking

---

mac/Keyman4Mac/Keyman4Mac/AppDelegate.m
mac/Keyman4Mac/Keyman4Mac/KMBarView.m
mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutBGView.m
mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMBarView.m
mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m
mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m
mac/Keyman4MacIM/Keyman4MacIM/KeySender.m
mac/Keyman4MacIM/Keyman4MacIM/OnScreenKeyboard/OSKWindowController.m
mac/Keyman4MacIM/Keyman4MacIM/OnScreenKeyboard/OSKWindowController.xib
mac/Keyman4MacIM/Keyman4MacIM/main.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/CoreWrapper/CoreKeyOutput.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/OSKKey.m
mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/OSKView.m

According to [AppKit Release Notes for macOS 14](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14#NSView) the property NSView.clipsToBounds which was defaulted to true was changed to default to false. This caused the Keyman OSK keys to not be drawn correctly under Sonoma, giving the appearance of a blank OSK. This change is to override the new default behavior and set the property back to true.
Fixes #11379 
Also, with the move to Xcode 15.3, there are several APIs called from Keyman for Mac that were deprecated before our minimum supported version of macOS (now set to 10.13). These can be replaced without doing version checks because the replacements are available for all of our supported OS versions. It was suspected that these may have …

fix(mac): restore OSK keys that became invisible in mac OS 14 Sonoma

---

windows/src/desktop/inst/keymandesktop.wxs

feat(windows): Don't install desktop shortcut for Keyman for windows on installation

---

oem/firstvoices/keyboards.csv

fv_nlakapamuxcheen (keymanapp/keyboards#2731) will be added to fv_all.kmp in keyboard package 12.9 (depends on keymanapp/keyboards#2740 to be built first)
This adds the keyboard and region to keyboards.csv for the FV mobile apps to include.
* Also update keyboard versions from recent updates (for fv_all.kmp 12.9)
* **TEST_FV** - Verifies fv_nlakapamuxcheen can be installed
1. Install the PR build of "FirstVoices Keyboards for Android.apk" (**not** 16.0)
2. From the FV app setup menu, go to Regions --> BC Interior
3. Select Nlakapamuxcheen (fv_nlakapamuxcheen) and install
4. Return to the FV setup menu and enable FV as the default system keyboard
5. Launch Chrome and select a text area
6. With the FV keyboard, verify the fv_nlakapamuxcheen keyboard can be used.

chore(android,ios): Add fv_nlakapamuxcheen

---

android/KMAPro/build.gradle
android/KMAPro/gradle/wrapper/gradle-wrapper.properties
android/KMAPro/kMAPro/build.gradle
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/BookmarksActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/LanguageSettingsActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/LanguagesSettingsActivity.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java
android/KMEA/app/build.gradle
android/KMEA/app/src/main/java/com/keyman/engine/KeyboardPickerActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/ModelPickerActivity.java
android/KMEA/build.gradle
android/KMEA/gradle/wrapper/gradle-wrapper.properties
android/README.md
android/Samples/KMSample1/app/build.gradle
android/Samples/KMSample1/build.gradle
android/Samples/KMSample1/gradle/wrapper/gradle-wrapper.properties
android/Samples/KMSample2/app/build.gradle
android/Samples/KMSample2/build.gradle
android/Samples/KMSample2/gradle/wrapper/gradle-wrapper.properties
android/Tests/KeyboardHarness/app/build.gradle
android/Tests/KeyboardHarness/gradle/wrapper/gradle-wrapper.properties
android/Tests/keycode/app/build.gradle
android/Tests/keycode/build.gradle
android/Tests/keycode/gradle/wrapper/gradle-wrapper.properties
oem/firstvoices/android/app/build.gradle
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVKeyboardSettingsActivity.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/PackageActivity.java
oem/firstvoices/android/build.gradle
oem/firstvoices/android/gradle/wrapper/gradle-wrapper.properties

Start of 18.0 chore in updating Android dependencies (including Sentry 7.8.0). These dev dependencies require no change to CI (still using JDK 11).
Fixes #11370 in minor increment from 7.4.0 to 7.4.2 of the Android gradle plugin. 
Updating to Gradle 8.0 will require a lot more work in also updating JDK to 17 and handling Robolectric changes.
Robolectric also recommends migrating to AndroidX Test at some point
https://robolectric.org/androidx_test/
> At some point the Robolectric equivalents will be deprecated and removed. 
Some of the code changes are because the Gradle update linter enforces `super.onBackPressed()` to be called.
**Setup** - Install the PR builds of the Android apps for the corresponding tests
* **TEST_KEYMAN** - Verifies back functionality on Keyman
1. Install the PR …

chore(android): Update dependencies

---

common/models/templates/package.json
common/models/wordbreakers/package.json
common/predictive-text/package.json
common/test/resources/package.json
common/tools/sourcemap-path-remapper/package.json
common/web/gesture-recognizer/package.json
common/web/input-processor/package.json
common/web/keyboard-processor/package.json
common/web/lm-worker/package.json
common/web/recorder/package.json
common/web/utils/package.json
package-lock.json
package.json
resources/build/version/package.json
web/package.json

Amother notable task I identified while working on https://github.com/keymanapp/keyman/pull/11300 (toward resolving https://github.com/keymanapp/keyman/issues/10497) is that a number of our packages have considerably out-of-date `@types/node` dependencies.  The testing framework we'll likely be transitioning to includes a dependency of its own that requires a more recent version than some of the packages currently utilize... including the one installed in our monorepo root package.
Re: `@types/node` updates:  https://stackoverflow.com/a/52404327
- Put simply, the type of the typings package should match that of node.  As we're currently on Node 18, I updated to the latest v18 typings.  If we shift to 20 (or higher) before this lands, this should be updated again.
**Note**: I believe I did …

chore(web): updates most @types/node dependencies, makes them consistent 🏃

---

package-lock.json
package.json

As part of #10497, formerly part of #11300, this prepares the new dependencies to be used in place of Karma.
As this operation tends to cause big package.json / package-lock.json changes, that's all this PR is in place to do.  (That way, subsequent PRs have a clearer scale and scope of changes.)
If you'd like to get a feel of what using this testing engine is like, the first "preview" / migrated-test can be found at #11404.

chore(web): adds '@web/test-runner' and related packages 🏃

---

android/KMAPro/gradle/wrapper/gradle-wrapper.properties
android/KMEA/gradle/wrapper/gradle-wrapper.properties
android/Samples/KMSample1/gradle/wrapper/gradle-wrapper.properties
android/Samples/KMSample2/gradle/wrapper/gradle-wrapper.properties
android/Tests/KeyboardHarness/gradle/wrapper/gradle-wrapper.properties
android/Tests/keycode/gradle/wrapper/gradle-wrapper.properties
oem/firstvoices/android/gradle/wrapper/gradle-wrapper.properties

Follows #11393 to match the Gradle version with the plugin.
Trying to troubleshoot why [18.0.34 master](https://build.palaso.org/buildConfiguration/KeymanAndroid_Build/462567?buildTab=log&logView=flowAware&linesState=944&focusLine=0) build failed.
I'm not sure - maybe Gradle hung for some reason trying to clean the build/tmp folder for oem/fv/android.
```bash
./build.sh build --ci
```
worked on my local environment.

chore(android): update Gradle wrapper version

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java
android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
android/KMEA/app/src/main/java/com/keyman/engine/KMPopoverView.java
android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java
oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/SystemKeyboard.java

Fixes #9586
Android API 30 deprecated several calls used to determine Window Display, Size, and Metrics. This refactors the calls to KMManager to handle the different API calls.
* These tests should run the PR builds on an Android Device/emulator of the specified API level to test each side of API 30
* GROUP_API_28: Android 9.0 Pie
* GROUP_API_34: Android 14.0 UpsideDown Cake
**Tests**
**TEST_KEYMAN** - Verifies orientation and keyboard height for Keyman app
1. Install Keyman for Android with the device in Portrait orientation
2. From "Get Started", enable Keyman as the default system keyboard. 
3. Dismiss "Get Started"
4. Note the current keyboard height.
5. From Keyman Settings --> Adjust keyboard height
6. From "Adjust keyboard height" menu, adjust the keyboard height for both portrait …

fix(android): Replace deprecated APIs for Display, Size, Metrics

---

android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java

Cherrypick #11458 to stable-17.0
This fixes the transition on the lock screen to handle the Globe key on key press (GLOBE_KEY_STATE_DOWN).
**Setup** - 
1. Install the PR build of Keyman for Android on an emulator. Best to use an emulator in case the lock screen gets stuck on the wrong keyboard for entering the password.
2. On the Android emulator Settings, set the lock screen to use a password of "qwerty".
**TEST_KEYMAN_LOCK_SCREEN** - Verifies Keyman globe key on lock screen
2. From "Get Started", set Keyman as the default ksystem keyboard.
3. Launch Chrome and select a text field.
4. Switch to Keyman if it's no the current keyboard. 
5. Lock the emulator
6. Press button to enter the lock screen
7. With Keyman on the lock screen, press and release the globe key
8. Verify …

cherrypick(android/engine): Handle globe key on lock screen 🍒 🏠

---

resources/builder.inc.sh

When using `module:target` style dependencies, Builder would not track the individual targets within the module, causing only the first target to be built; subsequent dependency targets within that module would be treated as already built.
This change means that builder will track individual targets within the dependency. However, it is possible for targets to be built multiple times if there a dependency listed for the entire module as well as for the individual target within dependency, as in the following example, where building `project1` and `project2` in one command would cause `module:mytarget` to be built twice.
```
builder_describe project1 \
@/module
builder_describe project2 \
@/module:mytarget
```
This scenario should not break builds as they any configure+build actions should …

fix(common): calculate already-build dependency targets correctly

---

resources/builder.inc.sh

The call to the command listed for `builder_run_action` was not properly quoted, which meant that quoted parameters would have been corrupted, for example:
```
builder_run_action clean   rm -rf "temp folder/"
```
Would have run:
```
rm -rf temp folder/
```

fix(common): properly quote `builder_run_action` call

---

android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java

Fixes #11479 - 
Will :cherries: pick to stable-17.0
Adds additional null check since getExtractedText 
> may fail either if the input connection has become invalid or the client is taking too long to respond with the text...
This was causing the crash:
> Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference

fix(android/app): Verify extracted text is not null

---

common/include/test_color.cpp
common/include/test_color.h
core/tests/unit/kmnkbd/meson.build
core/tests/unit/kmx/meson.build
core/tests/unit/ldml/ldml_test_source.cpp
core/tests/unit/ldml/meson.build
core/tests/unit/meson.build
developer/src/kmcmplib/tests/meson.build

Moves variable declaration for `bool enabled` from .h to .cpp and fixes up builds. Fixes `#include` in ldml_test_source.cpp which was inside a namespace.
Fixes: #10426

refactor(common): move `enabled` declaration into test_color.cpp

---

.github/workflows/api-verification.yml
.github/workflows/deb-packaging.yml
docs/core-api-verification.md
linux/scripts/deb-packaging.sh
linux/scripts/test/deb-packaging.tests.sh

The new `api-verification` workflow runs after `deb-packaging`.
Implements #10626.

chore(linux): Move API verification to separate action

---

developer/src/tike/debug/Keyman.System.Debug.DebugEvent.pas

The output from Keyman Core changed in #11172 to emit a `KM_CORE_IT_INVALIDATE_CONTEXT` action when a frame key is pressed, but the debugger was not catering for this scenario, causing an assertion failure.
Fixes: #11486
Fixes: KEYMAN-DEVELOPER-1Y4
**TEST_DEBUGGER_KEYS:** In the Keyman Developer debugger window, press a variety of keys, including letter keys, arrow keys, and more. The debugger should no longer crash.

fix(developer): handle `KM_CORE_IT_INVALIDATE_CONTEXT` in debugger

---

common/test/resources/test-runner-TC-reporter.mjs
common/test/resources/test-runner-rename-browser.mjs
common/test/resources/test-runner-stability-reporter.mjs
web/common.inc.sh

Try as I might, I couldn't find any reporters for @web/test-runner designed for use with TeamCity.  Fortunately, they've got pretty good documentation for their reporter API... so I decided to roll our own.  As work went on and I remembered some issues we've had with browser-level automated tests in the past, I also added a couple more features to enhance our build logs and surface data that wasn't easily accessible otherwise.
Obviously, I worked on these _after_ actually migrating many of our automated tests to @web/test-runner.  That said... it'd be simpler and more time-efficient to review such PRs with the changes near-finalized out of the gate, so I've hoisted this earlier in the commit chain.
So, the new modules:
1. test-runner-TC-reporter
- This formats test results in the format …

feat(web): custom infrastructure for @web/test-runner use 🏃

---

developer/src/tike/debug/Keyman.System.Debug.DebugEvent.pas

Cherry-pick of #11488.
The output from Keyman Core changed in #11172 to emit a `KM_CORE_IT_INVALIDATE_CONTEXT` action when a frame key is pressed, but the debugger was not catering for this scenario, causing an assertion failure.
Fixes: #11486
Fixes: KEYMAN-DEVELOPER-1Y4

fix(developer): handle `KM_CORE_IT_INVALIDATE_CONTEXT` in debugger 🍒 🏠

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Where bugs have been fixed and closed, users tend to miss this if the bug has not yet stable. So expanding the search to show all issues that match by default, whether open or closed.
Fixes: #11212

change(common): remove `is:open` from issue templates

---

resources/standards-data/iso639-3/iso639-3.tab
resources/standards-data/language-subtag-registry/language-subtag-registry
resources/standards-data/readme.md
windows/src/test/unit-tests/standards-data/Keyman.Test.System.CanonicalLanguageCodeUtilsTest.pas
windows/src/test/unit-tests/standards-data/Keyman.Test.System.Standards.LangTagsRegistryTest.pas

chore(common): Update standards data

---

oem/firstvoices/android/app/build.gradle
oem/firstvoices/android/build.gradle

Another attempt at addressing #11491
For OEM FV Android app, this reverts the Sentry dependencies done in #11393 back to what's in stable-17.0
https://github.com/keymanapp/keyman/blob/d3f41a518aeb900b80500f212023cf782f9bcecc/oem/firstvoices/android/app/build.gradle#L124
https://github.com/keymanapp/keyman/blob/d3f41a518aeb900b80500f212023cf782f9bcecc/oem/firstvoices/android/build.gradle#L10

fix(android): Revert Sentry version for FV Android

---

web/test.sh

I'm not sure how it wasn't caught as part of the test-runner PRs, but the manner in which the verbose-logging flag (`--debug`) was being passed caused it to have a prepended space that had a nasty unintended side-effect breaking runs like this one: https://build.palaso.org/buildConfiguration/Keymanweb_TestPullRequests/465297?buildTab=log&linesState=719&logView=flowAware

fix(web): properly pass test-runner verbose-logging flag

---

developer/src/tike/xml/help/contexthelp.xml

partial fix of: https://github.com/keymanapp/keyman/issues/2131 

chore(developer): add context/key-test 

---

android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java

Fixes #11506
This adds more sanity-checking to `KMKeyboard.updateSelectionRange()`. Will :cherries: pick to stable-17.0
Don't attempt to process selection if 
* text is empty
* selection is past the current text
I can verify these hit the debugger (selMax is 23 when the raw text length is 23). But I can't repro the crashes in the Sentry issue.
* **TEST_INVALID_SELECTIONS** - Verifies app does not crash on invalid selections
2. In the Keyman app, type some text
3. Move the cursor to earlier in the text
4. Move the cursor past the text
5. Verify cursor is at the right of the text

fix(android/engine): Ignore updating invalid selections

---

docs/build/macos.md
docs/build/windows.md

The minimum version for Windows and macOS should be 3.1.46 because that is known to work. See issue #9529 for reasons to avoid 3.1.45. Note: Ubuntu still requires 3.1.44 for now.
Fixes: #11369

docs(common): update min emscripten version in docs to 3.1.46

---

.github/workflows/api-verification.yml
.github/workflows/deb-packaging.yml

The previous attempt where we set a environment variable for the artifacts key resulted in a chicken/egg problem: we needed the environment variable to be able to restore the cached artifacts, but we needed the cached artifacts in order to be able to read the variables...
This change now properly uses run_id: in `deb-packaging.yml` we can directly use `run_id` from the context. In `api-verification.yml` we get it from the payload context.
Cf https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run

fix(linux): Properly use and pass run_id

---

.github/workflows/deb-packaging.yml

Ubuntu 22.04 has meson 0.61; 24.04 has meson 1.3, so updated the sourcepackage step in deb-packaging to 24.04 to meet min reqs.

chore(linux): run deb-package sourcepackage job on Ubuntu 24.04

---

.github/workflows/api-verification.yml

Previously we had an extra job where we setup the environment and restored the artifacts. However, the artifacts then were no longer available in the next job, `api_verification`. Instead of restoring the artifacts a second time this change squashes the two jobs. This will hopefully fix the API verification.

fix(linux): Restore artifacts for API verification in the correct job

---

.github/workflows/api-verification.yml

Set the option for the Checkout step to not  run `git clean` after checkout because that gets rid of the artifacts we previously restored.

fix(linux): Don't clean workdir after checkout in API verification

---

developer/src/server/src/index.ts

Fixes the scenario where the `%AppData%\Keyman\Keyman Developer\Server\bin` folder exists, but ngrok.exe is not in the folder, which caused Keyman Developer Server to crash.
Fixes: #11542
Fixes: KEYMAN-DEVELOPER-1JE

fix(developer): test existence of ngrok.exe before atttempting to start

---

developer/src/server/src/index.ts

Cherry-pick of #11543.
Fixes the scenario where the `%AppData%\Keyman\Keyman Developer\Server\bin` folder exists, but ngrok.exe is not in the folder, which caused Keyman Developer Server to crash.
Fixes: #11542
Fixes: KEYMAN-DEVELOPER-1JE

fix(developer): test existence of ngrok.exe before atttempting to start 🍒 🏠

---

developer/src/kmc-kmn/src/kmw-compiler/javascript-strings.ts
developer/src/kmc-kmn/test/fixtures/kmw/error_not_supported_in_keyman_web_output.kmn
developer/src/kmc-kmn/test/kmw/test-kmw-messages.ts

The `return` statement is unsupported in the web compiler. This is documented, but the problem here was that the `nomatch` and `match` metarules have no corresponding `fkp` structure, so that caused a fatal error in the compiler if these were used in combination, e.g.
nomatch > return
Fixes: #11545
Fixes: KEYMAN-DEVELOPER-1YK

fix(developer): handle unsupported `return` statement in `match` and `nomatch` in web compiler

---

developer/src/kmc-kmn/src/kmw-compiler/javascript-strings.ts
developer/src/kmc-kmn/test/fixtures/kmw/error_not_supported_in_keyman_web_output.kmn
developer/src/kmc-kmn/test/kmw/test-kmw-messages.ts

Cherry-pick of #11546.
The `return` statement is unsupported in the web compiler. This is documented, but the problem here was that the `nomatch` and `match` metarules have no corresponding `fkp` structure, so that caused a fatal error in the compiler if these were used in combination, e.g.
nomatch > return
Fixes: #11545

fix(developer): handle unsupported `return` statement in `match` and `nomatch` in web compiler 🍒 🏠

---

developer/src/tike/project/Keyman.Developer.System.Project.WelcomeRenderer.pas

Cherry-pick of #11552.
This arises if `%AppData%/Keyman/Keyman Developer` folder is missing. It is sporadic because most times, Keyman Developer Server wins a startup race and creates the folder before this code is ever reached.
Fixes: #11551
Fixes: KEYMAN-DEVELOPER-1MY

fix(developer): ensure folder for MRU list is always created 🍒 🏠

---

developer/src/tike/http/Keyman.Developer.System.HttpServer.App.pas
developer/src/tike/main/Keyman.Developer.System.ProjectOwningFile.pas

Also updates the only other place where a project file is loaded like this, in the project renderer, and handles it too (this scenario is less likely to happen because the project file must already have been loaded in order to be presented in the UI).
Fixes: #11557
Fixes: KEYMAN-DEVELOPER-1Z2

fix(developer): handle invalid project file when scanning for owner project

---

developer/src/tike/http/Keyman.Developer.System.HttpServer.App.pas
developer/src/tike/main/Keyman.Developer.System.ProjectOwningFile.pas

Cherry-pick of #11558.
Also updates the only other place where a project file is loaded like this, in the project renderer, and handles it too (this scenario is less likely to happen because the project file must already have been loaded in order to be presented in the UI).
Fixes: #11557
Fixes: KEYMAN-DEVELOPER-1Z2

fix(developer): handle invalid project file when scanning for owner project 🍒 🏠

---

developer/src/tike/project/Keyman.Developer.System.Project.WelcomeRenderer.pas

This arises if `%AppData%/Keyman/Keyman Developer` folder is missing. It is sporadic because most times, Keyman Developer Server wins a startup race and creates the folder before this code is ever reached.
Fixes: #11551
Fixes: KEYMAN-DEVELOPER-1MY

fix(developer): ensure folder for MRU list is always created

---

common/web/utils/src/managedPromise.ts
web/src/engine/dom-utils/src/stylesheets.ts
web/src/engine/osk/src/keyboard-layout/oskLayerGroup.ts
web/src/engine/osk/src/visualKeyboard.ts

Fixes #11467.
This is intended to be merged together with https://github.com/keymanapp/help.keyman.com/pull/1272, which fixes another facet of the same set of issues.
The issue was arising due to cross-origin stylesheet security.  So, a different pattern to detect stylesheet loading is needed.  Upon re-examining of the sources that led to the prior solution... much of it was StackOverflow from about a decade back, oriented toward much older browsers than we have today.  At the time, `<link>` elements didn't consistently support `onload` on all browsers... but that has since been rectified.  It appears that we can do this more simply than I previously thought.
Additionally, this fixes a follow-up issue that occurred once #11467 was fixed.  The way that help.keyman.com loads …

fix(web): correctly handle cross-origin stylesheets when calculating keyboard size and key cap font size

---

common/web/sentry-manager/src/index.ts

fix(web): add null guard for missing debug info when reporting to Sentry

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift

When writing a filename to the log, the fileUrl variable representing the file was miscast causing the app to crash. Removes cast and logs the absoluteString for the fileUrl instead.
Fixes #11567
Fixes KEYMAN-IOS-7A

fix(ios): remove incorrect cast in log statement to prevent crash

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift

Cherry-pick of #11569
When writing a filename to the log, the fileUrl variable representing the file was miscast causing the app to crash. Removes cast and logs the absoluteString for the fileUrl instead.
Fixes #11567
Fixes KEYMAN-IOS-7A

fix(ios): remove incorrect cast in log statement to prevent crash 🍒 🏠 

---

common/web/recorder/src/index.ts

This bugfix was originally part of #11424 and is now being spun off as its own PR.  It appears that previously, keyboard-simulation test failures would not have been reported properly if they occurred.  
The bug being fixed was discovered due to either "noImplicitAny" or "noImplicitThis" being enforced against the sourcefile.
I ended up extracting all changes from that PR, meaning that this PR makes the source file compatible with stricter .tsconfig settings.  I also added extra tweaks while I was at it, largely around type-names to facilitate checks against `'key' | 'osk'` so that TS could better make inferences about related control flow in line with "noImplicitReturns".
As this PR only adjusts unit-test resources, there's no need to bother 🍒-picking this.

fix(web): headless recorder unhandled paths, invalid test-sequence references 🔩

---

web/src/app/webview/src/oskConfiguration.ts
web/src/engine/element-wrappers/src/utils.ts
web/src/engine/osk/src/visualKeyboard.ts

Originally part of #11459, this PR extracts fixes for a couple of bugs found in dead code branches when using enhanced TS strictness settings.  The easy fix:  just remove the code, as requested by https://github.com/keymanapp/keyman/pull/11459#pullrequestreview-2062626843:
> Sounds like there are some dead code removal PRs coming up before too long as well?
In both cases, we were calling functions against `this` that simply didn't exist there.
The deleted `menuEvent` is removed because it becomes an "unused local" according to other TS strictness settings about to be enforced.
As the code paths are dead, we don't _have_ to 🍒-pick this... but again, as they're dead, there's no reason it wouldn't be safe to do so.  (Yay, file-size shrinkage!)

fix(web): remove dead code-branches 🔩

---

common/web/gesture-recognizer/src/tools/unit-test-resources/src/inputSequenceSimulator.ts
web/src/app/browser/src/context/focusAssistant.ts
web/src/app/browser/src/languageMenu.ts
web/tsconfig.base.json

Addresses part of #11473, correcting all remaining cases caught by enforcing `"noImplicitThis" across all Keyman Engine for Web related code.

chore(web): fixes implicit-this cases 🔩

---

common/web/lm-worker/src/main/model-compositor.ts

Originally part of #11424, this potential bug was spotted due to enforcing `"noUnusedLocals"` against the lm-worker codebase.  It's pretty clear that `finalInput` had an intended use... but... simply wasn't used.
It's notable that we haven't (knowingly) had any related bugs in the time it's been like this, so we're probably safer by _not_ 🍒-picking this change at this time.  I believe the change should actually be fine, as it would usually resolve to the same value, but there's little reason to risk it at this time.

fix(web): use intended source for prediction-to-context matching 🔩

---

web/src/engine/osk/src/banner/banner.ts
web/src/engine/osk/src/banner/bannerView.ts
web/src/engine/osk/src/banner/suggestionBanner.ts

While working on #11460, I noticed that unlike most of the other DOM-event interacting OSK components, the predictive-text banner lacked a destructor-style method.  In 17.0, the banner utilizes the new gesture engine.  To be safe, it's wisest to explicitly terminate the engine whenever its corresponding banner is swapped out.  
We're _probably_ fine without it due to garbage collection, but I believe part of the engine's setup can register an event handler outside of the banner hierarchy... which would thus _not_ be GC'd after swap without this change.  It should only ever be a _minor_ memory leak, even then, as we've not gotten any related error reports so far as we can tell.

fix(web): explicitly terminate banner gesture-handling when banner is swapped 🔩

---

web/src/app/ui/kmwuibutton.ts

Originally part of #11462, this fixes a Button-UI bug identified thanks to enforcing "noImplicitAny".  [(Original thread)](https://github.com/keymanapp/keyman/pull/11462#discussion_r1604515263)
As this _is_ a live bug in 17.0, it may be worth 🍒-picking.  It's _probably_ a niche scenario... but still.

fix(web): use correct parameter name in button UI OSK `hide` event 🔩

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Manager.swift

During startup of Keyman running from the system keyboard, do not attempt any migrations or keyboard state updates as keyboard extensions are not allowed to modify shared storage:
[Apple's custom keyboard documentation](https://developer.apple.com/documentation/uikit/keyboards_and_input/creating_a_custom_keyboard/configuring_open_access_for_a_custom_keyboard?language=objc):
> Custom keyboards operate in a sandboxed environment running in an isolated process. This sandbox’s default configuration disallows access to the network and prevents writing to the containing app’s shared group containers (reading is permitted). 
Fixes #11602
Fixes KEYMAN-IOS-7E
Fixes KEYMAN-IOS-7D

fix(ios): do not write to shared storage from system keyboard

---

ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift
ios/engine/KMEI/KeymanEngine/Classes/Manager.swift

Cherry-pick of #11613
During startup of Keyman running from the system keyboard, do not attempt any migrations or keyboard state updates as keyboard extensions are not allowed to modify shared storage:
[Apple's custom keyboard documentation](https://developer.apple.com/documentation/uikit/keyboards_and_input/creating_a_custom_keyboard/configuring_open_access_for_a_custom_keyboard?language=objc):
Custom keyboards operate in a sandboxed environment running in an isolated process. This sandbox’s default configuration disallows access to the network and prevents writing to the containing app’s shared group containers (reading is permitted).
Fixes https://github.com/keymanapp/keyman/issues/11602
Fixes KEYMAN-IOS-7E
Fixes KEYMAN-IOS-7D

fix(ios): do not write to shared storage from system keyboard 🍒 🏠 

---

developer/src/tike/main/KeymanDeveloperOptions.pas
developer/src/tike/main/UfrmMain.pas

If a relative or otherwise invalid path is given for `default project path` in .keymandeveloper/options.json, then this will reset the path to the default of `%Documents%/Keyman Developer/Projects`.
Fixes: #11554
Fixes: KEYMAN-DEVELOPER-1ZB

fix(developer): handle invalid default project path in options

---

developer/src/tike/main/KeymanDeveloperOptions.pas
developer/src/tike/main/UfrmMain.pas

Cherry-pick of #11555.
If a relative or otherwise invalid path is given for `default project path` in .keymandeveloper/options.json, then this will reset the path to the default of `%Documents%/Keyman Developer/Projects`.
Fixes: #11554
Fixes: KEYMAN-DEVELOPER-1ZB

fix(developer): handle invalid default project path in options 🍒 🏠

---

developer/src/tike/xml/layoutbuilder/builder.js

Cherry-pick of #11575.
Key selection was left in a corrupted state in `builder.loadState()`, on first load of the touch layout editor, because the selection was not restored after calling `prepareLayer()`.
This only happens on first load because after first load, the selection will have been saved to the state (which is kept in the backend, associated with the instance of the editor), so pressing F5 to reload the page will not reproduce the issue.
Fixes: #11573
Fixes: KEYMAN-DEVELOPER-1Z8

fix(developer): save touch layout editor selection when loading state 🍒 🏠

---

developer/src/tike/xml/layoutbuilder/layer-controls.js

Fixes: #11574
Fixes: KEYMAN-DEVELOPER-1GC

fix(developer): use correct variable when fixing up flick and multitap in Layer Properties dialog

---

developer/src/tike/xml/layoutbuilder/layer-controls.js

Cherry-pick of #11577.
Fixes: #11574
Fixes: KEYMAN-DEVELOPER-1GC

fix(developer): use correct variable when fixing up flick and multitap in Layer Properties dialog 🍒 🏠

---

developer/src/tike/xml/layoutbuilder/builder.js

There were two problems here:
* An undeclared variable `source`
* The `flick` parameter is an array, not an object, so indexing by direction is invalid
Fixes: #11581
Fixes: KEYMAN-DEVELOPER-1YW

fix(developer): correct the inference of default hint from flicks

---

developer/src/tike/xml/layoutbuilder/builder.js

There were two problems here:
* An undeclared variable `source`
* The `flick` parameter is an array, not an object, so indexing by direction is invalid
Fixes: #11581
Fixes: KEYMAN-DEVELOPER-1YW
Cherry-pick-of: #11582

fix(developer): correct the inference of default hint from flicks 🍒 🏠

---

common/windows/delphi/charmap/UfrmCharacterMapNew.pas

An apparent issue in the Grid control in Delphi is that if the top row is zero pixels high (hiding it), a pan gesture on touchscreen causes an EDivByZero. This patch works around the issue by making the top row 1 pixel high.
Fixes: #11589
Fixes: KEYMAN-DEVELOPER-1C3
Fixes: KEYMAN-WINDOWS-43C

fix(developer): make top row of Character Map 1 pixel to avoid DIV/0 in gestures

---

common/windows/delphi/charmap/UfrmCharacterMapNew.pas

An apparent issue in the Grid control in Delphi is that if the top row is zero pixels high (hiding it), a pan gesture on touchscreen causes an EDivByZero. This patch works around the issue by making the top row 1 pixel high.
Fixes: #11589
Fixes: KEYMAN-DEVELOPER-1C3
Fixes: KEYMAN-WINDOWS-43C
Cherry-pick-of: #11590

fix(developer): make top row of Character Map 1 pixel to avoid DIV/0 in gestures 🍒 🏠

---

developer/src/kmc-kmn/test/test-compiler.ts

Rarely, CI builds have been timing out building the test fixtures, with the default 2,000msec timeout. Increasing to 10,000msec.

chore: increase kmc-kmn build test timeout

---

common/windows/delphi/general/httpuploader.pas

This can be useful for debugging scenarios, where we want to use a local test HTTP server on a different port, e.g. setting `development.urls.api_keyman_com_host` to `localhost:8058`.

chore(windows): support port in THTTPUploader

---

resources/git-hooks/commit-msg
resources/git-hooks/pre-commit
resources/git-hooks/prepare-commit-msg

These changes come out of discussion in the team; we want to make use of git trailers and improve the quality of our commit messages. Starting by adding more hints to the commit suggestions. Includes some minor cleanup of the hooks, and hopefully also improves tests so that they don't interfere with interactions with non-Keyman repos.
Note: the scopes list may need maintenance as the list still includes sub-scopes and 'oem'.

change(common): add extra commit message hints

---

web/src/app/webview/src/contextManager.ts

Fixes: #11504
Cherry-pick-of: #11505

fix(web): pre-init keyboard activation awaits init before proceeding 🍒 🏠

---

common/web/sentry-manager/src/index.ts

Fixes: #11548
Cherry-pick-of: #11579

fix(web): add null guard for missing debug info when reporting to Sentry 🍒 🏠

---

developer/src/kmc-keyboard-info/package.json
developer/src/kmc-keyboard-info/src/font-family.ts
developer/src/kmc-keyboard-info/src/ttfmeta/LICENSE
developer/src/kmc-keyboard-info/src/ttfmeta/README.md
developer/src/kmc-keyboard-info/src/ttfmeta/lib/index.js
developer/src/kmc-keyboard-info/src/ttfmeta/lib/main.js
developer/src/kmc-keyboard-info/src/ttfmeta/lib/meta.js
developer/src/kmc-keyboard-info/src/ttfmeta/test/local.mjs
developer/src/kmc-keyboard-info/src/ttfmeta/test/mocha-index.mjs
developer/src/kmc-keyboard-info/tsconfig.json
package-lock.json

Remove ttfmeta from package.json, and copy only the relevant files into ttfmeta/ under kmc-keyboard-info. This is a stopgap measure as we will probably attempt to identify an alternate library in the future.
See also #11625 which is the driver for making this change now.
Fixes: #11630

fix(developer): bundle ttfmeta library internally with kmc-keyboard-info

---

developer/src/tike/xml/layoutbuilder/builder.js

Key selection was left in a corrupted state in `builder.loadState()`, on first load of the touch layout editor, because the selection was not restored after calling `prepareLayer()`.
This only happens on first load because after first load, the selection will have been saved to the state (which is kept in the backend, associated with the instance of the editor), so pressing F5 to reload the page will not reproduce the issue.
Fixes: #11573
Fixes: KEYMAN-DEVELOPER-1Z8
* **TEST_TOUCH_LAYOUT_EDITOR:** Open the touch layout editor, and perform a variety of standard operations. Verify that they behave as expected. Press F12 to open the Developer Tools, and verify that there are no errors shown in the Console.

fix(developer): save touch layout editor selection when loading state

---

HISTORY.md

Adds entries from `staging-17.0` version 17.0.326 HISTORY.md

chore: Update history from 17.0.326

---

common/web/keyboard-processor/src/keyboards/activeLayout.ts

This is a tweak on a fix originally included within #11424.  As [noted here](https://github.com/keymanapp/keyman/pull/11424/files#r1610884203), there was a pattern in keyboard-layout preprocessing that kept needing `// @ts-ignore` when enforcing stricter TS settings - and particularly `"noImplicitAny"`.  After giving it some thought, I figured a mild DRY-out would make things a bit simpler overall and avoid constant replication of `// @ts-ignore` due to the pattern.

refactor(web): refactor keyboard-layout preprocessing property transplantation 🔩

---

common/web/input-processor/src/correctionLayout.ts
common/web/input-processor/src/text/inputProcessor.ts
common/web/keyboard-processor/src/keyboards/defaultLayouts.ts
common/web/keyboard-processor/src/text/codes.ts
common/web/keyboard-processor/src/text/kbdInterface.ts

Originally part of #11424, these changes address bugs that were uncovered thanks to stricter TS settings.  There are three in total, but they're in the same region of code and are all quite small, so I lumped 'em together.

fix(web): fix keyboard-processing bugs uncovered by stricter TS settings 🔩

---

common/web/gesture-recognizer/src/test/auto/headless/gestures/isolatedPathSpecs.ts
common/web/gesture-recognizer/tsconfig.json
web/package.json
web/src/app/browser/src/contextManager.ts
web/src/app/browser/src/languageMenu.ts
web/src/app/ui/kmwuitoolbar.ts
web/src/engine/dom-utils/src/stylesheets.ts
web/src/engine/main/src/contextManagerBase.ts
web/src/engine/osk/src/input/gestures/specsForLayout.ts
web/src/engine/osk/src/visualKeyboard.ts
web/src/engine/package-cache/src/modelCache.ts
web/src/tools/testing/recorder/browserProctor.ts
web/src/tsconfig.dom.json

For some reason, I expected these final flags to be worse than enforcing `strictFunctionTypes`.  Maybe it's due to some of the changes the previous setting triggered, but this part went quite swimmingly.
Fixes #11473.
TEST_DEVELOPER_KMC:  Using the test build of Keyman Developer, verify that keyboard compilation works properly.
1. In your local copy of the keyboards repo, run `./build.sh clean`.
2. Open Keyman Developer.
3. Open any keyboard project - say, `ekwtamil99uni` (at https://github.com/keymanapp/keyboards/tree/master/release/e/ekwtamil99uni).
4. Use Keyboards > `ekwtamil99uni.kmn` > Build > Compile Keyboard and verify that no errors are emitted.
5. Returning to the .kpj overview, use Packaging > `ekwtamil99uni.kps` > Build > Compile Package and verify that no errors are emitted. …

chore(web): finalize web/ project parity with base-repo TS config settings (aside from JS version target) 🔩
